### ISSUE TITLE
Non-unicode character (i.e. Chinese/Japanese) support?

### ISSUE THREAD

**Issue by ysliew** [dompdf/dompdf#1001]
Doesn't seem to work when dealing with Chinese or Japanese Kanji characters (i.e. 中文，日文）。

**Comment by bsweeney** [comment]
Not with a default installation. You'll have to add a font supporting the characters you want to display. Read the [Unicode How-To](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo) for more information.
