### ISSUE TITLE
Class 'Dompdf\Dompdf' not found

### ISSUE THREAD

**Issue by VerzatileTom** [dompdf/dompdf#1003]
Hi, 
I'm using laravel framework, I added
`require __DIR__.'/../vendor/autoload.php';`
`require_once __DIR__.'/../vendor/dompdf/dompdf/dompdf_config.inc.php';`
on bootstrap autoload.php,
I have `use Dompdf\Dompdf;` above my code..
and I'm testing it with this code

`$dompdf = new Dompdf();`
`$dompdf->loadHtml('hello world');`

and im getting Class 'Dompdf\Dompdf' not found error exception..

any idea on how can i fix this? thanks

**Comment by bsweeney** [comment]
Which version of dompdf are you using? Are you using [barryvdh/laravel-dompdf](https://github.com/barryvdh/laravel-dompdf)? If so have you checked that project for relevant info?

**Comment by VerzatileTom** [comment]
I downloaded your latest version of dompdf via composer. Previously, I am using barryvdh/laravel-dompdf but I want to try a PDF package not dependent for laravel so I remember this package and i am trying this right now.

**Comment by bsweeney** [comment]
Which release did you specify in composer. The latest stable (0.6.1) does not support namespaces and so would not need the `use` statement in your code.

**Comment by bsweeney** [comment]
So ... got it figured out?
