### ISSUE TITLE
Special characters issue with justified alignment

### ISSUE THREAD

**Issue by moonlittran** [dompdf/dompdf#1005]
Hi everyone! I am using Dompdf in Laravel. 
the issue i am facing is special character with justified alignment.

&lt;p style="text-align: justify;"&gt;some text + &amp;rsquo; + more than 1 line of text&lt;/p&gt; -&gt; this does not work on pdf result.

&lt;p&gt;some text + &amp;rsquo; + more than 1 line of text&lt;/p&gt; -&gt; this works fine

4 character i need is &amp;rsquo; &amp;lsquo; &amp;rdquo; &amp;ldquo;

Help me help me, it is killing me.
Thanks everyone.

**Comment by bsweeney** [comment]
What do you mean by "this does not work?" Do you have a screen shot or example online?

There were some alignment issues with special character in 0.5.1 but more recent versions should be fine.

**Comment by bsweeney** [comment]
I *do* see a problem when using this with the DejaVu fonts. The rsquo character isn't even represented properly in the rendered PDF. Same issue?

**Comment by moonlittran** [comment]
Yeah. Aright. But ha fixed it. Thank you followed.

**Comment by bsweeney** [comment]
These characters were being mangled by some string replacement in the CPDF library that was not taking into account the fact that Unicode strings are two bytes long. The issue should be addressed by commits 18b08fdb3e22378e980f79fc45cdd3e0a69a416a and 18b08fdb3e22378e980f79fc45cdd3e0a69a416a.

**Comment by bsweeney** [comment]
Note that while the characters are no longer mangled there does appears to be an issue in the justification alignment. See issue #1168.

**Comment by bsweeney** [comment]
I believe the specific issue identified has been sufficiently addressed.
