### ISSUE TITLE
"Hello World" behind Cloudflare

### ISSUE THREAD

**Issue by ricsmo** [dompdf/dompdf#1012]
I've been using dompdf for a couple of years and it really works well for my project. The code I'm using is pretty much a copy/paste of the "Hello World" example.
Lately I've been experimenting with CDNs, etc. and tried Cloudflare. 

The pdfs are sent using the ->stream method after a URL with a query string is sent (for permissions checking, etc.). It works fine not behind Cloudflare, but the downloads time out behind Cloudflare. I checked with Cloudflare since they cache pdfs, but support said they won't cache if *.pdf isn't in the URL (and it's not here). 

The url looks something like this: https://mydomain.com/?unique_id_1=123&unique_id_2=456&unique_id_3=789

After PHP checks permissions, existence of the records, generates the html, etc I send this:

	$dompdf = new DOMPDF();
	$dompdf->set_base_path(ABSPATH . '/wp-content/plugins/myplugin/');
	$dompdf->load_html($html);
	$dompdf->render();
	$dompdf->stream("document_name.pdf");

I've searched here and on Google and the most I could find was that there might be some issues behind proxies, but I didn't see any solutions.  Is it simply not compatible or is there a workaround I'm not aware of?

**Comment by ricsmo** [comment]
Turns out it's suddenly working now. It was probably a CF issue.

**Comment by bsweeney** [comment]
Thanks for the follow up.

**Comment by ricsmo** [comment]
I discovered more information so I'm sharing. 
I actually have two separate functions that create two different PDF files. I closed the ticket above when one was working because I knew it was something with the code and not with CloudFlare or dompdf.

I started comparing the code and found that the one that was working had an exit(); statement shortly after the dompdf->stream() method. This was here for another reason (it was from a code sample that was serving a different purpose in the same function), but it was the only significant difference after the ->stream();. So I added an exit(); to the function that was timing out at things like 910k/851k downloaded and it works now too. It worked fine without CloudFlare, but now it works in both places.

So, at least in this case, and if behind CloudFlare, stopping PHP and anything WordPress wants to do with an exit(); after sending the stream is helpful.

**Comment by bsweeney** [comment]
Hm. That is interesting. There have been occasional reports about a dompdf-generated PDF never fully sending. I'll be sure to suggest calling `exit()` in the future to see if it helps.

This may bear more investigation.

**Comment by ricsmo** [comment]
I've also been working with CloudFlare support. Here was their response to using exit();

>That would make sense - if you don't call exit() the server will not close the connection, so a typical HTTP proxy like CloudFlare will not know when the response is complete. Without that indicator a timeout will occur.
