### ISSUE TITLE
Special character (only one) breaks <span> alignment

### ISSUE THREAD

**Issue by sQu1rr** [dompdf/dompdf#1014]
Only one special character causes the issue: "«". It causes span (and maybe any other element, i haven't tried any) to offset a bit to the left.

Full Testing Code

``` php
require 'vendor/autoload.php';

define('DOMPDF_ENABLE_AUTOLOAD', false);

require_once 'vendor/dompdf/dompdf/dompdf_config.inc.php';

$special = [
    '…', '‘', '’', '“', '”', '‚', '„', '′', '″', '‐', '–', '—', ' ', ' ', ' ',
    '¦', '•', '‣', 'ˆ', '¨', '˜', '‹', '›', '«', '»', '‾', '¿', '¡', 'œ',
    '&hellip;', '&lsquo;', '&rsquo;', '&ldquo;', '&rdquo;', '&sbquo;',
    '&bdquo;', '&prime;', '&Prime;', '&#8208;', '&ndash;', '&mdash', '&ensp;',
    '&emsp;', '&thinsp;', '&brvbar;', '&bull;', '&#8227;', '&circ;', '&uml;',
    '&tilde;', '&lsaquo;', '&rsaquo;', '&laquo;', '&raquo;', '&oline;',
    '&iquest;', '&iexcl;', '&oelig;'
];

$pdfText = '';
foreach ($special as $char) {
    if ($char != '«' && $char != '&laquo') continue; // comment to show others
    $pdfText .= "$char Fine<br>$char <span>Not Fine</span><br>";
    $pdfText .= "$char Fine <span>Not Fine, wtf?</span><br>";
}


$dompdf = new DOMPDF();
$dompdf->load_html($pdfText);
$dompdf->render();

$dompdf->stream("example.pdf");
```

I enclose screenshot of the generated PDF. Given that all the other chars are displayed correctly it should be just a typo/missing char, I'm guessing?

The weirdest thing is the 3rd line - only span is offset, not the text before it

``` html
« Fine <span>Not Fine, wtf?</span><br>
```

![main_002](https://cloud.githubusercontent.com/assets/3148267/9762907/2c4a9b82-570f-11e5-9c00-04aa1a817dd4.png)

**Comment by bsweeney** [comment]
Interesting. Looks to possibly be an issue with the font metrics, though I'm not sure why it only happens when a span is present. I tried it with DejaVu Sans and there was no issue, do you see the same?

**Comment by sQu1rr** [comment]
Yes, DejaVu Sans is Good. Possible workaround thank you. Would be nice to get the issue fixed though if its possible for generic sans-serif.

**Comment by bsweeney** [comment]
We will definitely take a look (at some point).
