### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by J1Duran** [dompdf/dompdf#1015]
I have the following error:
 Maximum execution time of 60 seconds exceeded in /var/www/html/.../vendor/dompdf/dompdf/include/frame.cls.php on line 395
Segmentation fault.
Any idea why this error?

**Comment by bsweeney** [comment]
Maybe related to issue #98? Do you have a sample of the HTML?

**Comment by J1Duran** [comment]
I export from a xls(Maatwebsite/Laravel-Excel).
Only it happens when my table is large, my table is approximately 1200 records

**Comment by bsweeney** [comment]
Could just be taking a long time to render the document. Table handling in dompdf is a bit janky ... can you try increasing the PHP max_execution_time?

**Comment by J1Duran** [comment]
No man, I will try this

**Comment by kanapes** [comment]
Hi,
just take a look at issue #992 - maybe it helps a bit.
Like #bsweeney said take care of your server/php configuration.

And that is for sure - large tables are very tricky ...

Maybe you try it first without any CSS declaration. Sometimes special CSS-definitions won't work within tables and dompdf. 

It is a try and maybe you will come a bit closer to solving your problem ... =) 
Another guess is to start the process directly on the server ... this will speed it up a little bit ... 

@bsweeney 
Maybe you can push this issue to the top of your list as this seems to be something that many people have problems with.

**Comment by J1Duran** [comment]
Thank you man.
