### ISSUE TITLE
White space in data-uri breaks image rendering

### ISSUE THREAD

**Issue by joanebrown** [dompdf/dompdf#1016]
How to use a data uri scheme image with dompdf?

I tried to use it directly and I see the image, but only when I see the html page directly:

```
<img width="200" height="50" src="<?php echo 'data:image/jpeg;base64,' . base64_encode($image->mydatauri); ?>"/>
```

but it returns the next error, when I create the PDF:

> Image type unknown

What's the problem? I already set `DOMPDF_ENABLE_REMOTE` to true.

Thanks :)

**Comment by bsweeney** [comment]
Which version of dompdf? You must be using at least 0.6.0.

**Comment by joanebrown** [comment]
Hi,

I use this version. (`DOMPDF 0.6.0 beta 3 release notes`). Is the version that uses thujohn (https://github.com/thujohn/pdf-l4/blob/master/src/Thujohn/Pdf/dompdf/readme.html)

Please, if you can help me with that I would be grateful

**Comment by bsweeney** [comment]
That version should work as well, though if you want you can try the newer release (0.6.1), it should be drop-in compatible.

Do you have a sample online that we can look at?

**Comment by joanebrown** [comment]
Hi bsweeney,

It's weird... May you can try my data URI in your dompdf? Pease... Maybe the error is in my data URI (I don't know) It's a localhost server :(

My data URI: http://jsfiddle.net/eo11L48s/

I see the image, a smile, in the browser, but I get:

`Image type unknown
data:image/jpeg;base64,LzlqLzRBQVFTa1pKUmd ...etc...`

in DOMPDF...

Please, if you can help me I would be very grateful

**Comment by joanebrown** [comment]
Oh, i see...

May you have a little solution for that? I tried with the next `preg_replace` to remove all break spaces:

`<img width="200" height="50" src="<?php echo 'data:image/jpeg;base64,' . preg_replace('~\x{00a0}~', '', base64_encode($image->mydatauri)); ?>"/>`

But doesn't work :S

**Comment by bsweeney** [comment]
I had actually written a rather detailed response, but I must have forgotten to actually submit it :(

So the problem does appear to be the line breaks in the base64-encoded data. I tried your sample from jsfiddle after removing white space and the smiley face rendered just fine. Most base64 decoders ignore white space, so I'm not sure what's going on here. There could be something happening when dompdf processes the document, but we'll have to look into it a bit more before we can say for sure.

I wasn't able to find a way to tell PHP not to include white space in encoded data so you might try removing line breaks:

```
<img width="200" height="50" src="<?php echo 'data:image/jpeg;base64,' . preg_replace('[\r\n]', '', base64_encode($image->mydatauri)); ?>"/>
```

or maybe just remove any non-word characters

```
<img width="200" height="50" src="<?php echo 'data:image/jpeg;base64,' . preg_replace('\W', '', base64_encode($image->mydatauri)); ?>"/>
```

**Comment by joanebrown** [comment]
Well, I tried this two solutions, but doesn't work... I'm desperate :S 

I tried other solutions, but doesn't work too...

**Comment by bsweeney** [comment]
Sorry ... my preg_replace usage was wrong (I didn't actually test). I updated the previous comment with valid code. Also, here's something more specific to base64:

```
<img width="200" height="50" src="<?php echo 'data:image/jpeg;base64,' . preg_replace('/[^\+\/\=A-Za-z0-9]/', '', base64_encode($image->mydatauri)); ?>"/>
```

**Comment by joanebrown** [comment]
Hi bsweeney and thanks, I hate to be heavy, but neither works... :(

![Image of error](http://s27.postimg.org/h6b9gnfzn/Sin_t_tulo.png)

**Comment by bsweeney** [comment]
Looks like the line breaks were removed at least. Can you share the actual HTML that you're feeding to dompdf?

**Comment by joanebrown** [comment]
I only have the image in my HTML:

`<img width="200" height="50" src="<?php echo 'data:image/jpeg;base64,' . preg_replace('/[^\+\/\=A-Za-z0-9]/', '', base64_encode($image->mydatauri)); ?>"/>`

Is weird... I will try to attach here an image or a pastebin with my code.

**Comment by bsweeney** [comment]
It'll help to see the actual HTML fed into dompdf (I guess preferably in pastebin since it'll include an encoded image). That way I can look to see if there's anything else in there making it difficult to parse.

**Comment by joanebrown** [comment]
This is the pastebin:

http://pastebin.com/ULknVdnV

Due to limited pastebin I have put a "etc" in the data URI. I used the next data URI: http://jsfiddle.net/eo11L48s/1/

Thanks for all your attention, I hope that helps :)

**Comment by bsweeney** [comment]
You certainly don't need the base64_encode for the first image since the image is already encoded. Try using the following (make sure no extra line breaks or white space is present inside the quotes as well):

```
<img width="150px" src="<?php echo 'data:image/jpeg;base64,' . preg_replace('/[^\+\/\=A-Za-z0-9]/', '', "/9j/4AAQSkZJRgABAQAAAQABAAD/2w [...etc...]"); ?>"/>
```

The second statement looks fine, so I dunno why it's failing. You might try generating the entire image tag inside the PHP code:

```
<?php echo '<img width="200" height="50" src="data:image/jpeg;base64,' , preg_replace('/[^\+\/\=A-Za-z0-9]/', '', base64_encode(Images::find(1)->mydatauri)) , '"/>'
```

It would still help to see what dompdf is actually parsing. Can you post what's returned by `$dompdf->output_html()`? Call that method after calling `$dompdf->load_html()`.
