### ISSUE TITLE
Table cell width is not honored if content exceeds the specified dimensions

### ISSUE THREAD

**Issue by jackyshek** [dompdf/dompdf#1017]
The Dompdf has a bug that it does not base on the div css to scale size which the div has over the page size. I have tried the table which the css not work for it. 

http://stackoverflow.com/questions/32556734/dompdf-bug-of-div-which-is-not-follow-the-css

**Comment by bsweeney** [comment]
I believe it's actually more of a table processing issue. From my comment on your SO answer:

> dompdf has some layout issues with tables that prevents it from limiting width when the contents are larger than the cell size... Just be sure to specify a width on the container and style with word-wrap: break-word;

This particular issue occurs even if the table has a specified dimension with overflow hidden or word-break enabled.
