### ISSUE TITLE
Call to undefined method DOMProcessingInstruction::getAttribute()

### ISSUE THREAD

**Issue by armorking5** [dompdf/dompdf#1018]
<table>
  <thead>
    <tr>
    <th>Titolo</th>
    <th>Autore</th>
    <th>Genere</th>
    <th>Editore</th>
    <th>Trama</th>
    <th>Data di Edizione</th>
    </tr>
  </thead>
  <tbody>
<tbody>
            <tr>
<td>jrtjrtjrt</td>
<td>jrtjrtjrtjrt</td>
<td>Romanzo</td>
<td>Piemme</td>
<td>Nessuna breve descrizione</td>
<td>03/09/2015</td>
</tr>
<tr>
<td>jrrjrj</td>
<td>jrrjjrrj</td>
<td>Giallo</td>
<td>De Agostini</td>
<td>Nessuna breve descrizione</td>
<td>01/09/2015</td>
</tr>
<tr>
<td>yjrtjr</td>
<td>jrtjrtjrt</td>
<td>Fantascienza</td>
<td>Mondadori</td>
<td>Nessuna breve descrizione</td>
<td>03/09/2015</td>
</tr>
<tr>
<td>hmghhg</td>
<td>fghgh</td>
<td>Horror</td>
<td>Cairo</td>
<td>fgfggh
</td>
<td>03/09/2015</td>
</tr>
<tr>
<td>sssdfsc</td>
<td>bgngmgh</td>
<td>Horror</td>
<td>Mondadori</td>
<td>dggdfgd</td>
<td>05/09/2015</td>
</tr>
<tr>
<td>fffff</td>
<td>fffffff</td>
<td>Saggio</td>
<td>Adelphi</td>
<td>Nessuna breve descrizione</td>
<td>11/09/2015</td>
</tr>
<tr>
<td>sdfdfsdfs</td>
<td>sdsdfsdfsdf</td>
<td>Saggio</td>
<td>Mondadori</td>
<td>dfsdfssd</td>
<td>06/09/2015</td>
</tr>
  </tbody>

</table>

code here : http://pastebin.com/9k2zd8sm
This table doesn't convert with get commands.
I'm using Stable version of dompdf

**Comment by bsweeney** [comment]
Stable meaning 0.6.1? I didn't have any issues parsing that table but this issue has been brought up before in issue #454. Do you have inline scripting enabled?

**Comment by armorking5** [comment]
Yes 0.6.1, and inline scripting I assume is enabling PHP or there is another flag? I'm Italian so sorry for every error I make

**Comment by bsweeney** [comment]
Inline scripting is enabled using the DOMPDF_ENABLE_PHP setting and allows dompdf to parse PHP code in blocks similar to the following:

```
<script type="text/php">
...
</script>
```

If you don't need I'd disable it and see if that helps.

Is it just that table causing issues (i.e. if you take it out does the error go away)? Do you have any inline script in your document? If there's more to your document it might help to see the full thing (HTML and CSS).

**Comment by armorking5** [comment]
For testing on this page I have no css and the table is populated with PHP so I can't set inline scripting to false.
If I include dompdf class on another page and use only the first page's html, it can work?

**Comment by bsweeney** [comment]
Do you have a sample of the code you're using to generate the PDF (not the table) that causes the problem vs. not?

Since you're not actually using inline script you can still get the desired result without enabling script support in dompdf. Something like the following would work:

```
ob_start();
include('table_generating_script.php');
$html = ob_get_clean();

$dompdf = new DOMPDF();
$dompdf->load_html($html);
$dompdf->render();
$dompdf->stream('table.pdf');
```

FYI, the next release of dompdf will not support pre-processing PHP code in the document. If you update when it comes out (and you should) you'll have to change how you do things.

**Comment by armorking5** [comment]
Using the code you posted, It functions perfectly!!
It isn't "css perfect" but I know where the problem is
Thanks!

**Comment by armorking5** [comment]
A question:
Are CSS spreadsheets supported?

**Comment by bsweeney** [comment]
Since this still appears to be a problem (with 0.6.x) I'd like to keep this issue open. For now anyway. If this is just DOMDocument trying to parse the actual PHP then I'll probably close it again.

**Comment by bsweeney** [comment]
As far as CSS spreadsheets are concerned, do you have an example?

**Comment by armorking5** [comment]
I use bootstrap and datatables for css

**Comment by bsweeney** [comment]
There are some issues with Bootstrap (see in particular issue #758 and #860). I'm going to hazard a guess that it's probably not going to work out like you want, but if you have a link to a sample online I can run a test render.

**Comment by armorking5** [comment]
https://www.datatables.net/manual/styling/bootstrap-simple.html this page is exactly what the same gas, I also put some buttons but overall is the same

**Comment by bsweeney** [comment]
JavaScript isn't supported at all, so a lot of what you see on that page wouldn't work. If possible you would want to perform some basic formatting before using DataTables (e.g. apply the Bootstrap classes yourself).

I was able to render the table with some basic formatting that way, though there are some odd formatting issues. But for some reason when I attempt to fetch that page from datatables.net it fails.
