### ISSUE TITLE
[DOC] Easy install with git not precise

### ISSUE THREAD

**Issue by tortueGniale** [dompdf/dompdf#1019]
This doc says to run three commands : 

git clone https://github.com/dompdf/dompdf.git
git submodule init
git submodule update

But actually we need to cd into the cloned repo before running the two other commands. If not familiar with theses two commands, you can fail the installation since no error is thrown when just running the commands as said in the docs.

**Comment by bsweeney** [comment]
Fixed by 4c7dca690edc85168cff0abe9d1d9aaf4ebb72ce

FYI, the [next release](https://github.com/dompdf/dompdf/tree/develop) doesn't use submodules and so that part won't be pertinent anymore.
