### ISSUE TITLE
Font issue?

### ISSUE THREAD

**Issue by tormjens** [dompdf/dompdf#1022]
When creating a PDF where we're using a custom font, we're experiencing some issues with character encoding. 

The PDFs work when I display them, but when they get imported through some third party service (in our case our client's CRM like Visma and so on) they get all scrambled up.

We kind of like this font, so hope there is some way we can keep it.

I've attached an image which shows the issue.

Anybody else experience this issue and can lead me in the direction as to what I'm doing wrong?

about:blank
![document-12096](https://cloud.githubusercontent.com/assets/3974889/10050339/1b4847a4-621c-11e5-86ea-1b32f83dd10e.jpg)

**Comment by bsweeney** [comment]
I don't know if the problem is the font or the way its embedded in the document. Do you know if other PDFs with embedded fonts display as expected? Are you using font subsetting? You might want to try turning off subsetting to see if that helps.

**Comment by tormjens** [comment]
I was not using font subsetting, so that was not the issue. I was, however, using an .otf font. I saw in some other issue that this was not popular with dompdf? I changed it to .ttf now, and will check if this solves the issue.

**Comment by bsweeney** [comment]
Font embedding has pretty much been developed around the TTF format. OTF is a fairly similar format, but I can't say right now if it works as well. Part of that depends on what level of support is provided in php-font-lib, but also I don't know that OTF is supported in PDF1.3 which is the spec we use for development.

Similar issues have cropped up in the past relating to fonts (see #512). If you can somehow validate the format in relation to your service we can try and address any issues.

**Comment by wreardan** [comment]
I'm having a very similar issue when trying to add the Lato font family.

Input File: https://www.dropbox.com/s/u2mm7rgzo55zz94/newreport.html?dl=0
Output PDF: https://www.dropbox.com/s/s8xnfgemrmqy8lw/newreport-dom.pdf?dl=0

I can't figure this out for the life of me: any help would be appreciated.

**Comment by bsweeney** [comment]
@wreardan I'm not sure if this is the same issue since you're doesn't appear to display correctly at all. Though perhaps it's related. What version of dompdf? Are you subsetting the font? I rendered your document without issue so it could be something local (a library, or corruption in the dompdf files).

**Comment by wreardan** [comment]
I was using a nightly build.  However I just tried 0.7.0 alpha 2 and that didn't seem to work either.  I think that html actually refers to a server-side css document that I just changed to remove the font style for testing.  Can you retry it now?

Just noticed that it looks empty except if opened in Firefox then it looks similar to tormjen's screenshot.

**Comment by bsweeney** [comment]
I modified the document prior to rendering to add that styling back when I noticed it was missing. But here's a fresh render: [0.6.1](http://eclecticgeek.com/dompdf/debug.php?identifier=98edfb5d1c51b430cefdf986eb408193) & [nightly](http://eclecticgeek.com/dompdf/debug.php?identifier=ccc9f9b0b7e30a3674b8035a90684131)

**Comment by bsweeney** [comment]
Are you grabbing a packaged version of the library? I don't usually do a lot of testing with the packaged version on different platforms, but maybe I'll take a look to make sure there's nothing wrong with it. What OS are you running?

If you are using a packaged version would you be willing to give a try using composer?

**Comment by wreardan** [comment]
Yep that looks perfect!  I've been using the nightlies available on this page: http://eclecticgeek.com/dompdf-info/ and just tried the GitHub release 0.7 alpha 2.
We are using FreeBSD 8.2 and Ubuntu 12.04 and it doesn't seem to work on either configuration.
I'm not terribly familiar with composer but definitely willing to give it a try!

Am I calling dompdf incorrectly?
```
	$dompdf = new Dompdf();
	$dompdf->loadHtml($html);
	$dompdf->render();
	$pdf = $dompdf->output();
	$dompdf->stream("report.pdf", array("Attachment" => 0));
```
Also which renderer are you using?  CPDF or PDFLib?  We could have an old version of pdflib on the servers.  
Thanks for the help: it's really appreciated!

**Comment by bsweeney** [comment]
I'm using cpdf. It's been a while since I did anything with pdflib. That's something I'll need to rectify in the future since I believe it still has a decent user base with dompdf.

Your usage looks fine, but try removing the output before stream just to see if that changes things.

**Comment by wreardan** [comment]
Taking out the output totally fix the issue.  Thanks a lot!!

**Comment by bsweeney** [comment]
Really? Did you figure out which backend you're using? We may need to modify those methods so that calling one doesn't interfere with the other.

**Comment by wreardan** [comment]
I couldn't figure out which backend was being used - is there an easy way to do this?  This also seemed to fix an issue where I couldn't get the footer working for me - it's now working nicely!

**Comment by bsweeney** [comment]
The default in newer versions of dompdf should be CPDF.

As of 0.7.0 you can retrieve the current setting:

```
$dompdf->get_option('pdfBackend');
```

For earlier versions you can check the value of the `DOMPDF_PDF_BACKEND` configuration constant in either dompdf_config.inc.php or dompdf_config.custom.inc.php.
