### ISSUE TITLE
Bootstrap, link stylesheet and inline style or on page level style not working

### ISSUE THREAD

**Issue by jimilsumra** [dompdf/dompdf#1023]
Hi 
Please help or at least let me know what is not possible with dompdf. Secondly, if I define any style to my html page where it's taking out for print the content on pdf so on that page if I apply any style on page level it's not applied to the print html report:(

In short:
1. table is wider than goes off the print report ...

2. if apply any inline css to table like color then it should be on print report.....

3. if apply external stylesheet then need to work....as not working so what settings required please let me know step wise.

4. dompdf have any support to bootstrap layout and stylesheets....main need to resolve

http://stackoverflow.com/questions/32750777/dompdf-related-issues-style-link-table-goes-out-and-related-issues

Please refer my two issue

**Comment by bsweeney** [comment]
resolved (?) http://stackoverflow.com/q/32750777/264628

**Comment by joshuatomasgarcia** [comment]
Just in case anyone else has this problem, just make the page size bigger. I set my page size to A2.
