### ISSUE TITLE
Error en variable de Cpdf.php 

### ISSUE THREAD

**Issue by javiauso** [dompdf/dompdf#1029]
En Cpdf.php en la versión de desarrollo, el método stream en la línea 3.508 tiene una variable llamada $filename que en realidad debería llamarse $fileName

**Comment by bsweeney** [comment]
This issue should be addressed by commit be53f5825fba90758f3856e3dbd6efc984c21353
([translate](https://translate.google.com/#en/es/This%20issue%20should%20be%20addressed%20in%20be53f5825fba90758f3856e3dbd6efc984c21353))
