### ISSUE TITLE
Dompdf checkbox

### ISSUE THREAD

**Issue by A-Lim** [dompdf/dompdf#1031]
There's an issue with DOMpdf checkbox. It keeps on skipping to the next line after the checkbox.
![capture](https://cloud.githubusercontent.com/assets/14160760/10172355/75350fb4-6711-11e5-83e7-920c0093745d.PNG)

Is there anyway that I can make it to become like this? ☐ Hello

**Comment by bsweeney** [comment]
Looks to actually be a problem with elements styled as `display: inline-block;`. Work around for your particular issue would be to style checkbox elements as inline instead of inline-block.

```css
input[type=checkbox] { display: inline; }
```

**Comment by bsweeney** [comment]
I think auto-width issues causing your problem will be addressed as part of #627.

**Comment by AlexiusLim** [comment]
It works. Thanks a lot.

**Comment by priya3192** [comment]
input[type=checkbox] { display: inline; }
This not working in dompdf

**Comment by bsweeney** [comment]
@priya3192 checkboxes are supported in the latest release of dompdf. Which version are you using?

**Comment by priya3192** [comment]
It works. Thanks a lot.
