### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by kanapes** [dompdf/dompdf#1032]
Hi folks,
don't know if i'am right here ... 
just one question ...

What about DOMPDF and PHP7?

Does it work together ...? Any experience?

**Comment by bsweeney** [comment]
I do not believe the current stable version (0.6.1) is compatible with PHP 7, we haven't really tested it. The next release should [run fine](https://travis-ci.org/dompdf/dompdf). Also, there are some efforts in the community to actively improve PHP 7 support (e.g. #1030).
