### ISSUE TITLE
spacings are uneven

### ISSUE THREAD

**Issue by mfeske** [dompdf/dompdf#1040]
When using the beta version I made a mistake is noticed. When I used the font Lato's all correct. When using Frutiger partly the line spacings are uneven.

**Comment by bsweeney** [comment]
Can you post a screen grab of the resulting PDF? Could be a problem with the font metrics. Or maybe something in the HTML is pushing the lines around.

**Comment by mfeske** [comment]
Hello bsweeney,
in Attachment the Screenshot from the Problem. Problem is between Berlin and Germany and between Seite and Kundennummer.

![dompdf_problem](https://cloud.githubusercontent.com/assets/4072127/10507614/019871c8-7322-11e5-93b7-e9d974e24740.png)

**Comment by bsweeney** [comment]
Definitely something off in that spacing. Looks to be some kind of last-line problem. Can you post the relevant HTML/CSS so we can debug the issue?

**Comment by mfeske** [comment]
<?
$empfaenger = nl2br($empfaenger);
.
.
.
$html =
"<html>".
"<head>";
if (($art =="option1")||($art =="option2")||($art =="option3")||($art =="option5")) {$html .=
"<link rel='stylesheet' type='text/css' href='css/vrmd_brief.css'/>";
}
if ($art =="option4") {$html .=
"<link rel='stylesheet' type='text/css' href='css/vrmd_einschreiben.css'/>";
}
$html .=
"</head>".
"<body>";
if (($art =="option1")||($art =="option2")||($art =="option4")) {$html .=
"<logo1><img src='img/logo_old.svg' alt='' width='220px'></logo1>";
}
$html .=
"<div id='box0'>$absender</div>";
if (($art =="option2")||($art =="option3")) {$html .=
"<div id='box1'>$zusatz</div>";
}
$html .=
"<div id='box2'>$empfaenger</div>";
if (($art =="option1")||($art =="option2")||($art =="option3")||($art =="option4")) {$html .=
"<div id='box3'>Datum:<br>Seite:<br>Kundennummer:</div>".
"<div id='box3a'>$datum<br>1 von 1<br>$kdnr</div>";
}
if ($art =="option5") {$html .=
"<date>$datum</date>";
}
in css:
#box2 {
 font-size: 12px;
 background-color: white;
 position: absolute;
 top: 52.7mm;
 left: 20mm;
 width: 85mm;
 height: 27.3mm;
 border: 0px solid black;
}
#box3 {
 font-size: 12px;
 background-color:#F6F6F6;
 position: absolute;
/* für DIN 5008 Form B
 top: 50mm;
*/
 top: 45mm;
 right: 20mm; 
 width: 55mm;
 height: 15mm;
 border: 1px solid darkgrey;
 -moz-border-radius: 5px;
 -webkit-border-radius: 5px;
 border-radius: 5px;
 padding: 5mm;
}
#box3a {
 font-size: 12px;
 position: absolute;
/* für DIN 5008 Form B
 top: 50mm;
*/
 top: 45mm;
 right: 20mm;
 width: 27.5mm;
 height: 15mm;
 padding: 5mm;
}

**Comment by Mellthas** [comment]
This might also be addressed by #2568.

**Comment by bsweeney** [comment]
agreed, though not really enough info to fully confirm so I'm going to go ahead and close
