### ISSUE TITLE
underline the line is not quite below

### ISSUE THREAD

**Issue by mfeske** [dompdf/dompdf#1041]
When using the beta version I made a mistake is noticed. When using underline the line is not quite below the font and intersects this part on.

**Comment by bsweeney** [comment]
Similar problems have been reported in the past (#454, #609, #846). You might try the advice from #846:

> if you modify the font metrics file (UFM) you can tweak the underline position by changing the value of `UnderlinePosition`.

**Comment by mfeske** [comment]
but in f45.ttf and Lato-Regular.ttf theire is no UnderlinePosition

**Comment by bsweeney** [comment]
Would need additional info, but I believe this will be fixed in an upcoming release. Closing as a duplicate of #609. Please follow that issue for updates.
