### ISSUE TITLE
how to use this

### ISSUE THREAD

**Issue by nostalgicdodo** [dompdf/dompdf#1044]
I want to use this but I have no clue as to how to use this lib.
What file to require? What function to use? Where is the HTML fed to?
I can't figure this out.
Could you post an code snippet showing how this is used?
Thanks.

**Comment by bsweeney** [comment]
First place to look for help is the [README.MD](https://github.com/dompdf/dompdf/blob/master/README.md). After that check out the wiki, particularly the [requirements](https://github.com/dompdf/dompdf/wiki/Requirements) and [usage](https://github.com/dompdf/dompdf/wiki/Usage) pages.

If you need help beyond that head on over to the [support forum](http://groups.google.com/group/dompdf).

**Comment by nostalgicdodo** [comment]
Thank you very much! I managed to get it to work.
