### ISSUE TITLE
Custom fonts not embedding/not appearing on file

### ISSUE THREAD

**Issue by iamraffe** [dompdf/dompdf#1046]
I am trying to create a PDF that utilizes custom fonts and a specific design. I am loading a view and streaming a PDF.

If you check this link:
http://iamraffe.com/
You can see the HTML View that is being loaded

And here:
http://iamraffe.com/create
The PDF being created.

While it looks perfect on the Chrome browser, once I download the PDF or try to print it out errors start to appear.

If I save the file locally the fonts dissappear, they are not being embedded/outlined.

If I print I get this error:

"PCL XL Error
SubSystem: CONTROL
Error: IllegalOperatorSequence
Operator: SetLineDash
Poisition: 20"
"Can't build /UCS.Unicode /CIDDecoding resource. See gs_ciddc.ps. Warning: fal"

Any suggestions/ideas?

**Comment by bsweeney** [comment]
Firefox doesn't appear to like it either, though it displays fine in OSX Preview. I didn't immediately see anything wrong in looking at the PDF source, but unless there was a glaring issue I would have to do more investigation.

Which version of dompdf are you running? You might try the 0.7.0 beta, which does include some structural fixes to the PDF.

Finally, when I attempted to render the web page it appeared that dompdf was trying to parse the WOFF fonts, which aren't really supported. You might try simplifying your CSS for dompdf to only reference the truetype fonts.

**Comment by raffe90** [comment]
I am only referencing .ttf and the issue still persists. Any ideas?

**Comment by bsweeney** [comment]
Can you post the PDF so I can run it through a validator? Also, version of dompdf?
