### ISSUE TITLE
Random graphic rendering error

### ISSUE THREAD

**Issue by aolszak** [dompdf/dompdf#1047]
Yesterday I had an error during pdf rendering. PDF was damaged and sent in that form to the customer. I need to investigate what could happened. I can't recreate that behavior. Looks like rare random bug. I've attached a partial preview file - background should be white and top graphic should not be damaged.

Waiting for some help.

![screen shot 2015-10-23 at 11 04 41](https://cloud.githubusercontent.com/assets/4125806/10688748/c4da72da-7976-11e5-8610-f4b171fa0a80.png)

**Comment by bsweeney** [comment]
Do you have IMagick or GMagick enabled? It could also depend on the version of GD installed on your system. If you can't recreate the issue then it will be a bit difficult to track down. Is the customer able to re-generate the PDF, and if so do they get the same corrupt output?

**Comment by bsweeney** [comment]
More than likely an IMagick issue that we hope is addressed with the next release. Closing due to lack of follow-up.
