### ISSUE TITLE
Minus sign displayed as question mark (?)

### ISSUE THREAD

**Issue by jandreasn** [dompdf/dompdf#1049]
Dompdf displays negative numbers' minus signs "−" (U+2212, &#8722;) replaced by question marks.

(develop-branch)

**Comment by bsweeney** [comment]
The core fonts (Arial, Times, Courier) only supports characters that can be encoded in Windows ANSI. In order to display a wider range of characters use one of the bundled DejaVu fonts, which have decent non-CJK unicode support.

Something like the following should work:

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <style>
    * { font-family: DejaVu Sans, sans-serif; }
  </style>
</head>
<body>
  <p>−</p>
</body>
</html>
```

**Comment by jandreasn** [comment]
Ah. I see. Sorry I missed that. A bit weird that a proper minus sign is not an ANSI character. Using DejaVu worked great though. Thanks!
