### ISSUE TITLE
dompdf custom fonts adobe reader

### ISSUE THREAD

**Issue by thulke** [dompdf/dompdf#1050]
if I open the pdf in browser - after downloading it or saving it to the server (with file_put_contents() or fwrite()) - all custom fonts look ok, like in direkt stream().

but if I open it in local adobe reader spacing between characters is messed up and adobe reader throws erro messages.

does someone have an idea why that's happening?

thanks in advance!

my code:

![code](https://cloud.githubusercontent.com/assets/15358180/10785456/94c0de44-7d64-11e5-8d80-fd9f08e4dda4.jpg)

pdf sreen shots see as attachment:

![reader](https://cloud.githubusercontent.com/assets/15358180/10785331/b38c39b4-7d63-11e5-8b04-966e3dc69523.jpg)
![browser](https://cloud.githubusercontent.com/assets/15358180/10785330/b38aca3e-7d63-11e5-966e-4ee04fb15f07.jpg)

**Comment by thulke** [comment]
problem solved. was just an font issue.

**Comment by bsweeney** [comment]
Thanks for the update. If you have any helpful details feel free to post for the benefit of others.

**Comment by thulke** [comment]
unfortunately its not solved yet. it is a font issue, but within dompdf. if I clear font cache I at least can use the download of the stream from the browser (but not the result  file_put_contents() from the server). after clearing the cache the file at the server does not render the characters at all ...

**Comment by bsweeney** [comment]
Are you using both `$dompdf->output()` and `$dompdf->stream()` at the same time? Right now this isn't something you can do and the most obvious result are font issues.

**Comment by thulke** [comment]
thank you very much indeed! that solved the problem, simply file_put_contents() without $dompdf->stream() (shame on me, I thought I had already tried this)
best regards, xoph
