### ISSUE TITLE
HTML Table generates "Division by zero"

### ISSUE THREAD

**Issue by Xeno22** [dompdf/dompdf#1057]
The following code produces a "Division by zero" with dompdf:
PHP Warning:  Division by zero in dompdf/include/table_frame_reflower.cls.php on line 162

This is the generated output of a template from our website with pasted MS-Office texts (I stripped it down to this particular test case):

``` html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>xxx</title>
<link rel="stylesheet" href="pdf.css" />
</head>
<body>

<div class="page">
<table class="agenda">
<tbody>
<tr>
<td>asdf</td>
<td><table width="441" style="width: 331pt; border-collapse: collapse;" border="0" cellspacing="0" cellpadding="0">  <colgroup><col width="441" style="width: 331pt; mso-width-source: userset; mso-width-alt: 16128;">  <tbody><tr height="19" style="height: 14.25pt;">    <td width="441" height="19" style="border: 0px black; border-image: none; width: 331pt; height: 14.25pt; background-color: transparent;"><p>asdf<br><br></p><table width="458" style="width: 344pt; border-collapse: collapse;" border="0" cellspacing="0" cellpadding="0">  <colgroup><col width="458" style="width: 344pt; mso-width-source: userset; mso-width-alt: 16749;">  <tbody><tr height="19" style="height: 14.25pt;">    <td width="458" height="19" style="border: 0px black; border-image: none; width: 344pt; height: 14.25pt; background-color: transparent;">asdf</td>   </tr> </tbody></table><span style="mso-spacerun: yes;"><p><br></p><p><br></p><table width="458" style="width: 344pt; border-collapse: collapse;" border="0" cellspacing="0" cellpadding="0">  <colgroup><col width="458" style="width: 344pt; mso-width-source: userset; mso-width-alt: 16749;">  <tbody><tr height="19" style="height: 14.25pt;">    <td width="458" height="19" style="border: 0px black; border-image: none; width: 344pt; height: 14.25pt; background-color: transparent;"></td>   </tr> </tbody></table><table width="458" style="width: 344pt; border-collapse: collapse;" border="0" cellspacing="0" cellpadding="0">  <colgroup><col width="458" style="width: 344pt; mso-width-source: userset; mso-width-alt: 16749;">  <tbody><tr height="19" style="height: 14.25pt;">    <td width="458" height="19" style="border: 0px black; border-image: none; width: 344pt; height: 14.25pt; background-color: transparent;"></td>   </tr> </tbody></table><p><br></p></span><p></p><p></p><span style="mso-spacerun: yes;"><p>&nbsp;</p><table width="458" style="width: 344pt; border-collapse: collapse;" border="0" cellspacing="0" cellpadding="0">  <colgroup><col width="458" style="width: 344pt; mso-width-source: userset; mso-width-alt: 16749;">  <tbody><tr height="19" style="height: 14.25pt;">    <td width="458" height="19" style="border: 0px black; border-image: none; width: 344pt; height: 14.25pt; background-color: transparent;"></td>   </tr> </tbody></table></span><p><span style="mso-spacerun: yes;">&nbsp;</span></p></td>   </tr> </tbody></table></td>
</tr>
</tbody>
</table>
</div>

</body>
</html>
```

I tried this example with laravel-dompdf, php-dompdf from ubuntu and the dompdf fresh from git. All are crashing with a "Division by zero".

At the moment, I tracked it down to the $max_width = 0 in the _assign_widths function, but I have no clue how to fix it. Currently I check if $max_width == 0 and set it to 1 to override this issue.

**Comment by bsweeney** [comment]
I'd have to look closer at the affected code. Perhaps it's an initialization error similar to #997. At the very least we should do something different if the divisor is zero.

**Comment by marcoraddatz** [comment]
A few weeks ago, everything was fine and now I got the same exception (plus some others). I debugged a lot and found out, that following CSS elements might create errors:

- border-collapse: collapse → `ErrorException in table_frame_reflower.cls.php line 162: Division by zero`
- border-spacing: 0 → `ErrorException in table_frame_reflower.cls.php line 162: Division by zero`
- box-sizing: border-box → `ErrorException in cellmap.cls.php line 676: Undefined offset: 164`

So I'd assume, that the example above might work without the `border-collapse`. Following code works for me (I've overwritten [Bootstraps default table style](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_normalize.scss#L416) here):
```
table {
    border-collapse: separate;
    border-spacing: 1px;
}
```

However, my last exception is also thrown because of [Bootstrap code](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_scaffolding.scss#L14):
```
*:before,
*:after {
  box-sizing: border-box;
}
```

For this I don't have a monkey patch yet.

**Comment by bsweeney** [comment]
@marcoraddatz thanks for the work-around.

I'd be surprised if the `box-sizing` declaration is having any effect since we don't yet support it.

**Comment by kumar-sumit55** [comment]
Each <td>(open td) and </td>closed td must need to write in different line instead of same line.
Example:
```
<td>
This is correct way.
</td>

<td>This is wrong way</td>
```

**Comment by johndwells** [comment]
I've encountered this too, and found that when I removed `cellpadding="0" cellspacing="0"` as per https://stackoverflow.com/a/49953106, the warning was avoided.

**Comment by bsweeney** [comment]
Looking at this again the issue encountered by the OP appears to be an issue with the table structure. I went through and fixed up the structure and no longer had any errors. As always, be sure to check your document structure because Dompdf is very finicky.
