### ISSUE TITLE
page-break-inside: avoid and large images may cause infinite loop

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#106]
_Original author: eclecticgeek (November 30, 2009 19:58:38)_

<b>What steps will reproduce the problem?</b>
1. create a document that contains an element styled with
&quot;page-break-inside: avoid&quot;
2. place inside the above element an image that spans more than a single page
3. render

<b>What is the expected output? What do you see instead?</b>
The image should be rendered and the PDF displayed. Reasonably the image
should be rendered cropped on a single page; arguably the image would be
rendered across multiple pages. Instead, DOMPDF enters an infinite loop
attempting to render the content on a single page.

Testing parameters:
 -PHP 5.2.9 on Windows and Linux
 -DOMPDF 0.6.0 alpha 2
 -remote JPG image reference
 -image dimensions 1920x1200

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=99_

**Comment by bsweeney** [comment]
This no longer seems to be causing an infinite loop, tested with

```
<div style="page-break-inside: avoid;"><img src="http://placekitten.com/200/200" width="1000" height="1000"></div>
```
