### ISSUE TITLE
Porting DomPDF 0.6 to 0.7

### ISSUE THREAD

**Issue by Mte90** [dompdf/dompdf#1070]
I'm searching to migrate https://github.com/MozillaKerala/Card-Generator to DomPDF 0.7 for the svg support.

First step: `composer require dompdf/dompdf:0.7.x@beta`
Second step: changed the path to the composer autoload
Third step: `use Dompdf\Dompdf;` in generate.php

With the same code is not working, the paper size is different.
There are any documentation for the news with the difference?

**Comment by bsweeney** [comment]
How are you setting the page size? Is this the only issue so far?

An overview of the differences is in the [release notes](https://github.com/dompdf/dompdf/releases/tag/v0.7.0-beta2). A bit more info is available from [this post in the support forum](https://groups.google.com/d/topic/dompdf/cE-551JlK-w/discussion).

**Comment by Mte90** [comment]
I think that is the only problem but a porting guide will be helpful for other problems that can be found.
I want also know if this are the correct way to install, in the readme is explained to download outside to github.
https://github.com/MozillaKerala/Card-Generator/blob/master/generate.php#L15

**Comment by bsweeney** [comment]
A migration guide is an excellent idea, and we'll post one on the wiki.

Your installation steps are correct and your code should work. `set_paper()` is still a valid call at this time, though eventually you'll want to use `setPaper()` instead. I tested locally and got the expected document size/orientation.

**Comment by Mte90** [comment]
Ok I have ported that but the paper size is wrong.
I want the size of a business card but I get 216 x 279 mm in the correct orientation.
https://github.com/Mte90/Card-Generator/blob/dompdf-0.7/generate.php

**Comment by bsweeney** [comment]
ah, I see. You're using the "card" page size, but I think that's something you must have added when you set up your copy of dompdf since it's not one of the page sizes we support. The quickest fix would be to update your `setPaper()` statement to be:

```
$dompdf->setPaper( array(0,0,295.00, 175.50), 'portrait' );
```

**Comment by Mte90** [comment]
Thank you very much!
What is the unit size of that values?
Also an error about that the size don't exist will be helpful for the future :-)

**Comment by bsweeney** [comment]
Units for PDF measurements are in PT, 72 PT per inch.

An error/warning about the size missing is a good idea, I'll keep this issue open as a reminder.
