### ISSUE TITLE
Remove internal autloading

### ISSUE THREAD

**Issue by edefimov** [dompdf/dompdf#1071]
It will be convinient to use dompdf library, if internal autoloading is removed, or at least disabled by default. Library's autoloading can be easily replaced using composer or framework related engine, there is no necessity in the own mechanism.

**Comment by bsweeney** [comment]
This is how 0.7.0 is set up. Try `composer require dompdf/dompdf:0.7.x@beta` ([from the beta](https://github.com/dompdf/dompdf/tree/v0.7.0-beta2)). We're on [packagist](https://packagist.org/packages/dompdf/dompdf) if you'd rather track our progress that way.
