### ISSUE TITLE
DOMPDF in wordpress showing "CURRUPT fileformat (text/html)"

### ISSUE THREAD

**Issue by SouravMajumdar** [dompdf/dompdf#1072]
I am generating a PDF file using DOMPDF in wordpress, 1st it was working fine, but from yesterday, it is downloading, but not opening showing "CURRUPT fileformat (text/html)". I replace the DOMPDF library with 3 different versions, $html string is cumming properly. googled this problem, neither space is there in my code. Please help me.
 Here is my code:-

```
<?php
session_start();
$htmlstring = $_SESSION['template']['html'];
$filename = $_SESSION['template']['file_name'];
include( get_template_directory() . '/dompdf/dompdf_config.inc.php' );
unset($_SESSION['template']);
echo $htmlstring = stripslashes($htmlstring);
ob_start();
$dompdf = new DOMPDF();
$dompdf->load_html ($htmlstring);

$dompdf->render();
$output = $dompdf->output();
$pdfFile = $path['path'].'/CSV_PDF/'.$filename;
file_put_contents($pdfFile, $output);
$dompdf->stream($filename);
unlink($attachment);
unlink($pdfFile);
return 1;
?>
```

My HTML is on another page.

**Comment by bsweeney** [comment]
The most likely cause is that some PHP errors/notices have made it into the PDF stream. This typically results from using dompdf while output buffering is enabled. You can check this by downloading your PDF and opening it in a text editor. The PHP notices will be above the PDF source.

When using dompdf we recommend that you turn off output buffering. Also, right now you should not use both the stream and output methods together. For some reason they interfere with the PDF generation. Plus, it doesn't really look like you're using the PDF file you create on your system.

The following might work better:

```
<?php
session_start();
$htmlstring = $_SESSION['template']['html'];
$filename = $_SESSION['template']['file_name'];
include( get_template_directory() . '/dompdf/dompdf_config.inc.php' );
unset($_SESSION['template']);
$htmlstring = stripslashes($htmlstring);
$dompdf = new DOMPDF();
$dompdf->load_html ($htmlstring);
$dompdf->render();
$dompdf->stream($filename);
?>
```

And really you should always disable sending errors to the browser in PHP

**Comment by SouravMajumdar** [comment]
Hello  bsweeney,

I tried it in your way. removed those output, implemented your codes you have given But it results the same. Its not working, Please help me. It was working fine previously, suddenly, this is showing errors, and PDF is not openning for currupt file format. Please help me here.

and,

"And really you should always disable sending errors to the browser in PHP" - what do u mean by this?

**Comment by bsweeney** [comment]
> you should always disable sending errors to the browser in PHP

Yes, I would recommend setting display_errors to off (if that's not your current setup).

Back to your problem ...

What version of dompdf are you using? There are some versions whose PDF structure is problematic for some PDF viewers. Can you upload a corrupted PDF so we can inspect it?

**Comment by lopandpe** [comment]
Hi!

I reopen this issue, because I have the same problem using DOMPDF in wordpress.

I'm trying with the basic example

```
// EXAMPLE TAKEN FROM https://github.com/dompdf/dompdf

require_once(GESTION_ODC_DIR . 'dompdf\autoload.inc.php');

// reference the Dompdf namespace
use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();
$dompdf->loadHtml('hello world');

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'landscape');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream();

```

And the file created has only 18 lines. Could you help me to identify the problem?


[document.pdf (2).pdf](https://github.com/dompdf/dompdf/files/464306/document.pdf.2.pdf)

**Comment by bsweeney** [comment]
@lopandpe there's nothing wrong with your Dompdf usage so it's probably related to how you're trying to integrate it into WordPress. It would help to see how you're using it inside dompdf.

I looked at the source of the PDF you attached and it has nothing but what looks like a part of the WordPress HTML header. This indicates that the something is causing the header to be sent to the browser before Dompdf is able to render the PDF. If content is sent to the browser Dompdf will throw an error when your call the `stream()` method. This is probably why this is the only content of the page.

You can test this theory by replacing `$dompdf->stream();` with `echo $dompdf->output();`. It won't address your issue, but at least you'll know whether or not dompdf is working correctly.

Might I suggest [using a plug-in](https://wordpress.org/plugins/search.php?q=dompdf) instead of developing the functionality yourself?

**Comment by lopandpe** [comment]
Hi @bsweeney thanks for answering. I've not found any wordpress plugin for doing all I need. 

I will ask in a wordpress forum, and I'll leave here the solution if Ifinally get it.

**Comment by waqastariqkhan** [comment]
@lopandpe sorry for pinging you after 8 years, do you remember how you were able to achieve this?
