### ISSUE TITLE
[FEATURE PROPOSAL] Add the DOMDocument support

### ISSUE THREAD

**Issue by Lcfvs** [dompdf/dompdf#1073]
Hi,

Just a little post to suggest to support a DOMDocument support as input and to use it, if any, in place of a string.

The idea is to avoid a double DOM parsing.

IMHO, it makes sense when you already built the document by DOM.

What do you think about it, please? :)

**Comment by bsweeney** [comment]
I do like the idea, I'll tentatively schedule this for 0.7.0.

**Comment by Lcfvs** [comment]
Thanks a lot :)

**Comment by Lcfvs** [comment]
Hi...

Still on deck ?

**Comment by bsweeney** [comment]
Sorry this completely slipped by me. Luckily somebody went ahead and put together a change that should support this.

**Comment by Lcfvs** [comment]
Hi,

I don't code in PHP anymore but thanks anyway.
