### ISSUE TITLE
Clear property doesn't working in dompdf?

### ISSUE THREAD

**Issue by kamalsamra** [dompdf/dompdf#1074]
```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body>
    <div>
        <div style="float:left;width:50%;">sdhfl<br/>ajsdhk asbhdkja</div>
        <div style="float:left;width:50%;">sdhfl</div>
        <div style="clear:both;"></div>
    </div>
    <div>
        sdlkfl;s jashfkjas
    </div>
</body>
</html>
```

On pdf generation of above HTML second div content get overlap on first floated div as in this clear property does not work properly.You can see output here http://eclecticgeek.com/dompdf/debug.php?identifier=8b754f378a42f3e839b3acbf9cf31239

**Comment by bsweeney** [comment]
There does appear to be a problem here. For this simple example you can work around the issue by moving the clearing div outside the float container, e.g.

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body>
    <div>
        <div style="float:left;width:50%;">sdhfl<br/>ajsdhk asbhdkja</div>
        <div style="float:left;width:50%;">sdhfl</div>
    </div>
    <div style="clear:both;"></div>
    <div>
        sdlkfl;s jashfkjas
    </div>
</body>
</html>
```

But that doesn't work on all variations on your structure. Generally clearing a two-column float seems to work better if the floats are in a container and the clear outside the container.

**Comment by kamalsamra** [comment]
Thanks but it is working only in this structure,there is one another structure
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <style>
  @page {
			margin:50px 0 0 0;
		}
		@page :first {
			margin:0;
		}
		
		  .heading {
font-size:3em;text-transform:uppercase;
line-height:1em;

}            

.first-head{
float:left;
}     
  
.clearfix{
display:block;
clear:both;
content:"";
}  
    
.align-right{
text-align:right;
}             </style>
</head>
<body>
  <div class="resumesheet" style="width:210mm;min-height:297mm;font-size:3.75mm"><div class="resumesheet-inner" style="font-family:Courier New;"><div>
<div class="horizontal-margin vertical-margin" style="padding-left: 5.1%; padding-right: 5.1%; padding-top: 4.9mm;">
<table cellspacing="0" style="width:100%; height:150px;">
<tbody><tr>
<td data-section="personal" style="width:60%;">
    <div class="block section" style="margin-bottom: 2em; font-family: Arial;">
        <div class="inner-section">
            <div class="inner-block" >
            <div class="first-head" data-calculateheight="true">
                <div><span data-section="name" class="heading">Kamal Samra</span></div>
                <div class="align-right"><span data-section="profession">Software Developer</span>
                    <br><span data-section="location">Jaipur</span>
                </div>
            </div>
            </div>
            <div style="clear:left;"></div>
            </div>
        </div>
    </td>

<td data-section="contact" style="width:40%;text-align:left">
    <div class="block section" style="margin-bottom:2em;">
        <div class="inner-section">
            <div class="inner-block">
                <div data-section="content"><p><span style="">your.name@example.com</span>
                <br style="">
                <span style="">111-222-3333</span><br style=""><span style="">www.your-website.com</span><br>
                </p></div></div></div></div></td>
</tr>
</tbody></table>
</div>
</div>
</div></div>
</body>
</html>
and you can see output here : 
http://eclecticgeek.com/dompdf/debug.php?identifier=55d8d8b05c977811475ed70076f7a11b

**Comment by bsweeney** [comment]
I realize that fix won't address all variations. Until we can resolve the underlying problem you'll have to find a way to work around the issue.

While there are still problems with the float rendering in this second sample the more relevant issue here is that dompdf does not yet correctly calculate the width of floated or positioned elements that have `width: auto` (#627). Plus, this second example seems to be working awfully hard to achieve what looks to be a fairly simple layout. Unless this is generated by some kind of framework or content management system I'd suggest simplifying your HTML.

Unless, of course, your example is merely contrived to illustrate the issue further.

**Comment by kamalsamra** [comment]
Hi
Float property is working but clear property does  not work properly as so for that we have to give height on parent element.But as we give height to parent element and text is more and some content of div move to next page then some white space added.

**Comment by bsweeney** [comment]
@kamalsamra works fine in some situations. Which version of dompdf are you using and can you provide a sample of your HTML?

**Comment by kamalsamra** [comment]
Hi,
You can check it here:
http://eclecticgeek.com/dompdf/debug.php?identifier=382e86d06e47679ead2e80eaac27af8c

**Comment by bsweeney** [comment]
Clearly some problems. First, without a height on the container element dompdf is unable to really figure out *where* to clear. Second, dompdf has problems clearing floats contained in another element. Third, dompdf doesn't appear to be taking the floats into account when calculating element height.

I don't have a good work-around right now.

**Comment by JLNNN** [comment]
👍  on this :)

**Comment by rsm0578** [comment]
http://eclecticgeek.com/dompdf/debug.php?identifier=cb3d322897c3c272bcc3e6c974ebeb1b
Image issue, once go through link

**Comment by bsweeney** [comment]
@rsm0578 not sure what you need. Try running again, but head to the options tab and select dompdf_develop as the dompdf release. You'll see that the particular issue is resolved. Though your code does bring up a new issue: float does not appear to apply to tables. You might want to start a new issue for that.

In terms of your document you don't even need the table surrounding the image so you can work around the issue.
