### ISSUE TITLE
Support for multibyte languages like Chinese, Russian etc

### ISSUE THREAD

**Issue by bbreukelen** [dompdf/dompdf#1085]
I don't think DomPDF supports multi-byte character sets.
When I insert some russian text it returns questionmarks only.

Are there any plans to support this or workarounds available?

Thanks!

**Comment by bsweeney** [comment]
Support for multi-byte character sets was included as of version 0.6.0. Please read the [Unicode How-To](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo) for more information.
