### ISSUE TITLE
Using relative protocol sources causes img not to load

### ISSUE THREAD

**Issue by dhaupin** [dompdf/dompdf#1086]
Hi, thanks for all the work you guys put in this lib.

There seems to be an issue with how DomPDF is rendering sources of assets that use relative protocol urls. Im not sure if this is a bug with domains in www like `//www.relativeproto.com/img.png`, or if it just applies to non-www subdomains like `//assets.relativeproto.com/img.png`, but regardless the image doesnt parse into PDF. We are using the second example, with a subdomain of "shop".

Im sure you know, but relative protocol source urls are those that operate in both `http://` and `https://` mode. They are popular with assets, images, etc. The idea is that when requesting a secure page they are able to provide an asset source that won't "break the green lock", and they are still able to run normal without extra SSL overhead.

A cheesy way around it is to use `str_replace('src="//', 'src="https://', $pdf_data)` to scrub the data of relative protocol strings, but there are better ways (albeit looking for proto from SSL flags is more than `$_SERVER['HTTPS']). Is there such a scrub or proto-rewrite in DomPDF?

**Comment by bsweeney** [comment]
As it so happens dompdf supports this functionality as of v0.6.2 (see #1048).

**Comment by dhaupin** [comment]
Interesting. That is the version im working with however the relatives arent working. I tried it as a raw test string as an img src. Is there a constant/setting/option or something that i need to flag at runtime to percolate this?

**Comment by bsweeney** [comment]
It should just work. Do you have a sample of your HTML and your PHP related to dompdf?

**Comment by dhaupin** [comment]
Sure, its basically a wrapper method inside the document class in Opencart. The `src` replace is commented out in this example:

	// Generates a pdf from input html data
	public function pdf($pdf_data, $pdf_name, $pdf_no_dl = false) {
		$pdf_name = $this->str_file($pdf_name, '_', 'pdf');
		//$pdf_data = str_replace('src="//', 'src="http://', $pdf_data);
		
		require_once(DIR_SYSTEM . '../vendor/dompdf/dompdf/dompdf_config.inc.php');
		
		$pdf = new Dompdf();
		$pdf->set_option('enable_remote', true);
		$pdf->set_option('enable_html5_parser', true);
		$pdf->load_html($pdf_data);
		$pdf->render();
		
		if ($pdf_no_dl) {
			$pdf->stream($pdf_name, array("Attachment" => 0));
		} else {
			$pdf->stream($pdf_name);
		}

		// this exit suppresses the headers already sent warn from DOMPDF
		exit;
	}

So testing with this string should work:

`$pdf_data = '<img src="//shop.cjshomedecor.com/image/data/Options/Icons/usaflag.png" />';`

Via the wrapper:

`$this->document->pdf($pdf_data, 'test_pdf', true);`

I'll try re-uploading the libs and stuff just to make sure i guess in the meantime

**Comment by bsweeney** [comment]
Since you're using the `load_html()` method dompdf has no way of knowing what the protocol is. You'll either have to include a base href
```
<base href="http://example.com">
```
 or set the base url using the appropriate methods:
```
```
