### ISSUE TITLE
dynamic footer and PAGE_NUM

### ISSUE THREAD

**Issue by flakesnow** [dompdf/dompdf#1089]
Hey :)

i wonder why this dont work.
I create dynamic footer and header, no problem.

i need a single header on the first page and a single footer on the last page. - No problem 

On the other Pages between the first and the last a header is not necessary and the footer should print the page number.

But my question is why this dont work: its not parsing the pdf.

Its not the whole code. Just the important pieces.

``` html

//css part
<style>
.pagenum:before {
    content: counter(page);
}
</style>

        //set up the global array
    <script type="text/php">
    $GLOBALS["footer"][]= array();
    </script>

        //create the footer content
    <div class="footer">
      <script type="text/php">$GLOBALS[\'footer\']= $pdf->open_object();</script>
      <div class="content">Seite - <span class="pagenums"></span>-</div>
      <script type="text/php">$pdf->close_object();</script>
    </div>

//write the footer
    <script type="text/php">
      $pdf->page_script(\'
$pdf->add_object($GLOBALS["footer"][$PAGE_NUM],"add");
      \')

```

Anybody a solution?
the thing is, when im changing div class footer to header. Its okay, everything works and the pdf get parsed sucsessfull.

**Comment by bsweeney** [comment]
For the single header on the first page and the single footer on the last page you could just use absolutely positioned content. Just put the header above everything else and the footer below everything else.

Of course, the in-between stuff is a bit more complex.

The code you're using isn't fully supported. I've certainly found ways to use HTML/CSS and embedded script mixed together, and I've even offered suggestions for how to use it to work out more complex documents (e.g. TOC), but you don't always get the expected results.

But let's start with the question at hand. So your document is rendered but the embedded script is not processed? Have you enabled PHP support in your configuration?

**Comment by hellboy81** [comment]
@flakesnow 

>I create dynamic footer and header, no problem.

How can you create it? Please provide sample code

>i need a single header on the first page and a single footer on the last page. - No problem

The same question

**Comment by bsweeney** [comment]
@hellboy81 see this statement:

> For the single header on the first page and the single footer on the last page you could just use absolutely positioned content. Just put the header above everything else and the footer below everything else.

If you need more detail it would help to know exactly what you need to create.

**Comment by bsweeney** [comment]
no additional info provided as of yet, closing
