### ISSUE TITLE
How to import new font (ex: Commons) in dompdf v0.7beta?

### ISSUE THREAD

**Issue by VienNguyen113** [dompdf/dompdf#1091]
Hi!
I had problem with import some font into dompdf v0.7 beta. Can you please tell me step to step about import font? I also use @font-face but it not working for me!
Please help me!
Thank you so much!
Vien Nguyen

**Comment by bsweeney** [comment]
The [Unicode How-to](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo) has information on how to install fonts.

Beyond that, do you have an example of your CSS?

**Comment by VienNguyen113** [comment]
Hi
Perhaps, google fonts: font-weight: bold; not support in dompdf, such as: Open Sans, Lato
I declared : 
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>
in my project.
Thanks!

**Comment by VienNguyen113** [comment]
Hi Brian,
I want to use pre-loading font because in my project font-weight: bold, italic is very important. But in v0.7 beta not support pre-loading font.
Can you give me v0.6.2 and let me know how to use it?
Please help me!
Thanks you so much!
Vien Nguyen.

**Comment by bsweeney** [comment]
dompdf does not support numeric weight very well (see #675). There is a work-around, but it's not very efficient.

0.7.0 does not include any extraneous code (such as the load_font.php script) in the package, but you can find related tools in the [utils project](https://github.com/dompdf/utils).

Whether you're using the 0.6.2 release or the 0.7.0 beta the README.md should have all the information you need to get started. Beyond that if you have any specific questions please feel free to ask.

**Comment by VienNguyen113** [comment]
Ok Brian, thanks for your help!
I just has a problem: i has tag img: `<img class="image-following" id="image" src="/web/upload/uploadImageCus/customer16671454085946.png">`, but when i render to pdf the pdf not show image.
If i use: src="data:image/jpge;base64....." then image show right.
Can you tell me about this? And let me know how i can fix it?
Thanks you so much!

**Comment by bsweeney** [comment]
How dompdf loads your image depends on how you load the HTML document. If you provide only a path in your URL then dompdf determines where the file is based on the location of the HTML document. When using `load_html()` dompdf has no pre-existing knowledge of the document location and so assumes the base path is the executing script's path on the file system.

So "/web/upload..." looks for the file on that path from the root of your file system. If this is actually a sub-path of your web server's document root you would need to append the document root path, e.g. "/www/content/web/upload...".

Probably the easiest method of working around the `load_html()` base path problem is to tell dompdf what the base is. Either by adding a base href to your document header:

```
<base href="http://example.com">
```

or by setting the base url using the appropriate methods:

```
$dompdf->setProtocol('http://');
$dompdf->setBaseHost('example.com');
$dompdf->setBasePath('/content/dir');
```

**Comment by VienNguyen113** [comment]
Ok, thanks! It work fine for me :+1:

**Comment by bsweeney** [comment]
Excellent! If you need any further help let us know. A good place for general questions is the support forum: http://groups.google.com/group/dompdf

**Comment by VienNguyen113** [comment]
Ok Thanks you!

**Comment by VienNguyen113** [comment]
I am using yii2.
When i generate pdf i had problem: `\source\vendor\dompdf\dompdf/lib/fonts/fonts\\0d957fa102d543d31cc8f0415c0b1506.ufm.php` **failed to open stream: No such file or directory**.
If i create folder **fonts** in **\vendor\dompdf\dompdf/lib/fonts/** then it work fine.
I modified in vendor, it's not good.
Can you please check it and let me know?
Thanks

**Comment by bsweeney** [comment]
I'm not sure why it would be trying to put the files in that particular directory. What is the setting for your font directory and font cache directory? By default it should be dompdf/lib/fonts.

**Comment by VienNguyen113** [comment]
Hi,
I had a problem.
When i up load code on my server, google font not working (in localhost it works fine).
Can you help me about this? 
Thanks!

**Comment by bsweeney** [comment]
Did you upload from your local install to your remote? If so you should probably reset your font directory so the font can be loaded again on the server. Remove the dompdf_font_family_cache.php file (*not* the .dist file).

**Comment by VienNguyen113** [comment]
Excellent!
Thanks for your help!
It work fine for me :)) :+1:
