### ISSUE TITLE
Rendering SVG File.

### ISSUE THREAD

**Issue by ChadTaljaardt** [dompdf/dompdf#1093]
Hello, 

I have a SVG file that i'm trying to get rendered and its just giving me the text with no images or styles. 

Do you have any advice on what i can do to fix this?

**Comment by bsweeney** [comment]
Do you have some sample code? You might also read through #320 to see if there's any useful info related to using SVG with dompdf.

**Comment by ChadTaljaardt** [comment]
Hello, 

Here is thhe certificate svg im using. 

https://gist.githubusercontent.com/ChadTaljaardt/ca87407148e8fde04877/raw/3e2db3bfbbfd987ad99aba2508aff2b219e48751/Certificate.html

Here is a screenshot of the output : http://cl.ly/1x2s1s1P3W3j

**Comment by ChadTaljaardt** [comment]
I forgot to say here is the code in my Controller.

<?php

namespace App\Http\Controllers\test;

use Illuminate\Http\Request;

use PDF;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class testController extends Controller
{
    public function testfunction() {
    	$pdf = PDF::loadView('cert.test');
		return $pdf->download('invoice.pdf');
    }
}

**Comment by bsweeney** [comment]
Are you attempting to render the SVG document directly? dompdf can't do that, it expects the document to be in HTML format and currently only renders SVG linked via IMG element, e.g. `<img src="certificate.svg">`.

If you want to directly convert an SVG check out [php-svg-lib](https://github.com/PhenX/php-svg-lib). This is the library that dompdf uses. Note that php-svg-lib does not yet have good support of text in SVG.

**Comment by maartenmachiels** [comment]
Hi, is SVG support via an image tag <img src="certificate.svg"> supported in version 0.6.3? I am trying to do exactly this, but keep getting the error "Image not found or type unknown".

**Comment by bsweeney** [comment]
@maartenmachiels only starting with 0.7.0.

**Comment by Jany-M** [comment]
Just an idea.
Try something like this in your page code instead, managing `svg/png` from the page directly, instead of messing with `svg` later (also better for some devices/compatibility):

`<img class="svg" src="someimage.svg" onerror="this.onerror=null; this.src=someimage.png"/>`

`
// Replace all SVG with inline SVG
replaceSvg();

function replaceSvg()    {
        jQuery('img.svg').each(function(){
            var $img = jQuery(this);
            var imgID = $img.attr('id');
            var imgClass = $img.attr('class');
            var imgURL = $img.attr('src');

            jQuery.get(imgURL, function(data) {
                // Get the SVG tag, ignore the rest
                var $svg = jQuery(data).find('svg');

                // Add replaced image's ID to the new SVG
                if(typeof imgID !== 'undefined') {
                    $svg = $svg.attr('id', imgID);
                }
                // Add replaced image's classes to the new SVG
                if(typeof imgClass !== 'undefined') {
                    $svg = $svg.attr('class', imgClass+' replaced-svg');
                }

                // Remove any invalid XML tags as per http://validator.w3.org
                $svg = $svg.removeAttr('xmlns:a');

                // Replace image with new SVG
                $img.replaceWith($svg);

            }, 'xml');

        });
}
`

**Comment by landsman** [comment]
Hello how looking this?
I have invoice with logo in SVG and its pain for printing by this package :/

**Comment by bsweeney** [comment]
FYI, anyone wanting to convert directly from SVG to PDF you might consider using [php-svg-lib](https://github.com/PhenX/php-svg-lib) directly instead of going through Dompdf.

**Comment by bsweeney** [comment]
Just FYI I'm going to tie this to the other issue. The SVG does appear to render but there are still issues to address. Any issues particular to the SVG library should be posted there.

**Comment by bsweeney** [comment]
FYI I believe the issue parsing the original SVG was due to the use of units (px in this case) throughout the document. php-svg-lib apparently doesn't parse values with units yet. Follow dompdf/php-svg-lib#76 for updates.
