### ISSUE TITLE
Pixelated/Blurry text when printing PDF

### ISSUE THREAD

**Issue by maurocasas** [dompdf/dompdf#1094]
Hey there!

I've been able to generate my PDF files properly, but when I print them in "real" paper the text looks blurry/pixelated.

I've tried removing all the images from the file, and replaced my fonts from Helvetica to DejaVu Sans but I'm still getting the same results.

Any idea why this may be caused?

Thx

**Comment by bsweeney** [comment]
Do you have some samples you can share, e.g. sample HTML, sample PDF output, and an image of what the printed version looks like?

**Comment by maurocasas** [comment]
Forgot to update on this.

What my software currently does is generate a PDF file for each request the user does, and then merges them into one using another tool.

This "another" tool, was actually converting each page to JPEG and then merging them into a new PDF file thus the quality loss. I have replaced my merging tool and now works just fine! :monkey:

**Comment by bsweeney** [comment]
That's just ugly! I'm curious which tool you were using and which you're using now.

**Comment by maurocasas** [comment]
I was originally using https://github.com/hanneskod/libmergepdf and now I'm using https://github.com/clegginabox/pdf-merger instead.

I don't really know why the difference, as they both use FPDI, but again, I haven't gone really deep down the code to see the actual difference in the processing as the task I'm trying to do is just merging the files for printing simplicity matters.

**Comment by bsweeney** [comment]
Thanks for the info :)

**Comment by maurocasas** [comment]
I'm actually using https://github.com/myokyawhtun/PDFMerger, just realized when I tried to composer update and failed haha
