### ISSUE TITLE
Call to undefined method DOMPDF::loadHtml()

### ISSUE THREAD

**Issue by qgoflake** [dompdf/dompdf#1095]
Hello All,

Downloaded and am using 0.6.2 Tried sample code...

        // include autoloader
	require_once "lib/dompdf/dompdf_config.inc.php";

	// instantiate and use the dompdf class
	$dompdf = new Dompdf();
	$dompdf->loadHtml('hello world');
	
	// (Optional) Setup the paper size and orientation
	$dompdf->setPaper('A4', 'landscape');
	
	// Render the HTML as PDF
	$dompdf->render();
	
	// Get the generated PDF file contents
	$pdf = $dompdf->output();
	
	// Output the generated PDF to Browser
	$dompdf->stream();

get the following error: Fatal error: Call to undefined method DOMPDF::loadHtml()

As good measure, tried to run setup and get access denied...

Access denied to host at XX

Any suggestions would be appreciated. Looks like great software.

**Comment by bsweeney** [comment]
The correct method call on 0.6.2 is `$dompdf->load_html()`. I'm in the process of updating the documentation.

Also, don't call `$dompdf->output()` and `$dompdf->stream()` ... the two methods interfere with each other.
