### ISSUE TITLE
How to get a file example pdf

### ISSUE THREAD

**Issue by duythien** [dompdf/dompdf#1098]
Hi Team,

I have take look your source but I don't see some file html example as demo at http://pxd.me/dompdf/www/examples.php#css_baseline.html,html

How to i do get it

**Comment by bsweeney** [comment]
The samples were removed starting with the 0.7 code base. You can look at previous versions of the code (e.g. [0.6.2](https://github.com/dompdf/dompdf/tree/v0.6.2)) by clicking the branch dropdown above the file listing and selecting the "tags" tab.
