### ISSUE TITLE
Uninitialized string offset: 0

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#110]
_Original author: fjgod... (December 04, 2009 12:14:20)_

A PHP Error was encountered
Severity: Notice

Message: Uninitialized string offset: 0

Filename: include/functions.inc.php

Line Number: 313

SOURCE LEVEL

/\* $Id: functions.inc.php 201 2009-12-04 04:46:42Z woody.gilk $ */

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=103_

**Comment by LizReina** [comment]
como resolviste el problema de Uninitialized string offset 0
