### ISSUE TITLE
Invalid PDF structure

### ISSUE THREAD

**Issue by bernhardhas** [dompdf/dompdf#1102]
I have a problem when showing the generated PDF with pdf.js and parsing them with "PDF Parser".
Error: Invalid PDF structure

Adobe-Reader will show and print the pdf-file correctly.

I have tested the latest versions: 0.6.2 (stable), 0.7.0 (beta3)

Need Help....

Thank you !!!

**Comment by bsweeney** [comment]
Do you have a sample of the HTML that's producing the problem PDF as well as the PDF itself?

**Comment by bernhardhas** [comment]
thank you for your quick response ....

you can do it with a very simple "hello world" example.
<html><head></head><body><div>hello world</div></body></html>

-----------------------------------------------------------------------------
I use dompdf for my browser business application.
It's very easy and fast. 
Almost everything is fine.

Only two Problems:
- i won't to integrate PDF-Viewing in browser with pdf.js (without plugin)
- i need a feature "auto-height" for endless-format (receipt (sales slip))
       (at this moment i have a workaround (but i cannot get the last text position (y-coordinate)))
     
Thank you for your help !

**Comment by bernhardhas** [comment]
sorry, - missing html-tags....

next try:

`<html><head></head><body><div>hello world</div></body></html>`

**Comment by bsweeney** [comment]
I haven't seen the same issue using Firefox (whose reader is based on pdf.js). Can you upload a sample PDF?

As for auto-height. It's a bit difficult to do right now. The workaround I've used is to define a custom page size, render the document, count the pages, calculate the height of the content, render again with a new custom size.

**Comment by bernhardhas** [comment]
1.
-----------------------------------------------------------------------
I've tested it once more !
You are right, - sorry !
The PDF-file generated from dompdf is okay !!
It's not a Problem of dompdf.

The Problem occurs, if i want to show a pdf from database with pdf.js !
With Adobe-Reader-plugin: no Problem !

On Server-side i output the pdf from database with PHP:
`header("Content-type: application/pdf");
echo $pdfFile;`

2.
--------------------------------------------------------------------------------------
The Workaround for auto-height: That's they way I've done it !

Thank you for your quick Response !

**Comment by bernhardhas** [comment]
pdf.js:

If i write the binary data from database to file on filesystem 
and use the direct link to the pdf-file, it works.

this link works: pdfjs/web/viewer.html?file=99.pdf
this link doesn't work: pdfjs/web/viewer.html?file=showFile.php?id=99

No idea .......

**Comment by bsweeney** [comment]
That's interesting. It could be due to the difference in how your web server serves up the file vs. when you stream from the db. Maybe the headers need to be adjusted. You also might try forcing the connection closed after the PDF has been sent (e.g. using `exit`).

**Comment by Rickardo228** [comment]
I’ve also been struggling with this issue!

When I feed the output of dompdf directly into pdfjs, I have a range of errors. However, if I download the file onto my system and upload manually, reading the file as a binary string using file.readAsBinaryString(), it works!

did you ever find a solution @bernhardhas?
