### ISSUE TITLE
border-radius and table cells

### ISSUE THREAD

**Issue by rickhessmann** [dompdf/dompdf#1104]
Hi guys. Is it possible to style table cells, like I do on browser?
I'm having a hard time trying to achieve the results I see on screen to be printed on PDF.

**Comment by rickhessmann** [comment]
Found a workaround, but differente problem appeard. I'm confused.
![fix](https://cloud.githubusercontent.com/assets/3538367/12939716/bb382536-cfa9-11e5-914d-1c0cf166ddab.png)

**Comment by bsweeney** [comment]
There's a bug in border radius rendering if values are not applied to the bottom corners, see [my comment](https://github.com/dompdf/dompdf/issues/374#issuecomment-22612595) on issue #374. The workaround for the issue is to add a 1px border radius to the other corners.
