### ISSUE TITLE
Warning errors in Magento

### ISSUE THREAD

**Issue by itBrujo** [dompdf/dompdf#1105]
Install the latest stable version via git.

Library works. Added Cyrillic, no question about it. There were problems with the display of images and layout tables. Images do not fall in the pdf file. Tables appear crooked. But now I want to deal with others.

The system log alerts just filled the form:

> ERR (3): Warning: include (Dompdf \ Canvas.php <..and all another lib classes...>): failed to open stream: No such file or directory in /home/<...site path...> / lib / Varien / Autoload.php on line 94

But in reality the classes are loaded by means of the library.
And here's the code around this line in lib/Varien/Autoloader.php:
```
static public function register()
    {
        spl_autoload_register(array(self::instance(), 'autoload'));
    }

```
```
    /**
     * Load class source code
     *
     * @param string $class
     */
    public function autoload($class)
    {
        if ($this->_collectClasses) {
            $this->_arrLoadedClasses[self::$_scope][] = $class;
        }
        if ($this->_isIncludePathDefined) {
            $classFile =  COMPILER_INCLUDE_PATH . DIRECTORY_SEPARATOR . $class;
        } else {
            $classFile = str_replace(' ', DIRECTORY_SEPARATOR, ucwords(str_replace('_', ' ', $class)));
        }
        $classFile.= '.php';
        return include $classFile;
    }
```
Prompt, what is it? And what to do with it?

**Comment by bsweeney** [comment]
I don't know Magento, so you'll have to do some poking around on your own. But a quick look at the autoloader code leads me to believe that the Magento autoloader does not support PHP namespaces. Since I don't use Magento you'll have to figure out the best way to address the issue, but I did find a project that adds namespace autoloading support: [kschroeder/magento-namespace-autoloader](https://github.com/kschroeder/magento-namespace-autoloader).

**Comment by bsweeney** [comment]
Also, please note that if you're pulling from the git repo directly you wont' have all the code you need. At the very least you'll also need a copy of [php-font-lib](https://github.com/PhenX/php-font-lib).

You might look into [using composer with magento](https://github.com/Cotya/magento-composer-installer).
