### ISSUE TITLE
Fatal error: Call to a member function split() on null

### ISSUE THREAD

**Issue by kirugan** [dompdf/dompdf#1110]
I`ve got this error: "**Fatal error: Call to a member function split() on null in /srv/avito/vendor/dompdf/dompdf/include/page_frame_decorator.cls.php on line 534**".
This is happend because page break starts when there is no table-row yet, (only table-row-group element exists).

**Comment by bsweeney** [comment]
So how did you even run into this error? I have so far been unable to reproduce.

**Comment by bsweeney** [comment]
Per #1125 the problem appears to be caused by a structural issue with the HTML document.
