### ISSUE TITLE
float is not working 

### ISSUE THREAD

**Issue by LakshmanKatragadda** [dompdf/dompdf#1116]
``` css
#company {
  float: right;
  text-align: right;
}
```

even text not displaying on pdf. text was disappeared

**Comment by bsweeney** [comment]
If you're using 0.6.2 or earlier you have to enable float support in your configuration (starting with 0.7.0 it's enabled by default). But the text shouldn't disappear. Do you have a more complete sample HTML document?

**Comment by laxman1223** [comment]
i am using latest version from composer 

https://gist.github.com/laxman1223/ca3fb31d542ded325f79

**Comment by bsweeney** [comment]
The float is working but support for clearing floats is still iffy (#26, #1074).

You can sort of get a working render by inserting a div after the elements containing floated children. But you may have to tweak the styling to get something acceptable.

**Comment by bsweeney** [comment]
I believe the code in the develop branch does a much better job with your document now. If you have a moment to take a look and report back we'd appreciate it.

**Comment by bsweeney** [comment]
@sgehrman which version of dompdf? Can't really help without seeing a sample of the HTML+CSS. If you still need help go ahead and open another issue, I'm going to close this one since there have been no recent updates from the OP.
