### ISSUE TITLE
Text overlapping & other strange things since moving to new server

### ISSUE THREAD

**Issue by keithslater** [dompdf/dompdf#1120]
We moved a site from one server to another. Since then we have had an issue with dompdf and text overlapping. The text that's overlapping isn't in a table or anything.

I have noticed that before the pdf's it generated were around 700KB, now it's generating 3KB files. Besides overlapping text, a lot of other things are wrong, thing not right aligned, no bold text, etc.. The other strange thing is the 3KB files only open in the browser with data. When I open it on my computer in Preview, it's empty but has the right amount of pages.

I don't see anything in the error logs or anything like that.

I tried to replicate everything from the old server to the new. The site itself was rsync'd so nothing changed there. Only minor version of PHP changed 5.4.16. GD and Imagick is installed. mbstring is installed. The fonts were part of the files that were rsynced so that seems correct.

Any other ideas of what could be going on or where to look?

**Comment by bsweeney** [comment]
More than likely the font metrics are no longer loading correctly. If the dompdf directory, the font directory, or the font cache directory on the new server is not the same as on the old then dompdf is failing to load the font metrics and font files.

**Comment by keithslater** [comment]
Sorry for the dumb question but where is the font cache directory normally located?

**Comment by bsweeney** [comment]
Depends. By default it's the same directory as the dompdf font directory. Since you're asking that's probably what it is.

Check your dompdf_font_family_cache.php file and make sure any paths in that file are accurate.

Also, which version of dompdf?

**Comment by keithslater** [comment]
Awesome, thanks for the help. The cache file was pointing to the wrong place for the fonts.
