### ISSUE TITLE
change application from "DOMPDF"

### ISSUE THREAD

**Issue by Pekinese** [dompdf/dompdf#1122]
How to change the application name from "DOMPDF" to some other name?
![87aecdeb68 1](https://cloud.githubusercontent.com/assets/10235040/13205211/1697460e-d8e3-11e5-89eb-1aa607298ff5.png)

**Comment by bsweeney** [comment]
You would do this by modifying the PDF meta after rendering your document:

```php
$dompdf = new DOMPDF();
$dompdf->load_html($html);
$dompdf->render();
$dompdf->add_info('Creator', 'My App Name');
```
[[ref](http://stackoverflow.com/a/32233973/264628)]

FYI, prior to v0.7.0 dompdf wrote library info into the "creator" pdf metadata element (aka Application). Starting with 0.7.0 we're moving this info to the more appropriate "producer" metadata element. The creator info is normally used to indicate the application that created the original document.
