### ISSUE TITLE
UTF-8 Currency Symbols are not working 

### ISSUE THREAD

**Issue by laxman1223** [dompdf/dompdf#1123]
ex : `&#x20B9;  `&#x20B9;

**Comment by bsweeney** [comment]
Characters that are not represented in the Windows ANSI character encoding require a non-core font family (the core font families being Helvetica, Times, Courier, and the generic fallbacks sans-serif, serif, monospace). Take a look at the [Unicode How-To](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo).

For your specific example, you can use the following with dompdf 0.6.0 or greater:

```html
<span style="font-family: DejaVu Sans;">&#x20B9;</span>
```

**Comment by onyema3** [comment]
How do i use this line
<span style="font-family: DejaVu Sans;">&#x20B9;</span>
Where do i add it

**Comment by bsweeney** [comment]
Add that code where you would normally want the symbol to appear. For ₦ try:

```
<span style="font-family: DejaVu Sans;">&#x20A6;</span>
```

*Note: in dompdf 0.6.0 or newer*

**Comment by onyema3** [comment]
Thanks

**Comment by dubems** [comment]
thanks for the naira. really helped me to

**Comment by VirendraArekar** [comment]
<span style="font-family: DejaVu Sans;">&#x20B9;</span> using but note getting symbol show me ?.
Give me solution.

**Comment by bsweeney** [comment]
@VirendraArekar that works for me, which version of Dompdf are you using?

**Comment by vipinjunior** [comment]
Its not working, someone please help me with this, not able to print rupee symbol in PDF

**Comment by virenderidsg** [comment]
<span style="font-family: DejaVu Sans;">&#x20A6;</span>

its work try this
