### ISSUE TITLE
Bootstrap panel heading background color half coloring

### ISSUE THREAD

**Issue by metallurgical** [dompdf/dompdf#1130]
View on page :

![panel1](https://cloud.githubusercontent.com/assets/6198891/13388585/25384ad6-defc-11e5-8b83-90b6f5528a7d.PNG)

After converted into pdf :

![panel2](https://cloud.githubusercontent.com/assets/6198891/13388617/6e2abd5a-defc-11e5-843b-d66e7229c548.PNG)

#### Working Environment

1) DomPDF : 0.7.x@beta
2) Bootstrap Framework : Bootstrap v3.3.5

Am include Stylesheet using external css. Is there any workaround on this?

**Comment by bsweeney** [comment]
There's a bug in border radius rendering if values are not applied to the bottom corners, see my comment on issue #374. The workaround for the issue is to add a 1px border radius to the other corners.

**Comment by metallurgical** [comment]
Problem fixed now. Did't find for the existing issues provided. Anyway, thanks. I'm closing this issues now
