### ISSUE TITLE
Text change Colspan width?!?

### ISSUE THREAD

**Issue by Colwidth** [dompdf/dompdf#1131]
Hello :)

First i will show you two screenshots.

![wtext](https://cloud.githubusercontent.com/assets/17568761/13426791/1841dd60-dfb0-11e5-9d70-69e3c194f471.PNG)

![itext](https://cloud.githubusercontent.com/assets/17568761/13426794/21f3f974-dfb0-11e5-921c-fc3f727add27.PNG)

In the first screenshot, all column widths are as they should be.
But when i writing a text in a column with colspan it change the widths of the original columns. See picture 2.
What i am doing wrong ... or is it a Bug? What can i do to fix it?

**Comment by bsweeney** [comment]
It would help to see a sample of the HTML you used so we can check the output ourselves.

**Comment by Colwidth** [comment]
Oh sure sry :/

`<html>   
 <head>
  </head>
  <body>
    <table border="0" cellpadding="0" cellspacing="0">
        <col class="col0">
        <col class="col1">
        <col class="col2">
        <col class="col3">
        <col class="col4">
        <col class="col5">
        <tbody>
          <tr class="row0">
            <td class="column0" colspan="5">test</td>
            <td class="column5"></td>
          </tr>
          <tr class="row1">
            <td></td>
            <td colspan="2"></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr class="row2">
            <td></td>
            <td colspan="2"></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </tbody>
    </table>
  </body>
</html>`

In class row0,1,2 are the line-height and height.
In the col tag classes are the width of each column. In this case:
col0 width:9% 
col1 width:23% 
col2 width:17% 
col3 width:33% 
col4 width:7% 
col5 width:11% 

I tried already px and pt. The result is the same. :(

**Comment by bsweeney** [comment]
dompdf definitely needs some work in relation to sizing table cells. In the meantime, since you have a set table widths you could style your table with a fixed layout, e.g. `table { table-layout: fixed; }`.

**Comment by Colwidth** [comment]
@bsweeney 
Thx for your answer. I insert the property without any effect :(

**Comment by bsweeney** [comment]
This should be addressed with the most recent release thanks to significant improvements to how column width is apportioned.
