### ISSUE TITLE
broken_image.png not being found

### ISSUE THREAD

**Issue by ThomasLandauer** [dompdf/dompdf#1133]
I'm getting
````
Warning: getimagesize(/../../res/broken_image.png): failed to open stream: No such file or directory
````
I guess the cause is in `dompdf\dompdf\src\Dompdf\Image\Cache.php`, line 37:
`public static $broken_image = "/../../res/broken_image.png";`

But I couldn't figure out the correct path :-(

BTW: The image is located at `dompdf\dompdf\lib\res\broken_image.png`

**Comment by bsweeney** [comment]
All kinds of errors coming in on your installation. I'm not sure what's going on here.

**Comment by ThomasLandauer** [comment]
OK, thanks, just tell me if I can help!

**Comment by ThomasLandauer** [comment]
As you presumed, this was depending on the composer issue in #1132. I'm closing this. @bsweeney Thanks for your help!
