### ISSUE TITLE
unique demo  is failed

### ISSUE THREAD

**Issue by mani95lisa** [dompdf/dompdf#1134]
![image](https://cloud.githubusercontent.com/assets/1968989/13519362/09d78de2-e212-11e5-8f19-98d358478733.png)

**Comment by bsweeney** [comment]
It's true, but I don't expect we'll be updating that. The Unicode demo relies on a font not installed on that system. Plus the web content included with dompdf is going away (possibly to be resurrected in the [utils project](https://github.com/dompdf/utils)).
