### ISSUE TITLE
Fatal error: Call to a member function getFontMetrics() on null in /dompdf/dompdf/src/FrameReflower/Text.php(453) : runtime-created function on line 1

### ISSUE THREAD

**Issue by jewei** [dompdf/dompdf#1136]
In dompdf/dompdf/src/FrameReflower/Text.php` line 447:

```
array_walk(
    $lines,
    create_function(
        '&$val,$str',
        '$val = $this->getFontMetrics()->getTextWidth($str, "' . $font . '", ' . $size . ', ' . $word_spacing . ', ' . $char_spacing . ');'
    )
);
```
You forgot to use `$root = $this;` or even better if you update it to look like the rest:

```
$root = $this;
array_walk($lines, function(&$val, $str) use ($font, $size, $word_spacing, $char_spacing, $root) {
    $val = $root->getFontMetrics()->getTextWidth($str, addslashes($font), $size, $word_spacing, $char_spacing);
});
```

And there is 2 switch control structures. I suppose they are duplicated, maybe of them are deprecated.

**Comment by bsweeney** [comment]
The two switch structures have always been there. They're not duplicated; the first block gets the min width, the second block gets the max width. The coding style is maybe prone to error. I'll have to walk back through the history to see why that one instance of `array_walk` is different.

**Comment by bsweeney** [comment]
I'm unable to reproduce the error in the latest code. Do you have some sample HTML I can use for debugging? Also, which version of dompdf?

**Comment by bsweeney** [comment]
I believe the different implementation of `array_walk` are entirely accidental. Looks like the code was partially updated in the middle of [another update](https://github.com/dompdf/dompdf/commit/611befe5030a7547913450a3b77b04a30462b576#diff-c46988f4cee921cdc58627cf25a89776). So far as I can tell, this also resulted in the unnecessary (and potentially buggy?) inclusion of `addslashes` in the function definition.

**Comment by bsweeney** [comment]
Note: issue would appear when text styled `white-space: pre-wrap;` was contained within a table.

**Comment by jewei** [comment]
Thanks. Sorry, I wasn't able to response earlier. 6880289975e0ae14289bd26fe97bfa0dd74c5a78 seems like a good fix. Well done!
