### ISSUE TITLE
Empty spaces at the end of line

### ISSUE THREAD

**Issue by simison** [dompdf/dompdf#1143]
I get extra empty space (red arrows) at the end of every line which is followed by new line:
![image](https://cloud.githubusercontent.com/assets/87168/13601520/62224684-e539-11e5-899b-f4519409a42b.png)

This causes problems if I want to set `text-align: right` to a multi line block:

![image](https://cloud.githubusercontent.com/assets/87168/13601553/9af89a94-e539-11e5-9402-724a4a1d8347.png)

Sample html:

``` html
<!DOCTYPE html>
<html>
<head>
  <title>demo</title>
  <style>
  * {
    font-size: 20px;
    line-height: 20px;
  }
  td {
    padding: 5px;
    border: 1px solid gray;
  }
  </style>
</head>
<body>
  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed posuere interdum sem. Quisque ligula eros ullamcorper quis, lacinia quis facilisis sed sapien. Mauris varius diam vitae arcu.</p>
  <p>Problem<span>occurs</span></p>
  <table style="width:200px;">
    <tbody>
      <tr>
        <td style="text-align:right;">Text aligned to right and multiple lines</td>
        <td>Short no prob</td>
      </tr>
    </tbody>
  </table>
</body>
</html>
```

A hacky fix is to add this:

``` php
$fix_text = $frame->get_text();
$frame->set_text( ' ' . rtrim($fix_text) );
```

To [this line](https://github.com/dompdf/dompdf/blob/master/src/FrameReflower/Text.php#L333), but then I get extra space in front of every new tag:

![image](https://cloud.githubusercontent.com/assets/87168/13601602/f6e94830-e539-11e5-954a-0af0ebf05196.png)

Pay attention to purple "problem occurs" line, html shouldn't give any spaces:

``` html
<p>Problem<span>occurs</span></p>
```

Any ideas how to fix in non-hacky way? :-) Could I sniff if the line has `text-align: right` style and apply this fix only then? How?

Thanks!

**Comment by bsweeney** [comment]
A problem [we are familiar with](https://github.com/dompdf/dompdf/blob/v0.7.0-beta3/src/FrameReflower/Text.php#L294). Unfortunately I don't really have a solution right now.

**Comment by Mellthas** [comment]
I think this is sufficiently addressed by now.
