### ISSUE TITLE
Composer instructions in Readme fail

### ISSUE THREAD

**Issue by twisty** [dompdf/dompdf#1145]
Instructions for installing the latest beta were changed in e3d1b4f.

When I try `composer require dompdf/dompdf:0.7.x@beta3` it fails with:

    Could not parse version constraint 0.7.x@beta3: Invalid version string "0.7.x@beta3"

However, using `composer require dompdf/dompdf:0.7.x@beta` resolves to `0.7.0-beta3` and installs correctly.

I don't think `@beta3` is a valid composer [stability flag](https://getcomposer.org/doc/04-schema.md#minimum-stability)?

My `composer --version` is:

    Composer version 1.0-dev (e8abc90b923250527a2d68712b663f0f41790594) 2016-03-09 11:44:27

**Comment by bsweeney** [comment]
Yes, sorry. I didn't mean to leave that so long (see #1132). Try `composer require dompdf/dompdf:v0.7.0-beta3`.

**Comment by twisty** [comment]
Will do, thanks.
