### ISSUE TITLE
Cannot authenticate to install fonts or access setup

### ISSUE THREAD

**Issue by maartenmachiels** [dompdf/dompdf#1146]
Hi

I'm using the latest stable version of DomPDF (v0.6.2) on a Linux server with PHP Version 5.6.18.
My webproject is running as a FastCGI-application.

I've defined a login name and password in my dompdf_config.custom.inc.php and I have added my IP-address to the list of accepted domains in head.inc.

Everytime I try to access the setup or try to install new fonts via the web interface, I am prompted for my login name and password, but they do not take. Authentication fails each time. I've tried multiple password/loginname combinations, tried to only define them in dompdf_config.inc.php, tried to leave it empty, but authentication fails each time.

What is wrong?

**Comment by bsweeney** [comment]
The authentication functionality relies on HTTP basic authentication, but this authentication scheme doesn't seem fully compatible with PHP when run via FastCGI ([ref google](https://www.google.com/search?q=fastcgi+%24_SERVER["PHP_AUTH_USER"])). Looks like maybe you can use [this code from symfony](https://github.com/symfony/symfony/blob/v3.0.3/src/Symfony/Component/HttpFoundation/ServerBag.php#L46), but it does require modification of your site's .htaccess as well.

The www site is no longer available as of dompdf 0.7.0 so we won't be producing a patch for the issue. If we resurrect the code in the [utils project](/dompdf/utils) I'm thinking it might be easier to deal with this by migrating to session-based authentication.

**Comment by bsweeney** [comment]
Have you tried using the `@font-face` CSS declaration instead to install fonts?

**Comment by maartenmachiels** [comment]
Hi, thanks for your answer. Yes, I've tried several times to use @font-face, but to no avail. I've found a workaround with the script of Ejaz here http://stackoverflow.com/questions/12581156/custom-fonts-for-dompdf (last answer). 

Now the issue I'm tackling is the font-quality. They seem to be a little rough. I had to convert my OTF font to TTF, maybe the quality loss is in there...

**Comment by bsweeney** [comment]
I'm not sure about the quality of the conversion. Try a simpler document first to see if that helps. There have been some situations in the past where the output appears to be fuzzy depending on the elements in the PDF.

If you can upload the font you're using we can test it out as well. Or you can use php-font-lib to browse inspect the TTF.

**Comment by maartenmachiels** [comment]
Thanks Brian

I have changed the font now to a Google font. Seems to work better.

Op do 10 mrt. 2016 om 18:13 schreef Brian Sweeney <notifications@github.com
