### ISSUE TITLE
Can't find autoload files 

### ISSUE THREAD

**Issue by harli91** [dompdf/dompdf#1148]
`Warning: require_once(...dompdf/lib/php-font-lib/src/FontLib/Autoloader.php): failed to open stream: No such file or directory...`

**Comment by bsweeney** [comment]
How did you get dompdf? If you're not using composer we recommend the packaged release. The dompdf source from github does not include any external dependencies.

Related: you only need to use the dompdf/autoload.inc.php file if you're using the packaged release. If you're using composer just use its autoloader.
