### ISSUE TITLE
Self-registered protocols are not supported (images)

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#115]
_Original author: magical (December 13, 2009 01:55:51)_

<b>What steps will reproduce the problem?</b>
1. Make an html document with an image on a self defined protocol, ie
&lt;image src=&quot;site://123/image.png&quot;/&gt;
2. Generate

<b>What is the expected output? What do you see instead?</b>
Should work, instead generated PDF is corrupted and a bunch of errors are
generated (Cannot use a scalar value as an array in
lib/class.pdf.php:597~660~674)

<b>What version of the product are you using? On what operating system?</b>
trunk (r207)

<b>Please provide any additional information below.</b>
Hacked functions.inc.php to add &quot;site://&quot; protocol in build_url.

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=108_

**Comment by bsweeney** [comment]
closing in favor of #2826 (same request against the current code base)
