### ISSUE TITLE
dompdf_config.inc.php not downloaded in plugin dompdf plugin 

### ISSUE THREAD

**Issue by hardie7** [dompdf/dompdf#1150]
Hi I have download dompdf plugin but I am didn't got "dompdf_config.inc.php" file in dompdf folder. And now it give error in require_once, So please suggest.

**Comment by themao** [comment]
@hardie7 which version did you download? It doesn't seem to have this file in 0.7.0-beta3 and it's still running properly for me

**Comment by preetamverma128** [comment]
its not working for me as well. same error

**Comment by bsweeney** [comment]
@preetamverma128 dompdf_config.inc.php is no longer part of Dompdf as of version 0.7.0. Please check out the [readme](https://github.com/dompdf/dompdf/blob/master/README.md) and the [usage page](https://github.com/dompdf/dompdf/wiki/Usage) on the wiki. If you're still having issues you should probably head over to the [support forum](http://groups.google.com/group/dompdf) to discuss the problem.

**Comment by sudhi112** [comment]
Hi I have download dompdf plugin but I am didn't got "dompdf_config.inc.php" file in dompdf folder. And now it give error in require_once, So please suggest.

**Comment by bsweeney** [comment]
@sudhi112 we would need more information about the error, Dompdf version, how your system is configured ...

Also, probably should open a new issue or (preferably) head over to the support forum.
