### ISSUE TITLE
Transparent background of PNG goes black

### ISSUE THREAD

**Issue by czechmilk** [dompdf/dompdf#1154]
Using 0.6.2, running on server with [this PHP configuration](https://github.com/dompdf/dompdf/files/181254/domdpdfissueserverno2phpconf.pdf). Transparent background of any PNG picture goes black:
![blackpngscreen](https://cloud.githubusercontent.com/assets/17947504/13904801/a4a39478-eeac-11e5-9de2-228e3855ab99.png)

I tested several transparent PNGs (24 bit RGB). However, the same result.

Surprisingly [PNG file](http://pxd.me/dompdf/www/test/images/png/rgb8_t_bk.png) grabbed from examples page works like a charm:
![correctpngscreen](https://cloud.githubusercontent.com/assets/17947504/13904811/f5f4a25e-eeac-11e5-852c-6d22fd4f6c7a.png)

Furthemore everything works well on server with [this PHP configuration](https://github.com/dompdf/dompdf/files/181253/domdpdfissueserverno1phpconf.pdf).

**Comment by bsweeney** [comment]
More than likely an IMagick (since it's disabled in the second configuration). Also see #432, which would indicate that this isn't an entirely new problem. Can you upgrade ImageMagick?

**Comment by czechmilk** [comment]
@bsweeney, thank you for you suggestion.Upgrading ImageMagick is not possible. Because Imagick 3.2.0RC1 is the most recent version for Linux Debian(Jessie).  I have also tried disabling Imagick. The same result.

**Comment by bsweeney** [comment]
So are your two configurations on separate servers (I was thinking it was different configurations on the same server)? Could maybe be a GD problem, then? It'll be difficult to resolve unless we can duplicate the issue. Can you upload the image causing problems?

**Comment by czechmilk** [comment]
You are right. Two separate servers. I am moving the PHP project from one to another. This issue occurs on the second server with PHP 5.6. I have also think it is a GD problem but I've upgraded GD lib to 2.4.2 and no luck.

There are few pictures causing problems:
[Image No. 1](https://cloud.githubusercontent.com/assets/17947504/13924050/1d10db88-ef83-11e5-9204-6ae175d95733.png)
[Image No. 2](https://cloud.githubusercontent.com/assets/17947504/13923978/e14b1f96-ef82-11e5-8bc8-1625eaeaa03f.png)
[Image No. 3](https://cloud.githubusercontent.com/assets/17947504/13923979/e14c062c-ef82-11e5-838b-a7c9bf9b32cd.png)

I do not why, but [PNG](http://pxd.me/dompdf/www/test/images/png/rgb8_t_bk.png) from DOMPDF examples works correctly. So there must be a difference in a way how the image is made.

**Comment by bsweeney** [comment]
I'm able to render those images correctly.

For reference the relevant version info on my system is:

 - PHP: 5.4.42
 - GD: 2.1.0
 - libPNG: 1.2.46
 - IMagick: 3.1.0RC2
 - ImageMagick: 6.6.9-7 2014-03-06 Q16

**Comment by bsweeney** [comment]
Closing due to lack of follow-up.
