### ISSUE TITLE
Port Number in remote image URL causes "Image not found or type unknown"

### ISSUE THREAD

**Issue by stemithy** [dompdf/dompdf#1156]
I spent quite some time troubleshooting the "Image not found or type unknown" error message on my local dev environment to discover in the end it was due to the image URL containing a port number:
https://localhost:8080/image.png...  I forwarded the port to 443 so I wouldn't have to include the port number in the URL and tada!  I don't know if there is a "fix" in this experience or maybe a foot note in the documentation.  In any case, dompdf is a great app and I appreciate the work that went into creating it.

Thanks,

**Comment by bsweeney** [comment]
I'm not seeing a similar issue using just `http://`. Without more testing I couldn't say if the issue were due to the way dompdf handles URLs or if there's an issue with the way PHP fetches `https://` content from non-standard ports.

Which version of dompdf and PHP are you using?

**Comment by stemithy** [comment]
I tried http with the same result.  Dompdf 0.7-Beta3; PHP 5.4.42

Thanks,
Stephen

**Comment by ayyobro** [comment]
bump

**Comment by simonberger** [comment]
Can you please make sure there is no problem with your server rendering the PDF to access this file using the functions `curl` and `file_get_contents`.
I didn't notice a general problem in the implementation. Both functions are getting the complete uri and are able to handle it.

**Comment by stemithy** [comment]
I wish I could.  When the issue was occurring, it was on a vagrant box that has since been destroyed.  It’s completely plausible that something about that box’s provisioning had something to do with my issue.  I haven’t since attempted to use dompdf on a URI with a port number, but I’ve had absolutely no problems in production.  I’m in full agreement if you want to close this one as an environment anomaly, and I sincerely appreciate all your help.

Thanks,
Stephen

**Comment by bsweeney** [comment]
Yeah, I think it's ok now. Could have been broken before but hard to say without more detail. If anyone happens to find a breaking case feel free to update this issue.

**Comment by unmecduweb** [comment]
I got the same issue and cannot access to any image from localhost with port number 8000. 

Exemple 
 - http://localhost:8000/myimage.png does not work
 - http://localhost/projectfolder/myimage.png works

Thanks

**Comment by kgaut** [comment]
Same issue for me here too.
Using php 7.0, no problem when using the port 80 but got
`Image not found or type unknown` when using the same website on port 8000

**Comment by bsweeney** [comment]
Can you share an example of the URL string you're using? I've not been able to reproduce the issue.

**Comment by stemithy** [comment]
Brian:

I submitted this a LONG time ago.  I’m not sure that it is even a problem any longer.  However at the time, I was trying to get this to work with a local dev box using domains such as http://localhost:8000 and https://localhost:8080.  I hope this helps, but as far as I’m concerned you can close it.

Thanks,
Stephen
