### ISSUE TITLE
Call to undefined method Cpdf::setLineTransparency()

### ISSUE THREAD

**Issue by KosherHotDog** [dompdf/dompdf#1157]
When attempting to create a pdf this error crops up.

> Fatal error: Call to undefined method Cpdf::setLineTransparency() in public_html/Agents/dompdf/src/Adapter/CPDF.php on line 452

Tag structure is as follows

``` html
<html>
  <body style='margin-top:80px;margin-left:80px;margin-right:80px;font-size:10px;'>
    <p><!-- 20 or so of these --></p>
  </body>
</html>
```

What could be causing this error?

**Comment by bsweeney** [comment]
I'm not entirely sure. The method exists and so you shouldn't be getting that error. There have been cases where a file was mangled during installation (such as from a bad ZIP or file extraction). First thing to try would be to download a fresh copy and see if that helps.

**Comment by KosherHotDog** [comment]
i have downloaded a fresh copy and it still gives me that error. this only started happening about 3 days ago.  it was working fine up until then.

**Comment by bsweeney** [comment]
How did you download? Did the issue show up after an update?
