### ISSUE TITLE
[ question ] dompdf  something similar to fpdf  Set xy ? ?

### ISSUE THREAD

**Issue by a-moses** [dompdf/dompdf#1163]
in dompdf their is something similar to fpdf Set xy ? 

````
 $pdf -> SetXY(56, 20);
 $pdf -> text('text'); 
 $pdf ->Output( 'test.pdf);
````

**Comment by bsweeney** [comment]
dompdf doesn't have exactly that functionality, but if what you want is to place text at a particular position on a page you can use the [Canvas::text method](https://github.com/dompdf/dompdf/blob/v0.7.0-beta3/src/Canvas.php#L260). 

Here's how you would use the method directly in v0.7.0:

```php
$dompdf = new Dompdf();
$dompdf->load_html(''); // empty to create blank page
$dompdf->render();
$font = $dompdf->getFontMetrics()->getFont('DejaVu Sans', 'normal');
$dompdf->getCanvas()->text(56, 20, 'text', $font, 12);
```

Because of the way document are rendered at this time you'll need to render the document first, which can present some issues related to placement. Typically you would work around this using embedded script or (preferably) page scripts.

**Comment by a-moses** [comment]
@bsweeney  
 and with and older version like 0.6.* ?

**Comment by bsweeney** [comment]
It's pretty similar, but the FontMetrics class is static:

```
$dompdf = new DOMPDF();
$dompdf->load_html(''); // empty to create blank page
$dompdf->render();
$font = FontMetrics::get_font('DejaVu Sans', 'normal');
$dompdf->get_canvas()->text(56, 20, 'text', $font, 12);
```

FYI, if you don't need the HTML/CSS rendering capabilities of dompdf (i.e. you just want to manually craft the PDF) you might consider using the CPDF class directly instead of going through dompdf.

**Comment by a-moses** [comment]
@bsweeney  

I'm google CPDF but I find something strange.

Where is the source of CPDF and some documentation  ?

Thank you very much !

**Comment by bsweeney** [comment]
The CPDF library used by dompdf is in the source, you can find it here: https://github.com/dompdf/dompdf/blob/master/lib/Cpdf.php.

We don't really have any documentation for it at this time. CPDF was originally created by a third-party but the related website is no longer available. You can find the original documentation on archive.org.

There also appears to be a [related project](http://pdf-php.sourceforge.net/), but I don't know anything about it beyond the fact that it's based on the same library. The documentation on that site related to the CPDF class is (probably) still relevant.

**Comment by a-moses** [comment]
Wow Thank you ! @bsweeney

**Comment by bsweeney** [comment]
We've talked about splitting off CPDF into it's own project. I think it's likely to happen at some point but it probably won't be until some of the larger issues with dompdf are settled. As far as documentation ... that's a more difficult question. I think for now the best option is to use the R&OS documentation.

**Comment by a-moses** [comment]
Thank you  for your patience.
