### ISSUE TITLE
DOMPDF Doesn't support arabic characters ?

### ISSUE THREAD

**Issue by goldsatish** [dompdf/dompdf#1166]
Dear Sir,

Can you tell to me how can generate pdf with Arabic text.

i am use cakephp2.6 and dompdf07

```
require_once(APP . 'Vendor' . DS . 'dompdf' . DS . 'autoload.inc.php'); 
use Dompdf\Dompdf;
$dompdf = new Dompdf();
$dompdf->load_html(utf8_decode($content_for_layout), Configure::read('App.encoding'));
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
$dompdf->stream();
```

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Creator Supporter List</title>
</head>
<body>
<p >
<h4>Supporter List</h4>
</p>
<p >
<h4>يبشسيب يتبت بلا بلا بيل</h4>
</p>
</body>
</html>
```

please help to me how can fix this issue?

**Comment by bsweeney** [comment]
You should absolutely not use `utf8_decode()` ... it'll completely destroy any non iso-8859 characters.

Have you read over the [Unicode How-To](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo)?

At the very least you should use a font that supports your characters:

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Creator Supporter List</title>
<style>
  * { font-family: DejaVu Sans, sans-serif; }
</style>
</head>
<body>
<p >
<h4>Supporter List</h4>
</p>
<p >
<h4>يبشسيب يتبت بلا بلا بيل</h4>
</p>
</body>
</html>
```

That being said there are still [some issues to work out](https://github.com/dompdf/dompdf/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+arabic), especially around compound characters and RTL directionality.

(ref #712)

**Comment by shadoWalker89** [comment]
@bsweeney why the solution in https://github.com/dompdf/dompdf/issues/712 by t3rep-com was not added in the library ?

**Comment by bsweeney** [comment]
@shadoWalker89 nobody has had a chance to investigate this further. I don't know about "soon" but we will look into fixing the issue.

**Comment by bsweeney** [comment]
Please watch 712 for updates.
