### ISSUE TITLE
text-align justify problem

### ISSUE THREAD

**Issue by kvskkvsk** [dompdf/dompdf#1168]
When set text-align to justify, then appears some spaces in words if use Cyrillic symbols like "Р" or "р".
Also bad situation with apostrophe (’)
![- -1](https://cloud.githubusercontent.com/assets/11290871/14344560/0321378c-fcb1-11e5-86d3-051db299bbf0.jpg)

**Comment by bsweeney** [comment]
Can you post some sample HTML? I believe this should be addressed by commit 003cea083c2fc1416c795fe69dae5aa78d6c9421 (ref #1159).

**Comment by kvskkvsk** [comment]
[source.html.txt](https://github.com/dompdf/dompdf/files/208631/source.html.txt)

**Comment by bsweeney** [comment]
This is addressed in the latest version, see attached.

![v0 7 0-final](https://cloud.githubusercontent.com/assets/485897/14371093/ecda57d2-fd01-11e5-9d22-57ede65aba21.png)

**Comment by kvskkvsk** [comment]
>This is addressed in the latest version:

In your example text-align is LEFT, not JUSTIFY

**Comment by bsweeney** [comment]
Wow, yeah. That's not right. The issue with the odd spacing is cleared up, but the justified text is no longer justified. I think it's probably an issue with how spacing adjustments are defined in PDF documents. We'll fix that up before release.

**Comment by bsweeney** [comment]
OK, so the broken spacing is fixed but the alignment on justified text is still off.

![screen shot 2016-04-08 at 10 54 28 pm](https://cloud.githubusercontent.com/assets/485897/14401384/69b739b4-fdde-11e5-9246-05a9c9c544b2.png)

**Comment by bsweeney** [comment]
Still not great but the changes in commit 311e856 should help with the alignment issues.

**Comment by bsweeney** [comment]
I believe this has been sufficiently addressed in the current release. This must have been addressed while we were working on another issue. If you have time to confirm please do so.
