### ISSUE TITLE
domPDF fails to generate a PDF when the generated page doesn't fit to paper size

### ISSUE THREAD

**Issue by marrch-caat** [dompdf/dompdf#1169]
We now try to use domPDF (the latest 0.7 beta istalled via composer) as a general solution for auto-generating all PDFs (from HTML pages). All our HTML templates for PDFs contain CSS page breaks (via page-break-after) to split them into page without breaking tables and texts etc.
In most cases it works fine. But in some rare cases for some reason the content between page breaks doesn't fit to an A4 page. This causes dompdf to freeze for a long time (more than 60 sec at least) and consume a large amount of memory in process. If we set domPDF to use A3 page size or set up a custom page size that's like A4, but longer :), that works as a workaround, but affects the document layout when it's printed so it doesn't look to be a usable solution.
Do you have any ideas what causes that behavior and how is it possible to fix it? We cannot roll out the domPDF-based solution to production due to that cases.

**Comment by bsweeney** [comment]
Do you have some sample HTML causing the issue? You mentioned tables so maybe related to #98?

**Comment by marrch-caat** [comment]
@bsweeney Thank you for the reference, I'll thoroughly inspect the #98 issue and check if it could help me, then if it won't I'll try to extract a sample HTML to reproduce the problem.

**Comment by marrch-caat** [comment]
@bsweeney Couldn't you please provide me with an email address where I could send the sample that breaks domPDF?

**Comment by bsweeney** [comment]
You can use my one-time upload page:
http://eclecticgeek.com/dompdf/upload/

Password: issue1169

**Comment by marrch-caat** [comment]
@bsweeney Done

**Comment by marrch-caat** [comment]
@bsweeney Do you have any hints on the problem?..

**Comment by bsweeney** [comment]
Looks like you're running into issue #98. In the sample you uploaded you have a container table around the content. Even if you're breaking pages between tables elsewhere this container table will cause an infinite loop. This container doesn't appear to be doing anything beyond adding some padding to the content, which you could easily do using a DIV element.

**Comment by marrch-caat** [comment]
@bsweeney We've fixed all our templates to avoid any page breaks inside TD containers, and now after a week of thorough testing I may approve that the problem is completely solved by the changes.
Thank you for your assistance!

**Comment by bsweeney** [comment]
Glad you were able to work around the issue. Thanks for following up.
