### ISSUE TITLE
Misrepresented horizontal tab-spaces in div with "white-space:pre" & tab-size CSS property.

### ISSUE THREAD

**Issue by jduarter** [dompdf/dompdf#1171]
Hi.

It looks like the "white-space: pre;" CSS property is not completely implemented in the case of TAB (ASCII 9) horizontal spaces.

Tabs are represented as common white-spaces (ASCII 32) when the following example code is used:

`$buf = '<div style="white-space:pre;">'."hi\tthis\tis\ta\ttest.".'</div>';`

I spent some hours analyzing the DOMPDF code to try to look for a solution without success. I also tried using XHTML entities without success (A non-printable character is added instead, the "square").

I guess the problem resides on the last stages when the character widths/positions are calculated. It looks like both characters (white-space and TAB) are being 'reworked' in the same way.

An additional issue could be the fact that "tab-size" CSS property is not implemented as well, but that could be considered secondary as there is no apparent way to add a TAB space yet?

Thanks for everything.

PHP version: 5.6.19-0+deb8u1 (cli)
DOMPDF version: master (0.6.2. stable) branch.

**Comment by bsweeney** [comment]
Going to close in favor of #2871 since the issue has been discussed more thoroughly there. Follow that issue for updates.
