### ISSUE TITLE
Pdf not Downloading with scripts and style effects

### ISSUE THREAD

**Issue by srikanth240369** [dompdf/dompdf#1172]
In my page I want display one mathematical formula it dependent on 
http://cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML

when I include by `<script>` download taking too much time and pdf is not rendering

**Comment by bsweeney** [comment]
dompdf is unable to parse JavaScript, it is solely a HTML/CSS rendering library. if you need JavaScript for your page you'll have to use a headless browser like [PhantomJS](http://phantomjs.org).
