### ISSUE TITLE
Fatal error: Class 'Cpdf' not found

### ISSUE THREAD

**Issue by Surt** [dompdf/dompdf#1173]
With 0.7 beta 3.
I just added ```"dompdf/dompdf": "0.7.x@beta"```  to my composer.json and use it on a file:

```
use Dompdf\Dompdf;

$dompdf = new Dompdf();
$dompdf->loadHtml("Hello");
$dompdf->render();
```

The error is:
```
Fatal error: Class 'Cpdf' not found in /x/vendor/dompdf/dompdf/src/Dompdf/Adapter/CPDF.php on line 190
```

**Comment by bsweeney** [comment]
This is a known issue (see #1132), but so far we haven't been able to determine a cause. So far as I can tell that should work.

For now you can use the following command to get the latest beta:

```
composer require dompdf/dompdf:v0.7.0-beta3
```

Because we're about to release the final 0.7.0 I don't expect we'll try to work out what's going on.

**Comment by Surt** [comment]
Thank you @bsweeney I didn's saw the #1132 
confirmed, requiring the problematic file the beta3 works as expected
```require_once __DIR__ . '/../../../vendor/dompdf/dompdf/lib/Cpdf.php';```

Thank you again. And keep the wonderful work with dompdf!

**Comment by vaajnur** [comment]
update your php to 7 or downgrade dompdf library.
