### ISSUE TITLE
"text-align: right" fails if the text contains multiple white spaces

### ISSUE THREAD

**Issue by adshrc** [dompdf/dompdf#1174]
Hi,

it seems like dompdf adds randomly one (or more) whitespaces at the end of a text container, when its content contains multiple white spaces. I experienced this, while i was creating an invoice template, thus it is impossible to get the lines aligned.

![bildschirmfoto 2016-04-13 um 01 58 07](https://cloud.githubusercontent.com/assets/16599151/14479127/d82a1642-011b-11e6-99ad-c5428f4a57f2.png)

**Comment by bsweeney** [comment]
Using v0.7.0? It could be related to issue #1168.

**Comment by unrl** [comment]
I was using the 0.6.* stable version, i just tested it with the latest version, same issue. 

I figured out, that this only happens if "letter-spacing" has an increased value. Tried it with several fonts, always the same problem. I found a fix by just adding a negative "margin-right" to the text-container.
It could also be fixed by adding white spaces at the beginning, which also causes this behaviour and finally the wanted result :smile:

**Comment by bsweeney** [comment]
Thanks for the follow-up. Looks like we'll need to catch for that possibility when determining the appropriate spacing.

**Comment by fadorator** [comment]
I encountered the same problem in Version 0.8.2:

<img width="710" alt="bildschirmfoto 2018-06-21 um 15 52 44" src="https://user-images.githubusercontent.com/5119250/41723512-97c1b0ee-756b-11e8-81ca-71fa09124e1e.png">

It seems like the space after the last word of each row is visible at the end (first 4 lines in this example). This is easier to see when using a fixed width font, like in the screenshot.
The last row is fine. I also tried removing multiple white spaces, it does not seem related to the problem.

The HTML code for this example:

    <html>
    <head>
    </head>
    <body>
    <div style="background: #c0c0c0; font-family: Courier; font-weight: normal;" align="right">LOOK AT SOME OF THESE TEST VALUES LOOK AT SOME OF THESE TEST VALUES LOOK AT SOME OF THESE TEST VALUES LOOK AT SOME OF THESE TEST VALUES LOOK AT SOME OF THESE TEST VALUES LOOK AT SOME OF THESE TEST VALUES LOOK AT SOME OF THESE TEST VALUES LOOK AT SOME OF THESE TEST VALUES LOOK AT SOME OF THESE TEST VALUES LOOK AT SOME OF THESE TEST VALUES</div>
    </body>
    </html>

**Comment by tobiasrast** [comment]
This problem still exist. Is there any solution coming up?

**Comment by bsweeney** [comment]
I don't think this change so far is quite sufficient. If the text alignment is "justify" instead then the text overflows the containing element.

**Comment by bsweeney** [comment]
Putting this here as much to remind myself as much as anyone else: a text split does not necessarily result in the text after the split moving to the next line unless a line break is forced. A split only indicates where a potential line break will occur. It's not until Dompdf processes the following line that the actual break is inserted. So, we have to be careful when trimming space during line splitting.

When I tried changing how the trim is implemented I was causing this particular issue.

**Comment by bsweeney** [comment]
FYI the "justify" issue looks to be unrelated to this change, though the infinite recursion issue is relevant.
