### ISSUE TITLE
How to print the '₹' in pdf generation

### ISSUE THREAD

**Issue by pavankumarkatakam** [dompdf/dompdf#1175]
Currently im using the package for genertaing the PDF for Invoice, so I want to print the '₹' symbol but when directly copy paste the ₹ symbol in blade it is printing as ?. So how to print special characters in pdf.

Actually im using laravel wrapper for this, check this [issue](https://github.com/barryvdh/laravel-dompdf/issues/207)

**Comment by bsweeney** [comment]
Please read through the Unicode How-To. When using the core fonts (Times, Helvetica, Courier) you only have access to characters represented by Windows ANSI encoding. For anything else you have to supply your own font that supports that character and use an appropriate encoding for your HTML.

Luckily that specific character *is* supported by dompdf using the included DejaVu fonts. Try the following:

```
<p style="font-family: DejaVu Sans, sans-serif;">₹</p>
```
