### ISSUE TITLE
Custom width/height in set_paper leads to memory size exceeded

### ISSUE THREAD

**Issue by jonathan-dejong** [dompdf/dompdf#1176]
Hi,

So as soon as i set a custom size using set_paper (or setPaper for v 7.0, I've tried both versions) the request eats up all memory and throws a fatal error. 

This is a suuuuuupersimple pdf with just one line of text so it's not about the size of the document. 
I've tried setting the sizes as an array `array(0,0,72.20,50.70)`, An array and a second parameter of orientation as well as adding in my own size in the array of default sizes and using that. 

They all throw this error. If I on the other hand set something like "a6" it works just fine. I don't know what else to try.. 

This is the php file it's converting:

```
<html>
    <head>
    </head>
    <body>
        <p><?php echo $user['firstname']; ?> <?php echo $user['lastname']; ?></p>
    </body>
</html>
```

I should mention I have set DOMPDF_ENABLE_PHP to true as well.

**Comment by bsweeney** [comment]
Yes it does. Your dimensions are extremely small. The dimensions for the size array are in PT, with PDF resolution set to 72 PPI (PT per inch). So your page size is defined as 1in by 3/4in. If that's actually the size you want you'll need to remove the margins from the page which are set to 1.2cm, or roughly .5in. That means the page margins are large enough that they'll cause paging all by themselves.

I'd suggest at least getting rid of the margins:

```
<html>
    <head>
        <style>
            @page {
                size: 72.20pt 50.70pt;
                margin: 0px;
            }
            body { margin: 0px; padding: 0px; }
        </style>
    </head>
    <body>
        <p>Joe Cool</p>
    </body>
</html>
```

Probably related to #323, among others. Our catch for infinite-paged content needs a bit more work.

**Comment by jonathan-dejong** [comment]
Ah I see.. I couldn't find anything related to margins in the wiki so I figured there where none.. silly me.

**Comment by bsweeney** [comment]
This layout should be significantly improved in the upcoming release.
