### ISSUE TITLE
Dompdf pdf generating problem getting 110 error

### ISSUE THREAD

**Issue by probircse** [dompdf/dompdf#1178]
Today I am downloading new version of Dompdf. I Used this code below
`require_once 'dompdf/autoload.inc.php';
use Dompdf\Dompdf;
$dompdf = new Dompdf();
$dompdf->loadHtml('hello world');
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
$dompdf->stream();`

But I have getting error to open generate pdf by Dompdf
![error](https://cloud.githubusercontent.com/assets/17059457/14672987/142364f8-071d-11e6-8867-fde81572bf87.jpg)

Anyone please help me

**Comment by bsweeney** [comment]
There's a good chance PHP threw a notice that got caught in the PDF content stream. Try opening your PDF in a text editor, the notices usually wind up above the PDF source.

**Comment by topher00** [comment]
I've got the same problem, even when creating the sample 'Hello World!' from the quick start. 

Strangle i've also got the problem with bold font weight mentioned by mikaser a couple of days ago too.

He is details in the text file, I can't see any errors:

```
%PDF-1.3
1 0 obj
<< /Type /Catalog
/Outlines 2 0 R
/Pages 3 0 R >>
endobj
2 0 obj
<< /Type /Outlines /Count 0 >>
endobj
3 0 obj
<< /Type /Pages
/Kids [6 0 R
]
/Count 1
/Resources <<
/ProcSet 4 0 R
/Font << 
/F1 8 0 R
>>
>>
/MediaBox [0.000 0.000 841.890 595.280]
 >>
endobj
4 0 obj
[/PDF /Text ]
endobj
5 0 obj
<<
/Producer (dompdf <18b08fd> + CPDF)
/CreationDate (D:20160422162614+01'00')
/ModDate (D:20160422162614+01'00')
>>
endobj
6 0 obj
<< /Type /Page
/MediaBox [0.000 0.000 841.890 595.280]
/Parent 3 0 R
/Contents 7 0 R
>>
endobj
7 0 obj
<<
/Length 77 >>
stream

0.000 0.000 0.000 rg
BT 34.016 537.859 Td /F1 12.0 Tf  [(hello world)] TJ ET
endstream
endobj
8 0 obj
<< /Type /Font
/Subtype /Type1
/Name /F1
/BaseFont /dompdf/lib/fonts/Times-Roman
/Encoding /WinAnsiEncoding
>>
endobj
xref
0 9
0000000000 65535 f 
0000000009 00000 n 
0000000074 00000 n 
0000000120 00000 n 
0000000274 00000 n 
0000000303 00000 n 
0000000435 00000 n 
0000000538 00000 n 
0000000665 00000 n 
trailer
<<
/Size 9
/Root 1 0 R
/Info 5 0 R
>>
startxref
791
%%EOF
```

**Comment by bsweeney** [comment]
OK, yeah. There does appear to be an issue here. The font reference is wrong,  `/BaseFont /dompdf/lib/fonts/Times-Roman` should be `/BaseFont /Times-Roman`. After fixing that line the PDF displayed as expected for me.

Looks like you're using the latest master. How did you get your copy? Any details on your system specs? Is this an upgrade or fresh copy of dompdf?

(I haven't had a chance to look at #1179 further yet.)

**Comment by topher00** [comment]
Probably explains the issue #1179 in the process.

I'm using  Window Web Server 2008 R2 with PHP 5.5.11. 

It's a fresh install using the download and install method with php-font-lib & php-svg-lib.

I have now installed version 0.6.1 which seems to be working fine.

**Comment by bsweeney** [comment]
@topher00 thanks for the follow-up. I'll take a closer look soon.

**Comment by topher00** [comment]
No problem. All the best

**Comment by bsweeney** [comment]
The problem was an issue with platform-specific directory separators (DS). We tried to improve DS handling with commit adf81af61c89f0be9c091e905ca7c6f1f2398271, but that only exposed further issues. I'm trying a different solution ... hopefully it will prove more robust.
