### ISSUE TITLE
Opens Sans bold doesn't work

### ISSUE THREAD

**Issue by mikaser** [dompdf/dompdf#1179]
I create PDFs with the GoogleFont Open Sans and Source Sans Pro. With Source Sans Pro the font-weight bold works fine. But it doesn't work with Open Sans bold, it's only the font-weight normal. I tested a lot of the sueggestion(`@font-face`, no numeric font-weight, no H1-Tags...) here. Is there a known issue? Or what can I try else? Anyone please help me.

**Comment by bsweeney** [comment]
Have you read through #675? Because Google uses numeric font weights dompdf is unable to parse the font declaration correctly. Probably the best solution for now would be to download the fonts so you can use the named font weights in the `@font-face` declaration.

**Comment by mikaser** [comment]
Yes, I have read and tried it with:
 `@font-face {
          font-family: 'Open Sans Bold';
          src: url('files/Open_Sans/OpenSans-Bold.ttf') format('truetype');
          font-weight: bold;
          font-style: normal;
          }`
But it didn't work.

**Comment by bsweeney** [comment]
It's possible the changes made to address #1178 may have addressed this issue. If you are able to test with the latest code that would be most helpful.

**Comment by summit-web** [comment]
I am also having this issue on a Linux server. I've tried storing it locally without success. I've had to remove all strong tags at the moment so the PDF looks okay. Oh and I'm using the latest full build (and all dependencies).

**Comment by bsweeney** [comment]
@summit-web what's your HTML/CSS look like? Using the TTF version of the font?

**Comment by summit-web** [comment]
I tried tracking down the TTF for Open Sans bold but couldn't manage to it. Posting the HTML wouldn't really help here as it's generated by a PHP script so half of it is PHP variables. Happy to post it with the PHP in place if you think it would help though.

**Comment by bsweeney** [comment]
Dompdf should be fed the bold version of the font by Google if it exists. But if you grab the download from [Google Fonts](https://fonts.google.com/specimen/Open+Sans?selection.family=Open+Sans:400,400i,700,700i) it should give the the TTF files.

FYI, you can get the HTML that dompdf is parsing by calling `$dompdf->output_html()`. The source PHP usually isn't all that helpful for figuring out HTML rendering issues.

**Comment by summit-web** [comment]
Thanks for that link, don't know how I failed to get the TTF before. Odd. I'll give that a go first and if I'm still having issues I'll output the HTML for you. Thanks!

**Comment by jessereynolds** [comment]
fyi this issue also exists when using Open Sans with [redcarpet](https://github.com/vmg/redcarpet).
