### ISSUE TITLE
PDFlib::set_parameter() is deprecated

### ISSUE THREAD

**Issue by bioteck** [dompdf/dompdf#1181]
I use DOMPDF 0.6.2 with PDFlib 9.0.6 and PHP 5.6.15, and I get this error:

```
PDFlib::set_parameter(): Deprecated, use PDF_set_option(), PDF_set_text_option() and PDF_set_graphics_option().
```

This error occured in `include/pdflib_adapter.cls.php`, line 170.

**Comment by bsweeney** [comment]
dompdf hasn't been updated along-side PDFLib and we're quite a few versions behind. We'll see if we can update for the newer version in the near future.

In the meantime I'll update the documentation to indicate the supported release of PDFLib before the final 0.7.0 release.

**Comment by bsweeney** [comment]
This method looks to have been deprecated with PDFLib 9.
