### ISSUE TITLE
Take css from web  

### ISSUE THREAD

**Issue by avi4880** [dompdf/dompdf#1182]
i want to use css from web but it is not working properly. I am using dompdf 6.2

**Comment by bsweeney** [comment]
Do you have a code sample? Is DOMPDF_ENABLE_REMOTE set to true?

**Comment by avi4880** [comment]
yes DOMPDF_ENABLE_REMOTE set is true

**Comment by bsweeney** [comment]
It could be that dompdf has the wrong URI for the CSS file. It depends on how you're loading your HTML document and how the CSS file is referenced.
