### ISSUE TITLE
Rendering lists with counters is incorrect when the list item is pushed to a new page.

### ISSUE THREAD

**Issue by Helenofpern** [dompdf/dompdf#1187]
See atached files for our css and an image of the problem
![list_formating_errorpng](https://cloud.githubusercontent.com/assets/19173267/14991890/79081efc-115b-11e6-9123-cd9695713ee0.png)

Following is the css sample
[scratch_18.txt](https://github.com/dompdf/dompdf/files/247376/scratch_18.txt)

**Comment by bsweeney** [comment]
Can you provide a full HTML example? Also, which version of dompdf are you using?

**Comment by Helenofpern** [comment]
I have check it on your current 7.0 beta 3 and 0.6.2 -- both of which exhibit the problem - As we are using dompdf to render documents from smarty templates it is a little hard to provide just the html that will demonstrate the problem but I will see if I can put something together.

**Comment by Helenofpern** [comment]
Ok here is a full example with php code the pdf shows the problem on page 8 clause 2.37
[Exsample.zip](https://github.com/dompdf/dompdf/files/247450/Exsample.zip)

hope that this helps

**Comment by bsweeney** [comment]
Confirmed with 0.6.2 and 0.7.0.

**Comment by Helenofpern** [comment]
Any idea when this might get looked at?

**Comment by bsweeney** [comment]
Not until after the 0.7.0 release. I can't say when, exactly, but I'll add it to the 0.7.1 milestone. I want to keep the development period on that one shorter.

**Comment by Helenofpern** [comment]
Thanks

**Comment by bsweeney** [comment]
I believe the changes made in the commit above sufficiently address the issue you encountered. If you're still working on this and have time to test that would be appreciated.
