### ISSUE TITLE
When subsetting a font the temp file shall be in DOMPDF_TEMP_DIR

### ISSUE THREAD

**Issue by chtheis** [dompdf/dompdf#1189]
Version 0.6.2, file class.pdf.php, line 2360: A temp. file is created in the fonts dir to hold the used subset. The user may not have the right to write to this directory. So the file shall be created in DOMPDF_TEMP_DIR instead,

**Comment by bsweeney** [comment]
This is addressed by commit eaa6b4f3cb9a779bd9f8ead71bd30427f8e863e1 for the upcoming 0.7.0 release.
