### ISSUE TITLE
Header and Footer on every page

### ISSUE THREAD

**Issue by salacis** [dompdf/dompdf#1190]
Is there a way to put a header and a footer on every page, generated by dompdf?
If I do the following and put the "page-break-after" property on the p element header and footer get split up. Header will be shown on first page, footer on last page.
`<body>`
   `<header>on each page</header>`
         `<main>`
             `<p>page1</p>`
             `<p>page2></p>`
        `</main>`
   `<footer>on each page</footer>`
`</body>`

**Comment by bsweeney** [comment]
To create a header/footer you use fixed position elements. These will appear on every page at the specified position. There's a bit of a quirk in how dompdf parses documents that results in elements appearing on the page on which they're first encountered, so you'll want to put any header/footer content at the top of the document. Also, the header and footer are positioned based on the body element, so to prevent them from overlapping your content you should add extra margin to the page and position the elements into the margin.

Something like the following:

```
<html>
<head>
  <style>
    @page { margin: 100px 25px; }
    header { position: fixed; top: -60px; left: 0px; right: 0px; background-color: lightblue; height: 50px; }
    footer { position: fixed; bottom: -60px; left: 0px; right: 0px; background-color: lightblue; height: 50px; }
    p { page-break-after: always; }
    p:last-child { page-break-after: never; }
  </style>
</head>
<body>
  <header>header on each page</header>
  <footer>footer on each page</footer>
  <main>
    <p>page1</p>
    <p>page2></p>
  </main>
</body>
</html>
```

**Comment by Tapulator** [comment]
One small correction: You want to use a **positive** value for the bottom attribute of the footer element otherwise you won't see it on any page.

So the CSS for the above example would be: `footer { bottom: 60px; }`

**Comment by bsweeney** [comment]
@Tapulator not in dompdf. Content is placed relative to the content area of the page, i.e. the body element. Since the page margins are outside the body element you want to push the header/footer into this space. bottom positioning indicates how far up from the bottom of the containing box you want to be. So using negative margins will shift the content down.

You can see this by making the body element visible (e.g. give it a border ... `body { border: 1px solid red;}`).

Where this would be a problem is if you had no page margins. Because then the header/footer would be pushed outside the visible page area.

**Comment by sandeepreddyg** [comment]
```
use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();
$dompdf->loadHtml('Some html content');

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4');

// Render the HTML as PDF
$dompdf->render();

$font = $dompdf->getFontMetrics()->get_font("helvetica", "bold");
$dompdf->getCanvas()->page_text(72, 18, "Header: {PAGE_NUM} of {PAGE_COUNT}", $font, 10, array(0,0,0));
$dompdf->stream("dompdf_out.pdf", array("Attachment" => false));
```

**Comment by andrescossio** [comment]
footer .pagenum:before {
      content: counter(page);
}
<footer>
            <div class="pagenum-container">Page <span class="pagenum"></span></div></footer>

**Comment by MunkelTrogg** [comment]
I've got a similiar problem.
There are three sections:
<section class="bill">...</section>
<p class="page-break"></p>
<section class="cover">...</section>
<p class="page-break"></p>
<section class="content">
<header style="position:fixed">Header</header>
Very long text (longer than one page)
</section>
Because the text is longer than one page, the header is only shown at the beginning of the section "content".
How can I get it on every page of the content? The header will require PHP, so CSS will probably not help.

**Comment by MunkelTrogg** [comment]
Hi cojocaru3,
as you see above I had a similiar problem. I guess the easiest way to solve this is to generate multiple PDFs (in your case first, main, last) and then merge them with another plugin. It worked well in my situation, I hope it does for yours as well.
A working plugin to merge PDF files can be found here: https://github.com/fheider/pdfmerger
Together with dompdf it works like this: Save the generated files to some folder, then use
`
use PDFMerger\PdfMerge;
$pdf = new PdfMerge();
$pdf->add( 'path/to/first.pdf');
$pdf->add('path/to/main.pdf');
$pdf->add('path/to/last.pdf');
`
Good luck!

**Comment by bsweeney** [comment]
@MunkelTrogg this is a little bit of a late response to your original question, and I see you found a solution, but maybe still helpful. I think maybe you're running into an issue with positioned elements contained in other elements. It's not ideal structurally, but I believe you just need to place your header outside the section so that it will render correctly.

Also, right now dompdf renders fixed-position content starting on the page on which it's encountered. In the future that will likely change, though I'm hoping at the same time we'll add named page support (I think that's what it's called) with some custom enhancements to better define when certain content should display.

@cojocaru3 there's not an easy way of doing this right now. If you can use the merge method suggestions by MunkelTrogg that would work best.

**Comment by lalynescobal** [comment]
![screencapture-localhost-capitol-public-pdf-collections_deposits-2019-02-04-14_53_55](https://user-images.githubusercontent.com/47238953/52193965-be045c00-288c-11e9-8878-beecad68d58e.png)
HOW TO FIX THIS PLS HELP

**Comment by bsweeney** [comment]
@lalynescobal please open a new issue. You'll have to provide detail before I can even begin to guess what's going on.

**Comment by Teasercry** [comment]
Hello everyone, my solution was to make <div id = "header"> like Header for all pages, and content in <main> and footer in <div id = "footer">. After applying css styles, in main write your code, see my example below


`<style media="screen">
  h3 {
    color: #222;
    font-family: 'Open Sans', sans-serif;
    font-weight: 600 !important;
  }

  .center {
    text-align: center;
  }

  th {
    color: white;
    font-size: 10pt;
  }

  .table-bordered,
  td {
    font-size: 8pt;
  }

  li {
    font-size: 10pt;
  }
  table {page-break-before:auto;}
  @page {
      margin: 0cm 0cm;
  }

  /** Define now the real margins of every page in the PDF **/
  body {
      margin-top: 7.1cm;
      margin-left: 2cm;
      margin-right: 2cm;
      margin-bottom: 2cm;
  }

  /** Define the header rules **/
  #header {
      position: fixed;
      top: 1cm;
      left: 0cm;
      right: 0cm;
      height: 5cm;
      margin-left: 2cm;
      margin-right: 2cm;
  }

  /** Define the footer rules **/
  #footer {
      position: fixed;
      bottom: 0cm;
      left: 0cm;
      right: 0cm;
      height: 2cm;
  }
</style>
<div id="header">
  <table border="0" cellpadding="0" cellspacing="2">
  <tr>
    <td colspan="3">
      <p class="center">IBEGESP | VIRTUS</p>
    </td>
  </tr>
  <tr>
    <td width="170" rowspan="3">
      <img src="https://virtus.ibegesp.org.br/img/Logo%20Transparente.png" style=" height: auto;width:100%;" alt="Logo Ibegesp Virtus">
    </td>
    <td style="padding-left: 35pt; padding-top:5pt;" colspan="2">
      <h3><b><?= $calendar['Classroom']['Course']['name_official'] ?></b></h3>
    </td>
  </tr>
  <tr>
    <td width="250" style="padding-left: 65pt;">
      <ul class="list-unstyled">
        <li>
          <b>Data: </b><?= $this->Data->format($calendar['ClassroomCalendar']['initial_date'], ' d/m/Y') ?>
        </li>
        <li>
          <b>Formato: </b><?= $calendar['Classroom']['Format']['name_official'] ?>
        </li>
        <li>
          <b>Cod. Turma: </b><?= $calendar['Classroom']['code'] ?>
        </li>
      </ul>
    </td>
    <td style="text-align:left;">
      <ul class="list-unstyled">
        <li>
          <b>Professor: </b><span style="text-transform: uppercase;"><?= $calendar['Teacher']['People']['name'] ?></span>
        </li>
        <li>
          <b>Local: </b><?= $calendar['Place']['name'] ?>
        </li>
        <li>
          <b>Sala: </b><?= $calendar['Room']['name'] ?>
        </li>
      </ul>
    </td>
  </tr>
</table>
  <table class="table table-bordered table-hover b-bottom">
    <tr style="background-color:#376eb0;">
      <th width="25" class="center">#</th>
      <th width="250">Nome</th>
      <th width="100" class="center">CPF</th>
      <th width="200" class="center">Assinatura</th>
    </tr>
  </table>
</div>
<main>
  <table class="table table-bordered table-hover b-bottom">

  <?php foreach ($matriculations as $i => $matriculation) { ?>
  <tr>
    <td width="25" class="center"><?= $i + 1 ?></td>
    <td width="250"><?= mb_strtoupper($matriculation['PeopleStudent']['name'], 'UTF-8');; ?></td>
    <td width="100" class="center"><?= $matriculation['PeopleStudent']['cpf'] ?></td>
    <td width="200"><span style="color:#fff;">Assinatura</span></td>
  </tr>
  <?php } ?>
</table>
<p align="right" style="padding:10px;">Impresso em: <?= date('d/m/Y'); ?></p>
</main>
<script type="text/php">
  if ( isset($pdf) ) {
    $pdf->page_script('
        if ($PAGE_COUNT > 1) {
            $font = Font_Metrics::get_font("Arial, Helvetica, sans-serif", "normal");
            $size = 10;
            $pageText = "Pagina ".$PAGE_NUM . " / " . $PAGE_COUNT;
            $y = $pdf->get_height() - 20;
            $x = $pdf->get_width() - 15 - Font_Metrics::get_text_width($pageText, $font, $size);
            $pdf->text($x, $y, $pageText, $font, $size);
        }
    ');
}
</script>
`



in my case if i use the body and html tag of the error

**Comment by Gamestarplayer41** [comment]
In dompdf 8.x (probably in all versions) the `<footer>` has to be before the `<main>` tag otherwise it wont render correctly!

**Comment by carlos-mora** [comment]
> ```
> footer .pagenum:before {
>       content: counter(page);
> }
> <footer>
>             <div class="pagenum-container">Page <span class="pagenum"></span></div>
> </footer>
> ```
Is there something similar to this for pagecount?

**Comment by bsweeney** [comment]
@carlos-mora unfortunately not. Due to how Dompdf processes pages we don't know the page count until all the pages have been rendered. The only post-render functionality available right now is performed via page text/script. Could probably hook into that to make this work, but some styling will never be 100% accurate (e.g. right-aligned text) unless we make some architectural changes (e.g. separate layout from actual rendering).

Watch #1636 for updates.

**Comment by bakerstreetsystems** [comment]
I'm using laravel-dompdf to create pdfs within my Laravel app, but I can't seem to get the static headers and footers to work. I'm using Laravel 5.8 and "barryvdh/laravel-dompdf": "^0.8.4", and I've tried the suggestions found above. But even if I literally copy and paste the following (borrowed from here) into my html content, the package will create a pdf with two pages (as expected), but there is no header and the footer just appears once after the last of the content, not at the bottom of each page as expected.

```
<html>
<head>
  <style>
    @page { margin: 100px 25px; }
    header { position: fixed; top: -60px; left: 0px; right: 0px; background-color: lightblue; height: 50px; }
    footer { position: fixed; bottom: -60px; left: 0px; right: 0px; background-color: lightblue; height: 50px; }
    p { page-break-after: always; }
    p:last-child { page-break-after: never; }
  </style>
</head>
<body>
  <header>header on each page</header>
  <footer>footer on each page</footer>
  <main>
    <p>page1</p>
    <p>page2></p>
  </main>
</body>
</html>
```
Am I missing something obvious? Any suggestions? Thanks in advance!

**Comment by punkpette** [comment]
i have 

> I'm using laravel-dompdf to create pdfs within my Laravel app, but I can't seem to get the static headers and footers to work. I'm using Laravel 5.8 and "barryvdh/laravel-dompdf": "^0.8.4", and I've tried the suggestions found above. But even if I literally copy and paste the following (borrowed from here) into my html content, the package will create a pdf with two pages (as expected), but there is no header and the footer just appears once after the last of the content, not at the bottom of each page as expected.
> 
> ```
> <html>
> <head>
>   <style>
>     @page { margin: 100px 25px; }
>     header { position: fixed; top: -60px; left: 0px; right: 0px; background-color: lightblue; height: 50px; }
>     footer { position: fixed; bottom: -60px; left: 0px; right: 0px; background-color: lightblue; height: 50px; }
>     p { page-break-after: always; }
>     p:last-child { page-break-after: never; }
>   </style>
> </head>
> <body>
>   <header>header on each page</header>
>   <footer>footer on each page</footer>
>   <main>
>     <p>page1</p>
>     <p>page2></p>
>   </main>
> </body>
> </html>
> ```
> 
> Am I missing something obvious? Any suggestions? Thanks in advance!

I have the same issue and i'm not able to make it work, why there's no documentation about this?

**Comment by bsweeney** [comment]
Would help to see a sample of your actual HTML+CSS. Rendering the above works fine on the latest release based on my own testing.

**Comment by saikumar-carbanio** [comment]
Can any one help me to include the HTML code while appending header except the first page

`<script type="text/php">
        if ( isset($pdf) ) {
            $pdf->page_script('
            if($PAGE_NUM > 1){
                $font = $fontMetrics->get_font("Arial, Helvetica, sans-serif", "normal");
                $size = 12;
                    $headerText = "_<h3>Dummy Header</h3>_";
                    $pdf->text(100, 100, $headerText, $font, $size);
            }

            ');
        }
    </script>`

coming like "<h3>Header</h3>"

**Comment by bsweeney** [comment]
@saikumar-carbanio if all you need is standard text then you should use standard HTML instead of embedded scripting. Embedded script gives you access to the underlying PDF backend for generating PDF objects manually, not to the HTML rendering engine.

[See this response](https://github.com/dompdf/dompdf/issues/1190#issuecomment-217681844).

**Comment by Boby** [comment]
chipping in, how do we show footer after the 1st page only? I tried using the rendering part and it fails

**Comment by bsweeney** [comment]
@Boby suggest you [start a discussion](https://github.com/dompdf/dompdf/discussions/new) and provide details about what you're tried so far.

**Comment by R-NoTH** [comment]
> Para crear un encabezado/pie de página, utiliza elementos de posición fija. Estos aparecerán en cada página en la posición especificada. Hay un poco de peculiaridad en la forma en que dompdf analiza los documentos que hace que los elementos aparezcan en la página en la que se encontraron por primera vez, por lo que querrá colocar cualquier contenido de encabezado/pie de página en la parte superior del documento. Además, el encabezado y el pie de página se colocan en función del elemento del cuerpo, por lo que para evitar que se superpongan con su contenido, debe agregar un margen adicional a la página y colocar los elementos en el margen.
> 
> Algo como lo siguiente:
> 
> ```
> <html>
> <head>
>   <style>
>     @page { margin: 100px 25px; }
>     header { position: fixed; top: -60px; left: 0px; right: 0px; background-color: lightblue; height: 50px; }
>     footer { position: fixed; bottom: -60px; left: 0px; right: 0px; background-color: lightblue; height: 50px; }
>     p { page-break-after: always; }
>     p:last-child { page-break-after: never; }
>   </style>
> </head>
> <body>
>   <header>header on each page</header>
>   <footer>footer on each page</footer>
>   <main>
>     <p>page1</p>
>     <p>page2></p>
>   </main>
> </body>
> </html>
> ```

bro veridico el truco esta en la posicion del footer gracias por tu sulucion bro.

**Comment by attisan** [comment]
@anyone struggling with header and footer (being only shown on the first page): header and footer tags must be (needed to be in my case) direct children of the `body`.

**Comment by bsweeney** [comment]
@attisan follow #1574 for resolution of that particular issue

**Comment by Bunz80** [comment]
from tests I understood that the structure must be like this
```
         <header>
            {!! $header !!}
        </header>
        <footer>
            {!! $footer !!}
        </footer>
        <main>
            //page 1
        </main>
        <main>
            //page 2
        </main>
```

if i break the table like this
```
<main>
// start table
@php
        $rowIndex++;
        if ($rowIndex % 5 === 0) {
        echo '
        </main>
                <div class="page-break"></div>
        <main>';
        }
@endphp
//end table
</main>
```

i get this error: Call to a member function get_cellmap() on null 
on row  return $pdf->stream();

How do I solve the problem of creating a new page?

**Comment by Bunz80** [comment]
`<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Order Print:{{ $order->number }}-{{ $order->year }}</title>
    </head>
    <body>
        <style>
            body { font-family: \'Nunito\', sans-serif; margin: 0px !important; }
            .row{ width: 100% !important; font-family: Montserrat,Helvetica,Arial,sans-serif; font-weight: 400; font-size:14px }
            .w100{ width: 100% !important; }
            .w50{ width: 50% !important; float:left; }
            .w33{ width: 33.33% !important; float:left; }
            .clear{ clear:both; margin: 2px; }

            .title { font-size:18px; font: bold; color: #000000; margin: 0px; padding: 0px; }
            .text-right{ text-align:right; }
            .footer_terms { position: fixed; bottom: 0px; margin-bottom: 100px;}

            @page { 
                margin-top: 10px; 
                margin-bottom: 10px; 
            }                   
                                
            main { margin-top: 120px; }
            header { position: fixed; left: 0px; top: 0px; right: 0px; height: 80px; text-align: center; margin-top: 20px !important; margin-bottom: 20px; z-index: ; }
            footer { position: fixed; left: 0px; bottom: 0px; right: 0px; height: 80px; }
            #footer .page:after { content: counter(page, upper-roman); }
                
            .page-break {page-break-after: always;}
            .pageNum:before { content: counter(page); }

            tr:nth-of-type(5n) {
                page-break-after: always;
            }
            .tr_grey {
                background-color: #ededed;
            }
            .tr_clear {
                background-color: #ffffff;
            }

            td { vertical-align: top; padding:3px; }
            .td-price { padding-left:10px; padding-right:10px; text-align:right; width:80px; }
        </style>

        <header>
            {!! $header !!}
        </header>

        <footer>
            {!! $footer !!}
        </footer>
        
        <main>
            {!! $delivery !!}
            
            <table>
                <thead>
                    <tr>
                        <th>Codice</th>
                        <th>Prodotto</th>
                        <th class="text-right">IVA</th>
                        <th class="text-right">Quantità</th>
                        <th class="text-right">Prezzo unitario</th>
                        <th class="text-right">Sconto</th>
                        <th class="text-right">Totale</th>
                    </tr>
                </thead>
                <tbody>

                @php
                    $total = $vat = $rowIndex = 0;
                    $priceunit = $tr_style = '';
                @endphp
                @foreach($products as $value)
                    @php
                        $nc = $value->code_company ? 'NC: '.$value->code_company : '';
                        $vc = $value->code_supplier ? 'VC: '.$value->code_supplier : '';
                        $tr_style = $loop->index % 2 === 0 ? 'tr_clear' : 'tr_grey';
                    @endphp
                    @if($value->price_taxable != 0)
                        <tr class="invoicerow {{ $tr_style }}">
                            <td>{{ $nc }} {{ $vc }}</td>
                            <td><b>{{ $value->name }}</b><br>{{ $value->description }}</td>
                            <td class="text-right">{{ $value->tax }}%</td>
                            <td class="text-right" style="padding:3px;">{{ $value->quantity }}{{ $value->unit }}</td>
                            <td class="text-right td-price">{{ number_format((float) ($value->price_unit), 2) }} {{ $value->currency }}</td>
                            <td class="text-right td-price">{{ number_format((float) ($value->discount_price), 2) }} {{ $value->discount_currency }}</td>
                            <td class="text-right td-price">{{ number_format((float) ($value->price_taxable), 2) }} {{ $value->currency }}</td>
                        </tr>
                    @else
                        <tr class="invoicerow {{ $tr_style }} " >
                            <td>{{ $nc }} {{ $vc }}</td>
                            <td><b>{{ $value->name }}</b><br>{{ $value->description }}</td>
                            <td class="text-right td-price"></td>
                            <td class="text-right td-price"></td>
                            <td class="text-right td-price"></td>
                            <td class="text-right td-price"></td>
                            <td class="text-right td-price"></td>
                        </tr>
                    @endif
                    
                    @php
                        $rowIndex++;
                        if ($rowIndex % 5 === 0) {
                            echo '
                            </main>
                            <div class="page-break"></div>
                            <main>';
                        }
                    @endphp

                    
                @endforeach
                </tbody>
            </table>
        
            {!! $terms !!}
        </main>

        
    </body>
</html>`

this is my layout

**Comment by Bunz80** [comment]
this is my layout
```

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Order Print:{{ $order->number }}-{{ $order->year }}</title>
    </head>
    <body>
        <style>
            body { font-family: \'Nunito\', sans-serif; margin: 0px !important; }
            .row{ width: 100% !important; font-family: Montserrat,Helvetica,Arial,sans-serif; font-weight: 400; font-size:14px }
            .w100{ width: 100% !important; }
            .w50{ width: 50% !important; float:left; }
            .w33{ width: 33.33% !important; float:left; }
            .clear{ clear:both; margin: 2px; }

            .title { font-size:18px; font: bold; color: #000000; margin: 0px; padding: 0px; }
            .text-right{ text-align:right; }
            .footer_terms { position: fixed; bottom: 0px; margin-bottom: 100px;}

            @page { 
                margin-top: 10px; 
                margin-bottom: 10px; 
            }                   
                                
            main { margin-top: 120px; }
            header { position: fixed; left: 0px; top: 0px; right: 0px; height: 80px; text-align: center; margin-top: 20px !important; margin-bottom: 20px; z-index: ; }
            footer { position: fixed; left: 0px; bottom: 0px; right: 0px; height: 80px; }
            #footer .page:after { content: counter(page, upper-roman); }
                
            .page-break {page-break-after: always;}
            .pageNum:before { content: counter(page); }

            tr:nth-of-type(5n) {
                page-break-after: always;
            }
            .tr_grey {
                background-color: #ededed;
            }
            .tr_clear {
                background-color: #ffffff;
            }

            td { vertical-align: top; padding:3px; }
            .td-price { padding-left:10px; padding-right:10px; text-align:right; width:80px; }
        </style>

        <header>
            {!! $header !!}
        </header>

        <footer>
            {!! $footer !!}
        </footer>
        
        <main>
            {!! $delivery !!}
            
            <table>
                <thead>
                    <tr>
                        <th>Codice</th>
                        <th>Prodotto</th>
                        <th class="text-right">IVA</th>
                        <th class="text-right">Quantità</th>
                        <th class="text-right">Prezzo unitario</th>
                        <th class="text-right">Sconto</th>
                        <th class="text-right">Totale</th>
                    </tr>
                </thead>
                <tbody>

                @php
                    $total = $vat = $rowIndex = 0;
                    $priceunit = $tr_style = '';
                @endphp
                @foreach($products as $value)
                    @php
                        $nc = $value->code_company ? 'NC: '.$value->code_company : '';
                        $vc = $value->code_supplier ? 'VC: '.$value->code_supplier : '';
                        $tr_style = $loop->index % 2 === 0 ? 'tr_clear' : 'tr_grey';
                    @endphp
                    @if($value->price_taxable != 0)
                        <tr class="invoicerow {{ $tr_style }}">
                            <td>{{ $nc }} {{ $vc }}</td>
                            <td><b>{{ $value->name }}</b><br>{{ $value->description }}</td>
                            <td class="text-right">{{ $value->tax }}%</td>
                            <td class="text-right" style="padding:3px;">{{ $value->quantity }}{{ $value->unit }}</td>
                            <td class="text-right td-price">{{ number_format((float) ($value->price_unit), 2) }} {{ $value->currency }}</td>
                            <td class="text-right td-price">{{ number_format((float) ($value->discount_price), 2) }} {{ $value->discount_currency }}</td>
                            <td class="text-right td-price">{{ number_format((float) ($value->price_taxable), 2) }} {{ $value->currency }}</td>
                        </tr>
                    @else
                        <tr class="invoicerow {{ $tr_style }} " >
                            <td>{{ $nc }} {{ $vc }}</td>
                            <td><b>{{ $value->name }}</b><br>{{ $value->description }}</td>
                            <td class="text-right td-price"></td>
                            <td class="text-right td-price"></td>
                            <td class="text-right td-price"></td>
                            <td class="text-right td-price"></td>
                            <td class="text-right td-price"></td>
                        </tr>
                    @endif
                    
                    @php
                        $rowIndex++;
                        if ($rowIndex % 5 === 0) {
                            echo '
                            </main>
                            <div class="page-break"></div>
                            <main>';
                        }
                    @endphp

                    
                @endforeach
                </tbody>
            </table>
        
            {!! $terms !!}
        </main>

        
    </body>
</html>
```

**Comment by bsweeney** [comment]
@Bunz80 you're producing a significantly malformed document structure here. Something along the lines of the following simplified structure:

```
<main>
  <table>
    <tr>...</tr>
    </main>
    <div class="page-break"></div>
    <main>
    <tr>...</tr>
  </table>
</main>
```

I'm not sure what you're attempting to do here but if you want to break the page at a particular row you could just style the TR with the page-break declaration and completely remove the % 5 logic.

```
<style>
  tr:nth-child(4n) {
    page-break-after: always;
  }
</style>
```

If this needs further discussion I suggest you [start a new topic](https://github.com/dompdf/dompdf/discussions/new).

**Comment by TonyTheFerg** [comment]
Finding that I can only get header and footer on the first page using the example provided in this thread:
`<html>
<head>
  <style>
    @page { margin: 100px 25px; }
    header { position: fixed; top: -60px; left: 0px; right: 0px; background-color: lightblue; height: 50px; }
    footer { position: fixed; bottom: -60px; left: 0px; right: 0px; background-color: lightblue; height: 50px; }
    p { page-break-after: always; }
    p:last-child { page-break-after: never; }
  </style>
</head>
<body>
  <header>header on each page</header>
  <footer>footer on each page</footer>
  <main>
    <p>page1</p>
    <p>page2></p>
  </main>
</body>
</html>`
