### ISSUE TITLE
Release Date for 0.7

### ISSUE THREAD

**Issue by maximebeaudoin** [dompdf/dompdf#1194]
Hi, we are wondering if the version 0.7 will be tagged soon because we need a stable version for this. The latest Beta release was on 21 January so it's was a long time ago.

Thank you !

**Comment by bsweeney** [comment]
I'm hoping by the end of the week. Since putting the code on the master branch a few issues have come up that have delayed release, but I think we've caught up with those. I have one last PR to review and then put together the download.

**Comment by maximebeaudoin** [comment]
@bsweeney Thank you for the quick answer.

**Comment by bsweeney** [comment]
The new release is now up.
