### ISSUE TITLE
PDF size

### ISSUE THREAD

**Issue by kromalski** [dompdf/dompdf#1196]
Im having problem with PDF size, seems like every PDF I try to generate which is > ~9MB fails to render. Below 9MB they generate fine. What can be the problem here? HTML is tables + images.
Even If I try to save it to server and then download it - it just cant be created if > ~9MB

My settings for php are
max_execution_time	300
max_file_uploads	20
max_input_nesting_level	64
max_input_time	180
max_input_vars	1000

Is there anyone who can help me with this issue?

**Comment by bsweeney** [comment]
Have you tried modifying the `memory_limit` PHP setting?

**Comment by kromalski** [comment]
Currently I have memory_limit	2048M, thats high enough, right?

**Comment by bsweeney** [comment]
Yes, should be. Do you have a sample of the HTML that's causing problems? You said it fails to render, but you didn't state whether you receive an error, an empty PDF, or if the script just stops running.

**Comment by kromalski** [comment]
Actually I get, error 500. Here is the sample code:
This is how i generate it (i get some posts from Wordpress). I thought that maybe generating html is giving me 500 so thats why i did refresh and stored html in SESSION
http://pastebin.com/eSQJhhc7

This is how generated html looks like:
http://pastebin.com/JBnPHYPg

This is how styles for PDF generated html look like:
http://pastebin.com/LpqQepmZ

**Comment by bsweeney** [comment]
It's a bit slow to render (about 20 seconds), but my system can handle that document. Which version of dompdf are you using?

500 error typically indicates that PHP had a problem. But if you're not actually seeing the error from PHP then you should either a) enable error logging in PHP and check the log file; or b) temporarily set `display_errors` to true so you can see the error in your browser.

**Comment by kromalski** [comment]
Sorry my bad, that was html which generated PDF under 9MB I've mentioned on my first post.
This is html which gives me 500
http://pastebin.com/0ijRPWEc

Im using dompdf-0.7.0-beta3

Well I've tried to turn display_errors but It wont give me php errors becuase of 500 error (I cant see the errors then).

**Comment by bsweeney** [comment]
That one increased the render time a bit, but the document does still render. It seems likely to be a resource (time or memory) exhaustion issue. It's hard to say which without seeing what exactly is causing the 500 error.

Are you on shared hosting, VPS, self-hosted?

**Comment by kromalski** [comment]
Thanks for some leads, turned out to be memory_limit, when generated needed > 9543616 bytes.
Works well now. Issue to be closed. Thanks

**Comment by bsweeney** [comment]
Thanks for the follow up. I'd like to see us add an option for low-memory installations, which would probably help in a circumstance like this. Though likely at the cost of render time.
