### ISSUE TITLE
2 different results from SVG to PDF ¿?¿?

### ISSUE THREAD

**Issue by baldiri** [dompdf/dompdf#1199]
Hi,

the page created is a simple html with 1 SVG  (hole page) which has an image inside (base 64). On scenario A works ok. On scenario B the result don't show the image inside svg but show the rest of elements that svg has (look attached documents).

Scenario A. 
Ubuntu, PHP Version 5.6.14, Apache Handler php, dompdf 0.7.0, (scotchbox2 + vagrant in my imac)

Scenario B.
Ubuntu, PHP Version 5.5.9, CGI/FastCGI (tested with Apache Handler php and same problem), dompdf 0.7.0, (plesk server, remote ubuntu)

Any ideas please? Maybe any module php? Any php directive? Any idea is welcome!

[A.pdf](https://github.com/dompdf/dompdf/files/275010/A.pdf)
[B.pdf](https://github.com/dompdf/dompdf/files/275009/B.pdf)

**Comment by bsweeney** [comment]
Could be a read/write problem to the temp directory. Or possibly an issue with the image type (possibly an issue with GD).

**Comment by baldiri** [comment]
Hi @bsweeney,

after review php error_log (at scenario B) when i generate pdf, i get quite lines like this one:

mod_fcgid: stderr: PHP Warning:  tempnam(): open_basedir restriction in effect. File() is not within the allowed path(s): (/var/www/vhosts/domain.tld/:/tmp/) in /var/www/vhosts/domain.tld/libs/dompdf/lib/php-svg-lib/src/Svg/Surface/SurfaceCpdf.php on line 161

Maybe is this the problem?

Thanks in advance!

**Comment by bsweeney** [comment]
Definitely the problem. It's a bit of a hack, but you can try modifying the `tempnam()` calls to specify where to write the files, e.g. something like `tempnam(sys_get_temp_dir(), "svg")`.

You also might [post a bug report](https://github.com/PhenX/php-svg-lib/issues/new) to the php-svg-lib project. This should be updated to use `sys_get_temp_dir()` based on [comments in the PHP manual](http://php.net/manual/en/function.tempnam.php#93256).

**Comment by baldiri** [comment]
Hi @bsweeney,

thanks a lot. As you say from [php manual](http://php.net/manual/en/function.tempnam.php#93256), it has solved my problem (i'he put an [issue to php-svg-lib project](https://github.com/PhenX/php-svg-lib/issues/5)).

Thanks!

**Comment by bsweeney** [comment]
Thanks, should be an easy enough fix. I'll leave this open for now as a reminder to double-check dompdf for any similar `tempnam` uses.

**Comment by bsweeney** [comment]
After a quick review I don't believe we're doing this anywhere.
