### ISSUE TITLE
Border radius leaves visual artifact.

### ISSUE THREAD

**Issue by Brandon-McGhee** [dompdf/dompdf#1201]
PHP Version: 5.5.31
Operating System: OS X El Capitan 10.11.4
Dompdf Version: 0.7.0 (stable)

Objects with a border-radius leave a visual artifact on the left side of the object that starts at the middle of the object and continues down to the bottom of the object.

Code to recreate:
![dompdf1](https://cloud.githubusercontent.com/assets/9789736/15487636/eb90a284-2103-11e6-9c09-4f3e3bcaaada.png)
![dompdf2](https://cloud.githubusercontent.com/assets/9789736/15487638/ef53e570-2103-11e6-8a21-83781eff7851.png)

v0.7.0:
![dompdf3](https://cloud.githubusercontent.com/assets/9789736/15487640/f52744ec-2103-11e6-936a-b8b42b0b178b.png)

v0.7.0-beta3:
![dompdf4](https://cloud.githubusercontent.com/assets/9789736/15487651/01c26cf4-2104-11e6-8403-d94f3a99ef36.png)

**Comment by bsweeney** [comment]
This is probably due to the attempted fix for the cross-cut problem from commit f92c8b83f877cd35c87beea47f77530b5b9e7718.

**Comment by bsweeney** [comment]
If you can't wait for 0.7.1 the fix required a *very* minor adjustment to the code (thanks @scotteh).

Modify [CPDF line 3281](https://github.com/dompdf/dompdf/blob/v0.7.0/lib/Cpdf.php#L3281) to replace the `-` with a `+`:

```
$this->addContent(sprintf("\n%.3F %.3F l ", $x1, $y1 + $rBL));
```

**Comment by BillTheGoat** [comment]
Awesome. First bug I found and it was already fixed. The only major issue with domPDF so far is that it is **_hard_** to find! Maybe you should post this on HN and around the web because you are alleviating a monumental headache. Thank you very much!
