### ISSUE TITLE
New font issue

### ISSUE THREAD

**Issue by Al3xR0** [dompdf/dompdf#1204]
I just loaded a new font from the css like this:

    @font-face {
        font-family: "HelveticaNeueLTPro";
        font-style: normal;
        font-weight: bold;
        src: url(/HelveticaNeueLTPro-BdCn.ttf) format("truetype");
    }

In the html version I can see it perfect. When I load pdf, I see strange characters. You have some examples below.

Html version
![a](https://cloud.githubusercontent.com/assets/6364236/15586877/4d884a90-238f-11e6-83ce-b1db633b5ba3.JPG)

Pdf version
![b](https://cloud.githubusercontent.com/assets/6364236/15586854/39953d0e-238f-11e6-91ee-3822d7e7882b.JPG)

What should be the issue? I am using the latest version and the font is original.

If I am copying the text from PDF and paste it in a notepad, the characters are ok.

**Comment by bsweeney** [comment]
Did you resolve the issue?

**Comment by Al3xR0** [comment]
@bsweeney Nope, I just replace the font with another one and it works

**Comment by bsweeney** [comment]
OK. If you want to try to work it out let me know. That's an ... odd ... issue.
