### ISSUE TITLE
where i can find the changelog?

### ISSUE THREAD

**Issue by Julian-B90** [dompdf/dompdf#1207]
I want to update my dompdf but i don´t know wich version i use.

**Comment by bsweeney** [comment]
Post-0.5.x we stopped bundling a change log with the project. The release page covers the most important changes.

If you're using Composer to install this shouldn't be a problem. If you're downloading a packaged release, we didn't include version information until the 0.7.0. So with the packages release:

 - presence of ChangeLog file indicates 0.5.2 or earlier
 - presence of VERSION file indicates 0.7.0 or later (the file contains version information)
 - if neither file is present then you're using a release in the 0.6.x family
