### ISSUE TITLE
How to change font?

### ISSUE THREAD

**Issue by asratnani** [dompdf/dompdf#1208]
i am trouble to change to font when i export data as a PDF.
please let me know as soon as possible how to fix this issues.

**Comment by bsweeney** [comment]
What have you tried? Some sample HTML/CSS would help determine the source of your problem.

**Comment by asratnani** [comment]
I had put this code in dompdf/lib/php-font-lib/www/font_info.php

@font-face {
  font-family: 'Helvetica';
  font-weight: normal;
  font-style: normal;
  font-variant: normal;
  src: url('<?php echo $fontfile; ?>'); 
}

this is enough for ref?

**Comment by bsweeney** [comment]
`$fontfile` is the path to the TTF? In addition you need to add a format attribute to the source:

```
@font-face {
  font-family: 'Helvetica';
  font-weight: normal;
  font-style: normal;
  font-variant: normal;
  src: url('<?php echo $fontfile; ?>') format("truetype");
}
```

**Comment by asratnani** [comment]
Yes $fontfile is path of the ttf font file..
Can you please give me full html ?
Because of i cant getting you..

Thanks bsweeney.

**Comment by bsweeney** [comment]
Something like this should work

```

<html>
<head>
  <style>
  @font-face {
    font-family: 'Elegance';
    font-weight: normal;
    font-style: normal;
    font-variant: normal;
    src: url("http://eclecticgeek.com/dompdf/fonts/Elegance.ttf") format("truetype");
  }
  body {
    font-family: Elegance, sans-serif;
  }
  </style>
</head>
<body>
  <p>hello world</p>
</body>
</html>
```

**Comment by asratnani** [comment]
Thanks .. Let me try this .. i will know you..

**Comment by asratnani** [comment]
i try this but now working yet..
can you join team viewer or skype?
its is good or me if yes..

**Comment by bsweeney** [comment]
A few other things to check:

1. Are you using the latest version of dompdf (currently 0.7.0)?
2. Does dompdf have read/write access to the temporary directory (`DOMPDF_TEMP_DIR` in 0.6.2 or earlier, `$dompdf->set_option('temp_dir', '')` in 0.7.0 or newer)?
3. Are you calling both `$dompdf->output()` and `$dompdf->stream()` in the same script? This can break font rendering.

Might help to see your dompdf-related code.

**Comment by aleksandar-irvas** [comment]
Hi,  I have the same problem with fonts. Also, `<strong>` and `<b>` do not work in pdf.

```
$dompdf = new \Dompdf\Dompdf();
    $dompdf->setPaper("A4");

    //settings
    $options = new Dompdf\Options();
    $options->setIsRemoteEnabled(true);
    $options->setDpi(100);
    $options->setIsHtml5ParserEnabled(true);
    $options->setIsJavascriptEnabled(true);
    $options->setIsPhpEnabled(true);
    $dompdf->setBasePath(get_template_directory() . '/style.css');
    
    $options->setIsFontSubsettingEnabled(true);
    $dompdf->setOptions($options);

    //$dompdf->output();



    // load the html content
    $content = '<!DOCTYPE html><html><head>';
    $content .= '<link rel="stylesheet" src="lib/bootstrap/css/bootstrap.css" type="text/css"/>';
    //$content .= '<link rel="stylesheet" href="'. get_template_directory_uri() .'/style.css" type="text/css" />';
    $content .= '<link rel="stylesheet" src="style.css" type="text/css" />';
    $content .= '<style>';
    $content .= '
    @font-face {
        font-family: "fontbold";
        font-style: normal;
        font-weight: bold;
        src: url("DejaVuSerif-Bold.ttf") format("truetype");
    }';
    $content .= '<div id="header">'. $subtitle . '</div>' . $html . '</body></html>';

    //write to file
//    $myfile = fopen("newfile.html", "w") or die("Unable to open file!");
//    $txt = $content;
//    fwrite($myfile, $txt);
//    fclose($myfile);

    $dompdf->loadHtml($content);
    $dompdf->render();
    $dompdf->setBasePath(get_template_directory_uri() . '/lib/bootstrap/css/bootstrap.csss');
    $canvas = $dompdf->getCanvas();

    $canvas->page_text(28, 10, $title,'', 18, array(0,0,0)); #header
    //$canvas->page_text(28, 35, $solution . ' ' . $feature, '', 10, array(0,0,0)); #header
    $canvas->page_text(28, 800, "Copyright ©2016 GPS Insight", '', 8, array(0,0,0)); #copyright

    $canvas->page_script('
        $pdf->image(get_stylesheet_directory()."/helpcenterlogo.png",487,10,80,35);#logo
        $pdf->line(28,60,567,60,array(0,0,0),1); #header hr
        $pdf->line(28,795,567,795,array(0,0,0),1); #footer hr
    ');

    $canvas->page_text(500, 800, "Page: {PAGE_NUM} of {PAGE_COUNT}", '', 8, array(0,0,0)); #footer

    //$dompdf->setOptions('defaultFont', 'Courier');

    $dompdf->stream($title);
```

**Comment by bsweeney** [comment]
@aleksandar-irvas perhaps your sample was just for demonstration, if that's the case maybe my comments are not on point. If so follow up with a bit more information. First, a few things I noticed about your sample code:

1. You don't need to enable javascript support. That's actually for inserting JS into the rendered PDF.
2. You don't need to enable PHP support. That's only needed if you're running embedded script (e.g. in the body of the HTML you have some php surrounded by `<script type="text/php">...</script>`).
3. The base path works a bit differently from the HTML meta tag. Pass in only a the directory path.

Second, since you're using a DejaVu font you don't need to use an `@font-face` declaration. The `@font-face` declaration is only to load a font that dompdf can then use when rendering your document. To actually use the font you would specify it in a `font-family` declaration (e.g. `body { font-family: DejaVu Serif, serif; }`).

**Comment by aleksandar-irvas** [comment]
Thanks for replay, this was just sample. But I noticed that same code in my localhost bolds `<strong>` attributes, but on the server strong do not work.

**Comment by bsweeney** [comment]
@aleksandar-irvas I would check that dompdf has read/write access to the temp directory, font directory, and font cache directory.

**Comment by cocomo** [comment]
Same problem over here trying to change Helvetica to Avenir:

1. Copied Avenir-Roman.ttf and the rest of the family to dompdf/fonts/. I used TransType to convert the original .ttc to .ttf
2. Added 
`,
        
        
    'Avenir' =>
    	array(
	    	'bold' => $distFontDir . 'Avenir-Medium',
            'bold_italic' => $distFontDir . 'Avenir-MediumOblique',
            'italic' => $distFontDir . 'Avenir-BookOblique',
            'normal' => $distFontDir . 'Avenir-Roman'
    	)`
to dompdf_font_family_cache.dist.php
3. Changed css style definition for body to `Avenir` or `Avenir-Roman`.

Found some advice on StackOverflow, but could not get it to work:

http://stackoverflow.com/questions/12581156/custom-fonts-for-dompdf

2013 is probably outdated? Or do I still need to create the .afm files as advised on stackoverflow?

I want to go after file privileges in temp and font cache directory but dont know where to set these. DejaVu renders fine, I'm using dompdf 0.7.0

**Comment by bsweeney** [comment]
@cocomo just FYI instead of manually setting up the font you can use an `@font-face` declaration or the [load_font.php](https://github.com/dompdf/utils/blob/master/load_font.php) script from the utils projects.

That being said, You do need a font metrics file. AFM is for fonts that use Windows ANSI encoding, UFM is for fonts that use Unicode encoding. For all intents and purposes Dompdf uses only UFM. You *can* get the font metrics using [php-font-lib](https://github.com/PhenX/php-font-lib) or some other font processing tool, but probably the easiest way to get everything set up is to use one of the methods I mentioned above.

**Comment by cocomo** [comment]
@bsweeney Thank you for the clarification, i finally got Avenir showing up with help of the load_font command. Since Avenir has 6 different weights i'm wondering how to set these up für dompdf? Should I create 3 custom font names, each with custom b/i/bi relations, or is there a way to keep the family bundled and to target individual weights in a css style, like `font-weight: 600`?

**Comment by bsweeney** [comment]
Unfortunately Dompdf doesn't currently support numeric weights (see #675). The work around would be, as you stated, to define each weight as a separate family in your stylesheet.

**Comment by lippoliv** [comment]
Hey all,
today I added "GosmickSans" via the ``` load_font.php ``` Script. I checked the ``` dompdf_font_family_cache.dist.php ``` and it was added:

```php
'gosmick-sans' => array(
    'normal' => DOMPDF_FONT_DIR . 'GosmickSans',
    'bold' => DOMPDF_FONT_DIR . 'GosmickSansBold',
    'italic' => DOMPDF_FONT_DIR . 'GosmickSansBoldOblique',
    'bold_italic' => DOMPDF_FONT_DIR . 'GosmickSansOblique',
  ),
```

While returning PDFs Content via an view as HTML, all Looks good, the Font is used. But as soon as I render PDF and open it, the font won't be used?

It's an Laravel-based Project if that is an usefull Information. It's dompdf 0.6.*

**Comment by bsweeney** [comment]
@lippoliv do you have a sample of the HTML?

**Comment by lippoliv** [comment]
@bsweeney here's the HTML (not really pretty, I know)

```html
<!doctype html>
<html lang="de">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>

        <style>
            @page  {
                margin: 0;
                padding: 0;
            }

            td {
                padding: 0;
                spacing: 0;
            }
        </style>
    </head>

    <body style="width: 100%;">
        
        <table>
            <tr>
                
                                    
                    <td>
                        <div style="
    position: relative;
    float: left;
    width: 259px;
    height: 156px;
    margin: 1px;
    padding: 0;
    font-family: gosmick-sans;
">
            <div style="
        font-size: 7pt;
        position: absolute;
        top: 9px;
        left: 15px;
        heigth: 8pt;
        border-bottom: 1px solid #000;
    ">abc</div>
    
    <div style="
        font-size: 11pt;
        position: absolute;
        top: 30px;
        left: 15px;
        margin: 0;
        padding: 0;
    ">
        xyz
    </div>
    <div style="
        font-size: 6pt;
        position: absolute;
        right: 15px;
        top: 30px;
        color: #CCC;
    ">200</div>
</div>                    </td>

                                                </tr>
        </table>
    </body>
</html>
```

**Comment by bsweeney** [comment]
Not pretty is ok ... certainly better for tracking down possible issues ;)

**Comment by lippoliv** [comment]
Here's the font if it helps you analysing (just normal font, not bold etc) [GosmickSans.zip](https://github.com/dompdf/dompdf/files/425185/GosmickSans.zip)

**Comment by bsweeney** [comment]
I don't see anything out of the ordinary, and a quick test seems to work. If you remove absolute positioning does that help? What if you set gosmick-sans globally in your stylesheet, e.g. `* { font-family: gosmick-sans, sans-serif; }`?

**Comment by lippoliv** [comment]
OK @bsweeney you answered it years ago #782

Regarding Laravel I only had to create folder ``` storage/fonts ``` and drop in all font-files and the ``` dompdf_font_family_cache.php ``` because of ``` vendor/barryvdh/laravel-dompdf/config/dompdf.php ``` rewrites the ``` DOMPDF_FONT_DIR ``` 

:+1:

**Comment by bsweeney** [comment]
Nice. I haven't used laravel-dompdf much but it seems to be quite popular. Glad to know it makes font installation easy.

**Comment by mitsest** [comment]
Hey there,
thanks for your plugin!
I 'm trying to include ubuntu font, because I need to support greek characters.

I tried what you suggested with Elegance font
```html
  @font-face {
    font-family: 'Elegance';
    font-weight: normal;
    font-style: normal;
    font-variant: normal;
    src: url("http://eclecticgeek.com/dompdf/fonts/Elegance.ttf") format("truetype");
  }
  body {
    font-family: Elegance, sans-serif;
  }
```

but I can't seem to make my own font to work.
My code is like 
```html
      @font-face {
        font-family: 'Ubuntu';
        font-weight: normal;
        font-style: normal;
        font-variant: normal;
        src: url("http://fonts.gstatic.com/s/ubuntu/v9/sVvvcJDRTINJla2R4XwPVevvDin1pK8aKteLpeZ5c0A.ttf") format("truetype");
      }
      body {
        font-family: 'Ubuntu', sans-serif;
      }
```

Any suggestions?

**Comment by kasra-appscore** [comment]
Non of them worked for me :(

**Comment by bsweeney** [comment]
@kasra-appscore we can discuss your issue over on the [support forum](http://groups.google.com/group/dompdf). Remember to provide details on what you've tried and the results.

**Comment by MauricioGO** [comment]
This work for me.
			```
table {
	border-collapse: collapse;
	border-spacing: 0;
	font-family:Arial!important;
}
```
try to put > !important

**Comment by biancaro** [comment]
@MauriocioGO, you're a life saver. That did the trick. Thanks!

**Comment by thewebdevelopment** [comment]
ہزمح ہزمح ہزمح   font get loaded but this is how it is showing every letter is separated in urdu 
font I am using https://urdufonts.net/fonts/jameel-noori-nastaleeq-kasheeda

Why every letter is separated?

**Comment by bsweeney** [comment]
Dompdf does not currently perform any complext text layout (such as shaping). Follow #2619 for updates. For now you will need to pre-process your text in order for it to

**Comment by asifrashid09** [comment]
i want to filter pdf of filtered data fro my table so i used this query 
 $this->applicantawardsheets = User_Details::where('advertisement_no',$this->advertisement_no)
        ->where('post_applied',$this->post_applied)
       ->get();
but  is not working . because $this->advertisement_no return null.

i watched all tutorials on dompdf but all used ::all() query .

**Comment by bsweeney** [comment]
@asifrashid09 your question appears unrelated and not necessarily a bug. You should [start a new discussion](https://github.com/dompdf/dompdf/discussions/new/choose), though the doesn't really seem specific to Dompdf so it may be better to use a site like [StackOverflow](https://stackoverflow.com).
