### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by paddelboot** [dompdf/dompdf#1209]
I have a very simple piece of DOM that used to display a background image just fine in Dompdf 0.6 Beta:

```
<html>
    <head>

        <style type="text/css">
            html { margin: 0 }
            body { background-image: url( <?php echo $bg_url; ?> ); background-repeat: no-repeat; background-position: center; }
        </style>

    </head>

    <body>
        <p><?php echo $random_text; ?></p>
    </body>

</html>
```

$bg_url is an absolute Url to the image file. 

Here is how I setup Dompdf:

```
$options = new Dompdf\Options();
$options->set( 'isRemoteEnabled', TRUE );

$dompdf = new Dompdf\Dompdf( $options );
$dompdf->set_paper( 'A4', 'portrait' );

$html = $this->get_layout(); // function that includes the above template
$dompdf->load_html( $html );

$dompdf->render();
$output = $dompdf->output();
```

No background image is ever displayed, neither on the body tag any another child element. 

If I echo the $html var directly to the browser, I can see the rendered background image.

What is going wrong?

**Comment by bsweeney** [comment]
Something must have changed in the CSS parsing after the release you're using. Dompdf versions 0.6.2 and 0.7.0 appear to have the same issue. If you tweak your CSS by removing the space before and after the URL it should work fine:

```
body { background-image: url(<?php echo $bg_url; ?>); background-repeat: no-repeat; background-position: center; }
```

**Comment by paddelboot** [comment]
Thanks a lot, seems to be working now.

**Comment by paddelboot** [comment]
While it works fine on localhost, on my remote test server the background image doesn't show up again. 

Any hints where I should start looking? Thanks in advance.

**Comment by bsweeney** [comment]
:/ ... those are the worst problems.

First place I'd check are read/write permissions on the temporary directory, followed by the URL used to access the file (by absolute do you mean it includes the domain?).

**Comment by paddelboot** [comment]
I do not remember having had those issues in the 0.5 release. Is it advisable to use this older version or are there any security issues or something?

Thanks.

**Comment by paddelboot** [comment]
Or is there, in the current version, a useful workaround for using CSS background-image, like absolute positioning and z-index?

**Comment by bsweeney** [comment]
If you want to try and move on by using an older version I'd suggest 0.6.2. It has a number of security fixes. I'm not sure why CSS backgrounds wouldn't work. You could try a fixed-position element with a negative z-index, but you'd have to manually tweak the image positioning because of some vertical alignment issues.

```
<div style="position: fixed; left: 0px; top: 0px; right: 0px; bottom: 0px; text-align: center;z-index: -1000; background-color: brown; border: 2px solid green;">
  <img src="http://eclecticgeek.com/images/macro/ants.jpg" style="width: 100%; margin-top: 25%;">
</div>

<div style="background-color: white; color: black; opacity: .5">
  <p>Hello world.</p>
</div>
```

**Comment by paddelboot** [comment]
I wanted to give it some more tries;

I have moved the temp dir via options to a path within the folder of my app. Still didn't work. On my server, I had a file in this /tmp folder with 0 bytes. Maybe that tells you something?

I tried relative paths to reference the image (../../../), didn't work either. 

Thanks.

**Comment by paddelboot** [comment]
If I add an image tag with the same (working) URL, it doesn't show either in the rendered PDF on the server:

> Image not found or type unknown

I'm a bit at my wits end.

**Comment by bsweeney** [comment]
The zero-byte image could be a write issue or just a left-over from `unlink`ing the file. It might help to see the error being thrown, try setting the global variables `$_dompdf_show_warnings = true;` and `$_dompdf_warnings = [];` before using dompdf.

So how are you loading your HTML document and how are you referencing the image?

**Comment by paddelboot** [comment]
Okay, the problem is:

> file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0

This simply means that remote images are no longer an option, because I will need to deploy this app on different servers where I cannot change the server config. Please correct me if I'm wrong.

So I would have to reference the image with a relative path, which didn't work until now unfortunately. My template file is loaded by a PHP function. I referenced the image both from the folder of the function file aswell as the folder of the template file. No success.

**Comment by paddelboot** [comment]
I have a folder structure:

wp-content/
- uploads
- themes/
-- mytheme/
--- classes/
---- generate/generate.php
--- templates/pdf.php

The template file pdf.php is included by generate.php. The image is under uploads/. So from classes/ (where generate.php is located), that's 3 levels up. But Dompdf doesn't find it.

**Comment by paddelboot** [comment]
This is really confusing, because to tell the truth, I **never** reference images with a relative path other than in my stylesheet. And there, it is always relative to where the stylesheet is located, so there is no issue.

**Comment by bsweeney** [comment]
Ah, yes, sorry. I sometimes forget to check that setting. There are ways to work around the issue if you have cURL enabled. You might try the modification in #1068.

**Comment by paddelboot** [comment]
OK, this seems to be still a problem.

I finally managed to reference the image correctly using a relative path:

/myfolder/mysubfolder/image.jpg

This works well with the CSS background-image property. It does not work with a HTML img tag! Before I invest several more hours, maybe you could tell me what I need to fix in my URLs.

Thanks!

**Comment by BoylesWhite** [comment]
I have the exact same image issue described above and will have to use background images for now. Any suggestions anyone?

**Comment by bsweeney** [comment]
@paddelboot you might look at the discussion in #1233, could be helpful. How are you loading the document? What does the HTML document look like after the PHP code has been parsed?

**Comment by paddelboot** [comment]
I solved the issue by getting the current dir using getcwd(). Then, I included the image relative to this path, i.e. (../../wp-content/uploads/). Still, this does explain why the relative path from the top public folder (i.e. /wp-content/uploads) does not work.

**Comment by bsweeney** [comment]
If you're loading a file from the local file system or using the `loadHtml` method all paths that do not include a protocol+domain are relative to the file system not the site. So a path beginning with a "/" indicates the file system root.

**Comment by bsweeney** [comment]
I believe the issues here are covered in the current stable code. If not post back and we'll take another look.

**Comment by ganefiatri** [comment]
> If you want to try and move on by using an older version I'd suggest 0.6.2. It has a number of security fixes. I'm not sure why CSS backgrounds wouldn't work. You could try a fixed-position element with a negative z-index, but you'd have to manually tweak the image positioning because of some vertical alignment issues.
> 
> ```
> <div style="position: fixed; left: 0px; top: 0px; right: 0px; bottom: 0px; text-align: center;z-index: -1000; background-color: brown; border: 2px solid green;">
>   <img src="http://eclecticgeek.com/images/macro/ants.jpg" style="width: 100%; margin-top: 25%;">
> </div>
> 
> <div style="background-color: white; color: black; opacity: .5">
>   <p>Hello world.</p>
> </div>
> ```

tq somuch this is really help me
