### ISSUE TITLE
setPaper('a4') seems to be ignored

### ISSUE THREAD

**Issue by Max13** [dompdf/dompdf#1213]
I'm from Europe and we're using A4 as default size (in fact, exclusively A4).

Apparently, `Dompdf::setPaper()` seems to be ignored when A4. "seems" because A3 produces a globally smaller content on the screen, but there is no difference on the produced PDF between the default behavior and when set as A4.

Apparently, images and text are bigger than on the `HTML`, and as everything seems to be proportionally bigger, and `setPaper('a4')` on not, the PDF is the same, I assume it's ignored.

I've checked with `0.7.0` and `dev-master`, on `OS X El-Capitan`, `PHP 5.6.22`.
Here is the file on debug platform: http://eclecticgeek.com/dompdf/debug.php?identifier=d84c6bb58942a7dbdbeeecdc50e543f9

Thanks for your help if I've missed something, and great job everyone !

**Comment by bsweeney** [comment]
I don't think it's ignored, but the default page size is "letter" which is pretty close in dimensions to the "a4" size. One thing to keep in mind is that dompdf sizes elements with `box-sizing: content-box`. So if you want to exactly size the container to your page you'll have to subtract margin and padding from the width.

**Comment by Max13** [comment]
When I say "ignored" it's because everything on the PDF seem bigger than expected. It could be (for me at least) related to the fact that contents is shown on smaller "view" which could produce this "zoomed" effect.

Thank you for your answer, but I'm a little bit confused. Dompdf uses `box-sizing: content-box`, which is a rule I don't know so I don't understand what margin/padding have to be subtracted from the width?

Plus, if you saw the HTML, I wrote the page with relative sizes as much as possible, so I don't really need to size the container (the width/height rules are only to show me, as HTML, what is would produce). I've also tried removing them (the body height/width rules), but the PDF produced is still not as expected.

Please explain be the subtraction needed, maybe it will be clearer for me. Thank you.

**Comment by bsweeney** [comment]
[Box sizing](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing) determines how a CSS-compliant user agent determines the width of a block element. When set to "content-box" a defined width defines the content box width. Margin and padding are then added to that to determine the actual width of the element. When set to "border-box" a defined width defines the total width of the element, margin and padding included.

Truth be told, you can address the positioning issue by just removing the width/height from the body styling. It's unnecessary.

As for the sizing, try tweaking the dompdf dpi. This affects the rendering of anything defined using px (this includes the image, which does not have defined dimensions). As for everything defined using em try tweaking the font size.

**Comment by Max13** [comment]
@bsweeney Thank you very much for your answer. What I had to learn is to ignore the `HTML` output, it's confusing. For those who are interested in the changes: http://eclecticgeek.com/dompdf/debug.php?identifier=e03cbe40bf65d39aa09224e37f5e63e6

Thanks.

**Comment by Max13** [comment]
Edited previous messages
