### ISSUE TITLE
tel: Bug

### ISSUE THREAD

**Issue by cocomo** [dompdf/dompdf#1214]
I managed to screw hyperlinks to telephone applications. The following code 

`Tel <a href='tel:00493012345678'>(030) 12 34 56 78</a>`

creates a pdf with a link to the following URL

 `/local/servers/path/holding/the/application/to/create/this/file/tel:00493012345678`

**Comment by bsweeney** [comment]
We current only support a small subset of URIs. We can take a look at what it would take to add support for additional ones. You can try adding the "tel:" to the [build_url helper function]((https://github.com/dompdf/dompdf/blob/v0.7.0/src/Helpers.php#L64).
