### ISSUE TITLE
block element nested in inline element breaks page reflow

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#122]
_Original author: emphatic... (January 18, 2010 15:12:25)_

<b>What steps will reproduce the problem?</b>
1.If my pdf data exceeds 1 page
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
The expected output is that the data should go on next page in pdf. All of
the data that exceeds one page is overlapped on the start of pdf.

<b>What version of the product are you using? On what operating system?</b>
I am using 0-6-0_alpha2

<b>Please provide any additional information below.</b>

I am attaching two files that are being generated. One of them is defective
in which the data is more than one page and it gets overlapped. The another
one is lesser than 1 page and it is perfectly generated

[no defect.pdf](https://github.com/dompdf/dompdf/files/9068043/no.defect.pdf)
[defective.pdf](https://github.com/dompdf/dompdf/files/9068044/defective.pdf)

_Original issue: [http://code.google.com/p/dompdf/issues/detail?id=116](http://web.archive.org/web/20160102042346/http://code.google.com/p/dompdf/issues/detail?id=116)_

**Comment by bsweeney** [comment]
The underlying issue represented by the available sample has been addressed.
