### ISSUE TITLE
Can't find any documentation online

### ISSUE THREAD

**Issue by luigimannoni** [dompdf/dompdf#1220]
Hello,
probably I've missed a link or a page, I've been going around for a couple of days trying to find any documentation for the library.
Is this available somewhere hosted on another site?

Thanks

**Comment by nebrot** [comment]
Here are some informations: https://github.com/dompdf/dompdf/wiki

**Comment by luigimannoni** [comment]
Yes thanks, I have already seen the Wiki, I am referring actually to the following statement:

> For more complete documentation of the Canvas API, see the API documentation.

There's no link to the API nor an article on the Wiki. I am trying to understand some stuff using a debugger I have found here: http://eclecticgeek.com/dompdf/debug.php but helps into a certain extent. 
Wondering if there's an online autogenerated PHPDoc documentation where I can see all the available methods for the library.

**Comment by bsweeney** [comment]
@luigimannoni you are correct. At one point we had more documentation available, but since moving everything to github we have not yet re-created the API documentation. I'm not sure when we'll have that available, but feel free to ask questions on the support forum.

**Comment by bsweeney** [comment]
I have added some basic information about the [API](https://github.com/dompdf/dompdf/wiki/Usage#dompdf-api) to the wiki. Still working on generating full API documentation but I'll add a link in the wiki once it's available.
