### ISSUE TITLE
UTF-8 text in inline PHP gets transcoded to HTML entities

### ISSUE THREAD

**Issue by rovexo** [dompdf/dompdf#1221]
Hey, it seems like currently all HTML passed to loadHtml gets converted to HTML-entities (according to code comments it's a workaround for an encoding bug in DOMDocument). Problem is that **inline PHP blocks also get converted** (like $pdf->text()). So function parameter strings get transcoded and it results in having actual HTML entity text in the PDF output.

**Inline PHP in the HTML page:**

```
<script type="text/php">
$pdf->text(10, 10, 'UTF-8 characters like ß.')
</script>
```

**Result in the PDF:**

UTF-8 characters like &amp;szlig;.

**Reproducing:**
- PHP Version doesn't matter I think
- Release 0.7.0 (or also what's on master and develop at the time of writing)
- Have the option isHtml5ParserEnabled at false

**Regards:**
Dompdf::loadHtml Line 516 (in the current 0.7.0 release).

**Possible solution:**
Somehow don't encode the inline PHP blocks, only the HTML (maybe splitting, encoding the HTML parts and concatenate afterwards).

Or have the text method (and similar ones) decode HTML entities.

By the way, I'm running PHP 5.4.45 and experimented with Dompdf::loadHtml(): I tried passing the non-encoded HTML string to DOMDocument::loadHTML. All characters came out fine in the PDF. Maybe the mentioned issue is done in later PHP version and a PHP version switch comes in handy (unless people start doing workarounds for the workaround).

**Comment by bsweeney** [comment]
Interestingly, this does not happen if you have the HTML5 parser enabled. Which I usually do.

**Comment by bsweeney** [comment]
Ultimately I agree. We don't need the special encoding anymore. The main potential pain point is that if a user does not specify the encoding then DOMDocument will assume it to be iso-8859-1. I tried to modify the logic such that the existing encoding is detected well enough that we can always convert to UTF-8 if the document is not already using that encoding.

The down side to making this change is that it's hard to test all the ways somebody could mess up their document encoding. Hopefully the eventual integration of an improved HTML5 parser will make the encoding-related logic unnecessary.

**Comment by rovexo** [comment]
Cool, thanks for looking into it. I know how much of a pain string encoding is with all these non-utf8 aware functions :)

**Comment by bsweeney** [comment]
Tell me about it!
