### ISSUE TITLE
Unable to use PDFLib Adapter with latest dompdf 0.7.0

### ISSUE THREAD

**Issue by ahgindia** [dompdf/dompdf#1222]
Hello,

I am using DomPDF with PDFLib as backend.
Recently I am trying to upgrade my application to use dompdf from _0.6.0_ to _0.7.0_.
But it is giving exception in following file : 
[src/Adapter/PDFLib.php#L213](https://github.com/dompdf/dompdf/blob/master/src/Adapter/PDFLib.php#L213)
`$families = $dompdf->getFontMetrics->getFontFamilies();`

Exception :

> [Dompdf\Exception, 0] 
> Invalid property: getFontMetrics 

Can you please let me know what is error in this ?

Below is the sample script that I am trying to run :

``` php
<?php
require_once('dompdf/autoload.inc.php');

// reference the Dompdf namespace
use Dompdf\Dompdf;
use Dompdf\Options;

$options = new Options();
$options->set(array(
        'pdfBackend'=>'PDFLib',
        'defaultMediaType'=>'print',
        'defaultPaperSize'=>'A4',
        'defaultFont'=>'arial',
        'enable_html5_parser'=>true,
        'enable_font_subsetting'=>true
));

// instantiate and use the dompdf class
$dompdf = new Dompdf($options);
$dompdf->loadHtml('hello world');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream();
```

Awaiting any reply on this issue,

Thanks & Regards,
Ankit

**Comment by ahgindia** [comment]
To get faster response on this question, I also posted same question on stackoverflow http://stackoverflow.com/questions/38138082/unable-to-use-pdflib-adapter-with-latest-dompdf-0-7-0

But still I am waiting for solution on this. :(

**Comment by bsweeney** [comment]
[Line 213](https://github.com/dompdf/dompdf/blob/v0.7.0/src/Adapter/PDFLib.php#L213) of Dompdf\Adapter\PDFLib should read:

```
families = $dompdf->getFontMetrics()->getFontFamilies();
```

**Comment by ahgindia** [comment]
Hello,
I have already tried that before.
But it gives following fatal error :

 Fatal error: Call to a member function getFontFamilies() on a non-object in dompdf/src/Adapter/PDFLib.php on line 230

Am I missing some configuration related to font path or something ?
Please guide me.

Thanks
Ankit

**Comment by bsweeney** [comment]
The commit I just added to the develop branch should address this issue. I fixed a few issues based on testing with PDFLib Lite 7.
