### ISSUE TITLE
Font Metrics calculates wrong width when using placeholders

### ISSUE THREAD

**Issue by luigimannoni** [dompdf/dompdf#1224]
Let's say I am injecting a page counter in the footer using $pdf->page_text() I would go for something like this: 

``` php
$text = 'Page {PAGE_NUM} of {PAGE_COUNT}';  
$width = $fontMetrics->getTextWidth($text, $font, $size);
$pdf->page_text($w - $width - 200, $y, $text . ' width of this is ' . $width, $font, $size, $color);
```

The result would be that:
![screenshot 2016-06-29 15 23 15](https://cloud.githubusercontent.com/assets/1405327/16455958/1009029c-3e0e-11e6-8e8d-13df0ea1eaec.png)

But if I put a static text, like this:

``` php
$text = 'Page 1 of 10';  
$width = $fontMetrics->getTextWidth($text, $font, $size);
$pdf->page_text($w - $width - 200, $y, $text . ' width of this is ' . $width, $font, $size, $color);
```

I am getting the correct computed width of the text, so I can align it flawlessly to the right margin of the page.
![screenshot 2016-06-29 15 22 49](https://cloud.githubusercontent.com/assets/1405327/16456038/630bcb64-3e0e-11e6-8ad0-7f91d125a335.png)

A (rather ugly) workaround for this would be calculating the width on a fake text:

``` php
$truetext = 'Page {PAGE_NUM} of {PAGE_COUNT}';
$faketext = 'Page 00 of 00';  
$width = $fontMetrics->getTextWidth($faketext, $font, $size);
$pdf->page_text($w - $width, $y, $truetext, $font, $size, $color);
```

That leads me to believe the fontmetrics class is literally taking in consideration the placeholders {PAGE_NUM} and {PAGE_COUNT} when doing the calculations

**Comment by bsweeney** [comment]
That sounds like a reasonable estimation of the problem. I'm not sure that there's a good means of getting a handle on that particular issue since you're manually laying out the text.

For that particular sample a solution on our part would be to support the page count via CSS. Then you wouldn't have to manually lay out the content.

**Comment by luigimannoni** [comment]
Hmm, is there a way to get the total number of pages using the CSS method?

**Comment by bsweeney** [comment]
Unfortunately not at this time.

**Comment by vielhuber** [comment]
Any update on this issue? It seems that it is impossible to align right a simple PAGE_NUM / PAGE_COUNT text.

**Comment by bsweeney** [comment]
I don't have a solution using this method, though I believe you could replace this with a page script and get the desired output. Something like the following should get you what you want:

```
$canvas = $dompdf->get_canvas();
$canvas->page_script(<<<'EOL'
   $text = 'Page ' . $PAGE_NUM . ' of ' . $PAGE_COUNT;
   $font = $fontMetrics->getFont('monospace');
   $page_width = $pdf->get_width();
   $page_height = $pdf->get_height();
   $width = $fontMetrics->getTextWidth($text, $font, 12);
   $pdf->text($page_width - $width - 20, $page_height - 20, $text, $font, 12);
EOL
);
```

I think this is a sufficient solution for the problem so I'm going to close this ticket.

Watch #1636 for updates on support for CSS counter totals.
