### ISSUE TITLE
Erro convert PDF

### ISSUE THREAD

**Issue by Renanh** [dompdf/dompdf#1229]
EXCEL:

![1](https://cloud.githubusercontent.com/assets/8283925/16368338/be4d629c-3c03-11e6-9578-8b73f6b822da.PNG)

PDF:

![2](https://cloud.githubusercontent.com/assets/8283925/16368463/e8dd0746-3c04-11e6-8c2c-4385fc0803d0.PNG)

Code:

```
ob_end_clean();
ob_start();
Excel::load(PATH_EXCEL, function ($file) {

(...)


 })->store('pdf')->download('pdf');
ob_flush();
```

**Comment by bsweeney** [comment]
Can you provide more details?

**Comment by Renanh** [comment]
I am writing in an excel file information returned from the bank. when exporting the model informed in PDF, are breaking.

**Comment by bsweeney** [comment]
This slipped by me, and I see some time has passed. Still need help?
