### ISSUE TITLE
bootstrap.css fonts not support to dompdf ?

### ISSUE THREAD

**Issue by Pravinslk** [dompdf/dompdf#1231]
When i use bootstrap.css i getting this error this is Laravel project how can i solve this issue.

```
ErrorException in Font_Binary_Stream.php line 249:
strftime() expects parameter 2 to be integer, float given
```

**Comment by nebrot** [comment]
See #631

**Comment by Pravinslk** [comment]
head is spinning when i read that link can you tell me what is solution ? @nebrot

**Comment by nebrot** [comment]
I think there is no solution yet ([comment](https://github.com/dompdf/dompdf/issues/631#issuecomment-32036135l)).
Related issue: barryvdh/laravel-dompdf#190

**Comment by Pravinslk** [comment]
if no solution then no need go for that next step ryt ... :) @barryvdh what is the solution for this please dont give any link plz

**Comment by bsweeney** [comment]
Which version of dompdf are you using?

The relevant laravel issue references PhenX/php-font-lib#43 which may address your issue.

**Comment by Pravinslk** [comment]
@bsweeney im using **"barryvdh/laravel-dompdf": "^0.6.1"** but what is the error ? what i want do ?

**Comment by bsweeney** [comment]
The issue is probably that v0.6.1 wasn't correctly limiting itself to the supported font formats  (currently just TTF). There are some other issues as well. You'll have to wait for 0.7.1 to get better support for Bootstrap fonts.

Relevant to #860

**Comment by bsweeney** [comment]
The upcoming 0.7.1 release of dompdf should appropriately support the glyphicons font.
