### ISSUE TITLE
readonly pdf

### ISSUE THREAD

**Issue by ryonnsan** [dompdf/dompdf#1232]
Hi there,

How can I set the generated PDF to be readonly?
I am not sure how

Please help/advise

Thank you

Regards,
Ron

**Comment by bsweeney** [comment]
After you have rendered the document you can set restrictions on it using the Cpdf library. In 0.7.0, after calling the render method call the following:

```
$dompdf->getCanvas()->get_cpdf()->setEncryption('', 'ownerpass', array());
```

The parameters of setEncryption are:

paramter | type   | description
-------- | ----   | -----------
1        | string | user password (restrictions apply)
2        | string | owner password (unlocks document)
3        | array  | strings indicating allowed actions when user password is supplied (e.g. print, copy). If the array is empty the user is limited to saving the document.

[via StackOverflow](http://stackoverflow.com/a/9605270/264628)

**Comment by ryonnsan** [comment]
Hi bsweeney,

Thank you for the response.
It seems to work, however the Open Sans Google font in my PDF disappears if I use this. The text is still there (can be selected, copied and pasted), but there is no visual of the letters.
Is there any workaround to set the PDF to be readonly while keeping the custom font intact?

Please advise
Thank you

**Comment by bsweeney** [comment]
I think this is an old issue we just haven't had a chance to review (#340 may be related).

**Comment by ryonnsan** [comment]
That is unfortunate.
Thank you for informing me about this, bsweeney

**Comment by bsweeney** [comment]
Yes, sorry about that. I'll add this to the 0.7.2 milestone so we at least start looking at it.

**Comment by Morfik** [comment]
Hello

This problem is solved?

**Comment by bsweeney** [comment]
@Morfik the issue around using embedded fonts with a protected document has not yet been addressed.

**Comment by zander009** [comment]
It worked on me but the problem is when I tried to enter my password it says "invalid password"

**Comment by bsweeney** [comment]
@zander009 more details? What version of dompdf? What password are you using?

**Comment by zander009** [comment]
Thank you for the response. I already solved it. The code $dompdf->getCanvas()->get_cpdf()->setEncryption('frogs', '', array('print')); is above the $dompdf->output(); thats why it cant recognized the function. It worked now. Im using ^0.7.0 version.

**Comment by hhh062001** [comment]
How can i remove password protection and keep the encryption?

**Comment by bsweeney** [comment]
@hhh062001 this is an old issue, you can use [discussions](https://github.com/dompdf/dompdf/discussions) to ask questions in the future.

To answer your question, if you want users to be able to open without providing a password just use a blank value.

The following allows users to open a PDF without providing a password (with no assigned rights). If the owner password is supplied the user has full access:
```
$dompdf->getCanvas()->get_cpdf()->setEncryption('', 'adminpass');
```

**Comment by saulsmith21** [comment]
Hello there!
I used the example exactly as you indicated:
$dompdf->getCanvas()->get_cpdf()->setEncryption('guestpass', 'ownerpass', array('print'));
It worked excellent, take ur beer 🍺🍺🍺
Google fonts worked excellent, without problem.
