### ISSUE TITLE
Can't include image using img tags: Image not found or type unknown

### ISSUE THREAD

**Issue by BoylesWhite** [dompdf/dompdf#1233]
Hello, 

I'm having an issue another user had too, it seems to remain unsolved. 

This code is fine:

`<div style="width:80px;height:80px;background-image:url('/wp-content/uploads/2015/11/tv-lic.png');background-repeat:no-repeat;"></div>`

But since background size doesn't work it's not that practical.

This code causes an error of "Image not found or type unknown":

`<img src="/wp-content/uploads/2015/11/tv-lic.png" />`

I have these options set:
```
$options = new Options();
$options->set('defaultFont', 'Courier');
$options->set('isRemoteEnabled', TRUE);
$options->set('debugKeepTemp', TRUE);
$options->set('isHtml5ParserEnabled', true);
$dompdf = new Dompdf($options);
```

Any help or direction is much appreciated. 

Thanks, 

Lewis

Some extra info:
GD all installed and fine. 
Nothing in error log.

**Comment by bsweeney** [comment]
Referring to #1209 ...

How are you loading the image? If you are using `$dompdf->loadHtml()` then the image path will be  based on the file system. Seems unlikely your /wp-content directory is at the root of your drive. You'll need to figure out a way to reference the path relative to the file creating the PDF document, or use a URL that includes the site domain.

If you're using `$dompdf->load_html_file()` the issue could be that the `allow_url_fopen` is not set to true.

**Comment by BoylesWhite** [comment]
Hello, 

Thanks for replying.

I am using:
`$dompdf->loadHtmlFile('pdf.html');`

alllow_url_fopen is set to "on"
allow_url_include is set to "off" though?

In fact here is the full code:

```
<?php // reference the Dompdf namespace
$_dompdf_show_warnings = true;
$_dompdf_warnings = [];
require_once 'autoload.inc.php';
use Dompdf\Dompdf;
use Dompdf\Options;

$options = new Options();
$options->set('defaultFont', 'Courier');
$options->set('isRemoteEnabled', TRUE);
$options->set('debugKeepTemp', TRUE);
$options->set('isHtml5ParserEnabled', true);
//$options->set('chroot', '');
$dompdf = new Dompdf($options);

// instantiate and use the dompdf class
$dompdf = new Dompdf();
$dompdf->loadHtmlFile('pdf.html');


// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'landscape');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream();

?>
```
![screen shot 2016-07-09 at 00 14 01](https://cloud.githubusercontent.com/assets/12235407/16703979/1428fb08-456a-11e6-9f0e-ddcee0d6cc09.png)

**Comment by bsweeney** [comment]
My previous comment wasn't entirely accurate, I updated it.

**Comment by BoylesWhite** [comment]
Thanks for this - it's solved the problem. Much appreciated.

**Comment by bsweeney** [comment]
Glad to hear it.

**Comment by inilabsn** [comment]
#bsweeney Can you post here how it is solved..?

**Comment by bsweeney** [comment]
@inilabsn the answer depends on your problem. In this particular case the issue revolved around the external resource reference and how the HTML document was loaded. To work out your particular issue it's best to head over to the [support forum](http://groups.google.com/group/dompdf) and give as much detail as you can.

**Comment by Santoshge-Reddy** [comment]
Got The issue if there are spaces in the image name or URL's

So replace the image-name with %20 it will be solved

$image = str_replace(' ', '%20', $items->image);

**Comment by ZerooCool** [comment]
The same problem when i'm using mediawiki and i don't know how i can fix that.
https://github.com/dompdf/dompdf/issues/1766

**Comment by jgmuchiri** [comment]
Solved the issue by using the absolute (full) path to the image if you are on Linux box

`<img src="/home/vagrant/projects/www/my-app/assets/images/logo.png">`

**Comment by faisalteastall** [comment]
I have also a solution but I will not tell you any more

**Comment by AmeerHamza33** [comment]
<?php
$path = 'logoweb.png';
$type = pathinfo($path, PATHINFO_EXTENSION);
$data = file_get_contents($path);
$base64 = 'data:image/' . $type . ';base64,' . base64_encode($data);
?>
<img src="<?php echo $base64?>" width="150" height="150"/>

**Comment by AmeerHamza33** [comment]
best solution that i found



$path = 'logoweb.png';
$type = pathinfo($path, PATHINFO_EXTENSION);
$data = file_get_contents($path);
$base64 = 'data:image/' . $type . ';base64,' . base64_encode($data);


//< src="<?php echo $base64?>" width="150" height="150"/>//
