### ISSUE TITLE
grouping two rows together so so on a dynamic page they do not have a page break between them

### ISSUE THREAD

**Issue by tarunnh** [dompdf/dompdf#1237]
Hello, I have an issue and I am not sure where to post this. I am using the latest version of Dompdf Version - 0.7.0
Basically I have a list of people their scores and comments that I need to render in the pdf. 
Representation: 

![screen shot 2016-07-13 at 2 39 34 pm](https://cloud.githubusercontent.com/assets/20173126/16817467/7e9a3ff0-4908-11e6-9aca-be70cdf71527.png)

Sorry for the poor representation, but hope it makes sense. 
Whats happening is that sometimes the page break happens between the row of results and comment
and I need that not to happen. It can happen after or before the two rows, but they need to be essentially grouped togeather. 

I have tried to add a page-break-before: avoid and a page-break-after: auto in the tr tags as such

<table>
     <tr style="page-break-before: auto;">
     </tr>
     <tr style="page-break-before:avoid;">
     </tr>
</table>

that is just one example of what i tried. But it did not work. I also tried to add the "page-break-inside:avoid" to the table tag. But it does not give me a result that is desired. Sometimes the information i get is more than a page long, so i get over 10 empty pages. 

Please help. I've been stuck with this issue for a while.

**Comment by bsweeney** [comment]
Unfortunately the page-break declarations (normally how you would do this) don't work too well with table elements right now. I can't really think of a great way to handle the setup. The best I can come up with off the top of my head is to used a fixed table layout and container table, e.g.:

```
<table width="100%">
  <tr><td width="100%">
    <!-- content start -->
    <table width="100%">
      <tr>
        <td width="50%">John D'oh</td><td width="25%">a</td><td width="25%">b</td>
      </tr>
      <tr>
        <td>Comments</td><td colspan="2">wat wat</td>
      </tr>
    </table>
  </td></tr>
  <!-- content end -->
</table>
```

Repeat that content block for each record. Because dompdf won't page a table row each content block will be paged as a whole.

**Comment by tarunnh** [comment]
Hey bsweeney, thanks for responding. I actually tried that as well, and then i quickly realized that if i did that, the table headers I've got setup then don't line up with the columns. and if i make the table headers part of the table, they don't show up in the next page in the case of overflow :( 
any other hacks you could think of?

**Comment by bsweeney** [comment]
If you carefully construct the table you should be able to get the headers to line up (should, but I haven't tried, so...). You just have to manually define the widths rather than rely on dompdf to calculate them based on the content. It's far from an ideal solution.

**Comment by tarunnh** [comment]
i see, i'll try that out and see if it works. Hopefully it works :) but thank you very much for your help bsweeney. Hopefully there will be an update to the dompdf soon to allow for something like this :)

**Comment by Mellthas** [comment]
`page-break-before` and `page-break-after` are supported on table rows now since version 1.1.0.
