### ISSUE TITLE
Page Size

### ISSUE THREAD

**Issue by colerua** [dompdf/dompdf#1248]
Is it possible to set custom page sizes and margins at render?

**Comment by hassanazimi** [comment]
I want to print receipts and I want page break to be set right after the text is finished meaning 80mm width with height adjusts to the text size, also if margins could be modified it would be perfect.

**Comment by zagreusinoz** [comment]
I'm just getting into dompdf myself, but i know you can set page sizes with: 

$dompdf->setPaper('A4', 'portrait');
string|array $size: 'letter', 'legal', 'A4', etc. See Dompdf\Adapter\CPDF::$PAPER_SIZES
string $orientation: 'portrait' or 'landscape'

Not sure about the margins though.

**Comment by bsweeney** [comment]
It depends on where you want to do this. @zagreusinoz provides an answer that works for standard page sizes. If you want a custom page size you can just provide the dimensions directly using the array syntax.

```
$dompdf->setPaper(array(100,100,0,0));
```

Or if you wanted to do it in your document:

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <style>
    @page { size: 500pt 500pt; }
  </style>
</head>
<body>
  ...
</body>
</html>
```

To set margins you just add that to your page declaration:

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <style>
    @page { size: 500pt 500pt; margin: 50px;  }
    body { background-color: orange; }
  </style>
</head>
<body>
  ...
</body>
</html>
```
(background color added for clarity)

**Comment by bsweeney** [comment]
@hassanazimi that's not really something dompdf is equipped to do, though I have worked out a method that may be sufficient for rendering content to a single page. See this SO post: http://stackoverflow.com/a/26771324/264628

**Comment by HKandulla** [comment]
Hi @hassanazimi, can you give me an idea how much work it would take to implement such a feature (auto-height). In mPdf and iText (Java) you can implement auto-height by getting the y-position after loading the html into an instance and than creating another instance with the y-position as height. So getting the y-position afther loading in some content (html) is necessary. Could you outline whether and how this could be implemented in dompdf? 
I would really like to switch to dompdf but I need auto-height. Maybe I can try to implement this feature into dompdf. Thanks, Hannes

**Comment by bsweeney** [comment]
@HKandulla didn't like the method I outlined in my linked answer?

Maybe you could do it the way you want by wrapping the entire content of the HTML document in the *first* render in an absolutely positioned element. After the render is complete, if you could find the correct frame object attached to that element, you could query its line boxes to see what the position of the last line is.

Something like this for the HTML:

```
<html>
  <head>
    <style>
      #height-container { position: absolute; left: 0px; right: 0px; top: 0px; }
    </style>
  </head>
  <body>
    <div id="height-container">
      <!-- your HTML here -->
    </div>
  </body>
</html>
```

Then like this with the HTML:

```
<?php
$dompdf = new Dompdf();
$dompdf->loadHtm($html);
$dompdf->render();

for ($i = 0; $i < \Dompdf\Frame::$ID_COUNTER; $i++) {
  $frame = $dompdf->getTree()->get_frame($i);
  if ($frame->get_node()->nodeName == "div" && $frame->get_node()->getAttribute("id") == "height-container") {
    $height = round(end($frame->get_decorator()->get_line_boxes())->y);
    break;
  }
}

unset($dompdf)
$dompdf = new Dompdf();
$dompdf->setPaper(array(0,0,612,$height));
$dompdf->loadHtml($html);
$dompdf->render();
$dompdf->stream();
?>
```

The main thing you would need to figure out is how to modify the stylesheet to remove the styling on the `#height-container` for the second rendering.

**Comment by HKandulla** [comment]
Hi @bsweeney thanks for your detailed answer! And sorry for my late response. 
That's sounds liek a good solution. I will give it a try and post my findings here. 
Thanks for all the good work, Hannes

**Comment by UVLabs** [comment]
> It depends on where you want to do this. @zagreusinoz provides an answer that works for standard page sizes. If you want a custom page size you can just provide the dimensions directly using the array syntax.
> 
> ```
> $dompdf->setPaper(array(100,100,0,0));
> ```
> 
> Or if you wanted to do it in your document:
> 
> ```
> <!DOCTYPE html>
> <html>
> <head>
>   <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
>   <style>
>     @page { size: 500pt 500pt; }
>   </style>
> </head>
> <body>
>   ...
> </body>
> </html>
> ```
> 
> To set margins you just add that to your page declaration:
> 
> ```
> <!DOCTYPE html>
> <html>
> <head>
>   <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
>   <style>
>     @page { size: 500pt 500pt; margin: 50px;  }
>     body { background-color: orange; }
>   </style>
> </head>
> <body>
>   ...
> </body>
> </html>
> ```
> 
> (background color added for clarity)

What exactly are the array values specifying?

`array(100,100,0,0)`

**Comment by bsweeney** [comment]
@UVLabs, sorry it looks like I mistyped, it should be `array(0,0,100,100)`. Per the CPDF comments: bottom left and upper right corner of the page, first two are normally zero.
