### ISSUE TITLE
Document structure can affect link rendering

### ISSUE THREAD

**Issue by Jany-M** [dompdf/dompdf#1250]
I'm using the latest `dompdf` release and I can't seem to be able to render links.
In the html version the links are correctly formatted as `<a href="http://example.com">text</a>`.

The only way the link will be clickable once rendered in the PDF, is if it's written in full, eg. `<a href="http://example.com">http://example.com</a>`

Am I missing something?

**Comment by bsweeney** [comment]
The latter example is probably the PDF reader translating the URI-looking text into a link (some of them do that).

Which dompdf version specifically? I tested that text and did not have any issues, but I may be missing something. There have been a few bugs in the URL helpers ([ref](https://github.com/dompdf/dompdf/commits/develop/src/Helpers.php)).

Also, what PDF viewer are you using.

**Comment by Jany-M** [comment]
I have made some changes to the layout and now all links render fine, even though their structure hasn't changed. Can't honestly pointpoint what could have possibly caused this. The issue was with the latest version (and the one before), but clearly it must be have been a weird exception as all is good now.

**Comment by bsweeney** [comment]
Interesting. If you run into the problem again and can post the full document maybe we can track down the issue.
