### ISSUE TITLE
Problem when rendering - Image in Cache Class

### ISSUE THREAD

**Issue by FernandoManoelAlmeida** [dompdf/dompdf#1257]
Hello, I have a problem.

I'm using dompdf with Laravel 4.2. When I rendering a html template with \View::make('template') setting a image a error happens.

Exemple:

            $info['image'] = $this->image;
            $info['title'] = 'Test';
            $info['some_date'] = $formatter->format(new \DateTime());
            $filename = 'test';
            $HTML = \View::make('test/Template_1', $info);
            $dompdf = new Dompdf();
            $options = $dompdf->getOptions();
            $options->setIsRemoteEnabled(true);
            $dompdf->setOptions($options);
            $dompdf->loadHtml($HTML);
            $dompdf->setPaper('A4', 'portait');
            $dompdf->render();
            $dompdf->stream($filename);

Error: 
![screenshot 2016-08-19 09 32 16](https://cloud.githubusercontent.com/assets/5129681/17810475/b8a95aa2-65f3-11e6-8c9a-c62f41c4f90d.png)
https://github.com/dompdf/dompdf/blob/develop/src/Image/Cache.php#L101

He expects a String, but a Array given. In else he expects a String to.

![screenshot 2016-08-19 10 08 33](https://cloud.githubusercontent.com/assets/5129681/17810716/2b37c2ec-65f5-11e6-8faf-c8fd3b612545.png)
https://github.com/dompdf/dompdf/blob/develop/src/Image/Cache.php#L111

var_dump($image)
![screenshot 2016-08-19 10 25 02](https://cloud.githubusercontent.com/assets/5129681/17811094/564d46c6-65f7-11e6-8f1e-c98395987a08.png)

When I put $image[0] all work well.
The strange is when I put a HTML without use the View's Class like this:

            $HTML = '<html>
                     <img src='same-link'>
                     </html>';

The same error happens.

**Comment by bsweeney** [comment]
Which release of dompdf are you using?

**Comment by FernandoManoelAlmeida** [comment]
"dompdf/dompdf": "0.7.x-dev"

**Comment by FernandoManoelAlmeida** [comment]
<c662c42>

**Comment by bsweeney** [comment]
OK, wonder if it has to do with the change to a helper function for file fetch. See commits c53dc98, 8a64c82, and 589ed86.

Two things:

 1. Is `allow_url_fopen` set to true
 2. It looks like I introduced a variable reference bug in 8a64c82

I'll fix that bug then double-check that things are working as expected and push an update today.

**Comment by FernandoManoelAlmeida** [comment]
Thanks man. I'll wait for it

**Comment by bsweeney** [comment]
No, thank *you*. Not many people are working off the develop branch, meaning mistakes like this take longer to catch. I appreciate you taking it for a spin.

The just-committed update should address the issue.

**Comment by FernandoManoelAlmeida** [comment]
The last update ( 74a9b6a ) makes all works fine, thanks
