### ISSUE TITLE
Incorrect indent after pagebreak with inline-block elements.

### ISSUE THREAD

**Issue by nuez** [dompdf/dompdf#1259]
# Problem

When rendering a list of DIVS that shouldnt break inside`(page-break-inside: avoid)`, and inside the DIV there are two DIVS put next to each other using `display:inline-block`, the first item on the next page will have an unintended left indent. 
# Steps to reproduce
## HTML

```
<html>
<link rel="stylesheet" type="text/css" href="test.css">
<body>

<article>
    {{ repeat the following HTML x 100 }}
    <div class="item">
        <div class="label">
            <div class="label">Lorem</div>
            <div class="description">Lorem</div>
        </div>
        <div class="text">Dolet
        </div>
    </div>
    {{ // end repeat }}
</article>
```
## CSS

```
article .item {
    page-break-inside: avoid;
}
article .item .text {
    width: 200px;
    display: inline-block;
}
article .item .label {
    width: 200px;
    display: inline-block;
}
```
## PHP

```
require_once("dompdf/autoload.inc.php");
$html = file_get_contents('test.html');

$dompdf = new \Dompdf\Dompdf();
$options = new \Dompdf\Options();
$options->setIsRemoteEnabled(TRUE);
$dompdf->setOptions($options);

$dompdf->load_html($html);
$dompdf->set_paper('A4');
$dompdf->render();
$dompdf->stream('pdf.pdf');
```
# Screenshot

![image](https://cloud.githubusercontent.com/assets/851889/18175991/eccd2e3c-7073-11e6-9296-d908b6f9badf.png)

**Comment by ikorgik** [comment]
Have the same issue.

**Comment by samgkea** [comment]
I'm a little late to the party here, but I was having the same exact issue. To fix this, I put in an empty div before my left + right inline-block div's and added a clear: left style declaration. Seems to be the magic elixir. 

See below:

`<div class="tableRow" style="display: block; font-size: 9px; overflow: hidden; padding: 0 0 .5em; margin: 0; -webkit-column-break-inside: avoid; page-break-inside: avoid; break-inside: avoid;"><div style="clear:left"></div><div class="leftColumn" style="display:inline-block; margin: 0; padding: 0; width: 35%"><span class="productTypeTitle" style="text-decoration: underline;">{ OUTPUT HERE }</span></div><div class="rightColumn" style="display: inline-block; margin: 0; padding: 0; width: 65%;">{ OUTPUT HERE }</div>`
