### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by ghost** [dompdf/dompdf#1260]
My function works fine on windows to generate a pdf from a laravel view but in our debian environment we get the following error:

```
production.ERROR: ErrorException: Undefined index: /var/www/application/dev/vendor/dompdf/dompdf\lib\fonts\Helvetica-Bold in /var/www/application/dev/vendor/dompdf/dompdf/src/
Renderer/Text.php:97
```

here is my code:

```
$filepath = app_path().'/TestFiles/';
$tempfilename = hash('sha1', Auth::user()->email)."-".hash('sha1', date(DATE_RFC2822)).'.pdf';

$file = $filepath . $tempfilename;

$pdf = PDF::loadView('Emails.quote', compact('quote', 'client', 'currency'));
$pdf->save($file);
```

My initial thought is the 3 slashes that are the wrong way in referencing the font

**Comment by bsweeney** [comment]
Were you able to resolve this issue?

**Comment by McGreeb** [comment]
Nope issue still persists

**Comment by bsweeney** [comment]
This is likely an issue with dompdf. I'm not sure what's going on but it looks like dompdf is attempting to read info about the font before it has been loaded into CPDF. Or maybe an attempt was made to load the font but it could not be found.

**Comment by McGreeb** [comment]
Anything you need me to test let me know.

**Comment by dylboy** [comment]
I had this issue moving from PC to MAC
i had to change page from backslash \ to forward slash /
in /myapp/storage/fonts/dompdf_font_family_cache.php

**Comment by McGreeb** [comment]
So after doing some investigation it seems to be down to the use of the DIRECTORY_SEPARATOR constant which comes out to "/" on my windows platform but "\" on my debian one.

There is no need to use the DIRECTORY_SEPARATOR constant as windows will handle both "\" and "/" and debian will handle "/" so we can just replace all instances of DIRECTORY_SEPARATOR with "/" 

I am trying to test this atm but having issues with pushing my vendor folder to my git reposirty in netbeans

**Comment by bsweeney** [comment]
That's a good point, though we'll have to ensure that the path is consistently generated. If the path is system-generated then it still matters if we're doing any kind of parsing.

**Comment by McGreeb** [comment]
So I replaced all instances of DIRECTORY_SEPARATOR with "/" and uploaded it to my Debian server and I'm still getting the same error

**Comment by bsweeney** [comment]
@McGreeb I think your issue (original post) may be unrelated.

The issue brought up by @dylboy is probably different. I may go back and update our code to use `/` instead of `DIRECTORY_SEPARATOR` ... but it will require a bit of finesse to make sure all related code is looking for the correct thing (as mentioned, some parts of the code may be parsing the path string).

BTW, which version of dompdf are you using?

**Comment by McGreeb** [comment]
Yeah I figured It would be a good quick test to give us some more information. 

This is the entry in my laravel composer.json: "barryvdh/laravel-dompdf": "0.7.x@dev"

**Comment by GregKeaney** [comment]
Anyone solve this?  I am getting the same issue.  Pushing from a PC to a Forge server.

**Comment by bsweeney** [comment]
Has anyone tried resetting their fonts? You do this by restoring dompdf/lib/fonts back to how it is in a fresh install. If you have also specified separate directories for the font directory and font cache directory you should clear those out.

**Comment by GregKeaney** [comment]
I'll try the first suggestion now...

**Comment by McGreeb** [comment]
I deleted my vendor folder in laravel and did a composer update essentially re-downloading and reinstalling all my plugins including dompdf, still have the same issue.

**Comment by GregKeaney** [comment]
Yep.  Did nothing for me either.

**Comment by bsweeney** [comment]
Just wanted to make sure.

**Comment by GregKeaney** [comment]
how about emptying storage/fonts on the production machine?

**Comment by bsweeney** [comment]
Maybe a system-related configuration issue around process isolation (e.g. PHP's safe mode). Any other errors logged by PHP or your web server software? Can you render a similar HTML file from the command line (if you have access)?

**Comment by GregKeaney** [comment]
you're getting about my pay grade...I do have command line access.  How would I render the page there?

**Comment by bsweeney** [comment]
Oh, wait. I see. It looks like a path parsing issue. We've been working to address this in newer versions of dompdf. You might try tweaking your dompdf_font_family_cache manually so that the path delimeter is a "/" instead of a "\".

**Comment by GregKeaney** [comment]
right I did try that.  Let me see if that actually got pushed.

**Comment by bsweeney** [comment]
Good lord I need to remember to re-read the thread next time. This was discussed earlier 😞

**Comment by McGreeb** [comment]
XD what change do you want me to try?

**Comment by GregKeaney** [comment]
Do I need to replace all instances of '\' in dompdf_font_famliy_cache with '/' ?

**Comment by McGreeb** [comment]
I have already tried replacing all instances of "DIRECTORY_SEPARATOR" with "/" in that file and had no luck. there are no raw "\" in it.

**Comment by bsweeney** [comment]
To make sure you don't run into any issues yes, you would want to make all path delimiters match your system's default.

**Comment by GregKeaney** [comment]
Yep.  Changing all the separators in the file worked.  Thanks!

**Comment by McGreeb** [comment]
Could you pastebin your file for me?

**Comment by bsweeney** [comment]
If you're using a custom font directory be sure to check the dompdf_font_family_cache.php file there as well.

**Comment by McGreeb** [comment]
I feel like im missing something, I only have one file \vendor\dompdf\dompdf\lib\fonts\dompdf_font_family_cache.dist.php that looks like this http://pastebin.com/9whLUZ4q is this the file your talking about?

**Comment by bsweeney** [comment]
That's is, but after you've used dompdf a file without the "dist" should also be present.

**Comment by McGreeb** [comment]
Any idea when we might get an update with a fix for this? starting to kinda need the functionality in my project

**Comment by bsweeney** [comment]
I hope to have fixes for this in the next version. In the meantime if you can grab a fresh copy of dompdf on your server rather than uploading the local copy you will hopefully avoid the problem.

**Comment by McGreeb** [comment]
don't upload local copy, do a composer-update to pull from source everytime

**Comment by bsweeney** [comment]
oh ... kay. Not sure why you're experiencing this particular issue then. You've created the appropriate font storage directory for laravel?

**Comment by McGreeb** [comment]
included in package I beleve

**Comment by bsweeney** [comment]
I can't say for sure, haven't used Barry's package. But I have seen that brought up before ([ref](http://stackoverflow.com/a/32713975/264628)).

Have you tried the latest from the develop branch to see if it helps?

**Comment by McGreeb** [comment]
I will try that when I get a chance

**Comment by McGreeb** [comment]
Yeah i have that folder, still have the issue.

```
username@server:/var/www/application/dev/storage$ ls -l
total 16
drwxrwx--- 3 www-data www-data 4096 Oct  7 17:42 app
drwxrwx--- 2 www-data www-data 4096 Oct  7 17:42 fonts
drwxrwx--- 5 www-data www-data 4096 Oct  7 17:42 framework
drwxr-xr-x 2 www-data www-data 4096 Oct  7 17:44 logs

```

**Comment by McGreeb** [comment]
OK i fxed it, found the file /var/www/application/dev/storage/fonts/dompdf_font_family_cache.php

Changed all the "\" to "/" works fine.

**Comment by dylboy** [comment]
Um pretty sure i said this 17 days ago?
Or is this something different?

**Comment by bsweeney** [comment]
@dylboy indeed it is ... must've slipped by without a notice :/

**Comment by McGreeb** [comment]
Yeah, I was looking in the wrong place for the file that's why. when you posted I was looking in the vendor folder for it not the storage folder.

**Comment by dylboy** [comment]
@McGreeb :) Glad you got it sorted out.
Hopefully plain sailing now.

**Comment by vincentkedison** [comment]
Is this issue resolved?

**Comment by bsweeney** [comment]
@vincentkedison the issue here was related to the path separator. I believe the latest version should sufficiently address that type of problem, but copying code between systems (or using some kind of continuous deployment from source) can cause this type of issue to rear up again. If you're not sure what's going on here or if this applies to you please start a thread on the [support forum](http://groups.google.com/group/dompdf).

**Comment by harsh1412** [comment]
Change backslash \ to forward slash / 
in fonts/dompdf_font_family_cache.php

**Comment by Eltyer** [comment]
Additionally:

In storage/fonts/dompdf_font_family_cache.php

change all "/" to "\"

You can do this with the "replace all" function of your text editor

**Comment by AmmarNaqvi** [comment]
Deleting everything inside app/storage/fonts, solved this for me

**Comment by sodikabdullaev** [comment]
Just deleting /storage/fonts folder is enough

**Comment by mcornielly** [comment]
Solved...
delete dompdf_font_family_cache.php. root (storage/fonts/dompdf_font_family_cache.php)
or change name dompdf_font_family_cache_.php
and ready.
