### ISSUE TITLE
Different footer on first page?

### ISSUE THREAD

**Issue by jiterziev** [dompdf/dompdf#1262]
I'm trying to make different footer for the first page of my documents. The idea is:

Page1:
|**header**|
|_content__|
|**footer1**|

Page2+:
|**header**|
|_content_pt2+__|
|**footer2**|

Footer 1 has a different length/height and content to footer 2
I'm using DOMPDF 0.7.0

Any help or idea for workaround will be highly appreciated! Thank you in advance!

**Comment by bsweeney** [comment]
Do you know where page two starts? If so the easiest way to achieve this is for the page 1 header/footer to be an absolutely-positioned element. If you put the page 2+ header/footer after the page break it should only render from page 2 onwards.

If you don't you can still use the absolute/fixed combination, it just requires a bit more work to style things such that the page 2+ header/footer is not visible on the first page.

I should note there's a good chance that in the future we may make a change such that positioned content will always be positioned from the first page. However, I hope that by then we can provide a more elegant solution for handling different headers/footers per page.
