### ISSUE TITLE
table doesnot seems to be closed 

### ISSUE THREAD

**Issue by sonispark** [dompdf/dompdf#1264]
my dompdf table rendering in two pages,but the table in the first page does not seems to be closed.
how to close the table in the first page?

**Comment by bsweeney** [comment]
Sample HTML?

**Comment by sonijoy** [comment]
<table id="date_table" style="height:auto; text-align:center;">
      <thead>
        <tr style="height:34px;">
          <th>Ref.</th>
          <th>Description</th>
          <th>Dept.</th>
          <th>Qty</th>
          <th>Unit</th>
          <th>Price</th>
          <th>Amount/DHS.</th>
        </tr>
      </thead>
      <tbody class="bill_table">
';



      for ($i=0;$i<=100;$i++) { 

        $html.= '<tr style="height:auto; ">
        <td>1</td>
        <td style="text-align:left;"> <div style="padding-bottom:5px;">  Test Description</div></td>
        <td>claim</td>
        <td  style="text-align:center;">1</td>
        <td>1</td>
        <td style="text-align:right;">100</td>
        <td style="text-align:right;">100</td>
      </tr>'; 

      } 


    
  $html .= '<tr class="tr_last">
        <td  colspan="6"><b>Total </b></td>
        <td style="text-align:right;" colspan="1">300</td>
      </tr>
      </tbody>
    </table>
    <table border="1" cellpadding="1" cellspacing="1" style="width:100%;margin-top: 0px;">
      <tbody>
        <tr style="padding:10px;">
          <td style="width:14%;font-size:10px; padding-bottom:10px;padding-top:0px;"><b>Remarks </b></td>
          <td style="color:#000; font-size:12px;"> testets </td>
        </tr>
      </tbody>
    </table>
![workspace 1_041](https://cloud.githubusercontent.com/assets/14216316/18337525/258ba0c4-75af-11e6-9a3e-22022e74b8a7.png)

**Comment by bsweeney** [comment]
I'd tentatively say this is to be expected. The table doesn't actually end after the first page so there's no break at the bottom (see #640). I can't really say if the styling is correct without also seeing the relevant CSS.
