### ISSUE TITLE
Example of Embedded PHP support

### ISSUE THREAD

**Issue by antoniogarcia78** [dompdf/dompdf#1265]
I use this script inside the html load in the dompdf object

```
<script type="text/php">
$pdf->text(100, 100, "Pagina {$PAGE_NUM} de {$PAGE_COUNT}", $fontMetrics->getFont("Arial"), 10, array(0, 0, 0));
</script>
```

The php is

```
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
$options = new \Dompdf\Options();
$options->setIsPhpEnabled(true);
$dompdf->setOptions($options);
$canvas = $dompdf->getCanvas();
$dompdf->stream();
```

I see nothing.
Any way to debug this? Thankyou

**Comment by bsweeney** [comment]
Try something more like this for your PHP:

```
$options = new \Dompdf\Options();
$options->setIsPhpEnabled(true);
$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
$dompdf->stream();
```

Dompdf determines what to do with the embedded script when you render the document, so you'll want to set that option before you render.

**Comment by antoniogarcia78** [comment]
Now in 0.7 work
The script in html is 
```
if (isset($pdf))
            {
            $font = $fontMetrics->getFont("Arial", "bold");
            $pdf->page_text(10, 580, "Informe Resumen", $font, 10, array(0, 0, 0));
            $pdf->page_text(770, 580, "Pagina {PAGE_NUM} de {PAGE_COUNT}", $font, 10, array(0, 0, 0));
            $pdf->line(10, 575, 830, 575, array(0,0,0), 1);
            }
```

Now the problem is the rowspan and pagebreak. But this is other history

**Comment by bsweeney** [comment]
Great! I'm going to leave this open for now to remind myself to add more documentation around embedded script.

**Comment by antoniogarcia78** [comment]
Great and thank you. 
I closed accidentally

**Comment by hugeps** [comment]
Is there any reference as to what class is the "$pdf" variable instance is ?
What methods and properties are accessible?

**Comment by bsweeney** [comment]
`$pdf` is the current [Canvas](https://github.com/dompdf/dompdf/blob/master/src/Canvas.php) instance ([documented in the wiki](https://github.com/dompdf/dompdf/wiki/Usage#embedded-php-support)). We do not yet have documentation outlining all the options, but you can get a good sense of what's available by browsing the interface source.
