### ISSUE TITLE
External stylesheets are no working

### ISSUE THREAD

**Issue by uc-bkr** [dompdf/dompdf#1266]
Hi,
I need to convert a html page into pdf. My html page contains huge css. Thats why i am taking it from external file.

But it is not working. Please help me out.

**Comment by bsweeney** [comment]
How are you using dompdf? How is the eternal CSS referenced?

**Comment by uc-bkr** [comment]
I have a template processor. I am printing via template engine which is smarty. 

So there are some template strings, which is resolved by smarty. 

And I have referenced stylesheet in following manner / : 
<link type="text/css" rel="stylesheet" href="style.css" />

It is rendering content correctly but css is not applying on given content

**Comment by bsweeney** [comment]
It's possible that dompdf just isn't finding the CSS. When using the load_html method paths that don't include a protocol+domain are relative on the local file system. If style.css is not in the same directory as the script running dompdf it won't be found. You can try setting the base path after loading the document.
