### ISSUE TITLE
How to Use in Pure PHP (no MVC)

### ISSUE THREAD

**Issue by summit-web** [dompdf/dompdf#1268]
Hi there,

Although I've successfully include()'d the auto loader, as I'm not using an MVC the code

`new Dompdf();`

fails as I'm not in a Class/Model scenario.

Do you have a link to the 'vanilla' PHP use of your code please?
Thanks,

Martin

**Comment by summit-web** [comment]
As an addendum, I have done the following:
`require('../dompdf-master/autoload.inc.php');`

without error, but I can't see how to go about the next stages, because

`$dompdf = new Dompdf();`

gives the error 

`Fatal error: Class 'Dompdf' not found`

Thanks!

**Comment by costafrancesco94** [comment]
It's supposed to work anyway... just add, in the top of the file in wich you are using 'new Dompdf();'

use Dompdf\Dompdf;

Don't forget to download (or install with composer) the other two libs that are required to load the entire framework

**Comment by bsweeney** [comment]
Be sure to take a look at the [README](https://github.com/dompdf/dompdf/README.MD) and [usage page on the wiki](https://github.com/dompdf/dompdf/wiki/Usage).

**Comment by summit-web** [comment]
Thanks, I'll re-look at those. I currently can't do `use Dompf\Dompf` as it doesn't recognise the `use` command. I'll check to see if I'm missing dependencies.

**Comment by summit-web** [comment]
After I moved some code around, it seems to be generating the PDF, must have been the order I did certain commands. Thanks for your help - now I just need to get the PDF looking right, but that's my responsibility, not yours! Cheers!
