### ISSUE TITLE
CMYK support for SVG in print-PDF

### ISSUE THREAD

**Issue by pittikolbenhirse** [dompdf/dompdf#1269]
while dompdf supports cmyk( c,m,y,k ) php-svg-lib does not. is it possible (for me) to change that?

**Comment by bsweeney** [comment]
I'm sure you could, but I don't know [php-svg-lib](https://github.com/PhenX/php-svg-lib) well enough to direct you. Head over to the project and put in an enhancement request. If @PhenX is able to give you enough direction to make the change make sure you submit a pull request.

**Comment by pittikolbenhirse** [comment]
I've found a solution by myself but faild to open a pull request :)

https://github.com/PhenX/php-svg-lib/issues/9

2016-09-21 22:44 GMT+02:00 Brian Sweeney <notifications@github.com>:
