### ISSUE TITLE
Dompdf won't display anonymous table rows

### ISSUE THREAD

**Issue by rob281** [dompdf/dompdf#1270]
Hi I am using dompdf 6.2 and I am trying to create 2 a column PDF using bootstrap in html similar to http://www.bootply.com/WqVCv8OBXr 

Everytime I run dompdf I get this error: 
Catchable fatal error: Argument 1 passed to DOMNode::appendChild() must be an instance of DOMNode, null given, called in C:\xampp\htdocs\testphp\dompdf\include\table_frame_decorator.cls.php on line 312 and defined in C:\xampp\htdocs\testphp\dompdf\include\frame.cls.php on line 765

I am a novice coder and it seems I bit off way more than I can chew right, I'm at a loss as to how to fix this. I just cannot find a proper solution even though I know it's gotta be out there somewhere. 
Here is what I want my PDF to look like: http://imgur.com/a/dHmyA

If you could take some time out of your day to give me a few pointers I would be forever grateful!

**Comment by bsweeney** [comment]
Your caption says it all. Watch issue #449 for updates on anonymous tables.

More specifically on your issue, to avoid the exception just add a container element around the content that defines the cell.

```
<div class="child">
  <div class="child-content">
    1
  </div>
</div>
```

That being said, fixing that exception will not make things look correct. Until we support breakpoints Bootstrap-based layout is probably not going to look quite right. Watch issue #631 for improved Bootstrap support.

**Comment by rob281** [comment]
Thanks for the reply! Are you aware of any alternative method to create my desired result or would you recommend I use a different plugin? I am taking a crash course in web dev right now and am trying to make dompdf work for my uses. Thanks!

**Comment by bsweeney** [comment]
Sounds like a project in and of itself. If you're looking for a quick fix using a headless browser would be the best solution. Take a look at [PhantomJS](http://phantomjs.org).
