### ISSUE TITLE
Does not recognize cirilicu

### ISSUE THREAD

**Issue by s-a-k-a** [dompdf/dompdf#1271]
I make site in cirilica. Cirilica is Serbian (Europe) language. 

This is my node:
http://prntscr.com/cmlauu
And this is pdf.
http://prntscr.com/cmlb2l 

He make pdf, but from some reason does not recognize our letter.

How to solve this problem?

**Comment by bsweeney** [comment]
Take a look at the [Unicode How-To](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo).

Quickest fix is to style your text using the bundled DejaVu fonts (e.g. `* { font-family: DejaVu Sans, sans-serif; }`).

**Comment by s-a-k-a** [comment]
Thank you. But where do put { font-family: DejaVu Sans, sans-serif; } ?

I use dompdf in entity_print module in drupal 8.  Does I need to instal https://github.com/phenx/php-font-lib/

I write this code composer require dompdf/dompdf onluy. :)

**Comment by bsweeney** [comment]
You would add that styling to your document's stylesheet.

Since you used composer you should not need to add any other packages.

**Comment by ivnish** [comment]
*{ font-family: DejaVu Sans, sans-serif; }

Does not help me :(
