### ISSUE TITLE
CSS counter doesn't work properly in table-header-group

### ISSUE THREAD

**Issue by e-moe** [dompdf/dompdf#1274]
**steps to reproduce**: generate multipage document with big table with rendered headers on each page using `display: table-header-group;` (see provided html example)

**actual result**: each page has table header with `content: counter(page);` always equal to 1

**expected result**: each page will have table header with correct values 1, 2, 3 ...

_note: counter outside table works correctly (see `<span class="page-number">Page #</span>` before and after table_

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <style>
    thead {
      display: table-header-group;
    }
    .page-number:after {
      content: counter(page);
    }
    td {
      padding: 200px;
    }
  </style>
</head>
<body>
  <span class="page-number">Page #</span>
  <table>
    <thead>
      <tr><th><span class="page-number">Page #</span></th></tr>
    </thead>
    <tbody>
      <tr><td>a</td></tr>
      <tr><td>b</td></tr>
      <tr><td>c</td></tr>
      <tr><td>d</td></tr>
    </tbody>
  </table>
  <span class="page-number">Page #</span>
</body>
</html>
```

**Comment by abruzzi** [comment]
Seems it's still a bug now in 2019, wondering if there are any progress?

**Comment by bsweeney** [comment]
Actually, looks like this is fixed though I couldn't say when we fixed it.
