### ISSUE TITLE
Only first images loaded correctly

### ISSUE THREAD

**Issue by Kocik** [dompdf/dompdf#1277]
Hello,
only couple of first images are loaded correctly. With the snippet below, first 13 images are loaded and there rest is replaced with those 13 first loaded. 

Curious thing is that when I run it on Debian setup it works ok. The problem appears when I run it on BSD system (with installed required dependencies).
We checked if the GD and DOM extensions are installed, if the memory is enough, if the image paths are ok, if there is some solution in google, `display: -dompdf-image !important;`. We cannot even find any warnings in logs that could explain that.

Any ideas what might be the issue?

```
<?php
error_reporting(E_ALL);
require "../vendor/autoload.php";
use Dompdf\Dompdf;

//add 100 unique images 16x16px
for($i = 0; $i<100; $i++) {
            $html .= $i . ": <img src=\"" . 
__DIR__  . "/images/flags/flag{$i}.png\"/><br> ";
}
$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
$dompdf->stream();

```

**Comment by bsweeney** [comment]
Could be the image type? Maybe a bug in the system libraries? Do you get the same results if you use a JPG?
