### ISSUE TITLE
Page doesnt render at all

### ISSUE THREAD

**Issue by youradds** [dompdf/dompdf#1278]
I'm having a problem getting this going. I've got all the libs included (as far as I'm aware), and have also installed PHP GD (as it was complaining that didn't exist).

This is the PDF it outputs:

[foo.pdf](https://github.com/dompdf/dompdf/files/514381/foo.pdf)

...and here is a text version of the PHP script:

[test.php.txt](https://github.com/dompdf/dompdf/files/514383/test.php.txt)

I'm calling via SSH with:

php test.php > foo.pdf

I would really love to give this a go, and I'm not happy with the current FPDF implementation we have (very hard to make changes to it)

Thanks!

Andy

**Comment by youradds** [comment]
haha typical... as soon as I post this! The problem seems to be with the following in my CSS file:


```
*
{
	border: 0;
	box-sizing: content-box;
	color: inherit;
	font-family: inherit;
	font-size: inherit;
	font-style: inherit;
	font-weight: inherit;
	line-height: inherit;
	list-style: none;
	margin: 0;
	padding: 0;
	text-decoration: none;
	vertical-align: top;
}
```

I removed that, and its all good now.

**Comment by bsweeney** [comment]
That is some unexpected behavior. Think we need to do a better job of cascading defaults for some of those values.

**Comment by youradds** [comment]
Thanks for the quick reply :)

While I'm making progress, I've hit a bit of a road block. Please see the outputted file:

[foo(2).pdf](https://github.com/dompdf/dompdf/files/514517/foo.2.pdf)

The scripts:

[test.php.txt](https://github.com/dompdf/dompdf/files/514512/test.php.txt)

[test.html.txt](https://github.com/dompdf/dompdf/files/514514/test.html.txt)

The HTML itself renders fine, but for some reason it doesn't work in the PDF?

Thanks!

**Comment by bsweeney** [comment]
This seems to render acceptably with the current release.
