### ISSUE TITLE
Font looks thicker in MAC os

### ISSUE THREAD

**Issue by satyajeetporadia** [dompdf/dompdf#1281]
I am using Times new Roman and the font looks thicker in Mac than windows. I tried -webkit-font-smoothing: antialiased; but it didn't work.

**Comment by bsweeney** [comment]
If you're using the core PDF fonts then I would expect the display to be system dependent. Those fonts are supplied by the PDF viewer and so are subject to the vagaries of implementation. Have you tried using an embedded font (such as DejaVu Serif in v0.6.0 or greater)?

**Comment by satyajeetporadia** [comment]
I tried to embed external fonts by using font-family,

@font-family: 'Pacifico';
  font-style: normal;
  font-weight: normal;
  src: url('path to ttf file') format('truetype');
  }

But that also seems to be not working.

**Comment by bsweeney** [comment]
Not working meaning it doesn't load the font? Or not working meaning it also looks heavier?

**Comment by satyajeetporadia** [comment]
Yes the fonts are not loading. Even if I have font-family: Pacifico, the fonts are coming Times new Roman

**Comment by bsweeney** [comment]
sorry, your CSS example is throwing me off. You have something like this?

```
@font-face {
  font-family: Pacifico;
  font-style: normal;
  font-weight: normal;
  src: url("...") format("truetype");
}
```

How do you load the font? Is the font path on the local filesystem? It could be that dompdf isn't finding the font file.

**Comment by satyajeetporadia** [comment]
I have uploaded font.ttf on my server and I am giving that file path in url("...").

**Comment by bsweeney** [comment]
Any notices logged by PHP? Might try turning on dompdf debugging to see what it says.

**Comment by satyajeetporadia** [comment]
Sorry, But I don't know how to enable debugging in dompdf.

**Comment by bsweeney** [comment]
Typically when I want to debug dompdf I do the following (in v0.7.0 or newer):

ensure errors are logged:
```
ini_set('error_log', 'dompdf.log');
ini_set('log_errors', true);
error_reporting(E_ALL);
```

then enable dompdf debugging:
```
$_dompdf_show_warnings = true;
$_dompdf_debug = false;
$_DOMPDF_DEBUG_TYPES = [
   'page-break' => false
];
$dompdf_options = array(
	'logOutputFile' => 'dompdf.log.html',
	'debugPng' => false,
	'debugKeepTemp' => false,
	'debugCss' => false,
	'debugLayout' => false,
	'debugLayoutLines' => false,
	'debugLayoutBlocks' => false,
	'debugLayoutInline' => false,
	'debugLayoutPaddingBox' => false
);
$_dompdf_warnings = array();

$dompdf = new Dompdf($dompdf_options);
```

You can get more debug messages by tweaking the debug settings.
