### ISSUE TITLE
Inconsistent log file permission check / output buffer not closed

### ISSUE THREAD

**Issue by astehlik** [dompdf/dompdf#1282]
The `render()` method currently opens a new output buffer `ob_start()` when a log file is configured and the log file exists or the log file directory is writable (https://github.com/dompdf/dompdf/blob/master/src/Dompdf.php#L722).

It does not check if the existing log file is writable.

The `write_log()` method is supposed to close the buffer with `ob_get_clean()`. Here a check is in place that makes sure the log file is writable (https://github.com/dompdf/dompdf/blob/master/src/Dompdf.php#L871).

So if the log file exists and is **not** writable the buffer is opened but never closed.

This might lead to this error when testing PDF generation with PHPUnit:

> Test code or tested code did not (only) close its own output buffers

**Comment by bsweeney** [comment]
Nice catch. Eventually we'll fix logging by addressing #960. In the meantime we'll address this for the next release.
