### ISSUE TITLE
UTF8 PDF is empty

### ISSUE THREAD

**Issue by denisosteo** [dompdf/dompdf#1283]
I followed step by step configuration to enable Unicode and load the required font to dompdf but the produced document display as empty while it seems to contains everything including the expected font

I joint the PDF file produced by dompdf
[document.pdf.pdf](https://github.com/dompdf/dompdf/files/529135/document.pdf.pdf)

PHP source:

```
<?php
// reference the Dompdf namespace
set_include_path(get_include_path() . PATH_SEPARATOR . "dompdf");
require_once "autoload.inc.php";
use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();

// create pdf content
// $html = 'Hello world !!!';
$html = '<html>';
$html .= '<head>'.PHP_EOL;
$html .= '<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>'.PHP_EOL;
$html .= '</head>'.PHP_EOL;
$html .= '<body>'.PHP_EOL;
$html .= '<p style="font-family: DFBiaoKaiShu1B, sans-serif;">献给母亲的爱</p>'.PHP_EOL;
$html .= '</body>'.PHP_EOL;
$html .= '</html>';

$dompdf->loadHtml($html);

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'portrait');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
// stream(filename [without .pdf], 1 compress, 1 force save dialog)
$dompdf->stream('MyForm', 1, 0);
?>
```

**Comment by bsweeney** [comment]
That does seem to be the case. Have you tried rendering with font subsetting disabled?

**Comment by denisosteo** [comment]
I'll be glad to try but how to set disable font subsetting ? Is it a dompdf option ?

**Comment by denisosteo** [comment]
I found how to ENABLE/DISABLE font subsetting and both ENABLE/DISABLE produces same result;

I also notice in Apcahe log file the following errors:
`[Sat Oct 15 11:19:48.735519 2016] [:error] [pid 6780:tid 1680] [client ::1:50539] PHP Warning:  Invalid argument supplied for foreach() in C:\\xampp\\htdocs\\MyForms\\dompdf\\lib\\Cpdf.php on line 2469, referer: http://localhost/MyForms/
[Sat Oct 15 11:19:48.765519 2016] [:error] [pid 6780:tid 1680] [client ::1:50539] PHP Warning:  Invalid argument supplied for foreach() in C:\\xampp\\htdocs\\MyForms\\dompdf\\lib\\php-font-lib\\src\\FontLib\\Table\\Type\\cmap.php on line 129, referer: http://localhost/MyForms/
[Sat Oct 15 11:19:48.775519 2016] [:error] [pid 6780:tid 1680] [client ::1:50539] PHP Warning:  max(): Array must contain at least one element in C:\\xampp\\htdocs\\MyForms\\dompdf\\lib\\Cpdf.php on line 2593, referer: http://localhost/MyForms/
[Sat Oct 15 11:19:48.775519 2016] [:error] [pid 6780:tid 1680] [client ::1:50539] PHP Warning:  Cannot use a scalar value as an array in C:\\xampp\\htdocs\\MyForms\\dompdf\\src\\Adapter\\CPDF.php on line 926, referer: http://localhost/MyForms/
`

**Comment by bsweeney** [comment]
Could be an issue with parsing your font. I see a similar error mentioned in PhenX/php-font-lib#40.

**Comment by Stone-Ynn** [comment]
I have the same question. I had see the https://github.com/dompdf/dompdf/wiki/UnicodeHowTo, install the firefly.ttf, but it can't be work.

**Comment by MichaelEugeneYuen** [comment]
@denisosteo 

Hope this helps

```
/**
     * Streams the PDF to the client.
     *
     * The file will open a download dialog by default. The options
     * parameter controls the output. Accepted options (array keys) are:
     *
     * 'compress' = > 1 (=default) or 0:
     *   Apply content stream compression
     *
     * 'Attachment' => 1 (=default) or 0:
     *   Set the 'Content-Disposition:' HTTP header to 'attachment'
     *   (thereby causing the browser to open a download dialog)
     *
     * @param string $filename the name of the streamed file
     * @param array $options header options (see above)
     */
    public function stream($filename = "document.pdf", $options = array())
```

```
<?php
// reference the Dompdf namespace
ini_set('display_errors',1); // enable php error display for easy trouble shooting
error_reporting(E_ALL); // set error display to all
require_once "dompdf/autoload.inc.php";
use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();

// create pdf content
// $html = 'Hello world !!!';
$html = '<html>';
$html .= '<head>'.PHP_EOL;
$html .= '<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>'.PHP_EOL;
$html .= '</head>'.PHP_EOL;
$html .= '<body>'.PHP_EOL;
$html .= '<p style="font-family: \'Droid\', sans-serif;">献给母亲的爱</p>'.PHP_EOL;
$html .= '</body>'.PHP_EOL;
$html .= '</html>';

$dompdf->loadHtml($html);

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'portrait');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
// stream(filename [without .pdf], 1 compress, 1 force save dialog)
$dompdf->stream('without.pdf',array('compress'=>1,'attachment'=>1));
?>
```

![akg](https://user-images.githubusercontent.com/25918819/31045693-c03575e4-a61b-11e7-9c04-c526f94797a3.jpg)
