### ISSUE TITLE
border not show on table tr

### ISSUE THREAD

**Issue by jeck5895** [dompdf/dompdf#1284]
Why does table tr border not showing on pdf but it does how on html?

**Comment by bsweeney** [comment]
How do you mean? Do you have some sample HTML+CSS?

**Comment by jeck5895** [comment]
`<style>
						tr.borderOK{
							border-bottom: 2px solid black;
							font-size:11px;
							font-weight:800;
						}
					</style>
                                        <tr class="borderOK">
								<td ><strong>NET PAY:</strong></td>
								<td></td>
								<td></td>
								<td align="right"><strong>5,699.11</strong></td>
							</tr>`

**Comment by jeck5895** [comment]
that is my sample html that I'm converting to pdf but the border is not showing while the other css are working

**Comment by bsweeney** [comment]
May also need to style your table with `border-collapse: collapse` (because without this some browsers also do not show a border). But yes, dompdf doesn't appear to handle this correctly.

**Comment by jeck5895** [comment]
Thank you for your response !. TCPDF does have the same bug XD

**Comment by RodrigoDavid** [comment]
Will it be fixed?

**Comment by saurabh-nichi** [comment]
`<table style="border-collapse:collapse;">
        <tr>
            <td style="border:1px solid #000; text-align: center;padding: 4px;">Item Code</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">Item name</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">Item unit</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">Estimate unit price</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">Remarks</td>
        </tr>
        @php($baseController = (new \App\Http\Controllers\Controller()))
        @if(array_first($data['items']))
        @foreach($data['items'] as $item)
        <tr>
            <td style="border:1px solid #000; text-align: center;padding: 4px;">{{$item->item_code}}</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">{{$item->item_name}}</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">{{$item->item_unit}}</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">{{$baseController->formatNumber($item->estimate_item_price, $data['numberFormattingInfo'])}}</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">{{$item->item_note}}</td>
        </tr>
        @endforeach
        @endif
        <tr>
            <td colspan="6" rowspan="1" style="border:1px solid #000; padding: 4px;">
                <div style="height: 200px;">name</div>
            </td>
        </tr>
    </table>`

I am facing this same issue, any possible resolutions yet?

**Comment by saurabh-nichi** [comment]
<table style="border-collapse:collapse;">
        <tr>
            <td style="border:1px solid #000; text-align: center;padding: 4px;">Item Code</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">Item name</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">Item unit</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">Estimate unit price</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">Remarks</td>
        </tr>
        @php($baseController = (new \App\Http\Controllers\Controller()))
        @if(array_first($data['items']))
        @foreach($data['items'] as $item)
        <tr>
            <td style="border:1px solid #000; text-align: center;padding: 4px;">{{$item->item_code}}</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">{{$item->item_name}}</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">{{$item->item_unit}}</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">{{$baseController->formatNumber($item->estimate_item_price, $data['numberFormattingInfo'])}}</td>
            <td style="border:1px solid #000;text-align: center;padding: 4px;">{{$item->item_note}}</td>
        </tr>
        @endforeach
        @endif
        <tr>
            <td colspan="6" rowspan="1" style="border:1px solid #000; padding: 4px;">
                <div style="height: 200px;">name</div>
            </td>
        </tr>
    </table>

I am facing the same issue, any resolutions so far?

**Comment by saurabh-nichi** [comment]
Well, just found a solution that worked for me, 
Use `border-spacing: -1px;` instead of `border-collapse: collapse;`.

Go here: https://stackoverflow.com/questions/16782160/dompdf-table-border-issue/62280334#62280334

**Comment by Mellthas** [comment]
Borders of table rows are now taken into consideration with `border-collapse: collapse`, see 36201f3b8bc5257b4aa8f1899f07dee00774e1aa.
