### ISSUE TITLE
Namespace use in Cpdf

### ISSUE THREAD

**Issue by duprasf** [dompdf/dompdf#1285]
I'm not sure if I'm the only (or first) one to find/report this problem, I did a quick search in your issues and could not find someone that reported it already. Sorry if this is a duplicate.

When using Dompdf on a server with Imagick I get a class not found error. In the Cpdf class, the class Imagick is called without the backslash or a `use` statement at the top so the code is looking for the `DompdfLib\Imagick` class.
https://github.com/dompdf/dompdf/blob/master/lib/Cpdf.php#L4406

It can be resolved easily by adding the `use Imagick;` statement at the beginning of the file. 

I'm guessing it would cause the same problem with the Gmagick class
https://github.com/dompdf/dompdf/blob/master/lib/Cpdf.php#L4371

**Comment by bsweeney** [comment]
Surprisingly first we've heard of it 😮!

**Comment by bsweeney** [comment]
Interesting error, though. That namespace isn't used by dompdf. Also CPDF isn't namespaced so it should reference the global namespace, yes? How are you using dompdf?

**Comment by bsweeney** [comment]
However this comes about we'll probably also need to be more specific about any other class names that aren't specific to dompdf (e.g. when we use the global Exception class).

**Comment by duprasf** [comment]
I my god, you are so right! I had to add the namespace of that class (called it ```namespace DompdfLib;```) to have it autoloaded. I used Dompdf to create a PdfViewModel in Zend Framework 2. This basically use all the same view model process as other (setting variable and options) but instead of a web page it returns a PDF.

I checked your commit and it would not fix all the problem if you (or someone else) decide to give this class a namespace since you have other reference to the Imagick class that are not preceded by the backslash. Everywhere that you use a constant from that class would also need the backslash, that's why I used the ```use Imagick;``` instead. 

Thanks for the quick response and sorry I reported a bug that I created myself...

**Comment by bsweeney** [comment]
Ah yeah, I see. I forgot to fix the static property references. I wanted to be more explicit with the class usage. I notice that if you add a `use` statement of that type then PHP will throw the following warning:

> Warning: The use statement with non-compound name 'Imagick' has no effect

We see questions regularly enough about non-halting PHP message (e.g. undefined index) that I don't want to add something that will generate more. I'll go back and fix up the rest of the references.

**Comment by bsweeney** [comment]
Hopefully I got them all that time.

**Comment by bsweeney** [comment]
I think we've got this one. If the issue turns out to still be present please post back.
