### ISSUE TITLE
Issue loading auto include on windows

### ISSUE THREAD

**Issue by nibblebits** [dompdf/dompdf#1286]
Message: require_once(C:\xampp\htdocs\private_dir\s\application\libraries\dompdf/lib/php-font-lib/src/FontLib/Autoloader.php): failed to open stream: No such file or directory

```
<?php

use Dompdf\Dompdf;
use Dompdf\Options;
require_once 'dompdf/autoload.inc.php';

class Pdf {

   public function getNewDomObj()
   {

       // instantiate and use the dompdf class
$dompdf = new Dompdf();
$dompdf->loadHtml('hello world');

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'landscape');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream();
   }
}
```

**Comment by bsweeney** [comment]
How are you retrieving dompdf? autoload.inc.php is included for use only when you're using the package release. If you're using Composer you should use the Composer autoloader. If you're grabbing the source code directly you'll need to separately fetch third-party libraries (php-font-lib, php-svg-lib).

**Comment by nibblebits** [comment]
Do you not have a guide I could follow?

Thanks

**Comment by bsweeney** [comment]
If you're not familiar with Composer I suggest downloading the packaged release. Current stable is [0.7.0](https://github.com/dompdf/dompdf/releases/download/v0.7.0/dompdf_0-7-0.zip).
