### ISSUE TITLE
HTM5 Support

### ISSUE THREAD

**Issue by pcfreak30** [dompdf/dompdf#1287]
With the following html, https://gist.github.com/pcfreak30/1b1b7900b7fdd0a9761f515be8fce59f, The rendering breaks in multipage due to the use of the main tag. I have tracked it down to Cellmap and its link to Table. A new cellmap gets created on a new page, and removes frame entries. Cellmap then tries to do a in_array on null for cells and columns. This is as far as I have bothered to debug the logic flow.

Thanks.

**Comment by bsweeney** [comment]
Not sure what this has to do with HTML5. Are you using dompdf 0.5.1?

**Comment by pcfreak30** [comment]
No, latest dompdf. And last i checked main was a html5 tag.

**Comment by bsweeney** [comment]
My comment was because I don't see a `main` tag in your gist.

**Comment by pcfreak30** [comment]
My bad, updated gist

**Comment by bsweeney** [comment]
OK, yeah. I see it now. The quick fix on your end would be to style your main element with `display: block;`.

**Comment by pcfreak30** [comment]
Thanks. Changing to a div worked without side effects but HTML5 does need actual support :).

**Comment by bsweeney** [comment]
Perhaps time to update our default CSS with the latest from Mozilla:
https://dxr.mozilla.org/mozilla-central/source/layout/style/res/html.css
