### ISSUE TITLE
Full documentation

### ISSUE THREAD

**Issue by AnarchyChampion** [dompdf/dompdf#1289]
Hi there!

Sorry for bothering you, but your wiki is a little bit poor of information.
I think this kind of module need a more detailed documantation.

AC

**Comment by bsweeney** [comment]
What type of documentation are you seeking?

**Comment by AnarchyChampion** [comment]
I see, you have a wiki. It's enough to generate a simple pdf, but if you wanted to generate a complex file, then that documentation is not enough to start.

E.g.: how to insert header/footer, page number, how to use float css, how to use page-breaks, etc.

I spent lot of work to figure it out (ofc I had to google too a lot), but if there was a detailed documentation, I wouldn't had to.

**Comment by bsweeney** [comment]
Point taken. We used to have a site linked from the README with a number of samples. We can add a few samples to the readme as we tidy up the documentation for the next release.

**Comment by bsweeney** [comment]
Some community support in this regard would be appreciated. But I have added a "[common use cases](https://github.com/dompdf/dompdf/wiki/Common-Use-Cases)" document to the wiki. Currently only has information on displaying a header/footer, and how to use counters to display the current page number.

**Comment by Mellthas** [comment]
I went ahead and updated the the [CSS compatibility page](https://github.com/dompdf/dompdf/wiki/CSSCompatibility) for 1.1.0.

**Comment by bsweeney** [comment]
Appreciated! I'm also planning to review it to see if anything is missing or needs an update.
