### ISSUE TITLE
TableCell line 66

### ISSUE THREAD

**Issue by EngEryx** [dompdf/dompdf#1291]
I have been trying to populate table  rows on this template using foreach

```
<table>
<thead>
<th>Head 1</th>
<th>Head 2</th>
</thead>
<tbody>
@for($i =0; $i < 20; $i++)
<tr><td>row {{$i}} col 1</td><td>row {{$i}} col 2</td></tr>
@endfor
</tbody>
</table>
```

.... But i keep getting this error: 

> ```
> ErrorException in TableCell.php line 66: in_array() expects parameter 2 to be array, null given
> in TableCell.php line 66 at HandleExceptions->handleError('2', 'in_array() expects parameter 2 to be array, null given',
> '/var/www/html/tenacle-dash/vendor/dompdf/dompdf/src/Renderer/TableCell.php', '66', array('frame' => object(TableCell), 'style' => object(Style), 'x' => '0', 'y' => '0', 'w' => 'auto', 'h' => 'auto', 'bg' => array('0.34117647058824', '0.69803921568627', '0.13725490196078', null, 'hex' => '#57b223', 'r' => '0.34117647058824', 'g' => '0.69803921568627', 'b' => '0.13725490196078'), 'url' => 'none', 'table' => object(Table), 'cellmap' => object(Cellmap), 'cells' => null, 'num_rows' => '0', 'num_cols' => '0', 'i' => null, 'top_row' => array('y' => '0', 'first-column' => '0', 'height' => null)))
> ```

As you can see I am using Laravel Framework. If i loop for a few rows it works fine...
Has anyone come across this issue.

**Comment by bsweeney** [comment]
Does that PHP represent the actual HTML causing the error, or is it a simplification (I'm unable to reproduce the error)?

**Comment by EngEryx** [comment]
It was just a simplification of what I am trying to do. 
![screenshot from 2016-10-27 17 48 43](https://cloud.githubusercontent.com/assets/10976009/19773736/595ed1ba-9c73-11e6-8c42-1d5f840a6b90.png)
I am trying to create a small invoice template. So I wanted to know how the page breaks will occur just incase the number of entries in the invoice go beyond those that can fit on a single page. 
Trying to create 20 rows on my template using foreach but I get the above error
`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Tenacle</title>
    <link rel="stylesheet" href="{{asset("pdf/style.css")}}" media="all" />
</head>
<body>
<header class="clearfix">
    <div id="logo">
        <img src="{{asset("pdf/logo.png")}}">
    </div>
    <div id="company">
        <h2 class="name">Company Name</h2>
        <div>455 Foggy Heights, AZ 85004, US</div>
        <div>(602) 519-0450</div>
        <div><a href="mailto:company@example.com">company@example.com</a></div>
    </div>
</header>

<main>
    <div id="details" class="clearfix">
        <div id="client">
            <div class="to">INVOICE TO:</div>
            <h2 class="name">John Doe</h2>
            <div class="address">796 Silver Harbour, TX 79273, US</div>
            <div class="email"><a href="mailto:john@example.com">john@example.com</a></div>
        </div>
        <div id="invoice" class="clearfix">
            <h1>INVOICE 3-2-1</h1>
            <div class="date">Date of Invoice: 01/06/2014</div>
            <div class="date">Due Date: 30/06/2014</div>
        </div>
    </div>

    <table border="0" cellspacing="0" cellpadding="0" id="tablediv">
        <thead>
        <tr>
            <th class="no">#</th>
            <th class="desc">DESCRIPTION</th>
            <th class="unit">UNIT PRICE</th>
            <th class="qty">QUANTITY</th>
            <th class="total">TOTAL</th>
        </tr>
        </thead>
        <tbody>
            @for($i =0; $i < 10; $i++)
                <tr id="tablediv" class="page-breaks">
                    <td class="service">SEO</td>
                    <td class="desc">Optimize the site for search engines (SEO)</td>
                    <td class="unit">$40.00</td>
                    <td class="qty">20</td>
                    <td class="total">$800.00</td>
                </tr>
                <div style="page-break-after:always;">
             @endfor
        </tbody>
        <tfoot>
        <tr>
            <td colspan="2"></td>
            <td colspan="2">SUBTOTAL</td>
            <td>$5,200.00</td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <td colspan="2">TAX 25%</td>
            <td>$1,300.00</td>
        </tr>
        <tr>
            <td colspan="2"></td>
            <td colspan="2">GRAND TOTAL</td>
            <td>$6,500.00</td>
        </tr>
        </tfoot>
    </table>
    <div id="thanks">Thank you!</div>
    <div id="notices">
        <div>NOTICE:</div>
        <div class="notice">A finance charge of 1.5% will be made on unpaid balances after 30 days.</div>
    </div>
</main>
<footer>
    Invoice was created on a computer and is valid without the signature and seal.
</footer>
</body>
</html>`
 That's the invoice template  without the css file,,,
When I reduce the number of rows to 6, It works fine..
![screenshot from 2016-10-27 18 35 18](https://cloud.githubusercontent.com/assets/10976009/19773964/2d8089ca-9c74-11e6-9a2c-d42ca30b5ee4.png)

but in the real field,i might have an invoice that has 25 entries....

**Comment by bsweeney** [comment]
Two quick things that should help:

First, you should [validate](https://validator.w3.org) your generated HTML. You have a `div` element between table rows (at the bottom of your `for` loop. This isn't a valid HTML document structure and dompdf doesn't always handle invalid document structure well.

Second, avoid HTML5 elements (e.g. `main`) until v0.7.1. Currently dompdf does not deal with them correctly and they can cause rendering issues.

**Comment by gemox94** [comment]
Hi there. I had the same problem and as @bsweeney  said, in the second advaice, I had to remove the <main> tag so it worked for me.
Thanks a lot.
P.S I'm also using Laravel

**Comment by EngEryx** [comment]
It worked after rewriting the html properly...
