### ISSUE TITLE
 PDF engines have access to custom font files for headings .

### ISSUE THREAD

**Issue by SakaSerbia** [dompdf/dompdf#1294]
I write css style. Like this:

```
@font-face {
  font-family: PT-Serif-Regular;
  src: url(pt-serif.regular.ttf);
}

body {
  font-family: PT-Serif-Regular, sans-serif;
}
```
Everything under paragraph is the font that I want.

The problem occurs in the title. 

http://prntscr.com/d049et

Is there a difference between paragraphs and headings .

The text under h1 and h2, are not recognizable.

**Comment by bsweeney** [comment]
Since H1 and H2 are bold you also have to define the font file to use for that variant of your font family.

**Comment by SakaSerbia** [comment]
Its work. 

http://prntscr.com/d04jcl

Thank you a lot.

**Comment by bsweeney** [comment]
Might have to update the documentation about that...
