### ISSUE TITLE
not downloading pdf file

### ISSUE THREAD

**Issue by tylerjnorin** [dompdf/dompdf#1298]
My php file will run fine but it will not download the file to my download folder. I don't have a specified path to download anywhere, so I believe it should simply download to the browser but does not. Please help.

I have a require once of the autoload.inc.php and use Dompdf\Dompdf;

Also,

```
$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
$dompdf->stream("Case");
```

**Comment by bsweeney** [comment]
What does happen?

**Comment by tylerjnorin** [comment]
My php file runs fine through developer tools completely but a pdf is not produced. No errors are thrown.

**Comment by bsweeney** [comment]
You might try ending execution of the file. There have been instances where the process does not end, causing the PDF to not download. Try adding an `exit;` statement after the dompdf code. Could also be related to #1282.
