### ISSUE TITLE
ErrorException in Cellmap.php line 800: Undefined offset: 515

### ISSUE THREAD

**Issue by ravor44** [dompdf/dompdf#1300]
It keeps on returning the error mentioned above. Also attached the HTML code and the error screenshot.
Any feedback would be appreciated.

[table_format.txt](https://github.com/dompdf/dompdf/files/574921/table_format.txt)
![error_1](https://cloud.githubusercontent.com/assets/20811624/20052442/0493b73c-a50f-11e6-9e33-d437311ccdd1.PNG)

**Comment by MattRogowski** [comment]
Same issue I have in #1295
