### ISSUE TITLE
Error generating TOC while using UTF-8

### ISSUE THREAD

**Issue by BillTheGoat** [dompdf/dompdf#1302]
This took me a while to track down because I have a complex documents structure; it is now distilled to the root problem.

Using v0.7.0 from Master, I can get [the TOC example](http://eclecticgeek.com/dompdf/debug.php?identifier=toc-v0.6.x) for v0.6 to work simply by changing `$font = Font_Metrics::get_font("helvetica", "bold");` to `$font = $fontMetrics->getFont("helvetica", "bold");`.

However, if I add a head above the body with:

```
<style>
     *{ font-family: DejaVu Sans;}
</style>
```

Instead of replacing the placeholders to read:

```
1. Chapter 1 ....................... page 2
2. Chapter 2 ....................... page 2
3. Chapter 3 ....................... page 4
```

the TOC is inserted like:

```
1. Chapter 1 ....................... page %%CH1%%
2. Chapter 2 ....................... page %%CH2%%
3. Chapter 3 ....................... page %%CH3%%
```

I use UTF-8, so this is a requirement. I don't really know what the next steps here are. Thanks.

**Comment by BillTheGoat** [comment]
It appears that a null byte is added before _every_ character in text fields so `[(text)]` becomes` [(\0t\0e\0x\0t)]` in the utf-8 version, as can be seen by adding in:

```
$checkBackside = addslashes(print_r($pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'], true));
error_log('backside = '.$checkBackside);
```

Thus, it is no problem for me to match one character, so I can replace `%` with `$page`.
 To be sloppy, I can insert some `**probably**` absent character and loop on it using a limited `preg_replace` instead of using named array keys, e.g. using `¥` like:

```
foreach($GLOBALS['chapters'] as $chapter => $page) {
		$pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'] = preg_replace( '/\xa5/i' , $page , $pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'], 1 );
```

But of course there is a major problem: if we are only replacing one character, and the page number is 10 or above, only the first digit will display because no space has been allotted for two characters.

**Comment by BillTheGoat** [comment]
Kludging it all together:

```
foreach($GLOBALS['chapters'] as $chapter => $page) {
		if(strlen($page) == 1) {
		$pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'] = preg_replace( '/\xa5/i' , ' ' , $pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'], 2 );
		$pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'] = preg_replace( '/\xa5/i' , $page , $pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'], 1 );
		} else if(strlen($page) == 2) {
		$pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'] = preg_replace( '/\xa5/i' , ' ' , $pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'], 1 );
		$pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'] = preg_replace( '/\xa5/i' , substr($page,0,1) , $pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'], 1 );
		$pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'] = preg_replace( '/\xa5/i' , substr($page,1,1) , $pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'], 1 );
		} else if(strlen($page) == 3) {
		$pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'] = preg_replace( '/\xa5/i' , substr($page,0,1) , $pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'], 1 );
		$pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'] = preg_replace( '/\xa5/i' , substr($page,1,1) , $pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'], 1 );
		$pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'] = preg_replace( '/\xa5/i' , substr($page,2,1) , $pdf->get_cpdf()->objects[$GLOBALS['backside']]['c'], 1 );
		}
```

/hangsHeadInShame

**Comment by bsweeney** [comment]
Hm, yes, I didn't take into account Unicode encoding. You should be able to use the CPDF library to encode your replacement text. I'll see if I can update the code.

You should also be able to specify a core font to avoid the Unicode encoding of the replacement text.

```
<ol>
	<li>Chapter 1 ....................... page <span style="font-family: sans-serif;">%%CH1%%</span></li>
</ol>
```

**Comment by BillTheGoat** [comment]
I switched to use single character because the template rather than the replacement determines the space in the pdf. I need to stick with unicode so everything is in the same font, but that kludge at least can tide me over for now. Thanks for your awesome library.
