### ISSUE TITLE
Pdf not render in chrome browser

### ISSUE THREAD

**Issue by wilariz** [dompdf/dompdf#1303]
Hi.
I have a problem with render pdf, it happends in chrome browser (mozila firefox is ok). I use nginx +zend server +php 7.0.11 + zendframework 3 + dompdfmodule for zf3
In apache is ok, and others PC with my same configuration work fine.
I found reference to same error here 
http://stackoverflow.com/questions/34599266/pdf-generation-results-in-err-invalid-response-in-chrome

I hope your help
Thank you

**Comment by bsweeney** [comment]
Did the answer on SO not help? Looks like the problem there was related to mod_security. What do you see in the Chrome dev tools as far as the network traffic? Seems to be browser-specific, a little more details on what types of errors your seeing would help.

**Comment by Kilgaloon** [comment]
This is very weird. I had same bug when i do $dompdf->stream(date('Y') . 'pdf'); i get Invalid response in every browser but when i wrap die($dompdf->stream(date('Y') . 'pdf')); it start download. dafaq
