### ISSUE TITLE
Is there a work around for "A non-numeric value encountered" in 7.1?

### ISSUE THREAD

**Issue by sunscreem** [dompdf/dompdf#1305]
I'm using php 7.1 and can't get dompdf to play nicely. I've tried using the latest version off the dev branch in the hope that might solve it. Its a long shot but anyone got an suggestions? (other than going back to 7.0 lol)

**Comment by bsweeney** [comment]
Sorry, not yet. You might follow #1272 to see if a PR comes in. We were planning to address this in 0.7.2, but looks like we may want to do it for the next release.

**Comment by bsweeney** [comment]
The stable branch should be ok on PHP 7.1.0 now. Look for a release soon.

**Comment by rpmconsulting** [comment]
I'm on PHP Version 7.1.14 and having this issue... Warning: A non-numeric value encountered in .../path/...../includes/includes.php on line 94.
This is line 94 in the file:  $mainContentWidth = 12 - ($asideLeftWidth + $asideRightWidth);

**Comment by bsweeney** [comment]
@rpmconsulting that's not from our code. If it's your own code try casting to int/float (and [StackOverflow](http://stackoverflow.com)). For example:

```
$mainContentWidth = 12 - ((int)$asideLeftWidth + (int)$asideRightWidth);
```
