### ISSUE TITLE
Issue with pdf generate

### ISSUE THREAD

**Issue by mukeshzt** [dompdf/dompdf#1306]
I'm using the dompdf but I was facing one issue with the formatting. 

In my application, we accepting the data from end users and based on provided data we create pdf using dompdf. (using PHP)
The issue is when end users copy data from word document/ existing other pdf and paste into provided text area. so its include the word formatting and bullets and all. It's stored as it is in my database, Once I send that information to dompdf then dompdf skip the formatted data and generate blank pdf.

**Comment by bsweeney** [comment]
Could be some difficulty dealing with the Word-formatted HTML. If users type the content in do things appear correctly? Do you have a sample of the HTML/CSS being parsed by dompdf?
