### ISSUE TITLE
Does dompdf support thai font?

### ISSUE THREAD

**Issue by maninnovation** [dompdf/dompdf#1311]
i would like to know that your library support Thai font or not? (on v0.7)

After we added font as your advise then it still not work and its display with square picture. Could you kindly advise more, if there are any solution to resolve this issue please.

**Comment by bsweeney** [comment]
Have you read through the [Unicode How-to](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo)? Can you post sample HTML/CSS and the PHP that implements Dompdf?

**Comment by maninnovation** [comment]
thank you very much

**Comment by LiguoMa274** [comment]
I can not use dompdf for Thai font
Please check this
https://prnt.sc/reiscf
And let me know why I have this issue

**Comment by simonberger** [comment]
To understand the issue you have we would need to know the thai language
Please add this thai sentence of text to a html sample so we can have a look how the browser renders it correctly.

**Comment by LiguoMa274** [comment]
Thanks for your fast response
I use this sentence for invoice 
"400/735 หมู่ที่ 12 ตำบลหนองปรือ อำเภทบางละมุง จังหวั
ดชลบุรี" with borwa_new font
As you can see on this character "ที่" has 3 characters
But I can not see the top character
Best Regards

**Comment by simonberger** [comment]
I got your issue now. You could try to increase the line height as it looks like it just can't render the rest of it. If this does not solve your problem please add a new issue here including a HTML example with an included font. This is an closed issue.
