### ISSUE TITLE
First page different than other page

### ISSUE THREAD

**Issue by SakaSerbia** [dompdf/dompdf#1312]
Is it posible to make first page different from other using dompdf?

**Comment by bsweeney** [comment]
Different in what way?

**Comment by SakaSerbia** [comment]
This is my code:

```
<header>header on each page</header>
<div class="page node-print-style">
    {{ content }}
</div>
<footer>footer on each page</footer>
```

In CSS i write this:

```
@page { margin-top: 1.9cm; margin-left:1.9cm; margin-right: 1.32cm; margin-bottom: 3.67cm; }
@page :first { margin-top: 2.54cm; margin-left:1.9cm; margin-right: 1.32cm; margin-bottom: 3.67cm;   }

header { position: fixed; top: -1.9cm; height: 50px; }
footer { position: fixed; bottom: -3.67cm; height: 50px; }
```

New I try header:first, header:first-of-type But in all this case I have header on front page.

I dont know how, but there is no footer on front page.

How to make that header is hide on front page?

**Comment by bsweeney** [comment]
Fixed-position content is rendered starting on the page on which it is encountered. So if your footer after your document content in the HTML source it will only display on the last page.

If you know where the first page ends you can easily keep the header/footer off that page by placing them after the first-page content. If you do not know where it ends the process is a bit trickier, but still possible.

**Comment by SakaSerbia** [comment]
I solve the problem.. Thank you a lot..

**Comment by mujtabaahmad1985** [comment]
> I solve the problem.. Thank you a lot..
HI Saka, 

I want to show some div on other than 1st page, how i can do it. can you help me?

Thanks
