### ISSUE TITLE
Class 'Dompdf/Dompdf' not found 

### ISSUE THREAD

**Issue by fizdalf** [dompdf/dompdf#1313]
I'm using dompdf v0.7.0, installed through Composer, and I'm getting this error with this code:

```
require_once 'vendor/autoload.php';

use Dompdf\Dompdf as Dompdf;


$dompdf = new Dompdf();
$dompdf->loadHtml('hello world');

$dompdf->setPaper('A4', 'portrait');

$dompdf->render();

$dompdf->stream();
```

I made sure other Composer depencies are available and load fine.

What should I try next?

**Comment by bsweeney** [comment]
Your use statement should be `use Dompdf\Dompdf;`. I believe (and someone feel free to correct me) that since you're aliasing the Dompdf namespace you would have to refer to the alias when instantiating the class (`$dompdf = new Dompdf\Dompdf()`).

**Comment by Soullivaneuh** [comment]
@fizdalf Are you sure you run the composer update command after including Dompdf?

I test the same code as you:

```
require_once 'vendor/autoload.php';

use Dompdf\Dompdf as Dompdf;

$dompdf = new Dompdf();
$dompdf->loadHtml('hello world');

$dompdf->setPaper('A4', 'portrait');

$dompdf->render();

$dompdf->stream();
```

And it works perfectly.

**Comment by Soullivaneuh** [comment]
BTW, why not just `use Dompdf\Dompdf;`? The result is the same AFAIK! :wink:

**Comment by alfred-saker** [comment]
bonjour desolé de revenir sur ce vieux sujet:
j'ai installer dompdf manuellement et j'ai  obtenu la même erreur:"Classe 'dompdf \ dompdf' introuvable"
voici mon fichier pdf.php qui se trouve dans ma librairy:
<?php defined('BASEPATH') OR exit('No direct script access allowed');

  require_once dirname(__FILE__).'/dompdf/src/autoloader.php';
 use dompdf\dompdf as dompdf;

class Pdf
{ 
  public function __construct()
  {
   
    $pdf = new dompdf(); 
    $CI = &get_instance();
    $CI->dompdf=$pdf; 
  } 
}
?>
 j'utilise le framework codeigniter 3.1.10 php
besoin d'aide svp

**Comment by MatheusSGomes** [comment]
I've been the same error, for me works run this command:
```
php composer.phar update
```
and then I reload window in my vs code.

**Comment by alfred-saker** [comment]
Hello

You put fine the library Dompdf in your folder project?

Le dim. 12 juin 2022 à 19:06, Matheus Gomes ***@***.***> a
écrit :

**Comment by MatheusSGomes** [comment]
> 

no, I use `composer require dompdf/dompdf`, it puts dompdf in folder **vendor**, and doesn't work. The only solution that works for me was run command `php composer.phar update`.

**Comment by alfred-saker** [comment]
Okay. You using Dompdf with native php or with any framework?
If it's with a framework, go the documentation or YouTube check the video
corresponding with our problem.
Also if you use composer, means you use them to install Dompdf. It's that?

Tell me after.

Le lun. 13 juin 2022 à 00:10, Matheus Gomes ***@***.***> a
écrit :
