### ISSUE TITLE
Google Chart image does not work

### ISSUE THREAD

**Issue by jor3l** [dompdf/dompdf#1316]
Hello, 

I'm working on generating a PDF with charts and I decided to implement GoogleCharts API. I have tried setting data:image or the URL but both give me the same result, no image at all.

This is one of the URLs: https://chart.googleapis.com/chart?cht=p&chds=a&chtt=Razones+de+rechazo&chs=700x280&chdl=Cancelado+por+decisi%C3%B3n+del+usuario.|El+restaurante+est%C3%A1+cerrado.|No+fue+posible+comunicarse+con+el+restaurante.|No+fue+posible+comunicarse+con+el+usuario.&chdls=FAA43A,11|5DA5DA,11|60BD68,11|4D4D4D,11&chdlp=t&chd=t:23,3,7,2&chxt=x,y,x,y&chxl=1:||0:||El%20restaurante%20est%C3%A1%20cerrado.||No%20fue%20posible%20comunicarse%20con%20el%20usuario.|2:|Cancelado%20por%20decisi%C3%B3n%20del%20usuario.||No%20fue%20posible%20comunicarse%20con%20el%20restaurante.|&chco=FAA43A&chm=v,BBCCED,0,-1,1.0|o,FAA43A,0,-1,5.0|N*p2*,888888,0,,8,0,ht::10&chxs=3,N*p2*&chma=100,40,40,40

Any idea what could be the issue?

Remote is enable, at least I think so:

```
    $options = new Options();
      $options->set('defaultFont', 'Courier');
      $options->set('isRemoteEnabled', true);
      $options->set('debugPng', true);
    
      $dompdf = new Dompdf($options);
      $context = stream_context_create(array(
          'ssl' => array(
              'verify_peer' => FALSE, 
              'verify_peer_name' => FALSE,
              'allow_self_signed'=> TRUE 
          )
      ));
      
      $dompdf->setHttpContext($context);

      $dompdf->loadHtml($reporte);
      $dompdf->setPaper('legal', 'landscape');
      $dompdf->render();
```

**Comment by bsweeney** [comment]
I was able to load the image just fine. What does your HTML look like? Does your installation meet the [minimum requirements](https://github.com/dompdf/dompdf/wiki/Requirements)?

**Comment by lmontenegro** [comment]
I have the same problem. 

You solved this?

**Comment by jor3l** [comment]
@lmontenegro sort of, found two ways to do this, one is to get the URL content and put the image as data: with base64, or save the image in a temp folder and then delete those images. With the later I'm able to cache that by setting the filename as the md5 of the content.

**Comment by lmontenegro** [comment]
I doing with base64, but not work :(... Here is my code:

`$html =<<<XYZ

<html>

<head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">

    <link href="../css/bootstrap.min.css" rel="stylesheet">

    
    <link href="../bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    
    <link href="../dist/css/timeline.css" rel="stylesheet">

    <link href="../css/jquery.datetimepicker.css" rel="stylesheet">

    
    <link href="../dist/css/sb-admin-2.css" rel="stylesheet">

    
    <link href="../bower_components/morrisjs/morris.css" rel="stylesheet">



    
    <link rel="stylesheet" href="../fonts/Font-Awesome/css/font-awesome.min.css">
    
    <link href="../css/style.css" rel="stylesheet" type="text/css">
    <link href="../css/bootstrap-select.css" rel="stylesheet" type="text/css">
    <link href="../css/bootstrap-select.css" rel="stylesheet" type="text/css">
    <link href="../css/jquery.dataTables.min.css" rel="stylesheet" type="text/css">
    <link href="../css/jquery-ui/jquery-ui.min.css" rel="stylesheet" type="text/css">
    
    <script src="../bower_components/tinymce/tinymce.min.js"></script>
    <script src="../bower_components/jquery/dist/jquery.min.js"></script>


    <script src="../js/jquery.js"></script>
    
    <script src="../js/jquery.datetimepicker.js"></script>
    <script src="../js/bootstrap-select.js"></script>
    <script src="../js/jquery.progresstimer.js"></script>
    
    
    <script src="../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    
    <script src="../bower_components/metisMenu/dist/metisMenu.min.js"></script>

    
    <script src="../dist/js/sb-admin-2.js"></script>
    <script src="../bower_components/flot/excanvas.min.js"></script>
    <script src="../bower_components/flot/jquery.flot.js"></script>
    <script src="../bower_components/flot/jquery.flot.pie.js"></script>
    <script src="../bower_components/flot/jquery.flot.resize.js"></script>
    <script src="../bower_components/flot/jquery.flot.time.js"></script>
    <script src="../bower_components/flot.tooltip/js/jquery.flot.tooltip.min.js"></script>
    <script src="../js/jquery.datetimepicker.js"></script>    
    <script src="../css/jquery-ui/jquery-ui.js"></script>
    

    <script src="../js/funciones.js"></script>
    <script src="../js/norms.js"></script>

    
    <link href="../flag-icon/css/flag-icon.css" rel="stylesheet">

    <script src="../amcharts/amcharts.js" type="text/javascript"></script>
    <script src="../amcharts/serial.js" type="text/javascript"></script>
    <script src="../amcharts/pie.js" type="text/javascript"></script>
    <script src="../amcharts/themes/light.js" type="text/javascript"></script>





    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

  <script type="text/javascript">
    google.charts.load("current", {packages:['corechart']});
    google.charts.setOnLoadCallback(drawChart);
    
    function drawChart() {

      var data = google.visualization.arrayToDataTable([
        ['Element', 'Density', { role: 'style' }],
        ['Copper', 8.94, '#b87333', ],
        ['Silver', 10.49, 'silver'],
        ['Gold', 19.30, 'gold'],
        ['Platinum', 21.45, 'color: #e5e4e2' ]
      ]);

      var options = {
        title: "Density of Precious Metals, in g/cm^3",
        bar: {groupWidth: '95%'},
        legend: 'none',
      };

      var chart_div = document.getElementById('chart_div');
      var chart = new google.visualization.ColumnChart(chart_div);

      // Wait for the chart to finish drawing before calling the getImageURI() method.
      google.visualization.events.addListener(chart, 'ready', function () {
        chart_div.innerHTML = '<img src="' + chart.getImageURI() + '">';
        console.log(chart_div.innerHTML);
      });

      chart.draw(data, options);

  }
  </script>

  <div id="example1">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><img id="logo-modulo" src="../img/vulnerabilidades.png"> &nbsp; $titulo $scanNombre</h1>
        </div>
    </div>

    <div class="container contenedor">
        <div class="row">
            <div class="col-sm-12">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="graph-reports">
                            <div id="chart_div" style="width: 1000px; height: 500px;"></div>
                            <h3>$m_144</h3>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


</head>

<body>
            
XYZ;


require_once("dompdf/autoload.inc.php");
use Dompdf\Options;
use Dompdf\Dompdf;

$options = new Options();
$options->set('defaultFont', 'Courier');
$options->set('isRemoteEnabled', true);
$options->set('debugPng', true);

$dompdf = new Dompdf($options);

$context = stream_context_create(array(
          'ssl' => array(
          'verify_peer' => FALSE, 
          'verify_peer_name' => FALSE,
          'allow_self_signed'=> TRUE,
          'dpi' => 300,
            'fontHeightRatio' => 1.2,
            'isPhpEnabled' => true,
            'isRemoteEnabled' => TRUE,
            'isJavascriptEnabled' => true,
            'isHtml5ParserEnabled' => true,
            'isFontSubsettingEnabled' => true,
          )
      ));
      
$dompdf->setHttpContext($context);
$dompdf->load_html($html);
$dompdf->render();
$dompdf->stream("mi_archivo.pdf");`

The first image work fine, but no google chart png image.

**Comment by bsweeney** [comment]
@lmontenegro it looks like you're relying on the JS library to draw the chart. Dompdf does not parse JavaScript so you'll need to have a browser render the page then submit the chart image URL that you can embed in the HTML document you feed to Dompdf.

**Comment by lmontenegro** [comment]
@bsweeney thank you for your answer... I have converted the dinamic google chart to png with base64, but it still not working.

**Comment by jor3l** [comment]
@lmontenegro tienes que de alguna forma generar el chart y guardarlo en disco para luego al generar el PDF lo vea desde ahí. No puedes ejecutar JS al momento de generar esto y veo que cargas un montón de librerías lo que probablemente te cause problemas. Trata de mantener todo lo mas simple y limpio posible

**Comment by bsweeney** [comment]
@lmontenegro sample of your code that converts to base64 and uses the image?

**Comment by jor3l** [comment]
@bsweeney suddenly my code stopped working and got a 500 internal server error. Is there a way to show errors or save a log so I can debug whats going on?

**Comment by bsweeney** [comment]
@jor3l that's a PHP setting, and whether or not you can change it depends on how you're hosting. But try adding `ini_set('display_errors', true)` to the top of your PHP script.
