### ISSUE TITLE
issue on Text above Image

### ISSUE THREAD

**Issue by cjrosero** [dompdf/dompdf#1317]
Need some help i manage to pull up the image but the thing is i want to put a text atleast at the center of the image. i tried using  position: absolute; but didnt work nothing is showing.
here my code: http://pastebin.com/XfRiP5fz

**Comment by bsweeney** [comment]
I'm not sure what I'm supposed to see since I only have the PHP source. Could you at least post an image from your web browser plus the PDF created by dompdf?

**Comment by cjrosero** [comment]
Thank you for response found some other solution. Thank you!
