### ISSUE TITLE
Blank PDF - (object value omitted)

### ISSUE THREAD

**Issue by Sajgoniarz** [dompdf/dompdf#1320]
Hi!

I just started to use library, but i even can't render example. Every time I have (object value omitted) in $pdf->dom, and page is blank. Same with copy-pasted HTML4 template.  Any ideas?

**Comment by bsweeney** [comment]
? ... can you provide more details?

**Comment by Sajgoniarz** [comment]
I use php 5.6 with apache on Windows 10 x64.  downloaded library from composer, and use it just in demo.

**Comment by bsweeney** [comment]
`$pdf->dom` is not part of our code or samples. It would help to have more details. Are you using a framework that implements dompdf? Can you share the PHP source? Maybe, also, what's your composer configuration?

**Comment by Sajgoniarz** [comment]
`#pdf->dom` was output from Xdebug. your debugging variable was empty. I download dompdf via widows composer cmd tool, and it was initiated then.

**Comment by bsweeney** [comment]
Still not sure what the setup is. How are you using dompdf? Can you show some code, please?
