### ISSUE TITLE
Laravel 5.3: Class 'Barryvdh\DomPDF\ServiceProvider' not found 

### ISSUE THREAD

**Issue by cruskai** [dompdf/dompdf#1321]
Hello,

I am getting the error Class 'Barryvdh\DomPDF\ServiceProvider' not found in Laravel 5.3 after installing via composer. I have read over a couple of other posts on the issue and couldn't find anything that helped me. I have attached my composer.json and config/app.php files. Any assistance is appreciated.

[composer and config.zip](https://github.com/dompdf/dompdf/files/619913/composer.and.config.zip)

**Comment by cruskai** [comment]
Made this post on the wrong git hub disregard

**Comment by bsweeney** [comment]
s'ok
