### ISSUE TITLE
 Class 'Dompdf' not found

### ISSUE THREAD

**Issue by adambeer** [dompdf/dompdf#1324]
I am manually including the autoload.inc.php file like so:

`require_once "includes/dompdf-master/autoload.inc.php";
$dompdf = new Dompdf();`

And am getting an error that the class isnt found. I am running PHP 5.3. This was installed by simply uploading the files from the zip file downloaded from the releases, no composer.

**Comment by bsweeney** [comment]
If you're using the latest version (which is the case if you're pulling from the master branch) then don't forget to reference the namespace.

```
require_once "includes/dompdf-master/autoload.inc.php";
use Dompdf\Dompdf;
$dompdf = new Dompdf();
```
