### ISSUE TITLE
How do i add custom fonts for the version 0.7.0?

### ISSUE THREAD

**Issue by nepalkillerperson** [dompdf/dompdf#1325]
hi,

As load_font.php does not exists in version 0.7.0. 
Is there a way to add new fonts ?

Thanks in advance

**Comment by bsweeney** [comment]
There is a version of the load_font.php script that works with dompdf 0.7.0 in the [utils project](https://github.com/dompdf/utils). But the recommended path would be to use an [`@font-face`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face) declaration in your stylesheet:

```
@font-face {
  font-family: "Some Font Name";
  src: url("http://example.com/somefont.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
}
```

**Comment by Lam784** [comment]
I tried to use @font-face, but it is not working. Can you spot anything wrong on my css?
@font-face {
  font-family: 'Impact';
  font-style: normal;
  font-weight: 400;
  src: url('/fonts/impact.ttf') format('truetype');
}
h1{
  font-family: 'Impact', Verdana, serif;
}

**Comment by bsweeney** [comment]
I don't believe there's anything wrong with the CSS. How are you loading your document? That will effect the way Dompdf translates the font path.
