### ISSUE TITLE
Examples: PDF-Views return 404

### ISSUE THREAD

**Issue by seiz** [dompdf/dompdf#1327]
All the Links to PDF-Output on your example pages (http://pxd.me/dompdf/www/examples.php) return a 404.

**Comment by bsweeney** [comment]
You can also see example renders (and provide your own HTML) on the debug helper here: http://eclecticgeek.com/dompdf/debug.php

**Comment by PhenX** [comment]
Hi, I recently reset my server, but could not put back the demo entirely. @bsweeney do you have a working "dompdf.php" that I could use for the demo ? I didn't make a backup :(

**Comment by bsweeney** [comment]
Yikes ... not sure. Where's you get that file?

**Comment by PhenX** [comment]
Hi, just to let you know that I changed my web host, and I'm currently putting back the demo, I also think I'll change the URL to be something like dompdf.net/demo (I own the domain, and dompdf.fr too).
@bsweeney I think you own dompdf.org don't you ? Too bad dompdf.com was already taken :(

**Comment by PhenX** [comment]
http://pxd.me is now up, and so as http://dompdf.net and http://dompdf.fr :)
I made a redirection from http://pxd.me/dompdf/www to http://dompdf.net

**Comment by bsweeney** [comment]
dompdf.org should now also redirect to dompdf.net
