### ISSUE TITLE
'DOMXPath::query(): Invalid expression' for '//[@href]'

### ISSUE THREAD

**Issue by twify93** [dompdf/dompdf#1329]
I am not quite sure why this is thrown and what is the cause, but currently on PHP 7.1 I see this error.
And I even don't have any links on the content.

Any clues?

**Comment by bsweeney** [comment]
Do you have a full stack trace? What about some sample HTML? We've started working on PHP 7.1 compatibility, but I haven't yet run across this message.

**Comment by twify93** [comment]
I am giving you a little bit of insight:

1. [Stylesheet.php:869](https://github.com/dompdf/dompdf/blob/master/src/Css/Stylesheet.php#L869)
2. Using 0.7.0 version with PHP 7.1.0 + Xdebug 2.5.0 + Zend Engine 3-1.0
3. Dumping the `$query` where it brakes, I get this array:
`[ 'query' => '//[@href]', 'pseudo_elements' => [] ]`
4. The html is as follow [GIST](https://gist.github.com/twify93/26e57639c44c61ffb35f5f0708cc8943)

**Comment by twify93** [comment]
This also fails:
```php
$dompdf = new Dompdf();
$dompdf->loadHtml('<!DOCTYPE html><html><head><body></body></html>');
// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4');
// Render the HTML as PDF
$dompdf->render();
 // Output the generated PDF to Browser
$dompdf->stream('filename.pdf', ['Attachment' => 0]);
```

**Comment by bsweeney** [comment]
That's probably due to something in the base stylesheet considering your test HTML. Testing with PHP 5.3-7.0 doesn't reveal any issues. I'll try with 7.1 when I get a chance.

**Comment by twify93** [comment]
Yes with both 5.6 and 7.0 we don't have issues, but with 7.1 we have.

**Comment by bsweeney** [comment]
When I render that HTML in PHP 7.1.0 I don't that error. Where DOMXPath::query() is used errors are suppressed (it's prefixed with an `@`). Is there something in your configuration that may be overriding that operator?

**Comment by twify93** [comment]
Yes this is strange... Only in our VM this happens. I will check the config and put it here.

**Comment by bsweeney** [comment]
Turns out it was a PHP 7.1 issue. Should be fixed in 89e43661, can you confirm?

**Comment by twify93** [comment]
I will check today when I boot the vagrant machine.

**Comment by twify93** [comment]
Case closed. :stuck_out_tongue: It is working correctly now.
