### ISSUE TITLE
PHP 7.1 - arithmetic with invalid strings

### ISSUE THREAD

**Issue by dsampaolo** [dompdf/dompdf#1330]
Upgrading PHP to 7.1 caused some issues related to "Notices and warnings on arithmetic with invalid strings" (see http://php.net/manual/fr/migration71.other-changes.php )

Some operations are throwing errors, such as :
`$max_y = $frame->get_position("y") + intval($margin_height);`

Adding intval() on both members do the trick, as intval('random_string') returns 0.

I'll submit a PR or my use case.

**Comment by bsweeney** [comment]
We'll be posting updates to #1272

**Comment by mohitpanjwani** [comment]
Any idea when this will be fixed? 

Really looking forward to use this on php 7.1

**Comment by bsweeney** [comment]
Working on it now, but no time frame for completion at the moment. As things are improved you should see updates in #1272.
