### ISSUE TITLE
Ignoring html input size parameter

### ISSUE THREAD

**Issue by KerwinSneijders** [dompdf/dompdf#1332]
Whenever you fill in something alike: 
`<input size="20">`
or:
`<input size="700"> `
it results in the same length, the value is totally **ignored**.

**Comment by bsweeney** [comment]
Probably just need to add an attribute translation for input. In the meantime you could use CSS to modify the width.

**Comment by bsweeney** [comment]
So ... input size is a weird attribute. I'll add the necessary translation, but really I'd say you're better off using CSS to style your inputs.
