### ISSUE TITLE
Tables with missing tbody tag gets one added around every tr - Result is much more memory use

### ISSUE THREAD

**Issue by simonberger** [dompdf/dompdf#1340]
I use Dompdf since a long time in many projects. Thanks for it. :)

Since now I never payed attention to Dompdfs options. But now I had a major memory usage problems.
One pdf listed 400 articles in a table (normally it were many less) that turned out to render 19 pages. Memory consumption was between 80 to 140 MB just for the rendering.
It was a simple pdf with no graphics or anything. I tried to debug a little bit, removed some CSS and at the end looked at the options.

After changing the option I could render the PDF with isHtml5ParserEnabled = true on every server without hitting the 128MB limit.
Using memory_get_peak_usage after the rendering showed 50MB - 140MB before and with isHtml5ParserEnabled = true showed 2MB (I know that might not be the actual correct value but the difference is still HUGE).

The result looked completely identical so for me that is quiet nice.
I write this issue because it might be a bug in case of isHtml5ParserEnabled = false or it's just a much better performance rendering in isHtml5ParserEnabled = true and you should push this setting and give a note that might be a try for everyone having problems with the memory consumption.

Every server runs Dompdf Version 0.7.0 on PHP 7.0

**Comment by bsweeney** [comment]
This isn't the effect I would expect. All that setting does is pre-filter the HTML document through the HTML5 parser. Otherwise the document is parsed in the same way as it is if the HTML5 parser is not used.

It could be that the clean-up the HTML5 parser did on your document significantly affected how it was represented when parsed. Do you have a sample of one of the documents?

**Comment by simonberger** [comment]
Ok here you go. It's the output of the 19 page pdf mentioned above and generated from a laravel template.
I took that output and anonymized it here and there. But tags and so on stayed the same.

I hope you can reproduce the different results I got.

[testexport.zip](https://github.com/dompdf/dompdf/files/685287/testexport.zip)

**Comment by simonberger** [comment]
I started to debug this problem and found a big difference with enabling the following options 

```
$options->set('debugKeepTemp', true);
$options->set('debugLayout', true);
```

With a DEACTIVATED php5 parser the debug-settings draw a red box around every Row (tr) of the table. while there was none with an activated php5 parser. I hope that helps finding the reason.

As a site note. With enabled CSS debugging I got a crash.
I'll open a separated issue for that minor problem.

**Comment by simonberger** [comment]
I got the change of the HTML5 Parser that reduces the memory usage by more than 20% in my case (80mb instead of 110mb).
It is just a ´´´<tbody>´´´ around the big table that also produces the different layout debugging output I wrote about in the last post.

**debugLayout Table without tbody**

![without_tbody](https://cloud.githubusercontent.com/assets/7163526/22183696/e94a152a-e0c3-11e6-8290-da0618abd7dd.png)

**debugLayout - Table with tbody**

![with_tbody](https://cloud.githubusercontent.com/assets/7163526/22183695/e948e36c-e0c3-11e6-9e93-7a2b91069c39.png)

**Comment by bsweeney** [comment]
Nice catch! The current behavior is definitely not very efficient.
