### ISSUE TITLE
[Question] PHP 7.0 compatability

### ISSUE THREAD

**Issue by elpiel** [dompdf/dompdf#1341]
Hello,
I see that the Readme is not updated(`PHP version 5.3.0 or higher`) and the title of the repo still says `(PHP5)`, but from what I know, there are issues with PHP 7.1 only?! Does this means that the library is actually OK(tested) with PHP 7.0 or it's not yet tested fully?

**Comment by bsweeney** [comment]
Dompdf should be fine to run under PHP 7.0. You are correct that there are some issues with 7.1 ( #1272) that we are working to address. I'm planning to add some additional parameters to my local testing environment so I get a better feel for compatibility across PHP versions. This is something we should update in the documentation.

**Comment by twify93** [comment]
Are you aiming for PHP 5 and 7/7.1 compatibility or you want to migrate to 7/7.1 and not keep backward compatibility for 5.6?

**Comment by bsweeney** [comment]
We'll be keeping 5.x compatibility for the next release. Not sure about after that, considering the lengthy period between stable releases right now. Though I have been toying around with the idea of smaller releases to fix bugs.

**Comment by twify93** [comment]
I find it a little bit strange that from 0.6 to 0.7 it brakes compatibility. Because upgrading to 0.7 forces some changes to the code itself, like using the Namespace and also using the config file when it doesn't exists anymore. I am just curious why you didn't release it as new version as a whole, like 1.0?

**Comment by Soullivaneuh** [comment]
> I find it a little bit strange that from 0.6 to 0.7 it brakes compatibility.

@twify93 please read: http://semver.org/#spec-item-4

0.x allows BC break compatibility according to semver convention.

BTW for PHP 7, I'm running this library one it from a while without any problem so far.

**Comment by bsweeney** [comment]
Truth be told our versioning is kind of semver-ish at this point. We don't really have a strong roadmap and versioning feels a bit strained with the development pace. We're trying our best.

The main breaking functionality was dropping support for PHP < 5.3 and no longer using the configuration file. We considered adding something that could read in the configuration file if it existed, but ultimately decided against it. I can see an argument for bumping the major version with that change. The project really doesn't feel like it's in a 1.0 state right now with some of the work that's needed.

**Comment by Soullivaneuh** [comment]
> We considered adding something that could read in the configuration file if it existed, but ultimately decided against it.

In this case you may consider this component: http://symfony.com/doc/current/components/config.html

But it will be overkill IMHO because lot of configuration can be done with framework integration like Symfony or Laravel.

**Comment by bsweeney** [comment]
For anyone interested, consideration of the Symfony Options Resolver will happen in #1343.
