### ISSUE TITLE
Remote font file Permission denied issue

### ISSUE THREAD

**Issue by filanico** [dompdf/dompdf#1342]
OS: Windows 7 6.1.7601 SP1 BUILD 7601 
WAMP stack: apache 2.4.17, mariadb 10.1.13, php 5.6.20.
Framework: Laravel 4.1.2

**## ISSUE**:
While attaching a new FONT via css "import" clause in the template file as follows
```
<style>
    @import url('https://fonts.googleapis.com/css?family=Open+Sans');
</style>
```
In the file /include/font_metrics.cls.php at line 365 a "permission denied" error occurs when trying to delete the temp file.
In my case this happened because the file handler opened by Font_TrueType class wasn't closed before deletion.

**## FIX**:
Please add this: 
`$font->close();`
before trying deletion.

**Comment by bsweeney** [comment]
This was fixed by commit 4fc095b, which was included in 0.7.0.
