### ISSUE TITLE
Enabled CSS Debugging fails on array to string conversion

### ISSUE THREAD

**Issue by simonberger** [dompdf/dompdf#1344]
I enabled CSS debugging on the input available in issue #1340.
After some time it failed on code https://github.com/dompdf/dompdf/blob/develop/src/Css/Style.php#L2686 with array to string conversion of variable "val"

The values were:

```
val = ['page' => '1'];
prop = 'counter_increment';
```

**Comment by gdevilbat** [comment]
Hello , how to debugging css ?

**Comment by bsweeney** [comment]
@simonberger wondering if this is still an issue ...

**Comment by simonberger** [comment]
I'll have in mind retesting this. I currently do not have this test file though. Should be on another hdd.

**Comment by bsweeney** [comment]
Unable to confirm this issue, closing unless further details help reproduce.
