### ISSUE TITLE
Attaching google chart to PDF

### ISSUE THREAD

**Issue by artlemaks** [dompdf/dompdf#1345]
I am generating a chart using the Google Charts API and the data from my database, which means that there is a call to an external file and data is echoed back in a JSON format. I know that the chart can be converted to an image so I thought that this might work but unfortunately not I have tried the code below:

  ```
google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);

  function drawChart() {
    var jsonData = $.ajax({
  url: "getData.php?id=<?php echo $user_id; ?>';",
  dataType:"json",
  async: false
  }).responseText;
    var data = new google.visualization.DataTable(jsonData);

   var options = {
        hAxis: {
          title: 'Audit Number'
        },
        vAxis: {
          title: 'Gross Profit %'
        }
      };
    var chart_div = document.getElementById('chart_div');
    var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

   google.visualization.events.addListener(chart, 'ready', function () {
    var imgUri = chart.getImageURI();
    // do something with the image URI, like:
    document.getElementById('chartImg').src = imgUri;
});

        chart.draw(data, options);

  }
```
I then call include the graph on the PDF report by

  ` $rep_table = " <html><img id='chartImg' />`
When I load the page in HTML view, it displays the chart but it's still interactive so the first issue is definitely something to do with the conversion of the chart.

The bigger issue is with including the graph on the report. When I try to generate the PDF report I get an error saying that the headers have already been sent. I used one of the tips on SO to find out what the problem is and this is what I got back:

```
/home/arturl/public_html/platform/class/class_report.php
21
```
Which corresponds to

 `url: "getData.php?id=<?php echo $user_id; ?>';",`
This makes perfect sense as the json string is echoed back and DOMPDF sees it as a header. Is there any other way to get this done?

**Comment by bsweeney** [comment]
Following here to see if you find a resolution: http://stackoverflow.com/q/41612042/264628
