### ISSUE TITLE
Background image and custom fonts from local to live server

### ISSUE THREAD

**Issue by Brian-Jutrzonka** [dompdf/dompdf#1346]
Hello,

I have recently been trying to transfer my local version of dompdf (which is working perfectly) to a live server and I am not able to get a couple of things to transfer to the live server.  Currently, the 2 large issues I have been dealing with deal with are the css background-image and font face properties.  I am using the loadHTML() method and it is definitely reading my stylesheet/styles except for these properties correctly.  I have tried what seems to be every combination of URLs (absolute, relative) and have come up empty in my 3 hour rabbit hole.  Is there any advice you can give me in terms of using these properties correctly on my live server?

**Comment by bsweeney** [comment]
Does your live implementation have read/write access to the directories Dompdf uses. If you haven't customized any of them that's usually the system temp and dompdf/lib/fonts directories.

Are the systems running on the same OS? You might need to refresh the dompdf_font_family_cache.php file (not the ".dist.php" file). Easiest method is just to remove it and dompdf will recreate it next time it runs. This file contains path information for the font files themselves and may not be correct after a system move.

For the background image ... ? Can you post a sample of the CSS you've tried?

**Comment by Brian-Jutrzonka** [comment]
Brilliant! I was able to get the fonts up and running by taking out the cache file and letting it generate again.  Thanks.

As for the background-image property,  I have done all of the following background-image calls without any results... 
In my css stylesheet
`background-image:url(http://example.com/apps/sell-sheets/images/image.jpg);`
`background-image:url(/apps/sell-sheets/images/image.jpg);`
`background-image:url(apps/sell-sheets/images/image.jpg);`
`background-image:url(/images/image.jpg);`
`background-image:url(images/image.jpg);`

In my php file
`$curdir = getcwd();
background-image:url('.$curdir.'/images/image.jpg);`

**Comment by bsweeney** [comment]
I'd expect at least one of those to work. For URLs make sure allow_url_fopen is true. The next release will have some curl-based functionality as a backup.

Make sure dompdf has read/write access to the temp directory specified in your configuration.

Make sure you have GD ... though that shouldn't be necessary for JPGs.

**Comment by Brian-Jutrzonka** [comment]
Its weird though, I am able to reference images with the HTML <img src=""> tag within the loadHTML() method by truncating the urls to 
`images/example.jpg`
 but not with the background images even when I place the background-image property as a style within the loadHTML() method on my div and I use the same path...

Would this have to do with that temp directory read/write access?  If so, do you know of any resources I can read to learn how to allow that?

**Comment by Brian-Jutrzonka** [comment]
Sorry, I meant the html `<img src="images/example.jpg">` tag

**Comment by bsweeney** [comment]
That is weird, then. If you can use the images normally then it's not a temp directory issue. It might be the format of the background-image statement. You might try varying the format of that property to see if it work (for example, add quotes around the image path).

**Comment by Brian-Jutrzonka** [comment]
Alright, so I decided to resort to using position absolute and a z-index of -1 to place the image within the background because I could not figure out why the background image property was acting the way that it was.  Works the exact same and I dont have anymore headaches.  Thank you so much for your help.  You were incredibly helpful!

**Comment by bsweeney** [comment]
That works! Sorry for the headaches, though. If you decide you want to spend some more time on this just post back here.
