### ISSUE TITLE
Multi-language problem

### ISSUE THREAD

**Issue by sanjib-dev** [dompdf/dompdf#1349]
my report consists of multiple languages. when only English is there, report  prints as expected. but with hindi or other fonts, its only printing ???
Please help me on this.
I have dompdf 7 so the unicode support is already default(i checked it and its there).
also, i am using dompdf as a engine of cakepdf and cakephp 3.2
I have tried to include external fonts also but no help.

**Comment by bsweeney** [comment]
Have you followed all the advice in the [Unicode How-To](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo)? If so, it would help to see a sample of your HTML.

**Comment by sanjib-dev** [comment]
I have followed the unicode wiki.
Please have a look in my htmls
I have a background image which has a copy-write issue so can't paste it here,Only pasting the html

------------------------------1st------------------
`<!DOCTYPE html>
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	
	<title>Document</title>
	  
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  
	<style>
            @page { margin: 0px; }
		body{
			
			background-repeat: no-repeat;
			background-attachment: fixed;
                        background-position: center; 
                        margin: 0px;
                         font-family: "Times New Roman", Times, serif;
                }
		#para1{
			position: fixed;
			top: 395px;
			left: 490px;
			font-size: 1.9em;
                        
		}
		#para2{
			position: fixed;
			top: 482px;
			left: 460px;
			font-size: 1.6em;
                     
		}
		#para3{
			position: fixed;
			top: 630px;
			left: 330px;
                        font-size: 1.2em;
                        
		}
		#para4{
			position: fixed;
			top: 630px;
			left: 860px;
                        font-size: 1.4em;
                       
		}
	</style>
</head>
<body>
	<p id="para1">
		Team  ELM
	</p>
	<p id="para2">
		ऑप्शन्स ट्रडिंग्स को समझने का सबसे आसान तरीका
	</p>
	<p id="para3">
		January 17, 2017
	</p>
	<p id="para4">
		Vineet trtt
	</p>
  
</body></html>`
----------------------------------------------------------
------------------------2nd------------------------------
`<!DOCTYPE html>
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	
	<title>Document</title>
	  
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<style>
            @page { margin: 0px; }
		body{
			
			background-repeat: no-repeat;
			background-attachment: fixed;
                        background-position: center; 
                        margin: 0px;
                         font-family: "Times New Roman", Times, serif;
                }
		#para1{
			position: fixed;
			top: 395px;
			left: 490px;
			font-size: 1.9em;
                        
		}
		#para2{
			position: fixed;
			top: 482px;
			left: 460px;
			font-size: 1.6em;
                     
		}
		#para3{
			position: fixed;
			top: 630px;
			left: 330px;
                        font-size: 1.2em;
                        
		}
		#para4{
			position: fixed;
			top: 630px;
			left: 860px;
                        font-size: 1.4em;
                       
		}
	</style>
</head>
<body>
	<p id="para1">
		Team  ELM
	</p>
	<p id="para2">
		এন্ট্রি এন্ড এক্সিট টেকনিকস ইউসিং সিম্পল
	</p>
	<p id="para3">
		January 17, 2017
	</p>
	<p id="para4">
		Vineet trtt
	</p>
  
</body></html>`

Please have a look.

When in html, it prints good in browser.

**Comment by bsweeney** [comment]
What font did you use? Did you load your own copy of Times New Roman? The core fonts (Times, Helvetica, Courier) only support Windows ANSI (which does not support the characters in your document).

**Comment by sanjib-dev** [comment]
Thanks for the reply.
As documented, the Dojo font will work(not working in my case)?
My problem is I have multiple languages to support.
Can you suggest something for this?
I have tried to load external fonts but the pdf generated is not the same as the data stored in DB(I use mysql and fields are unicoded).

**Comment by bsweeney** [comment]
I didn't see anywhere that you're actually using the Dojo font in your document. Make sure you have loaded in to dompdf (using either the load_font.php script or via `@font-face` declaration) and that you are styling your text appropriately.

**Comment by sanjib-dev** [comment]
Thanks again for reply. I did loaded the Dojo font in `@font-face` declaration.Its not working for me at least. I may have missing something. But is that font really supports regional languages like bengali or hindi?
`@font-face{
Dojo sans srif;
}`

that is my code.
Please help me on this.

**Comment by bsweeney** [comment]
That's not how you would use `@font-face`. That declaration tell the renderer (dompdf in this case) about the font (it's name, location, weight, etc.). Then you use the font-family property to indicate you want text to use that font. Should be more like:

```
<style>
@font-face {
  font-family: "Dojo Sans Serif";
  font-style: normal;
  font-weight: normal;
  src: url(http://example.com/fonts/dojosans.ttf) format('truetype');
}
* {
  font-family: "Dojo Sans Serif", "DejaVu Sans", sans-serif;
}
</style>
```

**Comment by sanjib-dev** [comment]
sorry for my late reply and thanks again for great help.
just one question: Dojo font is included in the default package(as in doc and i could see the font file in dompdf folder) ? do I have to include it separately like you mentioned?

**Comment by bsweeney** [comment]
I'm not sure where the Dojo font came from because it is not included as part of dompdf. A subset of the DejaVu fonts is. You can check to see if the font is actually installed by opening up the dompdf_font_family_cache.php file. If the font is installed it will be listed in that file.

**Comment by sanjib-dev** [comment]
Thanks for the reply and guided me to right direction.
I will try this for sure and let you know

**Comment by ridislam** [comment]
bsweeney i am using dompdf 0.7 , you say everyone to follow Unicode How-To link but is that technique works with dompdf 0.7? can you just set some example for hindi, bangla language..? cause its really not working..

**Comment by schtanislau** [comment]
Issue still remains :warning:

I need to use cyrillic chars in my PDF file, but instead I have white color chars (not even question marks).

I use [Roboto](https://fonts.google.com/specimen/Roboto) font true type format (which definitely supports UTF8) file like this:

```
@font-face {
    font-family: "Roboto";
    font-style: normal;
    font-weight: normal;
    src: url(http://example.com/roboto.ttf) format('truetype');
}
* {
    font-family: "Robot";
}
```

End result:

![image](https://cloud.githubusercontent.com/assets/5516292/24321034/32771eca-114b-11e7-9b4f-8f9843d69915.png)

`Татьяна` word is selected in browser inspector. On PDF page it's actually white color.

When I use code block above on a simple HTML page - everything shows correctly.

**Comment by simonberger** [comment]
Or you just got version 0.8.0 now and had 0.7.0 before?

**Comment by schtanislau** [comment]
@simonberger Nope, it was 0.8.0 from the very beginning. It seems that if cache files (`dompdf/lib/fonts/*.*`) were generated incorrectly then font won't work even if the configuration (font CSS styles) got fixed.

**Comment by bsweeney** [comment]
I don't suppose you held on to a copy of the bad files? I'd be curious to see what it was about them that was incorrect?

Did you upload from one system to another?

**Comment by mimehedi166** [comment]
I think i found the solution of this problem. i've tried some library (dompdf, TCPDF,FPDF,mPDF) which support PHP but not all of them are work properly. I didn't find any unicode support with dompdf, tcpdf worked but the fonts are broken. so i tried mPDF and it gave me my expected output. i'm using this library to my laravel project. To using mPDF with laravel project you need to follow the documentation of laravel-mpdf. link: https://github.com/niklasravnsborg/laravel-pdf

after installed the library successfully what you have to do this following steps for other language or bangla support.
1. first download the fonts for your supported language (i.e: for bangla i've downloaded solaimanLipi.ttf) and keep it to your fonts folder inside the resources folder. if there is no fonts folder just create it.
2.In config/pdf.php file add these codes inside of return array

```
'font_path' => base_path('resources/fonts/'),
	'font_data' => [
		'examplefont' => [
			'R'  => 'ExampleFont-Regular.ttf',    // regular font
			'B'  => 'ExampleFont-Bold.ttf',       // optional: bold font
			'I'  => 'ExampleFont-Italic.ttf',     // optional: italic font
			'BI' => 'ExampleFont-Bold-Italic.ttf' // optional: bold-italic font
			'useOTL' => 0xFF,    
			'useKashida' => 75, 
		]
		// ...add as many as you want.
	]
```


examplefont is your attribute name whatever you want to use. but inside this attribute paste your font name.

Example:

```
'bangla' => [
            'R'  => 'SolaimanLipi.ttf',    // regular font
            'B'  => 'SolaimanLipi.ttf',       // optional: bold font
            'I'  => 'SolaimanLipi.ttf',     // optional: italic font
            'BI' => 'SolaimanLipi.ttf' // optional: bold-italic font
            'useOTL' => 0xFF,   
            'useKashida' => 75, 
        ]
```

now in your view file use this CSS Scripts:

```
<style>
body {
    font-family: 'examplefont', sans-serif;
}
</style>
```

In Your Controller:

function generate_pdf() {
```
    $data = [
        'foo' => 'bar'
    ];
    $pdf = PDF::loadView('pdf.document', $data);
    return $pdf->stream('document.pdf');
}
```

Hints: pdf.document is your view file name. Use PDF at the top in your namespace

If you follow this step correctly ,it will work 100%. 
**This is my output** 
![sample](https://user-images.githubusercontent.com/7956469/38671890-6d786cc6-3e6e-11e8-831f-3c5fae8bbc82.PNG)


N.B: This is my first post. if i did any mistakes to write review in correct format please consider it take it lightly. Thank You, Mahabubul Islam Mehedi

**Comment by mehedi221** [comment]
i used dompdf version 0.8.1 but i can not include bangla font yet.
 do you have any solution

**Comment by mimehedi166** [comment]
yes. if u see my comment on github then I already gave a solution on there.
please see that

**Comment by NadimLU** [comment]
@mimehedi166 How implement this code in codeigniter dompdf library ?
 'font_path' => base_path('resources/fonts/'),
	'font_data' => [
		'examplefont' => [
			'R'  => 'ExampleFont-Regular.ttf',    // regular font
			'B'  => 'ExampleFont-Bold.ttf',       // optional: bold font
			'I'  => 'ExampleFont-Italic.ttf',     // optional: italic font
			'BI' => 'ExampleFont-Bold-Italic.ttf' // optional: bold-italic font
			'useOTL' => 0xFF,    
			'useKashida' => 75, 
		]
		// ...add as many as you want.
	]

**Comment by Mohan-Patidar** [comment]
> I have followed the unicode wiki. Please have a look in my htmls I have a background image which has a copy-write issue so can't paste it here,Only pasting the html
> 
> [Document_bengla.txt](https://github.com/dompdf/dompdf/files/710077/Document_bengla.txt) [Document_hindi.txt](https://github.com/dompdf/dompdf/files/710078/Document_hindi.txt)
> 
> As html files are not supported, uploaded this with txt Please have a look.
> 
> When in html, it prints good in browser.

![Screenshot_6](https://user-images.githubusercontent.com/67731760/142395171-e2006428-6770-429f-9f3a-763a818cf069.png)
Not working in hindi fonts

**Comment by bsweeney** [comment]
@Mohan-Patidar first thing you need to do is make sure you reference a font that has glyphs for the characters you need. Hindi is not supported by the bundled fonts.

**Comment by suraj-teknikforce** [comment]
Hello @bsweeney,
I want to use any language and export it to PDF.
I am attaching a TXT file of HTML that I want to export into PDF please find it.
It contains three languages: Hindi, English, and Greek (But I want to use more).
And this pdf I am getting, please find it, please ignore the background image.
Please help me.
I am looking forward to your response.

Thanks & Regards
Suraj Madhesiya

[document.pdf](https://github.com/dompdf/dompdf/files/9676370/document.pdf)
[dompdf.txt](https://github.com/dompdf/dompdf/files/9676345/dompdf.txt)

**Comment by bsweeney** [comment]
If you know at the time of render what languages you want to support you can just style the text with a supporting font. If not you'll need to find a font that supports all possible languages that you want to be able to include (at least until we support Unicode range declarations).

Individual font files with wide ranging language support are rare: Arial Unicode (but it's expensive to license), GNU Unifont (but you probably won't like the look). And even these are limited in their representation since Unicode supports far more characters than a TrueType font is capable of displaying.

**Comment by suraj-teknikforce** [comment]
Hello @bsweeney,
Thank you for your quick response.
No, I will not mix all the languages but I want to use french, Hindi, Portuguese, Chinese, etc, according to the need but I didn't find the TTF file.
Please help me to find all the TTF files according to the need.
I am looking forward to your response.

Thanks & Regards
Suraj Madhesiya

**Comment by bsweeney** [comment]
Dompdf out of the box does not support all potential languages. The core PDF fonts only support Windows ANSI character encoding. The DejaVu fonts support a wider range of characters but not all (e.g. Chinese). You can find which characters are supported by looking at the [DejaVu font PDF samples](https://dejavu-fonts.github.io/Samples.html).

Read through the [Unicode How-To](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo) to get a better understanding of how to support additional languages.

Since this issue is long closed, if you need further assistance I suggest starting a [new discussion topic](https://github.com/dompdf/dompdf/discussions/new).

**Comment by mohammadSulaiman29** [comment]
what about arabic issue ? 
please someone can help me ? 
i used dompdf
