### ISSUE TITLE
 Fatal error: require_once(): Failed opening required 'dompdf_config.inc.php' (include_path='../dompdf')

### ISSUE THREAD

**Issue by EL046167** [dompdf/dompdf#1351]
Hi i have downloaded the Dompdf from git also included the php-font-lib and php-svg-lib but am getting this error and my dompdf folder dosen't have any file named dompdf_config.inc.php

**Comment by bsweeney** [comment]
With 0.7.0 we no longer use that file. Please read over the quick start section of the readme and see if it helps: https://github.com/dompdf/dompdf#easy-installation
