### ISSUE TITLE
When generating PDF, The PNG Images background turn green instead of transparant.

### ISSUE THREAD

**Issue by DennisOffinga** [dompdf/dompdf#1352]
As first i love to use DOMPDF and it works just fine however, when i generate a PDF I get a ugly green background on my transparant PNG's, i hope someone could help me out.

**This image shows what i mean.**
![ugly green background](https://cloud.githubusercontent.com/assets/25222235/22103900/34b63b30-de3d-11e6-8d74-3079c97c0a90.png)

Thanks in advance!

**Comment by bsweeney** [comment]
Which version of dompdf are you using? Do you have the IMagick or GMagick extension? Can you upload the image for testing?

**Comment by bsweeney** [comment]
Closing due to lack of follow up.
