### ISSUE TITLE
Refactoring of phpdoc and deprecated methods

### ISSUE THREAD

**Issue by simonberger** [dompdf/dompdf#1359]
I went through some classes by hand and with an inspection tool. To summarize what I did for now:

- In 4 classes added and fixed phpdoc in all methods
- Fixed all easy to fix uses of deprecated marked methods (why did one start that job and didn't finish it?)
- Small code fixes in context of phpdoc

The commits can be seen [here](https://github.com/simonberger/dompdf/commits/minorfixes)

I am not one for marking deprecated methods or properties without any comment or possible context why this job can't be finished by now.
 I mainly refer to `Dompdf::pdf`. It seems to be replaced by `Dompdf::canvas` but gets parallely written and returned if Dompdf::canvas would be null. On top of that Dompdf::pdf is used directly instead of Dompdf::canvas or Dompdf::getCanvas. We know it does work because they are sharing the same object reference but I still call it a bug.

Would be nice if one could shed some light on this.

Apart from that question please have a short look at the changes and give me a note if you are interested to pull those kind of changes at all and within a narrow time frame (those changes be outdated quiet fast) then I'll continue the work,

**Comment by bsweeney** [comment]
That's all very nice work. Please feel free to add a PR. I'm not sure about timing, but I don't see any reason we wouldn't be able to merge this quickly. Though, you can continue adding to the PR if you have more changes.

As for the question regarding deprecated methods ... it's mostly a matter of time and who did the work. I this it would be preferable for changes like that to propagate all the way through, but it hasn't always been the case. My priority of late has been fixing actual bugs in the rendering process, but I would be happy to see some help with code cleanliness.

**Comment by simonberger** [comment]
Ok. Regarding those deprecated marks in Dompdf class I'll try to do a hard cut and remove all methods I can't find a direct or indirect references to including the pdf property.
We'll then see where that leads to. :)

**Comment by simonberger** [comment]
There is a lot of wrong phpdoc type declaration around the Frame base class that should be the decorated class AbstractFrameDecorator, Block, Page or whatever instead.
I would need some time to understand this inheritance structure good enough to try to fix this phpdoc. Surely at many places methods and properties could be many different types.

Do you guys think that work would be worth it or is it ok right now?
IDEs for example aren't able to resolve many methods that are in AbstractFrameDecorator while phpdoc notes (directly or indirectly through parent call) Frame right now. Or they report the wrong return type.

Edit:
Additionally as far as I have seen the class Block more or less is the AbstractBlockDecorator and is never instanced directly. We could change that to abstract.
