### ISSUE TITLE
Remove sys_get_temp_dir() from constructor

### ISSUE THREAD

**Issue by misog** [dompdf/dompdf#1366]
Hi, in Options.php there is sys_get_temp_dir() called:
```
$this->setTempDir(sys_get_temp_dir());
```
https://github.com/dompdf/dompdf/blob/master/src/Options.php#L296
However, this creates problems on some shared hostings.
Already-defined DOMPDF_TEMP_DIR constant should be used here. The constant is set in config:
```
"DOMPDF_TEMP_DIR" => sys_get_temp_dir(),
```

**Comment by simonberger** [comment]
Using global definitions has been dropped some years ago in favour of the options class you mention here.
The `sys_get_temp_dir()` call works in those shared hosting environments and just returns a path that you aren't allowed to write to, correct?

While it's maybe not perfect there are two ways to handle it. You can change that option after as you might do now and it seems to be possible to change the output sys_get_temp_dir gives.

[See here](http://stackoverflow.com/questions/13186069/sys-get-temp-dir-in-shared-hosting-environment)
`putenv('TMPDIR=/foo/bar')`

**Comment by bsweeney** [comment]
As mentioned by @simonberger, as of 0.7.0 we're no longer supporting the configuration constants defined in dompdf_config.inc.php that were used in previous releases. That file is, in fact, no longer referenced at all.

To change this setting in dompdf 0.7.0 or newer you can use the setOption method (`$dompdf->setOption('tempDir', '/some/path';`) or set the value when instantiating dompdf (e.g. `$dompdf = new Dompdf(array('tempDir'=>'/temp/path'));`).
