### ISSUE TITLE
Trouble calling external html

### ISSUE THREAD

**Issue by kimheenim** [dompdf/dompdf#1367]
I'm having a problem when using dompdf. When I call a html file, it just gives error 

> "Notice: Undefined variable: html in C:\xampp\htdocs\dom\printpdf.php on line 10
> 
> Fatal error: Uncaught exception 'Dompdf\Exception' with message 'Requested HTML document contains no data.' in C:\xampp\htdocs\dom\dompdf\src\Frame\FrameTree.php:146 Stack trace: #0 C:\xampp\htdocs\dom\dompdf\src\Dompdf.php(580): Dompdf\Frame\FrameTree->build_tree() #1 C:\xampp\htdocs\dom\dompdf\src\Dompdf.php(730): Dompdf\Dompdf->processHtml() #2 C:\xampp\htdocs\dom\printpdf.php(18): Dompdf\Dompdf->render() #3 {main} thrown in C:\xampp\htdocs\dom\dompdf\src\Frame\FrameTree.php on line 146
> "

but the code is only this
```
<?php
	// include autoloader
	require_once 'dompdf/autoload.inc.php';
	use Dompdf\Dompdf;
	$dompdf = new Dompdf();
	$dompdf->loadHtml($html);
	$html= file_get_contents("sampol.html");
	$dompdf->setPaper('Letter', 'portrait');
	$dompdf->render();
	$dompdf->stream();
?>
```
and the file I am calling is just plain 'Hello World'. What am I missing? Thanks in advance.

**Comment by simonberger** [comment]
Please have a look at the notice on top of your error/warning output. It'll give you the answer to the following error and the problem in your code.

**Comment by kieronsutton00** [comment]
@kimheenim You must define $html before attempting to use it.
Try this:
`<?php
	// include autoloader
	require_once 'dompdf/autoload.inc.php';
	use Dompdf\Dompdf;
	$dompdf = new Dompdf();
        $html= file_get_contents("sampol.html");
	$dompdf->loadHtml($html);
	$dompdf->setPaper('Letter', 'portrait');
	$dompdf->render();
	$dompdf->stream();
?>`
