### ISSUE TITLE
Images not working with Dompdf in joomla 3.5

### ISSUE THREAD

**Issue by csantof** [dompdf/dompdf#1368]
I have a problem displaying my logo in my pdf file
I put this code `<img` src="/myfolder/images/logo.jpeg" width="130" `height="63">` and it does not work every time I have the following message Image not found http://domain_nam/myfolder/images/logo.jpeg

I tried in all directions but could not display this logo.
The parameters are set as indicated in the other threads.
What I notice is that the size of my image applies well.
is there a solution

**Comment by bsweeney** [comment]
Presumably the HTML looks correct? Does your system meet the [minimum requirements](https://github.com/dompdf/dompdf/wiki/Requirements)?
