### ISSUE TITLE
problems with borders of multiple tables in a row.

### ISSUE THREAD

**Issue by Unniks-here** [dompdf/dompdf#1369]
I f there are multiple tables in different divisions with style="display:inline-block;" then "inline-block" style do not affect to the borders of tables except first.

![table_issue](https://cloud.githubusercontent.com/assets/7260715/22510493/264d1e08-e8b8-11e6-96de-f2b3133a19c4.JPG)

**Comment by Unniks-here** [comment]
<style>
        table {
            border-collapse: collapse;
        }

        table, th, td {
            border: 1px solid black;
        }
    </style>

<table style="font-size: 14px;">
        <thead>
        <tr>
            <th>Sl no</th>
            <th>Uni reg no</th>
            <th>Roll no</th>
            <th>Name</th>
        </tr>
        </thead>
        <tbody>
        @foreach($students1 as $student)

            <tr>
                <td style="width: 10%;">{{ $student->ID }}</td>
                <td style="width: 10%;">{{ $student->uniNo }}</td>
                <td  style="width: 10%;">{{$student->rollNum}}</td>
                <td style="width: 70%;">{{ $student->studentName }}</td>
            </tr>
         @endforeach
        </tbody>
    </table>

</div>
<div  style="display:inline-block; float: left; width: 50%; height: 100%; " >


    <table style="font-size: 14px;">
        <thead>
        <tr>
            <th>Sl no</th>
            <th>Uni reg no</th>
            <th>Roll no</th>
            <th>Name</th>
        </tr>
        </thead>
        <tbody>
        @foreach($students2 as $student)

            <tr>
                <td style="width: 10%;">{{ $student->ID }}</td>
                <td style="width: 10%;">{{ $student->uniNo }}</td>
                <td  style="width: 10%;">{{$student->rollNum}}</td>
                <td style="width: 70%;">{{ $student->studentName }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>


This is my code..

**Comment by simonberger** [comment]
Could you please build a testable example?
By hand or replacing your student output with a dummystring and provide the rendered html code.
I couldnt find any block or inlne-block style in this example

**Comment by bsweeney** [comment]
Agreed. I want to say a similar issue may be documented already, but I wasn't able to find it after a quick search.

**Comment by Unniks-here** [comment]
But I have solved my problem by replacing "border:collapse" with "border-spacing: 0"

**Comment by bsweeney** [comment]
Interesting ... that may help in determining why this is happening.

**Comment by jonathanpmartins** [comment]
Same problem here, but in my case "border-spacing: 0" didn't the job.
