### ISSUE TITLE
base_path ignored if URL has leading slash

### ISSUE THREAD

**Issue by chrBrd** [dompdf/dompdf#1370]
In the `build_url()` method in the `Helpers` class the `base_path` variable is ignored if the `url` variable has a leading slash (ln: 75).

This is intentional behaviour, and it looks like it's to differentiate between relative and absolute paths, but it may cause problems for some users. I'm using a Twig template in Symfony to build the HTML - the Twig asset() function used to reference stylesheets adds a leading slash to the paths, so they weren't loading even when using the `setBasePath()` method.

I can't think of an ideal solution - best proposal I have is checking if the user defined base path has a trailing slash or not, but that may cause as many problems as it solves.

**Comment by bsweeney** [comment]
This is a bit tricky. The way dompdf is set up isn't really optimized for differentiating a user-defined base path from the running file path. I'll need to think on this some more but probably a better way to do this is to let the base path be empty by default and in `build_url()` use the current file path unless the base path is set.

**Comment by bsweeney** [comment]
also see #144

**Comment by bsweeney** [comment]
additional discussion in #1370

**Comment by bsweeney** [comment]
Closing as, ultimately, I think we'll support this through user customization and not core functionality. Follow #3133.
