### ISSUE TITLE
PDF rendering library or library path has not been defined

### ISSUE THREAD

**Issue by NoVizin** [dompdf/dompdf#1373]
## I have this Error when try to use my code (I use composer)

Fatal error: Uncaught PhpOffice\PhpWord\Exception\Exception: PDF rendering library or library path has not been defined. in /home/dh_26bvvw/sendo.sufide.com/FinalPdf/vendor/phpoffice/phpword/src/PhpWord/Writer/PDF.php:50 Stack trace: #0 /home/dh_26bvvw/sendo.sufide.com/FinalPdf/vendor/phpoffice/phpword/src/PhpWord/IOFactory.php(44): PhpOffice\PhpWord\Writer\PDF->__construct(Object(PhpOffice\PhpWord\PhpWord)) #1 /home/dh_26bvvw/sendo.sufide.com/FinalPdf/index.php(26): PhpOffice\PhpWord\IOFactory::createWriter(Object(PhpOffice\PhpWord\PhpWord), 'PDF') #2 {main} thrown in /home/dh_26bvvw/sendo.sufide.com/FinalPdf/vendor/phpoffice/phpword/src/PhpWord/Writer/PDF.php on line 50

## Composer.json
{
    "require": {
       "phpoffice/phpword": "v0.13.*",
        "dompdf/dompdf": "^0.7.0"
    }
}

## My code in index.php 

require 'vendor/autoload.php';

$phpWord = new \PhpOffice\PhpWord\PhpWord();

$section = $phpWord->addSection();

$section->getSettings()->setMarginTop(5440);

$textrun = $section->addTextRun();

$textrun->addText('Test');

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
$objWriter->save('test.docx');

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'PDF');
$objWriter->save('test.pdf');

**Comment by simonberger** [comment]
You seem to miss the point of this portal.
It's meant to collect problems of dompdf. Not being spammed by users searching for help to fix their code.

Furthermore you post code snippets from a package having nothing to with dompdf expect answer a similar purpose.

**Comment by NoVizin** [comment]
So where can i find portal answering me on there kind of questions?

**Comment by bsweeney** [comment]
For dompdf help we have a [support forum](http://groups.google.com/group/dompdf) or you can always try [StackOverflow](http://stackoverflow.com/questions/tagged/dompdf). But your problem relates more with how to use PHPWord so you might start there: https://github.com/PHPOffice/PHPWord.
