### ISSUE TITLE
Paper size (A4) is different in height and width in version 0.7.0 than in 0.6.1

### ISSUE THREAD

**Issue by kikky7** [dompdf/dompdf#1375]
dompdf version 0.7.0 with Laravel 5.3 (current project and unable to install 0.6.1 version).
dompdf version 0.6.1 with Laravel 5.2.

I am using image (image size is 1240x1754px) with a fixed position as a repeating pattern (i.e. header and footer included at every page) and it fits perfectly to the paper with v0.6.1 (example 2), you can see it has orange and red borders at the top and bottom of the page.

However, the PDF document created with 0.7.0 version is cutted and there is no red border at the bottom of the page.

When I open both PDF documents in Photoshop and save them as image, the one created with v0.6.1 has resolution of 2480x3507 at 300dpi, and the one created with v0.7.0 has resolution of 2550x3300 at 300dpi.

I am using default configuration settings in both version, so how to fix this issue and why the newer version doesn't render a perfect A4 format as in older versions?

v 0.7.0
<img src="https://cloud.githubusercontent.com/assets/13437480/22633283/3d1014d6-ec20-11e6-93e3-eb084e963c40.jpg" width="200">

v 0.6.1
<img src="https://cloud.githubusercontent.com/assets/13437480/22633286/412f1bca-ec20-11e6-85b2-054c82034f4c.jpg" width="200">

**Comment by bsweeney** [comment]
It looks like in 0.7.0 your document is actually rendered in letter format, based on the dimensions you cite. How are you setting your page size?

**Comment by bsweeney** [comment]
Likely related to issue #1140.

**Comment by kikky7** [comment]
In config/dompdf.php (v0.7.0):

DOMPDF_DEFAULT_PAPER_SIZE is set to A4, but whatever value I use (letter, legal, a4, a3, ...), the output is the same, like this value is ignored upon rendering, also orientation is set to landscape, and switching to portrait I still get the same document output. So the default paper size value is getting ignored.

But when I change values of DOMPDF_DPI or DOMPDF_FONT_HEIGHT_RATIO the changes are shown in the document. Strange.

The paper size works when I use $pdf->setPaper('A4'); upon creating a document.

**Comment by bsweeney** [comment]
In 0.7.0 we no longer utilize the configuration constants. I'm surprised the other constants would have any affect. I'll double-check the code to see if we accidentally left in references.
