### ISSUE TITLE
0.6.2: broken auth_check

### ISSUE THREAD

**Issue by eti1** [dompdf/dompdf#1376]
In www/functions.inc.php auth_check function is supposed to fail when the default password is not changed.
One can authenticate anyway when omitting the $_GET['login'].
ie. curl http://user:password@example.com/dompdf/www/fonts.php -H 'Cookie: PHPSESSID=xxxxx'
will authenticate me, with the default configuration unchanged. 
Removing the first "isset($_GET["login"]) &&" will fix the problem.

Regards,

**Comment by bsweeney** [comment]
We're no longer distributing the www content. It may be resurrected as part of the [utils](https://github.com/dompdf/utils) project. If we do resurrect that code we'll take a look at that point.
