### ISSUE TITLE
Text opacity/alpha

### ISSUE THREAD

**Issue by crow1796** [dompdf/dompdf#1379]
How to set text opacity or alpha?

**Comment by bsweeney** [comment]
The only way you can do this in 0.7.0 is to set the opacity of the container.

```
<p style="background-color: black;"><span style="color: white; opacity: .35">35% OPACITY<span></p>
```

In the upcoming 0.7.1 release you can set the text color using rgb-alpha and hex-alpha to modify the coloring on just the text itself.

```
<p style="background-color: black; color: rgba(255,255,255,.35)">35% OPACITY</p>
<p style="background-color: black; color: #ffffff59">35% OPACITY</p>
```
