### ISSUE TITLE
Strange render with float and clear both structure 

### ISSUE THREAD

**Issue by boufle** [dompdf/dompdf#1380]
Hey there, 

I've got some strange render in my pdf with float left and clear both structure,
There is some screen to illustrate 

This is what i get in my pdf : http://imgur.com/a/WgdNJ
This is what i should get : sommething like that http://imgur.com/a/8vcLW
And there is my html structure : http://imgur.com/PdvHEOZ

i'm using dompdf 0.7 with symfony 3 
Thanks for your reply 
Best regards

**Comment by bsweeney** [comment]
Can you post your HTML source as a code snippet rather than as an image?

**Comment by boufle** [comment]
Yes there it is 

` <link rel="stylesheet" href="http://toutpourqy.cluster003.ovh.net/Rentalis/web/css/pdf.css">

            {% for i in 0..data.Chantier|length -1  %}
        <div style="width: 100%; height: 18px; clear: both;">
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;">{{data.Chantier[loop.index0].Code}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" class="">{{data.Chantier[loop.index0].Libelle|e('html')|lower[:5]}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="MO_MontantPrevu" class=" col-MO">{{data.Devis[loop.index0].TotalDebMO|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="MO_MontantRealise" class="MOreel col-MO">{{data.Facture[loop.index0].DebMO|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="MO_Autre" class=" col-MO"></div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="MOT_HPrevu" class=" col-MOT">{{data.Devis[loop.index0].TotalTempsMO|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="MOT_HRealise" class=" col-MOT">{{data.Facture[loop.index0].TempsMO|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="FOUR_MontantPrevu" class=" col-Four">{{data.Devis[loop.index0].TotalDebF|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="FOUR_MontantRealise" class=" col-Four">{{data.Facture[loop.index0].DebF|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="MDF_MontantPrevu" class=" col-MDF">{{data.Devis[loop.index0].TotalDebMat|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="MDF_MontantRealise" class=" col-MDF">{{data.Facture[loop.index0].DebMat|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="SSTR_MontantPrevu" class=" col-ST">{{data.Devis[loop.index0].TotalDebSst|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="SSTR_MontantRealise" class=" col-ST">{{data.Facture[loop.index0].DebSst|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="DT_TotalDevis" class=" col-DT">{{data.Devis[loop.index0].TotalDeb|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="DT_TotalFacture" class=" col-DT">{{data.Facture[loop.index0].TotalDeb|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="VF_TotalDevis" class="col-VF">{{data.Devis[loop.index0].TotalHTNetFin|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="VF_TotalFacture" class=" col-VF">{{data.Facture[loop.index0].HTNetFin|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="RAF" class=" col-RF">{{(data.Devis[loop.index0].TotalHTNetFin - data.Facture[loop.index0].HTNetFin)|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="MD_MontantPrevu" class=" col-MD">{{(data.Devis[loop.index0].TotalHTNetFin - data.Devis[loop.index0].TotalDeb)|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="MD_MontantRealise" class=" col-MD">{{(data.Facture[loop.index0].HTNetFin - data.Facture[loop.index0].TotalDeb)|number_format(0, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="COEF_Prevu" class=" col-COEFD">{{((data.Facture[loop.index0].TotalDeb == 0)? 0 : ((data.Devis[loop.index0].TotalDeb) / data.Facture[loop.index0].TotalDeb))|number_format(2, '.', ' ')}}</div>
                    <div style="width: 4.545454%; height: 18px; float: left; font-size: 10px;" type="COEF_Realise" class=" col-COEFD">{{((data.Devis[loop.index0].TotalHTNetFin - data.Devis[loop.index0].TotalDeb)==0)? 0 :((data.Facture[loop.index0].HTNetFin - data.Facture[loop.index0].TotalDeb)/(data.Devis[loop.index0].TotalHTNetFin - data.Devis[loop.index0].TotalDeb))|number_format(2, '.', ' ')}}</div>
        </div>
            {% endfor %}
`

**Comment by bsweeney** [comment]
We prefer to have HTML rather than PHP or template code so that we don't have to try and guess at what data should be in the document. Plus there's the time to replace the variables.
