### ISSUE TITLE
Script element after closing body tag causes extra blank page

### ISSUE THREAD

**Issue by ragulka** [dompdf/dompdf#1381]
It seems that if the the HTML is a full-blown HTML5 page and there is a `<script>` tag between the closing `</body>` and `</html>` tags, then an extra blank page is added to the PDF.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>title</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <!-- page content -->
  </body>
  <script src="script.js"></script> 
</html>
```

I have not tested i with other elements/tags yet, but this is definitely odd.

**Comment by bsweeney** [comment]
If you look at the [HTML4](https://www.w3.org/TR/html4/struct/global.html#edef-HTML) or [HTML5](https://www.w3.org/TR/html5/semantics.html#the-html-element) spec you'll see that the only elements allowed inside the HTML element are HEAD and BODY. Most browsers handle this structure by moving the script inside the body element (as you can see by inspecting the rendered document structure).

Fixing up the document syntax and structure is part of the parsing browsers do when loading an HTML document. Dompdf does a bit of fixing up as part of parsing a document, but if you want something more akin to what the browsers do you can set the isHtml5ParserEnabled option to true. Indeed we recommend it!

In a future release (once we upgrade the parsing library) we'll probably use the parser by default.
