### ISSUE TITLE
output stops at render() when log_output_file

### ISSUE THREAD

**Issue by Sephtex** [dompdf/dompdf#1387]
I noticed there isn't any output anymore after the render() function on version 0.7.0.
When I looked into Dompdf.php file, I saw there was an ob_start() when there is a logging file specified (which is the default), but I never could find an ob_get_clean() or variant.
My solution was to give the option to set an empty log_output_file as you can see:

```
                                $dompdf = new Dompdf(array('log_output_file' => ''));
                                $dompdf->load_html($html, 'UTF-8');
                                $dompdf->set_paper('a4', 'portrait');
                                $dompdf->render();
                                $pdf = $dompdf->output();
```

**Comment by bsweeney** [comment]
Prior to 0.8.0 the output buffer is closed in the [`write_log` method](https://github.com/dompdf/dompdf/blob/v0.7.0/src/Dompdf.php#L868), which is called from the `output` and `stream` methods. Besides being problematic if a user never calls output/stream, the process was buggy in cases where the log file was not writable (see #1282).

This is addressed for the 0.8.0 release, we're now starting/ending the output buffer in the same method. See commit e75c407c.
