### ISSUE TITLE
Link width is not correctly calculated when content is contained inside nested inline elements

### ISSUE THREAD

**Issue by digitoken** [dompdf/dompdf#1390]
I have html document which contains hyperlinked text, however the URL address is not converted in the PDF file generated by DOMPDF.

Could you please advise ?

Thks

**Comment by bsweeney** [comment]
Could you please elaborate a bit more?

**Comment by digitoken** [comment]
The problem occurs when I tried to convert from html files generated by MS Word (when I save my doc as web page) to PDF.

I guessed the following parts which cause the failure:

<a href="http://mylink1.com/"><span style="mso-bookmark:_Toc400163314"><span style="font-size:12.0pt;font-family:&quot;Calibri&quot;,&quot;sans-serif&quot;;
mso-bidi-font-family:&quot;Times New Roman&quot;;mso-no-proof:yes" lang="EN-US">survey</span></span><span style="mso-bookmark:_Toc400163314"></span></a>

I have tested to convert from simpler <a href...> format and it's working fine. Maybe the script doesn;t support complexed html tags

**Comment by bsweeney** [comment]
Looks like a bug. When a link contains nested inline elements Dompdf does not correctly calculate the size of the rectangle for the link action. The following simplified HTML will exhibit the issue:

```
<a href="http://example.com"><span><span>example.com</span></span>
```

**Comment by ThomasLandauer** [comment]
What I'm observing is a "plain" link just underneath `<body>`, where the text shows up blue underlined, and I get a hand-cursor when I hover it. However, when I click it, nothing happens (and Chrome doesn't show a target address in the status bar).

On another location, the very link text behaves as above, but the area 1 mm above and below the line works fine (i.e. link target opens).

**Comment by bsweeney** [comment]
This issue does not appear to be present in the most recent release.
