### ISSUE TITLE
Floats/clears displays correctly on monitor, printing ignores height of float

### ISSUE THREAD

**Issue by casperbakker** [dompdf/dompdf#1391]
I tried so many different things, hopefully someone knows how to resolve this.

We generate PDF's with dompdf on Ubuntu 16.04, send them to Printnode (printnode.com) and that prints them from a Windows 10 machine to the printer.

The layout is fairly simple, but uses 1 `float: right`. The weird thing is, it renders correctly in the PDF on the screen. But when Printnode prints the document automatically, it ignores the hide of the block that is floating. So it looks like something is wrong in the PDF, but the PDF reader for the display understands it.

Any idea if I am doing something stupid or if this is a bug in dompdf?

## Print out
This is the document I printed:
![img_0101](https://cloud.githubusercontent.com/assets/886975/23132849/43c3e0da-f78f-11e6-8692-dc36dbf0c53c.JPG)

## On monitor
But this is what it shows on the monitor:
![screen shot 2017-02-20 at 17 09 22](https://cloud.githubusercontent.com/assets/886975/23132871/5939e2c0-f78f-11e6-965a-e5edddf18805.png)

## The code
This is the simplified version of the code I used to render it. There is absolutly no other CSS code that uses floats, clears or with's. So I stripped that for clarity.

```html
<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <style type="text/css">
        #address {
        }
        #meta {
            float: right;
            width: 50%;
        }
        #content {
            clear: both;
            padding-top: 1cm;
        }
    </style>
</head>
<body>
<div class="document">
    <div class="head">
        <div id="meta">
            <table>
                <tr>
                    <th>Date</th>
                    <td>Today</td>
                </tr>
                <tr>
                    <th>Date</th>
                    <td>Today</td>
                </tr>
                <tr>
                    <th>Date</th>
                    <td>Today</td>
                </tr>
                <tr>
                    <th>Date</th>
                    <td>Today</td>
                </tr>
            </table>
        </div>
        <div id="address">
            Customer<br>Address<br>Zipcode<br>City<br>Country
        </div>
    </div>
    <div id="content">
        What is in the box:
    </div>
    <div class="below">Below contents</div>
</div>
</body>
</html>
```

## 2 floats
In the above example, it seems to 'clear' only to the content on the left which is not floating and ignores the height of the floating block on the right.

When I float the address block to the left (so using a float left on address, float right on meta) I seems to ignore the height of both blocks. 

![img_2114](https://cloud.githubusercontent.com/assets/886975/23133020/ddc6ac9e-f78f-11e6-99dc-46ff2d21aca1.JPG)

Any tips are welcome!

**Comment by simonberger** [comment]
I can't help with this problem directly at the moment. But some things you might want to try out in the meantime to fix it:

* Placing a div with the float clearing style directly behind address.
* What happens if you set a height for the right box? If the fields there aren't of a fixed number it's just for test case or you may be able to calculate the height before in your script.
* Use a table layout

**Comment by bsweeney** [comment]
You might also supply the PDF generated by your code? Do you know if PrintNode modifies the document before sending it to your print server? Is there any way to see exactly what's sent to your printer?

**Comment by casperbakker** [comment]
@simonberger When I define the height of the address div, it does move the content lower, but only by the that amount. We sometimes use that as a hacky-fix. We cannot use a table layout because it is a multi-tenant system and we allow users to add their own CSS to change the positions of the columns.

@bsweeney Hereby the generated PDF. PrintNode does not modify the PDF document itself, but it probably converts it into EMF to be able to print on every printer. But because the output changes so clearly when changing the floats, I suspect the core problem is with dompdf.

[picklist-PICK2017-00001006.pdf](https://github.com/dompdf/dompdf/files/795802/picklist-PICK2017-00001006.pdf)

**Comment by casperbakker** [comment]
I now tried placing an extra div directly behind #address as suggested by @simonberger and now I get the same result on the monitor as from the printer:

![screen shot 2017-02-23 at 10 12 21](https://cloud.githubusercontent.com/assets/886975/23252268/949e6cc8-f9b0-11e6-8018-8b09e328cdd2.png)

[picklist-PICK2017-00001007.pdf.pdf](https://github.com/dompdf/dompdf/files/796005/picklist-PICK2017-00001007.pdf.pdf)

**Comment by bsweeney** [comment]
If printnode is converting to EMF I wonder if maybe its mis-interpreting what's in the PDF source. Hard to know without seeing the output of their system. But really you should see the same results across systems.

Working with your updated HTML (with the added clearing div), it's likely a problem with how dompdf prior to 0.8.0 dealt with clearing floats. You should see improved results with the 0.8.0, have you updated on your server yet?

**Comment by casperbakker** [comment]
I have good news: dompdf 0.8 fixed it.

I was already working for 2 weeks on this bug, and followed #1272 intensely, but I missed the final release of 0.8.
