### ISSUE TITLE
"Invalid expression" error on PHP 7.1

### ISSUE THREAD

**Issue by UweKeim** [dompdf/dompdf#1392]
The following error occurs with PHP 7.1 and the latest dompdf package through Composer:

> DOMXPath::query(): Invalid expression

It does _not_ occur with PHP 7.0 or 5.6.

This is the stack trace:

```
#0 [internal function]: my_exception_error_handler(2, 'DOMXPath::query...', 'MyWebsite/...', 882, Array)
#1 MyWebsite/vendor/dompdf/dompdf/src/Css/Stylesheet.php(882): DOMXPath->query('//[@href]')
#2 MyWebsite/vendor/dompdf/dompdf/src/Dompdf.php(732): Dompdf\Css\Stylesheet->apply_styles(Object(Dompdf\Frame\FrameTree))
#3 MyWebsite/GeneratePdfInvoiceController.inc.php(117): Dompdf\Dompdf->render()
#4 MyWebsite/GeneratePdfInvoiceController.inc.php(63): GeneratePdfInvoiceController->doGeneratePdf('<!DOCTYPE html>...')
```

From the stack trace, it _seems_ that `DOMXPath->query('//[@href]')` generates the error.

**My question:**

Any chance to fix this by myself oder does it require an update to dompdf?

**Comment by UweKeim** [comment]
If the stack trace is correct, the following XPath query is the erroneous one:

    //[@href]

If I'm right, this actually _is_ an invalid XPath syntax. 

Probably it is meant to be written as

    //*[@href]

**Comment by bsweeney** [comment]
Which version of dompdf are you using? We released changes in dompdf 0.8.0 to improve PHP 7.1 compatibility. Specifically, we addressed the invalid expression in #1329 and the non-numeric value issue in #1272.

**Comment by UweKeim** [comment]
The composer.json says "0.7-dev".

Being a bit of a PHP noob, I tried to upgrade but it says no new version available.

Am I doing something completely wrong?

**Comment by UweKeim** [comment]
Awesome! I've just uninstalled and reinstalled, now I'm on 0.8.0 and the issue is gone!
