### ISSUE TITLE
Gap showing below tables when html 5 parser is enabled

### ISSUE THREAD

**Issue by eddturtle** [dompdf/dompdf#1394]
DomPdf Version v0.8
PHP 7/7.1 (tried on both)
Options debug_layout=1, isHtml5ParserEnabled=1

A line break after a table is affecting whether a gap is shown or not, only when html5 parser option is on (turn it off and they're identical).

Html (With Gap):

    <!doctype html><html><head><title>title</title></head>
    <body>
        <table width='100%'>
            <tbody>
            <tr>
                <td width='100%'>Table</td>
            </tr>
            </tbody>
        </table>
        <p>Paragraph</p>
    </body>
    </html>

Produces: https://dl.dropboxusercontent.com/u/459290/github-prs/with-gap.png

Html (Without Gap - notice the p tag is right after the table now):

    <!doctype html><html><head><title>title</title></head>
    <body>
        <table width='100%'>
            <tbody>
            <tr>
                <td width='100%'>Table</td>
            </tr>
            </tbody>
        </table><p>Paragraph</p>
    </body>
    </html>

Produces: https://dl.dropboxusercontent.com/u/459290/github-prs/without-gap.png

(v0.8 is looking great!)

**Comment by bsweeney** [comment]
This does appear to be the case and does not happen in 0.7.0. I wonder if this is related to the change in margin collapse handling (commit cce7388).

**Comment by eddturtle** [comment]
I believe you were right, commented some of it out and it started to look right again. I think it was because it was ignore block elements, when it should have been ignoring block elements and tables. Not 100% but I think it's right (thanks for the guiding commit).
