### ISSUE TITLE
Multiple fonts on one page not rendering in right way.

### ISSUE THREAD

**Issue by devacctgmailcom** [dompdf/dompdf#1397]
Hello Everyone

I am using Dompdf 0.8.0 to create my PDF. In one page there are multiple fonts are used. i.e. 2 font types are used for signatures and one is regular font.
But when we reach to signature fonts it change complete page fonts to signature fonts.
Please see attached image and underlined text. These marked text are signatures, other than of these are normal text. Here note the behavior of changing fonts. Each signature have different font family. And after text changed to respective font family.

I tried these ways already:
1. Used classes for signatures.
2. Used fonts family in line in tag.
3. Used fonts in dompdf options: $dompdf->set_option('defaultFont', 'dejavu sans');
4. Also tried with options:
$options = new Options();
$options->set('defaultFont', 'dejavu sans');

Can you please help me to resolve this problem? Please have a look at attachment.

![download](https://cloud.githubusercontent.com/assets/26294737/23738930/cc7b7a02-04c1-11e7-9778-159ed801392a.png)

**Comment by firetheweb** [comment]
I am sorry I don't speak English, I am Chinese, and I can speak Japnanese

2017-03-09 14:47 GMT+08:00 devacctgmailcom <notifications@github.com>:

**Comment by devacctgmailcom** [comment]
Is there anybody to help me please?

**Comment by bsweeney** [comment]
Do you have a sample of the HTML used?

**Comment by devacctgmailcom** [comment]
HTML have same structure as a HTML page have. There are 6 pages in PDF. First 5 pages are rendering fine, but in 6th page signature fonts changes and this happened.

> <div class="wizard-page">
    	
    	<div class="wizard-page-inner">
    		<div class="row">
    			<div class="col-sm-12">
    				<p><b><u>Main Listing Contact</u></b></p>
    				<p>Full Name:<span class="hr-bottom highlight wizard_page_full_name">Test</span> Phone Number:<span class="hr-bottom highlight wizard_page_phone_number">234567</span> Email:<span class="hr-bottom highlight wizard_page_email">testemail</span> </p>
    				<p><b><u>Acknowledgement Signatures</u></b></p>
    				<p>I / we acknowledge that I/we have read and understand the above information and agree to the terms by signing below:</p>
    				<div class="row">
                        <div class="col-sm-4">
                            <div class="hr-bottom min-height-35">Andrew Hillman</div>
                            
                            <p>Broker Print Name</p>
                        </div>
                        <div class="col-sm-4">
                            <div class="hr-bottom min-height-35 broker-signature-font">First signature font</div>
                            
                            <p>Broker Signature</p>
                        </div>
                        <div class="col-sm-4">
                            <div class="hr-bottom min-height-35"></div>
                            
                            <p>Date</p>
                        </div>
                    </div>
                    <div class="property_seller_new_holder">
                        
                                    <div class="row">
                                        <div class="col-sm-4">
                                            
                                            <div class="hr-bottom min-height-35 highlight wizard_page_seller_name_0" id="wizard_page_seller_name_0"></div>
                                            <p>Seller #1 Type Name</p>
                                        </div>
                                        <div class="col-sm-4">
                                            
                                            <div class="hr-bottom min-height-35 highlight signature_font wizard_page_seller_signature_0" id="wizard_page_seller_signature_0">Second Signature font</div>
                                            <p>Seller #1 Signature</p>
                                        </div>
                                        <div class="col-sm-4">
                                            
                                            <div class="hr-bottom highlight "></div>
                                            <p>Date</p>
                                        </div>
                                    </div>
                          
                    </div>
                    <p><b><u>Payment</u></b></p>
                    <p>We accept <u>Visa</u>, <u>MasterCard</u>, <u>Discover</u> and <u>American Express</u>. You can either pay by filling out the payment form below or online. We remove all payment info on this form once processed. We are very serious about privacy and security. All information is kept confidential. <b>If paying online please keep this page attached to the agreement.</b></p>
                    <p><b>Would you like us to send you a customizable for sale sign? <span class="hr-bottom highlight wizard_page_sale_sign text-capitalize">NO</span> Price: <u>$40.00</u></b></p>
                    
    			</div>
    		</div>

    	</div>
    	
    </div>

**Comment by devacctgmailcom** [comment]
This html is used for last page. First line of code got disappeared.

`<div class="wizard-page">`

**The main thing is that, everything is working fine on localhost but not working on server. Its neither showing any error nor working fine.**

**Comment by bsweeney** [comment]
I'm unable to reproduce the issue. Seeing the full document (HTML + CSS) might help.

That being said, the fact that it works differently on different systems may indicate a migration issue. Do you copy the code from one system to another or deploy from a repository? You may need to flush your font cache and reset your font directory on the server.
