### ISSUE TITLE
Format Numbers

### ISSUE THREAD

**Issue by vhngroup** [dompdf/dompdf#1399]
Hi, I could help, in advance thanks.
I have a number, example a million, that in the report appears like this: 1000000.00 I want to include the separators of thousands, it is deicir that appears as follows:
1,000,000.00
I could indicate how to achieve that, use dompdf with lavage 5.3 and the data come from the database, of decimal type (11.3).
Thank you

**Comment by bsweeney** [comment]
This isn't really a something dompdf is designed to handle. If you're pulling the data from a database can't you use the PHP [`number-format`](http://php.net/manual/en/function.number-format.php) function to format the number?

**Comment by vhngroup** [comment]
Thanks @bsweeney I will check it.
