### ISSUE TITLE
DomPDF doesn't work on server

### ISSUE THREAD

**Issue by levaifelasticad** [dompdf/dompdf#1400]
Hi, 

I have a strange issue with DomPDF. 
If I run my cron file locally, the pdf files are generated without any problem, but if I run the same cron on our server, the files doesn't appears.
I put some var_dump messages on dompdf code, and I found that something happens with reflow function in DomPDF class. 
It's also strange that, if I run locally my cron, my var_dump messages doesn't show from this peace of code , after the ob_start() call. But it's appear if I run cron on server.

 $this->saveLocale();
        $options = $this->options;

        $logOutputFile = $options->getLogOutputFile();

        if ($logOutputFile) {
            if (!file_exists($logOutputFile) && is_writable(dirname($logOutputFile))) {
                touch($logOutputFile);
            }

            $this->startTime = microtime(true);
            if (is_writable($logOutputFile)) {
                // if I put here var_dump('Show 1') it's appear
                ob_start();
            }
        }
       // if I put here var_dump('Show 2') it's doesn't appear
        $this->processHtml();

        $this->css->apply_styles($this->tree);

        // @page style rules : size, margins
        $pageStyles = $this->css->get_page_styles();
        $basePageStyle = $pageStyles["base"];
        unset($pageStyles["base"]);

        foreach ($pageStyles as $pageStyle) {
            $pageStyle->inherit($basePageStyle);
        }

Can you explain me what am I doing wrong here ?

Thanks,
Feri

**Comment by levaifelasticad** [comment]
[generate_bills.zip](https://github.com/dompdf/dompdf/files/837773/generate_bills.zip)

I upload the sample code.

**Comment by levaifelasticad** [comment]
Problem resolved.:)
I forgot to add GD extension on the server.

**Comment by MatthiasKuehneEllerhold** [comment]
composer should have warned you because "ext-gd" is required in the composer.json!

**Comment by bsweeney** [comment]
I hope composer did indeed warn on that missing dependency.
