### ISSUE TITLE
Custom Font not working

### ISSUE THREAD

**Issue by PacmanOnCrack** [dompdf/dompdf#1401]
I´m writing a Wordpress plugin where I export html content to a PDF file via DomPdf. It´s working very well except that I´m not able to use a custom font in my PDF. I tried all kinds of things like

- upload the .ttf file and use the @font-face rule (CSS inline) :
`@font-face {
    font-family: Ayita;
    src: url(' . plugin_dir_path( __FILE__ ) . 'fonts/Ayita/AyitaPro-Thin.ttf) format("truetype");
}`

- generate .afm and .ufm, upload the files and add the font to the "dompdf_font_family_cach.dist.php"

- load the font via `$font = Font::load(plugin_dir_path( __FILE__ ) . 'fonts/Ayita/AyitaPro-Thin.ttf);`
but then I´m not sure how to use the `$font` varialble. 

Have I overseen something important? Maybe this issue has to do something with Wordpress, considering I can´t use stylesheets in the PDF the same way as I do in Wordpress, where I load them with `wp_enqueue_style(' .. ')`, I have to specify the CSS for the PDF with inline-style attributes.

**Comment by bsweeney** [comment]
The third attempt won't work with the way dompdf is using the resources.

The second attempt _may_ work, but I'd have to see how you modified the font family cache and what files you uploaded.

The first attempt is preferred. By inline do you mean `style="..."` on an element? Or do you mean putting a style element inside your HTML. The former will not work, the latter should be fine. Just make sure you have read/write access to the directories specified in your configuration for the temporary directory, font directory, and font cache directory.

**Comment by PacmanOnCrack** [comment]
From the first attempt I tried both options, I am able to use the fonts already specified in the cache, like "DejaVu Sans". In the html-String I feed to `loadHtml(..)` I have something like this:

`<html>
<head>
<style>
     @page { margin: 10mm 0mm 10mm 0mm; }
     @font-face {
             font-family: "Ayita";
             src: url(' . plugin_dir_path( __FILE__ ) . 'fonts/Ayita/AyitaPro-Thin.ttf) format("truetype");
     }
     body, div {
             font-family: Ayita, sans-serif;
             font-size: 1em;
     }
</style>
</head>
    <body>
        <div> text </div>
    </body>
</html>
`

I also checked the directories, I have read & write access to all of them. I referenced the same .ttf file in an `@font-face` rule in the stylesheet for the UI, and I can use the font in my markup of the UI. It just won´t export to the PDF.

**Comment by bsweeney** [comment]
What does `plugin_dir_path` return? Is it the physical path to the file or a URI?

**Comment by hakimio** [comment]
I guess that's wordpress function:
https://developer.wordpress.org/reference/functions/plugin_dir_path/

Return
(string) the filesystem path of the directory that contains the plugin.

**Comment by PacmanOnCrack** [comment]
Hello bsweeney, sorry for the long reply time, I had to take a break from this project. 
Yesterday I started again and could manage to print a PDF with a custom font. I´m very glad, but it bothers me, that I don´t really know what caused the issue in the first place. 
I´ll keep you updated if something changes. Thank you for your support.

**Comment by bsweeney** [comment]
I'll close this, then. But if you run across the same issue in the future let us know and we can revisit.

**Comment by PacmanOnCrack** [comment]
Hello bsweeney, what did the trick in the end was to use this [ttf2ufm-converter](http://www.jimwrightonline.com/php/tcpdf_php4/fonts/ttf2ufm/) and upload the .afm, .ufm and .ttf file to dompdf/lib/fonts. After registering the font in the font-family cache, it worked perfectly. 

This ist the only way I could use custom fonts, maybe somebody encounters the same problem.

**Comment by michaellwatson** [comment]
This worked for me but using https://everythingfonts.com/ttf-to-ufm instead to create the .afm and .ufm. I also copied a afm.php and renamed it to my font, then added my font to the end of dompdf_font_family_cache.dist.php. Also make sure the dompdf/lib/fonts dir is writeable

**Comment by coder-rukon** [comment]
Use css and it worked. 
@font-face {
  font-family: myFontName;
  src:url('http:://yourwebsite.com/myFontName.ttf');
}
p {
	font: myFontName;
}

**Comment by patrick2k12** [comment]
If anyone still looking for a solution:
https://github.com/dompdf/dompdf/issues/1566#issuecomment-591955876
