### ISSUE TITLE
more text space (top) after upgrade 0.6.0 > 0.8.0

### ISSUE THREAD

**Issue by PDFCoder** [dompdf/dompdf#1402]
After upgrading from 0.6.0 to 0.8.0 we made all necessary changes to the code and the PDF results are looking fine so far.

But there is one thing in the PDF result that is different compared to the PDFs rendered with 0.6.0 release: The fonts have more space at the top (ascender?) in the text output. Thus in table headers (th) or table cells (td) the text starts with about 1mm space to the top table cell border. In other words: if (th) has 0.3em padding top and bottom the resulting text is sitting „below the line“.

We already set the fontHeightRatio option to 1.0 to make the line heights look like in former dompdf versions.

We tested the standard helvetica and DejaVue Sans included, and the font we have been using for years as standard with the old versions: DejaVue Sans Condensed. All the same result.

Do we have to adjust our html/css table cell paddings to fix this different rendering or is this a bug concerning font rendering that will be fixed in a new release? Or was the rendering in version 0.6.0 not correct and is now fixed?

Best regards,
Thorsten

**Comment by PHPGangsta** [comment]
I have a similar problem. I have this simple HTML:
```
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Not needed</title>
</head>
<body style="margin: 50px;">
    <div style="margin-bottom: 40px; font-size: 0.7em;">
        <div style="width: 300px; display: inline-block;">Hello here, first text...................................................</div>
        <div style="width: 300px; display: inline-block; float: right;">Hello there, second text........................................................</div>
    </div>
</body>
</html>
```

With 0.6 it looks fine. With 0.8, both strings are not on the same line, the right string is 3px or 5px lower than the left string.
![Image of difference](http://phpgangsta.de/download/dompdf08.png)

Maybe this is the same problem...

**Comment by simonberger** [comment]
No, your problem seems to have something to do with floating, while his is a general whitespace change (intended or not).

@PDFCoder 
If it's not too much work could you show a screenshot of the space change?
Best without css changes on your side.
Also comparing it to chrome browser rendering is always a good indicator if its ok or should be called a problem.

**Comment by PDFCoder** [comment]
Sorry for my delay. We switched to pdflib backend and had many things to fix.
By the way, the space problem exists with cpdf and pdflib! Here is a screenshot that shows the padding problem with a simple th (same problem with td), padding top and bottom are 3px:

![table_head](https://user-images.githubusercontent.com/26413959/30206534-aac3d0e8-948c-11e7-9cff-a308e245fd86.png)

**Comment by PDFCoder** [comment]
After some deeper testing it seems that I've found the solution to the problem: 
For my tests I used the option 'fontHeightRatio' and set it to '1.1', because line heights like '1.2em' were more narrow than before (with dompdf 0.6). If I set this value to 1.0 the output of the th/td paddings look ok! Sorry for the confusion … It seems that I have to adjust all em line heights in the css styles.

**Comment by bsweeney** [comment]
The line height calculation was tweaked in the 0.8.0 release but it still needs some work. We can look into it more but we'd need to see a sample of the HTML that was used. Either way I'm glad you were able to come to a resolution.
