### ISSUE TITLE
Font is not alligning properly

### ISSUE THREAD

**Issue by pimjansen** [dompdf/dompdf#1403]
I just load a custom font:
```
$options->setFontDir('skin/frontend/vodafone/default/fonts');
$options->setDefaultFont('customfontrg');
$options->setIsPhpEnabled(true);
$options->setIsHtml5ParserEnabled(true); // For combining multiple pdf outputs
$options->setIsFontSubsettingEnabled(true);
$options->setDebugCss(true);
$options->setDebugLayout(true);
$options->setDefaultPaperSize('A4');
$options->setDpi(72);
$dompdf = new Dompdf($options);
```

My font directory got a font family file as well which ensures that the fonts can be parsed:
```
<?php
return [
    'customfontrg' =>
        [
            'normal' => 'skin/frontend/vodafone/default/fonts/Roboto',
        ],
];
```

The result is that the font do is used but it is not alligning properly. I already tried it with multiple fonts but all have the same result (see attached image)
![font-align](https://cloud.githubusercontent.com/assets/1457219/23987745/5bdb13f6-0a2b-11e7-8d7e-be02a9d2f936.png)

Problem is that there is room in my P tag to put more text but the room is just not used properly. According to the debugger the yellow layer is used for room that i used at this point for writing the actual text but its clearly not.
My PDF is created with basic stuff (`<p>text</p>`)

Hope someone can help.

**Comment by bsweeney** [comment]
Commented on SO: http://stackoverflow.com/q/42764414/264628
