### ISSUE TITLE
text is writing over image

### ISSUE THREAD

**Issue by cperrot** [dompdf/dompdf#1405]
from 0.7.0 to 0.8.0 when including an image text is being written over the image.
text does not start underneath the image but writes over it.

what do you need from me to support you fixing this problem?

regards

Cedric

**Comment by bsweeney** [comment]
A [minimal, complete, and verifiable example](http://stackoverflow.com/help/mcve) always helps.

**Comment by cperrot** [comment]
well I can't help you with minimal but I've attached the application to install.
here is the link to download the zip file www.smartopensoft.net/bambooinvoice.zip

to install there is an sql in the root to get the database going then edit
application\config\config.php
application\config\database.php
to match your environment.

In system\helpers\to_pdf_helper.php
you can switch the dompdf version from 0.7.0 to 0.8.0.

Login into the application with following credentials
user:	admin@admin.com
pwd:	password

then create a client
then an invoice
generate invoice pdf and you'll see the difference.

Regards

Cedric

**Comment by bsweeney** [comment]
That's a bit more work than I want to do to get a sample of the HTML 😬. Can you just grab the HTML you're feeding to Dompdf?

How is the image styled? Since the release it's come to our attention that auto left/right margins can be a problem.

**Comment by bsweeney** [comment]
I think you're probably running into the same issue discovered in #1482. You have auto margins on your H2 element, which Dompdf is having trouble parsing. Seems like you can just specify a margin-top of "0" as a work around.
