### ISSUE TITLE
css float left no working in version 0.8

### ISSUE THREAD

**Issue by Keval17** [dompdf/dompdf#1409]
I am having trouble with float left while generating pdf. It shows perfectly fine in html page.
I am using version 0.8

Here is the html code. 

<!DOCTYPE html>
<html>
<head>
<title>Portfolio Summary Report</title>
<meta charset="UTF-8">

<style>

.bodyclass
{
	background: #ffffff;
	margin:0.5in;
	//border:1px solid black;
}

.summary_outer
{
	font-size: 100%; 
	font-weight: bold; 
	text-align: center;
	width: 100%; 
	position: relative;
	min-height: 1px; 

	float: left;
	 background: #ffffff;
}

.summary_header
{
color: black; 
font-size: 150%;
font-weight: bold;
text-align: left; 
width: 100%; 
min-height: 1px;
 background: #7cb6c7; 
}

.summary_stats
{
width:100%;
margin-top:10px;
border:0px solid black;
}
.summary_stats_inner
{

width:32%;
text-align:left;
border:0px solid black;
float:left;
}
</style>

</head>

<body class="bodyclass">

	<div class="summary_outer">

		
		<div class="summary_header"	>
			Portfolio Summary 
		</div>
		<div class="summary_stats">
			<div class="summary_stats_inner">
				Average Comfort Score : 95% ( 5% )
				<br>
				Average Asset Score : 90% (6% )
			</div>
			<div  style="float:left;text-align:left;border:0px solid black;width:25%;">
				Average Energy Savings : 43% ( 5% )
				<br>
				Average ESTAR Score: 12 ( 3% )
			</div>
			
		</div>
		
	
	</div>

</body>
</html>

**Comment by Keval17** [comment]
A fresh install did the trick. Thank You.

**Comment by bsweeney** [comment]
Thank goodness for quick fixes. I dunno why this is all it takes sometimes.

**Comment by moschel26** [comment]
@bsweeney, I need you help. Look at this : https://github.com/dompdf/dompdf/issues/1450
