### ISSUE TITLE
Get page count without render

### ISSUE THREAD

**Issue by 0vordhosbn00** [dompdf/dompdf#1410]
Hello,

Is there any solution for using "$dompdf->getCanvas()->get_page_count()" without doing "$dompdf->render()" before ?

Because in my case, with doing a "render" , "$dompdf->getCanvas()->get_page_count()" is equal to 2, and the "render" take a lot of time because I doing a while on this. Problem : if I don't use "render" before get number of page, it return always "1".

Any suggestions ?

Thanks in advance.

**Comment by m4tthumphrey** [comment]
How would you expect to get any sort of page count with rendering the content first?

**Comment by 0vordhosbn00** [comment]
@m4tthumphrey Maybe by calculate the "final" content just before transform in pdf, and get the page count of the final document faster. Do you think it's just impossible ?

**Comment by bsweeney** [comment]
Pages aren't determined until after rendering is complete. Dompdf splits the content into pages as it renders the document.

If your document is only two pages and takes a long time to render there could be some other issue.
