### ISSUE TITLE
Http Response Header Content-Length different,Case the pdf don't open

### ISSUE THREAD

**Issue by Stone-Ynn** [dompdf/dompdf#1413]
different Server environment , one is ok, one is error. this error may be caused by **mb_string()** function . But I don't know how to solve. who can help me ? 

**The right heade as follow :**

Accept-Ranges:182089
Cache-Control:private
Connection:keep-alive
Content-Disposition:attachment; filename="abc360%3F%3F%3F%3F%3F%3F.pdf"; filename*=UTF-8''abc360%E8%AF%BE%E7%A8%8B%E6%9C%8D%E5%8A%A1%E6%9D%A1%E6%AC%BE.pdf
Content-Length:182089
Content-Type:application/pdf
Date:Mon, 27 Mar 2017 11:00:22 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Pragma:no-cache
Server:nginx/1.11.7
X-Powered-By:PHP/5.6.29

**Below is error:**

Accept-Ranges:162663
Cache-Control:private
Connection:Keep-Alive
Content-Disposition:attachment; filename="abc360%3F%3F%3F%3F%3F%3F.pdf"; filename*=UTF-8''abc360%E8%AF%BE%E7%A8%8B%E6%9C%8D%E5%8A%A1%E6%9D%A1%E6%AC%BE.pdf
Content-Length:162663
Content-Type:application/pdf
Date:Mon, 27 Mar 2017 11:24:07 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive:timeout=15, max=98
Pragma:no-cache
Server:Apache
X-Powered-By:PHP/5.6.13

**Comment by simonberger** [comment]
You have to give us an idea of what you did and what the result was.

Ideally provide a small example that works on the first and fails on the second. But at least show some example code of the Dompdf methods you used.

Whats the content you get in the failure case. Is it just an incomplete pdf, complete garbage or different (please compare on your own. You might also be able to just dump the binary on teh server).

**Comment by Stone-Ynn** [comment]
@simonberger 
OK , this is a case:

```
if( isset($request['format']) && $request['format'] == 'pdf'){
            //unicode 
            setlocale(LC_ALL, 'zh_CN.GBK'); 

            // instantiate and use the dompdf class
            $options = new Options();
            $options->set('enable_font_subsetting', true);
            $dompdf = new Dompdf($options);
            $dompdf->loadHtml($html);

            // (Optional) Setup the paper size and orientation
            $dompdf->setPaper('A4', 'landscape');

            // Render the HTML as PDF
            $dompdf->render();

            // Output the generated PDF to Browser or download
            $file_name = (isset($request['file_name'])?$request['file_name']:'合同').'.pdf';
            $show_way = [
                'Accept-Ranges'=>(isset($request['output']) && $request['output']=='download')?1:0,
                'Attachment'=>(isset($request['output']) && $request['output']=='download')?1:0,
            ];
            $dompdf->stream($file_name,$show_way);
}
```

the first and fails on the second used the save code.  The fails one can't show  text , Just can disply picture.

I wonder if the apache conf caused the problem.

**Comment by bsweeney** [comment]
To start you might try a simpler file name using just latin characters. Also I believe there's some potential problems when setting the locale using LC_ALL. You might try removing that statement and seeing what happens.

**Comment by Stone-Ynn** [comment]
@bsweeney After I removing that line, The same question happend.

Then i open the error pdf source file and the right one. I find the error one missing some lines.

The following is header of two files.

**right one:**
```
%PDF-1.3
1 0 obj
<< /Type /Catalog
/Outlines 2 0 R
/Pages 3 0 R >>
endobj
2 0 obj
<< /Type /Outlines /Count 0 >>
endobj
3 0 obj
<< /Type /Pages
/Kids [6 0 R
15 0 R
17 0 R
19 0 R
21 0 R
23 0 R
25 0 R
27 0 R
31 0 R
33 0 R
35 0 R
37 0 R
]
/Count 12
/Resources <<
/ProcSet 4 0 R
/Font << 
/F1 8 0 R
...
```

**the error** 
```
%PDF-1.3
1 0 obj
<< /Type /Catalog
/Outlines 2 0 R
/Pages 3 0 R >>
endobj
2 0 obj
<< /Type /Outlines /Count 0 >>
endobj
3 0 obj
<< /Type /Pages
/Kids [6 0 R
]
/Count 1
/Resources <<
/ProcSet 4 0 R
/Font << 
/F1 8 0 R
>>
```

**Comment by Stone-Ynn** [comment]
@bsweeney 
Server Env: 
Error one : PHP5.6.13 Apache 2.2.29(Unix) , PHP load method: php model
Right one: PHP5.6.29 Apache2.4(Unix) , PHP load method: php-fpm

**Comment by bsweeney** [comment]
I think the content-length issues is a distraction. What type of error messages are you getting? Also, I just saw you mentioned MBString ... is that extension available in both environments.

**Comment by Stone-Ynn** [comment]
I saw the apache error log . while apache starting, have notice caused.  The mean is that your php config have some error. But don't  impact use. 

pdf content-length missing some bit may caused by apache2.2 version and php 5.6.19, may be the apache is too old.

**Comment by bsweeney** [comment]
I don't think it's the version of apache. Can you post the error messages?

**Comment by Stone-Ynn** [comment]
I have opned all error report, PHP and Apache ,while i run the pdf create ,no error caused!

**Comment by Stone-Ynn** [comment]
I have soved the problem. while i upgrade the apache to 2.4 and php to 5.6.29 . Everything is OK

**Comment by bsweeney** [comment]
Weird. Not what I would have expected. I guess it could have been a bug between the versions of PHP and apache. Or maybe a bug in that version of PHP.

I'm going to go ahead and close, but if the issue pops back up let us know.
