### ISSUE TITLE
Class 'DOMPDF' not found in Wordpress my customer plugin

### ISSUE THREAD

**Issue by nextun** [dompdf/dompdf#1414]
I have created plugin hat work basic thing normally. I want to add dompdf to it, but I got error. What I did as bellow,

```php
function my_pdf_action(){

//path is ok.
require_once('dompdf/autoload.inc.php');

$dompdf = new DOMPDF();// error line 
$dompdf->setPaper('A4','potrait');
$dompdf->load_html("<h1>Hello World</h1><p>PDF description</p>");
$dompdf->render();
$dompdf->stream('title.pdf');

}

add_action('init', 'my_pdf_action');
```

Once I run this from the front-end it says
"Fatal error: Class 'DOMPDF' not found in /site_location../wp-content/plugins/my_plugin-pdf/my_plugin-pdf.php on line number"

How to fix this ?

**Comment by bsweeney** [comment]
If you're using 0.7.0 or better (and I'm guessing you are since you're using the autoloader) you should re-read the [quick-start documentation](https://github.com/dompdf/dompdf#quick-start). Try the following:

```
// reference the Dompdf namespace
use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();
```
