### ISSUE TITLE
Missing "quadTo" method in Cpdf class

### ISSUE THREAD

**Issue by hakimio** [dompdf/dompdf#1415]
Cpdf class in dompdf is missing "quadTo()" method required by php-svg-lib to render some svg images. The missing method can be taken from php-svg-lib CPdf class (src/Svg/Surface/CPdf.php).

Example image to reproduce the "Call to undefined method Cpdf::quadTo()" attached to this bug report.

[arrow-down-green.zip](https://github.com/dompdf/dompdf/files/878781/arrow-down-green.zip)

**Comment by bsweeney** [comment]
Just thinking out loud, but I'm wondering if there's a namespacing issue since php-svg-lib includes it's own version of CPDF.

At any rate I think it makes sense to include this in our version of CPDF.

**Comment by hakimio** [comment]
The classes use different character casing "Cpdf" vs "CPdf", so I don't think namespacing is an issue, but maybe @PhenX might know more about it.

**Comment by bsweeney** [comment]
I'll go ahead and pull in #1493, no harm in the added functionality.
