### ISSUE TITLE
 Uncaught Error: Call to a member function get_cellmap() on null 

### ISSUE THREAD

**Issue by Zeeshan99** [dompdf/dompdf#1416]
Please help me!
I am using first time DOmpdf and facing this strange issue. 
This is what i' m facing when try to get file file to convert to pdf

```
Fatal error: Uncaught Error: Call to a member function get_cellmap() on null in C:\xampp\htdocs\dom\dompdf\src\FrameReflower\TableRow.php:60 Stack trace:
#0 C:\xampp\htdocs\dom\dompdf\src\FrameDecorator\AbstractFrameDecorator.php(893): Dompdf\FrameReflower\TableRow->reflow(Object(Dompdf\FrameDecorator\Block))
#1 C:\xampp\htdocs\dom\dompdf\src\FrameReflower\Inline.php(78): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(Object(Dompdf\FrameDecorator\Block))
#2 C:\xampp\htdocs\dom\dompdf\src\FrameDecorator\AbstractFrameDecorator.php(893): Dompdf\FrameReflower\Inline->reflow(Object(Dompdf\FrameDecorator\Block))
#3 C:\xampp\htdocs\dom\dompdf\src\FrameReflower\Block.php(850): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(Object(Dompdf\FrameDecorator\Block))
#4 C:\xampp\htdocs\dom\dompdf\src\FrameDecorator\AbstractFrameDecorator.php(893): Dompdf\FrameReflower\Block->reflow(Object(Dompdf\FrameDecorator\Block))
#5 C:\xampp\htdocs\dom\dompdf\src\FrameReflower\Block.php(850): Dompdf\FrameDecorator\AbstractFrameDecorator- in C:\xampp\htdocs\dom\dompdf\src\FrameReflower\TableRow.php on line 60
```

**Comment by bsweeney** [comment]
Please post a sample of the HTML + CSS that's causing the issue.

There may be some relevant issues already: [issue search for "get_cellmap"](https://github.com/dompdf/dompdf/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+get_cellmap)

**Comment by bsweeney** [comment]
Is this your SO question? http://stackoverflow.com/q/43128372/264628

**Comment by Zeeshan99** [comment]
Thanks #bsweeney for your response.

Yes, that's my question, there you can see the complete code and details about what's going there.
Please help me. if you can .

**Comment by hakimio** [comment]
You might have messed up with colspans in your tables. Remove them one-by-one to find out which one is causing issues.

**Comment by bsweeney** [comment]
Or rowspan? Any luck tracking down the issue?

**Comment by semul** [comment]
DOMpdf doesn't support TABLE-CELL

**Comment by guiachcar** [comment]
Check if you've opened and properly closed the table tags

**Comment by bsweeney** [comment]
Definitely a structural issue. With the the HTML5 parser enabled the error is not encountered. Running through a [validator](https://validator.w3.org) I found a span element directly inside a table element.

**Comment by Gregorio19** [comment]
the problem in my case is that i am using  display: flex in the css style and that make the error

**Comment by TheiAndy** [comment]
It seems display:inline-block; causes this error too.

**Comment by jonathanpmartins** [comment]
```
display: block;
```
inside <table> tag too

**Comment by bsweeney** [comment]
If you're messing with the display type of table elements you're probably going to run into problems. We haven't fully implemented anonymous table elements yet (#449) and until that happens you should avoid that type of styling.

**Comment by Mutale85** [comment]
I had the same issue. I discovered that i had closed the table twice. </table></table>. It worked good after removing one.

**Comment by zelucena** [comment]
As of 2022 I got this issue because of incorrect closing tags. Not a problem with the tool itself although I would appreciate a more descriptive error message
