### ISSUE TITLE
I generate empty pdf

### ISSUE THREAD

**Issue by matiaswsr** [dompdf/dompdf#1418]
I use dompdf to generate a pdf but generate empty pdf from a page .php
help?

**Comment by hakimio** [comment]
You have to provide at least the html produced by your "page.php" if you want to get any help.

**Comment by matiaswsr** [comment]
The page.php generate a simple page, his name is 'buscar.php' and generate a html page from a query to mysql .

how to happen the page .php to dompdf?

The code page is (code ti generate pdf, this code generate a blank page):

<?php
	ob_start();
	require_once("dompdf/dompdf_config.inc.php");

	$html ='buscar.php';

	$dompdf = new DOMPDF();
	$dompdf -> load_html($html);
	$dompdf -> render();

	$pdf = $dompdf -> output();
	$filename = "ficha".time().'.pdf';
	file_put_contents($filename, $pdf);
	$dompdf -> stream($filename);
?>

**Comment by hakimio** [comment]
Post what you have in your $html variable,

**Comment by matiaswsr** [comment]
In $html variable I try to pass the page 'buscar.php'

The code of "buscar.php" is:

`

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="css/estiloBuscar.css">		
		<script type="text/javascript" src="js/jquery-3.1.1.min.js"></script>
	</head>
<body>
	<?php
		include("conexion.php");

		//Obtengo la cedula a buscar
		$cedula = $_POST["cedula"];

		//Consulta para obtener todos los registros de la tabla datos
		$sql = "SELECT * FROM datos WHERE cedula=$cedula";	

		$resultado = mysqli_query($conexion, $sql);

		if($row = @mysqli_fetch_array($resultado, MYSQL_ASSOC)){
			do{
				echo "<div class='container espacio-arriba'>";
				echo "<div class='row'> <div class='col-md-2'></div>";	
				echo "<div class='col-md-8'>";
				echo "<form class='fondo' >";
				echo "<legend><strong>Maestra: Ver&oacute;nica Bueno. A&ntilde;o 2017</strong></legend>";
				echo "<div class='form-group' id='centrar'>";
				echo "<label>Nombre:</label> $row[nombre]<br>";
				echo "<label>Apellido:</label> $row[apellido]<br>";
				echo "<label>Edad:</label> $row[edad]<br>";
				echo "<label>C&eacute;dula:</label> $row[cedula]<br>";
				echo "<label>Nacionalidad:</label> $row[nacionalidad]<br>";
				echo "<label>Domicilio:</label> $row[domicilio]<br>";
				echo "<label>T&eacute;lefono:</label> $row[telefono]<br>";
				echo "<label>Cobertura M&eacute;dica:</label> $row[coberturaMedica]<br>";
				echo "<label>Emergencia:</label> $row[emergencia]<br>";
				echo "<label>Enfermedades:</label> $row[enfermedades]<br>";
				echo "<label>Alteraciones:</label> $row[alteraciones]<br>";
				echo "<label>Usa lentes:</label> $row[lentes]<br>";
				echo "<label>Vive con:</label> $row[viveCon]<br>";
				echo "<label>Cantidad de hermanos/as:</label> $row[cantHmnos]<br>";
				echo "<label>Edades de sus hermanos:</label> $row[edadesHmnos]<br>";
				echo "<label>Madre/Padre/Tutor:</label> $row[madrePadreTutor]<br>";
				echo "<label>Ocupaci&oacute;n:</label> $row[ocupacion]<br>";
				echo "<label>Nivel educativo:</label> $row[nivelEducativo]<br>";
				echo "<label>Beneficios Sociales:</label> $row[beneficios]<br>";
				echo "<label>Concurre a la escuela en:</label> $row[concurreEn]<br>";
				echo "<label>Recorre:</label> $row[recorre] (cuadras)<br>";
				echo "<label>Otras actividades:</label> $row[otrasActividades]<br>";
				echo "<label>Se duerme a las:</label> $row[seDuerme]<br>";
				echo "<label>Mira los programas de TV:</label> $row[programasTV]<br>";
				echo "<label>Le gusta jugar a:</label> $row[juega]<br>";
				echo "<label>Tiempo que dedica a estudiar:</label> $row[tiempoEstudio]<br><br>";				
			}while($row = mysqli_fetch_array($resultado, MYSQL_ASSOC));
				echo "<div class='espacio-arriba'><button type='button' name='volver' class='btn btn-primary btn-lg btn-block' id='pdf' value='volver' onClick='window.location.href=\"index.html\"''>Volver Atr&aacute;s</button></div>";				
				echo "<div class='espacio-arriba'><button type='button' name='pdf' class='btn btn-primary btn-lg btn-block' id='exportar' value='generar' onClick='window.location.href=\"pdf.php\"''>Generar pdf</button></div>";
				echo "</div>";		
				echo "</form></div><div class='col-md-2'></div></div>";
				echo "<div class='espacio-arriba2'><footer><p>Ver&oacute;nica Bueno &copy</p></footer></div>";
		}else{
			echo "<div class='container espacio-arriba'>";		
			echo "<div class='row'> <div class='col-md-4'></div>";	
			echo "<div class='col-md-4'>";
			echo "<form class='fondo' >";
			echo "<legend><strong>Año 2017</strong></legend>";
			echo "<div class='form-group'>";
			echo "<div class='form-group' id='centrar'>";
			echo "<br><strong>¡No existen registros!</strong><br><br>";				
			echo "<button type='button' name='volver' class='btn btn-primary' value='volver' onClick='window.location.href=\"index.html\"''>Volver Atr&aacute;s</button>";
			echo "<button type='button' name='pdf' class='btn btn-primary' value='pdf' onClick='window.location.href=\"pdf.php\"''>Descargar PDF</button>";
			echo "</div></div></div>";
			echo "</form></div></div>";

		}		
	?>
</body>
</html>




`

**Comment by matiaswsr** [comment]
$html = 'buscar.php';

**Comment by hakimio** [comment]
It should be HTML code, not PHP... You have to get the output of your PHP code first.

**Comment by matiaswsr** [comment]
Yes I understand.
First the page is formed and then I pass the page already formedbut with extension .php but the page is already loaded (extension .php).
that does not work?

**Comment by matiaswsr** [comment]
Thank you very much for your help!!!
Best regards!

**Comment by hakimio** [comment]
You have to pass html string, not filename to loadHtml(), but as I guess you already figured that out.
Now you can close the bug report.

**Comment by matiaswsr** [comment]
Yes, thank you.
