### ISSUE TITLE
Multi-line "inline-block" reflow issue

### ISSUE THREAD

**Issue by hakimio** [dompdf/dompdf#1419]
Reflowing of div blocks with display "inline-block" and fixed width and height is broken.
Simple steps to reproduce:
* Create a bunch of "inline-blocks" with fixed width and height.
* Make sure they don't fit on a single line and some end-up on the next line.

As a result of the steps above, you will have some invisible "phantom" blocks taking the same amount of space as the inline-block itself.

PS: if you think this bug is a duplicate, please link to existing issue and close this one.

**Comment by hakimio** [comment]
Must be the same as this issue -> https://github.com/dompdf/dompdf/issues/500

**Comment by PowerKiKi** [comment]
Please close this issue, as it duplicates #500.
