### ISSUE TITLE
Overlapping text

### ISSUE THREAD

**Issue by disklos** [dompdf/dompdf#1422]
I'm using PHP5.5 and dompdf 0.7. My code works as expected on my local WAMP server running under Windows 10 64bit. However, on transferring all the files to my server, the text is all scrunched together making a single black line. A table formats reasonably well as does the following text, though this is in the wrong font and not centered as it should be. My CSS uses only Helvetica and Times. 

[screenshot.pdf](https://github.com/dompdf/dompdf/files/895641/screenshot.pdf)

Would someone suggest where I should be looking to find what has changed between the local server and the online one?

**Comment by hakimio** [comment]
Maybe you loading CSS from external location and it wasn't loaded properly.
Posting HTML + CSS which produces this output would help.

**Comment by disklos** [comment]
I should have thought of posting the code. HTML & CSS attached in ZIP file. The HTML code is output from the same PHP file that prints the PDF. 

[printopp.zip](https://github.com/dompdf/dompdf/files/895774/printopp.zip)

**Comment by bsweeney** [comment]
Perhaps the font metrics files are not being read correctly. You might try installing a fresh copy of dompdf, "resetting" your font directory, or fixing the paths in the dompdf_font_family_cache.php file.
