### ISSUE TITLE
Multithreading / race condition when parsing remote fonts

### ISSUE THREAD

**Issue by consolibyte** [dompdf/dompdf#1423]
When pulling in remote fonts, DomPDF right now always uses a temporary file based on the `md5` hash of the remote filename:

* https://github.com/dompdf/dompdf/blob/master/src/FontMetrics.php#L183

I think this leads to a race condition, and the following error: 

`unlink(/tmp//d0914a6f5f9002d1ec6148e4cf9ab7b0): No such file or directory] on line ...`

Consider two HTTP requests that are executing at the same time: 

* Request 1 comes in and gets to this line: https://github.com/dompdf/dompdf/blob/master/src/FontMetrics.php#L183
* Request 2 comes in and recreates the same file, by the same line: 
* Request 1 gets to this line, and DELETES the file: https://github.com/dompdf/dompdf/blob/master/src/FontMetrics.php#L210
* Request 2 tries to delete the file again, BUT now the file DOES NOT EXIST

**Comment by bsweeney** [comment]
Yes, it would make more sense to use a `tempnam` for the temporary file and add some extra checks before copying the file into the font directory.

**Comment by marrch-caat** [comment]
@bsweeney Please consider reviewing the pull request #1466 
We face the problem in our production, and since it's a quite highloaded project - we had to do something to the problem, so I created the patch. It's my first pull request to a vendor library, so I ask you to be patient if I did something wrong :-\

**Comment by bsweeney** [comment]
@marrch-caat you did great. Even remembered to submit to the develop branch, bravo.
