### ISSUE TITLE
Question - Get position of the last element in the pdf

### ISSUE THREAD

**Issue by rick31** [dompdf/dompdf#1424]
Hello, 

Is it possible to know the y position of the last element of the last page ? 

Thanks in advance
Rick

**Comment by bsweeney** [comment]
Should be possible, I'm pretty sure I've done this before. But I'll need to refresh myself on how to get the value. You'll probably need to do it using inline script as I at the end of the rendering process the frame tree is cleaned up.

**Comment by rick31** [comment]
With the "end_frame" callback i can retrieve the frames positions list (with $frame->get_padding_box ) and then i get my last y position. Could you kindly confirm that it's the good way ?

**Comment by bsweeney** [comment]
Yes, that's how you would do it.

**Comment by bsweeney** [comment]
If you get what you need and have time post some sample code here. I know this question has come up before and I've just not had the time to document it.

**Comment by rick31** [comment]
`$dompdf->setCallbacks(array('myCallbacks' => array('event' => 'end_frame', 'f' => function ($infos){
			$frame = $infos["frame"];
			$GLOBALS["array_coord"][] = $frame->get_padding_box();
		})));`

By the way is there a way to search coordinates of an element even if it'snt the last one ? Maybe with a dummy class added to retrieve it during callback ?

**Comment by bsweeney** [comment]
Nice!

I wonder if `get_margin_box` would provide a more accurate number?

You can get the document node via the frame and query it for the class, e.g.:

```
$frame->get_node()->getAttribute("class")
```

Then it's just a matter of parsing for the expected class name.

**Comment by rick31** [comment]
Where is located this function `get_margin_box` ? I will have a look ...

Last but not least, how to get the page number where my element is ?

**Comment by bsweeney** [comment]
Sorry, I meant `get_border_box`.

To get the current page number you should be able to use the page counter (see [AbstractFrameReflower::_parse_content](https://github.com/dompdf/dompdf/blob/0f418c6b58fdeafc2a0e80eb1fa5e644e185089c/src/FrameReflower/AbstractFrameReflower.php#L324)). Something like:

```
$counter_frame = $frame->lookup_counter_frame('page');
$page_number = $counter_frame->counter_value('page', $type);
```

**Comment by bsweeney** [comment]
If you're happy with the solution you should answer your question on SO: http://stackoverflow.com/q/43365702/264628.

**Comment by rick31** [comment]
Sorry for the delay, i haven't notice differences between `get_margin_box` and `get_border_box` but i'll will have a deeper look on it later.. Thanks for the page number tip ! 
The solution seems to be durable so i will post it on SO 👍 

Thanks again !

**Comment by SStembridge** [comment]
How would I find the ending y position of a table that spans multiple pages? I can get the position for ones that fit on a single page because the border box height is an actual number, but for ones that take up multiple pages the height keeps returning as 'auto'.

**Comment by bsweeney** [comment]
@SStembridge I've noticed the same thing. It's something I need to research a bit.
