### ISSUE TITLE
tabs in class strings causing ignoring of class

### ISSUE THREAD

**Issue by millawell** [dompdf/dompdf#1425]
PHP 7.0.14 (cli) (built: Jan 12 2017 11:03:00) ( NTS )
dompdf v0.7.0 and v0.8.0

This example works as it should (hello has a magenta background):

		$dompdf = new Dompdf();
		$html = "
		<html>
			<head>
				<style>
					.bgcolor{
						background-color:#f0f;
					}
				</style>
			</head>
			<body>
				<span class='bgcolor'>hello</span>
			</body>
		</html>";

		$dompdf->loadHtml( $html );
		$dompdf->render();

As soon as I change the html to

                $html = "
		<html>
			<head>
				<style>
					.bgcolor{
						background-color:#f0f;
					}
				</style>
			</head>
			<body>
				<span class='bgcolor\t'>hello</span>
			</body>
		</html>";

The class is ignored.

Note, that I added a `\t` to the span class definition.

**Comment by Mellthas** [comment]
This seems to be resolved now.

**Comment by Mellthas** [comment]
Resolved by de40ed2426796fee5718c531c896595e81266f7b.
