### ISSUE TITLE
stream() causes file to break

### ISSUE THREAD

**Issue by OssiPesonen** [dompdf/dompdf#1426]
I'm attempting to get dompdf working on our system. I seem to have a problem using 

`$dompdf->stream('file.pdf');`

It only seems to produce corrupted PDF files and opening these files with notepad weirdly I see the **HTML up to a point in the source code (`<head>`) from the page I pressed the export button at**.

I'm simply trying to run the example:

```
$dompdf = new Dompdf();
$dompdf->loadHtml('hello world');
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
$dompdf->stream('filename.pdf');
```

However if I change from `->stream()` to  `->output() ` and then save the file on to the server, I get a working PDF. What's wrong here?

I am working on a local setup, Windows 10 and a pretty default WAMP installation.

**Comment by bsweeney** [comment]
Looks like you have output buffering turned on. At some point in the process before you call the stream method the buffer is being written to. Try clearing the buffer prior to streaming. You might also check that HTML to see if there are any PHP warnings thrown in.

**Comment by bsweeney** [comment]
Side note, good on you for checking the source! That's a level of debugging effort not usually put in.

**Comment by OssiPesonen** [comment]
This was my fault. Chevked source code and yes buffer was open.
