### ISSUE TITLE
Can't use PHP in my external file

### ISSUE THREAD

**Issue by Lapotor** [dompdf/dompdf#1430]
This is what i use:
```
<?php
require "dompdf/vendor/autoload.php";
include "rechnungmuster.php";

use Dompdf\Dompdf;

$dompdf = new Dompdf();
//Bei DomPDF PHP aktivieren
define("DOMPDF_ENABLE_PHP", true);
$dompdf->set_option('chroot', 'rechnungmuster.php');
//$dompdf->load_html_file('rechnungmuster.php');
$dompdf->load_html($vorlage);
$vorname = "test";
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream('rechnung');
?>
```

i tried it with `<?php ?>` and `<script type="text/php"></script>`

**Comment by bsweeney** [comment]
Dompdf no longer supports rendering HTMl in the file. You'll need to fully render the PHP to HTML before passing it to Dompdf. You can do that by accessing the file via your web server or by including it and capturing the results to an output buffering.

Note that the `<script type="text/php">...</script>` syntax is mainly used to accommodate embedded script that allows you to access the underlying PDF rendering back end. This doesn't allow you to generate HTML content on-the-fly, but you can add content to the page using the PDF canvas object.
