### ISSUE TITLE
dompdf not work with echo <<< html???

### ISSUE THREAD

**Issue by Francisko68** [dompdf/dompdf#1431]
This code works OK:

2. require_once 'dompdf/autoload.inc.php';
3. use Dompdf\Dompdf;
4. $pag = $_SERVER['PHP_SELF'];  
5. $url = 'http://'.$_SERVER['HTTP_HOST'] . $pag;
6.
7. content = '
8. <!doctype html><html><head><meta http-equiv="Content-Type" content="text/html;"></head>
9. <body>
10. ¿Qué es DOMPDF?< b r >Ejemplo lista< b r >'.$url;
11.
12. if ( ! isset($_GET['pdf']) ) {
13.	$content .= "<br><a href=\"$pag?pdf=1\">Generar documento PDF</a></body></html>";  
14.	echo $content;
15.	exit;
16. }
17.
19. $dompdf = new Dompdf();
20. $content = file_get_contents("$url");
21. $dompdf->loadHtml($content);
22. $dompdf->setPaper('A4', 'portrait'); 
23. $dompdf->render();
24. $dompdf->stream("descargar_mi_pdf.pdf", array("Attachment" => false));

If we now change the code in lines 7 to 10, by this one, it no longer works (the pdf is not created well)

7, echo <<< HTML
8. <!doctype html><html><head><meta http-equiv="Content-Type" content="text/html;"></head>
9. <body>
10. ¿Qué es DOMPDF?< b r >Ejemplo lista< b r >$url
11. HTML;

Why??????? I do not get it.

**Comment by bsweeney** [comment]
You're `echo`ing out the content instead of capturing it in the variable you pass to Dompdf. The new lines 7-10 should read:

```
echo <<< HTML
<!doctype html>

¿Qué es DOMPDF?< b r >Ejemplo lista<br>$url
HTML;
```
