### ISSUE TITLE
Dompdf removing subset from URL string

### ISSUE THREAD

**Issue by andreiPetatec** [dompdf/dompdf#1436]
I'm trying to output an url string using DOMPDF but I see it removes a subset of characters and can't figure out why

This is what I'm trying to print:

>     http://XXXX.com/uploads/users/80D3A293-8A73-C5C1-10EC-99D26AD202E9/avatar/240_74AEQMHz.jpg

and this is what it outputs:

>     http://XXXX.com/uploads/users/8A73-C5C1-10EC-99D26AD202E9/avatar/240_74AEQMHz.jpg

.. it removes the 80D3A293-

I'm using Dompdf 0.8.0 with PHP 5.6 and encoding the HTML page with UTF8

Thanks

**Comment by bsweeney** [comment]
Do you have a working URL I can use for testing. Maybe also the HTML you're trying to render. I have not seen that before.

**Comment by bsweeney** [comment]
http://stackoverflow.com/q/43628314/264628

**Comment by andreiPetatec** [comment]
Hi!

I resolved it by adding:

`$dompdf->set_option('enable_remote', TRUE);`

Don't know exactly how, but this fixed the problem. It started to output the correct string

**Comment by bsweeney** [comment]
Well, that's an odd affect. Was the URL part of a resource reference or just text on the page?

**Comment by andreiPetatec** [comment]
First it was used as an image src, which lead to a message saying that the image was missing, or something like that, and than I just printed the entire link and saw that part missing. Setting the "enable remote" to true fixed both cases.

**Comment by bsweeney** [comment]
You would need to enable remote if you're using a URI that includes the protocol+domain. I'm not sure what about the code is mangling the URI but we'll take a look.

**Comment by bsweeney** [comment]
I suspect this may have been caused by some kind of decoding of the URL string? But I have been unable to reproduce the issue and URL parsing has changed significantly since 0.8.0.
