### ISSUE TITLE
CSS styles are always applied for invalid or unknown pseudo-classes or pseudo-elements

### ISSUE THREAD

**Issue by Mellthas** [dompdf/dompdf#1438]
See the attached HTML file, which causes the bug.

[test.zip](https://github.com/dompdf/dompdf/files/959143/test.zip)

dompdf produces a big red rectangle in the middle of the page, although the only CSS rule used is the following:

    ::selection {
    	background-color: red;
    }

Actually, the bug can also be reproduced with any invalid pseudo-class or pseudo-element (like e.g. `:asd` or `::asd`).

Bug appears with dompdf version 0.8, but not with version 0.7. Tested with PHP 7.0.16.

**Comment by bsweeney** [comment]
indeed 😞

**Comment by Mellthas** [comment]
I can confirm this bug is fixed for us with the current develop branch.
