### ISSUE TITLE
function build_url (with base_path to local filesystem) is incorrect for absolute path

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#144]
_Original author: Freigh (March 25, 2010 15:36:32)_

I am using cakephp and using dompdf to render my dymanic view to pdf.
In the output my Stylesheets (CSS) and Javascript is linked absolute
without host &quot;/css/style.css&quot;. The Browser does append the host correctly
(http://domain1/css/style.css).

Now I would like to let dompdf access these files not over http, but using
the local filesystem. So I set $dompdf-&gt;set_base_url(/www/domain1/htdocs/)

Unfortunately the function build_url in functions.inc.php from dompdf will
set host to &quot;&quot; (because protocol is not specified) and then build the url
without the base_url.

To fix this I added to functions.inc.php:
... `&& host !== ""`

Heres the snippet:

``` php
  if ( $url{0} === "/" && $host !== "")
    // Absolute path
    $ret .= $host . $url;
  else {
    // Relative path

    $base_path = $base_path !== "" ? rtrim($base_path, "/\\") . "/" : "";
    $ret .= $host . $base_path . $url;
  }
```

Perhaps this could be corrected in the next release?

<b>What version of the product are you using? On what operating system?</b>
dompdf 0.5.1

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=138_

**Comment by tybruffy** [comment]
This is a pretty old bug, but this is still an issue.  The above fix works for me, but the code it addresses has moved.  It's now line 77 in Helpers.php.

Without this fix, the following WILL work in DomPDF:

`<link rel="stylesheet" type="text/css" href="app/assets/build/build.css">`

While this will not work in DomPDF

`<link rel="stylesheet" type="text/css" href="/app/assets/build/build.css">`

Notice the leading slash in the second example.  DomPDF treats that as a fully qualified path, which it is not.  The fully qualifed path for that link shoudl be something like `/var/www/site.com/app/app/assets/build/build.css`

The example without the leading slash will work for DomPDF, but if your site uses URLS like the `example.com/page-1/` the styles will not be output on the other pages.

**Comment by bsweeney** [comment]
I'm not convinced the "/" path, when considered on its own, is a bug if: 1) a local file is loaded using loadHtmlFile; or 2) the HTML document is read from a variable using loadHtml. Dompdf can't know what the document root is and so "/" represents a path from the root of the current filesystem.

There does still appear to be an issue when a base href is present in the HTML or the base path is set via the setBasePath Dompdf method. It looks like the base href is ignored, but a bit more investigation is needed. I suspect there could also be some issues specific to what operating system is in use.

**Comment by bsweeney** [comment]
closing this issue in favor of #1370
