### ISSUE TITLE
at-font-face with space in source URL does not load

### ISSUE THREAD

**Issue by frostedcheerio** [dompdf/dompdf#1440]
Solution: Turns out the issue in my case was an extra space before the URL string. Once that was removed the fonts rendered correctly in the pdf.

I realize there is a whole host of somewhat related topics but I just can't seem to find one that's the same and / or includes a solution that solves my problem.

I'm sending an html document to dompdf which includes embeded css and includes font-face declarations and class definitions. The fonts are on the same server and I've tried with both relative and absolute paths and can't seem to get them to work.

I'm including the following in the head of the html document I then send to dompdf.

```
<style type="text/css">
    @font-face {
        font-family: "Roboto";
        font-weight: normal;
        font-style: normal;
         src: url( "http://localhost/resources/fonts/Roboto/Roboto-Regular.ttf") format('truetype');
     }
      .font_alpha { font-family: "Roboto";}`

    /* .... Other css rules here ... */

</style>
```

When I echo the html rather than send it on to dompdf I can see that the font for any element with the .font_alpha class applied is correct, in inspector it also shows that it's using the network resource yet when I call the following on the html, the font doesn't get applied.

```
//This is where I would display the html directly for testing
//echo $report_html; exit;

$dompdf = new DOMPDF();
$dompdf -> load_html( $report_html );
$dompdf -> set_paper( $this -> paper_size, $this -> paper_orientation );
$dompdf	-> render();
$dompdf	-> output();
```

The pdf(s) get generated correctly with all css formating from the rest of the rules being correctly applied except for the fonts. 

To be honest I'm not sure if I need to be installing these fonts in an additional way like using cmd line load_font.php thirdparty lib or not. Based on what I believe I can understand about version 0.8.0 I shouldn't need to correct??

Any advice or input would be extremely helpful.

Thanks in advance,
Cheerios

**Comment by Sadzeih** [comment]
I'm having the same problem. The font works in HTML but the rendered PDF does not show the right font.

**Comment by Lam784** [comment]
Same here!
And this is what I have in my css:
@font-face {
  font-family: 'Impact';
  font-style: normal;
  font-weight: 400;
  src: url('/fonts/impact.ttf') format('truetype');
}

**Comment by alapaco** [comment]
I have the same problem too!
The bold font works good in html but not at dompdf.

@font-face {
    font-family:'NeoSansBoldImport';
    font-style:normal;
    font-weight:bold; src:url('/fonts/neo_sans/NeoSanBold.ttf') format('truetype');
}

**Comment by frostedcheerio** [comment]
I updated my original comment to note that I've tried with both absolute and relative paths to the font files and still no success.

**Comment by alapaco** [comment]
In my case, if I use a normal font this font looks good, the problem occurs when I use a font in bold.
It's strange.

**Comment by alapaco** [comment]
In my case the mistake was mine, had the source of the body on write to the source of the divs with the "important!" label.
Sorry.
Thanks for such a useful tool!

body {font-family:NeoSansImport !important; text-align:left;}

**Comment by Lam784** [comment]
What version of php do you guys have?

**Comment by frostedcheerio** [comment]
Turns out the issue in my case was an extra space before the URL string.  Once that was removed the fonts rendered correctly in the pdf.

**Comment by Lam784** [comment]
Got mine to work, 
Turns out I was trying to display the custom font in bold,
So I need to include the bold version of the font-face as well;

@font-face {
font-family: 'Impact';
font-weight: bold;
src: url('/fonts/impact.ttf') format('truetype');
}

**Comment by ncolbertzi** [comment]
Same exact issue - nothing will get any custom font to load.  
Loading from Google fail -
Loading from Local File provided by dompdf fail
Loading loading from full path fail - 
Loading from relative path fail

Any help would be appreciated - I have to move back to another lib without being able to use a custom font.

@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: normal;
  src: url(http://themes.googleusercontent.com/static/fonts/opensans/v8/cJZKeOuBrn4kERxqtaUH3aCWcynf_cDxXwCLxiixG1c.ttf) format('truetype');
}

@font-face {
  font-family: 'Deja';
  font-style: normal;
  font-weight: normal;
  src: url('<?= $_SERVER['DOCUMENT_ROOT'] ?>/zpark/vendors/dompdf/dompdf/lib/fonts/DejaVuSans.ttf') format('truetype');
}

h1 {
    font-family: 'Open Sans' sans-serif;
}

p {
    font-family: 'Deja' sans-serif;
    font-size: 1em;
}

**Comment by aashishsoni** [comment]
is it possible to add this Brady Bunch  font in dompdf as mine is not working, please help.

**Comment by mt15199** [comment]
After couple of hours of searching, I found out the caused on the issue that I'm facing with using google font and hosted custom font.

It was cause by using **$dompdf->ouput** and **$dompdf->stream** function on the same script.

**Comment by bsweeney** [comment]
Lots of issues identified and some fixes as well. We're planning to add some documentation around some of the raised issues and some issues we plan to address in a future release.

Anyone in this thread still need any specific help?

**Comment by mt15199** [comment]
I thought my issue has been resolved but when I moved the library into online hosting (free). The font is not working anymore.

Here's the link - https://marlz151990.000webhostapp.com/dompdf/makePDF.php

Attached is the file generated via localhost which font is working. I couldn't see any error on the developer area

May I know what's the issue on that? 

[file.PDF](https://github.com/dompdf/dompdf/files/1529803/file.PDF)

**Comment by mt15199** [comment]
I found the answer on this report - https://github.com/dompdf/dompdf/issues/1210

I just changed the "\" to "/" in dompdf/lib/fonts/dompdf_font_family_cache.php

**Comment by bsweeney** [comment]
That is a common issue, especially when migrating code rather than installing a fresh copy.

**Comment by marieve** [comment]
I was trying to put the font Calibri, but when I looked at the page dompdf/lib/fonts/dompdf_font_family_cache.php, I've seen that the name for PDF is calibrii !! So, instead of "font-family: Calibri;", I've put "font-family: calibrii;" and it now works !

**Comment by clebersleite** [comment]
@Lam784 Nice obs man; in bold the personal font work fine '-'

**Comment by dragosstancu** [comment]
You need to convert your fonts to base64 encoding:

@font-face {
    font-family: "San Francisco";
    font-weight: 500;
    src: url(data:application/x-font-woff;charset=utf-8;base64,d09GRgABAAAAAIDQABQAAAABXwwAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABC...) format('woff');
}

then : 

body{
    font-family: "San Francisco";
    font-weight: 500;
}

You need to do the same conversion for each font-weight value you want to use.

**Comment by edum18** [comment]
I have the same problem, works well on HTML output but not on the generated PDF...

        @font-face {
            font-family: 'RobotoThin';
            font-weight: 100;
            src: url('/assets/fonts/roboto/fonts/Thin/Roboto-Thin.woff') format('woff');
        }

        span.cls_003{font-family: 'RobotoThin', "Times New Roman", sans-serif; font-weight: 100; font-size: 30px;}
        div.cls_003{font-family: 'RobotoThin', "Times New Roman", sans-serif; font-weight: 100; font-size: 30px;}

I tried using the hosted method too:

        @font-face {
            font-family: 'RobotoThinn';
            font-style: normal;
            font-weight: 100;
            src: local('Roboto Thin'), local('Roboto-Thin'), url(https://fonts.gstatic.com/s/roboto/v18/KFOkCnqEu92Fr1MmgVxIIzI.woff2) format('woff2');
            unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
        }

        span.cls_003{font-family: 'RobotoThinn', "Times New Roman", sans-serif; font-weight: 100; font-size: 30px;}
        div.cls_003{font-family: 'RobotoThinn', "Times New Roman", sans-serif; font-weight: 100; font-size: 30px;}

The problem remains...

**Comment by wezwest** [comment]
edum18 - Try changing the font weight to normal rather than 100

`font-weight: normal;`

**Comment by edum18** [comment]
> @edum18 - Try changing the font weight to normal rather than 100
> 
> `font-weight: normal;`

@wezwest nop, still the same 🤔

**Comment by bsweeney** [comment]
Dompdf does not currently support WOFF fonts. Make sure you're using TTF.

**Comment by guifabrin** [comment]
> @edum18 - Try changing the font weight to normal rather than 100
> 
> `font-weight: normal;`

Solve for me, thanks!

**Comment by guifabrin** [comment]
My problem was basicly the font ttf there is not an bolder part.

In dompdf/lib/fonts/dompdf_font_family_cache.php I found just normal part and my element was in strong tag, so the font-weight was bold and not get the font-weight normal.

I hope this help you guys.

**Comment by sajsemegaloma** [comment]
I cannot get bold and italic to work no matter what I try. If I understand correctly, this should be enough:
PHP:
`    ini_set('display_errors', 1);
    ini_set('display_startup_errors', 1);
    error_reporting(E_ALL);

    $htmlsource = 'source.html';

    require_once('autoload.inc.php');

    use Dompdf\Dompdf;

	$dompdf = new Dompdf();
	$dompdf->load_html_file($htmlsource);
	$dompdf->setPaper('Letter', 'portrait');
	$dompdf->render();

	$dompdf->stream("test.pdf", array("Attachment" => false));`

HTML:
`<html>
<head>
	<style type="text/css">

		@font-face {
                font-family: 'Nunito';           
                font-weight: normal;
                font-style: normal;
                src: url('Nunito-Regular.ttf') format('truetype');
        } 

        @font-face {
                font-family: 'Nunito';           
                font-weight: bold;
                font-style: normal;
                src: url('Nunito-Bold.ttf') format('truetype');
        } 

		h1 {
			font-family: 'Nunito';
		}

		p {
			font-family: 'Nunito';
		}
	</style>
</head>
	<body>
		<h1>This is a test</h1>
	<p>Lorem ipsum dolor sit amet, <strong>consectetur adipisicing elit</strong>. Laudantium consequatur voluptatem, quo, distinctio neque, non repudiandae inventore hic alias unde doloremque harum illum iure adipisci, voluptatum nam molestiae. Excepturi, ipsam!</p>
	</body>
</html>`

If I open the html file in the browser the fonts are there, looks good. But as a PDF, the regular weight is there and bold is not, it defaults to Times New Roman.

![Capture](https://user-images.githubusercontent.com/1516179/56456069-fddbcb00-6334-11e9-8a24-92b06e73ed39.PNG)

I've tried everything, using the load_font.php method which creates the .uft files and adds them to the font cache file, but nothing beyond that.

I've tried a different set of font files (Roboto) just to make sure it's not somthing with the font I'm trying to use.

I've tried this:
`        @font-face {
                font-family: 'Nunito-Bold';           
                font-weight: normal;
                font-style: normal;
                src: url('Nunito-Bold.ttf') format('truetype');
        } `

And then using it as if it was a different family. Nothing.

Can someone help?

**Comment by dragosstancu** [comment]
I just did:

$html = '<!doctype html><html>
    <head>    
<style>
    @font-face {
        font-family: "Roboto Regular";           
        font-weight: normal;
        src: url(\'fonts/Roboto-Regular.ttf\') format(\'truetype\');
    } 

    @font-face {
        font-family: "Roboto Bold";           
        font-weight: bold;
        src: url(\'fonts/Roboto-Bold.ttf\') format(\'truetype\');
    } 

body{
        font-family: "Roboto Regular", sans-serif;
        font-weight: normal;
        line-height:1.6em;
        font-size:17pt;
	}
	
	h1,h2{
        font-family: "Roboto Bold", sans-serif;
        font-weight: bold;
        line-height:1.2em;
	} 

</style></head> ...';

![Screen Shot 2019-04-20 at 6 58 50 PM](https://user-images.githubusercontent.com/2857232/56463245-657a3080-639e-11e9-9383-c1661ed611e0.jpg)

**Comment by dragosstancu** [comment]
fonts URLs are relative to the PHP page rendering the PDF

**Comment by sajsemegaloma** [comment]
It seems my problem was somehow environment-related. When I move the code to an actual server it all works fine, but on my local machine with MAMP it was ignoring bolds and italics completely for some reason.

**Comment by Tomassito** [comment]
Any indication of progress on this issue? I'm having really hard time with trying to use a custom font in v0.83 :(

**Comment by coder-rukon** [comment]
Use css and it worked. 
@font-face {
  font-family: myFontName;
  src:url('http:://yourwebsite.com/myFontName.ttf');
}
p {
	font: myFontName;
}

**Comment by Developers-account** [comment]
Are you sure it works? If you have no problem can you share the complete HTML?

**Comment by coder-rukon** [comment]
> 
> 
> @coder-rukon Are you sure it works? If you have no problem can you share the complete HTML?

Yes. It is working good to me
http://prntscr.com/r5l0p6

**Comment by bl8m** [comment]
Check for the permission of the folder **/vendor/dompdf/dompdf/lib/fonts** , it must be writable, as described in the source code:

`    /**
     * The location of the DOMPDF font cache directory
     *
     * This directory contains the cached font metrics for the fonts used by DOMPDF.
     * This directory can be the same as $fontDir
     *
     * Note: This directory must exist and be writable by the webserver process.
     *
     * @var string
     */
    private $fontCache;`
