### ISSUE TITLE
"nth-child" CSS selector broken on CentOS

### ISSUE THREAD

**Issue by hakimio** [dompdf/dompdf#1441]
Following two CSS rules produce different results on CentOS even they work exactly the same on Windows. "nth-child" applies the specified background to the whole table while "nth-of-type" correctly applies the background to "even" rows.
```
<style>
.dataTable tr:nth-child(even) {
        background-color: #F9F9F9;
    }
</style>
```

```
<style>
.dataTable tr:nth-of-type(even) {
        background-color: #F9F9F9;
    }
</style>
```
```
<table class="dataTable">
<tr><td>a</td></tr>
<tr><td>b</td></tr>
<tr><td>c</td></tr>
<tr><td>d</td></tr>
</table>
```

Could it be because CentOS uses old version of libxml?

EDIT: Extra info:
PHP: 7.1.4 (from Remi RPM repository)
CentOS: centos-release-7-3.1611.el7.centos.x86_64 (CentOS 7 on MS Azure)

**Comment by hakimio** [comment]
Must be a CentOS 7 issue. The sh#tty distro still uses libxml 2.9.1 which has a major bug. More info:
http://stackoverflow.com/questions/39899632/same-xpath-returns-different-values-on-centos-ubuntu/39956501#39956501

**Comment by hakimio** [comment]
We'll just say it's CentOS bug.

**Comment by bsweeney** [comment]
Thank ... goodness (?). But that's a bummer.

**Comment by bsweeney** [comment]
This would be good for a "known issues" document. Re-opening until I have a chance to work through documentation updates related to the 0.8.0 release.

**Comment by hakimio** [comment]
@T0miii Either use "nth-of-type" instead of "nth-child" or switch to another linux distro. CentOS 7.5 still uses buggy version of libxml2.

**Comment by T0miii** [comment]
@hakimio nth-of-type helped, thx a lot. We are planing to switch to ubuntu early next year.

**Comment by bsweeney** [comment]
Started a wiki page for [known compatibility issues](https://github.com/dompdf/dompdf/wiki/Known-compatibility-issues).
