### ISSUE TITLE
PDF not render with PHP 5.6

### ISSUE THREAD

**Issue by rodrigoalvesnet** [dompdf/dompdf#1444]
Hi, i'm using Dompdf 0.8.0 and it's works fine, but when I set "Attachment" to "0" the PDF not render, It just show various characters in the screen, anyone knows whats happening and how fix this?
`$dompdf->stream('document',array('Attachment'=>0));`

**Comment by hakimio** [comment]
You need to set appropriate headers yourself before streaming. "Content-type", "Content-length", etc.

**Comment by rodrigoalvesnet** [comment]
I set this way and works:
`$this->response->type('application/pdf');`
Thank!
