### ISSUE TITLE
Setting line-height breaks layout, even across different pdfs

### ISSUE THREAD

**Issue by thewunder** [dompdf/dompdf#1445]
After a couple days I finally isolated the problem to a single css property.  In logo.html there is a line-height set in an id selector.  Setting that property breaks the layout in the second pdf render.

This issue occurs in both dompdf 0.7 and 0.8, using php 7.0.18

[dompdf_line_height.zip](https://github.com/dompdf/dompdf/files/971978/dompdf_line_height.zip)

```php
<?php
$options = new Options();

$options->setDpi(300)
    ->setIsPhpEnabled(true)
    ->setFontDir('/tmp/dompdf_fonts')
    ->setIsRemoteEnabled(true)
    ->setDefaultPaperSize([0, 0, 604.8, 216]);

$html = file_get_contents('/tmp/logo.html');
$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->render();
file_put_contents("/tmp/logo.pdf", $dompdf->output());


$options = new Options();

$options->setDpi(300)
    ->setIsPhpEnabled(true)
    ->setFontDir('/tmp/dompdf_fonts')
    ->setIsRemoteEnabled(true)
    ->setDefaultPaperSize([0, 0, 621, 810]);
$html = file_get_contents('/tmp/mediaKitPage2.html');
$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->render();
file_put_contents("/tmp/broken.pdf", $dompdf->output());

**Comment by bsweeney** [comment]
Confirmed. I've run into the issue myself (though, obviously, hadn't yet posted an issue) and am pretty sure it is a problem with static variable use. I'll need to review my earlier research to provide a temporary work-around.

**Comment by thewunder** [comment]
Any chance we could get this in the next release?  I may be able to help if you point me in the right direction here.

**Comment by bsweeney** [comment]
I think this is no longer an issue? At least I don't seem to be able to reproduce the issue. If that's not the case let us know and we'll take another look.

FYI the issue was due to the use of a static local variable. There are still some static locals in use and at some point we need to analyze the impact of these on rendering multiple documents within the same execution context.
