### ISSUE TITLE
Version file in composer download

### ISSUE THREAD

**Issue by jorrit** [dompdf/dompdf#1447]
When I download dompdf using composer the VERSION file contains `<0f418c6>`. It would be nice to have the human-readable version in this file.

**Comment by bsweeney** [comment]
Agreed. That's the commit reference. I'll need to look to see if this can be generated as part of the composer install or if we need to fix it in the file before tagging.

**Comment by PHLAK** [comment]
I'm building a package that might help with this, check it out: https://github.com/PHLAK/SemVer-CLI
