### ISSUE TITLE
Cant we directly give the HTML Url instead of typing whole code

### ISSUE THREAD

**Issue by vashisth1998** [dompdf/dompdf#1451]
Hi Developers!
Recently i have checked your dompdf project and its really good and i test it on different background images and simple css animation.It works  perfectly but i want to know is there any method so that we  can directly give the url of that html page/Directory  in sense like
> **src="dummy.html"** 

Anyway Good Project Indeed
Cheers!!

**Comment by hakimio** [comment]
You can use $dompdf->loadHtmlFile() to load html files and urls.
