### ISSUE TITLE
domPDF issue when the content has to go on the next page

### ISSUE THREAD

**Issue by terror2012** [dompdf/dompdf#1455]
![issue](https://cloud.githubusercontent.com/assets/9155285/25906733/1f7e976c-35ae-11e7-90f0-8eaa128ea893.png)

As you can see in the above picture, I have a file that generates a table row for each entry in a database. The problem is that when the content gets too big for 1 page, it happens as you can see in the picture, can I somehow make my body break to another page as soon as I get to end of the page?
Like the next line/row should be on the next page.
Thanks.

**Comment by bsweeney** [comment]
Breaking the page is the default behavior. It's likely something in your HTML that's throwing off the rendering. Can you post a sample of the HTML?
