### ISSUE TITLE
background images for all pages. 

### ISSUE THREAD

**Issue by krish-0404** [dompdf/dompdf#1457]
How to apply background image for all pages for cakePHP3 Dompdf. we can't find any solution please help as.

**Comment by bsweeney** [comment]
Just apply background image styling to the body. Something like the following:

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body style="background-image: url(http://eclecticgeek.com/images/macro/ants.jpg);background-repeat: no-repeat; background-position: center;">
  <p>p1</p>
  <p style="page-break-before: always;">p2</p>
</body>
</html>
```

If that's not sufficient you'll have to be more specific in your question.

**Comment by jonathanpmartins** [comment]
does not work here too

**Comment by bsweeney** [comment]
What release of Dompdf is everybody using? So far I've been unable to reproduce this issue.
