### ISSUE TITLE
Can I "construct" the PDF file on the fly, with what I have rendered on the screen at any given moment?

### ISSUE THREAD

**Issue by gadget00** [dompdf/dompdf#1462]
Let me give an example:
I have a screen in my project that has a table and some data on it.  I'm using dompdf to generate a pdf doc from that screen, but I want to know if it is possible to just take the div's that are in the screen, and append them to the $dompdf->HtmlFile() and then do the render() and stream()?

Something like this:

```
<div id='title'>
<h1>hello world</h1>
</div>
<div id="table"> 
<table>
<tr><td>hey</td><td>hey</td></tr>
<tr><td>man</td><td>man</td></tr>
</table>
```

then, on the PHP something like:

```
$dompdf->appendToHtmlFile("#title") ;
$dompdf->appendToHtmlFile("#table");
$dompdf->render();
$dompdf->stream('pdf-file');
```

Thanks for your comments

**Comment by bsweeney** [comment]
Are you saying you want to be able to take an existing HTML document and append content before rendering? Let us know if that's the case, or clarify what you want to do otherwise, so we can respond appropriately.

**Comment by gadget00** [comment]
Yes, that's exactly what I want to do

**Comment by simonberger** [comment]
You think a bit complicated. What you want to do is not a big deal but it is not a job of dompdf.

1. Create a dom object on server-side (for example with DOMDocument)
2. Add your stuff to some nodes through ajax call
3. Add more stuff to the same or other nodes
4. Pass the dom to dompdf and render it at the point you want
5. If you want add even more stuff to your dom
6. Maybe render again
...

**Comment by bsweeney** [comment]
I'm even more confused now. Are you saying you want to construct the PDF in parts and then merge them together? Or do you want to take various HTML snippets and combine then and then create the PDF?

If the latter Simon's provided you the technique. But either way he is also correct in that this is something outside the bounds of what Dompdf is designed to do.
