### ISSUE TITLE
Open source the examples from https://dompdf.net/examples.php

### ISSUE THREAD

**Issue by Singwai** [dompdf/dompdf#1463]
Hello,

Can you also open source these examples.

Best,

**Comment by EVDW** [comment]
@Singwai I think I found the sources, if it's what you looking for: [https://github.com/dompdf/dompdf/tree/tagged-pdf/www/test](https://github.com/dompdf/dompdf/tree/tagged-pdf/www/test)

**Comment by Singwai** [comment]
Thank!!!

**Comment by bsweeney** [comment]
The last release of that content would be included with dompdf 0.6.2 here: https://github.com/dompdf/dompdf/tree/v0.6.2/www/test

There are plans to re-create the content in the [dompdf/utils](/dompdf/utils) project ... but no timeline for doing that.
