### ISSUE TITLE
Error on require_once in autoload.inc.php

### ISSUE THREAD

**Issue by dlanz** [dompdf/dompdf#1467]
So I'm trying use dompdf in my project and I have included the [autoload.inc.php](https://github.com/dompdf/dompdf/blob/master/autoload.inc.php) file in my script along with the composer autoloader, but that file is generating an error on lines 20 and 21.  I checked to see if those files exist and it seems they do not ([https://github.com/dompdf/dompdf/tree/master/lib](https://github.com/dompdf/dompdf/tree/master/lib)).   

I understand dompdf has dependencies on "phenx/php-font-lib": "0.5.*" and "phenx/php-svg-lib": "0.2.*", which were resolved by composer, but they are not in those locations.  I'm sure I'm missing something, but not sure what or how.

My composer.json for dompdf includes:
`"dompdf/dompdf": "~0.8"`

Much appreciation for such a great package!

**Comment by MatthiasKuehneEllerhold** [comment]
AFAIK you dont need the autoload.inc.php if you're using the composer autoloader.

**Comment by dlanz** [comment]
Ah okay.  Yep, I don't know why but I was looking at the "install via Git" instructions.  Sure enough when I scroll up to the "Composer" instructions it explains that.  Knew I was missing something :).
