### ISSUE TITLE
float not working

### ISSUE THREAD

**Issue by gagan-coditas** [dompdf/dompdf#1468]
I am using dompdf 0.8.0. I tried a lot of solutions from internet but cannot reach my goal. I have to use float for this but it's not working. The HTML template looks pretty well but it breaks in the pdf file

**Comment by kaytotes** [comment]
I have this same issue. Prior to 0.8.0 I was using DomPDF to generate labels. 2 to a page using float:right; 

This no longer works so the labels are splitting up 1 to a page.

**Comment by OnkelTem** [comment]
Confirm this.

**Comment by gagan-coditas** [comment]
Thanks for your replies. Have used a different approach to get what I needed.

**Comment by simonberger** [comment]
Floats are supported but just at a very basic level.
Without an demo code of what you try no one will be able to help you.
Sometimes you can easier get your result with inline blocks or with help of tables.
