### ISSUE TITLE
v0.8.0: Fatal error: Class '\Dompdf\Positioner\Block' not found in ****\src\Frame\Factory.php on line 283

### ISSUE THREAD

**Issue by jutho-agentur** [dompdf/dompdf#1470]
Hi,

I get this error when trying ro generate a PDF.
In v0.7.0 everything worked fine. But in new version i have no chance.
What can I do?

Thanks for ur help!

**Comment by sasosmolej** [comment]
I can reproduce the error on PHP 5.3.1 on Windows.

Workaround:
On line 282 in \src\Frame\Factory.php
`            $class = '\\Dompdf\\Positioner\\'.$type;`
Replace with:
`            $class = 'Dompdf\\Positioner\\'.$type;`

Though I can't really find the exact entry in the changelog, \ is a namespace separator in 5.3 (but apparently not in 5.3.1).

**Comment by bsweeney** [comment]
That's ... interesting. The PHP version specific bugs are the worst. 5.3.1 is old enough that we'll probably not fix this. But I will do a bit more investigation just to be sure.

@jutho-agentur which version of PHP are you using?

**Comment by jutho-agentur** [comment]
@bsweeney Sorry for late answer. I'm using PHP 5.3.1 - so yes... it's really old ;)

**Comment by Kirancloudnix** [comment]
Any update on this issue?

**Comment by PerduGames** [comment]
I get the same error using php 5.6.33.
