### ISSUE TITLE
Getting a error with mb_internal_encoding()

### ISSUE THREAD

**Issue by wolfganggermain** [dompdf/dompdf#1474]
Hi,

First of all I would like to say beautiful job on creating Dompdf. Truly it is an amazing piece of code.

I've built myself a custom invoicing system that work on my server with is a reseller account.

But when I try to install it on VPS of one of my client it give me the following error
**Fatal error: Call to undefined function Dompdf\mb_internal_encoding() . . . /dompdf/src/Dompdf.php on line 274**

I know a similar issue was detected in earlier issue and the proposed solution was to add
**mb_internal_encoding('UTF-8')**
Before initialising the object and all part of the solutions **I've tried, was unsuccessful.**

I've also tried to update my php mb_string but without success.

I've spent a whole day researching the web for a solution still unsuccessful.

Would truly appreciate any help or suggestion one can provide.

Thank you in advance

**Comment by bsweeney** [comment]
The specific error indicates that PHP is looking for the `mb_internal_encoding()` method in the Dompdf namespace. I haven't run into this before so I'd need to take a closer look. I believe you should be able to temporarily avoid the issue by prepending that method call with a backslash (\), e.g. `\mb_internal_encoding(...);`

**Comment by bsweeney** [comment]
Just to confirm, MBString is enabled in your installation?

**Comment by sgehrman** [comment]
I had to add mb_internal_encoding('UTF-8');
To get it to  stop crashing.  Is this still the recommendation?

**Comment by bsweeney** [comment]
Yes, or the internal representation of the characters could be problematic during parsing. This mainly applies if you're rendering any non-Windows ANSI characters.

Still, it's not something you should have to do unless you're using an older version of Dompdf. It's the [the very first thing](https://github.com/dompdf/dompdf/blob/v0.8.2/src/Dompdf.php#L274) Dompdf does.

**Comment by justryingtocode** [comment]
I am using dompdf version  0.8.2 and i am getting the same error. Do I need to upgrade the version? Thankyou.

**Comment by simonberger** [comment]
Before I have a look at the code or a history of what had been done in the last versions. This is what I would need to do. What is stopping you from testing on the newest version? Please, bug reports always running on the newest release. In every project.

**Comment by justryingtocode** [comment]
> Before I have a look at the code or a history of what had been done in the last versions. This is what I would need to do. What is stopping you from testing on the newest version? Please, bug reports always running on the newest release. In every project.

hello simonberger,
I have upgraded the version to 0.8.5 but now i am getting these new errors when deploying on the server.
Mon Mar 16 15:16:22.710929 2020] [:error] [pid 1314] [client 127.0.0.1:47838] PHP Parse error:  syntax error, unexpected '=' in /var/www/html/pos/application/libraries/dompdf/src/Dompdf.php on line 356
[Mon Mar 16 15:21:43.291178 2020] [:error] [pid 5758] [client 127.0.0.1:47922] PHP Parse error:  syntax error, unexpected '=' in /var/www/html/pos/application/libraries/dompdf/src/Dompdf.php on line 388
[Mon Mar 16 15:22:27.060515 2020] [:error] [pid 5764] [client 127.0.0.1:47928] PHP Parse error:  syntax error, unexpected '=' in /var/www/html/pos/application/libraries/dompdf/src/Dompdf.php on line 589
[Mon Mar 16 15:23:14.834618 2020] [:error] [pid 5765] [client 127.0.0.1:47932] PHP Parse error:  syntax error, unexpected '=' in /var/www/html/pos/application/libraries/dompdf/src/Adapter/CPDF.php on line 193

I get these errors one by one, once I somehow resolve the previous line error the error gets changed to the next line and so on. 
Is this some bug in the newer version? 
Thankyou.

**Comment by simonberger** [comment]
Since version 0.8.4 Dompdf needs PHP 7.1.

**Comment by techtrail-git** [comment]
> I had to add mb_internal_encoding('UTF-8');
> To get it to stop crashing. Is this still the recommendation?

Enable MBString module in PHP Extensions in the cpanel

**Comment by tamcb2708** [comment]
I had use to it and it was very well
https://github.com/dompdf/dompdf

**Comment by gaining** [comment]
I had the same issue, fixed it with:  sudo apt install php8.2-mysql php8.2-mbstring php8.2-xml php8.2-curl
