### ISSUE TITLE
PHP 7.1

### ISSUE THREAD

**Issue by kreamweb** [dompdf/dompdf#1479]
Hello,
we have these two issue with PHP 7.1

/lib/dompdf/src/FrameDecorator/Table.php 
----------------------------------------------------------------------------------------------------------------------------------------------------- 
FOUND 1 ERROR AFFECTING 1 LINE 
----------------------------------------------------------------------------------------------------------------------------------------------------- 
200 | ERROR | Using 'break' outside of a loop or switch structure is invalid and will throw a fatal error since PHP 7.0 
-----------------------------------------------------------------------------------------------------------------------------------------------------

/lib/dompdf/src/Adapter/CPDF.php 
--------------------------------------------------------------------------------------------------------------------------------------------- 
FOUND 1 ERROR AFFECTING 1 LINE 
--------------------------------------------------------------------------------------------------------------------------------------------- 
197 | ERROR | Extension 'cpdf' is removed since PHP 5.1 - use pecl/pdflib instead. 
---------------------------------------------------------------------------------------------------------------------------------------------

Regards

**Comment by simonberger** [comment]
Those reports made my day. ;)
Did you use a static analyzer to get those?

1. That's not correct. Indeed the code is really bad there and I wonder why it is still there, but the if starts a new block and so the "second-line" without a surrounding block {} is in the loop too.
2. There is no pecl/php cpdf package in use. In fact it uses the dompdf/lib/Cpdf class that is out of a namespace as well.

**Comment by simonberger** [comment]
Fixed the syntax of your first report
