### ISSUE TITLE
Options not found

### ISSUE THREAD

**Issue by jbnv** [dompdf/dompdf#1481]
Error: Class 'Dompdf\Options' not found.

My code looks like this:
```
    public function pdf()
    {
        $options = new \Dompdf\Options();
        $options->set('dpi', 128);
        $dompdf = new \Dompdf\Dompdf($options);
        $dompdf->loadHtml($this->html()); // html() renders the object to HTML
        $dompdf->render();
        return $dompdf->output();
    }
```

I confirmed that the Composer autoloader is ahead of my project's autoloader in the queue. 

I'm looking in `vendor/dompdf/dompdf` and I'm really confused by what I see. The `src` folder from the repository isn't there. There's no Options.php file as I would expect. I ran `composer update` again to make sure that installed everything, and it says there's nothing to install.

What is the problem and how can I resolve it? I'm trying to debug another problem with DomPDF and this step in the process is getting a more recent version (I'm getting 0.6.2).

**Comment by jbnv** [comment]
Going to v.0.8 resolved the issue.

**Comment by ravisoni6262** [comment]
I'm using it within the WordPress plugin and was getting the same error. 

Calling the class via `$options = new Dompdf\Options();`
