### ISSUE TITLE
Some elements with auto margins receive no height

### ISSUE THREAD

**Issue by jbnv** [dompdf/dompdf#1482]
I have a document that, "out of nowhere," started formatting improperly. In debugging the issue, I found that the noticeable change was upgrading DomPDF to v0.8. I rolled back DomPDF to earlier versions, and identified that the PDF produced was correct under v0.7 but wrong under v0.8.

The issue: The document has a two-part page header. In [v0.7](https://github.com/dompdf/dompdf/files/1116367/report-v0.7.pdf) it renders correctly. In [v0.8](https://github.com/dompdf/dompdf/files/1116368/report-v0.8.pdf), the second part of the header is rendered on top of the first part. I have attached the source code for the page as well as the PDFs rendered by [v0.7](https://github.com/dompdf/dompdf/files/1116367/report-v0.7.pdf) and [v0.8](https://github.com/dompdf/dompdf/files/1116368/report-v0.8.pdf).

This was observed in PHP 5.6.22. I loaded and configured DomPDF through Composer.

```
<html>

<head>
  <title>JQWJQW Inspection - License / Application #8076 - Development</title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  <style>
    .toptable {
      width: 95%;
      margin-left: auto;
      margin-right: auto;
      margin-bottom: 15px;
      border: none;
      font-size: 15px;
    }

    .topcheckboxes {
      border-top: 1px solid;
      text-align: center;
      width: 100%;
    }

    body {
      width: 968px;
      font-family: 'Open Sans', sans-serif;
    }

    .header>table {
      width: 100%;
    }

    .toptable td {
      width: 50%;
      padding: 3px;
    }

    .answer-box {
      background-color: #999;
      padding: 5px;
      color: #000000;
      width: 13px;
      height: 13px;
      display: block;
    }

    .detail_table .answer-box {
      margin: 5px 0 5px 0;
    }

    .gray-back {
      background-color: #999;
      color: #000000;
      padding: 5px;
    }

    .detail_table tr td:nth-child(1),
    #second_page tr td:nth-child(1) {
      vertical-align: top;
      width: 49px;
    }

    .detail_table tr td:nth-child(2),
    #second_page tr td:nth-child(2) {
      width: 388px;
      font-size: 15px;
    }

    .detail_table tr td:nth-child(3),
    #second_page tr td:nth-child(3) {
      width: 48px;
    }

    .detail_table tr td:nth-child(4),
    #second_page tr td:nth-child(4) {
      width: 48px;
    }

    .detail_table tr td:nth-child(5),
    #second_page tr td:nth-child(5) {
      width: 48px;
    }

    .detail_table tr td:nth-child(6),
    #second_page tr td:nth-child(6) {
      width: 389px;
      font-size: 15px;
    }

    .detail_table tr td,
    .detail_table,
    #second_page,
    #second_page tr td {
      border-collapse: collapse;
      border-bottom: 1px black solid;
    }

    .detail_table tr td .checkbox,
    #second_page tr td .checkbox {
      padding-top: 2px;
      padding-bottom: 2px;
    }

    .title {
      font-weight: bold;
      font-size: 24px;
    }

    .text-middle {
      text-align: center;
    }

    .inner-answer {
      display: block;
      margin-top: -5px;
    }

    .default-top-margin {
      margin-top: 0px;
    }

    .block-div {
      display: inline-block;
    }

    .header {
      margin-left: auto;
      margin-right: auto;
      border-bottom: 1px solid;
    }

    .seal-img {
      height: 64px;
      width: 64px;
    }

    .force-inline-block {
      display: inline-block !important;
    }

    .subpage-header {
      page-break-before: always;
    }

    .cover-page-title {
      margin-top: 12pt;
      margin-bottom: 12pt;
      text-align: center;
      vertical-align: bottom;
      border-top: 1px solid;
      font-weight: bold;
      text-decoration: underline
    }

    .cover-page-subtitle {
      font-weight: bold;
      text-decoration: underline
    }

    .note {
      margin-bottom: 12pt;
    }
  </style>
</head>

<body>
  <div class="report-header">
    <div class="header">
      <table>
        <tr>
          <td><img src="LouisianaSeal.png" class="seal-img"></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td>
            <div class="text-middle">
              <span class="title">JQWJQWJQW JQWJQW JQW JQW JQW JQW JQWJQWJQWJQW</span><br> 28485 Ejqwjqwjqw Avenue, Jqwjqw Jqwjqw, LA 70201<br> (225)555-0000 &nbsp; &nbsp; &nbsp; (225)555-0000 &nbsp; &nbsp; &nbsp; jqwjqw@jqwjqw.jqwjqw &nbsp; &nbsp; &nbsp;
              jqw.jqwjqw.jqw
            </div>
          </td>
        </tr>
      </table>
      <table>
        <tr>
          <td><strong>JQWJQWJQW JQW JQWJQWJQWJQW JQWJQWJQWJQW JQWJQW JQWJQW</strong></td>
          <td style="text-align:right"><strong>Page 1 of 4</strong></td>
        </tr>
      </table>
    </div>
    <div>
      <table class="toptable" align="center">
        <tr>
          <td><strong>License / Application #:</strong></td>
          <td>8076</td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><strong>Inspection Date:</strong></td>
          <td>06/30/2017</td>
        </tr>
        <tr>
          <td><strong>Licensed Facility Name:</strong></td>
          <td>TEST WHOLESALE DISTRIBUTORS, INC.</td>
        </tr>
        <tr>
          <td><strong>Facility Address: &nbsp; </strong></td>
          <td>1234 Some Street</td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><strong>Product: &nbsp; </strong></td>
          <td>LD </td>
        </tr>
        <tr>
          <td></td>
          <td>Somecity, TN 70816 </span>
          </td>
        </tr>
        <tr>
          <td><strong>Facility Contact:</strong></td>
          <td></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><strong>Telephone:</strong></td>
          <td></td>
        </tr>
        <tr>
          <td><strong>Date of Last Inspection:</strong></td>
          <td>05/17/2017 (#59)</span>
          </td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><strong>Designated Responsible Party:</strong></td>
          <td>Fjqwjqwjqw Gjqwjqwjqw</td>
        </tr>
        <tr>
          <td><strong>Inspection Type:</strong></td>
          <td>Initial</td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><strong>Inspector Assignee:</strong></td>
          <td>Ejqwjqwjqw Tjqwjqwjqw</td>
        </tr>
        <tr>
          <td><strong>Inspection Complexity:</strong></td>
          <td></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><strong>Expiration Date:</strong></td>
          <td>12/31/2017</td>
        </tr>

      </table>
    </div>
  </div>
  <div class="cover-page-title" style="text-align:center"></div>

  <p>&nbsp;</p>

  <p>
    <strong>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce commodo venenatis sapien, at rutrum elit euismod eu. Nullam aliquet ipsum at justo molestie aliquam. </strong>
  </p>

</body>

</html>
```

**Comment by simonberger** [comment]
v0.8.0 brought some big changes and unfortunately in such a complex project it's unavoidable to have some drawbacks beside improvements.
I don't have an answer why exactly your PDF rendered bad now. But your html/css isn't really clean and unnecessary complicated which supports those rendering problems.

If you remove the margin left/right auto setting on the header class you recover the result of v0.7.0 as far as I noted.

**Comment by bsweeney** [comment]
Or if you specify a width. It looks like something about the auto-width calculation plus auto-margin calculation is causing problems.

**Comment by bsweeney** [comment]
Simplified example:

<div style="float: left; width: 30%; border: 1px solid red;">
  <h1>LOREM</h1>
  <div style="margin: auto;">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
  </div>
</div>

<div style="float: right; width: 30%; border: 1px solid red;">
  <h1>LOREM</h1>
  <div>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
  </div>
</div>

**Comment by bsweeney** [comment]
Another sample:

```
<div style="page-break-before: always; border: 1px solid black;"><img src="https://placekitten.com/200/200" style="display: block; width: 200px; height: 200px; margin: auto;"></div>
```

**Comment by Mellthas** [comment]
I have tracked this down: The issue is that the auto margins are not always resolved. This will result in `get_margin_width` reporting `auto` in
https://github.com/dompdf/dompdf/blob/4c65810c797674d0ceb8918859c645f298b5e358/src/FrameDecorator/Block.php#L155-L161
and thus the frame will not get added to the parent's line boxes below. This results in an erroneous content height for the parent (see `FrameReflower\Block::_calculate_content_height()`).

**Comment by Mellthas** [comment]
One more sample, using an inline element:
```html
<p style="border: 1px solid red;"><span style="margin: auto;">Test</span></p>
```

**Comment by Mellthas** [comment]
`display: block` on an image does not work, because the default stylesheet has and `!important` declaration for `-dompdf-image`. Specifying `display: block !important` results in the image not being rendered.

**Comment by bsweeney** [comment]
Regarding image display styling, that's correct. I believe it's partially the result of a change in how images were rendered. Originally, images were rendered as a containing element for general styling and an inner, generated element for the actual image. The container element was removed in an attempt to address some issues applying styles to the element. But that change caused the display styling issue because the rendering process only calls the image renderer if the display type of an element is -dompdf-image ([ref](https://github.com/dompdf/dompdf/blob/0ccafeb142dd04f556b43f1e8b5541aa06de1c26/src/Renderer.php#L126)).
