### ISSUE TITLE
Background size incorrect

### ISSUE THREAD

**Issue by creativefull** [dompdf/dompdf#1483]
i try to add background in body tag like this
```
body {
                        margin: 0px;
                        padding: 20px 100px;
                        background-image: url(img/Certificate.jpg);
                        background-position: center;
                        background-repeat: no-repeat;
                        width:100%;
                        height:100%;
}
```
but background not full size, just in center.
anyone can help me ? thanks before

**Comment by simonberger** [comment]
That is the absolute correct behaviour. Please open the same HTML-file in a browser.
What you might want is to change the background size with help of the background-size tag.

Have a look here: https://github.com/dompdf/dompdf/issues/463
I had a first test to implement some time ago and continue working on it soon hopefully.
