### ISSUE TITLE
Can't initialize a simple test

### ISSUE THREAD

**Issue by tragx** [dompdf/dompdf#1487]
When I try to do an example, calling the autoload.inc.php fails with a Warning

`require_once ('dompdf-2017\autoload.inc.php');`

` Warning: require_once(C:\<my-webserver-path>\dompdf-2017/lib/php-font-lib/src/FontLib/Autoloader.php) [function.require-once]: failed to open stream: No such file or directory in C:\<my-webserver-path>\dompdf-2017\autoload.inc.php on line 20`

When I go to inspect the directory 'php-font-lib' within the 'lib' directory, it is not there. The only folders are 'fonts' , 'html5lib' , and 'res'

It fails with a Fatal error eventually:

`Fatal error: require_once() [function.require]: Failed opening required 'C:\<my-webserver-path>\dompdf-2017/lib/php-font-lib/src/FontLib/Autoloader.php' (include_path='.;C:\php\pear') in C:\<my-webserver-path>\dompdf-2017\autoload.inc.php on line 20`

**Comment by tragx** [comment]
I'm reading this is because I need to have installed this via composer.

Is there an option for those who don't have composer, or the ability to install it in their hosting environment?

**Comment by simonberger** [comment]
Look here at the bottom. The zip-package.
https://github.com/dompdf/dompdf/releases/tag/v0.8.0

**Comment by tragx** [comment]
Thank you! =)

I was using the "Clone or Download" link
