### ISSUE TITLE
col-xs inside another col-xs doesn't work ?

### ISSUE THREAD

**Issue by noreddineelga** [dompdf/dompdf#1495]
I want to print this part of html code in pdf file:

`<div class="row">
				<div class="col-xs-5">
					<b style="font-size: 11px;">Tél: +212 539 716 797<b><br>
						<b style="font-size: 11px;">Av. Bouabid Zkt 07 N°20 RDCH Local N°22 TETOUAN</b><br>
						<b style="font-size: 11px;">Gsm: +212 667 436 706</b>
						<h3 style="font-weight: bolder;">LOCATION DE VOITURE</h3>
						<h4>N° 004008</h4>
					</div>
					<div class="row col-xs-5">
						<div class="col-xs-5">
							<div style="background:#000;padding: 8px;color:#fff;margin-bottom: 6px;">STATION DEPART</div>
							<div style="border: 1px solid;height: 40px;">...............</div>
						</div>
						<div class="col-xs-5">
							<div style="background:#000;padding: 8px;color:#fff;margin-bottom: 6px;">STATION RETOUR</div>
							<div style="border: 1px solid;height: 40px;">...............</div>
						</div>
					</div>
				</div>`
when i use col-xs inside another one, the one in inside dosen't work ?

**Comment by simonberger** [comment]
Please have a look at this issue: https://github.com/dompdf/dompdf/issues/631

The problem is that there is a massive usage of float. Float yet has just a very basic support.
