### ISSUE TITLE
image found but completely white

### ISSUE THREAD

**Issue by exdelierium** [dompdf/dompdf#1497]
Hi,
I am new to domPDF and managed to install the hello world on my server.
For hours now I try to insert a simple .jpg image to the hello world setup, but it does not work. After adding a black border to the image, I at least found out that the picture is theoretically showing correctly, meaning the position as well as the size of the image is correct (even though I did not set the dimensions manually, so the image must have been found and read correctly in order to know its dimensions).
However, inside the black css border is just an empty, white canvas.

What I tried so far:
- img {display:block}
- other paths to the image -> I now use a full path /usr/local/www/........., otherwise I get the error "Image not readable or empty"
- using loadHtmlFile instead of $dompdf->loadHtml($html); (whereas $html only holds [img src='".dirname(__FILE__)."/../img/ts-70x70.jpg' style='border:1px solid black;display:block;'])
- I checked that the minimum requirements for dompdf are met
- I included the base64 string of the image directly in the src="", which gave the same "white"(/empty) image
- using the path /img/pic.jpg gave the "Image not readable or empty" error
- setting remote stuff to true in the options.php
- stream_context_create with setHttpContext
- usingthe google logo from the google server as src=""

BUT, as the image obviously is found (i.e. no "Image not readable or empty"-error is showing up), AND as the dimensions of the image are read correctly (when I link to another image, the black border size adapts accordingly to the size of the other image), it does not seem to be the same problem that can be found multiple times via google when looking for "dompdf image not showing", as they all refer to that error I am NOT getting. The picture is just "empty"/white.... (see screenshot, where the black rectangle is EXACTLY the size of the image that should appear..)

Any ideas how to fix that?

Thanks

PS: using dompdf 0.8.0

![grafik](https://user-images.githubusercontent.com/7499491/28395072-b4557d5e-6cf1-11e7-9fad-1a485c5faf8f.png)

**Comment by bsweeney** [comment]
The one things you shouldn't do with images is change the display type. This is a known issue (#693) and I can't recall at the moment if we've addressed it at all.

JPG images are minimally processed, so it shouldn't be anything like IMagick/GMagick corruption. Do you have read/write access to the temporary directory used by Dompdf ([requirements](https://github.com/dompdf/dompdf/wiki/Requirements))? Can you post a sample of the HTML that's generating that PDF? And what about the PDF itself?

**Comment by exdelierium** [comment]
Hi,
the display type was only changed as a test, as I read this in another post somewhere...
The temp-folder does contain files like "ca_dompdf_img_CVcKDQ", so the right shouldnt be the issue.


The Code:
`require_once($dirThis."plugins/domPDF/autoload.inc.php");

// reference the Dompdf namespace
use Dompdf\Dompdf;
use Dompdf\Options;
// instantiate and use the dompdf class
$dompdf = new Dompdf();

$html = "
<html>
 <body>
  <h1>Hello Dompdf</h1>
  <img src='".dirname(__FILE__)."/../img/ts-70x70.jpg' style='border:1px solid black;'>
 </body>
</html>
";
$dompdf->loadHtml($html);
//*/
// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'portrait');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream();`


The file:
[document.pdf](https://github.com/dompdf/dompdf/files/1161660/document.pdf)

Thanks

**Comment by exdelierium** [comment]
Update:
I now checked the exact same setup (same domPDF version, same own code to generate pdf) on another server, and it worked perfectly well. Definitely has to do something with the server... However, I also asked the provider to check whether the requirements are met, and the response was, that all php extensions are activated. :-/

What is left to check?
- the extensions seem to work
- the tmp folder used by dompdf contains files with dompdf names, so must be writable by dompdf
- the images are NOT remote (even though the remote option is enabled)
- I tried several images in different formats, sizes and from different sources

How can this be? Anything I could write to my provider for him to know what to check again?

Thanks

**Comment by bsweeney** [comment]
You might try the following and then checking that the image file in the temp directory is correct. Set  the "debugKeepTemp" option to true, e.g. `$dompdf = new Dompdf(array('debugKeepTemp' => true));`.

It may not be the extension but the backing library. You can get all the relevant info on what's loaded using `php -i` from the console or with a PHP script with the `phpinfo();` function call in it.

**Comment by exdelierium** [comment]
There are no new files in the temp folder since 24 hours ago, how is that possible? I did not (knowingly) change anything with the permissions nor with the php code.
Also, I can open the temp folder in my ftp client to see the files, but when I try to download / open a file I get a "permission denied" :-/ might this be the problem?? if so, how is it possible ther are files iin that folder named "ca_dompdf_img_CVcKDQ"?

as for the phpinfo:

![grafik](https://user-images.githubusercontent.com/7499491/28440331-165a7644-6da6-11e7-9106-107a54223c68.png)

![grafik](https://user-images.githubusercontent.com/7499491/28440340-22f7611e-6da6-11e7-9af3-e053172b69c2.png)

![grafik](https://user-images.githubusercontent.com/7499491/28440360-3f19adfc-6da6-11e7-9af6-279655b19dc3.png)

![grafik](https://user-images.githubusercontent.com/7499491/28440381-4ea9c856-6da6-11e7-8f40-cee9c7df71bf.png)

![grafik](https://user-images.githubusercontent.com/7499491/28440400-63bdb8f6-6da6-11e7-88a5-8eefdca3ca2d.png)

**Comment by exdelierium** [comment]
I changed the tmp-folder to a folder I can control in the options.php of dompdf:
$this->setTempDir('/usr/local/www/....../tmp/'); //sys_get_temp_dir()
where I gave chmod 777.
After creating a pdf with a png and a jpg inside, there is only a log.htm file in the tmp folder, which contains just one line:
53 2048.00 KB 108.39 ms ON

**Comment by exdelierium** [comment]
I found the source of the error :-)

When saving the pdf to the server and then downloading it, the images show up as they should! 
$output = $dompdf->output();
file_put_contents()

Only when I stream the output with $dompdf->stream(); and then try to show the file, the error occurs. As the request to create the pdf is done via an ajax request, the stream is the response of the ajax call, and I tried to show that with:
----------
var blob=new Blob([data]);
window.open(URL.createObjectURL(blob));
----------
where data holds the full response of the ajax call.

So, this doesnt seem to be the correct way to show the generated pdf file adhoc, i.e. without saving it to the server first.
Any ideas with this newly found information?

Many thanks for sticking with me :-)

**Comment by youngcrv** [comment]
Just to let you know, I'm having the same issue (DomPDF 0.8), the image in the src is not appearing (not white ... transparent as doesn't show against a colored background).  A border and background show where the image should be.  Saving to a file doesn't seem to work for me.  
Weirdly, in some PDFs, earlier images show and then later ones do not.  Works fine when I just output as HTML to a browser window.

**Comment by youngcrv** [comment]
Found the solution to my issue by researching things that others have noted ... basically, in my case the css for img had been set as inline-block.  You don't want to do this with dompdf ("It appears that if your CSS specifies your images as display:block, DOMPDF won't show them sometimes. Have changed my code so that it uses a pdf-specific CSS file without that it.").  So, if you're experiencing the weird behavior in my prior post, check the css your on img.

**Comment by bsweeney** [comment]
@exdelierium that is an interesting result. I'm not sure why saving vs. streaming would cause such a problem. We have had issues in the past where the stream did not end correctly but that would usually result in PDF corruption errors rather than white images. You can try seeing if that's the cause by forcing your script to end after the call to `$dompdf->stream()`.
