### ISSUE TITLE
Images not be aligned as expected

### ISSUE THREAD

**Issue by khrisnagunanasurya** [dompdf/dompdf#1498]
I got the list margined each new page

![image](https://user-images.githubusercontent.com/6211333/28579880-7d9cc9cc-7190-11e7-8e28-8e7b5a2dba26.png)

How to fix this? I already tried it with margin and padding to 0 but not fix it, 
the image after new page is not supposed to be like that, it should be aligned with below or before the break page.

I'm using DOM PDF 0.6.2 for CodeIgniter

**Comment by Alpian-Imran** [comment]
An uncaught Exception was encountered

Type: Error

Message: Class 'Dompdf' not found

Filename: C:\xampp\htdocs\dompdf\application\controllers\Welcome.php

Line Number: 32

Backtrace:

File: C:\xampp\htdocs\dompdf\index.php
Line: 315
Function: require_once
 
Punya saya malahnya seperti di atas gan.. kira gimana untuk memperbaikinya. mohon bantuannya gan.

**Comment by khrisnagunanasurya** [comment]
Coba liat file welcome.phpnya gan

**Comment by Alpian-Imran** [comment]
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Welcome extends CI_Controller {
	public function __construct()
	{
		parent:: __construct();
		$this->load->helper('pdf_helper');
	}

	public function index()
	{
		$this->load->view('welcome_message');
	}

	public function generator()
	{
	    $html=$this->load->view('welcome_message');
			$dompdf = new \DOMPDF();
			$dompdf->load_html($html);
			$dompdf->render();
			$dompdf->stream('contoh.pdf',array('Attachment' =>0,));
	}
}

ni gan

**Comment by khrisnagunanasurya** [comment]
`
		$this->load->library('pdf');

	  	$this->pdf->load_view('pages/cetak_data', $data);
	  	$this->pdf->render();

	  	$this->pdf->stream('data.pdf');	
`

harusnya cuma kyk gitu untuk manggilnya gan,
gak perlu load helper,
soalnya dompdfnya dijadiin library.

**Comment by Alpian-Imran** [comment]
bisa minta wa apa fb atau kontak lainnya gan. pingin kosultasinya bnyak hal sama agan.

**Comment by Alpian-Imran** [comment]
Fatal error: Class 'DOMPDF' not found in C:\xampp\htdocs\Getpdf\application\libraries\pdf.php on line 15
A PHP Error was encountered

Severity: Error

Message: Class 'DOMPDF' not found

Filename: libraries/pdf.php

Line Number: 15

Backtrace:

begini gan..

**Comment by simonberger** [comment]
It is really hard to help based on the description and image you provided.

- I don't know what you expect it to look like.
- Which margin do you mean? The one from the top of the page or to the left?

Please provide a simple example in form of HTML code (no PHP).

**Comment by khrisnagunanasurya** [comment]
Hi, simonberger. The problem i got is why the first picture for every page is like it's styled with margin-left, what i want its to be like the rest. They are aligned in 1 coulmn position, not like on the top of the page, its like its aligned to middle

**Comment by simonberger** [comment]
Please use the newest version of Dompdf (0.8.0) and if this doesn't help provide some HTML so we can reproduce the behaviour.

**Comment by khrisnagunanasurya** [comment]
This is my html files.
FYI: I'm using Dompdf for Codeigniter, and what i can found that can be used for codeigniter is 0.6.2

`<style type="text/css">
	body { font-family: Calibri; }
	.wrapper { width: 605px; margin: 0 auto; }
	.row { width: 100%; display: block; margin-bottom: 10px; }
	.row:last-child { margin-bottom: 0; }
	.number { width: 5%; display: inline-block; text-align: center; vertical-align: top; }
	.photo { width: 20%; display: inline-block; padding: 10px; border: 1px solid #000; }
	.photo img { width: 100%; }
	.description { width: 370px; display: inline-block; vertical-align: top; border: 1px solid #000; font-size: 14px; padding: 10px; }
	.list { width: 100%; display: block; margin: 0; padding: 0; }
	.column-left { width: 30%; display: inline-block; }
	.column-right:before { content: ': '; }
	.column-right { width: 65%; display: inline-block; }
</style>

	<center>PROFIL ANAK LKSA WIDHYA ASIH</center>
	<center><?= date('Y') ?></center>
	<center>LKSA Widhya Asih : Singaraja</center>
	<br /><br />

	<div class="wrapper">
		<?php $i = 1; foreach($list_anak AS $anak) { ?>
			<div class="row">
				<div class="number"><?= $i ?></div>
				<div class="photo"><img src="<?= base_url('assets/uploads/anak/' . $anak['foto']) ?>"></div>
				<div class="description">
					<div class="list">
						<div class="column-left">Nama</div>
						<div class="column-right"><?= ucfirst($anak['nama']) ?></div>
					</div>
					<div class="list">
						<div class="column-left">Tempat Tgl lahir</div>
						<div class="column-right"><?= ucfirst($anak['tempat_lahir']) ?>, <?= date('d F Y', strtotime($anak['tanggal_lahir'])) ?></div>
					</div>
					<div class="list">
						<div class="column-left">Pendidikan</div>
						<div class="column-right"><?= ucfirst(explode('|', $anak['pendidikan_saat_ini'])[1]) ?></div>
					</div>
					<div class="list">
						<div class="column-left">Minat & Bakat</div>
						<div class="column-right"><?= $anak['minat_bakat'] ?></div>
					</div>
					<div class="list">
						<div class="column-left">Pretasi</div>
						<div class="column-right"><?= !empty($anak['prestasi_untuk_sponsor']) ? ucfirst(explode('|', $anak['prestasi_untuk_sponsor'])[1]) : 'Belum ada prestasi.' ?></div>
					</div>
				</div>
			</div>
		<?php $i++; } ?>
	</div>`

**Comment by simonberger** [comment]
You should be able to use every library written in native PHP on your own also in this framework.
A short search found me this.

https://github.com/hanzzame/ci3-pdf-generator-library
https://github.com/dompdf/dompdf/wiki/Using-Dompdf-in-CodeIgniter-3.x

There might be a problem that is also still in the newest version of dompdf but we really can't support such an old version and test it on bugs that might be fixed since ages.

**Comment by bsweeney** [comment]
I'd also like to note that you can help us help you by providing the actual HTML rendered by Dompdf rather than the PHP code that generates the HTML.

**Comment by khrisnagunanasurya** [comment]
@simonberger if i update the DOMPDF, what should i do? just replace the DOMPDF files to new the newer one?

@bsweeney actually that's the actual HTML that will be rendered by DOMPDF, why there is a PHP code is because there are a lot of data. and the data can be selected which one will be printed.

**Comment by bsweeney** [comment]
I do realize this is the template you use to generate the HTML. It's more helpful for us if you provide the generated HTML so we don't have to guess at what should replace the PHP code.

**Comment by khrisnagunanasurya** [comment]
@bsweeney Sorry, my mistake. Here is the generated HTML.
![2017_08_09_20_05_20_daftar_sponsor_august_2017](https://user-images.githubusercontent.com/6211333/29120807-9022d460-7d3e-11e7-9a42-f6cf895e0ca4.jpg)


It will be like that every time a new page created, only the top one of every page.

**Comment by bsweeney** [comment]
The screen capture is ok but it's easier for us to try to reproduce the issue if we have the actual code.

**Comment by khrisnagunanasurya** [comment]
@bsweeney sorry, but what is this 'actual code' do you mean? i don't understand it, if you mean the inspect element then sorry, it's PDF file, i can't look the code with inspect element. Or is it something else? 

if it's the code from controller, here it is:
public function daftar_sponsor_anak()
	```
{
		$this->load->model('cetak_model', 'cetak');
		$data['list_anak'] = $this->cetak->daftar_sponsor_anak();

		$this->load->library('pdf');

	  	$this->pdf->load_view('pages/cetak_data_sponsor_anak', $data);
	  	$this->pdf->render();

	  	$this->pdf->stream('daftar_sponsor_'. date('F Y') .'.pdf');	
	}
```

**Comment by bsweeney** [comment]
Sorry, I mean the HTML+CSS of the document you're trying to render.

**Comment by khrisnagunanasurya** [comment]
@bsweeney I already put it on the comment before, [it's here](https://github.com/dompdf/dompdf/issues/1498#issuecomment-319931646)

**Comment by bsweeney** [comment]
That's the PHP code that generates the HTML, not the actual HTML itself. We can more easily debug a problem if we don't have to go through and figure out what to replace the PHP code with.

Anyway, I rendered it without doing any replacement and it does indeed produce the results you describe. I suspect the issue is due to the heavy use of inline-blocks but more research will need to be done to isolate the specific issue.

Your document is structured in such a way that you should be able to achieve the same results using a table instead. Try something like the following:

```
<style type="text/css">
	body { font-family: Calibri; }
	.wrapper { width: 575px; margin: 0 auto; }
	.row { margin-bottom: 10px; }
	.row:last-child { margin-bottom: 0; }
	.number { width: 25px; text-align: center; vertical-align: top; }
	.photo { width: 125px; padding: 10px; border: 1px solid #000; }
	.photo img { width: 100%; }
	.description { width: 425px; vertical-align: top; border: 1px solid #000; font-size: 14px; padding: 10px; }
	.list { width: 100%; display: block; margin: 0; padding: 0; }
	.column-left { width: 30%; display: inline-block; }
	.column-right:before { content: ': '; }
	.column-right { width: 65%; display: inline-block; }
</style>

	<center>PROFIL ANAK LKSA WIDHYA ASIH</center>
	<center><?= date('Y') ?></center>
	<center>LKSA Widhya Asih : Singaraja</center>
	<br /><br />

<table class="wrapper">

<?php $i = 1; foreach($list_anak AS $anak) { ?>
  <tr class="row">
    <td class="number"><?= $i ?></td>
    <td class="photo"><img src="<?= base_url('assets/uploads/anak/' . $anak['foto']) ?>"></td>
    <td class="description">
					<div class="list">
						<div class="column-left">Nama</div>
						<div class="column-right"><?= ucfirst($anak['nama']) ?></div>
					</div>
					<div class="list">
						<div class="column-left">Tempat Tgl lahir</div>
						<div class="column-right"><?= ucfirst($anak['tempat_lahir']) ?>, <?= date('d F Y', strtotime($anak['tanggal_lahir'])) ?></div>
					</div>
					<div class="list">
						<div class="column-left">Pendidikan</div>
						<div class="column-right"><?= ucfirst(explode('|', $anak['pendidikan_saat_ini'])[1]) ?></div>
					</div>
					<div class="list">
						<div class="column-left">Minat & Bakat</div>
						<div class="column-right"><?= $anak['minat_bakat'] ?></div>
					</div>
					<div class="list">
						<div class="column-left">Pretasi</div>
						<div class="column-right"><?= !empty($anak['prestasi_untuk_sponsor']) ? ucfirst(explode('|', $anak['prestasi_untuk_sponsor'])[1]) : 'Belum ada prestasi.' ?></div>
					</div>
    </td>
  </tr>
  <?php $i++; } ?>
</table>
```

_note: I switched to fixed widths on the TD classes because dompdf was unable to determine the appropriate width for the image otherwise. A separate bug._

**Comment by khrisnagunanasurya** [comment]
Ahh now I understand what do you mean with that HTML things.

Yes, it's working perfectly fine now, thank you for your support, hope this issues helping the others as well
