### ISSUE TITLE
Class 'DOMPDF' not Found.  Help. How to Fix.....?

### ISSUE THREAD

**Issue by Alpian-Imran** [dompdf/dompdf#1501]
Fatal error: Class 'DOMPDF' not found in C:\xampp\htdocs\Getpdf\application\libraries\pdf.php on line 15
A PHP Error was encountered

Severity: Error

Message: Class 'DOMPDF' not found

Filename: libraries/pdf.php

Line Number: 15

Backtrace:

**Comment by simonberger** [comment]
Removed your comments in the other issue.

Please start with the installation and example that you can find on the documentation of this project.

https://github.com/dompdf/dompdf/#easy-installation

A minimum example which also shows the use/import that you have to do is 2 blocks under it.

https://github.com/dompdf/dompdf/#quick-start
