### ISSUE TITLE
Encrypt all strings in the document

### ISSUE THREAD

**Issue by simonberger** [dompdf/dompdf#1502]
There are still some non-encrypted strings left in.
Currently I know of:

* ordering
* registry

In font and font-descendent.
There might be more.

They aren't that easy to fix because they are written in the new action of the object and have to be moved to out.

**Comment by simonberger** [comment]
Do we have any known unencrypted strings open?
I have just a fleeting memory of having worked on this at all. ;)

**Comment by bsweeney** [comment]
I honestly can't remember what, if anything, we have left to encode. There does appear to be a problem with fonts when encoding is used, but that may be something we can address separately at this point.

Anybody feel up to checking our work?

**Comment by simonberger** [comment]
We should close this issue with the fix in the next version. Without the fix it showed problems in various validators after it was compatible with version 1.3 (or even 1.7).
