### ISSUE TITLE
List Item Issue

### ISSUE THREAD

**Issue by crow1796** [dompdf/dompdf#1503]
Why's the list item looks like this?
![image](https://user-images.githubusercontent.com/12120770/29013042-c3f85d6e-7b72-11e7-8f44-1a368c2683a5.png)
And its content is on the next page:
![image](https://user-images.githubusercontent.com/12120770/29013050-d715e812-7b72-11e7-95c0-9dc55e07ec74.png)

Here is the code: https://stackoverflow.com/questions/45539948/dompdf-list-item-issue

**Comment by bsweeney** [comment]
I was unable to reproduce the flow issue from your sample, but I believe this may be fixed for the next release (7c3fe91). If you are able to confirm this by trying out the develop branch that would be helpful.
