### ISSUE TITLE
Enhancement: CSS Background Cover

### ISSUE THREAD

**Issue by stargraphicdesign** [dompdf/dompdf#1507]
I would love to be able to utilize the background-size: cover css styling for background images. It basically allows you to proportionately fill a div with a background image and have it cropped via the css

example css:

```
.my-background-image{
    background: url('../images/background.jpg')  no-repeat center center transparent;
    background-size: cover;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
}
```

**Comment by simonberger** [comment]
Hi,
There already is a ticket (#463) to add background-size.
It's not that easy but I started working on it.
It still may take some time.

**Comment by stargraphicdesign** [comment]
thank you! 
sorry i did do a search for it before i posted.

*i figured this might be a bit messy, really appreciate the work!
