### ISSUE TITLE
Unicode title

### ISSUE THREAD

**Issue by rudiedirkx** [dompdf/dompdf#1514]
Using `DejaVu Serif` I can add very exotic unicode in the PDF, but it doesn't work in the PDF metadata (title). PDF viewer is Chrome on Windows.

![screen-pdf-unicode](https://user-images.githubusercontent.com/168024/29421552-abe69d48-8375-11e7-9a2c-7e18d3eb7a3f.png)

Is there a way to do that, or is it safer to `iconv` them for metadata?

**Comment by rudiedirkx** [comment]
Actually, that screenshot is from a merged result with metadata added directly into `FPDI`. This screenshot is with DomPdf only:

![screen-pdf-unicode-2](https://user-images.githubusercontent.com/168024/29421790-6c3f3ce4-8376-11e7-8bbe-045ac1360c41.png)

Different, but not better =)

**Comment by simonberger** [comment]
Fixed an issue some days ago. 
https://github.com/dompdf/dompdf/commit/1c9d285a55d7b8bf82dc72f2f2d94fdb4d07c935

But that was just together with the use of encryption.
But while fixing that I could test the working unicode title generally.

If you fon't use encryption.
As always a html/php example would be helpful.

**Comment by rudiedirkx** [comment]
Weeeell shit that's typical. As I'm trying to prove how it doesn't work, it does work: https://webblocks.nl/tests/dompdf/pdf-nissewaard.php?nomerge

Might Windows vs Ubuntu be important? On Windows it didn't work (not this exact testcase, which might be the difference), and on Ubuntu it does.

After merging, content still works, but metadata is broken, but that's libmergepdf's fault, or mine: https://home.hotblocks.nl/tests/dompdf/pdf-nissewaard.php

**Comment by rudiedirkx** [comment]
That test case works on Windows too... Only DomPdf in Symfony doesn't work for some reason.

Document starts with

```
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>461394054 Alicia Aarts Č č š Š ć</title>
```

but output is `461394054 Alicia Aarts ? ? ı − ?`.

Any idea?

**Comment by rudiedirkx** [comment]
Now I'm completely lost. This one works:

```
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Alicia Aarts Č č š Š ć</title>
```

and this one doesn't:

```
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Alicia Aarts Č č š Š ć</title>
```

Yes, they are exactly the same. The rest of the document isn't exactly the same. These are both sources: https://upload.webblocks.nl/index.php?batch=LV0DolFJZxWSNlljXkSpxziS `pdf-alicia` doesn't work, but `pdf-nissewaard` does...

Still only the document title. The text content works fine.

**Comment by simonberger** [comment]
You do a view render and put that result into dompdf?
I don't remember I think I just used the cpdf title function. I can have a look if I am back from vacation next week.
Can you as a last step make sure that this is the HTML document that dompdf gets and does not get corruped before?
It's absolutely possible that there is a problem in dompdf if unicode titles been read from the document.

**Comment by rudiedirkx** [comment]
I did a Twig render and put that directly into DomPdf, but now I have 2 HTML docs. One works, one doesn't. They are both UTF-8, with UTF-8 header, both have CRLF EOL, they have the same title. One came from a Twig render, the other was typed and pasted manually. Now they're the same on byte level.

**Comment by rudiedirkx** [comment]
The source docs are also in https://github.com/rudiedirkx/dompdf-demo and rendered on https://webblocks.nl/tests/dompdf/pdf-alicia.php?nomerge

**Comment by simonberger** [comment]
I don't understand where it works and where it doesn't work.
If it works and fails for you with the exactly same document on the same system, then the reason can just be a different dompdf version/code or different options for dompdf or cpdf.
I don't know what I could do now.
If its your symfony installation that fails it coult surly have a different dompdf version or calls dompdf differently.

**Comment by rudiedirkx** [comment]
It fails outside of Symfony. 2 different docs, but with the exact same `<title>`. 1 works and 1 doesn't. Same computer, same setup.

Only the metadata (title) is a problem, not the content.

* Works: [pdf-nissewaard.html](https://github.com/rudiedirkx/dompdf-demo/blob/master/pdf-nissewaard.html) ([demo](https://webblocks.nl/tests/dompdf/pdf-nissewaard.php?nomerge))
* Doesn't work: [pdf-alicia.html](https://github.com/rudiedirkx/dompdf-demo/blob/master/pdf-alicia.html) ([demo](https://webblocks.nl/tests/dompdf/pdf-alicia.php?nomerge))

It must be something in DomPdf, because there's nothing else different. Same underground PDF lib. Same server. Etc.

What could break a PDF's metadata? Is it simple added as utf8, or does it depend on something else further on in the source?

This is not high prio at all. Enjoy your holidays and stop reading my issues =)

**Comment by simonberger** [comment]
Well no problem. Dompdf is part of my spare time.
Looking at your document you use different fonts for the body.
Surely if it works in the document it should work in the title too. Still we should figure out the reason of the failure in one of your documents first as it's most likely the solution to the problem.

**Comment by rudiedirkx** [comment]
I've found it! And I reeaally don't get it.

This is the line that breaks `pdf-alicia`:

	$font = $fontMetrics->getFont("serif");

because of `serif`. If I change `serif` to `DejaVu Serif` (which is the doc's `body` font), it works. I understand why `getFont()` for an unsubsetted font wouldn't work, but why does it break metadata??

Also, maybe `$fontMetrics` should just try to load unknown fonts, but that's a different issue IMO.

*But wait*, it gets weirder, at least I think so. If I `getFont('hgyfvbg')` (obviously not a real font), everything works... The font that's used is the `body` font, and metadata works... Eh!?

**Comment by simonberger** [comment]
Yes it's what I expected. The used unicode characters will be stored in the pdf.
That right now is be done in dompdf not cpdf and before rendering.
So if you use characters in the title that aren't in use in the content it might break. But if you use a font that isn't in use in the content it fails for sure.

This really old issue is still the project state and gives some more information
https://github.com/dompdf/dompdf/issues/750
It gives you also an idea how to manually solve it in your code.

Ill have a look how we can fix this particular problem for now and how we can start moving this to cpdf.

**Comment by bsweeney** [comment]
This isn't an issue with font subsetting. The issue is that CPDF is converting the metadata field text to Windows ANSI as it compiles the PDF source.

So how does this happen? All text in the document is run through a filter to format it correctly. One of the filtering options is to convert the character encoding of the text to a PDF-compatible encoding. The encoding conversion relies on the currently selected font. This is fine for most text in the document since the font is selected as it is created. Some text, however, is filtered as the PDF source is compiled (during the output/stream method) and so does not select a font. Metadata is one of the these texts. If the last font used supports Unicode then all is well. If it doesn't then the text in the metadata fields is converted to Windows ANSI (the default PDF encoding).

I think to address this we can just go ahead and encode all metadata strings as UTF16 with BOM. It's a bit overkill since not all text needs to be encoded in that way, but it's probably more reliable than trying to determine if UTF16 is necessary and conditionally encoding the text. Thoughts?

To work around the issue for now you can just ensure that the last font used supports Unicode. In your sample you use embedded scripting to set some text. So at the end of the script just make sure to select a font that supports unicode (i.e. DejaVu).

**Comment by rudiedirkx** [comment]
Even the meta data needs some kind of character encoding! I'm kinda surprised this hasn't been an issue before...

Always encoding it in something reliable seems like a good idea. It's worth the few extra bytes.

So why did it not break with `getFont('hgyfvbg')` ? Did it fall back to the `body` font?

**Comment by bsweeney** [comment]
The meta-data has always been correctly encoded, just not always to the appropriate character set. If the last font loaded was a non-Unicode font it would convert the string to Windows ANSI encoding, resulting in a "?" for any characters not supported by that encoding.

You are correct in your presumption. If you specify a font that doesn't exist CPDF doesn't switch the font. It's like you didn't switch the font at all, meaning CPDF uses the font specified in the body styling.

**Comment by bsweeney** [comment]
Also just want to note that we probably have run into this issue before but didn't realized the cause.

**Comment by PirunSeng** [comment]
Please somebody show me a full sample code you can render unicode to pdf and it is displayed the unicode characters properly.
I get blank boxes of my unicode characters.
The following is what I have tried so far.

I've already had my mbstring extension enabled. (I don't need GD extension cuz my pdf does not have any images)
`extension=php_mbstring.dll`

![dompdf](https://user-images.githubusercontent.com/12696293/29761074-85e6af8c-8bf1-11e7-912b-f161564adfee.PNG)

**Comment by rudiedirkx** [comment]
Copyable text is more handy, so we don't have to type out your screenshot.

**Comment by PirunSeng** [comment]
```
<?php
  require_once 'dompdf/autoload.inc.php';

  $content = '<!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: DejaVu Sans; }
        </style>
      </head>
      <body>
        <h1>Hello សួស្ដី World!</h1>
        <h1>My Khmer unicode is in the middle of above heading.</h1>
      </body>
    </html>';
  use Dompdf\Dompdf;
  use Dompdf\Options;

  $options = new Options();
  $options->set('defaultFont', 'DejaVu Sans');
  $dompdf = new Dompdf($options);
  $dompdf->loadHtml($content);
  $dompdf->render();
  file_put_contents('file.pdf', $dompdf->output());
?>

```

**Comment by bsweeney** [comment]
@PirunSeng the issue is that DejaVu does not have support for Khmer glyphs yet. See the [coverage chart](https://github.com/dejavu-fonts/dejavu-fonts/blob/master/unicover.txt#L53). You'll need to load a different font that does support those characters.
