### ISSUE TITLE
CSS text-transform:capitalize forces to lowercase non-first letters

### ISSUE THREAD

**Issue by francois-m** [dompdf/dompdf#1520]
Hello,

The 'text-transform:capitalize' attribute is supposed to capitalize first letter of each word, without changing the case of other letters, but the implementation in DomPDF forces to lowercase all non-first letters.

Example: the text 'total VAT' should be displayed 'Total VAT', and not 'Total Vat'

See the W3C reference: https://www.w3.org/wiki/CSS/Properties/text-transform

The issue is related to the usage of the function mb_convert_case($text, MB_CASE_TITLE) in src/FrameReflower/Text.php, function _layout_line().

**Comment by francois-m** [comment]
The 'ucwords()' would be a more compliant approach, but ucwords() does not capitalize first letters if accentuated...

**Comment by simonberger** [comment]
Yes that is a good catch.
The solution won't be as easy and smart as one call to mb_convert_case looked like. But we fix that for the next release.

**Comment by simonberger** [comment]
Unfortunately I couldn't find a none-buggy version of a mb_ucwords implementation and wrote an own one.
Please have a test if possible. It's in the develop branch.

**Comment by francois-m** [comment]
Yes, everything seems ok now. Thank you.
Note that the develop version is 25% slower than the master, but I can easily suppose that the develop branch is not fully achieved yet.

**Comment by bsweeney** [comment]
Is develop 25% slower after the commit or just in general. We're not focussing on performance just yet, mainly bug fixes. But a 25% penalty would be extreme. Which version of PHP are you using?

**Comment by francois-m** [comment]
I run again some tests, and I was wrong: the PDF generation process takes the same time. Sorry for this undue alert.
