### ISSUE TITLE
Go to next page

### ISSUE THREAD

**Issue by VeeK727** [dompdf/dompdf#1521]
I want to generate a pdf with multiple pages. I haven't seen anything like this previously mentioned. Basically what I want is wherever the content ends, I could break the page there and start next content from  the new page. Am I being clear here? Is it possible?

**Comment by simonberger** [comment]
https://www.google.de/search?q=dompdf+force+new+page

**Comment by VeeK727** [comment]
Thanks for the hint. If someone's looking for the same thing, here's how you do it

CSS `.page_break { page-break-before: always; }`
HTML `<div class="page_break"></div>`

from [Stackoverflow](https://stackoverflow.com/questions/22746958/dompdf-adding-a-new-page-to-pdf)
