### ISSUE TITLE
Nested ordered lists overlapping

### ISSUE THREAD

**Issue by DojoGeekRA** [dompdf/dompdf#1525]
# Environment:

```
PHP version: 7.1.7
Operating system: macOS Sierra version 10.12.6 (16G29)
Dompdf version: 0.8.0
```

# Problem:

I have found that if i use an ordered list inside another ordered list, the PDF is rendered with the content overlapped.

Steps to reproduce:

- Create a PDF with the following content:

```html
<ol>
    <li>First outter item</li>
    <li>Second outter item</li>
    <ol>
        <li>First inner item</li>
        <li>Second inner item</li>
        <li>Third inner item</li>
    </ol>
    <li>Third outter item</li>
</ol>
```

This will generate something that looks like this:

![ordered-list](https://user-images.githubusercontent.com/5356595/29842230-d9261d22-8ccd-11e7-99ce-aa22b881b76b.png)

# Extra scenarios:

- I have tested the following scenarios:

Unordered list inside another unordered list

```
<ul>
    <li>First outter item</li>
    <li>Second outter item</li>
    <ul>
        <li>First inner item</li>
        <li>Second inner item</li>
        <li>Third inner item</li>
    </ul>
    <li>Third outter item</li>
</ul>
```

which produces the expected content:

![unordered-list](https://user-images.githubusercontent.com/5356595/29842368-4655471a-8cce-11e7-9641-5be9ae1b944e.png)

Ordered lists with unordered lists

```html
<ol>
    <li>First outter item</li>
    <li>Second outter item</li>
    <ul>
        <li>First inner item</li>
        <li>Second inner item</li>
        <li>Third inner item</li>
    </ul>
    <li>Third outter item</li>
</ol>
```

Which also creates overlapping

![ordered-with-unordered](https://user-images.githubusercontent.com/5356595/29842496-b86fc5b4-8cce-11e7-9db9-209f55c7e515.png)

And finally unordered list with ordered lists

```html
<ul>
    <li>First outter item</li>
    <li>Second outter item</li>
    <ol>
        <li>First inner item</li>
        <li>Second inner item</li>
        <li>Third inner item</li>
    </ol>
    <li>Third outter item</li>
</ul>
```

Which also creates overlapping

![unordered-with-ordered](https://user-images.githubusercontent.com/5356595/29842656-1bb98c4a-8ccf-11e7-829c-feb1eaa14665.png)

# Extra information

- I'm using this library through https://github.com/barryvdh/laravel-dompdf with the default settings
- I'm using the `@` operator to create the PDF because it throws a `A non-numeric value encountered` exception

Thanks for your time, and please let me know if i can provide more helpful information

**Comment by bsweeney** [comment]
I'm unable to reproduce what you're seeing. I would guess something in your CSS is causing the unexpected rendering. Can you share a full sample (HTML+CSS) that exhibits the issue?

I'd also like to note that your HTML syntax isn't quite right. You shouldn't place your inner list directly inside the outer list element. The inner list should be inside an LI element. This, however, doesn't appear to be the cause of what you're seeing.

**Comment by DojoGeekRA** [comment]
@bsweeney my apologies, i have found that i didn't remove my stylesheet from the canvas html where i rendered those examples. When i did, the lists are rendered correctly.

P.S. I was writing this when you posted your message, you were right, it was my CSS, i'm sorry for make you waste time 😓

**Comment by bsweeney** [comment]
No worries. Glad it worked out in the end.
