### ISSUE TITLE
Table bottom border doesn't work when table is large and breaks into pages.

### ISSUE THREAD

**Issue by kfelahiju** [dompdf/dompdf#1528]
This is how i did it. 
1. Fetch all data from db and create html rows for each records
2. Insert those rows in a table then generate the pdf. 

It creates multiple pages and table breaks into multiple page.
Problem in those pages where table breaks. Each column has border but the bottom border of last columns doesn't show. But table bottom border in the last page works!

![sc](https://user-images.githubusercontent.com/10286862/29905836-c94101cc-8e32-11e7-85b4-c85a0e5ff0b3.png)

This image is from the first page

**Comment by bsweeney** [comment]
Can we see a sample of the HTML+CSS?

**Comment by kfelahiju** [comment]
Here is the sample code with php. Please let me know if i am doing it right way. I think it could be css problem. Thank you.

$html = <<<DEMO

<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style type="text/css">
    @page {
        margin: 2cm;
    }

    body {
        margin: 334px 0px 0px 0px;
        text-align: justify;
    }
    table{
        border:1px solid #000;
        padding:0px;
        font-size:10px;
        table-collapse:collapse !important;

    }
    table td{
        text-align:center;
        border:1px solid #000;
        min-height:100px;
    }
    td.col_yellow{
        background-color:#F90;
        color:#000;
    }
    td.col_grey{
        background-color:#666;
    }
    td.col_red{
        background-color:#C00;
    }
    td.col_white{
        background-color:#fff;
    }
    td.col_category_name{
        text-align:left;
        padding-left: 10px;
        background-color:#3C3962;
        color:#fff;
    }
    td.asset_id{
        width:10%;
    }
    td.asset_description{
        width:18%;
    }
    td.eql_width{
        width:6%;
        text-align:center;
    }
    #header{
        position: fixed;
        left: 0;
        right: 0;
        color: #aaa;
        font-size: 0.9em;
        top: 20px;
        border-bottom: 0.1pt solid #aaa;
    }
    #header table{
        width: 100%;
        border-collapse: collapse;
        border: none;
    }
    #header td{
      padding: 0;
      width: 50%;
    }
    div.fixed-section{
        position: fixed;
        left: 0px;
        bottom: -180px;
        right: 0px;
        height: 150px;
        padding-bottom:5px;
    }
    span.region{
        display:block;
        float:left;
        width:500px;
    }
    .page-number{
        display:block;
        width:100px;
        float: right;
    }
    .footer .page-number:after { content: counter(page); }
</style>
</head>

<body>
<div id="header">
<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td class="col_yellow" style="width:6%">Col </td>
    <td class="col_yellow" style="width:6%">Col </td>
    <td class="col_yellow" style="width:6%">Col </td>
    <td class="col_yellow" style="width:6%">Col </td>
    <td class="col_yellow" style="width:6%">Col</td>
    <td class="col_yellow" style="width:6%">Col</td>
    <td class="col_yellow" style="width:6%">Col</td>
    <td class="col_yellow" style="width:6%">Col</td>
    <td class="col_yellow" style="width:6%">Col</td>
    <td class="col_yellow" style="width:6%">Col</td>
    <td class="col_yellow" style="width:6%">Col</td>
    <td class="col_yellow" style="width:6%">Col</td>
  </tr>
</table>
</div>
<div class="footer fixed-section">  
  <div class="right">
    <span class="region"><strong>Test: </strong> Test  <strong>Test: </strong> data  <strong>Test: </strong> data</span>
    <span class="page-number">Page </span>   
  </div>
</div>


<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
  <tr><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
</table>
</body>
</html>

DEMO;

    $dompdf = new Dompdf();
    $dompdf->set_paper("A4", "landscape");
    $dompdf->set_option("isPhpEnabled", true);
	$dompdf->load_html($html);
	$dompdf->render();

	$output = $dompdf->output();
	file_put_contents('test.pdf', $output);

**Comment by bsweeney** [comment]
WIth your sample code I wasn't able to reproduce the issue. I can't be of much help unless I can do so.

I'd guess it's probably an issue around the CSS. First thing I would try is to remove the styling and add back a piece at a time to try and isolate the cause.

**Comment by masonmonu** [comment]
I am also facing the same issue, any update?

**Comment by bsweeney** [comment]
@masonmonu as I mentioned in my previous comment I was unable to reproduce the issue. I would need more details about your Dompdf version and configuration, and some sample HTML that exhibits the problem.

**Comment by UdayasankarT** [comment]
I have this sample issue. Any solution for this issue?

**Comment by SonnySVK** [comment]
I have similar problem with tfoot after tbody, i just did simple solution that content in tfoot i moved to tbody (and set classes for this items to style it) and it solve my problem

so just dont use tfoot element in table (because dompdf make "space" for this element, also in case that table continues on other page)

**Comment by manesvenom** [comment]
Refer to the following thread  https://github.com/dompdf/dompdf/issues/518#issuecomment-438674581
replace the <tbody> with <body>, it did the trick.

**Comment by rozaliafashion** [comment]
Wrong Answer

**Comment by rozaliafashion** [comment]
@SonnySVK  You Are Wrong
