### ISSUE TITLE
Wrong FontHeight in $fontMetric

### ISSUE THREAD

**Issue by maxcuttins** [dompdf/dompdf#1529]
I need to know the height that i'm gonna to use for every box.
Everything is ok with one line box but with multiline box is not possible to have the right height of the element.

I can simplify the code as the following:
```
$line_height = 1.2;
$font = $fontMetrics->getFont("Helvetica");
$font_height_7pt = $fontMetrics->getFontHeight($font, 7);

$number_of_lines = 5;
$total_height_pt =
       2*$default_padding_pt +  //top + bottom 
       2*$default_border_pt +    //top + bottom
       $number_of_lines * $line_height * $font_height_7pt
```

But it's not working correctly.
By setting `padding` & `border` & `line_height` to zero I realized that the issue is in the `$font_height_7pt` given by FontMetric. It give me a `$font_height_7p` of `7.1225`, while I found that the perfect height is reached when this value is set to `7.9296`. I tried with differents number of lines and differents line_height.
It works correctly only if I manually set the $font_height to this value instead of retrieve it from the $fontMetric.

How can I get the real $font_height if fontMetric gives me wrong values?

**Comment by bsweeney** [comment]
This isn't really my strongest area. If @PhenX has time he might be better able to assist.

That being said, I don't think the issue is that the font height returned is incorrect. What are you attempting to do with the value? Set the height of a containing element?
