### ISSUE TITLE
begin_frame, begin_page, and end_page events are never triggered

### ISSUE THREAD

**Issue by Mellthas** [dompdf/dompdf#1530]
Contrary to `end_frame` and the documentation of the [`setCallbacks()`](https://github.com/dompdf/dompdf/blob/0f418c6b58fdeafc2a0e80eb1fa5e644e185089c/src/Dompdf.php#L1423-L1434) method in `Dompdf.php`, these events are never triggerd; those strings are even nowhere to be found in the code.

Is this intended? Or were they simply never implemented? Anyways, pull request [1531](https://github.com/dompdf/dompdf/pull/1531) adds the `begin_frame` event, because `end_frame` is already there.

**Comment by bsweeney** [comment]
Seems reasonable.
