### ISSUE TITLE
Filename containing spaces displayed incorrectly when downloading PDF

### ISSUE THREAD

**Issue by Mellthas** [dompdf/dompdf#1532]
When using the `stream()` method with a filename containing spaces and no characters outside ISO-8859-1, the current develop branch version of dompdf will show any spaces as `%20` in the current version of Firefox (Chrome seems to be fine; I did not test any other browsers). This worked with dompdf version 0.7.

**Example:**
`This is a test file.pdf` gets display as `This%20is%20a%20test%20file.pdf`.
`This is a test – file.pdf` works correctly.

Addressed by #1533.

**Comment by bsweeney** [comment]
Also seems to be an issue for Safari (tested with 10.1.2).
