### ISSUE TITLE
Regression with negative margin on block level element in table cell

### ISSUE THREAD

**Issue by Mellthas** [dompdf/dompdf#1534]
See the attached HTML test file [margin-bug.zip](https://github.com/dompdf/dompdf/files/1273247/margin-bug.zip). Compare the output of the current dompdf development version with the output of version 0.7:
* [Output develop.pdf](https://github.com/dompdf/dompdf/files/1273249/Output.develop.pdf)
* [Output v0.7.pdf](https://github.com/dompdf/dompdf/files/1273250/Output.v0.7.pdf)

The div inside the table cell has a negative left margin. With the current development version, the text inside the div stays within the table cell’s padding area, instead of moving to the left with its parent. The version 0.7 output is consistent with how Firefox and Chrome display it (minus the table border not being drawn over the div, but that is another issue).

**Comment by Mellthas** [comment]
Interestingly, if you apply `display: inline` to the #test div, the text moves to the left and the background stays within the table instead. There is no difference between the two versions. See [Output inline.pdf](https://github.com/dompdf/dompdf/files/1273260/Output.inline.pdf).

**Comment by bsweeney** [comment]
Appears to be due to commit 9895c02. We'll review that change.
