### ISSUE TITLE
Path of archives not found

### ISSUE THREAD

**Issue by marcoshenzel** [dompdf/dompdf#1536]
In the acrhive `dompdf/autoload.inc.php` on line 20 and 21 are required 2 files, but they not exists ...

     1  <?php
     2 /**
     3   * @package dompdf
     4   * @link    http://dompdf.github.com/
     5   * @author  Benj Carson <benjcarson@digitaljunkies.ca>
     6   * @author  Fabien Ménager <fabien.menager@gmail.com>
     7   * @license http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License
     8   */
     9 
    10    /**
    11   * Dompdf autoload function
    12   *
    13   * If you have an existing autoload function, add a call to this function
    14   * from your existing __autoload() implementation.
    15   *
    16   * @param string $class
    17   */
    18 
    19   require_once __DIR__ . '/lib/html5lib/Parser.php';
    20   require_once __DIR__ . '/lib/php-font-lib/src/FontLib/Autoloader.php';
    21   require_once __DIR__ . '/lib/php-svg-lib/src/autoload.php';
    22
    23  /*
    24   * New PHP 5.3.0 namespaced autoloader
    25   */
    26   require_once __DIR__ . '/src/Autoloader.php';
    27   Dompdf\Autoloader::register();

**Comment by bsweeney** [comment]
You're downloading the source code which does not include not dependencies maintained elsewhere.

You should only use this file if you are downloading a packaged release from the [releases page](https://github.com/dompdf/dompdf/releases). Look for a download link with the version number in it such as [dompdf_0-8-0.zip](https://github.com/dompdf/dompdf/releases/download/v0.8.0/dompdf_0-8-0.zip).
