### ISSUE TITLE
Working with PHP7.1?

### ISSUE THREAD

**Issue by brasileric** [dompdf/dompdf#1539]
Should DomPDF working well with php7.1 ?

**Comment by bsweeney** [comment]
We addressed a number of issues related to PHP 7.1 in the 0.8.0 release. A follow-up release (0.8.1) will be available in the near future that fixes a few issues that slipped by.

**Comment by jeffersonor900** [comment]
I'm work with PHP Version 7.2.1, ¡Help!
(Fatal error: Uncaught DOMPDF_Exception: No block-level parent found. Not good. in C:\xampp\htdocs\ctacobro_6\production\dompdf\include\inline_positioner.cls.php:38 Stack trace: #0 C:\xampp\htdocs\ctacobro_6\production\dompdf\include\frame_decorator.cls.php(546): Inline_Positioner->position() #1 C:\xampp\htdocs\ctacobro_6\production\dompdf\include\text_frame_reflower.cls.php(331): Frame_Decorator->position() #2 C:\xampp\htdocs\ctacobro_6\production\dompdf\include\frame_decorator.cls.php(556): Text_Frame_Reflower->reflow(NULL) #3 C:\xampp\htdocs\ctacobro_6\production\dompdf\include\page_frame_reflower.cls.php(138): Frame_Decorator->reflow() #4 C:\xampp\htdocs\ctacobro_6\production\dompdf\include\frame_decorator.cls.php(556): Page_Frame_Reflower->reflow(NULL) #5 C:\xampp\htdocs\ctacobro_6\production\dompdf\include\dompdf.cls.php(817): Frame_Decorator->reflow() #6 C:\xampp\htdocs\ctacobro_6\production\Impresion.php(859): DOMPDF->render() #7 {main} thrown in C:\xampp\htdocs\ctacobro_6\production\dompdf\include\inline_positioner.cls.php on line 38)
