### ISSUE TITLE
CSS Pseudo elements repeated on new page

### ISSUE THREAD

**Issue by bennybee** [dompdf/dompdf#1540]
I have a HTML table and the only way I was able to rotate the text in the head successfully was by using pseudo elements. Problem is that when the table runs over two pages, and the head is repeated, the pseudo elements also repeat inside each cell. So on the 2nd page there are 2 pseudo elements, 3rd page there are 3 etc.

eg the following code:

```
<table>
            <thead>
                <tr>
                    <th>
                        <div class="foo"></div>
                    </th>
```

```
.foo:after {content: 'foo';}
```

Results in a table that has 'foo' on the first page, 'foo foo' on the second, 'foo foo foo' on the third...

**Comment by bsweeney** [comment]
Already addressed for the next release. See #1518.
