### ISSUE TITLE
PDF metadata does not always display correctly for protected documents

### ISSUE THREAD

**Issue by bsweeney** [dompdf/dompdf#1541]
For protected documents the encrypted string produced for document metadata (title, creation date, etc) does not always display correctly (or at all) by the PDF viewer. Since the encryption key differs with each render the same HTML document may contain the correct metadata on some renders but not on others.

**Comment by bsweeney** [comment]
[This PDF](https://github.com/dompdf/dompdf/files/1301435/css_line_height.html.pdf) has an egregiously ridiculous producer field.

**Comment by Daniel-Beardsmore** [comment]
I don’t suppose there is any suggested workaround to this, is there?

I’ve just noticed the same problem myself.

**Comment by Daniel-Beardsmore** [comment]
Hmm … I would have thought that making this change to Cpdf::o_info would work:

	if ($encrypted) {
	//    $v = $this->ARC4($v);
	}

However, now the metadata is completely mangled!

**Comment by bsweeney** [comment]
@Daniel-Beardsmore it's been a while since I looked at this issue. No work-around that I can share. I'd really have to refresh myself on the problem before I could be of any help.

**Comment by Tigla** [comment]
> Hmm … I would have thought that making this change to Cpdf::o_info would work:
> 
> ```
> if ($encrypted) {
> //    $v = $this->ARC4($v);
> }
> ```
> 
> However, now the metadata is completely mangled!

I think it would be more correct to do this in [this line](https://github.com/dompdf/dompdf/blob/8d8a529500a2e5e01152c9b99488adb815d568cb/lib/Cpdf.php#L1779):
```
                    if ($encrypted) {
                        $v = $this->filterText($this->ARC4($v), false, false);
                    }
```

**Comment by bsweeney** [comment]
We made some updates to encrypted document handling with 0.8.6. I have not yet reviewed in regards to this particular issue but will try to do so shortly.

**Comment by Tigla** [comment]
I checked, this problem also exists in version 0.8.6.
Parentheses are not escaped in this, in fact, as described here: https://github.com/dompdf/dompdf/issues/1643
An additional call to the filterText() method fixes this problem.

**Comment by bsweeney** [comment]
Thanks for the follow up. I'll take a look and see if we can fix for the next release.
