### ISSUE TITLE
My font work in chrome but appear with dot in Windows

### ISSUE THREAD

**Issue by MaximeDetaille** [dompdf/dompdf#1542]
Hello,

I use dompdf for generate pdf files. I added a personal font with the php_load method and this is working in chrome.

But when i open it with Acrobat Reader, my personal font is replace by little dot.
There is a way to get a flatten image of my pdf or to add my font for acrobat ?

I will post my code juste behind :
```
$dompdf = new Dompdf();
        $options = new Options();
        $options->setIsRemoteEnabled(true);
        $options->setDpi(300);
        $options->setDefaultPaperSize("A4");
        $dompdf->setOptions($options);
        $contxt = stream_context_create([
            'ssl' => [
                'verify_peer' => FALSE,
                'verify_peer_name' => FALSE,
                'allow_self_signed'=> TRUE
            ]
        ]);
        $dompdf->setHttpContext($contxt);
        $html = $this->renderView('admin/pdfTemplating.html.twig',array(
            'nom' => $nom,
            'code' => $code,
            'somme' => $somme,
            'date' => $date,
            'evt' => $evt,
            'template' => $template
        ));
        $dompdf->loadHtml($html);
        $dompdf->render();

        //return $this->render('admin/pdfTemplating.html.twig');
        return new Response($dompdf->stream());
```

And i got an error in acrobat :
- the entered font contains an erroneous \ bbox

**Comment by bsweeney** [comment]
Which version of dompdf are you using? Can you upload a sample of the resulting PDF?

**Comment by hidestars** [comment]
I use the lastest version of dompdf so the 0.8.0

And the result of my pdf looks like this :
(https://github.com/dompdf/dompdf/files/1305557/document.1.pdf)

**Comment by bsweeney** [comment]
There does appear to be an issue. We'll need to take a closer look. Do you have font subsetting enabled? If so you might try disabling it.

**Comment by bsweeney** [comment]
What font are you using and is it one you can share with us?

**Comment by hidestars** [comment]
I try with and without subsetting enable but it still the same.

And the font is this one https://wildtype.design/product/entra-free-font/

**Comment by bsweeney** [comment]
Reviewing this, the download page for Entra indicates it's provided in OTF and WOFF formats. Dompdf (with php-font-lib) currently only supports TTF font files.
