### ISSUE TITLE
autoload.inc.php missing in v0.8.1

### ISSUE THREAD

**Issue by edolix** [dompdf/dompdf#1544]
Hi, 

latest release v0.8.1 is missing of *autoload.inc.php* .
It's already required into dompdf lib?

Thanks!

**Comment by edolix** [comment]
Sorry, i read the commit history and found it  39cf8906c39a01b0e54ed140d970332580350cd6

**Comment by bsweeney** [comment]
Indeed you're not the first to ask about it. I'll be working on documentation for a little while and I'll be sure to update the instructions if you're pulling directly from git. And hopefully I'll have a dist builder ready sometime soon in the utils project.

**Comment by shahid-webforest** [comment]
where is found autoload.inc.php missing

**Comment by bsweeney** [comment]
If you need the autoloader you can get it from the packaged release.

A copy of the original version can be found here: https://github.com/dompdf/utils/blob/d9049f5b5df23b4e97b332a81205b5bb5ae1fbcc/autoload.inc.php
