### ISSUE TITLE
How do i create watermarks in DOMPDF

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#155]
_Original author: bthakk...@gmail.com (May 04, 2010 06:38:56)_

<b>What steps will reproduce the problem?</b>
1. I want to create a watermark on the PDF files. 
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
There should be a watermark with word COPY on the generated PDF.

<b>What version of the product are you using? On what operating system?</b>
DOMPDF 5

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=149_

**Comment by tamaghna91** [comment]
where to put this code? I am unable to find..

**Comment by bsweeney** [comment]
You would put that code at the top of the body content. You also have to enable embedded script support by setting `DOMPDF_ENABLE_PHP` to true (in 0.6.0) or `$dompdf->set_option('isPhpEnabled', true);`. Before you do this, though, you should read the [security documentation](https://github.com/dompdf/dompdf/wiki/Securing-dompdf).

As of 0.6.0 you could also do this entirely using CSS with code similar to the following:

```
<html>
<head>
  #watermark {
    position: fixed;
    top: 45%;
    width: 100%;
    text-align: center;
    opacity: .6;
    transform: rotate(10deg);
    transform-origin: 50% 50%;
    z-index: -1000;
  }
</head>
<body>
  <div id="watermark">
    DRAFT
  </div>
  <div>
    ...
  </div>
</body>
</html>
```

You would, of course, need to tweak the CSS as needed such that the watermark is styled how you want.

**Comment by tamaghna91** [comment]
I am using dompdf 0.6 with drupal print module,@bsweeney is it possible to add header and footer template with you watermark solution on every page.

Your help is needed.Please.

**Comment by bsweeney** [comment]
It would help to see a sample of the HTML you're using.

In reviewing the previous embedded script sample again I can say it's not quite right. I'll tweak that comment so that it accurately reflects how to do this with embedded script.

You can also use my code sample for headers and footers. Check out this code sample from the 0.6.2 release: https://github.com/dompdf/dompdf/blob/v0.6.2/www/test/css_position_fixed.html

**Comment by tamaghna91** [comment]
I am unable to show you the exact html,coz drupal internally generates that html view which can't be identified on firebug when opening the pdf,the updated pdf is this,I have already tweak your css to work.

Not finding the solution,little playing around.Thanks for the help,this library is too good than the others.

**Comment by bsweeney** [comment]
Typically you'll see positioned content on a single page only when you use `position: absolute`. But it's hard to say exactly why you're getting this result without seeing the HTML. I don't really know drupal well enough to tell you how to get the HTML. If you have access to the dompdf object you can call `$dompdf->output_html()` to see the HTML it's working with.

**Comment by tamaghna91** [comment]
@bsweeney, onething can you help me,what and where to write code for header and footer template that  will print on every page.I know dompdf is responsible to render that rendering header and footer,as I have no idea about dompdf,need to know where to put code and what code.

Your help required.

**Comment by tamaghna91** [comment]
@bsweeney, finally I have done it what I required, gracious! Thanks for you auspicious help. Onething after loving dompdf, I would like to help the community,may I get your email to contribute with a better hand!

**Comment by bsweeney** [comment]
Head over to the developer discussion and we can start a conversation: http://groups.google.com/group/dompdf-dev

**Comment by dea96** [comment]
> You would put that code at the top of the body content. You also have to enable embedded script support by setting `DOMPDF_ENABLE_PHP` to true (in 0.6.0) or `$dompdf->set_option('isPhpEnabled', true);`. Before you do this, though, you should read the [security documentation](https://github.com/dompdf/dompdf/wiki/Securing-dompdf).
> 
> As of 0.6.0 you could also do this entirely using CSS with code similar to the following:
> 
> ```
> <html>
> <head>
>   #watermark {
>     position: fixed;
>     top: 45%;
>     width: 100%;
>     text-align: center;
>     opacity: .6;
>     transform: rotate(10deg);
>     transform-origin: 50% 50%;
>     z-index: -1000;
>   }
> </head>
> <body>
>   <div id="watermark">
>     DRAFT
>   </div>
>   <div>
>     ...
>   </div>
> </body>
> </html>
> ```
> 
> You would, of course, need to tweak the CSS as needed such that the watermark is styled how you want.

work like charm

**Comment by Yigaue** [comment]
Thanks, the CSS worked for me. I didn't need to use the script.

**Comment by rahulreghunath** [comment]
> You would put that code at the top of the body content. You also have to enable embedded script support by setting `DOMPDF_ENABLE_PHP` to true (in 0.6.0) or `$dompdf->set_option('isPhpEnabled', true);`. Before you do this, though, you should read the [security documentation](https://github.com/dompdf/dompdf/wiki/Securing-dompdf).
> 
> As of 0.6.0 you could also do this entirely using CSS with code similar to the following:
> 
> ```
> <html>
> <head>
>   #watermark {
>     position: fixed;
>     top: 45%;
>     width: 100%;
>     text-align: center;
>     opacity: .6;
>     transform: rotate(10deg);
>     transform-origin: 50% 50%;
>     z-index: -1000;
>   }
> </head>
> <body>
>   <div id="watermark">
>     DRAFT
>   </div>
>   <div>
>     ...
>   </div>
> </body>
> </html>
> ```
> 
> You would, of course, need to tweak the CSS as needed such that the watermark is styled how you want.

Works Perfectly
