### ISSUE TITLE
When and why "reference child is not a child of this node"  exception occurs and How to solve "reference child is not  a child of this node" exception.?

### ISSUE THREAD

**Issue by suresh-kumara-gist** [dompdf/dompdf#1550]
When and why "reference child is not a child of this node"  exception occurs and How to solve "reference child is not a child of this node" exception.?

Dompdf\Exception: Reference child is not a child of this node. in Dompdf\Frame->insert_child_after() (Zeile 1048 in vendor/dompdf/dompdf/src/Frame.php).

Thank you.

**Comment by bsweeney** [comment]
Do you have a sample of the HTML that you're attempting to render?

**Comment by suresh-kumara-gist** [comment]
If our HTML contains multiple order list. We get this issue.

Example:   <ol><li>test 1</li><li>test 2</li></ol> 
                 <ol><li>test 3</li><li>test 4</li></ol>

**Comment by bsweeney** [comment]
I don't see any errors using that text by itself. Perhaps something else in your document structure or the CSS is the cause. Can you provide a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve)?

**Comment by suresh-kumara-gist** [comment]
Issue is resolved to me. Thank you bsweeney . 

We had **float: left** style in our style sheet which was rendering in dom pdf.  We commented all the css from style sheet to debug. Only Html rendered in pdf without exception.  So it confirmed us that because of css we are getting error. Again uncommented in style sheet and line by line debugging in style sheet gave us root cause that **float: left**   and only when ol tag rendered more than once will throw exception. 

fixed by  removing **float : left ** style.

**Comment by suresh-kumara-gist** [comment]
Please close the issue.

**Comment by bsweeney** [comment]
I'd like to keep this open for not just to ensure we're not mis-handling an element. If you're willing to help, I'd like to see the code you used that caused the issue to see if we can reproduce it.
