### ISSUE TITLE
Call to a member function createElement() on null in Stylesheet.php

### ISSUE THREAD

**Issue by WeeHong** [dompdf/dompdf#1551]
Previously I managed to create a PDF without any issue.

But after I ran composer update and this issue.

May I know how to rectify this?

**Comment by bsweeney** [comment]
Composer updated to 0.8.1? I haven't run across this in my testing. Do you have a sample of the HTML + CSS?

**Comment by WeeHong** [comment]
@bsweeney 

I managed to compile my HTML + CSS into CSS by removing the hyperlink of bootstrap.

```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
```

But I believe this is not the main issue since I managed to convert my HTML to PDF a few days ago.

**Comment by usmanbarefoot** [comment]
i installed this in my project into two different branches and yesterday i just run the composer update command then after that it's will shown an error =>  Call to undefined method DOMDocument::hasAttribute() #393
and on other branch it's still working like charm

**Comment by WeeHong** [comment]
@usmanbarefoot 

Did my solution help you rectify your issue?

**Comment by bsweeney** [comment]
It's maybe an issue with some changes we made in 0.8.1. If I render an empty document with just a reference to the Bootstrap 4 CSS I get an error.

**Comment by usmanbarefoot** [comment]
@WeeHong 
yes!! 
Remove the external link or sciprt from view file it's worked but when you added the external links it's thrown same error

**Comment by bsweeney** [comment]
Unless I'm mistaken I don't think it's the reference to external CSS generally. I believe Dompdf is mis-handling something in the Bootstrap CSS.

**Comment by usmanbarefoot** [comment]
@bsweeney  Yes the problem is in bootstrap 4 CSS all other external CSS and JS are working

**Comment by WeeHong** [comment]
@bsweeney I try to remove other data attributes from `<link>` but it still getting an error. Could it be the URL issue?

@usmanbarefoot Which means the CSS from other party is fine but only Bootstrap got the issue?
