### ISSUE TITLE
How to add header and footer for every page 

### ISSUE THREAD

**Issue by xploregopi** [dompdf/dompdf#1552]
How to add header and footer for every page ? Any idea. 

How to hide the header and footer in first page.

**Comment by bsweeney** [comment]
There are a few issues related to adding a header/footer: #571, #1190.

Hiding it on the first page is a bit more difficult. How you do it depends more on the nature of your document. There's at least one related issue (#385) and a post on StackOverflow (https://stackoverflow.com/a/7214442/264628).

If these don't help and you need more specific help please post additional details.
