### ISSUE TITLE
Class 'DOMDocument' not found

### ISSUE THREAD

**Issue by WeeHong** [dompdf/dompdf#1554]
Class 'DOMDocument' not found when converting HTML to PDF.

I running my website on Ubuntu 17.04.

I tried to install `php7.1-xml` and restart the `php7.1-fpm` also the apache2.

<img width="767" alt="screen-shot-2017-09-27-at-12 29 30-pm" src="https://user-images.githubusercontent.com/6753022/30896533-ecb57f5a-a383-11e7-881d-06f4838bb0b9.png">

But I am still getting this error.

Possible to provide a solution to rectify this issue?

Thanks.

**Comment by bsweeney** [comment]
Is this resolved or did you close accidentally?

**Comment by WeeHong** [comment]
@bsweeney I resolved it. Thank you for following up.

**Comment by dhmusman** [comment]
Hi, How you have resolve can you let me know?

**Comment by WeeHong** [comment]
@dhmusnan

You try to remove your head tag and try.

**Comment by dhmusman** [comment]
@WeeHong Thanks for reply, can you give me commend which i have need to run?

**Comment by WeeHong** [comment]
@dhmusman 

This is the command I used to run when I setup for a new VM.

`sudo apt-get install -y php7.1-xml php7.1-xsl php7.1-mbstring php7.1-readline php7.1-zip php7.1-mysql php7.1-phpdbg php7.1-interbase php7.1-sybase php7.1 php7.1-sqlite3 php7.1-tidy php7.1-opcache php7.1-pspell php7.1-json php7.1-xmlrpc php7.1-curl php7.1-ldap php7.1-bz2 php7.1-cgi php7.1-imap php7.1-cli php7.1-dba php7.1-dev php7.1-intl php7.1-fpm php7.1-recode php7.1-odbc php7.1-gmp php7.1-common php7.1-pgsql php7.1-bcmath php7.1-snmp php7.1-soap php7.1-mcrypt php7.1-gd php7.1-enchant libapache2-mod-php7.1 libphp7.1-embed`

After that, you can try to generate the PDF again.
If the error occurred, try to remove everything in your file and just generate a simple `Hello World` PDF.

**Comment by dhmusman** [comment]
@WeeHong 
Thanks for reply, but it is not work in my case.
Fatal error: Uncaught Error: Class 'DOMDocument' not found in /

**Comment by WeeHong** [comment]
@dhmusman 
Would you mind to show me your HTML file which is ready to convert to PDF?

**Comment by dhmusman** [comment]
@WeeHong 
Hi, Thanks for reply, I am running virtualmin server on CLI php7.2 is running and on CGI php7.0, I am not able to change CGI version and not able to install php7.0-xml it say already installed but now working with php 7.0
