### ISSUE TITLE
render dynamic height table rows with header,footer

### ISSUE THREAD

**Issue by subdesign** [dompdf/dompdf#1555]
Hey, my problem is the following: I have to loop table rows with 3 columns of data: name, position, company. On every page I have a header and footer. In theory, if every row has the same height, I can count how much table rows I will have, and loop only that number, header and footer will be in place. 
But sometimes people has very long position or company name and that line will be 2x or 3x the height of the default row. What do you suggest to solve this problem with DomPDF? 
Or if possible, how to count how much rows I need per page on php side, and then I would build data chunks for the loop. Or should I guess the row number/page by the text length, is it possible?!?

thanks

**Comment by bsweeney** [comment]
I'm not sure I understand the issue you're having. Is the problem that the header/footer is overlapping your content? Or do you want the header/footer to appear in a certain location?

**Comment by naitsirch** [comment]
@bsweeney I think this issue can be closed because of lacking feedback.
