### ISSUE TITLE
Best practice to add custom font?

### ISSUE THREAD

**Issue by enumag** [dompdf/dompdf#1556]
I need some font supporting my language and DejaVu Sand seems quite ugly to me. So I need some custom font. However I don't know how to add it to the document.

I found [this](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo#load-a-font-supporting-your-characters-into-dompdf). I can't use runtime loading because I need the PDF to work offline - I need to somehow emebed the font into the document.

load_font.php is no good either since I install dompdf by composer. The contents of vendor directory should not be changed by anything else than composer.

Is there some other way? I'd like to do something like `$dompdf->addFont('Roboto', '/path/to/roboto.ttf')`. Or is it possible to use base64 data uri?

**Comment by enumag** [comment]
I tried the data uri and it doesn't work. Can you consider adding support for that?

**Comment by bsweeney** [comment]
It has, in fact, come up before. See #967. I'll put it on deck to we don't lose track of it for future dev work.

**Comment by enumag** [comment]
Thanks! I'll follow that issue then.

**Comment by MichalJakubeczy** [comment]
If your app is offline you can still save the font on local server and access it via http://localhost/{path to your font} URL.
