### ISSUE TITLE
External links does not work anymore

### ISSUE THREAD

**Issue by jonnyxe** [dompdf/dompdf#1559]
PHP 7.1
Dompdf 0.8.1

**Comment by bsweeney** [comment]
This does appear to be the case. Probably to do with string encoding.

**Comment by hultberg** [comment]
@bsweeney I'm having the same problem. After digging deeper into whats going on, I noticed that the URL gets a BOM character after (in CPDF) Cpdf::filterText is called with $bom=true, that then calls Cpdf::utf8toUtf16BE() https://github.com/dompdf/dompdf/blob/v0.8.1/lib/Cpdf.php#L4017

Is an acceptable fix just setting $bom=false here: https://github.com/dompdf/dompdf/blob/v0.8.1/lib/Cpdf.php#L1480 ?

**Comment by bsweeney** [comment]
This is the solution I was thinking was appropriate.

**Comment by Julianoe** [comment]
Has this been resolved ? I seem to have the same kind of problem

**Comment by gemal** [comment]
what is missing here? if a pull request is made will it be accepted and merged?

**Comment by bsweeney** [comment]
@Julianoe it has not yet been resolved. The fix is fairly straightforward but I've got other responsibilities that are consuming any time I might spend on it.

@gemal yes if someone submits a PR that addresses the issue I will accept it.

**Comment by hultberg** [comment]
Both @gemal and I have now opend a PR @bsweeney, closing mine as I was too late. 🙇‍

**Comment by ray-kay** [comment]
@bsweeney so this will be fixed in the next version (0.8.2)? Any idea when this release will be available?

**Comment by dynasource** [comment]
+1

**Comment by luukScheur** [comment]
Anyone else still having this issue? I tested it in 0.8.0, 0.8.1 and 0.8.2, all of them are not working. It seems that I can click (a little) below the link and it works fine, but clicking on the text itself does not work. PHP 7.0

**Comment by apcro** [comment]
I'm having this issue, and can confirm I am using 0.8.2 with the change to `$bom=false`. Any text that looks like a URI is linked, any text that has an <a> tag is not linked.

**Comment by seanmadrid** [comment]
> I'm having this issue, and can confirm I am using 0.8.2 with the change to `$bom=false`. Any text that looks like a URI is linked, any text that has an `<a>` tag is not linked.
> 
> On further investigation: this appears to be a new bug, as it affects 0.8.2 and 0.8.4 as well, with variable results depending on the structure of the `<a>` tag being rendered.

I am still experiencing this issue. Does anyone have a fix for this?

**Comment by bsweeney** [comment]
@seanmadrid please open a new issue or start a discussion so that we can get more details on your particular use case.
