### ISSUE TITLE
<p></p> or <p>&nbsp;</p> Are both ignored

### ISSUE THREAD

**Issue by MichaelEugeneYuen** [dompdf/dompdf#1561]
Can we use `<p></p>` or `<p>&nbsp;</p>`to create a line-break?
I know I can use `<br>` or `<br />` but since I am working this with TINYMCE editor, I need to find a way to work around it. Coz every carriage return will create a new `<p></p>`. Will need to use SHIFT + ENTER to insert `<br>` as alternative.

Example:
![akg](https://user-images.githubusercontent.com/25918819/31048149-12ae22b6-a64a-11e7-972f-42d3fd3d69f0.jpg)

**Comment by bsweeney** [comment]
Which version of Dompdf are you using?

**Comment by MichaelEugeneYuen** [comment]
I am using dompdf_0-8-1

**Comment by bsweeney** [comment]
I'm not seeing this with `<p>&nbsp;</p>`, but I can confirm with an empty P. We'll look into it.

**Comment by MichaelEugeneYuen** [comment]
Thanks

![akg](https://user-images.githubusercontent.com/25918819/31234293-212b4abe-aa21-11e7-978d-f8bdd2a2dadc.jpg)

**Comment by bsweeney** [comment]
Still not seeing it with `&nbsp;`. Maybe with that element it has something to do with your styling?

**Comment by MichaelEugeneYuen** [comment]
Just did some tests, and narrow down the problem:

<p>&nbsp;</p>don't seem to have any effect after I applied

* {
margin: 0;
}

**Comment by bsweeney** [comment]
The issue with `&nbsp;` may have been resolved with 0.8.3. Previous versions were treating those as regular spaced in some situations. So using `&nbsp;` in empty P element may be the best work around for now.

**Comment by dani-sanomads** [comment]
@Mellthas , @bsweeney What about the <a></a> tag. It does not use the &nbsp; properly.
![Screenshot 2023-05-23 at 11 54 29 AM](https://github.com/dompdf/dompdf/assets/101345208/8c150d9e-6c63-480e-91de-dc9ce4468f8e)

**Comment by bsweeney** [comment]
@dani-sanomads seems different from this issue, please [start a discussion](https://github.com/dompdf/dompdf/discussions/new/choose) so we can determine if there's an issue to address.
