### ISSUE TITLE
Call to undefined method DOMDocument::hasAttribute

### ISSUE THREAD

**Issue by Divxtaman** [dompdf/dompdf#1563]
**error**
Fatal error: Call to undefined method DOMDocument::hasAttribute() in dompdf/src/Css/Stylesheet.php on line 970
**html template**
```
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.css" crossorigin="anonymous">
</head>
<body>
    <div class="container">
      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
      </div>
    </div>
</body>
</html>
```
Does bootstrap works with this library?

**Comment by Divxtaman** [comment]
fixed by removing in bootstrap.css
```
.custom-file-control:lang(en)::before {
  content: "Browse";
}
```

**Comment by bsweeney** [comment]
Dompdf does work with Bootstrap ... conceptually. Something we changed with 0.8.1 seems to have broken rendering with Bootstrap 4. Until 0.8.2 you can use 0.8.0.

Relevant to #1551.
