### ISSUE TITLE
url(), absolute_url(), asset() not working in Twig+Symfony

### ISSUE THREAD

**Issue by ThomasLandauer** [dompdf/dompdf#1567]
When I link to an URL or asset, as I normally do it in Twig, it's not working in dompdf-generated PDF's. Is this an issue? Or is there another way to do it?

**Comment by ThomasLandauer** [comment]
I'm not sure.

I already observed this in version 0.8.0. And I don't know what "external link" means in the other ticket. I wouldn't call an asset in my own `web` directory an external link....

**Comment by bsweeney** [comment]
That issue is about links to other documents, i.e. `<a href="http://example.com">example.com</a>`.

**Comment by ThomasLandauer** [comment]
I'm talking about links to assets: `<img src="{{ asset('logo.svg') }}">` and full URL's to internal paths: `<a href="{{ absolute_url(path('Login')) }}">`

Both don't seem to be working, and I'm wondering if this is a bug, if there's a workaround, or if it just isn't expected to work that way ;-)

**Comment by bsweeney** [comment]
I'm not sure about hrefs in 0.8.0. Seems to be fine. What do you get for that?

I guess the question is what is going wrong? Links not working, assets not displaying?

Can you call `output_html` so we can see what's being rendered?

**Comment by ThomasLandauer** [comment]
Sorry for being so imprecise this time. Now I investigated this more thoroughly. I'm experiencing two separate issues:

* Twig's `asset('foo')` creates a link to `/foo`, whereas dompdf only works when the link is `foo`. So it looks like `asset()` is just not compatible with dompdf.

* The `absolute_url()` aspect has nothing to do with the address string itself, but looks related to https://github.com/dompdf/dompdf/issues/1390 - i.e. the "hot" area of the link is not quite where I would have expected it.

**Comment by bsweeney** [comment]
No worries, so long as we get where we need to go eventually.

For your asset issue see #144 / #1370.

**Comment by hidestars** [comment]
Got something like that in my code, but i fixed it like that :

**Comment by hidestars** [comment]
Btw im using 0.8.0 version of dompdf, PHP 7.0.18 and Symfony 3.3.10

**Comment by ThomasLandauer** [comment]
@MaximeDetaille Thanks, but it's not working for me :-(

@bsweeney Can it be that even `<img src="logo.svg">` is just not working on a dev machine (i.e. localhost)? On the live server, the same code works, in any environment.

So maybe the entire issue is not about Twig's `asset()`, but about localhost urls in general?

**Comment by ThomasLandauer** [comment]
Just found out that the reason probably is that the resolved full url `http://localhost/app_dev.php/logo.svg` is not working on my dev machine, due to the `app_dev.php` part (Symfony 3.4). I'm not investigating this further now, since these urls will change in Symfony 4 anyway.

**Comment by mathieumuller** [comment]
I solved the problem remomving the first '/' of the relative url generated by the asset function: 

```twig
<img src="{{ asset('my-image.png')[1:] }}"/>
```

It works for stylesheets too.

**Comment by bsweeney** [comment]
Thanks for the follow-up. That is ... unfortunate ... about the URL generated by those methods. I believe there's a way to make that work (I've done so in the past) but I'd have to research it. Something related to the "path_info" server variable.

**Comment by ThomasLandauer** [comment]
When generating the PDF from a Symfony CLI command, you need to set `base_path`: https://symfony.com/doc/current/reference/configuration/framework.html#base-path
