### ISSUE TITLE
The first radiobutton after a pagebreak is doubled, so 2 next to each other

### ISSUE THREAD

**Issue by Paul9321Appsoftware** [dompdf/dompdf#1568]
When creating a PDF from a html string with many radiobuttons every first radio button on a new page is doubled up, so instead of 1 radio there are 2 next to each other. On some pages the first 4 rows are doubled.

![double_radios1](https://user-images.githubusercontent.com/15029599/31179687-e4939f34-a91c-11e7-97f7-ec9031eb5583.PNG)

![double_radios](https://user-images.githubusercontent.com/15029599/31179618-b6024e72-a91c-11e7-8398-2e146f1fadc6.PNG)

**Comment by bsweeney** [comment]
This was addressed in 0.8.1. See #1404.
