### ISSUE TITLE
Content overflows and hidden 

### ISSUE THREAD

**Issue by Youv** [dompdf/dompdf#1577]
In my laravel view file i can see the full width view, but in my PDF file, the content is hidden at right hand side.How to display the hidden content in fullwidth.

Thanks

**Comment by Inamacio** [comment]
I am facing the same problem

**Comment by bsweeney** [comment]
Do you have a sample of the HTML+CSS causing the issue?

**Comment by Inamacio** [comment]
Follow the listed files

I can generate a pdf with up to 10 columns, however, with more this cuts the content. I've tried using 100% width, but when the content is too much, the view is impaired

[pdf.zip](https://github.com/dompdf/dompdf/files/1540211/pdf.zip)

**Comment by Inamacio** [comment]
I'm using laravel with blade files

**Comment by brada1703** [comment]
Has anyone been able to solve this?

I have tried overflow:hidden on the pages but that seems to do nothing. Then, I also tried position:absolute, which was a suggestions [elsewhere](https://www.princexml.com/forum/topic/2621/prevent-pagebreak-when-text-overflows), but even with the top stated on each page, it still just left me with 1 page.

Any help would be appreciated.

Thanks!

**Comment by brada1703** [comment]
I think I've found the solution! Thanks to BrianS, whoever you are!

Here is the [original link](https://groups.google.com/forum/#!topic/dompdf/L4-yyZD0qSo). 

Just in case it goes down, I'll copy the HTML here:

```
<html>
    <head>
      <style>
        div.page { position: absolute; top: 0px bottom: 0px; left: 0px; right: 0px; width: 100%; height: 100%; overflow: hidden; page-break-before: always; }
        div.page:first-child { page-break-before: never; }
      </style>
    </head>
    <body>
      <div class="page">
        ...
      </div>
      <div class="page">
        ...
      </div>
    </body>
</html>
```

I hope this helps someone!

Good luck 🤓
