### ISSUE TITLE
PHP Fatal error:Uncaught Dompdf\Exception: No block-level parent found.  Not good. in D:\Parallels\Plesk Panel\Vhosts\mydomain.co.uk\httpdocs\tools\dompdf\src\Positioner\Inline.php:48

### ISSUE THREAD

**Issue by SJDComputerslimited** [dompdf/dompdf#1582]
Hello I am getting the below errors can anyone help?

PHP Fatal error:  Uncaught Dompdf\Exception: No block-level parent found.  Not good. in D:\Parallels\Plesk Panel\Vhosts\mydomain.co.uk\httpdocs\tools\dompdf\src\Positioner\Inline.php:48
Stack trace:
#0 D:\Parallels\Plesk Panel\Vhosts\live-tracking.co.uk\httpdocs\tools\dompdf\src\FrameDecorator\AbstractFrameDecorator.php(788): Dompdf\Positioner\Inline->position()
#1 D:\Parallels\Plesk Panel\Vhosts\live-tracking.co.uk\httpdocs\tools\dompdf\src\FrameReflower\Text.php(360): Dompdf\FrameDecorator\AbstractFrameDecorator->position()
#2 D:\Parallels\Plesk Panel\Vhosts\live-tracking.co.uk\httpdocs\tools\dompdf\src\FrameDecorator\AbstractFrameDecorator.php(801): Dompdf\FrameReflower\Text->reflow(NULL)
#3 D:\Parallels\Plesk Panel\Vhosts\live-tracking.co.uk\httpdocs\tools\dompdf\src\FrameReflower\Page.php(133): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#4 D:\Parallels\Plesk Panel\Vhosts\live-tracking.co.uk\httpdocs\tools\dompdf\src\FrameDecorator\AbstractFrameDecorator.php(801): Dompdf\FrameReflower\Page->reflow(NULL)
#5 in D:\Parallels\Plesk Panel\Vhosts\live-tracking.co.uk\httpdocs\tools\dompdf\src\Positioner\Inline.php on line 48

**Comment by PheRum** [comment]
@bsweeney update version please

**Comment by SJDComputerslimited** [comment]
using the latest version 8.01, I have noticed should I drop php to 5.6.3 from 7.01 it works fine, just doesnt like php 7 ive figured out

code were using for creating pdfs is,

<?
        require_once '../tools/dompdf/autoload.inc.php';
        
        // reference the Dompdf namespace
        use Dompdf\Dompdf;
        use Dompdf\Options;
                
        function html2pdf($html)
        {                 
                $options = new Options();
                $options -> set('isRemoteEnabled', true);
                $options -> set('dpi', '128');
                
                $dompdf = new Dompdf($options);
                
                $dompdf->loadHtml($html);
                
                // (Optional) Setup the paper size and orientation
                $dompdf->setPaper('A4', 'landscape');
                
                // Render the HTML as PDF
                $dompdf->render();
                
                $result = $dompdf->output();
                                
                return $result;
        }
?>

**Comment by PheRum** [comment]
@SJDComputerslimited fix this https://github.com/dompdf/dompdf/commit/ad41b6dd17ba774b017407ffba09c14a66665723

**Comment by Bored0ne** [comment]
@bsweeney would love for this fix to get released! Also thanks for all the hard work!

**Comment by bsweeney** [comment]
The patch for this is now on the master branch. Look for the 0.8.2 release (coming soon).

**Comment by nadiyaparaamit** [comment]
Remove <thead> and <tbody> tags 
and remove space from <html><head> , </head><body> and </body></html>

It will work fine.!

**Comment by novitalia28** [comment]
Thank you @nadiyaparaamit, its work for me!

**Comment by delyteja** [comment]
Thank you @nadiyaparaamit , its work

**Comment by gianniskar** [comment]
Hi.Where is these tags?I mean in which html file(location?)

**Comment by nadiyaparaamit** [comment]
Generating PDF from HTML, On that HTML code we need remove those tags.

**Comment by gianniskar** [comment]
I do it that but now i have this error Fatal error: Uncaught Error: Call to a member function getData() on null
