### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by paddelboot** [dompdf/dompdf#1591]
I today updated dompdf via composer, and now the links in my generated PDFs are broken.

While updating, composer said that the files in the package had changed. I have no idea what this is, since I don't edit files of any composer package. I therefore chose to discard changes and run the update.

Any clues? Thanks.

**Comment by skerbis** [comment]
same problem here after update to 0.8.1 don't know why: https://github.com/FriendsOfREDAXO/pdfout/issues/17 . it seems not to be a php version problem because on my testing systems it works nice under 7.0.x and 7.1x

**Comment by skerbis** [comment]
I think I found the problem and solution: https://github.com/dompdf/dompdf/issues/1559

**Comment by paddelboot** [comment]
I rolled back to 0.7.

**Comment by paddelboot** [comment]
Now with 0.7.0, the layout of my PDFs is messed up. So I removed that too and went to 0.7.0-beta3. This one crashes with a fatal error which seems to come from a namespace issue. Is there any version ready for production? I was under the impression I was using 0.7.0 before, but apparently not.

**Comment by bsweeney** [comment]
The patch for this is now on the master branch. Look for the 0.8.2 release (coming soon).
