### ISSUE TITLE
page total 

### ISSUE THREAD

**Issue by pascaldls** [dompdf/dompdf#1595]
How to print total number of pages to each page such as 
pageNumber / Pages 
pageNumber of Pages

**Comment by crafack** [comment]
I do it _outside_ the HTML, after rendering the page. Here is a snippet of code:

```
//...
// Parse the page
$dompdf->loadHtml($page);
// Render the HTML as PDF
$dompdf->render();

// Page numbering
// Prepare font
$font = $dompdf->getFontMetrics()->get_font("Verdana", "");
// Print page numbering string at pos (500,118) on page, using $font in size 10
$dompdf->getCanvas()->page_text(500, 118, "Page {PAGE_NUM} of {PAGE_COUNT}", $font, 10, array(0,0,0));

// Output the generated PDF to Browser
$dompdf->stream($filename);
```

**Comment by PowerKiKi** [comment]
See https://github.com/dompdf/dompdf/issues/1636#issuecomment-490372233 for a proper way to get current and total page and be able to style everything via CSS as usual.
