### ISSUE TITLE
Compound/double class selector not working?

### ISSUE THREAD

**Issue by godbout** [dompdf/dompdf#1596]
I can't find much information on whether it is supported or not, sorry. Someone could confirm whether it is not or whether I'm making a mistake somewhere?

This is what I have:

CSS
```
.hero.is-dark {
    background-color: #363636;
    color: whitesmoke;
}
```

HTML
```
<div class="hero is-dark">
    <h1>Trying to get some shit done</h1>
</div>
```

`.hero.is-dark` is not recognized when I generate the PDF, but works fine when I dump the normal view. If I remove `.is-dark` the class is applied (but of course my whole CSS contains a lots of those multiple classes, and therefore don't work).

Thanks!

**Comment by Mellthas** [comment]
This seems to work just fine, even with older versions. Please reopen with more information if you still encounter this issue.

**Comment by bsweeney** [comment]
Earliest version I found where the specific example didn't quite work was 0.5.1 but that was also because the specified color wasn't supported.

**Comment by godbout** [comment]
thanks i solved this yesterday.
