### ISSUE TITLE
DomPDF 0.8.1 require PHP 5.4.0 (or more), please update your document

### ISSUE THREAD

**Issue by vanthuanqs** [dompdf/dompdf#1597]
https://github.com/dompdf/dompdf/blob/caedb7feb746866fcb40f4925dd49e2ebebf47e7/lib/Cpdf.php#L2072

This class call hex2bin function, but this function is declared sine PHP 5.4.0
Please update documents:
https://github.com/dompdf/dompdf#requirements
https://packagist.org/packages/dompdf/dompdf#v0.8.1

**Comment by bsweeney** [comment]
Good catch. We'll update the documentation and composer config.
