### ISSUE TITLE
Does the render time increase exponentially with the amount of pages ?

### ISSUE THREAD

**Issue by Mimiste** [dompdf/dompdf#1598]
Hello 

I have some problems here with the rendering of a big PDF document.
The document is composed of multiples chapters in html, coming from a database.
Each chapters can have a lot of pages (from 50 to 300)
If I try to render the full document, the process never finish... Or it will eventually finish in days, month, I dont know..

But I tried something like this : 

If I render 3 chapters only, It will take somethings like 40 minutes to render.
If I separately render the same 3 chapters It takes 1 minute for the first, 4 minutes for the chapter 2 and 10 minutes for chapter 3. So a total of 15 minutes.
Is this a normal behavior of the PDF format ? Like the more there are pages, the more it's hard for dompdf to add pages ? 

Thanks :)

**Comment by NirmalBalajiTU** [comment]
dompdf render taking too long to generate  ->  is there any other way ?
