### ISSUE TITLE
Class 'Sabberworm\CSS\Parser' not found when using SVG

### ISSUE THREAD

**Issue by marcovdb** [dompdf/dompdf#1601]
- dompdf version: 0.8.1
- Apache: 2.4.27
- PHP: 7.1.9

When using an SVG image inside of my HTML, like so: `<img src="foo.svg">`, I get the following error message:

```
Uncaught Error: Class 'Sabberworm\CSS\Parser' not found in C:\wamp64\www\proj\lib\dompdf\lib\php-svg-lib\src\Svg\Tag\StyleTag.php:19
Stack trace:
#0 C:\wamp64\www\proj\lib\dompdf\lib\php-svg-lib\src\Svg\Tag\AbstractTag.php(70): Svg\Tag\StyleTag-&gt;end()
#1 C:\wamp64\www\proj\lib\dompdf\lib\php-svg-lib\src\Svg\Document.php(400): Svg\Tag\AbstractTag-&gt;handleEnd()
#2 [internal function]: Svg\Document-&gt;_tagEnd(Resource id #73, 'style')
#3 C:\wamp64\www\proj\lib\dompdf\lib\php-svg-lib\src\Svg\Document.php(223): xml_parse(Resource id #73, '&lt;!-- Generator:...', false)
#4 C:\wamp64\www\proj\lib\dompdf\lib\Cpdf.php(5041): Svg\Document-&gt;render(Object(Svg\Surface\SurfaceCpdf))
#5 C:\wamp64\www\proj\lib\dompdf\src\Adapter\CPDF.php(850): Cpdf-&gt;addSvgFromFile('C:\\wamp64\\www\\c...', 24, 768.84, 49.05, 49.05)
#6 C:\wamp64\www\proj\lib\dompdf\src\Renderer\Image.php(110): Dompdf\Adapter\CPDF-&gt;image('C:\\wamp64\\www\\c...', 24, 24, 49.05, 49.05, 'normal')
#7 C:\wamp64\www\proj\lib\dompdf\src\Rende in <b>C:\wamp64\www\proj\lib\dompdf\lib\php-svg-lib\src\Svg\Tag\StyleTag.php</b> on line <b>19</b><br />
```

I realize this is probably because I am a simple man who does not use composer (so the Sabberworm CSS parser does not get installed), but the release version of dompdf does promise that it comes with all necessary dependencies.

**Comment by bsweeney** [comment]
When using composer all the dependencies will be installed by composer. If you download the packaged version of Dompdf all the dependencies _should_ be included. But I just checked and that dependency is currently _not_ in the packaged download. We'll fix that with the next release.

**Comment by bsweeney** [comment]
The 0.8.2 release is ready. If you're using the packaged version try downloading this release and see if you're issue is resolved.

**Comment by marcovdb** [comment]
Thanks. I can confirm the issue is fixed in 0.8.2!

**Comment by rmpel** [comment]
I report issue NOT fixed in 0.8.2.

Dompdf 0.8.2
php-svg-lib 0.3
php-font-lib 0.5.1

I will attempt with "packaged version" instead of separate git clones.

**Comment by rmpel** [comment]
Solution is simple: do not use git clone method; the documentation here lacks the part for the CSS parser, also, you will be missing the autoload.inc.php that loads all the stuff, so don't do what I did, but use the packaged version! That one works perfectly :)

**Comment by bsweeney** [comment]
@rmpel indeed you should use the packaged version or composer if possible. We do need to do a bit of work around the documentation. I moved out the autoload.inc.php since it's more an add-on for the packaged version.

**Comment by BrightCodeStudio** [comment]
Fatal error: Class 'Sabberworm\CSS\Parser' not found in G:\www\html2pdf\dompdf\dompdf\lib\php-svg-lib\src\Svg\Tag\StyleTag.php on line 19

Now I am using the libraries
Dompdf 0.8.2
php-svg-lib 0.3
php-font-lib 0.5.1

But I got this errors.
