### ISSUE TITLE
tempnam returns false in centos

### ISSUE THREAD

**Issue by nicdnepr** [dompdf/dompdf#1602]
In centos 6.8 https://github.com/dompdf/dompdf/blob/master/src/Image/Cache.php#L91 always return false, maybe because of PrivateTmp=true

**Comment by bsweeney** [comment]
I believe #842 would address the issue.

**Comment by bsweeney** [comment]
Just FYI, that code isn't yet integrated. We will include it for the 0.9.0 release and maybe before then in one of the intermediate releases.

**Comment by npoa-cm** [comment]
Any update here? Can't get DomPDF to work on PHP 7.1....
