### ISSUE TITLE
Page break handling inside tables incorrect

### ISSUE THREAD

**Issue by PDFCoder** [dompdf/dompdf#1603]
It seems that the new improved page break handling inside tables (since version 0.8.1) has some bugs. Sometimes a row breaks to the next page (let's say page 2) although there is enough space left on the page (page 1). And the rest of the new page (page 2) is blank; the next rows of the table appear on page 3.

Perhaps the available/remaining space of the page is not calulated properly? If I change the code of FrameDecorator/Page.php back to version 0.8.0 the „old“ handling is correct and better here …

I use dompdf 0.8.1 with pdflib adapter.

**Comment by SeanFacer** [comment]
Also struggling with this

**Comment by dragermrb** [comment]
Same here!

**Comment by casperbakker** [comment]
Same here

**Comment by Inamacio** [comment]
Same here!

**Comment by Mellthas** [comment]
Had a shot a the bug, see #1616. Would be great if anyone could check how their real-life documents render with the changes, in particular if the changes break anything else.

**Comment by dragermrb** [comment]
Hi @Mellthas 

Your PR is working correctly with my documents. Thanks!

**Comment by crafack** [comment]
Hi @Mellthas,

Your PR fixes the pagination errors in my documents. Thanks a lot for this!

**Comment by tmbdrogba** [comment]
The PR works great! Bug fixed ^^

**Comment by casperbakker** [comment]
@bsweeney Any change you could merge that PR and release a new version?

**Comment by casperbakker** [comment]
Awesome @bsweeney!

**Comment by bsweeney** [comment]
Sorry for the delay ... took a bit longer than I was hoping. But I guess that's the theme of the project 😞

**Comment by casperbakker** [comment]
Don't stress about it, that is how open source projects go sometimes. Still one of the best PDF builders for PHP! Keep up the good work, it is much appreciated.
