### ISSUE TITLE
touch() function fails to create file

### ISSUE THREAD

**Issue by phiter** [dompdf/dompdf#1606]
Hi, I'm using laravel and the plugin [laravel-dompdf by barryvdh](https://github.com/barryvdh/laravel-dompdf).

I'm having trouble creating a pdf file.

This is the error message I'm getting:

> (1/1) ErrorExceptiontouch(): Unable to create file C:\WINDOWS\TEMP\log.htm because Too many open files
> --
> in Dompdf.php (line 710)
> at HandleExceptions->handleError(2, 'touch(): Unable to create file C:\\WINDOWS\\TEMP\\log.htm because Too many open files', 'C:\\wamp\\www\\sistograf_novo\\vendor\\dompdf\\dompdf\\src\\Dompdf.php', 710, array('options' => object(Options), 'logOutputFile' => 'C:\\WINDOWS\\TEMP\\log.htm'))
> at touch('C:\\WINDOWS\\TEMP\\log.htm')in Dompdf.php (line 710)
> at Dompdf->render()in PDF.php (line 200)
> at PDF->render()in PDF.php (line 146)
> at PDF->output()in PDF.php (line 183)
> 
> 

I have no idea why, of course. It was working before and after I changed nothing, it stopped working. 

I'm using WAMP Server and PHP 7.1.9

**Comment by bsweeney** [comment]
I haven't had anyone run into this issue before. Is this after running for a period of time or does it always happen? If you restart your services do you still get the error?

**Comment by phiterf** [comment]
I had tried multiple times and the error was persisting. Now after 5 hours I've tried again and the error didn't happen.

**Comment by bsweeney** [comment]
Hm ... could be that the PHP process had hung and wasn't able to release some file handles. Let us know if you run into the issue again.

**Comment by WOEXX** [comment]
i'm having same issue, im using ubuntu and apache

**Comment by bsweeney** [comment]
@WOEXX unless you're getting the same error message you might want to open a separate ticket. Since the OS is different it's probably a different kind of issue.

First thing you might try is specifying a different temp directory.

```
$dompdf->set_option('tempDir', '...');
```

(where "..." is a path writable by the process running dompdf)
