### ISSUE TITLE
small size and split pdf

### ISSUE THREAD

**Issue by nicdnepr** [dompdf/dompdf#1609]
If I set small size in html like `size: 100px; 100px;"` and insert text and image in html the result pdf split into 2 pdf, in firts pdf text, in second image
Is it bug?
![0](https://user-images.githubusercontent.com/2581487/33526279-505b1f04-d847-11e7-9ef0-a57af153a7e3.png)

**Comment by bsweeney** [comment]
Can you provide more of the HTML+CSS that's resulting in that PDF?

**Comment by nicdnepr** [comment]
here is html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        @page {
            size: 100px; 100px;
            margin: 0px;
            padding: 0px;
        }
        body {
            margin: 0px;
        }
    </style>
</head>
<body>

<div>
    text
</div>
<div>
    <img src="http://informat.in.ua/images/Paint.Paint_9B19/4_fraktal3608ab310dc594c738706a02f4962899f.jpg" style='max-width: 100%;'>
</div>

</body>
</html>
```

php
```
$dompdf = new \Dompdf\Dompdf([
    'enable_remote' => true,
]);

$html = file_get_contents('11.html');

$dompdf->loadHtml($html);
$dompdf->render();

file_put_contents('xxx.pdf', $dompdf->output());
```

**Comment by bsweeney** [comment]
That looks about right. I mean, a 100x100 px page size will render about that big. There are some boundary issues in dompdf with elements that bump up against the page margins. If you need this to be a single page then you could wrap the whole thing in an absolutely-positioned DIV.

**Comment by nicdnepr** [comment]
I try this code but not help
```
<div>
<div>
    text
</div>
<div>
    <img src="http://informat.in.ua/images/Paint.Paint_9B19/4_fraktal3608ab310dc594c738706a02f4962899f.jpg" style='max-width: 100%;'>
</div>
</div>
```

also I try this size `size: 200px; 50px;` and it render single page, but why it show white line in bottom?
![1](https://user-images.githubusercontent.com/2581487/33527268-6fa563c4-d856-11e7-96ac-e6c538d93c6a.png)

**Comment by bsweeney** [comment]
Your size declaration isn't right. No semi-colon between the values. Should be something like

```
@page {
  size: 200px 50px;
}
```

The bottom space is because you haven't filled to the bottom of the page. If what you want is some text in the top portion and the image in the bottom portion you can position each separately.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        @page {
            size: 100px; 100px;
            margin: 0px;
            padding: 0px;
        }
        body {
            margin: 0px;
        }
    </style>
</head>
<body>

<div style="position: absolute; top: 0px; left: 0px; right: 0px;">
    text
</div>
<div style="position: absolute: bottom: 0px; left: 0px; right; 0px;">
    <img src="http://informat.in.ua/images/Paint.Paint_9B19/4_fraktal3608ab310dc594c738706a02f4962899f.jpg" style='max-width: 100%;'>
</div>

</body>
</html>
```

**Comment by nicdnepr** [comment]
thanks I fixed size
But still not clear about white bottom line
for example `size: 200px 169px;` I get this pdf
![0](https://user-images.githubusercontent.com/2581487/33527977-77a6a9f0-d862-11e7-91e4-61e70a6f2c79.png)
`size: 200px 170px;` I get this pdf
![1](https://user-images.githubusercontent.com/2581487/33527978-7d38b962-d862-11e7-89cf-563a69830f37.png)

In both bottom white line
Why it not fill whole pdf by image?

**Comment by bsweeney** [comment]
My sample had a typo. I edited the comment so it is now correct.

**Comment by nicdnepr** [comment]
What about situation when only image without text?
```
<div style="position: absolute; bottom: 0px; left: 0px; right: 0px;">
    <img src="http://informat.in.ua/images/Paint.Paint_9B19/4_fraktal3608ab310dc594c738706a02f4962899f.jpg" style='max-width: 100%;'>
</div>
```
now I get empty line on top
![0](https://user-images.githubusercontent.com/2581487/33528587-be7609a8-d86b-11e7-978a-f5656e1c3c41.png)
If I remove styles then I get empty line bottom

**Comment by bsweeney** [comment]
That situation is a bit more difficult. Dompdf does not yet fully support the CSS that would make this simple to do. You have a few options:

 1. Make the page size the same as the image;
 2. Set the height _and_ width to 100%. This will distort the image if it's not the same ratio as the page
 3. Set the height _or_ width to 100% such that the image will fit the page. This will crop the image if it's not the same ratio as the page.

There are also some issues around how Dompdf deals with `max-` styling as well as `height` styling on an element that doesn't specify a height (e.g. if the height is a percentage or set to auto).

So, a lot of caveats. But using 200x160 for the page size seems to work well:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        @page {
            size: 200px 169px;
            margin: 0px;
            padding: 0px;
        }
        body {
            margin: 0px;
        }
    </style>
</head>
<body>

<div style="position: absolute; bottom: 0px; left: 0px; right; 0px; top: 0px;">
    <img src="http://informat.in.ua/images/Paint.Paint_9B19/4_fraktal3608ab310dc594c738706a02f4962899f.jpg" style='height: 169px;'>
</div>

</body>
</html>
```

**Comment by bsweeney** [comment]
FYI you could now do this using a background image styled to "cover" the space:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        @page {
            size: 100px 75px;
            margin: 0px;
            padding: 0px;
        }
        body {
            margin: 0px;
            background-image: url(http://placekitten.com/100/75);
            background-size: cover;
        }
    </style>
</head>
<body>

</body>
</html>
```

or, if you didn't want to lose image resolution (background images are re-rendered at the indicated sizing):

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        @page {
            size: 100px 75px;
            margin: 0px;
            padding: 0px;
        }
        body {
            margin: 0px;
        }
    </style>
</head>
<body>

    <img src="http://placekitten.com/500/375" style="width: 100%; height: 100%;">

</body>
</html>
```
