### ISSUE TITLE
chinese fonts

### ISSUE THREAD

**Issue by nicdnepr** [dompdf/dompdf#1610]
I generate pdf with chinese and english words and set this font
```
* {
font-family: Firefly Sung, DejaVu Sans, sans-serif;
}
```
I test it local on ubuntu and it works
Then I test on server with centos and there get error
`Uncaught exception 'FontLib\\Exception\\FontNotFoundException' with message 'Font not found in: /tmp/9ad7bbf1f98835f4d47a36016ca5af9d.ttf.tmp.5a255585822e1' in /Lib/Action/pdf/PDFbyK/vendor/phenx/php-font-lib/src/FontLib/Font.php:28\nStack trace:\n#0 /Lib/Action/pdf/PDFbyK/vendor/dompdf/dompdf/lib/Cpdf.php(2843): FontLib\\Font::load('/tmp/9ad7bbf1f9...')\n#1 /Lib/Action/pdf/PDFbyK/vendor/dompdf/dompdf/src/Adapter/CPDF.php(987): Cpdf->selectFont('/var/ho...')\n#2 /Lib/Action/pdf/PDFbyK/vendor/dompdf/dompdf/src/FontMetrics.php(309): Dompdf\\Adapter\\CPDF->get_font_height('/var/ho...', 12)\n#3 /Lib/Action/pdf/PDFbyK/vendor/dompdf/dompdf/src/FrameReflower/Text.php(197): Dompdf\\FontMetrics->getFontHeight('/var/ho...', 12)\n#4 /Lib/Actio in /Lib/Action/pdf/PDFbyK/vendor/phenx/php-font-lib/src/FontLib/Font.php on line 28, `

then I try this
```
@font-face {
font-family: 'Firefly Sung';
font-style: normal;
font-weight: 400;
src: url(http://eclecticgeek.com/dompdf/fonts/cjk/fireflysung.ttf) format('truetype');
}
* {
font-family: Firefly Sung, DejaVu Sans, sans-serif;
}
```
local ubuntu works, but centos dont work
Local ubuntu I didnt install any fonts
dompdf last version from composer

**Comment by bsweeney** [comment]
Does the process running PHP have read/write access to /tmp directory?

**Comment by nicdnepr** [comment]
Yes, pdf is generated. but only chinese fonts are broken

**Comment by nicdnepr** [comment]
Here is info or result pdf
centos6 https://imgur.com/a/7Sy1i
centos7 https://imgur.com/a/QcpYg

**Comment by nicdnepr** [comment]
the problem was in meta charset
need use `<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>` instead of this code `<meta charset="utf-8">`
