### ISSUE TITLE
Svg rendering

### ISSUE THREAD

**Issue by usb248** [dompdf/dompdf#1612]
Since new release, svg are not displayed ....

My code : 
`<img src="/img/logo-burger-baseline.svg" alt="#" class="inbl" width="170"/>`
(before release, everything was working properly).

i have a strange square displayed instead of my logo.

someone have the same issue ?

**Comment by bsweeney** [comment]
How are you installing Dompdf? Do you have a sample of the SVG we can use for testing?

**Comment by usb248** [comment]
Via include autoload file : `autoload.inc.php`
and output browser through `$dompdf->stream('my-file',['Attachment' => false]);`

```
$dompdf = new DOMPDF();
$dompdf->set_option('defaultFont', 'Helvetica');
$dompdf->set_option('enable_php', true);
$dompdf->set_option('enable_remote', true);
$dompdf->setPaper('A4');
$dompdf->set_protocol(my_root_directory);
$dompdf->load_html(my_html_content);
$dompdf->render();
echo $dompdf->stream('output file name',['Attachment' => false]);
```

Yes, download link : https://ufile.io/6gq82

waiting for a return from you

**Comment by bsweeney** [comment]
I am seeing the same starting with 0.8.1. I'm not seeing any errors so I don't have much advice just yet. I'm not sure if the issue is related to updating php-svg-lib from 0.2 to 0.3 or if there's something else going on. Other SVG images render OK.

I'll leave this open while we investigate the Dompdf side, but you should also post a bug to the [php-svg-lib project](https://github.com/PhenX/php-svg-lib).

So you're using the packaged version of Dompdf? You could always drop-in replace the version of php-svg-lib to work around the issue for now (assuming that's the source).

**Comment by hakimio** [comment]
Have you tried setting both - width and height for the image?

**Comment by usb248** [comment]
Not yet, but before, just with the width it worked... So, there is no reason for it not to work now.

**Comment by hakimio** [comment]
The only change in php-svg-lib v0.3 is the following:
https://github.com/PhenX/php-svg-lib/commit/0a9869529a2a5f0bee31ba905bdc39962eba1025

If reverting it doesn't help, most likely php-svg-lib is not the problem.

**Comment by usb248** [comment]
Still broken (even with width and height for the image)...any fix...  So, i will use other lib to generate pdf file :( 👎

**Comment by sforsberg** [comment]
I encountered a similar rendering issue with an svg that had a style tag in a defs tag. I confirmed v0.8.0 worked still, however starting at v0.8.1 the svg rendering broke. The image was there, but the styles defined weren't applied to the final image. Maybe the parent document styles aren't inherited into the SVG rendering? And/or `currentColor` is no longer handled properly?

Example SVG:
```
<svg xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" id="Layer_1" data-name="Layer 1" viewBox="0 0 167.27 167.17">
	<defs>
		<style>path{fill: currentColor;}</style>
	</defs>
	<path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
</svg>
```

The only way to get the latest version to render the svg was to specify a fill color and move the style tag a a root-level node: 
```
<defs>
        <style>path{fill: currentColor;}</style>
</defs>
```

Changed to:
```
<style>path{fill: black;}</style>
```

But this limits the fill to a static color so it isn't ideal, but will likely be what we end up doing to move forward.

The html that was parsed by dompdf looked like this:
```
...
<img class="bcLogo" src="/local/absolute/path/to/image.svg" />
...
```

Hopefully this helps in some way...

**Comment by EArminjon** [comment]
your solution work, but the scale of svg no longer works with that.

**Comment by vielhuber** [comment]
Any update on this?

This gets rendered in 0.8.1 and onwards:
[1.zip](https://github.com/dompdf/dompdf/files/3259047/1.zip)

This doesnt:
[2.zip](https://github.com/dompdf/dompdf/files/3259049/2.zip)

In 0.8.0 both render perfectly well.

**Comment by vielhuber** [comment]
For anybody struggling with this:

Replace
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 79.02 55.93">

with
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 79.02 55.93" fill="#000000">

and everything works!

**Comment by bsweeney** [comment]
This looks to be an issue with php-svg-lib. I'm not sure what happened with that last release but it looks like whatever changes caused the default fill to no longer apply. An issue should be opened with that project.
https://github.com/PhenX/php-svg-lib/issues/new

**Comment by lov2code** [comment]
I searched FOREVER until I finally came up with my own solution. I thought I should share in case it could be useful to anyone else. If you are using **PHP** the best solution to inline SVG images (for me) is to output it using **BASE64_ENCODE()** on the actual svg, then wrapping it in an image using the src as follows:

```
$svg = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 36 36" class="circular-chart">
    <path class="circle-bg"
          stroke-width="1"
          fill="none"
          stroke="#ddd"
          d="M18 2.0845
             a 15.9155 15.9155 0 0 1 0 31.831
             a 15.9155 15.9155 0 0 1 0 -31.831"
          />
</svg>';

$html = '<img src="data:image/svg+xml;base64,'.base64_encode($svg).'"  width="100" height="100" />';
```
The only issue you might find is weird dimensions on the actual image. You will have to mess with it on the PDF output to make sure it displays as desired.  I needed to remove the width and height of the actual SVG to make sure it was sizing correctly. Again hope this helps!

**Comment by saywebsolutions** [comment]
> I searched FOREVER until I finally came up with my own solution. I thought I should share in case it could be useful to anyone else. If you are using **PHP** the best solution to inline SVG images (for me) is to output it using **BASE64_ENCODE()** on the actual svg, then wrapping it in an image using the src as follows:
> 
> ```
> $svg = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 36 36" class="circular-chart">
>     <path class="circle-bg"
>           stroke-width="1"
>           fill="none"
>           stroke="#ddd"
>           d="M18 2.0845
>              a 15.9155 15.9155 0 0 1 0 31.831
>              a 15.9155 15.9155 0 0 1 0 -31.831"
>           />
> </svg>';
> 
> $html = '<img src="data:image/svg+xml;base64,'.base64_encode($svg).'"  width="100" height="100" />';
> ```
> 
> The only issue you might find is weird dimensions on the actual image. You will have to mess with it on the PDF output to make sure it displays as desired. I needed to remove the width and height of the actual SVG to make sure it was sizing correctly. Again hope this helps!

Thank you @lov2code for the good workaround, shame this issue exists

**Comment by jurchiks** [comment]
I am still experiencing this issue, using dompdf v1.0.2.
4 years old problem still not fixed, and only a dirty hack as a workaround (`fill="#000000"` did not work for me, base64 probably would, but that is really not a proper solution).

**Comment by maze-map** [comment]
I was using dompdf v1.1.1 and found three problems that caused SVG images not to show.

For those having problems with this, I found an option "setDebugPng" that outputs information about all images not just png images to the log file.

`$dompdf->getOptions()->setDebugPng(true)->setLogOutputFile("/path/to/file");`

The first problem was that I came from an old 0.8.2 version that didn't have chroot so I had to add setChroot() to the options for the path containing the images.
The second problem was the fill wasn't set to anything in the SVG, so I had to modify my SVG images to add a `fill="#000000"` in the svg tag.

This still didn't fix anything for me. When I set the debug png option and checked the log file, I found the width was being set to zero. Additionally, the max-width was defaulting to zero! The relevant code dealing with calculating sizes is in dompdf/dompdf/src/FrameReflower/Image.php.

To solve the third problem, I set the following attributes on my img tag:

`<img src="/path/to/chroot/image.svg" height="120" width="auto" style="width: auto; height: 120px; max-width: none; min-height: none; min-width: none;">`

Voila! The image finally appeared in the PDF!

If it matters, I did use php-svg-lib version 0.4 and worked around the composer requirements by having this line in my composer.json "require" section:

`"phenx/php-svg-lib": "0.4 as 0.3.3"`

And the fill was required to be set in the SVG file because when the width was finally properly working, the images were drawing white on white.

**Comment by tnt-freskim-veliu** [comment]
I don't know if its already fixed in the new releases, but for me, it worked in this way:

` @php
                            $signature = $user->signature;

                            $svgFileContent = base64_encode(str_replace('<svg', '<svg fill="#000000" ', file_get_contents($signature)));
                        @endphp

                        <img src="data:image/svg+xml;base64,{{ $svgFileContent }}"
                             style="height: 40px;"
                             alt="img"
                        />`

The code is written in the blade, and the problem was with the fill attribute.

**Comment by TiagoJacobs** [comment]
I had a similar issue today, in my case I had to drop the entire `<page` element from SVG:
![image](https://user-images.githubusercontent.com/2075267/209552860-4d0fe9c9-a771-48c9-b412-ed4f77f2a7c8.png)

**Comment by bsweeney** [comment]
@TiagoJacobs this is an issue in php-svg-lib that seems to be a bug with how group properties flow down to the contained elements, which are overriding the properties of the child elements instead of acting as defaults. Follow dompdf/php-svg-lib#100 for updates.

**Comment by Nico-Schaefer-2111** [comment]
Why is this issue marked as closed ? there are still bugs with it ? 

Is this issue going to be fixed in the future ?

**Comment by jurchiks** [comment]
> Why is this issue marked as closed?

Because the issue is not in this library, but its dependency.

**Comment by Nico-Schaefer-2111** [comment]
> The only change in php-svg-lib v0.3 is the following: [dompdf/php-svg-lib@0a98695](https://github.com/dompdf/php-svg-lib/commit/0a9869529a2a5f0bee31ba905bdc39962eba1025)
> 
> If reverting it doesn't help, most likely php-svg-lib is not the problem.

I thought it was not, but maybe I did not read the following comments carefully enough.
