### ISSUE TITLE
Error handling for function split_text()

### ISSUE THREAD

**Issue by hkvstore** [dompdf/dompdf#1622]
Re: https://github.com/dompdf/dompdf/blob/master/src/FrameDecorator/Text.php

I think it is the same issue as https://github.com/dompdf/dompdf/issues/1549.

Now we have:
```php
$split = $this->_frame->get_node()->splitText($offset);
$deco = $this->copy($split);
```
I came across a case where the first line failed on handling some Japanese, $split became FALSE and calling $this->copy($split) failed.

Will it be better to add some error handling? e.g.
```php
$split = $this->_frame->get_node()->splitText($offset);
if (!$split) {
    return null;
} 
$deco = $this->copy($split);
```

**Comment by Mellthas** [comment]
Error handling has been added in 6cbcb81abe9a835af558066f34ae045fc7d5f71f.
