### ISSUE TITLE
Anchoring problem [0.8.2]

### ISSUE THREAD

**Issue by Riells** [dompdf/dompdf#1624]
Hi, I'm including a link to an anchor like this:

&#x3C;a name=&#x27;top&#x27;&#x3E;...&#x3C;/a&#x3E;
&#x3C;!-- more html code here --&#x3E;
&#x3C;a href=&#x27;#top&#x27;&#x3E;Top&#x3C;/a&#x3E;

When I test the link its href has changed to this following line, which resizes the pdf to fit the Acrobat's viewer.
http: //localhost/project/phps/article_pdf.php#[{"num":6,"gen":0},{"name":"Fit"}]

External links working fine.

**Comment by bsweeney** [comment]
This should be working OK with the latest release.
