### ISSUE TITLE
Entire paragraphs sometimes break to next page instead of breaking inside

### ISSUE THREAD

**Issue by gavin310** [dompdf/dompdf#1626]
This is very frustrating and if it's a large paragraph it makes for a very ugly PDF. Sometimes the entire paragraph breaks to the next page instead of breaking at the end of the page and continuing on the next page. I say sometimes because if I adjust margins on headings and/or line spacing, sometimes it will wrap normally. There is no special HTML or CSS, it's all very simple. The blue bar on the right is put there using `float: right` and the content just flows to the left of it. The paragraphs are simple `<p>` tags.

Any ideas how to fix this? Sometimes the text wraps to the next page fine, but with different content sometimes it pushes entire paragraphs to the next page.

![pdf](https://user-images.githubusercontent.com/7841802/34419817-a2cd7304-ec38-11e7-962d-081ca2763e5d.jpg)

**Comment by lan0** [comment]
Have you found a workaround? In some cases a `&nbsp;` at the end fixes the page break for us, but not always.

**Comment by bsweeney** [comment]
This isn't an entirely new problem, though I'd have to do a bit of searching to find the related issues. If you can provide some sample HTML that shows the problem we can take a look.

**Comment by bsweeney** [comment]
Significant improvements have been made to the page-break logic over the last few releases. Without sample HTML we have to believe the issue has been resolved.
