### ISSUE TITLE
Error when activating debugLayout

### ISSUE THREAD

**Issue by adlcadn** [dompdf/dompdf#1629]
I want to use the debug facilities in dompdf via composer (version = <5113accd>) but when I activate debugLayout with

$options = new Options (); 
$options->set (' debugLayout', true); 
$dompdf = new Dompdf ($options);

I get this error: 

ErrorException
A non-numeric value encountered
/Users/xxxxx/vendor/dompdf/dompdf/src/Adapter/CPDF.php
640

/Users/xxxxx/vendor/dompdf/dompdf/src/Renderer/AbstractRenderer.php (921) : rectangle : Dompdf\Adapter\CPDF : -> ( 34.0157480315, 34.0157480315, 510.236220472, auto, Array, 0.1, Array )

Obviously "auto" should be replaced by a numerical value.

**Comment by Michaeltlee** [comment]
I encountered the same issue when trying to debug a 2-page PDF. The second page used `page-break-after: always;`. Did not have the same issue with a single-page PDF.

**Comment by bsweeney** [comment]
@Michaeltlee I'm not able to reproduce. Which version of Dompdf and do you have a sample of the HTML where this happens? Also, any other layout options enabled or just the main switch?
