### ISSUE TITLE
function is deprecated

### ISSUE THREAD

**Issue by SergioAraya** [dompdf/dompdf#1634]
I got this message: 

local.ERROR: ErrorException: Function create_function() is deprecated in /home/vagrant/code/facturacion/vendor/dompdf/dompdf/include/text_frame_reflower.cls.php:376

**Comment by phpguru** [comment]
The PHP function `create_function` was deprecated in PHP 7.2. 

If you're using this library directly, upgrade to a newer version of dompdf.

If you're using a library with a downline dependency to dompdf, inform the package maintainer with the outdated dependency (in my case, "yajra/laravel-datatables-oracle": "^6.0" has this issue) -- roll back your PHP to 7.1.x.

**Comment by meztor** [comment]
change this line
`array_walk($words, create_function('&$val,$str',
                                         '$val = Font_Metrics::get_text_width($str, "'.addslashes($font).'", '.$size.', '.$word_spacing.', '.$char_spacing.');'));
      `
for this line
`array_walk($words, function(&$val,$str) use($font, $size, $word_spacing, $char_spacing){
        $val = Font_Metrics::get_text_width($val, $font, $size, $word_spacing, $char_spacing);
      });`

**Comment by bsweeney** [comment]
This was addressed by commit 6880289975e0ae14289bd26fe97bfa0dd74c5a78

**Comment by Evanzyl** [comment]
Hi

I'm getting this message for Laravel 5:

ErrorException in text_frame_reflower.cls.php line 376:
Function create_function() is deprecated

How can I fix this. Can't seem to get any answers on this issue.

Thanks.
