### ISSUE TITLE
dynamic height of page?

### ISSUE THREAD

**Issue by drcll** [dompdf/dompdf#1637]
Hello guys,
is possible to set up dynamic paper height of html content?

My settings are like:
`
$dompdf->loadHtml($html);
$dompdf->setPaper(array(0, 0, 595, 7280), 'portrait'); //7280 -- height of content with all sections
$dompdf->render();
$dompdf->stream();`

But I want to dynamic change sections, so I need something like this
`$dompdf->loadHtml($html);
$dompdf->setPaper(array(0, 0, 595, 'auto'), 'portrait');
$dompdf->render();
$dompdf->stream();`

Is it possible? Thanks for answers

**Comment by bsweeney** [comment]
Missed this one. This is not easily done with Dompdf. See #1524 for a method that might work.
