### ISSUE TITLE
load fonts error

### ISSUE THREAD

**Issue by drcll** [dompdf/dompdf#1640]
Hello, I moved my app, to production server. When I want to generate my PDF, app make this error

`Undefined index: /home/html/test.sk/public_html/vendor/dompdf/dompdf/lib/fonts\88f7dab015ebe744a5c1655803a4cf23

problem is on this line 
$cpdf_font = $this->_canvas->get_cpdf()->fonts[$style->font_family];
`
Any suggestions, please ?

**Comment by Kunilt** [comment]
Deleting cached font files helped here.
