### ISSUE TITLE
CSS Problem between local and s

### ISSUE THREAD

**Issue by devsmic** [dompdf/dompdf#1652]
**Here is the pdf view on the server:**
![image](https://user-images.githubusercontent.com/35441021/35919320-4ab510ee-0c47-11e8-8795-88fcb6c728ee.png)

**Here is the pdf view on local(eq: localhost:8000)**
![image](https://user-images.githubusercontent.com/35441021/35919326-4fccfb14-0c47-11e8-992b-f3b25c182338.png)

The difference is too much, the hosted server like have some problem with CSS.
The most important is the background of each page(watermark) not display properly, only work just like body page in html.

I think there is a problem with the platform or I missing something like installing or downloading some external dependencies. Cause this happened in another local server(another computer).

Any help will be appreciated.
Thank you

**Comment by Sa-arash** [comment]
یلسیبلسیبلسیبلسیبلسیلبسیبلسیبلسیبلیسلسبیل

**Comment by Sa-arash** [comment]
سیبلسیبلیسلبسیبل
