### ISSUE TITLE
All of russian symbols shows as '?'

### ISSUE THREAD

**Issue by Alexxosipov** [dompdf/dompdf#1656]
Hi. I did an dompdf app on my local openserver server and it worked, but when I upload it on shared hosting, all of symbols becomes to '?'. This server follows all of requirements, checked it with phpinfo(). Where did I go wrong? And is this an issue or my fault? 

By the way, I tried to include this font via `@font-face`, but nothing happens. Also used font_load.php, on local machine everything is good. 

V0.8.2

1 more note: if I open template.html in browser, it will work good. 
```

$dompdf = new Dompdf([
	'defaultFont' => 'TTNorms'
]);
$html = file_get_contents('template.html');
$html = mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8');
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream("dompdf_out.pdf", array("Attachment" => false));
exit(0);

```

template.html: 

```
<!DOCTYPE html>
<html lang="en">
<head>
	
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Document</title>
	<style>
		
		body {
			font: 14px TTNorms;
			margin: 50px;
			margin-bottom: 10px;

			position: relative;
			
		}
		*{margin:0;padding:0}

		//some css here
	</style>
</head>
<body>
	
	<div class="header clearfix">
		<div class="header__company">
			<img src="logo.png" alt="">
			<p class="company__name">КОМПАНИЯ "БТС"</p>
			<p class="company__description">Производство и установка газовых
электростанций по РФ</p>
			<p class="header__proposal">Коммерческое предложение</p>
			<p class="header__proposal-number">№25 от {date}</p>
		</div>
		<div class="header__manager">
			<img src="{manager}" alt="">
		</div>
	</div>

	<div class="proposal">
		<div class="proposal__header">Уважаемый {clientName}!</div>
		<div class="proposal__text">Предлагаем Вам газопоршневую электростанцию (ГПУ), выполненую с
применением запатентованных технологий на базе двигателя {brand}
 мощностью {power}</div>
	</div>

	<table class="{tableClass}">
		<thead>
			<tr>
				<td>Наименование</td>
				<td>Цена, в руб.</td>
				<td>Кол-во</td>
				<td>Сумма, в руб.</td>
				<td>Срок изготовления</td>
			</tr>
		</thead>
		<tbody>			
			{tableContent}
		</tbody>
	</table>

	<div class="info clearfix">
		<div class="left">
			<div class="payment">
				<p class="header">УСЛОВИЯ ОПЛАТЫ:</p>
				<p class="item">- 40% Предоплата</p>
				<p class="item">- 40% Промежуточная оплата</p>
				<p class="item">- 30% Расчет перед отгрузкой</p>
			</div>
			<div class="delivery">
				<p class="header">условия поставки:</p>
				<p class="item">EXW Санкт-Петербург</p>				
			</div>
			<div class="dop">
				<div class="header">ДОПОЛНИТЕЛЬНЫЕ УСЛУГИ:</div>
				<p class="item">- Доставка до места эксплуатации</p>
				<p class="item">- Проектирование инженерных сетей для ГПУ</p>
				<p class="item">- Монтаж станций и инженерных сетей</p>
			</div>
		</div>
		<div class="right">
			<div class="summ">Итого: {total}</div>
			<div class="director">
				<p class="dol">ГЕНЕРАЛЬНЫЙ ДИРЕКТОР</p>
				<p class="name">КАЛИНИН Р.О.</p>
			</div>
			<img src="petchat.png" alt="">
		</div>
	</div>
	<div class="footer">
		<p>ООО «КОМПАНИЯ «БТС»</p>
		<p>САНКТ-ПЕТЕРБУРГ, УЛ БАБУШКИНА, Д 40 ОФ.6</p>
	</div>
</body>
</html>
```

**Comment by iBobik** [comment]
Same issue with Czech diacritics (non-ascii) characters (e.g. `ěščřžýáíé`).

On localhost with Lando it works, but in production in Docker not working.

**Comment by bsweeney** [comment]
This could be due to dompdf not being able to find the font. When you're uploading dompdf from one system to another it's always a good idea to re-install your font. You can also look at the dompdf_font_family_cache.php file and update the path for your font such that it would point to the correct font location on the new system.

Another potential issue is dompdf not having read/write access to some of the directories on the server. The relevant directories would be the dompdf temp directory and the dompdf font cache directory.

**Comment by krolovolk** [comment]
Check real files encoding (template,html and yourdompdf.php)  
Check server's encoding
Make some tests with cyrilic text
Try to use iconv('windows-1251', 'UTF-8', $text) for achieving the desired result

**Comment by bsweeney** [comment]
No recent follow up from OP. Will re-open if new information is provided.

**Comment by ivan-cc** [comment]
```
$dompdf = new Dompdf([
	'defaultFont' => 'DejaVu Serif'
]);
```

**Comment by krolovolk** [comment]
> Same issue with Czech diacritics (non-ascii) characters (e.g. `ěščřžýáíé`).
> 
> On localhost with Lando it works, but in production in Docker not working.

Problems can be in folder dompdf/lib/fonts/
while dompdf first runnig it create new files for non native fonts in this folder 
You can see it by file names in this folder like  "2db347654ef98a4122b1fd12328b6ca2.ttf"

So if you reinstall dompdf it will add fonts without problems (if they worked on localhost). I reinstalled dompdf and  add dompdf folder to .gitignore. May be not the best but real solution.

**Comment by krolovolk** [comment]
> Same issue with Czech diacritics (non-ascii) characters (e.g. `ěščřžýáíé`).
> 
> On localhost with Lando it works, but in production in Docker not working.

Remove file dompdf_font_family_cache.php from the production. And then open in browser page with dompdf generating PDF. The Dompdf script will regenerate dompdf_font_family_cache.php file and add autogenerated fonts files. And it will be OK.

**Comment by muzanaka** [comment]
1. download russian fonts - https://disk.yandex.ru/d/MmsOb_IRPSTPpA
2. change fonts on lib folder (ex /vendor/dompdf/dompdf/lib/fonts)
3. delete dompdf_font_family_cache.dist.php on fonts folder

Set default font 

$options = new Options();
$options->set('defaultFont', 'times');
$dompdf = new Dompdf($options);
That's all
