### ISSUE TITLE
font-weight displayed as ????? when using Google fonts

### ISSUE THREAD

**Issue by kliment-toshkov** [dompdf/dompdf#1665]
I am importing fonts from google with the following:

```
<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700&amp;subset=cyrillic" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&amp;subset=cyrillic" rel="stylesheet">
```

Then address the font with:
```
<p style="font-family: Roboto Condensed; font-size: 9pt; font-weight: 300;">
```
Rendered text has no visible difference with font-weight: 400 but it is displayed properly.
However when using font-weight: 700 for bold, then text is reverted to default font and replaced with ????

The same is rendered properly when viewed as HTML in browser.

See attached screenshots for HTML rendered in browser, PDF rendered using dompdf 0.8.1 and the source HTML code.
![screen shot 2018-02-23 at 13 28 03](https://user-images.githubusercontent.com/10902296/36592200-6ac2d904-189d-11e8-9ee4-82a088f299e4.png)
![screen shot 2018-02-23 at 13 24 11](https://user-images.githubusercontent.com/10902296/36592201-6ae18336-189d-11e8-93fb-532bc8f1ced3.png)
![screen shot 2018-02-23 at 13 23 52](https://user-images.githubusercontent.com/10902296/36592202-6aff4380-189d-11e8-87d0-64a7c77f47f5.png)

**Comment by peter-gribanov** [comment]
I have a similar problem

**Comment by bsweeney** [comment]
Dompdf does not current support numeric font weights. Because of this it is falling back the default font (sans-serif?). You are getting "?" in your text because that font does not support those specific characters.

Follow #675 for updates on this issue.
