### ISSUE TITLE
get the pdf file

### ISSUE THREAD

**Issue by Ginso** [dompdf/dompdf#1669]
Hello, i'm trying to use this in a wordpress plugin.
When i try the hello world example i get the message "Unable to stream pdf: headers already sent"
But i don't want to display it anyway, i want to sent the file per mail. How can i set the name for the pdf file and where is it located?

**Comment by jeremielodi** [comment]
Hi Ginso, try to remove the header before send a new. see at the code bellow
```php
  header_remove();
  // header('location:Login.php');   use your new header after
```

**Comment by Ginso** [comment]
doesnt work:
Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\wordpress\wp-includes\class.wp-styles.php:225) in C:\xampp\htdocs\wordpress\wp-content\plugins\Trainingskonfigurator\trainingskonfigurator.php on line 30

and anyway that isn't my real question. My goal is not to display or let the user dowlnload the file, i want it to automaticaly sent by mail. So, where is it located?

**Comment by MatthiasKuehneEllerhold** [comment]
This works for us:
```php
$domPdf = new Dompdf();

// some options...
$domPdf->getOptions()->setFontCache('data/dompdf/fontcache');
$domPdf->getOptions()->setFontDir('data/dompdf/fontdir');
$domPdf->getOptions()->setTempDir('data/dompdf/tempdir');
$domPdf->getOptions()->setLogOutputFile(false);

$domPdf->loadHtml($htmlDocument);
$domPdf->setPaper('A4', 'Portrait');

$domPdf->render();
$pdfFile = $domPdf->output();
```

**Comment by jeremielodi** [comment]
// you can specify the path you need like this
```php
......
$pdfoutput = $dompdf->output();
$filepath =  __DIR__."/file.pdf";
$fp = fopen($filepath, "w");
fwrite($fp, $pdfoutput);
fclose($fp);
```

I just create  a file in server and put pdf content on it
