### ISSUE TITLE
TR element border styling not applied with border-collapse: collapse

### ISSUE THREAD

**Issue by Ginso** [dompdf/dompdf#1675]
Hello,
i have a table in my html text:
```
<table style="width:100%">
	<tr style="border-top:1px solid black; border-bottom:1px solid black">
		//<th>...
	</tr>
	<tr style="border-bottom:1px solid black">
		//<td>...
	</tr>
</table>
```

but in the pdf file, the borders are missing

**Comment by Daniel-Beardsmore** [comment]
It's worth noting that you need to add the following before this will work in any browser:

&lt;table style="width:100%; **border-collapse: collapse;**"&gt;

With that set, you can indeed apply borders to `<tr>`. And yes, DOMPDF seems not to be able to apply borders to `<tr>`, only to `<td>` and `<th>`. Also, you'd be better off, surely, using a `<style>` block and using CSS rules, as in `td, th { border-top: 1px solid black; border-bottom: 1px solid black; }`?

The bug still stands, however.

**Comment by alemdinarevic** [comment]
table {
  border-collapse: collapse;
}

will solve your issue of not having a border around your continuous table components - <tr>
