### ISSUE TITLE
Open Sans font

### ISSUE THREAD

**Issue by IonutPopescuRO** [dompdf/dompdf#1677]
Hello. I tried everything, added files, used `@import` google, css in base64, nothing, I can't use this font.
My code:
```
            $pdf = PDF::loadView('invoices.pdf', compact('settings', 'invoice', 'invoiceSettings'));
            $pdf->output();
            $dom_pdf = $pdf->getDomPDF();
            $canvas = $dom_pdf ->get_canvas();
            $canvas->page_text(35, 750, "Page: {PAGE_NUM} of {PAGE_COUNT}", null, 10, array(0,0,0));

```

**Comment by bsweeney** [comment]
Sorry we missed this. Hope you were able to work it out.

For anyone else `@import` seems broken right now for fonts (#2054). As is base64 embedded fonts (#967).
