### ISSUE TITLE
__autoload() is deprecated, use spl_autoload_register() instead

### ISSUE THREAD

**Issue by ashinzekene** [dompdf/dompdf#1678]
```php
Line Number: 83

Backtrace:

File: C:\xampp\htdocs\metrohealth\portal\vendor\dompdf\dompdf\dompdf_config.inc.php
Line: 333
```

**Comment by MatthiasKuehneEllerhold** [comment]
There is no `dompdf_config.inc.php` in the current versions.

**Comment by ashinzekene** [comment]
Version 0.8.2 
Downloaded it from the releases page yesterday

**Comment by MatthiasKuehneEllerhold** [comment]
Are you sure there is no old version lingering around?
It seems like you've installed it via composer (looking at your stack trace), you'll have to update it via composer too.

**Comment by ashinzekene** [comment]
Found out I had 0.6 in composer👍👍👍
