### ISSUE TITLE
Image not found or type unknown

### ISSUE THREAD

**Issue by alagesanbe08** [dompdf/dompdf#1681]
//set options
        $dompdf_option = new \Dompdf\Options();
        $dompdf_option->setIsFontSubsettingEnabled(true);
        $dompdf_option->setIsRemoteEnabled(true);
        $dompdf_option->setIsHtml5ParserEnabled(true);
        $dompdf->setOptions($dompdf_option);

		//$dompdfOptions = $dompdf->getOptions();
		//$dompdfOptions->set('enable_remote', true);
		//$dompdf->setBasePath($base_path.'template.css');
		$dompdf->setPaper("A4", "portrait");
		$dompdf->loadHtml($template_html);
		$dompdf->render();
		$output = $dompdf->output();

Php settings:
1. allow_url_fopen enabled and GD extension enabled, curl enabled
2. tmp folder permission set 777 also tried image full url

i am using dompdf 0.8.2.

**Comment by alagesanbe08** [comment]
Hi, image path need to set from root e.g: /var/www/joomla/images/logo.png
it fixed my issue

**Comment by ZerooCool** [comment]
I have the same problem.
How i can make that when i use mediawiki ?
https://github.com/dompdf/dompdf/issues/1766

**Comment by mahi13c** [comment]
I have the same problem with slight difference,
Image is loading on localhost but loading perfectly fine on live server. I have used full path also.
