### ISSUE TITLE
Dompdf stopped working after updating php version to 7+

### ISSUE THREAD

**Issue by umairm638** [dompdf/dompdf#1686]
I've updated php version from 5.6 to 7 and after that library stopped working, I'm just getting this error:

    "PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/cpanel/ea-php70/root/usr/lib64/php/modules/php_mysqli.dll' - /opt/cpanel/ea-php70/root/usr/lib64/php/modules/php_mysqli.dll: cannot open shared object file: No such file or directory in Unknown on line 0"

and nothing happening after it, no other error.

**Comment by MatthiasKuehneEllerhold** [comment]
This means that your php install couldn't load the mysqli extension. 

This has nothing to do with DomPDF.
