### ISSUE TITLE
Blank rows cause fatal errors

### ISSUE THREAD

**Issue by wreardan** [dompdf/dompdf#1689]
Having blank `<tr></tr>` elements with no `<td>` elements causes a fatal error in DomPDF.  It would be nice if it did not cause a fatal error, instead ignoring that row.  Because it DOES cause a fatal error currently, I now have to code extremely complex logic added to already complex display logic to not display the `<tr></tr>` elements under blank conditions.

**Comment by Mellthas** [comment]
This is resolved by now, see #2749.
