### ISSUE TITLE
I can not rename the file to be streamed

### ISSUE THREAD

**Issue by ricvillagrana** [dompdf/dompdf#1690]
I am just rendering and streaming it. Everything is working well but the name of the output file is the problem, every file is named "document".

**Comment by MatthiasKuehneEllerhold** [comment]
If you're streaming the PDF file to the browser, it will take the last part of the URL as filename upon saving. If you want to change that you'd have to change the URL this PDF is available it.
If you're sending the PDF to download for the user you can use the `Content-Disposition` HTTP header to set a filename.
```php
header('Content-Disposition: attachment; filename=my-pdf.pdf');
```

**Comment by ricvillagrana** [comment]
The last part of URL is not "document and the header seems not work.

**Comment by tweinreich** [comment]
Same issue here. The content disposition filename is set correctly and the file opens with a hash instead of a readable name as URL. When saving it, the name remains "document.pdf".

**Comment by Whip** [comment]
Why was this closed? I don't see a solution, did any of you managed to sort it out? Here's the code I'm using

```
$dompdf = new Dompdf([
	'chroot' => [__DIR__]
]);
$dompdf->loadHtml($invoiceHtml);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream();
```

**Comment by bsweeney** [comment]
Issues are closed if there isn't enough info to determine if there is an issue that requires resolution.

@Whip In your case you haven't specified the filename you want when you call the [stream method](https://github.com/dompdf/dompdf/wiki/Usage#stream):

```
$dompdf->stream("document.pdf");
```

**Comment by Whip** [comment]
That did it. Thank you very much
