### ISSUE TITLE
background-size not working

### ISSUE THREAD

**Issue by maartenhetworks** [dompdf/dompdf#1693]
Background-size is not working properly

`
@page {
            margin: 0;
}
html, body {
            background-image: url(url);
            background-repeat: no-repeat;
            background-position: bottom right;
            background-size: 100px;
            margin: 0;
            width: 100%;
            height: 100%;
}`

It ignores the background-size property. I can see the background image but it is to large.

**Comment by simonberger** [comment]
Duplicate of #463

**Comment by WebSpectrum** [comment]
any workaround for this to get a similiar result? I want to use CSS property baackground-size:cover ?? .... thanks

**Comment by bsweeney** [comment]
The closest you could get would be to absolutely position a div with z-index (to move it behind other content). The only element inside the DIV would be the image sized horizontally or vertically as appropriate to simulate a cover.

**Comment by Keania-Eric** [comment]
I solved my problem by using a graphical tool to resize the background image to exactly the size of the frame to render it. And that actually i think is best.
