### ISSUE TITLE
dompdf not support korean language 

### ISSUE THREAD

**Issue by sajid9** [dompdf/dompdf#1695]
when i generate pdf in korean language in this look like this ???????

**Comment by leechul** [comment]
mee too

**Comment by bsweeney** [comment]
Please review the [Unicode How-To](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo) for information on support other languages.

**Comment by axelf** [comment]
Is there any solution? I can't get it to work also with the link above. What font can i use for korean?
