### ISSUE TITLE
<th> elements are not centered

### ISSUE THREAD

**Issue by ygator** [dompdf/dompdf#1699]
I noticed on the demo other:demo_01 that the column headers on the PDF were not centered.  To confirm I made a simple table and sure enough the th elements were not center (they are bolded which is correct).  The work around is easy enough by just adding:
```
th {
    text-align: center;
}

```

**Comment by naitsirch** [comment]
I can confirm that text within <th> elements are centered per default in Firefox for example.

**Comment by bsweeney** [comment]
For sure the browsers render the text centered by default, but I'm not sure where that styling comes from for Firefox. Mozilla's [default stylesheet](https://dxr.mozilla.org/mozilla-central/source/layout/style/res/html.css) does not specify a text alignment for the TH element. Though other browsers do ([links to default stylesheets](https://stackoverflow.com/a/22510220/264628)).

The HTML3 spec did specify that TH should have its text centered: https://www.w3.org/MarkUp/html3/tablecells.html

The CSS2 spec does have an "informative, not normative" default stylesheet: https://www.w3.org/TR/CSS2/sample.html

And the HTML5 spec includes a suggested rendering document that seems to indicate that TH should be centered by default: https://html.spec.whatwg.org/multipage/rendering.html#tables-2:the-th-element-9

So, it's worthwhile to consider updating the default stylesheet to center text in the TH element.
