### ISSUE TITLE
Text does not appear in  pdf

### ISSUE THREAD

**Issue by Flyers2** [dompdf/dompdf#1710]
No text appears in the pdf. it just creates a blank pdf. I can get pictures on the pdf. 
I am using a basic amazon linux 2 system. with php7.2 and a hpptd server. 
There is no error message or warnings from php. 
I set all permissions in the dompdf folder to rule out permission issues.

**Comment by lbassin** [comment]
Same problem here.. 
No error, nothing :disappointed:

**Comment by bsweeney** [comment]
Would need some more info. You can start by providing the HTML source so we can see if we can  reproduce the issue. If you can provide a sample of the PDF created that would also help.

**Comment by Flyers2** [comment]
I ended up hosting the application on a Ubuntu 16 server instead of the amazon version. It works over there.

**Comment by bsweeney** [comment]
Guessing that maybe it was a font issue, such as Dompdf knowing about the font but unable to load the font file. Closing site you were able to work around the problem.
