### ISSUE TITLE
A problem with changing font

### ISSUE THREAD

**Issue by sergiota** [dompdf/dompdf#1714]
Hello!
I have a problem when I try to change the default font.
The symbols in resulting PDF are changed by ??? symbols, so I tried to change the default font.
But when I try to change the default font in vendor/barryvdh/laravel-dompdf/config/dompdf.php ("default_font" => "courier")
the font in the resulting PDF is not changed - Helvetica stays whatever I did.
What could be the problem?
Thanks!

**Comment by bsweeney** [comment]
Still having a problem here? There was a period where Dompdf wasn't respecting the default font setting, which should have been fixed.

**Comment by sergiota** [comment]
Well, I've added the following to my blade template in <style> section:
```
body {
            font-family: DejaVu Sans;
        }
```
And the workaround worked.
So, I do not know if the actual problem with Dompdf default font was fixed

**Comment by bsweeney** [comment]
That is certainly an easy work around. I'll close the issue, but feel free to comment back if you decide you do need more help and I'll reopen it.
