### ISSUE TITLE
Fatal error: Uncaught DOMPDF_Exception: No block-level parent found

### ISSUE THREAD

**Issue by justinkongyt** [dompdf/dompdf#1724]
Hi

Sorry I'm relatively new to this. I encountered the below problem once I migrated to a new server. Can any one kindly point me what to check or look out for in the server? I doubt is a program or code issue as it was running fine in old server.

Thanks in advance!

Error below:

> Fatal error: Uncaught DOMPDF_Exception: No block-level parent found. Not good. in dompdf/include/inline_positioner.cls.php:37 Stack trace:
> 0 dompdf/include/frame_decorator.cls.php(700): Inline_Positioner->position()
> 1 dompdf/include/text_frame_reflower.cls.php(330): Frame_Decorator->position()
> 2 dompdf/include/frame_decorator.cls.php(711): Text_Frame_Reflower->reflow(NULL)
> 3 dompdf/include/page_frame_reflower.cls.php(123): Frame_Decorator->reflow()
> 4 dompdf/include/frame_decorator.cls.php(711): Page_Frame_Reflower->reflow(NULL)
> 5 dompdf/include/dompdf.cls.php(951): Frame_Decorator->reflow()
> 6 include/inline_positioner.cls.php on line 37

**Comment by luigilima** [comment]
Edit the anycodings_php dompdf/dompdf_config.inc.php
from
def("DOMPDF_ENABLE_HTML5PARSER", false);
to
def("DOMPDF_ENABLE_HTML5PARSER", true);
