### ISSUE TITLE
padding on tablecells with some fonts

### ISSUE THREAD

**Issue by Mauskugel** [dompdf/dompdf#1725]
Hi there
I started with DOMPDF a few day ago and i am quite happy with it.
Now I have several issues.
First one is, that the cell padding in a table misbehaves using a custom font (f.e. “Gudea” in this case). I have set the cell padding to 0 top and bottom. On screen it looks fine,
![image](https://user-images.githubusercontent.com/38745692/39296284-cc0485fe-4940-11e8-9b62-560e2847b2bd.png)

the pdf shows extra padding on top. 
![image](https://user-images.githubusercontent.com/38745692/39296414-206f9994-4941-11e8-8ada-fd33808d1111.png)

so far i figured a workaround by loading special css for the pdf. there i am changing the cell padding top to negative values until it fits my needs. (padding: 0px 2px; padding-top: -5px;) wich is not conform to css. it should be possible by marging, wich does not work.
![image](https://user-images.githubusercontent.com/38745692/39297090-e35abf3c-4942-11e8-976c-55e8311df387.png)

i tried several fonts some work, some don't.

best regards.

**Comment by bsweeney** [comment]
Would need some sample HTML+CSS to isolate the issue if it still exists in the current release.
