### ISSUE TITLE
gd dependency on linux alpine

### ISSUE THREAD

**Issue by rocketlaunchr-cto** [dompdf/dompdf#1730]
Does anyone know how to install the required `gd` dependency on linux alpine?

```
composer install
.
.
.
Problem 1
    - Installation request for dompdf/dompdf v0.8.2 -> satisfiable by dompdf/dompdf[v0.8.2].
    - dompdf/dompdf v0.8.2 requires ext-gd * -> the requested PHP extension gd is missing from your system.
  Problem 2
    - dompdf/dompdf v0.8.2 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - laravel/cashier v7.1.0 requires dompdf/dompdf ^0.8.0 -> satisfiable by dompdf/dompdf[v0.8.2].
    - Installation request for laravel/cashier v7.1.0 -> satisfiable by laravel/cashier[v7.1.0].
```

**Comment by fabwu** [comment]
You can try ignoring the PHP requirements with this command:

```
composer install --ignore-platform-reqs
```
Maybe you can use dompdf anyways or check [this issue](https://github.com/docker-library/php/issues/225) for installing `gd` in your docker image.

**Comment by bsweeney** [comment]
GD will no longer be a required dependency with the next release (see the referenced #1621). So long as your HTML document does not include images that would result in a call to GD, Dompdf should still be able to render the document.
