### ISSUE TITLE
Error on line 175

### ISSUE THREAD

**Issue by agentmarine** [dompdf/dompdf#1731]
I have experienced an error on line 175 of src/Css/Stylesheet.php which exists because its being run via CLI

`list($this->_protocol, $this->_base_host, $this->_base_path) = Helpers::explode_url($_SERVER["SCRIPT_FILENAME"]);
`

the problem is $_SERVER["SCRIPT_FILENAME"] is not a valid index when running via CLI as the $_SERVER params are not being assigned, these should be checked prior to being used and have a fallback incase they aren't available, and shouldn't used unless it is set.

using php7 in my instance i've adjusted it to be 

> src/Css/Stylesheet.php

` list($this->_protocol, $this->_base_host, $this->_base_path) = Helpers::explode_url($_SERVER["SCRIPT_FILENAME"] ?? null) ?? 'commandline' ;
`

**Comment by bsweeney** [comment]
Which environment are you running in? As mentioned in the PR, I haven't run into this issue from the command line.

**Comment by agentmarine** [comment]
I believe this was running on OSX, I haven't ran it recently but i am sure that it corrected my issue at the time.
