### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by MajorasJack** [dompdf/dompdf#1733]
Getting the below error message randomly when attempting to run any basic laravel commands:

`[2018-05-10 12:43:58] dev.ERROR: ErrorException: Undefined index: DOMPDF_FONT_CACHE in /Users/jack/Work/sites/psg/plugins/renatio/dynamicpdf/classes/ServiceProvider.php:33`

Tried looking around and found issue #1260  but none of the resolutions/fixes mentioned there seem to fix the issue that I'm having.

Already tried:
Deleting vendor folder & running `composer update`
Deleting /storage/fonts directory content
`composer dump-autoload`
`composer dump-autoload -o`

**Comment by MajorasJack** [comment]
Update:

Changed all references of DOMPDF_FONT_CACHE to font_cache which appears to have fixed the issue, but don't think it's ideal.

**Comment by bsweeney** [comment]
We've changed some things about how installed fonts are processed so I think this should no longer be an issue but please follow up if the problem still occurs.
