### ISSUE TITLE
Non-Breaking Hyphen

### ISSUE THREAD

**Issue by Mauskugel** [dompdf/dompdf#1734]
using &#x2011; or &#8209; looks fine on screen, but will not be interpreted right by dompdf.
result: 
![image](https://user-images.githubusercontent.com/38745692/39913452-3486ec08-5502-11e8-82c9-d170dbe9e475.png)

workaround: replace in string before sending to domppdf.

**Comment by bsweeney** [comment]
You have to specify a font supporting the desired characters. DejaVu Sans will work for this one:

```
<div style="font-family: DejaVu Sans">&#x2011;</div>
<div style="font-family: DejaVu Sans">&#8209;</div>
```
