### ISSUE TITLE
Infinite loading if table is longer than the page

### ISSUE THREAD

**Issue by Doomkyn** [dompdf/dompdf#1735]
Hello, I have a table in a pdf that has a really long text, usually longer than a whole page. The problem it that dompdf is trying to stick the table into one page and load indefinitely without outputting any results. There shoukld be a way to allow dompdf to break the page inside a table to solve the issue.

**Comment by Ujifman** [comment]
I have the same issue

**Comment by bsweeney** [comment]
Version of Dompdf? Dompdf has a known issue around rendering a single table cell larger than the page (see #98).
