### ISSUE TITLE
Examples is missing

### ISSUE THREAD

**Issue by gnumoksha** [dompdf/dompdf#1736]
From: https://dompdf.net/examples.php:

> Below are some sample files. The PDF version is generated on the fly by dompdf. (**The source HTML & CSS for these files is included in the test/ directory of the distribution package**.)

But I'm unable to find "test" directory in this project.

**Comment by kirame09** [comment]
+1 for this.

**Comment by kirame09** [comment]
@gnumoksha , Here is the link https://github.com/dompdf/dompdf/tree/tagged-pdf/www/test

**Comment by khanks** [comment]
... Not ...

> 
> 
> @gnumoksha , Here is the link https://github.com/dompdf/dompdf/tree/tagged-pdf/www/test

... Nope, not there...
