### ISSUE TITLE
wrong url font

### ISSUE THREAD

**Issue by ajatdarojat45** [dompdf/dompdf#1737]
/laravel/vendor/dompdf/dompdf/lib/fonts\Helvetica-Oblique

how to change / to \ ?

**Comment by bsweeney** [comment]
The preferred delimeter for cross-platform paths is "/" so you would preferably see that value. The upcoming 0.8.4 should do a bit better job working cross-platform.

I the meantime, you can delete the dompdf_font_family_cache.php file and it will be regenerated on the next run.
