### ISSUE TITLE
How I can create table of content automatically for large PDF

### ISSUE THREAD

**Issue by shaiby** [dompdf/dompdf#1749]
I am using a dompdf for large PDF export from dynamic content templates in database. I need to create a table of content page in start of document. But I am unable to see the method where dompdf support auto generate of index or table of content page like FPDF generate. Is there any way?

**Comment by shaiby** [comment]
Please help in this issue...I need to finish a job. I really appreciate response regarding this.

**Comment by dandinuro** [comment]
Hello Shaiby,

You have a tabel in mysql and you want to print everything from it on pdf using dompdf? Did I understand correctly?

Servus, 
Dan

**Comment by shaiby** [comment]
Thanks a lot for response...
@dandinuro Yes I have database table in mysql. Issue is there are several entries those need to be used to create a PDF and each entry have number of content sections those need to be the part of COD. So simple mysql entry won't give me the correct idea for COD.

@noone-silent I need to show PDF page number where that title (content section) is to be displayed. So simply using anchor will not give me the real page number.

Any suggestion?

**Comment by shaiby** [comment]
There is a solution that I passed few days ago using script within content and then after rendering PDF but before generating output I can have each section's page number. I need that solution. Quick reference of this will help me a lot.

Please suggest me in this regard...I really appreciate as I am getting out of my project deadline.

**Comment by bsweeney** [comment]
We don't have a fully developed solution yet. Follow #217 for updates. In the meantime you can try a solution I worked out using embedded script. Here's a sample: http://eclecticgeek.com/dompdf/debug.php?identifier=toc-v0.6.x

**Comment by shaiby** [comment]
@bsweeney 
By seeing your example I have created a debug.....http://eclecticgeek.com/dompdf/debug.php?identifier=cd82468c0a99e995139bf3235162bfc4

Everything I hope is fine in there but still page number are not replacing. Please any help???

My PDF generation code is like this where $html is same as given in debug
**********************************************************
$options = new Options();
					$options->set('defaultFont', 'helvetica');
					$options->set('isRemoteEnabled', TRUE);
					$dompdf = new Dompdf($options);
					//$pdf=new Cpdf();
					//$dompdf = new Dompdf(array(0,0,0,0));
					$dompdf->load_html($html);
					$dompdf->set_paper('A4', 'portrait');
					$dompdf->render();
					$canvas = $dompdf->get_canvas();
					//$font = Font_Metrics::get_font('helvetica', 'normal');
					$canvas->page_text(270, 828, "(Page: {PAGE_NUM})", '', 7, array(0,0,0));
$dompdf->stream($filename,array("Attachment"=>0));
****************************************************************

**Comment by bhaidar** [comment]
@bsweeney Hey, do you have the source code to embed the TOC? Thanks

**Comment by bsweeney** [comment]
@bhaidar there's a version linked in my earlier comment. Though I'd probably go with the version [here](https://github.com/dompdf/dompdf/issues/1756#issuecomment-1006718311)
