### ISSUE TITLE
SVG Loading

### ISSUE THREAD

**Issue by mmartel-opinionsystem** [dompdf/dompdf#1751]
**DomPDF v0.8.2**
Since PHP 7.2 (probably 7+), getting this error when loading SVGs:

**Error:**
count(): Parameter must be an array or an object that implements Countable
on line 259 in lib/php-svg-lib/src/Svg/Document.php

My code to implement an SVG in DomPDF:
`<img src="image/certificat_adhesion/top_ribbon_portrait.svg" id="top_ribbon">`

Image show up in PDF, but creates php error log entries due to error.

**This is the problem:**
Line 259: 
`if (count($this->attributes)) {`

**Should be:**
`if (count($attributes)) {`

**Comment by Mellthas** [comment]
This has been addressed in php-svg-lib. See https://github.com/dompdf/php-svg-lib/issues/40.
