### ISSUE TITLE
Overlapping Text 

### ISSUE THREAD

**Issue by bady1985** [dompdf/dompdf#1754]
Hello,

I have a small issue with dompdf with pagebreakes and un/sorted lists. When an un/sorted list ends and I get a new page, the new Line overlapps with the new list.

Does anybody knows how can I fix it? I am using Version 0.8.2 and the text comes from the database, saved with ckeditor.

Thanks!

![overlapping](https://user-images.githubusercontent.com/10889242/41319085-f49cab66-6e9a-11e8-9992-a26e74406cfa.png)

**Comment by superyetkin** [comment]
1. Please make sure you are using valid HTML input.
2. Could you please provide a sample code portion to reproduce the issue?

**Comment by bsweeney** [comment]
No input received. Closing unless further information provided.
