### ISSUE TITLE
border-radius does not work on inline elements

### ISSUE THREAD

**Issue by miurin** [dompdf/dompdf#1760]
[This](https://github.com/dompdf/dompdf/wiki/CSSCompatibility) page says that border-radius is supported. It isn't working for me. I copied my HTML and CSS to a HTML doc and it works fine in there. I also tried a span element with a background and border radius, but it doesn't work.

**Comment by superyetkin** [comment]
The radius seems to render fine with the following HTML input.

`<div style="border: 2px solid red; border-radius: 25px;">
<p>line 1</p>
<p>line 2</p>
</div>`

**Comment by superyetkin** [comment]
A _div_ with syule "border: 2px solid red; border-radius: 25px;" seems to work fine.

**Comment by bsweeney** [comment]
It sounds like what you're saying is that the border radius does not render on non-block items, such as the following:

```
<div>
  <span style=" border-radius: 10px; border: 1px solid black;">dompdf</span>
</div>
```

The border on the span element surrounding the "dompdf" text renders without a radius. According the [CSS3 spec](https://drafts.csswg.org/css-backgrounds-3/#border-radius) it applies to all elements except tables with collapsed margins.

So, yes, we do support border radius but currently only on block elements.

If you have an inline element that doesn't span multiple lines you could try to work around the limitation by styling it with `display: inline-block;`.

**Comment by sgehrman** [comment]
I have a simple div with a border-radius: 3px and it shows like this: 
![image](https://user-images.githubusercontent.com/287137/43030657-29ab2740-8c48-11e8-98d2-1851859302d3.png)
