### ISSUE TITLE
Dompdf breaks on rendering ANY table on two pages

### ISSUE THREAD

**Issue by froid24** [dompdf/dompdf#1764]
Hello,

When I included dompdf in my code I was aware of the issue with rendering table cells with a too long content, so I made some checks to ensure that table cells/rows always fit on one page.

And it worked just fine... 

Now, after a few days, I made another test and dompdf breaks at rendering ANY table over to the next page, even if the contents are really small...
What is going on? Can someone point me in the right direction for solving this? Thanks.

Using dompdf 0.8.2. Here is an example of the html being rendered and the corresponding printscreen:

```
<table class="flux_table" name="opt_competitori_table" id="opt_competitori_table" border="1">
  <tbody>
    <tr class="blue1">
      <th>Competitor</th>
      <th>Caracteristici ale ofertei</th>
      <th>Puncte tari</th>
      <th>Puncte slabe</th>
    </tr>
    <tr>
      <td>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque </td>
      <td>ţiţiţiţiţiţiţ iţiţi ţiţiţiţiţiţiţi ţiţiţiţ iţiţiţiţiţi ţiţiţiţiţiţiţiţiţ iţiţiţiţiţiţiţ iţiţiţiţiţi ţiţiţiţi</td>
      <td>c</td>
      <td>d</td>
    </tr>
    <tr>
      <td>c</td>
      <td>d</td>
      <td>a</td>
      <td>b</td>
    </tr>
  </tbody>
</table>
```

![image](https://user-images.githubusercontent.com/26799334/41856993-139027ec-789f-11e8-8dab-c7d38ebb54f7.png)

**Comment by superyetkin** [comment]
Could you please post the HTML code you pass to the _loadHtml_ method?

**Comment by bsweeney** [comment]
This looks like what happens when dompdf encounters invalid HTML at the page break. Or maybe it's something about the styling. But without more details it would be difficult to diagnose. As mentioned by @superyetkin please provide fuller example, including the CSS.

**Comment by Velliz** [comment]
I have same issue, then downgrading from v0.8.2 to v0.8.1 solving the problem.
