### ISSUE TITLE
How To - Use dompdf with Mediawiki

### ISSUE THREAD

**Issue by ZerooCool** [dompdf/dompdf#1766]
I search help for use dompdf with Mediawiki.

The extension Pdf Export Dompdf was archived.
https://www.mediawiki.org/wiki/Extension:Pdf_Export_Dompdf

**Comment by ZerooCool** [comment]
Work. But : Image not found or type unknown


<?php

require_once 'extensions/dompdf/autoload.inc.php';
require_once 'extensions/dompdf/lib/html5lib/Parser.php';
require_once 'extensions/dompdf/lib/php-font-lib/src/FontLib/Autoloader.php';
require_once 'extensions/dompdf/lib/php-svg-lib/src/autoload.php';
require_once 'extensions/dompdf/src/Autoloader.php';
Dompdf\Autoloader::register();



echo ($_SERVER["HTTP_REFERER"]);
$page = file_get_contents($_SERVER["HTTP_REFERER"]);



// reference the Dompdf namespace
use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();
$dompdf->loadHtml($page);

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'landscape');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream();

?>

**Comment by bsweeney** [comment]
Is this still a problem? Last I checked (just now) Dompdf was able to parse URLs regardless of whether or not you encoded spaces in the URL.

**Comment by ZerooCool** [comment]
I don't know. Now i use TCPDF :
https://www.visionduweb.eu/wiki/index.php?title=Accueil
Then i can transform the menu mediawiki to a pdf file.

But, i don't no how i can transforme only the content of a mediawiki page.

**Comment by bsweeney** [comment]
If you decide to try Dompdf again and run into problems feel free to post back.

**Comment by mahi13c** [comment]
Image is not loading on localhost but loading perfectly fine on live server.
