### ISSUE TITLE
The PHP GD extension is required, but is not installed.

### ISSUE THREAD

**Issue by Radhe-PHPLaravelDeveloper** [dompdf/dompdf#1771]
The PHP GD extension is required, but is not installed.

**Comment by bsweeney** [comment]
Are you experiencing an issue? If so can you provide more details? As noted in the [requirements](https://github.com/dompdf/dompdf/wiki/Requirements) Dompdf requires the PHP extension for GD. You must ensure it is present before utilizing Dompdf.

**Comment by Cyrille37** [comment]
Hello @Radhe-PHPLaravelDeveloper 
Do you have some news ? Did u resolve your installation problem ?
Thanks & cheers

**Comment by bsweeney** [comment]
So it looks like this was a compatibility issue with certain systems where GD is not provided. To accommodate these systems, and because GD is really only required if your document includes certain image types (namely PNG) we removed the requirement starting with the 0.8.3 release.
