### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Barryvdh\DomPDF\ServiceProvider' not found

### ISSUE THREAD

**Issue by bogdantoporan** [dompdf/dompdf#1775]
Hello,

I have copied dompdf to shared hosting.

But when trying to clear cache I get the below error:

```
Configuration cache cleared!

   Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Barryvdh\DomPDF\ServiceProvider' not found

  at /project/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php: 208
  204:      * @return \Illuminate\Support\ServiceProvider
  205:      */
  206:     public function createProvider($provider)
  207:     {
  208:         return new $provider($this->app);
  209:     }
  210: }
  211: 

  Exception trace:

  1   Illuminate\Foundation\ProviderRepository::createProvider("Barryvdh\DomPDF\ServiceProvider")
      
/project/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php : 144

  2   Illuminate\Foundation\ProviderRepository::compileManifest()
      
/project/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php : 61

  Please use the argument -v to see more details.
```

P.S. - I am on shared hosting and I cannot user composer install. I need to transfer somehow the files to the server.

I have added the following in my config:

Barryvdh\DomPDF\ServiceProvider::class -> under providers

'PDF' => Barryvdh\DomPDF\Facade::class -> under aliases
Any resolution for this would be helpful.

Thanks.

**Comment by lxg** [comment]
@bogdantoporan Your issue is related to https://github.com/barryvdh/laravel-dompdf, not https://github.com/dompdf/dompdf. Also, this looks more like some problem with your setup than a bug of the library.

**Comment by Cyrille37** [comment]
Hello @bogdantoporan 
If answer is right, could u close the issue please ?
Thanks & cheers
