### ISSUE TITLE
tempnam(): file created in the system's temporary directory

### ISSUE THREAD

**Issue by heshanmax** [dompdf/dompdf#1781]
Hi

when i run this in laravel i get this error 
tempnam(): file created in the system's temporary directory

```
public function generatePDF()
 {
        $students = Student::all();

        $pdf = PDF::loadView('admin.index', compact('students'));

        return $pdf->download('page.pdf');

    }
```

**Comment by lukeholder** [comment]
This is occuring for us only on php 7.2.x when using remote images.

**Comment by lukeholder** [comment]
Maybe relevant: https://github.com/Glavin001/atom-beautify/issues/1108#issuecomment-272012827
