### ISSUE TITLE
DOMPDF with PHP 7.2.5 Uncaught Error: Class 'Dompdf\Frame\FrameTreeList' not found

### ISSUE THREAD

**Issue by Torsten2303** [dompdf/dompdf#1789]
I upgraded to PHP 7.2.5 from 7.1.1 and dompdf was running into errors not finding classes.

I downloaded dompdf latest version from git and same issue. I loaded the release version but the same issue appeared when executing the code. I basically reduced everything to the example code given by dompdf for showing "Hello World" but it it does not work.

Full Error with "Hello World":

```
Fatal error: Uncaught Error: Class 'Dompdf\Frame\FrameTreeList' not found in /srv/www/htdocs/vhosts/app.com/dompdf/src/Frame/FrameTree.php:131 Stack trace: # 0 /srv/www/htdocs/vhosts/app.com/dompdf/src/Css/Stylesheet.php(1040): Dompdf\Frame\FrameTree->get_frames() # 1 /srv/www/htdocs/vhosts/app.com/dompdf/src/Dompdf.php(721): Dompdf\Css\Stylesheet->apply_styles(Object(Dompdf\Frame\FrameTree)) # 2 /srv/www/htdocs/vhosts/app.com/order_print.php(104): Dompdf\Dompdf->render() # 3 {main} thrown in /srv/www/htdocs/vhosts/app.com/dompdf/src/Frame/FrameTree.php on line 131
```

My current Code:

```
require_once 'dompdf/autoload.inc.php';

use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();

$dompdf->loadHtml('hello world');

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'landscape');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream("order.pdf", array("Attachment" => 0));
```

Former code with the github download had all require_once included as requested by the install guide; rest was the same. But does not work either.

```
require_once 'dompdf/lib/html5lib/Parser.php';
require_once 'dompdf/lib/php-font-lib/src/FontLib/Autoloader.php';
require_once 'dompdf/lib/php-svg-lib/src/autoload.php';
require_once 'dompdf/src/Autoloader.php';
Dompdf\Autoloader::register();
```

Any idea what is going wrong here ?

Thanks
Torsten

**Comment by bsweeney** [comment]
I did a quick test and wasn't able to reproduce. Seems like your script isn't loading the class files. You can try requiring the file with that class directly to see if the problem persists.

```
require_once 'dompdf/src/Frame/FrameTreeList.php';
```

Could be the user running PHP doesn't have access to the files or is looking in the wrong place (though I wouldn't expect that just from a PHP update).

**Comment by saslanis** [comment]
I have the same problem..
There is no such file in the files.
The line with the error points to "  return new FrameTreeIterator($this->_root);" a class named FrameTreeIterator, not FrameTreeList

There is nothing like FrameTreeList in the code at all..

what is going on?

**Comment by saslanis** [comment]
i copied FrameTreeIterator to FrameTreeList, changed the classe's name in the new file and all is ok! strangest of things

**Comment by bsweeney** [comment]
That's not a solution I would recommend. FrameTreeList isn't something referenced by Dompdf. Can't really help without additional info.
