### ISSUE TITLE
Border and values not matching in PDF

### ISSUE THREAD

**Issue by carlbinalla** [dompdf/dompdf#1790]
This happens when I use `display: inline-block` to wrap a table. The table itself is in the correct position *(shown as pink)*, but the border is shifted down. 

![table](https://user-images.githubusercontent.com/35289441/44979408-abb18980-af9f-11e8-8c0e-9ff9b0fd0e35.png)

Here is the code, the three table has the same code, so I removed the other two.

```
    <div style="display: inline-block;">
        <table class="table-bordered" style="background-color: pink;">
            <tbody>
                <tr>
                    <th colspan="2" class="text-left p-2">
                        <p class="mb-0">
                            Some Name
                        </p>
                        <p class="mb-0">
                            Some Date
                        </p>
                    </th>
                </tr>
                <tr>
                    <td class="text-left p-1">
                        DATA
                    </td>
                    <td class="p-1">
                        VALUE
                    </td>
                </tr>
                <tr>
                    <td class="text-left p-1">
                        DATA
                    </td>
                    <td class="p-1">
                        VALUE
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
```

When I use `display: inline-table` instead, this happens:

![untitled](https://user-images.githubusercontent.com/35289441/44979878-e10aa700-afa0-11e8-9972-448fe0a56c9b.png)

The table is alright, but it is not in line anymore. I'm doing this because I can't use the grid system of Bootstrap 4 *(uses flex)*, and I need small `div`s which are inline.

Any idea on possible solutions for this problem or the cause?

**Comment by bsweeney** [comment]
Could be related to #489. If you style the table with `border-collapse: separate;` does it render accurately?
