### ISSUE TITLE
Dompdf with Wordpress doesn't render image and css

### ISSUE THREAD

**Issue by BenartDesign** [dompdf/dompdf#1791]
I'm loading and rendering pdf in Wordpress, where I post a pdf variable by ajax with my html code.
It renders, but it doesn't render any css or images, like print below:
![image](https://user-images.githubusercontent.com/28695281/45117612-7f774380-b12c-11e8-8d76-22afce0dc66f.png)

This is how it looks in browser:
![image](https://user-images.githubusercontent.com/28695281/45117766-e39a0780-b12c-11e8-9c85-b79191ada497.png)

Can someone help me?

**Comment by bsweeney** [comment]
I guess it depends on how you're loading the content of your document. Dompdf load images relative to document if you don't provide a full URI (e.g. https://example.com/pic.jpg).

Do you have a sample of the relevant HTML and PHP?

**Comment by BenartDesign** [comment]
This is how I'm loading images: 

```
<div class="pdfimages">
			<img src="/home/storage/2/ea/99/inter3/public_html/TRH/talentoincluir.com.br/new/wp-content/uploads/2018/07/logoV1_principalHorizontal-1.png">
			<img src="/home/storage/2/ea/99/inter3/public_html/TRH/talentoincluir.com.br/new/wp-content/uploads/2018/07/Logo_StaCausa_Curvas-01757.png">
		</div>
```

I was loading them by attachment_id, but still had the same problem, so I tried like this. And this is my functions.php where it's generating pdf:

```
$html = $_POST['pdf'];
					$dompdf = new Dompdf();
					
					$dompdf->loadHtml($html);
					$dompdf->render();
					$output = $dompdf->output();
			 
					// Use the WordPress API to upload the file
					$upload = wp_upload_bits('relatorio_formulario.pdf', null, $output);
```

**Comment by bsweeney** [comment]
That path looks like it should work (so long as it points to the actual files). You could try to be more specific and add the "file://" to the front.

Those files are in the wp-content directory, so they should also be accessible via your web server. Have you tried that. In all cases, make sure dompdf has access to the temp directory specified in the settings. If there's an access issue there should be something in your logs (if you have logging enabled).
