### ISSUE TITLE
Custom font Laravel DOMPDF

### ISSUE THREAD

**Issue by kartono21** [dompdf/dompdf#1795]
Hi all,
I have problem. I already `@font-face` on my blade.php, in page custom font running well, but when I generate to PDF not working, can you help me?

Here's my controller

```
public function invoicePDF(Request $request)
  {
    $spps = Invoice::selectRaw('*, sum(amount) as total')
    ->where('invoice',$request->invoice)
    ->get();

    /*return view('invoice', ['spps'=>$spps]);*/
    $pdf = PDF::loadView('invoice', ['spps'=>$spps]);
    return $pdf->download($request->invoice.'.pdf');
  }
```

I use "barryvdh/laravel-dompdf": "^0.8.3",

**Comment by bsweeney** [comment]
Have you made sure your server has read/write access to the storage/fonts directory?

**Comment by bilogic** [comment]
Hi,

I'm facing some difficulty by the same subject, so I'm just going to continue here.

Laravel/Composer puts packages such as dompdf inside the ```vendor``` folder, and the TTF fonts are stored in the ```vendor/dompdf/lib/fonts``` folder. Now, this ```vendor``` folder is supposed to be disposable, i.e. it can get overwritten/delete and all we need to do is issue a ```composer update``` to restore it

Implicitly, it means we do not make changes directly to anything inside the ```vendor``` folder

1. How does one go about using custom fonts with dompdf and Laravel?
2. Can dompdf support storing and loading fonts outside the ```vendor``` folder?

Thank you
