### ISSUE TITLE
Wrong colors displayed with $pdf->page_text

### ISSUE THREAD

**Issue by alekseykuleshov** [dompdf/dompdf#1802]
Hi all,

I have an issue I've been struggling with for hours. Actually, I was trying to add page numbers and page total using the solution available and the issue occurs when I do this in some color. 

Here is the code: 

```
<?php
	require 'dompdf/vendor/autoload.php';

	use Dompdf\Dompdf;
	use Dompdf\Options;

	$options = new Options(['isHtml5ParserEnabled' => true]);

	$options->setIsRemoteEnabled(true);
	$options->setIsPhpEnabled(true);
	$dompdf = new Dompdf($options);
	$dompdf->setPaper('A4');

	$html = '
	<html>
	 <body>
		------------------------------------------------------------------------
		<script type="text/php">
			if (isset($pdf)) {
				$footer = $pdf->open_object();

				// get height and width of page
				$w = $pdf->get_width();
				$h = $pdf->get_height();

				// get font
				$font = $fontMetrics->get_font("helvetica", "normal");

				// grey color #909090, not visible
				$color = array(144, 144, 144);
				$pdf->page_text(30, 100, "Text of grey color", $font, 12, $color);

				// mustard color #909000, wrong color
				$color = array(144, 144, 0);
				$pdf->page_text(30, 150, "Text of mustard color, but it is different one displayed (yellow)", $font, 12, $color);

				// red color #FF0000, it is red
				$color = array(255, 0, 0);
				$pdf->page_text(30, 200, "Text of red color, it is red", $font, 12, $color);

				$pdf->close_object();
				$pdf->add_object($footer, "all");
			}
		</script>
		------------------------------------------------------------------------
	 </body>
	</html>';

	$dompdf->load_html($html);
	$dompdf->render();

	$dompdf->stream("hello.pdf");
```

And the result:
![screenshot--2018 09 20-13-36-30](https://user-images.githubusercontent.com/6037974/45813768-30104600-bcdc-11e8-9ee7-4371ac15e3e1.png)

So, the first one is grey color (144, 144, 144), and it's not even visible. The second one (144, 144, 0) is displayed in a wrong color. Third one (255, 0, 0) red seems to be correct. 

Dompdf version is 0.8.2. 

What am I doing wrong? Is this a bug in a library?

P.S. I know the solution with css counter for page number, but I need page total as well. 

Thank you,
Alex

**Comment by alekseykuleshov** [comment]
Since there were no answer here, I had to get to the bottom of the problem myself. The RBG color code is not appropriate here. So, instead of $color = array(144, 144, 144); it should be `$color = array(0.565, 0.565, 0.565);` The values can be taken here: https://encycolorpedia.com/909090 , **Color Space Conversions** section, **RYB** row. 

Hope this saves somebody's time.

Concerning the codebase, https://github.com/dompdf/dompdf/blob/master/src/Adapter/CPDF.php#L1035 should be definitely fixed, it's misleading.

**Comment by bsweeney** [comment]
The issue is not in the codebase but in the documentation. The CPDF library was initially released long before Dompdf and knows nothing about HTML. The color specification it works against is the decimal representing the percentage saturation in the RGB space.

BTW, thanks for the link to Encycolorpedia ... bookmarked.
