### ISSUE TITLE
Link box placement incorrect when text position is adjusted through styling

### ISSUE THREAD

**Issue by korimarik** [dompdf/dompdf#1803]
Hi everyone!
I use this great library but met some problem with <a> links.

This is my `Controller's` code:
`$pdf = PDF::loadView('admin.pdf.index_2', compact('client', 'borderNone'));`
`return $pdf->stream($client->id . ' - ' . $client->first_name . '.pdf');`
and this is `view` code:
`<span class="pdf-menu"><a href="https://google.com">Google</a></span>`
`<span class="pdf-menu"><a href="https://facebook.com">Facebook</a></span>`

But these (and other) links don't work in a generated file.
I'm thankful for any help!

**Comment by bsweeney** [comment]
Not much here to work with. Which version of dompdf? Do you have a sample PDF document?

**Comment by korimarik** [comment]
Sorry, here is more info:
`"barryvdh/laravel-dompdf": "^0.8.2",` - this is from my `composer.json` file.
And PDF example below
[example.pdf](https://github.com/dompdf/dompdf/files/2416049/example.pdf)

**Comment by bsweeney** [comment]
The links are there, but the box defining the clickable area in the PDF appears to be wrong. It probably has something to do with the styling. Can you post a sample HTML document?

**Comment by korimarik** [comment]
Please
[sample.pdf](https://github.com/dompdf/dompdf/files/2422664/sample.pdf)
[sample.blade.txt](https://github.com/dompdf/dompdf/files/2422666/sample.blade.txt)

**Comment by korimarik** [comment]
Hi, @bsweeney!
Do you have updates for me?

**Comment by bsweeney** [comment]
The blade, by itself, doesn't indicate an issue. Which version of Bootstrap are you using. I tried with the latest 3.x release and it rendered OK for the most part (the link box was a bit higher than it should be but otherwise fine).

Looks like you have some CSS in css/admin/dev_2.css that we'd also need to see.

**Comment by korimarik** [comment]
yes!
I have found that links area is higher than it needs to be. **This is the problem**

`
.main-content, .header-info {
    margin-bottom: 20px;
    width: 100%;
}
.main-content td {
    border: 1px dashed #ccc;
}

.pdf-left {
    /*font-size: 50%;*/
}

.pdf-right {
    font-size: 60%;
}

.pdf-logo {
    max-width: 160px;
    /*width: 1400%;*/
    /*width: 90%;*/
}
.pdf-mtop {
    margin-top: 30px;
}
.pdf-right-content .pdf-social img {
    width: 20px;
}
.pdf-right-content {
    text-align: right;
}
.pdf-social-block {
    margin-top: 4px;
}
.pdf-menu-block {
    text-align: center;
    color: #428bca;
}
.pdf-menu {
    font-size: 70%;
    /*border-right: solid #428bca 1px;*/
    margin-right: 3px;
}
.pdf-separator td {
    padding-bottom: 20px;
    border-bottom: 2px dashed #f0f;
}
.pdf-content-header {
    width: 25%;
    font-weight: bold;
}
.pdf-content-body {
    width: 75%;
}
.pdf-content-body textarea {
    height: 100px;
    width: 90%;
    resize: none;
}
.pdf-generate-button {
    text-align: center;
}
.pdf-generate-button a {
    text-transform: uppercase;
}
footer {
    text-align: center;
    margin-bottom: 20px;
    margin-top: 20px;
}
.pdf-info-error {
    color: #f00;
}
`

**Comment by korimarik** [comment]
`Bootstrap v3.0.3`

**Comment by bsweeney** [comment]
Thank you for confirming. We'll take a closer look as we have have time.

I took a quick look at the relevant code and nothing popped out at me. I'd like to get this next release out soon, but we'll look at the issue for the following release.
