### ISSUE TITLE
 ErrorException in table_cell_frame_reflower.cls.php line 103: A non-numeric value encountered

### ISSUE THREAD

**Issue by jannidhi** [dompdf/dompdf#1804]
Previous it was working fine but i had been made few changes in model->app->product.php folder and upload whole model folder than error occur

ErrorException in table_cell_frame_reflower.cls.php line 103:
A non-numeric value encountered.
please tell how to fix it.

**Comment by bsweeney** [comment]
You must be using an old version of dompdf because that file hasn't been used since 0.6.x. Suggest upgrading to the newer release.
