### ISSUE TITLE
Passing variable to page_script to render footer from page 2 to all other pages

### ISSUE THREAD

**Issue by giacomok** [dompdf/dompdf#1805]
Hi,  
I use version 0.7.0 and I have this need:  
I need a dynamic footer displayed from page 2 to all pages, and I need to passing variable to page_script.

This is what i tried:

    if ( isset($pdf) ) {
        $pdf->page_script('
             if ($PAGE_COUNT > 1) {
                 $font = $fontMetrics->getFont("Lato", "regular");
                 $pdf->page_text(290, $pdf->get_height() - 44, "{PAGE_NUM} di {PAGE_COUNT}", $font, 8, array(0,0,0));
                 $pdf->page_text(0, $pdf->get_height() - 44, "{$variable}", $font, 8, array(0,0,0));
             }
        ');
    }

But I get an error cause $variable is not defined.  
I would use footer class and css but in that case I was not able to hide the footer for the first page.

**Comment by bsweeney** [comment]
`page_script` is a string that is `eval`ed to produce output on the current page. The scope of the variable is outside the scope of the script when it runs, thus why you can't access it. There are two ways to fix this.

1. Concatenate it into your code string
```
...
$pdf->page_text(0, $pdf->get_height() - 44, "' . $variable . '", $font, 8, array(0,0,0));
...
```

2. Reference `$variable` as a global instead of a local
```
$GLOBALS['variable'] = 'dompdf';
...
if ( isset($pdf) ) {
    $pdf->page_script('
         if ($PAGE_COUNT > 1) {
             $font = $fontMetrics->getFont("Lato", "regular");
             $pdf->page_text(290, $pdf->get_height() - 44, "{PAGE_NUM} di {PAGE_COUNT}", $font, 8, array(0,0,0));
             $pdf->page_text(0, $pdf->get_height() - 44, $GLOBALS["variable"], $font, 8, array(0,0,0));
         }
    ');
}
```

**Comment by bilogic** [comment]
@bsweeney 

Can consider doing a callback instead? e.g.

```
$dompdf->forEachPage(function (...) {
    // do something here
});


```

**Comment by bsweeney** [comment]
@bilogic that would be ideal, yes. There is a request for that functionality in #1838.
