### ISSUE TITLE
Unexpected librarary in 0.8.2 distro: Sabberworm/PHP CSS parser

### ISSUE THREAD

**Issue by MarkMaldaba** [dompdf/dompdf#1808]
The [distribution file for DomPDF 0.8.2](https://github.com/dompdf/dompdf/releases/download/v0.8.2/dompdf_0-8-2.zip) contains the [Sabberworm PHP CSS parser](https://github.com/sabberworm/PHP-CSS-Parser), in `~/lib/php-css-parser`.

This library was not present in 0.8.1, and does not appear to be referenced in any of the code changes in made since that revision.  It also doesn't appear to be mentioned in the [commit history](https://github.com/dompdf/dompdf/compare/v0.8.1...v0.8.2) between those two releases, nor is any reference to `sabberworm` or `php-css-parser` found if I search this repository on Github.

A mistake?  If so, how to fix?  Recreate the 0.8.2 release, or replace it with 0.8.3?

**Comment by bsweeney** [comment]
Dompdf itself doesn't require it but the php-svg-library does. If was excluded from earlier releases that was an oversight. If you do not require SVG support you can remove both the dompdf/lib/php-css-parser and dompdf/lib/php-svg-lib directories.

**Comment by MarkMaldaba** [comment]
OK - Thanks for the update.  Might be worth adding that to the 0.8.2 release notes.

**Comment by bsweeney** [comment]
Yes, that's a good idea. Especially now that php-svg-lib is required for 0.8.3.

**Comment by bsweeney** [comment]
Updated the requirements and release documentation with some additional information.
