### ISSUE TITLE
Large image causes Error 502

### ISSUE THREAD

**Issue by mxx-lxg** [dompdf/dompdf#1811]
I'm trying to render a PDF with a fullscreen image as the background.

The problem is that when i use an image larger than at least 32KB, maybe more, the page crashes in the browser with a 502 Bad Gateway error.

Are there any limitations to image sizes?

The page itself seems to render. But it crashes upon $dompdf->stream('test.pdf');

**Comment by bsweeney** [comment]
There are no limitations built into Dompdf but the resources available on your server could be a limiting factor.

A 502 error is a server-level response. You can probably better determine why it fails by looking at the error produced by PHP.

Image format and how you're rendering the document can affect resource usage. Have you tried using a JPG?

**Comment by mxx-lxg** [comment]
The issue has been closed, but fyi: The way i rendered the PDF was suboptimal. I essentially opened the php file in a browser and downloaded the PDF, that started to fail once the PDF got too large.

Once i ran the php file in the CLI and streamed it's output to a PDF file it worked.
`php -f render.php > file.pdf`
