### ISSUE TITLE
Can't load dompdf using autoload.inc.php 

### ISSUE THREAD

**Issue by arimourao** [dompdf/dompdf#1812]
I'm facing this issue. I've downloaded dompdf zip file to use it in a legacy app where composer is not an option. I've followed the instructions to require autoload.inc.php and when I try to instantiate dompdf

`$dompdf = new Dompdf();`

I get the error "include(Dompdf.php): failed to open stream: No such file or directory". The path to dompdf is ok, already checked that.

**Comment by arimourao** [comment]
I was able to solve this. Here are the steps:

1. importing Dompdf namespace into the script using the use statement (not found in the documentation)
`use Dompdf/Dompdf`

2. importing Cpdf using the use statement in the autoload.inc.php

Steps to reproduce the issue: Download the latest release (0.8.2) and try to generate an PDF from HTML following the current documentation.

If someone from the project confirms this is an issue, I'll submit a pull request.

**Comment by bsweeney** [comment]
Which ZIP file did you download? Did you follow the instructions in the [README](https://github.com/dompdf/dompdf/blob/master/README.md) (particularly the Download and install section)?

There's a [quick start section](https://github.com/dompdf/dompdf/blob/master/README.md#quick-start) in the README and a [usage document](https://github.com/dompdf/dompdf/wiki/Usage#version-070-or-newer) in the wiki.

**Comment by arimourao** [comment]
Yes, I followed all the instructions. In fact, it was just missing the import for the Cpdf library in the autoload.inc.php . I've downloaded the last version (0.8.2).

**Comment by bsweeney** [comment]
You shouldn't have to load the Cpdf file directly. The autoloader should load the dependencies (html4parser, php-font-lib, php-svg-lib) and the Dompdf Autoloader.php file. Cpdf is referenced in Autoloader.php.

I downloaded a fresh copy of the 0.8.2 release and was unable to reproduce your error. The archive you downloaded may have gotten corrupted in transit or there could be a system issue.
