### ISSUE TITLE
Not showing the "\n" 

### ISSUE THREAD

**Issue by Julekot** [dompdf/dompdf#1814]
Hi guys!

So I have a website that dynamically retrieves data from the form and has to display them in PDF using the dompdf library. The problem occurs when there is "enter" in the textbox, the library simply does not display it. e.g.

What is in the textbox:

Hi im trying to make PDF
using dompdf library.

What is dompdf showing:

Hi im trying to make PDF using dompdf library.

I've tried:

```
{{$notes = nl2br($order->note)}} //It is just showing the <br /> instead of actually doing something
{{$space = '&#13'}} //giving the viable the value of strong enter
{{$note = str_replace("<br />", $space, $notes)}} // trying to replace <br /> with strong enter
<td class="padding-bottom note">{{$note}}</td> // It shows &#13 instead of "\n"

```
Does anybody know the solution?

Best Regards 
Julek

**Comment by Julekot** [comment]
This is the solution:
```
{!! nl2br(e($order->note)) !!}
```

**Comment by bsweeney** [comment]
Remember, Dompdf renders as your browser would. A line break is white space and white space is by default ignored in HTML. You can use the `nl2br` function or you can style your content with the appropriate CSS (`<span style="white-space: pre-line;">{!! e($order->note) !!}</span>`).
