### ISSUE TITLE
Problem with GoogleFont and Size

### ISSUE THREAD

**Issue by daylaborers** [dompdf/dompdf#1816]
Hi there,

i try to generate a PDF from an HTML Source with DomPDF and i have 2 Problems:
1. I use GoogleFonts `https://fonts.google.com/specimen/Ubuntu?selection.family=Ubuntu:300,400,500` and only the 300 Style is imported. The other both are ignored.
2. The HTML has an width of 595px and i center the content. But the content isn't in the middle, but slightly left.

Here ist the HTML Template:
```
<!doctype html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700" rel="stylesheet" type="text/css">
    <style type="text/css">
        body {
            font-family: Ubuntu, Helvetica, Arial, sans-serif;
            width: 595px;
            margin: 0;
            padding: 0;
        }

        p {
            margin: 15px 0;
        }

        .container {
            max-width: 420px;
            text-align: center;
            margin: 0 auto;
        }

        .container--wide {
            max-width: 520px;
        }

        .logo {
            width: 380px;
        }

        .title {
            font-size: 30px;
            font-weight: 300;
            margin: 20px 0 10px;
            text-transform: uppercase;
        }

        .open {
            font-size: 14px;
            font-weight: 300;
            text-transform: uppercase;
            margin: 10px 0 25px;
        }

        .m {
            border-bottom:1px solid #CBCBCB;
        }

        .day {
            font-size: 15px;
            font-weight: 400;
            text-transform: uppercase;
        }

        .title2 {
            font-size: 14px;
            font-weight: 300;
            color: #111111;
        }

        .text {
            font-size: 14px;
            font-weight: 300;
        }

        .branding {
            width: 270px;
            overflow: auto;
            margin: 20px auto 0;
        }

        .branding-qr {
            width: 75px;
            float: left;
        }

        .branding-info {
            width: 180px;
            float: left;
            text-align: left;
            font-size: 12px;
            padding-left: 15px;
            color: #6A6A67;
        }

        .branding-logo {
            display: block;
            height: 30px;
            margin-bottom: 5px;
        }

        .branding-info-link {
            font-weight: 500;
            color: #000;
        }
    </style>
</head>

<body>
<section class="container">
    <img src="{{ $logo }}" class="logo" />
    <h1 class="title">
        Überschrift
    </h1>
    <h2 class="open">
        {{ $from }} - {{ $to  }}<br />
    </h2>
</section>
<section class="container">
    @foreach ($ms as $day => $m)
        <div class="m">
            <h2 class="day">{{ $day }}</h2>
        </div>
    @endforeach
</section>
<section class="container container--wide">
    <p class="text">
        Ein Text
    </p>
    <p class="text">
        {{ $r->name }}
    </p>
</section>
<section class="container">
    <div class="branding">
        <img class="branding-qr" src="../../../assets/image/qr.png" />
        <div class="branding-info">
            <img class="branding-logo" src="../../../assets/image.svg" />
        </div>
    </div>
</section>
</body>

</html>
```

Cheers
Ralf

**Comment by bsweeney** [comment]
1. Right now dompdf only supports named font weights (see #675).
2. If you want to specify the width on the body you might want to also make the left and right margins "auto" otherwise if the body does not fill the page things will appear shifted left.

```
        body {
            font-family: Ubuntu, Helvetica, Arial, sans-serif;
            width: 595px;
            margin: 0 auto;
            padding: 0;
        }
```

**Comment by github-ravikant** [comment]
There are same problem, Google Font are not taken in pdf

**Comment by bsweeney** [comment]
@github-ravikant you'll need to be more specific, but first you should look at #675 (will be addressed in next release) and see if that's what's causing your issues.

**Comment by godbout** [comment]
i have the same issue after 0.8.3. 
0.8.3 works fine for me.

**Comment by bsweeney** [comment]
@godbout please try Dompdf 0.8.5. If that doesn't work feel free to open an issue with more detail or start a discussion on the [support forum](https://groups.google.com/forum/#!topic/dompdf).

**Comment by godbout** [comment]
yep, tried, doesn't work. works fine with 0.8.3 so i'll stay on that one for now. let me know if there's any info i could give you to narrow down the issue. thanks.

**Comment by bsweeney** [comment]
sample HTML would be a good start

**Comment by godbout** [comment]
got caught again with the same issue. updated Laravel to 7.x, had to update dompdf, breaks after 0.8.3. still can't find the reason why.

**Comment by bsweeney** [comment]
Dompdf is currently at version 0.8.5. If you update to the latest release and still have issue please open a new issue.

**Comment by godbout** [comment]
yes, the issue happens after 0.8.3. but i'm sorting it out. seems that for whatever reason, some font-weight (at least) values don't work anymore. my 600s fail, if i replace by _bold_ it works. not sure where it comes from, but i think it's gonna be manageable. thanks, and i'll add some info if i find something more.

**Comment by godbout** [comment]
so i've solved my issue by replacing all the font-weight numbers by their keyword values and that's it 😅️

**Comment by bsweeney** [comment]
Numeric font weight support is improved in the latest release but still needs work. Best to stick to keywords where you can.
