### ISSUE TITLE
Problems to load font

### ISSUE THREAD

**Issue by geeksilva97** [dompdf/dompdf#1819]
I tried adding a font with the follow code :

```
@font-face {
  font-family: "Neon";
  font-weight: normal;
  font-style: normal;
  src: url("http://localhost/certificados/font/y2kbug.ttf") format('truetype');
}
```

This works in HTML but don't works in PDF file.
I already researched in many places including here, but I did not find solution that worked. I need help. Thanks!

**Comment by geeksilva97** [comment]
Yes, all access granted.

**Comment by geeksilva97** [comment]
It showed no error. PDF executed without the desired font.

Unfortunately I no longer have the HTML file because I found the `mPDF` that served me well.

**Comment by bsweeney** [comment]
party on then
