### ISSUE TITLE
Optional parameters before required parameters

### ISSUE THREAD

**Issue by PHPGangsta** [dompdf/dompdf#1827]
Optional parameters (with default values) always should be at the end, otherwise they are not optional 😄 

See http://php.net/manual/en/functions.arguments.php
"Note that when using default arguments, any defaults should be on the right side of any non-default arguments; otherwise, things will not work as expected."

The following is a list I found, where an required parameter appears after optional parameters:

```
Dompdf\Canvas
function __construct($paper = "letter", $orientation = "portrait", Dompdf $dompdf);

Dompdf\Adapter\CPDF
public function __construct($paper = "letter", $orientation = "portrait", Dompdf $dompdf)

Dompdf\Adapter\GD
public function __construct($size = 'letter', $orientation = "portrait", Dompdf $dompdf, $aa_factor = 1.0, $bg_color = array(1, 1, 1, 0))

Dompdf\Adapter\PDFLib
public function __construct($paper = "letter", $orientation = "portrait", Dompdf $dompdf)

Dompdf\Renderer\AbstractRenderer
protected function _border_line($x, $y, $length, $color, $widths, $side, $corner_style = "bevel", $pattern_name, $r1 = 0, $r2 = 0)

Cpdf
function addImagePng($file, $x, $y, $w = 0.0, $h = 0.0, &$img, $is_mask = false, $mask = null)
function addPngFromBuf($file, $x, $y, $w = 0.0, $h = 0.0, &$data, $is_mask = false, $mask = null)
private function addJpegImage_common(&$data, $x, $y, $w = 0, $h = 0, $imageWidth, $imageHeight, $channels = 3, $imgname)
```

Changing the order breaks backwards-compatibility. Not sure what to do here...

**Comment by bsweeney** [comment]
Yes, this isn't great. It was probably written this way to avoid compatibility issues early on. I believe we always pass all values internally so operationally things should work OK. And if we didn't I'd expect a world of trouble to arise.

Regardless, the function argument definitions should be fixed. I think it'll need to wait for a post-0.8.3 release.

**Comment by swiffer** [comment]
This becomes deprecated in PHP 8

PHP Deprecated:  Required parameter $dompdf follows optional parameter $paper in ..\vendor\dompdf\dompdf\src\Adapter\CPDF.php on line 183
PHP Deprecated:  Required parameter $dompdf follows optional parameter $paper in ..\vendor\dompdf\dompdf\src\Canvas.php on line 27
PHP Deprecated:  Required parameter $img follows optional parameter $w in ..\vendor\dompdf\dompdf\lib\Cpdf.php on line 5546
PHP Deprecated:  Required parameter $data follows optional parameter $w in ..\vendor\dompdf\dompdf\lib\Cpdf.php on line 5892
PHP Deprecated:  Required parameter $imageWidth follows optional parameter $w in ..\vendor\dompdf\dompdf\lib\Cpdf.php on line 6236
PHP Deprecated:  Required parameter $imageHeight follows optional parameter $w in ..\vendor\dompdf\dompdf\lib\Cpdf.php on line 6236
PHP Deprecated:  Required parameter $imgname follows optional parameter $w in ..\vendor\dompdf\dompdf\lib\Cpdf.php on line 6236
PHP Deprecated:  Required parameter $pattern_name follows optional parameter $corner_style in ..\vendor\dompdf\dompdf\src\Renderer\AbstractRenderer.php on line 848

**Comment by Swop** [comment]
@bsweeney Any news on this?

Also trying to test our code for PHP 8 here (which uses dompdf).
This is indeed breaking since depreciations are now thrown by default in PHP8, which lead to a Fatal error.

**Comment by Swop** [comment]
Weve got the same issue which is mentionned in the PHP 8 support issue (https://github.com/dompdf/dompdf/issues/2242)

```
Required parameter $dompdf follows optional parameter $paper
```

**Comment by bsweeney** [comment]
I'm going to close this in favor of #2242. If you can please test with branch php8-compat.
