### ISSUE TITLE
page_script callback?

### ISSUE THREAD

**Issue by joshkel** [dompdf/dompdf#1838]
I'm trying to set up a slightly tricky header and footer (page numbers in each footer, no header on the first page, and user information on subsequent pages' headers). I see that I can use `page_script` to do different headers for different page numbers, but setting up PHP code as text feels awkward.

It would be nice of page_script supported invoking a callback (and passing the $pdf, $fontMetric, $PAGE_NUM, and $PAGE_COUNT parameters) as well as calling eval. If there's interest, I can put together a PR demonstrating this.

**Comment by bilogic** [comment]
@bsweeney could point out where is the existing callback structure? 

I had a quick look at PHPEval and I thought that just replacing it might do the job. Thanks.

**Comment by bsweeney** [comment]
The current callback support is triggered when entering/existing page and frame reference objects elements. You can see the existing implementation by looking at the [setCallbacks method](https://github.com/dompdf/dompdf/blob/v1.0.2/src/Dompdf.php#L1422-L1447) and searching the code for [_check_callbacks](https://github.com/dompdf/dompdf/search?q=_check_callbacks).

This is a different from the post-render page scripts implement by the Canvas adapter. But might be a good reference for the sake of consistency.
