### ISSUE TITLE
Avast false positive?

### ISSUE THREAD

**Issue by davidecesarano** [dompdf/dompdf#1839]
Hi,
today AVAST reports pdf file generated by DOMPDF as malware.

Following code:
```php
$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->render();
$dompdf->stream('namefile');
```

Avast reports "VBS:Malware-gen" when open or download the file.

I already tried this solution `$dompdf->stream('namefile', ['compress' => 0]);` but it didn't work.

**Comment by dva-re** [comment]
https://www.avast.ru/false-positive-file-form.php

I have sent a false positive report. Send and you, perhaps this will somehow speed up the review process.

**Comment by dva-re** [comment]
@davidecesarano 
Do you still have a problem? I checked before for virus check and he showed me that the virus is there, but now it does not.

**Comment by davidecesarano** [comment]
@dva-re 
problem solved.

Thanks.
