### ISSUE TITLE
Platform-specific differences in spacing and pagination

### ISSUE THREAD

**Issue by joshkel** [dompdf/dompdf#1840]
Since upgrading from Dompdf 0.6.0 beta 3 to 0.8.2, we're noticing differences in vertical spacing and in pagination. Specifically, in Windows 10, using PHP 7.0 installed via XAMPP, and using Dompdf 0.8.2 as installed via Composer, the behavior is identical to 0.6.0 beta 3. (A table with 3-4 large rows has its last row on a separate page, and a div consisting of a mix of paragraphs, br tags, and lists has more vertical space.) On the PHP 7.0 Docker image and in PHP 7 on RHEL 7, we see a few differences: the table is all on one page, and the div has less vertical spacing.

The Docker and Linux behavior actually looks a bit better, but I'd like to at least understand the differences in behavior. (And the differences are causing problems for our automated tests - we have some tests that extract text from PDFs and compare it with the expected results, and the differences in page breaks are causing the extracted text to look different.)

I tried doing some debugging of the Dompdf internals to understand how elements are laid out, but I'm having trouble making much headway. Any suggestions or advice would be appreciated.

**Comment by bsweeney** [comment]
I haven't done a lot of cross-platform testing lately. Is the problem with a specific font or does it happen with all fonts?

I'd have to think about this a bit before I could provide some good guidance one where to look.

**Comment by bsweeney** [comment]
Would need some sample HTML + CSS to really dig into this.
