### ISSUE TITLE
No Fonts....

### ISSUE THREAD

**Issue by MGParisi** [dompdf/dompdf#1841]
Ive looked for a solution.  There are many on here for this.  Sadly, nothing I try works.  My Font directory is writable, and the program saves these random character named fonts in it.  But it never renders.  I'm on Windows and we use the Google Fonts.   Ive replaced all the numbered weights with text.  Sadly, we will loose some details as not all of them have a text counterpart.

Still, it doesn't work. Is there anyway to get this to render?  I'm pounding my head.

Ive tried removing the new fonts from the font directory.  And the associated records with it.  But this didn't do anything.  

I'm not sure what else to do.  Is this possible?

**Comment by MGParisi** [comment]
Its weird, the whole page is white.  No images, no nothing.  Just the very top two images!

**Comment by bsweeney** [comment]
Can you share a sample HTML and the rendered PDF?

**Comment by MGParisi** [comment]
Im sorry, THIS issue has been resolved.  There is a chrome issue that has not.  The PDF wont open in chrome.  I believe it actually a but Im not sure.  I think this was an issue with malformed HTML, but it has been so long ago Im not sure.
