### ISSUE TITLE
Multiple tables creating blank pages

### ISSUE THREAD

**Issue by Ugurkan953** [dompdf/dompdf#1842]
I am trying to create a PDF file with multiple tables. Tables are not nested. But when the tables dont fit to one page it creates many blank pages and then renders all into one page. This doesnt look the same as issue #98 

Adding clear both at the end of the table doesnt work, page-break-inside: avoid doesnt work.

Is there a fix or workaround for this ? I don't want to put manually pagebreaks

**Comment by bsweeney** [comment]
We'd need to see a sample of the HTML that causes the issue before we could make any suggestions.

**Comment by bSushil** [comment]
I have written a template in blade. Sometimes, when the pdf file is created, it adds blank pages before and after the main content. Is there a way to fix this? Below is my html code:

@extends('emails.blank')
@section('content')
<table class="maintable">
    <tr>
        <td class="col-540 noborder">
            <table class="table">
                <tr>
                    <td class="col-300 noborder">
                        <h3>履歴書</h3>
                    </td>
                    <td class="col-200 text-right align-baseline noborder">
            　　        {{date('Y', strtotime($model->resume_date))}}年{{date('n', strtotime($model->resume_date))}}月{{date('j', strtotime($model->resume_date))}}日現在
                    </td>
                </tr>
            </table>
            <table class="table table-bordered">
                <tr>
                    <td class="col-60 align-center">ふりがな</td>
                    <td class="col-420">{{ $model->last_name_spell }} {{ $model->first_name_spell }}</td>
                </tr>
                <tr>
                    <td class="align-center">氏 名</td>
                    <td class=""><h1>{{ $model->last_name }} {{ $model->first_name }}</h1></td>
                </tr>
            </table>
        </td>
        <td class="col-160 noborder">
            <img src="{{imageUrl('users', $model->image)}}" alt="" height="215" width="180">
        </td>
    </tr>
    <tr>
        <td class="noborder" colspan="2">
            <table class="table table-bordered">
                <tr>
                    <td class="col-60">国籍</td>
                    <td class="col-160"></td>
                    <td class="col-60">生年月日（年齢）</td>
                    <td class="col-80">{{date('Y', strtotime($model->birthday))}}年{{date('n', strtotime($model->birthday))}}月{{date('j', strtotime($model->birthday))}}日現在</td>
                    <td class="col-40">性別</td>
                    <td class="col-120 text-center">
                        @if($model->sex == 'FEMALE')
                        <span>男</span>　・　<span class="roundedborder">女</span>
                        @else
                        <span class="roundedborder">男</span>　・　<span>女</span>
                        @endif
                    </td>
                </tr>
                <tr>
                    <td class="">ふりがな</td> 
                    <td colspan="3">{{ $model->current_address_spell}}</td>
                    <td colspan="2" class="nopadding text-center">
                        <span class="h6">電話</span>
                        {{ $model->phone }}
                    </td>
                </tr>
                <tr>
                    <td class="">現住所</td>
                    <td colspan="3">
                        {{ $model->current_postal_code}},</br>
                        {{ $model->current_prefecture}}{{ $model->current_city}},<br/>
                        {{ $model->current_address}}
                    </td>
                    <td colspan="2" class="nopadding text-center">
                        <span class="h6">メール</span>
                        {{ $model->email }}
                    </td>
                </tr>
                <tr>
                    <td class="">ふりがな</td>
                    <td colspan="3"></td>
                    <td colspan="2" class="nopadding text-center">
                        <span class="h6">電話</span>
                        {{ $model->phone }}
                    </td>
                </tr>
                <tr>
                    <td class="">連絡先</td>
                    <td colspan="3">
                    {{ $model->contact_postal_code}},</br>
                    {{ $model->contact_prefecture}}{{ $model->contact_city}},<br/>
                    {{ $model->contact_address}}
                    </td>
                    <td colspan="2" class="nopadding text-center">
                        <span class="h6">メール</span>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="noborder">
            <table class="table table-bordered">
                <tr>
                    <td class="col-60 text-center">年</td>
                    <td class="col-60 text-center">月</td>
                    <td class="col-550 text-center">学  歴 ・ 職  歴</td>
                </tr>
                @foreach($model->educations as $education)
                <tr>
                    <td class="text-center">{{ $education->year }}</td>
                    <td class="text-center">{{ $education->month }}</td>
                    <td class="">{{ $education->institution }}</td>
                </tr>
                @endforeach
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="noborder">
            <table class="table table-bordered">
                <tr>
                    <td class="col-60 text-center">年</td>
                    <td class="col-60 text-center">月</td>
                    <td class="col-550 text-center"> 免 許 ・ 資 格</td>
                </tr>
                @foreach($model->qualifications as $qualification)
                <tr>
                    <td class="text-center">{{ $qualification->year }}</td>
                    <td class="text-center">{{ $qualification->month }}</td>
                    <td class="">{{ $qualification->qualification_name }}</td>
                </tr>
                @endforeach
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="noborder">
            <table class="table table-bordered">
                <tr>
                    <td colspan="4" class="col-430 text-center">特技、自己PRなど</td>
                    <td colspan="2" class="col-240 text-center">通勤時間</td>
                </tr>
                <tr>
                    <td colspan="4" rowspan="5">{{ $model->motivation_text }}</td>
                    <td colspan="2" class="text-center">{{ $model->commute_time }}</td>
                </tr>
                <tr>
                    <td colspan="2" class="text-center">扶養家族（配偶者を除く）</td>
                </tr>
                <tr>
                    <td colspan="2" class="text-center">{{ $model->dependents }}人</td>
                </tr>
                <tr>
                    <td class="col-120 text-center">配偶者</td>
                    <td class="col-120 text-center">配偶者の扶養義務</td>
                </tr>
                <tr>
                    <td class="text-center">
                        @if($model->is_married == 1)
                        <span class="roundedborder">有</span>　・　<span>無</span>
                        @else
                        <span>有</span>　・　<span class="roundedborder">無</span>
                        @endif
                    </td>
                    <td class="text-center">
                        @if($model->support_spouse == 1)
                        <span class="roundedborder">有</span>　・　<span>無</span>
                        @else
                        <span>有</span>　・　<span class="roundedborder">無</span>
                        @endif
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="noborder">
            <table class="table table-bordered">
                <tr>
                    <td class="col-700 text-center"> 本人希望記入欄</td>
                </tr>
                <tr>
                    <td class="">{{ $model->special_request }}</td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<style>
body {
font-family: ipag;
}
</style>
@endsection

**Comment by bsweeney** [comment]
@bSushil it's hard to debug the issue with just the blade because we don't have the full context of the document (the layout, the content of the table, the relevant CSS). Can you provide a sample of the actual HTML + CSS being parsed by Dompdf?
