### ISSUE TITLE
word-break

### ISSUE THREAD

**Issue by Ludoviccharruau** [dompdf/dompdf#1845]
Does the CSS _word-wrap:break-word_ works in dompdf. I have the impression that the size of my _td_ is systematically recalculated as soon as the word is too long.

**Comment by riliwanrabo** [comment]
Any luck on this?

**Comment by bsweeney** [comment]
I believe this may have been fixed in 0.8.3 (c8a1a93). Are you able to test?

**Comment by codevio** [comment]
Yeah,` word-wrap:break-word` is working.

**Comment by bsweeney** [comment]
If anyone sees otherwise feel free to follow up and we'll look into this more.
