### ISSUE TITLE
http error 500

### ISSUE THREAD

**Issue by Kakou347** [dompdf/dompdf#1847]
Hello,

I followed the guide start but I have "HTTP ERROR 500" when I want generate the PDF.

`<?php

     require_once ''.$_SERVER['DOCUMENT_ROOT'].'/interaction/dompdf/autoload.inc.php';

     use Dompdf\Dompdf;
     use Dompdf\Options;

     $options = new Options();
     $options->set('isPhpEnabled', true);
     $dompdf = new DOMPDF($options);
     $dompdf->setPaper('A4', 'portrait');
     $dompdf->loadHtml(file_get_contents('bail.php'));
     $dompdf->render();
     $dompdf->stream('bail-'.$_GET['id'].'.pdf');`

And bail.php I have just : 

`<h1>My bail</h1>`

I need you. Sorry for my bad english, I'm not english.
Thanks you !

**Comment by bsweeney** [comment]
Would need to know the actual error produced. 500 is what the server sends back but PHP should be reporting something more specific. Check your logs.
