### ISSUE TITLE
Remove header and footer

### ISSUE THREAD

**Issue by Hari1110** [dompdf/dompdf#1853]
how to generate pdf by using dompdf so that only the  body section of web page is shown in pdf and  excluding header and footer section of the page

**Comment by bsweeney** [comment]
You would do this by using a print style to hide those elements. You could, for example, add a class to those elements to indicate they should not be displayed when printing the PDF. Using the class `no-print` you would just add the following to your CSS.

```
@media print {
  .no-print {
    display: none;
  }
}
```
