### ISSUE TITLE
DOMpdf -failed to load PDF document on server 

### ISSUE THREAD

**Issue by sarumathiramasamy** [dompdf/dompdf#1855]
DOMpdf 0.8.2 with php version 7.1 works on localhost not working on server while downloading a pdf document. Showing error forbidden and failed to load a document .

![image](https://user-images.githubusercontent.com/43061815/49778028-1829ea80-fd3e-11e8-95cb-720fbd4fbf53.png)

**Comment by bsweeney** [comment]
Did you upload dompdf from your local to your server or install fresh. Sometimes this can cause issues. Can you get the actual error from the server logs?

**Comment by Esteban26** [comment]
Hi @bsweeney I'm trying to install codeigniter 3.1.10, with dompdf 0.6 and I'm facing the same issue, I'm running the composer install command at the server but  I'm getting the same issue, any other reason about it?

**Comment by Esteban26** [comment]
/application/config/config.php

$config['composer_autoload'] = "./vendor/autoload.php";

/system/libraries/Pdfgenerator.php

`<?php
defined('BASEPATH') OR exit('No direct script access allowed');

define('DOMPDF_ENABLE_AUTOLOAD', false);
require_once("./vendor/dompdf/dompdf/dompdf_config.inc.php");

class Pdfgenerator {

  public function generate($html, $filename='', $stream=TRUE, $paper = 'A4', $orientation = "portrait")
  {
    $dompdf = new DOMPDF();
    $dompdf->load_html($html);
    $dompdf->set_paper($paper, $orientation);
    $dompdf->render();
    if ($stream) {
        $dompdf->stream($filename.".pdf", array("Attachment" => 0));
    } else {
        return $dompdf->output();
    }
  }


}`

**Comment by bsweeney** [comment]
@Esteban26 The code looks fine at face value. Unless you can provide some additional information such as any PHP errors recorded I can't offer much advice (especially since I do not use codeigniter).

You're already using composer, maybe try the 0.8.3 release?

**Comment by Esteban26** [comment]
Hi @bsweeney I found the reason of the issues I was facing, so I'll share my experience, 

With version 0.6 I noticed dompdf was failing to create the pdf file since I've installed php7 on my server and it seems that 0.6 version is using some deprecated functions so I decided to upgrade to version 0.8.

Using 0.8.3 version I was getting the same error while trying to open the resultant pdf file, so when I opened the PDF file with VS i saw an error, in my case the autoload.inc.php file was not found, so after checking the documentation  I noticed that file was removed in recent commits and now we've to require all the files individually so, would be great if you could update this document from the project wiki.

https://github.com/dompdf/dompdf/wiki/Using-Dompdf-in-CodeIgniter-3.x

**Comment by bsweeney** [comment]
@Esteban26 thanks for the pointer. That document was written by the community and while I reviewed it initially I haven't maintained it. It is definitely out of date and I would consider it wrong from the start. I'm not a CI user so can you help me out? The instructions utilize composer to install Dompdf but then ignore the composer autoloader in favor of the Dompdf autoloader. Is that common with CI?

**Comment by Esteban26** [comment]
On my case I had to execute the composer install and it downloaded the dompdf packaged, then I had to execute another composer install command to download the complete list of packages since they were not downloaded with the first execution.

**Comment by Abuabdelah** [comment]
Running **ob_end_clean();** before stream fixed the issue for me.

```
ob_end_clean();
$dompdf->stream($invoiceFileName, array("Attachment" => false));
```

**Comment by darkterminal** [comment]
@Abuabdelah thanks for ur solution! it's work like charm :smile_cat:

**Comment by CaterinMorales** [comment]
@Abuabdelah  despues de horas buscando tu solución fue la que me funciono, muchas graciass ♥

**Comment by Abuabdelah** [comment]
@darkterminal, @CaterinMorales
PEACE be upon those who follow guidance.

**Comment by justryingtocode** [comment]
hello i am using dompdf version 0.8.2 in my codeigniter app php. It fails to load pdf on the server side while i am using NGNIX server,error

**Comment by soumyajyoti-divii** [comment]
> false

no mine isn't working,
here is my code, please check.
<?php require_once $_SERVER['DOCUMENT_ROOT'].'./projects/it_outsourcing_2/goldenq/vendor/dompdf/autoload.inc.php';
use Dompdf\Dompdf;
$dompdf = new DOMPDF();
$html = "<table border='1' width='100%' style='border-collapse: collapse;'>
        <tr>
            <th>Username</th><th>Email</th>
        </tr>
        <tr>
            <td>yssyogesh</td>
            <td>yogesh@makitweb.com</td>
        </tr>
        <tr>
            <td>sonarika</td>
            <td>sonarika@gmail.com</td>
        </tr>
        <tr>
            <td>vishal</td>
            <td>vishal@gmail.com</td>
        </tr>
        </table>";
$filename = "newpdffile";
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
ob_end_clean();
$dompdf->stream($filename,array("Attachment"=>false));
?>

**Comment by lucaslimafons** [comment]
@Abuabdelah you just saved my life buddy, omfg!!! Thanks!

**Comment by jazen4p** [comment]
> > false
> 
> no mine isn't working,
> here is my code, please check.
> 
> ```
> <?php require_once $_SERVER['DOCUMENT_ROOT'].'./projects/it_outsourcing_2/goldenq/vendor/dompdf/autoload.inc.php';
> use Dompdf\Dompdf;
> $dompdf = new DOMPDF();
> $html = "<table border='1' width='100%' style='border-collapse: collapse;'>
>         <tr>
>             <th>Username</th><th>Email</th>
>         </tr>
>         <tr>
>             <td>yssyogesh</td>
>             <td>yogesh@makitweb.com</td>
>         </tr>
>         <tr>
>             <td>sonarika</td>
>             <td>sonarika@gmail.com</td>
>         </tr>
>         <tr>
>             <td>vishal</td>
>             <td>vishal@gmail.com</td>
>         </tr>
>         </table>";
> /* POSITION AFTER (ob_end_clean();)
> $filename = "newpdffile";
> $dompdf->loadHtml($html);
> $dompdf->setPaper('A4', 'landscape');
> $dompdf->render();
> $dompdf->stream($filename,array("Attachment"=>false));
> ?>
> ```
can you try with re-positioning the code ?

**Comment by cikal** [comment]
@Abuabdelah you're live saver man.. finaly after **1 hour** and **10 minute** fighting.. LoL :tada:

**Comment by HoussemBenmammar** [comment]
> Running **ob_end_clean();** before stream fixed the issue for me.
> 
> ```
> ob_end_clean();
> $dompdf->stream($invoiceFileName, array("Attachment" => false));
> ```



> Running **ob_end_clean();** before stream fixed the issue for me.
> 
> ```
> ob_end_clean();
> $dompdf->stream($invoiceFileName, array("Attachment" => false));
> ```

you are a life saver thank you

**Comment by HoussemBenmammar** [comment]
@wpplumber , ob_end_clean(); saved me thanks a lot

**Comment by harrisrehmanmalik** [comment]
thanks it fix my error :).

**Comment by DavronDave** [comment]
> Abuabdelah

Hi, Where is code? can you write me a code
