### ISSUE TITLE
Using DejaVu makes PDFs not editable.

### ISSUE THREAD

**Issue by taniaivanova** [dompdf/dompdf#1860]
I am using dompdf for creating PDFs for a long time, and it was working very good ... till I decided to change some font to DejaVu, in order to get some Turkish characters. 
So, I obtained a good-looking  PDF in all viewers ..... but I cannot edit this PDF in Adobe Acrobat PRO. It can be opened, but I receive a message that there is an error in the file.
If I put back the default font – the result PDF can be edited in the Adobe without any problem.
I attach a simple PDF file where I use a DejaVu font in only one line. And this file can be viewed but cannot be edited in Adobe.
Any idea?
[576.pdf](https://github.com/dompdf/dompdf/files/2689928/576.pdf)

**Comment by bsweeney** [comment]
We have had some issues in the past related to InDesign (#517). This could be related. Have you tried generating your PDF with font sub-setting disabled?

**Comment by taniaivanova** [comment]
I have sub-setting by default:
def("DOMPDF_ENABLE_FONTSUBSETTING", false);

And just to check - I change it to true - and the result is the same, but with smaller PDF.

**Comment by taniaivanova** [comment]
Thank you for the help.
Neither I have Adobe PRO - I had to install 7-day evaluation copy just to see the problem :-)
But with this file the preflight tool dosn´t work. Almost all tools inside Adobe PRO don't work. It looks like the file is corrupted.

**Comment by bsweeney** [comment]
OK, thanks. I'll run it through some online validators and see what we can do.

**Comment by bsweeney** [comment]
The upcoming release of Dompdf has some improvements with how we handle font and font subsetting. If you're still around and able can you check out if a PDF rendered using the code from the develop branch produces an editable PDF?
