### ISSUE TITLE
Request for CSS element1~element2 Selector

### ISSUE THREAD

**Issue by KarlMacz** [dompdf/dompdf#1864]
I am currently using version 0.8.2 on my project. I tried using the _`element1 ~ element2`_ selector and it doesn't seem to work. After that, I read the CSSCompatibility Wiki and found out that this is not in the list of selectors.

Is there any way this selector be added?

**Comment by bsweeney** [comment]
Should be doable, though it'll have to wait for the next release.

**Comment by Mellthas** [comment]
Support was added with version 1.1.0.
