### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by DigitalSolo** [dompdf/dompdf#1865]
I just upgraded to PHP 7.3.0;  I'm now getting these PHP Warnings when I create a pdf:
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in vendor\dompdf\dompdf\src\Dompdf.php on line 609
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in vendor\dompdf\dompdf\src\Dompdf.php on line 630
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in vendor\dompdf\dompdf\lib\Cpdf.php on line 467
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in vendor\dompdf\dompdf\lib\Cpdf.php on line 474
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in vendor\dompdf\dompdf\lib\Cpdf.php on line 481
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in vendor\dompdf\dompdf\lib\Cpdf.php on line 488
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in vendor\dompdf\dompdf\src\Css\Stylesheet.php on line 1360
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in vendor\dompdf\dompdf\src\Renderer\Text.php on line 140

**Comment by PHPGangsta** [comment]
Already fixed, see #1825 
Please use Dompdf 0.8.3, all of the PHP 7.3 problems should be fixed in that version.

**Comment by DigitalSolo** [comment]
Yes, sorry I noticed the update AFTER I submitted the issue.
