### ISSUE TITLE
Inherited styles should be computed values

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#187]
_Original author: fabien.menager (September 14, 2010 20:01:29)_

Actually, it seems that the inherited values are not the computed ones, whereas it should be so.

http://www.w3.org/TR/CSS2/cascade.html#value-def-inherit

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=181_

**Comment by bsweeney** [comment]
This has been addressed by a [number of commits leading up to the 0.8.4 release](https://github.com/dompdf/dompdf/compare/db8a70abcaccc17152af658ce70dd6c5026eb87b...c4f39cd16db8fc8e5921fe1820d06164696cc102).
