### ISSUE TITLE
Wrong pdf rendering on table

### ISSUE THREAD

**Issue by exstreme** [dompdf/dompdf#1871]
Sample of HTML
http://eclecticgeek.com/dompdf/debug.php?identifier=7a3190b709be5be3d72c28334dfd472b

**Comment by bsweeney** [comment]
You're using tables for layout, which I wouldn't recommend with Dompdf right now. The main limiting factor being that it does not currently support splitting a table cell between pages (#98). You're not really doing much with that external table in your sample so I'd suggest leaving out the external table completely.
http://eclecticgeek.com/dompdf/debug.php?identifier=fc9b4b26bced06224df5a8e326815136

Also, update to 0.8.3. It has some improvements to table handling. I haven't yet done this with the debugger.
