### ISSUE TITLE
Version 0.8.3 images are not rendered

### ISSUE THREAD

**Issue by christian987** [dompdf/dompdf#1873]
Hello,

first of all i am very thankful for your beautiful and open source work!

I was using version 0.6 a long time. Now i did an update to 0.8.3 everything works just fine, instead of the images.

My Code:
```
	$options = new Dompdf\Options();
	$options->set('isRemoteEnabled', true);
	$options->set('isPhpEnabled', true);
	$options->set('enable_font_subsetting', true);

	$dompdf = new Dompdf\Dompdf($options);
	$context = stream_context_create([ 
		'ssl' => [ 
			'verify_peer' => FALSE, 
			'verify_peer_name' => FALSE,
			'allow_self_signed'=> TRUE
		],
		'http' => array(
			'method'=>"GET",
			'header'=>"Accept-language: en\r\n" .
			"Cookie: bw_rds=".$_POST['bw_rds']."\r\n"
		)
	]);

	$dompdf->setHttpContext($context);
	$dompdf->loadHtml($html);
	$dompdf->setPaper('A4', 'portrait');
	$dompdf->render();
	$dompdf->stream();
```

The images are not direct links. They are called with a php-file and then streamed
e.g: https://www.mydomain.com/file.php?image=21678

Worked in 0.6 but does not work in 0.8.3 for me

Hope you can help.

Best regards

**Comment by christian987** [comment]
Okay i found a quick soultion:
src/Image/Cache.php Line 97

**replace**
`list($image, $http_response_header) = Helpers::getFileContent($full_url, $dompdf->getHttpContext());`
**with**
`set_error_handler(array("\\Dompdf\\Helpers", "record_warnings"));
$image = file_get_contents($full_url, null, $dompdf->getHttpContext());
restore_error_handler();`

**Comment by bsweeney** [comment]
Are there no other changes to your system? And your file is being accessed via the web (i.e. not using a local file path? Any errors or anything from PHP?

My initial guess was that maybe dompdf is using the curl library. We added the getFileContent abstraction so that we could support curl usage when allow_url_fopen was false. Our implementation of curl does not currently support custom contexts. But the fact that you can switch to `file_get_contents` says that's probably not the case.

**Comment by CodeWorldUser** [comment]
> Okay i found a quick soultion:
> src/Image/Cache.php Line 97
> 
> **replace**
> 
> ```
> list($image, $http_response_header) = Helpers::getFileContent($full_url, $dompdf->getHttpContext());
> ```
> **with**
> 
> ```
> set_error_handler(array("\\Dompdf\\Helpers", "record_warnings"));
> $image = file_get_contents($full_url, null, $dompdf->getHttpContext());
> restore_error_handler();
> ```
For me image is rendering but color scheme is changed to black and white.
not worked me. Suggest some other way.

**Comment by bsweeney** [comment]
@CodeWorldUser you should open a new issue so we can discuss separately.

**Comment by CodeWorldUser** [comment]
I have already opened a my own issue as fresh , Please check this :-> 
https://github.com/dompdf/dompdf/issues/1877
