### ISSUE TITLE
Add new pages after render

### ISSUE THREAD

**Issue by djs84** [dompdf/dompdf#1876]
It is possible to add one page or several pages **before the last page** after rendering and before output?

I always want to have an even number of pages in my pdf.

Example:
```
1. Page 
2. Page  (<div style="page-break-before:always;">CONTENT</div>)
3. Page (<div style="page-break-before:always;">CONTENT</div>)
4 - ?? Page (<div style="page-break-before:always;">CONTENT</div>)
??. Last Page (<div style="page-break-before:always;">CONTENT</div>)
```

if i have only 17 pages, a page should be inserted between the last page and the penultimate page.

Thx

**Comment by bsweeney** [comment]
You can easily do this via embedded script. First make sure you have embedded script enabled (`$dompdf->set_option('isPhpEnabled', true);`). Then add the following code inside your last-page div _before_ any content:

```
<script type="text/php">
if ($pdf && $PAGE_NUM % 2 == 1) {
  $pdf->new_page();
}
</script>
```
