### ISSUE TITLE
[suggestion] Special markups

### ISSUE THREAD

**Issue by evsar3** [dompdf/dompdf#1880]
What about implementing special markups to be parsed by the engine? Eg:
`<page-header>...</page-header>`
`<page-footer>...</page-footer>`
`<pdf-header>...</pdf-header>`
`<pdf-footer>...</pdf-footer>`
Then the engine can repeat the contents of these special tags on the right spot.

Some special placeholders should also be very handy, like:
`{{PAGE_COUNT}}`
`{{PAGE_NUM}}`

I wish I know more about PDF format so I could help more, but for now, I just have ideas to offer.

😉

**Comment by bsweeney** [comment]
It would be preferable to avoid this type of mark-up in lieu of adding better CSS support. We could probably accommodate this type of setup via named pages and some other CSS features.
