### ISSUE TITLE
DomPDF turkish character not display (ğ,ş)

### ISSUE THREAD

**Issue by ATMCgrafik** [dompdf/dompdf#1881]
Hi, i have been using dompdf in my project. But i can't displayed turkish character. for exp; (ğ,ş). Can you help me please.

**Comment by fahn** [comment]
did you read this howto?
https://github.com/dompdf/dompdf/wiki/UnicodeHowTo

**Comment by mustafakucuk** [comment]
I fixed with this code.

```
<style>
    body { font-family: DejaVu Sans; }
</style>
```
