### ISSUE TITLE
PROBLEM UPDATING DOMPDF

### ISSUE THREAD

**Issue by belairclick** [dompdf/dompdf#1882]
Hello! I'm trying to update the version of dompdf and it gives me the following error and I do not know why, if some one can help
![captura de pantalla 2019-01-21 a las 19 58 19](https://user-images.githubusercontent.com/42769988/51493995-7b844f00-1db7-11e9-9ebc-a7c7ec67002f.png)
![captura de pantalla 2019-01-21 a las 19 55 28](https://user-images.githubusercontent.com/42769988/51493996-7b844f00-1db7-11e9-8d6e-108ddc7412d7.png)

**Comment by bsweeney** [comment]
We don't maintain any plug-ins for WordPress so I couldn't say. Have you contacted the author?
