### ISSUE TITLE
Force table row to split across 2 pages

### ISSUE THREAD

**Issue by faheemhameed** [dompdf/dompdf#1883]
Hi there,

I have a simple table with rows tds with big text content... For ex:

`<!DOCTYPE html>
<html>
    <head>
   </head>

    <body>
        <table>
            <thead>
                <tr>
                    <th>PRODUCT</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                <td>1-----
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                </td>
                </tr>
                <tr>
                <td>2-----
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                </td>
                </tr>
                <tr>
                <td>3-----
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                </td>
                </tr>
                <tr>
                <td>4-----
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                </td>
                </tr>
                <tr>
                <td>5-----
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
                </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>` 

<img width="1170" alt="screenshot 2019-01-23 at 6 01 51 pm" src="https://user-images.githubusercontent.com/990088/51599046-b7dfb880-1f39-11e9-908f-f5600c8f1841.png">

When I print it using A4 size page, I would like to have a part of 4th row print in the first page in the available space and then continue to print the rest of the text in the next page. But it seems that all of the 4th row is moved to the second page. Is there any way to force this as per my requirement?

Thanks for your quick feedback..

Cheers!!

**Comment by faheemhameed** [comment]
I have tried the following css for the page breaks:

`            table {
                page-break-inside: always;
            }

            table tr {
                page-break-inside: always;
            }

            table tr td {
                page-break-inside: always;
            }`

But they never helped me to split a row between 2 pages.

Can anyone please confirm that, with the current version, it's achievable or not.
If I can't then I will have to find other plugins. 

Please help!!

**Comment by bsweeney** [comment]
Dompdf (currently at 0.8.3 as of this post) does not support splitting table rows across pages. This is a long-standing issue with Dompdf (ref #98).

Your particular content, if it follows the sample you provided, does not really look to need a table structure since it only has one cell per row. You could fairly well replicate the structure using simple DIV elements.

Only gotcha is that table header. If the sample truly reflects your output you could use a page header instead.

Something along the lines of the following:

```
<!DOCTYPE html>
<html>

<head>
  <style>
    @page { margin-top: 50px; }
    #header { position: fixed; top: -50px; left: 0px; right: 0px; padding: 10px; text-align: center; font-weight: bold; }
  </style>
</head>

<body>

  <div id="header">
    PRODCUT
  </div>
  
  <div>
  1-----
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
    MCHBMES1 -- MCHBMES1 -- MCHBMES1 -- MCHBMES1 --
  </div>

</body>

</html>
```

**Comment by faheemhameed** [comment]
@bsweeney Thanks for your reply and for your suggestion.

Actually I wanted to use muti-column table and gave you my html as an example. I am aware about the div which can split across pages.

Finally I have used TCPDF to achieve this.

Thanks.

**Comment by abdallamarojillo** [comment]
@faheemhameed I'am currently having the dompdf issue of not splitting table row when the content is large.
May I know how you solved it using TCPDF

**Comment by kertaskids** [comment]
Having the similar issues. TCPDF looks promising in this case.

**Comment by reineltchris** [comment]
anything new about that ?
I want to achive the same

**Comment by bsweeney** [comment]
Nothing yet though I had started to work on it at some point. The only changes I made were to remove the restriction of splitting within a table cell, so minor changes so far. But I'll resurrect that in a branch so that if anyone's interested they can think about it some more.

**Comment by ronel-glitch** [comment]
Is there an update about this issue?

**Comment by acgtwentyone** [comment]
I also would like to know if there's an update on this issue.
