### ISSUE TITLE
Rendering Issue from HTML to PDF

### ISSUE THREAD

**Issue by khokandc** [dompdf/dompdf#1885]
I am using DOMPDF for invoicing purpose. 
Currently, we are facing these two issues:

- When we are using a custom font (such as Japanese, Arabic, Chinese), it is rendering in HTML format. However, when it is converting into PDF, the font is not getting displayed. 

- Now, also we are adding a logo on the invoice. We are getting the URL of the jpeg file, but it is not getting rendered in pdf.
Can you please guide us how to solve this?

**Comment by armansheikh** [comment]
Hi @khokandc,
Could you please post your code that you are using?

**Comment by bsweeney** [comment]
As mentioned by Arman, we'll need more details.

A few notes:
 - Dompdf should be able to use custom fonts, so long as they're in TTF
 - For remote images, have you changed the configuration to allow remote resource access?
 - Does the user running Dompdf (e.g. web server process) have read/write access to the directories specified by tempDir, fontDir, and fontCache?
