### ISSUE TITLE
Receipt print margin right

### ISSUE THREAD

**Issue by dennisdc** [dompdf/dompdf#1888]
We are trying to print to a receipt with 72mm width but the page is printing at the right with only 2 starting chars (seems like there is a margin on the left with more than 1,5inch where the receipt is close to 2inch).  We tried setting the body and page size in the layout, setting the options dpi, almost everything but nothing worked.  what are we missing?  As far as I understand, the width should be somewhere to $dompdf->setPaper([0,0,226.77, 800.00]) but this is not working.

**Comment by bsweeney** [comment]
Do you have a screen shot of the output so I can see what's going on. There is a default margin, so in addition to setting the page size did you set margins?

```
<style>
@page {
  size: 72mm 282mm;
  margin: 0em;
}
</style>
```
