### ISSUE TITLE
End of PDF broken with page-break-before and many div (0.6.0 beta1) 

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#190]
_Original author: sylvain (September 21, 2010 14:18:55)_

<b>What steps will reproduce the problem?</b>
1. With DOMPDF 0.6.0 beta1 (DOMPDF_ENABLE_REMOTE =&gt; true)
2. use the following HTML : http://pastebin.com/zbvN3dZg
3. with linked Stylesheet : http://pastebin.com/EaYDTkn6 (document.css head link)

<b>What is the expected output? What do you see instead?</b>

At the end of file we expect to have the &quot;Contrib TEST 74 div&quot; on a single Page and a last page contaning text &quot;DISCLAIMER DISCLAIMER DISCL...&quot;

But instead the &quot;Contrib Test 74&quot; is Broken on 3 pages and the Disclaimer Text is behind the broken div.

<b>What version of the product are you using? On what operating system?</b>
Using 0.6.0 beta1 runing on an xubuntu WebServer (apache2/php5)

Please provide any additional information below :

Found a bug wich may be linked with &quot;page-break&quot; style options bug.

After a certain number of div having &quot;page-break-before: left;&quot; the pdf broke all the HTML organisation. A div is split over 3 pages instead of being on a single one and the next content became a background of the broken pages

You can see on the attached PDF that the bug appears after the 10th page.

[tmp_21_09_2010-154414.pdf](https://github.com/dompdf/dompdf/files/7476427/tmp_21_09_2010-154414.pdf)

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=184_

**Comment by bsweeney** [comment]
Unable to fully reproduce because I don't see the "disclaimer" text in the source documents. The rendering of the actual content, however, appears to be OK with 1.0.2 and much improved with 1.1.0.
