### ISSUE TITLE
How to remove HTTP request from pdf

### ISSUE THREAD

**Issue by mgarcia96** [dompdf/dompdf#1906]
Hey there, how can I remove que HTTP status from the pdf?

HTTP/1.0 200 OK Cache-Control: no-cache, private Date: Mon, 18 Mar 2019 10:12:15 GMT 
![image](https://user-images.githubusercontent.com/6561770/54523036-e04ec680-496e-11e9-866c-5aa89b411f0f.png)

My options (Using symfony):

```
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');
        $pdfOptions->set('isRemoteEnabled',true);      
        
        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);
        
        // Retrieve the HTML generated in our twig file
        $html = $this->render('@Base/Product/pdf.twig', [
            'locale' => $request->getLocale(),
            'product' => $product,
            'category' => $category,
        ]);
        
        // Load HTML to Dompdf
        $dompdf->loadHtml($html);
        
        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (force download)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => false
        ]);
```

**Comment by karameloso** [comment]
$dompdf->loadHtml($html->getContent());

**Comment by mgarcia96** [comment]
> try `$dompdf->loadHtml($html->getContent());`

Blank page

**Comment by bsweeney** [comment]
The header is being captured in the stream sent do Dompdf. I don't use Symfony so I can't say for sure, but have you tried using `renderView` instead of `render` ([ref](https://tools.belchamber.us/symfony-rendering-a-twig-template-without-headers-for-special-template-output/))?

**Comment by mgarcia96** [comment]
> The header is being captured in the stream sent do Dompdf. I don't use S

Same, Blank page

**Comment by bsweeney** [comment]
What do you get if you just return the value of $html?

**Comment by mgarcia96** [comment]
> What do you get if you just return the value of $html?

The HTML, but the pdf is blank

**Comment by bsweeney** [comment]
This is probably something you should ask on a symphony forum. Pretty sure the HTTP header should only render to the PDF if it's captured in the $html variable.

**Comment by dzschille** [comment]
@bsweeney i had the same problem using Symfony 4. Using `renderView` instead of `render` fixed it. Thanks!

**Comment by Hexa-IT** [comment]
The `->getContent()` solved my problem in Symfony:

`$domPdf->loadHtml($this->render('example.html.twig')->getContent());`
