### ISSUE TITLE
No inline SVG

### ISSUE THREAD

**Issue by NiklasLazinbee** [dompdf/dompdf#1910]
I try to render inline SVG, but it dont work. I use the Dompdf 0.8.3 and PHP 7.3 (in PHP 5.6 it is the same)

Here is my code:
```
$html = '<html><head><meta http-equiv="Content-Type" content="charset=utf-8" /></head><body><svg id="Ebene_1" data-name="Ebene 1" xmlns="http://www.w3.org/2000/svg" width="202.87" height="163.79" viewBox="0 0 202.87 163.79"><defs><style>.cls-1 {fill: #181715;}</style></defs><rect class="cls-1" width="202.87" height="163.79"/></svg></body></html>';

require_once 'dompdf/autoload.inc.php';

use Dompdf\Dompdf;

$dompdf = new Dompdf();
$dompdf->loadHtml($html, 'UTF-8');

$dompdf->setPaper('A4');

$dompdf->set_option('defaultMediaType', 'all');
$dompdf->set_option('isFontSubsettingEnabled', true);

$dompdf->render();
$dompdf->stream();
```

What's wrong with it?

Apart from that, Dompdf is great. More documentation would be good.

**Comment by bsweeney** [comment]
Dompdf (as of 0.8.3) does not currently support embedded SVG. Watch issue #320 for updates.

We have all the necessary functionality, just need to build in the ability to pull out the SVG document for rendering.

Until this is ready you can always reference the SVG as either an external file or using a data-uri.

**Comment by lov2code** [comment]
I searched FOREVER until I finally came up with my own solution. I thought I should share in case it could be useful to anyone else. If you are using **PHP** the best solution to inline SVG images (for me) is to output it using **BASE64_ENCODE()** on the actual svg, then wrapping it in an image using the src as follows:

```
$svg = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 36 36" class="circular-chart">
    <path class="circle-bg"
          stroke-width="1"
          fill="none"
          stroke="#ddd"
          d="M18 2.0845
             a 15.9155 15.9155 0 0 1 0 31.831
             a 15.9155 15.9155 0 0 1 0 -31.831"
          />
</svg>';

$html = '<img src="data:image/svg+xml;base64,'.base64_encode($svg).'"  width="100" height="100" />';
```
The only issue you might find is weird dimensions on the actual image. You will have to mess with it on the PDF output to make sure it displays as desired.  I needed to remove the width and height of the actual SVG to make sure it was sizing correctly. Again hope this helps!
