### ISSUE TITLE
Filename cannot be empty

### ISSUE THREAD

**Issue by MudassirAbbas** [dompdf/dompdf#1913]
I am using macbook:
i am trying to create pdf from html page
using 
$pdf = PDF::loadView('admin.pdf');
        return $pdf->download('itsolutionstuff.pdf');
error is 
ErrorException (E_WARNING)
file_put_contents(): Filename cannot be empty

**Comment by bsweeney** [comment]
Looks like you're using [laravel-dompdf](https://github.com/barryvdh/laravel-dompdf). You'll want to ask there or on StackOverflow.
