### ISSUE TITLE
Issue when HTML class attribute has multiple lines (0.8.3)

### ISSUE THREAD

**Issue by fitztrev** [dompdf/dompdf#1914]
If a `class=""` attribute spans multiple lines in the source, the classes are not applied when rendering the PDF.

```html
<style>.yellow { background: yellow; }</style>

// This works
<div class="yellow">hello</div>

// This doesn't work
<div class="
    yellow
">hello</div>
```

Expected output is both `<div>`s with yellow background. Actual output:

<img width="174" alt="Screen Shot 2019-03-29 at 10 53 23 AM" src="https://user-images.githubusercontent.com/271432/55241175-ebc4ac00-5210-11e9-9827-1645ec1229e0.png">

## Steps to reproduce

1. Put this in `index.php`:

```php
<?php

require 'vendor/autoload.php';

use Dompdf\Dompdf;

$dompdf = new Dompdf();

$dompdf->loadHtml('
    <style>.yellow { background: yellow; }</style>

    <div class="yellow">hello</div>

    <div class="
        yellow
    ">hello</div>
');

$dompdf->render();
$dompdf->stream();
```

2. Run these commands:

```bash
composer require dompdf/dompdf
php -S localhost:9008
```

3. Visit http://localhost:9008/

**Comment by bsweeney** [comment]
This is indeed a bug. We'll fix for the next release.

**Comment by bsweeney** [comment]
The HTML5 specification outlines how to parse the class attribute:
https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#classes
