### ISSUE TITLE
Not compatible with PHP 7.2

### ISSUE THREAD

**Issue by clickstudio** [dompdf/dompdf#1915]
I am getting the following compatibility report/error after upgrading to PHP 7.2.

190 | ERROR | Extension 'cpdf' is removed since PHP 5.1; Use pecl/pdflib instead

--------------
Usage:
 

$options = new Options();
$options->setIsRemoteEnabled(true);

$dompdf = new DOMPDF();
$dompdf->setOptions($options);
		
$dompdf->set_paper("A4");

$dompdf->load_html( $vars['content'] );
$dompdf->render();
		
$output = $dompdf->output();

**Comment by Bert-de-Jong** [comment]
Related to this, I have a question for the developer.

At the top of the [main page](https://github.com/dompdf/dompdf) of this project, it says (emphasis mine):

> HTML to PDF converter (**PHP5**) http://dompdf.github.com/

The [Requirements](https://github.com/dompdf/dompdf#requirements) section says (again, emphasis mine):

> PHP version **5.4.0 or higher**

Going by just this sentence, "or higher" would include 7.x.

Question: is dompdf compatible with 7.x?
And, if it's not, this project is basically dead, right?

**Comment by Bert-de-Jong** [comment]
Oh, and if it _is_ compatible with 7.x, I suggest this edit for the main page: change "(PHP5)" to "(PHP5+)" or "(PHP5 and 7)", or even "(PHP7)" if it's no longer compatible with PHP 5.x.

**Comment by bsweeney** [comment]
@clickstudio looks like you're using the PECL version of CPDF. We use a bundled version with the library. There's a PR (#1851) to namespace the bundled version to avoid this type of conflict. That will be done for the next release. In the meantime just remove the PECL library.

@Bert-de-Jong you're right. We'll update that with the next release.
