### ISSUE TITLE
position: fixed; of element (0.8.3)

### ISSUE THREAD

**Issue by Aleksa95x** [dompdf/dompdf#1916]
When I set some HTML element to `position: fixed;` and place it on bottom of page by using `bottom: 0;` text content moves out of page, shouldn't text move to upper part of document?
<br>

![image](https://user-images.githubusercontent.com/35258434/55403639-8ea16100-5556-11e9-8f60-a560de089525.png)

**Comment by bsweeney** [comment]
Did you intend to close this issue? It does appear to still be a problem.

**Comment by bsweeney** [comment]
Unable to reproduce and without sample HTML + CSS it would be difficult to determine the cause. Recommend updating to the most recent release.
