### ISSUE TITLE
Stream() not working on raspbian with apache 

### ISSUE THREAD

**Issue by maximus1127** [dompdf/dompdf#1919]
I have working code on my windows machine. 

```    
public function print($id){
      $student = Student::find($id);
      $pdf = PDF::loadView('printTables', compact('student'));
      return $pdf->stream();
}
```

This works completely as expected on windows. I am trying to host this app on my raspberry pi and access it externally (i have all my port forwarding and stuff done already). I can access every other part of this app. The database works, submissions work, but when i click my button to generate a pdf, the page stalls and times out with an error after 30 seconds. Any suggestions? I'm running the latest version of raspbian from the raspberry website as well as the latest version of apache with php 7.2

**Comment by bsweeney** [comment]
Only idea of the top of my head is that maybe that the server is expecting more data and not sending the PDF even though Dompdf is done with its work. We've seen this when the content size reported by Dompdf doesn't match what's fed to the web server. The work-around for this has been to call `exit` after you stream from Dompdf.

Looks like you're using laravel-dompdf. I'm not sure how effective this method will work with your configuration.
