### ISSUE TITLE
Not displaying correct Indic Characters (Diacritic character)

### ISSUE THREAD

**Issue by karishmapujara** [dompdf/dompdf#1921]
Hello

I followed Unicode How-To? tutorial and generated font.

Here is the output

![Untitled](https://user-images.githubusercontent.com/3817026/56734256-f1fe6780-677f-11e9-84cf-6f7402a853ae.png)

Problem is that the diacritic character should appear second, even though it should be rendered left of the main character.

In HTML it's displaying correct.

So any solution?

**Comment by bsweeney** [comment]
Looks like you've already found issue #1092, any follow up will occur on that issue.
