### ISSUE TITLE
count() function called on empty value

### ISSUE THREAD

**Issue by jboullion** [dompdf/dompdf#1922]
> Warning: count(): Parameter must be an array or an object that implements Countable in /Sites/propertydrive/reports/vendor/spipu/html2pdf/src/Html2Pdf.php on line 5096

The line: `$nbCasesK = count(self::$_tables[$param['num']]['cases'][$k]);` can sometimes try to "count" an empty value and throws an error, which can prevent the headers being sent and breaking the PDF build.

wrapping this line with: `if(! empty(self::$_tables[$param['num']]['cases'][$k])){ ... }` seems to resolve the issue

**Comment by bsweeney** [comment]
That error is not from Dompdf. Html2Pdf is a different Dompdf.
