### ISSUE TITLE
PHP IN DOMPDF how include ?

### ISSUE THREAD

**Issue by Kakou347** [dompdf/dompdf#1924]
Hello all.

My problem is the PHP doesn't display.
My english is bad so, just look my code.

So, my URL to arrive here

`<?php
     
     ob_start();
     require ''.$_SERVER['DOCUMENT_ROOT'].'/folder/database.php';
     require ''.$_SERVER['DOCUMENT_ROOT'].'/folder/donnees.php';
     $html = ob_get_clean();
     
     require ''.$_SERVER['DOCUMENT_ROOT'].'/modules/dompdf/autoload.inc.php';

     use Dompdf\Dompdf;
     use Dompdf\Options;

     $options = new Options();
     $options->set('isPhpEnabled', true);
     $dompdf = new DOMPDF($options);
     $dompdf->setPaper('A4', 'portrait');
     $dompdf->loadHtml(file_get_contents('file/bail.php'));
     $dompdf->render();
     $dompdf->stream('bail-'.$niveau[3].'.pdf');`

I have the PDF who save it, it's ok.

Now I have bail.php

`<!DOCTYPE html>

 <html>
          <head></head>

          <body>

               <h1>Blablabla</h1>
               <p><?php echo $donnees['prenom']; ?></p>

          </body>

 </html>`

Here, the PHP doesn't display. where is my error please ? :'(

Thanks you !

**Comment by bsweeney** [comment]
You don't. We removed PHP parsing from Dompdf for security reasons. Embedded script is still supported until we build out some missing HTML+CSS rendering support.

Just capture the output and feed the HTML document to Dompdf.

```
ob_start();
require_once('file/bail.php');
$html = ob_get_contents();
ob_end_clean();
$dompdf->load_html($html);
```
