### ISSUE TITLE
Rendering PDF error font weight. Only <b> or <strong> is showing, others are blocks

### ISSUE THREAD

**Issue by samet5** [dompdf/dompdf#1927]
I have PDF rendering error font weight. Only texts with **b** or **strong** is showing, others, like paragraphs are weird blocks. If I just stream the PDF and preview, everything looks fine. But when I save the PDF on the server and open the PDF from the server, the characters with font-weight 400 wil not show up instead showing weird blocks. Does anyone have a fix for this? I am searching for almost 6 hours and can't find a solution.

I have everything like:

```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

@font-face {
      font-family: 'Nunito';
      font-style: normal;
      font-weight: normal;
      src: url('https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet'); /* IE9 Compat Modes */
}

body {
    font-family: 'Nunito', sans-serif!important;
}
```

![Knipsel](https://user-images.githubusercontent.com/32731949/56871861-d8307f00-6a22-11e9-94de-27d49fbfd24b.PNG)

**Comment by samet5** [comment]
Also have 
    `<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>`
Inside head

**Comment by bsweeney** [comment]
Your `@font-face` declaration is incorrect. Google provides a stylesheet that sets up the font, not a link to the font itself. Your HTML should actually be something like the following:

```
<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" />
<style>
body {
    font-family: 'Nunito', sans-serif !important;
}
</style>
</head>

<body>
  <p>dompdf <b>dompdf</b></p>
</body>
</html>
```

But also note you're likely to run into a separate issue related to numeric font weights. Follow #675 for updates.
