### ISSUE TITLE
Anyone have updated 2019 latest version instructions on how to change font?

### ISSUE THREAD

**Issue by cAstraea** [dompdf/dompdf#1928]
I want to try to change the font to a Japanese one for example NotoSansKannada-Regular.ttf
http://fonts.gstatic.com/ea/notosanskannada/v3/NotoSansKannada-Regular.ttf
but getting question marks instead.

Any documentation on how to do this step-by-step please ? Feels like I'm missing some files , tried to mix and match from older dompdf versions but couldn't get it to work... spent many many hours on this already.
Is load_font.php still included or it's another package?

**Comment by cAstraea** [comment]
Ok finally found a solution everyone. For people using the composer version of dompdf.
Step 1 -> Find a font that supports the language you need. 
I went for this one http://ipafont.ipa.go.jp/old/ipafont/download.html and downloaded ipag00003. I copied the ipag.ttf font to somewhere handy. I put it inside vendor/dompdf/dompdf 

Step 2-> Download the package from here https://github.com/dompdf/utils and copy load_font.php and autoload.inc.php to /vendor/dompdf/dompdf

Step 3-> Ensure you have php-svg-lib and php-font-lib  folders inside /vendor/dompdf/dompdf
You can get these from https://github.com/PhenX/php-font-lib and https://github.com/PhenX/php-svg-lib

Step 4-> Edit the load_font.php file make sure that the first require_once points to the dompdf autoloader for example 
require_once "/var/www/html/xxxxx.com/public_html/vendor/autoload.php";

Step 5-> Install the font running `php load_font.php ipag ipag.ttf `
If all goes well you should see this output 
Unable to find bold face file.
Unable to find italic face file.
Unable to find bold_italic face file.
Copying ipag.ttf to /var/www/html/zzzz.com/public_html/vendor/dompdf/dompdf/lib/fonts/ipag.ttf...
Generating Adobe Font Metrics for /var/www/html/zzzzz.com/public_html/vendor/dompdf/dompdf/lib/fonts/ipag...

You can also check the dompdf_font_family_cache.php if the font was written successfully 

Now to use the font you can simply reference it in styles add a class for example 
 .ipag-font {font-family: ipag;} and use it 
`<div class="ipag-font">こんにちは</div>`

**Comment by metheglin** [comment]
Let me share my situation. 
I ran into the similar problem but I could finally solve the japanese font issue with the usual way described below.(I'm not sure if it's only japanese problem)
- https://stackoverflow.com/a/52024837/3988797
- https://github.com/dompdf/dompdf/wiki/About-Fonts-and-Character-Encoding

The problem of my case seemed to lie on dompdf. Once remove vendor dir and `composer install` again got success.

Version
```
"barryvdh/laravel-dompdf": "^0.8.1",
```

**Comment by bsweeney** [comment]
Glad you were able to resolve your issues.

**Comment by hlaporthein** [comment]
![font-problems](https://user-images.githubusercontent.com/1018870/65697528-1947c080-e0a1-11e9-9380-90055383d5ff.png)


Just only add font ipag.ttf, ipag.ufm and dompdf_font_family_cache.php  in storage fonts folder. I think it it more convenient than touching vendor folder.

Don't forget to add below array in dompdf_font_family_cache.php file

`
  'ipag' => array(
    'normal' => $fontDir . '/ipag',
    'bold' => $fontDir . '/ipag',
    'italic' => $fontDir . '/ipag',
    'bold_italic' => $fontDir . '/ipag',
  ),
`
