### ISSUE TITLE
Default Page Border/Margin/Padding  - Remove or are these print margins?

### ISSUE THREAD

**Issue by MPJHorner** [dompdf/dompdf#1930]
Hey all,

Please see example below.
<img width="816" alt="ticket layout" src="https://user-images.githubusercontent.com/4990716/57284922-0a3c8380-70aa-11e9-81ca-27cf28422935.png">

(The black line around the edge shows the edge of the paper/page)

1) I have made custom page which doesn't exist, essentially 1/3 of A4 = `DL` paper size, however I overrode this,

See the example, I have used 100% width/height and also done these using pixels.

However the page padding/margin (whatever you want to call it) or maybe it is even print margins are huge? I can't see any method to override these? How can I go to the edge or closer too?

Many thanks in advance.

**Comment by bsweeney** [comment]
It would help to see a sample of the HTML you used to create this. Otherwise just conjecture, but ... there are default margins, which you can override via CSS:

```
<style>
@page { margin: 0; }
</style>
```

**Comment by bofrank** [comment]
@motia  All paragraph body text needs to be scalable including the two text areas on the first page.

**Comment by amagrawal** [comment]
Thanks a lot
