### ISSUE TITLE
protocol undefined in build_url when using loadHtml()

### ISSUE THREAD

**Issue by jlsjonas** [dompdf/dompdf#1932]
Relative protocol links break when using loadHTML

I'd suggest to use `http` as sane default here (mostly, if not only used for style inclusions, added security benefit is principally minimal in these cases; and it allows for most scenarios to work)

**Comment by bsweeney** [comment]
I'm rather ambivalent towards this one since there are ways to [specify a default protocol](https://github.com/dompdf/dompdf/issues/1086#issuecomment-174356414).

**Comment by bsweeney** [comment]
Think we'll leave as-is since it's possible to specify a default.
