### ISSUE TITLE
Print scaling 

### ISSUE THREAD

**Issue by codmdu** [dompdf/dompdf#1937]
Hello,

is it possible to set the print scaling ?
Currently we have to download and open the pdf every time we want to print them.
On the Print Modal we also have to tick the "scaled" (i dont know how it is called in the english modal) checkbox manually.

The Application Adobe Reader can save that option, can dompdf also save the option so we only have to open the pdf with adobe reader and just print ?

Greetings,
codmdu

**Comment by bsweeney** [comment]
The only two options related to print scaling are "None" and "AppDefault" with AppDefault being the default. I'm not sure if there's much that can be done beyond that, would require some research.

In code: https://github.com/dompdf/dompdf/blob/v0.8.3/lib/Cpdf.php#L479

This option was actually introduced in the PDF 1.6 spec. The CPDF back end officially supports 1.3 (though that preference is supported).

**Comment by codmdu** [comment]
Thank you for the informations.
