### ISSUE TITLE
fontMetrics->getFont custom font

### ISSUE THREAD

**Issue by vielhuber** [dompdf/dompdf#1940]
Hello!

Custom fonts work without any problem inside css via @font-face.

But I output my page number and page count via $pdf->page_script:

```
$pdf->page_script('
$font = $fontMetrics->getFont("custom-font", "regular");
$size = 20;
$text = "Seite " . $PAGE_NUM . "/" . $PAGE_COUNT;
$x = $pdf->get_width() - 50 - 10 - $fontMetrics->getTextWidth($text, $font, $size);
$y = 50;
$pdf->text($x, $y, $text, $font, $size);
');
```

There the custom fonts don't work.

Where can I find documentation how to apply custom fonts also for page_script?

**Comment by vielhuber** [comment]
Got it working:
```
$font = $fontMetrics->getFont("custom-font", "normal");
```

**Comment by bilogic** [comment]
@vielhuber i can't get custom fonts and ```page_script()``` to work together on #602, able to share your code? Thank you.

**Comment by bilogic** [comment]
I realized that's a different but related repo. thanks anyway
