### ISSUE TITLE
inline-block elements just flows out of its float parent

### ISSUE THREAD

**Issue by carlbinalla** [dompdf/dompdf#1943]
Code:

````
<!DOCTYPE html>
<html>
<head>
    <style>
        * {
            font-size: x-small;
            font-family: Arial, Helvetica, sans-serif;
        }
        .child {
	    background-color:orange;
	    display:inline-block;
	    width:25%;
	    vertical-align:top;
	}
    </style>
</head>
<body>
    <div style="background-color:pink;">
        <div style="background-color:red;float:left;width:50%;">PARENT</div>
	<div style="background-color:green;float:left;width:50%;font-size:0;">
	    <div class="child">CHILD</div>
	    <div class="child">CHILD</div>
	    <div class="child">CHILD</div>
	    <div class="child">CHILD</div>
	    <div class="child">CHILD</div>
	    <div class="child">CHILD</div>
	    <div class="child">CHILD</div>
	    <div class="child">CHILD</div>
	    <div class="child">CHILD</div>
	</div>
    </div>
</body>
</html>
````
Rendered PDF:

![inline](https://user-images.githubusercontent.com/35289441/59011316-dc905900-8866-11e9-8cfe-3bc5e60d905b.png)

Is there a way to make them flow properly? I also used `float:left` instead of `display:inline-block`, but they just overlaps with each other:

![inline2](https://user-images.githubusercontent.com/35289441/59011509-87a11280-8867-11e9-9e4d-9b60e90af66c.png)

I am aiming for something like this *(in browser)*:

![inline3](https://user-images.githubusercontent.com/35289441/59011642-f0888a80-8867-11e9-8e31-b2ac153e5ff7.png)

**Comment by bsweeney** [comment]
There are a few flow-related issues here. I don't have a work around for the problem right now.

**Comment by bsweeney** [comment]
Also see #500 and #1419.

**Comment by Mellthas** [comment]
This works fine now with the current `develop`.
