### ISSUE TITLE
Without Composer?

### ISSUE THREAD

**Issue by WebSpectrum** [dompdf/dompdf#1944]
Where can i get the latest stable build that doesn't require messing about with Composer?

**Comment by PowerKiKi** [comment]
See https://github.com/dompdf/dompdf/releases, there is a download available specifically for that.

Next time, please refrain from posting question in this bug tracker. Questions should be asked on http://groups.google.com/group/dompdf or https://stackoverflow.com/questions/tagged/dompdf.
