### ISSUE TITLE
Illegal string offset 'compress'

### ISSUE THREAD

**Issue by davidanibalfernandez** [dompdf/dompdf#1945]
good ones. first of all, i sorry for my bad english.

if i run this in php 7.2 it working perfect

********************the error************************************
Warning: Illegal string offset 'compress' in D:\xampp\htdocs\php\pdf\dompdf\src\Adapter\CPDF.php on line 1166

Warning: Illegal string offset 'compress' in D:\xampp\htdocs\php\pdf\dompdf\src\Adapter\CPDF.php on line 1170
*****************************************************************

***********************my code*********************************
/////file crearPdf.php//////

// Cargamos la librería dompdf que hemos instalado en la carpeta dompdf
require_once 'dompdf/lib/html5lib/Parser.php';
require_once 'dompdf/lib/php-font-lib/src/FontLib/Autoloader.php';
require_once 'dompdf/lib/php-svg-lib/src/autoload.php';
require_once 'dompdf/src/Autoloader.php';
Dompdf\Autoloader::register();
// Introducimos HTML de prueba

use Dompdf\Dompdf;

$html=file_get_contents_curl("http://localhost:8080/php/pdf/misDatosPdf.php");

// Instanciamos un objeto de la clase DOMPDF.
$pdf = new DOMPDF();

// Definimos el tamaño y orientación del papel que queremos.
$pdf->set_paper("letter", "portrait");

// Cargamos el contenido HTML.
$pdf->load_html(utf8_decode($html));

// Renderizamos el documento PDF.
$pdf->render();

// Enviamos el fichero PDF al navegador.
$pdf->output('reportePdf.pdf');

function file_get_contents_curl($url) {
	$crl = curl_init();
	$timeout = 5;
	curl_setopt($crl, CURLOPT_URL, $url);
	curl_setopt($crl, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($crl, CURLOPT_CONNECTTIMEOUT, $timeout);
	$ret = curl_exec($crl);
	curl_close($crl);
	return $ret;
}

////file misDatosPdf.php/////////

<!DOCTYPE html>
<html>
<head>
    <title>prueba</title>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <style>
    </style>
</head>
<body>

    <div id="header">
        <div id="top">          
            <div >
                <div >
                       <img src="<?php // echo $logo_cabecera ?>"/> 
                       <h1 id="letras"></h1>
                </div>
                <div >
                    <div id="search">
                        Impreso por: izi
                    </div>
                </div>
            </div>          
        </div>
    </div>
    
    <div id="footer">
        <div >
            asd</br>  qwe Versión   1<br />
            Desarrollado por: yo
        </div>
    </div>
    
    <form name="form1">
        <div>
            <h3 >FICHA DE CLIENTE</h3>
            <div >             
                <h3 >DATOS GENERALES</h3>
            </div>          
            <div>    
                <table >
                    <thead>
                        <tr>
                            <th>Nº</th>
                            <th>Nombres</th>
                            <th>Cedula</th>
                            <th>Correo</th>
                            <th>Telefono</th>
                            <th>Grupo</th>
                            <th>Activo</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td style="font-size: 10px;">a</td>
                            <td style="font-size: 10px;">b</td>
                            <td style="font-size: 10px;">c</td>
                            <td style="font-size: 10px;">d</td>
                            <td style="font-size: 10px;">e</td>
                            <td style="font-size: 10px;">f</td>
                            <td style="font-size: 10px;">Si</td>
                        </tr>
                    </tbody>
                </table>                
            </div>          
        </div>       
    </form>
</body>
</html>
*********************************************************

************ server ********************************
im runing xampp XAMPP for Windows 7.3.5(Apache/2.4.39 (Win64) OpenSSL/1.1.1b PHP/7.3.5)

**Comment by davidanibalfernandez** [comment]
i resoll the problem. it was in what the library was trying to cach a variable that dont exist.

**Comment by Romdh4ne** [comment]
hello my friend, i have the same problem, how did you fix it?

**Comment by davidanibalfernandez** [comment]
> hello my friend, i have the same problem, how did you fix it?

hi. the problem in the moment was with the way php manage the errors and warnings.  as you know, php 7.2 to 7.3 change some errors and warnings.

the library in the version i was use in the moment do not control the exceptions correctly.

the problem in my case was a wrong variable name. verify them first.

i cant show you the code because a lost the proyect source code
