### ISSUE TITLE
PHP Fatal error:  Call to a member function build_tree() on a non-object in 

### ISSUE THREAD

**Issue by NewFake** [dompdf/dompdf#1952]
Hello,

I am trying to convert an html file (an invoice) and i get the error:
> PHP Fatal error:  Call to a member function build_tree() on a non-object in /dompdf/src/Dompdf.php on line 570

My code:
```
<?php 
require_once '/var/www/html/adm/login/dompdf/autoload.inc.php';

use Dompdf\Dompdf;

$dompdf = new Dompdf();

ob_start();

$html = file_get_contents("/invoice/QEIIWR.html");

ob_get_clean();

ob_end_clean();

$dompdf->setPaper('A4', 'portrait');

$dompdf->render();

$dompdf->output("Invoice-".$code, array("Attachment" => 1));
?>
```

What could be the problem? The file contain generated HTML.

**Comment by bsweeney** [comment]
Would need to see the contents of the HTML file to be able to say anything about what's going on.
