### ISSUE TITLE
What should I do..?? Script not working.. pdf

### ISSUE THREAD

**Issue by ShekhSaifuddin007** [dompdf/dompdf#1953]
```
<script type="text/javascript"> try { this.print(); } catch (e) { window.onload = window.print; } </script>
```
this line go directly in print window but I have other script for showing total amount in words but this pdf generator totally skip those lines. What should I do..??

**Comment by bsweeney** [comment]
No idea. What is the context of using that particular script (i.e how is it used)?

**Comment by anilsaini81155** [comment]
Hi,

   I have been working on DomPdf library for last six months, this library does not support advanced CSS and responsive boostrap tags and also javascript tags.

**Comment by bsweeney** [comment]
@anilsaini81155 you're right about JavaScript. Doubt we'll ever support that. We support HTML + CSS and that's it.

Responsiveness works, just not great. Need to add support for box-sizing then we'll pretty much be there. Though if you're relying on more advanced CSS like flexbox or grid, well, yeah, we're not there yet.

**Comment by Sayyam-Ipsum** [comment]
How to run javascript code laravel-dompdf view file?

**Comment by bsweeney** [comment]
Dompdf does not support JavaScript.
