### ISSUE TITLE
dompdf recent issues

### ISSUE THREAD

**Issue by 83dons** [dompdf/dompdf#1955]
I use an old version of dompdf in conjunction with a PHP web page on my website so that the user completed an online form and the website uses SMTP to turn this into an email with the contents of the form turned into a PDF attachment by dompdf (have no clue how as this was setup so long ago!). Emails went off last Friday morning and since turned back on by support but now getting the email through with a blank PDF attachment. Is there an issue with DOMPDF since last week maybe linked to changes in PHP or something? If not how would I go about trouble shooting or is it quite easy for me to update DOMPDF code to the latest version in my web scripts and the uploaded library aI think it was on the server?

**Comment by bsweeney** [comment]
The update is pretty straight-forward. The newer release is almost a drop-in replacement for the old (see the readme for information on how to use).

I don't have much advice otherwise. Your said emails went off. Did something change on your system? Try checking your PHP logs for any messages.
