### ISSUE TITLE
Dompdf file saved with squares in place of letters

### ISSUE THREAD

**Issue by iacreative** [dompdf/dompdf#1958]
Hi,

I'm using dompdf-master and dompdf-0.8.3 both render the Arial font in the browser I created using an old version of dompdf that has the www folder. But I am saving the file in a folder and when I open this file instead of letters in the body of the pdf I have qaudrados. What could be happening?
![dompdf01](https://user-images.githubusercontent.com/15638446/60164816-a0507880-97d4-11e9-9f67-62e5fad4c280.png)
![dompdf02](https://user-images.githubusercontent.com/15638446/60164848-a9d9e080-97d4-11e9-8ca7-361557030e24.png)

My code

```
require_once  '/php/dompdf/src/Autoloader.php' ; 
Dompdf \ Autoloader :: register ();


use  Dompdf \ Dompdf ;
use  Dompdf \ Options ;

$dirName = "./upload/";
$nameFile = "teste_pdf.pdf";

$options = new Options();
$options->set('defaultFont', 'Arial');
$dompdf = new Dompdf($options);
$html = '
	<!DOCTYPE html>
	<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<link rel="stylesheet" href="css/teste_pdf.css">
	</head>
	<body>
		<div class="page">
			<h1>Hello World DOMPDF!!!<h1>
		</div>
	</body>
	</html>
';
$dompdf->loadhtml($html, 'UTF-8');
$dompdf->setPaper('a4', 'portrait');

$dompdf->render();

$dompdf->stream('teste_pdf.pdf', array("Attachment" => false));
$output = $dompdf->output();
file_put_contents($dirName . $nameFile, $dompdf->output());

exit(0);

```

**Comment by iacreative** [comment]
I'm from Brazil and I wanted to say square and not qaudrados. Also I had forgotten that this is happening with the dejavu sans font family. Does this have to do with the .afm file since both have only .ufm file

**Comment by iacreative** [comment]
Hi guys,

On the problem that happens with the added fonts, it seems to be related to some problem of the dompdf itself, stream () and output () do not work together, I have inverted their positions and what comes first works while the latter does not. Maybe this is only related to added fonts and they do not have the .afm file as in the case of the Dejavu font. You could provide information on how to add dompdf-master and dompdf-0.8.3 fonts similar to dompdf-0.6.0 when we can use the www folder. Thank you, always!

**Comment by bsweeney** [comment]
The AFM files are only used with non-Unicode aware fonts and so are not used at all with DejaVu. Dompdf definitely has issues using both output and stream in sequence (there's an issue in here ... somewhere). You should use one or the other.

If you need to both save the file and send it to the browser just use output, save the file, then use the `readfile()` PHP function to send it to the browser. The down side to this method is you'll have to specify the content headers yourself. If you don't want to get into that you can save the file to a browser-accessible location and redirect the user to the saved file.

**Comment by iacreative** [comment]
Hi Brian,

That's exactly what I said last I did. Thank you, always!

**Comment by bsweeney** [comment]
As far as adding fonts, you can find that information in the wiki ([Unicode How-to](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo)).

Essentially, use the `@font-face` CSS declaration.
