### ISSUE TITLE
Empty pdf with enabled html5 parser

### ISSUE THREAD

**Issue by guratr** [dompdf/dompdf#1960]
With php official docker image and isHtml5ParserEnabled option enabled i get empty pdf file. 
The source of problem is probably in html5lib/inputStream.php line 77
`$data = @iconv('UTF-8', 'UTF-8//IGNORE', $data);`
in docker image it returns empty string, and gives warning " iconv(): Wrong charset, conversion from UTF-8 to UTF-8//IGNORE is not allowed in..."
more about the issue here [https://github.com/docker-library/php/issues/240](url)
Possible solution is using 
`ini_set('mbstring.substitute_character', "none"); 
$text= mb_convert_encoding($text, 'UTF-8', 'UTF-8'); `
as described here
[https://www.php.net/manual/en/function.iconv.php#108643](url)

**Comment by bsweeney** [comment]
I'm hoping to get rid of the embedded HTML5 library with the next release. It's quite out of date. Current plan is to use [masterminds/html5-php](https://github.com/Masterminds/html5-php) though there's also been a request for [wikimedia/remex-html](https://github.com/wikimedia/remex-html) (#1908).
