### ISSUE TITLE
Final Page Rectangle Renders - Text Doesn't - Off By One Text Rendering Error?

### ISSUE THREAD

**Issue by jgbyvan** [dompdf/dompdf#1962]
I have the following code:

<pre>
                $canvas = $dompdf->get_canvas();
                $canvas->page_script('
                if( $PAGE_NUM == $PAGE_COUNT ) {
                        $font = $fontMetrics->get_font("Open Sans", "bold");
                        $color = array(0, 0, 0);
                        $pdf->filled_rectangle(168, 722, 35, 15, $color);
                        $pdf->page_text(173, 718, "END ", $font, 12, array(1,1,1));
                }
                ');
</pre>

This is rendering the box on the last page as expected, but the text 'END' is not rendered.

If I take out the "if" then it renders the rectangle on every page and renders the "END" text on all pages but the final one.

So this got me thinking and I tried this code...
<pre>
                if( $PAGE_NUM == $PAGE_COUNT ) {
                        $color = array(0, 0, 0);
                        $pdf->filled_rectangle(168, 722, 35, 15, $color);
                }
                if( $PAGE_NUM == ($PAGE_COUNT - 1)) {
                        $font = $fontMetrics->get_font("Open Sans", "bold");
                        $pdf->page_text(173, 718, "END ", $font, 12, array(1,1,1));
                }
</pre>
This correctly renders the text on the final page over the box. Which seems rather counter-intuitive.

I'm using DomPDF within the context of someone eles's Woocommerce plugin - but I've checked the plugin code to see if it does anything that seems odd and it doesn't seem to.

This is the latest release version of DomPDF.

Can provide more context data and samples of required.

**Comment by bsweeney** [comment]
Two things...

First, yes there is a bug. It looks like we initialize the page number and count to zero instead of 1. This leads to an incorrect evaluation of the page count when parsing page_text and page_script. We'll fix this with 0.8.4.

Second, your usage isn't quite right. If you're placing text inside a page script you should use the `text` method instead of the `page_text` method. The text method renders text to the page immediately, the `page_text` method queues text to render during post-processing. Doing this inside a page script means it'll start rendering on the following page. You just a small tweak to your original code:

```
$canvas = $dompdf->get_canvas();
$canvas->page_script('
  if( $PAGE_NUM == $PAGE_COUNT ) {
    $font = $fontMetrics->get_font("Open Sans", "bold");
    $color = array(0, 0, 0);
    $pdf->filled_rectangle(168, 722, 35, 15, $color);
    $pdf->page(173, 718, "END ", $font, 12, array(1,1,1));
  }
');
```

**Comment by jgbyvan** [comment]
Thanks Brian. Changed the `page_text` to `text` and it works as desired. Guess by getting that wrong I ran into a bug by luck then, bonus.

**Comment by bsweeney** [comment]
Huh. Actually, I don't think there was a bug I think my local just got mussed (probably when I was testing something else out). That commit I just checked in didn't actually do anything :swear

**Comment by jgbyvan** [comment]
Sorry for causing such confusion. Thanks for your time.
