### ISSUE TITLE
Generate PDF with image that has as source a PHP script with DOMPDF

### ISSUE THREAD

**Issue by 11JoseMarcos11** [dompdf/dompdf#1965]
Hello.

We are using Dompdf to generate PDF files and within that file we want to put a QRCode. For this, we are using the line below, but it is not working:

```
require_once ("dompdf / autoload.inc.php");
use Dompdf \ Dompdf;
$ options = new Options ();
$ options-> set ('isRemoteEnabled', TRUE);
$ dompdf = new DOMPDF ($ options);
$ dompdf-> load_html ('
....
<img id = "img" src = "qr_img0.50j / php / qr_img.php? d = Creating QrCode in PHP & e = H & s = 10"
....
');
$ dompdf-> setPaper ('A4', 'landscape');
$ dompdf-> render ();
$ dompdf-> stream (
     "wallet -". $ pe-> Directory. ".pdf",
     array (
         "Attachment" => false // To download only change to true
     )
);
```

We tried that, but it did not work either:

```
$ dompdf-> setPaper ('A4', 'landscape');
$ dompdf-> render ();
$ output = $ dompdf-> output ();
file_put_contents ("wallet -". $ pe-> Directory. ".pdf", $ output);
```

Could you help us?

Many thanks and greetings from Brazil.

**Comment by bsweeney** [comment]
Dompdf does not parse PHP. There are two options to addressing the issue:
1. Reference the image PHP via a web server, something like `<img id="img" src="http://example.com/qr_img0.50j/php/qr_img.php?d=Creating+QrCod+ in+PHP&e=H&s=10"`
2. Run the script from the file utilizing Dompdf and then either save the file or base64 encode it. Then you can reference one of those in your generated HTML. If the image is relatively small I'd base64 encode it.
