### ISSUE TITLE
html <a> tags not generating as links, unless link text is URI

### ISSUE THREAD

**Issue by apcro** [dompdf/dompdf#1967]
DomPDF version(s): confirmed in `0.8.2` and `0.8.4`

DomPDF will not render a clickable link from an `<a>` tag inside a well-formed HTML file unless the link text is a URI itself - the `<a>` tag seems to be stripped entirely from the HTML before the PDF is rendered, and the link text handled separately if it matches the form of a URI.

The following HTML will not render a clickable link:
`<a href="https://www.google.com" target="_blank" style="color: #000;">Google</a>`

The following HTML _will_ render a clickable link:
`<a href="https://www.google.com" target="_blank" style="color: #000;">https://www.google.com</a>`

Modifying the HTML by removing the style attribute in the first example will generate 'blue' text, not clickable. In the second example it will generate 'blue' text, clickable.

Removing the `target=` attribute has no effect.

And after further investigation, just having what appears to be a URI will be linked. For example, `https://www.google.com` on it's own will render a clickable link, without being wrapped in an `<a>` tag.

In addition, the `isHtml5ParserEnabled` setting has no bearing on this.

**Comment by bradyuen** [comment]
I get this same issue.
Just try to make a link look like a button.
Unfortunately, it look like it's not able to do it.

**Comment by bsweeney** [comment]
This may be more a function of your PDF viewer and not a problem with Dompdf. I notice, for example, that if the PDF is displayed in an iframe in Safari the link is clickable but appears to do nothing. Firefox, however, is fine.

The fact that a URL itself is rendered clickable is solely a function of your PDF viewer.

**Comment by seanmadrid** [comment]
> This may be more a function of your PDF viewer and not a problem with Dompdf. I notice, for example, that if the PDF is displayed in an iframe in Safari the link is clickable but appears to do nothing. Firefox, however, is fine.
> 
> The fact that a URL itself is rendered clickable is solely a function of your PDF viewer.

Links are not clickable in Adobe Acrobat.
