### ISSUE TITLE
DOMPDF Boxes layout not align to first box

### ISSUE THREAD

**Issue by Waseem-Jutt** [dompdf/dompdf#1970]
I need really urgent help on this issue.
PDF View
![pdf-view](https://user-images.githubusercontent.com/8005637/62240369-430d9f80-b3f0-11e9-95d0-6db291f480c1.png)

Desktop View
![dekstop-view](https://user-images.githubusercontent.com/8005637/62240383-4d2f9e00-b3f0-11e9-96ae-920ec1dfeccf.png)

CSS Code For PDF
```
	* {
	box-sizing: border-box;
	}
	.order-list-view2{max-width:58%;}
	.order-lists{background-color: #fff;display: block;float: left;width: 100%;padding-bottom: 0px;margin-left: 0;padding-left:0;}
	.order-lists li{display: inline-block;width: 55mm;height: 30mm; margin-left: -4px;padding-top: 20px;padding-left: 20px;padding-right: 20px;position: relative;list-style:none;vertical-align: top;}
	.order-lists li h4{margin-top:0px;margin-bottom: 12px;}
	.order-lists li .order-list-view1,
	.order-lists li .order-list-view2{display: inline-block;vertical-align: top;}
	.order-lists li .order-list-view1{}
	.order-lists li h4{font-size:16px;}
	.order-list-view2 span{border-bottom:1px solid #333;font-size:14px;}
	.order-lists .class-name{font-size: 22px;font-weight: bold;display: inline-block;text-align: center;padding-left: 20px;}
	.order-lists .order-date{font-size:14px;transform: rotate(90deg);display: block;position: relative;top: 16px;}
```

**Comment by joeybab3** [comment]
What is the issue?

**Comment by Waseem-Jutt** [comment]
Check PDF View not showing show Desktop View showing.. Column should be 3 in a row.. Now only in one row showing 3 and from 2nd showing 2 columns in a row...

**Comment by bsweeney** [comment]
Would help to see full HTML+CSS you're using. I will note that Dompdf does not yet support the `box-sizing` CSS declaration (follow #669 for updates).
