### ISSUE TITLE
Javascript not working

### ISSUE THREAD

**Issue by nitinbansude** [dompdf/dompdf#1974]
Is there any way to add javascript while creating pdf.?

**Comment by bsweeney** [comment]
What kind of JavaScript? Dompdf does not support parsing JS, but you can insert PDF-oriented JS into the output.

**Comment by nitinbansude** [comment]
I am trying to add Barcode.js file to create barcode in the pdf. But it is not working.

**Comment by yueming-Chen** [comment]
Hi @nitinbansude , you can try this way for this following code.

```php
function get_rendered_html($template_path,$your_paras...){
    ob_start();
    include($template_path);
    $rendered = ob_get_contents();
    ob_end_clean();
    return $rendered;
}
```

Then the HTML you get is executed the JS code rendered.

**Comment by bsweeney** [comment]
@nitinbansude you'd need to use a browser-based utility like wkhtmltopdf to get that functionality. Dompdf does not have support for that type of functionality.

The other option would be to get the user's client browser to render the image, then send that back to the server for inclusion in the PDF.
