### ISSUE TITLE
Old release files seem to have vanished.

### ISSUE THREAD

**Issue by MarkMaldaba** [dompdf/dompdf#1975]
I wanted to test some of our code against DomPDF v0.7.0 and v0.8.0 because something has broken between when the code was written (for v0.6.2) and the latest version (0.8.3).

However, it looks like the release tarballs for a number of past releases (but not all of them) seem to have vanished.

For example, I know for a fact that the following URL contained the release version of 0.8.1, as I have the record of it in our vendor repository: https://github.com/dompdf/dompdf/releases/download/v0.8.1/dompdf_0-8-1.zip

Please can you restore the full release versions for old releases - the source code tarballs that are still present are useless as they don't contain all the required dependencies.

**Comment by bsweeney** [comment]
I can do that.

**Comment by bsweeney** [comment]
Done.
