### ISSUE TITLE
loadHtml() - $encoding argument has no effect

### ISSUE THREAD

**Issue by MarkMaldaba** [dompdf/dompdf#1977]
The `Dompdf::loadHTML()` function takes a second argument, called `$encoding`, but this currently has no effect.

On line 457 (DomPDF 0.8.3), before the argument is used for anything, we have the following, meaning that the argument is always forced to 'UTF-8' regardless of what you specify:
```php
        //FIXME: since we're not using this just yet
        $encoding = 'UTF-8';
```

The function seems to have some code that attempts to detect the correct encoding, but in my tests we are finding that we get invalid characters (boxes) when using iso-8859-1 content, even when we set this argument correctly, so this is not working effectively (if at all).

Is the intention to allow for non-UTF8 HTML documents to be renderable by DomPDF, or should we always be passing in UTF-8 and thus perform any relevant conversions before calling `loadHtml()`?

**Comment by bsweeney** [comment]
Encoding is a tricky thing to handle gracefully since the encoding of the actual file may differ from the encoding indicated in the HTML headers, which may further differ from the encoding of the transport stream. I believe this is ultimately why we went this route at the time. I personally have looked at this code since that change was implemented.

To be safe you should just pass in UTF8-encoded text. We're happy to look into the issue further if you can provide additional details. Can you provide some more information on the text you're feeding dompdf? Are you loading a remote file or calling loadHtml with the encoding argument?

**Comment by MarkMaldaba** [comment]
> Encoding is a tricky thing to handle gracefully since the encoding of the actual file may differ from the encoding indicated in the HTML headers, which may further differ from the encoding of the transport stream.

By my understanding, the transport encoding should be handled transparently at the transport layer 
before the file contents are returned to the PHP code.

However, more generally, the character encoding can be specified in one of two places - either external to the document, or as markup within the document itself.  In the context of `loadHtml()` any externally-specified encoding is passed in as `$encoding`, therefore for the purposes of this ticket we don't really need to worry about where this comes from, we just need it to be respected.  I have separately logged ticket #1987 to cover the correct handling of externally-defined encodings in `loadHtmlFile()`, but that is a separate issue.

In terms of in-document encoding, there is already some code which is handling this to a certain extent, but it's hard to see whether it is behaving correctly.  For the purposes of this ticket, we can assume it is and if that turns out not to be the case it should be logged as a separate ticket.

Therefore, given the above, the only issue to be resolved is to ensure that if `$encoding` is specified, that it is respected.  I am aware this may not be as simple as it sounds, but I don't think it involves most of the issues you mention in your last response, as these are not the responsibility of this function.

**Comment by lucasMesquitaBorges** [comment]
As @MarkMaldaba said, same problem here, I believe aswell that if $encoding is specified it must be respected and no need to use mb_detect_encoding.

I edited locally to respect $encoding if specified, to rapidly resolve a production problem.

I can handle this issue. Soon i'll submit a PR if no one do it first.
