### ISSUE TITLE
Instructions out of date

### ISSUE THREAD

**Issue by mongldroid** [dompdf/dompdf#1978]
The readme says to include the file:

require_once 'dompdf/autoload.inc.php';

after downloading and moving to the remote directory. This file does not exist. I find an Autoload.php in the src folder, and so then I assume I should now use the following instructions:

require_once 'dompdf/lib/html5lib/Parser.php';
require_once 'dompdf/lib/php-font-lib/src/FontLib/Autoloader.php';
require_once 'dompdf/lib/php-svg-lib/src/autoload.php';
require_once 'dompdf/src/Autoloader.php';
Dompdf\Autoloader::register();

but those files do not exist either. I have read your entire documentation and there is no examples or other instructions for how to load this tool. As a result I get the error:

Uncaught Error: Class 'Dompdf\Dompdf' not found

**Comment by bsweeney** [comment]
What file did you download? You're probably downloading the git source rather than the packaged archive.
