### ISSUE TITLE
the pdf file size is too large

### ISSUE THREAD

**Issue by MrCuire** [dompdf/dompdf#1982]
i create 3 pages pdf file by dompdf and the file size is 3.9m which is too large.Is it any options in dompdf to make the size smaller?

**Comment by bsweeney** [comment]
Are you using fonts other than the PDF core fonts (Helvetica, Times Roman)? If so, do you have font subsetting enabled?

**Comment by MrCuire** [comment]
> Are you using fonts other than the PDF core fonts (Helvetica, Times Roman)? If so, do you have font subsetting enabled?

No,i don't know what is 'font subsetting enabled' , i am Chinese and Helvetica, Times Roman can't support Chinese word.I fix it by chose a smaller font file. Now I create a 7 page file and the file size dropped to 1.94m ,it still large but much better than before. Thank u for tell me about 'font subsetting enabled'.Can't u tell me more like how to use it?

**Comment by bsweeney** [comment]
Font subsetting recreates a font using just the glyphs that are present in the PDF. For any of the ideographic languages with a large set of characters subsetting can save a significant amount of space.

I see we don't have documentation on how to enable it, so here's one way you would enable it:

```
$dompdf = new Dompdf()
$dompdf->set_option('isFontSubsettingEnabled', true);
```

**Comment by chuoke** [comment]
> .I fix it by chose a smaller font file.

@MrCuire 大哥，还记得用的什么小体积字体吗？ 🙏

**Comment by MrCuire** [comment]
不建议用改字体的方式，否则没有安装那个字体的客户端打开pdf会导致空白或者乱码。我的解决方式写在这里了。https://segmentfault.com/a/1190000020364074




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dompdf/dompdf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月3日(星期五) 下午4:20
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [dompdf/dompdf] the pdf file size is too large (#1982)





  
.I fix it by chose a smaller font file.
  
@MrCuire 大哥，还记得用的什么小体积字体吗？ 🙏
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
