### ISSUE TITLE
$dompdf->render(); hangs/freezes

### ISSUE THREAD

**Issue by fillmore-admin** [dompdf/dompdf#1983]
Latest version

```
$pdfExport = trim($html);
				
//dompdf
// instantiate and use the dompdf class
$dompdf = new Dompdf();
$dompdf->loadHtml($pdfExport);
				
// (Optional) Setup the paper size and orientation
$dompdf->setPaper('letter', 'landscape');
				
// Render the HTML as PDF
$dompdf->render();
```

**Comment by bsweeney** [comment]
As in nothing happens and the server just returns an empty response? Or the page just continues loading forever until you get tired of waiting?

**Comment by fillmore-admin** [comment]
> As in nothing happens and the server just returns an empty response? Or the page just continues loading forever until you get tired of waiting?

I was able to narrow it down to something in my CSS.
<html><head><style> ... some bad style in here or something ... </style></head></html>

That, triggered my "The site is experiencing technical difficulties." page from wordpress.
It was a CSS file with about 2000 lines.

**Comment by bsweeney** [comment]
That's a lot of CSS. Glad you were able to narrow it down.
