### ISSUE TITLE
loadHtmlFile() should use the Content-Type HTTP header, if present

### ISSUE THREAD

**Issue by MarkMaldaba** [dompdf/dompdf#1987]
Currently this function always pulls the encoding from the `<meta>` tag, if present, falling-back on `UTF-8` if not.

In addition, it should be checking the returned `Content-Type` header, if present (which would only apply to remote files, obviously) and if this specifies a character set, then this should take precedence over the value in the document (as per [the HTML specification](https://www.w3.org/International/questions/qa-html-encoding-declarations)).

Note that I am logging this for completeness, as it came up in the discussion for ticket #1977.  I don't think this is a particularly urgent issue.

**Comment by lucasMesquitaBorges** [comment]
#2012 Will solve this issue when encoding is informed explicitly.. From Content-type header we still need a better detection encoding.

**Comment by lucasMesquitaBorges** [comment]
#2012 Will solve this issue, as $encoding will be used and we detect it from content-type. It won't be overrided by UTF-8 before convertion.
