### ISSUE TITLE
Certain characters not working with some fonts

### ISSUE THREAD

**Issue by kakitzmiller** [dompdf/dompdf#1989]
I am using Futura Medium font, and I'm noticing that ', ", /, etc don't work.  For the single and double quotes, I could put in the &rsquo; &ldquo; and &rdquo; and they worked, but I can't get the same to work with the forward slash.  Have you run into certain fonts having this issue before?

FYI, running 0.8.3

**Comment by kakitzmiller** [comment]
It also looks like it's leaving out other random characters, specifically K, L, 4, and 5 in this instance.  Below is a screenshot of the html render and the dompdf render, respectively.

![image](https://user-images.githubusercontent.com/24317516/64642713-fb116d80-d3dc-11e9-8103-3cac94feea0e.png)

![image](https://user-images.githubusercontent.com/24317516/64642728-019fe500-d3dd-11e9-9ed1-196c82a5b6b6.png)

**Comment by kakitzmiller** [comment]
I forgot I had extracted the .ttf file from a pdf, and I think it was broken.  I downloaded the file and it appears to work now.  You can close this ticket.

**Comment by bsweeney** [comment]
Thanks for the update. Glad it ended up not being a Dompdf issue (this time).
