### ISSUE TITLE
Quick Start Example is wrong

### ISSUE THREAD

**Issue by simonseyock** [dompdf/dompdf#1992]
In the quick start example the `setPaper` call does not work. It actually has to come before the `loadHtml` call.

**Comment by kristoffermodified** [comment]
I just tested this on v0.8.3 and this doesn't seem to be an issue anymore?

It correctly changes the paper to A5 in landscape mode. This was tested running PHP 7.3.13.

Code:
```php
use Dompdf\Dompdf;

$dompdf = new Dompdf();
$dompdf->loadHtml('hello world');

$dompdf->setPaper('A5', 'landscape');

$dompdf->render();

$dompdf->stream()
```

**Comment by bsweeney** [comment]
@kristoffermodified thanks for the check.

@simonseyock which version of Dompdf were you using when you tried this?

**Comment by bsweeney** [comment]
I am also unable to reproduce the issue. There was a period of time where there were some problems with how this was handled but the latest release should be OK. If you're still having issues please let us know which version of Dompdf and provide a sample of both the PHP utilizing Dompdf and the HTML you're attempting to render.
