### ISSUE TITLE
the pdf file can't display Chinese characters in Mac/IOS/Andriod system

### ISSUE THREAD

**Issue by MrCuire** [dompdf/dompdf#1993]
My file can display Chinese characters in windows system.It seem like a font file problem . Because the problem only arise on the situation that I using a dark horse font .The character can display in any system When I using a common Chinese font file simsun(宋体) .

**Comment by bsweeney** [comment]
Have you read through the [Unicode How-To](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo)? If not can you provide a sample of the HTML?

**Comment by wpshushu** [comment]
@bsweeney Same problem here. I did follow [Unicode How-To](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo) [Here](view-source:https://falanxi360.com/?debug_custom_invoice=yes&order_id=2883) is the HTML page I intend to convert to PDF. I am using a Google Font, as you can see from the page source. My code is straightforward:

`
	$dompdf = new Dompdf();
	$dompdf->loadHtml($html);
	$dompdf->setPaper('A4', 'landscape');
	$dompdf->render();
	echo $dompdf->stream();

`

Could you shed a light why it isn't working? 


Thanks.
