### ISSUE TITLE
Encoding - special char Č

### ISSUE THREAD

**Issue by Orange06** [dompdf/dompdf#1996]
Trying all possible solutions from known issues, using header('Content-type: text/plain; charset=utf-8'); or mb_internal_encoding('UTF-8'); or meta http-equiv="Content-Type" content="text/html; charset=utf-8", special character Č is still not working which means utf8 ecoding is not working.
Has anyone encountered on this problem and found solution yet ?

**Comment by Orange06** [comment]
Okay, after 14132534232412412 tries, included fonts - for example dejavusans and helvetica should be latin-extended but they are actually not. 
By far the simplest solution is to @import font from google fonts one that has latin-extended support, but carefull, all of them are not working also, for example, Josefin sans still dont render ČčĆć.. Roboto works fine so it will have to be enough for now.
Cheers.

**Comment by bsweeney** [comment]
DejaVu Sans does support that character. The following works fine for me:

```
<span style="font-family: DejaVu Sans, sans-serif;">Č</span>
```

Might be something specific to your HTML or Dompdf configuration.

**Comment by bsweeney** [comment]
I can confirm it displays correctly when set to bold as well.
