### ISSUE TITLE
Function create_function() is deprecated

### ISSUE THREAD

**Issue by Evanzyl** [dompdf/dompdf#1999]
I'm getting this message for Laravel 5:

ErrorException in text_frame_reflower.cls.php line 376:
Function create_function() is deprecated

How can I fix this. Can't seem to get any answers on this issue.

Thanks.

**Comment by hapidjus** [comment]
Its due to the create_function function being deprecated in your PHP version.
Are you using the latest version of dompdf?

**Comment by bsweeney** [comment]
Based on the implicated filename that's a pretty old version of Dompdf. I suggest updating to the latest release.

**Comment by Evanzyl** [comment]
How do I know what version of Dompdf I'm using? Sorry I inherited this website and not complete familiar with Laravel yet. If I upgrade, can I just download the files and ftp the new files to the server?

**Comment by bsweeney** [comment]
@Evanzyl identifying the version depends on how Dompdf was installed. We're still trying to make this easier to do, but if you're using Composer then you can use `composer show` to see which package versions are installed. If you're using a packaged download, then the Dompdf directory should have a VERSION file with version information (for more recent versions anyway). If neither of those work you can try looking at the folder structure to see if you're using a _really_ old version (i.e. < 0.7.0 will have an include directory, and anything newer will have a src directory).
