### ISSUE TITLE
lib/Cpdf.php is missing a global namespace declaration for Imagick

### ISSUE THREAD

**Issue by josephkmh** [dompdf/dompdf#2000]
**PHP version:** 7.0.33
**dompdf version:** 0.8.3

I'm working on a WordPress site that has a plugin which requires dompdf as a dependency. I have just run into the problem that the class `Imagick` cannot be found, although it is installed properly on the server.

I dug around the code and found that `Imagick` is not properly namespaced in [lib/Cpdf.php on line 4859](https://github.com/josephkmh/dompdf/blob/master/lib/Cpdf.php#L4859).

Essentially, changing `Imagick::IMAGICK_EXTVER` to `\Imagick::IMAGICK_EXTVER` fixes the issue. I have opened a pull request #2001 to fix this.

All other instances of `Imagick` are properly referenced as `\Imagick`, so I assume this was just an oversight. I am, however, not very familiar with dompdf or the Cpdf.php dependency. So apologies if this is not the correct way to address this.

**Comment by bsweeney** [comment]
Thanks for the report and pull request. We'll add it to the next release.

**Comment by bsweeney** [comment]
addressed by #1851
