### ISSUE TITLE
CSS @page Selectors like :left, :right, :odd, :even and :first are ignored

### ISSUE THREAD

**Issue by ccharz** [dompdf/dompdf#2002]
If i add a specific margin to the first page like so:

`@page :first { 
     margin: 0 !important;
}`

the definition is ignored.

When I look at the source of the \Dompdf\Css\Stylesheet class the cause for this problem seems to be that in the switch-case is missing a "break" and always runs into the default case "break 2" which skips the css rule completly.

https://github.com/dompdf/dompdf/blob/master/src/Css/Stylesheet.php#L1362

**Comment by keksdieb** [comment]
I guess there's a break operator missing below $key = $page_selector. This would work:

`
                            case ":left":
                            case ":right":
                            case ":odd":
                            case ":even":
                            /** @noinspection PhpMissingBreakStatementInspection */
                            case ":first":
                                $key = $page_selector;
                                break;

                            default:
                                break 2;`

**Comment by bsweeney** [comment]
ref #1898, addressed in cccb56d5150ff1e4b921ef0b087dee645d6866e8

**Comment by bsweeney** [comment]
FYI the noinspection statement is for coding standard validator like [squizlabs/PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer)
