### ISSUE TITLE
[PHP 7.4 RC3] Invalid characters passed for attempted conversion, these have been ignored

### ISSUE THREAD

**Issue by HepplerDotNet** [dompdf/dompdf#2003]
After updating my DEV box from PHP 7.3.10 to PHP 7.4-RC3 my Laravel 6.2 App, running dompdf v0.8.5, throws this error when trying to generate PDF:
**Invalid characters passed for attempted conversion, these have been ignored** 
Error occurs on vendor/dompdf/dompdf/lib/Cpdf.php:2545
```
if ($c >= 0) {
  if ($c != hexdec($n)) {
    $data['codeToName'][$c] = $n;
  }
  $data['C'][$c] = $width;
} else {
  $data['C'][$n] = $width;
}
```

**Comment by Messhias** [comment]
Hello, 

I'm facing the same issue, I tried to change the source code but more errors ha been triggered and it gets worst, the only solution for now for me it was a rollback to PHP 7.3 and wait for the most stable version.

But I'm following the thread to see if someone comes with a solution.

**Comment by LeRoyJulian** [comment]
Problem still here with PHP 7.4 final.

**Comment by LeonardoBuares** [comment]
Same problem here, PHP 7.4 final

**Comment by m4rcoperuano** [comment]
Same same same ugh :(

**Comment by m4rcoperuano** [comment]
After wasting 2 hours, I found a work around (ugh). Hope it helps

I found this in PHP 7.4's deprecated notes:
https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.core.invalid-base-characters

> Passing invalid characters to base_convert(), bindec(), octdec() and hexdec() will now generate a deprecation notice. The result will still be computed as if the invalid characters did not exist. Leading and trailing whitespace, as well as prefixes of type 0x (depending on base) continue to be allowed.

That deprecation notice was crashing my app; I kept seeing this exception being thrown `Invalid characters passed for attempted conversion, these have been ignored`. This got me thinking that, if it's ignoring these values, then it should just CONTINUE to work, but it wasn't. But maybe my PHP settings were treating deprecations as fatal errors. So after some digging, I found a SO post on how to turn off deprecation notices:

https://stackoverflow.com/questions/2803772/turn-off-deprecated-errors-in-php-5-3

I think you can edit these values in your php-ini file , but i didn't want this to be a global thing. So instead, I just put this function:

`error_reporting(E_ALL ^ E_DEPRECATED);`

... in the file that was throwing these errors (the file generating my PDF), and :tada:...sigh.

**Comment by Messhias** [comment]
The problem of ignoring the depreciation warnings is because when they
remove the feature your code could broken.

**Comment by LeRoyJulian** [comment]
Quick fix. Line 2543, add : 
` if (ctype_xdigit($c) && ctype_xdigit($n)) {`
Then close after following if statement.

**Comment by m4rcoperuano** [comment]
@Messhias Correct, it's not good practice. But a decent enough bandaid for my usecase. I'm only disabling the deprecation warning for requests that will output a PDF, so not system-wide. Waiting for a more elegant fix or for a dompdf update :)

**Comment by Messhias** [comment]
> @Messhias Correct, it's not good practice. But a decent enough bandaid for my use case. I'm only disabling the deprecation warning for requests that will output a PDF, so not system-wide. Waiting for a more elegant fix or a dompdf update :)

I tried to figure out here taking with the last PHP FPM docker image, work partially without "workaround",  but when you try to generate some pages with a lot images and colors triggers the most variety of errors XD

**Comment by LeRoyJulian** [comment]
Well, this is still not fixed yet... Time to switch to another PDF lib ?

**Comment by Messhias** [comment]
@LeRoyJulian I switched, I create a lambda javascript function on my AWS services to generate this for me. 

I already removed the dependency from my project.

**Comment by neoteknic** [comment]
> Quick fix. Line 2543, add :
> ` if (ctype_xdigit($c) && ctype_xdigit($n)) {`
> Then close after following if statement.

I made a PR for this...

**Comment by Astriaporta** [comment]
> Solution rapide. Ligne 2543, ajoutez:
> ` if (ctype_xdigit($c) && ctype_xdigit($n)) {`
> puis fermez après avoir suivi l'instruction if.

I confirm. This fix the problem.

**Comment by mberneis** [comment]
Can be done in one line as interpreter stops evaluating after first false (2545:
```
 if (ctype_xdigit($c) && ctype_xdigit($n) && $c != hexdec($n)) {
```

**Comment by bsweeney** [comment]
@mberneis that's not quite what we want. `$c` is always an int (cast as such when set) so basically we just need to check to see if the decimal value of `$n` matches `$c`. If `$n` is not a hex value then it should be a glyph name, which is what the original condition is actually checking for.

So, I used `!ctype_xdigit($n) || $c != hexdec($n)`. 

For others `ctype_xdigit($c) && ctype_xdigit($n)` pretty much just makes the error go away but actually introduces a bug since the condition being checked is, basically, the opposite of what was being done before.

**Comment by DenjanD** [comment]
> Can be done in one line as interpreter stops evaluating after first false (2545:
> 
> ```
>  if (ctype_xdigit($c) && ctype_xdigit($n) && $c != hexdec($n)) {
> ```

thanks for the help. it works really well

**Comment by jahidulrudro** [comment]
just replace line to
`if ($c >= 0) {
                                if (ctype_xdigit($c) && ctype_xdigit($n)) {
                                    $data['codeToName'][$c] = $n;
                                }
                                $data['C'][$c] = $width;
                              }`

it will solve the issue

**Comment by qahtansaid** [comment]
just try to type "Composer Update" it solved my issue

**Comment by LeonBuchner** [comment]
Downgrade to PHP 7.3 fixed the issue for me

**Comment by jeantalons** [comment]
> just replace line to
> `if ($c >= 0) { if (ctype_xdigit($c) && ctype_xdigit($n)) { $data['codeToName'][$c] = $n; } $data['C'][$c] = $width; }`
> 
> it will solve the issue

best answer.
melhor resposta.

**Comment by bsweeney** [comment]
The 0.8.4 release of Dompdf addressed this issue.

**Comment by cibermesias** [comment]
> The 0.8.4 release of Dompdf addressed this issue.

Thanks, man, updating DOMPDF was all I needed.

**Comment by steffersonj** [comment]
Hi all,

This is how I use it with PHP 7.4 and by pass all warnings: 

ob_start();
    error_reporting(E_ALL & ~E_NOTICE);
    ini_set('display_errors', 0);
    ini_set('log_errors', 1);
    //convert html to pdf
    $pdf = array(
        'fileName'      => $pdf_title,
        'size'          => 'a4',
        'orientation'   => 'portrait',
        'html'          => $pdf_body,
        'savePath'      => '',
        'output'        => false
    );
    ob_end_clean();
    $cms->generatePDF($pdf);


I hope this helps!

**Comment by houghtonacciona** [comment]
> hen close after following if stateme

Still working and saving lives on October 2020

**Comment by houghtonacciona** [comment]
> Quick fix. Line 2543, add :
> ` if (ctype_xdigit($c) && ctype_xdigit($n)) {`
> Then close after following if statement.

Still working and saving lives on October 2020

**Comment by jimdamian** [comment]
> Can be done in one line as interpreter stops evaluating after first false (2545:
> 
> ```
>  if (ctype_xdigit($c) && ctype_xdigit($n) && $c != hexdec($n)) {
> ```

Confirm, its work.

**Comment by uisumo** [comment]
> Can be done in one line as interpreter stops evaluating after first false (2545:
> 
> ```
>  if (ctype_xdigit($c) && ctype_xdigit($n) && $c != hexdec($n)) {
> ```

This will work. Thanks a lot

**Comment by wagnerloch** [comment]
> just replace line to `if ($c >= 0) { if (ctype_xdigit($c) && ctype_xdigit($n)) { $data['codeToName'][$c] = $n; } $data['C'][$c] = $width; }`
> 
> it will solve the issue

Still working in 2024, thank you for your simple solution
