### ISSUE TITLE
laravel 5.8 dompdf arabic are displaying in individually words not in string and reverse format

### ISSUE THREAD

**Issue by arshadsherani** [dompdf/dompdf#2004]
I am using laravel 5.8 dompdf for arabic but text are not displaying properly. first it's in reverse format and second it's not combined form. I have set font-family: DejaVu Sans,sans-serif and changed "default_font" => "dejavu sans" in config file but still facing this issue.  assist me regarding this. Thanks

**Comment by bsweeney** [comment]
By reverse format are you referring to expecting the text to display right-to-left? Dompdf does not currently support that functionality. Watch #1009 for updates.

As for separated characters. That's also a known issue. You can watch #712 for updates on fully supporting Arabic. There is a work-around for the problem noted in that issue.
