### ISSUE TITLE
Deprecated function: PDFlib::get_value(): Deprecated, use PDF_get_option() in get_value() (line 1289 of /var/www/html/vendor/dompdf/dompdf/src/Adapter/PDFLib.php)

### ISSUE THREAD

**Issue by rsanzante** [dompdf/dompdf#2007]
PHP: 7.1.17
PDFlib GmbH Binary-Version: 9.2.0
Dompdf: v0.8.3

I got this error message: 

> Deprecated function: PDFlib::get_value(): Deprecated, use PDF_get_option() in get_value() (line 1289 of /var/www/html/vendor/dompdf/dompdf/src/Adapter/PDFLib.php)

This comes from those lines: 
```
$asc = $this->_pdf->get_value("ascender", $fh);
$desc = $this->_pdf->get_value("descender", $fh);
```

PDFLib 9.x deprecated the get_value function. They instruct to use get_option. Unfortunately, the params seem different and I didn't find a way to translate from one function to another.

I  found, however, a PDFLib example to get font info here: 
https://www.pdflib.com/pdflib-cookbook/fonts/font_metrics_info/php/

They use the function info_font. I blindly replace the above code with:
```
$asc = $this->_pdf->info_font($fh, "ascender",  "fontsize=$size");
$desc = $this->_pdf->info_font($fh, "descender", "fontsize=$size");
```
$size is the font size and is needed by the info_font function. The value is available in the original code.

However, the value returned seems $size times greater. So I switched to:

```
$asc = $this->_pdf->info_font($fh, "ascender",  "fontsize=$size") / $size;
$desc = $this->_pdf->info_font($fh, "descender", "fontsize=$size") / $size;
```

It seems to work, but honestly I don't know what I'm doing.

Maye someone with more knowledge on PDFLib and Dompdf can validate this or propose a better solution.

**Comment by rsanzante** [comment]
PR ready: https://github.com/dompdf/dompdf/pull/2020

**Comment by noone-silent** [comment]
PDFLib 6 documentation says: 

`ascender = PDF_get_value(p, "ascender", font) * fontsize;`
`descender = PDF_get_value(p, "descender", font) * fontsize;`

So if the value from info_font is larger than $size, it seems they integrated the calculation into info_font. I don't think you need to divide it by $size. Even on the example page they do not divide it

**Comment by rsanzante** [comment]
> PDFLib 6 documentation says:
> 
> `ascender = PDF_get_value(p, "ascender", font) * fontsize;`
> `descender = PDF_get_value(p, "descender", font) * fontsize;`
> 
> So if the value from info_font is larger than $size, it seems they integrated the calculation into info_font. I don't think you need to divide it by $size. Even on the example page they do not divide it

Keep in mind that I'm not using PDF_get_value because PDFLib 9.x deprecated the get_value function. I'm using the info_font function, see first comment.

**Comment by noone-silent** [comment]
That's not what I meant. PDF_get_value with ascender/descender is only available in PDFlib 6, from PDFlib 7+ one should use info_font. Have you read what I posted of the * $fontsize?

**Comment by rsanzante** [comment]
@noone-silent, yes I've read it, but I'm sorry, I don't know how PDFlib manges fonts and don't have much knowledge on fonts, so I don't totally understand it. 

I've played a little more. Currently, if I call
`$this->_pdf->info_font($fh, "ascender",  "fontsize=11");`

I got `8.008`. 

Other example: calling the same code with `fontsize=19.25` the result is `14.014`.

Those values, according to documentation, are the fraction of the font size. I don't understand this, because 8.008, if it's a fraction, means the ascender is 8 times the font size. Could it be over 10 instead of 1? So it would 80% of fontsize. Still too high. May over 100? So it's 8% from fontsize.

Anyway, the only  thing I know is that if I use the above code there are big blank spaces between lines on the generated PDF file. 

I agree dividing by $size makes no sense (it seems result may be close to the right values just by chance), but I don't know what to do with the ascender/descender values.

Just for the record, later in this `get_font_height` function the values are used for the return value:

` return $size * ($asc - $desc) * $ratio;`

**Comment by noone-silent** [comment]
8.008 looks good to me. Take a look at the second image on the right on the following Wikipedia article:
https://en.wikipedia.org/wiki/Ascender_(typography)

So on a font size of 11 the ascenders start at 8.008 and with a font size of 19.25 the ascenders start at 14.014

Even the sample from PDFLib looks wrong to me. The descender is shown correctly, but the ascender is the whole font height from the baseline.

The great question is, how is the function used in dompdf? Is it used to really get the ascender or is it used to get the used font height? Maybe @bsweeney can answer this?

**Comment by bsweeney** [comment]
So I did a bit more research to see what changed between the new and old methods.

The PDFLib 6 API doc states:
> get_value(capheight|ascender|descender): Returns metrics information for the font identified by the modifier. The values are measured in fractions of the font size, and must therefore be multiplied by the desired font size.

and

>The values of capheight, ascender, and descender for a specific font can be queried from PDFlib as follows:
> ```
> float capheight, ascender, descender, fontsize;
> ...
> font = PDF_load_font(p, "Times-Roman", 0, "winansi", "");
> PDF_setfont(p, font, fontsize);
> capheight = PDF_get_value(p, "capheight", font) * fontsize;
> ascender = PDF_get_value(p, "ascender", font) * fontsize;
> descender = PDF_get_value(p, "descender", font) * fontsize;
> ```

So, the old method returned the multipler that you could use to calculate the ascender/descender values. So to figure out the font height with the old method Dompdf took the sum of those values, multiplied that by the font height to get the distance between the ascender and descender, then multiplied by the Dompdf font height ratio (for spacing).

The new method returns the actual distance of the ascender/descender from the baseline. So what we get from the two methods methods is significantly different.

The PDFLib 9 API doc states:

> info_font(ascender): Metrics value for the ascender. Supported options:
> - faked(Boolean) 1 if the value had to be estimated because it was not available in the font or metrics file, otherwise 0
> - fontsize(Fontsize) Value will be scaled to the specified font size (default: fontsize=1000)

And from the [PDFLib cookbook](https://www.pdflib.com/pdflib-cookbook/form_fields/form_textfield_height/) (which reflect PDFLib 9 usage as of this writing):

```
/* Create another text field "date3". In this case, the font size is
 * given as a fixed value of 24 and the field height should be chosen
 * appropriately: Retrieve the ascender and descender (which is usually
 * negative) of the font size 24. The resulting value will be a good
 * starting point for determining the field height, for example.
 * 
 * Since the behaviour of Acrobat regarding the chosen font and 
 * baseline is not obvious, the field height will be too small in many
 * cases. To avoid that we add a margin of an appropriate percentage of
 * the field height, e.g. 50%.
 */
ascender = p.info_font(font, "ascender", "fontsize=24");
descender = p.info_font(font, "descender", "fontsize=24");

height = (ascender - descender) * 1.5;
```

Here's what I got from a quick test using Times Roman at 37.5pt:

*get_value* (old)
- Ascender: 0.718
- Descender: -0.207

*info_font* (new)
- Ascender: 26.925
- Descender: -7.7625

As you can see, the values given by the old method, multiplied by the font size, give you the values from the new method (e.g. 0.718 * 37.5 = 26.925).

Based on this information I think the modification to these lines should just be:

```
$asc = $this->_pdf->info_font($fh, "ascender", "fontsize=$size");
$desc = $this->_pdf->info_font($fh, "descender", "fontsize=$size");

return (abs($asc) + abs($desc)) * $ratio;
```

@rsanzante if you go ahead and make that tweak I'll merge the PR.

**Comment by rsanzante** [comment]
PR updated, thanks!
