### ISSUE TITLE
Windows defender is marking the PDF as TrojanDownloader:PDF/Domepidief.A!eml

### ISSUE THREAD

**Issue by ahmadb-allshore** [dompdf/dompdf#2008]
I have a process where the PDF files is created and uploaded to GDrive and attached in the email as well to the customer.
Some of the clients have been complaining that their windows defender is not downloading the email attachment file and marking it as **TrojanDownloader:PDF/Domepidief.A!eml**
I have also had this tested and the issue is there. 

Please note that file is downloading successfully from the GDrive and server. The issue is only in the case of downloading email attachment

I am using `Laravel 5.7`
Php version 7.3

TIA
Regards
Baig

**Comment by ahmadb-allshore** [comment]
> I've encountered this as well, do you have any hyperlinks in your pdf by any chance? Just a theory that hyperlinks may be triggering the false-positive somehow

Yes there are some hyperlinks in my generated PDF. Did you find the solution for this?

**Comment by djhexy** [comment]
Interesting. I've a theory that hyperlinks are the cause of the false-positive after reading this page about the how the virus behaves: https://www.pcrisk.com/removal-guides/13621-trojandownloader-pdf-domepidiefa-virus 

I'm currently liasing with a Client who should be testing a version of our generated content that doesn't have hyperlinks present to see if it stops the "detection".

**Comment by ahmadb-allshore** [comment]
> Interesting. I've a theory that hyperlinks are the cause of the false-positive after reading this page about the how the virus behaves: https://www.pcrisk.com/removal-guides/13621-trojandownloader-pdf-domepidiefa-virus
> 
> I'm currently liasing with a Client who should be testing a version of our generated content that doesn't have hyperlinks present to see if it stops the "detection".

Let me know if that works. We will also look for another solution then

**Comment by ahmadb-allshore** [comment]
Apparently this issue is resolved when I removed the hyperlinks from my generated PDF

**Comment by bsweeney** [comment]
Huh, that's an interesting find. Thanks for the heads-up.

adding info to #952
