### ISSUE TITLE
Dompdf & PHP 7.2

### ISSUE THREAD

**Issue by Evanzyl** [dompdf/dompdf#2016]
I need some help please. My hosting company moved over to PHP 7.2 and now the dompdf function is not working anymore.

I updated the following folders (via ftp - don't have composer available)
vendor/barryvdh
vendor/dompdf

I tested version 6, 7 and 8 and I'm getting errors on all of them for example:
Fatal error: Class 'Dompdf\Dompdf' not found

What am I doing wrong and how can I get this function to work again?

Any suggestions would be greatly appreciated.

Thank you.

**Comment by noone-silent** [comment]
Check the paths in your autoloader or include/require. Have they changed?

**Comment by Evanzyl** [comment]
What exactly should I be looking for? I tested it now and getting this error:

FatalThrowableError in ServiceProvider.php line 49:
Fatal error: Class 'Dompdf\Dompdf' not found

Thanks

**Comment by noone-silent** [comment]
Use get_included_files() and search for Dompdf/Dompdf.php. If it is missing something is wrong with loading the file. Maybe the path in vendor/autoload.php is wrong.

**Comment by bsweeney** [comment]
@evanzyl you might try upgrading to a newer version of Dompdf, but really this looks like something else. Are you using Domdpf inside another framework? What is ServiceProfvider.php?
