### ISSUE TITLE
Trying to create the ufm inside the vendor directory

### ISSUE THREAD

**Issue by vivoconunxino** [dompdf/dompdf#2017]
I'm getting a permissions issue because of this, did I miss any configuration step? I couldn't see any of this in the docs nor Google.

> Uncaught PHP Exception ErrorException: "Warning: fopen(/var/www/current/backend_test/vendor/dompdf/dompdf/lib/fonts/3acefc91d6a5f4f2c1e9e3a30075afb6.ufm): failed to open stream: Permission denied" at /var/www/current/backend_test/vendor/phenx/php-font-lib/src/FontLib/AdobeFontMetrics.php line 45

**Comment by bsweeney** [comment]
By default Dompdf stored font information in Dompdf/lib/fonts. If you want/need to use another location you can set the fontDir and fontCache options:

```
$dompdf->set_option('fontDir', '/path/to/font/storage/directory');
$dompdf->set_option('fontCache', '/path/to/font/cache/directory');
```

**Comment by jtomek** [comment]
For reference: https://github.com/barryvdh/laravel-dompdf/issues/687
