### ISSUE TITLE
Table with colspan-rowspan issue

### ISSUE THREAD

**Issue by mbourne** [dompdf/dompdf#2018]
I have a table involving colspan and rowspan that gives messy results when the content of the rowspan cell has less height than the adjacent rowspan cell.

Here's the table:

    <table>
      <tr>
        <td>Cultural Intelligence</td>
        <td colspan="2">The ability to &nbsp;loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.</td>
      </tr>
      <tr>
        <td>Traits</td>
        <td colspan="2">Performance</td>
      </tr>
      <tr>
        <td rowspan="2">&nbsp;loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances and rain on my parade </td>
        <td>Not Yet But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the systems. Does not seek information to handle new tasks.</td>
        <td>Substantially Developed and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful</td>
      </tr>
      <tr>
        <td colspan="2">Evaluation: Not Yet 1 2 3 4 5 6 7 8 9 10 Substantially Developed</td>
      </tr>
      <tr>
        <td rowspan="2">CQ &nbsp;loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.</td>
        <td>Not Yet Demonstrates little understanding of general and/or specific cultures involved. 
    </td>
        <td>Substantially Developed Demonstrates excellent insights of general and/or specific cultures involved.</td>
      </tr>
      <tr>
        <td colspan="2">Evaluation: Not Yet 1 2 3 4 5 6 7 8 9 10 Substantially Developed</td>
      </tr>
      <tr>
        <td rowspan="2">CQ Strategy &nbsp;loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.</td>
        <td>Not Yet &nbsp;loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.</td>
        <td>Substantially &nbsp;loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure..</td>
      </tr>
      <tr>
        <td colspan="2">Evaluation: Not Yet 1 2 3 4 5 6 7 8 9 10 Substantially Developed</td>
      </tr>
    </table>

The CSS:

    table{border:none}
    table td,table th{border:0.01em solid #444}
    @page {
        size: 21cm 29.7cm;
        margin: 20mm 25mm 20mm 25mm;
    }

This results in:

![image](https://user-images.githubusercontent.com/7541940/68528713-74700280-0331-11ea-9658-154a5e34646f.png)

It appears that because the "loves or pursues" cell is not as high as the TDs to the right of it, thus messing things up.

However, if I give that first td with a colspan (the first "evaluation" one, background grey) a fixed height (in this case 50 px - anything less and it still resulted in overlapping TDs) then the whole thing behaves itself:

![image](https://user-images.githubusercontent.com/7541940/68528612-05de7500-0330-11ea-8765-3828a9919fc8.png)

This involves user-generated content, so I won't know in advance what will be the height of different cells, nor how many rows or columns will be spanned.

Any help would be appreciated.

**Comment by bsweeney** [comment]
No idea at first glance but I'll continue to analyze the issue and see what I can find.

**Comment by bsweeney** [comment]
This was previously reported in #1328. The next release will include a fix for the issue.
