### ISSUE TITLE
Laravel, Dompdf & PHP 7.2

### ISSUE THREAD

**Issue by Evanzyl** [dompdf/dompdf#2019]
I need help please. My hosting company moved over to PHP 7.2 and now the dompdf function is not working anymore.

I updated the following folders (via ftp - don't have composer available)
vendor/barryvdh
vendor/dompdf

I tested version 6, 7 and 8 and I'm getting errors on all of them for example:
Fatal error: Class 'Dompdf\Dompdf' not found

What am I doing wrong and how can I get this function to work again?

Any suggestions would be greatly appreciated.

Thank you.

**Comment by bkuhl** [comment]
This isn't an issue with the package, but an issue of how you're using it.  To be honest this question is better suited for StackOverflow.  

> don't have composer available

[This article](https://blog.jgrossi.com/2013/why-you-should-use-composer-and-how-to-start-using-it/) may provide some insight on what composer does and help you see what the underlying issue is.

**Comment by bsweeney** [comment]
Agreed. And with no response not sure we could provide additional guidance anyway. Surely the host can provide some support for how to update the system.

**Comment by Evanzyl** [comment]
Hi bkuhl  & bsweeney

Thank you for your comments. Just some background to this problem. I inherited this Laravel website. Dompdf is there and working at the moment on PHP 5.6. The hosting company is changing the PHP version to 7.2 and the current Dompdf function doesn't work on it. When I switch over to this PHP version I'm getting all the errors. I thought if I just update the 2 Dompdf packages everything should work... but it doesn't

Not sure how to et this fixed.

**Comment by bsweeney** [comment]
I have no idea. You'll have to do some basic trouble-shooting to figure it out. The fact that the class can't be found after upgrading means you're maybe not referencing the autoloader correctly. Which version of Dompdf were you using before the PHP upgrade? What package did you download for those releases? What is the relevant PHP code?

**Comment by bkuhl** [comment]
This project is stable on PHP 7.2 as of at least 0.8.3, so if you're encountering issues it's either the autoloader or your'e using an older version.
