### ISSUE TITLE
Helpers::encodeURI() breaks parameter strings

### ISSUE THREAD

**Issue by SlowFox71** [dompdf/dompdf#2021]
```
strtr(rawurlencode(rawurldecode($uri)), array_merge($reserved,$unescaped,$score));
```

This piece of code takes care that (amongst others), a "+" sign (used instead of a blank) remains a "+" sign. But problems arise if an URI contains a **real** plus sign, correctly encoded as "%2B" (or, even worse, an amphersand).

This small example reproduces the steps of the conversion:
```
$uri = '?a[]=1&b%5B%5D=1&c=d+e&f=g h&i=j%2Bk%26l';echo $uri . "\n";
echo rawurldecode($uri) . "\n";
echo rawurlencode(rawurldecode($uri)) . "\n";
echo strtr(rawurlencode(rawurldecode($uri)), array_merge($reserved, $unescaped, $score)) . "\n";
```

Results are:
> ?a[]=1&b%5B%5D=1&c=d+e&f=g h&i=j%2Bk%26l
> ?a[]=1&b[]=1&c=d+e&f=g h&i=j+k&l
> %3Fa%5B%5D%3D1%26b%5B%5D%3D1%26c%3Dd%2Be%26f%3Dg%20h%26i%3Dj%2Bk%26l
> ?a%5B%5D=1&b%5B%5D=1&c=d+e&f=g%20h&i=j+k&l

Everything is fine for characters which have to be escaped like "[]" and fine for characters which may not be escaped like "?" and "&". But if special characters are in the original string, they are broken in the result, as in "i=j+k&l".

I am not far enough into this to have a solution at my fingers. The first rawurldecode() ruins the string, so a completely different approach must be used here.

**Comment by SlowFox71** [comment]
Ok, some findings:

Helpers::encodeURI($uri) does, what the comments say: "Assumes that the URI is a complete URI, so does not encode reserved characters that have special meaning in the URI".

But if there is an <img> tag in the HTML source, this is handled in the constructor of FrameDecorator\Image:

`$url = $frame->get_node()->getAttrlist("src");`
`list($this->_image_url, /*$type*/, $this->_image_msg) = Cache::resolve_url($url, ...);`

If the URL is remote and fully qualified, Cache::resolve_url() calls Helpers::getFileContent() which in turn calls Helpers::encodeURI(). Problem is, the original URI must already be escaped; if it is not, the HTML is broken, which is clearly not our fault. So the error is **not** (as I expected in the beginning) a problem in Helpers::encodeURI(), but rather the fact that Helpers::encodeURI() **is called at all**. Every external URI containing special characters will break this way.

For me it is sufficient to drop the call of Helpers::encodeURI() in Helpers::getFileContent(). As the latter method might be called somewhere else (with an unescaped URI), I am not sure, if this is a generally valid solution.

**Comment by bsweeney** [comment]
This is interesting and has me wondering if it is the cause of #2054.

**Comment by KbaylonH** [comment]
I'm having this problem with images hosted in Firebase. For the moment, I just need to convert the images to data-uri.

**Comment by KbaylonH** [comment]
I think one way to handle this problem would be to add an new attribute in the img tag called "encode", whose value is a boolean. This new attribute indicates whether or not it is necessary to encode the url.

**Comment by bsweeney** [comment]
Apparently I made this change in 7f170fb340d6f317ec5203862a25b3858de0e10e. I didn't link to any issues nor provide any guidance in the commit message so I'm not sure why I made that change. Perhaps it was to avoid potential issues with unencoded characters (such as the space in the example). But if that's the case my thinking has evolved, the user should ensure their HTML is properly encoded. I'll consider removing this from the next release.

**Comment by bsweeney** [comment]
I probably added this in order to perform some type of URL normalization, similar to what most web browsers do (relevant on SO: https://stackoverflow.com/a/11071438/264628) because file_get_contents can be finicky. Will need to consider how best to handle this, though removal of that logic may still be the best option.

**Comment by bsweeney** [comment]
In removing that function from the code the Google font URL in 2054 still fails as is or encoded, whereas it does work when using the encodeUri function and the Google URL is already encoded. So, it does seem like I added this in an attempt to manage issues around using file_get_contents. Will definitely need to put a little more thought into this.

**Comment by Akecel** [comment]
If someone passes by here by the biggest of the chances, personally to circumvent this problem, I had no other choice than to overide this file in my composer and by removing the call to this function `encodeURI` which was not useful in my use.

```
  "autoload": {
    "files": [
      "app/Extensions/DomPDF/Helpers.php"
    ],
    "exclude-from-classmap": [
      "/vendor/dompdf/dompdf/src/Helpers.php"
    ]
  },
```

This is of course far from an optimal solution and it is particularly sensitive to breacking change (a new function in the Helper file called in the rest of the package will undoubtedly cause a problem so I have to watch this particular case.)

But if this can help as a temporary solution for some

**Comment by bsweeney** [comment]
I believe I added the call to rawurldecode (which was not in the original StackOverflow answer) in order to avoid double-encoding any characters. Of course, as shown, that does have the potential to break URLs where a special character was already encoded. I think the actual solution to the double-encoding problem is to use the original method but add a step to replace any double-encoded characters with the single-encoded character (`preg_replace('/\%25([a-fA-F0-9]{2,2})/', '%$1', strtr(rawurlencode($uri), array_merge($reserved, $unescaped, $score)))`).

I think the method could be further improved by encoding each URI component separately since the rules can vary between components. I may push that particular improvement to a future release.
