### ISSUE TITLE
PDF Generation working fine on Testsystem but not on Live-Environment

### ISSUE THREAD

**Issue by TSInf** [dompdf/dompdf#2025]
Hallo Dear DOMPDF-Developers,
i used DOMPDF to create a PDF Generation of a Customer Offer.

On the Testsystem it is working very fine. On Live Environment all elements are on the same page, no page break.

DOMPDF Version is 0.8.3.

Here are the Head-Data of the 2 System:

**Testsystem**: WAMP64, Windows 10 64-bit, PHP 7.2.4 64-bit.
Extensions:

DOM/XML | enabled
DOM/XML API Version | 20031129
libxml Version | 2.9.7
HTML Support | enabled
XPath Support | enabled
XPointer Support | enabled
Schema Support | enabled
RelaxNG Support | enabled

Multibyte Support | enabled
Multibyte string engine | libmbfl
HTTP input encoding translation | disabled
libmbfl version | 1.3.2
oniguruma version | 6.3.0

GD Support | enabled
GD Version | bundled (2.1.0 compatible)
FreeType Support | enabled
FreeType Linkage | with freetype
FreeType Version | 2.8.1
GIF Read Support | enabled
GIF Create Support | enabled
JPEG Support | enabled
libJPEG Version | 9 compatible
PNG Support | enabled
libPNG Version | 1.6.34
WBMP Support | enabled
XPM Support | enabled
libXpm Version | 30512
XBM Support | enabled
WebP Support | enabled

**Live-System** (NOT WORKING):
Linux dd46736 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64
PHP Version 7.2.24-nmm1

Extensions:
DOM/XML | enabled
DOM/XML API Version | 20031129
libxml Version | 2.9.4
HTML Support | enabled
XPath Support | enabled
XPointer Support | enabled
Schema Support | enabled
RelaxNG Support | enabled

Multibyte Support | enabled
Multibyte string engine | libmbfl
HTTP input encoding translation | disabled
libmbfl version | 1.3.2
oniguruma version | 6.7.0

GD Support | enabled
GD Version | bundled (2.1.0 compatible)
FreeType Support | enabled
FreeType Linkage | with freetype
FreeType Version | 2.8.1
GIF Read Support | enabled
GIF Create Support | enabled
JPEG Support | enabled
libJPEG Version | 8
PNG Support | enabled
libPNG Version | 1.6.34
WBMP Support | enabled
XPM Support | enabled
libXpm Version | 30411
XBM Support | enabled
WebP Support | enabled

If you need more information i could provide PHP Configuration of both Systems and sample PDF-Files by PN or E-Mail.

**Comment by bkuhl** [comment]
You'll need to provide a specific error message for anyone to be able to help with this.

**Comment by TSInf** [comment]
Hallo many thanks for your reply. The funny thing was there was no error message anywhere. The Document was created and it was broken. Thats all.

But i have fixed it in the last week. I have downloaded the latest relase again. There was no difference between the old and the new folder. But in another file i tried to load a font and i think that was going wrong. when i had removed this file all was working. 

Why it worked on the Testsystem and not in live, i can`t say. But it works now how i want (without the font, i don`t need it) and i am glad.

Many thanks for the reply. You can close the issue in my opinion.
