### ISSUE TITLE
dompdf uses wrong fonts on elements

### ISSUE THREAD

**Issue by fmgrafikdesign** [dompdf/dompdf#2028]
Hi, I have the strangest issue. When I put an element before another, the subsequent element also changes its font to the one of the first element, ignoring all css. The fonts are loaded in my css from google fonts. Note that in both events, the wrong font is used on the span elements (not Lato as expected). If you have an idea what went wrong here, it'd be much appreciated!

Attached is a small screencap showcasing the issue. Also attaching the project as is.

PHP version 7.2.25, dompdf installed via composer as instructed on github.

Best Regards & thank you for your hard work!

Video: https://drive.google.com/open?id=1h18cNVCm3KQdq4dCejnd7m0g9lPBdfF1

[dom_pdf.zip](https://github.com/dompdf/dompdf/files/3941232/dom_pdf.zip)

**Comment by bsweeney** [comment]
Qiuck note: Dompdf doesn't officially support the WOFF font format. You should use the truetype version.

I tried out your sample and didn't run across the issue. Maybe something weird with how the document is being parsed. Are you using the HTML5 parser? Maybe try wrapping the spans in a block element (DIV or P).

Which version of Dompdf are you using? Try the recently released 0.8.4 to see if it does better.

**Comment by pmochine** [comment]
I've a similar problem now. Although I'm using locally available fonts. 

`    * { 
        box-sizing: border-box;
        font-family: sans-serif !important;
    }`

It worked always fine since today I updated my composer and now the fonts have serfis!
Look here on this image, you see the difference. And I still cannot find out why sometimes it shows sans-serif and sometimes not (super random)

<img width="916" alt="Bildschirmfoto 2020-02-06 um 15 54 49" src="https://user-images.githubusercontent.com/25006691/73948272-0bc8ff80-48f9-11ea-8b45-fde805dfe0f8.png">

**Comment by pmochine** [comment]
Wow super strange. I found the issue. If I add a global `font-weight: 400;` everything works fine again. How weird.

**Comment by bsweeney** [comment]
@pmochine up until Dompdf 0.8.4 Dompdf did not really support numeric font weights. With the 0.8.4 release numeric weights are supported, but we still need to fill out the logic around how it works if the weight you specify is not supported by any of the fonts available. For Dompdf 0.8.3 or earlier stick to normal and bold. With Dompdf 0.8.4 you can specify normal/400 and bold/700, or a numeric weight for a font registered with Domopdf using a numeric weight.
