### ISSUE TITLE
PHP warning because of "Use of undefined constant DOMPDF_DIR"

### ISSUE THREAD

**Issue by chekka** [dompdf/dompdf#2031]
Getting following warning while using DOMPDF for Drupal print module:

> Warning: Use of undefined constant DOMPDF_DIR - assumed 'DOMPDF_DIR' (this will throw an Error in a future version of PHP) in require_once() (line 22 of ... /dompdf/include/autoload.inc.php).

**Comment by bsweeney** [comment]
Looks like you're using a pretty old version of Dompdf (newer versions don't have an "include" directory). I recommend you upgrade.
