### ISSUE TITLE
Dompdf install problem at vps centos 7

### ISSUE THREAD

**Issue by IlhamriSKY** [dompdf/dompdf#2033]
I have tried installing dompdf on laragon windows, it is already running normally.

this is my localhost specification

- Laragon php 7.2.19
- normal phpmodule by laragon
- install dompdf 0.8.3 using composer

Then I moved all my projects to vps, and dompdf could not be run when I open it it says 404

this is my VPS specification

- Centos7
- Apache
- php 7.2.25

I tried installing the dom and mbstring modules, but it still doesn't work

is this wrong about the settings in my codeigniter (but I run locally its fine) or php on my vps that has problems

Please help

**Comment by bsweeney** [comment]
Not sure I have much to offer in the way of support. This doesn't seem like a problem specific to Dompdf, but probably with the particular system configuration since you're getting a 404. You mention codeigniter so maybe the necessary route mapping isn't in place.
