### ISSUE TITLE
replace continue into continue 2

### ISSUE THREAD

**Issue by kriit24** [dompdf/dompdf#2037]
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /Dompdf6/src/Dompdf.php on line 610

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /Dompdf6/src/Dompdf.php on line 631

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /Dompdf6/lib/Cpdf.php on line 467

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /Dompdf6/lib/Cpdf.php on line 474

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /Dompdf6/lib/Cpdf.php on line 481

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /Dompdf6/lib/Cpdf.php on line 488

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /Dompdf6/src/Css/Stylesheet.php on line 1360

**Comment by kriit24** [comment]
after replaceing continue to continue 2
Warning: "continue 2" targeting switch is equivalent to "break". Did you mean to use "continue 3"? in /Dompdf6/src/Css/Stylesheet.php on line 1360

**Comment by tbradsha** [comment]
Looks like this is a PHP warning as of PHP 7.3:

>continue within a switch that is attempting to act like a break statement for the switch will trigger an E_WARNING.

https://www.php.net/manual/en/control-structures.continue.php

**Comment by bsweeney** [comment]
This should have been addressed already. See #1822.
