### ISSUE TITLE
0.8.4 milestone - Releasing early and often

### ISSUE THREAD

**Issue by bkuhl** [dompdf/dompdf#2041]
I'm concerned about updates here hindering my ability to upgrade to PHP 7.4 quickly.  The past 2 releases for this package were almost a year apart.  Currently the [milestone for 0.8.4](https://github.com/dompdf/dompdf/milestone/11) contains 45 more open issues.  There's a few issues here related to PHP 7.4 compatibility that releasing sooner rather than later, would add a decent amount of value to the community, allowing folks to proceed with upgrading to PHP 7.4 who don't need to take advantage of the other bug fixes.  Is the team open to shipping a smaller release, containing smaller improvements/fixes?

**Comment by bsweeney** [comment]
You're absolutely right. I keep telling myself I'm going to move more in this direction and yet, somehow, I've never quite gotten to the point where I feel I'm ready. Perhaps it's time I stop thinking big and focus more on incrementalism.

As for the 0.8.4 milestone, I'm actually planning to move any non-addressed issues to the dompdf-next milestone (the "working set" of potential issues for the next release). My goal was to finish reviewing the pull requests and once I've finished going through those release 0.8.4.

And maybe this is how I get to the "early and often" release scheme. Move everything that isn't ready to dompdf-next, go ahead and release 0.8.4, only add things that are ready to go for each future milestone, and release on a schedule (every other month or something like that).

**Comment by bsweeney** [comment]
OK, I went through and moved almost everything to dompdf-next. Maybe we can get 0.8.4 out the door.

**Comment by bkuhl** [comment]
I can't thank you enough for re-evaluating the release cycle for 7.4 compatibility.  That plan sounds good!  

This is a _heavily_ used project because it solves a huge need and quite frankly makes PDF generation _very_ easy.  I just threw a small donation your way, anyone else can [do the same here](https://github.com/dompdf/dompdf#limitations-known-issues) as well.  Thanks for all the effort you and the team have put in on this project and being open to feedback on the release schedule!

**Comment by gbrunacci** [comment]
+1 to this, I heavily depend on this.

**Comment by LasseRafn** [comment]
Any progress on this? and/or any way I can help out? Really want to get 7.4 support out the door

**Comment by bsweeney** [comment]
Just about done. There's one more compatibility issue that was just identified around using the PDFLib adapter with PHP 7.4. I want to render various documents myself in 7.4 to see if I can identify anything else. Then I think we'll be ready.

**Comment by bsweeney** [comment]
OK, I think the code is pretty much ready. Should have it up this week.

**Comment by bsweeney** [comment]
and done

**Comment by bkuhl** [comment]
Woohoo!  Thank you!
