### ISSUE TITLE
Custom font face

### ISSUE THREAD

**Issue by ipol2n** [dompdf/dompdf#2043]
Problem: It failed to load custom font from external

Solution: Add write permission to vendor/dompdf/dompdf/lib/fonts directory

Hope this help.

**Comment by bsweeney** [comment]
This is in the vendor directory, so part of a composer install? This works, but it might be preferable to specify a different working directory for the fonts. For example:

```
$dompdf->set_option("fontDir", "/some/other/directory")
$dompdf->set_option("fontCache", "/some/other/directory")
```
