### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dmitryuk** [dompdf/dompdf#2044]
Is it possible to rollout a new release? php 7.4 support fixed only in dev-master, but it is not possible to use in my case (forbidden composer requirement dev-master).

**Comment by mbardelmeijer** [comment]
Just wanted to open an issue for this as well, a new release would be greatly appreciated due to PHP 7.4 compatibility.

**Comment by bsweeney** [comment]
Working on it. Please see #2041.
