### ISSUE TITLE
Add support for duplex viewer preference

### ISSUE THREAD

**Issue by trevorclarke** [dompdf/dompdf#2046]
Is it possible to preset a pdf document to use duplex (both sides of a sheet of paper) printing when creating a PDF with dompdf?

I've seen that in Word docs this presetting parameter is possible, but not sure if it is possible with pdf's....

Tried to ask via stackoverflow but the question was closed as not being a software question.
![pdf print duplex](https://user-images.githubusercontent.com/1445761/72423713-a449e500-377c-11ea-8ba3-d4761f35f5b0.png)

**Comment by bsweeney** [comment]
So, looking at the PDF 1.3 spec (the one officially supported by Dompdf) there is no option for setting this viewer preference. There is an option in the PDF 1.7 spec, but we're probably a long way off from supporting a new PDF spec (just in terms of reviewing current output against the spec for any required changes).

Interestingly CPDF does appears to include some support for the duplex preference, but it does not currently encompass the options from the 1.7 spec.

Here's what the spec says:
> Duplex (name) (Optional; PDF 1.7): The paper handling option to use when printing the file from the print dialog. The following values are valid
> - Simplex: Print single-sided
> - DuplexFlipShortEdge: Duplex and flip on the short edge of the sheet
> - DuplexFlipLongEdge: Duplex and flip on the long edge of the sheet

If you're up to hacking this together yourself and seeing if it works without making other changes (i.e. to the spec version) you would just need to add the additional values to the existing logic handling this preference ([ref L489](https://github.com/dompdf/dompdf/blob/e252335236cb6d79663c08ca8e1c29d7c99399ce/lib/Cpdf.php#L489)). I'm not sure what the reader would do with a 1.3-spec PDF that includes this preference.

Then to use you can either call the method directly or add a meta tag defining the preference.

**Comment by bsweeney** [comment]
ref https://stackoverflow.com/q/59714283/264628

**Comment by simonberger** [comment]
@trevorclarke If you are able to test this new branch https://github.com/simonberger/dompdf/tree/48dc5fbd491b86b493a76a040afee3ae730854e4 with the latest commit and it works for you, a potential release could be expedited.
We still need to investigate this version raise though.

You can change the settings currently just directly in CPdf after the render step like this:

```
$dompdf = new \Dompdf\Dompdf();
$dompdf->loadHtml(file_get_contents("doc.html"));
$dompdf->render();
$cpdf = $dompdf->get_canvas()->get_cpdf()->setPreferences('Duplex', 'DuplexFlipLongEdge');
$dompdf->output()
```

Another Duplex setting is `DuplexFlipShortEdge`

**Comment by bsweeney** [comment]
@simonberger did you ever merge this into the develop branch?

**Comment by bsweeney** [comment]
Ah, I see it.
