### ISSUE TITLE
How to retrieve result of search to create data in pdf table

### ISSUE THREAD

**Issue by Adhik13th** [dompdf/dompdf#2055]
i Have Search Function, this result of a search is table data and will be export by PDF. but this data on the search did not retrieve on the pdf page ( null ). I don't know what happens, I try to set load pdf in the search function, its show normally but I don't need this because this search function is not working again . you can see at this controller 

    public function search_range(Request $request)
	{
        
        $ipsrs_id = Auth::user()->roles->ipsrs_id;
        $from = $request->from;
        $to = $request->to;
        $status = $request->status;

        if($status == 'Belum Selesai'){
            $new_status =['Tindakan Lanjutan' , 'Belum Dikerjakan' ,'Sedang Dikerjakan'];
        }
        
        elseif($status == 'Semua Laporan'){
            $new_status = ['Tindakan Lanjutan' , 'Belum Dikerjakan', 'Sedang Dikerjakan' , 'Selesai'];
        }
        else{
            $new_status = 'Selesai';
        }

        $stats = collect($new_status);

        $journal = Aduan::where('ipsrs_id',$ipsrs_id)->whereIn('status',$stats)
        ->whereBetween('created_at', [$request->get('from'), $request->get('to')])->get();

       

        
        $request->session()->put('journal', $journal);
        $request->session()->save();
        
           // dd($journal);
        //$pdf = PDF::loadView('sarpras.file_pdf',['journal' => $journal]);
        // return $pdf->stream('result.pdf'); // if i unmark this line , this pdf is show here and this 
       // data is true

       return view('sarpras.journal_sarpras',['journal' => $journal ]);

        
        
    }

pdf function

    public function getPDF(){
         $journal = Session::get('journal');
        // dd($journal);
          $pdf = PDF::loadView('sarpras.file_pdf',['journal' => $journal]);
          return $pdf->stream('file.pdf');
    }

but after i clicked button export pdf , this pdf not showing data and if i dd its showing null . whats wrong this ?

i dd this session but this session is null . how to retrieve variable function to another function in 1 controller laravel ???

**Comment by bsweeney** [comment]
Your questions are beyond the scope of this project. You should try your query on StackOverlow or similar forum where you can find more generalized help.
