### ISSUE TITLE
Trying to access array offset on value of type int, Cpdf.php, line: 4052

### ISSUE THREAD

**Issue by xpetter** [dompdf/dompdf#2057]
I get this error with PHP 7.4

Trying to access array offset on value of type int, dompdf/lib/Cpdf.php, line: 4052

**Comment by apervikov** [comment]
Same, it's related to: #https://github.com/PhenX/php-font-lib/issues/75

**Comment by bsweeney** [comment]
@xpetter would need some more info to narrow down the issue. Which version of Dompdf are you using? Do you have a sample of the HTML + CSS that causes this issue?

Could be related to php-font-lib or could be a similar issue in Dompdf. I haven't run across it in reference to that line in my testing.

**Comment by xpetter** [comment]
Dompdf 0.8.4

I have done some tests and get the error even on pdf without content. But after some more tests the error disappears when I remove: $dompdf->add_info('Subject', 'Test');

**Comment by bsweeney** [comment]
I'm still not seeing the error. Can you post a full example?

**Comment by xpetter** [comment]
I know why now.
$dompdf->add_info('Subject', 'Test'); This row does not trigger the error
$dompdf->add_info('Subject', 123); But this one does.

If we send an int value, the error occurs.

**Comment by bsweeney** [comment]
OK, yeah that does it. I guess it would be worthwhile for us to either require a specific content type or cast to the appropriate type.
