### ISSUE TITLE
Release notes minimum version inaccurate

### ISSUE THREAD

**Issue by bkuhl** [dompdf/dompdf#2058]
@bsweeney The https://github.com/dompdf/dompdf/releases/tag/v0.8.4 release notes say 0.8.4 is compatible with PHP 7.0+ but [`composer.json` requires PHP 7.1+](https://github.com/dompdf/dompdf/blob/8f49b3b01693f51037dd50da81090beba1b5c005/composer.json#L30)

**Comment by bsweeney** [comment]
Thanks for the heads-up. Fixed.
