### ISSUE TITLE
Ayuda porfavor

### ISSUE THREAD

**Issue by payalacun** [dompdf/dompdf#2059]
Estoy renderizando con DOMPDF, en mi computadora local se renderiza correctamente pero cuando subo al servidor los archivos el renderizado no es correcto, las cosas no salen donde deben de salir.

Mi computadora local: Windows 10, PHP 7.2, 
Servidor: CentOs, PHP 7.2

Alguna idea? que puedo revisar?

He tratado de subir capturas de pantalla pero sale un error al intentar subirlo.

Gracias!!!!

**Comment by bsweeney** [comment]
Lo siento, mi espanol es muy malo, entonces ... Google Translate:

Por favor, intente eliminar el archivo dompdf_font_family_cache.php ubicado en su directorio de fuentes.

**Comment by payalacun** [comment]
Funciono perfecto! muchas gracias @bsweeney
