### ISSUE TITLE
RGB color does not support dompdf for page numbers and text in footer part

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#206]
_Original author: rubbyra...@gmail.com (November 15, 2010 07:02:10)_

<b>What would you like dompdf to do:</b>

RGB color does not support dompdf for page numbers and text in footer part.

Thanks 
Brijmohan karadia

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=200_

**Comment by garhbod** [comment]
To extend on @PhenX answer you can simply inline the equation
```
array(152 / 255, 100 / 255, 0 / 255)
```
