### ISSUE TITLE
Question: How to generate a pdf that contains two copies of the same invoice ? 

### ISSUE THREAD

**Issue by moroccan-webdev** [dompdf/dompdf#2061]
I am working on web application in which I wanted to print the final paper that has two copies of the invoice on one single paper or one pdf . Thanks in advance

**Comment by bsweeney** [comment]
Not easily with dompdf. I mean, it's possible but that's not really what Dompdf is designed for. You'd either have to create an HTML page in that form and Dompdf could just render it like normal or you could try using the canvas methods to capture the content and resize it. Not sure if that's even possible I haven't tried.

Easier would be to use a complimentary tool like FPDF/FPDI.

**Comment by moroccan-webdev** [comment]
@bsweeney Thank you so much for you quick response and the Extra provided details.
