### ISSUE TITLE
Problem with phenx/php-font-lib

### ISSUE THREAD

**Issue by carlospauluk** [dompdf/dompdf#2063]
There's a problem with phenx/php-font-lib (https://github.com/PhenX/php-font-lib/pull/76), with an already build solution, but unfortunatelly it seems that no one's taking care of that project anymore. We could fork it and update the dependency here at dompdf?

Thanks

**Comment by andrefedalto** [comment]
I'm using dompdf through laravel and having the same issue. One workaround I could find is:
1. Apply the fix by @LinkingYou locally on `vendor\phenx\php-font-lib\src\FontLib\AdobeFontMetrics.php:142`;
1. Set your font folder for dompdf to a folder in your repository;
1. Run your script to build the pdf locally, this will make dompdf generate all font temp files (ttf, ufm, php) in your font folder;
1. Commit these files to your repository;
1. Revert the local changes in AdobeFontMetrics.php;
1. 🎉 dompdf will now use the parsed fonts instead of parsing them again. Remember you have to repeat all the steps here for each new font you use

**Comment by bsweeney** [comment]
That library is the sole work of @PhenX. Before I go to the extreme step of forking the project I'll talk to him about getting contributor access so I can start working through the issue backlog.

**Comment by PhenX** [comment]
@bsweeney hey ! Of course I'll give you access to the project. I'm really sorry for my absence for so long. In fact I thought I already gave someone access to this project, but it was in fact on https://github.com/PhenX/php-svg-lib

**Comment by PhenX** [comment]
Also, someone asked me if it was a good idead to transfer ownership of https://github.com/PhenX/php-svg-lib to the dompdf organisation, I was a little bit reluctant about it, but now, I think this can be a good idea, as dompdf was the main reason I wrote both of theses libs.

**Comment by bsweeney** [comment]
I leave the transfer question up to you. I'm happy to work on it under the auspices of your account. In the meantime, thanks for adding me to both projects. I'll start working through the PRs and other issues alongside Dompdf.

**Comment by marijnbent** [comment]
@PhenX Can you please accept this pull request? https://github.com/PhenX/php-font-lib/pull/76

**Comment by bsweeney** [comment]
That PR has been merged and I'm am in the process of looking at other PHP compatibility issues. I'm planning to try and get a new version of PhenX's libraries out shortly after the 0.8.5 release (since 0.8.4 introduced some bugs it's coming sooner than I was planning).

**Comment by Tamrael** [comment]
@bsweeney 0.8.5 is out 10 days now. any word on when php-font-lib will get the fix released? would really love to upgrade to php 7.4

**Comment by bsweeney** [comment]
No progress yet, but I should be able to get back to it soon.

**Comment by binzram** [comment]
@bsweeney Any news? :point_up:

**Comment by jonathanpmartins** [comment]
Take a look at this: https://github.com/PhenX/php-font-lib/pull/76#issuecomment-594494040

**Comment by bsweeney** [comment]
The world has conspired to make me even less productive than I was. I'm trying to finalize the next release of Dompdf because of some newly-introduced issues. After that I'll move back over to working out the next update for php-font-lib.

**Comment by ngunyimacharia** [comment]
Really hope this is permanently closed soon.

**Comment by PhenX** [comment]
Hello, as far as I know, as php-font-lib 0.5.2 (with this fix) was released on packagist, and dompdf requires php-font-lib "^0.5.1", which patches also 0.5.2 (see https://getcomposer.org/doc/articles/versions.md#caret-version-range-), you should check your composer.lock file to see if it sticks to 0.5.1.
