### ISSUE TITLE
Speed on Localhost slow but on Server not

### ISSUE THREAD

**Issue by Gamestarplayer41** [dompdf/dompdf#2065]
Hi,
I have issues with the performance on localhost. On localhost my html file takes about 4-8s but on a Linux server it only takes less than a second.
Server PHP v: 7.1.31
Local PHP v: 7.3.4

**Comment by bsweeney** [comment]
Seems unlikely PHP 7.3 would be the issue (though one never knows). Probably has more to do with system resources. What are the hardware specs for each system? OS? Anything else that might help.

**Comment by simonberger** [comment]
Closed after a month of no answer.
@Gamestarplayer41 If you have some more details why it could be caused by dompdf please don't hesitate to still add.
