### ISSUE TITLE
Deprecation errors cause an exception

### ISSUE THREAD

**Issue by IonBazan** [dompdf/dompdf#2067]
Any deprecation message will cause an exception to be thrown in `record_warnings` method: https://github.com/dompdf/dompdf/blob/adcd9738253afff908eadce9cff0d790f7ae2072/src/Helpers.php#L506-L508

I see a few solutions to that:

- Add `E_DEPRECATED`, `E_USER_DEPRECATED` and `E_STRICT` to excluded error levels (trivial)
- Use `try {...} catch (\Throwable $e)` as we are already dropped PHP 5 (that would probably break streaming support in some cases)
- Don't register any error handler at all because it should be an application responsibility - not the library one (BC break) and maybe use `@` when it's ok to suppress the errors.

**Comment by bsweeney** [comment]
Any particular issue that brought this up that hasn't been addressed? Generally I think we should look at implementing PSR-3 (see #960). But in the meantime a solution for this particular issue would be good.

**Comment by IonBazan** [comment]
We use DomPDF with Laravel Horizon worker, which registers its own error handler. When DomPDF register his own handler, it is supposed to pop it from error handlers stack using `restore_error_handler` but sometimes it doesn't happen (still don't have a clue why) and the application ends up with invalid handler stack, where the DomPDF's one is on top while using domain code so that all `E_USER_DEPRECATED` "errors" get caught by `record_warnings` method instead of Laravel's handler.

Maybe it has something to do with catching PHP7.x `\Error`s? I will investigate and keep you updated.

**Comment by IonBazan** [comment]
Look like the problem is that the error handler does not catch `TypeError`s that may occur when DomPDF is operating.
Minimal example:
```php
<?php

function test1(stdClass $a)
{
    echo 'call me...';
}

function generatePdf()
{
    set_error_handler(function (int $code, string $message) {
        echo "Handled by DomPDF: $message\n";
    });

    // Throw a generic error
    trigger_error('to be handled by DomPDF', E_USER_ERROR);
    test1('definitely not a stdClass'); // TypeError
    restore_error_handler(); // Restore default error handler
}

// A try-catch block used in the app
try {
    generatePdf();
} catch (\Throwable $e) {
    echo $e->getMessage() . "\n";
}

trigger_error('to be handled by app', E_USER_ERROR); // An error happening in the app should be handled by app error handler
```

Output:
```
Handled by DomPDF: to be handled by DomPDF
Argument 1 passed to test1() must be an instance of stdClass, string given, called in /Users/ion/work/bmg/v3/a.php on line 16
Handled by DomPDF: to be handled by app
```

As you can see, DomPDF does not reset the error handler when an error occurs. Solution is to wrap the code in `try ... finally` block to remain bubbling the exception but reset the handler before, like it's done in Doctrine DBAL: https://github.com/doctrine/dbal/blob/97e0c2bb7386288ef6954aeb10f990b9231cb517/lib/Doctrine/DBAL/Types/ArrayType.php#L49-L57

**Comment by bsweeney** [comment]
Nice work.

FYI I'm planing to swap out the bundled HTML5 parser with something a bit more modern (currently looking at [Masterminds/HTML5-PHP](https://github.com/Masterminds/html5-php). Maybe for the next release.
