### ISSUE TITLE
0.8.4 breaks table cell width calculation

### ISSUE THREAD

**Issue by schniper** [dompdf/dompdf#2068]
I will try to create an example, but this is a heads up. I was using a layout with a table using rowspan and colspan and cell widths are no longer respected, either using rem or %.
Also, on a simpler table layout, widths seem to exhibit issues.

**Comment by bsweeney** [comment]
I'll be waiting.

**Comment by apiaget** [comment]
Hello,

I think I may have the same bug. Here is an example :

https://gist.github.com/apiaget/5f699dce9f076a7c2615f70bc50c1c21

The html doesn't apprear to be missing ending tags or other bug that I am aware of.


Here is the result with dompdf 0.8.3 (correct) :
![dompdf-0 8 3](https://user-images.githubusercontent.com/634083/73594611-24f43980-4510-11ea-9d4d-f5da6c978135.JPG)


And here is the same code with dompdf 0.8.4 (the layout is now broken) :
![dompdf-0 8 4](https://user-images.githubusercontent.com/634083/73594604-14dc5a00-4510-11ea-8705-4750a0a79190.JPG)

The configuration I am running (If other info are needed to track down the bug, I will gladly add them) :
PHP 7.4.1 (WAMP)
dompdf:0.8.3 and 0-8-4 (installed with composer)
imagick module version : 3.4.4
Imagick compiled with ImageMagick version : ImageMagick 7.0.7-11 Q16 x64 2017-11-23 http://www.imagemagick.org
Imagick using ImageMagick library version : ImageMagick 7.0.9-8 Q16 x64 2019-12-07 http://www.imagemagick.org


I hope that the example corresponds to the bug mentioned by schniper.

Thank you,

-apiaget

**Comment by bsweeney** [comment]
Thanks, @apiaget, that does help confirm the issue. There appears to be at least two issues with the rendering that we'll need to look at.

- table cell width calculation
- font-size inheritance of the H1 in the header

**Comment by dfinfo** [comment]
Hello,
same here, large tables messed up since 0.8.4, revert to 0.8.3.

WITH 0.8.3
![Capture du 2020-02-04 15-30-30](https://user-images.githubusercontent.com/16663775/73753904-bc9d9600-4763-11ea-96f5-2c50df363c3f.png)

WITH 0.8.4
![Capture du 2020-02-04 15-30-44](https://user-images.githubusercontent.com/16663775/73753917-c626fe00-4763-11ea-9778-9115a4c78ab3.png)

Thank you

**Comment by bsweeney** [comment]
Created a new issue to address the problem with the font, see #2079.

**Comment by bsweeney** [comment]
the issue with tables seems to be caused by commit 08c765e022dbf8f576e380b8d6632144bccddd9e

**Comment by bsweeney** [comment]
And I can confirm that removing excess white space from around the content of the cell appears to produce a more accurate rendering. So something about the attempt to exclude non-breaking spaces from word boundaries is causing the issue.

**Comment by bsweeney** [comment]
welp, that was a dumb error

**Comment by skollro** [comment]
I'm happy this has been resolved so quickly. Is there any ETA when 0.8.5 will be tagged? Asking because this table thing is such a common use case and this bug prevents from upgrading to PHP 7.4.

**Comment by bsweeney** [comment]
Unless another bug introduced with 0.8.4 arises I’ll probably go ahead and release this week.
