### ISSUE TITLE
Footer after main tag not renderd right

### ISSUE THREAD

**Issue by Gamestarplayer41** [dompdf/dompdf#2077]
The `<footer>` with position fixed is only rendered on all pages correctly, if the tag is before the main tag. If it is after it renders weirdly.

**Comment by bsweeney** [comment]
Which version of Dompdf are you using? Do you have sample HTML + CSS to demonstrate the issue as well as the resulting PDF or screen shots?

**Comment by Gamestarplayer41** [comment]
sure @bsweeney. Im using dompdf 0.8.4 (via Composer). 
As you can see in the screenshoot, the footer is only on the last page even if its position fixed.
If I put `<footer>` now before the `<main>` the footer will show up on every page. On production I encountered some other weird rendering with footer as last element, but i cant recreate it and cant show it, so this is the only real problem.
http://eclecticgeek.com/dompdf/debug.php?identifier=8bfb9f749d2331a61610ede23a1790f1
```<html>
<body>
  <style>
    @page{
      margin: 1cm;
    }
  </style>
  <header style="position: fixed;top:-1cm">
    Header
  </header>
  <main>
    MAIN
    <div style="page-break-before:always"></div>
  </main>
  <footer style="position: fixed; bottom: 0cm;">
    FOOTER
  </footer>
</body>
</html>
```


![image](https://user-images.githubusercontent.com/51420498/74091360-db2ec480-4ab6-11ea-996b-82ff5726ff95.png)

**Comment by bsweeney** [comment]
Ah, yes. This is a known quirk with how Dompdf renders documents. Please follow #491 for updates.
