### ISSUE TITLE
Fonts and conditional sections.

### ISSUE THREAD

**Issue by misterHippo** [dompdf/dompdf#2083]
Firstly, I realise this is the wrong channel for help, but I tried to post on the Google Groups, and it appeared to work, but I cannot see it anywhere. So I don't know if it worked. :(

Apart from failing to internet, my issues are two fold: 
**1)** I can't get the font to import; and **2)** for the life of me I cannot get page numbers. (Through any sort of script or post render application.) ... and bonus **3)** I also am hoping to have a conditional section in the HTML either hidden or added.

The VERSION file contains `<75f13c70>` (installed a few days ago).

**Firstly**, the font - I've referred to the locally stored TTF file via CSS in:

- absolute reference: /font/fontname.ttf
- relative reference: ../font/fontname.ttf
- absolute https reference: https://www.domain.com/font/fontname.ttf

From what I the font doesn't take effect, and reading the PDF properties, it's not in there either.

**Secondly**, the pagination - I may be making it harder than required, but the HTML is in a PHP variable. I'm adding in the `<script type='text/php'>` code just before I send it to DOMPDF. I've found through trial and error that the `$variables` have to have their `$` escaped or the "primary PHP" (the actual page it's sitting on) crashes complaining about undefined variables. (in case that helps someone else.)

Oh; ok, I moved something I had accidentally put in the header. That seems to be working now.

For others sake: 
```
<script type='text/php'>
if ( isset(\$pdf) ) {
  \$size = 10;
  \$color = array(0,0,0);
  \$foot = \$pdf->open_object();
  \$w = \$pdf->get_width();
  \$h = \$pdf->get_height();
  \$y = \$h - \$text_height - 24;
  \$pdf->close_object();
  \$pdf->add_object(\$foot, 'all');
  \$text = '{PAGE_NUM}';  
  // Centered text
  \$pdf->page_text(\$w / 2 - \$width / 2, \$y-25, \$text, \$font, \$size, \$color);
}
</script>";
```
Subsequent Question: why would the above code fall over with the color set to array(66,66,66) ?
Subsequent Answer: numbers are between 0 and 1. So 0.5 is 50% grey.

Anyway **Lastly**, I'm writing an invoice, and I essentially want to have the big fat header of awesome (BFHOA) on the first page, and the small header that you barely notice (SHTUBN) on subsequent pages.

I have thought of a few ways to do it, some in CSS some not. hiding it using `:first-child` didn't seem to work, trying to add it in conditionally using `page_text()` / `page_script()` doesn't seem to work either, as that would require knowing the page number at the HTML render time, which I'm now assuming it cannot do (given the above code.)

Do you have any suggestions on how to overcome the font / header issues?

**Comment by bsweeney** [comment]
Sorry about the forum. It was moderated for new users. I check for messages waiting for moderation at most once a day. But I think I'll switch to unmoderated for now unless we start seeing excessive spam.

**Comment by bsweeney** [comment]
Before I get to far ahead of myself, how did you install Dompdf? I see you have a hash version, so I'm thinking Composer but I just want to confirm. If you install directly via git you have to manually add php-font-lib.

So on to your questions:

First, of the font paths used I would stick with the third option. The other two are dependent on how you load your HTML into Dompdf and seems to trip up the most people. Using that third option requires two settings:
1. [isRemoteEnabled](https://github.com/dompdf/dompdf/blob/v0.8.4/src/Options.php#L162) set to true, e.g. `$dompdf->set_option('isRemoteEnabled', true);`
2. either [allow_url_fopen enabled](https://github.com/dompdf/dompdf/wiki/Requirements#optional-configuration) or curl installed

Second, to use script embedded in a document you have to set [isPhpEnabled](https://github.com/dompdf/dompdf/blob/v0.8.4/src/Options.php#L141) to true, e.g. `$dompdf->set_option('isPhpEnabled', true);`

But really I would just use CSS if you don't need the total number of pages (we don't yet support page count via CSS):

```
<style>
.pagenum::before { content: counter(page); }
</style>
<div class="pagenum"></div>
```

Third, conditional headers are more complicated, but still potentially possible using a combination of HTML and script. But I'd try something simpler to start. Objects are layered based on the order in which they are encountered, You could try something as simple as covering the SHTUBN with the BFHOA.

A very rudimentary example:

```
<style>
  .pagenum::before { content: counter(page); }
</style>

<div style="position: fixed; z-index: -1000; height: 1em; top: -1.5em; width: 100%; background-color: green;"></div>
<div style="position: absolute; z-index: -1000; height: 5em; top: -1.5em; width: 100%; background-color: orange;"></div>

<div style="padding-top: 4em;">
  <p>page <span class="pagenum"></span></p>
  <p style="page-break-before: always;">page <span class="pagenum"></span></p>
</div>
```

**Comment by misterHippo** [comment]
Hey, thanks for the reply.

About to go to bed, but I have _cURL support_ enabled and _allow_url_fopen_ on - shown in `phpinfo()`.

I have all the HTML/CSS in a variable, then I echo it to page just after `ob_start();` and immediately put it in a variable `$rhtml = ob_get_clean();`. (Why? I was trying to work out how to get a css file connected, and couldn't so I `$css=file_get_contents("../css/crm.css");` - perhaps this is connected to the remote file not working?

```
use Dompdf\Dompdf;
$dompdf = new Dompdf();
$dompdf->set_option('isHtml5ParserEnabled', true);
$dompdf->set_option('isPhpEnabled', true);
$dompdf->set_option('isRemoteEnabled', true); // this is new 
$dompdf->loadHtml($rhtml);
```

Adding `isRemoteEnabled` appears to have changed nothing.

I read somewhere that someone else base64()'d the font, and stuck it in the CSS. I haven't tried that yet.

I haven't readdressed the `if( $page != 1 ){ addHeader(); }` idea yet. Something for tomorrow.

**Comment by bsweeney** [comment]
I guess at this point it would help to see a sample of what you're feeding to Dompdf (from the `$rhtml` variable). I don't really see anything out of the ordinary otherwise.

**Comment by misterHippo** [comment]
_... time passes ..._ 
Morning!

Right. So, I've deducted that the counter(page) _doesn't_ work when not in conjunction with ::before. I removed the ::before during previous construction to simplify things. #thatWorkedWell

So your idea for the repeated SHTUBN is that it gets covered by something (i.e.: the BFHOA) on page 1, and not on subsequent pages. I shall try this.

_... more time passes ..._ 

You can see from the next image that there is a certain layering issue with the header idea.
![image](https://user-images.githubusercontent.com/605912/74296101-048d7000-4d97-11ea-922c-729c39a4b471.png)

Relevant CSS: 

```
.inv-header{position: fixed; left:2.1cm;right:2.1cm;top:1cm;text-align:left;width:626px;margin:auto;height:2em;}
.inv-footer{position: fixed; left:2.1cm;right:2.1cm;bottom:1cm;text-align:center;width:100%;height:2em;font-size:0.75em;}
#first-table,#second-table {position:relative;top:-40px;background:white;}
#second-table{margin-bottom:-40px;}
```
The `background:white` doesn't work, presumably due to the whole print. I absolutely positioned & stretched a 1px x 1px white image behind the business name, and that didn't help either. 

The negative top position and negative bottom margin worked well though :)

Example HTML
```
<!DOCTYPE html><html><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1'><style type='text/css'>
@font-face { font-family: 'NunitoLight'; src:url('https://srsbzns.com.au/fonts/Nunito-ExtraLight.ttf') format('truetype');}
*HTML5 Bootstrap Stuff*/
*,*:before,*:after{box-sizing:border-box;-moz-box-sizing:border-box;}
.clearfix{*zoom:1;}
/* !! Mass of CSS removed, including media queries, no print stuff though */
</style></head><body>
<div class="inv-header"><div class="grey nunito">SRS BZNS - TAX INVOICE</div></div>
<script type="text/php">
if ( isset($pdf) ) {
  $size = 10;
  $color = array(0.5,0.5,0.5);
  $foot = $pdf->open_object();
  $w = $pdf->get_width();
  $h = $pdf->get_height();
  $y = $h - $text_height - 24;
  $pdf->close_object();
  $pdf->add_object($foot, 'all');
  $text = '{PAGE_NUM}';  
  // Centered text
  $pdf->page_text($w / 2 - $width / 2, $y-25, $text, $font, $size, $color);
}
</script>
<div id="invoice_wrapper"><table id="first-table">
    <tbody><tr>
        <td id="logo" class="grey nunito"><span>SRS BZNS</span></td>
        <td class="text-right">PO Box 1<br>Yourtown NSW 2000<br>Australia<br>www.srsbzns.com.au<br>accounts@srsbzns.com.au<br>0000 000 000<br></td>
    </tr>
    <tr><td id="invoice-title" class="nunito grey">TAX INVOICE</td><td class="text-right">ABN: 00 000 000 000</td></tr>
    </tbody></table>
    <table id="second-table">
        <tbody><tr><td><strong>Billed To</strong></td><td class="text-center"><strong>Date of Issue</strong></td><td class="text-center"><strong>Invoice Number</strong></td><td class="text-right"><strong>Amount Due</strong></td></tr>
        <tr>
            <td class="td-top">Yomomma's Dance House<br>ABN: 00 000 000 000<br><br>PO Box 2<br>Yourtown NSW 2000<br>Australia</td>
            <td class="text-center td-top" style="padding-top:0.8em">24 Jan 2020</td>
            <td class="text-center td-top" style="padding-top:0.8em">0000000</td>
            <td id="amount" class="text-right orange nunito td-top">$000.00</td>
        </tr>
    </tbody></table><hr class="orangehr ohrtop">
<!-- !! nicely balanced HTML below -->
</body></html>
```

And no, btw. Srs Bzns isn't my domain / business. but the more I write it, I _REALLY_ want it to be.

**Comment by misterHippo** [comment]
G'day, 

So I've now played with the idea of `base64()` encoding the fonts, and include them in the CSS. Which is fine in the browser (along with the other ways of including them), but fails to work in the PDF.

I also bypassed the `$rhtml` variable, and used the pre `ob_start()` / `ob_get_clean()` variable of $html - with no change. (Was wondering if there was some rendering difference.)

Apart from the the concept of adding the fonts in manually to the PDF object, I believe I've tried all the expected ways of adding the fonts.

So this is still outstanding, and we don't know why. (As well as the query above about what is essentially a second page onward header.)

Looking forward to hearing from you again. Thanks for the assistance so far.

**Comment by bsweeney** [comment]
FYI base64-embedded fonts do not currently work (#967). For the `@font-face` declaration I'd go ahead and fill it out to ensure Dompdf is understanding it correctly:

```
@font-face {
  font-family: 'NunitoLight';
  font-weight: normal;
  font-style: normal;
  src: url('https://srsbzns.com.au/fonts/Nunito-ExtraLight.ttf') format('truetype');
}
```

You also might try removing the dompdf_font_family_cache.php file to see if that helps.

Read/write access is for sure important. Dompdf should have read/write access to the directories specified by tmpDir, fontDir, and fontCache.

As for how your headers are rendering and your sample HTML... I'd need to see a more complete example, including the CSS. There could be something particular to your CSS causing the issue.

**Comment by misterHippo** [comment]
G'day, 

I switched the font declaration to the above suggested with no success.

The only similar file I can see to the `dompdf_font_family_cache.php` is the `...../vendor/dompdf/dompdf/lib/fonts/dompdf_font_family_cache.dist.php` and as you might expect, removing that causes an almighty crash. I was unable to find dompdf_font_family_cache.php

I wasn't specifying fontCache or tmpDir, and I didn't realise that fontDir required write. What permissions should I be granting them? (I've started with chown'ing them to `apache:apache`, and chcon'ing to `httpd_sys_rw_content_t`.)

Interestingly, `tmpDir` and `fontDir` have no changed/additional contents. But the `fontCache` has three files. Helvetica.afm.php, Times-Bold.afm.php, & Times-Roman.afm.php. (Times isn't in the CSS at all, while Helvetica is being picked up at the end of this:
```
body{font-family:-apple-system,system-ui,BlinkMacSystemFont,Roboto,"Helvetica Neue","Segoe UI","Fira Sans",Ubuntu,Oxygen,"Oxygen Sans",Cantarell,"Droid Sans","Apple Color Emoji","Segoe UI Emoji","Segoe UI Emoji","Segoe UI Symbol","Lucida Grande",Helvetica,Arial,sans-serif;}
```
Which, incidentally, is being overridden by `body{font-family:'OpenSans',sans-serif;}` in the CSS later.

To be sure there wasn't some 'max iteration' for font family issue, I removed the first long body declaration, and no change was observed.

I put the CSS through the Jigsaw validator, and this was the outcome.

![image](https://user-images.githubusercontent.com/605912/74614934-40964b80-5170-11ea-8dbe-dbc80dc03a5d.png)

I've removed / sorted all those issues (in a new css file), and strip out as much non-relevant CSS as I could (including the massive `font-family` declaration above). But that didn't help either.

Re: BFHOA & SHTUBN - 
Is this even possible? If the default for printing is no background images / background colours - doesn't that mean that this will never work?

Oh wait, I have a `position:absolute`'d image...  Well, the relevant CSS is: 
[example_css.txt](https://github.com/dompdf/dompdf/files/4211263/example_css.txt)
and as you'll see from above, there's first-table and second-table that have basically been moved up a little to overlap the SHTUBN.

Thanks for all your assistance by the way. I really appreciate it :)

**Comment by bsweeney** [comment]
The system executing the PHP script does need read/write access to those directories. This could be why you're not seeing the font selected. With `@font-face` declarations Dompdf downloads the font and places it in the font directory.

Re: BFHOA & SHTUBN ... I didn't think about the possibility of disabling backgrounds, but that type of setting would be more of a browser issue. I don't believe you would normally run into that in a PDF since that's not how things are rendered. A PDF is basically just a collection of positioned objects, sometimes they have a relationship. But "background" isn't really one of them. In the case of a filled background the PDF is rendered as a filled rectangle followed by text (which renders on top of it per order precedence).

**Comment by misterHippo** [comment]
Re: paths - Well, as noted above, at least the font cache folder is being used. The temp dir doesn't have anything in it at the moment. The fonts path and the log file both have the same permissions. (log file works too.)

Question though - is it safe to put the folders in ...../vendor/dompdf/<folder>/? I thought that was a good idea at first, but now I'm wondering if composer will spit chips when it seems them there. (or just remove them.)

Re: BFHOA & SHTUBN - So, having an image stretched and z-indexed lower behind the brand would be fine?

**Comment by bsweeney** [comment]
Temp dir shouldn't retain files unless you tell Dompdf to do so (`$dompdf->set_option('debugKeepTemp', true);`).

The font cache should is typically the same directory as the font directory unless you change it. The *.afm.php and *.ufm.php files are cached data after parsing the AFM/UFM. So you should always see one when a font is used.

In the font directory you _should_ see a file named dompdf_font_family_cache.php. If this file isn't present then Dompdf isn't able to persist what it knows about the fonts it can use and will just keep using the bundled fonts.

I would place any read/write directories outside the vendor directory. As you noted, Composer is likely to grumble.

**Comment by misterHippo** [comment]
OK, so: 

1. Temp should be empty outside of processing
2. I've moved the fonts path to somewhere else - nobody wants grumbly composers.
3. I've made fontcache and fonts the same directory.
4. There is no dompdf_font_family_cache.php at all.
5. I'm only seeing Time and Helvetica fonts in the combined Fonts/FontCache path.

Why would it be that the dompdf_font_family_cache.php isn't being created?

**Comment by misterHippo** [comment]
Subsequent questions:

- How/Where is DIRECTORY_SEPARATOR set?
- After reading how they do it in Laravel, I've now set the $rootDir to the `[path]/vendor/dompdf/dompdf`. What should the owner/group be set to? (I've set it to apache:[other user group], and chcon'd it so that apache can save into it.)

**Comment by misterHippo** [comment]
Hi,
 
Thought I'd try the load_font.php file from utils and see how that goes. Apart from generating this error for every font file:
```PHP Warning:  strftime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/crm/vendor/phenx/php-font-lib/src/FontLib/BinaryStream.php on line 285```
It appears to have created the fonts in the dompdf/lib/fonts path (the `.ttf` and the `.utm`). As well as the elusive `dompdf_font_family_cache.php`

Of course, I then tried to run the PDF generation, and still wound up with the wrong fonts. :(

**Comment by misterHippo** [comment]
Wait up! I got the fonts working :) Yay!

When I tested it above, I had the current CSS* referring to NuntioLight and OpenSans, which didn't match the first load_font.php [font family] reference. (* having been through MANY changes)

Ok, For those who have similar issues - **The solution in short is**...

> Manually download DOMPDF Utils - [https://github.com/dompdf/utils](url)
> Put them somewhere in your project (I put them in `/path/to/project/vendor/dompdf/utils/`)
> run `php /path/to/project/vendor/dompdf/utils/load_font.php [Font Name From your CSS] [/path/to/fonts/FONTNAME.ttf]` (and include the font variants as noted here: [https://github.com/dompdf/dompdf/wiki/UnicodeHowTo](url) )

This should result in your fonts and `dompdf_font_family_cache.php` being put into your font path (default is: `.../vendor/dompdf/dompdf/lib/fonts/`)

That basically bypasses the need for DomPDF to download the font, and store it. You're *precaching* them.

So that's good. :)

Now all I have to do is work out the header overlap/hiding subsequent header from first page.

**Comment by bsweeney** [comment]
Sorry about mis-typing the tempDir option.

It's true, the benefit of using the load_font.php script is that the font gets pre-caching. The fact that it's not working via CSS is troublesome, but if that's the worst of your problems with the CSS at least you're able to move past it.

Good luck with the header. There are additional ways to do it, but they only get more complex so if you can get the recommended CSS working that would be idea.

**Comment by misterHippo** [comment]
That's ok, can't be perfect. :)

I don't mind complex ;) Would be good to hear them outlined in brief if you have time.

**Comment by misterHippo** [comment]
So, update on the header positioning thing.

I can: 
- Negatively relatively position something,
- Give something a negative bottom margin,
- Have images show up
- Have backgrounds show up (images or otherwise)

However, I can't get a background (image or style colour) to be over text. Regardless of:
- positioning / z-index
- order in HTML

It works in the HTML actual, rendered in Firefox. 

Thoughts?

**Comment by misterHippo** [comment]
Ok, well, thank you for your help. I believe I have everything sorted now. The outcome is very good :)

I hope I have included enough info above for others.

**Comment by bsweeney** [comment]
Glad you finally got it to where you're satisfied.
