### ISSUE TITLE
When tr is having a large content then the content does not overflow to the next page of PDF

### ISSUE THREAD

**Issue by priyabluecopper** [dompdf/dompdf#2089]
![sc](https://user-images.githubusercontent.com/61147046/74652831-ecf62300-51ac-11ea-8835-7ea06abe3e35.png)

**Comment by zelding** [comment]
this is clearly stated in the readme; table rows can not be broken to multiple pages

> Table cells are not pageable, meaning a table row must fit on a single page.

**Comment by priyabluecopper** [comment]
Then in that case what is the alternative solution? I need to have the design like table.

**Comment by bsweeney** [comment]
Based on what you show in your screen shot Dompdf isn't going to work. There are two issues, the first being that a table row can't span pages. The second issue is that content is rendered linearly, meaning that as elements on the page are encountered they are rendered. If an element causes a page break then any elements "next to" them get rendered on the next page, not on the page where that first element started.

If you want to watch for progress subscribe to updates to #98.

**Comment by chdonncha** [comment]
This is a feature I'd really like to see. I'm getting the exact same issue as well, thought it was possible to have tables span multiple pages until seeing this issue.

The current state of my PDF:
![image](https://github.com/user-attachments/assets/18808b50-3f13-4513-92d4-9abdcb849b3e)
