### ISSUE TITLE
BUG img with 100% width inside a table cell will result in very small image

### ISSUE THREAD

**Issue by welrachid** [dompdf/dompdf#2100]
Hi
```
<table width="100%">
<tr>
     <td width="100%" style="border-spacing:0px;border:none;">
	<img alt="banner" src="https://dummyimage.com/600x400/000/fff" width="100%"  />
     </td>
</tr>
</table>
```
Tried using the newest version 0.8.5
will result in a image that is very small...

**Comment by simonberger** [comment]
You need to set the row to 100%

**Comment by welrachid** [comment]
i dont follow?
This is my entire code
```
<?php
$html = '<table width="100%">
<tr width="100%">
     <td width="100%" style="border-spacing:0px;border:none;">
	<img alt="banner" src="https://dummyimage.com/600x400/000/fff" width="100%"  />
     </td>
</tr>
</table>';
	$dompdf = new \Dompdf\Dompdf();
	$options = new \Dompdf\Options();
	$options->setIsRemoteEnabled(true);
	$dompdf->setOptions($options);

	$dompdf->set_paper('A4','portrait');
    $dompdf->load_html($html);
	$dompdf->render();
	$dompdf->stream('test.pdf');

```

**Comment by simonberger** [comment]
You are correct. I had a missing quote in the html structure which resulted technically in this HTML document:

```
<table width="100%">
	<tr>
		<img width="100%" alt="banner" src="https://dummyimage.com/600x400/000/fff"  />
	</tr>
</table>
```

and this indeed works, but is obviously not something you should take as a solution.
Percentage values inside the td seem to have some problems. They takes the non automatically calculated width of the td as a base. If you set the td to 200px width the 100% image gets this width as well.

**Comment by welrachid** [comment]
Hi. This is the result. Still not working..
[test (1).pdf](https://github.com/dompdf/dompdf/files/4254192/test.1.pdf)
This is with only the HTML you provided.
The problem is i want to use the same HTML in both webview, email-view and pdf-view (receipt)

**Comment by simonberger** [comment]
I got your point. The HTML I provided is no solution anyway !!

I am going to look into the size calculation issues of images inside a table cell in the next days. I don't know if this receives a bugfix anytime soon though. You may try to change your HTML structure to get around the percentage value on the image or the cell or try it without a table.
But I know this might not be possible with what you need to build.

**Comment by welrachid** [comment]
Ok great. Waiting for your update :)

**Comment by simonberger** [comment]
https://github.com/simonberger/dompdf/commit/4df42b42f9b8249523eef85650f41c8995419414 is a quick fix to this issue. The problem is that the containers still have the percentage values and no actual dimensions. I don't know if this is just a behavior of tables or if other block elements have the same problem.
The patch stores all percentage values while traversing up and calculates the actual value at the end.

@bsweeney I guess a functionality like in the get_size method already exists and is used elsewhere right?

**Comment by welrachid** [comment]
Confirmed working. Looks great. Thanks!
