### ISSUE TITLE
DomPDF importing custom font is not working

### ISSUE THREAD

**Issue by priyabluecopper** [dompdf/dompdf#2101]
![sc](https://user-images.githubusercontent.com/61147046/75242518-46360600-57ee-11ea-89d4-96213b58debd.png)

The fonts are correctly embedded, but it is not showing in adobe reader.

![sc1](https://user-images.githubusercontent.com/61147046/75242620-79789500-57ee-11ea-8af0-20b18ccfc660.png)

**Comment by vishalsharma822** [comment]
i am aslo facing same problem

**Comment by vishalsharma822** [comment]
except english no other language are showing in pdf

**Comment by simonberger** [comment]
Please create a short HTML sample including the language. Otherwise we can't do much here.

I currently don't know if some languages have additional problems but beside this you can look at some other issues. Several users with similar problems could solve them there.
#1566, #1440

**Comment by skerbis** [comment]
- Version 0.8.5 
- Delivered and external via @font-face don't load
- Write / read permissions to cache is given: 


| PHP           |            |
| ------------: | :--------- |
|       Version | 7.2.30     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.29 |
| Character set | utf8         |


| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |


| Request       |               |
| ------------: | :------------ |
|       Browser | Safari/13.0.5 |
|      Protocol | HTTP/1.0      |
|         HTTPS | yes           |

**Comment by bsweeney** [comment]
Closing until further information is available.
