### ISSUE TITLE
Use a custom font on google app engine

### ISSUE THREAD

**Issue by HugoMartinez44** [dompdf/dompdf#2105]
Hello,

My servers are hosted by google app engine, I want to use a custom font however google does not allow the possibility of giving write rights on my application. On my dev environment, everything works well, how could we do for my google environments?

Error : "fopen(/srv/storage/fonts//poppins-normal_a312d75ffc9e3afb453066e28f1d83ba.ufm): failed to open stream: Read-only file system"

**Comment by bsweeney** [comment]
With some minor tweaks to the code you should be able to get this working. Please see #1719 for details.
