### ISSUE TITLE
syntax error, unexpected '=' in Dompdf.php on line 356

### ISSUE THREAD

**Issue by hchouhan02** [dompdf/dompdf#2106]
Hi, I'm getting the following error:
syntax error, unexpected '=' in /dompdf/src/Dompdf.php on line 356

Thanks in advance.

**Comment by simonberger** [comment]
Dompdf supports PHP 7.1 and above. The line uses a new syntax construct introduced in PHP 7.1 so I assume you run a PHP 7.0.X version.

**Comment by hchouhan02** [comment]
No, I'm using PHP 5.6.39. 
According to doc here: http://dompdf.github.io/
Under **Requirements**, it mentioned that **PHP 5.4+** is required.

Let me know, which version will work with this PHP version?

Thanks

**Comment by bsweeney** [comment]
As of Dompdf 0.8.5 you need PHP 7.1 or higher. We'll update the documentation on that page.

If you're unable to upgrade your version of PHP you can downgrade to Dompdf 0.8.3 (0.8.4 saw the introduction of a few styling/layout bugs that are likely to affect you).

**Comment by hchouhan02** [comment]
I tried with dompdf v0.8.3 but getting the same error, can you help to find the exact version which doesn't have this issue.

**Comment by bsweeney** [comment]
The exact same error or something else? Line 356 is completely different in 0.8.3.

How are you installing Dompdf? Composer or packaged download?

**Comment by raikodok** [comment]
> I tried with dompdf v0.8.3 but getting the same error, can you help to find the exact version which doesn't have this issue.

![image](https://user-images.githubusercontent.com/17611867/98064665-680b8080-1e85-11eb-8c70-791de130c813.png)

i change my composer.json to this and compose update , it solve  for me.

**Comment by compressore** [comment]
I'm having the same issue as above mentioned.  I'm not able to upgrade my PHP version, so when I downgrade to Dompdf 0.8.3 I ran into layout issues. Is there any other alternative solution to this?

**Comment by bsweeney** [comment]
@compressore not with the official releases of Dompdf. If you're not sure the layout issue is due to a bug start a discussion and we can try and figure out a work around.

**Comment by compressore** [comment]
Well, my issue was solved by using Dompdf 0.8.4 on  PHP version(7.0)

**Comment by nadyafw** [comment]
@compressore thankyou it works for me
