### ISSUE TITLE
Embed attachment to PDF file

### ISSUE THREAD

**Issue by tdjac0bs** [dompdf/dompdf#2111]
Hello, we would like to generate a PDF file with attached files inside it ( embeded ).

Is it possible to do with dompdf?

References:

- https://www.gnostice.com/nl_article.asp?id=193&t=Embed_Files_As_Attachments_To_PDF_Using_Java
- https://helpx.adobe.com/acrobat/using/links-attachments-pdfs.html#add_an_attachment

**Comment by simonberger** [comment]
This is unfortunately first possible with PDF file version 1.7 and dompf implements 1.3.
It would be good to increase the version but we first need to eveluate which changes this needs on our side.

**Comment by tdjac0bs** [comment]
Sounds really good @simonberger 

Is it a feature you see implemented in let's say, next 6 months? 

I ask because I need to choose the library to be used, so if you say it's in the roadmap we could go with dompdf and implement the embeded attachments later.

Thank you very much.

**Comment by simonberger** [comment]
You can monitor progress and discussion on #2115 .
One of the next steps will be a team discussion if we do this 1.7 raise or not.
Dompdf has no constantly active progress looking at the last month and years which means you won't get a real estimation for features nor there is a roadmap.
But I am currently on some tasks that shall bring some new features to users and some life in dompdf. PDF 1.7 with new possibilities like file attachment is one of these.

To anwer your question: It is possible that the feature is feasible and coming in the next weeks and month without any promise. ;)

**Comment by bsweeney** [comment]
FYI, this actually looks like it was first available in PDF 1.3 (section 3.10, same as in 1.7).

**Comment by simonberger** [comment]
You are correct it looks like this is fully available in version 1.3. I found some version history logs saying that just in version 1.7 embedding all file types is allowed.
It was this one or similar.
https://www.pdfen.com/blog/attachments-in-a-pdf-a-what-is-allowed-and-what-is-not

But that is maybe wrong or just for PDF/A which we do not follow anyway.

**Comment by sambenne** [comment]
Hi, I can see this is now in, but there does not seem to be away to actually use this method. How are you supposed to use it?

**Comment by simonberger** [comment]
Hi @sambenne have a look at the pull request.
You can find a usage example there.

https://github.com/dompdf/dompdf/pull/2117
