### ISSUE TITLE
Potential incorrect code

### ISSUE THREAD

**Issue by mbomb007** [dompdf/dompdf#2113]
### Version 0.8.2

I found the following using a code scan:

```php
if ($stroke = $style->stroke && is_array($style->stroke)) {
```

This is in SurfacePDFLib.php

This is equivalent to the following because assignment happens after the Boolean `&&`.
```php
if ($stroke = ($style->stroke && is_array($style->stroke))) {
```

I just want to make sure that this isn't a problem in some way, because this mistake is common. If wrong, it would be fixed by

```php
if (($stroke = $style->stroke) && is_array($style->stroke)) {
```

or by using `and` instead of `&&`.

Another occurrence in the same file:

```php
if ($fill = $style->fill && is_array($style->fill)) {
```

**Comment by simonberger** [comment]
You are correct. This is an issue and should be fixed. But it is another package. please add the issue again here: https://github.com/PhenX/php-svg-lib/issues
