### ISSUE TITLE
Raise PDF file format to version 1.7

### ISSUE THREAD

**Issue by simonberger** [dompdf/dompdf#2115]
This issue wants to evaluate the feasibility of raising the pdf file version of the (internal) CPdf PDF Renderer from 1.3 to 1.7 and on success add the needed changes.

**Comment by simonberger** [comment]
I can't find any problems or incompatibilities increasing the version to 1.7 even without doing anything.
I'd like to plan this for the next version if you have no concerns @bsweeney

**Comment by bsweeney** [comment]
I think that's probably fine. From Wikipedia:

> The specifications for PDF are backward inclusive. The PDF 1.7 specification includes all of the functionality previously documented in the Adobe PDF Specifications for versions 1.0 through 1.6. Where Adobe removed certain features of PDF from their standard, they are not contained in ISO 32000-1 either. Some features are marked as deprecated.

We're not using any obscure features right now so I suspect this should be fine. Implementing features from the newer versions, however, would definitely be more work.
