### ISSUE TITLE
WriteBlob Failed issue

### ISSUE THREAD

**Issue by Kistlak** [dompdf/dompdf#2119]
I was using dompdf to create pdfs since 2019. But, today it gave me this error.

```
"message": "WriteBlob Failed `/tmp/cpdf_img_V9CWAM.png' @ error/png.c/MagickPNGErrorHandler/1628",
    "exception": "ImagickException",
    "file": "/mnt/data/home/125764.cloudwaysapps.com/abghtyh/public_html/vendor/dompdf/dompdf/lib/Cpdf.php",
    "line": 4875,
```

I contacted the cloudways and ask them to change the permissions also. But, it didn't work. How can I solve this issue ??

**Comment by simonberger** [comment]
This is a permission issue. Either you aren't allowed to write to the file system of your provider, you have to use a different folder (not /tmp) or the permissions are just wrong.
You could change the temp dir via [setTempDir](https://github.com/dompdf/dompdf/blob/master/src/Options.php#L974)

**Comment by robwent** [comment]
For anyone finding this through Google.
I got this same error due to running out of memory when trying to process a very large PNG file (Coming from an API).
Increasing the memory limit fixed it.
