### ISSUE TITLE
Nested span & bg-color bug

### ISSUE THREAD

**Issue by Nuranto** [dompdf/dompdf#2122]
HTML to reproduce : 

```
<span style="background-color:red">
            toto
            <span style="background-color:green">tata</span>
            toto
            <span style="background-color:green">tata</span>
</span>
```
HTML result : 
![Capture d’écran 2020-03-25 à 16 22 42](https://user-images.githubusercontent.com/1633463/77553578-455bc700-6eb5-11ea-9dc7-ebe306f3d7a5.png)

PDF result : 
![Capture d’écran 2020-03-25 à 16 22 29](https://user-images.githubusercontent.com/1633463/77553387-09c0fd00-6eb5-11ea-95a2-da575a528cdb.png)

As you can see, there is a part where the background is missing (or wrongly white).
There is also a background vertical align issue, but that's less important.

**Comment by simonberger** [comment]
I'll have a look. 
In a first try I just tested how an outer inline div changes the result. With some negative padding we get the correct result.

```
<div style="padding-bottom: -2px; display: inline-block; background-color:red">
    toto
    <span style="background-color:green">tata</span>
    toto
    <span style="background-color:green">tata</span>
</div>
```

**Comment by Nuranto** [comment]
Hello @simonberger 
I've just tested your fix in my real case, and it does fix the issue, thank you !

(For the v-align issue, I cannot edit the html in my case, but that's not an important issue.)

**Comment by simonberger** [comment]
@Nuranto Thank you for confirming.
Regarding the vertical aligning problem you mentioned. First to note I am by far no CSS expert. But the background color moves with the text no matter how it is vertically aligned in its container.
I am a somewhat surprised by the text centering behavior. Dompdf renders it the way I expected it to be correct. It is the baseline position.
But it is indeed a low low priority problem I won't debug at this moment.
