### ISSUE TITLE
`white-space:pre-wrap` fails in two newline scenarios 

### ISSUE THREAD

**Issue by sakihl** [dompdf/dompdf#2124]
I think this partially overlaps with  [1315](https://github.com/dompdf/dompdf/issues/1315).
I am using PHP 7.2.28 and dompdf 0.8 (loaded by barryvdh/laravel-dompdf).
The problems are:
1. If there is a long line _without a newline_ at the end, it does not wrap.
2. If there are tags (e.g. bold) in a line _with a newline_ at the end, the newline is inserted before the part of the line after the closing tag, rather than at the end.

[ A third scenario came up later in the thread see [comment below](https://github.com/dompdf/dompdf/issues/2124#issuecomment-606063177).
3. Blank lines created by extra newlines not preserved ]

Example HTML (the monospace part is irrelevant to this issue - it makes it easier to check examples with leading spaces):

```html
<style>
	p.monospace-pre-wrap {
        font-family: Consolas, Courier, monospace;
        white-space: pre-wrap;
      }
</style>
<p class="monospace-pre-wrap">This is a long line with no newline at the end. Pre-wrap setting on the paragraph means that this line should wrap.</p>
<p class="monospace-pre-wrap">This line has <b>bold tags</b> and text afterwards ending in newline.
Another line.
</p>
```
In the PDF the long line just continues off the page without wrapping. The line with bold tags inserts the newline directly after the closing `</b>` tag instead of at the end.
![image](https://user-images.githubusercontent.com/62707603/77662338-a649d480-6f73-11ea-957d-9b134113981e.png)

I think both problems are in [FrameReflower/Text.php](https://github.com/dompdf/dompdf/blob/master/src/FrameReflower/Text.php)

In function `_layout_line()`, this piece of code (starting line 239) 
```php
case "pre-wrap":
                $split = $this->_newline_break($text);

                if (($tmp = $this->_line_break($text)) !== false) {
                    $add_line = $split < $tmp;
                    $split = min($tmp, $split);
                } else
                    $add_line = true;
```
does not handle the case where the line needs to wrap but there is no newline, so `$split` is false but `$tmp` is not.
I think it needs to be replaced with
```php
                $split = $this->_newline_break($text);
                if (($tmp = $this->_line_break($text)) !== false) {
                    if ($split !== false) {
                        $add_line = $split < $tmp;
                        $split = min($tmp, $split);
                    } else {
                        $split = $tmp;
                    }
                } else {                   
                    if ($split !== false) {
                        $add_line = true;
                    }
                }
```
I could not find a way to fix the second scenario locally within the `_layout_line()` function. The newline is being inserted within that function by this piece of code (line 314)
```php
           if ($add_line) {
                $this->_block_parent->add_line();
                $frame->position();
            }
```
but the piece of text before the newline is being inserted by calling `$block->add_frame_to_line($frame)` in the calling function `reflow()` **after** the call to `_layout_line()` returns
```php
     $this->_layout_line();

        if ($block) {
            $block->add_frame_to_line($frame);
        }
```
My suggested solution is 

1. remove the adding of the newline from `_layout_line()` 
```php
           /* Line now added afterwards in reflow()
           if ($add_line) {
                $this->_block_parent->add_line();
                $frame->position();
            }
           */
```
2. make `_layout_line()` return a boolean $add_line to indicate when there needs to be a newline after the text just handled, i.e a couple of instances of changing `return;` to `return $add_line;`
and one passing back the value from the recursive call (line 292)
```php
  // Layout the new line
  // $this->_layout_line();
  $add_line = $this->_layout_line();
```

3. put the actual adding of the newline into `reflow()`

```php
       $add_line = $this->_layout_line();

        if ($block) {
            $block->add_frame_to_line($frame);
            if ($add_line) {
                $block->add_line();
            }
        }
```
I have tried this approach by editing Text.php locally and my examples work.

![image](https://user-images.githubusercontent.com/62707603/77668065-da74c380-6f7a-11ea-8004-41456d07c342.png)

I have not tried to fix 'pre-line' but I think a similar fix would be required. 

As I said, I could not find a way to get the newline in the right place locally within `_layout_line()` and am not sure if moving the `add_line()` 'up' into `reflow()` will break something else.  Someone with more knowledge of the code may see a better solution. 
I am happy to paste my amended Text.php if that would be helpful.

**Comment by simonberger** [comment]
Thanks for the reported issue and the debugging. I reproduced the second problem and your fix.
The current add line behavior works in almost no case. I'll have some more tests tomorrow if something breaks and then probably add a pull request.

**Comment by sakihl** [comment]
Thank you for your quick response.

**Comment by sakihl** [comment]
I'm sorry if this is a silly question (I'm new at this). Do you need to indicate in the code that _layout_line now returns a boolean?

**Comment by simonberger** [comment]
> I'm sorry if these are silly questions (I'm new at this).
> Do you need to indicate in the code that _layout_line now returns a boolean?
> 
> Also, this change, from
> 
> ```
>  protected function _line_break($text)
> ```
> 
> to
> 
> ```
>  protected function _line_break($text): bool
> ```
> 
> means that _line_break now returns `true` in `$tmp` rather than the offset of where the line should wrap. I think we still need the offset to be returned.

Thank you for the kind note, that I did bullshit there. ;)
bool return type is now on the correct function.

**Comment by sakihl** [comment]
Thank you again for responding so fast. That fixes that.
However lines with a newline in the middle but not at the end do not break. For example
```html
<p class="monospace-pre-wrap">This line ends in newline
Another line after newline.</p>
```
comes out as
![image](https://user-images.githubusercontent.com/62707603/77894116-be1fa200-726c-11ea-87b2-c8a2e36df8bc.png)

The problem is in the pre-wrap code in _layout_line() at line [252](https://github.com/dompdf/dompdf/blob/d9258cf7d77a2e166e369b0fd5dea0cd9c55197b/src/FrameReflower/Text.php#L252)

```php
             } else if ($split === true) {
```
$split will never be true because _newline_break either returns false or an int.
I think we need either
```php
             } else if ($split !== false) {
```
or
```php
             } else if ($split > 0) {
```
I'm not sure which is better. The `!== false` option would be consistent with the "pre" code further up. Both "pre" and "pre-wrap" would set an extra `$add_line = true`  if `$split == 0` but this gets overwritten by the recursive call to _layout_line later on. The second option makes explicit that the add_line is only needed if `$split` is greater than 0, i.e. if the newline is not at the beginning of the line. 

Either option works for my specific example.
![image](https://user-images.githubusercontent.com/62707603/77896219-d513c380-726f-11ea-9e75-73ca380b634a.png)

**Comment by sakihl** [comment]
I have found another non-working case: a blank line created by two newlines is not preserved.
```html
<p class="monospace-pre-wrap">Line before two newlines

Line after two newlines</p>
```
comes out as

![image](https://user-images.githubusercontent.com/62707603/77927971-c0e7ba80-729f-11ea-91c3-40de18d07d86.png)

This time the problem seems to be in function add_frame_to_line in [FrameDecorator/Block.php line 159](https://github.com/dompdf/dompdf/blob/6782abfc090b132134cd6cea0ec6d76f0fce2c56/src/FrameDecorator/Block.php#L159)

```php
// FIXME: Why? Doesn't quite seem to be the correct thing to do,
// but does appear to be necessary. Hack to handle wrapped white space?
if ($w == 0 && $frame->get_node()->nodeName !== "hr") {
    return;
}
```
We don't want to return here if we are in pre-wrap so I think the line needs an extra check on is_pre()
```php
if ($w == 0 && $frame->get_node()->nodeName !== "hr" && !$frame->is_pre()) {
```
Again this fixes my example but I don't know what else might be affected.
![image](https://user-images.githubusercontent.com/62707603/77929317-6c453f00-72a1-11ea-8f2d-06392a817f01.png)

**Comment by simonberger** [comment]
@sakihl thank you for the very good input. I just had to double check and pushed your suggested changes.
Feel free to open a pull request on your own for the next bug or missing feature you find. It is quiet easy.

**Comment by sakihl** [comment]
@simonberger Thank you for making the changes and the encouragement. I have edited the original description to say this third scenario is also covered.
