### ISSUE TITLE
Transparent PNG files not rendered correctly with new Imagemagick

### ISSUE THREAD

**Issue by hasso** [dompdf/dompdf#2132]
There is a simple test with PNG file from http://www.libpng.org/pub/png/img_png/imgcomp-440x330.png :
```php
<?php
require 'vendor/autoload.php';
use Dompdf\Dompdf;

$dompdf = new Dompdf();
$dompdf->loadHtml('PNG:<br><br><img src="imgcomp-440x330.png">');
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
$dompdf->stream();
```

With gd (imagick module unloaded) it renders correctly ([document-gd.pdf](https://github.com/dompdf/dompdf/files/4415822/document-gd.pdf)), with Imagemagick it does not ([document-imagick.pdf](https://github.com/dompdf/dompdf/files/4415821/document-imagick.pdf)).

- There seems to be an issue with extracting opacity info. With imagemagick it's inverse what's expected and commenting out the line '$alpha_channel->negateImage(true);' from lib/Cpdf.php fixes the issue.
- The issue doesn't appear with older Imagemagick releases and seems to appear first with 7.0.9.14 release. However I'm unable to spot any real difference with convert utility between older and newer releases.

**Comment by bsweeney** [comment]
Likely related to #2087. Are you able to confirm that the change in that PR addresses the issue? I believe the following outlines the change in ImageMagick functionality: http://blog.awm.jp/2018/11/18/im7negate/

**Comment by hasso** [comment]
Yes, I can confirm that #2087 fixes the issue. Thanks.

**Comment by BrandonJamesBorders** [comment]
@bsweeney I'm able to confirm the change fixes the issue as well.

**Comment by bsweeney** [comment]
Thank you for the feedback.
