### ISSUE TITLE
[Updating] Problem table render, unicode font

### ISSUE THREAD

**Issue by vuvansang07** [dompdf/dompdf#2139]
DomPDF is great library to create PDF from HTML with CSS supported, this is stable library, but:
1. But have a problem with table render: "Table cells are not pageable". Please fix this limitations.
2. A little font render is not working, I use load_font.php tool, like: Calibri font, i get a little square when set font-style: italic.
3. I realize DomPDF render quite slow. But it is not problem with powerfull CSS supported from DomPDF.
4. DomPDF no have doc and example, hard for newbie when config and use it. Like FontMetrics, Options. I spend more time to learn how to use DomPDF. 

Now I use TCPDF to solve problem: font, table render. But TCPDF use core FPDF, it is weakness with support CSS.

After all, please fix limitations: "Table cells are not pageable". This is enough.

**Comment by simonberger** [comment]
Do not add several problems to one issue.
Reading through your issues most of them are already reported or know issues. Please use the search function.

**Comment by vuvansang07** [comment]
Yes, I know, but more time, I don't see any updating or discussion about it.
I can not chat in a close issue.

I think this is closed forever. So I want say about it.
If this problem make you annoy insted listening, ignore it.

This is simple, bye

________________________________
