### ISSUE TITLE
Bug : Neither <nobr> nor white-space:nowrap works with multiple elements

### ISSUE THREAD

**Issue by LoicBoursin** [dompdf/dompdf#2140]
I have a code which looks like this :

```HTML
<div style="width: 100px; border: 1px solid black">
   <span style="white-space:nowrap">
      <a href="#">TEST1</a>
      <a href="#">TEST2</a>
      <a href="#">TEST3</a>
      <a href="#">TEST4</a>
   </span>
</div>
```

I want "TEST" to be kept as a whole word, but currently it breaks the word in the next line. I have tried also the <nobr> tag but it didn't work.

I am doing this because the link clickable area isn't correctly placed when it involves multiline links (for too long content in link)

Thanks

**Comment by simonberger** [comment]
You seem to not use the latest dompdf release as I can't reproduce your problem.

**Comment by LoicBoursin** [comment]
I have to do this because of another issue, but after having searched everywhere and trying everything, I didn't solve it.

Here is the screen of my issue leading to this :
<img width="292" alt="Capture d’écran 2020-04-30 à 10 03 26" src="https://user-images.githubusercontent.com/32396605/80686997-e861bb00-8ac9-11ea-80c1-dde17dcf8828.png">
I have a table with a width:33% (grey bg) on the left & width:66% (white bg) on the right of dotted border.
When links just have only one <a> tag like on Twitter or Facebook, it happens that the clickable link area is misplaced after a line break. Or the clickable area is too high (_blog interne_ on the bottom).

The only solution I have found is to replace whole <a> tags by <a> tags for each letter (which leads us to the asked question to prevent breaking my words !)

**Comment by simonberger** [comment]
Please provide an example of this. I can't reproduce it. This should be worth more to fix.

**Comment by LoicBoursin** [comment]
Here is a very simplified version of my page, where the bug still occurs.
```PHP
<?php

require_once('assets/dompdf/autoload.inc.php');

use Dompdf\Dompdf;
use Dompdf\Options;
use Dompdf\FontMetrics;

$options = new Options();
$options->setIsRemoteEnabled(true);
$options->setIsHtml5ParserEnabled(true);
$options->setDefaultMediaType('all');
$options->setIsFontSubsettingEnabled(true);
$options->set('fontHeightRatio', 0.75);

$dompdf = new Dompdf($options);

$html = '';

$html .= '
<html><head>

<style>
@page{margin:0;padding:0}

@font-face {
  font-family: "Hind";
  font-style: normal;
  font-weight: normal;
  src: url('.CFG_WEBSITE_URL.'/assets/fonts/hind/Hind-Light.ttf) format("truetype");
}
*,
*::before,
*::after{
  box-sizing: inherit;
}

body, p, h3{
  margin:0;
}
.text-center{
  text-align:center;
}
a{
  text-decoration: none!important;
}
table{
  border-collapse: collapse!important;
}
.left-column{
  background-color: #f7f7f7;
}
.right-column{
  border-left: 1px dashed #7E7F7F!important;
  background-color: #fff;
}
.left-column, .right-column{
  padding-left:20px!important;
  padding-right:20px!important;
  padding-top:0px!important;
  padding-bottom:0px!important;
  height:1122px!important;
  line-height:1em!important;
}

p{
  font-family: "Hind"!important;
}
</style>
</head><body>
';

$html .= '<table width="794px">';
$html .= '<tbody style="vertical-align: baseline;">';
$html .= '<tr>';
$html .= '<td width="33%" class="left-column">';

$html .= '<p>printer took a <a href="https//www.google.com">ENORMOUSWORD</a> of type and scrambled it to make a type specimen book. It has survived not only five <a href="https//www.google.com">ENORMOUSWORD</a>, but also the leap into electronic typesetting, remaining <a href="https//www.google.com">ENORMOUSWORD</a> unchanged. It was popularised in the 1960s <a href="https//www.google.com">ENORMOUSWORD</a> the release of Letraset sheets <a href="https//www.google.com">ENORMOUSWORD</a> Lorem Ipsum passages, and more <a href="https//www.google.com">ENORMOUSWORD</a> with desktop publishing software like Aldus PageMaker including <a href="https//www.google.com">ENORMOUSWORD</a></p>';

$html .= '</td>';
$html .= '<td width="66%" class="right-column">';

$html .= '<p>printer took a galley <a href="https//www.google.com">ENORMOUSWORD</a> type and scrambled it to make a type specimen book. It has survived not only five <a href="https//www.google.com">Facebook</a>, but also the leap into <a href="https//www.google.com">ENORMOUSWORD</a> typesetting, remaining essentially unchanged. It was popularised in the <a href="https//www.google.com">ENORMOUSWORD</a> <a href="https//www.google.com">ENORMOUSWORD</a> the <a href="https//www.google.com">Twitter</a> of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versionsesfefsefs eorem Ipsum is sim<a href="https//www.google.com">ENORMOUSWORD</a>ply dummy text of the printing and typesetting<a href="https//www.google.com">Facebook</a> industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type <a href="https//www.google.com">Facebook</a>and scrambled it to make a type specimen book. It has survived not only <a href="https//www.google.com">Facebook</a>five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker inc<a href="https//www.google.com">Facebook</a>luding versionsesfefsefse

</p>';

$html .= '</td></tr></tbody></table>';

$html .= '</body></html>';

$dompdf->loadHtml($html);

$dompdf->setPaper('A4', 'portrait');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream("dompdf_output.pdf", array("Attachment" => false));

exit(0);
```
Here is a picture from my PDF viewer showing where are the clickable areas (misplaced when line break) 
<img width="777" alt="Capture d’écran 2020-04-30 à 20 23 07" src="https://user-images.githubusercontent.com/32396605/80745330-6a7cce80-8b20-11ea-9a34-8517ff701a18.png">

After testing a bit, it looks like the box-sizing: inherit (which is included within Bootstrap CSS) is causing the bug, but removing it leads clickable links links to be higher than the real link & other issues. 

<img width="777" alt="Capture d’écran 2020-04-30 à 20 24 57" src="https://user-images.githubusercontent.com/32396605/80745568-c7788480-8b20-11ea-8bd5-2b4fd6cd0aaf.png">

**Comment by simonberger** [comment]
"Interesting" bug. I can reproduce the misspositioned clickable areas. But after removing:
```
*,
*::before,
*::after{
  box-sizing: inherit;
}
```
It is correct in my test. I removed the custom font and the and the CSS p tag definition in my sample though.

**Comment by LoicBoursin** [comment]
I think the misplacement even with ```box-sizing: inherit;```removed is caused either by my ```$options->set('fontHeightRatio', 0.75);``` or ```line-height:1em!important;```which is necessary in my case to keep lines correctly spaced.
Adding support for ```box-sizing: inherit```with links would be great because it is included in every Bootstrap template :)

**Comment by bsweeney** [comment]
`box-sizing` support does not exist in Dompdf at present. I do have some preliminary work done to support it. We'll look to pick back up that work after 0.8.6 is released.

**Comment by bsweeney** [comment]
Looking at this one quickly it appears that one issue is that the clickable areas does not flow to the next line when the text reflows. Hopefully that particular issue is not too much of a challenge to fix.

**Comment by bsweeney** [comment]
I believe the layout problems identified in this issue have been addressed with more recent releases.
