### ISSUE TITLE
Syntax error Dompdf.php on line 356

### ISSUE THREAD

**Issue by GoodPanel** [dompdf/dompdf#2143]
Parse error: syntax error, unexpected '=' in /var/www/......./dompdf/src/Dompdf.php on line 356
Help :)

**Comment by bsweeney** [comment]
For the latest release you must be using PHP 7.1 or higher.

**Comment by olakunlemuheeb** [comment]
I'm currently getting the same error and I'm using PHP 7.3.6

**Comment by olakunlemuheeb** [comment]
@bsweeney

**Comment by bsweeney** [comment]
Is this through a web server or shell script? If web server can you supply info relevant to the PHP instance running through a phpinfo() page?
