### ISSUE TITLE
update messed fonts and czech characters

### ISSUE THREAD

**Issue by elizabeth-wood** [dompdf/dompdf#2145]
in version <6782abfc> dejavu sans works only in <h*> header tags, otherwise it drops to some default font, witch is not supporting czech characters in utf-8. And it causes me problems right now :) 

its about these characters:  č, ř, ě it just show "?"

I can't rollback because of other bug, but is there any quick workaround? 

![Screenshot from 2020-05-06 07-27-51](https://user-images.githubusercontent.com/5411228/81140875-33b51700-8f6b-11ea-89dc-5aa138139c32.png)

I'm using dompdf in symfony 5.0.* with template from twig, characters are directly in that twig template. I don't know right now, what aditional information should I provide, I am following your guides, so my code is pretty much the same as in the guides. But I'll provide you, what you ask for!

**Comment by nikhilbhatia22** [comment]
> in version <6782abfc> dejavu sans works only in <h*> header tags, otherwise it drops to some default font, witch is not supporting czech characters in utf-8. And it causes me problems right now :)
> 
> its about these characters: č, ř, ě it just show "?"
> 
> I can't rollback because of other bug, but is there any quick workaround?
> 
> ![Screenshot from 2020-05-06 07-27-51](https://user-images.githubusercontent.com/5411228/81140875-33b51700-8f6b-11ea-89dc-5aa138139c32.png)
> 
> I'm using dompdf in symfony 5.0.* with template from twig, characters are directly in that twig template. I don't know right now, what aditional information should I provide, I am following your guides, so my code is pretty much the same as in the guides. But I'll provide you, what you ask for!

Similar issue with INR symbol (₹), when using it with `<span style="font-family: DejaVu Sans; sans-serif;">&#8377;</span>`

**Comment by simonberger** [comment]
Please provide a HTML only example of your problem. I don't know of such a problem and the HTML snipped from @nikhilbhatia22 works fine for me.

Did you both activate the option `setIsRemoteEnabled` ?

**Comment by elizabeth-wood** [comment]
`<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Faktura - {{ invoice.invoiceNumber }} </title>
</head>
<body>

    <div class="container1">
    <h1>Faktura <br> {{ invoice.invoiceNumber }} </h1>
    <hr>
    <div class="row">
        <div class="col-6">
            dodavatel <br>
            <h2>{{ invoice.issuerName }}</h2>
            {{ invoice.issuerAdress|raw }}<br>
            ič: {{ invoice.issuerRegId }} <br>
            dič: {{ invoice.issuerVatId }} <br>
        </div>
        <div class="col-6">
            oděratel <br>
            <h2>{{invoice.name}}</h2>
            {{invoice.adress}}<br>
            ič: {{invoice.regId}} <br>
            dič: {{invoice.vatId}} <br>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-6">
            banknkovní účet: <strong>{{ invoice.issuerBankAccount }}</strong> <br>
            variabilní symbol: <strong>{{ invoice.invoiceNumber }}</strong> <br>
            způsob platby: Převodem <br>


        </div>
        <div class="col-6">
            vystaveno: <strong>{{  invoice.issueDate|date('d. m. Y') }}</strong> <br>
            datum splatnosti: <strong>{{  invoice.dueDate|date('d. m. Y') }}</strong>
        </div>
    </div>
    <hr>
        <br>
        <div class="row mini">
            <div class="col-7">Objednávka</div>
            <div class="col-2 text-right">základ</div>
            <div class="col-2 text-right">DPH</div>
            <div class="col-3 text-right">Celkem</div>
        </div>
    {% for item in invoice.invoiceRecords %}
        <div class="row mini">
            <div class="col-7">
                objednávka
{#                <a href="{{ path('AdminOrderDetail', {'uid':item.orderDay.orderEnt.uid}) }}">{{ item.orderDay.orderEnt.hrid }}</a>#}
                {{ item.orderDay.orderEnt.hrid|upper }}
                - {{ item.orderDay.menuDay.name() }} {{ item.orderDay.menuDay.date() }}
                - {{ (item.orderDay.amoutXl + item.orderDay.amoutNormal) }} jídel
            </div>
            <div class="col-2 text-right">{{ item.priceBase}} Kč</div>
            <div class="col-2 text-right">{{ item.priceVat}} Kč</div>
            <div class="col-3 text-right">{{ item.priceTotal}} Kč</div>
        </div>
    {% endfor %}
    <hr>
         <div class="row">
            <div class="col-7">Celkem</div>
             <div class="col-2 text-right">{{ invoice.priceBase }} Kč</div>
             <div class="col-2 text-right">{{ invoice.priceVat }} Kč</div>
             <h2 class="col-3 text-right">{{ invoice.priceTotal }} Kč</h2>
        </div>
    </div>


     <style type="text/css">

        body {
            font-size: 2.4mm;
            color: #333;
            line-height: 3mm;
            padding: 0px;
            font-weight: 100;
            margin: 0px;
            font-family: DejaVu Sans, sans-serif;

        }

        .text-right {
            text-align: right;
        }

        .container {
            max-width: 210mm;
            margin: auto;
        }

        .cistic {
            clear: both;
        }

        .clients{
           /* height: 220px;*/
        }

        .test {
            position: absolute;
            top: 0mm;
            left: 0mm;
            width: 30mm;
            height: 30mm;
            background:red;
        }

        hr {
            background: #aaaaaa;
            border: none;
            height: 0.2pt;
            margin: 2mm none ;
        }

        h2 {
            margin: 0px;
            font-size: 4mm;
            line-height: 5mm;
            margin-bottom: 0mm;
        }

        h3 {
            font-size: 3.2mm;
            line-height: 4mm;
            font-weight: 400;
            margin-bottom: 0mm;

        }

        .text-success {
            color: #28a745;
        }

        .text-danger {
            color: #dc3545;
        }

        .text-info {
            color: #17a2b8;
        }

        h1 {
            font-size: 7mm;
            line-height: 7.5mm;
            margin-top: 0mm;
        }
        .row {
            padding-bottom: 5mm;
        }

        .row.mini {
            padding-bottom: 0mm;
        }

        .row-mini {
            padding-top: 0px;
            padding-bottom: 0px;
        }
        .row.item {
            /*height:30px;*/
        }

        .col-6 {
            width: 48%;
            display: inline-block;
            vertical-align: top;
        }

        .col-7 {
            width: 54%;
            display: inline-block;
            vertical-align: top;
        }

        .col-2 {
            width: 11%;
            display: inline-block;
            vertical-align: top;
        }

        .col-3 {
            width: 19%;
            display: inline-block;
            vertical-align: top;
        }

        .col-month {
            width: 53%;
            display: inline-block;
            vertical-align: top;
        }

        .col-comment {
            width: 64%;
            display: inline-block;
            vertical-align: top;
        }

        .col-1-5 {
            width: 12%;
            display: inline-block;
            vertical-align: top;
        }

        .f-right {
            float: right;
        }

        .footer {
            position: absolute;
            bottom: 0px;
            left: 0px;
        }

    </style>

   
</body>
</html>
`

I tried it on different computer and that error was there, so I reverted back to 0.8.3 and it wors fine again

**Comment by nikhilbhatia22** [comment]
> Please provide a HTML only example of your problem. I don't know of such a problem and the HTML snipped from @nikhilbhatia22 works fine for me.

Then probably, the cause must be something else, will try to dig out and report.

**Comment by simonberger** [comment]
@elizabeth-wood There are no builtin fonts for `font-weight: 100`.
Just for `normal` (400) and `bold` (700). This is the reason the headline works which is unchanged `font-weight: bold` and the rest doesn't.
You might face the same problem @nikhilbhatia22 if you changedit in your CSS.
