### ISSUE TITLE
How to Use in Dompdf in Php MVC pattern not Laravel. 

### ISSUE THREAD

**Issue by modernman00** [dompdf/dompdf#2147]
URL = www.example.com/about

route =     $router->map('GET', '/about', 'App\About@show', 'about');

controller = class About { function(){ return view('about')}}

view = about.blade.php

I want to CONVERT the about page to html

so I called the dompdf function

            ob_start();
            require('/about');            
            $page = ob_get_contents();
            ob_end_clean();
            $document = new Dompdf();
            $document->loadHtml($page);
            $document->setPaper('A4', 'portrait');
            $document->render();
            //$document->stream();
            $document->stream("About.pdf", array("Attachment"=>0));
            $fileUpload = $document->output();
            return $fileUpload;

THE ERROR: I keep getting a warning message that '/about' cannot be found

Warning: include(/about): failed to open stream: No such file or directory in
xxxxxxx/xxxx/xxx/xxx/xx.php

**Comment by ytokarchukova** [comment]
Example,  `->loadHtml(view('your.view'))`

**Comment by modernman00** [comment]
Am getting this error:
Warning: require(): Filename cannot be empty in xxxx  require('/about');   on line 13

Fatal error: require(): Failed opening required '' (include_path='\xampp\php\PEAR') in C:\xampp\htdocs\__PATH TO THE CLASS on line 13.

Really frustrating. It worked okay in other application that was built without MVC design

**Comment by simonberger** [comment]
Your issue is before anything from dompdf is coming into play. For support please visit stackoverflow
