### ISSUE TITLE
How can I get  truly pdf content   height ? 

### ISSUE THREAD

**Issue by baijingqi** [dompdf/dompdf#2151]
First of all, my English is poor. I'm sorry if there are any grammatical mistakes in the following sentences.
I want to get the html's height and tried some ways. Finally I decided to use js to get the html's height and then told a  interface the height. but when I used the height to make pdf file , I got a pdf with much blank.  I also  tried  this way in issue 1524 to get height , the height was much larger than the height I got with js , so the pdf has much blank too.
How can I get   truly pdf content  height ? 
I hope someone can get me some suggestions, Thanks a lot.

**Comment by simonberger** [comment]
Without some (example) HTML showing your issue it is not possible to help you.

**Comment by bsweeney** [comment]
Dompdf can't tell you that until after it's completed rendering a document (see #1524). Retrieving the height via JS is possible though you'd have to make sure the browser dimensions (page width, DPI) closely match Dompdf's dimensions.
