### ISSUE TITLE
Information disclosure vulnerability in version 0.8.5 and earlier

### ISSUE THREAD

**Issue by keksa** [dompdf/dompdf#2152]
Hello, I believe I found a vulnerability in dompdf. I don't want to post the information publicly and I did not find any security contact information, so I'm going to send the info as a DM to your twitter account (@dompdf).

**Comment by bsweeney** [comment]
We'll review the information you provided and get back to you.

**Comment by bsweeney** [comment]
Curious if anyone can see this comment other than those with repo access. If not I'll add the details here.

**Comment by keksa** [comment]
Hey @bsweeney, is there any update with this? 🙂

**Comment by bsweeney** [comment]
Not yet but we are looking at it for the next release. Life is ... hectic ... right now.

**Comment by bsweeney** [comment]
The parsing logic has been updated with extra security. The adapter class and the bundled CPDF library are excluded because the parsing logic intermediates calls to those classes. A user should only have access if they can execute PHP directly, in which case the extra security there is pointless.

**Comment by bsweeney** [comment]
@keksa thanks for bringing this issue to our attention. I have a few more things to look at related to resource handling, but the changes currently posted in PR #2215 should address your concerns. If you have time please take a look.

I'll update this ticket with details on the issue once the 0.8.6 release is ready.

**Comment by keksa** [comment]
@bsweeney I can confirm this fixes the issue with our usecase, thank you.

**Comment by peter-gribanov** [comment]
This is a serious problem, but why did you break backward compatibility? You've broken a lot of your clients' code. Why was it impossible to add deprecation warnings and break backward compatibility at least in the minor version?
Please do not break backward compatibility in the patch anymore.

**Comment by bsweeney** [comment]
@peter-gribanov this has been brought up elsewhere. This was an oversight on my part and I apologize. We will try to do better in the future.

**Comment by naitsirch** [comment]
@bsweeney I have extended the documentation so that it is easier for users to spot their issues with this restriction: https://github.com/dompdf/dompdf/wiki/Usage#security-restrictions-for-local-files

I hope this will help.

**Comment by bsweeney** [comment]
Thanks for that @naitsirch! I'm still hoping to build out a bit more documentation around the issue and any help is appreciated.

**Comment by naitsirch** [comment]
Three further things may help:
1. Add the chroot option setting to the first usage example in the wiki. This will teach the users to specify that setting as soon as they start using dompdf.
2. Add the method to the method summary.
3. Search for code snippets in stackoverflow.com and add the chroot option setting.
