### ISSUE TITLE
Php inside Html showing in pdf

### ISSUE THREAD

**Issue by fatima-z** [dompdf/dompdf#2158]
Hi, I wonder how it's possible to Use Dompdf in Php MVC pattern, because I always get 'php code' inside the html generated to pdf.
(P.S : The view in php works fine)
the pdf file : 
![image](https://user-images.githubusercontent.com/41304333/82160497-53aadb80-9885-11ea-9b05-11d7b6960403.png)

**Comment by bsweeney** [comment]
Dompdf does not parse PHP, it accepts HTML and renders it to PDF. You can use Dompdf to support PDF rendering within your MVC framework, but the specific method you use would depend on which framework you're using.

Unless somebody familiar with your framework can comment you may not find an answer here.
