### ISSUE TITLE
How to format content overflow

### ISSUE THREAD

**Issue by nicksanchezc137** [dompdf/dompdf#2159]
My HTML has multiple sections, I am trying to prevent the content of a section from overflowing to the next page. I thought of using Javascript and pushing the entire section content to the next page instead of a section being cut between 2 pages. Since Javascript is not supported, how will I be able to properly format content and prevent the overflow of section content to the next page?

**Comment by ValdesChe** [comment]
You can do it by using CSS property **page-break-inside**  code : 
```
<div style="page-break-inside: avoid;">
  Your content 1
</div>
<div style="page-break-inside: avoid;">
  Your content 2
</div>
```
Automotically, if 2nd div content can't be on the same page with the first one, it will jump to the next page.

**Comment by nicksanchezc137** [comment]
Thanks will try it out

**Comment by bsweeney** [comment]
Avoiding the page break doesn't prevent the content from flowing to a new page. What it does is, if the element is not wholly contained on the page it will flow to the next page. At that point, if the content is still larger than the page then it will page the content.

If that's sufficient, then all good. If you need to avoid paging content at all that's a bit harder but still doable.

**Comment by godsdog** [comment]
I have the same problem with multiple divs containing a headline and p text. Right now it is not possible for me to prevent flowing text. How can this be achieved? You wrote: "If you need to avoid paging content at all that's a bit harder but still doable." Tell me how please ;)

**Comment by bsweeney** [comment]
@godsdog it really depends on your layout and how you want it to appear. Simplest form would be an absolutely positioned div with hidden overflow. If you have a variable-sized container you would likely have to resort to some level of coding ... might be able to do it through a callback but I'd have to look into it.
