### ISSUE TITLE
Color hex is missing

### ISSUE THREAD

**Issue by smartman** [dompdf/dompdf#2162]
I got this error.

Illegal string offset 'hex' at /vendor/dompdf/dompdf/src/Css/Style.php:1478

Related composer dependencies.
barryvdh/laravel-dompdf              v0.8.6    A DOMPDF Wrapper for Laravel
dompdf/dompdf                        v0.8.5    DOMPDF is a CSS 2.1 compliant HTML to PDF converter

$color value will become "windowtext" instead of array. Turns out that HTML had "color: windowtext;"

There should be validation of invalid colors.

Code that fails:
```
    protected function _get_border($side)
    {
        $color = $this->__get("border_" . $side . "_color");

        return $this->__get("border_" . $side . "_width") . " " .
1478:            $this->__get("border_" . $side . "_style") . " " . $color["hex"];
    }
```

**Comment by bsweeney** [comment]
Do you have a sample of the HTML/CSS? I was unable to reproduce with the following simple HTML:

```
<style>
  * { color: windowtext; }
</style>

<p>wat</p>
```

**Comment by smartman** [comment]
> Do you have a sample of the HTML/CSS? I was unable to reproduce with the following simple HTML:
> 
> ```
> <style>
>   * { color: windowtext; }
> </style>
> 
> <p>wat</p>
> ```

Try with something like that 

`<div style="text-align: justify;"><span lang="ET" style="font-family: 'Arial',sans-serif; color: windowtext; font-weight: normal; mso-bidi-font-weight: bold;"> MT&Uuml; lapsele <strong>!!lapse nimi!!</strong>, isikukood <strong>text</strong>(edaspidi <em style="mso-bidi-font-style: normal;">Laps</em>) J&auml;rvek&uuml;la, <span style="mso-spacerun: yes;">&nbsp;</span>7 alates <strong>!!alustamiskuup&auml;ev!!</strong>, millenem<span style="mso-spacerun: yes;">&nbsp; </span>Lapsehoiu tasu<span style="mso-spacerun: yes;">&nbsp; </span>(edaspidi <em style="mso-bidi-font-style: normal;">tasu</em>).<span style="mso-spacerun: yes;">&nbsp;<br /><br /></span></span></div>`

**Comment by salabh10** [comment]
i am getting the same error

**Comment by bsweeney** [comment]
OK, yes. Appears to be something with the inheritance of the color. Applying the color directly to an element is not an issue, but when the color is inherited by a child the error is displayed.

```
<p style="color: windowtext;">OK</p>
<p style="color: windowtext;"><span>ERROR</span></p>
```

**Comment by JoaoFOliveira** [comment]
I'm having the same error.

**Comment by salabh10** [comment]
@JoaoFOliveira , yes remove any inherited colour in your css class. Worked for me.

**Comment by JoaoFOliveira** [comment]
@salabh10 I'm getting user generated html to turn into PDFs and some of that is getting this error. Are you literally talking about `color: inherit;` or inherited color as a concept?
