### ISSUE TITLE
Ability to add security options?

### ISSUE THREAD

**Issue by sanjacornelius** [dompdf/dompdf#2164]
Hi! I am looking for a way to allow configuring security options such as

1. Disabling the ability to print/copy content.
2. Password protect PDF's

Is there currently a way/workaround that can achieve this with dompdf?

Thanks in advance!

**Comment by ravdeep9530** [comment]
@sanjacornelius 

1> May you found something here [https://stackoverflow.com/questions/12190294/prevent-copying-content-in-a-pdf-that-is-created-with-dompdf](url)
2>  Just set your password `$pdf->setEncryption($password);` 

 I used this `$this->dompdf->get_canvas()->get_cpdf()->setEncryption('userpass', 'ownerpass', array('print', 'copy'));` in my last project.

**Comment by sanjacornelius** [comment]
@ravdeep9530  thank you!
