### ISSUE TITLE
Outlined numbering of CSS counters do not properly render across page breaks.

### ISSUE THREAD

**Issue by mort1305** [dompdf/dompdf#2167]
There is a problem with outlined nested numbering being properly rendered over page breaks in DomPDF version 0.8.5.  I have attached a text file of the HTML used to create the attached PDF output.  Take notice the numbering does not continue from "3.2" to "3.3", but instead restarts at "3.1".

I've gone thru the code, but can't seem to figure it out:  I'm sorry that I cannot propose an answer to fix this issue.  However, I do have an inkling that this bug has something to do with the numbering counters being reset upon the adding of a new page to the PDF (as opposed to being preserved).

[numbering-problem.txt](https://github.com/dompdf/dompdf/files/4754893/numbering-problem.txt)
[numbering-problem.pdf](https://github.com/dompdf/dompdf/files/4754861/numbering-problem.pdf)

**Notes:**  I've blacked-out a little bit of the PDF and replaced that text with blanks in the HTML.  Also, the red text is added _after_ PDF generation so you won't find that in the HTML code.

**Comment by bsweeney** [comment]
Yeah, I'm seeing that as well. Nothing jumps out at me on initial look so we'll have to dig into it a bit.
