### ISSUE TITLE
Anchor tag linking is not working for Text

### ISSUE THREAD

**Issue by yogeshnipane** [dompdf/dompdf#2168]
**Dompdf 0.8.5**
When i use below code it works

`<a href="https://www.example.com">www.example.com</a>`

But it doesn't work when i use below code

`<a href="https://www.example.com">example</a>`

**Comment by bsweeney** [comment]
Works for me. Could be that the link box is being rendered in the wrong location. This previously came up in #1803 but we haven't had a chance to look into it yet.
