### ISSUE TITLE
Page break issue

### ISSUE THREAD

**Issue by mosvict** [dompdf/dompdf#2171]
Hi. I have some problems to use this package.
I already posted the issue for css. I am having other problem too.
I defined page size(A4) in html and set margin.
But I think it is not working.
I added 3 tables but each table made page break and I got 3 pages.
So I spent a lot of time to solve this problem.
I used "position:absolute" for 2 tables and solved. but I am not sure.
What problem?

**Comment by bsweeney** [comment]
Can't really help without seeing a sample of the HTML involved and any additional information you can provide.

**Comment by ahmedelfa** [comment]
Hello, I've been struggling with something similar while using tables. I figured out that even if the table is shown on the entire A4 page, it takes some pixels of the next or previous page. You may see that by coloring your table example : `table {background-color: blue;}` 

All I did was to use smaller font size for the whole content of my table 
`<table class="table table-bordered" style="font-size: 10px;">`
you may have to calibrate it manually until you find the most suitable size
