### ISSUE TITLE
Load with composer

### ISSUE THREAD

**Issue by ikbenignace** [dompdf/dompdf#2172]
Hello, I get a really confusing and big error after installing and using the pdf generator.

**Comment by ikbenignace** [comment]
Warning: Illegal string offset 'compress' in /data/sites/web/tracknteacheu/checkout/development/6fb885b72b8cf9c09b1716851d9d6d5cdd2ae58e/www/vendor/dompdf/dompdf/src/Adapter/CPDF.php on line 1141

Warning: Illegal string offset 'Attachment' in /data/sites/web/tracknteacheu/checkout/development/6fb885b72b8cf9c09b1716851d9d6d5cdd2ae58e/www/vendor/dompdf/dompdf/src/Adapter/CPDF.php on line 1142

Warning: Illegal string offset 'compress' in /data/sites/web/tracknteacheu/checkout/development/6fb885b72b8cf9c09b1716851d9d6d5cdd2ae58e/www/vendor/dompdf/dompdf/src/Adapter/CPDF.php on line 1146

Warning: Cannot modify header information - headers already sent by (output started at /data/sites/web/tracknteacheu/checkout/development/6fb885b72b8cf9c09b1716851d9d6d5cdd2ae58e/www/vendor/dompdf/dompdf/src/Adapter/CPDF.php:1141) in /data/sites/web/tracknteacheu/checkout/development/6fb885b72b8cf9c09b1716851d9d6d5cdd2ae58e/www/vendor/dompdf/dompdf/src/Adapter/CPDF.php on line 1149

Warning: Cannot modify header information - headers already sent by (output started at /data/sites/web/tracknteacheu/checkout/development/6fb885b72b8cf9c09b1716851d9d6d5cdd2ae58e/www/vendor/dompdf/dompdf/src/Adapter/CPDF.php:1141) in /data/sites/web/tracknteacheu/checkout/development/6fb885b72b8cf9c09b1716851d9d6d5cdd2ae58e/www/vendor/dompdf/dompdf/src/Adapter/CPDF.php on line 1150

Warning: Cannot modify header information - headers already sent by (output started at /data/sites/web/tracknteacheu/checkout/development/6fb885b72b8cf9c09b1716851d9d6d5cdd2ae58e/www/vendor/dompdf/dompdf/src/Adapter/CPDF.php:1141) in /data/sites/web/tracknteacheu/checkout/development/6fb885b72b8cf9c09b1716851d9d6d5cdd2ae58e/www/vendor/dompdf/dompdf/src/Adapter/CPDF.php on line 1151

Warning: Illegal string offset 'Attachment' in /data/sites/web/tracknteacheu/checkout/development/6fb885b72b8cf9c09b1716851d9d6d5cdd2ae58e/www/vendor/dompdf/dompdf/src/Adapter/CPDF.php on line 1154

Warning: Cannot modify header information - headers already sent by (output started at /data/sites/web/tracknteacheu/checkout/development/6fb885b72b8cf9c09b1716851d9d6d5cdd2ae58e/www/vendor/dompdf/dompdf/src/Adapter/CPDF.php:1141) in /data/sites/web/tracknteacheu/checkout/development/6fb885b72b8cf9c09b1716851d9d6d5cdd2ae58e/www/vendor/dompdf/dompdf/src/Adapter/CPDF.php on line 1155
%PDF-1.3 1 0 obj << /Type /Catalog /Outlines 2 0 R /Pages 3 0 R >> endobj 2 0 obj << /Type /Outlines /Count 0 >> endobj 3 0 obj << /Type /Pages /Kids [6 0 R ] /Count 1 /Resources << /ProcSet 4 0 R /Font << /F1 8 0 R /F2 9 0 R /F3 10 0 R /F4 11 0 R >> /ExtGState << /GS1 12 0 R /GS2 13 0 R /GS3 14 0 R /GS4 15 0 R /GS5 22 0 R /GS6 23 0 R >> >> /MediaBox [0.000 0.000 595.280 841.890] >> endobj 4 0 obj [/PDF /Text ] endobj 5 0 obj << /Producer (��dompdf <�6782abfc> + CPDF) /CreationDate (D:20200613180730+02'00') /ModDate (D:20200613180730+02'00') >> endobj 6 0 obj << /Type /Page /MediaBox [0.000 0.000 595.280 841.890] /Parent 3 0 R /Annots [ 16 0 R 18 0 R 20 0 R 24 0 R 26 0 R 28 0 R ] /Contents 7 0 R >> endobj 7 0 obj << /Filter /FlateDecode /Length 5163 >> stream x��\M�$�q�ﯨ�����,�DB��2$r$A��i�c�=3K����"^d��v�R�[�^f7�3�2#^�����W�׶��������/^/�BlK��uy}�|��y�����,˟�������O?/w��ϖϟ��wW�w�.?<�wOO��w�˛��˛���ۋ���rqw�|+�dد����������Z;��N������������J<�\mZ\b��b�$�ORH�Ĵ��C��Ĵ�ǋ��F,W�~��ˎ����w�W�_~U����><��ק.�e)��쿽�}s|X�Y~x�����g��@8���_�ç��:.�>�����Ä��e�ڗۥ�xH�L��3M ��&�b�̸��[�/B��qhy�F:n����ˇ���6���\i��^�R��<�VY�^�wŵKK*��b�a����*B��<�U�~c@L���e�:��Ǝ��&^��u(D\#����8U����/ y��=�)d�i. r�q�r�mS�T��ܹm��+��j���r*}Zr��-��T�� ���r����И� ��'nO!����1N䩬W0`j��C�j�m�QG�^��<�?p�N����E[H�X¼-䜓/TM����!�X�� ����|�[1�@Np2��D78M�8r�a�2�d3��$��̀�!Ǽ�r*��� iB�rFA�j���f$^C!G�Bnz���ceL���4�9ƌ�t�W�C�;�0*����햌j_cޗLN��D��M�Q�&d��hd$�*�ʍN>ۼB�s�� ݫd���dS���aC.�pE�v����d� �< ٻ���h����l����U��s�W��y��R����kZ�r4�I�ѣ�c�0\C��/?-a����e�����nl�ɒ]�*���"6�@o�b q��9Qhm����?MɆ��������i(��j�S%�b7������qe�C4�1kND�J�\ �� ��qx6<$`K�+ ��p1�eTC���%���d�ޛ O#�®��ֲ��!�r�|}�?m�}Cssf"8)���bg�KP�Z�\���~ЌV�����*���4��iD%:7:�Q�����Ԧ� �2��ۺ�24� Tc�D��W4�hk)gJ�m�!d�xé�)��u"��#�!���ۼE d�38���|��=�%���������4?0fMDL�0��(���U�`X���g�r��%M����3*�`�S��zD��7@�Ed�Iai�ʄh�>��hx��X��lk���d{K6l�����6�hJ�"�Ƣs��~�Q�dO�ب��D��"�5g#��f�r���1�+t�m[p��nG�f#Ǻ�c�m�Ѳ9��ɽ���N�ܼ�1�0�v�x�o0r^p�9o8�Y6�:�8�����^[ 8�y�8�y 9Ez��󸦐�78��S��F��{�� <� �[&B�%�v�Q-s�-�l F�3�O�c�b�����q��v�B +g�j#��\�Wh�V����f�k��f4��$Y���v��ϯkf��lFa��'�ر�B㌼ڌ��6�ر�5�^3S3��啢����\���~� !�2�Y��4[ ���霻w9�h�f+i�Kin��2w�nP4���[��s�L���*��J3S��Zɕ8����L���z�h��=N�k�W�"(�YY�4Z��8a��:�lD������h��ͨ�xI5�]��1�0�5�*�n�1��l�>s��cs\���G�a�gvPE�4�%��:�{P�<��*cĉ]��������!����=(J�^S�чe�������Zì3�!����4��~gg+:J�;��"��@� 2����P!�ũ'�Dp�Y��!"��P@>��8� \�㇫�6�g�@��J�l��⴬G-��=�1D�y�ѯ[���D��0Q�9Q�,@�9I���N3D����#�y���4ǀr"4�V����Nkk���"eC�u �[�i�R��hm��������Rj�����㙦��ї����p��n��������0�VG��ھ��8��5�������77��]�wy�ymc�z�T�:��VF���H�6��h��:�4�|�5D�M%�D,���5Q$9 D\q���^q>D�FNʨU]�XХH*V��� �)b Նg�a���H&cӐ�!3���Qj�bD�";����g"��"å2ѻW����3v.��A��w�OI?_�}��_iv�B��R��bPRl�f�ҥ��&^����)O�xB4=n3:L[��z��wޯ�6�s="���V���n7�5���jY5mѫ���Ve[����:--�sO��CQ�i�DYG��'!���hGV�'�!�@��{� F <�i�&��6������s=(6m��Z�9��h=��y�\l���H3[x��3WM���Al��A�rB�'����p��7�p�#�Y�~wk��q�7)Jp�8Q�E3��$�A�6� 39�����B*[G8D���E !���(��c�������z<��Z��g�����p���r~�-�}hig�� g/zʹ�~t�~vn$�9�g։"g^��y�tޞu^'�w'��A�yb��6|��r]Pt4oe=r��Ćf$�}I�a����N<�����<��*�h �K���10S�pK���f�1���o舘Iڱs~R�ßD)��`�['`V�&x� �`��0G0� M]��������5�&�#�7�#���� ���̀0��&?β�"�:<6[;��-O���*���Z�p7���>Z���3B�?3�Mq.? yqկ����"j ���x�V-���i {�H��6P�h��ˊؙК��s�N�@����=��_��eL�� Z����;QEHU`I�����i�*0��uch4���E�V��r��Q�l�s֯t?����#�Q�%S��:&� �+�֡`TlB�}b����J� E��)LN�]]#b%�5r����+MN;��PD��Z$7�������"۩�-���L�@���b�S����8�U�� VR�2�*�S�� "LIx?w��g���^9>�q�pu���zG���&��؝�ql�v�|Z�#cZ�#����<�_=.�w�Z�£z�ƣ��rN �3&&�S�Yg"zfȎxg,F���� �uίH������?��MU�Ir��U��xj��gҖ{"ـm8Jz$��}J*��%� b�wNF�T4��k���r�q�Tt�f���ٳ�������&�M��X4��]��/�T�1z����Û?Z���' �i�[��Stg�����,�Sd������]��� ���>�u@b;����X����F&�z����7���[�Um8Z,n[�m�vP+x�^Ǵ|lڊ���CH�� �1�*Sh,��5Q��+��s$&UP�8�P��61)"I��E�V���#�[$&5"D���9�k����_0����|N | �_�D��w�B�ϧ�@D>�6�����.|pl�X�TȇH�Zd@��C�t�y��wqE3.����m�X�.��H�z�aLN@��g@�7N�u�1Ěw�E���T���v"��l�w��@�=��W�>|uD��~�kv�}�wb�m3��#�ݲD�[~F�{���~�[�ȥZܹ��� F��fF���Q�#'8&'g8f�)�h2�#~2�G��|�E_O����� d]R""���h�����i���������\���}*��i�L���I��F}Z��O��1�#bf��ՊX�}�nV{.�q����h��l%�T����%�ii+y�Ċ�X}zJ�����kL;?���"D�s�P� ��H� Q&bNqb"M�(�^3-m��w1]�u1w�x�z���f��������%���?�nٟr[�{嶚�-�%�_ni����w�bo���Λ�yv���%��9�f��Qƾ�c�]C���*:��ut��'�!����-�1-�C�x\�owӯ���G-Q�Q=Q�QOT9's���)Ĭ3�4�ňp>c�8�}����_Tcs�A��_�CO@Ű����z �:;H&״�H@���X@d�n�����;��{�� �uvK �X��E���uxg����F��j�ʲS�^D�]�c��:AP���P��}$佅_��,I2;E�CA�"ѥR�M���|�TЮ�@7�/�u1����}u� ��g��wǞ�����H��رp˲�ᖟ���!�7vKܯ���~���PT�㨙�G{9�9vz���e�hֆ�Gr��>�G�P�!֥z柏]̏]̏]���.f�FUP{}��v1�:���xܿ��k�=����/�/�xAÇ��$��Y�b�U7���JR�s��?a�>T��wl�d���R6�?���?��o�tD������#\s�L����M���tDY�]�~�#�~��?��O��ǋ�N��G�B���y��味/d�~nZA#��~vr��{������oZ_<=O���3����77׏���7?�ޢ������xu|���o_�o.���%�OC���_9��8��/o/�ov+8����ή��:<��~s{}w�����������qw����X9�D��Y~�O�'�������������������O������Y=�>Mɽ�pq�$��Y�.���=5�'�J���?��g�]�㗧������n���n�:�x���?VsW�w�����r��m���������S�����3���˼�~3��ĭj���������.~� �T��� endstream endobj 8 0 obj << /Type /Font /Subtype /Type1 /Name /F1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >> endobj 9 0 obj << /Type /Font /Subtype /Type1 /Name /F2 /BaseFont /Times-Bold /Encoding /WinAnsiEncoding >> endobj 10 0 obj << /Type /Font /Subtype /Type1 /Name /F3 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >> endobj 11 0 obj << /Type /Font /Subtype /Type1 /Name /F4 /BaseFont /Helvetica-Oblique /Encoding /WinAnsiEncoding >> endobj 12 0 obj << /Type /ExtGState /BM /Normal /ca 0.1 >> endobj 13 0 obj << /Type /ExtGState /BM /Normal /CA 0.1 >> endobj 14 0 obj << /Type /ExtGState /BM /Normal /ca 1 >> endobj 15 0 obj << /Type /ExtGState /BM /Normal /CA 1 >> endobj 16 0 obj << /Type /Annot /Subtype /Link /A 17 0 R /Border [0 0 0] /H /I /Rect [ 43.7657 535.8551 43.7657 535.8551 ] >> endobj 17 0 obj << /Type /Action /S /URI /URI (/data/sites/web/tracknteacheu/checkout/development/6fb885b72b8cf9c09b1716851d9d6d5cdd2ae58e/www/about:blank) >> endobj 18 0 obj << /Type /Annot /Subtype /Link /A 19 0 R /Border [0 0 0] /H /I /Rect [ 43.7657 525.1713 43.7657 535.8551 ] >> endobj 19 0 obj << /Type /Action /S /URI /URI (/data/sites/web/tracknteacheu/checkout/development/6fb885b72b8cf9c09b1716851d9d6d5cdd2ae58e/www/about:blank) >> endobj 20 0 obj << /Type /Annot /Subtype /Link /A 21 0 R /Border [0 0 0] /H /I /Rect [ 43.7657 525.1713 43.7657 535.8551 ] >> endobj 21 0 obj << /Type /Action /S /URI /URI (/data/sites/web/tracknteacheu/checkout/development/6fb885b72b8cf9c09b1716851d9d6d5cdd2ae58e/www/about:blank) >> endobj 22 0 obj << /Type /ExtGState /BM /Normal /ca 0.05 >> endobj 23 0 obj << /Type /ExtGState /BM /Normal /CA 0.05 >> endobj 24 0 obj << /Type /Annot /Subtype /Link /A 25 0 R /Border [0 0 0] /H /I /Rect [ 297.6400 426.1854 491.2240 438.3954 ] >> endobj 25 0 obj << /Type /Action /S /URI /URI (mailto:diederik.roelandts@min.ksleuven.be) >> endobj 26 0 obj << /Type /Annot /Subtype /Link /A 27 0 R /Border [0 0 0] /H /I /Rect [ 297.6400 426.1854 297.6400 438.3954 ] >> endobj 27 0 obj << /Type /Action /S /URI /URI (mailto:diederik.roelandts@min.ksleuven.be) >> endobj 28 0 obj << /Type /Annot /Subtype /Link /A 29 0 R /Border [0 0 0] /H /I /Rect [ 491.2240 426.1854 491.2240 438.3954 ] >> endobj 29 0 obj << /Type /Action /S /URI /URI (mailto:diederik.roelandts@min.ksleuven.be) >> endobj xref 0 30 0000000000 65535 f 0000000009 00000 n 0000000074 00000 n 0000000120 00000 n 0000000396 00000 n 0000000425 00000 n 0000000584 00000 n 0000000741 00000 n 0000005977 00000 n 0000006084 00000 n 0000006192 00000 n 0000006305 00000 n 0000006421 00000 n 0000006480 00000 n 0000006539 00000 n 0000006596 00000 n 0000006653 00000 n 0000006779 00000 n 0000006938 00000 n 0000007064 00000 n 0000007223 00000 n 0000007349 00000 n 0000007508 00000 n 0000007568 00000 n 0000007628 00000 n 0000007756 00000 n 0000007849 00000 n 0000007977 00000 n 0000008070 00000 n 0000008198 00000 n trailer << /Size 30 /Root 1 0 R /Info 5 0 R /ID[] >> startxref 8291 %%EOF

**Comment by ikbenignace** [comment]
I don't even get a autoload.inc.php file

**Comment by bsweeney** [comment]
When loading via composer you use the composer autoloader. Looks like maybe your usage of Dompdf is where the issue is because that error is complaining about an array reference of a string. How are you calling the `stream` method?

**Comment by ikbenignace** [comment]
Looks like everything works on my personal host, but on my production host I get these errors, I tested it and normally it works but it doesn't, they have both PHP7.2

**Comment by bsweeney** [comment]
You may have the same issue locally but perhaps your local is just swallowing the errors instead of displaying them. Can't really offer any advice without info about your actual usage.
