### ISSUE TITLE
Undefined property: DOMAttr::$value

### ISSUE THREAD

**Issue by TechNov** [dompdf/dompdf#2175]
Hello, i have a trouble when i use dompdf from ubuntu 18 , php-fpm 7.2 and nginx like app server.
But my App work fine on Windows and windows server ( dev and test environement)
(1/1) ErrorExceptionUndefined property: DOMAttr::$value

---

in AttributeTranslator.php line 233
at HandleExceptions->handleError(8, 'Undefined property: DOMAttr::$value', '/var/www/api.bravafuel.com/bravafuel_bam_vivo_back/vendor/dompdf/dompdf/src/Css/AttributeTranslator.php', 233, array('frame' => object(Frame), 'node' => object(DOMElement), 'tag' => 'table', 'valid_attrs' => array('align' => array('left' => 'margin-left: 0; margin-right: auto;', 'center' => 'margin-left: auto; margin-right: auto;', 'right' => 'margin-left: auto; margin-right: 0;'), 'bgcolor' => 'background-color: %s;', 'border' => '!set_table_border', 'cellpadding' => '!set_table_cellpadding', 'cellspacing' => '!set_table_cellspacing', 'frame' => array('void' => 'border-style: none;', 'above' => 'border-top-style: solid;', 'below' => 'border-bottom-style: solid;', 'hsides' => 'border-left-style: solid; border-right-style: solid;', 'vsides' => 'border-top-style: solid; border-bottom-style: solid;', 'lhs' => 'border-left-style: solid;', 'rhs' => 'border-right-style: solid;', 'box' => 'border-style: solid;', 'border' => 'border-style: solid;'), 'rules' => '!set_table_rules', 'width' => 'width: %s;'), 'attrs' => object(DOMNamedNodeMap), 'style' => '', 'attr_node' => object(DOMAttr), 'attr' => 'cellspacing'))in AttributeTranslator.php line 233

Ubuntu 18
php-fpm 7.2
nginx

**Comment by TechNov** [comment]
i was face at this trouble,
in my case, my app workt in dev env ( windows and windows server, apache, php), but problem occur in prod ( ubuntu 18, nginx, php7.2-fpm).

when i run this : php --ini ; i got these warning!

Warning: Module 'dom' already loaded in Unknown on line 0
Warning: Module 'mbstring' already loaded in Unknown on line 0
Warning: ........................
Warning: Module 'xxx' already loaded in Unknown on line 0

so i fix them like talk [here](https://colekcolek.com/2011/12/16/fix-php-warning-module-loaded-unknown-line-0-ubuntu/) and [here](https://stackoverflow.com/questions/32764981/php-warning-module-already-loaded-in-unknown-on-line-0).

Remeber that dompdf use php 'dom' extenstion and other. so if this extension occur problem, dompdf will not work .

Enjoy

**Comment by bsweeney** [comment]
thanks for following up with how you resolved your issue
