### ISSUE TITLE
Dompdf not wokring on live server but works fine on localhost.

### ISSUE THREAD

**Issue by shehlizah** [dompdf/dompdf#2176]
I've been trying to generate a pdf. It is working fine on localhost but it doesn't works on live server i.e. Bluehost. It shows HTTP 500 error whenever i click on "Download PDF"  button on my site.

**Comment by bsweeney** [comment]
You'll have to find the error behind the 500 message. Try enabling PHP error logging.

**Comment by juanantoniodamianv** [comment]
@shehlizah did you solved or what was the issue behind status code 500?
