### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by ravikant-tcs** [dompdf/dompdf#2177]
phpcs -p --standard=PHPCompatibility --runtime-set testVersion 7.4 dompdf
...........W................................................ 60 / 84 (71%)
..........E........W....                                     84 / 84 (100%)

FILE: /Users/ravikantmane/Desktop/patch/dompdf/lib/html5lib/TreeBuilder.php
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3445 | WARNING | Since PHP 7.0, functions inspecting arguments, like debug_print_backtrace(), no longer report the original value as passed to a parameter, but will instead
      |         | provide the current value. The parameter "$node" was used, and possibly changed (by reference), on line 3444.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /Users/ravikantmane/Desktop/patch/dompdf/src/Adapter/CPDF.php
----------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------
 198 | ERROR | Extension 'cpdf' is removed since PHP 5.1; Use pecl/pdflib instead
----------------------------------------------------------------------------------

FILE: /Users/ravikantmane/Desktop/patch/dompdf/src/Helpers.php
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 481 | WARNING | Since PHP 7.0, functions inspecting arguments, like debug_backtrace(), no longer report the original value as passed to a parameter, but will instead provide the
     |         | current value. The parameter "$type" was used, and possibly changed (by reference), on line 480.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Time: 3.8 secs; Memory: 44.01MB

**Comment by cicoasm** [comment]
It doesn't work with php 7.4, from many problems. Example error log:

2020/06/26 08:47:30 [error] 25591#25591: *5372 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 0 in /var/www/clients/client0/web30/web/dompdf/dompdf/lib/Cpdf.php on line 4475PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/clients/client0/web30/web/dompdf/dompdf/lib/Cpdf.php on line 4475PHP message: PHP Notice:  Undefined offset: 0 in /var/www/clients/client0/web30/web/dompdf/dompdf/lib/Cpdf.php on line 4476PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/clients/client0/web30/web/dompdf/dompdf/lib/Cpdf.php on line 4476PHP message: PHP Notice:  Undefined offset: 0 in /var/www/clients/client0/web30/web/dompdf/dompdf/lib/Cpdf.php on line 4477PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/clients/client0/web30/web/dompdf/dompdf/lib/Cpdf.php on line 4477PHP message: PHP Notice:  Undefined offset: 0 in /var/www/clients/client0/web30/web/dompdf/dompdf/lib/Cpdf.php on line 4478PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/clients/client0/web30/web/dompdf/dompdf/lib/Cpdf.php on line 4478" while reading response header from upstream, client: 192.168.0.107, server: test.it, request: "GET /dompdf/test.php HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php7.0-fpm/web30.sock:", host: "test.it"

**Comment by simonberger** [comment]
Your bottom line tells me you use PHP 7.0 which is not supported. The specific line on the other hand does not point to where the issue might come from. There is no PHP version specific code.
