### ISSUE TITLE
External images don't work

### ISSUE THREAD

**Issue by simonschaufi** [dompdf/dompdf#2181]
Embedding external images doesn't work. This also shows the example page here: https://dompdf.net/examples.php#image_remote.html,pdf

When I search for the constant `DOMPDF_ENABLE_REMOTE`, I don't find anything in the source code.

## Test code:

```html
<img src="https://placebear.com/200/300.jpg" alt="not found" />
```

## Result

![image](https://user-images.githubusercontent.com/941794/85960124-6abf0c00-b9a1-11ea-8d26-9fd27fdc4fa8.png)

**Comment by bsweeney** [comment]
That constant is used in versions of Dompdf prior to 0.7.x. To enable remote resource loading with Dompdf 0.7.x and higher you have to set the option. There are a few ways to do that, here's one:

```
$dompdf->set_option('isRemoteEnabled', true);
```

**Comment by tillackt** [comment]
Hi, 

don't use "$dompdf->set_option('isRemoteEnabled', true);". This is deprecated. Use the following instead:

`
$pdfOptions = new Options();
$pdfOptions->setIsRemoteEnabled(true);
$dompdf = new Dompdf($pdfOptions);
`

**Comment by bsweeney** [comment]
Yeah, sorry 'bout that.

**Comment by simonschaufi** [comment]
Could the example page also be updated?

**Comment by bsweeney** [comment]
done on Develop, master will be updated when the next release is ready
