### ISSUE TITLE
Font scale

### ISSUE THREAD

**Issue by cristiano-linvix** [dompdf/dompdf#2184]
Good afternoon, I would like to know how I can reduce the font scale in the pdf gift.

For example, fonts are 15px in html, and I would like all of them to be 1px less than 15, but automatically.

Or scalling all elements on PDF.

**Comment by bsweeney** [comment]
You can try a few things:
- change the Dompdf DPI, PX are translated to PT at a resolution of 72 PPI. So if your DPI is 72 you get a 1-to-1 translation. If If you want PX to cover half the distance in your PDF you would set your DPI to 144.
- use a Dompdf-specific stylesheet. Dompdf recognizes "dompdf" as a valid media type so you can specify dompdf as the media type to a linked stylesheet:
```
<link href="print.css" rel="stylesheet" media="dompdf">
```
or add a media type query with the dompdf-specific styling to your existing stylesheet:
```
@media dompdf {
  /* add your dompdf-specific styles here */
}
```
