### ISSUE TITLE
Page breaking on table

### ISSUE THREAD

**Issue by hhjung2013** [dompdf/dompdf#2189]
I am trying to bring a weekday table into a PDF. It probably won't fit on one landscape page, so I am looking for a way to have more control over where to do the page break. I have tried `page-break-inside: avoid` on the table and `page-break-after: always` on the row for testing but both didn't have any effect at all.

Here is my basic code:
```
<!DOCTYPE html>
<html>
<head>
<link type="text/css" rel="stylesheet"
	href="https://www.devah.de/wp-content/themes/infinity-pro/style-pdf.css">
</head>
<body>
	<table class="dv-kursplan kp-large">
		<thead>
			<tr></tr>
		</thead>
		<tbody>
			<tr></tr>
			<tr></tr>
			<tr></tr>
		</tbody>
	</table>
</body>
</html>
```
```
table {
	page-break-inside: avoid;
}	

.dv-kursplan {
	background-color: #eee;
	font-family: sans-serif;
	font-size: 1.2rem;
}

.dv-kursplan th {
	text-align: center;
	border: 1px solid #fff;
	font-weight: normal;
}
	
.dv-kursplan td {
	width: 14%;
	padding: 0;
	border: 1px solid #fff;
}
```

The full page is available here:
https://www.devah.de/pdf-test/

This is the rendered PDF result:
[devah_kursplan(4).pdf](https://github.com/dompdf/dompdf/files/4875710/devah_kursplan.4.pdf)

Any help on how to apply page breaking is greatly appreciated.

**Comment by bsweeney** [comment]
If I recall correctly Dompdf does not handle page break declarations on table elements (#404). I'd have to review the current state of the code to say for certain if that has changed at all.

**Comment by hhjung2013** [comment]
This post made me think it was possible:
https://stackoverflow.com/questions/8723487/dompdf-page-break-if-element-is-exceeding-page-height
If you could check the code for clarity it would be very helpful.

If page breaking inside of tables is not supported, I guess using table-styled divs would be the way to go. Any other ideas?

**Comment by bsweeney** [comment]
It's possible to use the page-break declarations, just not on table elements. What I would have to review is if any work has been done to address that deficiency, but I do not believe so.

If you want this type of layout now using table-styled divs would probably work best. Though, I'd create a sample document before you invest too much time into it.

**Comment by hhjung2013** [comment]
But the above stackoverflow topic is about page breaks on tables, isn't it?

It seems to me that dompdf breaks tables on row level by default. In the document I posted above it breaks the page before the last row because it doesn't fit on the first page. If I reduce the height of the last row everyhting is on one page. Does that go along with your code?

**Comment by bsweeney** [comment]
OK so I did some quick testing with a simple layout and the page break declarations generally work OK on the table element itself. They do not work at all on TR and TD elements. If you want to break at a particular row I'd add an element with page break styling inside the first TD element of the row that should appear on the next page.

As far as how Dompdf handles tables, it is currently unable to break an individual table cell across pages. So if any cell in a row needs a page break Dompdf moves the entire row to the next page.

I'm not sure based on your attachment what you're expecting, and the link you provided is to the rendered PDF not to the HTML so I can't really inspect it to see what's going on.

**Comment by hhjung2013** [comment]
The link returned HTML by the time I started the thread. I could bring it back but maybe it's not that important. My intention was to bring as much content of the table as possible on the first page an the rest on the next page. Currently the table consists of three rows and it seems to break after the second. Are you saying that `page-break-inside: avoid`on table should work?
Maybe he solution is to simply break down the content into more rows so dompdf can break more fine-grained. I will also try a portrait format I just wanted to understand page breaking in dompdf better.

**Comment by simonschaufi** [comment]
related: https://github.com/dompdf/dompdf/issues/2190

**Comment by bsweeney** [comment]
Sample HTML from the original post is no longer available (reminder to always post sample HTML with the issue). Based on the description, however, I believe the next release will sufficiently handle the use case outlined. As such I'm closing the issue.

Note that break declarations on TD elements are still not honored, but an individual table cell is still unable to span pages so we'll address page declarations when we address individual cell paging (#98).

**Comment by caltejohn** [comment]
I have a one large table (Job Application).  The results with this one large table are subpar.  Will page breaks work  between tables?  I am thinking of breaking my document into several small tables.

Thanks
