### ISSUE TITLE
DOMPDF whole table was broke to a new page when my table filled up

### ISSUE THREAD

**Issue by nguyenpr9** [dompdf/dompdf#2190]
I'm using version Dompdf 0.8.5
This is my code and my pdf render: 
![FireShot Capture 008 -  - localhost](https://user-images.githubusercontent.com/55862211/86585376-98631100-bfb0-11ea-9ecd-ea18b9ae307b.png)

```
            <div>header</div>
            <div>title</div>
            <div>somethingelse</div>

            <div class="detail" style="width:100%">
                <table id="tbDetail" cellpadding="0" cellspacing="0" width="100%" style="font-size: 11.5px">
                    <thead>
                        <tr class="detail-header">
                            <td class="br-1 bb-1 bt-1 text-center" style="width:3%">NBR</td>
                            <td class="br-1 bb-1 bt-1 text-center" style="width:35%">Product</td>
                            <td class="br-1 bb-1 bt-1 text-center" style="width:13%">Unit</td>
                            <td class="br-1 bb-1 bt-1 text-center" style="width:10%">Quantity</td>
                            <td class="br-1 bb-1 bt-1 text-center" style="width:17%">Price</td>
                            <td class="br-1 bb-1 bt-1 text-center" style="width:19%">Total</td>
                        </tr>
                    </thead>
                    <tbody>
                        <xsl:for-each
                                select="(//node())[37 >= position()]">
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                        </xsl:for-each>
                    </tbody>
                </table>
            </div>
```

Please help me to resolve this issue :(((

**Comment by bsweeney** [comment]
That layout alone shouldn't cause this particular issue. Could be something in the CSS. Can you post a full sample of the HTML+CSS?

**Comment by nguyenpr9** [comment]
> That layout alone shouldn't cause this particular issue. Could be something in the CSS. Can you post a full sample of the HTML+CSS?

`
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:exsl="http://exslt.org/common"
                extension-element-prefixes="exsl">
    <xsl:decimal-format name="european" decimal-separator="," grouping-separator="."/>
    <xsl:template match="/">
        <html>
            <head>
                <title>Detail</title>
            </head>
            <style>
                @page { margin:0; }
                body {
                padding: 45px;
                }
                #tbDetail {
                border-style: solid;
                border-color: #776b6b;
                border-width: 0.7px;
                border-collapse: collapse;
                line-height: 16px;
                }
                #tbDetail td {
                border-style: solid;
                border-color: #776b6b;
                border-width: 0.7px;
                padding: 2px;
                }
                #tbDetail .detail-data td {
                border-style: none solid dotted none;
                }
                #tbDetail tr td span {
                display: inline-block;
                text-align: center;
                }
                .bt-1{
                border-top: 1px solid #776b6b;
                }
                .br-1 {
                border-right: 1px solid #776b6b;
                }
                .bb-1 {
                border-bottom: 1px solid #776b6b;
                }

            </style>
            <body>
                <div>header</div>
                <div>title</div>
                <div>somethingelse</div>
                <div class="detail" style="width:100%">
                    <table id="tbDetail" cellpadding="0" cellspacing="0" width="100%" style="font-size: 11.5px">
                        <thead>
                            <tr class="detail-header">
                                <td class="br-1 bb-1 bt-1 text-center" style="width:3%">NBR</td>
                                <td class="br-1 bb-1 bt-1 text-center" style="width:35%">Product</td>
                                <td class="br-1 bb-1 bt-1 text-center" style="width:13%">Unit</td>
                                <td class="br-1 bb-1 bt-1 text-center" style="width:10%">Quantity</td>
                                <td class="br-1 bb-1 bt-1 text-center" style="width:17%">Price</td>
                                <td class="br-1 bb-1 bt-1 text-center" style="width:19%">Total</td>
                            </tr>
                        </thead>
                        <tbody>
                            <xsl:for-each
                                    select="(//node())[37 >= position()]">
                                <tr class="detail-data text-left">
                                    <td>&#160;</td>
                                    <td>&#160;</td>
                                    <td>&#160;</td>
                                    <td>&#160;</td>
                                    <td>&#160;</td>
                                    <td>&#160;</td>
                                </tr>
                            </xsl:for-each>
                        </tbody>
                    </table>
                </div>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
`
here

**Comment by ahmednawazbutt** [comment]
I copied/pasted your code in an online [xml validator](https://www.xmlvalidation.com/)
It tells a lot is wrong in your XML.
Please check by yourself

**Comment by bsweeney** [comment]
I'm still not seeing it. You can try reproducing here: http://eclecticgeek.com/dompdf/debug.php

**Comment by nguyenpr9** [comment]
I'm just add all my code in one file. just my html/css and logic  but it still have proplem 
[test.pdf](https://github.com/dompdf/dompdf/files/4882057/test.pdf)

`
            $dompdf = new Dompdf();
            $html = <<<'ENDHTML'
            <html>
            <head>
                <title>Detail</title>
            </head>
            <style>
                @page { margin:0; }
                body {
                padding: 45px;
                }
                #tbDetail {
                border-style: solid;
                border-color: #776b6b;
                border-width: 0.7px;
                border-collapse: collapse;
                line-height: 16px;
                }
                #tbDetail td {
                border-style: solid;
                border-color: #776b6b;
                border-width: 0.7px;
                padding: 2px;
                }
                #tbDetail .detail-data td {
                border-style: none solid dotted none;
                }
                #tbDetail tr td span {
                display: inline-block;
                text-align: center;
                }
                .bt-1{
                border-top: 1px solid #776b6b;
                }
                .br-1 {
                border-right: 1px solid #776b6b;
                }
                .bb-1 {
                border-bottom: 1px solid #776b6b;
                }

            </style>
            <body>
                <div>header</div>
                <div>title</div>
                <div>somethingelse</div>
                <div class="detail" style="width:100%">
                    <table id="tbDetail" cellpadding="0" cellspacing="0" width="100%" style="font-size: 11.5px">
                        <thead>
                            <tr class="detail-header">
                                <td class="br-1 bb-1 bt-1 text-center" style="width:3%">NBR</td>
                                <td class="br-1 bb-1 bt-1 text-center" style="width:35%">Product</td>
                                <td class="br-1 bb-1 bt-1 text-center" style="width:13%">Unit</td>
                                <td class="br-1 bb-1 bt-1 text-center" style="width:10%">Quantity</td>
                                <td class="br-1 bb-1 bt-1 text-center" style="width:17%">Price</td>
                                <td class="br-1 bb-1 bt-1 text-center" style="width:19%">Total</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                              <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                              <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                              <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                            <tr class="detail-data text-left">
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                                <td>&#160;</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </body>
        </html>
ENDHTML;
            $dompdf->loadHtml($html);
            $dompdf->setPaper('A4', 'portrait');
            $dompdf->render();
            $dompdf->stream("example.pdf", array("Attachment" => 0));
`
my file when i render

**Comment by nguyenpr9** [comment]
> I'm still not seeing it. You can try reproducing here: http://eclecticgeek.com/dompdf/debug.php
> 
> You'll need to supply the actual HTML + CSS produced by your XSL.



> I copied/pasted your code in an online [xml validator](https://www.xmlvalidation.com/)
> It tells a lot is wrong in your XML.
> 
> even if I try to [format your code](https://www.freeformatter.com/xml-formatter.html), it says
> 
> > Unable to parse any XML input. Error on line 79: The element type "xsl:template" must be terminated by the matching end-tag "</xsl:template>".
> 
> Please check by yourself
> 
> Also, if possible, please beautify your code you pasted here

**It's a bug. this code i'm using v 8.0.5 but when i use v 8.0.1 i resolve my issue**

**Comment by circuitmamu** [comment]
I think vesion i 0.8.4 from where this issue starts when we parse whole HTML code with table

**Comment by bsweeney** [comment]
bug or no we can't help you without seeing a sample document (HTML + CSS) that exhibits the issue

**Comment by circuitmamu** [comment]
@bsweeney 
you can have a look it it below I made an demo to how things gone change
http://demo.eonssofttech.co/pdf_demo/demofile.html
this is the demo html file is used in all my pdf demo exmaple you can view source code it if want

http://demo.eonssofttech.co/pdf_demo/0.8.3/test.php
http://demo.eonssofttech.co/pdf_demo/0.8.4/test.php
http://demo.eonssofttech.co/pdf_demo/0.8.5/test.php

Then I made three directory 0.8.3, 0.8.4, 0.8.5 and add a test.php inside all of them having same code that load html from  demofile.html and render to browser. each directory load different version of dompdf

I also post here PHP code so you can have a look it

`<?php
use Dompdf\Dompdf;
use Dompdf\Options;

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

// include autoloader
require_once 'vendor/autoload.php';

$options = new Options();
$options->set('isRemoteEnabled', true);
//$options->set('isHtml5ParserEnabled', true);
$options->set('debugLayout', false);
//$options->set('debugPng', true);
$options->set('enable_php', false);


$dompdf = new Dompdf($options);

$html = file_get_contents('../demofile.html');
$dompdf->loadHtml($html);
$dompdf->render();
$dompdf->stream('file.pdf',array("Attachment" => 0));
?>
`

**Comment by bsweeney** [comment]
@circuitmamu I believe your issue may be slightly different. I believe there may be one or more issues related, though the only one I could find at the moment is #2165

**Comment by rmilecki** [comment]
Try
```
table {
	page-break-before: avoid;
}
```

**Comment by bsweeney** [comment]
I have still been unable to reproduce the issue based on the example provided by nguyenpr9 (event after running the XSL transformation).

As for the issue reported by @circuitmamu, it actually looks like a bug related to separated borders where the table has a top margin. I'll create a new issue related to that.

**Comment by jony741** [comment]
table{
            page-break-inside: avoid
        }
        table tr{
            page-break-after: avoid
        }
