### ISSUE TITLE
PDF Preview of HTML(Bootstrap Page)

### ISSUE THREAD

**Issue by more-yogesh** [dompdf/dompdf#2192]
Each time when I create HTML to PDF I have to download and check that design is okay or not, Is there any way to check the exact preview of my PDF that is going to build from HTML? It'll also solve all the design issues and anyone can find issues easily.

**Comment by bsweeney** [comment]
Not sure what you mean. The only way to really tell with Dompdf is to attempt to render.

Note that because of some outstanding deficiencies (namely, lack of support for the box-sizing declaration) that Bootstrap layouts may not render quite as expected.

**Comment by HaiAlison** [comment]
you can use stream(); to see what export to pdf
