### ISSUE TITLE
DOMPDF suddenly can't convert HTML to PDF

### ISSUE THREAD

**Issue by Sudhindra51** [dompdf/dompdf#2194]
Don't know what happened and I didn't change any code recently, DOMPDF suddenly stops converting my HTML to PDF. When I tried to debug, it is stopping in "$root->reflow();" in the render function. Couldn't able to find the exact problem in that step. I have been sending the same or less content in HTML that I used to send before. Before no problem used to show, now it is redirecting to 404.

Please help me with this!!!

[dompdf.txt](https://github.com/dompdf/dompdf/files/4910978/dompdf.txt)

**Comment by bsweeney** [comment]
We would need to see the error message generated plus a sample document exhibiting the issue before we can provide any guidance.
