### ISSUE TITLE
Not showing content ")" after ordered list Item counter number

### ISSUE THREAD

**Issue by Adeelmirza215** [dompdf/dompdf#2195]
Hi, i'm using 0.8.5 version of dompdf and have an issue after generating pdf. i want to add small bracket after counter number of list item .

1 ) Item 1
2 ) Item 2

but in html it shows perfect but not showing in pdf. In pdf it shows as 

Item 1
Item 2

Code:

```
ol {
    counter-reset: list;
    margin: 0;
    list-style: none;
}

ol > li {
    list-style-type: none;
    position: relative;
    font-family: Calibri;
    font-size: 10pt;
}

ol > li:before {
    counter-increment: list;
    content: counter(list,decimal) ")";
    position: absolute;
    left: -1.8em;
    font-weight: bold;
    font-family: Calibri;
}
```

**Comment by bsweeney** [comment]
Looks like a bug in the stylesheet parser. I haven't reviewed the source but I believe it's detecting the right parenthesis as a CSS syntactical character rather than as part of a string literal.

You can work around the issue by hex-encoding the character:

```
ol > li {
  content: counter(list,decimal) "\0029";
}
```
