### ISSUE TITLE
Dompdf Version 0.8.5 Arabic RTL Not Showing Correctly

### ISSUE THREAD

**Issue by moussahoussein** [dompdf/dompdf#2197]
I'm currently using the latest version of dompdf 0.8.5 , trying to export arabic text to pdf file

```
<?php

$linktentinvoice='<html><head><style>*{ font-family: DejaVu Sans, sans-serif; }</style><head><p>مرحبا</p></html>';

require_once 'dompdf/autoload.inc.php';

use Dompdf\Dompdf;
// instantiate and use the dompdf class
$dompdf = new Dompdf();
$dompdf->loadHtml($linktentinvoice, 'UTF-8');

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'landscape');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream();

?>
```

The result is showing : ا ب ح ر م

However the result has to be: مرحبا

**Comment by bsweeney** [comment]
Dompdf does not currently support the features required to correctly render Arabic script. Please see #712 for more information. We've started working on support (see #2107) but it's not yet ready for release.
