### ISSUE TITLE
Can't get css in PDF

### ISSUE THREAD

**Issue by robertnicjoo** [dompdf/dompdf#2201]
If I load my view in browser it looks like this

![001](https://user-images.githubusercontent.com/8672823/88510948-3412fa80-d00e-11ea-9b36-ccb85fe3166c.png)

But when I add `pdf` function to it, it will look like this

![002](https://user-images.githubusercontent.com/8672823/88511061-645a9900-d00e-11ea-8cf1-5860500b00d5.png)

# Code

```php
public function exportTemplate(Request $request, $id) {
    $templateContent = .......;
    
    // return view('backend.template.pdf', compact('templateContent')); // screenshot #1
    
    $view = View('backend.template.pdf', ['templateContent' => $templateContent]);
    $pdf = \App::make('dompdf.wrapper');
    $pdf->loadHTML($view->render());
    return $pdf->stream(); // screenshot #2
  }
```
`view`

```html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>
    <body>
        {!! $templateContent !!}
    </body>
</html>
```

> Note: My data (including html and css) all are inside `templateContent` variable.

**Any idea?**

[Ref](https://github.com/barryvdh/laravel-dompdf/issues/703)
[Suggested](https://github.com/barryvdh/laravel-dompdf/issues/703#issuecomment-664664299)

**Comment by bsweeney** [comment]
No ideas without seeing a sample of the HTML + CSS in question.

**Comment by hafizSiddiq7675** [comment]
I facing the same issue any help?
