### ISSUE TITLE
Anchor in pdf are not working properly.

### ISSUE THREAD

**Issue by mvdhoek1** [dompdf/dompdf#2202]
Hi,

I'm having trouble with adding anchors to a pdf. When I insert 2 anchors the first one is only working but the second one is not.  Below the anchors:
- <a target="_blank" href="https://www.impactwijzer.nl">Impactwijzer</a>
- <a target="_blank" href="https://www.movisie.nl/publicatie/overzicht-meetinstrumenten-monitoren-sociaal-domein">overzicht van meetinstrumenten en monitoren sociaal domein</a>

I've added the pdf where this occurs

[uitslag-make-a-move-assessment-allesisgezondheid.pdf](https://github.com/dompdf/dompdf/files/4999202/uitslag-make-a-move-assessment-allesisgezondheid.pdf)

**Comment by bsweeney** [comment]
The issue actually looks to be a placement error with the link box. If you move the mouse toward the left side of the page eventually you'll encounter the link box. Looks like it's being placed where it would be if the line weren't center aligned.

Follow #1803 for updates and feel free to add context (e.g. minimal sample HTML + CSS that causes the issue). Testing a render with just a few links in aligned text doesn't seem to do it.
