### ISSUE TITLE
How I can include bootstrap cdn to my blade view?

### ISSUE THREAD

**Issue by juanantoniodamianv** [dompdf/dompdf#2203]
I include the bootstrap cdn from this way:
```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </head>
```

 this above it works in my local environment, but don't in my server (Apache/2.4.10 Debian)

**Comment by bsweeney** [comment]
Have you enable support for remote resources in your options on the server?

**Comment by nickfls** [comment]
@juanantoniodamianv are you able to use bootstrap at all?
for me it always shows the dreaded "No block-level parent found. Not good."

**Comment by juanantoniodamianv** [comment]
> Have you enable support for remote resources in your options on the server?

**Comment by bsweeney** [comment]
@nickfls I'm not seeing that particular error when rendering with bootstrap. Render isn't always great since we don't yet support all the CSS properties used by Bootstrap.
