### ISSUE TITLE
dompdf 0.8.6 is not working with CSS Pseudo-classes before and after

### ISSUE THREAD

**Issue by biru2042** [dompdf/dompdf#2204]
Please Some one help to fix this issue
dompdf 0.8.6 is not working with CSS Pseudo-classes before and after

**Comment by bsweeney** [comment]
We would need to see a sample of the HTML + CSS so we can identify if there's an issue to address.

**Comment by biru2042** [comment]
i use this package with laravel here is css and html coding
<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  
    <link rel="stylesheet" href="{{public_path('/assets/front/css/pdf-gapp.css')}}">

    <title>Subba Foundation</title>


     <style type="text/css">

            @charset "utf-8";

            @font-face {
                font-family: 'Source Sans Pro', sans-serif;
                src: url({{ storage_path('fonts/SourceSansPro-Regular.ttf') }});
                font-weight: 400;
                font-style: normal;
            }

            @font-face {
                font-family: 'Source Sans Pro', sans-serif;
                src:url({{ storage_path('fonts/SourceSansPro-ExtraLight.ttf') }});
                font-weight: 300;
                font-style: normal;
            }

          body {
                margin-left: 60px;
                margin-right: 60px;
                background-color: #fff;
                font-family: 'Source Sans Pro', sans-serif;
                font-weight: 400;
                font-style: normal;
            }

            .app-innerbanner {
                background-color: #f5f5f5;
                min-height: 150px;
            }
            .app-breadcrumb ul li+li:before,
            .app-breadcrumb ul li.active {
                color: #333333;
            }
            /*-- view relation --*/
            /*.view-section {
                padding-top: 0;
                width: 40%;
                background-color: yellow;
            }*/
            .view-entry-header {
                padding: 5px 0;
                border-bottom: 1px solid #dddddd;
                margin-bottom: 30px;
            }
            .hdr-button-wrap {
                margin: 10px 0;
                text-align: right;
            }
            .view-enty-wrap {
                text-align: center;
                margin: 0 auto;
                position: relative;
            }
            .entry-search {
                margin: 10px 0;
            }
            .entry-search .search-form-wrap {
                box-shadow: none;
                padding: 0;
            }
            .view-enty-wrap ul {
                display: inline-block;
            }

            .view-enty-wrap ul,
            .view-enty-wrap ul li {
                list-style: none;
            }
            .view-enty-wrap ul {
                position: relative;
            }
            .view-enty-wrap ul ul {
                position: relative;
                margin: 0;
                padding: 0;
                margin-left: 30px;
            }
            .view-enty-wrap ul li.heilight .v-entry-item {
                border: 3px solid #f7be14;
            }
            .view-enty-wrap ul li.heilight ul:before {
                background-color: #f7be14;
                width: 3px;
            }
            .view-enty-wrap ul li.heilight ul li:before {
                background-color: #f7be14;
                height: 3px;
            }
            .view-enty-wrap ul ul:before {
                content: "";
                position: absolute;
                background-color: #cccccc;
                width: 1px;
                height: 100%;
                left: -20px;
                top: -36px;
                z-index: -1;
            }
            .view-enty-wrap ul ul li {
                position: relative;
            }
            .view-enty-wrap ul ul li:before {
                content: "";
                position: absolute;
                background-color: #cccccc;
                width: 20px;
                height: 1px;
                left: -20px;
                top: 35px;
            }
            .view-enty-wrap ul ul li:last-child:after {
                content: "";
                position: absolute;
                background-color: #ffffff;
                width: 3px;
                height: 100%;
                left: -20px;
                top: 36px;
            }

            .view-enty-wrap li {
                display: block;
                position: relative;
                /* width: 120px; */
            }
            .view-enty-wrap li:before,
            .view-enty-wrap li:after {
                    content: '';
                    position: absolute;
                    
            }
            .view-enty-wrap li:first-child::before, .view-enty-wrap li:last-child:after {
                border: 0 none;
            }
            ul>li ul:before {
                content: "";
                display: block;
                clear: both;
            }
            .v-entry-item {
                width: 200px;
                background-color: #ffffff;
                border:1px solid #cccccc;
                padding: 5px;
                margin: 10px 0;
                border-radius: 5px;
                overflow: hidden;
                display: flex;
                display: -webkit-flex;
                align-items: center;
                text-decoration: none;

            }
            .v-entry-img {
                margin: 0;
                padding: 0;
                width: 60px;
            }
            img {
                width: 60px;
                height: 60px;
                object-fit: cover;
                border-radius: 30px;
            }
            .v-entry-info {
                width: calc(100% - 60px - 10px);
                text-align: left;
                padding-left: 10px;
            }
            .v-entry-info h4 {
                color: #1f9fa2;
                font-family: 'Roboto';
                font-size: 0.875rem;
                margin: 0;
            }
            .sample{
                color:yellow;
            }
            .sample::before{
                content: "Hello kxa";
                color: red;
            }
        </style>   
</head>
<body>

	<section class="section-all view-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-sm-12 col-md-12">

                    <div id="viewentryWrap" class="view-enty-wrap">

                        <div id="entryContainer">
                            <ul>
                                @foreach($memberss as $key => $member)
                                
                                <li>
                                    <a href="javascript:void(0)" class="v-entry-item">
                                         @if($member->photo)
                                        <figure class="v-entry-img">
                                            <img src="{{ $member->photo->getUrl('big_thumb') }}" alt="11">
                                        </figure>
                                        @else
                                        <figure class="v-entry-img">
                                            <img src="{{ asset('public/assets/front/images/team/3.jpg') }}" alt="img1">
                                        </figure>
                                        @endif
                                        <div class="v-entry-info">
                                            <h4>{{ ucwords($member->full_name) }}</h4>
                                        </div>
                                    </a>
                                     
                                    
                                    @if(count($member->childs))
                                        @include('front.user.pdf-child-view',['childs' => $member->childs])
                                    @endif
                                </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    </body>

</html>

**Comment by bsweeney** [comment]
A few things of note here:
1. Dompdf does not yet support flexbox and that will pretty much completely break the render. Follow #971 for updates.
2. You reference an external stylesheet (assets/front/css/pdf-gapp.css), anything relevant in there?
3. This is the PHP that generates the HTML + CSS you're attempting to render, not the actual HTML + CSS. We'll need a sample of the actual in order to debug more. I did a quick edit to see what I could get (see below), but it's not great so getting an actual sample would be helpful.

```
<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  
    <title>Subba Foundation</title>


     <style type="text/css">

            @charset "utf-8";

          body {
                margin-left: 60px;
                margin-right: 60px;
                background-color: #fff;
                font-family: 'Source Sans Pro', sans-serif;
                font-weight: 400;
                font-style: normal;
            }

            .app-innerbanner {
                background-color: #f5f5f5;
                min-height: 150px;
            }
            .app-breadcrumb ul li+li:before,
            .app-breadcrumb ul li.active {
                color: #333333;
            }
            /*-- view relation --*/
            /*.view-section {
                padding-top: 0;
                width: 40%;
                background-color: yellow;
            }*/
            .view-entry-header {
                padding: 5px 0;
                border-bottom: 1px solid #dddddd;
                margin-bottom: 30px;
            }
            .hdr-button-wrap {
                margin: 10px 0;
                text-align: right;
            }
            .view-enty-wrap {
                text-align: center;
                margin: 0 auto;
                position: relative;
            }
            .entry-search {
                margin: 10px 0;
            }
            .entry-search .search-form-wrap {
                box-shadow: none;
                padding: 0;
            }
            .view-enty-wrap ul {
                display: inline-block;
            }

            .view-enty-wrap ul,
            .view-enty-wrap ul li {
                list-style: none;
            }
            .view-enty-wrap ul {
                position: relative;
            }
            .view-enty-wrap ul ul {
                position: relative;
                margin: 0;
                padding: 0;
                margin-left: 30px;
            }
            .view-enty-wrap ul li.heilight .v-entry-item {
                border: 3px solid #f7be14;
            }
            .view-enty-wrap ul li.heilight ul:before {
                background-color: #f7be14;
                width: 3px;
            }
            .view-enty-wrap ul li.heilight ul li:before {
                background-color: #f7be14;
                height: 3px;
            }
            .view-enty-wrap ul ul:before {
                content: "";
                position: absolute;
                background-color: #cccccc;
                width: 1px;
                height: 100%;
                left: -20px;
                top: -36px;
                z-index: -1;
            }
            .view-enty-wrap ul ul li {
                position: relative;
            }
            .view-enty-wrap ul ul li:before {
                content: "";
                position: absolute;
                background-color: #cccccc;
                width: 20px;
                height: 1px;
                left: -20px;
                top: 35px;
            }
            .view-enty-wrap ul ul li:last-child:after {
                content: "";
                position: absolute;
                background-color: #ffffff;
                width: 3px;
                height: 100%;
                left: -20px;
                top: 36px;
            }

            .view-enty-wrap li {
                display: block;
                position: relative;
                /* width: 120px; */
            }
            .view-enty-wrap li:before,
            .view-enty-wrap li:after {
                    content: '';
                    position: absolute;
                    
            }
            .view-enty-wrap li:first-child::before, .view-enty-wrap li:last-child:after {
                border: 0 none;
            }
            ul>li ul:before {
                content: "";
                display: block;
                clear: both;
            }
            .v-entry-item {
                width: 200px;
                background-color: #ffffff;
                border:1px solid #cccccc;
                padding: 5px;
                margin: 10px 0;
                border-radius: 5px;
                overflow: hidden;
                display: inline-block;
                align-items: center;
                text-decoration: none;

            }
            .v-entry-img {
                margin: 0;
                padding: 0;
                width: 60px;
            }
            img {
                width: 60px;
                height: 60px;
                object-fit: cover;
                border-radius: 30px;
            }
            .v-entry-info {
                width: calc(100% - 60px - 10px);
                text-align: left;
                padding-left: 10px;
            }
            .v-entry-info h4 {
                color: #1f9fa2;
                font-family: 'Roboto';
                font-size: 0.875rem;
                margin: 0;
            }
            .sample{
                color:yellow;
            }
            .sample::before{
                content: "Hello kxa";
                color: red;
            }
        </style>   
</head>
<body>

	<section class="section-all view-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-sm-12 col-md-12">

                    <div id="viewentryWrap" class="view-enty-wrap">

                        <div id="entryContainer">
                            <ul>
                                <li>
                                    <a href="javascript:void(0)" class="v-entry-item">
                                        <figure class="v-entry-img">
                                            <img src="https://placekitten.com/100/50" alt="img1">
                                        </figure>
                                        <div class="v-entry-info">
                                            <h4>Dompdf</h4>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    </body>

</html>
```

**Comment by KeremArdicli** [comment]
Hi everybody. I actually have the same problem. Though it is working fine in localhost (Apache, Php 8.1.17), but not working on production (Microsoft IIS, PHP 8.1.19). here is the code I am rendering:

`<html lang="tr">

<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <style>
        @page {
            margin: 0 auto;
        }

        img.bg-image {
            position: fixed;
            width: 210mm;
            height: 297mm;
            top: 0;
            left: 0;
            margin: 0;
            padding: 0;
            z-index: -1;
        }

        img.logo-image {
            position: absolute;
            top: -70px;
            right: 10px;
            max-width: 150px;
            max-height: 150px;
        }

        .page-break {
            position: fixed;
            top: 100px;
            width: 190mm;
            left: 10mm;
            page-break-after: always;
            font-family: Candara, "barlow", Calibri, sans-serif;
        }

        .page-break:last-child {
            page-break-after: never;
        }

        .baslik {
            text-align: center;
            font-size: 1.5em;
            font-weight: bold;
            color: #3c3c3d;
        }

        .odeme-detay {
            text-align: center;
            font-size: 1.4em;
            padding: 0;
            padding-top: 1rem;
            font-weight: bold;
            color: #c00000;
        }

        .bilgilendirme {
            padding: 6px 4px;
            margin-top: 2rem;
            background-color: #b1b1b1;
            color: #1f1b1b;
            font-size: 14px;
        }

        .bilgiler-tablosu {
            margin-bottom: 1.5rem;
        }

        .bilgiler-tablosu table {
            border-collapse: collapse;
            border-spacing: 2px;
            margin-bottom: 0.5rem;
            font-size: 14px;
        }

        .bilgiler-tablosu td {
            text-align: left;
            border: 1px solid #272727;
            padding: 2px 5px;
        }

        .bilgiler-tablosu td:nth-child(odd) {
            font-size: 14px;
            color: #c00000
        }

        .butce-tablolari table {
            border-collapse: collapse;
            border-spacing: 2px;
            margin-bottom: 0.75rem
        }

        .butce-tablolari thead {
            font-size: 14px;
            background-color: #5d5d5d;
            color: #fff
        }

        .butce-tablolari th {
            text-align: left;
            border-bottom: 1px solid #ffffff;
            border-right: 1px solid #ffffff;
            padding: 2px 5px;
        }

        .butce-tablolari td {
            font-size: 14px;
            text-align: left;
            border-bottom: 1px solid #5d5d5d;
            border-right: 1px solid #5d5d5d;
            padding: 2px 5px;
        }

        .butce-tablolari th:last-child,
        .butce-tablolari td:last-child {
            border-right: none;
        }

        .butce-toplam td {
            font-size: 14px;
            padding: 4px 2px;
            font-weight: bold;
            text-align: right
        }

        .butce-toplam td:nth-child(3n+1) {
            background-color: #5d5d5d;
            color: #ffffff;
        }

        .butce-toplam td:nth-child(3n+2) {
            border: 1px solid #8b8a8a;
        }

        .banka-bilgileri {
            margin-top: 2rem;
        }

        .banka-bilgileri td {
            padding: 2px 4px;
        }

        .banka-bilgileri table td:first-child {
            font-size: 14px;
            background-color: gray;
            color: #ffffff;
            text-align: right;
        }

        .banka-bilgileri table td:nth-child(2n) {
            font-size: 14px;
            color: #000000;
            text-align: left;
            border: 1px solid #000000;
        }

        .banka-bilgileri table tr:first-of-type td {
            text-align: center;
            font-weight: bold
        }
    </style>
</head>

<body>
    <main>
        
        <div class="page-break">
            <div>
                <img class="bg-image" src="./vendor/dompdf/dompdf/lib/res/bg2.png">
            </div>
            <div>
                <img class="logo-image" src="./vendor/dompdf/dompdf/lib/res/En Güncel Versiyon_logo.jpeg">
            </div>
            <h3 class="baslik"><em>Sponsorluk Bütçesi</em></h3>

            <div class="bilgiler-tablosu">
                <table class="tg" width="100%">
                    <tbody>
                        <tr>
                            <td>TALEP EDEN FİRMA</td>
                            <td colspan="3">ödeme günleri ile deneme</td>
                        </tr>
                        <tr>
                            <td width="25%">YETKİLİ KİŞİ</td>
                            <td width="28%">developer</td>
                            <td width="20%">E-POSTA ADRESİ</td>
                            <td width="27%">keremardicli@plazaevent.com.tr</td>
                        </tr>
                        <tr>
                            <td>TELEFON NUMARASI</td>
                            <td>5339138121</td>
                            <td>BÜTÇE TARİHİ</td>
                            <td>2023-06-15</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="butce-tablolari">
                <table width='100%'>
                    <thead>
                        <tr>
                            <th width='30%'>Kayıt Hizmeti</th>
                            <th width='5%'>Adet</th>
                            <th width='12%'>Birim Fiyatı</th>
                            <th width='8%'>KDV</th>
                            <th width='15%'>KDV Hariç Tutar</th>
                            <th width='15%'>KDV Tutarı</th>
                            <th width='15%'>Toplam Tutar</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Dernek Üyesi Hekim</td>
                            <td>1</td>
                            <td>5.000,00₺</td>
                            <td>%18</td>
                            <td>5.000,00₺</td>
                            <td>900,00₺</td>
                            <td>5.900,00₺</td>
                        </tr>
                    </tbody>
                </table>
                <table width='100%'>
                    <thead>
                        <tr>
                            <th width='30%'>Kayıt Hizmeti</th>
                            <th width='5%'>Adet</th>
                            <th width='12%'>Birim Fiyatı</th>
                            <th width='8%'>KDV</th>
                            <th width='15%'>KDV Hariç Tutar</th>
                            <th width='15%'>KDV Tutarı</th>
                            <th width='15%'>Toplam Tutar</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Tek Kişilik Konakalama</td>
                            <td>1</td>
                            <td>7.500,00₺</td>
                            <td>%8</td>
                            <td>7.500,00₺</td>
                            <td>600,00₺</td>
                            <td>8.100,00₺</td>
                        </tr>
                    </tbody>
                </table>
                <table width='100%'>
                    <thead>
                        <tr>
                            <th width='30%'>Kayıt Hizmeti</th>
                            <th width='5%'>Adet</th>
                            <th width='12%'>Birim Fiyatı</th>
                            <th width='8%'>KDV</th>
                            <th width='15%'>KDV Hariç Tutar</th>
                            <th width='15%'>KDV Tutarı</th>
                            <th width='15%'>Toplam Tutar</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Tek Yön</td>
                            <td>1</td>
                            <td>75,00€</td>
                            <td>%18</td>
                            <td>75,00€</td>
                            <td>13,50€</td>
                            <td>88,50€</td>
                        </tr>
                    </tbody>
                </table>
                <table width='100%'>
                    <thead>
                        <tr>
                            <th width='30%'>Kayıt Hizmeti</th>
                            <th width='5%'>Adet</th>
                            <th width='12%'>Birim Fiyatı</th>
                            <th width='8%'>KDV</th>
                            <th width='15%'>KDV Hariç Tutar</th>
                            <th width='15%'>KDV Tutarı</th>
                            <th width='15%'>Toplam Tutar</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Standa Alanı (6m2)</td>
                            <td>1</td>
                            <td>25.000,00₺</td>
                            <td>%18</td>
                            <td>25.000,00₺</td>
                            <td>4.500,00₺</td>
                            <td>29.500,00₺</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <h1 class="odeme-detay"><em>Ödeme Detayları</em></h1>
            <div class="butce-toplam">
                <table width="100%">
                    <tbody>
                        <tr>
                            <td width="25%">Toplam Tutar TL</td>
                            <td width="18%">37.500,00</td>
                            <td width="17%"></td>
                            <td width="25%">Toplam Tutar EUR</td>
                            <td width="18%">75,00</td>
                        </tr>
                        <tr>
                            <td>Toplam KDV Tutarı TL</td>
                            <td>6.000,00</td>
                            <td></td>
                            <td>Toplam KDV Tutarı EUR</td>
                            <td>13,50</td>
                        </tr>
                        <tr>
                            <td>Genel Toplam Tutar TL</td>
                            <td>43.500,00</td>
                            <td></td>
                            <td>Genel Toplam Tutar EUR</td>
                            <td>88,50</td>
                        </tr>
                        <tr>
                            <td>Yapılan Ödeme TL</td>
                            <td>0,00</td>
                            <td></td>
                            <td>Yapılan Ödeme EUR</td>
                            <td>0,00</td>
                        </tr>
                        <tr>
                            <td style="background-color: #e59696; color: #000000;">Kalan Ödeme TL</td>
                            <td style="color: #9d2c2c;">43.500,00</td>
                            <td></td>
                            <td style="background-color: #e59696; color: #000000;">Kalan Ödeme EUR</td>
                            <td style="color: #9d2c2c;">88,50</td>
                        </tr>
                    </tbody>
                </table>
                <span><em>*** EURO yapılan ödemelerde, ödemenin yapıldığı güne ait olan merkez bankası efektif satış
                        kuru baz alınır!</em></span>
            </div>
        </div>
        

        
        <div class="page-break">
            <div>
                <img class="bg-image" src="./vendor/dompdf/dompdf/lib/res/bg2.png">
            </div>
            <div>
                <img class="logo-image" src="./vendor/dompdf/dompdf/lib/res/En Güncel Versiyon_logo.jpeg">F
            </div>


            <div class="bilgilendirme">
                <span><em><strong>Bilgilendirme:</strong></em><br></span>
                <span>ödeme günleri ekleme testi</span>
            </div>

            <div class="banka-bilgileri">
                <table width="100%">
                    <tbody>
                        <tr>
                            <td colspan="2" align="center">BANKA HESAP BİLGİLERİ</td>
                        </tr>
                        <tr>
                            <td width="40%">Banka Adı</td>
                            <td width="60%">HALK BANKASI</td>
                        </tr>
                        <tr>
                            <td>Şube Adı ve Kodu</td>
                            <td> İZMİR YOLU SANAYİ ŞUBE - 1307</td>
                        </tr>
                        <tr>
                            <td>Hesap Adı</td>
                            <td>PLAZA EVENT KONGRE ORGANİZASYON TUR. SAN. VE TİC. AŞ.</td>
                        </tr>
                        <tr>
                            <td>IBAN (TL)</td>
                            <td>TR78 0001 2001 3070 0010 1009 18</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        
    </main>
</body>

</html>`

**Comment by bsweeney** [comment]
@KeremArdicli I don't see any pseudo-classes in your sample. You should [start a new discussion](https://github.com/dompdf/dompdf/discussions/new/choose) to try and figure out whether there is a bug to address or just a configuration issue.

**Comment by bsweeney** [comment]
ah, yes, sorry ... I missed that when I was looking over your sample
