### ISSUE TITLE
Extra Spacing in Footer

### ISSUE THREAD

**Issue by remanbala** [dompdf/dompdf#2207]
Pdf has extra spacing at the bottom of the page. How to remove it?

**Comment by bsweeney** [comment]
Would need to see a sample (HTML + CSS plus the PDF output) to know exactly what you mean.

**Comment by bsweeney** [comment]
I got your out-of-band query. So, Dompdf generates a document at a specific size. If you want to resize the document height based on the amount of content you would have to know the height of the content in advance. Dompdf doesn't currently have a way to do this as-is, but you can work with the process to generate what you need by rendering the document twice. See #1524 for some sample code.
