### ISSUE TITLE
 Image not Displaying in live server.

### ISSUE THREAD

**Issue by Vinya007** [dompdf/dompdf#2211]
Uploaded image I can find file in storage and also i seen image in localhost.
But not able seen image on live server.

**Screenshots**
![with_image](https://user-images.githubusercontent.com/45792827/90375185-39ee7f80-e092-11ea-8acd-ae58a7511c9a.png)
![with_out_image](https://user-images.githubusercontent.com/45792827/90375188-3b1fac80-e092-11ea-9ca9-115b14acf574.png)

**Comment by bsweeney** [comment]
We'd need more information. What is the HTML + CSS? Does Dompdf have read/write access to the temp directory defined by the options? Are you using ImageMagick?

**Comment by Vinya007** [comment]
Yes Dompdf has access of temp directory,
No i'm not using ImageMagick ;
I removed ImageMagick from local after this image is showing,


$logo i used here
1. public_path()
2. storage_path()
3. full url of image.

But not able seen image on live server.

Here is my HTML + CSS;

```html
<!DOCTYPE html>
<html>

<head>
    <title>Invoice</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <style type="text/css">
        /* -- Base -- */
        body {
            font-family: "DejaVu Sans";
        }

        html {
            margin: 0px;
            padding: 0px;
            margin-top: 50px;
        }

        .text-center {
            text-align: center
        }

        /* -- Header -- */

        

        .header-container {
            position: absolute;
            width: 100%;
            height: 90px;
            left: 0px;
            top: -50px;
        }

        .header-logo {
            height: 50px;
            margin-top: 20px;
            text-transform: capitalize;
            color: #817AE3;
        }

        
    </style>
</head>

<body>
    <div class="header-container">
        <table width="100%">
            <tr>
                <td class="text-center">
                        <img class="header-logo" src="{{ $logo }}" />
                </td>
            </tr>
        </table>
    </div>
</body>

</html>
```

**Comment by Vinya007** [comment]
I used both relative path and fully qualified ,

With the below code i get "Image not found or type unknown".
```php

view()->share([
      'logo' => $logo,
]);

$pdf = PDF::setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true])->loadView('app.pdf.invoice.');
        
return $pdf->stream();
```
With the below code I got some png image as black and whit, and some of other png, jpg, etc
not visible.
```php

view()->share([
       'logo' => $logo,
]);

$pdf = PDF::setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true])->loadView('app.pdf.invoice');
        $pdf = $pdf->getDomPDF()->setHttpContext(
            stream_context_create([
                'ssl' => [
                    'allow_self_signed'=> true,
                    'verify_peer' => false,
                    'verify_peer_name' => false,
                ]
            ])
        );  
return $pdf->stream();
```

**Comment by bsweeney** [comment]
If you get no image then it's possible either the path is incorrect based on the base HREF of the document. You might also need to confirm that Dompdf has access to the temp directory specified via options, by default the system temp directory.

As for images rendered but not appearing correctly that sounds like an issue we've noted with ImageMagick transparency processing. Confirm your server doesn't have the extension enabled. JPG images are placed without additional processing so that's the easiest format to work out path issues with.
