### ISSUE TITLE
Images processed by ImageMagic are rendered incorrectly due to changes in transparency functionality

### ISSUE THREAD

**Issue by angel-luis** [dompdf/dompdf#2212]
Hi,

I've been using the library about one year without any problem. After two weeks ago, suddenly stopped to work. I don't know the cause. 

I've upgraded to the latest version, and also upgraded the PHP version of the server to 7.1. The same problem keeps happening.

Basically my program is:
- User generates a image (data/png64)
- That image is included into a HTML
- That HTML is converted to PDF
- The PDF is sent via email

Current code:

```
 require_once '../dompdf/autoload.inc.php';
 use Dompdf\Dompdf;
 
 $dompdf = new Dompdf();
 
 $dompdf->loadHtml('
 <html>
 <head>
   <style>html { margin: 0; padding: 0; } img { width: 21cm; height: 29.7cm; }</style>
 </head>
 <body>'
   . $image .
   '</body>
</html>');
 
$dompdf->setPaper('A4', 'portrait');
 
$dompdf->render();
 
$pdf_gen = $dompdf->output();
```

Expected (I've blurred text and images for privacy):
![2020-08-17_12h31_45](https://user-images.githubusercontent.com/17672548/90387147-f261f680-e085-11ea-894f-2c51087b8e81.png)

Output:
![2020-08-17_12h32_25](https://user-images.githubusercontent.com/17672548/90387159-f7bf4100-e085-11ea-84e7-5960a0286c78.png)

All requirements are activated (gd, imagegick, dom, mbstring...).

I've checked the image (in format data/png64) and it's well rendered if it's included as email body without dompdf (for discard external issues).

Thanks in advance.

**Comment by bsweeney** [comment]
This sounds like an issue with the version of ImageMagick. Are you able to test out with the change introduced in #2087?

**Comment by angel-luis** [comment]
It seems that my current provider (Hostinger) has updated the ImageMagick extension without consulting it previously. 

Now I'm using the release 0.8.3 because I need the PHP 7.0 compatibility. So I'll try either downgrade the ImageMagick version or convert the image to jpg.

**Comment by kryptus36** [comment]
I'm experiencing the same issue. I tried multiple versions of image magick and I can say fairly confidently it is something introduced in 7.0.Running 6.9.11.22 works, 7.0.10.22 does not. These are versions from Gentoo's portage tree.

**Comment by bsweeney** [comment]
@kryptus36 version 7 changed some things about transparency handling. Earlier I mistakenly thought that the fix we introduced has already been released, but that's not the case. It'll be in the 0.8.6 release which is coming soon.

**Comment by bsweeney** [comment]
If anyone is able to confirm that the code in the develop branch addresses the issue that'd be awesome since OP had to revert to an older release.
