### ISSUE TITLE
Anchor Links + Explicit Page Breaks

### ISSUE THREAD

**Issue by rolandoscott** [dompdf/dompdf#2213]
Thanks for making this great tool..

So I'm able to create anchor links to my document, and they work just fine..

I'm also able to add css to do explicit page breaks to break up my content in new pages/sections.. that works fine as well..

The issue is when I combine both of these. The anchor links point to where the section would have been if it were not for the page break css.. I really need both in order to get the document to export how I want it to..

**Comment by bsweeney** [comment]
Do you have sample HTML + CSS exhibiting the issue?
