### ISSUE TITLE
stylesheet.cls.php error

### ISSUE THREAD

**Issue by EstopaceMA** [dompdf/dompdf#2216]
I'm having this error guys, can anyone help me, I'm using codeigniter and the version of DOM_PDF there was **DOMPDF 0.6.0 beta 3**

![image](https://user-images.githubusercontent.com/37571727/91153508-e368ed00-e6f2-11ea-9174-eaf68e8690a9.png)

**Comment by bsweeney** [comment]
You'll need to upgrade to a newer version of Dompdf. Version 0.8.3 is the last version to support older versions of PHP (5.4 and up). Use the latest if you have PHP 7.1 or higher: https://github.com/dompdf/dompdf/releases

**Comment by EstopaceMA** [comment]
@bsweeney, it is okay if I upgrade DOM_PDF to a newer version? because our server PHP version is 5.5.9 and my local is 7.2?

**Comment by bsweeney** [comment]
So long as you use version 0.8.3 or earlier you should be OK. Starting with 0.8.4 we started using features specific to PHP 7.1.

**Comment by EstopaceMA** [comment]
Thanks @bsweeney , btw Do you know how to update the library DOM_PDF on code igniter?

**Comment by bsweeney** [comment]
Sorry, I do not. There's a document in the wiki somebody in the community put together that might help.
https://github.com/dompdf/dompdf/wiki/Using-Dompdf-in-CodeIgniter-3.x
