### ISSUE TITLE
SVG Gradient in IMG tag

### ISSUE THREAD

**Issue by ChrisAdels** [dompdf/dompdf#2221]
First of all, thank you very much for the tool.

I would like to include SVGs using an IMG tag. That works so far, only gradients do not appear. In the browser etc. the gradient is displayed correctly in the IMG tag. I tested multiple SVGs. Thanks

**Comment by bsweeney** [comment]
SVG rendering is managed by php-svg-lib. There appears to be an existing issue for the lack of gradient support (PhenX/php-svg-lib#16).

FYI, Dompdf itself also does not currently support gradients (#1912).
