### ISSUE TITLE
The :nth-last-child(N) selector not working

### ISSUE THREAD

**Issue by renancr176** [dompdf/dompdf#2222]
The **:nth-last-child(N)** selector is working like **:nth-child(N)**

**Comment by bsweeney** [comment]
Do you have a sample? This was an issue prior to 0.8.0 but I believe is parsing correctly now.

**Comment by renancr176** [comment]
The link below is the example, the commented css at line between 44 and 54 is't working, it should removes non needed last cut marks as shown below.

https://github.com/renancr176/SuaFigurinha/blob/master/resources/views/pdf/album-figures-grid.blade.php

`<html lang="pt-BR"><head>
    <style>
        @font-face {font-family: 'Rage Italic'; src: url('/files/fonts/rage-italic.ttf');}

        @page
        {
            size: 330.00mm 480.00mm;
        }

        html,
        body
        {
            margin: 0px;
            padding: 0px;
            width: 330.00mm;
            height: 480.00mm;
        }

        table.page
        {
            padding: 0px;
            margin: auto;
            page-break-after: always;
            border-spacing: 0px;
        }

        table.page:last-child
        {
            page-break-after: avoid;
        }

        .cut-horizontal-mark
        {
            border-right: 1px solid black;
        }

        .cut-vertical-mark
        {
            border-bottom: 1px solid black;
        }

        table.page tr:nth-child(2) td:nth-child(8),
        table.page tr:nth-last-child(2) td:nth-child(7)
        {
            border-right: none;
        }

        table.page tr:nth-last-child(3) .cut-vertical-mark:first-child,
        table.page tr:nth-last-child(3) .cut-vertical-mark:last-child
        {
            border-bottom: none;
        }

        table.page.figures-grid td.border-corner,
        table.page.figures-grid td.border-horizontal,
        table.page.figures-grid td.border-vertical,
        table.page.figures-grid td.figure-container
        {
            background-color: #ECBEB3;
        }

        .border-horizontal
        {
            height: 3.50mm;
        }

        .border-vertical
        {
            width: 3.50mm;
        }

        table.page.figures-grid td.figure-container
        {
            text-align: center;
            padding: 1.50mm;
        }

        table.page.figures-grid-bg td.figure-container
        {
            position: relative;
            text-align: center;
            padding: 1.50mm;
        }

        table.page.figures-grid-bg .figure-bg-num
        {
            position: absolute;
            padding: 0px;
            margin: 0px;
            color: #F5874F;
        }

        .space
        {
            margin-left: 8px;
        }
    </style>
</head>
<body>
        <table class="page figures-grid">
        <tbody>
            <tr>
                <td>&nbsp;</td>
                <td colspan="8">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td rowspan="10">&nbsp;</td>
                <td style="width: 5mm; height: 5mm;">&nbsp;</td>
                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                <td style="width: 5mm; height: 5mm;">&nbsp;</td>
                <td rowspan="10">&nbsp;</td>
            </tr>
            <tr>
                <td class="cut-vertical-mark">&nbsp;</td>
                <td class="border-corner">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-corner">&nbsp;</td>
                <td class="cut-vertical-mark">&nbsp;</td>
            </tr>
                        <tr>
                <td class="cut-vertical-mark">&nbsp;</td>
                <td class="border-vertical">&nbsp;</td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-1.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-2.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-3.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-4.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="border-vertical">&nbsp;</td>
                <td class="cut-vertical-mark">&nbsp;</td>
            </tr>
                        <tr>
                <td class="cut-vertical-mark">&nbsp;</td>
                <td class="border-vertical">&nbsp;</td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-5.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-6.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-7.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-8.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="border-vertical">&nbsp;</td>
                <td class="cut-vertical-mark">&nbsp;</td>
            </tr>
                        <tr>
                <td class="cut-vertical-mark">&nbsp;</td>
                <td class="border-vertical">&nbsp;</td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-9.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-10.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-11.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-12.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="border-vertical">&nbsp;</td>
                <td class="cut-vertical-mark">&nbsp;</td>
            </tr>
                        <tr>
                <td class="cut-vertical-mark">&nbsp;</td>
                <td class="border-vertical">&nbsp;</td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-13.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-14.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-15.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-16.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="border-vertical">&nbsp;</td>
                <td class="cut-vertical-mark">&nbsp;</td>
            </tr>
                        <tr>
                <td class="cut-vertical-mark">&nbsp;</td>
                <td class="border-vertical">&nbsp;</td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-17.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-18.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-19.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="figure-container">
                    <img src="../storage/app/album_orders/e2153a8e-ec57-11ea-932e-6c2b59523a59/figurinha-20.png" style="width: 72.00mm;
                    height: 72.00mm;">
                </td>
                                <td class="border-vertical">&nbsp;</td>
                <td class="cut-vertical-mark">&nbsp;</td>
            </tr>
                        <tr>
                <td class="cut-vertical-mark">&nbsp;</td>
                <td class="border-corner">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-corner">&nbsp;</td>
                <td class="cut-vertical-mark">&nbsp;</td>
            </tr>
            <tr>
                <td style="width: 5mm; height: 5mm;">&nbsp;</td>
                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                <td style="width: 5mm; height: 5mm;">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="8">&nbsp;</td>
            </tr>
        </tbody>
    </table>

    <table class="page figures-grid-bg">
        <tbody>
            <tr>
                <td>&nbsp;</td>
                <td colspan="8">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td rowspan="10">&nbsp;</td>
                <td style="width: 5mm; height: 5mm;">&nbsp;</td>
                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                <td style="width: 5mm; height: 5mm;">&nbsp;</td>
                <td rowspan="10">&nbsp;</td>
            </tr>
            <tr>
                <td class="cut-vertical-mark">&nbsp;</td>
                <td class="border-corner">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-corner">&nbsp;</td>
                <td class="cut-vertical-mark">&nbsp;</td>
            </tr>
                        <tr>
                <td class="cut-vertical-mark">&nbsp;</td>
                <td class="border-vertical">&nbsp;</td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    04
                                            </p>
                </td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    03
                                            </p>
                </td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    02
                                            </p>
                </td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    <span class="space">01</span>
                                            </p>
                </td>
                                <td class="border-vertical">&nbsp;</td>
                <td class="cut-vertical-mark">&nbsp;</td>
            </tr>
                        <tr>
                <td class="cut-vertical-mark">&nbsp;</td>
                <td class="border-vertical">&nbsp;</td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    08
                                            </p>
                </td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    07
                                            </p>
                </td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    06
                                            </p>
                </td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    05
                                            </p>
                </td>
                                <td class="border-vertical">&nbsp;</td>
                <td class="cut-vertical-mark">&nbsp;</td>
            </tr>
                        <tr>
                <td class="cut-vertical-mark">&nbsp;</td>
                <td class="border-vertical">&nbsp;</td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    <span class="space">12</span>
                                            </p>
                </td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    <span class="space">11</span>
                                            </p>
                </td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    <span class="space">10</span>
                                            </p>
                </td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    09
                                            </p>
                </td>
                                <td class="border-vertical">&nbsp;</td>
                <td class="cut-vertical-mark">&nbsp;</td>
            </tr>
                        <tr>
                <td class="cut-vertical-mark">&nbsp;</td>
                <td class="border-vertical">&nbsp;</td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    <span class="space">16</span>
                                            </p>
                </td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    <span class="space">15</span>
                                            </p>
                </td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    <span class="space">14</span>
                                            </p>
                </td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    <span class="space">13</span>
                                            </p>
                </td>
                                <td class="border-vertical">&nbsp;</td>
                <td class="cut-vertical-mark">&nbsp;</td>
            </tr>
                        <tr>
                <td class="cut-vertical-mark">&nbsp;</td>
                <td class="border-vertical">&nbsp;</td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    20
                                            </p>
                </td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    <span class="space">19</span>
                                            </p>
                </td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    <span class="space">18</span>
                                            </p>
                </td>
                                <td class="figure-container">
                    <img src="/files/images/albuns/frames/default.png" style="width: 72.00mm;
                    height: 72.00mm;">
                    <p class="figure-bg-num" style="top: 10.00mm;
                    left: 27.00mm;
                    font-size: 45.00pt;
                    font-family: 'Rage Italic';">
                                                    <span class="space">17</span>
                                            </p>
                </td>
                                <td class="border-vertical">&nbsp;</td>
                <td class="cut-vertical-mark">&nbsp;</td>
            </tr>
                        <tr>
                <td class="cut-vertical-mark">&nbsp;</td>
                <td class="border-corner">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-horizontal">&nbsp;</td>
                                <td class="border-corner">&nbsp;</td>
                <td class="cut-vertical-mark">&nbsp;</td>
            </tr>
            <tr>
                <td style="width: 5mm; height: 5mm;">&nbsp;</td>
                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                                <td class="cut-horizontal-mark">&nbsp;</td>
                <td style="width: 5mm; height: 5mm;">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="8">&nbsp;</td>
            </tr>
        </tbody>
    </table>
    

</body></html>`

**Comment by bsweeney** [comment]
OK yeah I'm seeing the issue. So, generally support for the pseudo class is functional but something about your specific styling is breaking things. Will need to see if we can narrow down the issue since this is a somewhat complex document.

I do see that using class selectors with the nth-* pseudo class appears to be broken. Here's a minimal example of that problem.

```
<style>
.colorme:nth-child(1) {
  background-color: green;
}
</style>


<p class="colorme">green</p>
<p class="colorme">not green</p>
<p class="colorme">not green</p>
<p class="colorme">not green</p>
```

This could be implicated in the issue you're seeing with your render.

**Comment by renancr176** [comment]
Many thanks, but in my projet it isn't a problem because it's just a cut mark and it will be cutted off any way, I hope this reporte help to improve this great framework.
😁

**Comment by katsar0v** [comment]
I can confirm this is not working even in 1.1.1 
My selector:
```
table:nth-child(2n) td::before {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            height: 1;
            content: "";
            background: red;
        }
```
