### ISSUE TITLE
dompdf will not print second page

### ISSUE THREAD

**Issue by webchambers** [dompdf/dompdf#2225]
I have a sample shop that generates a receipt on products purchased. When a user checks out it generates a receipt as a pdf file using dompdf.

If i select a few products and generate a pdf file its ok it shows the products and total price, however if i choose lots of products, too many to fit on one page then when i generate a pdf it only show the first page the rest of the products and the total price are not displayed on page 2 ?

Here is the bit of the code that generates the pdf

sorry i am not very experienced in this stuff i am trying to learn !

```
$options = new Dompdf\Options();
$options->set('isRemoteEnabled', true);
$dompdf = new Dompdf\Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->render();
$output = $dompdf->output();
$info = file_put_contents("../../files/" . $filepath . $filename, $output);
return array($filename,$filepath);
```

any advice please

**Comment by bsweeney** [comment]
The issue is more likely with the HTML you are trying to render. Do you have sample HTML + CSS that shows the issue?

**Comment by webchambers** [comment]
here is the page code

`<?php
ob_start();
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Receipt</title>
<style>
body{
width: 900px;
font-family: arial, sans-serif;
font-size: 16px;
}
h3 {
margin-top: 0;
color: #000000;
}
h4{
margin-top: 0;
color: #000000;
}
.heading {
border: 2px;
border-bottom-style: solid;
border-bottom-color: #90c4f1;
}
.footer {
position: absolute;
bottom: 10px;
right: 10px;
text-align: right;
font-size: 9px;
color: darkgrey;
}
.company {
color: #008af5;
}
hr {
width: 600px;
margin-left: auto;
margin-right: auto;
height: 2px;
background-color: #3d3d3d;
color:gray;
border: 0 none;
}

#tblproduct-details table {
font-family:Arial, sans-serif;
border-collapse:collapse;
border-spacing: 0;
border-color: #DFDFDF;
}

#tblproduct-details th {
background: #90c4f1;
border: 2px solid #ffffff; /* No more visible border */
border-spacing: 0;
padding: 10px 0 0 0;
}

.desc{
font-size: 16px;
font-family: "arial", "sans-serif";
}

.writing{
font-size: 14px;
font-family: "arial", "sans-serif";
}
.text-right{
text-align: right;
}

.text-center{
text-align: center;
}

.inv-p p{
display: inline-block;
text-align: right;
padding: 0;
margin: 0;
}

.logo-img{
height: 160px;
width: 500px;
}

</style>
<style>
.b {
word-wrap: break-word;
}
</style>
</head>

<body>

<img src="https://invoiceman.co.uk/img/logobw.jpg" style="position:absolute;left:0px;top:20px;z-index:0;">

<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:20px;top:100px;z-index:0;">
<tr>
<td class="writing">Online Shopping At Its Best ! Merchant House, Newcastle Upon Tyne, NE1 1EE</td>
</tr>


</table>

<table width="500px" cellspacing="1" cellpadding="4" style="position:absolute;left:0px;top:170px;z-index:0;">
<tr>
<td width="200px"></td>
<td><H3>Customer Receipt</h3></td>
<td></td>
</tr>


</table>







<table width="400px" cellspacing="1" cellpadding="4" style="position:absolute;left:0px;top:210px;z-index:0;">



    <tr>



        <td width="150px"></td>



        <td><h4>Customer Details</h4></td>



        <td></td>



    </tr>



    



</table>







<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:10px;top:240px;z-index:0;">



    <tr>



                    <td class="writing"><?php echo htmlspecialchars($user["customer_name"]); ?></td>



                    



                </tr>



                  



</table>







<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:10px;top:260px;z-index:0;">



    <tr>



                    <td class="writing"><?php echo htmlspecialchars($user["address1"]);?></td>



                    



                </tr>



                  



</table>







<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:10px;top:280px;z-index:0;">



    <tr>



                    <td class="writing"><?php echo htmlspecialchars($user["address2"]);?></td>



                    



                </tr>



                  



</table>







<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:10px;top:300px;z-index:0;">



    <tr>



                    <td class="writing"><?php echo htmlspecialchars($user["address3"]);?></td>



                    



                </tr>



                  



</table>







<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:10px;top:320px;z-index:0;">



    <tr>



                    <td class="writing"><?php echo htmlspecialchars($user["address4"]);?></td>



                    



                </tr class="writing">



                  



</table>







<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:10px;top:340px;z-index:0;">



    <tr>



                    <td class="writing"><?php echo htmlspecialchars($user["address5"]);?></td>



                    



                </tr>



                  



</table>





<table width="800px" cellspacing="1" cellpadding="4" style="position:absolute;left:0px;top:380px;z-index:0;">



    <tr>



        <td width="800px"></td>

		<?php $date = new DateTime($data['receipt-date']); ?>

        <td class="desc"><h4>Order Date : <?php echo $date->format('d M Y'); ?></h4></td>



        <td></td>



    </tr>



    



</table>









<table width="800px" cellspacing="1" cellpadding="4" style="position:absolute;left:0px;top:420px;z-index:0;">



    <tr>



        <td width="800px"></td>



        <td class="desc"><h4>Order Details : </h4></td>



        <td></td>



    </tr>



    



</table>





<table width="800px" cellspacing="1" cellpadding="4" style="position:absolute;left:400px;top:170px;z-index:0;">



    <tr>



        <td width="800px"></td>



        <td class="desc"><h4>Customer E Mail : </h4></td>



        <td></td>



    </tr>





</table>



<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:410px;top:200px;z-index:0;">



    <tr>



                    <td class="writing"><?php echo htmlspecialchars($user['customer_email']); ?></td>



                    



                </tr>



                  



</table>



<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:410px;top:230px;z-index:0;">



    <tr>



                    <td class="writing">Multi Shop UK is a sister company to :<br><br>Build And Fix<br> Clean And Handy<br>Universal Motor Spares<br> Power Tools Pro<br> E Zone Health & Safety<br> Universal Motor Spares<br> Music Mania</td>



                    



                </tr>



                  



</table>

















            <table cellspacing="0" width="750px" cellpadding="4" style="position:absolute;left:10px;top:470px;z-index:0;">



                <tr>



                    <th><p style="position:absolute;left:0px;top:-30px;">Description</p></th>



                    <th><p style="position:absolute;left:570px;top:-30px;">Amount</p></th>



                </tr>

				

				<?php foreach($_SESSION['cart']['products'] as $product) { ?>

                <tr>



                    <td class="writing b"><?php echo $product['quantity'] ?> x <?php echo $product['product_name'];?></td>



                    <td class="writing b"><?php echo number_format($product['product_price'],2);?></td>



                </tr>

				<?php } ?>







<tr><td></td></tr>



<tr><td></td></tr>











<tr>



        <td width="475px" class="text-right">



            <strong>Total Amount Paid</strong>



        </td>



        



        <td width="150px">



            <strong>

                &pound; <?php echo number_format($_SESSION['cart']['total_price'],2); ?><br>



            </strong> </td>



        



    </tr>











            </table>



       



    



























            



















</body>



</html>



<?php



 $html = ob_get_clean();



?>`

**Comment by webchambers** [comment]
Here is the page coding...

`<?php



ob_start();



?>



<!DOCTYPE html>



<html lang="en">



<head>



    <meta charset="UTF-8">



<title>Receipt</title>



    <style>



        body{



            width: 900px;



            font-family: arial, sans-serif;



            font-size: 16px;



        }







        h3 {



            margin-top: 0;



            color: #000000;



        }



        h4{



            margin-top: 0;



            color: #000000;







        }







        .heading {



            border: 2px;



            border-bottom-style: solid;



            border-bottom-color: #90c4f1;



        }







        .footer {



            position: absolute;



            bottom: 10px;



            right: 10px;



            text-align: right;



            font-size: 9px;



            color: darkgrey;



        }







        .company {



            color: #008af5;



        }



        hr {



            width: 600px;



            margin-left: auto;



            margin-right: auto;



            height: 2px;



            background-color: #3d3d3d;



            color:gray;



            border: 0 none;



        }



        #tblproduct-details table {



            font-family:Arial, sans-serif;



            border-collapse:collapse;



            border-spacing: 0;



            border-color: #DFDFDF;



        }







        #tblproduct-details th {



            background: #90c4f1;



            border: 2px solid #ffffff; /* No more visible border */



            border-spacing: 0;



            padding: 10px 0 0 0;



        }



        .desc{



                        font-size: 16px;



            font-family: "arial", "sans-serif";



        }







	.writing{



                        font-size: 14px;



            font-family: "arial", "sans-serif";



        }







        .text-right{



            text-align: right;



        }



        .text-center{



            text-align: center;



        }



        .inv-p p{



            display: inline-block;



            text-align: right;



            padding: 0;



            margin: 0;



        }



        .logo-img{



        height: 160px;



        width: 500px;



        }







    </style>











<style>



.b {



  word-wrap: break-word;



}



</style>











</head>



<body>



<img src="https://invoiceman.co.uk/img/logobw.jpg" style="position:absolute;left:0px;top:20px;z-index:0;">



<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:20px;top:100px;z-index:0;">



    <tr>



                    <td class="writing">Online Shopping At Its Best ! Merchant House, Newcastle Upon Tyne, NE1 1EE</td>



                    



                </tr>



                  



</table>









<table width="500px" cellspacing="1" cellpadding="4" style="position:absolute;left:0px;top:170px;z-index:0;">



    <tr>



        <td width="200px"></td>



        <td><H3>Customer Receipt</h3></td>



        <td></td>



    </tr>



    



</table>







<table width="400px" cellspacing="1" cellpadding="4" style="position:absolute;left:0px;top:210px;z-index:0;">



    <tr>



        <td width="150px"></td>



        <td><h4>Customer Details</h4></td>



        <td></td>



    </tr>



    



</table>







<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:10px;top:240px;z-index:0;">



    <tr>



                    <td class="writing"><?php echo htmlspecialchars($user["customer_name"]); ?></td>



                    



                </tr>



                  



</table>







<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:10px;top:260px;z-index:0;">



    <tr>



                    <td class="writing"><?php echo htmlspecialchars($user["address1"]);?></td>



                    



                </tr>



                  



</table>







<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:10px;top:280px;z-index:0;">



    <tr>



                    <td class="writing"><?php echo htmlspecialchars($user["address2"]);?></td>



                    



                </tr>



                  



</table>







<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:10px;top:300px;z-index:0;">



    <tr>



                    <td class="writing"><?php echo htmlspecialchars($user["address3"]);?></td>



                    



                </tr>



                  



</table>







<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:10px;top:320px;z-index:0;">



    <tr>



                    <td class="writing"><?php echo htmlspecialchars($user["address4"]);?></td>



                    



                </tr class="writing">



                  



</table>







<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:10px;top:340px;z-index:0;">



    <tr>



                    <td class="writing"><?php echo htmlspecialchars($user["address5"]);?></td>



                    



                </tr>



                  



</table>





<table width="800px" cellspacing="1" cellpadding="4" style="position:absolute;left:0px;top:380px;z-index:0;">



    <tr>



        <td width="800px"></td>

		<?php $date = new DateTime($data['receipt-date']); ?>

        <td class="desc"><h4>Order Date : <?php echo $date->format('d M Y'); ?></h4></td>



        <td></td>



    </tr>



    



</table>









<table width="800px" cellspacing="1" cellpadding="4" style="position:absolute;left:0px;top:420px;z-index:0;">



    <tr>



        <td width="800px"></td>



        <td class="desc"><h4>Order Details : </h4></td>



        <td></td>



    </tr>



    



</table>





<table width="800px" cellspacing="1" cellpadding="4" style="position:absolute;left:400px;top:170px;z-index:0;">



    <tr>



        <td width="800px"></td>



        <td class="desc"><h4>Customer E Mail : </h4></td>



        <td></td>



    </tr>





</table>



<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:410px;top:200px;z-index:0;">



    <tr>



                    <td class="writing"><?php echo htmlspecialchars($user['customer_email']); ?></td>



                    



                </tr>



                  



</table>



<table width="600px" cellspacing="1" cellpadding="4" style="position:absolute;left:410px;top:230px;z-index:0;">



    <tr>



                    <td class="writing">Multi Shop UK is a sister company to :<br><br>Build And Fix<br> Clean And Handy<br>Universal Motor Spares<br> Power Tools Pro<br> E Zone Health & Safety<br> Universal Motor Spares<br> Music Mania</td>



                    



                </tr>



                  



</table>

















            <table cellspacing="0" width="750px" cellpadding="4" style="position:absolute;left:10px;top:470px;z-index:0;">



                <tr>



                    <th><p style="position:absolute;left:0px;top:-30px;">Description</p></th>



                    <th><p style="position:absolute;left:570px;top:-30px;">Amount</p></th>



                </tr>

				

				<?php foreach($_SESSION['cart']['products'] as $product) { ?>

                <tr>



                    <td class="writing b"><?php echo $product['quantity'] ?> x <?php echo $product['product_name'];?></td>



                    <td class="writing b"><?php echo number_format($product['product_price'],2);?></td>



                </tr>

				<?php } ?>







<tr><td></td></tr>



<tr><td></td></tr>











<tr>



        <td width="475px" class="text-right">



            <strong>Total Amount Paid</strong>



        </td>



        



        <td width="150px">



            <strong>

                &pound; <?php echo number_format($_SESSION['cart']['total_price'],2); ?><br>



            </strong> </td>



        



    </tr>











            </table>



       



    



























            



















</body>



</html>



<?php



 $html = ob_get_clean();



?>`

**Comment by bsweeney** [comment]
Your table is absolutely positioned. Absolutely positioned elements do not page.

**Comment by bsweeney** [comment]
#1138 covers an enhancement for paging absolutely positioned element
