### ISSUE TITLE
0.8.6 doesn't rendering img?!

### ISSUE THREAD

**Issue by djs84** [dompdf/dompdf#2230]
hi,

is there a new setting for pictures?
in the version 0.8.5 everything was generated correctly

**JPG in 0.8.6**
![img086](https://user-images.githubusercontent.com/46485329/92465523-f7bae880-f1ce-11ea-8869-4ce4078b0906.JPG)

**JPG in 0.8.5**
![img085](https://user-images.githubusercontent.com/46485329/92465550-02757d80-f1cf-11ea-8211-f34670a68dcd.JPG)

**my code:**
![code](https://user-images.githubusercontent.com/46485329/92465997-b5de7200-f1cf-11ea-8cc6-4c29bedfb19e.JPG)

thx 4 help

**Comment by bsweeney** [comment]
The new version enforces chroot restrictions for local files per #2152 (additional documentation forthcoming in that issue about the security implications). There a small bit in the [release notes](https://github.com/dompdf/dompdf/releases/tag/v0.8.6) about the change, reproduced here:

> Because of the changes in resource security, some resources that would previously load with the default settings may not longer load. To ensure compatibility with this release ensure the [remote resources can be loaded](https://github.com/dompdf/dompdf/blob/v0.8.6/src/Options.php#L162..L181) and that any local filesystem resources are within the directory specified by the [chroot setting](https://github.com/dompdf/dompdf/blob/v0.8.6/src/Options.php#L46..L61). By default, chroot is set to the Dompdf directory. Information on how to change these settings can be found in the readme section on [setting options](https://github.com/dompdf/dompdf/tree/v0.8.6#setting-options).

We will be working on some tweaks to the setting in relation to #2229.

**Comment by ThomasLandauer** [comment]
Duplicate of https://github.com/dompdf/dompdf/issues/2229
