### ISSUE TITLE
Licenses – LGPL 2.1 vs LGPL 3.0

### ISSUE THREAD

**Issue by hc-sven** [dompdf/dompdf#2231]
The two dependencies `phenx/php-font-lib` and `phenx/php-svg-lib` are licensed under LGPL 3.0 while dompdf itself is LGPL 2.1. I wanted to use dompdf in a project and was told by a lawyer that those two are not compatible. How is it possible for dompdf to use those two and not be a LGPL 3.0 license itself?

**Comment by bsweeney** [comment]
Quick note about licenses:
- Dompdf (currently at version 0.8.6) is licensed under LGPL 2.1: https://github.com/dompdf/dompdf/blob/master/LICENSE.LGPL
- php-font-lib (currently at version 0.5.2) is licensed under LGPL 2.1: https://github.com/PhenX/php-font-lib/blob/0.5.2/LICENSE
- php-svg-lib (currently at version 0.3.3) is licensed under LGPL 3: https://github.com/PhenX/php-svg-lib/blob/v0.3.3/COPYING

IANAL but I would be curious as to the reason your lawyer believe the two licenses are not compatible. The GNU org has a license chart for quick reference and code licensed under LGPL v2.1 does not appear to have any issue _using_ a library licensed under LGPL 3.
https://www.gnu.org/licenses/gpl-faq.html#gpl-compat-matrix

If your lawyer is willing to provide clarification that you can post here that would be helpful.

**Comment by hc-sven** [comment]
Thank you for your reply. Regarding php-font-lib: You are right, the LICENSE file does say 2.1, I hadn't noticed that. I use https://packagist.org/packages/metasyntactical/composer-plugin-license-check to generate a list of the used licenses and there it is listed as 3.0, which seems to come from its composer.json file.

I will ask for clarification.

**Comment by bsweeney** [comment]
Ah, you are correct regarding the license mismatch on php-font-lib. Something to review/correct.

**Comment by hc-sven** [comment]
The lawyer has clarified that it should be compatible, so I will close this here.

**Comment by bsweeney** [comment]
Thanks for the update!
