### ISSUE TITLE
Packaged release is nowhere to be found

### ISSUE THREAD

**Issue by JanisE** [dompdf/dompdf#2235]
> Click the link labeled "dompdf_0-8-6.zip" for the packaged release.

See the "Download Instructions". Such link - to download the packaged release, not auto-generated source code, does not exist anywhere.

**Comment by bsweeney** [comment]
Uh, yeah, sorry. I haven't had a chance to put it together just yet. Will be doing that soon.

**Comment by bsweeney** [comment]
Dompdf 0.8.6 packaged release posted: https://github.com/dompdf/dompdf/releases/download/v0.8.6/dompdf_0-8-6.zip
