### ISSUE TITLE
Yes, another <img src=""> problem :-(

### ISSUE THREAD

**Issue by maije** [dompdf/dompdf#2238]
Dear all,

I've been reading so many topics in this forum related to the same problem. Most of them are linked to server permissions to folder where the images are stored, but I believe it is not my case. I have the base64 code of the image (generated from Javascript from a canvas and sent via AJAX to PHP as a POST variable). Then I use that code in the `<img src ="here the code">` and it is not working at all when streamming the PDF. I checked the base64 code in a plain HTML file to see the code was right, and it is. I also generated the base64 code in https://www.base64-image.de/ and it works exactly the same. I also have created a session variable with the base64 content, same result just in case there is an incompatibility with AJAX. Even I have saved the image to the server as PNG (it is being stored and opens perfectly) and then re-open it again, encode it as base64 and used that code again in the `<img src="...">`. Same result:

![image](https://user-images.githubusercontent.com/39513527/93202493-10894800-f753-11ea-9bfc-db8c594337fe.png)

The PDF is being generated properly but the embedded images. Here it is my relevant portion of code (both using session variable and opening an existing image file in the server and none of them working although both base64 image codes are correct and the same...). 

```
if (isset($_SESSION[thenameofmyvariable...])) {
    $base64Img = str_replace(' ', '+', $_SESSION[thenameofmyvariable...);
    $html .= '<p>INFO: '.$base64Img.'</p>';
    $html .= '<img src ="'. $base64Img.'" width = "10%">';
}
if (file_exists($path)) {
    $html .= "<h1>Chart</h1>";
    $image = file_get_contents($path);
    if ($image !== false){
        $imgStr = 'data:image/png;base64,'.base64_encode($image);
        $html .= $imgStr; 
        $html .= '<img src="'.$imgStr.'" width = "100%">';
    } else {
        $html .= '<h2>It was not possible to recover the chart to be added to the report.</h2>';
    }
    // unlink($path);
} else {
    $html .= "<h1>The chart file was not located in expected path.</h1>";
}
```

And here my last version of object creation with the  options I found could be related in some way, even if I think they should not affect, but just in case:

```
$options = new Options();
$options->set('defaultFont', 'Courier');
$options->set('isRemoteEnabled', TRUE);
$options->set('debugKeepTemp', TRUE);
$options->set('isHtml5ParserEnabled', true);
//$options->set('chroot', '');

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');

$dompdf->render();
$dompdf->stream("report.pdf");

$output = $dompdf->output();
file_put_contents("report.pdf", $output);
```

As you see I am also saving the PDF to the server with no problem, just  in case it was a problem related to the stream function, but that is not the situation. I am so sorry in case I am creating a new  issue which has been already solved, but none of the solutions I found fixed my problem and the issues were already closed (for instance #2230 or #2152 ).

Thank you very much for your appreciated support with this.
Best regards,
Jaime

**Comment by bsweeney** [comment]
I'm not seeing an issue with rendering a base64 image, generally (http://eclecticgeek.com/dompdf/debug.php?identifier=8c89f9d2df5bf76b2072ee086c0cc62c). Do you see any errors logged? What image type is it? Can you post a sample of the actual HTML (with the base64 image) Dompdf is attempting to parse?

**Comment by maije** [comment]
Yes, I can see the image being rendered on a plain html:

![image](https://user-images.githubusercontent.com/39513527/93240774-d6389e80-f784-11ea-8c74-ba4233fde891.png)

And this is the result:

![image](https://user-images.githubusercontent.com/39513527/93240857-f1a3a980-f784-11ea-9de7-ee283c056909.png)

I copied and pasted the code from the console (outputed from Javascript):

![image](https://user-images.githubusercontent.com/39513527/93241176-4810e800-f785-11ea-84f0-4243edf01198.png)

So the code I am sending as base64 seems to be fine, it can be saved as PNG and the image is properly stored and can be seen normally. It is just when I add the tag `<img src="thewholebase64codefotheimage" width="100%">`, render it and stream it, when the images are not being added, either by any of the methods I tried: using the code from Javascript or opening the image from the server with PHP and encoding as base64. 

I have no clue on what could be happening here and there is no error triggered when streaming or storing the PDF file, just when I open the PDF, the images are not there.

Please, do no hesitate to ask me to send you any detail about my pipeline in case you think it would be useful in some way.
Best regards

**Comment by bsweeney** [comment]
Your pipeline looks solid to me. I think I'll need to see the actual HTML Dompdf is working with. Can you put the source that's in the `$html` variable somewhere I can access so I can try loading it. You're also welcome to use my debug helper and post a link here to what you get: http://eclecticgeek.com/dompdf/debug.php

**Comment by Naveen1895** [comment]
@bsweeney @maije I had similar problem. I had set the "enable_remote" as TRUE and changed the "chroot" path to the directory where my file was located. It worked for me. 
@bsweeney Is this how you wanted to specify ??

**Comment by maije** [comment]
Thank you for your support @bsweeney, here it is the test, it looks like it is working smooth and fine in your debugging  tool:

http://eclecticgeek.com/dompdf/debug.php?identifier=be1fd6423834579fc5432c922f239997

Therefore I am afraid you won't be able to help me if we cannot reproduce the issue :-( 

@Naveen1895, thank you for your answer as well, but I cannot see how the path would affect in my case as I am pasting directly the base64 code for the image and it is not working either :-( I also tried the chroot option both with URL and 

Just for completing information, the website is running on a Windows machine and ISS. I am executing this code as a child theme in WordPress. PHP version is 7.2.14 and I just realised the dompdf version I am running is 0.8.5 while the debugger is running 0.8.6 if I am right.. I though I downloaded the stable version from your website, 

I will try the 0.8.6 and will come back to you. Hopefully it will fix the issue :-)

**Comment by GusnaIkhsan** [comment]
hay @maije if your dompdf version 0.8.6 you can downgrade to 0.8.5, latest version maybe not stable. Just now i get same error and downgrade the version. its work for me.

**Comment by maije** [comment]
Unfortunatelly, upgrading to 0.8.6 didn't fix the issue. I also tried the nightly release, just in case, but got the same result. Images are not being rendered in the PDF. I also tried to open the website  into another browser (Firefox) to be sure it was not caused by some previous cached script but got same result again. If I export the $html variable content as an HTML file with PHP, the file is perfectly fine, I can open it and images are properly rendered and displayed, so there has to be something wrong in my configuration when rendering or streaming the PDF file. 

```
[...]
$html .= '</body></html>';
file_put_contents("test.html", $html);
[...]
```

Thank you @GusnaIkhsan for your answer, but I was using 0.8.5 in the first place. Maybe my next test will be based on downgrade to 0.8.4, but I would prefer to support the last release in order to make it more stable (if it is a library problem, because it might be cause by server configuration or dependencies, I really do not know).

**Comment by maije** [comment]
This is the last test I did:

```
<?php

require_once 'someincludesfrommywebsite.php';
require_once 'relativepath/ThirdParties/dompdf/autoload.inc.php';
use Dompdf\Dompdf;
use Dompdf\Options;

$path = './chart.png';

$html = '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Report</title></head>';
$html .= '<body><h1>Report</h1>';

if (isset($_SESSION[thenameofmysessionvariable])) {
    $html .= "<h1>Chart from session var</h1>";
    $html .= '<img src ="'. $_SESSION[thenameofmysessionvariable].'" width = "10%">';
} else {
    $html .= '<h1>Session variable was not properly set</h1>';
}
if (file_exists($path)) {
    $html .= "<h1>Chart from file reading</h1>";
    $image = file_get_contents($path);
    if ($image !== false){
        $imgStr = 'data:image/png;base64,'.base64_encode($image);
        $html .= '<img src="'.$imgStr.'" width = "10%">';
    } else {
        $html .= '<h2>It was not possible to recover the chart to be added to the report.</h2>';
    }
    $html .= "<h1>Chart from server file linking absolute path</h1>";
    $html .= '<img src="'.__DIR__.'/chart.png" width = "10%">';
    
    $url = "https://www.mydomain.com/somefolderstructure/chart.png";
    $html .= "<h1>Chart from server file linking the URL</h1>";
    $html .= '<img src="'.$url.'" width = "10%">';
    // unlink($path);
} else {
    $html .= "<h1>The chart file was not located in the expected path.</h1>";
}

$html .= '</body></html>';
$htmlFileName = "test.html";
file_put_contents($htmlFileName, $html);
sleep(5);
$options = new Options();
$options->set('isRemoteEnabled', TRUE);
$options->set('chroot', __DIR__);

$dompdf = new Dompdf($options);
$dompdf->loadHtmlFile(__DIR__.'/'.$htmlFileName);
$dompdf->render();
$output = $dompdf->output();
file_put_contents("reportFromFile.pdf", $output);
// $dompdf->stream("reportFromFile.pdf");

$dompdf2 = new Dompdf($options);
$dompdf2->loadHtml($html);
$dompdf2->render();
$output = $dompdf2->output();
file_put_contents("reportFromVar.pdf", $output);
$dompdf2->stream("reportFromVar.pdf");
?>
```

This is the result in PDF, exactly the same whatever the source. If it generates the PDF from the $html variable or if it generates the PDF from the test.html file:

![image](https://user-images.githubusercontent.com/39513527/93326911-de8ee900-f819-11ea-9811-e9d1536db654.png)

And this is the generated HTML from the $html variable on my local machine:

![image](https://user-images.githubusercontent.com/39513527/93326976-f8303080-f819-11ea-9e43-70a63a19d3b7.png)

As yo can see, I have tried to add the same image by:

1. Passing the  base64 code as a POST variable
2. Storing the base64 code into a session variable
3. Creating a PNG on the server with that code, reading its value and re-encoding as base64
4. Linking the PNG image as absolute path on the server (obviously is not working outside the server on my local machine)
5. Linking the PNG image as an external URL

None of these images are being rendered properly in the PDF.
Then I tried to stream the PDF files and to store them on the server, with same results using:

1. loadHtml($html)
2. loadHtmlFile($path2thefile)

Regardless the HTML file looks good, the PDF is not rendering it properly. I added some delay in PHP (sleep) to give some time just in case there were some asynchronous tasks which were not finished when the PDF was being generated, but same result again. I also tried 3 diffrerent versions of the library (0.8.5, 0.8.6 and nightly).

Don't know what else I could try, any recommendation will be welcomed, thank you very much!

**Comment by bsweeney** [comment]
Could this be an issue with the temp directory? Maybe Dompdf is unable to read or write the file? PNG images go through extra parsing, you could try a JPG to see if there's any difference in rendering.

For the local file reference, maybe get the realpath to the file and use that for the image source instead of __DIR__/chart.png? You might also try prefixing it with file:// just to hint that it's a local file. Though this doesn't really seem like the issue.

**Comment by maije** [comment]
Dear @bsweeney , thank you for your support again.

I've changed what you suggested and the result has no sense to me at all. Now, the report is working but only for the "absolute server path" option:

![image](https://user-images.githubusercontent.com/39513527/93372359-17e44a80-f854-11ea-9b1a-ba7de0f9c95a.png)

With these codification:
```
$html .= "<h1>Chart from server file linking absolute path</h1>";
$html .= '<img src="'.__DIR__.'/chart.jpg" width = "10%">';
```

I really cannot predict the result of this and not getting any pattern of behaviour :-(

Why the base64 codes are not working? Why suddenly, the option which I believed should not work at all, is working :-S
I used jpeg codification and 1.0 quality... just in case that can trigger some ideas or ring some bells in your mind, because I am completely blind about this issue. Can it be related to asynchronous operations in the background so the result is this unexpected? 

Will try to keep on searching in order to have a deeper understanding of the reasons, but at least, I got the image working  by some method, despite of I have to store it in the server, then link it and finally destroy it (VERY unefficient with disk operations) to get it into the PDF file.

If I can guess why is this happening or it stops working, I will post again, if not, maybe this will help you in some way to detect a hidden issue for further releases or other colleagues stuck in the very same place as I am :-D

Best regards,
Jaime

**Comment by jonathanchris** [comment]
I don't have a whole lot to add here, but can confirm similar problems. I've been trying to load a png from the server path and have been seeing the same results. I was able to roll back to v0.8.5 and the issue was resolved for me. It would seem something in the recent release has broke image loading.

**Comment by jonathanchris** [comment]
So I tracked my issue down to the Cache::resolve_url() method and realized that there is a new (or new to me) option to set the $chroot. In setting this to the directory where I was referencing local images, it fixed my issue. This will not fix the "data" image problem @maije is describing.

**Comment by bsweeney** [comment]
@jonathanchris the chroot option isn't new, but enforcement of it for resource references (images, external stylesheets) was added in 0.8.6. This should not impact base64 encoding so I'll have to keep researching that question.

**Comment by BruAPAHE** [comment]
shit lib

**Comment by bsweeney** [comment]
@BruAPAHE thanks for your intelligent, reasoned, and compassionate support of the develops who work on this project in their free time.

**Comment by maije** [comment]
All my support and thankfulness to the amazing developers working on this project which helped me to achieve what I was trying to get, freely by the way. I do appreciate your very kind support and quick answer to the post. Keep on working this hard and forget about toxic comments. The rest of the community value what you are doing here!

**Comment by bsweeney** [comment]
I appreciate that @maije 😄 

I know the majority of the community is understanding to our limitations and appreciative of the work. I don't usually respond, sorry to let the negativity cloud up this ticket.

![it's cool](https://media.giphy.com/media/KyMienR8eLdoDBGiMz/source.gif)

**Comment by maije** [comment]
No worries and my encouragement! I am sorry I stoped tracking this as I found a way (with you help) to make it work. If I have some more time, I will try to keep on doing tests in order to help you tracking this issue, which probably will rely on some type of server-side problem.  Best!

**Comment by spacedog4** [comment]
Just to document, I was having this problem when I was trying to inject an base64 image to `src`.

To work I needed to prepend `data:image/png;base64,` to start of the base64 because `base64_encode` didn't generated

**Comment by bsweeney** [comment]
@maije are you still having issues with this? Are you able to try out the code in the develop branch to see if any of the recent changes help?

Some thoughts:
- base64 encoded image: could be that white space is causing problems I'd try stripping those out (per #1386)
- session variable file: does this fall under the chroot path?
- have you tried changing the path for the temporary directory (e.g. `$options->set('tempDir', __DIR__);`)
- you're using PNG images, which require some amount of processing to embed in the PDF, can you convert to JPG and try again (also a good test to see if imagick/gmagick are causing problems if in use)
- try enabling warnings, logging is still mostly managed through globals so just call `$_dompdf_show_warnings = true;` to see if anything useful is thrown, you can also do some extra debugging for PNG images using `$options->set('debugPng', true);`
- you've already set debugKeepTemp, were you seeing temp images created in your temporary directory?

**Comment by maije** [comment]
Dear @bsweeney 

so sorry for the late reply, I read it back in December but forgot to reply and then my inbox devoured the email xDD.

I was experiencing some more problems related to CSS styles when exporting my PDF, because no matter what, I was no able to link the CSS file to be processed, even only using color as a CSS attribute. I was running out of time, wasn't sure if it could be caused by WordPress or whatever, so I moved on to javascript and calling the browser "print page" function. To me, it was not the best solution, as the print page gets the user to a new window and the print-to-PDF function can cut graphics in half between two pages, but I had to take a compromise solution in this case. 

Whenever I have some more time or another project involving HTML->PDF export, I will give it a try to the last available release and I am sure it will be working smoothly and, hopefully, I will have control over the server (and avoid WP...) to do more exhaustive tests on it and being a bit more helpful here in case some bug arises :-)

I would like to say that I do appreciate all your efforts and feedback.
My encouragements in these hard corona times.
Peace, health and best wishes,
maije

**Comment by roelofjan-elsinga** [comment]
> Just to document, I was having this problem when I was trying to inject an base64 image to `src`.
> 
> To work I needed to prepend `data:image/png;base64,` to start of the base64 because `base64_encode` didn't generated

This solved this issue for me!

**Comment by danielvanschaik** [comment]
> @maije are you still having issues with this? Are you able to try out the code in the develop branch to see if any of the recent changes help?
> 
> Some thoughts:
> 
> * base64 encoded image: could be that white space is causing problems I'd try stripping those out (per [ White space in data-uri mime type breaks image rendering #1386](https://github.com/dompdf/dompdf/issues/1386))
> * session variable file: does this fall under the chroot path?
> * have you tried changing the path for the temporary directory (e.g. `$options->set('tempDir', __DIR__);`)
> * you're using PNG images, which require some amount of processing to embed in the PDF, can you convert to JPG and try again (also a good test to see if imagick/gmagick are causing problems if in use)
> * try enabling warnings, logging is still mostly managed through globals so just call `$_dompdf_show_warnings = true;` to see if anything useful is thrown, you can also do some extra debugging for PNG images using `$options->set('debugPng', true);`
> * you've already set debugKeepTemp, were you seeing temp images created in your temporary directory?

Setting 
$options->set('tempDir', {{MY ROOT PATH}});
Fixed this for me.

**Comment by granite-carter** [comment]
I unlocked the solution https://lnkr.fun/271c1b3

**Comment by Quendi6** [comment]
Adding `"data://" => ["rules" => []],` to `config/dompdf.php` allowed_protocols:
```
[
  'options'=>[        
    'allowed_protocols' => [
        "data://" => ["rules" => []],
        "file://" => ["rules" => []],
        "http://" => ["rules" => []],
        "https://" => ["rules" => []]
    ],
]
```
That's what solved my problem.

**Comment by edwinvdpol** [comment]
> Adding `"data://" => ["rules" => []],` to `config/dompdf.php` allowed_protocols:
> 
> ```
> [
>   'options'=>[        
>     'allowed_protocols' => [
>         "data://" => ["rules" => []],
>         "file://" => ["rules" => []],
>         "http://" => ["rules" => []],
>         "https://" => ["rules" => []]
>     ],
> ]
> ```
> 
> That's what solved my problem.

This is the solution, thank you!
