### ISSUE TITLE
PHP script hangs when dompdf tries to render

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#224]
_Original author: hellc...@gmail.com (January 17, 2011 09:48:02)_

Our script was working fine until we upgraded to PHP 5.3.4. 

Now it fails when it reaches this line: 

$dompdf-&gt;render(); 

There are no errors and the script just continues waiting and waiting. 

Our php.ini settings remain the same as before the upgrade, and the 
'max_execution_time' and 'memory_limit' directive settings are ample.

Any idea what could be causing this and if there is a solution

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=218_

**Comment by bartosz-grabski** [comment]
I have a similar issue, execution hangs on render (). The strange this is that it works well on my local Mac. When I upload the app to a hosted server, it hangs

**Comment by bsweeney** [comment]
@bartosz-grabski first thing to check is your PHP and/or web server logs (make sure you're set up to use the error log).
