### ISSUE TITLE
Img width/height doesnt work with auto option in 0.8.6

### ISSUE THREAD

**Issue by imasarovic** [dompdf/dompdf#2240]
In 0.8.6 the images with width or height set to auto doesnt render anymore. Min-width/min-height doesnt help as well

I think this has to do something with this fix:
Do not render images with width or height of 0 7ce7afd

**Comment by bsweeney** [comment]
Do you have some sample HTML + CSS. I rendered a document with the following and it was OK:

```
<img src="https://placekitten.com/200/200" style="width: auto; height: auto;" />
```

**Comment by imasarovic** [comment]
In previous Version this was working too
<img src="https://placekitten.com/200/200" height="21" width="auto" />
But you code works on 0.8.6, thanks

**Comment by bsweeney** [comment]
ah, I see ... maybe something is going on with attribute translation. Wonder if this has any relevance to #2228

**Comment by bsweeney** [comment]
Also, just FYI, "auto" isn't strictly an allowable value for the width attribute. Per MDN it "must be an integer without a unit." ([ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-width)). Though we didn't make any changes specific to how that is parsed something obviously changed to affect how it is parsed.

**Comment by bsweeney** [comment]
So, this is a result of 7ce7afd. What has happened all along is that the "auto" height/width attribute is being translated to a style value of "autopx", which then is read out as a height of 0. With the release of 0.8.6 we stopped adding images to the PDF when the width is zero. Previous releases would add the image, and if a length was zero the Cpdf back end would calculate the length based on the image dimensions.

I don't know that we want to change the behavior introduced in 0.8.6, but what we might want to do is tweak the logic somewhere to not read "autopx" as "0" and instead just drop that attribute/style.
