### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by shopx** [dompdf/dompdf#2242]

**Comment by bsweeney** [comment]
Any known incompatibilities at this time? I don't have 8 set up for testing yet.

Didn't see any migration notes on the PHP site yet, but here's a list of breaking changes: https://stitcher.io/blog/new-in-php-8#breaking-changes

**Comment by shopx** [comment]
eg function set_z_index in Style.php:
round($val) gives fatal error when val=auto.
change at least  from
`round($val) != $val && $val !== "auto"`
to
`$val !== "auto" && round($val) != $val`

we tested with this. no fatal error, but scrambled pdf output

**Comment by bsweeney** [comment]
Thank you for that, should help identify similar issues. That probably falls under the TypeError change mentioned in the doc I referenced.

**Comment by MarkBaker** [comment]
```2) PhpOffice\PhpSpreadsheetTests\Functional\StreamTest::testAllWritersCanWriteToStream with data set #6 ('Dompdf')
Required parameter $dompdf follows optional parameter $paper
/home/travis/build/PHPOffice/PhpSpreadsheet/vendor/dompdf/dompdf/src/Adapter/CPDF.php:183
/home/travis/build/PHPOffice/PhpSpreadsheet/vendor/dompdf/dompdf/src/CanvasFactory.php:57
/home/travis/build/PHPOffice/PhpSpreadsheet/vendor/dompdf/dompdf/src/Dompdf.php:300
/home/travis/build/PHPOffice/PhpSpreadsheet/src/PhpSpreadsheet/Writer/Pdf/Dompdf.php:17
/home/travis/build/PHPOffice/PhpSpreadsheet/src/PhpSpreadsheet/Writer/Pdf/Dompdf.php:61
/home/travis/build/PHPOffice/PhpSpreadsheet/tests/PhpSpreadsheetTests/Functional/StreamTest.php:37```

PHP8 is a lot stricter about optional arguments to a method before mandatory arguments

**Comment by fixpunkt** [comment]
We have a few products which depend on Dompdf and are planning our own timeline for achieving PHP 8 support. Because of this, some information about the Dompdf project's plans would be very much appreciated:

* Is there an approximate timeline for achieving PHP 8 support and if so, what does it look like?
* If we wanted to pitch in, what would be the best way to help out?

**Comment by bsweeney** [comment]
I don't have a timeline for completing PHP 8 support at the moment. I had hoped to be further along (or started at least) by now, but things being the way they are ...

If you want to pitch in feel free to do so by doing some work and setting up a pull request. I'm collecting potential issues to address and pull requests to include in (what is currently) the 0.8.7 milestone. Go ahead and set up a pull request against the develop branch and I'll review it.

**Comment by bsweeney** [comment]
I'll start looking at this. If anyone wants to do any work please use the php8-compat branch.

**Comment by bsweeney** [comment]
I did an initial run with PHP 8 through my test bed and the number of required changes we would need to make look to be minimal. It's certainly possible (probable?) I've missed something, so please feel free to post relevant info.

I need to do a bit of analysis of the changes, but after I've done that I'll push to the branch for anyone to review.

**Comment by bsweeney** [comment]
off to a great start 😅 

![Screen Shot 2020-11-13 at 1 19 25 PM](https://user-images.githubusercontent.com/485897/99106891-faf99880-25b2-11eb-88ae-21214d78b430.png)

**Comment by bsweeney** [comment]
I don't know what level of work I was expecting PHP8 compatibility to require but the RFC [Saner string to number comparisons](https://wiki.php.net/rfc/string_to_number_comparison) certainly wasn't something I was expecting. That change is going to require a thorough inspection of Dompdf top to bottom to look for places where we might be comparing a numeric value to "auto" 😭.

**Comment by bsweeney** [comment]
Quick update: I think I have things functional under PHP 8 I'm just trying to analyze some potential outlier cases. Should have the functional code pushed to the branch in the next few days. Anybody have time to do some testing once it's up?

**Comment by zmitic** [comment]
@bsweeney 

> Anybody have time to do some testing once it's up?

I can, already using PHP8 for last month. But have to run dompdf from CLI to force PHP7.4.

**Comment by bsweeney** [comment]
branch php8-compat is ready for testing

**Comment by zmitic** [comment]
@bsweeney I tested this branch and I am happy to say: not a **single** problem found.

Thank you for your work, I don't have to meddle with 2 PHP versions anymore.

**Comment by peterdevpl** [comment]
@bsweeney did you actually run a test suite with PHP 8? :)

I did, and here are some necessary fixes (for example adding PHPUnit 9 support):
https://github.com/peterdevpl/dompdf/commit/2f2f5e1a6141782d5826ae520e10f8cbb1ddc562

**Comment by bsweeney** [comment]
I ran some sample HTML docs I use to check for rendering issues as well as the unit tests bundled with the project. I didn't see any errors when running the unit tests but I'll double-check.

**Comment by peterdevpl** [comment]
@bsweeney please do. I have two issues:
1. If I do `composer install` on a **clean copy of your branch**, it fails: `Root composer.json requires php ^7.1 but your php version (8.0.0) does not satisfy that requirement; phpunit/phpunit[7.5.0, ..., 7.5.20] require php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.`
2. When I create an empty project and do `composer require dompdf/dompdf` with PHP 8, it downloads version 0.8.3 instead of the latest 0.8.6. Perhaps it's because of dependencies.

**Comment by bsweeney** [comment]
Ah, clean install. I hadn't done an install/update via composer. Thanks for the reminder.

**Comment by mralston** [comment]
> 2. When I create an empty project and do `composer require dompdf/dompdf` with PHP 8, it downloads version 0.8.3 instead of the latest 0.8.6. This is because of the `^7.1` constraint that was introduced in 0.8.4 (earlier there was `>=5.4`).

That had me scratching my head for a while earlier!

**Comment by unfulvio** [comment]
Hey there, and thanks for providing support to PHP 8.

I've tried to either use the development branch with PHP 8 code or importing the changes into a 0.8.5 version I'm currently using in another project. 

However, in either case, when using PHP 8, while PDF generation is successful and no PHP 8 errors/notices are shown, I can't get images in my PDF output anymore.

I couldn't figure out why is that so. I don't have anything useful in the logs (and I'm sure logging everything as running PHP 8 with any of 0.8.x releases clearly produces errors and notices). 

Any ideas?

**Comment by mralston** [comment]
> branch php8-compat is ready for testing

I've been using php8-compat for a few days now (since you recommended it on my pull request). php8-compat is working great for me. I provided more details of my use cases and environments in that pull request.

**Comment by bsweeney** [comment]
@unfulvio are the images pulled from the local filesystem? Starting with v0.8.6 Dompdf requires local resources to fall under the path specified for the chroot option.

**Comment by unfulvio** [comment]
@bsweeney  thanks! that seemed to do the trick, I was unaware of the change, sorry

I have a question: what if the images come from different paths?

**Comment by bsweeney** [comment]
@unfulvio no worries. If you have multiple, discrete paths for content you'll have to wait for the next release. Relevant logic was implemented in #2232.

**Comment by unfulvio** [comment]
that's nice @bsweeney I guess I will wait for the next release since both the php compat branch and this logic target develop - I'm assuming the next release will contain both

thanks again

**Comment by marcoalesan** [comment]
Hi guys, how can I use the PHP8 branch without Composer?? I mean download DomPDF as a folder in my server?? Is it possible?

**Comment by marcoalesan** [comment]
Hi Guys. I need DomPDF PHP8 branch **without composer**. Is it available?? Or how can I get it please?

**Comment by enumag** [comment]
I think it will be available when the branch is merged into master. Just be patient. ;-) If you really need it now then just create it yourself, it should be quite easy imo.

**Comment by marcoalesan** [comment]
I found this site https://php-download.com/

Very nice, it creates a **"Non Compser"** version of any Github project and branch. It seems to be working just fine

**Comment by williambarau** [comment]
Solution for version 0.8 follows. In the Block.php file at line 261 if $height equals "auto" set $height to the content of $content_height
![image](https://user-images.githubusercontent.com/2808441/143094160-600c4fb0-0eda-4843-9f85-12e5d3ecb107.png)

**Comment by hstoellinger** [comment]
Any progress with PHP 8 compatibility?

**Comment by hstoellinger** [comment]
Thanks!

**Comment by jdyach** [comment]
is PHP 8.2 supported?

**Comment by enumag** [comment]
8.2? At this point we should start asking about 8.3. 😅

**Comment by bsweeney** [comment]
@jdyach PHP 8.2 is supported, yes.

@enumag yikes yes we should!
