### ISSUE TITLE
Font's keep downloading on each request

### ISSUE THREAD

**Issue by johnwc** [dompdf/dompdf#2246]
Every time we stream a pdf, it will redownload all the fonts for the html into the font cache directory and then produce the pdf. We are using font-awesome in order to use a bunch of their font icons, and their font cache ends up being around 430 cached files. It does this every single time we stream the pdf, redownloads the 430 fonts. For some reason it is not using the already cached files.

**Comment by bsweeney** [comment]
Does something about the font URL change with each render? Dompdf uses a hash to help identify whether or not it has downloaded a font in the past. I don't expect it would be read/write permission issues or the fonts wouldn't embed correctly. Do you see updates to the dompdf_font_family_cache.php file?
