### ISSUE TITLE
Word break styling in a table cell does not work if text is not contained within another element with a defined width

### ISSUE THREAD

**Issue by hmanprod** [dompdf/dompdf#2248]
Hi

My table is cut as below : 
![image](https://user-images.githubusercontent.com/1670599/94166606-2fdf4e00-fe94-11ea-9f89-bfcd2e1bec35.png)

How can i fix this issue. I tried to apply a fixed width and a word-break css on the first column but with no sucess.

Any idea on how to fix this ?

**Comment by bsweeney** [comment]
Need to see your HTML + CSS to provide any useful feedback.

**Comment by PDFCoder** [comment]
This should be the behaviour that web browsers have too. The long links that don't have any blank space force dompdf to "widen" the table cell.

Have a look at css property "word-wrap: break-word;" – dompdf supports it and should solve your problem.

Important: There also exists the css3 property "word-break: break-word;" that works in browsers, but not in dompdf.

**Comment by pablowbk** [comment]
I have my css property set inline, but it's not working once the html is parsed by dompdf, any ideas what I might be missing?


"<td class='desc ft24b2' style='vertical-align: top;word-wrap: break-word;'>" . $valor['desc'] . "

"<td class='desc ft24b2' style='vertical-align: top;overflow-wrap: anywhere;'>" . $valor['desc'] . "


tried using also "overflow-wrap: anywhere" to no avail...

**Comment by bsweeney** [comment]
Width parsing within tables is a bit wonky because of how Dompdf tries to accommodate the table content. You can work around the issue by surrounding your content with a div set to the expected width of the table cell (inheriting works). You can make it easy by just inheriting the width of the container:

```
<table>
  <tr>
    <td style='vertical-align: top; width: 100px; word-wrap: break-word;'>
      <div style="width: inherit">
        lijdflaskdjfalskdjfalsdkjfalksdfjalksdfjalksdfjalksdjalskdjflijdflaskdjfalskdjfalsdkjfalksdfjalksdfjalksdfjalksdjalskdjflijdflaskdjfalskdjfalsdkjfalksdfjalksdfjalksdfjalksdjalskdjflijdflaskdjfalskdjfalsdkjfalksdfjalksdfjalksdfjalksdjalskdjf
      </div>
    </td>
  </tr>
</table>
```


Of course, if your table cell has no defined width Dompdf will make it as wide as possible.

**Comment by pablowbk** [comment]
> Width parsing within tables is a bit wonky because of how Dompdf tries to accommodate the table content. You can work around the issue by surrounding your content with a div set to the expected width of the table cell (inheriting works). You can make it easy by just inheriting the width of the container:
> 
> ```
> <table>
>   <tr>
>     <td style='vertical-align: top; width: 100px; word-wrap: break-word;'>
>       <div style="width: inherit">
>         lijdflaskdjfalskdjfalsdkjfalksdfjalksdfjalksdfjalksdjalskdjflijdflaskdjfalskdjfalsdkjfalksdfjalksdfjalksdfjalksdjalskdjflijdflaskdjfalskdjfalsdkjfalksdfjalksdfjalksdfjalksdjalskdjflijdflaskdjfalskdjfalsdkjfalksdfjalksdfjalksdfjalksdjalskdjf
>       </div>
>     </td>
>   </tr>
> </table>
> ```
> 
> Of course, if your table cell has no defined width Dompdf will make it as wide as possible.

Hey, thanks a lot for your response. It means a lot me,and things make more sense now. 🙂

**Comment by bsweeney** [comment]
Sorry it took so long to get you a response but I'm glad it was helpful.

**Comment by Mellthas** [comment]
`overflow-wrap: anywhere;` and `overflow-wrap: break-word;` should now work as expected.
