### ISSUE TITLE
<img> doesn't working in 0.8.6 version

### ISSUE THREAD

**Issue by mrrfly** [dompdf/dompdf#2249]
Hi all,

I'll get straight to the point,

$s =DomPDF version;

i'am using tag `<img src="">` for displaying image

if($s == "0.8.6") {
 is not working
} elseif($s == "0.8.5") {
 is working
} else {
 don't know
}

i using the same code in all version :

```
< ?php
$barcode = "dokumen/sl/barcode/".str_replace('/', '_', $agenda->NoAgenda).'.png';
?>
< img style="padding-bottom: 5px; padding-left:67%;" src="<?= $barcode; ?>" alt="<?= $barcode; ?>">
```

![domwork](https://user-images.githubusercontent.com/34133496/94408374-e8600700-019e-11eb-9da8-3f6deef2ea5c.png)
dompdf is working in 0.8.5 version
 
![domnotwork](https://user-images.githubusercontent.com/34133496/94408421-f9107d00-019e-11eb-94d6-8c9f4e844a16.png)
dompdf is not working in 0.8.6 version

maybe is my fault.
but if it's my fault you can correct me,
but if it's not my fault maybe you can telling about the error or fix this,

thx 👯‍♀️

**Comment by bsweeney** [comment]
With 0.8.6 we started enforcing chroot restrictions for resource references. If the file is pulled from the local filesystem you'll need to make sure the path to the file is under whatever is specified by chroot.

**Comment by mrrfly** [comment]
thx for the response 👍 I will study it...

**Comment by ThomasLandauer** [comment]
Duplicate of https://github.com/dompdf/dompdf/issues/2229
