### ISSUE TITLE
Image type unknown exception

### ISSUE THREAD

**Issue by graeme1995** [dompdf/dompdf#2253]
**Describe the bug**
Using Laravel, when including images inside my blade, I get the error exception `Image type unknown`.

**To Reproduce**
- Laravel version: 6.18
- DOMPDF version:  ^0.8.7

In my blade I have 
`<img src="{{$file->pdf_url}}" />`

The `$file->pdf_url` produces the following url: `https://project.test/api/expenses/file/graemem/5/test.jpg`

To generate the PDF, my code is 

````
        $pdf = PDF::setOptions([
            'isHtml5ParserEnabled' => true,
            'isRemoteEnabled' => true,
        ])->loadView('pdf.expenses.expense-and-mileage', compact('expense_group', 'expenses', 'mileages', 'attachments', 'total_expenses', 'total_mileages', 'grand_total'))
            ->setPaper('a4', 'landscape');

$pdf_name = "{$expense_group->display_name_of_claimee} - {$expense_group->created_at->format('d/m/Y')}.pdf";

return $pdf->stream($pdf_name);
````

I also have warnings enabled in the dompdf config file. 

**Expected behavior**
The image should display within the PDF file. 

**Additional context**
I have tried both .jpg, .jpeg and .png files. 

I can also access the files directly in the browser with no issue. 

I have also tried linking directly to the absolute file path of the image in the storage folder rather than the public route I created, however I get a `Permission denied` error. 

If it helps, here is the function for accessing my images directly via a route:

````
    /**
     * Show the expense image for viewing.
     *
     * @param ExpenseFile $expense_file
     * @param string      $filename
     *
     * @return void
     */
    public function show(User $user, ExpenseFile $expense_file, $filename)
    {
        $this->authorize('view', $expense_file);

        $file_path = 'app/user-files/' . $expense_file->user_username . "/expenses/{$expense_file->expense_type}/{$expense_file->id}";

        $path = storage_path($file_path . '/' . $filename);

        // If the file does NOT exist, return 404
        if (!File::exists($path)) {
            abort(404);
        }

        $file = File::get($path);
        $type = File::mimeType($path);

        $response = Response::make($file, 200);
        $response->header('Content-Type', $type);

        return $response;
    }
````

**Comment by bsweeney** [comment]
A few quick things:
- for local file access to resources (stylesheets, images), with 0.8.6 you'll need to specify a valid containing path for the chroot option
- ensure that dompdf has read/write access to the temp directory, by default that would be the system temp directory but you can set a value via options
- for web access, is this an authorized path? if so you'll have to authenticate then [set up a custom context](https://github.com/dompdf/dompdf/wiki/Usage#sethttpcontext) with authentication information

**Comment by graeme1995** [comment]
> A few quick things:
> 
> * for local file access to resources (stylesheets, images), with 0.8.6 you'll need to specify a valid containing path for the chroot option
> * ensure that dompdf has read/write access to the temp directory, by default that would be the system temp directory but you can set a value via options
> * for web access, is this an authorized path? if so you'll have to authenticate then [set up a custom context](https://github.com/dompdf/dompdf/wiki/Usage#sethttpcontext) with authentication information

Many thanks, the third bullet point fixed it for me by removing the route of the image from the middleware.
