### ISSUE TITLE
Image local asset doen't work in 0.8.6 

### ISSUE THREAD

**Issue by itemvirtual** [dompdf/dompdf#2260]
Two hours investigating the reason why doesn't show images when I use a local path, finally i fix the problem downgrading to 0.8.5

**Comment by bsweeney** [comment]
With 0.8.6 we modified Dompdf to honor the chroot setting for resource references. There's a note about this in the [release notes](https://github.com/dompdf/dompdf/releases/tag/v0.8.6).

**Comment by ThomasLandauer** [comment]
Duplicate of https://github.com/dompdf/dompdf/issues/2229
