### ISSUE TITLE
Problem with Cyrillic symbols

### ISSUE THREAD

**Issue by p0cketn1nja** [dompdf/dompdf#2262]
I try create pdf using dompdf's latest version (0.8.6 I guess), but dompdf won't create pdf with cyrillic symbols. I use DejaVu Sans, and it's not working, all cyr characters looks like "?". Here below my php code:
```
<?
$html =
'<html><body>'.
'<p style="font-family:DejaVu Sans">Теперь решим проблему с шрифтами в domPDF!</p>'.
'</body></html>';

header("Content-Disposition:attachment;filename='downloaded.pdf'");

include_once($_SERVER["DOCUMENT_ROOT"].'/classes/dompdf/autoload.inc.php');
use Dompdf\Dompdf;

$dompdf = new Dompdf();
$dompdf->load_html($html);
$dompdf->render();
$dompdf->stream();
?>
```
And here below example of PDF what I get as result:
![image](https://user-images.githubusercontent.com/71624275/95443441-24f5e480-098f-11eb-9ad8-70a36a149a5d.png)
All fonts working for latin characters, but cyr always was "?". 
I've tried  0.8.5 ver of dompdf, all the same. I've tried to read "UnicodeHowTo", but didn't find anything to help me.

**Comment by bsweeney** [comment]
That HTML should work. It could be that the font family reference is incorrect. This can happen if you copy Dompdf from one system to another. In the configured font directory (dompdf/lib/fonts by default) look for and remove a file named "dompdf_font_family_cache.php" (_not_ the one with "dist" in the name).

This is unrelated, but you don't need to set the content disposition header manually. Dompdf by default sets the content disposition to attachment. And you can specify a name when you call the method:
```
$dompdf->stream('downloaded.pdf');
```

**Comment by p0cketn1nja** [comment]
Thank you for answer!

> This is unrelated, but you don't need to set the content disposition header manually. Dompdf by default sets the content disposition to attachment. And you can specify a name when you call the method:

Yes, I know that, I've just tried to solve problem with symbols by different ways. Thinked, that was problem with headers. Also about name I knew too.

> In the configured font directory (dompdf/lib/fonts by default) look for and remove a file named "dompdf_font_family_cache.php" (not the one with "dist" in the name).

I look through this directory and find some interesting thing - directory have no "dompdf_font_family_cache.php" or anything else with the same name. It contains only  "dompdf_font_family_cache.dist.php". Maybe that's problem? What should I do?

**Comment by bsweeney** [comment]
The .dist file is the bundled version Dompdf starts with when retrieving font file information. You might try disabling font subsetting to see what happens. And make sure that the process using Dompdf has read/write access to the temp directory.

**Comment by p0cketn1nja** [comment]
> The .dist file is the bundled version Dompdf starts with when retrieving font file information. You might try disabling font subsetting to see what happens. And make sure that the process using Dompdf has read/write access to the temp directory.

Looks like dompdf have some problems witch access to temp directory on our server - I saw some warnings in console. Anyway, we resolved this problem by copying older working version (0.8.2) of dompdf from other directory of our server. Also, 0.8.6 ver have some problems with DejaVu fonts - it drops errors when I try to set this font as default. 
Have no idea why 0.8.2 is working, looks like someone edit it before.

**Comment by bsweeney** [comment]
If you want to work through the problems with 0.8.6 I'm happy to continue.

As for the temp directory, that could be the source of a number of problems. You can set a different temp directory by calling `$dompdf->set_option('tempDir', '/path/to/temp/dir');` where the directory is someplace the process has read/write access.
