### ISSUE TITLE
Problem with cyrillic symbols

### ISSUE THREAD

**Issue by p0cketn1nja** [dompdf/dompdf#2263]
I try create pdf using dompdf's latest version (0.8.6 I guess), but dompdf won't create pdf with cyrillic symbols. I use DejaVu Sans, and it's not working, all cyr characters looks like "?". Here below my php code:
```
<?
$html =
'<html><body>'.
'<p style="font-family:DejaVu Sans">Теперь решим проблему с шрифтами в domPDF!</p>'.
'</body></html>';

header("Content-Disposition:attachment;filename='downloaded.pdf'");

include_once($_SERVER["DOCUMENT_ROOT"].'/classes/dompdf/autoload.inc.php');
use Dompdf\Dompdf;

$dompdf = new Dompdf();
$dompdf->load_html($html);
$dompdf->render();
$dompdf->stream();
?>
```
And here below example of PDF what I get as result:
![image](https://user-images.githubusercontent.com/71624275/95443441-24f5e480-098f-11eb-9ad8-70a36a149a5d.png)
All fonts working for latin characters, but cyr always was "?". 
I've tried  0.8.5 ver of dompdf, all the same. I've tried to read "UnicodeHowTo", but didn't find anything to help me.

**Comment by bsweeney** [comment]
see #2262
