### ISSUE TITLE
PDF generates in Firefox, but not in Safari or Chrome.  Why? 

### ISSUE THREAD

**Issue by JordSmack** [dompdf/dompdf#2264]
Here's a test document:  https://reporting.kineticcontent.com/pdf.php?v=3F960E800C79C0D21B9A

It will generate in Firefox, but Safari just gives a blank page and Chrome gives a "Failed to load PDF document" error.  

Is there a way to get more detailed error information so that I can look into this?

**Comment by bsweeney** [comment]
There's definitely a different between the browsers. Hard to say what's going on without more information. Have you checked your PHP error logs and/or web server logs? You might try a few things to start:
1. end script execution after the PDF has been streamed using `exit`
2. changing the attachment type to download `$dompdf->stream('render.pdf', ['attachment' = true]);`
3. render a simpler document to see if you still experience the same issue

**Comment by ivansnp** [comment]
Hi @JordSmack . How did you fix it? I can download your PDF in any browser. Mine is not working yet.

**Comment by bazl0** [comment]
I still have this issue even after doing the above mentioned by @bsweeney - anyone managed to figure out what's going on?
