### ISSUE TITLE
image base64 not working error 

### ISSUE THREAD

**Issue by YoussefTizi** [dompdf/dompdf#2266]
Hello 
i have an error in dompdf with base64
i generate image from an url
can you help me

 
<img width="802" alt="Capture d’écran 2020-10-13 à 13 48 39" src="https://user-images.githubusercontent.com/39154583/95862914-74eff500-0d5b-11eb-8a1f-f9119199f98f.png">

<img width="677" alt="Capture d’écran 2020-10-13 à 13 55 10" src="https://user-images.githubusercontent.com/39154583/95863148-c00a0800-0d5b-11eb-8704-30b9b3f9d2fa.png">

<img width="599" alt="Capture d’écran 2020-10-13 à 13 51 33" src="https://user-images.githubusercontent.com/39154583/95862972-86390180-0d5b-11eb-8f17-959d69a0cab3.png">

**Comment by bsweeney** [comment]
Do you see any errors in your PHP error logs? Does Dompdf have read/write access to the temp directory specified by the tempDir option (system temp directory by default)? Can you post a sample of the image you're attempting to render? And of the actual HTML?

**Comment by YoussefTizi** [comment]
thank you for your reply
Yes, problems in the work environment, I work on a Mac os
It doesn't work in local, but when I put it on the server it worked fine
i think the problem is the permission (read/write) i don't know how to change the (temp directory) in my machine

**Comment by bsweeney** [comment]
The temp directory used by Dompdf is managed via options. So you would do something like the following (based on how you're setting options in your sample code):

```
$options->set('tempDir', '/path/to/writeable/directory');
```

**Comment by YoussefTizi** [comment]
Thank You For Your Reply 
Yes it's work fine
i use this : $dompdf->set_option('tempDir', '/Applications/XAMPP/xamppfiles/htdocs/lasttestdom/temp');
thank you so much for your help and your time

**Comment by bsweeney** [comment]
Good to know, this may help with others experiencing similar issues.
