### ISSUE TITLE
v0.8.6 has broken styling

### ISSUE THREAD

**Issue by anchordigi** [dompdf/dompdf#2267]
Hi,

Since upgrading to v0.8.6 my styling has broken. I'm putting my PDF together by doing:

```
    // instantiate and use the dompdf class
    $dompdf = new Dompdf();

    ob_start();
    ?>
    <html><head><link rel="stylesheet" id="main-stylesheet-css" href="ABSOLUTE PATH TO CSS HERE" type="text/css" media="all"></head><body>
<!-- PDF CONTENT HERE -->
    $html = ob_get_clean();
    $dompdf->loadHtml($html);

    // (Optional) Setup the paper size and orientation
    $dompdf->setPaper('A4', 'portrait');

    // Render the HTML as PDF
    $dompdf->render();


    $output = $dompdf->output();
```

This used to work fine, but now my PDF has no styling. Do I need to change something?

Thanks!

**Comment by bsweeney** [comment]
With the release of 0.8.6 you'll have to ensure that any resources referenced in the HTML document fall under the path specified by the chroot option. So in your example add something like following after the setPaper call: `$dompdf->set-option('chroot', __DIR__);` (or whatever path would be appropriate to accommodate any stylesheets and images from your local file system).

**Comment by ThomasLandauer** [comment]
Duplicate of https://github.com/dompdf/dompdf/issues/2229
