### ISSUE TITLE
The css position:absolute does not work after the first page of the generated pdf.

### ISSUE THREAD

**Issue by salammsaif** [dompdf/dompdf#2271]
If css position: absolute is used on multiple pages, it only works on the first page.
After the first page, it seems like the content with position absolute does not obeys its css property.

Below is the generated pdf of the 2 pages.
Only the first's page absolute-positioned(red background-color) element were generated as expected.

[Page 1 of the generated pdf]
![2020-10-19_16h42_11](https://user-images.githubusercontent.com/28549821/96417228-0368e880-122c-11eb-87b3-83b24b180543.png)

[Page 2 of the generated pdf]
![2020-10-19_16h42_11-2](https://user-images.githubusercontent.com/28549821/96417324-1bd90300-122c-11eb-8e24-726536f9b95a.png)

For more information, below are the code (PHP and HTML) for this issue.

[PHP logic for rendering the page]
```
public function show()
{
	$domPdf = new Dompdf();
	$domPdf->loadHtml("test.html");
	return $domPdf->stream();
}
```

[HTML of the page]
```
<style>
  .test-p {
    position: absolute;
    background-color: red;
    padding: 2px;
    top: -20;
    left: 20;
}
</style>

<!-- first page -->
<p style="position:relative; background-color: #aaaaaa">
  <span class="test-p">page1</span>
  paragrapah
</p>

<!-- second page -->
<div style="page-break-before: always"></div><!-- page break for the second page -->
<p style="position:relative; background-color: #aaaaaa">
  <span class="test-p">page2</span>
  paragrapah
</p>
```

**Comment by bsweeney** [comment]
There does appear to be an issue here. The element is positioned, but it looks like the negative margin is not honored. We'll have to take a closer look.
