### ISSUE TITLE
JavaScript is not working with the Adobe Reader

### ISSUE THREAD

**Issue by MaximilianKresse** [dompdf/dompdf#2273]
Example code:
```
require_once __DIR__ . '/vendor/autoload.php';

$dompdf = new Dompdf\Dompdf();

$html = '<body><script type="text/javascript">
app.alert("Hello World");
</script><h1>Hello World</h1></body>';

$dompdf->loadHtml($html);
$dompdf->render();
file_put_contents('test.pdf', $dompdf->output());
```

Result:
Javascript doesn't work in Adobe  Reader (v 2020.012.20048). 

The problem can be found here:
![image](https://user-images.githubusercontent.com/545671/96457853-8dab4f80-1220-11eb-9404-40dce1291fd7.png)

And in your code here:
https://github.com/dompdf/dompdf/blob/master/lib/Cpdf.php#L3174

The text "Javascript" is wrong. It has to be "JavaScript". I know it's stupid but it works with this fix.

It is documented as this text in the pdf documentation and Adobe (and many other) expect exactly this text.
![image](https://user-images.githubusercontent.com/545671/96458142-e24eca80-1220-11eb-8acf-0250b26ad323.png)

**Comment by bsweeney** [comment]
I'll have to confirm the case sensitivity of that key but this sounds legit.
