### ISSUE TITLE
UTF-8 Problem [error FontLib\\Table\\Type\\fftm not found]

### ISSUE THREAD

**Issue by bulyakit** [dompdf/dompdf#2275]
Hey,

I ran into this error (and many others) while was trying to generate pdf from a few different html inputs.

I'm on a [blockly project](https://developers.google.com/blockly) and this is from where the (very simple) html sources are coming.

I have to use UTF-8 output and when I try to use the builtin Dejavu fonts I got the errors below (with some cpdf debug message) and the pdf is not generated. I'm on windows and I have a linux server as well to test the results and got the same problem there - not counting that on linux there were more missing table type errors.

The only workaround I found yet is to force to use some already known table type by adding these to the File.php in php-font-lib/src/FontLib/TrueType:

![image](https://user-images.githubusercontent.com/58424111/97101764-50bbde80-16a0-11eb-94c0-655133d2f1bf.png)

I tried first to create manually these empty classes to avoid the error, but when I figured out all the missing classes and it worked finally on windows it turned out that on linux were more other missing classes - so I gave up and simply ignored all the unknown types.

Do I miss something or it is something which is not handled yet? I have a feeling that I'm doing something wrong...but I was thinking it worth a try to ask.

Thanks in advance for any input an help!

[Sun Oct 25 08:14:56.449926 2020] [php7:notice] [pid 26780:tid 1820] [client ::1:50646] selectFont: selecting - C:\\xampp\\htdocs\\snap\\SNAP\\vendor\\dompdf/lib/fonts/DejaVuSerif - , 1\nopenFont: C:\\xampp\\htdocs\\snap\\SNAP\\vendor\\dompdf/lib/fonts/DejaVuSerif - DejaVuSerif\nmetrics: DejaVuSerif.ufm, cache: DejaVuSerif.ufm.php\nopenFont: php file exists C:\\xampp\\htdocs\\snap\\SNAP\\vendor\\dompdf/lib/fonts/DejaVuSerif.ufm.php\nselectFont: selecting - C:\\xampp\\htdocs\\snap\\SNAP\\vendor\\dompdf/lib/fonts/DejaVuSerif-Bold - , 1\nopenFont: C:\\xampp\\htdocs\\snap\\SNAP\\vendor\\dompdf/lib/fonts/DejaVuSerif-Bold - DejaVuSerif-Bold\nmetrics: DejaVuSerif-Bold.ufm, cache: DejaVuSerif-Bold.ufm.php\nopenFont: php file exists C:\\xampp\\htdocs\\snap\\SNAP\\vendor\\dompdf/lib/fonts/DejaVuSerif-Bold.ufm.php\nselectFont: checking for - C:\\xampp\\htdocs\\snap\\SNAP\\vendor\\dompdf/lib/fonts/DejaVuSerif.ttf\n, referer: https://localhost/snap/SNAP/snut/get_page.php?page_id=7357852355104343&panel=M
[Sun Oct 25 08:14:56.455779 2020] [php7:notice] [pid 26780:tid 1820] [client ::1:50646] [snap] [error FontLib\\Table\\Type\\fftm not found] [pid 26780] [url /snap/SNAP/repo03/mapper/process.php] [username nev****ind] [userid 7595783275122354] [pageid -] [pagename -] [processid 7377862355104091] [details {"class":"RuntimeException"}] [stack [{"function":"{closure}","args":["FontLib\\\\Table\\\\Type\\\\fftm"]},\r\n{"function":"spl_autoload_call","args":["FontLib\\\\Table\\\\Type\\\\fftm"]},\r\n{"file":"C:\\\\xampp\\\\htdocs\\\\snap\\\\SNAP\\\\vendor\\\\dompdf\\\\lib\\\\php-font-lib\\\\src\\\\FontLib\\\\TrueType\\\\File.php","line":312,"function":"class_exists","args":["FontLib\\\\Table\\\\Type\\\\fftm"]},\r\n{"file":"C:\\\\xampp\\\\htdocs\\\\snap\\\\SNAP\\\\vendor\\\\dompdf\\\\lib\\\\php-font-lib\\\\src\\\\FontLib\\\\TrueType\\\\File.php","line":124,"function":"readTable","class":"FontLib\\\\TrueType\\\\File","type":"->","args":["FFTM"]},\r\n{"file":"C:\\\\xampp\\\\htdocs\\\\snap\\\\SNAP\\\\vendor\\\\dompdf\\\\lib\\\\Cpdf.php","line":1170,"function":"parse","class":"FontLib\\\\TrueType\\\\File","type":"->","args":[]},\r\n{"file":"C:\\\\xampp\\\\htdocs\\\\snap\\\\SNAP\\\\vendor\\\\dompdf\\\\lib\\\\Cpdf.php","line":931,"function":"processFont","class":"Dompdf\\\\Cpdf","type":"->","args":[8,{"name":"DejaVuSerif","fontFileName":"C:\\\\xampp\\\\htdocs\\\\snap\\\\SNAP\\\\vendor\\\\dompdf\\/lib\\/fonts\\/DejaVuSerif","SubType":"Type1","isSubsetting":true,"fontNum":1,"encoding":"WinAnsiEncoding","toUnicode":9,"cidFont":10}]},\r\n{"file":"C:\\\\xampp\\\\htdocs\\\\snap\\\\SNAP\\\\vendor\\\\dompdf\\\\lib\\\\Cpdf.php","line":3198,"function":"o_font","class":"Dompdf\\\\Cpdf","type":"->","args":[8,"add"]},\r\n{"file":"C:\\\\xampp\\\\htdocs\\\\snap\\\\SNAP\\\\vendor\\\\dompdf\\\\src\\\\Adapter\\\\CPDF.php","line":1213,"function":"output","class":"Dompdf\\\\Cpdf","type":"->","args":[false]},\r\n{"file":"C:\\\\xampp\\\\htdocs\\\\snap\\\\SNAP\\\\vendor\\\\dompdf\\\\src\\\\Dompdf.php","line":932,"function":"output","class":"Dompdf\\\\Adapter\\\\CPDF","type":"->","args":[{"compress":true}]},\r\n{"file":"C:\\\\xampp\\\\htdocs\\\\snap\\\\SNAP\\\\repo03\\\\report_utils.php","line":182,"function":"output","class":"Dompdf\\\\Dompdf","type":"->","args":[]},\r\n{"file":"C:\\\\xampp\\\\htdocs\\\\snap\\\\SNAP\\\\repo03\\\\mapper\\\\process.php(66) : eval()'d code","line":8,"function":"PDFwithAttachment","args":["<style>\\r\\n ....     

Here are my dompdf settings, actually the whole function with using the new attachment feature released in 0.8.6 (it works perfectly)
```
function PDFwithAttachment($aPDFcontent, $aPDFattachments) {
    //set dompdf options
    $options = new Options();
    $options->set('defaultFont', 'dejavu serif, serif');
    $options->setIsHtml5ParserEnabled('true');
    $dompdf = new Dompdf($options);

    //setup the paper size and orientation (optional)
    $dompdf->setPaper('A4', 'portrait');

    //add custom css
    //input type text related customization is needed to handle correctly form inputs and their labels
    $customCSS = "<style>
        input[type=text]:before { border: 1px solid #FFF; }
        label { display: block; padding-bottom: 2px; }
        </style>
        ";

    $aPDFcontent = $customCSS . $aPDFcontent;

    $dompdf->loadHtml($aPDFcontent, 'UTF-8');
    //Render the HTML as PDF
    $dompdf->render();

    //Handling attachments
    $attachments = [];
    $pdfAttachments = [];

    if(!empty($aPDFattachments)) {
        if (isset($aPDFattachments['attachment_content'])) {
            $attachments[0] = $aPDFattachments;
        } else {
            $attachments = $aPDFattachments;
        }

        $i = 0;
        foreach ($attachments as $attachment) {
            $tmpfname = tempnam(sys_get_temp_dir(), 'pdf');

            $handle = fopen($tmpfname, "w");
            fwrite($handle, $attachment['attachment_content'] ?? '');
            fclose($handle);

            $i++;
            $pdfAttachments[] = [
                'name'           => $attachment['attachment_name'] ?? 'attachment_' . $i . '.xml',
                'mime'           => 'text/xml',
                'description'    => $attachment['attachment_description'] ?? '',
                'AFRelationship' => 'Alternative',
                'path'           => $tmpfname
            ];
        }
    }

    /** @var Cpdf $cpdf */
    $cpdf = $dompdf->getCanvas()->get_cpdf();

    foreach ($pdfAttachments as $attachment) {
        $cpdf->addEmbeddedFile(
            $attachment['path'],
            $attachment['name'],
            $attachment['description']
        );
    }

    //Output the generated PDF as String
    return $dompdf->output();
}
```

**Comment by bsweeney** [comment]
The error messaging does seem to indicate a problem with the DejaVu font, but I have not run into this before but based on the (minimal) research I did for PhenX/php-font-lib#48 fftm is related to a font created with Font Forge. For the underlying issue you should follow up in the php-font-lib project, but I'm curious to identify if something we're providing is triggering the issue. If you render without the user-generated content do you still get the error?

Can you attach a copy of the font file so we can inspect it?

**Comment by bulyakit** [comment]
Hey @bsweeney 
Thanks for the reply!
I made a little more deep digging and figured out this:
`RuntimeException: FontLib\\Table\\Type\\fftm not found in C:\\xampp\\htdocs\\snap\\SNAP\\vendor\\quipo\\kafka-php\\src\\examples\\autoloader.php:38\nStack trace:\n#0 [internal function]: {closure}('FontLib\\\\Table\\\\T...')\n#1 [internal function]: spl_autoload_call('FontLib\\\\Table\\\\T...')\n#2 C:\\xampp\\htdocs\\snap\\SNAP\\vendor\\dompdf\\lib\\php-font-lib\\src\\FontLib\\TrueType\\File.php(312): class_exists('FontLib\\\\Table\\\\T...')\n#3 C:\\xampp\\htdocs\\snap\\SNAP\\vendor\\dompdf\\lib\\php-font-lib\\src\\FontLib\\TrueType\\File.php(124): FontLib\\TrueType\\File->readTable('FFTM')\n#4 C:\\xampp\\htdocs\\snap\\SNAP\\vendor\\dompdf\\lib\\Cpdf.php(1167): FontLib\\TrueType\\File->parse()\n#5 C:\\xampp\\htdocs\\snap\\SNAP\\vendor\\dompdf\\lib\\Cpdf.php(931): Dompdf\\Cpdf->processFont(8, Array)\n#6 C:\\xampp\\htdocs\\snap\\SNAP\\vendor\\dompdf\\lib\\Cpdf.php(3195): Dompdf\\Cpdf->o_font(8, 'add')\n#7 C:\\xampp\\htdocs\\snap\\SNAP\\vendor\\dompdf\\src\\Adapter\\CPDF.php(1213): Dompdf\\Cpdf->output(true)\n#8 C:\\xampp\\htdocs\\snap\\SNAP\\vendor\\dompdf\\src\\Dompdf.php(932): Dompdf\\Adapter\\CPDF->output(Array)\n#9 C:\\xampp\\htdocs\\snap\\SNAP\\repo03\\report_utils.php(192): Dompdf\\Dompdf->output(Array)\n#10 C:\\xampp\\htdocs\\snap\\SNAP\\repo03\\mapper\\process.php(66) : eval()'d code(8): PDFwithAttachment('1', Array)\n#11 C:\\xampp\\htdocs\\snap\\SNAP\\repo03\\mapper\\process.php(66): eval()\n#12 {main}output, referer: https://localhost/snap/SNAP/snut/get_page.php?page_id=7357852355104343&panel=M`

It seems that some other external class-autoloader library is wired into the process and this is what drops the missing class error message - not the dompdf or the php-font-lib itself.

Let me discuss this with the team first and if we can move forward I'll be back with a result of our investigation.
At this point I think the culprit is not any part or library of the dompdf.

**Comment by bsweeney** [comment]
I appreciate the follow up and look forward to any additional information you may be able to provide.

**Comment by bulyakit** [comment]
@bsweeney 
It turned out that the source of the problem was the kafka plugin (and how it was implemented). 

Thank you for your help and sorry for the false alarm!

I hope this will help someone else too when facing a similar issue...

**Comment by bsweeney** [comment]
Thanks for following up. I'll close then, will reopen if something relevant comes up that we can address.

**Comment by acobarras** [comment]
a mi me aparecen los siguientes errores para utilizar un checkbox en DOMPDF 

<br />
<b>Fatal error</b>:  Uncaught Error: Failed opening required 'C:\xampp\htdocs\sidpa_2\app/FontLib/Table/Type/fftm.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\sidpa_2\app\autoload.php:7
Stack trace:
#0 [internal function]: mi_funcion('FontLib\\Table\\T...')
#1 C:\xampp\htdocs\sidpa_2\vendor\phenx\php-font-lib\src\FontLib\TrueType\File.php(308): class_exists('FontLib\\Table\\T...')
#2 C:\xampp\htdocs\sidpa_2\vendor\phenx\php-font-lib\src\FontLib\TrueType\File.php(121): FontLib\TrueType\File-&gt;readTable('FFTM')
#3 C:\xampp\htdocs\sidpa_2\vendor\dompdf\dompdf\lib\Cpdf.php(1188): FontLib\TrueType\File-&gt;parse()
#4 C:\xampp\htdocs\sidpa_2\vendor\dompdf\dompdf\lib\Cpdf.php(951): Dompdf\Cpdf-&gt;processFont(10, Array)
#5 C:\xampp\htdocs\sidpa_2\vendor\dompdf\dompdf\lib\Cpdf.php(3216): Dompdf\Cpdf-&gt;o_font(10, 'add')
#6 C:\xampp\htdocs\sidpa_2\vendor\dompdf\dompdf\src\Adapter\CPDF.php(1168): Dompdf\Cpdf-&gt;output(false)
#7 C:\xampp\htdocs\sidpa_2\vendor\dompdf\dompdf\src\Dompdf.php(908): Dompdf\Adapter\CPDF-&gt;stream('', Array)
#8 C:\xampp\htdocs\sidpa_2\app\negocio\util\PDF.php(316): Dompdf\Dompdf-&gt;stream('', Array)
#9 C:\xampp\htdocs\sidpa_2\app\negocio\controladores\configuracion\DescargaControlador.php(89): negocio\util\PDF::pdf_pedidos(Object(stdClass), Array, Array, Object(stdClass), Object(stdClass))
#10 C:\xampp\htdocs\sidpa_2\app\negocio\generico\Core.php(104): negocio\controladores\configuracion\DescargaControlador-&gt;generar_pdf_num_pedido()
#11 C:\xampp\htdocs\sidpa_2\app\negocio\generico\Core.php(25): negocio\generico\Core-&gt;URL()
#12 C:\xampp\htdocs\sidpa_2\index.php(5): negocio\generico\Core-&gt;__construct()
#13 {main}
  thrown in <b>C:\xampp\htdocs\sidpa_2\app\autoload.php</b> on line <b>7</b><br />

Pasa solamente cuando quiero poner un checkbox en el pdf

**Comment by acobarras** [comment]
@bsweeney  estoy usando la version 1.2.2 de dompdf y la 8.1.16 de php, no se en donde mirar el proceso de fuentes, me podrias explicar mejor

**Comment by acobarras** [comment]
y las librerias de Deyavu las tengo todas creo entonces la verdad no se q hacer

**Comment by bsweeney** [comment]
@acobarras go ahead and open a new issue as this looks to potentially be an integration issue that we'll need to work through with you.

**Comment by acobarras** [comment]
a donde hago el procedimiento ?
