### ISSUE TITLE
MathJx equations are not getting rendered in DOMPDF

### ISSUE THREAD

**Issue by pawan-khade** [dompdf/dompdf#2276]
MathJx equations are not getting rendered in DOMPDF

```
<script type="text/javascript">window.MathJax = { MathML: { extensions: ["mml3.js", "content-mathml.js"]}};</script>
<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=MML_HTMLorMML"></script>
```

code in the middle

```
<script type="text/javascript">
MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
</script>
```

**Comment by bsweeney** [comment]
Dompdf doesn't support JavaScript processing. For something like that you'd want to use a headless browser such as wkhtmltopdf. Your other option would be to generate the MathJax on the client and export to a SVG document which you could then reference server-side.
