### ISSUE TITLE
font issues  and Font Undefined index: glyf.

### ISSUE THREAD

**Issue by Pionell** [dompdf/dompdf#2279]
Hello, I have  a little problem here. 
I'm using the 0.8.6 version.

I'm trying to load the pdf , and when I've run into multiple problems with fonts.

While on localhost everything seems to be working fine when I'm using 

`body { font-family: DejaVu Sans; }`

and when I upload it to a server I get a 

`Notice: Undefined index: glyf in /..../vendor/phenx/php-font-lib/src/FontLib/TrueType/File.php on line 329`

error. I've seen your previous response where you mentioned that "dompdf_font_family_cache.php" needs to be deleted when moving into another server, and only the file with dist is present, so that isn't the problem.
When removing the 
`body { font-family: DejaVu Sans; }`  from css in the html the pdf loads fine, but the characters are broken because I have ąčęėįšųūž in the content and the default font isn't loading those.. 😞 

When trying to load external fonts I've tried multiple things:

```
      @font-face {
	  font-family: 'Lora';
	  font-style: normal;
	  font-weight: normal;
	  src: url('http://domain.com/assets/fonts/Lora-Regular.ttf') format('truetype');
          /* the domain of course is specified*/
	}
	body { font-family: 'Lora', serif; }
```

And I've tried relative path loading, I've tried `src: local()` thing, I've tried including the css file in the header and just specifying the font family, nothing seems to load the font in the final PDF. I've tried the setDefaultFont method and it doesn't see to do anything either

**Comment by Pionell** [comment]
quick update
```
$dompdf = new Dompdf([
            'enable_remote' => true,
            'chroot' => "/path/to/file/directory",//I left it as __DIR__ -  it doesn't seem to do anything for me when loading ext fonts.
        ]);
```
this "hack" helped me load external fonts on localhost where the project was created. 
like this:
```
<style>
	@font-face {
	  font-family: 'Lora';
	  font-style: normal;
	  font-weight: normal;
	  src: url('http://domain.com/assets/fonts/Lora-Regular.ttf') format('truetype');
	}
	@font-face {
	  font-family: 'Lora';
	  font-style: Bold;
	  font-weight: Bold;
	  src: url('http://domain.com/assets/fonts/Lora-Bold.ttf') format('truetype');
	}
	
	body{ font-family: 'Lora', serif; }
	
	</style>
```

The problem with `Notice: Undefined index: glyf in` is still there when I moved servers though. The PHP version on the problematic server is 7.4.11

**Comment by Pionell** [comment]
```
Fatal error: Uncaught Error: Call to a member function getGlyphIDs() on null in /../vendor/phenx/php-font-lib/src/FontLib/TrueType/File.php:202 Stack trace: 
#0 /../vendor/dompdf/dompdf/lib/Cpdf.php(1171): FontLib\TrueType\File->setSubset() 
#1 /../vendor/dompdf/dompdf/lib/Cpdf.php(931): Dompdf\Cpdf->processFont() 
#2 /../vendor/dompdf/dompdf/lib/Cpdf.php(3196): Dompdf\Cpdf->o_font() 
#3 /../vendor/dompdf/dompdf/src/Adapter/CPDF.php(1185): Dompdf\Cpdf->output() 
#4 /../vendor/dompdf/dompdf/src/Dompdf.php(905): Dompdf\Adapter\CPDF->stream() 
#5 ../
#6 ../
#7 /home/ in /../vendor/phenx/php-font-lib/src/FontLib/TrueType/File.php on line 202
```

**Comment by bsweeney** [comment]
I haven't seen this issue before. Is the autoloader finding all of the php-font-lib classes?

Looks like it's having an issue during font subsetting, if you disable subsetting (`'isFontSubsettingEnabled' => false`) does the error go away?

**Comment by Pionell** [comment]
using `'isFontSubsettingEnabled' => false` produces this weird result:
![image](https://user-images.githubusercontent.com/24505446/97671658-57c46180-1a91-11eb-9839-f470b46561af.png)

**Comment by bsweeney** [comment]
Hrm ... looks like maybe the glyph widths are zeroed out somehow, causing placement of text segments to calculate incorrectly. Do you have a small sample of the HTML we can look at. Also, is this render using DejaVu? Can you share the UFM related to the font?

**Comment by NathanSweet** [comment]
I was using NotoSans TTF fonts [just fine](https://github.com/dompdf/dompdf/issues/2146#issuecomment-672278603) for a long time. After I updated Domdpdf, now I get the error above (`getGlyphIDs` on null).
