### ISSUE TITLE
UTF-8 for filenames and descriptions of embedded files produces garbled text in viewers

### ISSUE THREAD

**Issue by Emdek** [dompdf/dompdf#2281]
v0.8.6 finally introduced support for embedding arbitrary files as PDF attachments, but there seems to be a serious limitation.
UTF-8 characters in filenames and file descriptions are not interpreted correctly, for example `€` ends up as `â‡¬`.
Iit seems to be consistent across document viewers, at least in case of okular and evince.
Acrobat Reader seems to have similar issues.

Is this dompdf limitation or PDF standard letdown?

Example code:
```php
$dompdf = new Dompdf();
$dompdf->loadHtml('HTML GOES HERE');
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->getCanvas()->get_cpdf()->addEmbeddedFile('some-file.txt', '€.txt', '€');
$dompdf->stream('report.pdf', ['Attachment' => FALSE]);
```

I've tried other Unicode encodings but nothing helped, hopefully transliteration to ASCII won't be necessary…

BTW, any plans to add support for specifying file creation and modification time attributes?

**Comment by bsweeney** [comment]
Looking at the related code quickly I think this is likely a deficiency in CPDF. No encoding is performed on the filename, which means it would be interpreted with Windows ANSI encoding by default. But I'll need to do a bit more research to confirm the issue.

**Comment by bsweeney** [comment]
> [A]ny plans to add support for specifying file creation and modification time attributes?

For the PDF itself or for the embedded files? We don't have current plans for this feature but if you open a new issue we can look at adding it to an upcoming milestone.

**Comment by Emdek** [comment]
@bsweeney, thanks for the quick reply.

> For the PDF itself or for the embedded files?

Embedded files, I'll add another ticket then.

**Comment by Emdek** [comment]
@bsweeney, I've done some research, and apparently Acrobat can properly encode non ASCII filenames for embedded files, although I was unable to find out how yet, since output was more binary compared to one from this library…

BTW, I've found "PDF Reference, Third Edition", and I've found "Multiple-Byte Strings in File Specifications" section there.
I've tried to apply that encoding scheme to filenames but so far without luck.

**Comment by Emdek** [comment]
Found it, this seems to do the trick for both filenames and descriptions:

```php
chr(0xFE).chr(0xFF).mb_convert_encoding($string, 'UTF-16', 'UTF-8');
```

Section "Text Strings" mentions that it should be UTF-16 with BOM.

The question is, should it be done automatically (detect encoding? assume UTF-8?) or just mentioned in the comments?

**Comment by Emdek** [comment]
I see that there is already `Cpdf::utf8toUtf16BE()` that seems to do that job.
BTW, TCPDF also fails to properly encode filenames.

**Comment by bsweeney** [comment]
Thanks for the research. If you want to work up a PR feel free. If not I think we have enough info to fix this.

**Comment by Emdek** [comment]
@bsweeney, I can prepare PR, but I'm not sure which approach should be taken:

> The question is, should it be done automatically (detect encoding? assume UTF-8? and avoid double encoding if input is already properly encoded) or just mentioned in the comments?

Double encoding is a possibility since some people, including me, might want to workaround it for now.
I guess that `Cpdf::utf8toUtf16BE()` could check if BOM was already applied and return original `$text` in that case.

BTW, I've noticed `Cpdf::utf8toCodePointsArray()` too, nowadays it can be accomplished using much simpler code (might be more efficient too):

```php
preg_split('//u', $text, -1, PREG_SPLIT_NO_EMPTY);
```

**Comment by bsweeney** [comment]
Text encoding ... so much to wrap one's head around. Confirming the existing encoding would probably be a useful addition though how to go about it ... ? A BOM check is easy enough for the relevant methods.

I'd have to think through the change to using preg_split instead of utf8toCodePointsArray though if that works it would almost definitely be more efficient.

**Comment by Emdek** [comment]
@bsweeney, personally I would go for either using document encoding or assuming UTF-8, and do BOM check anyway.
What is the current approach for encoding in the library? It should be consistent if possible (except for that BOM thing for avoid double encoding).

Also I'm wondering if conversion should be done in cases when it is technically not needed, when string is compatible with *PDFDocEncoding*, in places where it is allowed.
It just increases document size (and makes it less readable when viewing in text editor, which was my crude way for learning PDF structure and doing quick debugging when working with annotations).

`preg_split()` worked great for me, obviously it would require some test cases to compare both accuracy and performance (just for fun, since it is likely to be way more efficient).

BTW, any plans to expose that method on the `Dompdf` class level?
`Dompdf::getCanvas()::get_cpdf()::addEmbeddedFile()` looks kinda ugly and more like abuse of (semi) internal API. ;-)
