### ISSUE TITLE
 Call to a member function get_cellmap() on null 

### ISSUE THREAD

**Issue by CrowdForge** [dompdf/dompdf#2282]
Getting the following error:

Fatal error: Uncaught Error: Call to a member function get_cellmap() on null in /Users/mikegrotton/Local Sites/ms/app/public/wp-content/themes/marshal-child/lib/dompdf/src/FrameReflower/TableCell.php on line 37

Any ideas?  could there be something wrong with my table?

**Comment by CrowdForge** [comment]
The table that seems to be tripping it up is marked up as follows:

`

<table id="report-details-table" class="table table-responsive text-left">
--
  | <tbody>
  | <tr>
  | <td>Lessee/Borrower Name</td>
  | <td>:</td>
  | <td>Four Leaf Construction</td>
  | </tr>
  | <tr>
  | <td>Asset Vertical</td>
  | <td>:</td>
  | <td>Construction</td>
  | </tr>
  | <tr>
  | <td>Asset Description</td>
  | <td>:</td>
  | <td>Backhoe w GP Bucket and Dig Bucket (Other)</td>
  | </tr>
  | <tr>
  | <td>Quantity <span>( #Units )</span></td>
  | <td>:</td>
  | <td> 1</td>
  | </tr>
  | <tr>
  | <td>Manufacturer</td>
  | <td>:</td>
  | <td> JCB </td>
  | </tr>
  | <tr>
  | <td>Model Number</td>
  | <td>:</td>
  | <td> 3CX-15</td>
  | </tr>
  | <tr>
  | <td>Year New</td>
  | <td>:</td>
  | <td> 2018 </td>
  | </tr>
  | <tr>
  | <td>Fair Market Value <span>( MON NOVEMBER 02 2020 )</span></td>
  | <td>:</td>
  | <td> $110,000 <span>(Per Unit)</span></td>
  | </tr>
  | <tr>
  | <td>Expected Use</td>
  | <td>:</td>
  | <td>Normal</td>
  | </tr>
  | </tbody>
  | </table>

`

**Comment by bsweeney** [comment]
Dompdf is a bit rigid when it comes to table structure. I don't see anything wrong with the table itself so it could be related to the styling.

**Comment by AbdulrahmanMasoud** [comment]
DomPDF Make Conflict with CSS properties Like Display I don't Know why But Try to remove Display

**Comment by gemal** [comment]
It will die on:
```
<html>
<body>
<table style="display: block">
<tr>
<td>
</td>
</tr>
</table>
</body>
</html>
```

`Error: Call to a member function get_cellmap() on null`

**Comment by AbdulrahmanMasoud** [comment]
> It will die on:
> 
> ```
> <html>
> <body>
> <table style="display: block">
> <tr>
> <td>
> </td>
> </tr>
> </table>
> </body>
> </html>
> ```
> 
> `Error: Call to a member function get_cellmap() on null`

DomPDF Make Conflict with CSS properties Like Display I don't Know why But Try to remove Display

**Comment by bsweeney** [comment]
When you change the display styling of a table element it's no longer rendered as a table. Dompdf will fail attempting to parse the table structure because the (rigid) expectations are no longer met.

Probably the way we would handle this is to then generate an anonymous table element inside the table element whose display styling has been changed. That functionality hasn't been built out yet (#449).
