### ISSUE TITLE
dompdf not working after upgrade pdf from 7.2 to 7.4.12

### ISSUE THREAD

**Issue by JohanKrab** [dompdf/dompdf#2284]
The latest version of dompdf i installed : 0.8.6
It worked fine with PDF 7.2 and dompdf 0.8.5
Acrobat read error attached 
![dompdf-error](https://user-images.githubusercontent.com/66780834/98241110-c3fc0500-1f6a-11eb-9317-d81b82c337a8.PNG)

**Comment by JohanKrab** [comment]
the generated pdf file contains html and not pdf (as in the past)
[oisreport(1).pdf](https://github.com/dompdf/dompdf/files/5494390/oisreport.1.pdf)

**Comment by bsweeney** [comment]
There appears to be an error thrown by PHP somewhere. If you open the PDF in a text editor you'll see it's actually part of an HTML document instead of the rendered PDF. Enable PHP logging and check for errors.

**Comment by JohanKrab** [comment]
I enabled logging but no errors seen.
I reinstallad everything but issu still exists.

**Comment by bsweeney** [comment]
Are you logging to a file or just outputing logs to the client? If the latter, open the generated PDF after you've enabled logging to see if there's any additional information.

**Comment by JohanKrab** [comment]
I did some testing by isolating and created a small php script.
It works fine.
So because i use dompdf in a joomla component i have to look more into it.
For now it look likes it is not a problem with dompdf.
Thanks sofar.

Johan

**Comment by bsweeney** [comment]
Good to know. If you're so inclined, feel free to post what you find in case others run into the same issue.
