### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by bsweeney** [dompdf/dompdf#2287]
As we've seen with past releases the current versioning scheme isn't quite working out. Sticking to a sub-1.0 release until Dompdf is feature complete is not compatible with the semantic versioning expected by composer-managed projects. Moving forward I would like to see us do a better job considering how changes.

The next release will accommodate PHP 8 and as such will necessarily change some of the implementation details of Dompdf. These changes may result in changes that are incompatible with previous releases (e.g. modifying method argument order). As such we're looking for feedback from the community about how to proceed.

At present these are the options I have in mind for the next release:
- 0.8.7: current planned version, possibly will introduce issues on particular systems during upgrades
- 0.9.0: semantic versioning indicates that this would be a backwards-compatible change. While the release will be compatible with the same PHP versions as 0.8.6 it is likely that the Dompdf API will change.
- 1.0.0: bump the version to indicate the release is not backwards compatible
- 9.0.0: shift one versioning space over; achieves the same result as going to 1.0 but preserves some semblance of the versioning history

**Comment by simonberger** [comment]
Semantic versioning allows us generally to break everything even in a patch release but that obviously doesn't help projects using Dompdf and isn't what most of the users are expecting. I like the idea to jump to 1.0.0 soon. Looking at the feature backlog or code base there probably never would be a time to release a 1.0.0 confidently.
Beside indicating breaking changes with new major releases the versions should also show which kind of changes can be expected. A release like the last which was full of new features could be a new minor or even major version.

>  9.0.0: shift one versioning space over; achieves the same result as going to 1.0 but preserves some semblance of the versioning history
I doubt the idea behind it will really be understood.

**Comment by PowerKiKi** [comment]
Just go with 1.0.0, especially if things break, but also to show that this lib is mature enough to be used in production systems (it has been used in production system for years).

Jumping to 9.0.0 is not the best option. By doing so it would give a special "human" meaning to version number. Versions should not have "emotion" attached to it, but instead be fact based as much as possible. Does it break API ? then increase major. Does it add feature ? then increase minor. Does it fix a bug ? then increase patch. As simple, and cold, as that. It's the best way to communicate clearly what the version is about.

**Comment by j3j5** [comment]
Just for the record, on projects below 1.0.0, breaking changes are [allowed on minor versions under semantic versioning](https://semver.org/#spec-item-4). Rules on `composer.json` should be set accordingly if you are using a <1.0 version. On a different note, I totally agree that DomPDF is mature enough to jump to 1.x already.

**Comment by bsweeney** [comment]
well, I guess I feel ... better? ... that we're still using major version zero then 😅 

Thanks, everyone, for the feedback. I agree that Dompdf is fairly stable and worthy of a major release at this point. My original thought long (long) ago was that we could polish up table support and bump up to 1.0. Time is cruel beast, and life gets in the way, so best to recognize where we are and drop such grand fantasies.

1.0.0 it is.
