### ISSUE TITLE
CSS border style double prints 3 lines

### ISSUE THREAD

**Issue by naitsirch** [dompdf/dompdf#2291]
```html
<style>
    .border-top {
        border-top: 1px solid #dee2e6;
    }
    .border-bottom-double {
        border-bottom: 3px double #dee2e6;
    }
</style>
<!-- ... -->
<table>
    <tr>
        <td class="border-top border-bottom-double">Gesamtkosten</td>
    </tr>
</table>
```

The border at the bottom of the table cell doesn't look like expected:
![grafik](https://user-images.githubusercontent.com/1118790/98949780-70ecf980-24f8-11eb-8c73-1b4ce9239dfd.png)

The screenshot is created with high zoom ;-)

**Comment by bsweeney** [comment]
I'm not seeing the same, is there potentially some other layout/styling that could be affecting border rendering?

Also, which version of Dompdf are you using?

**Comment by naitsirch** [comment]
I will check it on monday.

**Comment by naitsirch** [comment]
Okay, I reduced the code for reproduction wrongly.

Please check this one:
```html
<!DOCTYPE html>
<html lang="de">
    <head>
        <style>
            table {
                border-collapse: collapse;
            }
            .border-bottom-double {
                border-bottom: 3px double #dee2e6 !important;
            }
        </style>
    </head>
    <body>
        <table class="border-bottom-double">
            <tr>
                <td>Gesamtkosten</td>
            </tr>
        </table>
    </body>
</html>
```
Those three conditions must be met:
- The class `border-bottom-double`  must be set on the table element (not the td)
- the border-bottom rule must be suffixed with `!important`
- border-collapse must be set to `collapse`

Now it should be reproducable.

I have installed version v0.8.6 (commit hash dompdf@db91d81866c69a42dad1d2926f61515a1e3f42c5).
