### ISSUE TITLE
How is everyone getting fonts to work!!!?

### ISSUE THREAD

**Issue by Micu22** [dompdf/dompdf#2293]
Look, these is what I tried:
1. Using font-face: (the directory of font is root/fonts/)
```
@font-face { 
	font-family: gilroy; 
	font-weight: normal; 
	font-style: normal; 
	src: url('fonts/gilroy-extrabold.ttf') format('truetype'); 
}
```
2. Using google fonts:
```
@font-face {
	font-family: 'montserrat';
	font-style: normal;
	font-weight: 400;
	src: url('https://fonts.googleapis.com/css2?family=Montserrat') format('truetype');
}
```
or
`<link href='https://fonts.googleapis.com/css2?family=Montserrat&display=swap' rel='stylesheet'>`

3. running load_font.php and getting all sorts of errors, I think this one is the closest to working:
```
C:\Apache24\htdocs\dompdf\lib>php load_font.php Gilroy ./fonts/Gilroy-Medium.ttf ./fonts/Gilroy-SemiBold.ttf ./fonts/Gilroy-ExtraBold.ttf
Unable to find bold_italic face file.
Copying ./fonts/Gilroy-Medium.ttf to C:\Apache24\htdocs\dompdf/lib/fonts/Gilroy-Medium.ttf...
PHP Fatal error:  Uncaught Dompdf\Exception: Unable to copy './fonts/Gilroy-Medium.ttf' to 'C:\Apache24\htdocs\dompdf/lib/fonts/Gilroy-Medium.ttf' in C:\Apache24\htdocs\dompdf\lib\load_font.php:148
Stack trace:
#0 C:\Apache24\htdocs\dompdf\lib\load_font.php(201): install_font_family(Object(Dompdf\Dompdf), 'Gilroy', './fonts/Gilroy-...', './fonts/Gilroy-...', './fonts/Gilroy-...')
#1 {main}
  thrown in C:\Apache24\htdocs\dompdf\lib\load_font.php on line 148

Fatal error: Uncaught Dompdf\Exception: Unable to copy './fonts/Gilroy-Medium.ttf' to 'C:\Apache24\htdocs\dompdf/lib/fonts/Gilroy-Medium.ttf' in C:\Apache24\htdocs\dompdf\lib\load_font.php on line 148

Dompdf\Exception: Unable to copy './fonts/Gilroy-Medium.ttf' to 'C:\Apache24\htdocs\dompdf/lib/fonts/Gilroy-Medium.ttf' in C:\Apache24\htdocs\dompdf\lib\load_font.php on line 148

Call Stack:
    0.0007     423448   1. {main}() C:\Apache24\htdocs\dompdf\lib\load_font.php:0
    0.0284    2781488   2. install_font_family() C:\Apache24\htdocs\dompdf\lib\load_font.php:201
```

4. shamelessly copying code from internet and trying it without much thinking due to being enraged
```
require_once( './dompdf/autoload.inc.php');

use Dompdf\Dompdf;
use Dompdf\Options;

$options = new Options();
$options->set('defaultFont', 'Open Sans');
$options->set('fontDir', 'vendor/webfontkit/open-sans/fonts');

$dompdf = new Dompdf($options);
$dompdf->loadHtml(file_get_contents('template.html'));


$dompdf->setPaper('A4');
$dompdf->render();
$dompdf->stream();
```
5. Using the bundled fonts in dompdf via @font-face (referencing the lib/fonts folder)

Nothing works so far. If you need more info ask, I will do everything to solve this...

btw. Could you include a guide in the wiki that ACTUALLY helps in configuring it properly? HELP HELP

Edit: Forgot to add, if I copy the exact same html and echo it to the website it shows the fonts properly, so it's obvious that the problem is I am doing something wrong in dompdf 😫

**Comment by Micu22** [comment]
@update
I made it somewhat work. But I don't understand how. What I did was I found a project I did using dompdf a loooong time ago. I looked into it and fount strange files in the lib/fonts directory
• 78b7cb56f45d7ca07d739d3f0d7f374c.ufm.php
• 78b7cb56f45d7ca07d739d3f0d7f374c.ufm
• 78b7cb56f45d7ca07d739d3f0d7f374c.ttf
Just of curiosity I run the old project without them and they happened to be vital to font-loading.
So what I did was I looked with the sublime text search function for any references to the names of these files, and I found one inside 
lib/fonts/dompdf_font_family_cache.php
I copied the referencing fragment to the new project cache file and copied these three files and „et voilà !” the font loaded correctly. (note: NO @font-face present in css)
Now.... my question is HOW to prepare files like those from regular font files ?? (I do not remember how I did it for this old project) 
if it's the load_font.php script, then please explain how to use it so it doesn't throw errors.

**Comment by bsweeney** [comment]
2.2 should work:
```
<link href='https://fonts.googleapis.com/css2?family=Montserrat&display=swap' rel='stylesheet'>
```

What you may be missing is read/write access to the directory specified by the fontDir and fontCache options and/or enabling of remote resources (which are currently disabled by default).

There is some information in the wiki (see the [requirements](https://github.com/dompdf/dompdf/wiki/Requirements) and [unicode how-to](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo)), but specific guidance on how to reference and use external fonts may be in order.

**Comment by Micu22** [comment]
> What you may be missing is read/write access to the directory specified by the fontDir and fontCache options and/or enabling of remote resources (which are currently disabled by default).
In my estimation these reasons are not valid. One font works, so I guess the fontDir and fontCache options are set up correctly.
I have allow_url_fopen set to 'On' so that is not the case.

Could anyone explain what are these files:
• 78b7cb56f45d7ca07d739d3f0d7f374c.ufm.php
• 78b7cb56f45d7ca07d739d3f0d7f374c.ufm
• 78b7cb56f45d7ca07d739d3f0d7f374c.ttf
and HOW to create them from regular .ttf files?
These are the only font files I can get to work, as I said I have taken them from a very old project in dompdf and I forgot how to create them. (I think `load_font.php` is the solution, but it throws errors which I have listed above).

**Comment by bsweeney** [comment]
Those files are:
- TTF: The downloaded font file, name is hashed to prevent naming collision
- UFM: The generated font metrics
- UFM.PHP: The parsed font metrics, cached as a PHP file to improve performance.

Are you saying that you have a different external font that works, but Montserrat does not?

It's been a while since we worked on load_font.php and so I'm not sure how compatible it is with the current release. Have you downloaded the current version of that file from the [utils project](https://github.com/dompdf/utils)?

As for the error, it speaks for itself. Unable to copy the files which would seem to indicate a write issue. Some extra error handling/messaging in load_font.php would probably help figure it out. Do both the source file and destination directory exist?

**Comment by Micu22** [comment]
Alright thanks for your response, I thought the console can read and write everywhere without any setup but maybe this is the problem. Could you explain me how to give write permission to my console in windows? 

Yes I am using the latest version of load_font.php, I have just redownloaded it and tried again and the same error shows up.

Yes both the file and the directory exist.

**Comment by bsweeney** [comment]
Giving write permissions is system dependent, not sure how much help I'd be there. First I'd try modifying the settings to see if specifying a different directory helps. Just try creating a directory in the same place where your PHP file is. I'd also try using the `@font-face` declaration since I know that works. You have to specifically enable remote resource loading to reference anything from the web.

With 0.8.6 local resource references have to be under the chroot directory. If you're referencing local files you can check if that's the issue by setting chroot to the root (/).

Try something like this to start:

```
require 'vendor/autoload.php';
use Dompdf\Dompdf;

$content = <<<HTML
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet"> 
</head>
<body style="font-family: 'Montserrat', monospace;">Lorem ipsum</body>
</html>
HTML
;

$pdf = new Dompdf([
	'fontDir' => realpath('./scratch'),
	'fontCache' => realpath('./scratch'),
	'tempDir' => realpath('./scratch'),
	'chroot' => realpath('/'),
	'isRemoteEnabled' => true
]);
$pdf->loadHtml($content);
$pdf->render();
file_put_contents("output.pdf", $pdf->output());
```

**Comment by Micu22** [comment]
Okay I tested your code. I have pointed these:
```
'fontDir' => realpath('./scratch'),
'fontCache' => realpath('./scratch'),
'tempDir' => realpath('./scratch'),
```
Here: ( I have created folders: fontCache and temp, they were empty, after running the code a file appeared in fontCache )
```
'fontDir' => realpath('./lib/fonts'),
'fontCache' => realpath('./fontCache'),
'tempDir' => realpath('./temp'),
```

I have placed your code in a file that is inside dompdf folder.
It generates a pdf with the proper google font (I tried a couple different google fonts, all work).

Local fonts work too (specified with @font-face)!!

I guess the problem was I have not created the fontCache and tempDir folders and have not pointed the script to them.

I will stick to local fonts and disable Remote. 

I would also like to move the file outside of dompdf folder for security reasons I want dompdf to not be accesible from the web. I have not tried that yet, so maybe leave this thread open I will update it this in a few days.

**Comment by yediaeluzai** [comment]
> Giving write permissions is system dependent, not sure how much help I'd be there. First I'd try modifying the settings to see if specifying a different directory helps. Just try creating a directory in the same place where your PHP file is. I'd also try using the `@font-face` declaration since I know that works. You have to specifically enable remote resource loading to reference anything from the web.
> 
> With 0.8.6 local resource references have to be under the chroot directory. If you're referencing local files you can check if that's the issue by setting chroot to the root (/).
> 
> Try something like this to start:
> 
> ```
> require 'vendor/autoload.php';
> use Dompdf\Dompdf;
> 
> $content = <<<HTML
> <!DOCTYPE html>
> <html>
> <head>
> 	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
> 	<link rel="preconnect" href="https://fonts.gstatic.com">
> 	<link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet"> 
> </head>
> <body style="font-family: 'Montserrat', monospace;">Lorem ipsum</body>
> </html>
> HTML
> ;
> 
> $pdf = new Dompdf([
> 	'fontDir' => realpath('./scratch'),
> 	'fontCache' => realpath('./scratch'),
> 	'tempDir' => realpath('./scratch'),
> 	'chroot' => realpath('/'),
> 	'isRemoteEnabled' => true
> ]);
> $pdf->loadHtml($content);
> $pdf->render();
> file_put_contents("output.pdf", $pdf->output());
> ```

@bsweeney is this working for 0.8.3?? Because the server still on php 7.0

**Comment by bsweeney** [comment]
That should work with 0.8.3, though the chroot restriction for resource references does not exist in that version

**Comment by smashing57** [comment]
@Micu22 https://phps.space/questions/is-it-safe-to-use-dompdf-in-conjunction-with-filegetcontents
