### ISSUE TITLE
It tells me that a version above 7.2.5 is required, but the README file does not tell me this

### ISSUE THREAD

**Issue by Zmzblink** [dompdf/dompdf#2295]
![97_AQ2F{5WN@@U%`C9D`LVY](https://user-images.githubusercontent.com/41999796/99227439-351ea080-2826-11eb-9643-d639a54acdc9.png)

**Comment by bsweeney** [comment]
What's the exact messaging you receive? Our Composer configuration specifies 7.1 or higher.

**Comment by Zmzblink** [comment]
I got it wrong, it was an error from another component in my code

**Comment by Zmzblink** [comment]
Bro, it's my problem, can you delete this issue?  XD

**Comment by bsweeney** [comment]
done and done
