### ISSUE TITLE
Https URL image is not loading in PDF view

### ISSUE THREAD

**Issue by rmkpmohan88** [dompdf/dompdf#2297]
Earlier the HTTPS URL image is loading well in the pdf view from last week the HTTPS URL is not working in the pdf view but the HTTP URL image is loading well. We tried to find the root cause and fix the issue but couldn't find the root cause of this issue. In our staging server, the HTTPS URL image is loading well in the pdf view but in the Prod server, it is not working in the pdf view.
Enabled the "allow_url_fopen" in php.ini file.

Language   - PHP 7.1.33 FPM
Framework - Phalcon
Server         - nginx/1.19.1
System       - ubuntu16.04.1

**code**:

```
use Dompdf\Dompdf; 

$dompdf = new Dompdf(array('enable_remote' => true));
$dompdf->setbasepath(realpath('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/'));
$dompdf->setPaper('A4', 'portrait'); 
$dompdf->loadHtml($htmlContent); 
$dompdf->render();  
$dompdf->stream("download.pdf", array("Attachment" => false));
```

**Comment by bsweeney** [comment]
Which version of Dompdf? Is it any HTTPS URL or a specific one? For example, can you load https://placekitten.com/500/500?

FYI setBasePath is confusingly named when thinking about the web. It should be just the path portion of the base HREF. You have to set protocol, host, and path separately to configure a base HREF.

**Comment by rmkpmohan88** [comment]
> Which version of Dompdf? Is it any HTTPS URL or a specific one? For example, can you load https://placekitten.com/500/500?
> 
> FYI setBasePath is confusingly named when thinking about the web. It should be just the path portion of the base HREF. You have to set protocol, host, and path separately to configure a base HREF.

dompdf : "^0.8.0"

Image URL what we used in pdf: 

Not working - https://quote2cash.app/assets/images/AMEX-Bluebox-Logo.jpg
Working       - http://servicechum.com/layout6/assets/images/AMEX-Bluebox-Logo.jpg

We didn't make any code changes, earlier working well but from last week onwards the HTTPS URL images are not loading in the pdf view and displaying **Image not found or type unknown** error in pdf view.

Is that any server configuration needs to load HTTPS URL images in the pdf.

**Comment by bsweeney** [comment]
Have there been any system changes that were not directly related to PHP/Dompdf? There's no specific configuration modifications you need to make in order to access HTTPS URLs via Dompdf so I would guess an underlying system change.

Dompdf uses file_get_contents to retrieve files. You can supply a custom HTTP context if file_get_contents is fully configured. Optionally Dompdf will use curl if configured and allow_url_fopen is false (though it doesn't currently work with the custom context).

Have you tried a plain PHP script to access an HTTPS resource? Something like:

```
<?php
file_get_contents('http://placekitten.com/500/500');
?>
```

**Comment by rmkpmohan88** [comment]
Thanks for your response, I tried with the below mentioned plain PHP script an HTTP file contents are working and HTTPS file contents are not working.

**Working with displaying the image** =>

```
<?php
$imageData = file_get_contents('http://placekitten.com/500/500');
echo '<img src="' . $imageData . '">';
?>
```

**Not working with displaying empty page** =>

```
<?php
$imageData = file_get_contents('https://placekitten.com/500/500');
echo '<img src="' . $imageData . '">';
?>
```

**Comment by bsweeney** [comment]
Looks like something changed in your underlying system configuration. Might try enabling error messaging in that snippet to see if you can figure out why it's failing.

```
<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');
$imageData = file_get_contents('https://placekitten.com/500/500');
var_dump($http_response_header);
?>
```

**Comment by rmkpmohan88** [comment]
Finally found the root cause it was an OpenSSL certificate issue now it got resolved. The HTTPS URL image is loading well in PDF view.

Thanks a lot for your support.

**Comment by bandarusaiprashanth** [comment]
> Finally found the root cause it was an OpenSSL certificate issue now it got resolved. The HTTPS URL image is loading well in PDF view.
> 
> Thanks a lot for your support.

Hi, May I know what was the issue with the certificate? I am facing the same issue.

**Comment by committeemanbennett4** [comment]
@bsweeney https://phps.space/questions/is-it-safe-to-use-dompdf-in-conjunction-with-filegetcontents
