### ISSUE TITLE
unexpected '=' in /dompdf/src/Dompdf.php on line 356 with php version  7.2.22

### ISSUE THREAD

**Issue by maodomalick99** [dompdf/dompdf#2300]
hello, I'm getting the following error:
syntax error, unexpected '=' in /dompdf/src/Dompdf.php on line 356
my php version is 7.2.22 when i put php -v in the server

Thanks in advance.

**Comment by bsweeney** [comment]
Is the process using Dompdf (e.g. your web server) also running with PHP 7.2.22?

**Comment by maodomalick99** [comment]
Yes my web server has the 7.2.22 version

**Comment by bsweeney** [comment]
What do you get back if you create a `phpinfo();` page and access via your web server?

**Comment by jazen4p** [comment]
Can you provide the all code in the function that has the error line in 356? 
From what i saw, something stuck when you recall the dompdf library.

**Comment by dyaskur** [comment]
based my experience I accidentally write unexpected char on file on the vendor's folder when I want to learn it.

**Comment by maodomalick99** [comment]
Hi,
It was the version of php , my computer has two php version so he use the wrong version
thanks for the help
