### ISSUE TITLE
border-radius not working on table and td elements

### ISSUE THREAD

**Issue by theDyingMountain** [dompdf/dompdf#2301]
I use version 0.8.6. The border-radius doesn't work on table and td tags. I tried high and low values.

**Comment by bsweeney** [comment]
Would need to see a sample of your HTML + CSS to offer any help. Those work find for me, so long as `border-collapse: separate;`.

**Comment by theDyingMountain** [comment]
Yes with `border-collapse:separate` it works. But I need a solution for `border-collapse: collapse`

**Comment by bsweeney** [comment]
It looks like Dompdf renders similar to web browsers for `border-collapse: collapse;`. I'd have to review the spec to see what it says about rendering borders in that situation. I would expect at most the table itself might get a radius but since the table cells themselves are collapsed there's no separate borders to render.

It might help to see an example of exactly what you're trying to achieve.

**Comment by theDyingMountain** [comment]
Okay so the problem has nothing to do with DOM PDF. I found a solution with this CSS Code:

```
table {
    width: 100%;
    border-spacing: 0; 
    border-collapse: separate;
}

table tr:last-child td:last-child {
    border-bottom-right-radius:10px;
}

table tr:last-child td:first-child {
    border-bottom-left-radius:10px;
}

table tr:first-child th:first-child,
table tr:first-child td:first-child {
    border-top-left-radius:10px
}

table tr:first-child th:last-child,
table tr:first-child td:last-child {
    border-top-right-radius:10px
}

table tr th:first-child,
table tr td:first-child {
   border-left: 2px solid #B2DBF4;
}
table tr:first-child th,
table tr:first-child td {
   border-top: 2px solid #B2DBF4;
}
```

**Comment by xexclusiv3x** [comment]
When adding background color to the above code, the color goes outside the radius. Any solution for this?
![border-radius-sample-01](https://user-images.githubusercontent.com/12998519/113800079-a640ff00-9799-11eb-8708-5e0fb4fe68e4.png)

**Comment by bsweeney** [comment]
@xexclusiv3x I don't think we've implemented any logic to apply the border radius to table elements. I went ahead and created a new issue related to that (#2434).

**Comment by rahultetame** [comment]
try this one it will work 

table {
   border-radius: var(--cui-border-radius) !important;
   overflow: hidden !important;
}

**Comment by rajanisar288** [comment]
> 

yeah its work
