### ISSUE TITLE
Image not found or type unknow (SOLVED)

### ISSUE THREAD

**Issue by biandishilaji** [dompdf/dompdf#2302]
My options:
```
setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => false])
```

Laravel 8

after update laravel 7 to laravel 8, domPdf can't find image from tag <img>

my blade : 

```
 <img src="{{url(asset(public_path("assinatura.png")))}}"
         alt="" style="width: 150px; height: 150px;">

    <img src="/srv/www/app/public/assinatura.png" class="css-class" alt="alt text">
    <img src="{{URL::asset(public_path('assinatura.png'))}}" alt="profile Pic" height="200" width="200">
```

i try multiples types of src, but none work

any resolution?

**SOLVED**

```
PDF::setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true, 'chroot' => public_path()])
->setPaper('a5', 'portrait')->loadView('Eobrigacoes::toPDF.simple_billings',
compact('simpleBillings', 'user', 'dateNow', 'company'))->download();
```

i'm use option 'chroot' = public_path() and works fine.
im my case, images are in public path, view in modules/module/views.

`<img src={{public_path('image.png')}} alt="">`

**Comment by hustlahusky** [comment]
I faced this issue too with 0.8.6. I have prepared the repository https://github.com/hustlahusky/dompdf-issues with example to reproduce this issue

**Comment by bsweeney** [comment]
Which version of Dompdf are you using? With the release of 0.8.6 resources pulled from the local filesystem have to be contained under the path specified by the Dompdf chroot option.

**Comment by biandishilaji** [comment]
> Which version of Dompdf are you using? With the release of 0.8.6 resources pulled from the local filesystem have to be contained under the path specified by the Dompdf chroot option.

Hello, 0.8.6 

i will check, thx

**Comment by biandishilaji** [comment]
> I faced this issue too with 0.8.6. I have prepared the repository https://github.com/hustlahusky/dompdf-issues with example to reproduce this issue

did you solve?
I used base64encode and it worked
but I don't think it's the best way to do this

**Comment by hustlahusky** [comment]
> did you solve?

downgrade to 0.8.5 for now.



> I used base64encode and it worked
> but I don't think it's the best way to do this

Yeah, I tried that too. But my images just too large to put them base64 encoded right into template.

**Comment by jamielsharief** [comment]
I faced this issue as well, once I set the chroot option, it started working again. 
![image](https://user-images.githubusercontent.com/20553479/100376962-b0dfd080-3010-11eb-8f91-5a26d8954dee.png)

**Comment by biandishilaji** [comment]
> I faced this issue as well, once I set the chroot option, it started working again.
> ![image](https://user-images.githubusercontent.com/20553479/100376962-b0dfd080-3010-11eb-8f91-5a26d8954dee.png)

im my case, the files are in public, I would chroot = public_path()?

**Comment by biandishilaji** [comment]
SOLVED

PDF::setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true, 'chroot' => public_path()])
                ->setPaper('a5', 'portrait')->loadView('Eobrigacoes::toPDF.simple_billings',
                    compact('simpleBillings', 'user', 'dateNow', 'company'))->download();

i'm use option 'chroot' = public_path() and works fine.
im my case, images are in public path, view in modules/module/views.

<img src={{public_path('image.png')}} alt="">

**Comment by jamielsharief** [comment]
> > I faced this issue as well, once I set the chroot option, it started working again.
> > ![image](https://user-images.githubusercontent.com/20553479/100376962-b0dfd080-3010-11eb-8f91-5a26d8954dee.png)
> 
> im my case, the files are in public, I would chroot = public_path()?

Yes, my `WEBROOT` points to /var/www/public

**Comment by biandishilaji** [comment]
> I faced this issue too with 0.8.6. I have prepared the repository https://github.com/hustlahusky/dompdf-issues with example to reproduce this issue

I managed to make it work, did you test the chroot method?

**Comment by biandishilaji** [comment]
chroot works fine

my options:

PDF::setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true, 'chroot' => public_path()])

**Comment by ThomasLandauer** [comment]
Duplicate of https://github.com/dompdf/dompdf/issues/2229
