### ISSUE TITLE
CSS parser breaks with bad CSS definitions

### ISSUE THREAD

**Issue by senyahnoj** [dompdf/dompdf#2303]
We encountered fatal errors with PHP 7.4 and dompdf v0.8.6 when we tried to generate a PDF from a page which had CSS in it from bootstrap-datepicker

For some reason their distributed CSS contained a strange background-color value of `{background-color:#fbf069\9}`

I have raised this as a separate bug with that project at https://github.com/uxsolutions/bootstrap-datepicker/issues/2598 but I also think that dompdf would benefit from doing some input parsing to protect itself from bad values.

The line in question in dompdf is in src/Css/Color.php where it is trying to parse the alpha portion of the RGBA value.

```      
 else if ($length == 9 && $color[0] === "#") {
     $alpha = round(hexdec(mb_substr($color, 7, 2))/255, 2);
```
The hecdec() throws a "Invalid characters passed for attempted conversion, these have been ignored" error (PHP 7.4 error). The reason is that the last 2 characters of the $color string of #fbf069\9 - i.e. the "\9" bit - are being passed to hexdec().

If you try hexdec('\\9') you'll see the error.

My suggestion is that the dompdf code does some checking to see if this is a valid alpha value. If it isn't then it should ignore the alpha.

**Comment by bsweeney** [comment]
We do have some safety checks elsewhere in the code but you're right that this would be a good place to add some more. We'll fix up for the next release. Feel free to submit a PR if you have a suggested code fix.
