### ISSUE TITLE
When the release with PHP 8 support will be ready?

### ISSUE THREAD

**Issue by fiullax** [dompdf/dompdf#2304]
The company where I work want update Wordpress to latest version (5.6), this version will support PHP 8 and we want to start use it. In many of our sites we user dompdf for generating pdf. 

Thanks in advance for the information!

**Comment by bsweeney** [comment]
Initial work on PHP 8 support is complete. You can use the php8-compat branch for testing. As for when ... I don't have a specific time frame but sometime in the next two weeks seems reasonable. I'm still waiting to see if anyone else has feedback on the changes made.

You can watch #2242 for updates.

**Comment by fiullax** [comment]
Thanks for the answer. I've tried to use the code of php8-compat in one of our site. It works like before, good job. Waiting for the release!

PS. Sorry for duplicate the issue, I have not seen the ticket🤦‍♂️

**Comment by bsweeney** [comment]
No worries on the duplicate, it happens.
