### ISSUE TITLE
[PHP 8.0] PDF data prints overlapped

### ISSUE THREAD

**Issue by Harverbo** [dompdf/dompdf#2308]
Data is being printed overlapped when I'm trying to print PDF. I'm using PHP version 8.0.

Everything was fine while I was using PHP version 7.4.

**Screenshot**
![image](https://user-images.githubusercontent.com/37876363/100623283-538d9d00-32f8-11eb-885e-48235b8719f3.png)

**Comment by bsweeney** [comment]
Dompdf won't support PHP 8 until the next release (likely to be 1.0.0). If you can't run under PHP 7.x then try out the code in the php8-compat branch. Follow #2242 for updates.
