### ISSUE TITLE
Matrix transform not working on SVG

### ISSUE THREAD

**Issue by raduvarga** [dompdf/dompdf#2325]
I am trying to generate a PDF which includes a SVG that has a matrix transform at its top level.
The SVG renders correctly in the browser, in the PDF however the matrix transform is not being applied.

In one specific example, the matrix transform "matrix(-1, 0, 0, 1, 0, 0)" is doing a flip on the x axis, however if I replace the matrix with a "scaleX(-1)" transform, this does get applied correctly in the PDF.
Inside the SVG, there are many other matrix transforms that are being respected, so it seems that just the top level one is not working. I have also tried to wrap the SVG with a div that contains that matrix transform, with no success.

Thoughts?

**Comment by bsweeney** [comment]
please re-post in [Phenx/php-svg-lib](https://github.com/PhenX/php-svg-lib)
