### ISSUE TITLE
Fatal error and deprecation warnings show on PHP 8 (Debian Buster) using DomPDF v0.8.6

### ISSUE THREAD

**Issue by szaqal83** [dompdf/dompdf#2328]
My pdf config is

$style = '* { font-family: "Encode Sans Semi Expanded", "DejaVu Sans Mono"; } h3 { text-align: center; } thead, tr.header td { font-weight: bold; } th { text-align: left; font-weight: 400; } table { border-collapse: collapse; width: 100%; font-size: 12px; } table, th, td { border: 1px solid grey; } th, td { padding: 10px; } tr.header { background-color: #f9f9f9; }';
		$html = '<html><head><style type="text/css">' . $style . '</style></head><body>abc</body></html>';

$dompdf = new Dompdf\Dompdf();
		$dompdf->set_paper('a4', $orientation);
		$dompdf->loadHtml($html);
		$dompdf->render();
		$dompdf->stream($filename, array('Attachment' => 1));

on PHP 8 results folowing deprecation errors and one Fatal error:

Deprecated: Required parameter $dompdf follows optional parameter $paper in /.../dompdf/dompdf/src/Adapter/CPDF.php on line 183

Deprecated: Required parameter $dompdf follows optional parameter $paper in /.../dompdf/dompdf/src/Canvas.php on line 27

Deprecated: Required parameter $img follows optional parameter $w in /.../dompdf/dompdf/lib/Cpdf.php on line 5546

Deprecated: Required parameter $data follows optional parameter $w in /.../dompdf/dompdf/lib/Cpdf.php on line 5892

Deprecated: Required parameter $imageWidth follows optional parameter $w in /./dompdf/dompdf/lib/Cpdf.php on line 6236

Deprecated: Required parameter $imageHeight follows optional parameter $w in /./dompdf/dompdf/lib/Cpdf.php on line 6236

Deprecated: Required parameter $imgname follows optional parameter $w in /./dompdf/dompdf/lib/Cpdf.php on line 6236

Deprecated: Required parameter $pattern_name follows optional parameter $corner_style in /./dompdf/dompdf/src/Renderer/AbstractRenderer.php on line 848

Fatal error: Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /.../dompdf/dompdf/src/Css/Style.php:3304

**Comment by neoteknic** [comment]
you can use the devellop branch. I dont know when the new version will be released.

**Comment by bsweeney** [comment]
FYI new version should be out in a few days. You can see full discussion on the issues in #2242.
