### ISSUE TITLE
Images doesn't appear in the pdf

### ISSUE THREAD

**Issue by Heba-Farid** [dompdf/dompdf#2340]
I want to generate a pdf when someone clicks on the generate pdf button. This pdf contains the image of the pile of squares highlighted corresponding to what the user highlighted in the image on the web page. Whenever I try to include the svg I get a blank pdf. Not only SVG, whenever I try to include any image I get "image not found or type unknown in my pdf"

trial.html:
```
   <?php
     use Dompdf\Dompdf;

    use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\SMTP;
    use PHPMailer\PHPMailer\Exception;
    
    

    if(isset($_POST['send']))
    {

     $output = ' <!DOCTYPE html>
                <svg  width="564" height="409" >
                    <image
                        href="https://media.geeksforgeeks.org/wp-content/uploads/unique-rectangles-formed-using-n-unit-squares.png"
                        width="564"
                        height="409"
                    />
                    <polygon title="1" points="21,385 24,309 100,309 101,385" />
                    <polygon title="2" points="102,305 23,304 23,228 101,227" />
                    <polygon title="3" points="103,225 26,228 25,149 99,151" />
                    <polygon title="4" points="103,147 102,65 25,70 23,147" />
                </svg>';
      //   $output .= '<img src="data:image/svg+xml;base64,'.base64_encode($svg).'"  width="100" height="100" />';

     require 'C:\Users\Main\vendor/autoload.php';  

     $cart_body='<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Squares</title></head><body><p>Test Printing...</p></body></html>';
             $dompdf = new Dompdf();
             $dompdf->load_html($output);//body -> html content which needs to be converted as pdf..
             $dompdf->render();
             $dompdf->stream("sample.pdf");

     }?>
```

script.js:
```
    function handleSVGClick(event) {
    if (event.target.tagName === "polygon") {
      event.target.style.fill = `hsl(${Math.random() * 360}, 90%, 60%)`;
    }
   }
```

style.css:
```
   polygon {
    stroke-width: 2px;
    stroke: #333;
    fill: transparent;
  }
```

**Comment by bsweeney** [comment]
A couple of issues:

1. Dompdf does not yet support embedded SVG documents (#320 would be the closes issue I guess), so you need to use the base64 encoded data-uri logic that you have commented out (with some variable reference tweaks).
2. The SVG rendering library we use ([PhenX/php-svg-lib](https://github.com/phenx/php-svg-lib/)) is looking specifically for "xlink:href" for the image reference. Obviously not as flexible as a web browser in some respects.

Try something like the following:

```
$svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 564 409">
    <style>
    polygon {
        stroke-width: 2px;
        stroke: #333;
        fill: transparent;
      }
    </style>
    <image xlink:href="https://media.geeksforgeeks.org/wp-content/uploads/unique-rectangles-formed-using-n-unit-squares.png" width="564" height="409" />
    <polygon title="1" points="21,385 24,309 100,309 101,385" />
    <polygon title="2" points="102,305 23,304 23,228 101,227" />
    <polygon title="3" points="103,225 26,228 25,149 99,151" />
    <polygon title="4" points="103,147 102,65 25,70 23,147" />
</svg>';
$output = '<img src="data:image/svg+xml;base64,'.base64_encode($svg).'"  width="100" height="100" />';

$dompdf = new Dompdf();
$dompdf->load_html($output);
$dompdf->render();
$dompdf->stream("sample.pdf");
```

**Comment by Heba-Farid** [comment]
@bsweeney The problem is not in SVGs only. All images doesn't appear. I tried removing SVG  and replacing it with normal image but still it didn't appear.

**Comment by bsweeney** [comment]
You didn't provide a sample of the non-SVG image usage so I can't comment on what may be going on there. Have you read through the wiki (namely the [requirements](https://github.com/dompdf/dompdf/wiki/Requirements) and [usage](https://github.com/dompdf/dompdf/wiki/Usage) pages)? You haven't enabled remote resource support in your sample so that may be impacting your ability to load images. If the images are local you also have to set the chroot option appropriately.

**Comment by Heba-Farid** [comment]
@bsweeney What is the chroot option?

**Comment by bsweeney** [comment]
The [chroot option](https://github.com/dompdf/dompdf/blob/v1.0.1/src/Options.php#L46..L63) specifies the path from which HTML documents and any resources references by it (images or stylesheets) may be accessed through the local file system (as opposed to a web server).

For example, if your files are located under the /inet/www file system path then you would do something like the following:

```
$options = ['chroot' => '/inet/www'];
$dompdf = new Dompdf();
```

**Comment by ThomasLandauer** [comment]
Probably a duplicate of https://github.com/dompdf/dompdf/issues/2229

**Comment by Heba-Farid** [comment]
@bsweeney This is the example of the code using normal image and what I get is hello only and the rest of the pdf is empty

trila.html:
`<?php
require 'vendor/autoload.php';  
    use Dompdf\Dompdf;
    use Dompdf\Options;
    use Dompdf\Adapter\CPDF;
 $output = '<!DOCTYPE html>
                <div>
                <p>Hello</p>
                </div>
                <img href="https://media.geeksforgeeks.org/wp-content/uploads/unique-rectangles-formed-using-n-unit-squares.png" width="564" height="409"/>';
 $dompdf = new Dompdf();
 $dompdf->load_html($output);//body -> html content which needs to be converted as pdf..
 $options = new Options();
 $options->setIsRemoteEnabled(true);
 $dompdf->render();
 $dompdf->stream("sample.pdf"); //To popup pdf as download?>

`

**Comment by Heba-Farid** [comment]
@bsweeney I don't know why my code doesn't want to appear in the above comment

**Comment by bsweeney** [comment]
Markdown formatting issues. I fixed it up for you.

As for your code sample, the IMG element uses "src" not "href" to reference images. If you fix that syntax error does the image show up?
