### ISSUE TITLE
Option "chroot" does not work for multiple paths

### ISSUE THREAD

**Issue by neonella** [dompdf/dompdf#2341]
Current "chroot" check in src/Image/Cache.php will always fail if chroot option has more than one path. Current logic requires an image to be within ALL provided paths, which is impossible, instead of checking that image is located within al least one allowed path. My proposal is to replace the code in "src/Image/Cache.php" from this:

```
$chrootError = false;
if (!is_array($chroot) || count($chroot)<1){
    $chrootError = true;
} else {
    foreach($chroot as $chrootPath){
        $chrootPath = realpath($chrootPath);
        if ($chrootPath === false || strpos($realfile, $chrootPath) !== 0) {
            $chrootError = true;
        }
    }
}
if($chrootError){
    throw new ImageException("Permission denied on $resolved_url. The file could not be found under the directory's specified by Options::chroot.", E_WARNING);
}
```

to this:

```
$chrootValid = false;

foreach(((is_array(($chroot ?? null))) ? $chroot : []) as $chrootPath) {
	if (($chrootPath = realpath($chrootPath)) !== false && strpos($realfile, $chrootPath) === 0) {
		$chrootValid = true;
		break;
	}
}

if ($chrootValid !== true) {
	throw new ImageException("Permission denied on $resolved_url. The file could not be found under the directory's specified by Options::chroot.", E_WARNING);
}
```

I already implemented that change on my end in production environment and it works as expected. Before I had to simply comment the exception to allow images from multiple paths.

**Comment by bsweeney** [comment]
Ack! Of course you are correct. Sorry to have missed that during review. We'll release an update to address the issue.

**Comment by bsweeney** [comment]
FYI until we release an update anyone running into this issue can revert back to using a single path for the chroot.

**Comment by bsweeney** [comment]
Mostly went with your suggested fix, with one small change to ensure that the Options class always returns an array. Requires a bit less shorthand logic, which I try to avoid for Dompdf (for the most part).

**Comment by neonella** [comment]
Thank you so much for fixing that!
