### ISSUE TITLE
bug link on the same domain

### ISSUE THREAD

**Issue by ismanu** [dompdf/dompdf#2343]
Hi,
happy new year to you all !

found a bug (debian jessie , php 7.2)  with links if they are on the same domain name which we launched the generation of the pdf. 

example : 
you call this type of url, that will generate the pdf : 

`http://mydomain.com/generate.pdf`

and this code :
```
$html = '<html><body><a href="http://mydomain.com/contact.php" target="_blank">test<a></body></html>';
$dompdf = new Dompdf();        
$dompdf->loadHtml($html);
$dompdf->render();
$dompdf->stream('myfile.pdf');

```
the link in the generated pdf file will be "like"/replaced by : 

`space/vhosts/mydomain/current/contact.php`

dompdf  render method seems replace the domain name :

`<html><body><a href="space/vhosts/mydomain/current/contact.php" target="_blank">test<a></body></html>`

played with setOptions and isRemoteEnabled / setIsRemoteEnabled but nothing change.

a workarround (for me) was to change the case of a letter in the domain name like : 

`$html = '<html><body><a href="http://Mydomain.com/contact.php" target="_blank">test<a></body></html>';`

with this... dompdf preserve the href link 

have a good day !

manu

**Comment by bsweeney** [comment]
I'm not seeing the same thing when trying out your example on my own site (http://eclecticgeek.com/generate.php). Which version of Dompdf are you using?
