### ISSUE TITLE
Ordered list item with roman numeral higher than 3999 produce "out of index" text

### ISSUE THREAD

**Issue by bsweeney** [dompdf/dompdf#2348]
Consider this bit of HTML:

```
<ol type="i">
<li value="50000">50000</li>
</ol>
```

Web browsers display the arabic nuber above 3999, Dompdf displays the text "(Index out of range)" or nothing at all.

According to the English language Wikipedia as it stands at the time of this PR (https://en.wikipedia.org/wiki/Roman_numerals#Standard_form), 3999 is the largest number that can be represented in the standard form of roman numerals.

bug sourced after researching Dompdf handling after reviewing tecnickcom/TCPDF#315

**Comment by Mellthas** [comment]
See the linked PR, I think that should solve it, if I didn't miss anything.
