### ISSUE TITLE
Table colspan and rowspan attributes

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#235]
_Original author: craig.ph...@ntlworld.com (February 11, 2011 11:44:17)_

Using the beta, the table (code below) uses colspans to merge cells, in the browser it displays as expected, but in the PDF it stretches passed 100% (off the page), I believe the problem to be with the colspan attributes.

```
<table width="100%">
<tr>
<td colspan="2" style="border:0px; text-align:left;">SECURITY CLASSIFICATION: UNCLASSIFIED</td>
<td colspan="2" style="border:0px; text-align:right;">EXPORT CONTROL: NOT LISTED</td>
</tr>
<tr>
<td width="33%"></td>
<td width="43%" valign="top" align="center"><b><font size="2" color="red">ENGINEERING CHANGE ORDER</font><br><br><br><font size="3" color="blue">ASTRA 2E and 2F</font></b></td>
<th width="11%">REFERENCE</th>
<td width="13%">AST2.ECO.00810.DP.P.ASTR</td>
</tr>
</table>
```

Many Thanks

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=229_

**Comment by Mellthas** [comment]
The sample renders properly now.
