### ISSUE TITLE
Internal links do not work when content wraps to a new page

### ISSUE THREAD

**Issue by tpformybh** [dompdf/dompdf#2356]
e.g.
```
<a href="#section">Section Name</a>
...
<div id="section">...</div>
```
The link should link to the section, and dompdf renders it as an anchor, but it isn't actually linked to anywhere.

PHP 7.4

--- 
Edit
After some digging the root of the problem is if the content wraps over another page, then the link does not work.

**Comment by tpformybh** [comment]
Just to add to this: I believe using `<a name="section">&nbsp;</a> does work if content wraps on a new page.

**Comment by bsweeney** [comment]
Possible cause is an attempt to prevent duplicate named destinations.
