### ISSUE TITLE
URL-encoded text in links is decoded when written to PDF

### ISSUE THREAD

**Issue by AldivioAlves** [dompdf/dompdf#2357]
the storage firebase returns links for donwload files with this formatt (when we set folders for files):
https://firebasestorage.googleapis.com/v0/b/bucket_name.appspot.com/o/folder_name%2Fother_folder_name%2Ffile.extension

the problem is when the pdf is generate, the link of file is converted in: 
https://firebasestorage.googleapis.com/v0/b/bucket_name.appspot.com/o/folder_name/Fother_folder_name/file.extension

"%2F" => "/"

the link don`t work anymore after conversion

I need some sugestion about this problem pleasee

**Comment by bsweeney** [comment]
It does appear that some level of decoding is happening, we'll have to take a look. In the meantime, you can work around the issue by double-encoding any encoded characters. Something like ...

```
<a href="https://firebasestorage.googleapis.com/v0/b/bucket_name.appspot.com/o/folder_name%252Fother_folder_name%252Ffile.extension">
https://firebasestorage.googleapis.com/v0/b/bucket_name.appspot.com/o/folder_name%2Fother_folder_name%2Ffile.extension
</a>
```

**Comment by okilux** [comment]
Hi i got the same issue : 
https://portal.payconiq.com/qrcode?f=PNG&s=M&c=https://payconiq.com/t/1/6135ddf1b0XXX10006076a7a%3FD%3DFacture-00269%26A%3D2260

The %26A%3D2260 is changing to : &A=2260
I dont want to be decoded somewhere, how to ? 
Any idea ?

**Comment by bsweeney** [comment]
reposting my comment from [2904](https://github.com/dompdf/dompdf/issues/2904#issuecomment-1143642109): 
Looks like that has always been part of the code ([fb4e70d](https://github.com/dompdf/dompdf/commit/fb4e70d0737f96c860bc3ffb975c1481558ab4ae)) and I'm not entirely sure why. Based on current handling of links I'm going to change up those methods to place links as-is. They're already processed as part of document parsing so I don't believe there's need for additional processing at this stage.
