### ISSUE TITLE
 text-overflow: ellipsis is not working

### ISSUE THREAD

**Issue by nongnapat-s** [dompdf/dompdf#2361]
Hello,
I've tried to use `text-overflow: ellipsis` on my pdf file but it's not working. How can I do?
// style .css
`.order {
   overflow: hidden;
    text-decoration: none;
    white-space: nowrap;
    text-overflow: ellipsis;
}`

**Comment by bsweeney** [comment]
Dompdf does not yet support this option. Supported styling is listed in the [CSS compatibility chart](https://github.com/dompdf/dompdf/wiki/CSSCompatibility).

Please follow #505 for any updates.
