### ISSUE TITLE
bug, with php foreach as associative arrays.

### ISSUE THREAD

**Issue by devorel** [dompdf/dompdf#2363]
https://github.com/dompdf/dompdf/blob/0ccafeb142dd04f556b43f1e8b5541aa06de1c26/src/Cellmap.php#L415

it's return error if you use as associative arrays.

`@foreach($categories as $category => $products) `

it's can't read the key ($category ) , it's read it just if the array is order and integer .

my change will solove it .
replace the line 

```
        foreach ($rows as $i) {
            if (!isset($this->_rows[$i])) {
                continue;
//                throw new Exception("The row #$i could not be found, please file an issue in the tracker with the HTML code");
            }
            $h += $this->_rows[$i]["height"];
        }
```

**Comment by bsweeney** [comment]
The error relates to the structure of your HTML, not your use of an associative array to generate that HTML. Suggest you run your HTML through a validator and, if it checks out, post a sample here so we can see what exactly is causing the issue.
