### ISSUE TITLE
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

### ISSUE THREAD

**Issue by khoebeke** [dompdf/dompdf#2364]
Hi, since I did an update to the newest drupal 9.1.4, I have an error:

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /customers/0/3/1/mysite.be/httpd.www/D9/vendor/dompdf/dompdf/src/Dompdf.php on line 600 Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /customers/0/3/1/mysite.be/httpd.www/D9/vendor/dompdf/dompdf/src/Dompdf.php on line 621 The website encountered an unexpected error. Please try again later.

Can somebody help me with this?
I already did a composer update but no success

**Comment by bsweeney** [comment]
You must be using an older version of Dompdf. We addressed these issues in, I believe, 0.8.3. See #1822.

Make sure you're not pinned to a particular version of Dompdf, either directly in your composer configuration or because of a dependency requirement.
