### ISSUE TITLE
Rendering 20 blank pages when using large text with fixed header and footer

### ISSUE THREAD

**Issue by maxa22** [dompdf/dompdf#2365]
I'm trying to create a memorandum for a firm. It is suppose to have a header, footer and main text. Problem occurs when the main text is larger than one page, dompdf renders 20-25 blank pages. The problem is that the main text can be formated by the user, it can have larger font size, multiple blank rows, lists...
How to add page break when i don't know when the main text is 2-3-4 pages long?

**Comment by bsweeney** [comment]
Can you share a sample of the document structure. This is typically seen when an individual table cell is too large to fit on a page.

**Comment by maxa22** [comment]
[result.pdf](https://github.com/dompdf/dompdf/files/5952899/result.pdf)
And the text should be in between.

**Comment by bsweeney** [comment]
I'll need to see a sample of the actual HTML document. It looks like this is, in fact, probably a table issue. For example, if your HTML is something like the following:

```
<table>
<tr><td>header</td></tr>
<tr><td>body with lots and lots of content</td></tr>
<tr><td>footer</td></tr>
</table>
```

Then you'll run into this issue. Based on that PDF you can probably use a DIV-based structure without causing issues.

But, again, I'd need to see a sample of your HTML to say for sure.

**Comment by maxa22** [comment]
I used floats in footer and forgot to use clean after, that was the problem.

**Comment by bsweeney** [comment]
Interesting ... might be something worth looking at for us. Glad you were able to determine the cause.
