### ISSUE TITLE
td with no dim spec breaks table rendering

### ISSUE THREAD

**Issue by Orcozzio** [dompdf/dompdf#2366]
Hi Devs,
I'm using the 1.0.2 version of Dompdf with PHP Version 7.2.24
I need to build a simple html page ready to be printed as PDF document in A4.

Preview of the upper part of the page in Chrome:
![image](https://user-images.githubusercontent.com/7241861/107121004-6096b180-6890-11eb-842b-cb9e8eea8bfa.png)

...the result in AcroReader:
![image](https://user-images.githubusercontent.com/7241861/107121099-e9ade880-6890-11eb-805d-fec795488813.png)

the html page saved as text:
[html_page.txt](https://github.com/dompdf/dompdf/files/5937009/html_page.txt)

I'm using this function to configure Dompdf:
```
function d_getDomPdfObj($options=[])
{

	//  PDF settings
	$def_options = [
		'default_paper_size'=> 'a4',
		'def_paper_orientation'=> 'portrait',	// 'portrait' or 'landscape'
		'dpi'=> 96,
		'font_height_ratio'=> 1,
		'is_php_enabled'=> true,
		'is_remote_enabled'=> true,
		'is_javascript_enabled'=> true,
		'enable_html5_parser'=> true,
		'enable_font_subsetting'=> true,
	];
	$pdf_options = array_merge($def_options, $options);

	//  Create PDF
	$DomPdfObj = new \Dompdf\Dompdf( new \Dompdf\Options($pdf_options) );
	$DomPdfObj->set_paper($pdf_options['default_paper_size']
		, $pdf_options['def_paper_orientation']);

	return $DomPdfObj;
}
```

I can easily work around this issue for what I need in my project, but I wanted to leave you a detailed feedback about what it looks like something wrong in the table rendering of Dompdf.
Let me know if you need more details.

PS: someone may find strange width: 215.884mm; for A4... yes, it should be 210mm, but that is about another issue I will report to you the next time.

Thank all of you for your work
cheers

**Comment by Mellthas** [comment]
This is fixed by #2497, commit 50ad01984d07c29c63ea66bef3596b99a69acaa0, due to a bugfix in `AbtractFrameReflower::get_min_max_width` (the “degenerate” case handling ignored explicitly specified dimensions). I can put up a separate PR just for that fix, if need be.

The alignment on the top right box being ignored is #1761.
