### ISSUE TITLE
https images broken

### ISSUE THREAD

**Issue by shah-ut** [dompdf/dompdf#2369]
I use cloudflare on my site. Cloudflare has an option to make your site more secure by forcing https across the whole site. 

When this option is on, all images on dompdf that are https get sent as a square with an X through it. 

The only fix I could find was to either use a base64 image or to manually change the image URL back to http. Both are not ideal. The original image URL is an https address. Currently it is not working as https in dompdf.

**Comment by bsweeney** [comment]
Do you see any errors in your PHP logs? What is the actual URL you're using? Could it be that the request never goes through Cloudflare? And if that's the case does your local web server have HTTPS enabled?

**Comment by shah-ut** [comment]
No errors in logs.

URL is "
https://undergroundtracks.com/wp-content/uploads/2020/12/UT-Text-Logo-as-O-clean-Black.png
">

Not sure about the request routing but it worked fine a couple weeks back.
After I changed a setting in Cloudflare which "forces https" this broke.

https is enabled across my site.

**Comment by crusnac** [comment]
I am having the same issue.  Anytime, I am trying to load a HTTPS Image or Stylesheet, it's failing. 
![Screen Shot 2021-02-10 at 3 24 50 PM](https://user-images.githubusercontent.com/5386135/107586201-576d5380-6bb4-11eb-9636-c78c2003364c.png)

**Comment by zaibatsu777** [comment]
same issue.. Any luck with that?
- isRemoteEnabled is true
- Curl is on

Still presenting with the same  error.

**Comment by bsweeney** [comment]
If HTTP works but not HTTPS I don't have a lot of ideas. Have you tried retrieving the same image directly using a simple PHP script and `file_get_contents` and/or the relevant curl functions?

**Comment by shah-ut** [comment]
To be honest, that’s well over my head.  Dompdf is intergrated into a
plug-in for Wordpress that is use. The plug-in dev and I discovered the
issue and a small work around but he had no other suggestions. I am unable
to execute what you mentioned.

**Comment by crusnac** [comment]
I setup a quick test 

```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$image = 'https://domain.com/dc/img/headerimage.jpg';
// Read image path, convert to base64 encoding
$imageData = base64_encode(file_get_contents($image));

// Format the image SRC:  data:{mime};base64,{data};
$src = 'data: '.mime_content_type($image).';base64,'.$imageData;

// Echo out a sample image
echo '<img src="' . $src . '">';
?>
```


and I got the following error:


```
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /Repos/dc/test-image.php on line 14

Warning: file_get_contents(): Failed to enable crypto in /Repos/dc/test-image.php on line 14

Warning: file_get_contents(https://domain.com/dc/img/headerimage.jpg): failed to open stream: operation failed in /Repos/dc/test-image.php on line 14

Warning: mime_content_type(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /Repos/dc/test-image.php on line 17

Warning: mime_content_type(): Failed to enable crypto in /Repos/dc/test-image.php on line 17

Warning: mime_content_type(https://domain.com/dc/img/headerimage.jpg): failed to open stream: operation failed in /Repos/dc/test-image.php on line 1
```

**Comment by bsweeney** [comment]
@shah-ut it's probably a system issue but can't really say for sure without some further investigative work on your end. If the plugin-dev has the bandwidth they should be able to help isolate the cause. But at least you have a work-around for now.

@crusnac certificate verification failure is definitely a more low-level issue. It's possible your server is configured to use a non-public cert for particular endpoints. OK for testing but not for production use. If you're not using curl you can [set a custom context](https://github.com/dompdf/dompdf/wiki/Usage#sethttpcontext) to see if disabling verification fixes HTTS image loading.

```
$context = stream_context_create([ 
	'ssl' => [ 
		'verify_peer' => FALSE, 
		'verify_peer_name' => FALSE,
		'allow_self_signed'=> TRUE 
	] 
]);
$dompdf->setHttpContext($context);
```

If your installation utilizes curl instead of file_get_contents (used when allow_url_fopen is false) this won't work since we haven't yet built out support for customized contexts for curl just yet.

And, again, I wouldn't recommend in production.

**Comment by Nexample-G** [comment]
Follow this 100% working
https://youtu.be/R3OhMI9P4-s

**Comment by MattGrdinic** [comment]
@Nexample-G For **local** images this fix isn't very practical, as it requires you to constantly apply a "questionable" code change with every update. 

A better solution will be to provide a proper setup in the DOMPDF options block as:

```
use Dompdf\Dompdf;
use Dompdf\Options;

// Options
$options = new Options();
$options->set('chroot', './');
$options->set('isRemoteEnabled', false);
[...]
```

Assume three images:

```
<img src="no-image.png"  />
<img src="../no-image.png" />
<img src="../../no-image.png" />
```

$options->set('chroot', './');` -> the first image shows. 
$options->set('chroot', '../');` -> the first _and_ second images show. 
$options->set('chroot', '../../');` -> _all_ three images show. 

The pattern is hopefully clear -- ./ means DOMPDF can pull images from the same directory as the source page and any child of that, ../ means allow any image from one level up from the calling page (and of course any children of), and so on. 


That said unfortunately DOMPDF exhibits strange behavior with images in general. So for example using the code above this localhost server call fails:

`<img src="https://pro/output/forms/header-logo.png" />`

Whereas this works:

`<img src="https://www.rackforms.com/images/index/reasons/sprite-reasons.png" />`

...so long as we use:

`$options->set('isRemoteEnabled', true);`

Also, Webp image fail outright with an exception. 

So yeah, bit of a mixed bag. We've got well-intentioned security code mixing it up with not-so-great documentation and missing features. Still, a great library so here's hoping for the best!

**Comment by bsweeney** [comment]
@MattGrdinic curious about the name-only URL. As far as I know the server-name version of the URL should work so long as PHP can read it. But I don't have a system on which I can check that. What error do you get? And does that URL work with plain PHP?

Also, WebP support was added with v1.1.0, which was just released. Support is currently dependent on the back end used. Are you using the latest version?

**Comment by MattGrdinic** [comment]
Hey Brian, 

So yes on the URL working in plain PHP and my bad on the webp support -- I updated to 1.1.0 halfway through my tests and never re-tested to check the specific error messages. Said as I can confirm a different error now:

`Uncaught Dompdf\Exception: Function imagecreatefromwebp() not found.`

I have GD installed but this is the macOS built-in version of PHP 7.3.29, and I appear not to have Webp compiled. I'd fully expect this part to work if I did, so please accept my apologies!

I'll circle back when I have some time and see about that localhost URL.

**Comment by bsweeney** [comment]
@MattGrdinic no worries you never know how things are going to play out once you release something live. Hopefully the most you need is to rebuild PHP with WebP support. Something we might need to document.

Thanks for planning to follow up on the localhost support.
