### ISSUE TITLE
bad image URLs filling temporary directory up with empty files

### ISSUE THREAD

**Issue by bradbulger** [dompdf/dompdf#2377]
Cache::resolve_url() uses tempnam() to create a $resolved_url value for remote images before it tries to load the image. If it is later unable to get a valid image, it throws an exception. The temporary file created by tempnam() is never removed. Because of some weird behavior by our CMS, we ended up with hundreds of these empty files.

We could maybe add code to the catch block to remove it?

**Comment by bradbulger** [comment]
In trying to force cases where the temporary file is left undeleted, I had times where an exception was being thrown in resolve_url() and times where it wasn't. So I put the check outside of the try/catch block. Also, I could do a file_exists() check instead of suppressing warnings from the unlink() call if that seems better.

**Comment by Nexample-G** [comment]
Follow this
https://youtu.be/R3OhMI9P4-s
