### ISSUE TITLE
background-image:none fails with absolute URL in BASE tag in 0.8.6

### ISSUE THREAD

**Issue by bradbulger** [dompdf/dompdf#2378]
I've found in 0.8.6 that a document with an absolute URL in BASE (eg https://localhost/reports/green) ends up processing background-image values as absolute URLs as well, including when the value is "none". It tries to load https://localhost/reports/green/none as an image, which fails.

If BASE is changed to a relative URL (eg /reports/green) then in the Block render, the style->background_image value is just "none" and it doesn't try to load it.

I know there are other issues somewhat related to this but I couldn't figure out any direct application of them to this problem.

**Comment by bsweeney** [comment]
There was an issue with parsing background image properties in 0.8.6 (#2288). That issue was addressed for the 1.0.x release (2ee96e2). Recommend you try the latest release (currently 1.0.3).

**Comment by bradbulger** [comment]
That indeed fixes it, thanks.
