### ISSUE TITLE
Hyper Link is not working in DOM PDF Version 0.8.3

### ISSUE THREAD

**Issue by sanowar-ali** [dompdf/dompdf#2379]
Sample HTML

```
.row {
  display: -ms-flexbox;
  display: flex;
  -ms-flex-wrap: wrap;
  flex-wrap: wrap;
  margin-right: -7.5px;
  margin-left: -7.5px;
}


<div class="row" style="padding:10px 0px 0px 10px;width:100%;page-break-inside: avoid;">
    <table>
        <tr>
            <td>
                  <a href="https://google.com">Visit Website</a>                                 
             </td>
        </tr>
    </table>
</div>
```

Sample PDF
[Bali - BUnny - 22 February 2021-2.pdf](https://github.com/dompdf/dompdf/files/6020111/Bali.-.BUnny.-.22.February.2021-2.pdf)

**Comment by bsweeney** [comment]
Your sample HTML seems to work OK for me. There may be a combination of styling that are causing an issue. You might also mouse around the linked text because there have been issues with the link not fully covering the text (#1803).

**Comment by sanowar-ali** [comment]
Hi @bsweeney  thanks for the quick reply.
I have attached the full html here in zip format. 
[sample_quote.html.zip](https://github.com/dompdf/dompdf/files/6026952/sample_quote.html.zip)

 Can you point out the styling which causing the issue?  There are only one anchor tag used in the html file.

**Comment by bsweeney** [comment]
Still unable to reproduce the issue when I render it through the [debug helper](https://eclecticgeek.com/dompdf/debug.php). You might want to upgrade Dompdf to 1.0.3 if you are able.

**Comment by sanowar-ali** [comment]
I can't execute my sample html on debug helper. How to execute this on debug helper?
Is there any issue on 0.8.3 version? I can't upgrade  to 1.0.3 as it requires higher PHP version as well. 
Is there any other options?

**Comment by bsweeney** [comment]
You would select the "Manual Entry" tab to enter the HTML, then the "Options" tab to specify the Dompdf version.

I ran it for you here: http://eclecticgeek.com/dompdf/debug.php?identifier=bbd7fd0d7369f72bab964cd178f1a9bc

**Comment by sanowar-ali** [comment]
It's working fine in debug helper.
But in actual it's not working. My server PHP Version is 7.0.15 and debug helper PHP version is 7.1.
Can it be the main reason behind this?
![Screenshot 2021-02-25 at 10 58 45 AM](https://user-images.githubusercontent.com/74847521/109108071-d3d96800-7758-11eb-8834-3eca81ed0f18.png)

**Comment by bsweeney** [comment]
Possible, but I'm not sure. I'll have to test locally with an older version of PHP to see what happens.
