### ISSUE TITLE
mixed arabic number with english

### ISSUE THREAD

**Issue by anood** [dompdf/dompdf#2382]
Dear team

when I extract the data from the database and using this font dejavu sans it will display on pdf with mixed number (arabic and English)
in the style I put 
*{ font-family: DejaVu Sans !important;}
I don't know why it mix the numbers
[https://drive.google.com/file/d/1URU-QwFzHw38JHpeGd4f98RmujH9HBGt/view](url)

**Comment by bsweeney** [comment]
Which version of Dompdf are you using? And can you provide a sample of the HTML you're rendering?

**Comment by anood** [comment]
I'm using 0.8.5

﻿<html>
    <head>

        <meta http-equiv="Content-Type" content="text/html;" charset="utf-8" />



        

        <style>


        *{ font-family: DejaVu Sans !important;}




            th {
                text-align: right;

                border: solid 1px black;
                font-size: 12px;
            }

            table {
                width: 100%;
                text-align: right;


            }

            th, td, tr {
                text-align: right;
                /* direction: rtl; */
                float: right;
            }

             tr{ text-align: right;
                }



        </style>
    </head>

    <body >

        
        <div class="all_middle ">
            <div class="container middle">
                <div class="row" style="width: 100%; margin: auto; direction: rtl;">

                    <div style=" width: 400px; margin:  10px auto;">
                        <a href="<?php echo site_url('/'); ?>"><img src="<?php echo base_url(); ?>/public/frontend/images/logo.png" alt="<?php echo $this->lang->line('Oman_Development_Bank'); ?>"/></a>
                    </div>
                    <table>
                        <tr>
                            <td>
                                <h1 style="text-align: center;"><?php echo $this->lang->line('request_a_loan'); ?></h1>
                            </td>
                        </tr>
                    </table>
                    
                    <div class="box box-info">
                        <div class="box box-primary">

                            <div class="box-body">

                                <div class="col-md-12">


                                    <table>
                                        <tr>
                                            <td>
                                                <hr>
                                            </td>
                                        </tr>
                                        <tr><td> <strong>البيانات الشخصية</strong></td></tr>
                                    </table>

                                    <table>
                                        <tr>
                                            <td style="color:blue;">
                                                <?php echo $this->lang->line($loan_row['gender']); ?><b style="color:black; ">الجنس : </b>
                                            </td>
                                            <td>
                                                <span style="color:blue; "><?php echo $loan_row['applicant_id_no']; ?></span><b style="color:black;">رقم البطاقة الشخصية: </b>
                                            </td>
                                        </tr>

                                        <tr>
                                            <td><span id="age"></span><b> </b></td>
                                            <td><span style="color:blue; "><?php echo $loan_row['birth_date']; ?></span> <b style="color:black;"> تاريخ الميلاد :  </b></td>

                                        </tr>


                                        <tr>
                                            <td colspan="2" style="color:blue; ">
                                            افراد  <span style="color:blue; "><?php echo $loan_row['sons_no']; ?></span>
                                                <b style="color:black;">عدد افراد المعالين :</b>
                                            </td>

                                        </tr>
                                    </table>



                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        

    </body>

</html>

**Comment by anood** [comment]
I fixed it by updating ar-php

**Comment by bsweeney** [comment]
So, processing the text through ar-php prior to rendering? Makes sense. We are working on an update to support text shaping and limited directionality, though the work is stalled right now.

**Comment by anood** [comment]
yes.
we develop this library to support complex text layout.
you can use it

https://github.com/HOST-Oman/libraqm

**Comment by bsweeney** [comment]
@anood thanks for the pointer. We've been using https://github.com/tecnickcom/tc-lib-unicode in the current development but I'm always open to looking at other libraries.

**Comment by RiadhVet** [comment]
> 
> 
> I fixed it by updating ar-php

How ?
