### ISSUE TITLE
new Dompdf() causing HTTP ERROR 500

### ISSUE THREAD

**Issue by perina98** [dompdf/dompdf#2384]
Hi, Iam using PHP 7.2 and dompdf 1.0.2. After migrating to other server with the same PHP version, Iam getting HTTP ERROR 500 on this line of code `$dompdf = new Dompdf();` . Any suggestions ?

**Comment by bsweeney** [comment]
What kind of exception does PHP report?

**Comment by perina98** [comment]
Honestly Iam not sure... I dont have access to the server log or anything like that. However.. I found out that one requirement MBString php extension is disabled. Could it be caused by that ? I will be writing message to server administrator.

**Comment by bsweeney** [comment]
That would definitely cause an issue. And there is a call to one of the MBString methods as part of constructing the object, so that should at least get you past instantiating the class.
