### ISSUE TITLE
Cant get my custom fonts to work

### ISSUE THREAD

**Issue by dunchaseme** [dompdf/dompdf#2389]
Hi, I using custom font for dompdf, but when I print out, there are few issues
1. font-weight with less than 400 not working, and even if I use font-weight: lighter also not able to get it work.
2. Inconsistent of letter spacing on custom font.
![bug_2](https://user-images.githubusercontent.com/23028389/109375970-1d15ed00-78fc-11eb-8aa1-75ae74274565.png)
3. It printed our barcode-like lines
![bug_1](https://user-images.githubusercontent.com/23028389/109375981-35860780-78fc-11eb-9233-6be447b88618.png)

This is my setup (I put my custom font in storage/fonts)
dompdf version : ^1.0

HTML :
```
@font-face {
     font-family: 'Inter';
     src: url({{ storage_path('fonts\Inter-Regular.ttf') }}) format("truetype");
     font-weight: normal;
     font-style: normal;
}

@font-face {
     font-family: 'Inter';
     src: url({{ storage_path('fonts\Inter-Thin.ttf') }}) format("truetype");
     font-weight: 100;
     font-style: normal;
}

body{
    font-family: 'Inter', sans-serif !important;
    font-weight: 100;;
}
```

Is there anything I setup or did wrong

**Comment by bsweeney** [comment]
I don't see anything wrong there. Do you have a sample of the PDF output we can look at?

**Comment by kindrosker** [comment]
I had the same issue. I have created custom php code to load font using FontLib. Hope this is help you.
Just load .ttf fonts in font dir (in my case 'vendor\dompdf\dompdf\lib\fonts\')
and  define fonts in $font_types var. 

```
$font_family = 'arial';

$font_types = Array
(
	['normal'] => 'arial.ttf',
	['italic'] => 'arial_italic.ttf',
	['bold'] => 'arial_bold.ttf',
	['bold_italic'] => 'arial_bold_italic.ttf'
);

$dompdf = new Dompdf\Dompdf();     
                

if(count($font_types))
{
	$font_metrics= [];

	foreach($font_types as $type=>$filename)
	{                
		$dest = $dompdf->getOptions()->get('fontDir') . '/' . $filename;
		$entry_name = mb_substr($dest, 0, -4);

		//load font
		$font_obj = \FontLib\Font::load($dest);
		$font_obj->saveAdobeFontMetrics($entry_name. '.ufm') ;
		$font_obj->close();

		$font_metrics[$type] = $entry_name;            
	}


	$fontMetrics = $dompdf->getFontMetrics();

	// Store the fonts in the lookup table
	$fontMetrics->setFontFamily($font_family, $font_metrics);

	// Save the changes
	$fontMetrics->saveFontFamilies();
}
```
In result for each font name will be created .ufm file like (arial.ufm) 
And also font will be added to dompdf_font_family_cache.php file

**Comment by ratandeora1** [comment]
Just check here 
 https://github.com/dompdf/dompdf/issues/2773#issuecomment-1512428271

**Comment by Zeus2024sdsd** [comment]
// Define the custom font
    $fontDir = __DIR__ . '/fonts';
    $customFont = $fontDir . '/COOPBL.ttf';
    
    // Load the font and register it with Dompdf
    $fontMetrics = $dompdf->getFontMetrics();
    $customFontFamily = $fontMetrics->getFont('Cooper Black', 'bold', $customFont);
    
    //$dompdf->set_option('defaultFont', 'CenturySchoolbook-Bold');

	// Load HTML content into DOMPDF
	$html = "
	<!DOCTYPE html>
    
	<style>
	
	    
		.pdf-container1 {border: 1px solid black; padding: 3px; margin-left: -0.5cm; margin-right: -0.5cm; margin-top: -0.5cm; margin-bottom: -2cm;}
		.pdf-container2 {border: 2px solid black; padding: 3px;}
		.pdf-container3 {border: 1px solid black; padding-right: 30px; padding-left: 30px; padding-top: 10px; padding-bottom: 60px;}
		table {border-collapse: collapse;width: 100%;}
		body{padding-right: 10px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px;}
		
		 @font-face {
            font-family: 'CenturySchoolbook-Bold';
            src: url('fonts/CenturySchoolbook-Bold.ttf') format('truetype');
            font-weight: bold;
            font-style: normal;
        }

        .cent {
            font-family: 'CenturySchoolbook-Bold'; /* Use Century Schoolbook Bold for .pdf-container1 */
        }
    
        
        @font-face {
        font-family: 'Cooper Black';
        src: url('$customFont') format('truetype');
        font-weight: 900%;
        font-style: normal;
        }
        .coop {
            font-family: 'Cooper Black';
        }

	</style>
		
	<div class='pdf-container1'>
	<div class='pdf-container2'>
	<div class='pdf-container3'>

		<head>
			<link rel='icon'type='image/jpg' href='images/logo.jpg'>
			
			<div class='cent'>
    			<table style='padding-bottom: 15px;'>
    				<tr><td style='text-align: center; padding-bottom: 15px;'><b style='font-size: 34px; font-family: CenturySchoolbook-Bold;'>PAPUA NEW GUINEA</b></td></tr>
    				<tr><td style='text-align: center; padding-bottom: 15px;'><b style='font-size: 22px; font-family: CenturySchoolbook-Bold;'>SECURITY (PROTECTION) INDUSTRY ACT 2004</b></td></tr>
    				<tr><td style='text-align: center; padding-bottom: 15px;'><b style='font-size: 18px; font-family: CenturySchoolbook-Bold;'>LICENSE ISSUED PURSUANT TO SECTION 40</b></td></tr>
    				<tr><td style='text-align: center;'><img src='" . ImageToDataUrl('images/diamond.jpg') . "' style='height: 15px;'></td></tr>
    			</table>
			</div>
			
		</head>

		<body>
            
            <div class='coop'>
    			<table style='padding-bottom: 15px;'>
    				    <tr><td style='text-align: center;'><b style='font-size: 30px;  font-weight: 900%; !important'>$companylicensetype</b></td></tr>
    			</table>
			</div>
