### ISSUE TITLE
Image overlaying text

### ISSUE THREAD

**Issue by joaovmeneses** [dompdf/dompdf#2391]
Hi folks, i wanna know if somebody know how fix that: 
![image_overlayer](https://user-images.githubusercontent.com/58236175/109389853-116efa00-78ed-11eb-84e3-f041dadd601f.png)

**Comment by joaovmeneses** [comment]
And other issue, how do fix that too: 
![header_overlayer](https://user-images.githubusercontent.com/58236175/109389917-5dba3a00-78ed-11eb-8e86-320e8ab1ac22.png)

Thanks folks!! <3

**Comment by bsweeney** [comment]
Would help to see a sample of the HTML + CSS involved.

**Comment by joaovmeneses** [comment]
![image](https://user-images.githubusercontent.com/58236175/110139202-8e98e400-7db1-11eb-93cf-c742b29752b1.png)

CSS
![image](https://user-images.githubusercontent.com/58236175/110139444-c7d15400-7db1-11eb-97e4-23404ffa5076.png)


Thanks for help!!

**Comment by bsweeney** [comment]
can you post that as text instead of a screen grab?

**Comment by joaovmeneses** [comment]
Ok bro, Thanks!

HTML:
                    <div class="linha" style="text-align:center">
                        @for($i = 0; $i < 2; $i++)
                            <div class="coluna-2">
                                <img src="{{config('app.url')}}/storage/app/public/{{$d['diarioCampo']->imagens[$i]->base64}}" width="200" height="150" alt="">
                                <div style="margin-top:5px"></div>
                                <span class="img-center"><i>{{$d['diarioCampo']->imagens[$i]->descricao}}</i></span>
                            </div>
                        @endfor
                    </div>
                    <div style="height:50px"></div>
                    <div class="linha" style="text-align:center">
                        @for($i = 2; $i < 4; $i++)
                            <div class="coluna-2">
                                <img src="{{config('app.url')}}/storage/app/public/{{$d['diarioCampo']->imagens[$i]->base64}}" width="200" height="150" alt="">
                                <div style="margin-top:5px"></div>
                                <span class="img-center"><i>{{$d['diarioCampo']->imagens[$i]->descricao}}</i></span>
                            </div>
                        @endfor
                    </div>
                    <div style="height:130px"></div>
                    <div class="linha" style="text-align:center">
                        @for($i = 4; $i < 6; $i++)
                            <div class="coluna-2">
                                <img src="{{config('app.url')}}/storage/app/public/{{$d['diarioCampo']->imagens[$i]->base64}}" width="200" height="150" alt="">
                                <div style="margin-top:5px"></div>
                                <span class="img-center"><i>{{$d['diarioCampo']->imagens[$i]->descricao}}</i></span>
                            </div>
                        @endfor
                    </div>
_______________________________________________________________________________________________________________________________________
Style:

<style>

.float-center{
    text-align:center;
}

.float-right{
    float: right;
}

.img-center{
    display:block;
    margin-left: auto;
    margin-right: auto;
}
.float-left{
    float: left;
}

.coluna-2 {
  float: left;
  width: 49%;
  padding: 5px;
}

.coluna-3{
    float: left;
    width: 32.33%;
    padding: 5px;
}

/* Clear floats after image containers */
.linha::after {
  content: "";
  clear: both;
  display: table;
}

/* HEADER E FOOTER  
header { position: fixed; top: 60px; left: 0px; right: 0px; background-color: lightblue; height: 50px; }
footer { position: fixed; bottom: -60px; left: 0px; right: 0px; height: 50px; }
*/

/** Define the margins of your page **/
@page {
    margin: 80px 25px;
}

html{
    font-family: Calibri,Candara,Segoe,Segoe UI,Optima,Arial,sans-serif; 
    /*font-size: 12px;*/
}

header {
    position: fixed;
    top: -80px;
    left: 0px;
    right: 0px;
    height: 80px;
    border-bottom: 1.0px solid #32CD32;
    text-align: center;
    /** Extra personal styles 
    background-color: #03a9f4;
    color: white;
    text-align: center;
    line-height: 35px;
    **/
}

footer {
    position: fixed; 
    bottom: -60px; 
    left: 0px; 
    right: 0px;
    height: 50px; 
    text-align: center;

    /** Extra personal styles 
    background-color: #03a9f4;
    color: white;
    text-align: center;
    line-height: 35px;
    **/
}

</style>

**Comment by joaovmeneses** [comment]
@bsweeney can you help me?

**Comment by bsweeney** [comment]
I can try but it's easier if you can post a sample of the generated HTML + CSS rather than the PHP that creates it.

**Comment by bsweeney** [comment]
Not sure why your header is overlaying the content, maybe just need a bit more page margin. It's not in your sample so I couldn't say for sure.

I can reproduce the issue. It looks like it's similar to #1482. If you remove the auto margins from the `.img-center` class the document renders as expected.

Here's an extremely simplified sample of the issue:

```
<div style="float: left; width: 30%; border: 1px solid red;">
  <h1>LOREM</h1>
  <div style="margin: auto;">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
  </div>
</div>

<div style="float: right; width: 30%; border: 1px solid red;">
  <h1>LOREM</h1>
  <div>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
  </div>
</div>
```
