### ISSUE TITLE
Image cache problem

### ISSUE THREAD

**Issue by mobbi-dev** [dompdf/dompdf#2392]
Is it possible to disable image cache (can't use imagick), because I have to downgrade my php5.6 in debian buster, but now I can't install php5.6-imagick anymore. This will emergency fix for now before I can rewrite my codebase to work with php 7.x

PHP Fatal error:  Class 'Image_Cache' not found in /dompdf/include/image_frame_decorator.cls.php

**Comment by bsweeney** [comment]
IMagick isn't required for image caching. You're using a pretty old version of Dompdf, ahve you tried 0.8.3, which should still support PHP5.6?

**Comment by Nexample-G** [comment]
Follow this
https://youtu.be/R3OhMI9P4-s
