### ISSUE TITLE
Render "Flatten PDF"

### ISSUE THREAD

**Issue by dmartinovs** [dompdf/dompdf#2396]
Hello,

Seems that I can't find a option to render PDF "flattened" to use for printing with domPDF. Reference about flattening here: https://www.printivity.com/insights/2020/04/30/what-flatten-pdf-file-means-and-how-to-do-it/

Is domPDF able to do that, or this must be done by PDF client right before printing?

**Comment by bsweeney** [comment]
Dompdf does not currently support flattening a PDF. You'd have to look to third-party apps, either Adobe Acrobat or maybe something like PDFtk can handle it.

**Comment by dmartinovs** [comment]
@bsweeney thank you! :)
