### ISSUE TITLE
PHP 8.0.0 + Composer require => stream() is a blank page

### ISSUE THREAD

**Issue by mathmul** [dompdf/dompdf#2406]
No matter how much I tone down my HTML string given to `loadHTML()` the `stream()` method yields a single blank page.

The following should produce a single white page with a word "Content" written in the top left corner.

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$domPdf = new \Dompdf\Dompdf();
$domPdf->loadHtml(<<<HTML
    <!DOCTYPE html>
    <html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <title>PDF</title>
    </head>
    <body>
        Content
    </body>
    </html>
HTML
);
$domPdf->stream();
```

I even tried with the following line
```php
$domPdf->loadHtml('<!DOCTYPE html><html><head><meta http-equiv="content-type" content="text/html; charset=UTF-8"><title>PDF</title></head><body>Content</body></html>');
```

My composer looks like this if it matters. A completely fresh project.
```json
{
    "name": "vendor/project",
    "description": "Description",
    "type": "project",
    "license": "Private",
    "authors": [
        {
            "name": "Me",
            "email": "my@email.com"
        }
    ],
    "minimum-stability": "stable",
    "require": {
        "spatie/ray": "^1.21",
        "dompdf/dompdf": "^1.0"
    }
}
```

Local development with Windows10 / Laragon / Apache / PHP 8.0.0 (no framework).

Attached the resulting file.
[document.pdf](https://github.com/dompdf/dompdf/files/6117093/document.pdf)

**Comment by m00n71ght** [comment]
You forgot to call `$domPdf->render()` before `$domPdf->stream();`

**Comment by mathmul** [comment]
I'm an idiot. Thank you.
