### ISSUE TITLE
getting blank pdf and add css bootstrap in the dompdf 

### ISSUE THREAD

**Issue by suraj-TheDeveloper** [dompdf/dompdf#2410]
```
<?php
ob_start();
require_once 'vendor/autoload.php';
use Dompdf\Dompdf;
$dompdf = new Dompdf();
?>
<!DOCTYPE html>
<html>
    <head>
       
    </head>
    <body>
            <?php
                if(isset($_POST['submit'])){
                    $link = mysqli_connect("localhost", "root", "", "billing");
                    $Sql = "SELECT * FROM cart;";
                    $result = mysqli_query($link, $Sql);
                    $html = '';
                    while($row = mysqli_fetch_assoc($result)){
                    $html .= '
                        <h1 class="card-title caption" style="text-align:center;">Total Bill</h1>
                        
                                    <th>Item Name</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                        <td>'.$row['ProductsName'].'</td>
                                        <td>'.$row['Quantity'].'</td>
                                        <td>'.$row['total'].'</td>
                                    
                    ';
                        }
                   
                }
            ?>
    </body>
</html>
<?php
$html = ob_get_contents();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'potrait');
$dompdf->render();
ob_get_clean();
$dompdf->stream("", array("Attachment" => false));
?>
```

**Comment by bsweeney** [comment]
Is it a blank HTML page or an empty PDF?

**Comment by suraj-TheDeveloper** [comment]
It was an empty pdf now I have got the output can you say how to add css in dompdf??. I have changed the code

**Comment by suraj-TheDeveloper** [comment]
**cart.php**
<?php
    ob_start();
?>
<!DOCTYPE html>
<html>
    <head>
        <title>Billing Software</title>
        
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, minimum-scale=1,0, maximum-scale=1.0">
        
        <link rel="stylesheet" href="/billingsoftware/User/CSS/design.css">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

        
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

        
        <script src="https://kit.fontawesome.com/5fc9410497.js" crossorigin="anonymous"></script>

        
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    </head>
    <body>
        <div class="container">
            <div class="card">
                <form action="dom.php" method="POST">
                    <div class="card-body">
                        <h1 class="card-title caption" style="text-align:center;">Total Bill</h1>
                        <table class="table table-hover table-responsive-sm table-responsive-md table-responsive-lg table-responsive-xl">
                            <thead>
                                <tr>
                                    <th>Item Name</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                    $totals = 0;
                                    $link = mysqli_connect("localhost", "root", "", "billing");
                                    $Sql = "SELECT * FROM cart";
                                    $result = mysqli_query($link, $Sql);
                                    while($row = mysqli_fetch_assoc($result)){
                                        ?>
                                        <tr>
                                            <td><?php echo $row["ProductsName"]; ?></td>
                                            <input type="hidden" name="ProductsName" value="<?php echo $row['ProductsName'] ?>">
                                            <td><?php echo $row["Quantity"]; ?></td>
                                            <input type="hidden" name="Quantity" value="<?php echo $row['Quantity'] ?>">
                                            <td><?php echo $row["total"]; ?></td>
                                            <input type="hidden" name="total" value="<?php echo $row['total'] ?>">
                                        </tr>
                                    <?php
                                    }
                                ?>
                            </tbody>
                        </table>
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xl-6">
                            <?php
                                $query = "SELECT COUNT(ProductsName) AS TotalCount FROM cart";
                                $results = mysqli_query($link, $query);
                                while($rows = mysqli_fetch_assoc($results)){
                            ?>
                                    <p class="caption">Total Amount for <?php echo $rows["TotalCount"]; ?> Items</p>
                                    <input type="hidden" name="TotalCount" value="<?php echo $rows['TotalCount']; ?>">
                            <?php
                                }
                                ?>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xl-6">
                            <?php
                                $queries = "SELECT SUM(total) AS TotalAmount FROM cart"; 
                                $resultes = mysqli_query($link, $queries);
                                while($rowes = mysqli_fetch_assoc($resultes)){
                            ?>
                                    <p class="caption" style="margin-left: 160px;"><?php echo $rowes["TotalAmount"]; ?></p>
                                    <input type="hidden" name="TotalAmount" value="<?php echo $rowes['TotalAmount']; ?>">
                                    <?php       
                                    }
                                ?>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </body>
</html>
 
**dompdf.php**
<?php
ob_start();
require 'vendor/autoload.php';
$dompdf = new Dompdf\Dompdf();
include("cart_print.php");
$html = ob_get_contents();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'potrait');
$dompdf->render();
ob_get_clean();
$dompdf->stream("", array("Attachment" => false));
?>

**Comment by suraj-TheDeveloper** [comment]
**dompdf.php**
<?php
ob_start();
require 'vendor/autoload.php';
$dompdf = new Dompdf\Dompdf();
include("cart_print.php");
$html = ob_get_contents();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'potrait');
$dompdf->render();
ob_get_clean();
$dompdf->stream("", array("Attachment" => false));
?>

**Comment by suraj-TheDeveloper** [comment]
![billes](https://user-images.githubusercontent.com/78358604/111018425-be15a500-83de-11eb-9027-53278496b322.png)

**Comment by bsweeney** [comment]
Be sure to update your runtime options to enable support for remote content. Something like the following should work (see the change to Dompdf instantiation):

```
ob_start();
require 'vendor/autoload.php';
$dompdf = new Dompdf\Dompdf(['isRemoteEnabled' => true]);
include("cart_print.php");
$html = ob_get_contents();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'potrait');
$dompdf->render();
ob_get_clean();
$dompdf->stream("", array("Attachment" => false));
```

There may be other options you need to adjust, but since you're referencing Bootstrap from MaxCDN you'll at least need to change that one.
