### ISSUE TITLE
Safari - cannot parse response

### ISSUE THREAD

**Issue by ctrick** [dompdf/dompdf#2416]
On Safari (13, 14) a generated PDF loads not complete (41KB size) and an error occurs: "cannot parse response"
This happens on the live-server. My dev-server works fine with Safari. 
Other browsers have no problems on both servers.

The dompdf-code is quite simple:
```
require_once 'wp-content/themes/themename/assets/dompdf/autoload.inc.php';

use Dompdf\Dompdf;
use Dompdf\Options;

$options = new Options();
$options->set('isRemoteEnabled',true);      
$dompdf = new Dompdf( $options );

$dompdf->loadHtml($markup); // simple html with some styling and one img
$dompdf->setPaper('A4', 'portrait');

// Render the HTML as PDF
$dompdf->render();

$dompdf->stream('test.pdf');
```

**Comment by bsweeney** [comment]
One work around I've seen for this type of issue is to `exit` after the PDF has been streamed. I think some web servers are buffering output and never release it because the script doesn't explicitly end execution.

**Comment by mIIwaukee** [comment]
**Clean the output buffering:**
Add this: 
while (ob_get_level()) ob_end_clean();

**Comment by bsweeney** [comment]
I totally forgot about the possibility of nested output buffers!
