### ISSUE TITLE
Generate preview image of PDF

### ISSUE THREAD

**Issue by Whip** [dompdf/dompdf#2419]
I'm surprised this hasn't been asked yet (or I couldn't find it). I wanted to know if its possible for dompdf to generate a preview image of the pdf after its generated it from HTML?

**Comment by sirbenson** [comment]
Print the pdf directly to the browser: $dompdf->stream("filename.pdf", array("Attachment" => false));

**Comment by Whip** [comment]
That's not an image. And that's certainly not an efficient way to load thumbnails.
