### ISSUE TITLE
Dompdf 0.8.3 Chinese Character not showing

### ISSUE THREAD

**Issue by yediaeluzai** [dompdf/dompdf#2420]
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style>
	@font-face {
		font-family: dfguyinmedium1b;
		font-style: normal;
		font-weight: normal;
		src: url(http://work.nanyangbridge.com/assets/css/dfguyinmedium1b.TTF) format('truetype');
	}
</style>
</head>
<body>
<div style="font-family: dfguyinmedium1b;">新疆是中国陆地面积最大的省份</div>
</body></html>
```

> $CI = &get_instance();
> $dompdf = new Dompdf();
> $html = $CI->load->view($view, $data, TRUE);
> 
> /* echo $html;exit; */
> 
> $dompdf->loadHtml($html);
> $dompdf->set_option('isRemoteEnabled', TRUE);
> $dompdf->set_option('isFontSubsettingEnabled', true);
> 
> // (Optional) Setup the paper size and orientation
> $dompdf->setPaper('A4', 'portrait');
> 
> // Render the HTML as PDF
> $dompdf->render();
> $time = time();
> 
> // Output the generated PDF to Browser
> $dompdf->stream("welcome-". $time, array("Attachment" => 0));

I developed a system using Codeigniter and failed to extract Chinese characters from HTML to PDF. Already tried to use Dejavu Sans but also no luck. I tracking the content on the 'loadHtml' function until before render() the chinese character still showup, but when i try to output() or stream() the chinese character dissapear.

**Comment by bsweeney** [comment]
I can the document to render on 0.8.3, though there are issues with it. 1.0.2 does not like it at all, though I don't know if it's Dompdf specifically or php-font-lib. I'll have to look into it more.

**Comment by driesvints** [comment]
Hey @bsweeney, I also can't get the example from the wiki to work: https://github.com/dompdf/dompdf/wiki/UnicodeHowTo#create-a-compatible-html-document

Using dompdf v1.1.1 and I'm sure I implemented the code snippets from the wiki properly.

**Comment by bsweeney** [comment]
I would need to see a sample of the document you're attempting to render to be able to provide any feedback.

I rendered the OPs document again in a few versions of Dompdf and it came out OK, though there are a few notices that require looking into.

**Comment by driesvints** [comment]
@bsweeney thanks for replying! I tried it with the following:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
        @font-face {
            font-family: 'Firefly';
            font-style: normal;
            font-weight: normal;
            src: url(http://example.com/fonts/firefly.ttf) format('truetype');
        }

        body {
            font-family: firefly, DejaVu Sans, sans-serif;
            font-size: 12px;
        }
    </style>
</head>
<body>
<div>
    Text: 你好世界
</div>
</body>
</html>
```

Gives:

<img width="292" alt="Screenshot 2022-01-21 at 14 37 21" src="https://user-images.githubusercontent.com/594614/150536400-744862f9-d40c-49c0-a914-6f2be9755718.png">

**Comment by driesvints** [comment]
I'm not entirely sure if DejaVu Sans renders these characters? It does seem that Firefly can't render them either?

https://ufonts.com/fonts/firefly.html#preview

<img width="620" alt="Screenshot 2022-01-21 at 14 42 13" src="https://user-images.githubusercontent.com/594614/150537043-7115e806-da25-47a4-8e3b-27321ea5523e.png">

**Comment by bsweeney** [comment]
DejaVu does not render those characters, here's a [character reference sheet](https://dejavu-fonts.github.io/Samples.html) (mostly accurate). We'll be looking into providing expanded character support in the future.

In the meantime you can use [Google Fonts](https://fonts.google.com/?subset=chinese-simplified) to find a font with the desired characters.

For example:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ma+Shan+Zheng&display=swap" rel="stylesheet"> 

    <style>
        body {
            font-family: 'Ma Shan Zheng', DejaVu Sans, sans-serif;
            font-size: 12px;
        }
    </style>
</head>
<body>
<div>
    Text: 你好世界
</div>
</body>
</html>
```

Reminder that Dompdf currently only works with the TrueType fonts (TTF). Some of the Google fonts are OpenType.

**Comment by driesvints** [comment]
Thanks @bsweeney, that's insightful 👍 

I'm looking for a solution that allows both latin an Chinese characters at the same time as we sometimes have mixed input. But it seems that's not possible atm.

**Comment by bsweeney** [comment]
That just depends on what font you're using. The Ma Shan Zhen font supports Latin characters, though since it's a highly stylized font it's not idea. There are others such as ZCOOL XiaoWei that look a bit better, though php-font-lib does generate some errors when trying to parse it.

**Comment by bsweeney** [comment]
Looking at this, the OPs issue in more recent releases appears to be due to how Dompdf is handling the "src" property in the CSS declaration. A fix will be included in the next release.

**Comment by bsweeney** [comment]
One more thing. Whatever generated the dfguyinmedium1b.TTF font file produced something that is not supported by php-font-lib. So, even when the CSS parsing issue is addressed the PDF won't render as expected. It looks like the font is, primarily, missing the CMAP table so there's no character mapping information which is necessary to define the font metrics. I'm not sure right now what, if anything, we can do to address that in php-font-lib and Dompdf.
