### ISSUE TITLE
what is the difference between PDF::class and new Dompdf() method

### ISSUE THREAD

**Issue by carsonchan96** [dompdf/dompdf#2425]
1. Recently, I am using dompdf to generate PDF from HTML. However, I find some tutorial uses 

```
     $pdf = PDF::loadView('sample', $data);
     return $pdf->stream('invoice.pdf');
```

and some tutorial uses

```
    $dompdf = new Dompdf();
    $dompdf->loadHtml($sample);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    return $dompdf->stream('sample', ['Attachment' => 0]);
```

What is the difference between two methods?
And I found that the second method cannot pass the variable to the html view while the first one can do this by:

```
    $pdf = PDF::loadView('sample', $data);
```

2. beside, I google search the 'cannot display chinese characters with Dompdf' problem and all of the result regards to the second method approach. Are there any solution is for first approach?

**Comment by bsweeney** [comment]
The first method looks like what you would do from within Laravel. The second example is for using the Dompdf class directly. I'm not familiar enough with Laravel to help you in that environment.
