### ISSUE TITLE
dompdf 1.0.2 does not print images

### ISSUE THREAD

**Issue by cperrot** [dompdf/dompdf#2431]
I have tried with local path to load images and with isRemoteEnabled as well. 

It does not load under any circumstances the image. 
changed as well from gif to jpg

    // CONFIGURATION
    $pdfOptions = new Options();
    $pdfOptions->set('isRemoteEnabled', true);
    //$pdfOptions->set('isHtml5ParserEnabled', true);
    $pdfOptions->set("a4", "portrait");

    $dompdf = new Dompdf($pdfOptions);
    $dompdf->load_html($html);
    $dompdf->render();

**Comment by cperrot** [comment]
I even tried the local filename /var/www/img/logo.jpg
with no luck

**Comment by maciej-laskowski** [comment]
@cperrot We had similar issues and ended up converting images to base64 and then using them in templetes like so `<img src="{{ logoBase64 }}"/>`. Of course this is more like a workaround that does not scale well if you have many images.

**Comment by bsweeney** [comment]
Can you post a sample of the HTML + CSS?

**Comment by TehWan** [comment]
I managed to make it work by removing the leading `/` in the HTML image source (and for stylesheets).
`<img src="/assets/logo.png" />` --> `<img src="assets/logo.png" />`

It seems that dompdf thinks the leading `/` is for an absolute path, when for web it is just relative to the root of the website.

**Comment by TehWan** [comment]
The fix is available in this pull request: https://github.com/dompdf/dompdf/pull/2256
A chroot is expected to have `/` point to the base of the chroot, not to the base of the actual filesystem.

**Comment by bsweeney** [comment]
chroot in Dompdf has always been used as a validation not a path adjustment. Thank you for helping clarify for me that the option is poorly named. I think we should fix that and at the same time add actual chroot-like functionality. It's a breaking change so it'll have to be included in a major release.

**Comment by TehWan** [comment]
In docker-compose, I know they use "context" as a validation, similar to how "chroot" is used in Dompdf, if that can give you ideas on terminology to use.

I think most of the confusion also comes from the expected behavior, where it is expected to act like a web browser rather than a filesystem traversal system. This is especially confusing given we are dealing with HTML files in a PHP context, where one would want to generate a page using a view system (such as Smarty for example) and then create a PDF output of it (such as generating a personalized certificate for download).

**Comment by romanown** [comment]
i replaced the file src/Image/Cache.php in new vwrsion by old version from 10/10/2017.

**Comment by romanown** [comment]
to try reade [https://github.com/dompdf/dompdf/issues/2435](https://github.com/dompdf/dompdf/issues/2435)

**Comment by cperrot** [comment]
I found the problem.

It is a coding error in src/Image/Cache.php which causes a problem.

old code:
$chroot = realpath($dompdf->getOptions()->getChroot());
new code:
$chroot = realpath($dompdf->getOptions()->getChroot()[0]);

getChroot returns an array and not a string.

Now everything works for me.

**Comment by Nexample-G** [comment]
Follow This

https://youtu.be/R3OhMI9P4-s

**Comment by romanown** [comment]
this makes the algorithm not work correctly. I removed all the new code. I downloaded the old file instead. I do not have this mechanism. so I don't have this problem now. I don't need this new mechanism in the code. therefore, I have no need to make such changes. moreover, these changes affect security. youtube is full of such videos. but my decision to exclude all new code seems to me safer than always allowing it. thanks.

**Comment by Nexample-G** [comment]
maybe ! but one time see my video i'm always create genuine content | Is
useful ! And I'm not using any special code

**Comment by romanown** [comment]
I watched the video before I wrote the message. the video changes the operation of the condition. thus, the code will not work correctly according to the idea of the creator. which theoretically can be considered equal to the fact that this check is missing. this is also equal to deleting the verification code. previously, this check was not carried out. I replaced the new file with an old one that did not have a check. theoretically, our actions on the final result are equal.

**Comment by romanown** [comment]
we will wait for the creator to release a new version with a fix.

**Comment by Nexample-G** [comment]
Ok thanks but i am new on YouTube for solving problems about PHP ! Thanks
for replying

**Comment by bsweeney** [comment]
The OP hasn't responded and the issue introduced with the changes to how the chroot option is handled is sufficiently documented. If you have further questions [post in the discussion forum](https://github.com/dompdf/dompdf/discussions/new) or [open a new issue](https://github.com/dompdf/dompdf/issues/new/choose) for a suspected bug.
