### ISSUE TITLE
"Image not found or type unknown" dompdf 1.0.2

### ISSUE THREAD

**Issue by humblewizard** [dompdf/dompdf#2435]
I've had a website database for a group of clubs running since 2010 using a version of dompdf from that time like 0.6. It's been working fine but when the server recently moved to php 7.1 it quit working all together. I've got a cron job that processes about 400 documents at night - or it was. 

So I now have Dompdf 1.0.2 loaded and it's refusing to display the images. I've tried hard coding the direct path to the image on the server: The page has three different images and none are showing but the rest of the document is rendering fine. The page shows properly including the images in a browser.

          <img src="/srv/www/myDomain.org/public_html/reciprocal/attachments/burgee-216.png" />

in which case I'm getting the "Image not found or type unknown" in the pdf.
 
And, using the site URL the script goes away and never comes back.

         <img src="https://myDomain.org/reciprocal/attachments/burgee-216.png" />

I've tried nearly everything I could find online and some other stuff too. No luck. 

Any ideas for me? Here is the options array.

          Dompdf\Options Object
          (
              [rootDir:Dompdf\Options:private] => /srv/www/myDomain.org/public_html/dompdf_1.0.2/dompdf
              [tempDir:Dompdf\Options:private] => /tmp
              [fontDir:Dompdf\Options:private] => /srv/www/myDomain.org/public_html/dompdf_1.0.2/dompdf/lib/fonts
              [fontCache:Dompdf\Options:private] => /srv/www/myDomain.org/public_html/dompdf_1.0.2/dompdf/lib/fonts
              [chroot:Dompdf\Options:private] => Array([0] => /srv/www/myDomain.org/public_html/dompdf_1.0.2/dompdf)          
              [logOutputFile:Dompdf\Options:private] => /tmp/log.htm
              [defaultMediaType:Dompdf\Options:private] => screen
              [defaultPaperSize:Dompdf\Options:private] => letter
              [defaultPaperOrientation:Dompdf\Options:private] => portrait
              [defaultFont:Dompdf\Options:private] => serif
              [dpi:Dompdf\Options:private] => 96
              [fontHeightRatio:Dompdf\Options:private] => 1.1
              [isPhpEnabled:Dompdf\Options:private] => 
              [isRemoteEnabled:Dompdf\Options:private] => 1
              [isJavascriptEnabled:Dompdf\Options:private] => 1
              [isHtml5ParserEnabled:Dompdf\Options:private] => 
              [isFontSubsettingEnabled:Dompdf\Options:private] => 1
              [debugPng:Dompdf\Options:private] => 
              [debugKeepTemp:Dompdf\Options:private] => 
              [debugCss:Dompdf\Options:private] => 
              [debugLayout:Dompdf\Options:private] => 
              [debugLayoutLines:Dompdf\Options:private] => 1
              [debugLayoutBlocks:Dompdf\Options:private] => 1
              [debugLayoutInline:Dompdf\Options:private] => 1
              [debugLayoutPaddingBox:Dompdf\Options:private] => 1
              [pdfBackend:Dompdf\Options:private] => CPDF
              [pdflibLicense:Dompdf\Options:private] => 
          )

The OS is Ubuntu 16.04 and the PHP is 7.1

**Comment by bsweeney** [comment]
For the local file reference, you would need to update the chroot option to allow access to the path where the image is located. Something like the following:

```
$options = $dompdf->getOptions();
$options->setChroot('/srv/www/myDomain.org/public_html/');
$dompdf->setOptions($options);
```

(or however you're setting you other options)

You're using a PNG image, which requires extra processing so make sure GD is installed. Also ensure that Dompdf has read/write access to the temp directory.

I'm not sure why accessing via the web server would just halt processing. Any PHP errors logged?

**Comment by humblewizard** [comment]
Setting the $options->setChroot worked --> **thanks**. I don't understand what this does really. It sets a permission to allow the use of the absolute image path? 

Now I have another problem which is new. The stylesheet is not being loaded or read. Different subject I know. I'll dig into this on my own for a while.

**Comment by romanown** [comment]
i replaced the file src/Image/Cache.php in new vwrsion by old version from 10/10/2017.

**Comment by cperrot** [comment]
I found the problem.


It is a coding error in src/Image/Cache.php which causes a problem.

old code:
$chroot = realpath($dompdf->getOptions()->getChroot());
new code:
$chroot = realpath($dompdf->getOptions()->getChroot()[0]);

getChroot returns an array and not a string.

Now everything works for me.
