### ISSUE TITLE
column size setting not working in second page just working in first page

### ISSUE THREAD

**Issue by tomiteruz** [dompdf/dompdf#2437]
I set my html page with table size and column size using width property, after break page (second page) table size and column size not working. 

I using dompdf version 1.0.2 in codeigniter

![image](https://user-images.githubusercontent.com/37565709/114749630-55bf3800-9d7d-11eb-81b1-d1caa34c1a37.png)

**Comment by bsweeney** [comment]
Would need to see some HTML to have a better sense of what's happening here, but this is likely already reported in #2353 or #2395
