### ISSUE TITLE
superscript is incorrectly rendered inside tables

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#244]
_Original author: excepti...@hotmail.com (February 25, 2011 20:27:51)_

<b>What steps will reproduce the problem?</b>
1. create a table with some cells
2. put something &lt;sup&gt;in superscript&lt;/sup&gt;
3. render

<b>What is the expected output? What do you see instead?</b>
expected is a good superscript rendering, but it fails to do so.

<b>What version of the product are you using? On what operating system?</b>
0.6 beta2

<b>Please provide any additional information below.</b>
The the rendering of the superscript seems to be influenced by altering the global line-height of the document.

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=238_

**Comment by bsweeney** [comment]
no longer a bug
