### ISSUE TITLE
Maximum execution time Exception with no Stacktrace

### ISSUE THREAD

**Issue by petrosit** [dompdf/dompdf#2441]
Hi,
I've been using dompdf for some quite time in different projects. But in one of the projects suddenly I am receiving a weired exception throughout the day. It has no Stracktrace. I only see this kind of errors:

Maximum execution time of 120 seconds exceeded
/.../vendor/dompdf/dompdf/src/Css/Style.php +893
or
...dompdf/dompdf/src/Frame.php +422
or
...FrameDecorator/AbstractFrameDecorator.php +530

And the stacktrace always only shows:

#0 {main}

In this project I use dompdf to generate resumes in a laravel web app.

Apparently none of the users is complaining about it but I'm not sure what exactly is happening on the user frontend. I am not able to reproduce it either.

Does anyone have an idea wher ethe issue could be? I read on some forums that this might be related to css issues, but I dont understand why this was not happening earlier (it's still on the same server) and why is it happening only sometimes?

Thanks for any help!
Br
Petros

**Comment by petrosit** [comment]
The issue was fixed position in my css + page break always

**Comment by bsweeney** [comment]
Thanks for the notice. Was this because the fixed-position content was larger than the current page? I thought we ignored page breaks inside absolute/fixed positioned content but I'll have to double check.
