### ISSUE TITLE
Imagick::clone method is deprecated and it's use should be avoided

### ISSUE THREAD

**Issue by Nuranto** [dompdf/dompdf#2442]
From `…/vendor/dompdf/dompdf/lib/Cpdf.php:5687` : https://github.com/dompdf/dompdf/blob/0ccafeb142dd04f556b43f1e8b5541aa06de1c26/lib/Cpdf.php#L5687

PHP : 8.0.3
dompdf : v1.0.2
Imagick : 3.4.4

**Comment by Nuranto** [comment]
Sorry, didn't checked the PR. It seems it is already managed by https://github.com/dompdf/dompdf/pull/2373 ?

**Comment by bsweeney** [comment]
this was mentioned in #1807 and the issue managed via #1296

**Comment by bsweeney** [comment]
I believe the logic release with 1.1.0 is sufficient? Eventually we'll take the extra logic out but seems to work for now.
