### ISSUE TITLE
Is there a way to have full page background color in css without setting page margins to 0?

### ISSUE THREAD

**Issue by xoich** [dompdf/dompdf#2444]
the `@page` and `html` css selector do not seem to accept `background-color`. I know you can do this by setting the `@page` margins to zero and body background color, but I need the margins.

**Comment by bsweeney** [comment]
Styling for `@page` is limited (per the CSS spec). `html` is the same as `body` as far as rendering.

It's possible to do what you want, however, using a bit of CSS. See my last comment on #2422.
