### ISSUE TITLE
EASY! Update the GitHub URL

### ISSUE THREAD

**Issue by jarednova** [dompdf/dompdf#2446]
The URL on the About section points to the old structure for GitHub pages.
![Screen Shot 2021-04-30 at 1 18 01 PM](https://user-images.githubusercontent.com/1298086/116730444-81196800-a9b6-11eb-9e0e-7fc44cf5aded.png)

... this should be updated to the new one:

https://dompdf.github.io/

**Comment by bsweeney** [comment]
Thanks for that! Now if only I had time to do the hard work of updating the content 😬

**Comment by jarednova** [comment]
Indeed, I know the feeling!
