### ISSUE TITLE
Blank or Corrupted PDF using version 0.8.6

### ISSUE THREAD

**Issue by nickabond** [dompdf/dompdf#2449]
First off, fantastic job on this library, it has helped me tremendously!

I'm having a issue every now and again and I don't entirely understand why, the user gets a blank PDF or a corrupted one with a bunch of symbols. I have a JavaScript function that makes a call to my PHP file, it then generates the PDF using the code below, and then the user can download it. 

Even though it corrupts it or is blank every now and again. If the user tries again it isn't blank the next time. 

Here's the code I'm using:
```
for($i = 0;$i<count($passedDataObject);$i++){
  $dompdf = new Dompdf();
  $options = $dompdf->getOptions();
  $options->setIsHtml5ParserEnabled(true);
  $options->setIsRemoteEnabled(false);
  $options->setIsJavascriptEnabled(false);
  $options->setDebugCss(false);
  $options->setDebugPng(false);
  $options->setDebugLayout(false);
  $options->setDebugLayoutBlocks(false);
  $options->setDebugLayoutInline(false);
  $options->setDebugLayoutPaddingBox(false);
  $dompdf->setOptions($options);
  
  $reportHTML .= '
                            <style>
                                    @page { margin: 20px 5px 10px 5px; }
                                    body { width:100%;margin: 0px;}

                                    .individualConcreteReport:not:(first-of-type){
                                        page-break-after:always;
                                        margin-top:20px;
                                    }

                                  ...more styles than this...
                            </style>
';


<<<< There's a lot more that gets added onto $reportHTML but I think this is enough to show the basic structure >>>>

  $dompdf->loadHtml($reportHTML);
                  
  $dompdf->setPaper('A4', 'portrait');
  $dompdf->render();
  
  ob_clean();
  
  $pdf = $dompdf->output();
  
  file_put_contents('//Server/Location/'.$docName, $pdf);
  
  unset($reportHTML);
  unset($reportData);
  unset($pdf);
  unset($dompdf);
}
```
Any help would be greatly appreciated.

**Comment by bsweeney** [comment]
Can you share a copy of one of the corrupted/blank PDFs? Anything reported in your PHP error logs?

**Comment by nickabond** [comment]
I've got nothing in the PHP error logs. It won't let me attach the PDF
because the blank one is 0 bytes. Let me see if I can find one of the ones
that's corrupted so it at least has something in it.

**Comment by nickabond** [comment]
I just found this. I had the starting html tag after the style tag. Would this account for my issue?

```
<style>
........styles here.......
</style>
<html>
<body>
```

**Comment by bsweeney** [comment]
Since you're using the HTML5 parser I wouldn't expect that structure to cause any problems.

Have you tried upgrading to 1.0.2?

**Comment by nickabond** [comment]
Got it, alright. Yeah I can try that. Do I need to be on PHP 8 to switch to
the later version or is it backwards compatible?

**Comment by bsweeney** [comment]
The latest release is compatible with PHP 7.1 or higher.

**Comment by nickabond** [comment]
Figured out the issue....

It was a coding mistake on my end. The document was being deleted before it was fully downloaded by the browser some of the time, which was leading to a corrupted or blank file.
