### ISSUE TITLE
List bullet alignement problem

### ISSUE THREAD

**Issue by itajackass** [dompdf/dompdf#2451]
I use tinymce 5 to write A4 document. then with a button i'll pass the content of editor to ajax.php that convert it in PDF with dompdf 1.0.2

The problem is on OL (ordered list): marker not aligned correctly with text. See screenshot (number 6 of list):

And html code:

    <ol>
    <li style="line-height: 2; font-size: 11pt; font-family: Calibri, sans-serif; text-align: left;"><span style="font-family: arial, helvetica, sans-serif; background-color: #fbeeb8; color: #169179; font-size: 11pt;"><strong><span style="line-height: 150%; background-color: #fbeeb8;">ciao</span></strong></span></li>
    <li style="line-height: 2; font-size: 11pt; font-family: Calibri, sans-serif; text-align: left;"><span style="font-family: arial, helvetica, sans-serif; background-color: #fbeeb8; color: #169179; font-size: 11pt;"><strong><span style="line-height: 150%; background-color: #fbeeb8;">ciao</span></strong></span></li>
    <li style="line-height: 2; font-size: 11pt; font-family: Calibri, sans-serif; text-align: left;"><span style="font-family: arial, helvetica, sans-serif; background-color: #fbeeb8; color: #169179; font-size: 11pt;"><strong><span style="line-height: 150%; background-color: #fbeeb8;">ciao</span></strong></span></li>
    <li style="line-height: 2; font-size: 11pt; font-family: Calibri, sans-serif; text-align: left;"><span style="font-family: arial, helvetica, sans-serif; background-color: #fbeeb8; color: #169179; font-size: 11pt;"><strong><span style="line-height: 150%; background-color: #fbeeb8;">ciao</span></strong></span></li>
    <li style="line-height: 2; font-size: 11pt; font-family: Calibri, sans-serif; text-align: left;"><span style="font-family: arial, helvetica, sans-serif; background-color: #fbeeb8; color: #169179; font-size: 11pt;"><strong><span style="line-height: 150%; background-color: #fbeeb8;">ciao</span></strong></span></li>
    <li style="line-height: 2; font-size: 11pt; font-family: Calibri, sans-serif; text-align: left;"><span style="font-family: arial, helvetica, sans-serif; font-size: 11pt;"><strong>other text</strong></span></li>
    <li style="line-height: 2; font-size: 11pt; font-family: Calibri, sans-serif; text-align: left;"><span style="font-family: arial, helvetica, sans-serif; background-color: #fbeeb8; color: #169179; font-size: 11pt;"><strong><span style="line-height: 150%; background-color: #fbeeb8;">ciao</span></strong></span></li>
     <li style="line-height: 2; font-size: 11pt; font-family: Calibri, sans-serif; text-align: left;"><span style="font-family: arial, helvetica, sans-serif; background-color: #fbeeb8; color: #169179; font-size: 11pt;"><strong><span style="line-height: 150%; background-color: #fbeeb8;">ciao</span></strong></span></li>
     <li style="line-height: 2; font-size: 11pt; font-family: Calibri, sans-serif; text-align: left;"><span style="font-family: arial, helvetica, sans-serif; background-color: #fbeeb8; color: #169179; font-size: 11pt;"><strong><span style="line-height: 150%; background-color: #fbeeb8;">ciao</span></strong></span></li>
     <li style="line-height: 2; font-size: 11pt; font-family: Calibri, sans-serif; text-align: left;"><span style="font-family: arial, helvetica, sans-serif; background-color: #fbeeb8; color: #169179; font-size: 11pt;"><strong><span style="line-height: 150%; background-color: #fbeeb8;">ciao</span></strong></span></li> 
     <li style="line-height: 2; font-size: 11pt; font-family: Calibri, sans-serif; text-align: left;"><span style="font-family: arial, helvetica, sans-serif; background-color: #fbeeb8; color: #169179; font-size: 11pt;"><strong><span style="line-height: 150%; background-color: #fbeeb8;">ciao</span></strong></span></li>
    </ol>

![dompdf align](https://user-images.githubusercontent.com/17260726/117443582-a1a66c80-af38-11eb-84d1-6987d26359ad.jpg)

**Comment by bsweeney** [comment]
Guessing that the line height adjustments must not be correctly flowing to the rendered bullet. The issue is also present in unordered lists.

**Comment by eddturtle** [comment]
Not sure if this is helpful, but we had an issue where default fonts would line up, but custom/webfonts wouldn't. It was to do with the font code somewhere, but tried to implement a hacky solution on the list bullets themselves to fix the problem (in a fork): https://github.com/eddturtle/dompdf/commit/75503034f6e21bf54431e6a1ec086917a566ada8
