### ISSUE TITLE
HTML links do not work unless the link text contains the "http://" or "https://"

### ISSUE THREAD

**Issue by seanmadrid** [dompdf/dompdf#2455]
This issue is similar to #1559. I am using version 0.8.6 and running PHP version 7.2.18.

This is happening after the final step on [http://parks.brinkdev.com/active-guide-pdf-demo/](http://parks.brinkdev.com/active-guide-pdf-demo/).

**Comment by bsweeney** [comment]
Hyperlinks in a PDF generally won't work in PDF readers unless they include a protocol (e.g. http://). If you're generating the PDF without any kind of base href and the links do not include the protocol then they will be rendered with a local filesystem path.

You can hint the base path through one of the following methods:
- load the HTML using `$dompdf->loadHtmlFile(...)`
- add a BASE meta tag to the document, e.g. `<base href="http://example.com/" />`
- specifically set the base properties for Dompdf, e.g. `$dompdf->setProtocol('http://'); $dompdf->setBaseHost('example.com'); $dompdf->setBasePath('/');`

If that doesn't help I'd need to see a sample of the HTML + CSS. And also a version of the PDF [without compression](https://github.com/dompdf/dompdf/wiki/Usage#stream) so I can peek at the source.

**Comment by seanmadrid** [comment]
Thanks @bsweeney,

The href has always contained the protocol. It's only when the text of the link itself contains it that they render as hyperlinks in the PDF. If I do `<a href="https://example.com">Click Me</a>` , the "Click Me" part will not be linked in the PDF.

[your-events-guide (37).pdf](https://github.com/dompdf/dompdf/files/6526978/your-events-guide.37.pdf)

You can inspect it at [http://parks.brinkdev.com/active-guide-pdf-demo/](http://parks.brinkdev.com/active-guide-pdf-demo/). If you click the checkboxes for each step, you'll reach **Step 4: Review**. This is where the PDF preview is generated and users are able to download it.

**Comment by bsweeney** [comment]
I had already gone through the process at the demo site, and can confirm that I'm seeing the same from the PDF generated there, but I don't really have enough info to diagnose what's going on. I'm only able to reproduce the issue in the particular scenario I outlined (missing protocol, no base href).

It would help to see a sample of the HTML+CSS source being fed to Dompdf as well as the uncompressed PDF so I can confirm that the link box isn't misplaced.

**Comment by seanmadrid** [comment]
Are you seeing that PDF as compressed? I ask because I just downloaded it and it was a non-compressed PDF. 

There is no HTML file, but I can share the full plugin:
[brink-active-montgomery.zip](https://github.com/dompdf/dompdf/files/6534551/brink-active-montgomery.zip)

**Comment by bsweeney** [comment]
Compressed as in internal PDF compression, yes that's what I'm getting back. But also, I see you're using another library to merge the PDF generated by Dompdf with another PDF document. Perhaps that's where the links are being impacted? If you output just the content generated by Dompdf are the links working?

**Comment by seanmadrid** [comment]
That was it. I was able to append additional pages as images. I scrapped the additional library and now all of the links work.
