### ISSUE TITLE
Parse error after calling new Dompdf();

### ISSUE THREAD

**Issue by Inkperial** [dompdf/dompdf#2470]
Hi, I am running php 7.4 and latest Dompdf (1.0.2).
I get this error message:
Parse error: syntax error, unexpected '=' in dompdf/src/Dompdf.php on line 371

Here's my code:

```
require_once 'plugins/dompdf/autoload.inc.php';
// reference the Dompdf namespace
use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();
$dompdf->loadHtml('hello world');

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'landscape');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream();
```

I tried other php versions as well (7.1, 7,2 and 8.0) but the same error occurs in each version. What am I doing wrong?

**Comment by bsweeney** [comment]
The syntax in question is array destructuring (`[$this->protocol, $this->baseHost, $this->basePath] = Helpers::explode_url($file);`) and was made available starting with [PHP 7.1](https://www.php.net/manual/de/migration71.new-features.php). I couldn't say why you might be seeing that error unless Dompdf is still being executed under an older version of PHP.
