### ISSUE TITLE
Multiple %%EOF on generated pdf file

### ISSUE THREAD

**Issue by jouko567** [dompdf/dompdf#2474]
generating pdf from url with version Dompdf_1.0.2 gives multiple %%EOF, which should be only on last line. 
Here is example

```
0000011830 00000 n 
trailer
<<
/Size 19
/Root 1 0 R
/Info 5 0 R
/ID[<cfd12517cd5c3c7848238da2baa5b79a><cfd12517cd5c3c7848238da2baa5b79a>]
>>
startxref
12283
%%EOF
1
%%EOF
0 R
/Info 5 0 R
/ID[<2b3fe805509b4f8ecdf36add0de62614><2b3fe805509b4f8ecdf36add0de62614>]
>>
startxref
12407
%%EOF
><ccbe66df5ea745e9b9e7842b18d93439>]
>>
startxref
12469
%%EOF
000 n 
0000000399 00000 n 
0000000436 00000 n 
0000000621 00000 n 
0000000724 00000 n 
0000002381 00000 n 
0000002488 00000 n 
0000002600 00000 n 
0000002629 00000 n 
0000003065 00000 n 
0000012025 00000 n 
0000012239 00000 n 
0000012299 00000 n 
0000012359 00000 n 
0000012416 00000 n 
0000012473 00000 n 
trailer
<<
/Size 19
/Root 1 0 R
/Info 5 0 R
/ID[<043eb092db259f62361a2e16064f0caa><043eb092db259f62361a2e16064f0caa>]
>>
startxref
12919
%%EOF
```

**Comment by bsweeney** [comment]
That's ... odd. What is your usage scenario? Are you using in conjunction with any other libraries? Which backend are you using?

**Comment by jouko567** [comment]
we are sending electronic Invoices . 
Use case

1.generate xml invoice (Finvoice 3.0) to xml file.
2.invoice pic url --> dompdf --> save to file
3. zip both files
4. send zip to bank network using rest API

Backend is apache server

ps.

I did dirty temporary fix for this.
I search first occurrence of %%EOF, and cut result from there.

function fix_pdf($s) {
    // temporary fix
	$pos = strpos($s,"%%EOF",0)+7;
	$s = substr($s,0,$pos);
	return $s;
}

**Comment by bsweeney** [comment]
That is a dirty fix. Are you rendering multiple time with Dompdf? I'm at a loss for how the extra EOF are winding up in the file. If you have more insight in the future please share.
