### ISSUE TITLE
Negative margins causing a line break with inline elements

### ISSUE THREAD

**Issue by eddturtle** [dompdf/dompdf#2476]
Applying a negative margin on an element breaks the text to a new line after the inline element.

The HTML:

```html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body>
  
  <p style="margin-left:-30px;">the garage dated 22<sup>nd</sup> March 2013. This would appear to have been the work that has been carried out by your Seller. Outline Planning</p>

</body>
</html>
```

![Screenshot 2021-06-21 at 15-01-50 0 pdf issue - 0pdfissue pdf](https://user-images.githubusercontent.com/902607/122775026-a2555100-d2a1-11eb-9cc1-1dd52add9827.png)
![Screenshot 2021-06-21 at 14-59-35 dompdf Debugging Helper](https://user-images.githubusercontent.com/902607/122774932-8a7dcd00-d2a1-11eb-9d40-f832c0416c95.png)

Would expect "March" to appear next to, and to the right of, the "nd" superscript.

We've tried this using: https://eclecticgeek.com/dompdf/debug.php running Dompdf v1.0.2 and v0.8.3 and they both show this issue happening.

On our local machines, if we set the margin left to -17px then it didn't work, but -16px did (this could be something on our setup though). Probably un-important, but `transform: translateX(-30px);` caused the same issue to happen.

I've tried looking at the code (would happily put together a PR, but can't find the right bit). The best I could come up with would be the positioner isn't positioning the 2nd line correctly? Any help would be amazing!

**Comment by Mellthas** [comment]
Had a look at the code handling inline elements a while ago, and yes, I think the positioner is forcing line breaks where it shouldn't. I have some work on this lying around that I need to review again; when I find some time I will post a PR. Though I cannot guarantee that it fixes this particular bug.

**Comment by epmor** [comment]
@Mellthas Would you be in the position to create a gist (or here) of the fix? Would be much great if you could!

**Comment by Mellthas** [comment]
I have posted #2497. It is mostly concerned with fixing issues around page breaks, and although it contains a few fixes related to line breaks, it unfortunately does not fix the issue here. Maybe the changes can help in finding a solution. The most important parts of the changes are in https://github.com/dompdf/dompdf/pull/2497/commits/d2106633a54cbd95d5e4cf5519d2a7f90d1f439b.

**Comment by Mellthas** [comment]
The issue here does not seem to be related to the negative margin, actually. It seems it depends on the space available for the text. I can reproduce the issue with `style="width: 700pt;` instead of the negative margin on the `p` element (with a page size of A4).

**Comment by Mellthas** [comment]
The following HTML makes the issue more visible:
```html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<style>
  @page {
    size: 400pt 300pt;
    margin: 50pt;
  }
</style>
<body>

<p style="width: 350pt;">
Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor
incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
nostrud exercitation ullamco laboris <b>nisi</b> ut aliquid ex ea commodi consequat.
Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat
nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa
qui officia deserunt mollit anim id est laborum.
</p>

</body>
</html>
```
![issue-2476](https://user-images.githubusercontent.com/5852189/127241447-8da2ede3-70ba-4a0b-9209-43d74b960b03.png)

The single inline frame messes up the following line layout. If you take it out, the layout works properly. In trying to debug this I have come thus far, maybe someone can pick up from there:
* When a line break for the text portion after the inline frame is decided, the available width, mainly the width of the containing block, is reported properly. https://github.com/dompdf/dompdf/blob/dd096368ce150b2cc9fe000f86343f6ae205788f/src/FrameReflower/Text.php#L80-L84
* But when reflow happens, and the frame is added to the current line, the containing block reports a smaller width – presumably the width between the page margins – and the text that was calculated to fit onto the current line before is now moved to the next line.
https://github.com/dompdf/dompdf/blob/dd096368ce150b2cc9fe000f86343f6ae205788f/src/FrameReflower/Text.php#L400-L403
https://github.com/dompdf/dompdf/blob/dd096368ce150b2cc9fe000f86343f6ae205788f/src/FrameDecorator/Block.php#L180-L183

**Comment by Mellthas** [comment]
I think I found the culprit, but it would be nice if someone could double-check the logic in PR #2499.

**Comment by eddturtle** [comment]
Thanks for the notes/work above - the code change looks like it fixes our scenario (above) and makes sense :+1:
