### ISSUE TITLE
Error installing Dompdf

### ISSUE THREAD

**Issue by mark1828** [dompdf/dompdf#2480]
So, I'm trying to install a project on github (https://github.com/LaravelDaily/laravel-invoices) that requires dompdf. But I get the following error:

![image](https://user-images.githubusercontent.com/32937993/124710118-9e117080-defc-11eb-83fb-355ce6f48458.png)

I googled a lot and tried the following:

- https://github.com/barryvdh/laravel-dompdf/issues/747 ( Same here with PHP8.0.2 - I fixed it using "barryvdh/laravel-dompdf": "^0.9.0" )
- https://stackoverflow.com/questions/48301899/composer-require-gives-errors-while-installing-barryvdh-laravel-dompdf

But none of these work, I still get the following error: 

![image](https://user-images.githubusercontent.com/32937993/124710454-17a95e80-defd-11eb-9417-d88d8e627dab.png)

This is my composer version: 
![image](https://user-images.githubusercontent.com/32937993/124710703-69ea7f80-defd-11eb-97e1-6299d7377e11.png)

This is my laravel version:
![image](https://user-images.githubusercontent.com/32937993/124710759-7ec71300-defd-11eb-8b54-47ad4e85b243.png)

Any suggestion please let me know, or if you need more information, i'll let you know. Thanks!

My composer.json file:

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "barryvdh/laravel-dompdf": "^0.8.2",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5",
        "laraveldaily/laravel-invoices": "2.0"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\": "app/",
    "Database\Factories\": "database/factories/",
    "Database\Seeders\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
    "Illuminate\Foundation\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r "file_exists('.env') || copy('.env.example', '.env');""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

And my composer.lock file:

```
{
    "name": "dompdf/dompdf",
    "version": "v0.8.3",
    "source": {
        "type": "git",
        "url": "https://github.com/dompdf/dompdf.git",
        "reference": "75f13c700009be21a1965dc2c5b68a8708c22ba2"
    },
    "dist": {
        "type": "zip",
        "url": "https://api.github.com/repos/dompdf/dompdf/zipball/75f13c700009be21a1965dc2c5b68a8708c22ba2",
        "reference": "75f13c700009be21a1965dc2c5b68a8708c22ba2",
        "shasum": ""
    },
    "require": {
        "ext-dom": "",
        "ext-mbstring": "",
        "phenx/php-font-lib": "0.5.",
        "phenx/php-svg-lib": "0.3.",
        "php": ">=5.4.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.8|^5.5|^6.5",
        "squizlabs/php_codesniffer": "2.*"
    },
    "suggest": {
        "ext-gd": "Needed to process images",
        "ext-gmagick": "Improves image processing performance",
        "ext-imagick": "Improves image processing performance"
    },
    "type": "library",
    "extra": {
        "branch-alias": {
            "dev-develop": "0.7-dev"
        }
    },
    "autoload": {
        "psr-4": {
            "Dompdf\": "src/"
        },
        "classmap": [
            "lib/"
        ]
    },
    "notification-url": "https://packagist.org/downloads/",
    "license": [
        "LGPL-2.1"
    ],
    "authors": [
        {
            "name": "Fabien Ménager",
            "email": "fabien.menager@gmail.com"
        },
        {
            "name": "Brian Sweeney",
            "email": "eclecticgeek@gmail.com"
        },
        {
            "name": "Gabriel Bull",
            "email": "me@gabrielbull.com"
        }
    ],
    "description": "DOMPDF is a CSS 2.1 compliant HTML to PDF converter",
    "homepage": "https://github.com/dompdf/dompdf",
    "support": {
        "issues": "https://github.com/dompdf/dompdf/issues",
        "source": "https://github.com/dompdf/dompdf/tree/master"
    },
    "time": "2018-12-14T02:40:31+00:00"
}
```

**Comment by mark1828** [comment]
My composer.json file:

> {
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "barryvdh/laravel-dompdf": "^0.8.2",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5",
        "laraveldaily/laravel-invoices": "2.0"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

And my composer.lock file:

> {
            "name": "dompdf/dompdf",
            "version": "v0.8.3",
            "source": {
                "type": "git",
                "url": "https://github.com/dompdf/dompdf.git",
                "reference": "75f13c700009be21a1965dc2c5b68a8708c22ba2"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/dompdf/dompdf/zipball/75f13c700009be21a1965dc2c5b68a8708c22ba2",
                "reference": "75f13c700009be21a1965dc2c5b68a8708c22ba2",
                "shasum": ""
            },
            "require": {
                "ext-dom": "*",
                "ext-mbstring": "*",
                "phenx/php-font-lib": "0.5.*",
                "phenx/php-svg-lib": "0.3.*",
                "php": ">=5.4.0"
            },
            "require-dev": {
                "phpunit/phpunit": "^4.8|^5.5|^6.5",
                "squizlabs/php_codesniffer": "2.*"
            },
            "suggest": {
                "ext-gd": "Needed to process images",
                "ext-gmagick": "Improves image processing performance",
                "ext-imagick": "Improves image processing performance"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-develop": "0.7-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Dompdf\\": "src/"
                },
                "classmap": [
                    "lib/"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "LGPL-2.1"
            ],
            "authors": [
                {
                    "name": "Fabien Ménager",
                    "email": "fabien.menager@gmail.com"
                },
                {
                    "name": "Brian Sweeney",
                    "email": "eclecticgeek@gmail.com"
                },
                {
                    "name": "Gabriel Bull",
                    "email": "me@gabrielbull.com"
                }
            ],
            "description": "DOMPDF is a CSS 2.1 compliant HTML to PDF converter",
            "homepage": "https://github.com/dompdf/dompdf",
            "support": {
                "issues": "https://github.com/dompdf/dompdf/issues",
                "source": "https://github.com/dompdf/dompdf/tree/master"
            },
            "time": "2018-12-14T02:40:31+00:00"
        }

**Comment by bsweeney** [comment]
The errors thrown by composer isn't specific to Dompdf. The issue is that version 2 of laravel-invoices (to which you're pinned by your own composer.json) expects laravel-dompdf 0.8.x (^0.8.5) per the [caret versioning syntax](https://getcomposer.org/doc/articles/versions.md#caret-version-range-). You should either specify the newer version of laravel-invoices (2.2) or similarly use caret syntax so you don't get pinned to a specific release (^2.0).
