### ISSUE TITLE
Can't use Custom fonts or google fonts

### ISSUE THREAD

**Issue by jogeshpi03** [dompdf/dompdf#2481]
I am trying to implement google fonts and came across with an old thread with same problem. 
And even given example from the thread is not working for me.

https://github.com/dompdf/dompdf/issues/1208#issuecomment-223633664

I am using the Latest version of this library
OS: Windows ( Using WAMP )
Env: Local

PHP code:

```php
ob_start();
include 'inc/views/vendor-special-message.php';
$_template = ob_get_clean();

// dd($_template);

$dompdf = new Dompdf();
$dompdf->loadHtml( mb_convert_encoding($_template, 'HTML-ENTITIES', 'UTF-8') );

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'landscape');
$dompdf->set_option('temp_dir', '');

$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream( time() . ".pdf", array("Attachment" => false));
exit;
```

vendor-special-message.php :

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-15">
    <style>
        @font-face {
            font-family: 'Elegance';
            font-weight: normal;
            font-style: normal;
            font-variant: normal;
            src: url("http://eclecticgeek.com/dompdf/fonts/Elegance.ttf") format("truetype");
        }
        body {
            font-family: 'Elegance', sans-serif;
        }
    </style>
</head>
<body>
    <p>Happy Birthday</p>
</body>
</html>
```

It would be great if someone point me to the right direction.

**Comment by bsweeney** [comment]
First off, temp_dir should be set to _something_. I think in that older post I was just indicating the setting. Since you're attempting to use a Google font you'll also need to enable remote resources (`$dompdf->set_option('isRemoteEnabled', true);`).

**Comment by jogeshpi03** [comment]
@bsweeney Thank you so much, ```$dompdf->set_option('isRemoteEnabled', true);``` works for me.
