### ISSUE TITLE
Headers pile up when there is a page break

### ISSUE THREAD

**Issue by GaloRB** [dompdf/dompdf#2482]
Working locally I have no problem, but when mounting on the hosting when the report is generated, when taking a page break followed by a header, all the headers are accumulated (I show it in the attached image) and then it shows the content, and the truth is that I don't know how to solve it.
![Captura de pantalla de 2021-07-08 12-00-16](https://user-images.githubusercontent.com/67932276/124965543-de99e880-dfe7-11eb-868a-d0e6fbf6baca.png)

**Comment by bsweeney** [comment]
Do you have a sample of the HTML + CSS?
