### ISSUE TITLE
DomPDF & html header / footer show and hide

### ISSUE THREAD

**Issue by luismabenitez** [dompdf/dompdf#2491]
Working on creating a self generated magazine on PDF, where basically I have two type of pages, full image pages and content pages.

The full image pages doesn't need to have the header or the footer so trying to find the way to show / hide the header and the footer in the pages I want. Was trying with z-index, what is a basic concept and sounds like it should to work, but dompdf doesn't like it.

I have defined the css for this two type of pages, the full images as absolute and the other as relative.

```
.cover_sheet {
    position         : absolute;
    top              : 0px;
    left             : 0px;
    right            : 0px;
    bottom           : 0px;
    overflow         : hidden;
    margin           : 0;
    padding          : 0;
}

.margin_sheet {
    position         : relative;
    top              : 70px !important;
    bottom           : 0px;
    overflow         : auto;
    margin           : 40px !important;
    padding          : 0;
}
```

Then, I'm defining every block with:

```
div.page {
    page-break-after: always;
    page-break-inside: auto;
}
```

I need to have it as and because I have blocks with more than one page. I already make it works just having divs for every page with like "" and setting the .margin_sheet as absolute, but then, if the first page on the block overflows, it doesn't show the content of next pages.

So with the solution I have everything works as I expected, but just need to hide the damn header on footer on the "cover_sheet" divs. Any idea?

**Comment by bsweeney** [comment]
z-index should work but you'd have to set a background color in order to hide the things behind it. This is an older post, if you still want to get this working let us know.

**Comment by playcock** [comment]
@luismabenitez 

I was looking for a solution where I could control which pages have a footer and which do not. I am using version 1.2.2 and , yes, I do need to upgrade. Enabling isHtml5ParserEnabled, this is what worked for me. I like it because I can use different footers on different pages, too. This will also work with headers if you want to control those too.

```
use Dompdf\Dompdf;
use Dompdf\Options;

$html = "
<html>
<head>
    <style>
        section.page_break_after {
            page-break-after: always; /* Start a new page before each section, except the first */
        }
        footer {
            border-top: 1px solid #000;
            padding: 10px;
            text-align: center;
            position: fixed;
            bottom: -57px;
            left: -35px;
            right: 0px;
            height: 50px;
        }
    </style>
</head>
<body>
    <section class="page_break_after">
        <h1>Section 1</h1>
        <p>Content without a footer.</p>
    </section>
    <section class="page_break_after">
        <h1>Section 2</h1>
        <p>Content with a footer.</p>
        <footer>Footer for Section 2</footer>
    </section>
    <section class="page_break_after">
        <h1>Section 3</h1>
        <p>Another section without a footer.</p>
    </section>
    <section>
        <h1>Section 4</h1>
        <p>Another section with a footer.</p>
        <footer>Footer for Section 4</footer>
    </section>
</body>
</html>
";

// Initialize options and enable HTML5 parser (optional for Dompdf 2.0.0+)
$options = new Options();
$options->set('isHtml5ParserEnabled', true);
// add any other options you are using

// Instantiate Dompdf
$dompdf = new Dompdf($options);

// Load HTML
$dompdf->loadHtml($html);

// Set paper size
$dompdf->setPaper('letter', 'portrait');

// Render the PDF
$dompdf->render();

// add the rest of your dompdf code
```
