### ISSUE TITLE
Cpdf.php line 3836 "Notice:  Trying to access array offset on value of type null"

### ISSUE THREAD

**Issue by rs2pt** [dompdf/dompdf#2494]
Hi
First time participating, so I hope this is on right place, and hope being usefull.

getting many NOTICE on php log:

> Notice:  Trying to access array offset on value of type null in (...)/dompdf/lib/Cpdf.php on line 3836

Also in debug (everything mode) it gets there at Cpdf.php 3836: "Notice:  Trying to access array offset on value of type null"

LINE 3836:
```
if ($mode === isset($this->currentFillTransparency["mode"]) &&
    $opacity == isset($this->currentFillTransparency["opacity"])
) {
    return;
}
```

is it wise to have there a kind of isset() ?

```
if ($mode === isset($this->currentFillTransparency["mode"]) &&
    $opacity == isset($this->currentFillTransparency["opacity"])
) {
    return;
}
```

**Comment by bsweeney** [comment]
Thanks for the report. We always welcome feedback.

This particular issue was previously reported in issue #2226 and fixed by PR #2227. The next release will include this change.
