### ISSUE TITLE
Lines getting garbled

### ISSUE THREAD

**Issue by gharik** [dompdf/dompdf#2496]
Hello,

firstly, thank you very much for a great tool :-).

We are using Laravel DomPDF v 0.9.0. The hrozion starts a task, that uses DomPDF to generate a document with:

`$pdf = App::make('dompdf.wrapper');`
`$pdf->getDomPdf()->set_option("enable_php", true)->set_option("dpi", 100);`
`$pdf->loadView($this->view, ['content' => $this->content],[], "utf-8");`

After some 100-200 documents, the lines of the pdf start getting garbled:

![grafik](https://user-images.githubusercontent.com/28233415/127118892-da36f585-0217-487c-8721-1df38a5ada75.png)

After this happens, each further generated pdf has the same problem.

The problem gets resolved by running
`php artisan queue:restart`

After that the same job, that was garbled before is ok again. 

The issue appears again after certain amount of documents is generated.

Do you have any ideas what might be causing this? Some kind of caching / memory issue? Let me know, if you need any further info.

**Comment by bsweeney** [comment]
Can't say I've run into this particular issue before. Is the same document rendered each time or does it vary? And does the error begin occurring on or after a particular document?

**Comment by gharik** [comment]
Hi bsweeney and thank you for replying :-)

We have a queue that generates all the documents. Different documents are generated from the queue.

After certain amount of documents is generated, the documents start getting garbled in this way. When this "point of error" is reached, it does not matter which document you generate - all documents, even those, which have been rendered correctly before, are getting garbled if you try to create them again.

Once the queue is restarted, all the documents (before error / after error) are generated correctly again.

As far as we know:

- It is probably not a resource issue - there is no difference in resource issue before queue restart and queue and there is a plenty of resources for the 
- It could be some kind of caching problem.
- It does not seem to be a issue of a template, since the same template is used.
- There does not seem to be any particular document, that could cause this problem - it seems that it corelates with amount of documents that you generate.

**Comment by bsweeney** [comment]
I tried to reproduce with a simple test and did not see any errors. The problem may be relevant to the actual HTML + CSS used for your document. Can you share something I can test against that mirrors what you're trying to render?

Also, is it possible to capture the HTML+CSS of one of the bad renders? Could be something in the generation process as well, but the layout looks more like Dompdf has lost track of line positioning.

FYI laravel-dompdf 0.9.0 is utilizing Dompdf 1.x.x (currently 1.0.2).

**Comment by Waqas-Sharif** [comment]
Hi there, I've created a pdf and stored it on AWS S3 Bucket. But when I tried to get it. Everything rendered smooth but when I tried scrolling it started clipping/cropping lines. 

Here is my html + css code:
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1, width=device-width" />
{{--    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap" />--}}
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <style>
        @page { margin:0px; }

        html {
            font-size: 10px;
            font-family: 'Poppins';
        }

        body {
            margin: 0;
            padding:0;
            line-height: 1;
            font-family: 'Poppins';
        }

        td {
            font-family: 'Poppins';
        }

        p {
            font-family: 'Poppins';
        }

        a {
            font-family: 'Poppins';
        }

        .main_div_list_data>tr:nth-child(even) {
            background: #F7FAF9;
        }
    </style>
</head>

<body style="font-family: 'Poppins';font-style: normal;font-weight: 400;color: #6D6B6B;">
<div
    style="background-image:url(https://mydomain.com/assets/rsz_2.jpg);background-repeat:no-repeat;background-size:cover;height:150px;width:100%;overflow:hidden">
    <img src="https://mydomain.com/assets/logo_white%201.png" style="width:200px; padding:33px 0px 0px 30px;" />


    
    
</div>

<p style="
                               color:#025041;
                               font-size:22px;
                               font-weight: 500;
                               padding:20px;
                           ">
    Top up via M-Pesa
</p>
<div style="
                               max-width:96%;
                               margin: 30px auto;
                               background:#FFFFFF;
                               box-shadow: 0px 1px 4px rgba(122, 122, 122, 0.25);
                               border-radius: 5px;
                               clear: both;
                               margin-top:15px;
                           ">
    <table style="
                                   width:100%;
                                   table-layout:fixed;
                                   word-break: break-all;
                                   word-wrap: break-word;
                                   line-height: 1
                               ">
        <tbody class="main_div_list_data">
        <tr style="background:#FFFFFF">
            <td style="
                                                       font-weight: 400;
                                                       font-size: 14px;
                                                       color:#2E2E2E;
                                                       width:50%;
                                                       padding: 12px 5px;
                                                   ">Pay Bill Number</td>
            <td style="
                                                       font-weight: 500;
                                                       font-size: 13px;
                                                       color:#6D6B6B;
                                                       width: 50%;
                                                   ">
                <div className='right text-capitalize tag'>
                            <span style="letter-spacing: 1px;">
                                {{$paybill_number}}
                            </span>
                </div>
            </td>
        </tr>
        <tr>
            <td style="
                                                   font-weight: 400;
                                                   font-size: 14px;
                                                   color:#2E2E2E;
                                                   width:50%;
                                                   padding: 12px 5px;
                                               ">ABC Account Number</td>
            <td style="
                                                   font-weight: 500;
                                                   font-size: 13px;
                                                   color:#6D6B6B;
                                                   width: 50%;
                                                   letter-spacing: 1px;
                                               ">{{$account_number}}</td>
        </tr>
        </tbody>
    </table>

</div>
<table style="max-width: 70%;
    margin: auto;">
    <tr style="background: #FFFFFF">
        <td>
            To also use ABC to easily manage your business expenses, sign up here : </td>
        <td> <a style="color: #025041;text-decoration: none;font-weight: 600;"
                href="1234567890">Book a demo</a></td>
    </tr>
</table>
</body>
</html>

**Comment by bsweeney** [comment]
@Waqas-Sharif I don't see the same issue rendering that sample. I think you'll need to provide the actual HTML Dompdf is rendering rather than the template.
