### ISSUE TITLE
PHP 8 Issue with GD extension

### ISSUE THREAD

**Issue by gjae** [dompdf/dompdf#2498]
Hello everyone. I have PHP8 installed and i want use this library, but i'm have the follow error:
The PHP GD extension is required, but is not installed.

### Platform: ubuntu 20.10

```bash
$ sudo apt-get install php8.0-gd 

Output 
E: The php8.0-gd package could not be located
E: Could not find any packages using "*" with "php8.0-gd"
E: Could not find any package with regular expression "php8.0-gd"
```

**Comment by bsweeney** [comment]
Sorry, but I don't have enough experience configuring ubuntu (or linux in general) to be of much help.

Based on the Internet that's the way to do it. Maybe your repo cache is corrupt or needs a refresh?

FYI, if you're not rendering images you should be able to run without the gd extension.
