### ISSUE TITLE
Taking too much time for downloading PDF

### ISSUE THREAD

**Issue by mshakirkhan** [dompdf/dompdf#2504]
Hi, Facing issue in these days. DOM PDF is working fine with fewer records but when it crosses 200+ records it is taking too much time. Right now I have records of 714 in text format and it is taking 3 to 5 mins to download PDF. Also, consume up to 90%  CPU while downloading this report which has 714 records.

Here is a method for downloading PDF.

```
public function pdfFile()
{
    $this->load->model('ApiModel');
    $data = $this->ApiModel->getAllParticipantsStudiesFilter();
    $mydata["records"] = json_decode($data);
    $mydata["strdata"]=$this->getawsencryptionkey();
    $this->load->library('pdf');
    $html_content = $this->load->view('pdf', $mydata, true);
    $this->pdf->loadHtml($html_content);
    $this->pdf->setPaper('A4', 'landscape');
    $this->pdf->render();
    $this->pdf->stream("ParticipantReport.pdf", array("Attachment"=>1));
}
```

**Comment by kaedenbrinkman** [comment]
Same thing here - sometimes the page takes 10+ seconds to load. If I just `echo` my html and `exit;` it loads instantly, so I'm not exactly sure why this happens.

**Comment by securious-mayank** [comment]
Facing same issue but query and result instant fast but don't the issue
Sometimes it shows 500 gateway error or sometimes 524 A timeout occurred
