### ISSUE TITLE
Why gotham fonts are not working inside pdf there weight changed

### ISSUE THREAD

**Issue by harshvardhan6565** [dompdf/dompdf#2508]
the gotham bold fonts are working correctly on the html page but whenever odf generated the weight bold fonts are changed : as the weight of fonts changed also they stretched inside the pdf
these are the screenshot 
![Screen Shot 2021-08-03 at 12 06 54 PM](https://user-images.githubusercontent.com/87815964/127969299-01a35c04-9f96-4e5e-ad55-e5fb684bcafa.png)

this is screenshot of the html as the fonts are rendered correctly on the html page but not in the pdf 

![Screen Shot 2021-08-03 at 12 07 10 PM](https://user-images.githubusercontent.com/87815964/127969318-735c3cd5-6751-4362-b118-9d69ed63beae.png)

**Comment by harshvardhan6565** [comment]
i have tried different fonts with the bold property like from google fonts they are working correctly but this happening only with gotham fonts if some on have any suggestions plz let me know i have wasted 3 days on r&d to use gotham inside the pdf but as i'm not a php expert i can't find understandable working solutions these fonts are coming from the server as there is another one which was also coming through the server that is working fine on html as well as inside the pdf .

**Comment by bsweeney** [comment]
Can you provide a sample of the HTML + CSS?

**Comment by harshvardhan6565** [comment]
I have checked the that some particular font files are not working as I tried another font file of the gotham and it renders perfectly although it doesn't mean that first file is corrupted that file is working perfectly on all the browsers
