### ISSUE TITLE
Generated PDF doesnt load Tailwind styles

### ISSUE THREAD

**Issue by ALGAzevedo** [dompdf/dompdf#2513]
I have been trying to generate a pdf with a HTML template using Tailwind in a Laravel project, but i am not beeing able to get my styles correct.
If i load the view in the browser everything is ok, but when  i download the pdf there are no styles.

Is there any known issue regarding Tailwind and DomPdf?

Hope someone can provide me an answer.

**Comment by bsweeney** [comment]
Did you find a solution? My guess is the means by which the style resources are referenced is not compatible with Dompdf.

**Comment by calvinalkan** [comment]
Im having the same issues. Some tailwind styles work some dont. 

For example text-yellow-500 gets compiled by tailwind to: 
`
.text-yellow-500 {
  --tw-text-opacity: 1;
  color: rgba(245, 158, 11, var(--tw-text-opacity));
}`

And this does not seem to work with dompdf

**Comment by bsweeney** [comment]
Dompdf does not currently support CSS variables. Follow #1872 for updates on that.
