### ISSUE TITLE
Mixed font styles aren't converting to PDF correctly.

### ISSUE THREAD

**Issue by recentpuma7650** [dompdf/dompdf#2517]
Having issues with font styles.

The first image represents what it looks like in the browser, the second image what it looks like converted to a PDF. I've shown the styles and HTML elements as part of the text to make this easier to look at. Using DejaVu Sans fonts. PHP 8.

When converting to a PDF the CSS styles version drops underline, whereas the elements version drops bold sometimes.

The html is coming from a contenteditable div. I have the div set to use CSS styles which allows bold to show, but breaks underline. I've also set it so that using underline switches back to elements but because I can't control the order of &lt;u&gt;, &lt;b&gt;, and &lt;i&gt; the bold can't be ensured.

Below is the browser HTML rendering
![HTML Version](https://user-images.githubusercontent.com/19962745/128768461-c623dc3a-3e86-45ac-9e11-c0eed91318bf.png)

Below is the PDF rendering
![PDF Version](https://user-images.githubusercontent.com/19962745/128768470-91478b66-d417-457b-9475-6db335154cc0.png)

**Comment by bsweeney** [comment]
Can you provide a sample of the actual HTML + CSS? I did a simple test and didn't see the same issue.
