### ISSUE TITLE
Custom Font only Applied to Certain HTML Elements

### ISSUE THREAD

**Issue by bradsi** [dompdf/dompdf#2525]
I've followed the documentation to load a custom font using `@font-face` and it's working on a `<p>` element, but not on other HTML elements.

For example, I have some code like this:

```
<p style="font-family: roboto;">
    <strong>{{__('pdf.invoice_no')}}</strong>
 </p>
```

And the font isn't working, it's also not being applied to a `<h2>` element. There are likely other elements as well but I wanted to open this issue and see if anyone else is experiencing this or knows if this is documented anywhere as I couldn't find anything.

I'm using barryvdh/laravel-dompdf v0.9.0 which uses dompdf/dompdf v^1 as a dependency. Laravel v 8.54.0.

Thanks!

**Comment by bsweeney** [comment]
What does your `@font-face` declaration look like? H2 and STRONG would require a bold version of the font.

**Comment by bradsi** [comment]
That sounds like it's probably the solution, will check shortly and report back. Thanks!

**Comment by bradsi** [comment]
@bsweeney That's resolved the issue, really appreciate your help, thank you!
