### ISSUE TITLE
blank pdf

### ISSUE THREAD

**Issue by srakl** [dompdf/dompdf#2535]
When i execute this code on Yii2, php 8.0.8 i get an empty PDF

```
use Dompdf\Dompdf;

....

function actionPdf() {
   $dompdf = new DOMPDF();
   $dompdf->loadHtml('hello world');
   $dompdf->setPaper('A4', 'landscape');
   $dompdf->render();
}
```

anyone have any idea why? Thanks

**Comment by JudsonArtur** [comment]
try it 
$dompdf->loadHtml('<h1>hello world</h1>');
$dompdf->stream("file.pdf",["Attachment"=>false]);

**Comment by srakl** [comment]
i tried

```
$dompdf = new DOMPDF();
$dompdf->loadHtml('<h1>hello world</h1>');
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
$dompdf->stream("file.pdf",["Attachment"=>false]);
```

and

```$dompdf = new DOMPDF();
$dompdf->loadHtml('<h1>hello world</h1>');
$dompdf->setPaper('A4', 'landscape');
$dompdf->stream("file.pdf",["Attachment"=>false]);
```

both still blank

**Comment by bsweeney** [comment]
Are you running this within the context of Yii or as a plain PHP page? Does Yii intercepted the output? The first sample you tried should work. What happens if you add an `exit;` to the end of it?

**Comment by calvinalkan** [comment]
I facing the same issue inside a WordPress project. To confirm that WordPress has nothing to do with the issue I put the readme code in the index.php file before WordPress ever boots.

```php

require_once __DIR__.DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'autoload.php';

$dompdf = new Dompdf();
$dompdf->loadHtml('hello world');

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'landscape');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream();

die();


```

Both methods just show a blank pdf/page. 

I dont know what to do anymore. There are no error messages. The global `$_dompdf_warnings` variable is nul ( debugged this with Xdebug).

The log file output is the following:

<span style='color: #000' title='Frames'>     4</span><span style='color: #009' title='Memory'>   2048.00 KB</span><span style='color: #900' title='Time'>     10.13 ms</span><span  title='Quirksmode'>  <span style='color: #d00'> ON</span></span><br />

The local dev environment is laravel valet.

**Comment by calvinalkan** [comment]
Update:

I got totally confused by the readme example comment "Render the HTML as PDF" , I thought its EITHER render or stream.. When using both it works.

**Comment by bsweeney** [comment]
The render method generates the PDF internally, but it isn't until you stream (to the user) or output (to a variable) that you have the actual PDF.

**Comment by syntheticminds** [comment]
I was also confused by this. I expected the `stream()` function to run `render()` for me if I hadn't already.

**Comment by tedyno** [comment]
> Update:
> 
> I got totally confused by the readme example comment "Render the HTML as PDF" , I thought its EITHER render or stream.. When using both it works.

me too

**Comment by bsweeney** [comment]
> I was also confused by this. I expected the stream() function to run render() for me if I hadn't already.

Something we can consider for a future release. It would require some extra logic to determine if render has already been called so not quite an "add this line here" kind of change. I'll create a ticket.
