### ISSUE TITLE
Font awesome icon 5 not working in generated pdf

### ISSUE THREAD

**Issue by iamkumarishwetha** [dompdf/dompdf#2540]
I have included all the font in internal styles

```
  @font-face {
font-family: "FontAwesomeRegular";
font-weight: normal;
font-style : normal;
       src : url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-regular-400.ttf") format("truetype");
}
@font-face {
font-family: "FontAwesomeBrands";
font-weight: normal;
font-style : normal;
       src : url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-brands-400.ttf") format("truetype");
}
@font-face {
font-family: "FontAwesomeSolid";
font-weight: bold;
font-style : normal;
       src : url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-solid-900.ttf") format("truetype");
} 

.fas{
    font-weight: bold !important;
     font-family: FontAwesomeSolid !important;
}
.fas:before{
    font-weight: bold !important;
    font-family: FontAwesomeSolid !important;
}
.fab{
    font-weight: normal !important;
     font-family: FontAwesomeBrands !important;
}
.fab:before{
     font-weight: normal !important;
    font-family: FontAwesomeBrands !important;
}
.far{
    font-weight: normal !important;
     font-family: FontAwesomeRegular !important;
}
.far:before{
     font-weight: normal !important;
    font-family: FontAwesomeRegular !important;
}
```

then called icons `<i class="fas fa-align-right"></i>`

icons are not showing in pdf

**Comment by bsweeney** [comment]
That's not how you use font-awesome. In addition to referencing the font files you have to reference the FA stylesheet so that you have a definition of what character to display. Just saying you want to use the font isn't enough. For example, fa-align-right is `content:"\f038"`.

You can get all the necessary links via CDN, e.g. https://cdnjs.com/libraries/font-awesome

If you modify your sample to the following it should render correctly:

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<style>
  @font-face {
      font-family: "FontAwesomeRegular";
      font-weight: normal;
      font-style: normal;
      src: url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-regular-400.ttf") format("truetype");
  }

  @font-face {
      font-family: "FontAwesomeBrands";
      font-weight: normal;
      font-style: normal;
      src: url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-brands-400.ttf") format("truetype");
  }

  @font-face {
      font-family: "FontAwesomeSolid";
      font-weight: bold;
      font-style: normal;
      src: url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/webfonts/fa-solid-900.ttf") format("truetype");
  }
</style>
<i class="fas fa-align-right"></i>
```

**Comment by dmcchanaka** [comment]
If you are using laravel dompdf you can download font awesome webfonts folders & replace it inside storage directory. then after add these css

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        @font-face {
            font-family: "FontAwesomeRegular";
            font-weight: normal;
            font-style: normal;
            src: url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/webfonts/fa-regular-400.ttf") format("truetype");
        }

        @font-face {
            font-family: "FontAwesomeBrands";
            font-weight: normal;
            font-style: normal;
            src: url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/webfonts/fa-brands-400.ttf") format("truetype");
        }

        @font-face {
            font-family: "FontAwesomeSolid";
            font-weight: bold;
            font-style: normal;
            src: url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/webfonts/fa-solid-900.ttf") format("truetype");
        }
 </style>
