### ISSUE TITLE
External stylesheet not applied on server, but is in dompdf Debugger

### ISSUE THREAD

**Issue by Twansparant** [dompdf/dompdf#2554]
Hi there,

I'm trying to incorporate your great library into my Laravel/Wordpress project using [Sage](https://roots.io/sage/).
On a POST request submit, I render a Blade view with some parameters and load that as the html:

```php
public static function generateConfigPdf() {
	$dompdf = new Dompdf([
		'isRemoteEnabled'         => true,
		'isHtml5ParserEnabled'    => true,
		'chroot'                  => public_path(), // /mytheme/public
		'defaultMediaType'        => 'all',
		'defaultPaperSize'        => 'a4',
		'defaultPaperOrientation' => 'landscape'
	]);

	// Render blade view
	$config = isset($_REQUEST['configuration']) ? $_REQUEST['configuration'] : null;
	$html   = view('template-product-download', [
		'config' => $config
	])->render();

	// Save as html
	$file = fopen('/srv/www/mydomain.com/current/web/config.html', 'w');
	fwrite($file, $html);
	fclose($file);

	// Stream to browser
	$dompdf->loadHtml($html);
	$dompdf->render();
	$dompdf->stream('my_file_'. $config .'.pdf');
}
```

This works fine, when I save this html it looks great!
The PDF has all the data, but just no styles so it seems.

In my view I add a (local) stylesheet like this:

```blade
<!doctype html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<link href="{!! Roots\asset('styles/print.css')->uri() !!}" media="all" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="l-app" id="app">
			@yield('content')
		</div>
	</body>
</html>
```
Which outputs this:
```html
<link href="https://mydomain.test/app/themes/mytheme/public/styles/print.css?id=1be0ff0085f33a89cf88" media="all" rel="stylesheet" type="text/css">
```
The weird thing is, when I copy paste the output of the generated html (with the stylesheet url) into the [dompdf Debugger](http://eclecticgeek.com/dompdf/debug.php), it DOES generate the styles correctly?

I checked if my options are set the same, and they are:

```
CSS media type: Default (screen)
[x] Enable support for CSS float(still in development)
Defautl Font: Default (serif)
[x] Enable font subsetting (recommended)
Font/Height Ratio: 1.1
[x] Enable the HTML5 document parser (recommended)
Paper size and orientaion: a4 landscape
DPI: Default (72)
dompdf release: 1.0.2
PDF Backend: cpdf
Load the file via: Dompdf::load_html() using local file system
[ ] Turn on layout debugging
[ ] Password protect
PHP Version: 7.4
```
I also installed the `php7.4-gd` extension.
I use Bootstrap 5 as CSS framework so my file does contain css variables etc., but I don't understand that your debugger does render correctly and my server doesn't?

Any thoughts?
Thanks!

**Comment by bsweeney** [comment]
One setting I don't see referenced that could impact the ability to render is if allow_url_fopen is set to true. If that is false Dompdf will make the attempt with curl, so also worthwhile to check if that extension is enabled.

**Comment by Twansparant** [comment]
Thanks for your reply, I just checked with `phpinfo()` and `allow_url_fopen` is on.

**Comment by bsweeney** [comment]
which version of Dompdf are you using locally?

**Comment by Twansparant** [comment]
The latest 1.0.2 version

**Comment by bsweeney** [comment]
Dompdf doesn't need to to save the file, I wonder if there's something else blocking the download. If you do a simple file_get_contents on the URL in a simple PHP file does it retrieve the file correctly?

**Comment by Twansparant** [comment]
> If you do a simple file_get_contents on the URL

What URL? Of the stylesheet?

**Comment by bsweeney** [comment]
And I'm guessing nothing logged to indicate an error retrieving the file.

Running out of ideas. You could try having Dompdf dump any warnings it records to it's internal messaging array: `$_dompdf_show_warnings = true;`

You could also try enabling CSS debugging: `$dompdf = new Dompdf(['debugCss' => true]);`

**Comment by Twansparant** [comment]
Indeed, no errors.

But I did compare the logs from your debugger and mine locally and the styles are just not processed at all.
**Dompdf** should still be able to process a stylesheet from my local domain right? So styles from `https://mydomain.test/app/themes/mytheme/public/styles/print.css` should still be valid?

I discovered that if I use the stylesheet `path` instead of the `uri` locally, it does work correctly:
works in development and production:
`<link href="{!! Roots\asset('styles/print.css')->path() !!}" media="print" rel="stylesheet" type="text/css">`
works in production only:
`<link href="{!! Roots\asset('styles/print.css')->uri() !!}" media="print" rel="stylesheet" type="text/css">`

**Comment by bsweeney** [comment]
I'm not sure what's happening, then. Seems like Dompdf is behaving as if remote resources are disabled. If you add in a reference to an image under the same domain does it load correctly? What about if you reference an image from another domain? And what about stylesheets from another domain?

**Comment by Twansparant** [comment]
> If you add in a reference to an image under the same domain does it load correctly?

No (local) images on the same domain are also not displayed. If I set the stylesheet url to my production environment locally, styles do work? Strange...

**Comment by bsweeney** [comment]
That is strange. Can you check a copy of the HTML Dompdf is working with by calling `$dompdf->outputHtml()` to make sure it looks OK?
