### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted (Outline.php)

### ISSUE THREAD

**Issue by Micccza** [dompdf/dompdf#2557]
Windows 7 SP1 64bit
PHP Version 7.2.30
DOMPDF 1.0.2 (dompdf_1-0-2.zip)

i got the following error message when rendering a PDF:

`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in C:\Work\Web\dompdf102\lib\php-font-lib\src\FontLib\Glyph\Outline.php on line 50`

The PDF was created successfully and looks ok despite the error message.
The PDF has only 1-2 pages.

btw: i use the font "ARIAL UNICODE MS.TTF" at the html code via external css to display unicode characters.

any ideas how to avoid this error message?

**Comment by bsweeney** [comment]
If you can allocate more memory to PHP that would resolve the issue.

**Comment by bsweeney** [comment]
134217728 is 128MB, parsing that Arial Unicode MS font will obviously require more memory. We can probably do something to address low-memory environments but it's not a high priority at this time.
