### ISSUE TITLE
Trailing zero 0 character gets eaten by table cells

### ISSUE THREAD

**Issue by markkimsal** [dompdf/dompdf#2563]
When a table cell requires a word break, if the last character is a single zero (0) it will not render.  Any other character will render the zero, like "10" or "01" or even "00".

```php
$dompdf = new \Dompdf\Dompdf();
$dompdf->loadHtml('<table border="1" style="width:20px"><tr><td>Segment 0</td></tr></table>');
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
$dompdf->stream();
```

**Comment by bsweeney** [comment]
Apparently so. We'll look into this for the next release.

**Comment by Mellthas** [comment]
This was a funny bug, see the referenced commit.

**Comment by markkimsal** [comment]
Thanks for the incredibly quick turn around.  `empty()` bites again!
