### ISSUE TITLE
Critical Security breach through the Sabberworm library (code injection)

### ISSUE THREAD

**Issue by Jany-M** [dompdf/dompdf#2573]
As mentioned in detail [here](https://github.com/sabberworm/PHP-CSS-Parser/issues/343), the Sabberworm library has a HUGE vulnerability and can be used to compromise critically any website.

My specific case was with a WordPress site that had malicious js injected into EVERY single .js file (core, plugins, theme).

I advise anyone using dompdf to lock that folder down immediately hoping it gets addressed asap.

**Comment by bsweeney** [comment]
Dompdf does not use the Sabberworm PHP-CSS-Parser directly, though it is used by the php-svg-lib dependency. Can you open a new issue in that project? We'll keep an eye out for updates to determine what, if anything, we need to do.

**Comment by PowerKiKi** [comment]
@bsweeney, I suspect a false positive. I'd suggest to close this issue to keep the discussion in a single place, https://github.com/sabberworm/PHP-CSS-Parser/issues/343, until we better understand what is going on and to avoid to alert users until we have a clear solution. But that's up to you if you prefer to keep this open.

**Comment by bsweeney** [comment]
I think that makes sense. If the sabberworm issue produces actionable information we can re-open the project-specific tickets.
