### ISSUE TITLE
TypeError : Unsupported operand types: float + string

### ISSUE THREAD

**Issue by Nuranto** [dompdf/dompdf#2577]
Dompdf 1.0.2

PHP 8.0.6

![Capture d’écran 2021-09-27 à 12 03 11](https://user-images.githubusercontent.com/1633463/134888339-e6e05367-a7bf-4fbf-a3cc-39fbba4e7486.png)

**Comment by Mellthas** [comment]
This is already addressed by #2423. The fix will be available with the next release.

**Comment by mhalseyperry** [comment]
Any ETA on the new release?

**Comment by bsweeney** [comment]
1.1.0 is available now.
