### ISSUE TITLE
str_pad problem

### ISSUE THREAD

**Issue by wiseguysby** [dompdf/dompdf#2579]
I've code like this in my php file
```
<?php $str = '( '.str_pad($this->session->userdata('user_name'), 20, ' ', STR_PAD_BOTH).' )';  ?>
```
result in log its ok like this 
![image](https://user-images.githubusercontent.com/33086336/135714539-efe9c905-7634-4adb-8817-2aaa453a7560.png)

but in dompdfresult why the padding missing like this ?
![image](https://user-images.githubusercontent.com/33086336/135714484-cf88d988-e4ee-4a7c-99dd-ba00500a152d.png)

**Comment by bsweeney** [comment]
Dompdf is an HTML parsing library and, as such, squashes whitespace in the document unless the container is styled to prevent that. You'd have to do something like:

```
$str = '<span style="white-space: pre">( '.str_pad($this->session->userdata('user_name'), 20, ' ', STR_PAD_BOTH).' )</span>';  ?>
```

If you're unsure if you're getting the correct render compare against what you see when the content is rendered as HTML by a web browser.

**Comment by wiseguysby** [comment]
great, @bsweeney  thanks a lot...problem solved.
