### ISSUE TITLE
Options.php and dompdf_font_family_cache.dist

### ISSUE THREAD

**Issue by sarateching** [dompdf/dompdf#2582]
Hello, I' new to dompdf so I have barely no idea of what I'm doing, and sorry for my english.

Fisrt of all, I added new fonts to the dompdf_font_family_cache.dist.php file but they are not showing in my PDF.

![image](https://user-images.githubusercontent.com/91954663/136014976-8a378855-5ce1-4111-bc18-948077587627.png)

This is not working either:
![image](https://user-images.githubusercontent.com/91954663/136015092-638f9de8-34ab-4a09-ad8f-b5482d6e2fde.png)

And, can i change things in the Options.php file? Like this?

![image](https://user-images.githubusercontent.com/91954663/136015184-6e0033f4-f2c9-43ad-b2bc-3e36be0ba749.png)
 It was in false before.

And the last thing, images aren't showing etiher.

Sorry for this messy issue but it's my first time here and in Github too. Thank you very much.

**Comment by bsweeney** [comment]
A few notes:
- Dompdf does not currently support OTF fonts, so you'll need a TTF version of any font families.
- You should not need to modify the dompdf_font_family_cache.dist.php file. So long as you are correctly referencing the fonts in your CSS Dompdf will use it for display.
- To ensure best compatibility you should specify the full `@font-face` definition:

```
@font-face {
  font-family: 'SomeFont';
  font-style: normal;
  font-weight: 400;
  src: url(http://example.com/somefont.ttf) format(truetype);
}
```

- If you plan to use the font with a variety of stylings make sure you specify different font weights and styles
- To change the Dompdf options you would just specify the value during Dompdf instantiation:
```
$dompdf = new Dompdf([ 'isRemoteEnabled' => true ]);
```

be sure to read through the wiki, which has a lot of this information: https://github.com/dompdf/dompdf/wiki
