### ISSUE TITLE
Class "Dompdf\Cpdf" not found > PHP8 Update and New Dompdf branch

### ISSUE THREAD

**Issue by TChord22** [dompdf/dompdf#2588]
Hi all, 

Im struggling to find the issue to this, as I see the last issue this was brought up was in 2016.
Still havent figured out a way. Currently we have wp pdf templates running on our WordPress site.

That plugin is so freaking old, we decided to update it ourselves. Using the latest branch develop.
However we seem to have run into some issues we cant seem to find a fix for.

Error List currently pushing:

Fatal error: Uncaught Error: Class "Dompdf\Cpdf" not found in [SITE]/wp-content/plugins/wp-pdf-templates/vendor/dompdf/dompdf/src/Adapter/CPDF.php:203 Stack trace: #0 [SITE]/wp-content/plugins/wp-pdf-templates/vendor/dompdf/dompdf/src/CanvasFactory.php(57): Dompdf\Adapter\CPDF->__construct('letter', 'portrait', Object(Dompdf\Dompdf))
1 [SITE]/wp-content/plugins/wp-pdf-templates/vendor/dompdf/dompdf/src/Dompdf.php(299): Dompdf\CanvasFactory::get_instance(Object(Dompdf\Dompdf), 'letter', 'portrait')
2 [SITE]/wp-content/plugins/wp-pdf-templates/wp-pdf-templates.php(368): Dompdf\Dompdf->__construct()
10 {main} thrown in /usr/www/users/rhistdqxsd/amo21.rhi-staging.co.za/wp-content/plugins/wp-pdf-templates/vendor/dompdf/dompdf/src/Adapter/CPDF.php on line 203 

If anyone could help, we would appreciate it. :)

**Comment by bsweeney** [comment]
That does limit the scope of the problem. Composer should be pulling all the necessary files.

Is this the plugin?
https://github.com/anttiviljami/wp-pdf-templates

I took a quick look at the plugin logic and I don't see anything there that really stands out that would cause this particular issue, except for maybe that the composer.lock file points to an old version of Dompdf. Are you installing dependencies using `composer install` or `composer update`?

**Comment by bsweeney** [comment]
closing for lack of updates, #2615 and #2660 may have useful info
