### ISSUE TITLE
CSS FLOAT property support

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#26]
_Original author: goo...@gmail.com (May 29, 2009 20:51:58)_

<b>What would you like dompdf to do:</b>
Either have a more robust table-within-table functionality (also
div-within-table), or add float support.

<b>Do you have an example:</b>

``` html
<div style="width:65mm; height:40mm; float:left;">Block one</div>
<div style="width:65mm; height:40mm; float:left;">Block two</div>
<div style="width:65mm; height:40mm; float:left;">Block three</div>
<div style="width:65mm; height:40mm; float:left;">Block four</div>
<div style="width:65mm; height:40mm; float:left;">Block five</div>
<div style="width:65mm; height:40mm; float:left;">Block six</div>
```

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=19_

**Comment by bsweeney** [comment]
Individual known float bugs are covered by #2258 and #2831
