### ISSUE TITLE
Use composer to create packaged release ?

### ISSUE THREAD

**Issue by PowerKiKi** [dompdf/dompdf#2608]
Today DomPdf can either use composer's autoload mechanism, or use its custom autoload mechanism. I would like to suggest to drop the custom autoload mechanism. First of all because nowadays composer is quite ubiquitous.

But more importantly, because of the fact that DomPdf has this custom mechanic, it makes it mandatory for all (transitives) dependencies to also have such thing. This is visible in packaged version of DomPdf's `autoload.inc.php`:

```php
// Sabberworm
spl_autoload_register(function($class)
{
    if (strpos($class, 'Sabberworm') !== false) {
        $file = str_replace('\\', DIRECTORY_SEPARATOR, $class);
        $file = realpath(__DIR__ . '/lib/php-css-parser/lib/' . (empty($file) ? '' : DIRECTORY_SEPARATOR) . $file . '.php');
        if (file_exists($file)) {
            require_once $file;
            return true;
        }
    }
    return false;
});

// php-font-lib
require_once __DIR__ . '/lib/php-font-lib/src/FontLib/Autoloader.php';

//php-svg-lib
require_once __DIR__ . '/lib/php-svg-lib/src/autoload.php';
```

Removing entirely `src/autoload.php` and similar in dependencies would simplify maintenance (in at least 3 packages) and allow dependencies to manage their own dependencies independently of DomPdf.

As for the packaged version, if is deemed too important to drop it, then it can be re-created with automated third party tools, such as https://php-download.com/package/dompdf/dompdf. Even though my personal preference would be to not recommend pre-packaged version, because composer really is superior to "download and unzip".

I'd create a PR for that. What do you think ?

**Comment by bsweeney** [comment]
Though not nearly as high as Composer installation, the packaged version still get quite a few downloads (https://api.github.com/repos/dompdf/dompdf/releases). So I think we'd probably do well to keep it around.

The autoload.inc.php seems irrelevant to the discussion, since dependency management wouldn't (typically) use the packaged release. So I think we can just focus on how Dompdf works with Composer and for source copied scenarios. It is true that the autoloader is excessive for when Composer is involved. Curious to see what changes you would make.

And hear any arguments against such a change.

**Comment by PowerKiKi** [comment]
Manually summing [the chart points](https://packagist.org/packages/dompdf/dompdf/stats#v1.0.2), I counted 122 000 downloads for composer, and 26 085 for packaged version. Both for DomPdf 1.0.2 only. So about **17% of downloads are packaged version**. It is a bit higher than I expected. And so it would be best to keep the packaged version available, as you said.

My point was to specifically delete `autoload.inc.php` (which apparently does not live in this repository ?), and related files in this and other repositories (because they _do_ live in the repository, [here](https://github.com/dompdf/dompdf/blob/master/src/Autoloader.php), [here](https://github.com/PhenX/php-svg-lib/blob/master/src/autoload.php) and [here](https://github.com/PhenX/php-font-lib/blob/master/src/FontLib/Autoloader.php)). And instead use a tool to generate the autoloading mechanism.

Even though I did mention https://php-download.com, I think it actually is better to use composer itself to package this library (duh!). This way both release type work exactly the same (directly via composer, or indirectly via composer), and maintenance for 3 projects is reduced.

If you can share your packaging scripts, I might give you a more concrete plan on how we could do that. But it would probably be something similar to:

```
php7.1 /usr/local/bin/composer install --no-dev --optimize-autoloader
zip  -r dompdf.zip ../dompdf/ -x .git/\* -x tests/\* -x .idea/\*
```

**Comment by PowerKiKi** [comment]
I updated the title to better reflect the current discussion. Using composer for custom autoload mechanism would still be a way to simplify maintenance while providing a more robust release pipeline (to manage transient dependencies).

**Comment by markkimsal** [comment]
The packaged version is invaluable for creating an installation that can manage multiple versions of DomPDF for testing.  You can't simultaneously have 1.1.1 and 1.2.0 installed and choose between them with composer.

**Comment by PowerKiKi** [comment]
This discussion is no longer about dropping packaged version, but instead it is about how we can improve the packaged version release process. So that it requires less work for maintainers, across multiple packages, while keeping the same benefits for users. It might even be slightly more performant during runtime (though I'm not quite sure about that yet).

@bsweeney you didn't reply to this proposal yet. Would you be interested in using composer to create the packaged release instead of the current homemade mechanism ?

**Comment by bsweeney** [comment]
I'd be interested to see what you have for this. Using composer to create the packaged release makes sense since. As noted in dompdf/utils#12 I didn't pay enough attention to path changes in recent releases.

**Comment by markkimsal** [comment]
I threw together a bash script to construct a release that looks the same as the old package - i.e. the top folder is `dompdf-x.y.z` and there's a top-level `autoload.inc.php`.  I tested the output with a project that is currently using the old style packages and it seems to function as a drop-in replacement.  I have not tested it in a root project that doesn't already have composer support, but it seems like a compiled and distributed vendor/autoload.php should just work.

The new replacement for `autoload.inc.php` is just

```php
require (__DIR__ . '/vendor/autoload.php');
```

**Comment by PowerKiKi** [comment]
I created #2799 to suggest what I had in mind. If it is merged, I'll update other packages too to remove their manual autoload mechanism.

**Comment by ndmax** [comment]
@PowerKiKi @bsweeney 

I do not use Composer, and I am not going to install for one dependency.  Neither am I going to manually download and install a packaged version.  I just use a bash script to pull the repo and copy the files (along with every other PHP library) as one part of the build pipeline.

So for me dropping the custom autoload fundamentally broke dompdf.  

Is there any possibility of including a "build" directory on the master branch, which contains the generated output from the new Composer build process (essentially what you're zipping up as a "package")?

**Comment by bsweeney** [comment]
@ndmax that's a possibility if needed. Before we go that step, however, could you use something like the following command to grab the packaged release instead?
https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8

Maybe also worthwhile for us to add a generically named download to the latest release so you can just use https://github.com/dompdf/dompdf/releases/latest/download/dompdf.zip to get the packaged release.

I want to say there are also some other possible options but I'd have to mull it over.

**Comment by PowerKiKi** [comment]
A generically named download seems like a reasonable compromise.

Including the build in the repo, on the other hand, sounds like a huge step backwards and would add burdens to every single maintainers and contributors that would then have to deal with that anytime they work on the project.

I don't think it's fair to refuse to use an automated tool that is working for million of users, and then ask for special treatment for a very small minority that, somehow don't even want to manually use the packaged version kindly prepared by @bsweeney, but instead are trying to reproduce a homebrew version of an automated tool.

It would take much less time to learn the basics of composer, than to debug your script, find this issue and reply to it. Not even mentioning our time spent replying.

**Comment by ndmax** [comment]
@bsweeney Sure, I could grab a generic "latest release" URL _via_ `wget` or `curl` or whatever and unpack.

**Comment by PowerKiKi** [comment]
This will get you the first asset of the latest release of dompdf in a file that is always named `dompdf.zip`. So pretty much what you want:

```sh
curl https://api.github.com/repos/dompdf/dompdf/releases | jq '.[0].assets[0].browser_download_url' | xargs curl -L --output dompdf.zip
```

**Comment by ndmax** [comment]
@PowerKiKi Yes that works.
