### ISSUE TITLE
Poor table rendering, not scaling to height of div, height of cell background doesn't match height of cell

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#261]
_Original author: themauiw...@gmail.com (March 30, 2011 23:40:50)_

<b>What steps will reproduce the problem?</b>
1. Please view source and CSS for http://alakani.org/tmwtest/invoice-html.php?ord_id=10000 -- both validate at w3.  I've already had to use a bunch of position: absolutes to get the top part to work right, when relative looked fine in all browsers.

<b>What is the expected output? What do you see instead?</b>
Expected is same as browser rendering.  Instead, http://alakani.org/tmwtest/invoice.php?ord_id=10000

<b>What version of the product are you using? On what operating system?</b>
Latest CVS code, linux/apache server.

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=255_

**Comment by simonberger** [comment]
Sample HTML is gone and from the comments the actual problem is not clear.
