### ISSUE TITLE
Bangla language font break problem

### ISSUE THREAD

**Issue by junayedmahmud** [dompdf/dompdf#2627]
Recently I tried to generate pdf with Dompdf. I see bangla language not loading with font face but it works with load_font.php. 

After that i realized that fonts are broken in whole PDF . 
![image](https://user-images.githubusercontent.com/16017682/139688796-9fbee6fd-8721-40d3-bcdc-104eb08512d9.png)

face font dont load fonts

![image](https://user-images.githubusercontent.com/16017682/139688904-8f0224d2-a58e-4640-b890-4edd8358079e.png)

I also tried with niklasravnsborg but CSS dont work like as dompdf. But fonts are okey. I think use OTL dont work in DomPDF thats why complex word dont show correctly. Have any way to fix that? I just want correct form with DomPDF.
Here is correct generated PDF.
![image](https://user-images.githubusercontent.com/16017682/139689528-c0689f90-4520-4691-b599-3b7cdcbd21f1.png)

I just want it with dompdf. Please Help

**Comment by bsweeney** [comment]
We'd need to see a sample of your usage to provide guidance on what's going wrong using CSS to load the font.

As for specific support for Bangali/Bengla, in addition to a supporting font the text would need to be run through a shaping engine prior to rendering. Text shaping is not yet supported by Dompdf and so you would have to do this prior to rendering your document.

The shaping issue is covered by #2619 so please follow that issue for updates.
