### ISSUE TITLE
min-height applied to table cell ignored

### ISSUE THREAD

**Issue by bsweeney** [dompdf/dompdf#2632]
```
<table style="border-collapse: collapse; border: 1px solid black"><tr><td style="min-height: 200px;"></td></tr></table>
<table style="border-collapse: separate; border: 1px solid black"><tr><td style="min-height: 200px;"></td></tr></table>
```

**Comment by Mellthas** [comment]
Given that this is not covered by CSS 2.1 (see https://www.w3.org/TR/CSS21/visudet.html#propdef-min-height) and does not seem to be handled by Chrome or Firefox as well from a quick look, I wouldn't consider it a bug ;-).

**Comment by bsweeney** [comment]
hm ... I could have sworn I got a min height from Firefox when I was testing. I must've been moving through old tickets too fast and been looking at the wrong render 😞 

Thanks for looking at it from the spec standpoint. I was thinking I should do that and now I have proved to myself that I should. 😭
