### ISSUE TITLE
No longer able to embed vimeo player

### ISSUE THREAD

**Issue by chrisakeley** [dompdf/dompdf#2635]
As of dompdf 0.8.2, the following code would successfully embed a video in a PDF:

```
<div style="padding:56.25% 0 0 0;position:relative;"><iframe allow="autoplay; fullscreen; picture-in-picture" allowfullscreen="" frameborder="0" src="https://player.vimeo.com/video/370125692?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Josh_LA_c"></iframe></div>
<script src="https://player.vimeo.com/api/player.js"></script>
```
In dompdf 1.0.2, this produces a box where the video should be but no video. 

In both cases, I'm using PHP 7.4. For the 1.0.2 version I am setting isRemoteEnabled to 'true'.

**Comment by bsweeney** [comment]
Is that true? Do you have a sample PDF generated by Dompdf with embedded video?

Dompdf does not currently support iframes (#1228). And general JavaScript parsinge/execution (#563) is definitely not supported (and unlikely to be).

**Comment by chrisakeley** [comment]
My mistake. It wasn't working in 0.8 either.
