### ISSUE TITLE
Imagick::clone method is deprecated

### ISSUE THREAD

**Issue by srakl** [dompdf/dompdf#2640]
When i add this into my html 

`<img src="https://static.blabla.com/wp-content/uploads/2020/12/logo.png" width="200px" height="57px">`

i get this error

`Imagick::clone method is deprecated and it's use should be avoided`

i use this code to generate my pdf

```
        $options = new Options();
        $options->set('isRemoteEnabled', TRUE);
        $options->setDpi(150);
        

        $dompdf = new DOMPDF($options);
        
        $context = stream_context_create([ 
            'ssl' => [ 
                'verify_peer' => FALSE, 
                'verify_peer_name' => FALSE,
                'allow_self_signed'=> TRUE 
            ] 
        ]);
        $dompdf->setHttpContext($context);

        $dompdf->loadHtml($view); 

        $dompdf->setPaper('A4', 'portrait');

        $dompdf->render();
        $dompdf->stream($filename, [ "Attachment" => 1]);

        Yii::$app->end();
```

i'm using PHP 8

any idea how to resolve this?

**Comment by bsweeney** [comment]
Some IMagick installations don't appropriately report the version installed. The next release (which should be published very soon) will have improved logic.

If you need the fix sooner you can use the release-ready version of the code in the master branch (dev-master in composer). Or you can manually patch the code with the fix (see issue #1296 or PR #2373).
