### ISSUE TITLE
dompdf and PHP74 compatibility warnings and errors from PHP_CodeSniffer-3.6.1 and PHPCompatibility-9.3.5

### ISSUE THREAD

**Issue by webservant316** [dompdf/dompdf#2649]
I am upgrading PHP71 to PHP74 or PHP80. So I am running PHP_CodeSniffer-3.6.1 and PHPCompatibility-9.3.5 to test for issues.

Folowing are the errors and warnings reported.

/dompdf/lib/Cpdf.php	467	33	warning	Targeting a 'switch' control structure with a 'continue' statement is strongly discouraged and will throw a warning as of PHP 7.3.
/dompdf/lib/Cpdf.php	474	33	warning	Targeting a 'switch' control structure with a 'continue' statement is strongly discouraged and will throw a warning as of PHP 7.3.
/dompdf/lib/Cpdf.php	481	33	warning	Targeting a 'switch' control structure with a 'continue' statement is strongly discouraged and will throw a warning as of PHP 7.3.
/dompdf/lib/Cpdf.php	488	33	warning	Targeting a 'switch' control structure with a 'continue' statement is strongly discouraged and will throw a warning as of PHP 7.3.
/dompdf/lib/html5lib/TreeBuilder.php	3445	13	warning	Since PHP 7.0, functions inspecting arguments, like debug_print_backtrace(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter \$node\" was used
/dompdf/lib/php-svg-lib/src/Svg/Surface/SurfaceCpdf.php	36	33	error	Extension 'cpdf' is removed since PHP 5.1; Use pecl/pdflib instead
/dompdf/src/Renderer/Text.php	140	21	warning	Targeting a 'switch' control structure with a 'continue' statement is strongly discouraged and will throw a warning as of PHP 7.3.
/dompdf/src/Adapter/CPDF.php	198	28	error	Extension 'cpdf' is removed since PHP 5.1; Use pecl/pdflib instead
/dompdf/src/Dompdf.php	610	33	warning	Targeting a 'switch' control structure with a 'continue' statement is strongly discouraged and will throw a warning as of PHP 7.3.
/dompdf/src/Dompdf.php	631	25	warning	Targeting a 'switch' control structure with a 'continue' statement is strongly discouraged and will throw a warning as of PHP 7.3.
/dompdf/src/Helpers.php	481	20	warning	Since PHP 7.0, functions inspecting arguments, like debug_backtrace(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter \$type\" was used

**Comment by bsweeney** [comment]
Which version of Dompdf are you using?

We addressed a number of PHP compatibility issues a few releases ago. Recommend you upgrade to the latest release. See #1822.

We do not use the cpdf extension, and as of 0.8.4 we have put the Cpdf back end in its own namespace. See #1851.
