### ISSUE TITLE
Image not rendering in PDF when using Symfony twig

### ISSUE THREAD

**Issue by pottink** [dompdf/dompdf#2655]
I'm trying to write some images to the PDF using:

```
<img src="{{ absolute_url(vich_uploader_asset(attachment, 'imageFile')) }}" alt="{{ attachment.imageName }}" />
```

Using this config:

```
        $options = new Options();
        $options->setIsRemoteEnabled(true);
        $options->setIsHtml5ParserEnabled(true);

        $pdf = new Dompdf($options);
        $pdf->setPaper('A4');

        $pdf->loadHtml($this->twig->render(
            'invoice/pdf.html.twig',
            ['invoice' => $invoice]
        ));
        $pdf->render();

        file_put_contents(
            sprintf('%1$s/%2$s/%3$s.pdf', $this->projectDir, $this->outputDir, $invoice->getNumber()),
            $pdf->output()
        );
```

But the image won't render, only the alt value is displayed.

**Comment by bsweeney** [comment]
In twig the absolute_url generates a value with the protocol and domain, e.g. http://example.com/img/imagefile.png, correct? Have you confirmed that the value generated is a valid URL? If it is would the file be behind access control, use a non-public domain, or requested via TLS where the server is using a self-signed cert?

**Comment by pottink** [comment]
Yes indeed, this will render the full URL. I have echo'ed it to test in the PDF and the URL is correct.

**Comment by bsweeney** [comment]
Does dompdf have read/write access to the temp directory (`sys_get_temp_dir()` by default)?

**Comment by pottink** [comment]
After deploy I works. So indeed that was the issue. Thanks @bsweeney !
