### ISSUE TITLE
I am getting the error when dompdf is downloading in laravel

### ISSUE THREAD

**Issue by Lakshmi-TN** [dompdf/dompdf#2667]
I am getting these error when downloading the pdf Anyone please help on these issue.

My version php-8
larvael-8,
dompdf-1.1.0,
barryvdh/dompdf-1.0

then also it is coming i m not use any type operand +,-,*,/

![image](https://user-images.githubusercontent.com/94172590/144206184-702d816f-a3eb-434b-b0d3-644072fde438.png)
![image](https://user-images.githubusercontent.com/94172590/144207756-8ba2be41-5c18-45d7-b5b4-6cfdf81dc8b3.png)

**Comment by Mellthas** [comment]
Please make sure to update to the latest dompdf version, this should already be addressed in version 1.1.1. See #2646.

**Comment by Lakshmi-TN** [comment]
I changed the version 1.1.1 also same error getting..please help on this

**Comment by Lakshmi-TN** [comment]
> Please make sure to update to the latest dompdf version, this should already be addressed in version 1.1.1. See #2646.

I changed the version 1.1.1 also same error getting..please help on this

**Comment by Mellthas** [comment]
Is the exception thrown for the exact same line number and file? It should be impossible with dompdf version 1.1.1 to throw that exception in that line, but you might have discovered a similar bug elsewhere. Can you provide some sample HTML and CSS to exhibit the issue?

**Comment by Lakshmi-TN** [comment]
<!DOCTYPE html>
<html>
<head>
    <title>One transaction pdf</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style type="text/css">
        .border img {
            width: 20%;
            padding-top: 30px;
        }

        .border {
            border: 4px solid #1A2E22;
            text-align: center;
            width: 698px;
            margin: 0 auto;
            /* height:1050px; */
        }

        h2 {
            font-size: 30px;
            font-weight: 900;
            margin-bottom: 5px;
            margin-top: 0px;
            padding-top: -15px;
        }

        p {
            font-weight: 600;
            font-size: 25px;
            margin-top: 0px;
        }

        .text p {
            text-align: center;
            font-size: 15px;
            font-weight: 500;
        }

        .text .text1 {
            border-left: 1px solid grey;
            border-right: 1px solid grey;
            padding-left: 4px;
            padding-right: 4px;
        }

        .borders {
            margin: 0px auto;
            width: 95%;
            border-collapse: collapse;
            border: 2px solid black;
        }

        th {
            padding: 10px 15px;
            border: 1px solid black;
            font-weight: 600;
        }

        th {
            padding: 10px 15px;
            border: 1px solid black;
            font-weight: 600;
        }

        td {
            padding: 10px 15px;
            border: 1px solid black;
        }

        .borders td {
            text-align: center;
        }

        .border1 {
            border-top: 1px solid #1a2e22;
            border-bottom: 1px solid #1a2e22;
        }

        h4 {
            margin-bottom: 5px;
            color: red;
        }

        h6 {
            text-align: left;
            padding: 0px 10px;
            margin: 10px;
        }

        .bottom {
            background-color: #1a2e22;
            text-align: center;
            padding: 10px;
            color: #fff;
            margin: 10px;
        }

        .bottom h3 {
            margin: 2px;
            padding: 1px;
            font-size: 16px;
        }

        .second {
            text-align: right;
        }

        .remove-borders {
            border: none;
            margin: 0px auto;
            width: 95%;
        }

        .remove-borders td {
            border: none;
        }

        @media only screen and (max-width: 767px) {
            h1 {
                font-size: 30px !important;
            }

            .bottom p {
                font-size: 24px !important;
            }
        }
    </style>
</head>

<body>
<div class="border">
    <img src="{{ public_path('images/goldsikka-limited-logo.jpeg') }}" alt="logo">
    <h2> Goldsikka Limited</h2>
    <p>{{$transaction->txnHeading}}</p>
    <div class="text">
        <p>CIN No : U51909TG2019PLC130903 | GSTIN No : 36AAHCG7082N1ZZ | PAN No : AAHCG7082N</p>
    </div>
    <table class="remove-borders">
        <tr>
            <td> Name : {{$transaction->userName->name}} </td>
            <td class="second">Transaction Date : {{$transaction->date}} </td>
        </tr>
        <tr>
            <td> Transaction ID : {{$transaction->id}}</td>
            <td class="second"> Transaction Type : {{$transaction->txnType}}</td>
        </tr>
    </table>

    <table class="borders">
        <tr>
            <th>Grams</th>
            <th>Gold Rate (per gram)<br> (Only Raw Metal)</th>
            <th>Gold Metal Amount</th>
            @if($transaction->txnType == 'Buy')
                <th>Taxes & Other Levies<br> (GST(3%),TCS(0.1%),<br>TDS(0.1%),Other Levies)</th>
                <th>Total Amount</th>
            @endif
        </tr>
        <tr class="border1">
            <td> {{$transaction->grams}}</td>
            <td> {{$transaction->gold_price_per_gram}}</td>
            <td> Rs. {{$transaction->amount}}</td>
            @if($transaction->txnType == 'Buy')
                <td>Rs. {{$transaction->gst}}</td>
                <td>Rs. {{$transaction->total_amount}}</td>
            @endif
        </tr>
    </table>
    <br><br>
    <h4>*This is Computer generated invoice as such signature is not required</h4>

    <h6>Note:The Delivery / Claim of the Gold Bullion / Silver Bullion / Gold Jewellery mention above in this Payment
        Receipt can be Delivered / Claimed as per the minimum values applicable and agreed in the Terms and Conditions
        of the choosen Plan.
        The Terms and Conditions of the Gold Bullion / Silver Bullion / Gold Jewellery Plan has been read, understood
        and agreed by the bearer of the Payment Receipt and subsequent subscription to the choosen plan of Goldsikka
        Limited.
    </h6>

    <div class="bottom">
        <h3>----</h3>
        <h3>---</h3>
    </div>

</div>
</body>
</html>

**Comment by Lakshmi-TN** [comment]
<!DOCTYPE html>
<html>
<head>
    <title>One transaction pdf</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style type="text/css">
        .border img {
            width: 20%;
            padding-top: 30px;
        }

        .border {
            border: 4px solid #1A2E22;
            text-align: center;
            width: 698px;
            margin: 0 auto;
            /* height:1050px; */
        }

        h2 {
            font-size: 30px;
            font-weight: 900;
            margin-bottom: 5px;
            margin-top: 0px;
            padding-top: -15px;
        }

        p {
            font-weight: 600;
            font-size: 25px;
            margin-top: 0px;
        }

        .text p {
            text-align: center;
            font-size: 15px;
            font-weight: 500;
        }

        .text .text1 {
            border-left: 1px solid grey;
            border-right: 1px solid grey;
            padding-left: 4px;
            padding-right: 4px;
        }

        .borders {
            margin: 0px auto;
            width: 95%;
            border-collapse: collapse;
            border: 2px solid black;
        }

        th {
            padding: 10px 15px;
            border: 1px solid black;
            font-weight: 600;
        }

        th {
            padding: 10px 15px;
            border: 1px solid black;
            font-weight: 600;
        }

        td {
            padding: 10px 15px;
            border: 1px solid black;
        }

        .borders td {
            text-align: center;
        }

        .border1 {
            border-top: 1px solid #1a2e22;
            border-bottom: 1px solid #1a2e22;
        }

        h4 {
            margin-bottom: 5px;
            color: red;
        }

        h6 {
            text-align: left;
            padding: 0px 10px;
            margin: 10px;
        }

        .bottom {
            background-color: #1a2e22;
            text-align: center;
            padding: 10px;
            color: #fff;
            margin: 10px;
        }

        .bottom h3 {
            margin: 2px;
            padding: 1px;
            font-size: 16px;
        }

        .second {
            text-align: right;
        }

        .remove-borders {
            border: none;
            margin: 0px auto;
            width: 95%;
        }

        .remove-borders td {
            border: none;
        }

        @media only screen and (max-width: 767px) {
            h1 {
                font-size: 30px !important;
            }

            .bottom p {
                font-size: 24px !important;
            }
        }
    </style>
</head>

<body>
<div class="border">
    <img src="{{ public_path('images/goldsikka-limited-logo.jpeg') }}" alt="logo">
    <h2> Goldsikka Limited</h2>
    <p>{{$transaction->txnHeading}}</p>
    <div class="text">
        <p>CIN No : 324234 | GSTIN No : 36AAH23282N1ZZ | PAN No : AAH337082N</p>
    </div>
    <table class="remove-borders">
        <tr>
            <td> Name : {{$transaction->userName->name}} </td>
            <td class="second">Transaction Date : {{$transaction->date}} </td>
        </tr>
        <tr>
            <td> Transaction ID : {{$transaction->id}}</td>
            <td class="second"> Transaction Type : {{$transaction->txnType}}</td>
        </tr>
    </table>

    <table class="borders">
        <tr>
            <th>Grams</th>
            <th>Gold Rate (per gram)<br> (Only Raw Metal)</th>
            <th>Gold Metal Amount</th>
            @if($transaction->txnType == 'Buy')
                <th>Taxes & Other Levies<br> (GST(3%),TCS(0.1%),<br>TDS(0.1%),Other Levies)</th>
                <th>Total Amount</th>
            @endif
        </tr>
        <tr class="border1">
            <td> {{$transaction->grams}}</td>
            <td> {{$transaction->gold_price_per_gram}}</td>
            <td> Rs. {{$transaction->amount}}</td>
            @if($transaction->txnType == 'Buy')
                <td>Rs. {{$transaction->gst}}</td>
                <td>Rs. {{$transaction->total_amount}}</td>
            @endif
        </tr>
    </table>
    <br><br>
    <h4>*This is Computer generated invoice as such signature is not required</h4>

    <h6>Note:The Delivery / Claim of the Gold Bullion / Silver Bullion / Gold Jewellery mention above in this Payment
        Receipt can be Delivered / Claimed as per the minimum values applicable and agreed in the Terms and Conditions
        of the choosen Plan.
        The Terms and Conditions of the Gold Bullion / Silver Bullion / Gold Jewellery Plan has been read, understood
        and agreed by the bearer of the Payment Receipt and subsequent subscription to the choosen plan of Goldsikka
        Limited.
    </h6>

    <div class="bottom">
        <h3>Registered Address : ---</h3>
        <h3>Tel: ---</h3>
    </div>

</div>
</body>
</html>

**Comment by Mellthas** [comment]
Using that sample, I can reproduce the exception with 1.1.0, but not with 1.1.1. Can you double check that your dompdf is on version 1.1.1? Line 198 in `src/FrameReflower/Block.php` needs to read `$rm = (float) $rm + $diff;`.
