### ISSUE TITLE
PDF Producer meta issue

### ISSUE THREAD

**Issue by jamieburchell** [dompdf/dompdf#2673]
Not sure if this is related to https://github.com/dompdf/dompdf/issues/1541, but with v1.1.1 I'm seeing this:

![Capture](https://user-images.githubusercontent.com/3270426/144598147-c8edd2a9-5966-4595-b162-16c9d9d0dede.PNG)

```
$options = new \Dompdf\Options;
$options->set( 'isRemoteEnabled', true );

$pdf = new \Dompdf\Dompdf( $options );
$pdf->loadHtml( '<p>Foo</p>' );
$pdf->setPaper( 'A4', 'portrait' );
$pdf->render();
$pdf->add_info( 'Creator', 'Jamie' );
$pdf->get_canvas()->get_cpdf()->setEncryption();
```

I also can't see the creator in the document properties, but this might be expected.

In v1.0.2 I actually don't see anything here using the same code:

![Capture](https://user-images.githubusercontent.com/3270426/144597778-a2eb23a4-37dd-4e8a-8a6e-874e19532ace.PNG)

**Comment by jamieburchell** [comment]
Actually seems more bizzare than I thought. I just produced 2 PDFs with 1.1.1. First PDF has a meta title and all expected meta data. Second PDF created had none of those.

**Comment by jamieburchell** [comment]
@Tigla suggested fix seems to resolve the issue @bsweeney
https://github.com/dompdf/dompdf/issues/1541#issuecomment-700951464

**Comment by bsweeney** [comment]
Thank you for following through with the research. Seems like a minor enough change it might be worthwhile to incorporate in the next release.

**Comment by bsweeney** [comment]
I think that's the correct fix. A bare date shouldn't run through the filter. However, dates aren't excepted from encryption and the change is running the encrypted text through the filter.
