### ISSUE TITLE
Is it possible to set/change an option instead of replacing the whole options

### ISSUE THREAD

**Issue by dodaydream** [dompdf/dompdf#2690]
Hi, It seems calling `setOptions` will override all the options.

I would like to ask how can I set an option individually, or is it possible to add such a method?

Thanks

**Comment by erikn69** [comment]
`$dompdf->getOptions()->set($key,$value);`
https://github.com/dompdf/dompdf/blob/643eb722100cfaff6c3e506e9a9b64add804256b/src/Dompdf.php#L1390-L1393
