### ISSUE TITLE
DOMNode does not have getAttribute method

### ISSUE THREAD

**Issue by bsweeney** [dompdf/dompdf#2693]
In the Dompdf class (line number 605) We're calling the getAttribute method. The usage here is not quite correct since the method is part of the DOMElement class and not the DOMNode class. And the collection we're pulling the element from is a DOMNode collection. An error is not thrown during runtime since the node we're accessing is actually a DOMElement. But the specific logic we use can be better written.

_Originally posted by @bsweeney in https://github.com/dompdf/dompdf/discussions/2692#discussioncomment-1786838_

**Comment by markkimsal** [comment]
```php
        if ($base_nodes->length
            && $base_nodes->item(0)->attributes
            && ($href = (string)$base_nodes->item(0)->attributes->getNamedItem("href"))
        ) {
            [$this->protocol, $this->baseHost, $this->basePath] = Helpers::explode_url($href);
        }
```
? or

```php
        $base_nodes = $this->dom->getElementsByTagName("base");
        // the "base" tag is actually a DOMElement, but we only have
        // a container of DOMNodeList, which can only have DOMNodes, the parent class.
        /** @var DOMElement $base_node */
        $base_node = $base_nodes->item(0);
        if ($base_node && ($href = $base_node->getAttribute("href"))) {
            [$this->protocol, $this->baseHost, $this->basePath] = Helpers::explode_url($href);
        }
```
