### ISSUE TITLE
Font dir in local storage. 

### ISSUE THREAD

**Issue by Mishanki** [dompdf/dompdf#2694]
`setFontDir` doesn't change path to font dir.

```php

private function reportGen(): Dompdf
    {
        if(!$data = $this->repository->retrieveReportMiNp()) {
            throw new NotFoundException('Data not found', Errors::NOT_FOUND_ERROR);
        }
        $options = new Options();
        $options->setDefaultFont('open sans');

        $options->setFontDir(storage_path('dompdf-fonts/lib/fonts')); // not working for me
        // $options->setRootDir(storage_path('dompdf-fonts')); // working (copy `lib/*` dir to local storage)
        $dompdf = new Dompdf($options);
  
        $dompdf->loadHtml(view('/some/report', ['data' => $data]));
        $dompdf->setPaper('A4', 'landscape');

        $dompdf->render();

        return $dompdf;
    }

```

**Comment by bsweeney** [comment]
Which version of Dompdf? What error are you are running into?

setFontDir changes the path where Dompdf should look or persist _installed_ fonts. The bundled fonts are always retrieved from {$rootDir}/lib/fonts.

**Comment by Mishanki** [comment]
Install fonts by `load_font.php`. Work fine.

`curl -o load_font.php https://raw.githubusercontent.com/dompdf/utils/master/load_font.php`

In `load_font.php` set custom `fontDir` 
$fontDir = "/var/www/project/storage/dompdf-fonts/lib/fonts";

In terminal
`php load_font.php SourceSans /private/var/www/gov-2/vendor/webfontkit/open-sans/fonts/opensans-regular.ttf`

In project
```php
$options->setDefaultFont('sourcesans');
$options->setFontDir(storage_path('dompdf-fonts/lib/fonts'));
```

Thanks

**Comment by bsweeney** [comment]
It's possible that load_font.php isn't functional with the latest release of Dompdf. I'll have to take a look.

**Comment by lordspace** [comment]
Hey, is there an update on this?
I am using DejaVu Sans because it shows Cyrillic characters but on one of the servers Ubuntu 16 it doesn't find the font even though it's there.

**Comment by bsweeney** [comment]
@lordspace it sounds like you're running into a different issue. Suggest [starting a new discussion](https://github.com/dompdf/dompdf/discussions/new) to figure out what's going on.
