### ISSUE TITLE
Using inline-block with text uppercase is breaking phrases into 2 lines using version 1.1.1

### ISSUE THREAD

**Issue by alexmigf** [dompdf/dompdf#2702]
I have notice that using `inline-block` with text `uppercase` in a phrase, it breaks it into 2 lines using version `1.1.1`.

#### Using `uppercase` to simulate the issue:

```php
$dompdf  = new \Dompdf\Dompdf();
$html    = '
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body style="width:100%;">
	<div style="width:100%;">
		<span style="display:inline-block; text-transform:uppercase;">Some new text</span>
		<span style="display:inline-block; text-transform:uppercase;">Another same test</span>
	</div>
</body>
</html>
<html></html>';
$dompdf->loadHtml( $html );
$dompdf->render();
$dompdf->stream();
```

Output:

![Captura de ecrã de 2021-12-21 15-31-28](https://user-images.githubusercontent.com/533273/146956138-484f03e2-ead7-4439-aed4-df8a4c0f4287.png)

#### Not using `uppercase`:

```php
$dompdf  = new \Dompdf\Dompdf();
$html    = '
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body style="width:100%;">
	<div style="width:100%;">
		<span style="display:inline-block;">Some new text</span>
		<span style="display:inline-block;">Another same test</span>
	</div>
</body>
</html>
<html></html>';
$dompdf->loadHtml( $html );
$dompdf->render();
$dompdf->stream();
```

Output: 

![Captura de ecrã de 2021-12-21 15-32-28](https://user-images.githubusercontent.com/533273/146956243-34abd2bb-c591-44be-80d8-7bc3a1183bf2.png)

**Comment by Mellthas** [comment]
Confirmed. The issue is that inline-block width is now calculated as shrink-to-fit before reflow. But `text-transform` is only applied during reflow, so it is not taken into account when determining the width. The issue also affects previous versions when using tables instead of inline-block elements.

**Comment by alexmigf** [comment]
Thank you @Mellthas !

After testing your branch, it seems that the `inline-block` elements are ignoring the `min-width` value when provided. Could you check that also?

**Comment by alexmigf** [comment]
Sure! In the tests I made with your new branch the `inline-block` issue is in fact solved but I saw a difference in spacing compared to the DOMPDF 1.0.2 version:

#### DOMPDF 1.0.2

![Captura de ecrã de 2022-01-03 16-50-13](https://user-images.githubusercontent.com/533273/148060622-d2f1927e-9841-4357-ba48-ac5f10026b76.png)

#### DOMPDF ([whitespace](https://github.com/dompdf/dompdf/tree/whitespace) branch)

![Captura de ecrã de 2022-01-04 12-40-24](https://user-images.githubusercontent.com/533273/148060534-912ec084-336a-499d-8ac7-7abcd18b4fd8.png)

#### HTML

```html
<span class="shipping-method-label">Shipping method:</span><span class="shipping-method-name">Flat Rate</span>
<span class="payment-method-label">Payment method:</span><span class="payment-method-name">Direct Bank Transfer</span>
```

#### CSS

```css
.shipping-method-label, .payment-method-label {
	display: inline-block;
	min-width: 40mm;
	padding-right: 2mm;
}
```

**Comment by Mellthas** [comment]
Shrink-to-fit width does not take `min/max-width` into account currently, so the calculated width can be off because of that; but that does require a more complex test case, it shouldn’t affect the sample you posted.

**Comment by alexmigf** [comment]
@Mellthas you're right, was some confusion from my side, you could ignore the `min-width` situation, sorry.
