### ISSUE TITLE
Discussion of string support for `page_script` method

### ISSUE THREAD

**Issue by Mellthas** [dompdf/dompdf#2703]
Support for passing a callback function to the `page_script` method was added in #2689. The open question is whether to drop support for passing a string (which will be evaluated via `eval` and needs the `isPhpEnabled` option to be set), and if, when to do that exactly.

From #2689:
> Maybe for the 2.0 release we mark string values as deprecated and remove it with 3.0? I don't see much need to continue supporting it, though, since there are few situations where the user can't just pass in a callable.
> 
> Generated logic being the exception, but in those cases the user can wrap variables.

> Maybe we could even mark string values as deprecated with the next release and remove it in 2.0 already? I can’t imagine any situation right now where only passing a string would work, but passing a callable wouldn’t. On the other hand, supporting a string for only the CPDF and PDFLib back ends as legacy feature wouldn’t be too much of a hassle, as the required code is quite minimal.

It would be interesting to know if there are any good arguments for the string option to be supported going forward. So, if you are a strong proponent of that feature, please speak up.

**Comment by Mellthas** [comment]
As a reminder: Documentation in the wiki needs be updated.

**Comment by Mellthas** [comment]
@bsweeney I have updated the documentation on the [Usage](https://github.com/dompdf/dompdf/wiki/Usage#dompdf-api) page, promoting the option of passing a callback. Please have a look if you are fine with that.

**Comment by bsweeney** [comment]
I like it.

**Comment by Mellthas** [comment]
With the PR merged, I think we can consider this resolved then.
