### ISSUE TITLE
Dompdf Failed to Render HTML output

### ISSUE THREAD

**Issue by junaidimunto** [dompdf/dompdf#2708]
How to solve this dompdf failed to render in my online site, but it displayed normal pdf output view in localhost? Im running PHP 7.4 and using CodeIgniter 4
![dompdferrorrender](https://user-images.githubusercontent.com/72388586/147174153-ac54be06-7c98-4c68-ae09-91f493a77cbb.png)

**Comment by fd6130** [comment]
Maybe your online hosting missing some dependencies or extension. Just double check the dompdf requirements.

**Comment by junaidimunto** [comment]
I've just checked the extensions and looked fine. I installed through composer, is it still possible my online hosting missing some dependencies?

**Comment by bsweeney** [comment]
This was more appropriate in the forums, where I see you already posted. No need to post there and open an issue. We can always create an issue if needed. I'll answer in #2707.
