### ISSUE TITLE
Error: Class 'Dompdf\\Dompdf' not found

### ISSUE THREAD

**Issue by JorginoGC** [dompdf/dompdf#2710]
I executed "composer require dompdf/dompdf"

And i have this code:

```
require 'vendor/autoload.php';

// reference the Dompdf namespace
use Dompdf\Dompdf;

// instantiate and use the dompdf class
$dompdf = new Dompdf();
```

But when i execute it, it gives me the following error: Uncaught Error: Class 'Dompdf\\Dompdf' not found in /X/X/X/X/test.php:10\nStack trace:\n#0 {main}\n  thrown in /X/X/X/X/test.php on line 10

The problem is "new Dompdf()", some solution?

**Comment by bsweeney** [comment]
What was the output after you ran the composer command? If you reference the namespace does it work?

```
$dompdf = new Dompdf\Dompdf();
```

**Comment by JorginoGC** [comment]
> ¿Cuál fue el resultado después de ejecutar el comando composer? Si hace referencia al espacio de nombres, ¿funciona?
> 
> ```
> $dompdf = new Dompdf\Dompdf();
> ```
(Sorry my english)

When i execute "$ composer require dompdf/dompdf":
```
Using version ^0.6.2 for dompdf/dompdf
./composer.json has been updated
Running composer update dompdf/dompdf
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking dompdf/dompdf (v0.6.2)
  - Locking phenx/php-font-lib (0.2.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing phenx/php-font-lib (0.2.2): Extracting archive
  - Installing dompdf/dompdf (v0.6.2): Extracting archive
Generating autoload files
```


With "$dompdf = new Dompdf\Dompdf();" i have same error

**Comment by bsweeney** [comment]
The version of Dompdf (0.6.2) loaded is far behind the current release (1.1.0). Have you followed the instructions for the 0.6.2 release?
https://github.com/dompdf/dompdf/tree/v0.6.2#install-with-composer

Though I would highly recommend updating the version you're using to the latest if possible.
