### ISSUE TITLE
memory-leak when html contains tag pre <pre>

### ISSUE THREAD

**Issue by erlangparasu** [dompdf/dompdf#2711]

**Comment by bsweeney** [comment]
Do you have some details on what you're seeing? Version of Dompdf? Version of PHP? Sample HTML+CSS?

**Comment by flonzo** [comment]
I had exactly the same problem today. It's hardly reproducable, but when I removed white-space: pre; from css class definition - there is no longer memory limit problem.
Error occurred for specific html only on one machine. On other machines the same code did not produce an error.

The error was:
Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in .../vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php on line 222 

I changed php memory limit up to 2GB and it consumed it all.

**Comment by bsweeney** [comment]
Interesting. Could be an issue with an underlying library, then. Would still be helpful to see a sample of the HTML + CSS and also, considering the varying behavior, the system configuration such as OS and PHP version (phpinfo details might be useful if you're comfortable sharing).

**Comment by flonzo** [comment]
@bsweeney , thank you for quick response.

Unfortunately i can't post full template code. First - it's generated in Twig, second - some data in the template is confidential.
I've made a few modifications to the template to hide confidential areas. It looks like the problem lays in .content css class and html content of div class="content". 

OS: Ubuntu Release 20.04.3 LTS (Focal Fossa) 64-bit
PHP version: php7.3
Server: Apache
Framework: Symfony
Dompdf version: 1.0.2 (installed through composer)

Html output:
`<!DOCTYPE html>
<html>
<head>

<meta http-equiv="Content-type" content="text/html; charset=utf-8">
		<title>Preview</title>
		<style>
			body {
				font-family: DejaVu Sans;
				margin: 0;
				font-size: 0.30cm;
			}
			@page {
				size: 21cm 29.7cm;
				margin-left: 2cm;
                margin-right: 2cm;
                margin-top: 0.5cm;
                margin-bottom: 1.5cm;
				size: A4;
				font-size: 0.30cm;
			}
			.previewPage {
				page-break-before: always;
				width: 100%;
			}
			.previewPage:first-child {
				page-break-before: avoid;
			}
			.header {
                width: 100%;
                height: 3.4cm;
				margin-bottom: 0.5cm;
                font-size: 0.22cm;
			}
            .header p {
                margin-top: 0; 
                margin-bottom: 0;
                line-height: 0.22cm;
            }
			.logo {
                margin-right: 0.5cm;
                width: 6.5cm;
			}
            .envelop_window {
                width: 6cm;
                height: 4.5cm;
                margin-right: 0.5cm;
                margin-left: auto;
				text-align: left;
                font-size: 0.35cm;
			}
            .content {
				text-align: justify;
                font-size: 0.35cm;
                page-break-before: avoid;
                white-space: pre;
            /*    tab-size: 4;*/
			}
            .outgoing_number {
                text-align: left;
                font-size: 0.35cm;
                position: absolute;
            }
/*            .signatures {
                text-align: right;
                margin: 1.5cm;
                font-size: 0.20cm;
                float: right;
            }*/


            .signatures {
                text-align: right;
                margin: 1.5cm 0 0;
                display: block;
                padding-top: 0cm;

            }
            .stamp{
                font-size: 0.25cm;
                line-height: 0.28cm;    
                font-style: bold;            
            }

            .watermark{
                opacity: 0.2;
                font-size: 52px;
                color: 'black';
                background: '#ccc';
                position: absolute;
                bottom: 50%;
            }
            .rotate {
                transform: rotate(-45deg);
            }
            .noselect {
                -webkit-touch-callout: none; /* iOS Safari */
                -webkit-user-select: none; /* Safari */
                -khtml-user-select: none; /* Konqueror HTML */
                -moz-user-select: none; /* Old versions of Firefox */
                -ms-user-select: none; /* Internet Explorer/Edge */
                user-select: none; /* Non-prefixed version, currently
                                    supported by Chrome, Edge, Opera and Firefox */
            }

			.ql-align-center{
				text-align: center;
			}
			.ql-align-right{
				text-align: right;
			}
			.ql-align-justify{
				text-align: justify;
			}
                        .ql-indent-1 {
                padding-left: 3em;
            }
                        .ql-indent-2 {
                padding-left: 6em;
            }
                        .ql-indent-3 {
                padding-left: 9em;
            }
                        .ql-indent-4 {
                padding-left: 12em;
            }
                        .ql-indent-5 {
                padding-left: 15em;
            }
                        .ql-indent-6 {
                padding-left: 18em;
            }
                        .ql-indent-7 {
                padding-left: 21em;
            }
                        .ql-indent-8 {
                padding-left: 24em;
            }
                        .ql-indent-9 {
                padding-left: 27em;
            }
                        .ql-indent-10 {
                padding-left: 30em;
            }
            

            .footer { 
                position: fixed; 
                bottom: -2cm; 
                left: 0px; 
                right: 0px; 
                height: 4cm; 
                font-size: 0.2cm;
                font-style: italic;
            }

		</style>

</head>

<body>	
         <div class="previewPage">

                <div class="watermark noselect rotate">Document preview</div>
                
                <div class="header">
                    <table style="border-bottom: 2px solid red;">
                        <tbody><tr>
                            <td>
                                <img class="logo" src="logourl.png" alt="">
                            </td>
                            <td>
                                 <p style="font-size: 0.45cm; font-weight: bold; line-height: 0.48cm; white-space: nowrap;">Something</p>
                                <p style="font-size: 0.35cm; font-weight: bold; line-height: 0.38cm;">Something 2</p>
                                <p>Something 3</p>
                                <p>Something 4</p>
                                <p>Something 5</p>
                                <p>Something 6</p>
                                <p>Something 7</p>
                                <p>Something 8</p>
                                <p>Something 9</p>
                                <p>Something 10</p>
                            </td>
                        </tr>
                    </tbody></table>
                </div>

                <div class="outgoing_number">

                        H/...........................

                </div>

                <div class="envelop_window">
                    Hogwart, ...........................
                    <br><br><br>
                    <br>
                    Harry Potter
                    <br>
                    Room 123, <br>
                    Hogwart
                </div>


                <div class="content">
                    <p>First test</p><p class="ql-indent-1">Second test</p><p class="ql-indent-1"><span style="font-size: 59pt;">This is a test</span></p><p class="ql-indent-1"><br></p><p class="ql-indent-2">Indent 2</p><p class="ql-indent-3"><span style="font-size: 8pt;">Indent 3</span></p><p class="ql-indent-4">Indent 4</p><p class="ql-indent-5">Indent 5</p><p class="ql-indent-6"><span style="font-size: 59pt;">Indent</span> 6</p><p class="ql-indent-7">Indent 7</p><p class="ql-indent-8">Indent 8</p><p>No intent</p>
                </div>


                <div class="signatures stamp"></div>
                <div class="footer">
                    Document made by:<br>
                    Albus Dumbledore<br>                     
                </div>
           </div>

</body>
</html>`

**Comment by bsweeney** [comment]
You can add HTML just be sure to wrap in ``` (on a line by itself) for the [github-supported markdown syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).

**Comment by flonzo** [comment]
Ehh. Updated from dompdf 1.0.2 to 1.1.1 and the problem is gone.
Disregard my last message.

**Comment by bsweeney** [comment]
Thanks for the sample HTML and update regarding version support. Perhaps an issue we already addressed but I'll be sure to take a look and see if that's actually the case.

**Comment by bsweeney** [comment]
I was unable to reproduce the issue. Some additional parameters must be involved. Will revisit if anyone is able to reproduce on latest release.
