### ISSUE TITLE
Loading PNG images fails in some cases when using imagick 3.6.0+

### ISSUE THREAD

**Issue by Tarinu** [dompdf/dompdf#2713]
I have an image of a [barcode](https://user-images.githubusercontent.com/5955598/147765700-a29022cb-00fc-4dbc-b878-46fca486e450.png) that I wanted to add to the PDF. It has bit depth of 8 and color type of 3, which means it will be handled by `addImagePngAlpha`:
https://github.com/dompdf/dompdf/blob/5a72ddd8a7c5408c9e1ba586520910cf22c9db1f/lib/Cpdf.php#L5845-L5857

But it doesn't read the alpha correctly when it reaches the imagick check here:
https://github.com/dompdf/dompdf/blob/5a72ddd8a7c5408c9e1ba586520910cf22c9db1f/lib/Cpdf.php#L5725

Even though the image doesn't have an alpha channel, it still thinks it does and the generated PDF is missing the given barcode (or it just renders white box over the image).

The cause seems to be that the return type for `Imagick::getImageAlphaChannel()` was changed from `int` to `bool` in 3.6.0 (https://github.com/Imagick/imagick/issues/466).

| Package | Version |
| --- | --- |
| PHP | 7.3 |
| dompdf | 1.1.1 |
| Imagick module | 3.6.0 |
| ImageMagick | 7.1.0-16 Q16 x86_64 2021-11-21 |

Tested it with ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 as well but for some reasons this issue didn't appear on that version. While fixing the return type seems to make it render correctly, there might be some other issue that makes the difference between ImageMagick version itself.

**Comment by Mellthas** [comment]
Would you be willing to put up a PR? From reading the linked discussion, just simplifying the check to

```php
if ($imagick->getImageAlphaChannel()) { 
```

should be enough to fix the issue for all versions of the extension.

**Comment by Tarinu** [comment]
Sure, I can probably do it later in the day.
