### ISSUE TITLE
imagecreatefrompng() libpng warnings

### ISSUE THREAD

**Issue by palazonyuanchen** [dompdf/dompdf#2718]
From the recent fix of PHP library (https://bugs.php.net/bug.php?id=71316), there is an error exception thrown from libpng warnings. This causes the application unable to generate pdf (refer to dompdf/dompdf/lib/Cpdf.php:5612).

Please advise how we can prevent this issue.

**Comment by andrespoder** [comment]
`Warning (2): imagecreatefrompng(): gd-png: libpng warning: iCCP: extra compressed data in [VENDORS/dompdf/dompdf/lib/Cpdf.php, line 5640]`

```     
 // generate images
        $img = imagecreatefrompng($file);
```

**Comment by andrespoder** [comment]
I guess warnings should be suppressed using @?
`$img = @imagecreatefrompng($file);`

**Comment by palazonyuanchen** [comment]
> I guess warnings should be suppressed using @? `$img = @imagecreatefrompng($file);`

@andrespoder Thank you for providing more details. The error that I got is 
`imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile in /var/www/vhosts/cs.soas.com/httpdocs/vendor/dompdf/dompdf/lib/Cpdf.php:5612`

**Comment by BadRookiDev** [comment]
I have the same problem (incorrect sRGB profile) on PHP 8.0.7.
Is it possible to suppres that warning as well?

**Comment by bsweeney** [comment]
From the PHP bug report the following image generates the "iCCP: known incorrect sRGB profile" warning: http://imgbox.com/BzOXLiOr

I see a few locations where we use imagecreatefrompng that would need suppression.

If there are other images that generate warnings from GD that can be shared we'll test with those as well. PNG seems to be the common denominator for this particular issue but we don't use suppression on any of the GD methods (except for in one instance). Not sure if there are similar issues with other image formats.

**Comment by bsweeney** [comment]
I went ahead and suppressed errors in the places I could find where we read images. This isn't strictly necessary everywhere I made the change. libjpg warnings have been [suppressed by default since PHP 7.1](https://www.php.net/manual/en/image.configuration.php#ini.gd.jpeg-ignore-warning). And some of the read images are generated within the code and so _should_ be OK. But consistently handling reads seems appropriate.

**Comment by rabiulhasanriaz** [comment]
> `Warning (2): imagecreatefrompng(): gd-png: libpng warning: iCCP: extra compressed data in [VENDORS/dompdf/dompdf/lib/Cpdf.php, line 5640]`
> 
> https://github.com/dompdf/dompdf/blob/0e0a5e60c2e98afdfbc7d30c561fbb245ad02673/lib/Cpdf.php#L5640

thanks , its work for me

**Comment by zanzhiem** [comment]
> I guess warnings should be suppressed using @? `$img = @imagecreatefrompng($file);`

thankyou bro, its work 💯

**Comment by swbittib** [comment]
Hello, we have same issue:

_**imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile**_

on PHP 8.2.1 and DomPdf 2.0.3

Thanks
