### ISSUE TITLE
DOMpdf -failed to load PDF document on server

### ISSUE THREAD

**Issue by dineshuprety** [dompdf/dompdf#2727]
I have a problem loading pdf files with the help of DOMPDF.
```
public function InvoiceDownload($id)
	{
		$stream = true;
		$order = Order::with('user')->where('id',$id)->get()->first();
    	$orderItem = OrderItem::with('product')->where('order_id',$id)->orderBy('id','DESC')->get();
		
		$pdf = new Dompdf();
		// load pdf from view
		$pdf->loadHtml(view('admin/orders/order_invoice',compact('order','orderItem')));
		// (Optional) Setup the paper size and orientation 
		$pdf->setPaper('A4', 'landscape');
		// Render the HTML as PDF 
		$pdf->render(); 
		// Output the generated PDF (1 = download and 0 = preview) 
		
		if ($stream) {
                        ob_end_clean();
			$pdf->stream("billing_invoice.pdf", array("Attachment" => 0));
			
		} else {
			return $pdf->output();
		}

		die();

 
	}
```
   // by using  ob_end_clean(); DOMPDF render white pdf without html contant

**Comment by bsweeney** [comment]
Have you tried ending output buffering sooner? Also, you're running this inside a framework so maybe calling die is short-circuiting something in the framework?

If you can post one of these blank PDFs we can see if there's _anything_ useful in its source.

**Comment by dineshuprety** [comment]
[billing_invoice (1).pdf](https://github.com/dompdf/dompdf/files/7833456/billing_invoice.1.pdf)
This is my output. pdf without content

**Comment by bsweeney** [comment]
Looks like a perfectly empty PDF. Does using the output method instead work? And what's returned by the view method?

**Comment by dineshuprety** [comment]
> Looks like a perfectly empty PDF. Does using the output method instead work? And what's returned by the view method?
view method will return the blade file with data.

**Comment by bsweeney** [comment]
Using laravel, then? loadHtml is looking for a string value, do you need to render the blade?

**Comment by dineshuprety** [comment]
> Using laravel, then? loadHtml is looking for a string value, do you need to render the blade?

yes sir I need to render the blade in pdf.

**Comment by bsweeney** [comment]
No, I mean do you need to call the `render` method? Something like this:

```
$html = view('admin/orders/order_invoice',compact('order','orderItem'))->render();
$pdf->loadHtml($html);
```

**Comment by dineshuprety** [comment]
> loadHtml

i made a helper function for view 
`
function view($path, array $data = [])
{
    //includeing requriment file to active blade template
    $view = __DIR__ .'/../../resources/views';
    $cache = __DIR__ .'/../../bootstrap/cache';
    
    $blade = new Blade($view, $cache);
    echo $blade->view()->make($path, $data)->render();
}
`

**Comment by bsweeney** [comment]
Ah, I see.  Instead of echoing from that function you should return the value:

```
function view($path, array $data = [])
{
    //includeing requriment file to active blade template
    $view = __DIR__ .'/../../resources/views';
    $cache = __DIR__ .'/../../bootstrap/cache';
    
    $blade = new Blade($view, $cache);
    return $blade->view()->make($path, $data)->render();
}
```

**Comment by dineshuprety** [comment]
> Ah, I see. Instead of echoing from that function you should return the value:
> 
> ```
> function view($path, array $data = [])
> {
>     //includeing requriment file to active blade template
>     $view = __DIR__ .'/../../resources/views';
>     $cache = __DIR__ .'/../../bootstrap/cache';
>     
>     $blade = new Blade($view, $cache);
>     return $blade->view()->make($path, $data)->render();
> }
> ```

thank you
