### ISSUE TITLE
Release Zip archive is invalid since 1.1.0 (forward slash must be used as a directory separator)

### ISSUE THREAD

**Issue by bohwaz** [dompdf/dompdf#2730]
Hi, the provided zip archive for releases is invalid since 1.1.1:

```
Archive:  dompdf_1-1-1.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     1090  2020-12-01 20:12   dompdf\autoload.inc.php
     1371  2021-11-23 19:45   dompdf\composer.json
     2856  2021-11-23 19:45   dompdf\CONTRIBUTING.md
    24352  2021-11-23 19:45   dompdf\LICENSE.LGPL
     3003  2021-11-23 19:45   dompdf\phpcs.xml
...
```

(output of `zipdetails`)

However the ZIP specification says that backslashes are forbidden:

>    4.4.17 file name: (Variable)
>
>       4.4.17.1 The name of the file, with optional relative path.
>       The path stored MUST NOT contain a drive or
>       device letter, or a leading slash.  All slashes
>       MUST be forward slashes '/' as opposed to
>       backwards slashes '\' for compatibility with Amiga
>       and UNIX file systems etc.  If input came from standard
>       input, there is no file name field.  

Source: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

Not sure what tool is used to generate those ZIP files but it produces invalid ZIP files.

As a result, when extracting the archive using PHP functions (eg.  ZipArchive::extractTo), the directories are not created:

```
% ls
dompdf\autoload.inc.php
dompdf\composer.json
dompdf\CONTRIBUTING.md
...
```

**Comment by bsweeney** [comment]
Thanks for the head's up. I've been working on a WIndows-based system more recently and I am 😞.

**Comment by bohwaz** [comment]
A quick search showed that this might be a bug of Powershell, maybe try using 7zip instead?

**Comment by bsweeney** [comment]
Indeed, I saw the same thing. It appears an updated package that can be installed using:

```
Install-Module Microsoft.PowerShell.Archive -MinimumVersion 1.2.3.0 -Repository PSGallery -Force
```

[ref](https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/48)

**Comment by bsweeney** [comment]
I've updated the packaged releases. Thanks, again.

**Comment by bohwaz** [comment]
Thank you, have a great day :)
