### ISSUE TITLE
Regression: max-height on image in table breaks second column

### ISSUE THREAD

**Issue by Spreeuw** [dompdf/dompdf#2738]
I'm seeing an issue with `max-height` in the current `master` that was not present in 1.0.2 or 1.1.1. Possibly related to #2556? I'm seeing quite a few min-max _width_ related PRs for 1.1.0 but nothing specifically about _height_.
```php
$html = '<table style="width:100%;">
	<tbody>
		<tr>
			<td><img src="https://picsum.photos/768/348" style="max-height:7cm;"></td>
			<td>Donaudampfschiffahrtsgesellschaftskapitän</div>
			</td>
		</tr>
	</tbody>
</table>';
$options = new \Dompdf\Options( [
	'isRemoteEnabled' => true,
] );
$dompdf = new \Dompdf\Dompdf( $options );
$dompdf->loadHtml( $html );
$dompdf->render();
$dompdf->stream();
```

The result in 1.0.2 (same as 1.1.1):
![dompdf-max-height-issue-1 0 2](https://user-images.githubusercontent.com/3217773/149394999-454e1581-ee99-487d-868d-15cd5a09c5d2.png)
as you can see the image pushes the text away but it's flowing correctly

result in current `master` (different image, same size):
![dompdf-max-height-issue-dev](https://user-images.githubusercontent.com/3217773/149395088-80533b10-2ecd-4679-8de6-ac285242d4e1.png)

And for comparison, if I change `max-height` to `height`, it works as expected in the current `master` too:
![dompdf-height-no-issue-dev](https://user-images.githubusercontent.com/3217773/149395208-3cc342e8-6b88-4295-a4bb-39f1e49127f3.png)

**Comment by bsweeney** [comment]
Looks like the cell with the image is provisioned a width equivalent to the original width of the image. You can see that in the following:

```
<style>
    @page {
        size: letter landscape;
    }
</style>
<table border="1">
	<tbody>
		<tr>
			<td><img src="https://picsum.photos/768/348" style="max-height:1cm;"></td>
			<td>Donaudampfschiffahrtsgesellschaftskapitän</div>
			</td>
		</tr>
	</tbody>
</table>
<table border="1">
	<tbody>
		<tr>
			<td><img src="https://picsum.photos/768/348"></td>
			<td>Donaudampfschiffahrtsgesellschaftskapitän</div>
			</td>
		</tr>
	</tbody>
</table>
```

Don't have time right now to confirm the cause, could be related to #2700.

**Comment by Mellthas** [comment]
> Looks like the cell with the image is provisioned a width equivalent to the original width of the image.

That is indeed what is happening. After the changes in #2700, `max-height` and `min-height` are simply not considered anymore when determining the width of the image for the cell width. I’ll have a look in the coming days.

**Comment by Spreeuw** [comment]
confirmed that #2740 fixes this issue, thanks for the super quick turnaround! 🚀
