### ISSUE TITLE
Images broken (0.8.5 to 1.1.1)

### ISSUE THREAD

**Issue by Latro666** [dompdf/dompdf#2743]
Hi there

We are doing a provisional test of upgrading an older version 0.8.5 to 1.1.1 and it has had the result of images not loading in the PDF where they did before. 

Images were used relative to the url generating the PDF e.g. /assests/5/image.jpg  and in some cases the absolute server paths e.g. /var/home/sites/thissite/assests/5/image.jpg

Both via the use of the <img> tag and via CSS background property, both seem to have stopped working via the upgrade?

I checked the release notes and can't find anything that noted as a breaking change between versions, especially regarding images?

example code:
https://jsfiddle.net/n4fyekh0/

**Comment by Latro666** [comment]
I have left this in here is probably a 'discussion' topic in case release notes need updating

**Comment by bsweeney** [comment]
Not sure about 0.8.5 but from 0.8.6 onward you have to specify allowable local resource paths in the chroot option, see #2744.

Release notes from 0.8.6 to 1.0.2 have a note relating to this change.
