### ISSUE TITLE
Lot of depreciations to fix

### ISSUE THREAD

**Issue by bastien70** [dompdf/dompdf#2746]
There is a lot depreciations to fix :

- [ ]  mb_stripos(): Passing null to parameter # 1 ($haystack) of type string is deprecated
- [ ] mb_stripos(): Passing null to parameter # 1 ($haystack) of type string is deprecated
- [ ] Return type of Dompdf\Frame\FrameTreeList::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
- [ ] Return type of Dompdf\Frame\FrameList::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

### Return type of Dompdf\Frame\FrameTreeIterator::XXXXXXX should either be compatible with Iterator::XXXX: ...#[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

With following methods :

- [ ] Dompdf\Frame\FrameTreeIterator::current()
- [ ] Dompdf\Frame\FrameTreeIterator::next()
- [ ] Dompdf\Frame\FrameTreeIterator::key() 
- [ ] Dompdf\Frame\FrameTreeIterator::valid()
- [ ] Dompdf\Frame\FrameTreeIterator::rewind()
- [ ] Dompdf\Frame\FrameListIterator::current()
- [ ] Dompdf\Frame\FrameListIterator::next()
- [ ] Dompdf\Frame\FrameListIterator::key()
- [ ] Dompdf\Frame\FrameListIterator::valid()
- [ ] Dompdf\Frame\FrameListIterator::rewind()

**Comment by bsweeney** [comment]
The next release will address any known compatibility issues with PHP 8.1.

**Comment by jamieburchell** [comment]
@bsweeney That's brilliant news. Do you have a rough idea when the next release will be?

**Comment by fd6130** [comment]
> @bsweeney That's brilliant news. Do you have a rough idea when the next release will be?

#2704
