### ISSUE TITLE
[bug][v1.1.1] Bad render with tag @media in css

### ISSUE THREAD

**Issue by jsamaniegog** [dompdf/dompdf#2753]
Version dompdf: v1.1.1

Headings h1, h2... are not displayed when `@media` is used in css.

For example, this is a part of Bootstrap 4.6.x css:
`@media (max-width:1200px){.h1,h1{font-size:calc(1.35rem + 1.2vw)}}`

html:
`<h1 class="w-100 text-center bg-primary text-white">TEST</h1>`

Result:
![image](https://user-images.githubusercontent.com/15769828/150289575-9fe95773-a42b-4d5d-be54-ce1a9b147b62.png)

**Comment by fd6130** [comment]
https://github.com/dompdf/dompdf/wiki/CSSCompatibility

**Comment by bsweeney** [comment]
The issue is unrelated to the `@media` rule. Dompdf is not correctly parsing the `calc` function, which is currently unsupported. Watch #2501 for updates.
