### ISSUE TITLE
Floats collapsing with specific combinations

### ISSUE THREAD

**Issue by Spreeuw** [dompdf/dompdf#2754]
I'm seeing unexpected behavior with floats collapsing with specific combinations of widths. I wrote a small test that demonstrates this:

HTML: <details>

```php
$table = '<table>
	<tbody>
		<tr>
			<td>text</td>
			<td style="width: %smm">
				<div>
					<div class="container">
						<div>
							<div class="label">Lorem: </div>
							<div class="value">Ipsum</div>
						</div>
						<div>
							<div class="label">Dolor sit: </div>
							<div class="value">Amet</div>
						</div>
					</div>
					<div style="clear:both;">
				</div>
			</td>
			<td><span>text</span></td>
		</tr>
	</tbody>
</table>
';
$css = '<style type="text/css">
table { width: 100%; }
table td { border: 1pt solid black; }
.label {
	font-weight: bold;
	float: left;
	margin-right: 4px;
}

.value {
	float: left;
}

.container,
.container > div {
	width:100%;
	clear: both;
}

.value,
.label {
	width:50%;
}
</style>';
$html = $css;
for ($i=20; $i < 55; $i++) { 
	$html .= sprintf($table, $i);
}

$dompdf = new \Dompdf\Dompdf();
$dompdf->loadHtml( $html );
$dompdf->render();
$dompdf->stream();
```
</details>

Result:
[test.pdf](https://github.com/dompdf/dompdf/files/7904873/test.pdf)
![float-collapse-1](https://user-images.githubusercontent.com/3217773/150335318-ff5ea265-03a8-4ac6-a3d4-3a1be07a4d0d.png)

In this particular test, it only appears to happen at the beginning of a new page, however, I had the same issue in a real life situation where multiple of these floating rows were printed after eachother and it happened quite randomly:
![float-collapse-2](https://user-images.githubusercontent.com/3217773/150335333-ab1f95b4-ba7d-4bd4-8ffb-b2a1c023cc4d.png)

**Comment by Mellthas** [comment]
The issue with float position after page breaks is fixed on master, it was just recently reported in #2741. Would need more information on the other issue, likely has a different cause if it does not appear after a page break only.

**Comment by Spreeuw** [comment]
Thanks, I missed that fix indeed! Testing with latest master the original issue seems to be resolved too.
