### ISSUE TITLE
Margin ignored on ul element

### ISSUE THREAD

**Issue by Spreeuw** [dompdf/dompdf#2756]
This example shows the top margin of an `<ul>` element being ignored:

HTML: <details>

```html
<style type="text/css">
	ul {
		display: inline-block;
		list-style: none;
		padding: 0;
		margin: 0;
		margin-top: 10px;
	}

	ul li {
		display: inline-block;
		padding: 0;
		margin: 0;
	}

	ul li strong {
		display: inline-block;
		font-weight: normal;
	}

	ul li p {
		display: inline-block;
		margin: 0;
	}
</style>


<div>
	<span>Biozertifiziert</span> | <span>DE-&Ouml;KO-XXX</span> |
	<ul>
		<li><strong>Variante:</strong> <p>1kg (20% Rabatt)</p></li>
	</ul>
</div>
```
</details>

![dompdf-margin-top-dev-master](https://user-images.githubusercontent.com/3217773/150520839-478948eb-fcf6-45fa-a9c7-5dd7b9e70042.png)

In 1.0.2 it looked like this:
![dompdf-margin-top-1 0 2](https://user-images.githubusercontent.com/3217773/150520934-45711953-fe1a-4d50-97b4-4664dae5fa60.png)

Neither situation seems to be rendered the same as Chrome renders the HTML, which simply moves down the entire line when the margin of that `<ul>` element is increased (rather than moving just the `<ul>` element itself. So it seems like the top margin was patching a bug to begin with, but now that it's ignored it appears to be even worse than before because it can no longer be controlled via that margin.

**Comment by Mellthas** [comment]
Hm, so the margin has exactly the right value to make the lines aligned in dompdf. The cause of the change is 96a93459e06df326afee96a579f50d2594406237, which I thought would be a small, innocent improvement. I think it is best if we revert that for now. Vertical alignment really needs some proper treatment, the current implementation is pretty hackish.

**Comment by Mellthas** [comment]
As mentioned in [#2757](https://github.com/dompdf/dompdf/pull/2757#issuecomment-1019553194), you can use `vertical-align: -10px` to achieve the same effect, and it works with current master, too. I think this actually a more appropriate workaround for the misalignment.

**Comment by bsweeney** [comment]
Should see some improvements with rendering under #2762.
