### ISSUE TITLE
Cannot change margin of first page

### ISSUE THREAD

**Issue by ameriel** [dompdf/dompdf#2758]
Hi, The [documentation](https://github.com/dompdf/dompdf/wiki/CSSCompatibility) suggests I should be able to specify different margins for the first page than the others using `@page :first` and indeed that has worked until I tried to upgrade from 0.8.4 to 1.1.1. Now, even if I include `@page :first { margin-bottom: 2in; }` the text breaks as though the first page has the same margins as the rest of the pages. However, if I add a border to the `<body>` element I can see _that_ does respect the 2in margin, weirdly enough.

I attached the HTML markup for a simple document I'm testing: [test.txt](https://github.com/dompdf/dompdf/files/7916993/test.txt) - you can see the behavior I'm describing if you enter it in the Debug Helper: https://eclecticgeek.com/dompdf/debug.php?identifier=c09b42666fa07fb7427c20d4b74208b1 I have also attached the output I get using DOMPDF 8.4.0, which is what I want: [8-4-0-output.pdf](https://github.com/dompdf/dompdf/files/7917049/8-4-0-output.pdf) 
EDIT: Just did a little more checking and it looks like the issue came up sometime between 1.0.2 and 1.1.0.

Hoping someone will be able to help with this (whether it's a bug or I'm just missing something obvious) - we need to be able to alter the margins of the first page in order to include a footer on that page (that isn't on the others) so we can't update until we can resolve this.

**Comment by bsweeney** [comment]
This does look to be buggy behavior.

**Comment by Mellthas** [comment]
Dang, this indeed broke between 1.0.2 and 1.1.0, in commit 2d0af0ca3350fe5b20a6b8040cfef8ef274a704a. The linked PR should fix this.
