### ISSUE TITLE
don't support Arabic 

### ISSUE THREAD

**Issue by facceapps** [dompdf/dompdf#2760]
i change Default font (DejaVu Sans)
and dont support arabic 
 (https://pasteboard.co/GsgTOHCM1NcP.png)
([pdf file](https://eclecticgeek.com/dompdf/debug.php?identifier=194ae611df340a378082a9bdd61d0e22))

**code**
```
require_once __DIR__ .'/dompdf/autoload.inc.php';
use Dompdf\Dompdf;

$dompdf = new Dompdf();
$dompdf->loadHtml('
<style>html,body{font-family: "DejaVu Sans";}</style>
السلام عليكم');
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream();
```

**Comment by bsweeney** [comment]
The DejaVu Sans font supports Arabic glyphs. The issue is that Dompdf does not yet fully support the complex layout features (bidi, shaping) required to correctly render Arabic. Follow #2619 for updates.

There are some suggestions in #712 that may help you get the render you want.

**Comment by facceapps** [comment]
Thank you very much
May Allah save you 

I developed the library and made it support Arabic and 
With the text direction fixed

**Comment by facceapps** [comment]
you're great
Thank you very much
May Allah save you

I developed the library and made it support Arabic and
With the text direction fixed

**Comment by facceapps** [comment]
‫في الاثنين، 24 يناير 2022 في 9:27 ص تمت كتابة ما يلي بواسطة ‪facce apps‬‏
***@***.***‬‏>:‬
