### ISSUE TITLE
Call to a member function get_position() on null

### ISSUE THREAD

**Issue by srakl** [dompdf/dompdf#2763]
I'm using ` "dompdf/dompdf": "dev-master",` and i'm getting this error

`Call to a member function get_position() on null`

in `vendor/dompdf/dompdf/src/FrameReflower/Inline.php`  on line `163`

```
        // Assume the position of the first child
        [$x, $y] = $frame->get_first_child()->get_position();
```

this is my code to generate the pdf

```
$options = new Options();
        $options->set('isRemoteEnabled', TRUE); //If this setting is set to true, DOMPDF will access remote sites for images and CSS files as required.
        $dompdf = new DOMPDF($options);
        
        // images are hosted on a server with a self-signed security certificate or other certificate problems, creating and setting a stream context will be necessary.
        $context = stream_context_create([ 
            'ssl' => [ 
                'verify_peer' => FALSE, 
                'verify_peer_name' => FALSE,
                'allow_self_signed'=> TRUE 
            ] 
        ]);
        $dompdf->setHttpContext($context);

        $dompdf->loadHtml($view); 

        $dompdf->setPaper('A4', 'portrait');

        $dompdf->render();

        // Parameters
        $x          = 505;
        $y          = 820;
        $text       = "Page {PAGE_NUM} of {PAGE_COUNT}";     
        $font       = $dompdf->getFontMetrics()->get_font('Helvetica', 'normal');   
        $size       = 10;    
        $color      = [0,0,0];
        $word_space = 0.0;
        $char_space = 0.0;
        $angle      = 0.0;

        $dompdf->getCanvas()->page_text(
            $x, $y, $text, $font, $size, $color, $word_space, $char_space, $angle
        );

        $dompdf->stream($filename, [ "Attachment" => (YII_ENV) ? 0 : 1]); //set to 1 to auto download

        Yii::$app->end();
```

any idea why? my code works sometimes too. not sure what's making it break on some of my html (`$view`)

**Comment by Mellthas** [comment]
Thanks for the report. If you have some HTML and CSS reproducing the error, that would be very helpful.

**Comment by bsweeney** [comment]
I'm still unable to generate the specific error (even with the samples provided in 2822) and so am inclined to assume that the suggested changes will address the issue.

**Comment by Mellthas** [comment]
Hm, if the samples don’t lead to a `Call to a member function get_position() on null` error for you with current master or 1.2.0, how does the output look? Maybe there is something in my setup influencing the output. The error only triggers if there is a line break before _alialiquid_, it is fine in other places.

**Comment by bsweeney** [comment]
Ah, nvm it was me. I had changed my default font, which was impacting the reflow. Confirmed but and fix.

**Comment by noir04** [comment]
Hey guys

I found a consistent way to replicate this bug, and yes I realise the HTML is invalid, but it's funny that it takes 20 "repeats" of the troublesome HTML before DOMpdf gives up.

```
require_once('vendor/autoload.php');
$html = <<<HTML
<p class="MsoNormal"><span style="font-size:10.0pt;line-height:107%;font-family:" arial",sans-serif"=""><o:p>&nbsp;</o:p></span></p>
HTML;
$html = str_repeat($html, 20);
$dompdf = new Dompdf\Dompdf();
$dompdf->loadHtml($html);
$dompdf->render();
```

Environment:
Debian 11
DOMpdf 1.2.1
PHP 8.1.4

**Comment by bsweeney** [comment]
Huh yeah that does it. Something about flowing to the next page is triggering the error. Will need to revisit this.

**Comment by Mellthas** [comment]
Here is a simplified version without any invalid markup:

```html
<style>
@page {
    size: 100pt 100pt;
    margin: 0;
}

span > span {
    display: block;
}
</style>

<p><span><span>Test</span></span></p>
<p><span><span>Test</span></span></p>
<p><span><span>Test</span></span></p>
<p><span><span>Test</span></span></p>
```
