### ISSUE TITLE
Getting error if used css property which is invalid 

### ISSUE THREAD

**Issue by manojiksula** [dompdf/dompdf#2764]
Hello, 

Getting below errors when admin user put html in description and used the css property which is invalid.

Error generating document: Failed to generate PDF: 'tab_stops' is not a recognized CSS property.,
 'mso_layout_grid_align' is not a recognized CSS property.,
 'text_autospace' is not a recognized CSS property.,
 'mso_layout_grid_align' is not a recognized CSS property.,
 'text_autospace' is not a recognized CSS property.,
 'mso_layout_grid_align' is not a recognized CSS property.,
 'text_autospace' is not a recognized CSS property.,
 'tab_stops' is not a recognized CSS property.,
 'mso_layout_grid_align' is not a recognized CSS property.,
 'text_autospace' is not a recognized CSS property.,
 'mso_layout_grid_align' is not a recognized CSS property.,
 'text_autospace' is not a recognized CSS property.,
 'mso_layout_grid_align' is not a recognized CSS property.,
 'text_autospace' is not a recognized CSS property.,
 'tab_stops' is not a recognized CSS property.,
 'mso_layout_grid_align' is not a recognized CSS property.,
 'text_autospace' is not a recognized CSS property.,
 'mso_layout_grid_align' is not a recognized CSS property.,
 'text_autospace' is not a recognized CSS property.,
 'mso_layout_grid_align' is not a recognized CSS property.,
 'text_autospace' is not a recognized CSS property.,
 'tab_stops' is not a recognized CSS property.,
 'mso_layout_grid_align' is not a recognized CSS property.,
 'text_autospace' is not a recognized CSS property.,
 'mso_layout_grid_align' is not a recognized CSS property.,
 'text_autospace' is not a recognized CSS property.,
 'mso_layout_grid_align' is not a recognized CSS property.,
 'text_autospace' is not a recognized CSS property.,
 'tab_stops' is not a recognized CSS property.,
 'tab_stops' is not a recognized CSS property.,
 'mso_layout_grid_align' is not a recognized CSS property.,
 'text_autospace' is not a recognized CSS property.,
 'mso_layout_grid_align' is not a recognized CSS property.,
 'text_autospace' is not a recognized CSS property.

Atleast we should have something to skip these property or have some allowable html.

**Comment by bsweeney** [comment]
Which version of Dompdf? I agree that it would be ideal to _not_ throw an error, but just adding one of those properties doesn't do that when I test. Do you have a sample of the HTML + CSS that causes the issue?

**Comment by manojiksula** [comment]
I am using "dompdf/dompdf": "^1.1", below is the sample for the same `<p style="margin-bottom:13px">
  <strong>
    <span style="font-size:11pt">
      <span style="line-height:115%">
        <span style="font-family:Calibri,sans-serif">
          <span style="font-family:Roboto">Zoom sur les aides proposées pour l'isolation thermique des fenêtres (et parois vitrées) :</span>
        </span>
      </span>
    </span>
  </strong>
</p>
<table border="1" cellpadding="0" cellspacing="0" class="MsoTableGrid" style="border-collapse: collapse; border: none;">
  <tbody>
    <tr>
      <td style="width:123.3pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-bottom-alt:solid windowtext .5pt;mso-border-right-alt:solid windowtext .5pt;
  padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="147">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;tab-stops:127.7pt">
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto">
            <o:p>&nbsp;</o:p>
          </span>
        </p>
      </td>
      <td style="width:87.65pt;border:solid windowtext 1.0pt;
  border-left:none;mso-border-left-alt:solid windowtext .5pt;mso-border-alt:
  solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="111">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;mso-layout-grid-align:none;text-autospace:none">
          <strong>
            <span style="font-size:9.0pt;mso-bidi-font-size:11.0pt;font-family:Roboto;
  mso-bidi-font-family:Marianne-Medium">Forfait</span>
          </strong>
          <span style="font-size:9.0pt;mso-bidi-font-size:11.0pt;font-family:Roboto;
  mso-bidi-font-family:Marianne-Medium">
            <o:p></o:p>
            <strong>&nbsp;MaPrime</strong>
            <o:p></o:p>
            <strong>&nbsp;Rénov’</strong>
            <o:p></o:p>
          </span>
        </p>
      </td>
      <td style="width:140.3pt;border:solid windowtext 1.0pt;
  border-left:none;mso-border-left-alt:solid windowtext .5pt;mso-border-alt:
  solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="170">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;mso-layout-grid-align:none;text-autospace:none">
          <strong>
            <span style="font-size:9.0pt;mso-bidi-font-size:11.0pt;font-family:Roboto;
  mso-bidi-font-family:Marianne-Medium">Estimation</span>
          </strong>
          <span style="font-size:9.0pt;mso-bidi-font-size:11.0pt;font-family:Roboto;
  mso-bidi-font-family:Marianne-Medium">
            <o:p></o:p>
            <strong>&nbsp;du montant</strong>
            <o:p></o:p>
            <strong>&nbsp;des CEE*</strong>
            <o:p></o:p>
          </span>
        </p>
      </td>
      <td style="width:113.15pt;border:solid windowtext 1.0pt;
  border-left:none;mso-border-left-alt:solid windowtext .5pt;mso-border-alt:
  solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="139">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;mso-layout-grid-align:none;text-autospace:none">
          <strong>
            <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto;mso-bidi-font-family:Marianne-Medium">MaPrime</span>
          </strong>
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto;mso-bidi-font-family:Marianne-Medium">
            <o:p></o:p>
            <strong>&nbsp;Rénov’</strong>
            <o:p></o:p>
          </span>
        </p>
      </td>
    </tr>
    <tr>
      <td style="width:123.3pt;border:solid windowtext 1.0pt;
  border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;
  padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="147">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;tab-stops:127.7pt">
          <strong>
            <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto">BLEU</span>
          </strong>
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto">
            <o:p></o:p>
          </span>
        </p>
      </td>
      <td style="width:87.65pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="111">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;mso-layout-grid-align:none;text-autospace:none">
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto;mso-bidi-font-family:Marianne-Regular">100 €/ <o:p></o:p>équipement <o:p></o:p>
          </span>
        </p>
      </td>
      <td style="width:140.3pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="170">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;mso-layout-grid-align:none;text-autospace:none">
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto;mso-bidi-font-family:Marianne-Regular">79 €/ <o:p></o:p>équipement <o:p></o:p>
          </span>
        </p>
      </td>
      <td style="width:113.15pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="139">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;mso-layout-grid-align:none;text-autospace:none">
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto;mso-bidi-font-family:Marianne-Regular">179 €/ <o:p></o:p>équipement <o:p></o:p>
          </span>
        </p>
      </td>
    </tr>
    <tr>
      <td style="width:123.3pt;border:solid windowtext 1.0pt;
  border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;
  padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="147">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;tab-stops:127.7pt">
          <strong>
            <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto">JAUNE</span>
          </strong>
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto">
            <o:p></o:p>
          </span>
        </p>
      </td>
      <td style="width:87.65pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="111">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;mso-layout-grid-align:none;text-autospace:none">
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto;mso-bidi-font-family:Marianne-Regular">80 €/ <o:p></o:p>équipement <o:p></o:p>
          </span>
        </p>
      </td>
      <td style="width:140.3pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="170">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;mso-layout-grid-align:none;text-autospace:none">
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto;mso-bidi-font-family:Marianne-Regular">39 €/ <o:p></o:p>équipement <o:p></o:p>
          </span>
        </p>
      </td>
      <td style="width:113.15pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="139">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;mso-layout-grid-align:none;text-autospace:none">
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto;mso-bidi-font-family:Marianne-Regular">119 €/ <o:p></o:p>équipement <o:p></o:p>
          </span>
        </p>
      </td>
    </tr>
    <tr>
      <td style="width:123.3pt;border:solid windowtext 1.0pt;
  border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;
  padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="147">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;tab-stops:127.7pt">
          <strong>
            <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto">VIOLET</span>
          </strong>
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto">
            <o:p></o:p>
          </span>
        </p>
      </td>
      <td style="width:87.65pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="111">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;mso-layout-grid-align:none;text-autospace:none">
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto;mso-bidi-font-family:Marianne-Regular">40 €/ <o:p></o:p>équipement <o:p></o:p>
          </span>
        </p>
      </td>
      <td style="width:140.3pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="170">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;mso-layout-grid-align:none;text-autospace:none">
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto;mso-bidi-font-family:Marianne-Regular">39 €/ <o:p></o:p>équipement <o:p></o:p>
          </span>
        </p>
      </td>
      <td style="width:113.15pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="139">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;mso-layout-grid-align:none;text-autospace:none">
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto;mso-bidi-font-family:Marianne-Regular">79 €/ <o:p></o:p>équipement <o:p></o:p>
          </span>
        </p>
      </td>
    </tr>
    <tr>
      <td style="width:123.3pt;border:solid windowtext 1.0pt;
  border-top:none;mso-border-top-alt:solid windowtext .5pt;mso-border-alt:solid windowtext .5pt;
  padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="147">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;tab-stops:127.7pt">
          <strong>
            <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto">ROSE</span>
          </strong>
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto">
            <o:p></o:p>
          </span>
        </p>
      </td>
      <td style="width:87.65pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="111">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;tab-stops:127.7pt">
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto">
            <o:p>&nbsp;</o:p>
          </span>
        </p>
      </td>
      <td style="width:140.3pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="170">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;mso-layout-grid-align:none;text-autospace:none">
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto;mso-bidi-font-family:Marianne-Regular">39 €/ <o:p></o:p>équipement <o:p></o:p>
          </span>
        </p>
      </td>
      <td style="width:113.15pt;border-top:none;border-left:
  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-left-alt:solid windowtext .5pt;
  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt" valign="top" width="139">
        <p class="MsoNormal" style="margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal;mso-layout-grid-align:none;text-autospace:none">
          <span style="font-size:9.0pt;mso-bidi-font-size:
  11.0pt;font-family:Roboto;mso-bidi-font-family:Marianne-Regular">39 €/ <o:p></o:p>équipement <o:p></o:p>
          </span>
        </p>
      </td>
    </tr>
  </tbody>
</table>`

**Comment by bsweeney** [comment]
I don't get an exception when parsing that document. I tried 0.8.6 - 1.1.1. There is the possibility of a thrown exception with that message, but only in certain use cases that Dompdf wouldn't normally trigger.

What do things look like on the integration side (PHP)? Could be something relevant there.

**Comment by markkimsal** [comment]
Are you using `barryvdh/laravel-dompdf` with `show_warnings` set to true in `config/dompdf.php` ?

**Comment by bsweeney** [comment]
That's helpful, Mark. I'll have to try to remember that possibility if the issue comes up again.
