### ISSUE TITLE
Packaged Release 1.2.0 missing

### ISSUE THREAD

**Issue by mutec** [dompdf/dompdf#2769]
> If you're not yet using Composer you can download a packaged release of dompdf which includes all the files you need to use the library. Click the link labeled "dompdf_1-2-0.zip" for the packaged release. The download options labeled "Source code" are auto-generated by github and do not include all the dependencies.

`dompdf_1-2-0.zip` is currently missing in the 1.2.0 Release. Is the release of the packaged version delayed or did someone forget that - or will this "feature" be removed?

**Comment by bsweeney** [comment]
What was forgotten was to comment out that text. The packaged release will be posted later today.

**Comment by bsweeney** [comment]
packaged release is now available
