### ISSUE TITLE
404 Not Found nginx

### ISSUE THREAD

**Issue by rachmanpratama** [dompdf/dompdf#2780]
<img width="1249" alt="Screen Shot 2022-02-15 at 11 21 31" src="https://user-images.githubusercontent.com/34361952/153992156-bf63185e-7032-4a66-beec-f9307d068a84.png">

> $data = {
>   "a": "xxxxxx",
>   "b": "xxx",
>   "c": "xxx",
>   "d": "xxx",
>   "e": xxxxx,
>   "f": "xxx",
>   "array": [
>     {
>       "a": 1,
>       "b": "Ixxxxx",
>       "c": null,
>       "d": null,
>       "e": null,
>       "f": null,
>       "g": "xxxxx",
>       "h": null,
>       "j": "xxxx",
>       "k": "xx",
>       "l": null,
>       "m": "xxx",
>       "n": "xxxx",
>       "o": null,
>       "p": null,
>       "q": null,
>       "r": null,
>       "s": "xxx,
>       "t": null,
>       "u": null,
>       "v": "xxx,
>       "w": null
>     },
> ............,
>  {
>       "a": 66,
>       "b": "Ixxxxx",
>       "c": null,
>       "d": null,
>       "e": null,
>       "f": null,
>       "g": "xxxxx",
>       "h": null,
>       "j": "xxxx",
>       "k": "xx",
>       "l": null,
>       "m": "xxx",
>       "n": "xxxx",
>       "o": null,
>       "p": null,
>       "q": null,
>       "r": null,
>       "s": "xxx,
>       "t": null,
>       "u": null,
>       "v": "xxx,
>       "w": null
>     }]}

> $pdf = PDF::setOptions(['isRemoteEnabled' => true, 'isHtml5ParserEnabled' => true])->loadview('template.receipt.statement', $data);

> return $pdf->stream('account_statement_' . date('dmYHis') . '.pdf');

Can someone help me with this? I want to generate a report, but got 404 when i have a lot of data. If the array has more than 60, it return 404

**Comment by bsweeney** [comment]
Any relevant errors in the PHP error log?

**Comment by rachmanpratama** [comment]
> 

There were no errors on laravel. So i am assuming the 404 errors because of the dompdf lib.

**Comment by bsweeney** [comment]
Dompdf itself doesn't produce 404 errors. Could be that an exception is thrown and the exception handler in laravel returns a 404. If you just return the HTML instead of rendering to PDF does the document display?

**Comment by rachmanpratama** [comment]
I tried your suggestion, but no errors occurred. Is there a limit to generate pages in Dompdf?

**Comment by bsweeney** [comment]
Dompdf itself does not, though depending on the size/complexity of your document and your system configuration memory or CPU time limits may be hit.

**Comment by rachmanpratama** [comment]
hi @bsweeney .. i checked nginx log, and it shows something like this `2020/05/21 06:32:45 [error] 103874#103874: *16601903 open() “/var/www/html/fifgroup/public/fonts/Mark Simonson - Proxima Nova Alt Regular-webfont.woff2” failed (2: No such file or directory), client: 182.1.109.227, server: www.fifgroup.c`.. i assume this happened because when i hit stream function, the file still not ready yet. is there any solution for this? thank you
