### ISSUE TITLE
Verison Changes Disturbs Layout + CSS

### ISSUE THREAD

**Issue by Hasan-Ikram** [dompdf/dompdf#2781]
Hi,
I have been using https://github.com/barryvdh/laravel-dompdf a wrapper for dompdf. It was working fine and create pdf with same layout on local & production. Once i update composer on PROD, it disturbs layout + css. And i checked composer.lock file, it was working with v1.1.1 but on v1.2.0 it does not render well.
Screenshots added below.

v1.1.1
![image](https://user-images.githubusercontent.com/81748617/154203519-e389d771-f1e4-4a29-a61f-caa06ae059b8.png)

v1.2.0
![image](https://user-images.githubusercontent.com/81748617/154203546-c1a66825-de88-4f00-a87c-44f48010ab61.png)

It should not be the case like this. Have used simple HTML + compatible css.

**Comment by bsweeney** [comment]
Would need to see a sample of the HTML + CSS so we can identify the cause.

**Comment by Hasan-Ikram** [comment]
Working with v1.1.1
```
<div class="sr-labelse" style="margin-bottom:-30px; margin-top:-25px !important; z-index:20;">
     <h3 style="  letter-spacing: 5px;  font-size: 23px; " class="MontserratExtraBold">CUSTOMER COMMUNICATION</h3>
</div>
```

But not with v1.2.0.

**Comment by bsweeney** [comment]
That's not sufficient to identify the issue. Can you provide more detail?

**Comment by Hasan-Ikram** [comment]
I am talking about only this portion which get disturbed when version changes.
![image](https://user-images.githubusercontent.com/81748617/154488820-e00b367f-3f86-4a70-9ec4-0d15f91f315d.png)

v1.1.1: 
`<div class="sr-labelse" style="margin-bottom:-30px; margin-top:-25px !important; z-index:20;">
     <h3 style="  letter-spacing: 5px;  font-size: 23px; " class="MontserratExtraBold">CUSTOMER COMMUNICATION</h3>
</div>`

v1.2.0:
`<div class="sr-labelse" style="margin-bottom:30px; margin-top:-35px!important; z-index:20;">
      <h3 style="  letter-spacing: 5px;  font-size: 23px; " class="MontserratExtraBold">CUSTOMER COMMUNICATION</h3>
</div>`

**Comment by bsweeney** [comment]
For example, this seems fine:

```
  <div style="background-color: orange; height: 100px; width: 100%;"></div>
  <div style="background-color: blue; width: 50%; border-radius: 10px; height: 20px; margin: -10px auto; z-index: 1000"></div>
  <div style="background-color: red; height: 100px; width: 100%;"></div>
```

So there's styling involved than just setting some margins and unless you provide more detail it'll be harder to identify.

**Comment by mattschlosser** [comment]
I have a minimum example here. 

[1.1 Version](https://replit.com/@mattschlosser/dompdf-11)
[1.2 Version](https://replit.com/@mattschlosser/dompdf-12)

In the second case, the image renders larger than before

**Comment by Mellthas** [comment]
This looks like it is completely unrelated. The difference is due to how the `height` attribute is parsed; in previous versions, `height="130px"` worked, but it looks like more or less unintentionally. dompdf 1.2.0 is stricter and only accepts percentage values and unit-less numbers.

From a quick browser testing, Chrome and Firefox seem to accept anything that starts with a number, interpreting it as a pixel value. Any further characters are discarded; unless there is a percentage sign, in which case the declaration seems to be discarded … Anyway, I think I can pull up a quick fix to basically restore the previous behavior.

**Comment by mattschlosser** [comment]
Thanks for the quick reply and fix. I tested the fix with and it resolves one of my issues.

Now i am having issues with flex box. 
[1.1](https://replit.com/@mattschlosser/dompdf-11-again)
[1.2 with attribute-fix](https://replit.com/@mattschlosser/dompdf-12-again)

**Comment by bsweeney** [comment]
That's ... interesting? Dompdf does not support flexbox yet (#971) so the previous rendering was just accidentally visually acceptable. In versions prior to 1.2 the layout pretty much just breaks when `display: flex` is used. With 1.2 we changed dompdf to at least understand block vs non-block for valid display types that are not yet supported. You can see that with a small tweak to your example. You can see that the contained DIVs are pretty much just rendered on top of each other in 1.1.

```
<!DOCTYPE html>
<HTML>
<head>
  <style>
	.row{
		display:flex;
	}

  .company-details {
    text-align: right;
  }
  
  .row > div:nth-child(1)
  {
		background-color: #cc000066;
  }

  .row > div:nth-child(2)
  {
		background-color: #0000cc66;
  }
  </style>
</head>
<BODY>
<div >
    <div class='row'>
        <div>
            <img height='130' src='http://placekitten.com/130' data-holder-rendered='true' />
        </div>
        <div class='company-details' >
          <div style='font-size:2em;'>ABCS</div>
            <div>
              Address here<br/>
              email here <br/>
              phone here
            </div>
          </div>
      </div>
    </div>
</body>
</html>
```

I'd have to dive into the code a bit to see how exactly the changes we made impacted rendering for flexbox, but I don't think we're going to go back to the way it was before. Your best option with Dompdf right now is to look for a different means of producing the same of layout. The example I provided earlier would work, but I don't know if it works with your overall document structure.
