### ISSUE TITLE
PHP 8.1 uses HTML parsing functions in other way

### ISSUE THREAD

**Issue by panvid** [dompdf/dompdf#2782]
See: https://www.php.net/manual/en/function.htmlspecialchars.php

> 8.1.0 | flags changed from ENT_COMPAT to ENT_QUOTES \| ENT_SUBSTITUTE \| ENT_HTML401.

https://github.com/dompdf/dompdf/blob/master/src/Frame.php#L1203 and https://github.com/dompdf/dompdf/blob/master/src/Frame.php#L1247

**Comment by bsweeney** [comment]
Thanks for the notice. That function isn't used during rendering and the change shouldn't be an issue but we'll review all the same.

**Comment by bsweeney** [comment]
I think the flags change is acceptable. Maybe even preferable since it's more likely to produce a usable result. I'm not going to make any changes to the code since it's used only by the __toString magic methods which are intended primarily for debugging.
