### ISSUE TITLE
Plugin is attempting to start a session with WordPress. WP Session Manager will not work!

### ISSUE THREAD

**Issue by wadid** [dompdf/dompdf#2785]
I get the error message "Another plugin is attempting to start a session with WordPress. WP Session Manager will not work!  how to find error"

I am trying to correct the code of somebody. He uses dompf. There is stuff like $_Session in the code. 

What need to be done broadly? Does these parts of the code need to be encapsulated in functions. or do I need to reset something?

Sorry for being so unspecific but I just want a broad level of understanding first...

**Comment by bsweeney** [comment]
Dompdf itself doesn't use sessions (PHP or otherwise). I was going to suggest you ask on StackOverflow, which is seems you have done: https://wordpress.stackexchange.com/q/402887
