### ISSUE TITLE
BDT currency symbol problame

### ISSUE THREAD

**Issue by MdAnowarHosen** [dompdf/dompdf#2787]
I need  BDT currency symbol in my receipt. I'm using that `<span style="font-family: DejaVu Sans;">&#2547;</span>` but it's not working. How can I do this?

**Comment by bsweeney** [comment]
The DejaVu font family provides a wider range of glyph support, but this isn't among them. You'll need to reference a supporting font to get this to display correctly.

For example, using Noto Sans

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Bengali&display=swap" rel="stylesheet"> 
</head>
<body>
  <span style="font-family: Noto Sans Bengali;">&#2547;</span>  
</body>
</html>
```

**Comment by khairul-773** [comment]
Thank you. its work perfectly.
