### ISSUE TITLE
Footer-Tags get lost

### ISSUE THREAD

**Issue by benidroe** [dompdf/dompdf#2788]
Hi, 
I use dompdf in my laravel projects together with the package barryvdh/laravel-dompdf.
Since I've updated to the current DOMPDF version, my footer does not display the footer content `<bottom1>` and `<bottom2>`.
Only the` <footer>` background is rendered.

CSS:
```
@page { margin: 0mm 0mm; }
footer { position: fixed; bottom: 0px; left: 0px; right: 0px; background-color: #df922e; height: 28mm; font-family: "Arial", sans-serif;  font-size: 11px; }

bottom1 {position: fixed; bottom: 10mm; left: 13mm; width: 50mm; height: 11mm; z-index: 1000;}
bottom2 {position: fixed; bottom: 7mm; left: 81mm; width: 120mm; height: 15mm; z-index: 1000;}
```

Footer CSS:

```
<footer>

    <bottom1>
        <img src="{{storage_path('app/assets/LogoFoot.svg')}}" style="width:49mm;height:11mm;">
    </bottom1>


   <bottom2>
        Company Name<br />
        Tel.: +49 1234 - USt.IdNr.: 123456 <br/>
        My Canary Bank - IBAN: DE06 0000 0000 0000 1111 22 - BIC: ABCDEFGH1234
        </bottom2>
</footer>
```

As a quick workaround, I removed the z-index and changed the relations from bottom to top. The issue seems to be the bottom distance property.

```
bottom1 {position: fixed; left: 13mm; width: 50mm; height: 11mm; margin-top: 7mm; }
bottom2 {position: fixed; left: 81mm; width: 120mm; height: 15mm; margin-top: 7mm; }
```

However, I have a lot more dompdf blades and it will be a lot of hassle to change all of them.
Could you help me, please?

**Comment by bsweeney** [comment]
fixed-position content inside fixed-position content is a bit of odd styling and is likely the source of the issue, since fixed position elements are rendered independent of their parent. The only change you really need to make is to modify the positioning to absolute instead of fixed.

Can you update your stylesheet instead of your blades?

Maybe related to #1574?

**Comment by benidroe** [comment]
Thank you verry much. With absolute positions it works quite a lot more deterministic.  I've fixed the most templates this night.

However, one more little issue occured with floated tags in the header, I was not able to solve:
```
<body>
<header>
<h2 class="h2 float-left">My Heading</h2>
<div class="float-right text-right">
My adress 1, 12345 My City<br /> <br/>
Date: {{App\Helper::convertDate(date('Y-m-d'))}}<br />
<span class="page-number">Page</span></div>
</header>

```
CSS:

```
header {position: fixed; left: 0mm; right: 0mm; top: 10mm; margin-right: 16mm; margin-left: 25mm; margin-top: 10mm; height: 30mm; }
.float-left{ float:left; }
.float-right{ float:right; }
.text-right{ text-align: right;  }
```

In former dompdf versions and in plain HTML, the top left corner of both boxes is at the same y-level. However, the float-left box is alligned on the vertical center of the .float-right box. Neither `vertical-align: baseline` nor `vertical-align: top` changed anything.

I could use absolute positions here. But I use the template for different paper formats and absolute won't be responsive enough.

**Comment by bsweeney** [comment]
Using just that HTML+CSS the PDF rendering appears similar to that for a web browser. Is there perhaps some other relevant CSS that's affecting the margins on the elements?

**Comment by benidroe** [comment]
Oh, you're right. I'm wondering that Chrome is rendering the code the same way. It seems that floated elements do not support any vertical alignment properties. I have to try it with absolute positions.
