### ISSUE TITLE
Can't hide element when printing.

### ISSUE THREAD

**Issue by ep1sode** [dompdf/dompdf#2789]
I have already set styles for a certain element on media print. Pls see below.

`
@media print {
    .no-print { display: none !important }
}
`

But every time I print the document, the element in question is not hidden. How do I resolve this?

**Comment by bsweeney** [comment]
The [default media type](https://github.com/dompdf/dompdf/blob/master/src/Options.php#L70-L82) utilized by Dompdf is "screen" so if you want it to parse styles for the the print media type you'll want to update your options:

```
$dompdf = new Dompdf(["defaultMediaType" => "print"]);
```

FYI, the additional media types that are always parsed are:
- all
- bitmap
- dompdf
- paged
- static
- visual
