### ISSUE TITLE
pdf generation problem

### ISSUE THREAD

**Issue by hassanimadi** [dompdf/dompdf#2796]
Hello, I have a problem generating pdf with the Absolute path of the images, no more images are found, and the font always takes times new roman and not arial,
the style not taken into account like:
![Capture](https://user-images.githubusercontent.com/42210279/157051386-763592ca-4ada-4347-8c1e-544c6f0de962.JPG)

```
// Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');
         $pdfOptions->set('isRemoteEnabled', true);
// Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);
```

**Comment by hassanimadi** [comment]
[Dompdf\Dompdf](http://127.0.0.1:8000/_profiler/open?file=vendor\dompdf\dompdf\src\Dompdf.php&line=70#line70) {[#4622 ▼](http://127.0.0.1:8000/formations/temps_teleformation_print/3352#sf-dump-605314575-ref24622)
  -version: "dompdf 1.2.0"
  -dom: DOMDocument {[#4620 ▶](http://127.0.0.1:8000/formations/temps_teleformation_print/3352#sf-dump-605314575-ref24620)}
  -tree: [Dompdf\Frame\FrameTree](http://127.0.0.1:8000/_profiler/open?file=vendor\dompdf\dompdf\src\Frame\FrameTree.php&line=30#line30) {[#4856 ▶]()}
  -css: [Dompdf\Css\Stylesheet](http://127.0.0.1:8000/_profiler/open?file=vendor\dompdf\dompdf\src\Css\Stylesheet.php&line=31#line31) {[#4599 ▶](http://127.0.0.1:8000/formations/temps_teleformation_print/3352#sf-dump-605314575-ref24599)}
  -canvas: [Dompdf\Adapter\CPDF](http://127.0.0.1:8000/_profiler/open?file=vendor\dompdf\dompdf\src\Adapter\CPDF.php&line=38#line38) {[#5245 ▶](http://127.0.0.1:8000/formations/temps_teleformation_print/3352#sf-dump-605314575-ref25245)}
  -paperSize: "A4"
  -paperOrientation: "portrait"
  -callbacks: []
  -cacheId: null
  -baseHost: ""
  -basePath: "C:\wamp64\www\BackofficeABS/public"
  -protocol: ""
  -httpContext: null
  -systemLocale: null
  -mbstringEncoding: null
  -pcreJit: null
  -defaultView: "Fit"
  -defaultViewOptions: []
  -quirksmode: true
  -allowedProtocols: array:4 [[▶]()]
  -allowedLocalFileExtensions: array:2 [[▶]()]
  -messages: []
  -options: [Dompdf\Options](http://127.0.0.1:8000/_profiler/open?file=vendor\dompdf\dompdf\src\Options.php&line=4#line4) {[#4615 ▶](http://127.0.0.1:8000/formations/temps_teleformation_print/3352#sf-dump-605314575-ref24615)}
  -fontMetrics: [Dompdf\FontMetrics](http://127.0.0.1:8000/_profiler/open?file=vendor\dompdf\dompdf\src\FontMetrics.php&line=25#line25) {[#4703 ▶](http://127.0.0.1:8000/formations/temps_teleformation_print/3352#sf-dump-605314575-ref24703)}
}

**Comment by bsweeney** [comment]
Unless you have installed the "Arial" font you can't use it with Dompdf. The PDF standard font is Helvetica, or you can use the sans-serif generic. You may also want to consider DejaVu Sans for expanded character support.

As for the images, absolute as in a path on the local filesystem? You'll need to specify a containing path for the chroot option, otherwise Dompdf will refuse to load.

```
$pdfOptions->set('chroot', [ '/path/to/images' ]);
```

**Comment by hassanimadi** [comment]
Hello I still can't load the Arial font despite the @font-face 

   @font-face {
            font-family: 'Arial';
            src: url(Arial.ttf)  format('truetype');
        }

and put defaultFont example 'dejavue sans' 
$pdfOptions->set('defaultFont', 'dejavu sans');
my document is still times new roman

**Comment by bsweeney** [comment]
Just confirming, your at-font-face declaration would have to point to the actual font file. Your sample would indicate it's in the same directory as the HTML and/or PHP (depending on how your loading the HTML into Dompdf). Also make sure to update the chroot so that the path to the font is allowed.

As for the default font, there have been issues in the past with that option. Which version of Dompdf are you using? But also, if your stylesheet specifies a font anywhere that will override the default, which is only used if none of the fonts specified in the stylesheet are available.

**Comment by hassanimadi** [comment]
hello here are the elements for a better analysis of my problem

![image](https://user-images.githubusercontent.com/42210279/158990063-74dd8241-8de4-4129-957c-cc2b5f3a5526.png)

**Comment by hassanimadi** [comment]
my html code

<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <title>{% block title %}ABS Administration{% endblock %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Aquila infotech">


    
    <link rel="icon" type="image/png" sizes="16x16" href="/admin/plugins/images/favicon.png">

 
    

    <style type="text/css">
   
     
        html {
            position: relative;
            min-height: 100%;
            background: #fff;
            font-size: 10px;
            -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
        }

        * {
            outline: 0 !important;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }

        body {
            background: #2f323e;
            margin: 0;
            overflow-x: hidden;
            color: #313131;
            font-weight: 300;
            font-size: 13px;
            line-height: 1.42857143;
        }

        header {
            position: fixed;
            top: 0cm;
            left: 0cm;
            right: 0cm;
            height: 2cm;
        }

        footer {
            position: fixed;
            bottom: -60px;
            left: 0px;
            right: 0px;
            height: 160px;

            /** Extra personal styles **/
        }

        h3 {
            line-height: 30px;
            font-size: 21px;
        }

        h1,
        h2,
        h3,
        h4,
        h5,
        h6 {
            color: #313131;
            margin: 10px 0;
            font-weight: 300;
        }

        h5 {
            font-size: 0.83em;
        }

        table {
            background-color: transparent;
            border-spacing: 0;
            border-collapse: collapse;
            margin-bottom: 10px;
            width: 100%;
            max-width: 100%
        }

        tbody {
            color: #797979;
        }

        td,
        th {
            padding: 0;
        }

        th {
            color: #666;
            font-weight: 500;
            text-align: left;
        }

        .table>thead>tr>th {
            vertical-align: bottom;
            border-bottom: 1px solid #e4e7ea;
        }

        .table>tbody>tr>td,
        .table>tbody>tr>th,
        .table>tfoot>tr>td,
        .table>tfoot>tr>th,
        .table>thead>tr>td,
        .table>thead>tr>th {
            padding: 8px 8px;
            vertical-align: middle;
        }

        img {
            vertical-align: middle;
            border: 0;
        }

        p {
            line-height: 1.6;
            margin: 0 0 10px;
        }

        .col-md-12 {
            position: relative;
            min-height: 1px;
            padding-left: 15px;
            padding-right: 15px;
        }
    </style>
</head>

<body style="background: white">

    <div class="col-md-12">
        <table width="100%">
            <tr>
                <td align="top"><img src="https://espace-client.autobilan-systems.com/admin/plugins/images/logo%20abs.jpg" width="200">
                    <p>Arteparc – Bat F Route de la Cote d’Azur <br>
                        Lieu dit le Canet de Meyreuil <br>
                        13590 MEYREUIL <br> Tel : 09 72 50 99 30</p>
                </td>
                <br>
                <td style="text-align: right;padding-bottom: 1px">
                    <h3>Bon de commande</h3>
                    <p>Réf.commande : {{commandes.numCommande}} <br>
                        Date de commande : {{commandes.dateCommande|date("d/m/Y")}} <br>
                        Réf.client : {{Centre.NumeroAgrementCentre}}
                        <br>
                        <br> Type de commande : {% if commandes.type == 1 %}
                        Location
                        {% else %}
                        Comptant
                        {% endif %}
                        <br>
                        {% if commandes.modeReglement == 1 %}
                        Mode de règlement : Prélèvement
                        {% elseif commandes.modeReglement == 2 %}
                        Mode de règlement : Chèque
                        {% elseif commandes.modeReglement == 3 %}
                        Mode de règlement : Virement bancaire
                        {% endif %}
            </tr>
            <tr>
                <td>



                </td>
                <br>
                <td>

                    <span>{{commandes.NomLivraison}} {% if Centre.estVL == 0 %}
                        (PL)
                        {% else %}
                        (VL)
                        {% endif %}</span>

                    {# <h5>{{commandes.NomPersonnel}} {{commandes.PrenomPersonnel}}</h5> #}
                    <p>{{commandes.AdresseLivraison}} {{commandes.ComplLivraison}}</p>
                    <p>{{commandes.CodePostalLivraison}} {{commandes.VilleLivraison}}</p>

                </td>
            </tr>

        </table>
    </div>

    <div class="col-md-12">
        {% set TotalHT = 0 %}
        {% if LigneCommandes|length > 0 %}

        {% set AvecRemise = false %}
        {% for ligneCommande in LigneCommandes %}
        {% if ligneCommande.remise %}
        {% set AvecRemise = true %}
        {% endif %}
        {% endfor %}
        <table id="demo-foo-addrow1" class="table color-table " style="border-collapse:collapse">
            <thead style="background-color: lightgray;">
                <tr>


                    <th style="height: 10px;border:0.5px solid black">Libelle</th>
                    <th style="height: 10px;width: 13%;border:0.5px solid black;text-align: right">Prix/HT</th>
                    {% if AvecRemise %}
                    <th style="height: 10px;width: 10%;border:0.5px solid black;text-align: right">%Remise</th>

                    <th style="height: 10px;width: 10%;border:0.5px solid black;text-align: right">Prix/Remise</th>
                    {% endif %}


                    <th style="height: 10px;width: 10%;border:0.5px solid black;text-align: center">Quantité</th>
                    <th style="height: 10px;width: 15%;border:0.5px solid black;text-align: right">Total Prix/HT</th>

                </tr>
            </thead>
            <tbody style="border: black">
                {% set TotalHTC = 0 %}

                {% for ligneCommande in LigneCommandes %}
                <tr>
                    {% set Total = ligneCommande.prixHtU * ligneCommande.quantite %}

                    <td style="border:0.5px solid black">{{ligneCommande.produit}}
                        {% if ligneCommande.idProduit.ViewDetails %}
                        <p style="font-size: 11px">{{ligneCommande.Description}}</p>
                        {% endif %}
                    </td>
                    <td style="border:0.5px solid black;text-align: right">
                        {{ligneCommande.prixHtSansRemise|number_format(2,',',' ')}}€
                    </td>
                    {% if AvecRemise %}
                    <td style="border:0.5px solid black;text-align: right">
                        {{ligneCommande.remise|number_format(2,',',' ')}}%
                    </td>
                    <td style="border:0.5px solid black;text-align: right">
                        {{ligneCommande.prixHtU|number_format(2,',',' ')}}€
                    </td>
                    {% endif %}


                    <td style="border:0.5px solid black;text-align: center">{{ligneCommande.quantite}}</td>
                    <td style="border:0.5px solid black;text-align: right">{{Total|number_format(2,',',' ')}}€</td>
                </tr>
                {% set TotalHT = TotalHT + Total %}
                {% set TotalHTC = TotalHTC + Total %}
                {% endfor %}

            </tbody>
            {% if commandes.type == 0 %}
            <tfoot>

                <tr>
                    <td style="border-top: 0.5px solid black;border-left:  0.5px solid black"></td>
                    <td style="border:0.5px solid black;text-align: right" {% if AvecRemise %}colspan="4" {% else
                        %}colspan="2" {% endif %}><strong>TOTAL (HT)</strong></td>
                    <td style="border:0.5px solid black;text-align: right">
                        <strong>{{TotalHTC|number_format(2,',',' ')}}€</strong>
                    </td>
                </tr>
                <tr>
                    <td style="border-left:  0.5px solid black"></td>
                    <td style="border:0.5px solid black;text-align: right" {% if AvecRemise %}colspan="4" {% else
                        %}colspan="2" {% endif %}><strong>FRAIS DE PORT
                            (HT)</strong>
                    </td>
                    <td style="border:0.5px solid black;text-align: right">
                        <strong>{{commandes.fraisPort|number_format(2,',',' ')}}€</strong>
                    </td>
                </tr>
                <tr>
                    <td style="border-left:  0.5px solid black"></td>
                    <td style="border:0.5px solid black;text-align: right" {% if AvecRemise %}colspan="4" {% else
                        %}colspan="2" {% endif %}><strong>TVA</strong></td>
                    <td style="border:0.5px solid black;text-align: right">
                        <strong>{{((TotalHTC + commandes.fraisPort) * 20 / 100)|number_format(2,',',' ')}}€</strong>
                    </td>
                </tr>

                <tr>
                    <td style="border-left:  0.5px solid black;border-bottom: 0.5px solid black"></td>
                    <td style="border:0.5px solid black;text-align: right" {% if AvecRemise %}colspan="4" {% else
                        %}colspan="2" {% endif %}><strong>TOTAL TTC
                        </strong></td>
                    <td style="border:0.5px solid black;text-align: right">
                        <strong>{{(TotalHTC + ((TotalHTC + commandes.fraisPort) * 20 / 100) +
                            commandes.fraisPort)|number_format(2,',',' ')}}€</strong>
                    </td>
                </tr>


            </tfoot>
            {% else %}
            <tfoot>

                <tr>
                    <td style="border-top: 0.5px solid black;border-left:  0.5px solid black"></td>
                    <td style="border:0.5px solid black;text-align: right" {% if AvecRemise %}colspan="4" {% else
                        %}colspan="2" {% endif %}><strong>TOTAL (HT)</strong></td>
                    <td style="border:0.5px solid black;text-align: right">
                        <strong>{{TotalHTC|number_format(2,',',' ')}}€</strong>
                    </td>

                </tr>

                <tr>
                    <td style="border-left:  0.5px solid black"></td>
                    <td style="border:0.5px solid black;text-align: right" {% if AvecRemise %}colspan="4" {% else
                        %}colspan="2" {% endif %}><strong>TVA</strong></td>
                    <td style="border:0.5px solid black;text-align: right">
                        <strong>{{((TotalHTC) * 20 /100)|number_format(2,',',' ')}}€</strong>
                    </td>
                </tr>

                <tr>
                    <td style="border-left:  0.5px solid black;"></td>
                    <td style="border:0.5px solid black;text-align: right" {% if AvecRemise %}colspan="4" {% else
                        %}colspan="2" {% endif %}><strong>TOTAL TTC
                            {% if commandes.type == 1 %}
                            (Mensuel)
                            {% endif %}</strong></td>
                    <td style="border:0.5px solid black;text-align: right">
                        <strong>{{(TotalHTC + ((TotalHTC ) * 20 /100) )|number_format(2,',',' ')}}€</strong>
                    </td>
                </tr>
                <tr>
                    <td style="border-left:  0.5px solid black"></td>
                    <td style="border:0.5px solid black;text-align: right" {% if AvecRemise %}colspan="4" {% else
                        %}colspan="2" {% endif %}><strong>FRAIS DE PORT
                            (TTC)</strong>
                    </td>
                    <td style="border:0.5px solid black;text-align: right">
                        <strong>{{(commandes.fraisPort + ((commandes.fraisPort) * 20 /100))|number_format(2,',','
                            ')}}€</strong>
                    </td>
                </tr>

                <tr>
                    <td style="border-left:  0.5px solid black;border-bottom: 0.5px solid black"></td>
                    <td style="border:0.5px solid black;text-align: right" {% if AvecRemise %}colspan="4" {% else
                        %}colspan="2" {% endif %}><strong>TOTAL TTC (1ere
                            Mensualité)</strong>
                    </td>
                    <td style="border:0.5px solid black;text-align: right">
                        <strong>{{(TotalHTC + ((TotalHTC + commandes.fraisPort) * 20 /100) + commandes.fraisPort
                            )|number_format(2,',',' ')}}€</strong>
                    </td>
                </tr>
            </tfoot>
            {% endif %}


        </table>

        {% endif %}

        {% if LigneCommandes|length > 0 and LigneCommandesLoc|length > 0 %}
        <div style="page-break-after:always"></div>
        {% endif %}


        {% if LigneCommandesLoc|length > 0 %}

        {% set AvecRemise = false %}
        {% for ligneCommande in LigneCommandesLoc %}
        {% if ligneCommande.remise %}
        {% set AvecRemise = true %}
        {% endif %}
        {% endfor %}
        <br>
        <table id="demo-foo-addrow2" class="table color-table " style="border-collapse:collapse">
            <thead style="background-color: lightgray;">
                <tr>

                    <th style="height: 10px;border:0.5px solid black">Libelle</th>
                    <th style="height: 10px;width: 10%;border:0.5px solid black;text-align: right">Prix/HT</th>
                    {% if AvecRemise %}
                    <th style="height: 10px;width: 10%;border:0.5px solid black;text-align: right">%Remise</th>
                    <th style="height: 10px;width: 10%;border:0.5px solid black;text-align: right">Prix/Remise</th>
                    {% endif %}


                    <th style="height: 10px;width: 10%;border:0.5px solid black;text-align: center">Quantité</th>
                    <th style="height: 10px;width: 15%;border:0.5px solid black;text-align: right">Total Prix/HT</th>

                </tr>
            </thead>
            <tbody style="border: black">

                {% set TotalHTL = 0 %}
                {% for ligneCommande in LigneCommandesLoc %}
                <tr>
                    {% set Total = ligneCommande.prixHtU * ligneCommande.quantite %}

                    <td style="border:0.5px solid black">{{ligneCommande.produit}}

                    </td>
                    <td style="border:0.5px solid black;text-align: right">
                        {{ligneCommande.prixHtSansRemise|number_format(2,',',' ')}}€
                    </td>
                    {% if AvecRemise %}
                    <td style="border:0.5px solid black;text-align: right">
                        {{ligneCommande.remise|number_format(2,',',' ')}}%
                    </td>
                    <td style="border:0.5px solid black;text-align: right">
                        {{ligneCommande.prixHtU|number_format(2,',',' ')}}€
                    </td>
                    {% endif %}
                    <td style="border:0.5px solid black;text-align: center">{{ligneCommande.quantite}}</td>
                    <td style="border:0.5px solid black;text-align: right">{{Total|number_format(2,',',' ')}}€</td>
                </tr>
                {% set TotalHT = TotalHT + Total %}
                {% set TotalHTL = TotalHTL + Total %}
                {% endfor %}


            </tbody>


            <tfoot>

                <tr>
                    <td style="border-top: 0.5px solid black;border-left:  0.5px solid black;"></td>
                    <td style="border:0.5px solid black;text-align: right" {% if AvecRemise %}colspan="4" {% else
                        %}colspan="2" {% endif %}><strong>TOTAL (HT)</strong></td>
                    <td style="border:0.5px solid black;text-align: right">
                        <strong>{{TotalHTL|number_format(2,',',' ')}}€</strong>
                    </td>
                </tr>
                <tr>
                    <td style="border-left:  0.5px solid black"></td>
                    <td style="border:0.5px solid black;text-align: right" {% if AvecRemise %}colspan="4" {% else
                        %}colspan="2" {% endif %}><strong>TVA</strong></td>
                    <td style="border:0.5px solid black;text-align: right">
                        <strong>{{(TotalHTL * 20 /100)|number_format(2,',',' ')}}€</strong>
                    </td>
                </tr>
                <tr>
                    <td style="border-left:  0.5px solid black;border-bottom: 0.5px solid black"></td>
                    <td style="border:0.5px solid black;text-align: right" {% if AvecRemise %}colspan="4" {% else
                        %}colspan="2" {% endif %}><strong>TOTAL TTC
                            (Mensuel)</strong></td>
                    <td style="border:0.5px solid black;text-align: right">
                        <strong>{{(TotalHTL + (TotalHTL * 20 /100))|number_format(2,',',' ')}}€</strong>
                    </td>
                </tr>

            </tfoot>
        </table>
        {% endif %}

    </div>
    <br>


    <footer>


        <div class="col-md-12 col-sm-12 col-xs-12" style="float: left">

        </div>
        <br><br><br><br><br>
        <p style="text-align: center">Siret : 334 821 097 00089 - APE : 7120A – RCS AIX-EN PROVENCE – Capital
            :
            19392€</p>
    </footer>




</body>

</html>

**Comment by bsweeney** [comment]
I believe the issue is that you're setting the font-weight to 300. Default font weight (i.e. normal) is 400. We don't have strong handling of numeric weights so if a specific weight isn't defined the font matching logic will fail. This is currently the case even for the default font. You should stick to normal (400) and bold (700) weights at present unless you've installed a font at a different weight.

I opened two issues related to this. In the short term we should be able to handle this particular use case better by ensuring that the ultimate fallback is the default font (#2816). In the long term we need to improve how Dompdf handles numeric font weights (#2817).
