### ISSUE TITLE
How to make a different margin top and bottom only for the first page? Different headers and footers

### ISSUE THREAD

**Issue by wadid** [dompdf/dompdf#2815]
On the first page I have a slightly bigger header and footer. I set them with position absolute and z index. They are together in one dinA4 picture which I use as background for the dompdf.

Then for the following pages after the first one I use a background image (again header and footer in one file) in the body element

```
		@page { 
			size: 2480px 3508px;
		}
		
		.bg { 
			position: absolute;
			width:100%;
			height:100%;
			left:0px;
			top:0px;
			background: url("/wp-content/plugins/mbm_kalkulation/img/brief_1.jpg");
			background-position: top left;
			background-repeat: no-repeat;
			background-size: 100%;
			z-index:10;
		}

		body { 
			margin: 0px; 
			padding:0; 
			font-size:32px;
			background: url("/wp-content/plugins/mbm_kalkulation/img/brief_2.jpg");
			background-position: top left;
			background-repeat: no-repeat;
			background-size: 100%;
			padding: 0px 0px 0px 0;
			font-family: "OpenSans";
		}	
```

Now I need to do a different margin on the first page than on the second. Unfortunately I am generating dynamic content (tables) not static content. So I dont know where my page break is. So I cannot set a specific element with a top or bottom margin.
Is there some command to set the margin only for a subset of pages or to exclude some?

**Comment by bsweeney** [comment]
Margins are easy:

```
<style>
  @page { margin: .5in }
  @page :first { margin: 2in; }
  body { background-color: orange; }
</style>

<p>page 1</p>
<p style="page-break-before: always;">page 2</p>
```

Headers not so much, and depends on what you can realistically use (crafted PDF objects, css, embedded scripts, callbacks). Easiest method is to render the regular header on all pages but cover it on the first page so that it doesn't show. The way you might do this varies depending on the release of Dompdf, with 1.2.0:

```
<style>
  @page { margin: .5in }
  @page :first { margin: 2in; }
  body { background-color: orange; }
  
  #header-page1 {
    position: absolute;
    top: -2in;
    left: -2in;
    right: -2in;
    height: .5in;
    background-color: black;
  }
  #header-cover {
    position: absolute;
    top: -2in;
    left: -2in;
    right: -2in;
    height: 2in;
    background-color: white;
  }
  #header {
    position: fixed;
    top: -2in;
    left: -2in;
    right: -2in;
    height: .5in;
    background-color: gray;
  }
</style>

<div id="header"></div>
<div id="header-cover"></div>
<div id="header-page1"></div>

<p>page 1</p>
<p style="page-break-before: always;">page 2</p>
```

This isn't ideal but produces the desired visual result.

**Comment by wadid** [comment]
So with this solution I would need headers and footer separate? Would it work if header and footer is together in one file?

I saw you put in a page break. Because the tables are created dynamically I dont know where the page break is. Do I need to know that for that solution?

At the moment  lot of the tables are split in half when there is a new page starting. Is there a way to make sure that tables when they exceed the available page will be put on the next page. Unfortunately I can't know the exact size of the tables before the pdf is generated. :/ Thank you very much!

**Comment by bsweeney** [comment]
This works with headers and footers in the same document. The page break is in there just to create a page break. Anything that causes a page break will behave the same manner (even a table larger than one page). I was just keeping the sample simple.

<details>
<summary>longer example</summary>

```
<style>
  @page { margin: .5in }
  @page :first { margin: 2in; }
  body { background-color: orange; }
  
  #header-page1 {
    position: absolute;
    top: -2in;
    left: -2in;
    right: -2in;
    height: 2in;
    background-color: black;
  }
  #header-cover {
    position: absolute;
    top: -2in;
    left: -2in;
    right: -2in;
    height: 2in;
    background-color: white;
  }
  #header {
    position: fixed;
    top: -2in;
    left: -2in;
    right: -2in;
    height: .5in;
    background-color: gray;
  }
  #footer-page1 {
    position: absolute;
    bottom: -2in;
    left: -2in;
    right: -2in;
    height: 2in;
    background-color: black;
  }
  #footer-cover {
    position: absolute;
    bottom: -2in;
    left: -2in;
    right: -2in;
    height: 2in;
    background-color: white;
  }
  #footer {
    position: fixed;
    bottom: -2in;
    left: -2in;
    right: -2in;
    height: .5in;
    background-color: gray;
  }
</style>

<div id="header"></div>
<div id="header-cover"></div>
<div id="header-page1"></div>

<div id="footer"></div>
<div id="footer-cover"></div>
<div id="footer-page1"></div>

<table>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
  <tr><td>dompdf</td></tr>
</table>
```

</details>

**Comment by wadid** [comment]
I realized if you set a negative margin on top that the footer on the bottom of the first page disappears behind the footer for the second and following pages. I needed to set the height of the div to like 130% then the footer for the first page reappeared.

Also I wanted to ask if there is way to make tables not split by a page break?

**Comment by bsweeney** [comment]
With the current release you can style the table with `page-break-inside: avoid;`. That won't absolutely prevent page breaks, such as if the table is too large to fit on a page. But if the table is smaller than a single page it'll move it to the next page before splitting it.

**Comment by bsweeney** [comment]
> the dompdf version for that project is 0.8.2

Ah, bummer. Some of the same techniques may still work but you might have to play around with the styling. Avoid the page break styling on tables, though, because it's not handled well.

> I am trying also to set the pagenumbering on a different position on the first page compared to the other pages.

page_text is applied to all pages after the PDF is rendered. You'd have to use page_script instead. I believe something like the following (untested code) would work:

```
<script type="text/php">
  if (isset($pdf)) {
    $pdf->page_script('
      if ($PAGE_NUM === 1) {
        $x = 183;
        $y = 919;
      } else {
        $x = 283;
        $y = 819;
      }
      $text = "Seite $PAGE_NUM von $PAGE_COUNT";
      $font = $fontMetrics->get_font("OpenSans", "bold");
      $size = 6;
      $color = array(0,0,0);
      $word_space = 0.0;  //  default
      $char_space = 0.0;  //  default
      $angle = 0.0;   //  default
      $pdf->page_text($x, $y, $text, $font, $size, $color, $word_space, $char_space, $angle);
    ');
  }
</script>
```
