### ISSUE TITLE
Inherited font-size and font-size-relative styling in the same style declaration throws exception

### ISSUE THREAD

**Issue by bsweeney** [dompdf/dompdf#2818]
This bug stems from the fact that style properties that inherit are computed later in the style parsing process. At the same time, side widths (outline, margin, border, padding) are computed when the value is set. As a result, if font-size is set to "inherit" within the same style declaration as a font-size-relative measurement PHP throws an exception similar to the following (in PHP 8.1):

> TypeError: Unsupported operand types: string * float in dompdf\dompdf\src\Css\Style.php:851
> Stack trace:
> 0 dompdf\dompdf\src\Css\Style.php(2058): Dompdf\Css\Style->single_length_in_pt('1em')
> 1 dompdf\dompdf\src\Css\Style.php(2851): Dompdf\Css\Style->_set_style_side_type('border', 'top', 'width', '1em')
> 2 dompdf\dompdf\src\Css\Style.php(1322): Dompdf\Css\Style->set_border_top_width('1em')
> 3 dompdf\dompdf\src\Css\Style.php(963): Dompdf\Css\Style->compute_prop('border_top_widt...', '1em')
> 4 dompdf\dompdf\src\Css\Stylesheet.php(1204): Dompdf\Css\Style->merge(Object(Dompdf\Css\Style))
> 5 dompdf\dompdf\src\Dompdf.php(753): Dompdf\Css\Stylesheet->apply_styles(Object(Dompdf\Frame\FrameTree))
> 6 Dompdf\Dompdf->render()
> 7 {main}

and can be triggered with something as simple as the following:

```
<div style="font-size: inherit; padding: 2em;"></div>
```

Within the `single_length_in_pt` method the font-size is expected to be numeric (per the typed argument, though certainly internal use doesn't necessarily have to conform). Because font-size is used internally when setting other properties it maybe deserves special handling so that it always has a valid computed value.

_Originally posted by @bsweeney in https://github.com/dompdf/dompdf/issues/2814#issuecomment-1072918854_

**Comment by bsweeney** [comment]
Thinking we just remove the inherit-related lines from `set_font_size` and condition the "inherit" logic in `compute_property` to exclude font-size so the setter is called.

**Comment by Mellthas** [comment]
Thanks for the analysis. I think we can simply make sure to always have a valid computed value for any property, no need for a font-size special case. During inheritance, the specified value (`$style->_props`) is checked, so there is no point in computing to `inherit` at all.
