### ISSUE TITLE
Add support for custom stream wrappers as local file

### ISSUE THREAD

**Issue by pfeigl** [dompdf/dompdf#2826]
PHP allows to register custom stream wrappers (see https://www.php.net/manual/de/function.stream-wrapper-register.php)

This allows PHP to work with those files with all the default file based functions.

Now dompdf has various checks across it's code base where the `protocol` is checked against `file://` and if so it proceeds as if the file is local.
We'd like to have custom stream wrappers also handled as local files instead of them beeing interpreted as remote files.

Our specific situation is, that we would like to integrate images files hosted on an S3 compatible storage into the PDF files without using http(s) URLs. S3 storages can be integrated in php using a custom `s3://` protocol. See here for details: https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html

What I'd love to have is a possibility to set specific list of protocols to be handled as `local` instead of `remote`. This could be setable via the the `Options` when initializing a new object instance. This could be pre-initialized with `file://`.

Thoughts?

**Comment by bsweeney** [comment]
Going to be doing some work around file access so I'll see if I can get this done as well.

**Comment by bsweeney** [comment]
Curious if you require the protocol to be treated as local. It would be a bit easier to implement as a remote protocol, which of course would require that remote resources can be loaded.

**Comment by pfeigl** [comment]
For our specific usecase local would work out better I think. I'm not 100% sure what a remote implementation would mean. I saw that in certain situations it falls back to use `curl` and that would obviously not work I think.

**Comment by bsweeney** [comment]
I think the way to handle this is to always parse non-core protocols (those other than file://, http://, https://) using `file_get_contents`, similar to local files. This special handling is necessary since the Dompdf definition of local vs remote has implications related to validation and the core rules may not be sufficient for custom protocols. This means we'll bypass the validation rules for custom protocols, and we'll outline that in the documentation.

**Comment by pfeigl** [comment]
As long as wie push those paths through standard PHP file access functions, everything should be fine I think

**Comment by bsweeney** [comment]
The changes made in #2859 should make it possible to utilize custom stream wrappers.
