### ISSUE TITLE
Dompdf Library Issue with Number character,

### ISSUE THREAD

**Issue by SuperStarDeveloper** [dompdf/dompdf#2827]
Hello everyone.

as a web developer, I am using dompdf laravel package for invoice pdf. but there is a problem with arabic number. now showing mixed arabic number with english, so please assist me. thank you,

issue:
Order Date :22:25:10 am 09-Feb-20٢2
lNMS164٤4023٢2

best regards,
Jin

**Comment by erikn69** [comment]
https://github.com/dompdf/dompdf/issues/2760#issuecomment-1019533668

**Comment by SuperStarDeveloper** [comment]
yet there is a problem with character.
like 
Invoice Number :357
Order Date :**32:52:11 am 27-Mar-٢0٢2**
Tax ID Number :123456
Order ID :ODhk1648381952
Shipping Method :Ship To Address
