### ISSUE TITLE
Image not found or type unknown

### ISSUE THREAD

**Issue by poritoshdavid** [dompdf/dompdf#2832]
```
$html="<img src='ant.png'/>";
    // $dompdf->loadHtml($aData['html']);
    $dompdf->set_option("isRemoteEnabled",TRUE);
    $dompdf->loadHtml($html);
    $dompdf->render();

    $dompdf->loadHtml($html);
    $dompdf->render();
    $dompdf->stream();
```

**Comment by bsweeney** [comment]
Using a recent release? Local resources are path-restricted. You'll need to set the chroot option to the path(s) where resources may be referenced.

For your specific example one of the following would work. Replace `__DIR__` with something more appropriate for your actual image locations (if different).

```
$dompdf = new Dompdf(["options" => [__DIR__]])
```

```
$dompdf->set_option("chroot", [__DIR__]);
```
(note that set_option is deprecated and will be removed in a future release)

**Comment by Whip** [comment]
It should be
```
$dompdf = new Dompdf(["chroot" => [__DIR__]])
```

**Comment by bsweeney** [comment]
@Whip thanks for catching that, fixed my comment to avoid confusion in the future.
