### ISSUE TITLE
Float does not work proper in case of 2 column.

### ISSUE THREAD

**Issue by sssisodia93** [dompdf/dompdf#2835]
I am trying to create a layout with columns by using dompdf. After some research I used display: inline-block; instead of float: left;

The problem is next:

If I have 2 columns (column1 and column2), column1 will generate on page1 and if column1 exceeds page1 and the content goes on page2, then the next column (column2) will be generated on page2, not on page1 as it should be.

Do you know how to fix this issue with columns in dompdf, or give me an advice how to successfully do this?

**I have used the below css for it:**

```
.BlankResumePrint_row_left {
      max-width:470px !important;  
      float:left !important;
      height: 100%; 
}

 .BlankResumePrint_row_right {
  float: right !important;
  width:210px !important; 
  height: 100%;  
  background:green; 
  color:#fff; 
  padding-left:25px;
  padding-right:35px; 
  vertical-align: top;
}
     
.BlankResumePrint_row{
  display: block;
  width: 100%; 
}
```

**You can see the green column on the right, it should goes to page no 1 not where the column 1 content end.**

![image](https://user-images.githubusercontent.com/16095154/160077820-9874fcad-3de0-4b8b-94c8-296e14602b9d.png)

**Comment by bsweeney** [comment]
This is due to a quirk in the way that Dompdf renders pages. Content is rendered as it's encountered, so when a page break is required content rendered after the break is rendered to the new page. It's something we would like to address, though no timeline at present.

First reported in ... #1192 I think?
