### ISSUE TITLE
Can this service achieve such a PDF to Word effect? https://www.geekersoft.com/pdf-to-word.html

### ISSUE THREAD

**Issue by John123255665656565** [dompdf/dompdf#2837]
Can this service achieve such a PDF to Word effect?
https://www.geekersoft.com/pdf-to-word.html

**Comment by bsweeney** [comment]
Dompdf is not a service but a library you can add to your own projects. Also, it's purpose is to convert HTML to PDF.

**Comment by John123255665656565** [comment]
> Dompdf is not a service but a library you can add to your own projects. Also, it's purpose is to convert HTML to PDF.

Thanks
