### ISSUE TITLE
Dompdf issue with Arabic character.

### ISSUE THREAD

**Issue by SuperStarDeveloper** [dompdf/dompdf#2843]
yet there is a problem with character.
like
Invoice Number :357
Order Date :32:52:11 am 27-Mar-٢0٢2
Tax ID Number :123456
Order ID :ODhk1648381952
Shipping Method :Ship To Address

**Comment by bsweeney** [comment]
Do you have sample HTML + CSS? The core PDF fonts (e.g. helvetica) only supports characters from the Latin-1 encoding. You would need to use a font that supports Arabic characters, such as the bundled DejaVu fonts.

**Comment by SuperStarDeveloper** [comment]
yes, now there is only problem with date character.

**Comment by bsweeney** [comment]
The following seems to render fine.

```
<style>
  * { font-family: DejaVu Sans, sans-serif; }
</style>
Invoice Number :357<br>
Order Date :32:52:11 am 27-Mar-٢0٢2<br>
Tax ID Number :123456<br>
Order ID :ODhk1648381952<br>
Shipping Method :Ship To Address
```

Can't really help without seeing the HTML + CSS you're trying to render.

**Comment by SuperStarDeveloper** [comment]
Okay. I will share my code, could you share email?
