### ISSUE TITLE
How to add table title to next pages

### ISSUE THREAD

**Issue by Ademgenc53** [dompdf/dompdf#2844]
Sample:
![Annotate-a-local-image](https://user-images.githubusercontent.com/55327675/161539626-33aec04c-7227-423f-996d-b2ea371d2320.png)

Hello,
I am creating multiple pages with table, but I want to add table title at the beginning of each page.
How is this done?

Thank you from now

**Comment by bsweeney** [comment]
You can do this using a THEAD element for the header row:

```
<table>
  <thead>
    <tr><td>column 1</td><td>column 2</td></tr>
  </thead>
  <tbody>
    <tr><td>1</td><td>2</td></tr>
    <!-- more rows creating a page break -->
  </tbody>
</table>
```
