### ISSUE TITLE
how to handle the unknown height of a table?

### ISSUE THREAD

**Issue by michabbb** [dompdf/dompdf#2847]
hi,
i am very happy with this package but I am wondering how others are handling the following issue:
let's say you create a "delivery note" with a list of products you show within a table. so customers can order
5 or 50 items, depending on the count the table gets its height. so I don´t know the height of the table exactly
and neither I don´t know if the table needs a 2nd page.

i can place anything below the table by putting something below `</table>` okay.
but let´s say I need the absolute position of the table's end - is there any way to get that info ?
so I am able to work with absolute positions instead of a relative?

the next problem in my example: let´s say someone orders so many items, they won´t fit on one page
and each item has a "title" and the title is dynamic as well. a title can fit into one row or needs 3 rows,
because there are several `<br>` included. 

while creating the table inside a `foreach` I need to know where to stop and create
a 2nd page to continue with my table if the height is too big. but for that I need to
calculate the height of the table **before** it´s too late.

i would be happy to get some advice, recommendations, and tips here!
thanks !

**Comment by bsweeney** [comment]
On your first question, what is the use case for knowing the end of the table? Are you intending to put some boilerplate content at the end of the table on each page?

As for your section question, are you trying to avoid breaking an individual row across pages? Dompdf currently requires the entire row to fit within a single page, so this shouldn't be a problem.

**Comment by michabbb** [comment]
first question: yes. but as I said, putting something underneath `</table>` will solve that problem, without knowing the height of the table. it´s a more general question, in case I need to position something "absolute" via CSS. for that I would need to know where the table ends. and I was just wondering if there is a chance to find out.

> Dompdf currently requires the entire row to fit within a single page, so this shouldn't be a problem.

that´s something I don´t understand, sorry. first, you say that dompdf "requires" something, and in the same
sentence you say "shouldn´t be a problem", which is confusing. 

when I don´t know how heigh my table gets because the contents of the table is dynamic and each row can have one or more  "newlines"... i actually have no control to decide, where I force a page-brake and start with the rest of my data on the next page. 
that´s my concern here.

if dompdf goes on with the table on the second page on the very top of the page, that might be "okay" for most...
but if you create invoices you don´t want a table just going on on the next page, you need a fresh new table at a specific position and go on from there... and this for every page....

but I will never know how many pages I need because I don´t know the height of my table...

i hope I was able to explain my problem here.

**Comment by bsweeney** [comment]
> in case I need to position something "absolute" via CSS. for that I would need to know where the table ends. and I was just wondering if there is a chance to find out.

With pure HTML + CSS no. By the time that information is available Dompdf will have already ingested your HTML and started the layout process. As a result there is not anything you can do with the HTML at that point.

It may be possible using callbacks ... though that would be a lot more complex operation because you'd either have to inser the content manually (using the Canvas adapter) or dynamically update the Dompdf representation of the document which I guess is _maybe_ possible?

> > Dompdf currently requires the entire row to fit within a single page, so this shouldn't be a problem.
>
> that´s something I don´t understand, sorry. first, you say that dompdf "requires" something, and in the same sentence you say "shouldn´t be a problem", which is confusing.

I can see how that statement can be confusing. What I mean to say is that Dompdf _will not_ split any single row across pages. If any cell within the row doesn't fit onto a single page then the entire row is moved to the next page.

> but if you create invoices you don´t want a table just going on on the next page, you need a fresh new table at a specific position and go on from there... and this for every page....

Not entirely sure what you mean by this. As I said Dompdf will not split the table row across pages so your multi-line product name will all be on the same page. And if you are saying you want a table header to repeat on the next page, just put it in a THEAD at the top of the table.

**Comment by michabbb** [comment]
> I can see how that statement can be confusing. What I mean to say is that Dompdf will not split any single row across pages. If any cell within the row doesn't fit onto a single page then the entire row is moved to the next page.

i guess I finally understand, what you mean, thanks for clarification 😏 
but my point, I guess where you might not understand my point:  this "moved to the next page" is something I have no control of, If i understand you correctly. so i cannot say "okay, move to the next page if you need, but please, start your new row on the next page with a margin-top of 5em or something like that" - correct ? i guess i have no control about this "auto-next-page-behavior", isn´t it ?

> And if you are saying you want a table header to repeat on the next page, just put it in a THEAD at the top of the table.

so do i understand this correctly? if i am working with a THEAD, dompdf will create "the same" header automatically on the next page for me ? 🤔

**Comment by bsweeney** [comment]
CSS3 supports supports the re-application of margins when a box is broken across pages, which we don't yet support (#640). There may be other ways to accommodate what you need but I'd have to have a sense of what you're trying to accomplish visually.

One possibility to accomplish this might be to use a [callback](https://github.com/dompdf/dompdf/wiki/Usage#callbacks) to tweak the styling of an element manually after a page break. I'd have to ponder on that.

As for THEAD, yes the header is replicated at the top of the table on every page.

**Comment by michabbb** [comment]
@bsweeney thanks for your feedback here. i will do some simple tests and play around. of course, showing something visually helps more than words 😏 will try to prepare something....
