### ISSUE TITLE
How to avoid ???? for Arabic Text

### ISSUE THREAD

**Issue by mansoorahmadofficial** [dompdf/dompdf#2849]

**Comment by bsweeney** [comment]
Use a font the supports the characters in the document. Such as one of the DejaVu fonts bundled with Dompdf.

You can find more info in the [Unicode HowTo](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo) in the wiki.

**Comment by mansoorahmadofficial** [comment]
Hey Brian Sweeney ,
Thank for your response, I m using the font you mentioned but it doest work
for me
$dompdf = new Dompdf();
$options = $dompdf->getOptions();
$options->setDefaultFont('DejaVuSans');
$dompdf->setOptions($options);

$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
ob_end_clean();
$output = $dompdf->output();

**Comment by bsweeney** [comment]
What does your HTML look like? The default font is the one used if no document-defined fonts are available.
