### ISSUE TITLE
'Failed - Network error'

### ISSUE THREAD

**Issue by bazl0** [dompdf/dompdf#2852]
When downloading the generated PDF I get 'Failed - Network error'.

Works fine locally but not on live AWS EC2 instance.

Anyone had similar problems?

**Comment by bazl0** [comment]
Using print and 'printing' as PDF saves the file fine...

**Comment by Jiang-Haichen** [comment]
I got the same question. working fine for both reviewing and downloading in local env but not good for downloading in server side...

**Comment by bsweeney** [comment]
Since using the browser's print function doesn't involve Dompdf I would expect that to work differently.

Are you streaming the PDF (e.g. `$dompdf->stream()`)? Maybe try capturing the PDF in a string to echo to the browser to see if that works better:

```
$pdf = $dompdf->output();
header("Content-type:application/pdf");
echo $pdf;
exit;
```

**Comment by bazl0** [comment]
@bsweeney you absolute star - this worked a treat and actually fixed another problem I had with Safari not even loading the PDF in the browser. 

Thank you kindly for your help.

**Comment by bsweeney** [comment]
Not sure what's going on that would cause this type of error when calling `stream`. The stream method doesn't do much more than what I outlined, though it is a bit more complex. Maybe the explicit call to `flush()`? Might be worth some investigation.

**Comment by GerritEMulder** [comment]
I have this same issue, I am using $dompdf->stream($filename); and on the live version of the website I get 'Failed - Network error' when it tries to download the pdf.  However on the dev site which is pretty much identical to the live site (identical code, same server, no local) it works fine and downloads with no issues.  I tried all sorts of things (disabling headers, cloudflare, different browsers etc) but with no luck.

Thankfully the workaround @bsweeney gave works great so I am just going to use that for now.

**Comment by MarcPinnell** [comment]
I am having issues with this error as well, with the same experience where "printing" allows you to save the file. The wrinkle in my case is I am saving each page of the PDF to disc (in an attempt to make PDF generation faster) and then merging together and streaming to screen. So I can't use the @bsweeney fix above. Because of my workflow I don't think it would be a domPDF issue, but open to suggestions:

```
loopy stuff here to create PDFs

		//Now combine PDFs into a single file and serve them up:
		$merger = new Merger;
		for ($x = 0; $x < $i; $x++) {
			$merger->addFile($path.$x.'.pdf');
		}
		$createdPdf = $merger->merge();

		//don't need the pieces anymore
		$this->removeFolder($path);

		$stream = fopen('php://memory','r+');
			fwrite($stream, $createdPdf);
			rewind($stream);
			header('Content-type: application/pdf');
			header('Content-Disposition: inline; filename='.$pdfTitle);
			echo stream_get_contents($stream);
		fclose($stream);

		exit();

```
