### ISSUE TITLE
Dependency Vulnerability

### ISSUE THREAD

**Issue by ktam-riab** [dompdf/dompdf#2853]
Our dependency scanner has found two issues related to the most recent release (1.2.1):

✗ Medium severity issue found in phenx/php-svg-lib
  Description: LGPL-3.0 license
  Info: https://snyk.io/vuln/snyk:lic:composer:phenx:php-svg-lib:LGPL-3.0
  Introduced through: dompdf/dompdf@1.2.1
  From: dompdf/dompdf@1.2.1 > phenx/php-svg-lib@0.4.1

✗ Medium severity issue found in phenx/php-font-lib
  Description: LGPL-3.0 license
  Info: https://snyk.io/vuln/snyk:lic:composer:phenx:php-font-lib:LGPL-3.0
  Introduced through: dompdf/dompdf@1.2.1
  From: dompdf/dompdf@1.2.1 > phenx/php-font-lib@0.5.4

Can this be addressed and a new version released?

Thanks.

**Comment by bsweeney** [comment]
I'm not sure what vulnerability is being referenced here. Can you clarify?

**Comment by omarkdev** [comment]
https://github.com/advisories/GHSA-x752-qjv4-c4hc

**Comment by ktam-riab** [comment]
Hi @bsweeney 

Snyk, our dependency scanner, has flagged the phenx/php-svg-lib and phenx/php-font-lib packages that get installed with the latest dompdf v1.2.1 install as having issues.

However, checking their own library pages for these packages, the latest versions of each don't show as currently having vulnerabilities:
https://snyk.io/vuln/composer:phenx%2Fphp-font-lib
https://snyk.io/vuln/composer:phenx%2Fphp-svg-lib

We'll check with Snyk to see what's going on.

Thanks.

**Comment by S-DICKSON** [comment]
@ktam-riab any updates on this?

**Comment by ktam-riab** [comment]
Hi. Yes, we misunderstand the Snyk finding on these two dependencies. Snyk is flagging these as a medium severity issue because of the license they are using (GNU Lesser General Public License) instead of the standard GNU GPL, due to the Lesser license's more restrictive use conditions.

**Comment by bsweeney** [comment]
I was under the impression that the LGPL was _less_ restrictive, not more. It is one of the reasons outlined by GNU to use the GPL instead where possible: https://www.gnu.org/licenses/why-not-lgpl.en.html

As I understand it the flagging is because of "potentially legal vulnerable" for inclusion but I'm curious what the specific reason LGPL is considered worse in Synk's view.

**Comment by S-DICKSON** [comment]
I fixed this problem by upgrading to version 1.0, forgot to mention it.
