### ISSUE TITLE
Hindi / Devanagari Fonts not rendering properly in DOMPDF

### ISSUE THREAD

**Issue by swapnilraja1212** [dompdf/dompdf#2855]
I have included online google hindi / devanagari fonts in my DOMPDF. Font are being called but text are not rendering properly.

Corrent Word: अंतरिक्ष यान से दूर नीचे पृथ्वी शानदार ढंग से जगमगा रही थी ।

Font rendered in PDF: 
![error_font](https://user-images.githubusercontent.com/5059713/163327033-ad7b6576-49c5-47e1-bb20-43f5749bdc12.JPG)
 
Please somebody help!

**Comment by mehtamanoj** [comment]
> I have included online google hindi / devanagari fonts in my DOMPDF. Font are being called but text are not rendering properly.
> 
> Corrent Word: अंतरिक्ष यान से दूर नीचे पृथ्वी शानदार ढंग से जगमगा रही थी ।
> 
> Font rendered in PDF: ![error_font](https://user-images.githubusercontent.com/5059713/163327033-ad7b6576-49c5-47e1-bb20-43f5749bdc12.JPG)
> 
> Please somebody help!

@swapnilraja1212 have you fixed this?
  I have the same problem

**Comment by swapnilraja1212** [comment]
@mehtamanoj There are some limitations in dompdf. I have used mpdf and it's better than dompdf
