### ISSUE TITLE
Function name must be a string: dompdf/src/FontMetrics.php:143

### ISSUE THREAD

**Issue by cannycookie** [dompdf/dompdf#2861]
Version: 1.2.1

if I delete the file: ```storage/fonts/dompdf_font_family_cache.php```

The PDF loads for the first load only, second time we get an error.

I have noticed that there's an extra forward slash in the path ```storage/fonts//dompdf_font_family_cache.php``` 

created from 
```php
 public function getCacheFile()
    {
        $file = $this->options->getFontDir() .'/'. self::CACHE_FILE;
```

If I remove the extra slash it works -> kinda hurrah.  How best to fix this for everyone?

Thanks for any help..

**Comment by cannycookie** [comment]
To allow our site to work -> it's a bit mission critical,  I've removed the extra slash with a post deploy hack:-

```
sudo sed -i "s+'/' . self::CACHE_FILE+self::CACHE_FILE+g" vendor/dompdf/dompdf/src/FontMetrics.php
```

And now the font file is 0 bytes, if I delete it it's not recreated.

But

the previous version was:-

```php
<?php return function ($fontDir, $rootDir) {
return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'fontawesome' => array(
    'normal' => $fontDir . '/fontawesome_normal_b9be68b0c5f28a446c6cb0ef95254567',
  ),
);
}; ?>
```

Annoyingly the problem does not occur on my machine -> vagrant with Ubuntu
but on AWS linux it doesn't and we get the error.

**Comment by bsweeney** [comment]
So right now you're not able to detail the issue because of the post-deploy hack? Which is _totally_ understandable for a live site. Any possibility of setting up a mirror in a different directory? Or a separate AWS instance?

I'm still trying to wrap my head around what's actually happening.

**Comment by bsweeney** [comment]
Also note that with 2.0.0 I was planning to change how the installed-font cache works (#2450).

**Comment by cannycookie** [comment]
Sure, I have other instances. 

The error is thrown on this call:-

```php
 $cacheDataClosure = require $this->getCacheFile();
```
So $cacheDataClosure isn't defined until the error happens.

I may have found the issue though.  in barryvdh/laravel-dompdf wrapper the config file suggests including a trailing slash on the font directory - Clearly your code is adding it in as well.

Having removed the trailing slash in the config it is now working, took a while to confirm as the opcache needed refreshing in between changes.

Many Thanks
Case closed.  No bug :-)

**Comment by bsweeney** [comment]
I think that might have been the expected format at one point, but obviously not what we're looking for now. I'm still a bit surprised at the sequence of events, but since that logic is about to change I'll just leave this as a documentation question.

I'll review the code to see if there's anywhere else we're building a path that something like this might occur.

**Comment by cannycookie** [comment]
Thanks for your prompt help.  Got there in the end.

[image: Lee Evans] <http://www.ekouk.com/>

Lee Evans MSc, MCSE
Cloud Architect, Systems Analyst, White Hat

Technical Director at *Eko UK Limited*

Mocatta House, Trafalgar Place, Brighton, BN1 4DU

t: +44 (0)1273 455 706 <01273-455706>

e: ***@***.***

m: +44 (0)7702 000 007 <+44-7702-000-007>

w: https://www.ekouk.com

[image: twitter] <https://twitter.com/CannyCookie>

[image: facebook] <https://www.facebook.com/AcroYogaNinja>

[image: instagram] <https://www.instagram.com/acroyoganinja/>
