### ISSUE TITLE
Image not found or type unknown

### ISSUE THREAD

**Issue by fadharpra** [dompdf/dompdf#2862]
Im using Codeigniter with composer behind Nginx Reverse Proxy Server, dompdf cant show image and have error message 'Image not found or type unknown'. If im not use Nginx Reverse Proxy Server, dompdf can show image.

Application with dompdf runing on port 80 using Apache, and Nginx Reverse Proxy using port 443 with IP Public.

My configuration of Nginx Reverse Proxy:
```
server{
       	listen 80;
        return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name somedomain.com www.somedomain.com;

    #ssl on;
    ssl_certificate         /some/dir/ssl.pem;
    ssl_certificate_key     /some/dir/ssl.key;
    #ssl_trusted_certificate /some/dir/ssl.crt;

    ssl_session_cache shared:SSL:20m;
    ssl_session_timeout 10m;

    ssl_prefer_server_ciphers       on;
    ssl_protocols                   TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers                     ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;

    add_header Strict-Transport-Security "max-age=31536000";

    access_log      /var/log/nginx/somedomain_access.log;
    error_log       /var/log/nginx/somedomain_error.log;



    location / {
        proxy_pass http://ip-local;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_pass_request_headers	on;
        }
}
```
Please help me, this issue stressed me out 
Thank You!

**Comment by bsweeney** [comment]
Any errors in the logs? You can enable Dompdf's error logging by setting the global variable `$_dompdf_show_warnings = true;`. Errors are persisted to the log file indicated by the logOutputFile option.

You're using SSL on your reverse proxy. Is that using a self-generated certificate? If not you'll need to [set a custom stream context](https://github.com/dompdf/dompdf/wiki/Common-Use-Cases#custom-http-stream-context) to disable some of the HTTPS checks.

**Comment by fadharpra** [comment]
I have edited the global variable for error logging to true, and there is a message `Unable to stream pdf: headers already sent` 

Im using Trusted CA Signed SSL Certificates, `$auth = base64_encode("username:password");` what is meaning for? Im not using authentication on reverse proxy.
