### ISSUE TITLE
Wrong table width calculation with long text in fixed column width

### ISSUE THREAD

**Issue by PDFCoder** [dompdf/dompdf#2866]
After some testing of version 1.2.1 we found an issue in the calculation of the width of table cells.

If the content of table column "Quantity" (with a fixed td width) is growing (in pos. 2 -> 3 rows) the width of the whole table is shrinking! The longer the text is in this column the smaller the table will be. The red line shows how the correct table width ought to be:

<img width="1057" alt="wrong table width calulation 1" src="https://user-images.githubusercontent.com/26413959/167105412-b872388c-3dc6-44f9-a3f0-e6189eca9ccb.png">

In the example all table th tds – excluding the column "Service" – have a fixed css width (unit px).

If the column td "Quantity" has no width set, the table width is ok:

<img width="1034" alt="wrong table width calulation 2" src="https://user-images.githubusercontent.com/26413959/167106371-78c5b8cb-95a6-4e2f-87d6-c1f67ee97d1d.png">

The behaviour is reproducable, table width is set to 100%, page has `@page` margins
Test scenario: PHP 7.4/8.0 and dompdf 1.2.1.

**Comment by bsweeney** [comment]
Perhaps we are not correctly distributing widths when the column content is wider than the column's defined width.

Can you share some sample HTML + CSS?

**Comment by PDFCoder** [comment]
Of course, I prepared some sample html + css

```
<!DOCTYPE html>
<html lang="de">
<head>
<title>PDF-Test</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<style type="text/css">
@page {
	margin-top: 20mm;
	margin-bottom: 20mm;
	margin-left: 20mm;
	margin-right: 20mm;
}

body {
	font-family: Helvetica, sans-serif;
    font-size: 9pt;
	line-height: 1.3em;
}

p {
	margin: 0;
	padding: 1em 0 0 0;
}

table {
	border-collapse: collapse;
	margin: 0;
	width: 100%;
}
	
th {
	padding: 0.3em 0.8em 0.3em 0.8em;
	font-weight: bold;
	text-align: left;
    border-bottom: 2px solid #000;
}

td {
	padding: 0.6em 0.8em 0.1em 0.8em;
	vertical-align: top;
}

td p {
	margin: 0;
	padding: 0;
	padding-bottom: 0.5em;
}

td.borderBottom {
	border-bottom: 1px solid #cecccc;
}

td {
    overflow-wrap: anywhere;
}

.alignRight {
	text-align: right;
	padding-right: 4mm;
}
</style>
</head>

<body>
<p>table with long text in column "Quantity"<p> 
<table>
    <thead>
        <tr>
            <th class="td1b">Pos.</th>
            <th>Service</th>
            <th class="alignRight" style="width:55px;">Quantity</th>
            <th class="alignRight" style="width:70px;">Price</th>
            <th class="alignRight" style="width:80px;">Total</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="borderBottom"><p>1</p></td>
            <td class="borderBottom">
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
            </td>
            <td class="borderBottom alignRight">1.000,00 a very long content here in this table cell</td>
            <td class="borderBottom alignRight">100,60&nbsp;€</td>
            <td class="borderBottom alignRight">100.600,00&nbsp;€</td>
        </tr>
    </tbody>
</table>
<p>same table with short text in column "Quantity"<p>
<table>
    <thead>
        <tr>
            <th class="td1b">Pos.</th>
            <th>Service</th>
            <th class="alignRight" style="width:55px;">Quantity</th>
            <th class="alignRight" style="width:70px;">Price</th>
            <th class="alignRight" style="width:80px;">Total</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="borderBottom"><p>1</p></td>
            <td class="borderBottom">
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
            </td>
            <td class="borderBottom alignRight">short text</td>
            <td class="borderBottom alignRight">100,60&nbsp;€</td>
            <td class="borderBottom alignRight">100.600,00&nbsp;€</td>
        </tr>
    </tbody>
</table>

</body>
```

The visual result with v 1.2.2 is:
<img width="1028" alt="screenshot_v1-2-2" src="https://user-images.githubusercontent.com/26413959/167387801-fd142edb-a626-486a-8297-b54ed551ea9a.png">

The problem is the long text in the column "Quantity" that has a fixed width. It seems that it causes the wrong calculation of the table width. Thank you for having a look at it!

**Comment by Mellthas** [comment]
Thanks for the sample. The issue occurs due to inconsistent state with absolute-width columns when not all of the cells have a width set. You can work around the issue by specifying the fixed width on all cells of the column. Working on a fix.
