### ISSUE TITLE
word-wrap: break-word not working any longer

### ISSUE THREAD

**Issue by PDFCoder** [dompdf/dompdf#2868]
In version 0.8.6 the css property "word-wrap: break-word;" on table cells was working as expected (a word is split in a table column with a fixed width):

<img width="114" alt="not working word-wrap break-word 1 v0-8-6 OK" src="https://user-images.githubusercontent.com/26413959/167111176-0e033484-ddcf-4966-8e6c-366f168a06fd.png">

In our tests with dompdf version 1.1.1 and 1.2.1 the property doesn't seem to have any effect, the table column width is growing:

<img width="133" alt="not working word-wrap break-word 3 v1-2-1" src="https://user-images.githubusercontent.com/26413959/167111355-7c9c9f2e-ed4e-4a07-b23e-7efbf45f8f17.png">
 
Does anyone have a solution for this? The property "word-break: break-word;" is not working too.

**Comment by bsweeney** [comment]
Does seem to be an issue. Likely around the min/max/restricted width calculations for table cells.

Sample HTML:

```
<html>
  <head>
    <style type="text/css">
      div, table {
        background: #EDEDED;
        border: solid 1px #CCC;
        width: 50px;
        padding: 10px;
      }
      
      .break-word {
        word-wrap: break-word;
        word-break: break-word;
      }
    </style>
</head>
<body>
  <table>
    <tr>
      <td>
        <p class="break-word">I'm a veeeeeeeerryyyyyy loooooooonggggggg teeeeexxxtttt</p>
      </td>
    </tr>
  </table>
  
  <div>
    <p class="break-word">I'm a veeeeeeeerryyyyyy loooooooonggggggg teeeeexxxtttt</p>
  </div>
</body>
</html>
```

**Comment by bsweeney** [comment]
Only work-around I could offer right now would be to wrap the content in the table cell with a block element with restricted width.

**Comment by Mellthas** [comment]
The behavior is more spec-compliant now. You should be able to use `overflow-wrap: anywhere` to get the old behavior (`word-wrap` is a legacy alias for `overflow-wrap`). See https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap.

**Comment by bsweeney** [comment]
OK, yes, of course you are right I obviously hadn't fully comprehended the definitions. I think safe to say that this is not a bug. Thoughts on adding the translation of `word-break: break-word;` to `overflow-wrap: anywhere`?

**Comment by PDFCoder** [comment]
Thank you for the clarification! Changing the css of table cells in our pdf scenario to `overflow-wrap: anywhere;` will do the job. :) I just didn't know that `word-wrap: break-word` is deprecated.

**Comment by Mellthas** [comment]
> Thoughts on adding the translation of `word-break: break-word;` to `overflow-wrap: anywhere`?

I think it makes sense for compatibility reasons. See #2872.

**Comment by MuneebAccrual** [comment]
If you are working in Laravel or PHP you can do wordwrap function. In my case it worked perfectly

$description = nl2br($data['description_temporary_work_required']);
$wrappedText = wordwrap($description, 100, "<br>", true);
echo $wrappedText;

break-word, overflow and white-space is not working in mpdf or dompdf
