### ISSUE TITLE
td rowspan 跨行的问题

### ISSUE THREAD

**Issue by 233cy** [dompdf/dompdf#2878]
> <?php
require 'vendor/autoload.php';
// reference the Dompdf namespace
use Dompdf\Dompdf;

$table = '';
for ($i=0; $i < 100; $i++) {
    if( $i <= 0 ){
      $table .= '<tr><td rowspan="100" style="height: 200px; width: 100px;">左侧标题</td><td>1</td><td>2</td></tr>';
    }else{
      $table .= '<tr><td>1</td><td>2</td></tr>';
    }
}

$html = <<<EOD
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<table style="table-layout: fixed; width: 350px;" border="1">
<tbody>
{$table}
</tbody>
</table>
</body>
</html>

EOD;

// instantiate and use the dompdf class
$dompdf = new Dompdf();

/* 将中文字体设置为默认字体 */
$opt = $dompdf->getOptions();
$opt->setDefaultFont('zt');
$dompdf->setOptions($opt);

/* 设置中文字体库 */
$font = $dompdf->getFontMetrics();
$font->setFontFamily('zt', [
  'bold' => __DIR__ . '/fonts/zt',
  'bold_italic' => __DIR__ . '/fonts/zt',
  'italic' => __DIR__ . '/fonts/zt',
  'normal' => __DIR__ . '/fonts/zt'
]);
$dompdf->setFontMetrics($font);

$dompdf->loadHtml($html, 'UTF-8');

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'portrait');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream();

<img width="1766" alt="image" src="https://user-images.githubusercontent.com/29916783/168571000-351a7ff1-82e8-4b51-a78c-f7b1a2ea34da.png">
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/29916783/168571047-46ab8bc5-8b08-4c1a-bc0e-a8da54b0edf3.png">

td rowspan  Missing on page spread 
@PhenX 
@BrunoDeBarros

**Comment by bsweeney** [comment]
known issue, watch #1388 for updates

**Comment by 233cy** [comment]
@bsweeney  I haven't found a solution in #1388. Hasn't this problem been solved yet?

**Comment by BrunoDeBarros** [comment]
@233cy It is not OK to tag people out of the blue to force them to be notified of your issue on an open source project. I don't know you, I don't work for you, and I do not owe you any support. Do not do this again.

**Comment by bsweeney** [comment]
Not solved.
