### ISSUE TITLE
Assets randomly not loading

### ISSUE THREAD

**Issue by justijndepover** [dompdf/dompdf#2883]
Hi!
First of all, thank you for the amazing library!

I'm using the library to generate PDF's which contain a couple of images.
Approximately 4 png images each about 10-30 kb.
The CSS file is also loading 4 external Font faces (each about 180kb).

When generating the PDF's I get inconsistent behaviour where sometimes some of the images, or the CSS file are not loaded properly.

The images are hosted on the same server, and loaded with the relative path.
`enable_remote` is also set on the `Dompdf` class.
And both GD and imagemagick are installed.

Any idea as to what could cause the issues?

**Comment by justijndepover** [comment]
I upgraded to the latest version and the problem keeps occuring

**Comment by bsweeney** [comment]
Bummer. Do you see any PHP errors/warnings?

**Comment by justijndepover** [comment]
No I do not, could it have to do with the asset sizes?

**Comment by bsweeney** [comment]
I don't think so. If the size was problematic (e.g. a timeout or memory issue) then I would expect an error to be recorded.

You can try enabling debugging to see what Dompdf says about the resources. I use something along the lines of the following:

```
ini_set("display_errors", true);
ini_set("error_log", "phperr.log");
ini_set("log_errors", true);
error_reporting(E_ALL);

$_dompdf_show_warnings = true; // 
$dompdf = new Dompdf([
    "logOutputFile" => "log.html",
    "debugPng" => false, // extra messaging
    "debugKeepTemp" => false, // don't delete temp files
]);

// do things
```

**Comment by justijndepover** [comment]
It looks like it's a server problem. I get this error:
```
Unable to load css file https://domain.com/css/editor.css?id=85a4a541f4e469283d55
file_get_contents(https://domain.com/assets/header.jpg): failed to open stream: HTTP request failed! HTTP/1.1 429 Too Many Requests
```
