### ISSUE TITLE
Encoding on URLs not working

### ISSUE THREAD

**Issue by ivo75** [dompdf/dompdf#2904]
dompdf version: 1.2.1
PhP: 7.4
charset: utf-8
platform: Wordpress

If a url contain an ASCII code such as "%3D%3D", when I click on the link in the PDF it returns "==", generating a broken link

Example:

www.website.com/abc%3D%3D/ becomes www.website.com/abc==/ 

Any suggestions on how to solve this issue?

**Comment by bsweeney** [comment]
This does seem potentially problematic. The only work-around I have in mind is to double-encode: `http://www.website.com/abc%253D%253D/`

**Comment by bsweeney** [comment]
The issue appears to be that we're running links through `urldecode`. I'm not sure why this is, the code has been in place for a very long time. I'll review and see if we can address for the next release.
