### ISSUE TITLE
Issue about page break

### ISSUE THREAD

**Issue by ivo75** [dompdf/dompdf#2905]
dompdf version: 1.2.1
PhP: 7.4
charset: utf-8
platform: Wordpress

I have a table with text, with code similar to the one below. The text length is dynamic, thus adding a manual pagebreak in the code is not a solution.

Problem:

In some case the text is broken during pagebreak in the PDF file, and it doesn’t show in the next page (basically it disappear below the margin of the page).

This seems to only occur in some cases, and towards the end of the text. I have 2 theories:

a.It occurs when the text is too long, during the second page break of the table

b.It occurs when the text is longer than 1 page in the PDF file

But it could also be something else

I did a lot of research and thought this could fix the issue:

```	table tr { page-break-before: avoid; }
	table { page-break-inside:avoid; }
	tr { page-break-inside:avoid; }
	div { page-break-inside:avoid; }
```

However it’s not working. Any idea on how to solve the problem?

```
<tr class="toggle-data">
<td>
<table style="width: 100%; border-collapse: collapse;">
<tr>
<td>Content</td>
</tr>
<tr class="space">
<td>
<strong class="toggle-data-heading">content</strong>
<p class="pt10">content</p>
</td>
</tr>

[content]

<tr class="space">
<td>
<h3 class="sub toggle-data-heading">'.$labelicon.' content</h3>
<p class="pt10 mb10">content</p>
<td>
</tr>
</table>
</td>
</tr>
</table>
</td>
</tr>
```

**Comment by bsweeney** [comment]
Would need to see a more complete example to say for sure, but you may just be running into the issue where Dompdf is unable to break an individual table cell across pages (see #98).

For your particular layout example above I don't see any need to use tables at all so you might consider other structural options.
