### ISSUE TITLE
404 Page Not Found (no PDF displayed / downloaded)

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#291]
_Original author: sc0ttkclark (May 20, 2011 19:39:21)_

<b>What steps will reproduce the problem?</b>
1. Open PHP page that uses DOMPDF
2. No errors sent back visually
3. Header 404 is sent to browser
4. Browser shows 404 error though it receives actual PDF data

<b>What is the expected output? What do you see instead?</b>
PDF (either inline or attached)

<b>What version of the product are you using? On what operating system?</b>
0.6.0 beta

<b>Please provide any additional information below.</b>
Browsers effected are Firefox and Chrome, I haven't tested IE

Solution:
I added a header('HTTP/1.1 200 OK'); above the other headers and after the headers_sent() check.

Really NOT sure why it was sending out a 404, but this solved it. I've been chasing this bug for a while now and only just now came across the solution. Hope it helps others.

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=285_

**Comment by fenriz07** [comment]
Thanks Brother!

**Comment by bsweeney** [comment]
@fenriz07 what debug steps have you taken? Tried sending the input back manually (e.g. using `echo $dompdf->output();`)? Tried setting the compress option?

**Comment by isf-informatica** [comment]
Im facing the same issue on making it live on godaddy. How is the issue resolved. I tried all the above. Can someone give me an answer how they overcame the problem.

**Comment by bsweeney** [comment]
@isf-informatica it's impossible to provide any guidance without details relating to your usage. Turn on error logging and either seek help on the support forum or open a new issue with more details report any errors plus a sample of your PHP code.

**Comment by aaryandeveloper** [comment]
what is accesspdf.html 404
