### ISSUE TITLE
Error Message on render() 

### ISSUE THREAD

**Issue by cnsaavedra** [dompdf/dompdf#2928]
**Summary**:
Currently trying to attach a pdf file to a mail, but have problem in creating the PDF.

**Codeblock**:
```
$dompdf = new Dompdf();
$dompdf->loadHtml('hello world');
$dompdf->setPaper('A4', 'landscape');

// the problem lies here
$dompdf->render();
```

**Explanation**:
When I use render(), it outputs an error of:
`preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated 8192`

**Figure: Error Message**
<img width="907" alt="Screen Shot 2022-06-16 at 4 46 56 PM" src="https://user-images.githubusercontent.com/16085208/174160780-f7f861c4-4da5-4d0e-ade0-e4500653b7b3.png">

When I try other methods such as outputHtml(), it creates the html I want which currently I have an output of:
```<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd"> <html><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"></head><body><p>hello world</p></body></html>```

If anyone could please help me understand why I am getting this issue when calling $dompdf->render() despite the fact of being able to output and html?

**Comment by bsweeney** [comment]
What version of PHP and version of Dompdf are you using? Some older versions of Dompdf are not fully compatibility with recent PHP releases. You should be able to resolve the issue by updating to the latest Dompdf release.
