### ISSUE TITLE
Line break issue in a div or p tag 

### ISSUE THREAD

**Issue by Ahmadullahhadem** [dompdf/dompdf#2935]
I have created a page in dompdf but  there is an issue with the page tag that the text inside the p tag or div tag will have a line break in the middle and I have tried many methods of CSS like: inline and other methods but still it did not worked for me. 

below is the code that I have written.

```
<div class="header">
    <div style="text-align: center; width: 100%; background: green; font-size: 10px;">
        <span id="text-start"> Sender's declaration: </span> &nbsp;   This is a long code that needs to be tested to show that it will have a line break in between. still working on this to solve it. 
    </div>
</div>
```

**Comment by bsweeney** [comment]
I don't quite follow your issue. Are you saying there's a problem with a line break or a page break? Can you post an example of the output and describe what you are seeing versus what you expect to see in the output?

**Comment by Ahmadullahhadem** [comment]
I have put above code and there is a line break that it should not be there. just attaching the code output for reference and I want that lines of text to be in one line but still it's showing up on two separate lines. 
![Capture](https://user-images.githubusercontent.com/3850979/175856239-de7b5121-c7fc-42c5-810f-11d255fc627a.JPG)

**Comment by bsweeney** [comment]
I don't see anything that would cause that to happen. We would need to see a more complete example before we could provide any feedback or guidance.
