### ISSUE TITLE
Creating PDF fails

### ISSUE THREAD

**Issue by RainerBielefeld** [dompdf/dompdf#2942]
## My Configuration
* KANBOARD Application version: 1.2.22 on all-inkl.com
* PHP version: 7.4.28
* PHP SAPI: fpm-fcgi
* HTTP Client: cURL
* OS version: Linux 4.15.0-177-generic
* Database driver: mysql
* Database version: 5.7.37-nmm1-log
* [Plugins](https://kanboard.org/plugins.html): [Wiki](https://github.com/funktechno/kanboard-plugin-wiki), [ProjectInvitation](https://github.com/ipunkt/KanboardProjectInvitation), [MarkdownPlus](https://github.com/creecros/MarkdownPlus),**[Task2Pdf](https://github.com/creecros/Task2pdf)** and [Plugin Registration v1.0.8](https://github.com/kanboard/plugin-registration/),  TaskProgressBar
* Browser: **SeaMonkey** (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0)  (does not matter, problem also reproducible with FF and Chromium)

## STR 
0. You need to be logged in as Project member to have access to "Task2PDF" and "Print open Tasks" (to PDF) functions
 So please visit [sample project](https://tickets.kanban.bielefeldundbuss.de/?controller=BoardViewController&action=show&project_id=13), register new account and leave a message here concerning registration.
1. after I have granted Project Member permissions login to my [Test Board(https://tickets.kanban.bielefeldundbuss.de/?controller=BoardViewController&action=show&project_id=13) with your user login.
2. open Task 122 by click on summary "This task causes Problems with Print2PDF"
3. In the column left from Task contents click "Create PDF"
   » Mouse Pointer changes to idle view, nothing happens
   » Expected: Finally PDF will be created
   » Actual: Depending on Browser white page or Error Message [page](https://tickets.kanban.bielefeldundbuss.de/?controller=PrintTaskController&action=printTask&plugin=task2pdf&task_id=122&project_id=13)  appears after ca. 30s 😥

### More or less same problem:
11. After Login switch to Project Board View (if necessary)
12. ˋClick toothed wheel "Configure this Project (top left of page contents) → Print Open Tasksˊ
   » Mouse Pointer changes to idle view, nothing happens
   » Expected: Finally PDF will be created
   » Actual: Depending on Browser white page or Error Message [page](https://tickets.kanban.bielefeldundbuss.de/?controller=PrintTaskController&action=printProject&plugin=task2pdf&project_id=13)  appears after ca. 30s 😥

## Additional info:
a) Error log entry for failure in step 3: "[07-Jul-2022 06:20:53 Europe/Berlin] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /www/htdocs/w0075f62/tickets.kanban.bielefeldundbuss.de/plugins/Task2pdf/vendor/dompdf/dompdf/src/Frame.php on line 596"
b) Error log entry for failure in step 3: "[07-Jul-2022 06:29:18 Europe/Berlin] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /www/htdocs/w0075f62/tickets.kanban.bielefeldundbuss.de/plugins/Task2pdf/vendor/dompdf/dompdf/src/Frame.php on line 571"
c) Problem is confirmed by an other user on a different server
d) Probably related to #2940 here (there oyu find contents of a problem causing KANBOARD task 
e) Probably root of "Task2PDF  Plugin does Nothing. #[20](https://github.com/creecros/Task2pdf/issues/20)"
f) Problem in step (12) also can appear for projects where all single tasks proceed steps (1) ... (3) without any problem.

**Comment by RainerBielefeld** [comment]
### Additional info:
g) I tried with a different project. It took a lot of time (100s or so), but finally PDF became created
g1) few days ago I got error message as per Step (12) for this project after ca. 5 s; if I tried several times I finally got a PDF. In between the project has got some modifications, and I modified Server Memory Settings

**Comment by bsweeney** [comment]
It appears that nesting a large number of (custom) inline elements is the causing the slow-down. I was able to significantly improve rendering time by picking one of those elements randomly (`<thema>`) and styling it as an inline block.

I'm still investigating, but based on what I've found so far your issue might be related to #639.

**Comment by bsweeney** [comment]
Your issue is definitely the same as 639 and is fixed by #2949 which will be included in the 2.0.1. release.
