### ISSUE TITLE
non-wrapping element no longer being moved to next line since 1.2.0

### ISSUE THREAD

**Issue by Elkano** [dompdf/dompdf#2945]
While upgrading DomPDF from 1.0.2 to 2.0.0 I noticed a change in the output that was not easily explained by the general layouting fixes in the newer versions:  
A `<span>` with `white-space: nowrap;` is no longer pushed to the next line even though there isn't enough room for it in the current one. This results in overlapping words in words in a text block styled with `text-align: justify;`.

---

I tried to reproduce this behavior with a minimal code snippet and it turns out that at least `text-align` wasn't the cause, it just changed the way the problem shows.  
Thus I came up with the following HTML:

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>DomPDF error example</title>
<style>
    .base {
        max-width: 18em;
        margin: 1em;
        display: inline-block;
        background: lightgray;
    }
    
    .justify {
        text-align: justify;
    }
</style>
</head>
<body>
<div class="base">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</div>
<div class="base">
    Lorem ipsum dolor sit amet, consectetur <span style="white-space: nowrap;">adipiscing elit,</span> sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</div>
<br>
<div class="base justify">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</div>
<div class="base justify">
    Lorem ipsum dolor sit amet, consectetur <span style="white-space: nowrap;">adipiscing elit,</span> sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</div>
</body>
</html>
```

Result with 2.0.0: (https://eclecticgeek.com/dompdf/debug.php?identifier=745caa4d60181c69946eede60b0d17ab)  
![image](https://user-images.githubusercontent.com/965706/177963571-5a847966-0d3d-4a20-bbfb-022af3b6281d.png)  
As one can see, the `<span>` is output in the first line of text even though (by chance) none of its words are when not wrapping them in the span.

On 1.0.2 however, the right text looked exactly like the left one (https://eclecticgeek.com/dompdf/debug.php?identifier=f59b1dbd6b5cbe8981e9a3c7515a494f).  
I'm aware that them matching is also a result of none of the words fitting the first line even without `nowrap` and not the generic expected result.

---

As there have been multiple releases between 1.0.2 and 2.0.0 I narrowed the initial occurrence of the problem to version 1.2.0 and from there to commit 99eeb28df349d6ab3b20e6e939f879700ad9e158.

**Comment by bsweeney** [comment]
Thank you for the detailed research into the problem. Should help greatly in resolving the issue.

**Comment by Mellthas** [comment]
Yes, thanks for the detailed report! Should be handled by #2948.
