### ISSUE TITLE

Add a functional test that compares generated PDF outputs

### ISSUE THREAD

**Issue by JohJohan** [dompdf/dompdf#2952]
Add a functional test that compares generated PDF outputs

Is it an idea to add a functional test that will compare Data Fixture PDF files with newly generated PDF files? That way we can check what kind of an impact a change will have.

We can use something like php-imagick extension. I already do this for my work projects. If a change is detected the test fails and it will write an image with the differences so you can see what is different between the 2 PDF files.

Let me know if we want something like that. I can create a pull request for this.

**Comment by bsweeney** [comment]
Have you looked at #2510?
