### ISSUE TITLE
Many Information in PDF Report/ Archivo PDF no se genera con mucha información

### ISSUE THREAD

**Issue by AlexisRamirezHernandez** [dompdf/dompdf#2958]
Hi guys! I've a trouble with this library in my laravel proyect. 
I need to process almost 5000 registers of my database and present a report in pdf but the trouble happens with i generated my report broken because it has many information, I try others libraries and the result it's same and I try to increment memory to 512 mb to 2048 mb but it's not the problem. Any Sugeration? When I've few register for example 100 not problem.
¡Hola chicos! Tengo un problema con esta biblioteca en mi proyecto laravel.
Necesito procesar casi 5000 registros de mi base de datos y presentar un informe en pdf pero el problema es que generé mi informe porque se romperá porque tiene mucha información, pruebo otras bibliotecas y el resultado es el mismo y trato de incrementar la memoria a 512 mb a 2048 mb pero ese no es el problema. ¿Alguna Sugerencia? PD: Cuando tengo pocos registros no hay problema

**Comment by bsweeney** [comment]
If you are able to do so you'll probably have success breaking the render into multiple, smaller documents with 100 records each. After the PDFs are generated you can combine them into a single PDF using a library like FPDF+FPDI.

**Comment by RaulAcevedoF** [comment]
Hi Alexis! I have the same problem, but after search y prefer use Laravel Excel ! You can visit  their website at this link https://laravel-excel.com/    💯 👍🏼

**Comment by AlexisRamirezHernandez** [comment]
Thank you @bsweeney   I try it and it doesn't fix but @RaulAcevedoF  should  be try Laravel Excel and this appear my unique option :( Thank You Guys!
