### ISSUE TITLE
Chinese and Japanese characters are not displayed

### ISSUE THREAD

**Issue by mcolominas** [dompdf/dompdf#2959]
I am using the DejaVu Sans font, it shows the Latin, Russian and Arabic characters without problems, but the Chinese and Japanese theme does not show them, the strange thing is that it does not show any rectangle or ?, they are simply transparent, I started looking that character using the browser's search engine and I found it.

![PDF Capture](https://user-images.githubusercontent.com/32141081/179511115-c01aa390-e66e-48fe-88db-5600ca4b3358.PNG)
![PDF Capture](https://user-images.githubusercontent.com/32141081/179511379-6c9bb252-c0d1-490d-86fe-011501666a3b.PNG)

Does anyone know what it could be due to?

**Comment by bsweeney** [comment]
DejaVu fonts do not support CJK characters. You'll have to install a separate font.

Question marks would only be used if the underlying font encoding didn't support the characters (e.g. Windows ANSI for the core fonts). The missing "unknown glyph" character looks to be missing when generating a font subset.

**Comment by mcolominas** [comment]
Ok thank you very much for the information, so until they put the unicode-range I will have to review that character and put some class or style inline to change the font of a specific element.

The only characters that this font does not include are Chinese, Japanese, and Korean or is there any more?

**Comment by bsweeney** [comment]
You can see the full list of supported characters for the variants in the DejaVu font family here: https://dejavu-fonts.github.io/Samples.html
