### ISSUE TITLE
Error displaying image.  Any solution?

### ISSUE THREAD

**Issue by zlukasmoura** [dompdf/dompdf#2966]
![image](https://user-images.githubusercontent.com/33609119/181524035-fa91cc08-ee95-4931-8229-4e23158e7d91.png)
![image](https://user-images.githubusercontent.com/33609119/181524183-2b3776bc-c49c-498f-a43b-2efd8fca2d27.png)

**Comment by bsweeney** [comment]
Have you allowed remote files (set isRemoteEnabled to true)? I know "localhost" is not a remote URL but as far as Dompdf is concerned anything accessed over HTTP is remote.

**Comment by Ajility97** [comment]
@bsweeney I'm using laravel-dompdf wrapper (dompdf 1.2.2) and having the same issue.

Offending line:
`<img class="{{ $logo->class }}" src="{{ $logo->url }}" alt="logo"/>`

Result:
![image](https://user-images.githubusercontent.com/68575573/182420362-fcb34ce4-d1bd-4fc1-b505-3e29e7589d6d.png)

config/dompdf.php:
`'enable_remote' => true`

`$logo->url` is a temporary URL to a JPG image in AWS S3. It looks something like this:
`https://bucketname.s3.amazonaws.com/10/400px.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA3REDACTEDTHIS%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220802T160626Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86400&X-Amz-Signature=REDACTEDTHIS`

It works fine in my local environment, but fails in our staging environment, don't see anything in the PHP log. I'm having trouble finding out why.

Things I've confirmed about the staging environment:
- The temporary directory is writeable by the webserver process.
- `gd` extension is enabled
- `allow_url_fopen` is true
- Environment uses a wildcard SSL certificate

**Comment by bsweeney** [comment]
Sounds like you've done the basics with regard to trouble-shooting. I don't have any additional thoughts off the top of my head. You might try enabling additional debugging ([debug configuration in the wiki](https://github.com/dompdf/dompdf/wiki/Debugging-Dompdf)).

**Comment by Ajility97** [comment]
As a note to anyone who runs into this, my work-around was to base64 encode the image. No issues that way, and I default to a local image on error:

```
...
    private function getLogoTemporaryUrl(): string
    {
        return $this->logo?->getTemporaryUrl(now()->addMinutes(15)) ?? public_path('images/error-image.png');
    }

    public function getLogoBase64(): ?string
    {
        $mimeType = $this->logo?->mime_type ?? 'image/png';

        return 'data:' . $mimeType . ';base64, ' . base64_encode(
            file_get_contents($this->getLogoTemporaryUrl())
        );
    }
...
```

**Comment by bsweeney** [comment]
@Ajility97 yeah that is definitely one way around the issue. Sorry I didn't have any better advice on what was causing problems fetching the image.
