### ISSUE TITLE
fopen(/home/insitmrx/dail.ng/naira/storage/fonts/nunito_normal_f8ce9593f0c56e52776379aa29b2d690.ufm): Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by Temian1** [dompdf/dompdf#2969]
when i try downloading pdf got this error

`fopen(/home/insitmrx/dailypay.ng/nairawave/storage/fonts/nunito_normal_f8ce9593f0c56e52776379aa29b2d690.ufm): Failed to open stream: No such file or directory`

**Comment by bsweeney** [comment]
Is that path valid for your Dompdf installation? How was the font installed (`@font-face` would be the typical method)? Possible that the storage directory was cleared at some point?

**Comment by Tadaz** [comment]
Just had the same issue and it took me a couple of hours to realise that path to fonts must exist (in my case storage/fonts). After creating fonts dir inside storage it started working.
