### ISSUE TITLE
[Question] Seeting up Pages and a Footer

### ISSUE THREAD

**Issue by mimmi20** [dompdf/dompdf#2982]
We want to create a document with several pages. We want to define which content in which page, and we want to set up a footer for all pages.

Is it possible to do this with dompdf? How do i set this up?

**Comment by bsweeney** [comment]
I think I'm going to need to know a bit more about the specific layout. You can isolate content on pages using page-break styling. If the footer is the same on all pages that's fairly straightforward. If it needs to be different depending on the content that's a bit more of a challenge.

**Comment by mimmi20** [comment]
Currently we are using [spipu/html2pdf](https://github.com/spipu/html2pdf), but the author dont want to maintain it longer ([see](https://github.com/spipu/html2pdf/issues/680)). Now we are searching a replacement.

Our template for the html is something like this:
```html
<style></style>
<page>
    <page_footer>
    <!-- some html to be in the footer>
    </page_footer>
    <!-- some html to be in the page>
</page>
<page>
    <page_footer>
    <!-- some html to be in the footer>
    </page_footer>
    <!-- some html to be in the page>
</page>
```

If possible, we want to define the content for each page.

**Comment by bsweeney** [comment]
That should be doable. If your `<page>` element entirely defines the content of a single page, then you can style the `<page_footer>` element absolutely to have it render out of the normal document flow at the position specified and only on the current page.
