### ISSUE TITLE
libpng warning: Interlace handling should be turned on when using png_read_image

### ISSUE THREAD

**Issue by bastien70** [dompdf/dompdf#2983]
Hello, I created a command to generate pdf (with Twig template) which I store locally.
In this PDF, there is an image, from my assets, and included in base64, like this :

```twig
<img src="{{ base64('build/app/images/logo.png') }}" alt="Logo">
```

It works, but I see the following warning : **libpng warning: Interlace handling should be turned on when using png_read_image**
Is it normal ? How can I fix it ?

Thank you !

**Comment by bsweeney** [comment]
I believe this would happen if the source image is interlaced? Per google there may also be bugs in some versions of the underlying software. First thing to try would be to confirm if the image is interlaced and, if it is, save it as non-interlaced.
