### ISSUE TITLE
Problem with custom Avenir Font starting from version 0.8.6

### ISSUE THREAD

**Issue by tgsjames** [dompdf/dompdf#2987]
I'm trying to troubleshoot an issue which seems to have started from version 0.8.6 where a custom font (Avenir_medium.ttf) is incorrectly displayed with odd characters instead of spaces. This is working fine on 0.8.5.

Fonts are included using:

`@font-face {
	font-family: Avenir-medium;
	src: local('Avenir-medium'), url('https://path-to-cdn/Avenir_medium.ttf');
}`

And then set via CSS using:
`body {
	font-family: Avenir-medium, sans-serif !important;
	letter-spacing: -0.25px;
}`

The text is showing in the PDF as:
<img width="138" alt="Screenshot 2022-08-21 at 20 17 51" src="https://user-images.githubusercontent.com/58995913/185807328-8883be17-0588-48fa-88f0-8560e3a55f69.png">

The bolder font Avenir_heavy is not affected, its only Avenir_medium that has the issue.

Any suggestions?

Thanks

**Comment by bsweeney** [comment]
That works but is not necessarily the best resolution. Depending on the font the size of the PDF can significantly increase when you disable font subsetting. Incorrect glyph display with font subsetting has been reported in the past. I've found related discussion but am not finding an issue (that I'm pretty sure exists).
