### ISSUE TITLE
Including Helvetica Neue font over url in css

### ISSUE THREAD

**Issue by T-D3V** [dompdf/dompdf#2989]
So I have a project and we'd like to use the helvetica Neue font in the pdf's but now if I try to get it over the url in the pdf it doesn't work.

![image](https://user-images.githubusercontent.com/40610605/186383974-4034c75f-96b5-4825-b209-eb70a5b168ee.png)

This is just the base scss file where it is and gets used by every other styling file.
Now this whole thing works like a charm if I just echo the html, but If i try to generate a pdf it won't accept the font.
other things I include over url like stylefiles and imgs work but the font in the css just won't work.

FYI if you are asking yourself why am I using urls well cause local paths even with chroot defined doesn't work.

I am using version 2.0.

**Comment by bsweeney** [comment]
The format string for the TrueType version should be "truetype" instead of "ttf".

I was not asking myself why you weren't using a local path, though I'm happy to help you try and figure that out as well.

**Comment by T-D3V** [comment]
Well that was it thank you so much, had to fix it and since it worked before I assumed this wasn't the issue but it sure is, for the local paths issue I might come back to that when I've got more time but anyways thx for the help.
