### ISSUE TITLE
Bangladeshi taka (৳) symbol rendered as question mark

### ISSUE THREAD

**Issue by pankaj-infyom** [dompdf/dompdf#2993]

**Comment by nazmulhaquep** [comment]
> Below code is working for me to display taka sign in dompdf package "barryvdh/laravel-dompdf": "^3.0",.

`<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Bengali&display=swap" rel="stylesheet">

<style>

body {
font-family: 'sorob',sans-serif;
} 

* {
font-family: 'sorob',sans-serif;
}

@page {
size: A4;
margin: 0;
}
</style>
</head>
<body>
<table>
<thead>
        <tr>
            <td class="text-bold"> SL </td>
            <td class="text-bold"> Item Name </td>
            <td class="text-bold"> Qty </td>
            <td class="text-bold"> Unit Price </td>
            <td class="text-bold"> Total Price </td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>Surgical Gloves</td>
            <td>2</td>
            <td> <span style="font-family: 'Noto Sans Bengali', sans-serif;">&#x09F3;</span> 900 </td>
            <td> <span style="font-family: 'Noto Sans Bengali', sans-serif;">&#x09F3;</span> 180 </td>
        </tr>
    </tbody>
</table>
</body>
</html>
`

**Comment by nazmulhaquep** [comment]
![Image](https://github.com/user-attachments/assets/e3064f90-7e47-402a-9cc3-3a84149ecc34)

Below code is working for me to display taka sign in dompdf package "barryvdh/laravel-dompdf": "^3.0",.

**Comment by nazmulhaquep** [comment]
![Image](https://github.com/user-attachments/assets/8ebb32fe-ad94-424e-bb5c-673cf4cf9dfa)

Above code is working for me to display taka sign in dompdf package "barryvdh/laravel-dompdf": "^3.0",.

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Bengali&display=swap" rel="stylesheet">

<style>

body {
font-family: 'sorob',sans-serif;
} 

* {
font-family: 'sorob',sans-serif;
}

@page {
size: A4;
margin: 0;
}
</style>
</head>
<body>
<table>
<thead>
        <tr>
            <td class="text-bold"> SL </td>
            <td class="text-bold"> Item Name </td>
            <td class="text-bold"> Qty </td>
            <td class="text-bold"> Unit Price </td>
            <td class="text-bold"> Total Price </td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>Surgical Gloves</td>
            <td>2</td>
            <td> <span style="font-family: 'Noto Sans Bengali', sans-serif;">&#x09F3;</span> 900 </td>
            <td> <span style="font-family: 'Noto Sans Bengali', sans-serif;">&#x09F3;</span> 180 </td>
        </tr>
    </tbody>
</table>
</body>
</html>
