### ISSUE TITLE
PHP 8, last dompdf version issue

### ISSUE THREAD

**Issue by robertaonnis** [dompdf/dompdf#3000]
function: Dompdf\Renderer\Inline->render()

the program stop here :
dompdf/vendor/dompdf/dompdf/src/Renderer/Inline.php:153

and the issue is: 0 - Unsupported operand types: string + float
could you help me?

**Comment by bsweeney** [comment]
When you say "last dompdf version" to which version are you referring?

**Comment by robertaonnis** [comment]
Sorry maybe is my issue,
i have see now that the composer download me 0.8.3.

I don't understand why

**Comment by bsweeney** [comment]
I was thinking it was an older version. I'm not sure why, either, though it could be a dependency issue.

**Comment by robertaonnis** [comment]
maybe is my issue it continue to download me 0.8.3
i check better why

**Comment by robertaonnis** [comment]
I confirm was my issue. I Sorry fo this.
Thanks

**Comment by bsweeney** [comment]
No worries. Glad you were able to figure it out.
