### ISSUE TITLE
how to Line break and move text in new page

### ISSUE THREAD

**Issue by kipurvesh098** [dompdf/dompdf#3008]
My table is too long, that's why the will page break. But I want to keep the table border before the page break. Is that any solution?

![image](https://user-images.githubusercontent.com/77538311/190891243-b8e70d75-125f-4e97-89d8-ea8e67557676.png)

**Comment by bsweeney** [comment]
Dompdf is currently unable to break a table cells across pages (see #98). The only mechanism to support this, right now, is iIf you can modify your structure so that no single table cell is larger than the page.
