### ISSUE TITLE
Failed to open stream on installed-fonts.json

### ISSUE THREAD

**Issue by HeadStudios** [dompdf/dompdf#3009]
Not sure why this is happening as it was working before - suspect the installed-fonts.json font got overwritten and maybe there's some issue who knows - I wrote about this on a Reddit post:
https://www.reddit.com/r/laravel/comments/xhghdw/installed_fonts_json_permissions_dompdf_and_git/

But.... yeh you get the idea. - basically getting this error:
[2022-09-18 13:12:29] production.ERROR: file_put_contents(/home/forge/rrdevours.monster/storage/fonts/installed-fonts.json): Failed to open stream: Permission denied {"exception":"[object] (ErrorException(code: 0): file_put_contents(/home/forge/rrdevours.monster/storage/fonts/installed-fonts.json): Failed to open stream: Permission denied at /home/forge/rrdevours.monster/vendor/dompdf/dompdf/src/FontMetrics.php:101)

Permission denied? What's going on let me check the file one sec
`{
    "roboto": {
        "normal": "roboto_normal_3ef16c3fc239e05137df2565b4634870"
    },
    "mont-bold": {
        "normal": "mont_bold_normal_00bf941265e00529c66828d5343381dc"
    },
    "mont-regular": {
        "normal": "mont_regular_normal_6c6e388373964314400cc7aba4d2a9be"
    },
    "opensans": {
        "normal": "opensans_normal_2efebbd87ddc7bcf1123fea04b4bc76b"
    },
    "montserrat": {
        "normal": "montserrat_normal_2efebbd87ddc7bcf1123fea04b4bc76b"
    }
}`

That's the code in there.. you reckon if I change permissions on the file it'll work? Any idea is it a chmod - what number? Or someone on Reddit was saying it's the server user who knows.

**Comment by bsweeney** [comment]
That installed-fonts.json file would be created on the first run when you specify custom fonts. If you copy that file from one system to another it's possible that the permissions on the file aren't configured to allow write access. If it was running fine on the same system previously and just ... stopped? ... could be that something about the system configuration changed.

One thing you can try, if your `@font-face` declarations are working correctly is to delete or rename that file. It should be regenerated next time you run.

**Comment by HeadStudios** [comment]
> That installed-fonts.json file would be created on the first run when you specify custom fonts. If you copy that file from one system to another it's possible that the permissions on the file aren't configured to allow write access. If it was running fine on the same system previously and just ... stopped? ... could be that something about the system configuration changed.
> 
> One thing you can try, if your `@font-face` declarations are working correctly is to delete or rename that file. It should be regenerated next time you run.

Yep.. so file access system is what it was - I went and did a chown for both columns and it's working beautifully now :) - man my contract is starting to look so sexy I love it... thank you for your quick response btw and I'm closing this as this issue is closed.
