### ISSUE TITLE
Image not found or type unknown after PHP upgrade

### ISSUE THREAD

**Issue by adeyjones** [dompdf/dompdf#3011]
Hi, have used DomPDF for years now to create invoices for clients, but this morning I updated it to the latest version after a PHP upgrade to 8.1 and the background image on my PDF will no longer display.
I can confirm that the path is right because a) the file has not moved and b) when I echo my $output HTML the image loads fine, but when I revert back to DomPDF I get "Image not found or type unknown".
I can also confirm allow_url_fopen is enabled on PHP8.1 and isRemoteEnabled is set to true in the options.

This is what I have at the end of my invoice.php file:
```
    $pdf = new Pdf();
    $file_name = $practicecode.'-'.$invoiceno.'.pdf';
    $pdf->setPaper('A4', 'portrait');
    $pdf->loadHtml($output);
    $pdf->render();
    $pdf->stream($file_name, array("Attachment"=>false));
```

**Comment by bsweeney** [comment]
Can you provide a sample of the URL? It's possible that some of the additional security measures added in recent versions may be the cause. You can also try [enabling extra debug logs](https://github.com/dompdf/dompdf/wiki/Debugging-Dompdf) to try and determine why it's failing.

**Comment by adeyjones** [comment]
Unfortunately i'm unable to provide URL because it's live account data and it is also password protected.

I've tried enabling the extra debug logs but when I load the URL, it opens the PDF window but is empty (doesn't render anything) - where is the error log file saved?

This is what is now at the bottom of my invoice.php file:

    ini_set("display_errors", true);
ini_set("error_log", "phperr.log");
ini_set("log_errors", true);
error_reporting(E_ALL);

$_dompdf_show_warnings = true; // record warnings generated by Dompdf
$_dompdf_debug = false; // output frame details for every frame in the document
$_DOMPDF_DEBUG_TYPES = [
    'page-break' => false // record information about page break determination
];

    $pdf = new Pdf([
    "logOutputFile" => "log.html",
    "debugPng" => false, // extra messaging
    "debugKeepTemp" => false, // don't delete temp files
    'debugCss' => false, // output Style parsing information and frame details for every frame in the document
    'debugLayout' => false, // draw boxes around frames
    'debugLayoutLines' => false, // line boxes
    'debugLayoutBlocks' => false, // block frames
    'debugLayoutInline' => false, // inline frames
    'debugLayoutPaddingBox' => false // padding box
]);
    $file_name = $practicecode.'-'.$invoiceno.'.pdf';
    $pdf->setPaper('A4', 'portrait');
    $pdf->loadHtml($output);
    $pdf->render();
    $pdf->stream($file_name, array("Attachment"=>false));

**Comment by adeyjones** [comment]
If I remember right I paid someone to install this for me because I didn't have a clue how, and that's just the variable that he used. The top of my invoice.php has `require_once 'pdf.php';` and in pdf.php is:
```
require_once 'dompdf/autoload.inc.php';
use Dompdf\Dompdf;
class Pdf extends Dompdf{
    public function __construct() {
        parent::__construct();
    }
}
```

so i'm guessing that's where the `new Pdf()` comes in?

The image is hosted in an 'images' directory within the password protected directory, yes, but that's never been an issue. The directory is password protected using .htaccess and .htpasswd

**Comment by bsweeney** [comment]
Could be that requests from local IP are allowed, but I couldn't say for sure since I don't know the details of the configuration. If it's actually password protected you would need to add a context specifying the password.

Also, redirects are no longer followed so if that happens as part of image load (even just HTTP to HTTPS) you'd also have to specify that redirects are allowed.

I'm ... not sure what's going on with pdf.php there. Is that the entirety of it? Could be that he just wanted to make it a one-liner for you to use. Since you're referencing the Dompdf autoloader I assume you're using the download version and not Composer. He's not passing through the constructor argument so you'd have to set your options differently. Oh, and be sure to specify any other options as well (such as isRemoteEnabled). Something like the following:

```
$pdf = new Pdf();
$pdf->setOptions(new Dompdf\Options([
    // runtime options
    "isRemoteEnabled" => true,

    // debug options
    "logOutputFile" => "log.html",
    "debugPng" => false, // extra messaging
    "debugKeepTemp" => false, // don't delete temp files
    'debugCss' => false, // output Style parsing information and frame details for every frame in the document
    'debugLayout' => false, // draw boxes around frames
    'debugLayoutLines' => false, // line boxes
    'debugLayoutBlocks' => false, // block frames
    'debugLayoutInline' => false, // inline frames
    'debugLayoutPaddingBox' => false // padding box
]));
```

**Comment by adeyjones** [comment]
Perfect thank you, so I have put that in and it ran OK, the PDF downloaded (albeit without background image), and a log file was saved.

The log file contains:
`file_get_contents(https://xxxxxxxxx/clients/images/image-name.png): Failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized Image not found https://xxxxxxxxx/clients/images/image-name.png`

This suggests to me that it is an issue with the password protecting. Out of interest, I emptied .htaccess and ran it again, the PDF downloaded again and this time the image loaded fine. Unfortunately I can't not password protect this system as the database contains many details and accounts for around 250 businesses I look after.

Is this something that's been amended in the DomPDF update? As this has never been an issue before. Next question, how do we get round this haha

And thanks so much for your time and help thus far.

**Comment by bsweeney** [comment]
Progress!

We didn't really change anything that would impact how password-protected resources would be accessed. I don't know if there's something specific in your htaccess to allow Dompdf, but we did change like the user agent and some other minor things.

As for how to fix ... you're in luck: https://github.com/dompdf/dompdf/wiki/Common-Use-Cases#custom-http-stream-context

**Comment by adeyjones** [comment]
I've taken the chickens way out and just moved the image to another directory that is not password protected, but I appreciate all yours efforts in helping me today, and thanks agin for your time.
Have a great day.

**Comment by bsweeney** [comment]
Glad you were able to come to some resolution, even if it's not ideal. The stream context configuration is not too challenging, but I understand wanting to move on. If you give it a try in the future and need some guidance I'm happy to type words.

**Comment by afonseca69** [comment]
> Perfect thank you, so I have put that in and it ran OK, the PDF downloaded (albeit without background image), and a log file was saved.
> 
> The log file contains: `file_get_contents(https://xxxxxxxxx/clients/images/image-name.png): Failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized Image not found https://xxxxxxxxx/clients/images/image-name.png`
> 
> This suggests to me that it is an issue with the password protecting. Out of interest, I emptied .htaccess and ran it again, the PDF downloaded again and this time the image loaded fine. Unfortunately I can't not password protect this system as the database contains many details and accounts for around 250 businesses I look after.
> 
> Is this something that's been amended in the DomPDF update? As this has never been an issue before. Next question, how do we get round this haha
> 
> And thanks so much for your time and help thus far.

I have the same issue. 
My log file returned
<span style='color: #000' title='Frames'>   150</span><span style='color: #009' title='Memory'>  14336.00 KB</span><span style='color: #900' title='Time'>     55.14 ms</span><span  title='Quirksmode'>  <span style='color: #0d0'>OFF</span></span><br />

This code is not in my php file

**Comment by afonseca69** [comment]
My log file returned
"<span style='color: #000' title='Frames'>   150</span><span style='color: #009' title='Memory'>  14336.00 KB</span><span style='color: #900' title='Time'>     55.14 ms</span><span  title='Quirksmode'>  <span style='color: #0d0'>OFF</span></span><br />"

**Comment by bsweeney** [comment]
@afonseca69 this seems like an unrelated issue. You should start a [new discussion](https://github.com/dompdf/dompdf/discussions/new/choose) to determine if there's a bug or you just need some configuration help. That being said, the text you quoted looks like the log data produced by Dompdf. If you're not using the latest release just disable the log file (via #2810):

```
$dompdf = new Dompdf([logOutputFile => '']);
```

**Comment by afonseca69** [comment]
Thank you, I was not using a log file, I started to use, to try to solve the image trouble.

In phg 7.3 dompdf2 is ok. In php 8.1 the image doesn't appear.



Atenciosamente,


[SoftServ Sistemas]<http://www.softserv.com.br/>[Google+]<https://plus.google.com/+SoftservBr1994> [Curta nossa pÃ¡gina] <https://www.facebook.com/softservsistemas/>  [Conecte-se ao Linkedin] <https://www.linkedin.com/company/softserv-sistemas>  [Siga-nos no Twitter] <https://twitter.com/softserv1994>  [Siga-nos no Instagram] <https://www.instagram.com/softservsistemas>  [Inscreva-se em nosso canal] <http://www.youtube.com/c/SoftservBr1994>    André Fonseca
Pesquisa e Desenvolvimento
Suporte
skype.softserv
(11) 3995 5200
(21) 3195 5200
(31) 3195 5200
(41) 3195 5200
(51) 3195 5200

Comercial
0800 727 2099
Ligação gratuita
São Paulo
Rio de Janeiro
Minas Gerais
Paraná
Rio Grande do Sul


Brasil
[Veja no ***@***.***,-43.271048,17z/data=!4m5!1m2!2m1!1ssoftserv!3m1!1s0x0000000000000000:0xa22666f336c06271?hl=pt-BR>    Sede
Av. Pastor Martin Luther King Jr. 126 Office 2000 Sala 226,
Shopping Nova América, Rio de janeiro - RJ, 20765-971   [http://softserv.com.br/email/assinatura/PENSE_IMPRIMIR.gif]
________________________________



________________________________
De: Brian Sweeney ***@***.***>
Enviado: quinta-feira, 19 de janeiro de 2023 19:32
Para: dompdf/dompdf ***@***.***>
Cc: Andre Fonseca ***@***.***>; Mention ***@***.***>
Assunto: Re: [dompdf/dompdf] Image not found or type unknown after PHP upgrade (Issue #3011)


@afonseca69<https://github.com/afonseca69> this seems like an unrelated issue. You should start a new discussion<https://github.com/dompdf/dompdf/discussions/new/choose> to determine if there's a bug or you just need some configuration help. That being said, the text you quoted looks like the log data produced by Dompdf. If you're not using the latest release just disable the log file (via #2810<https://github.com/dompdf/dompdf/issues/2810>):

$dompdf = new Dompdf([logOutputFile => '']);
