### ISSUE TITLE
Bad link on 2.0.1 release page

### ISSUE THREAD

**Issue by kaamui** [dompdf/dompdf#3012]
Hello,

First of all thank you for your great work. 

On the [releases page](https://github.com/dompdf/dompdf/releases) :

> The list of addressed issues can be found in the [2.0.1](https://github.com/dompdf/dompdf/milestone/25?closed=1) release milestone.

The link ([2.0.1](https://github.com/dompdf/dompdf/milestone/25?closed=1)) is not the good one.

the good one => https://github.com/dompdf/dompdf/milestone/20?closed=1

**Comment by bsweeney** [comment]
Whoops! Thanks for the heads up. Fixed.

I also realized I forgot to upload the packaged release. Also done.
