### ISSUE TITLE
Font Loading Version 2.0.1

### ISSUE THREAD

**Issue by joworeiter** [dompdf/dompdf#3014]
After Updating from 2.0.0 to 2.0.1 the font loading seems to be broken. 
I'm using Raleway, hosted on my site with `@font-face` to loading. See code below.
After investigation, sadly I couldn't find the issue, so I rolled back to v 2.0.0. and the fonts are workting again.

```
@font-face {
  font-family: "raleway";
  font-style: normal;
  font-weight: 400;
  src: url("https://xxx/fileadmin/templates/fonts/Raleway-Regular.ttf") format('truetype');
}

@font-face {
    font-family: "raleway";
    font-style: normal;
    font-weight: bold;
    src: url("https://xxx/fileadmin/templates/fonts/Raleway-Bold.ttf") format('truetype');
}
```

**Comment by bsweeney** [comment]
Do you get any errors related to loading the font? The change related to font loading was to return if validation failed. Is validation of your URL failing? For example, have you set `isRemoteEnabled => true` in your Options?

**Comment by joworeiter** [comment]
As far as I could debug, the font gets loaded but not packed into the pdf. 
Setting the `isRemoteEnable => true` Option hasn't worked for me.

**Comment by C0C45** [comment]
The same happened to me

**Comment by bsweeney** [comment]
Would like to identify the cause but I'll need more info.

@C0C45 are you also loading a font from your own system? Do you have a sample of the relevant CSS?

**Comment by joworeiter** [comment]
> Would like to identify the cause but I'll need more info.
> 
> @C0C45 are you also loading a font from your own system? Do you have a sample of the relevant CSS?

@bsweeney I'll try to get a whole debug log tomorrow, had lunch-day today, so I wasn't able to investigate further on the issue

**Comment by C0C45** [comment]
I will try get more information.

CSS:

@font-face {
            font-family: 'Calibri';
            font-weight: normal;
            font-style: normal;
            font-variant: normal;
            src: url("Calibri.ttf") format("truetype");
        }

        @font-face {
            font-family: 'Calibri';
            font-weight: bold;
            font-style: normal;
            font-variant: normal;
            src: url("Calibrib.ttf") format("truetype");
        }

Thanks

**Comment by bsweeney** [comment]
Any more information to help determine what's going on here?

**Comment by joworeiter** [comment]
@bsweeney finally I found the wrong peace of code. 
I tried `isRemoteEnabled(true)` to set the option acutally `setIsRemoteEnabled(true)` has to be called. Works again.

**Comment by bsweeney** [comment]
Ah sorry about that. Yes to set the option individually that's the function (`$options->setIsRemoteEnabled(true)`). isRemoteEnabled is the name of the option (`$options = new Options(['isRemoteEnabled' => true])`).
