### ISSUE TITLE
Is there any limitation for dom-pdf 2.0.0?

### ISSUE THREAD

**Issue by watanove** [dompdf/dompdf#3018]
Hi,

I use dom-pdf2.0.0 on ubuntu 20.04.
I want to output to pdf File,is paged about 100.

Is there any limitation for dom-pdf2.0.0?
For example ,amount of HTML or amount ofCSS?

Sincerely

**Comment by bsweeney** [comment]
There is no limitation except for the resources available on your system. 100 pages may take a while, depending on the nature of the content, so you want to make sure PHP is configured for sufficient memory and execution time.

**Comment by watanove** [comment]
Thank you!
