### ISSUE TITLE
Uninitialized string offset 22

### ISSUE THREAD

**Issue by jochemgruter** [dompdf/dompdf#3019]
Got the error `Uninitialized string offset 22 ` on file vendor/dompdf/dompdf/src/Css/Stylesheet.php:772

When i add the following code above `switch ($tok[$j]) { ` then the problem is solved.
                    
      if (!isset($tok[$j])) {
              break;
      }

**Comment by jochemgruter** [comment]
[app.css.txt](https://github.com/dompdf/dompdf/files/9718885/app.css.txt)

This is the css file I use, to reproduce.

**Comment by bsweeney** [comment]
Looks like there's an issue parsing CSS that uses variable-like syntax in the class name. The following from your stylesheet triggers the error.

```
.w-\[var\(--sidebar-width\)\]{width:var(--sidebar-width)}
```

That doesn't appear to be an actual CSS variable but a CSS variable used as a class name? I dunno it just looks weird.

**Comment by bsweeney** [comment]
FYI, Dompdf doesn't yet support CSS variables (#1872), which your stylesheet appears to use heavily. There's a lot to parse so I didn't look to see if there's sufficient fallback styling.
