### ISSUE TITLE
include custom font in dompdf

### ISSUE THREAD

**Issue by ballotade** [dompdf/dompdf#3023]
Hello,

how can I include a custom font with css in dompdf.

I tried this:
`@font-face {
	font-family: Questrial;
	src: url("Questrial-Regular.ttf");
	font-weight: normal;
    font-style: normal;
}`

It worked with dompdf 0.8
But with the newest version (I think it is version 2.0) it does not work.

Can I include it with base64?

Thanks for your ideas. :)

**Comment by bsweeney** [comment]
Moved to discussion (#3025).
