### ISSUE TITLE
External fonts with a space in their names are not being loaded

### ISSUE THREAD

**Issue by Tadaz** [dompdf/dompdf#3026]
A popular [_Roboto Condensed_ ](https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400) font will not be loaded with this library because it has a white space in its name. However, its sibling font _Roboto_ will be loaded just fine.

Some people already have had this issue for years and they use [this workaround](https://stackoverflow.com/a/44741404/3088867).

My test snippet (works fine if I change the font family name to "Roboto":
```
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700" rel="stylesheet">

<style>
    body,
    body > * {
        font-family: "Roboto Condensed", cursive;
    }
</style>
```

Furthermore, I can see that both fonts are being downloaded to my fonts directory.

**Comment by Tadaz** [comment]
Apparently, I just needed to adjust _font-weight_ attribute and it started working. Apologies for raising this issue.

**Comment by bsweeney** [comment]
Glad you were able to address your issue. There are some problems parsing URLs that have certain characters in them. I'm currently working on an update to the this in relation to #2054.
