### ISSUE TITLE
Increase maximum PDF size

### ISSUE THREAD

**Issue by glauberdeyvisonjs** [dompdf/dompdf#3042]
Sometimes when returning a very large PDF I get the response "no body returned for response" in imsomnia. Is there any way to increase the maximum size of the PDF? I implement the PDF in Laravel, and use Foreach in the blade for each record, sometimes generating large PDF's.
![large pdf](https://user-images.githubusercontent.com/40475228/198286479-60f1c4da-26e1-489c-b348-300c39aabeaf.png)

**Comment by bsweeney** [comment]
This wouldn't necessarily be a Dompdf issue since there are no inherit limits on PDF size. The issue is likely system resource exhaustion. You'll either want to increase the allowed execution time or the memory limit, whichever is causing script execution to end early (thus the 500 error).

**Comment by ekazda** [comment]
@glauberdeyvisonjs Did you ever resolve this issue? I'm experiencing a similar problem (or at least I think I am) and researching a possible solution.

**Comment by glauberdeyvisonjs** [comment]
> @glauberdeyvisonjs Did you ever resolve this issue? I'm experiencing a similar problem (or at least I think I am) and researching a possible solution.

Bro, I did exactly what was suggested above.
I set max_execution_time to 500s and memory_limit to 2gb, and it worked correctly.
