### ISSUE TITLE
fonts folder and git pull / gitignore

### ISSUE THREAD

**Issue by spfmoby** [dompdf/dompdf#3046]
Hi

I'm using dompf (2.0.1) and have the following problem:
I use git to transfer my development code to the production server (git pull on the production server).
Sometimes the generated pdf files include some fonts that are different from what has been tested on the development server, so when I call the git pull to update the production server there is an error because some files have changed on the production server and are not on the git repository.
OK that's quite normal, but often, when this behavior is expected, the files are clearly located in different folders.

I tried to use the following code to move the cache folder and added a . gitignore entry to ignore this dompdf_font_cache folder :
$options = new Options();
$options->set('isRemoteEnabled', TRUE);
$options->set('fontCache', $my_root.'/includes/dompdf_font_cache/');
$dompdf = new Dompdf($options);

But it does not seem enough. There are new ttf, and utm files and also the "installed-fonts.json" is created in the original dompdf "fonts" folder.

I think that natively mixing "needed" files (like installed-fonts.dist.json for example) and auto generated files (when the app is used) in the same folder is really a bad idea. The two should be separated from the beginning, without any specific configuration.
For example dompdf could use 2 separate folders like 
/dompdf-2.0.1/vendor/dompdf/dompdf/lib/fonts
/dompdf-2.0.1/vendor/dompdf/dompdf/lib/fonts_cache
and use the first to provide everything needed to start
and the second everything that will be written by the app itself while in use.
With such a solution it would be easy to explude the /dompdf-2.0.1/vendor/dompdf/dompdf/lib/fonts_cache folder with a gitignore entry and there would be no more problem.

In the meantime, what would be a correct solution to avoid this problem?

Thanks in advance.

**Comment by bsweeney** [comment]
You almost had it. The fontCache is used for cache files, which are separate from the installed fonts. To move the installed fonts out of the path of your repo you should set the fontDir Option.

```
$options = new Options();
$options->set('isRemoteEnabled', TRUE);
$options->set('fontDir', $my_root.'/includes/dompdf_font_cache');
$options->set('fontCache', $my_root.'/includes/dompdf_font_cache');
$dompdf = new Dompdf($options);
```

I didn't vary the path since you _may_ use the same directory for both if you want.

**Comment by bsweeney** [comment]
The font directory included with Dompdf contains the bundled fonts. Dompdf always utilizes the contents of that directory from it's specific (relative) location. So, that directory should not be copied or modified. The directory specified by the fontDir Option is where user-installed fonts are stored. The fonts and the installed-fonts.json file will populate that directory.

**Comment by spfmoby** [comment]
Ok, thank you for the details. I understand it better now.
