### ISSUE TITLE
Exception : Call to undefined method Sabberworm\CSS\CSSList\Document::insert()

### ISSUE THREAD

**Issue by BenAgroS** [dompdf/dompdf#3062]
Hi there,

I have this exception when I upgrade my moodle, DomPdf is installed in the plugin I developped and it do the job. I used composer.json to install it.
```
{
  "require-dev": {
    "dompdf/dompdf": "v2.0.1"
  }
}
```

I just have this exception, "Exception : Call to undefined method Sabberworm\CSS\CSSList\Document::insert()"  don't know where it come from.
If anyone has a suggestion thx in advance.

**Comment by bsweeney** [comment]
Sabberworm is a CSS parser used by the php-svg-lib dependency, which is used to render SVG images. Something in your SVG's styling is throwing off the parser.

**Comment by BenAgroS** [comment]
Thx for your reply, I will investigate it, but I don't use any images or svg in my .mustache file to create my pdf.
Strange, thx anyway.

**Comment by bsweeney** [comment]
Sabberworm shouldn't be in use unless an SVG is being rendered. Could be that Moodle defaults to an SVG for some core images. Anyway, let us know if you need any further help.

**Comment by BenAgroS** [comment]
Thx for your quick reply, I will keep investigating, not easy to solve without touching moodle core which I prefer not to, and also to find the issue cause there is no debug info. I saw this exception during plugin's upgrade on my terminal using ssh.
 I will post if I solve the issue.
