### ISSUE TITLE
Cannot render input type="number"

### ISSUE THREAD

**Issue by kosn1** [dompdf/dompdf#3065]
Hello,
I am trying to render html code into pdf. So far I am struggling with input elements not rendering at all, especially `<input type="number">` or  `<input type="email">` . If I change the type to text it is working fine but that's not what I want. I have tested it [here](https://eclecticgeek.com/dompdf/debug.php). My code for testing porpuses was 
```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body>
  <h3>Test input</h3>
  <input type="number" id="quantity" name="quantity" min="1" max="5" value=2>
</body>
</html>
```

and the output pdf was this

![image](https://user-images.githubusercontent.com/47416784/202213957-791bb1d0-6730-45b7-a363-78dce90e4a08.png)

Can you help me figure out why is this happening?

**Comment by bsweeney** [comment]
Dompdf has not been updated to support HTML5 input elements. You can mirror what it does for `<input type="text">` with the following addition to your stylesheet:

```
input[type=number] {
  width: 12em;
  background: #FFF;
  border: 1px solid #999;
  padding: 2px;
  margin: 2px;
}
input[type=number]:before {
  content: attr(value);
}
```

And, if you want to restrict that styling to Dompdf you can wrap it with a media type declaration:

```
@media dompdf {
  input[type=number] {
    width: 12em;
    background: #FFF;
    border: 1px solid #999;
    padding: 2px;
    margin: 2px;
  }
  input[type=number]:before {
    content: attr(value);
  }
}
```

**Comment by kosn1** [comment]
Thank you for your answer, applying these rules in my stylesheet fixed the issue!
