### ISSUE TITLE
Remove elements from pdf

### ISSUE THREAD

**Issue by kosn1** [dompdf/dompdf#3070]
Hello,
I am trying to render some html into pdf and I don't want to include some elements into the pdf. Those elements have a specific class which is added to them by javascript while document is loading. I have tried to hide them with css but it seems like the assigned classes are not applied in my rendered html so I cannot target them. I also tried some inline script before I render my html but that didn't work either. Here is what I am trying to do
```
use Dompdf\Dompdf;
 
    ob_start();
?>
   <script>
        jQuery(document).ready(function($) {
            $('.hide-me').remove();
        });
    </script>
   <div class="a">aaaa</div>
   <div class="hide-me">bbbb</div>
   <div class="c">cccc</div>
   
<?php
    $content = ob_get_contents();
    ob_end_clean();
    $dompdf = new Dompdf();
 
    $dompdf->loadHtml($content);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    ob_end_clean();
    $dompdf->stream();
```

As I said I can't apply some css like `.hide-me{display:none;} `. The class names seems to be applied on my browser when page loads but not on my rendered html (`$dompdf->loadHtml($content);`). Probably because they are added dynamically by a script on page load. Is there a way to do some preprocessing and hide those elements so I can get the desired output in my pdf?

PS. I am calling ob_end_clean() twice because I get: 

> failed to load pdf document

 error if I do not do so.

**Comment by bsweeney** [comment]
Dompdf does not support JavaScript. For the particular scenario you describe you can hide the elements only when generating a PDF by styling those elements as hidden only for Dompdf. Within your document stylesheet just add the following:

```
@media dompdf {
  .hide-me { display: none; }
}
```
