### ISSUE TITLE
Get html from every pdf page

### ISSUE THREAD

**Issue by GORGDEVELOPER** [dompdf/dompdf#3072]
Hello, first of all sorry about my english it isn't very good.
I have a question, i wath to get every pdf page as html content, how can i do this? I think i can do it with "end_page_render" callback, but i'm don't know how..
Maybe anybody can help me,
Thanks.

**Comment by bsweeney** [comment]
Are you saying you want to get the HTML that was used to create the PDF page? Or do you want to take the PDF page and re-render as HTML? Getting the backing HTML should be possible using callbacks, as you noted. The following should work:

```
$dompdf->setCallbacks([
    [
        'event' => 'end_page_render',
        'f' => function ($frame, $canvas, $fontMetrics) {
            $node = $frame->get_node();
            file_put_contents("page{$canvas->get_page_number()}.html", $node->ownerDocument->saveHTML($node));
        }
    ]
]);
```
