### ISSUE TITLE
Is set_paper deprecated?

### ISSUE THREAD

**Issue by AnthonySarzuri** [dompdf/dompdf#3076]
So, i was doin' my webpage using dompdf and there seems to be a problem with the set_peper function, I was testing recently and there's just empty pdf's, while checking the code it says  ̶s̶e̶t̶_̶p̶a̶p̶e̶r̶ an the desc says is deprecated, what should i use?
![image](https://user-images.githubusercontent.com/88399326/205305856-f10e9644-e822-441e-aca1-0bc64fc71619.png)
also with the function load_html
or maybe is just the version im working on, i'm on php 8.1

**Comment by bsweeney** [comment]
`set_paper` is deprecated, yes. You can use `setPaper` instead. Same for `load_html`, use `loadHtml`.

**Comment by AnthonySarzuri** [comment]
Oh well thx! :D
