### ISSUE TITLE
Supporting LTR 

### ISSUE THREAD

**Issue by gabayim** [dompdf/dompdf#3078]
Greetings,
Is there any any plan to support LTR ? the solution at the moment is very limited on contries with the need for it (Arabic, Hebrew, and such).

Thnak you,

**Comment by bsweeney** [comment]
Do you mean `dir=rtl` (HTML) or `direction: rtl;` (CSS)? We would like to add support, yes. Some initial work was done with #2107 but proved insufficient for multi-line text or text broken into multiple frames (i.e., text broken by inline elements).

The issue to follow for RTL support is #1009, or more generally #2619 for complex text layout, including shaping for languages that utilize it (such as Arabic).

Wanting to add support, however, is different from actually supporting the feature. Current active devs do not use a RTL language natively. And there is nobody working full time so it's a matter of who has the time and desire to implement the feature.
