### ISSUE TITLE
Pdf content generated in multiple pages instead od Single page

### ISSUE THREAD

**Issue by a-akashsoni** [dompdf/dompdf#3079]
I tried to convert html to pdf in laravel 7 . But after converted it converted in 5 different pages instead of single page. **Current output is :-**
![Screenshot_1](https://user-images.githubusercontent.com/110217613/206982336-f432ca88-ed90-415c-bf04-9a174b515fcd.png)
 **Expected output is :-**
![Screenshot_3](https://user-images.githubusercontent.com/110217613/206982671-8260eb1f-8cbf-477e-bdbf-a685603d7a93.png)

Kindly help to resolve this issue.

**Comment by a-akashsoni** [comment]
Hey , Sample of the HTML + CSS is below . can you check this.......
`
<!DOCTYPE html>
<html lang="en">

<head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preload" href="fonts/transfonter.org-20221201-054935/" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="fonts/transfonter.org-20221201-053057/" as="font" type="font/woff2" crossorigin>

</head>
<style>
    @font-face {
        font-family: 'Chomsky';
        src: url('fonts/Chomsky.woff2') format('woff2'), url('fonts/Chomsky.woff') format('woff');
        font-weight: normal;
        font-style: normal;
        font-display: swap;
    }
    
    @font-face {
        font-family: 'LT Comical';
        src: url('fonts/LTComical-Medium.woff2') format('woff2'), url('fonts/LTComical-Medium.woff') format('woff');
        font-weight: 500;
        font-style: normal;
        font-display: swap;
    }
</style>

<body style="overflow-x: hidden;margin: 0;">
    <section style="background-image: url(./images/green-bg-top.jpg);background-size: cover;background-repeat: no-repeat;background-position: center;width: 100%;height: 100%;">
        <div style="padding: 100px 0;">
            <div style="max-width: 100%;margin: 0 auto;padding: 30px;background-image: url(./images/yellow-bg.jpg);position: relative;">
                <img src="./images/logo.png" style="
    position: absolute;
    top: -50px;
">
                <div style="text-align: center;max-width: 730px;margin: 0 auto;">
                    <h1 style="font-family: 'Chomsky';color: #536a32;font-size: 40px;font-weight: 100;">To All &amp; Sundry whom these presents do concern Scotland Titles does declare that</h1>
                    <h3 style="font-family: 'Chomsky';color: #10094c;font-weight: 100;font-size: 50px;margin-top: 0;">Lord Cameron James McDonald &amp; Lady Isla Jane McDonald</h3>
                    <div style="padding-bottom: 50px; "> <img src="./images/certificate-icon.png" style="max-width: 240px; "></div>


                </div>
                <div style="display: flex;width: 100%;padding-bottom: 80px;">
                    <div style="width: 50%; ">
                        <div style="font-family: 'LT Comical';font-size: 18px;letter-spacing: 1px;line-height: 28px; ">
                            <p>
                                <span style="font-family: 'Chomsky';color: #536a32;font-size: 36px;font-weight: 100; ">
                Having By Petition</span> UNTO US THIS DAY IN THE SIXTY SEVENTH YEAR OF THE REIGN OF OUR SOVEREIGN ELIZABETH THE SECOND, BY THE GRACE OF GOD, OF THE UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND,
                                QUEEN, HEAD OF THE COMMONWEALTH, DEFENDER OF THE FAITH, </p>
                            <p>
                                <span style="font-family: 'Chomsky';color: #536a32;font-size: 36px;font-weight: 100; "> Shewwen:</span> THAT THE SAID PETITIONERS HAVE OWNERSHIP OF LANDS IN SCOTLAND AND THE PETITIONERS HAVING PREYED THAT THERE MIGHT BE
                                GRANTED UNTO THEM TO USE SUCH ENSIGNS ARMORIAL AS MAY BE THE LAWFUL PROPERTY OF SCOTLAND TITLES AND MIGHT BE SUITABLE AND ACCORDING TO THE LAWS OF ARMS, KNOW YE THEREFORE THAT WE HAVE ASSIGNED, AND DO BY THESE PRESENTS
                                DECLARE, RATIFY AND CONFIRM UNTO THE PETITIONERS THE FOLLOWING ENSIGNS ARMORIAL, AS DEPICTED HEREOF, AND MATRICULATED OF EVEN DATE WITH THESE PRESENTS AS A MARK OF THE INTELLECTUAL PROPERTY OF SCOTLAND TITLES, TO BE PRESENTED
                                BY THE PETITIONERS AS THEY DEEM, </p>

                            <p>
                                <span style="font-family: 'Chomsky';color: #536a32;font-size: 36px;font-weight: 100; "> Videlicit: </span> BY DEMONSTRATION OF WHICH ENSIGNS ARMORIAL THE SAID PETITIONERS ARE, AMONGST ALL NOBLES AND IN ALL PLACES OF HONOUR,
                                TO BE TAKEN, NUMBERED, ACCOUNTED AND RECEIVED AS LAIRDS OF SCOTLAND,
                            </p>

                            <p>
                                <span style="font-family: 'Chomsky';color: #536a32;font-size: 36px;font-weight: 100; "> In Testimony Whereof.</span> WE HAVE SUBSCRIBED THESE PRESENTS AND THE SEAL OF OUR OFFICE IS AFFIXED HERETO AT SCOTLAND TITLES THIS
                                DAY.
                            </p>
                        </div>
                    </div>
                    <div style="width: 0px;border: 5px solid #10094c;margin: 0 20px;border-radius: 22px;">

                    </div>
                    <div style="width: 50%; font-family: 'LT Comical';font-size: 18px;letter-spacing: 1px;line-height: 28px; ">
                        <img src="./images/ryt-img.png" style="width: 100%;max-width: 350px; margin: 0 auto;display: flex; ">
                        <p>
                            <span style="font-family: 'Chomsky';color: #536a32;font-size: 36px;font-weight: 100;display: flex;margin-bottom: 10px; ">
                    furthermore know ye therefore that 
                    </span>SCOTLAND TITLES HAS SET OUT PART OF THE ESTATE KNOWN AS OLGRINMORE WOOD, HALKIRK, HIGHLAND, SCOTLAND, HEREINAFTER REFERRED TO AS THE ESTATE, AS A SCHEME OF SOUVENIR PLOTS AND
                        </p>

                        <p>
                            <span style="font-family: 'Chomsky';color: #536a32;font-size: 36px;font-weight: 100; ">
                    Scilicet:</span> BY VIRTUE OF OWNERSHIP OF THE LAND IN SCOTLAND AND IN PARTICULAR THE LAND DESCRIBED ABOVE WITHIN THE LORDSHIP OF CAITHNESS BY HALKIRK AS FURTHER DESCRIBED IN THE CERTIFICATE OF DISPOSITION
                            AND SALE, THE PETITIONERS MAY HENCEFORTH AND IN PERPETUITY BE KNOWN BY THE STYLE OF LAIRDS AND IN PARTICULAR LAIRDS OF OLGRINMORE.
                        </p>

                    </div>



                </div>
                <div style="position: relative;display: flex;align-items: center; ">
                    <div style="padding: 20px 0;text-align: right;position: absolute;right: 0;bottom: 0; ">

                        <img src="./images/bottom-logo.png" style="max-width: 170px; "> </div>

                    <div style="width: 45%;font-family: 'LT Comical';text-align: center;margin: 0 auto ; font-size: 18px;letter-spacing: 1px;line-height: 28px; ">
                        <p style="display: flex;align-items: center; margin: 0; ">
                            <span style="font-family: 'Chomsky';color: #536a32;font-size: 36px;font-weight: 100; margin-right: 40px ">
                        Signed</span><img style="max-width: 120px;height: 60px;object-fit: contain; " src="./images/sign.png">
                        </p>
                        <p style=" margin-top: 0;margin-bottom: 8px;">
                            <span style="margin: 0; font-family: 'Chomsky';color: #536a32;font-size: 36px;font-weight: 100; margin-right: 40px ">
                        Date</span>THIS 1ST DAY OF JANUARY IN THE YEAR 2019
                        </p>
                    </div>

                </div>
                <p style="
            font-family: 'LT Comical';
            font-size: 12px;
            letter-spacing: 1px;
            line-height: 18px;
            text-align: center;
            margin: 0;
        ">All test, layout, twork and Thatrations copyright Scotland The 2019 and subject to me COTLAND
                </p>
            </div>
        </div>

    </section>
</body>

</html>`

**Comment by bsweeney** [comment]
The main issue is that you're using flexbox, which dompdf does not yet support (#971). You can use floats for this particular layout and it should work so long as the content does fit on a single page. If you need to target Dompdf for that styling you can do so by using the `dompdf` media type:

```
<style>
@media dompdf {
  /* your styles here */
}
</style>
```

**Comment by a-akashsoni** [comment]
Thanks for your reference........
