### ISSUE TITLE
Browser-oriented JavaScript in the document body may be rendered inline

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#308]
_Original author: eclecticgeek (June 08, 2011 18:23:27)_

<b>What steps will reproduce the problem?</b>
1. Create a HTML document with JavaScript in the body.
2. Render the document.

<b>What is the expected output? What do you see instead?</b>
The document should be created without the presence of the content of the JavaScript code. Portions of the script are, however, rendered as normal document text.

Are there any known causes?
DOMDocument-&gt;loadHTML() appears to parse the text of the script block (including text that is part of a JavaScript string) as part of the normal document. If the script contains any HTML tags DOMDocument will make the same type of structural corrections it would for the document body. In the worst case, if a closing html tag is in the code block DOMDocument will treat it as the end of the HTML, breaking things horribly.

Are there any known work-arounds?
Break up strings with HTML tags into multiple parts (e.g. change &quot;&lt;/html&gt;&quot; to &quot;&lt;&quot;+&quot;/html&gt;&quot;)

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=302_

**Comment by Mellthas** [comment]
Should be addressed with the use of html5-php.
