### ISSUE TITLE
watermark issue on middle pages in latest version

### ISSUE THREAD

**Issue by Ademgenc53** [dompdf/dompdf#3084]
Hello,
I was using the [url](https://www.codesenior.com/en/tutorial/Dompdf--Create-Watermark-and-Page-Numbers) watermark code here with version 1.2.2.
When I installed the last version "2.0.1", the watermark on the middle pages is full black text and is not soft.
What should I do for this? Is there a solution?

**Comment by bsweeney** [comment]
Starting with 2.0.0 we did make some changes to how canvas methods operate. This is probably causing your issue though I'd have to research more to see exactly what's happening.

That being said, the ability to set the opacity in relation to the page_text method was not an intended feature. As such, it's not unexpected that at some point we would break it. If you want to continue doing this through script, you should move your text generation into the page_script block. Also note that page script now accepts a function, so you don't have to pass a text blob representing the script to run.

The relevant section of that sample code can be rewritten to something like this:

```
$canvas = $dompdf->getCanvas();
$canvas->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
    $w = $canvas->get_width();
    $h = $canvas->get_height();
    $pageNumberWidth = $w / 2;
    $pageNumberHeight = $h - 50;
    $font = $fontMetrics->getFont("times", "normal");

    if ($pageNumber > 1) {
        $current_page = $pageNumber-1;
        $total_pages = $pageCount-1;

        $canvas->set_opacity(1,"Multiply");
        $canvas->text(297.64, 791.89, "$current_page / $total_pages", $font, 10, array(0,0,0));
        $canvas->set_opacity(1,"Normal");

        $canvas->set_opacity(0.2,"Multiply");
        $canvas->image(public_path('images/logo/icon.png'), 475.28, 771.89, 50, 50);
        $canvas->image(public_path('images/logo/kultur_logo.png'), 75.28, 771.89, 50, 50);
        $canvas->set_opacity(1,"Normal");
    }

    $canvas->set_opacity(.1,'Multiply');//Multiply means apply to all pages.
    // Specify watermark text
    $text = "dompdf";
    $txtHeight = $fontMetrics->getFontHeight($font, 150);
    $textWidth = $fontMetrics->getTextWidth($text, $font, 40);

    $x = (($w-$textWidth)/2);
    $y = (($h-$txtHeight)/2);

    $canvas->text($x, $y, $text, $font, 40,$color = array(255,0,0),
        $word_space = 0.0, $char_space = 0.0, $angle = 20.0);

    $canvas->set_opacity(1, "Normal");
});
```

But what I would really do for any text that doesn't require the total number of pages would be to just utilize CSS. Positioning can be a little tricky since you can't calculate the height of the text and use that for placement. But for simple text you can get pretty close. For example, the watermark text from that sample code can just use the following HTML:

```
<div style="position: fixed; inset: 50% 0; width: 100%; text-align: center; font-size: 300%; font-weight: bold; opacity: .2; transform: rotate(25deg);">
    dompdf
</div>
```

Total page count is not yet supported through CSS so rendering that particular text still requires page_script/page_text.

**Comment by Ademgenc53** [comment]
Thank you very much for your help.
I see you closed the topic, but there is a problem.
Text watermark appears transparently on all pages, it's fine.
Problem 1: The logo at the bottom of the page is missing on the first page
Problem 2: The page number is missing on the first page and it starts as (1/5) on the second page. This shows that there are 5 pages when there are 6 pages.

As seen in the picture below, the page number starts from the second page.
![Ekran görüntüsü 2022-12-20 115258](https://user-images.githubusercontent.com/55327675/208626967-9ce59584-784e-4c63-ba84-840f7df67dd8.png)

As seen in the image below, I am using the footer logo but there is no logo on the first page. There is no logo in the picture above.
![Ekran görüntüsü 2022-12-20 115134](https://user-images.githubusercontent.com/55327675/208627180-5a4b447b-e4fc-4f78-ae4d-a965d0707cf8.png)

**Comment by bsweeney** [comment]
That's because of the condition that says `if ($pageNumber > 1)`, which is what the sample you linked to is doing. If you want things to start on page 1 then adjust your code. And if you're using something different than what you linked to you should share that instead.

**Comment by Ademgenc53** [comment]
Here are my codes, I would be glad if you can help
PS: I am a beginner in php.

```
ob_start();
include("../tablo_pdf.php");
$html = ob_get_clean();

// Dompdf ad alanına başvurun 
use Dompdf\Dompdf; 
// Seçenekler ad alanına başvurun 
use Dompdf\Options; 
// Font Metrikleri ad alanına başvurun
use Dompdf\FontMetrics; 

$options = new Options();
$options->set('defaultFont', 'DejaVu Sans');
$options->set('isRemoteEnabled', TRUE);
//$options->set('isPhpEnabled', true);
$dompdf = new Dompdf($options);

$dompdf->loadHtml($html, 'UTF-8');

// HTML'yi PDF olarak işleyin
$dompdf->render();


if ($filigran_metni) {

    $GLOBALS["logo1"] = $site_url.'/images/logo.png';
    $GLOBALS["logo2"] = $site_url.'/images/logo.png';
    $GLOBALS["metin"] = $filigran_metni;

    $canvas = $dompdf->getCanvas();
    $canvas->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
    $w = $canvas->get_width();
    $h = $canvas->get_height();
    $pageNumberWidth = $w / 2;
    $pageNumberHeight = $h - 50;
    $font = $fontMetrics->getFont("DejaVu Sans", "Bold");
    
        if ($pageNumber > 1) {
            $current_page = $pageNumber;
            $total_pages = $pageCount;
    
            $fontno = $fontMetrics->getFont("DejaVu Sans");
            $canvas->set_opacity(0.7,"Multiply");
            $canvas->text(550.28, 5, "$current_page / $total_pages", $fontno, 10, array(0,0,0));
            $canvas->set_opacity(1,"Normal");
    
            $canvas->set_opacity(0.2,"Multiply");
            $canvas->image($GLOBALS["logo1"], 475.28, 771.89, 100, 20);
            $canvas->image($GLOBALS["logo2"], 30.28, 771.89, 100, 20);
            $canvas->set_opacity(1,"Normal");
        }
    
        $canvas->set_opacity(.1,'Multiply');//Multiply means apply to all pages.
        // Specify watermark text
        $text = $GLOBALS["metin"];
        $txtHeight = $fontMetrics->getFontHeight($font, -200);
        $textWidth = $fontMetrics->getTextWidth($text, $font, 70);
    
        $x = (($w-$textWidth)/2);
        $y = (($h-$txtHeight)/2);

        $canvas->text($x, $y, $text, $font, 100, $color = array(0,0,0), 
            $word_space = 0.0, $char_space = 0.0, $angle = -55.0);
        $canvas->set_opacity(1, "Normal");
    });

}

$output = $dompdf->output();
```

**Comment by bsweeney** [comment]
FYI for more basic PHP questions it's best to use sites like [StackOverflow](https://stackoverflow.com/) or the [discussion boards](https://github.com/dompdf/dompdf/discussions). Issue trackers are intended for bugs. A little searching around might even find you an answer.

You haven't stated what it is you're trying to produce or given a sample so I really don't have enough info I can use to help you. That being said, in the following I commented out the condition that's preventing the page number on the first page.

```
ob_start();
include("../tablo_pdf.php");
$html = ob_get_clean();

// Dompdf ad alanına başvurun 
use Dompdf\Dompdf; 
// Seçenekler ad alanına başvurun 
use Dompdf\Options; 
// Font Metrikleri ad alanına başvurun
use Dompdf\FontMetrics; 

$options = new Options();
$options->set('defaultFont', 'DejaVu Sans');
$options->set('isRemoteEnabled', true);
//$options->set('isPhpEnabled', true);
$dompdf = new Dompdf($options);

$dompdf->loadHtml($html, 'UTF-8');

// HTML'yi PDF olarak işleyin
$dompdf->render();


if ($filigran_metni) {

    $GLOBALS["logo1"] = $site_url.'/images/logo.png';
    $GLOBALS["logo2"] = $site_url.'/images/logo.png';
    $GLOBALS["metin"] = $filigran_metni;

    $canvas = $dompdf->getCanvas();
    $canvas->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
    $w = $canvas->get_width();
    $h = $canvas->get_height();
    $pageNumberWidth = $w / 2;
    $pageNumberHeight = $h - 50;
    $font = $fontMetrics->getFont("DejaVu Sans", "Bold");
    
        //if ($pageNumber > 1) {
            $current_page = $pageNumber;
            $total_pages = $pageCount;
    
            $fontno = $fontMetrics->getFont("DejaVu Sans");
            $canvas->set_opacity(0.7,"Multiply");
            $canvas->text(550.28, 5, "$current_page / $total_pages", $fontno, 10, array(0,0,0));
            $canvas->set_opacity(1,"Normal");
    
            $canvas->set_opacity(0.2,"Multiply");
            $canvas->image($GLOBALS["logo1"], 475.28, 771.89, 100, 20);
            $canvas->image($GLOBALS["logo2"], 30.28, 771.89, 100, 20);
            $canvas->set_opacity(1,"Normal");
        //}
    
        $canvas->set_opacity(.1,'Multiply');//Multiply means apply to all pages.
        // Specify watermark text
        $text = $GLOBALS["metin"];
        $txtHeight = $fontMetrics->getFontHeight($font, -200);
        $textWidth = $fontMetrics->getTextWidth($text, $font, 70);
    
        $x = (($w-$textWidth)/2);
        $y = (($h-$txtHeight)/2);

        $canvas->text($x, $y, $text, $font, 100, $color = array(0,0,0), 
            $word_space = 0.0, $char_space = 0.0, $angle = -55.0);
        $canvas->set_opacity(1, "Normal");
    });

}

$output = $dompdf->output();
```

**Comment by Ademgenc53** [comment]
"StackOverflow" website has no right to ask questions to newbies like us. Because in order to ask a question, it is necessary to write answers to other questions. As we are newbies, we cannot reply to those who ask for help.

I'm trying to do something for myself not commercial
I create PDF from 1/1 page to 1/22 page

Thank you very much for your help problem solved.
