### ISSUE TITLE
Not render well characters

### ISSUE THREAD

**Issue by atellez91** [dompdf/dompdf#3085]
Hi! I have a problem when creating a PDF and previewing it from a web or from Postman there are random characters that do not render well. If I update it may be that they all look good or that others are the ones that look bad.
I leave you an example of how they look bad:

![image](https://user-images.githubusercontent.com/32269658/208645134-815a9d80-e3a1-40a3-91a5-17052c96ff46.png)

If I download the file as a pdf file, everything is displayed correctly.

I am using:
- Docker
- Alpine 3.16.2
- PHP 8.1
- Symfony 6.0.8
- dompdf 2.0

**Comment by bsweeney** [comment]
That's ... odd. Looks like something is rendering on top of the text. Can you share the PDF?

**Comment by atellez91** [comment]
> Looks like something is rendering on top of the text. Can you share the PDF?

The PDF document is viewed correctly, it only happens when the PDF content is returned to preview in some browser. If the content is downloaded as a PDF file, the error is not displayed.

**Comment by bsweeney** [comment]
Do you have a sample available online?

**Comment by atellez91** [comment]
> 

No, sorry, it is a private application

**Comment by bsweeney** [comment]
So viewing in the browser it's corrupt, but if you save the PDF that you viewed in the browser it's fine when viewed?

Are you using both the output and the stream methods from the Dompdf class? That can cause PDF corruption.

If you could post a corrupted version of the PDF I could at least try and figure out what's causing the issue. But as-is I don't really have enough information.

**Comment by atellez91** [comment]
> So viewing in the browser it's corrupt, but if you save the PDF that you viewed in the browser it's fine when viewed?
> 
> Are you using both the output and the stream methods from the Dompdf class? That can cause PDF corruption.
> 
> If you could post a corrupted version of the PDF I could at least try and figure out what's causing the issue. But as-is I don't really have enough information.

Yes, when I download the pdf the errors are not displayed.

I am using the render method and then output.

I am going to try to publish the PDF, but there you can't see the error because in PDF it always comes out fine, it is only at browser level or from Postman itself.

**Comment by bsweeney** [comment]
If you can share the raw data from Postman that may help.

**Comment by atellez91** [comment]
This is the answer in Postman:
![image](https://user-images.githubusercontent.com/32269658/212060649-798c8de2-6f10-408f-b6b1-6468b210b592.png)
![image](https://user-images.githubusercontent.com/32269658/212060804-d86d08f8-5f5e-4046-b50f-9d2daf445a81.png)

If I download the response I get this document
[aaa.pdf](https://github.com/dompdf/dompdf/files/10401313/aaa.pdf)

**Comment by bsweeney** [comment]
Are you using the "Save Reponse" option within postman? Would fetching something like curl or wget produce a corrupted PDF? What about if you use save the PDF to disk using`$dompdf->output()` then view it?

**Comment by atellez91** [comment]
I have tried both options and the PDF is generated well, but to view it correctly I would have to separate the process and read the 
PDF generated locally. It still does not work directly from the output()

**Comment by atellez91** [comment]
I have found the source of the problem. It's a bug in Chromium with the 2d canvas rendering.

**Comment by bsweeney** [comment]
Well that's unfortunate. I didn't find a bug report in the chromium project though I did [find](https://community.apryse.com/t/choppy-text-rendered-with-windows-and-chrome/6034) [a few](https://support.papersapp.com/support/solutions/articles/30000046026-pdf-rendering-issues-in-google-chrome-on-windows-10) [posts](https://support.digitaltheatreplus.com/choppy-text-in-pdfs) about the issue.
