### ISSUE TITLE
My font google cdn links is not working with domPdf

### ISSUE THREAD

**Issue by a-akashsoni** [dompdf/dompdf#3090]
I tried to change the  fonts for the pdf with laravel 7. But the fonts links are not working in the blade file. And show default font style. Kindly suggest me for the same so I can change font style in the laravel.

**Comment by bsweeney** [comment]
Can't really provide any guidance without knowing what you've tried. Please provide a sample of your HTML.

**Comment by a-akashsoni** [comment]
Kindly check the sample html 
`

<!DOCTYPE html>
<html lang="en">

<head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preload" href="fonts/transfonter.org-20221201-054935/" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="fonts/transfonter.org-20221201-053057/" as="font" type="font/woff2" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Passion+One:wght@400;700;900&display=swap" rel="stylesheet">
	</head>
<style>
    @font-face {
        font-family: 'Righteous', cursive;
        src: url('fonts/Chomsky.woff2') format('woff2'), url('fonts/Chomsky.woff') format('woff');
        font-weight: normal;
        font-style: normal;
        font-display: swap;
    }
    
    @font-face {
        font-family: 'LT Comical';
        src: url('fonts/LTComical-Medium.woff2') format('woff2'), url('fonts/LTComical-Medium.woff') format('woff');
        font-weight: 500;
        font-style: normal;
        font-display: swap;
    }
    
    * {
        padding: 0;
        box-sizing: border-box;
        margin: 0;
    }
    
    body {
        width: 29.7cm;
        height: 41cm;
        margin: 0 auto;
        display: block;
    }
    
    
</style>

<body>
    <table style="width: 100%; border-spacing: 0;background-color: #ffeeb6;">
        <tbody>
            <tr>
                <td><img src="./images/multi-color-background.png" style="width: 100%; display: block;"></td>
            </tr>
        </tbody>
    </table>

    <table style="width: 100%;background-color: #ffeeb6;  ">
        <tbody style="position: relative;">
            <tr>
                <td><img src="./images/logo.png" style="width: 100%;max-width: 120px;display: block; margin-top: -65px;"></td>
            </tr>

            <tr>
                <td style="font-family: 'Passion One', cursive; color: #536a32;font-size: 32px;font-weight: 100;text-align: center; line-height: 50px; text-align: center;max-width: 720px;margin: 0 auto; display:block;">To All & Sundry whom these presents do concern Scotland Titles does declare that</td>
            </tr>  
            <tr>
                <td style="font-family: 'Passion One', cursive; color: #10094c;font-weight: 100;font-size: 36px;margin-top: 0;text-align: center; line-height: 50px; text-align: center;max-width: 540px;margin: 0 auto; display:block;">Lady Craig Edward Smith & Lady Kevin Michael Smith</td>
            </tr>
            <tr>
                <td style=" padding-top: 20px; text-align: center";>
                    <img src="./images/upper-logo.png" style="max-width: 160px;width: 100%;display: block;margin: 0 auto;"></td>
            </tr>
        </tbody>
    </table>

    <table style="width: 100%;border-spacing: 0;background-color: #ffeeb6;padding: 20px 20px 0 20px;">
        <tbody>
            <tr>
                <td style="font-family: 'LT Comical';font-size: 16px;letter-spacing: 1px;line-height: 28px;width: 50%; padding-right: 20px;">
                    <div style="font-family: 'Patrick Hand', cursive; font-size: 16px;line-height: 23px; ">
                        <p style="padding-bottom: 10px;">
                            <span style="font-family: 'Righteous', cursive; color: #536a32;font-size: 20px;font-weight: 100; ">
                            Having By Petition</span>  UNTO US THIS DAY IN THIS  YEAR OF THE REIGN OF OUR SOVEREIGN CHARLES THE THIRD, BY THE GRACE OF GOD, OF THE UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND,KING, HEAD OF THE COMMONWEALTH,DEFENDER OF THE FAIT, </p>
                        <p style="padding-bottom: 10px;">
                            <span style="font-family: 'Righteous', cursive; color: #536a32;font-size: 20px;font-weight: 100; "> Shewwen:</span>  THAT THE SAID PETITIONER SHAVE OWNERSHIP OF LANDS IN SCOTLAND AND THE PETITIONERS HAVING PREYED THAT THERE MIGHT BE GRANTED UNTO THEM TO USE SUCH ENSIGNS ARMORIAL AS MAY BE THE LAWFUL PROPERTY OF SCOTLAND TITLES AND MIGHT BE SUITABLE AND ACCORDING TO THE LAWS OF ARMS, KNOW YE THEREFORE THAT WE HAVE ASSIGNED, AND DO BY THESE PRESENTS DECLARE, RATIFY AND CONFIRM UNTO THE PETITIONERS THE FOLLOWING ENSIGNS ARMORIAL, AS DEPICTED HEREOF, AND MATRICULATED OF EVEN DATE WITH THESE PRESENTS AS A MARK OF THE INTELLECTUAL PROPERTY OF SCOTLAND TITLES, TO BE PRESENTED BY THE PETITIONERS AS THEY DEEM,  </p>

                        <p style="padding-bottom: 10px;">
                            <span style="font-family: 'Righteous', cursive; color: #536a32;font-size: 20px;font-weight: 100; "> Videlicit: </span> BY DEMONSTRATION OF WHICH ENSIGNS ARMORIAL THE SAID PETITIONER SARE , AMONGST ALL NOBLES AND IN ALL PLACES OF HONOUR, TO BE TAKEN, NUMBERED, ACCOUNTED AND RECEIVED AS  LAIRDS OF SCOTLAND,
                        </p>

                        <p style="padding-bottom: 10px;">
                           <span style="font-family: 'Righteous', cursive; color: #536a32;font-size: 20px;font-weight: 100; "> In Testimony Whereof.</span> WE HAVE SUBSCRIBED THESE PRESENTS AND THE SEAL OF OUR OFFICE IS AFFIXED HERETO AT SCOTLAND TITLES THIS DAY.  
                        </p>
                    </div>
                </td>
                <td style="width: 0px;border: 5px solid #10094c;margin: 0 20px;border-radius: 22px;">

                </td>
                <td style="font-family: 'Patrick Hand', cursive; font-size: 16px;letter-spacing: 1px;line-height: 23px;width: 50%; padding-left: 20px;">
                    <img src="./images/royl-img.png" style="width: 100%;max-width: 350px; margin: 0 auto;display: flex; ">
                    <p style="padding-bottom: 10px;">
					
                    <span style="font-family: 'Righteous', cursive; color: #536a32;font-size: 20px;font-weight: 100;display: flex;margin-bottom: 0px; ">furthermore know ye therefore that 
                   </span>SCOTLAND TITLES HAS SET OUT PART OF THE ESTATE BY BLAIRADAM FOREST KNOWN AS CANTSDAM ,FIFE, SCOTLAND, HEREINAFTER REFERRED TO AS ‘THE ESTATE’, AS A SCHEME OF SOUVENIR PLOTS AND
                    </p>

                   <p style="padding-bottom: 10px;">
                        <span style="    font-family: 'Righteous', cursive;color: #536a32;font-size: 20px;font-weight: 100; ">
                Scilicet:</span> BY VIRTUE OF OWNERSHIP OF THE LAND IN SCOTLAND AND IN PARTICULAR THE LAND DESCRIBED ABOVE WITHIN THE KINGDOM OF FIFE BY CANTSDAM AS FURTHER DESCRIBED IN THE CERTIFICATE OF DISPOSITION AND PROCLAMATION , THE PETITIONERS MAY HENCEFORTH AND IN PERPETUITY BE KNOWN BY THE STYLE OF LAIRDS AND IN PARTICULAR LAIRDS OF BLAIRADAM .
                    </p>
                </td>
            </tr>
        </tbody>
    </table>

    <table style="width: 100%; border-spacing: 0;background-color: #ffeeb6;">
        <tbody style="text-align: center;position: relative;">
            <tr>
                <td style="text-align: right; padding-top: 30px;">
                    <img src="./images/star-logo.png" style="max-width: 180px;width: 100%;padding: 16px 0;text-align: right;margin-right: 40px;margin-top: 0px;margin-left: auto;position: relative;z-index: 9; display: block;">
                </td>  
            </tr>
        </tbody>
    </table>
    <table style="width: 100%;border-spacing: 0;padding: 20px; margin-top: -160px;">
        <tbody style="text-align: center;position: relative;">
            <tr>
                <td>
                    <p style="font-family: 'Righteous', cursive;color: #536a32;font-size: 26px;font-weight: 100;display: flex;align-items: center;justify-content: center;">
                        Signed<img style="max-width: 120px;height: 60px;object-fit: contain;margin-left: 40px;" src="./images/sign-img.png">
                    </p>
                    <p style=" margin-top: 0;margin-bottom: 8px; font-family: 'LT Comical';">
                        <span style="margin: 0; font-family: 'Righteous', cursive;color: #536a32;font-size: 26px;font-weight: 100; margin-right: 40px;">Date</span>THIS 4TH DAY OF JUNE IN THE YEAR 2022
                    </p>
                    <p style="font-family: 'Patrick Hand', cursive;font-size: 12px; letter-spacing: 1px; line-height: 16px; text-align: center;margin: 0;">All content, layout, artwork and illustrations copyright Scotland Titles 2021 and subject to licence
                    </p>
                </td>
            </tr>
        </tbody>
    </table>

    <table style="width: 100%; border-spacing: 0;background-color: #ffeeb6;">
        <tbody>
            <tr>
                <td><img src="./images/multi-color-background.png" style="width: 100%; display: block;"></td>
            </tr>
        </tbody>
    </table>








</body>

</html>`

**Comment by bsweeney** [comment]
A few things of note:
1. Dompdf currently only supports TrueType fonts.
2. You're referencing Righteous from Google fonts (via the `link` element, but also locally (via the `@font-face` declaration). You should only need to use one of those. 
3. Your stylesheet `@font-face` declaration for Righteous is invalid. You're specifying the "cursive" fallback.
4. Dompdf only supports serif, sans-serif, and monospace fallback fonts. cursive is not supported.
5. But most importantly to your issue, Dompdf does not currently have logic to find the closest matching font. Either the font you specify is present or it is not, meaning you have to reference a supporting font for each weight/style combination.

Your use of Righteous in the document seems to be primarily at a weight of 100 but Google does not even offer that font at that weight. Render the following HTML samples to see this more clearly:

```
<!DOCTYPE html>
<html lang="en">

<head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Righteous&family=Roboto:wght@100;400;700&display=swap" rel="stylesheet">
</head>

<body>
    <p style="font-family: Righteous;">Righteous at normal/100 weight</p>
    <p style="font-family: Righteous; font-weight: 100;">Righteous at 100 weight</p>
    <p style="font-family: Roboto;">Roboto at normal/100 weight</p>
    <p style="font-family: Roboto; font-weight: 100;">Roboto at 100 weight</p>
    <p style="font-family: Roboto; font-weight: 700;">Roboto at 700 weight</p>
</body>

</html>
```
