### ISSUE TITLE
Stream downloading as PHP

### ISSUE THREAD

**Issue by oleteacher** [dompdf/dompdf#3101]
Greetings!

This has me baffled and have searched google + here in issues + stackoverflow without solution / answer.

When I set `$dompdf->stream("thePDF", array("Attachment" => 1));` get prompt to download the PDF with .pdf extension.

When I set `$dompdf->stream("thePDF", array("Attachment" => 0));` the PDF is opened in the browser and when clicking download button, the file is showing download as .php

I have tried true / false in place of numbers and no change.

I have tried chrome and edge. Both same results.

Using dompdf 2.0.1

Simple html/php example:

https://gist.github.com/oleteacher/5c1ab1ca54eb717837a09de5278784ac

**What am I doing wrong?**

**Comment by bsweeney** [comment]
I'd say try adding the extension first and see what happens?

```
$dompdf->stream("thePDF.pdf", array("Attachment" => 0));
```

If that doesn't work then something might be modifying the HTTP content type header after Dompdf is done. In which case try exiting immediately after streaming:

```
$dompdf->stream("thePDF.pdf", array("Attachment" => 0));
exit();
```

**Comment by oleteacher** [comment]
Hi Brian.

I had already tried adding extension and no change.

Added exit(); and not change.

![image](https://user-images.githubusercontent.com/26278259/211051407-725f78ab-622c-4b9a-976c-b0a93b0a6a58.png)

This is very strange. I have tried on local server and live server with same results.

**Comment by bsweeney** [comment]
Do you have a link to the live server?

**Comment by bsweeney** [comment]
Which button are you clicking? When I click the save button in the PDF viewer it's given the correct extension and shows as the correct document type. What OS are you using?

**Comment by oleteacher** [comment]
Using Windows 10 Educational. Please see screenshot for button:

![image](https://user-images.githubusercontent.com/26278259/211094594-3f68d81e-85af-4992-b589-19a350583ea9.png)

**Comment by oleteacher** [comment]
If working for you, it is obviously not a domPDF issue. When I get home will try on personal desktop, but it is on Win 10 Educational too. Got a laptop on Win10 Pro, will try it too.

I have never seen anything like this, big mystery to me:)

**Comment by bsweeney** [comment]
OK, yeah, that's how I tried it as well. Could be system-specific but hard to say without more test cases.

You could use the browser's dev tools to view the request details to make sure the headers are correct. I would expect it to be OK since the PDF displays correctly, but it's also possible the browser is doing some content sniffing to determine that it's a PDF.

**Comment by oleteacher** [comment]
Since we cannot install browsers on school computers, all we can test with is Edge and Chrome. Crazy thing is Chromium OS based laptops are also downloading as .php

**Comment by oleteacher** [comment]
Bests the heck out of me. I have tried on Windows 10:

Chrome - opens as php
Edge - opens as php
Brave - opens as php
Opera - opens as PDF
Firefox - opens as PDF

Not sure how to proceed. I figured what the hell, will try this from another issue and still no change:

```
$dompdf = new Dompdf();
$dompdf->loadHtml('...');
$dompdf->render();
$pdf = $dompdf->output();
if (headers_sent()) {
    die("Unable to stream pdf: headers already sent");
}
header("Cache-Control: no-cache, no-store, must-revalidate");
header("Content-Type: application/pdf");
header("Content-Length: " . mb_strlen($pdf, "8bit"));
header(\Dompdf\Helpers::buildContentDispositionHeader("inline", "output.pdf"));
echo $pdf;
flush();
```

**Comment by bsweeney** [comment]
I'm stumped. Only thing I can think of is the header getting munged somehow. Since it's a school computer maybe some security software is the culprit. In Edge if you hit F12 you can open the dev tools window and see the actual network traffic in the "Network" tab.

**Comment by bsweeney** [comment]
I tested with Firefox and Edge.

The headers you showed from dompdf_generate.php have two sets of content-type headers. It looks like there are request headers mixed in there. If that's not just some copy/paste munging that could be causing the issue.

**Comment by oleteacher** [comment]
"The headers you showed from dompdf_generate.php have two sets of content-type headers"

Good catch did not notice but what is causing that is a mystery to me. Looks like I have some exploring to do.

**Comment by oleteacher** [comment]
I will not give up on quest to solve the mystery of this issue, but for now have to move on. Seems to be happening to few others I have had test, so not limited to me or anything on school network / firewall. Very strange.

I thank you for your patience since it is not a domPDF issue. 

Will close this now.

**Comment by oleteacher** [comment]
Craziest sh*t I have seen in a long time. Everything started working fine and downloading as PDF instead of PHP.

No changes to code. I do know of fact my edge browser was updated, maybe it flushed some corrupt garbage from the pipes. Even started working correctly for another teacher helping me debug.

Somethings will remain a mystery it appears:)

Thanks again for your help.
