### ISSUE TITLE
unpack(): Type n: not enough input, need 2, have 0

### ISSUE THREAD

**Issue by naseemkhan7021** [dompdf/dompdf#3102]
Hello there,
  My name is Naseem khan from Mumbai India.

### Issue:
 When I try to create PDF with my custom google font-family `<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">`  this gives me an error `unpack(): Type n: not enough input, need 2, have 0`. I am using default dompdf.config file.
I tried every single possibility which is found on google. I try to run it on Windows 10 and Ubuntu v16.04

I need help.

**Comment by bsweeney** [comment]
That's an issue with php-font-lib. Follow dompdf/php-font-lib#47 for updates.
