### ISSUE TITLE
The font skips sections on the document.

### ISSUE THREAD

**Issue by JurakZdenek** [dompdf/dompdf#3105]
Hey guys, a lot has been said here about Fonts. Still, I have a problem that I can't find a thread for. I have an HTML file (invoice). I had a problem with Czech and I didn't want to use the Dejavu font. That's why I used some unicode fonts from Google. I was dealing with installation issues etc.. I solved that. Now we're at the stage where when I generate the PDF it won't apply the font to some words. I do not understand why. Blocks in HTML are nothing special. I have a simple CSS. See picture. Some ideas?
I tried `@font-face` too but it didn't work.

![2023-01-09 09_05_06-Clipboard](https://user-images.githubusercontent.com/74710914/211276255-08f94d4c-212c-4f2b-9b7f-f49017051645.png)

**HTML code:**
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Faktura0033</title>
	<link rel="stylesheet" type="text/css" href="css/PDFfaktura.css">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Rubik+Bubbles&display=swap" rel="stylesheet">
</head>
<body>
<div class="obsah">
<div class="hlavicka">
<div>
<img style="padding: 30px 0 30px 0;" src="css/logo.svg" alt="www.jurakit.cz">
</div><div>      
<h1 style="line-height: 32px;">Faktura číslo: 0033</h1>
Objednávka: Adaptér HP<br>
Datum vystavení: 06.09.2022<br>
</div>
</div>
<div class="odberatel">
<div>
<h3>Zdeněk Jurák</h3>
Havlíčkova 1182<br>
75701, Valašské Meziříčí<br>
IČO: 08841331<br>
etc....
```
CSS:
```
body {
   font-family: 'Rubik Bubbles', cursive;
   width:  18cm;
   height: 26.7cm;
   margin: auto;
   border: black solid 2px;
}

.obsah {
   margin: 30px 30px 30px 30px;
}
etc.....
```

PHP:
```
<?php
 require_once "dompdf/autoload.inc.php";
 use Dompdf\Dompdf;
 use Dompdf\Options;
 
$html = file_get_contents("vzor.html");
$fontDIR = __DIR__.'/dompdf/myfonts';

$dompdf = new Dompdf([
    'logOutputFile' => '',
    'isRemoteEnabled' => true,
    'fontDir' => $fontDIR,
    'fontCache' => $fontDIR,
    'tempDir' => $fontDIR,
    'chroot' => __DIR__,
]);
$dompdf->loadHtml($html, 'UTF-8'); //load an html
$dompdf->render();
$dompdf->stream('hello.pdf', [
    'compress' => true,
    'Attachment' => false,
]);
?> 
```

**Comment by JurakZdenek** [comment]
Now I see that the Font is not applied to bold.

**Comment by JurakZdenek** [comment]
Gentlemen, solved.
As I noticed that it doesn't apply to bold, I selected all the options on google fonts - bold, italic, regular. He put the code in the HTML and everything started working. Yesterday I sat with it for 6 hours.
from this:
```
<link rel="stylesheet" type="text/css" href="css/PDFfaktura.css">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Rubik+Bubbles&display=swap" rel="stylesheet">
```
to this:
`<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Tinos:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">`

Everything is okay now

![obrazek](https://user-images.githubusercontent.com/74710914/211290138-50461abe-7f0f-4e62-b769-e9d02fb514fe.png)

**Comment by bsweeney** [comment]
Glad you were able to solve the issue. Dompdf does require the specified font family in the used style and weight. Browsers have a bit more functionality around font selection and display which I hope we will be able to support in the future.
