### ISSUE TITLE
Missing Unicode on Helvetica

### ISSUE THREAD

**Issue by Nico-Schaefer-2111** [dompdf/dompdf#3106]
When using U+2076 (= ⁶) with font 'Helvetica' it generates only a questionmark.

**Comment by bsweeney** [comment]
Dompdf currently relies on the core PDF fonts for Helvetica, Times, Courier, and the generic fallbacks (sans-serif, serif, monospace). The core PDF fonts only support Windows ANSI encoding. You'll want to style your text with a font that supports Unicode (e.g. one of the bundled DejaVu fonts).
