### ISSUE TITLE
broken images and css with HTTPS

### ISSUE THREAD

**Issue by KelvinSeverino** [dompdf/dompdf#3113]
I developed the feature to generate pdf in my system.

But it only works correctly when I'm in the DEV environment that uses HTTP, when I move to the Official environment that uses SSL certificate generated by Let's Encrypt it breaks, the images and style.css don't load.

I tried passing the parameters below, but it still doesn't work.
        
        $options = new Options();
        $options->setChroot($projectPath);
        $options->isRemoteEnabled(true);

        $domPdf = new Dompdf($options);
        $domPdf->setBasePath($projectPath);
        
        $context = stream_context_create([
            'ssl' => [
                'allow_self_signed'=> TRUE,
                'verify_peer' => FALSE,
                'verify_peer_name' => FALSE,
            ]
        ]);      
        $domPdf->setHttpContext($context);
     
        $domPdf->loadHtml($htmlFile);

**Comment by bsweeney** [comment]
Would need to see what error is actually generated when attempting to retrieve the image. You can [enable additional debug logging](https://github.com/dompdf/dompdf/wiki/Debugging-Dompdf) to get that information.

**Comment by gadget00** [comment]
in my case the CSS is ignored, and the image error is "Image not found or type unknown"

**Comment by gadget00** [comment]
in my case the CSS is ignored, and the image error is "Image not found or type unknown"

**Comment by bsweeney** [comment]
"Image not found or type unknown" within the PDF? That's the generic message displayed to the user. You would have to enable additional debugging to see what type of error is produced when attempting to access the image.
