### ISSUE TITLE
Image not found or type unkown 

### ISSUE THREAD

**Issue by newmanbhd** [dompdf/dompdf#3114]
Hi Team, 
I have spent over a week trying to solve this problem without any luck. You are my last hope, the power of the internet. 

I am trying to create a pdf of an invoice template via a form. The form works, but I cannot get the logo to print out on the pdf. I have looked at many forums and tried many different scenarios without success. I am hoping there is someone who can see what I cannot see and help display the image 

below is the template invoice.php
```
<?php 
include 'mailer.php';
?>


<html>
<body>
	
	
	<table style="width:700px;height:900px;">
		<tr><td>
		<table>
		<tr><th colspan="5" style="font-size:40px;text-align:center;width:100%;">Tax Invoice2</th></tr>
		<tr><td></td><td></td><td></td><td></td><td><img src="rm-red-Logo-200x151.png"></td></tr>
		<tr><td>&nbsp;</td></tr>
		<tr><td>&nbsp;</td></tr>
		
		<tr><td style="width:200px;font-weight: 700;"><label>Invoice to:</label></td><td style="width:30px;font-weight: 700;">&nbsp;</td><td style="width:300px;font-weight: 700;"><label>Contact Details</label></td><td style="width:30px;">&nbsp;</td><td style="width:150px;font-weight: 700;"><label>Invoice Date:</label></td></tr>
		
		<tr><td >%invto%</td><td ></td><td ><label>Email: %email%</label></td><td >&nbsp;</td><td>%mydate%</td></tr>
		
		<tr ><td rowspan="2">%add1%</td><td >&nbsp;</td><td sytle="vertical-align: top;"><label>Mobile: %mobile%</label></td><td >&nbsp;</td><td><label>Invoice: 0001:</label></td></tr>
		
		<tr><td >&nbsp;</td><td >&nbsp;</td><td >&nbsp;</td><td >&nbsp;</td><td>&nbsp;</td></tr>
		
		
		</table>
		<table style="width:700px;">
			<tr><td colspan="5"><hr>&nbsp;</td></tr>
		<tr ><th style="width:400px;">Description</th><th style="width:50px;">Qty</th><th style="width:50px;">Unit Price</th><th style="width:50px;">GST</th><th style="width:80px;">Amount</th></tr>
			<tr><td colspan="5"><hr>&nbsp;</td></tr>
			<tr><td>%mybin% for hire - %dat3% to %dat5%</td><td>%qty%</td><td align="right">%unit%</td><td align="right">%gst%</td><td align="right">%price%</td></tr>
			<tr><td colspan="5" style="margin-top:10px;margin-bottom:10px;"><hr>&nbsp;</td></tr>
			
		</table>
	</td></tr>
	</table>
</body>
</html>
```

Below is the dompdf section in a file called dompdf.php

```
<?php
use Dompdf\Dompdf;
use Dompdf\Options;
// reference the Dompdf namespace

echo("stage a1 <br>");
require 'vendor/composer/autoload_real.php';
require 'vendor/dompdf/autoload.inc.php';

//use vendor\Dompdf\Options;

// include autoloader

if (isset($Post['submit'])) 
	$instr = $_POST['instructions'];
	$bin = $_POST['mybin'];
    $dat3 = $_POST['date3'];
    $dat5 = $_POST['date5'];
    $add1 = $_POST['address1'];
	$waste = $_POST['waste'];
    $price = number_format($_POST['price'],2);
	echo("stage 2a <br>");
	$email = $_POST['email'];
	$invto = $_POST['invoiceto'];
	$mydate = $_POST['mydate'];
	$mobile = $_POST['mobile'];
	$qty = 1;
	$unit = round(($price/1.1),2);
	$gst = round(($price/11),2);
echo("stage 2b <br>");
 $email_template = 'invoice.html';
 
 $message = file_get_contents($email_template);
 
 $message = str_replace('%invto%',$invto,$message);
 $message = str_replace('%mydate%',$mydate,$message);
 $message = str_replace('%email%',$email,$message);
 $message = str_replace('%mobile%',$mobile,$message);
 $message = str_replace('%mybin%',$bin,$message);
 $message = str_replace('%dat3%',$dat3,$message);
 $message = str_replace('%dat5%',$dat5,$message);
 $message = str_replace('%price%',$price,$message);
 $message = str_replace('%qty%',$qty,$message);
 $message = str_replace('%unit%',$unit,$message);
 $message = str_replace('%gst%',$gst,$message);
 $message = str_replace('%add1%',$add1,$message);

$dompdf = new dompdf();
//$dompdf->getOptions()->setChroot('/var/www/mobilebins/public_html/Rental');

$options = new options();
$dompdf = new dompdf($options);

$dompdf->loadHtml($message);
$dompdf->setPaper('A4', 'portrait');
// (Optional) Setup the paper size and orientation
echo("stage 4 <br>");
// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
ob_end_clean();
$dompdf->stream();

$output= $dompdf->output();
file_put_contents('Invoice2a.pdf', $output);

?>
```

Any any and all help is greatly appreciated

**Comment by bsweeney** [comment]
What is the path for the image? You have a commented-out line to set the chroot path, which you will need for any files retrieved from the filesystem.

**Comment by newmanbhd** [comment]
adding the root path doesn't make any difference, reason why its commented out

**Comment by bsweeney** [comment]
You _will_ need to set the chroot path to a parent directory of the image, so you should uncomment that line regardless. Is it possible the image reference isn't actually pointed to that location? You're using the `load_html` method so the relative path will be based on the location of the dompdf.php file.

Is the Dompdf temp directory accessible?

You can try to determine why the image fails to load by [enabling additional debug messaging](https://github.com/dompdf/dompdf/wiki/Debugging-Dompdf).

**Comment by newmanbhd** [comment]
can you help with the syntax, I have tried a few different things but they don't seem to be doing anything. I added the code to show the errors but it doesn't wrtite to the file only displays on the screen. Not very strong on PHP

See the code below is what I have added to set the paths
`$dompdf = new Dompdf([
    "logOutputFile" => "/vendor/dompdf/dompdf/src/log.html",
    "debugPng" => false, // extra messaging
    "debugKeepTemp" => false, // don't delete temp files
    'debugCss' => false, // output Style parsing information and frame details for every frame in the document
    'debugLayout' => false, // draw boxes around frames
    'debugLayoutLines' => false, // line boxes
    'debugLayoutBlocks' => false, // block frames
    'debugLayoutInline' => false, // inline frames
    'debugLayoutPaddingBox' => false, // padding box
	'enable_remote'         => true,
    'chroot'                => getcwd() . '/var/www/mobilebins/public_html/Rental/vendor/dompdf/dompdf/src/',
	'rootDir'               => getcwd() . '/var/www/mobilebins/public_html/Rental/vendor/dompdf/dompdf/src/',
    'isHtml5ParserEnabled'  => true,
	'isPhpEnabled'	 		=> true
]);
`

**Comment by bsweeney** [comment]
Seeing the errors on-screen is better than not seeing them at all while you debug. If you copied the debug configuration as-is then you can just exclude the `ini_set("display_errors", true);` line to prevent writing to the screen.

A few notes:
* chroot should probably be something like "/var/www/mobilebins/public_html/" (if the "var" directory is at the root of your filesystem)
* you don't need to modify the rootDir
* specifying the logOutputFile with a starting "/" indicates that the file is in the root of the filesystem, which seems unlikely based on the path you specified try just "log.html" and the file should be written to the same directory where your script resides
* also generally recommend not writing anything to the vendor directory since that's managed by Composer

Lastly, just making sure, include these lines to get the full set of potential messages:
```
ini_set("error_log", "phperr.log");
ini_set("log_errors", true);
error_reporting(E_ALL);
$_dompdf_show_warnings = true;
```

**Comment by newmanbhd** [comment]
I tried what you suggested and even a few other things Again with no lock. It still cannot find the image file. I have tried png and jpg formats. Below is the code. Your help is greatly appreciated

> 

`<?php
ob_start();


use Dompdf\Dompdf;
use Dompdf\Options;
// reference the Dompdf namespace

echo("stage a1 <br>");
require 'dompdf/autoload.inc.php';
echo("stage a1A <br>");


ini_set("display_errors", true);
ini_set("error_log", "phperr.log");
ini_set("log_errors", true);
error_reporting(E_ALL);

$_dompdf_show_warnings = true; // record warnings generated by Dompdf
$_dompdf_debug = false; // output frame details for every frame in the document
$_DOMPDF_DEBUG_TYPES = ['page-break' => false // record information about page break determination
];

if (isset($Post['submit'])) 
	
 $email_template = file_get_contents("/var/www/mobilebins/public_html/Rental/invoice.html");
 
 $message = ($email_template);
 
$dompdf = new dompdf([
    "logOutputFile" => "log.html",
    "debugPng" => false, // extra messaging
    "debugKeepTemp" => false, // don't delete temp files
    'debugCss' => false, // output Style parsing information and frame details for every frame in the document
    'debugLayout' => false, // draw boxes around frames
    'debugLayoutLines' => false, // line boxes
    'debugLayoutBlocks' => false, // block frames
    'debugLayoutInline' => false, // inline frames
    'debugLayoutPaddingBox' => false, // padding box
     'enable_remote'         => true,
    'chroot'                => getcwd() . 'var/www/mobilebins/public_html/Rental/',
	'isHtml5ParserEnabled'  => false,
	'isPhpEnabled'	 		=> true,
	]);

$options = new options();
echo("stage 2db <br>");
$dompdf = new dompdf($options);

$dompdf->loadHtml($message);
$dompdf->setPaper('A4', 'portrait');

$dompdf->render();
// Output the generated PDF to Browser
ob_end_clean();
$dompdf->stream();
?>
'
> 

Below is the html file

`
<body>

	<table style="width:700px;height:900px;">
		<tr><td>
		<table style="width:700px;">
		<tr><th colspan="5" style="font-size:40px;text-align:center;width:100%;background-color: red; color:white;margin-bottom:40px;">Tax Invoice</th></tr>
		<tr style="margin-top:40px;"><td><img src="/var/www/mobilebins/public_html/Rental/rm-red-Logo-200x151.jpg" /></td><td></td><td></td><td></td><td style="background-color: red; color:white;">Rent Me Aust Pty Ltd <br>12/70 Holbeche Rd <br>Arndell Park <br> NSW 2148</td></tr>
		<tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
		<tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
		
		<tr><td style="width:200px;font-weight: 700;"><label>Invoice to:</label></td><td style="width:25px;font-weight: 700;">&nbsp;</td><td style="width:300px;font-weight: 700;"><label>Contact Details</label></td><td style="width:25px;">&nbsp;</td><td style="width:150px;font-weight: 700;"><label>Invoice Date:</label></td></tr>
		
		<tr><td >%invto%</td><td ></td><td ><label>Email: %email%</label></td><td >&nbsp;</td><td>%mydate%</td></tr>
		
		<tr ><td rowspan="2">%add1%</td><td >&nbsp;</td><td sytle="vertical-align: top;"><label>Mobile: %mobile%</label></td><td >&nbsp;</td><td><label>Invoice: 0001:</label></td></tr>
		
		<tr><td >&nbsp;</td><td >&nbsp;</td><td >&nbsp;</td><td >&nbsp;</td></tr>
		
		
		</table>
		
</body>

`

**Comment by acidhexe** [comment]
With cakePdf as engine dompdf.
Here the same problem are two days trying to add a picture png or jpg, no chance ... all path spellings through ... url in debug is correct ... what else can I test?

**Comment by bsweeney** [comment]
Why are you instantiating Dompdf twice in your PHP? The second instance doesn't have any of the options. Also, looks like you're missing the braces around the body of the `if` statement.

Try the following PHP:
```
<?php
ini_set("display_errors", true);
ini_set("error_log", "phperr.log");
ini_set("log_errors", true);
error_reporting(E_ALL);

// reference the Dompdf namespace
use Dompdf\Dompdf;
use Dompdf\Options;

require "dompdf/autoload.inc.php";
$_dompdf_show_warnings = true; // record warnings generated by Dompdf

if (isset($Post['submit'])) {
    $message = file_get_contents("/var/www/mobilebins/public_html/Rental/invoice.html");
 
    $dompdf = new dompdf([
        "logOutputFile" => "log.html",
        "enable_remote" => true,
        "chroot"        => "/var/www/mobilebins/public_html/Rental/",
    ]);

    $dompdf->loadHtml($message);
    $dompdf->setPaper("A4", "portrait");

    $dompdf->render();
    $dompdf->stream();
}
?>
```

**Comment by acidhexe** [comment]
OK! i caught the bug :)
in dompdf/src/Image/cache.php
in my case line 80-90
comment out the foreach block and add $protocol hard coded, not flexible but helps for now.
                      
```
    /*
    foreach ($allowed_protocols[$protocol]["rules"] as $rule) {
	    [$result, $message] = $rule($full_url);
	    if (!$result) {
		    throw new ImageException("Error loading $url: $message", E_WARNING);
	    }
    }
    */
}
$protocol = 'http://';
```
... hope it helps!

**Comment by bsweeney** [comment]
I mean sure, you _can_ do that. However, that logic is there to help protect you from malicious end user activity so I would not recommend it. The message you get from that exception should indicate why the image failed to load. Once you have that info you just need to tweak your options to allow the image to pass validation.

**Comment by newmanbhd** [comment]
Well Done acidhexe 

That did the trick

**Comment by acidhexe** [comment]
> exception

Of course it is not clean and safe that the validation is deactivated, but in my case the function is called without user input. Are you sure the exception is thrown correctly? had the feeling that she always throws. Does the foreach look a bit strange to me or do I have to define the rule somewhere?

**Comment by acidhexe** [comment]
@bsweeney 
Of course it is not clean and safe that the validation is deactivated, but in my case the function is called without user input. Are you sure the exception is thrown correctly? had the feeling that she always throws. Does the foreach look a bit strange to me or do I have to define the rule somewhere?

**Comment by bsweeney** [comment]
The [default rules](https://github.com/dompdf/dompdf/blob/master/src/Options.php#L1108-L1158) are currently [assigned](https://github.com/dompdf/dompdf/blob/v2.0.1/src/Options.php#L573-L593) in Options.php. Local file access requires that the file be under one of the paths specified for chroot. Remote file access requires that isRemoteEnabled be true.

You can also specify your own rules, overriding the defaults.
