### ISSUE TITLE
How to use cursive fonts family with dompdf 

### ISSUE THREAD

**Issue by a-akashsoni** [dompdf/dompdf#3116]
I tried to convert HTML to PDF using dompdf. But it does not work with  Chomsky font family and LT Comical font family . I need to use these particular font families. Kindly give your reference for this , how to use these cursive fonts in the dompdf. 
 
 Thanks..

**Comment by bsweeney** [comment]
What have you tried so far?

**Comment by a-akashsoni** [comment]
I have tried these fonts family but it does not work. While converting it changes to default fonts but cursive fonts are not working.

**Comment by bsweeney** [comment]
Yes, but how have you tried? Sample HTML?

**Comment by a-akashsoni** [comment]
Kindly check the sample html below. 

`<html>
<body>




<!DOCTYPE html>
  | <html lang="en">
  |  
  | <head>
  | <title></title>
  | <meta charset="UTF-8">
  | <meta name="viewport" content="width=device-width, initial-scale=1">
  | <link rel="preload" href="fonts/transfonter.org-20221201-054935/" as="font" type="font/woff2" crossorigin>
  | <link rel="preload" href="fonts/transfonter.org-20221201-053057/" as="font" type="font/woff2" crossorigin>
  |  
  | </head>
  | <style>
  | @font-face {
  | font-family: 'Chomsky';
  | src: url('fonts/Chomsky.woff2') format('woff2'), url('fonts/Chomsky.woff') format('woff');
  | font-weight: normal;
  | font-style: normal;
  | font-display: swap;
  | }
  |  
  | @font-face {
  | font-family: 'LT Comical';
  | src: url('fonts/LTComical-Medium.woff2') format('woff2'), url('fonts/LTComical-Medium.woff') format('woff');
  | font-weight: 500;
  | font-style: normal;
  | font-display: swap;
  | }
  |  
  | * {
  | padding: 0;
  | box-sizing: border-box;
  | margin: 0;
  | }
  |  
  | body {
  | width: 29.7cm;
  | height: 41cm;
  | margin: 0 auto;
  | display: block;
  | }
  |  
  |  
  | </style>
  |  
  | <body>
  | <table style="width: 100%; border-spacing: 0;background-color: #ffeeb6;">
  | <tbody>
  | <tr>
  | <td><img src="./images/multi-color-background.png" style="width: 100%; display: block;"></td>
  | </tr>
  | </tbody>
  | </table>
  |  
  | <table style="width: 100%;background-color: #ffeeb6;">
  | <tbody style="position: relative; top: -65px;">
  | <tr>
  | <td><img src="./images/Group-img.png" style="width: 100%;max-width: 120px;display: block;"></td>
  | </tr>
  |  
  | <tr>
  | <td style="font-family: 'Chomsky';color: #536a32;font-size: 44px;font-weight: 100;text-align: center;     line-height: 46px; text-align: center;margin: 0 auto; display:block; margin-top: -90px;">Certificate of Disposition and Proclamation</td>
  | </tr>
  | <tr>
  | <td style="font-family: 'LT Comical';color: #000;font-size: 18px;font-weight: 100;text-align: center;     line-height: 46px; text-align: center;margin: 0 auto; display:block; margin-top: -30px;
  | ">between Scotland Titles,
  | Unit 61892, PO Box 26965, Glasgow G1 9BW United Kingdom and</td>
  | </tr>
  |  
  | <tr>
  |  
  | <td style="font-family: 'Chomsky';color: #10094c;font-weight: 100;font-size: 50px;margin-top: 0;text-align: center; line-height: 60px; text-align: center;margin: 0 auto; display:block;">Lady Craig Edward Smith of Blairadam</td>
  | </tr>
  | <tr style="text-align: center;max-width: 30px;margin: 0 auto; display:block;">
  | <td style="font-family: 'Chomsky';color: #000;font-size: 20px;font-weight: 100;text-align: center;     line-height: 46px;">and</td>
  | </tr>
  | <tr style="text-align: center;max-width: 0px;margin: 0 auto; align-items:center;">
  | <td style="font-family: 'Chomsky';color: #536a32;font-size: 36px;font-weight: 100;text-align: center;     line-height: 46px;"><span style="color:#10094c; font-size: 50px;">Lady Kevin Michael Smith of Blairadam</td>
  | </tr>
  |  
  | <tr style="text-align: center;max-width: 0px;margin: 0 auto; align-items:center;">
  | <td style="font-family: 'LT Comical';color: #000;font-size: 36px;font-weight: 100;text-align: center;     line-height: 46px;"><span style="color:#10094c; font-size: 18px;">(here after to be proclaimed as “THE LADIES”),care of Unit 61892, PO Box 26965, Glasgow G1 9BW United Kingdom</td>
  | </tr>
  |  
  | <tr>
  | <td style=" padding-top: 0px; text-align: center";>
  | <img src="./images/yellow-icon.png" style="max-width: 160px;width: 100%;display: block;margin: 0 auto; "></td>
  | </tr>
  | </tbody>
  | </table>
 

<br class="Apple-interchange-newline">
</body>
</html><!DOCTYPE html>
<html lang="en">

<head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preload" href="[fonts/transfonter.org-20221201-054935/](https://github.com/dompdf/dompdf/issues/fonts/transfonter.org-20221201-054935/)" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="[fonts/transfonter.org-20221201-053057/](https://github.com/dompdf/dompdf/issues/fonts/transfonter.org-20221201-053057/)" as="font" type="font/woff2" crossorigin>

</head>
<style>
    @font-face {
        font-family: 'Chomsky';
        src: url('fonts/Chomsky.woff2') format('woff2'), url('fonts/Chomsky.woff') format('woff');
        font-weight: normal;
        font-style: normal;
        font-display: swap;
    }
    
    @font-face {
        font-family: 'LT Comical';
        src: url('fonts/LTComical-Medium.woff2') format('woff2'), url('fonts/LTComical-Medium.woff') format('woff');
        font-weight: 500;
        font-style: normal;
        font-display: swap;
    }
    
    * {
        padding: 0;
        box-sizing: border-box;
        margin: 0;
    }
    
    body {
        width: 29.7cm;
        height: 41cm;
        margin: 0 auto;
        display: block;
    }
    
    
</style>

<body>
    <table style="width: 100%; border-spacing: 0;background-color: #ffeeb6;">
        <tbody>
            <tr>
                <td><img src="[./images/multi-color-background.png](https://github.com/dompdf/dompdf/issues/images/multi-color-background.png)" style="width: 100%; display: block;"></td>
            </tr>
        </tbody>
    </table>

    <table style="width: 100%;background-color: #ffeeb6;">
        <tbody style="position: relative; top: -65px;">
            <tr>
                <td><img src="[./images/Group-img.png](https://github.com/dompdf/dompdf/issues/images/Group-img.png)" style="width: 100%;max-width: 120px;display: block;"></td>
            </tr>

            <tr>
                <td style="font-family: 'Chomsky';color: #536a32;font-size: 44px;font-weight: 100;text-align: center;     line-height: 46px; text-align: center;margin: 0 auto; display:block; margin-top: -90px;">Certificate of Disposition and Proclamation</td>
            </tr>
			 <tr>
                <td style="font-family: 'LT Comical';color: #000;font-size: 18px;font-weight: 100;text-align: center;     line-height: 46px; text-align: center;margin: 0 auto; display:block; margin-top: -30px;
">between Scotland Titles,
                 Unit 61892, PO Box 26965, Glasgow G1 9BW United Kingdom and</td>
            </tr>
			  
            <tr>
			  
                <td style="font-family: 'Chomsky';color: #10094c;font-weight: 100;font-size: 50px;margin-top: 0;text-align: center; line-height: 60px; text-align: center;margin: 0 auto; display:block;">Lady Craig Edward Smith of Blairadam</td>
            </tr>
			<tr style="text-align: center;max-width: 30px;margin: 0 auto; display:block;">
                <td style="font-family: 'Chomsky';color: #000;font-size: 20px;font-weight: 100;text-align: center;     line-height: 46px;">and</td>
            </tr>
			<tr style="text-align: center;max-width: 0px;margin: 0 auto; align-items:center;">
                <td style="font-family: 'Chomsky';color: #536a32;font-size: 36px;font-weight: 100;text-align: center;     line-height: 46px;"><span style="color:#10094c; font-size: 50px;">Lady Kevin Michael Smith of Blairadam</td>
            </tr>
			
			<tr style="text-align: center;max-width: 0px;margin: 0 auto; align-items:center;">
                <td style="font-family: 'LT Comical';color: #000;font-size: 36px;font-weight: 100;text-align: center;     line-height: 46px;"><span style="color:#10094c; font-size: 18px;">(here after to be proclaimed as “THE LADIES”),care of Unit 61892, PO Box 26965, Glasgow G1 9BW United Kingdom</td>
            </tr>
					
            <tr>
                <td style=" padding-top: 0px; text-align: center";>
                    <img src="[./images/yellow-icon.png](https://github.com/dompdf/dompdf/issues/images/yellow-icon.png)" style="max-width: 160px;width: 100%;display: block;margin: 0 auto; "></td>
            </tr>
        </tbody>
    </table>`

Kindly check the sample html and guide me for correct way to use these font families. 

Thanks

**Comment by bsweeney** [comment]
Dompdf does not currently support the woff format. You'll want to use a TrueType version of the font.
