### ISSUE TITLE
CheckBox render error Bootstrap 5.2.3

### ISSUE THREAD

**Issue by Ghibba** [dompdf/dompdf#3118]
Good Evening,

I've found a problem rendering a checkbox with this library. 
Could someone help me ?

This is html code:

```
<div class="sottorisposta_flag d-flex align-items-center mb-2" style="margin-top: 0px;">
        <input class="form-check-input mt-0 me-2 " style="font-size: 28px; cursor: pointer;" checked type="checkbox" name="check_1" value="True" id="check_1" autocomplete="off" />
</div> 
```

and this is the html result:

![image](https://user-images.githubusercontent.com/123496197/214371832-d4367068-1cba-4bee-a1c5-2ccac7ed4253.png)

but when I try to transform in a pdf file that's the result:

![image](https://user-images.githubusercontent.com/123496197/214372500-fa8ec999-15e7-4f38-9d10-d3bfa6e930b7.png)

**Comment by bsweeney** [comment]
There are a number of CSS features that Dompdf doesn't currently support that Bootstrap utilizes. A big one for Bootstrap-styled documents is box-sizing, which means that the alignment is never going to be quite right. Checkbox rendering is also problematic because Dompdf uses a character glyph and not a control.

You don't specify which version of Dompdf. I recommend using the latest.

You can get a better render with some custom styling, though perhaps still not perfect. Here's what I get with just a bit of effort when using Dompdf 2.0.1:

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <style>
    input[type="checkbox"].form-check-input:checked {
      color: white;
    }
    input[type="checkbox"].form-check-input:checked:before {
      display: inline-block;
      margin: -.35em 0 0 .15em;
      content: "\2714";
    }
  </style>
</head>
<body>
  <input class="form-check-input" checked type="checkbox" />
  <input style="font-size: 200%" class="form-check-input" checked type="checkbox" />
</body>
</html>
```
![bootstrap-checks](https://user-images.githubusercontent.com/485897/214377885-08cb8e2d-ff74-4764-b26b-8e85786f331f.png)

**Comment by Ghibba** [comment]
> There are a number of CSS features that Dompdf doesn't currently support that Bootstrap utilizes. A big one for Bootstrap-styled documents is box-sizing, which means that the alignment is never going to be quite right. Checkbox rendering is also problematic because Dompdf uses a character glyph and not a control.
> 
> You don't specify which version of Dompdf. I recommend using the latest.
> 
> You can get a better render with some custom styling, though perhaps still not perfect. Here's what I get with just a bit of effort when using Dompdf 2.0.1:
> 
> ```
> <!DOCTYPE html>
> <html>
> <head>
>   <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
>   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
>   <style>
>     input[type="checkbox"].form-check-input:checked {
>       color: white;
>     }
>     input[type="checkbox"].form-check-input:checked:before {
>       display: inline-block;
>       margin: -.35em 0 0 .15em;
>       content: "\2714";
>     }
>   </style>
> </head>
> <body>
>   <input class="form-check-input" checked type="checkbox" />
>   <input style="font-size: 200%" class="form-check-input" checked type="checkbox" />
> </body>
> </html>
> ```
> 
> ![bootstrap-checks](https://user-images.githubusercontent.com/485897/214377885-08cb8e2d-ff74-4764-b26b-8e85786f331f.png)


Thank you very much for the support.
I'm using the latest version of dompdf.
Like you've just said, problably dompdf not support scss features of Bootstrap, however  your **custum styling** using **negative margin** solved my problem.
