### ISSUE TITLE
 Incorrect font rendering in DOMPDF

### ISSUE THREAD

**Issue by bhupesh7shakya** [dompdf/dompdf#3119]
When using a specific font in a document that is being converted to a PDF using DOMPDF, the font does not render correctly. The characters appear distorted or are replaced with a different font

**Comment by bsweeney** [comment]
Do you have a sample?

**Comment by AbderrezakZed** [comment]
Use
 `$options = new Options();`
`$options->set('default-Font','Courier);`
 @bhupesh7shakya

**Comment by bhupesh7shakya** [comment]
>yes like 
this is the html view 
![image](https://user-images.githubusercontent.com/54110001/218267113-d164b27b-6d2a-4496-81f9-fd6784a1b2ad.png)
pdf view
![image](https://user-images.githubusercontent.com/54110001/218267178-76ee437d-cdd4-415f-8561-a4845442db34.png)
and like many more

**Comment by bsweeney** [comment]
That's expected since, currently, Dompdf does not fully support complex text layout. Watch #2619 for updates.

Also, just a note: it's more helpful if you provide HTML samples as text in case we need to try and debug.

**Comment by bhupesh7shakya** [comment]
<p>अहिले कार्यान्वयनको चरणमा रहेको नेपालको संघीय प्रणालीमा एकभन्दा बढी संसद् र <p/>

**Comment by bkkrishna** [comment]
Seems like it's going to take some time to work on the feature. Hi there @bhupesh7shakya, any workarounds at the moment?

**Comment by bhupesh7shakya** [comment]
> Seems like it's going to take some time to work on the feature. Hi there @bhupesh7shakya, any workarounds at the moment?

yeah for now i am gernerating it from frontend html2pdf right now there no single library in php that support actually support clear other language until now that i search till the date

**Comment by bkkrishna** [comment]
>> yeah for now i am gernerating it from frontend right now there no single library in php that support actually support clear other language until now that i search till the date

Just found an easy [mPDF based package](https://github.com/niklasravnsborg/laravel-pdf) to deal with the issue. Here available fonts like freesans & freeserif need no additional effort to implement Indic (various languages inside Indian sub-continent) unicode characters . I'm loving using it. Hope that helps someone who stumbles upon this issue.

<img width="846" alt="Screenshot 2023-02-26 at 10 31 02 PM" src="https://user-images.githubusercontent.com/8872069/221424687-32a5692c-7c07-4d94-8cf4-bde346427858.png">
