### ISSUE TITLE
Uninitialized string offset 17

### ISSUE THREAD

**Issue by dorkyboi** [dompdf/dompdf#3121]
Hi, I am trying to make a PDF out of my Blade file, but I am having this exception:
![image](https://user-images.githubusercontent.com/23461412/215490529-4b9ad7d7-dec2-43f2-bad5-53456dcb0a8d.png)
<details>
  <summary>Debug information</summary>
  <img src="https://user-images.githubusercontent.com/23461412/215490646-65808316-2c8f-42a8-a78e-7a459a0f2313.png"/>
  <img src="https://user-images.githubusercontent.com/23461412/215491167-0324c8bf-21e1-467d-8141-3675b544b51d.png"/>
</details>

I wonder if this is a bug or am I simply doing something wrong?

**Comment by bsweeney** [comment]
This looks to be the same as #3019. Essentially, Dompdf does not support the calc method and as a result is parsing that value incorrectly. I'm prepping a release that addresses the parsing issue (though not the lack of calc support).
