### ISSUE TITLE
text-align: right; CSS class not working for me

### ISSUE THREAD

**Issue by HeadStudios** [dompdf/dompdf#3122]
I am attempting to align some text on an agreement document to the right in the header in Laravel DomPDF wrapper - the blade from which the agreement is loaded can be viewed below:
https://gist.github.com/HeadStudios/42bc330f7df3fdc24483dbf58b285994 (please take note of the lines starting at 71)

The final output PDF is as follows: 
https://www.docdroid.net/lCfPmEe/shakashaka-2-pdf

Any input on my challenge of alignment would be much appreciated.

Thank you!

**Comment by bsweeney** [comment]
You can't text-align: right the content of an inline element since it's width is the width of the content. Play around with the layout in HTML to get closer to your desired layout.

At any rate, try float: right and see what you think.

**Comment by HeadStudios** [comment]
Hi Brian,

Thank you - I can confirm float:right; has fixed my issue. Also appreciate the idea of rendering the HTML in Laravel route prior to loading PDF to troubleshoot issues.
