### ISSUE TITLE
utf-8 encoding??? "ő" is just a "?"

### ISSUE THREAD

**Issue by Siposattila** [dompdf/dompdf#3126]
Even if I use ```mb_convert_encoding($this->renderView("example.html.twig", ["data" => $data]), "HTML-ENTITIES", "UTF-8");``` the character "ő" is just a question mark. What can I do about it? ```<meta charset="utf-8" />``` is set in my html document so as far as I know thats not a problem because dompdf should autodetect utf-8 in loadHtml.

I use ```font-family: sans-serif;``` as my font.

**Comment by bsweeney** [comment]
The core PDF fonts do not support Unicode characters. You'll want to use a font that supports the characters in your document. DejaVu Sans should work for this particular character, see the [font samples](https://dejavu-fonts.github.io/Samples.html) for all supported characters. More info is available in the wiki:
- [About Fonts and Character Encoding](https://github.com/dompdf/dompdf/wiki/About-Fonts-and-Character-Encoding)
- [Unicode How-To](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo)
