### ISSUE TITLE
Font showing on HTML preview but not on final PDF

### ISSUE THREAD

**Issue by HeadStudios** [dompdf/dompdf#3128]
I have a PDF preview mode which can be viewed in the URL below - please take note specifically of the 'Prepared By' and 'Prepared For' headings at the top fo the first page:
https://dev1.rrdevours.monster/playwithme

And below is the page once it's rendering with DomPDF:
https://www.docdroid.net/aRlbLDZ/shakashaka-6-pdf

Please note the missing font on the Prepared For and Prepared By headings. I'm not sure why the fonts are not working here but are working on the HTML preview.

Any input or advice would be much appreciated.

Thank you!

**Comment by bsweeney** [comment]
Your `@font-face` declarations are not sufficient for Dompdf. For example, your Monserrat declarations are:

```
@font-face {
    font-family: 'Montseratt Bold';
    src: url('fonts/mont-bold.ttf') format('truetype');
}

@font-face {
    font-family: 'Montseratt';
    src: url('fonts/mont-regular.ttf') format('truetype');
}
```

An H3 element is actually styled with a font-weight of bold, so Dompdf is looking for the bold version of the font, which you have not declared. You should fully fill out the declarations to make them compatible with Dompdf.

```
@font-face {
    font-family: 'Montseratt Bold';
    font-style: normal;
    font-weight: bold;
    src: url('fonts/mont-bold.ttf') format('truetype');
}

@font-face {
    font-family: 'Montseratt';
    font-style: normal;
    font-weight: normal;
    src: url('fonts/mont-regular.ttf') format('truetype');
}
```

The reason you're getting different results from your browser when rendering in Dompdf is that the font matching logic is fairly rudimentary. While the browser will go through various versions of a font before falling back, Dompdf only looks for an exact match. Issue #2817 will be used to track work on that improvement.

**Comment by HeadStudios** [comment]
Thank you so much! I can confirm this has fixed my problems.
