### ISSUE TITLE
Font Dejavu Sans breaks the page

### ISSUE THREAD

**Issue by Aleksoge** [dompdf/dompdf#3129]
How fix it https://sked.ald-art.org/createWeekPdf.php
I installed this with composer 

```
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);

require 'vendor/autoload.php';
use Dompdf\Dompdf;
use Dompdf\Options;
$options = new Options();
$options->set('defaultMediaType', 'UTF-8');
$options->set('isHtml5ParserEnabled', true);
$options->set('isFontSubsettingEnabled', true);
$options->set('defaultFont', 'DejaVu Sans');

$dompdf = new Dompdf($options);

$htmlPDF = '
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
      body {
        font-family: DejaVu Sans;
      }
      table {
        border-collapse: collapse;
        width: 100%;
      }
      th, td {
        border: 1px solid black;
        padding: 8px;
        text-align: left;
      }
      th {
        background-color: #f2f2f2;
      }
    </style>
  </head>
  <body>
    <table>
      <thead>
        <tr>
          <th>Колонка 1</th>
          <th>Колонка 2</th>
          <th>Колонка 3</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Колонка 1</td>
          <td>Колонка 2</td>
          <td>Колонка 3</td>
        </tr>
        <tr>
          <td>Колонка 1</td>
          <td>Колонка 2</td>
          <td>Колонка 3</td>
        </tr>
        <tr>
          <td>Колонка 1</td>
          <td>Колонка 2</td>
          <td>Колонкаn 3e</td>
        </tr>
      </tbody>
    </table>
  </body>
</html>
';

$dompdf->loadHtml($htmlPDF, 'UTF-8');

$dompdf->render();

$TableName = generateRandomString();
$output = $dompdf->output();
$dompdf->stream('hello.pdf', [
    'compress' => true,
    'Attachment' => false,
]);
```

**Comment by Aleksoge** [comment]
Code insert doesn't work, sorry for the crooked insertion of the code into the text

**Comment by bsweeney** [comment]
You error seems to indicate that the default temp directory is not writeable. Since you have font subsetting enabled Dompdf needs to be able to write data somewhere. You can specify a directory using the following option: `$options->set('tempDir', '/writeable/path');`.

**Comment by Aleksoge** [comment]
> You error seems to indicate that the default temp directory is not writeable. Since you have font subsetting enabled Dompdf needs to be able to write data somewhere. You can specify a directory using the following option: `$options->set('tempDir', '/writeable/path');`.

I's dont work :( Nothing changes, the path is indicated, the rights are set to 777, it does not work

**Comment by Aleksoge** [comment]
> You error seems to indicate that the default temp directory is not writeable. Since you have font subsetting enabled Dompdf needs to be able to write data somewhere. You can specify a directory using the following option: `$options->set('tempDir', '/writeable/path');`.

THANKS!
