### ISSUE TITLE
filtered data 

### ISSUE THREAD

**Issue by asifrashid09** [dompdf/dompdf#3134]
i want to filter pdf of filtered data fro my table so i used this query
$this->applicantawardsheets = User_Details::where('advertisement_no',$this->advertisement_no)
->where('post_applied',$this->post_applied)
->get();
but is not working . because $this->advertisement_no return null.

i watched all tutorials on dompdf but all used ::all() query .

**Comment by bsweeney** [comment]
This doesn't really seem like a Dompdf issue. Also, you're not providing nearly enough detail for anyone to know how to help you. Suggest you focus just on generating the HTML before you try to use Dompdf.
