### ISSUE TITLE
Fatal error: Uncaught Error: Class "Masterminds\HTML5"

### ISSUE THREAD

**Issue by JeyjooMilano** [dompdf/dompdf#3138]
Hi,

I installed Dompdf via Git and have the following error:

```
Fatal error: Uncaught Error: Class "Masterminds\HTML5" not found in /myroot/dompdf/src/Dompdf.php:477
Stack trace:
  #0 /myroot/create_polizza.php(65): Dompdf\Dompdf->loadHtml()
  #1 {main} thrown in /myroot/dompdf/src/Dompdf.php on line 477
```

Any ideas? As far as I can see, mastermind is not a dependency.

Thanks

**Comment by bsweeney** [comment]
If you pull the source directly from the git repository you still need to install and load the dependencies.

The easiest way to do this is using Composer. You just execute `composer update` from the dompdf directory. Then to run Dompdf just require vendor/autoload.php.

If you're not using composer I recommend you download a [packaged release](https://github.com/dompdf/dompdf/releases) or the [nightly](http://eclecticgeek.com/dompdf/dompdf_nightly.zip).
