### ISSUE TITLE
Better OTF Font Support

### ISSUE THREAD

**Issue by robvanderlee** [dompdf/dompdf#3141]
I've tested and successfully loaded OTF fonts for PDF's using DomPDF by telling through `@font-face` that the font is truetype. Fontlib fetches the file header and loads OTF's fine. I'd like to see better support for OTF fonts.

I've also noticed that a lot of OTF fonts subsetting does not work like intended even though OTF fonts support subsetting fine. I'd like to look into this and contribute if I find a viable solution. Any info on the subject would be nice gather here.

**Comment by bsweeney** [comment]
You can start by reading through #932. I'm working on some stylesheet parsing updates and I can add "opentype" to the supported formats while I'm in there. If any real work needs to be done it would either by in Cpdf related to embedding the font, or php-font-lib to address the subsetting issue.

I recommend you start by [creating a new issue in php-font-lib](https://github.com/dompdf/php-font-lib/issues/new) to look at the subsetting issue.

**Comment by robvanderlee** [comment]
I've already read #932 and that lead me to be able to use OTF fonts. I will look into submitting a new issue over at `php-font-lib` later. However, for proper OTF support things like `src/Css/Stylesheet.php:1459`, that specifically looks for truetype would also need to change.

Fontllib from what I've gathered should be able to support TTF, OTF and WOFF.

The end result at the moment would be the same as `FontLib\OpenType\File` extends `FontLib\TrueType\File` without additional logics.

**Comment by bsweeney** [comment]
FYI you do not need to open a new issue if one already exists. You can respond to that issue.

> However, for proper OTF support things like `src/Css/Stylesheet.php:1459`, that specifically looks for truetype would also need to change.

As I mentioned, I'm working on some stylesheet parsing updates and I can add "opentype" to the supported formats while I'm in there.

**Comment by robvanderlee** [comment]
@bsweeney is there a est. on your current work for OTF or can I contribute code in some way?

**Comment by bsweeney** [comment]
I should clarify. I'm not doing anything with OTF I'm just working on stylesheet parsing updates. Adding just enough logic for Dompdf to recognize OTF as a valid type is pretty minimal ([ref truetype usage in the code](https://github.com/dompdf/dompdf/search?q=truetype)). But since I haven't fully analyzed the issue I don't know if anything more would need to be done.
