### ISSUE TITLE
Automated unicode range determination in font loading and selection

### ISSUE THREAD

**Issue by robvanderlee** [dompdf/dompdf#3142]
I've seen that DomPDF currently does not support [font fallback](https://css-tricks.com/css-basics-fallback-font-stacks-robust-web-typography/). This would be a great addition to the library. I will try to find a solution to this problem. This would make issues [like](https://github.com/dompdf/dompdf/issues/2959) [these](https://github.com/dompdf/dompdf/issues/2146) easier to solve. It would greatly improve the usability of DomPDF.

Any input on this issue would be great to have.

**Comment by bsweeney** [comment]
Dompdf does support font fallback. Font fallback doesn't mean that if the font doesn't support a character then the fallback is used. Fallback means that if a specified font isn't available at all then the fallback is used.

I believe what you're interested in seeing implemented is Unicode range support (#913), where a range of supported characters is specified for a font such that the font is only used for those characters, and fallbacks are used for other characters.

Suggest you start by reading through #913. Support for this would require updating various parts of Dompdf. To start I believe we would need the following (at a high level):
- Css/Stylesheet: support range handling
- Css/Style: support range during font selection
- FrameReflower/Text: break text into separate frames based on the defined ranges, as applied to the block through the font-family declaration
- Renderer/Text: rendering with the appropriate font based on the range contained in the frame

**Comment by robvanderlee** [comment]
@bsweeney this is not what my issue is aiming at. Our usecase is quite broad as our system has a wide range of characters that we need to support, CJK included. The fields that contain these characters are not marked with a class or handled without specific logics to determine what font to be used. This results in fields like names, places to break when trying to use fonts as they don't fallback like CSS would in the browser.

My suggestion, as a solution to this problem, is to mimic the same behavior a browser would have. I've made a WIP where I was able to create this behavior. I specifically use the subsetting feature for this and compare the string against the subtables of the font. Resulting in being able to specify a CSS font-family fallback. Let me provide a sample and working pdf that should bring my intention across.

The html file is what results in the PDF.

* [fallback-css.pdf](https://github.com/dompdf/dompdf/files/10825294/fallback-css.pdf)
* [fallback-css.html.txt](https://github.com/dompdf/dompdf/files/10825299/fallback-css.html.txt)

**Comment by robvanderlee** [comment]
> Font fallback doesn't mean that if the font doesn't support a character then the fallback is used.

This is exactly the functionality I'm aiming at. Not the font fallback on file level implementation you are referring to.

**Comment by bsweeney** [comment]
So what you want is automated unicode-range support. Which, OK, that seems like a reasonable request. However, from my perspective the requirements still stand. First unicode-range would have to be implemented. Then we would need to update the font loading logic in Dompdf to support generating the appropriate unicode-range if none is specified.

I still think just adding support for unicode range is sufficient. You do not need to mark anything with classes for it to work. You just need to declare your fonts with ranges.

Using your example:
```
<!doctype html>
<html>
    <head>
        <style>
            @font-face {
                font-family: 'Noto Sans JP';
                font-style: normal;
                font-weight: 400;
                src: url(https://fonts.gstatic.com/ea/notosansjp/v5/NotoSansJP-Regular.otf) format('truetype');
                unicode-range: U+3000-U+303F
            }
        </style>
        <style>
            @font-face {
                font-family: 'Great Vibes';
                font-style: normal;
                font-weight: 400;
                src: url(https://www.1001fonts.com/download/font/great-vibes.regular.ttf) format('truetype');
                unicode-range: U+0080-U+00FF
            }
        </style>
        <style>
            body {
                font-family: 'Great Vibes', 'Noto Sans JP', serif;
            }
            .with-class {
                font-family: 'Noto Sans JP', serif;
            }
        </style>
    </head>
    <body>
        <p>This is great vibes font rendered text.</p>
        <p>能登半島</p>
        <p class="with-class">能登半島</p>
    </body>
</html>
```

Note that the Unicode range I provided for Noto Sans JP is not accurate. Better to just [use their stylesheet](https://fonts.googleapis.com/css2?family=Noto+Sans+JP&family=Tilt+Prism&display=swap).

The description of what you did for your WIP sounds ... interesting? I can't really comment on it without seeing the work.

**Comment by robvanderlee** [comment]
Note that this is a rough WIP. I was trying get a working example. I'm going on vacation today but will be able to share commits later or even make a PR with the necessary feedback changes.

```
# in CPDF.php

    public function attemptFontText(string $fontFile, string $text)
    {
        return $this->_pdf->attemptFontText($fontFile, $text);
    }
```

```
# in Cpdf.php

/**
     * @param string $fontFile
     * @param string $text
     * @return bool
     * @throws FontNotFoundException
     */
    public function attemptFontText(string $fontFile, string $text)
    {
        $font = &$this->fonts[$fontFile];
        $adobeFontName = isset($font['PostScriptName']) ? $font['PostScriptName'] : $font['FontName'];
        $adobeFontName = $this->getFontSubsettingTag($font) . '+' . $adobeFontName;
        $this->stringSubsets[$fontFile][] = 32; // Force space if not in yet

        $this->attemptRegisterText($fontFile, $text);
        $subset = $this->stringSubsets[$fontFile];
        sort($subset);

        $fileSuffix = $font['fileSuffix'];
        $fbfile = "$fontFile.$fileSuffix";

        // Load font
        $font_obj = Font::load($fbfile);
        $font_obj->parse();

        // Find Unicode char map table
        $subtable = null;
        foreach ($font_obj->getData("cmap", "subtables") as $_subtable) {
            if ($_subtable["platformID"] == 0 || $_subtable["platformID"] == 3 && $_subtable["platformSpecificID"] == 1) {
                $subtable = $_subtable;
                break;
            }
        }

        if ($subtable) {
            $glyphIndexArray = $subtable["glyphIndexArray"];
            unset($glyphIndexArray[0xFFFF]);

            if (array_intersect($this->stringSubsets['_attempt'], array_keys($glyphIndexArray)) === $this->stringSubsets['_attempt']) {
                return true;
            }
        }

        return false;
    }

 /**
     * register text for font subsetting
     *
     * @param string $font
     * @param string $text
     */
    function attemptRegisterText($font, $text)
    {
        if (!$this->isUnicode || in_array(mb_strtolower(basename($font)), self::$coreFonts)) {
            return;
        }

        $this->stringSubsets['_attempt'] = array_unique(
            $this->utf8toCodePointsArray($text)
        );

        $this->registerText($font, $text);
    }
```

```
# in Text.php renderer (check fontFallback under the font definition)

/**
     * @param \Dompdf\FrameDecorator\Text $frame
     */
    function render(Frame $frame)
    {
        $style = $frame->get_style();
        $text = $frame->get_text();

        if ($text === "") {
            return;
        }

        $this->_set_opacity($frame->get_opacity($style->opacity));

        list($x, $y) = $frame->get_position();
        $cb = $frame->get_containing_block();

        $ml = $style->margin_left;
        $pl = $style->padding_left;
        $bl = $style->border_left_width;
        $x += (float) $style->length_in_pt([$ml, $pl, $bl], $cb["w"]);

        $font = $style->font_family;

        if ($this->_dompdf->getOptions()->getIsFontSubsettingEnabled()) {
            $fontFallback = $style->get_font_family_raw();
            if (strpos($fontFallback, ',')) {
                foreach (explode(',', $fontFallback) as $fontFamily) {
                    $attemptFont = $this->_dompdf->getFontMetrics()->getFont(trim($fontFamily));
                    $isFontCompatible = $this->_canvas->attemptFontText($attemptFont, $text);
                    if ($isFontCompatible) {
                        $font = $attemptFont;
                        break;
                    }
                }
            }
        }


        $size = $style->font_size;
        $frame_font_size = $frame->get_dompdf()->getFontMetrics()->getFontHeight($font, $size);
        $word_spacing = $frame->get_text_spacing() + $style->word_spacing;
        $letter_spacing = $style->letter_spacing;
        $width = (float) $style->width;

        /*$text = str_replace(
          array("{PAGE_NUM}"),
          array($this->_canvas->get_page_number()),
          $text
        );*/

        $this->_canvas->text($x, $y, $text,
            $font, $size,
            $style->color, $word_spacing, $letter_spacing);

        $line = $frame->get_containing_line();

        // FIXME Instead of using the tallest frame to position,
        // the decoration, the text should be well placed
        if (false && $line->tallest_frame) {
            $base_frame = $line->tallest_frame;
            $style = $base_frame->get_style();
            $size = $style->font_size;
        }

        $line_thickness = $size * self::DECO_THICKNESS;
        $underline_offset = $size * self::UNDERLINE_OFFSET;
        $overline_offset = $size * self::OVERLINE_OFFSET;
        $linethrough_offset = $size * self::LINETHROUGH_OFFSET;
        $underline_position = -0.08;

        if ($this->_canvas instanceof CPDF) {
            $cpdf_font = $this->_canvas->get_cpdf()->fonts[$style->font_family];

            if (isset($cpdf_font["UnderlinePosition"])) {
                $underline_position = $cpdf_font["UnderlinePosition"] / 1000;
            }

            if (isset($cpdf_font["UnderlineThickness"])) {
                $line_thickness = $size * ($cpdf_font["UnderlineThickness"] / 1000);
            }
        }

        $descent = $size * $underline_position;
        $base = $frame_font_size;

        // Handle text decoration:
        // http://www.w3.org/TR/CSS21/text.html#propdef-text-decoration

        // Draw all applicable text-decorations.  Start with the root and work our way down.
        $p = $frame;
        $stack = [];
        while ($p = $p->get_parent()) {
            $stack[] = $p;
        }

        while (isset($stack[0])) {
            $f = array_pop($stack);

            if (($text_deco = $f->get_style()->text_decoration) === "none") {
                continue;
            }

            $deco_y = $y; //$line->y;
            $color = $f->get_style()->color;

            switch ($text_deco) {
                default:
                    continue 2;

                case "underline":
                    $deco_y += $base - $descent + $underline_offset + $line_thickness / 2;
                    break;

                case "overline":
                    $deco_y += $overline_offset + $line_thickness / 2;
                    break;

                case "line-through":
                    $deco_y += $base * 0.7 + $linethrough_offset;
                    break;
            }

            $dx = 0;
            $x1 = $x - self::DECO_EXTENSION;
            $x2 = $x + $width + $dx + self::DECO_EXTENSION;
            $this->_canvas->line($x1, $deco_y, $x2, $deco_y, $color, $line_thickness);
        }

        if ($this->_dompdf->getOptions()->getDebugLayout() && $this->_dompdf->getOptions()->getDebugLayoutLines()) {
            $text_width = $this->_dompdf->getFontMetrics()->getTextWidth($text, $font, $size, $word_spacing, $letter_spacing);
            $this->_debug_layout([$x, $y, $text_width, $frame_font_size], "orange", [0.5, 0.5]);
        }
    }

```

**Comment by bsweeney** [comment]
OK I see what you've done. That's not bad, though I'm not sure I'd do it this way. For one it doesn't abstract things sufficiently that other back ends can be used. I don't know that PDFLib has similar functionality for attempting the text/font combo (I haven't checked).

The second issue not handled here is mixed text. That's why I'd do it in FrameReflower/Text, you could request the ranges for the defined font-family (via FontMetrics) then split the frame whenever a boundary is encountered. We would need some way to indicate the appropriate range in the frame so that during the rendering portion of the process doesn't have to re-parse the text again, and is also able to select the appropriate font.

**Comment by robvanderlee** [comment]
@bsweeney I've worked out a rough solution. I'm struggling to understand frames and was hoping you could help me explain or put me in the right direction on this. I've written code to detect and put together the strings per font. My train of thought would be add additional frames per boundary as per your suggestion.

You can check the work (WIP) [here](https://github.com/robvanderlee/dompdf/tree/enhancement-css-fallback). I'm specifically struggling [here](https://github.com/robvanderlee/dompdf/blob/7d2c32b227af1c61364efbeb41c7acb8864580bf/src/FrameReflower/Text.php#L408).

**Comment by bsweeney** [comment]
I have a lot more analysis to do, but at first glance you can significantly simplify the changes to the reflow logic.

First I would rewrite the new FontMetrics methods to just accept the relevant string values instead of the Style instance:
```
public function canStyleRender(string $font, string $text): bool
{
    if (!key_exists($font, $this->unicodeCharMapTables)) {
        $this->loadunicodeCharMapTables($font);
    }

    return $this->intersectUnicodeAgainstFont($text, $font);
}
```

and
```
public function getTextFamilies(array $fontFamilies, string $text): array
```

You're doing a lot of work in the reflow method that is already handled elsehwere, so you can simplify the relevant reflow logic like this:
```
if ($this->getFontMetrics()->canStyleRender($style->font_family, $text) === false) {
    $charMapping = $this->getFontMetrics()->getTextFamilies(explode(",", $style->get_specified("font_family")), $text);
    $breakpoints = array_keys($charMapping);
    if (count($breakpoints) > 1) {
        $frame->split_text($breakpoints[0] + mb_strlen($charMapping[$breakpoints[0]["char"]]));
        $text = $this->pre_process_text($frame->get_text());
    }
    $mapped_font = $charMapping[$breakpoints[0]]["font"];
    if ($mapped_font !== false) {
        $style->set_used("font_family", $mapped_font);
    }
}
```

<details>
<summary>FrameReflower\Text::reflow</summary>

```
function reflow(BlockFrameDecorator $block = null)
{
    $frame = $this->_frame;
    $page = $frame->get_root();
    $page->check_forced_page_break($frame);

    if ($page->is_full()) {
        return;
    }

    // Determine the text height
    $style = $frame->get_style();
    $size = $style->font_size;
    $font = $style->font_family;
    $font_height = $this->getFontMetrics()->getFontHeight($font, $size);
    $style->set_used("height", $font_height);

    // Handle text transform and white space
    $text = $this->pre_process_text($frame->get_text());

    if ($this->getFontMetrics()->canStyleRender($style->font_family, $text) === false) {
        $charMapping = $this->getFontMetrics()->getTextFamilies(explode(",", $style->get_specified("font_family")), $text);
        $breakpoints = array_keys($charMapping);
        if (count($breakpoints) > 1) {
            $frame->split_text($breakpoints[0] + mb_strlen($charMapping[$breakpoints[0]["char"]]));
            $text = $this->pre_process_text($frame->get_text());
        }
        $mapped_font = $charMapping[$breakpoints[0]]["font"];
        if ($mapped_font !== false) {
            $style->set_used("font_family", $mapped_font);
        }
    }

    $a = $frame->get_node();
    $frame->set_text($text);

    if ($block === null) {
        return;
    }

    $add_line = $this->layout_line($block);

    if ($add_line === null) {
        return;
    }

    $frame->position();

    // Skip wrapped white space between block-level elements in case white
    // space is collapsed
    if ($frame->get_text() === "" && $frame->get_margin_width() === 0.0) {
        return;
    }

    $line = $block->add_frame_to_line($frame);
    $trimmed = trim($frame->get_text());

    // Split the text into words (used to determine spacing between
    // words on justified lines)
    if ($trimmed !== "") {
        $words = preg_split(self::$_whitespace_pattern, $trimmed);
        $line->wc += count($words);
    }

    if ($add_line) {
        $block->add_line();
    }
}
```
</details>

And, this works pretty much exactly like we'd want, splitting a frame into multiple frames with the supporting font family as the used value in the Style...

```
<html>

<head>
  <style>
    @import url("https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,600i,700,700i,800,800i&display=swap");
    @import url('https://fonts.googleapis.com/css2?family=Zhi+Mang+Xing&display=swap');
  </style>
</head>

<body>

  <p style="font-family: sans-serif, DejaVu Sans, Open Sans, Zhi Mang Xing;">what ǻǼǽ ΅ 鉴于</p>

</body>
</html>
```

![image](https://user-images.githubusercontent.com/485897/225033633-cfffccf4-1de3-4c32-9024-75bc764259fb.png)

---

Still lots of work to do to fully optimize the logic, but this is looking quite promising.

**Comment by robvanderlee** [comment]
@bsweeney thanks! That is exactly what I needed. I've gone ahead and put in your work and then did some optimization work in the `getTextFamilies()` loop that seemed to take the most time to compute. I'm sure you still might have suggestions.

---

I've managed to render the following file in 1.903706 seconds but do take that with a grain of salt as it's repeating the same text.
* [fallback-css.pdf](https://github.com/dompdf/dompdf/files/10985052/fallback-css.pdf)
* [fallback-css.html.txt](https://github.com/dompdf/dompdf/files/10985050/fallback-css.html.txt)

---

It's very clear from my test that there is still a major performance impact after these initial improvements. My suggestion for this functionality would be putting it behind an option. That way each can decide if they would want to take that performance hit or not. Aside from what further performance improvements we can make.

**Comment by robvanderlee** [comment]
At any rate. I will look further into optimizing the performance and the unit tests that are now failing for now.

**Comment by bsweeney** [comment]
I'm also looking at this. I was able to resolve the test issues with the changes I'm working on. I'm still seeing if I can squeeze some performance out of this. While I think this is the right method to address the feature, the performance issue may not be resolvable for something like your sample document. The issue appears to be the large number of frames created (456 without parsing unicode ranges, 4489 with parsing).

I'll add suggested changes to the PR once I'm done experimenting.

**Comment by bsweeney** [comment]
OK, I added a review to the PR with suggested changes that I think improves performance.

One thing to note: currently we're processing the actual font files, but I wonder if we would see better performance using the existing font metrics rather than processing the font again. The logic would be similar to what's in use by [Cpdf::openFont](https://github.com/dompdf/dompdf/blob/v2.0.2/lib/Cpdf.php#L3299). This would allow using the cached font metrics if they exist, removing that performance hit. Making this change would also add support for AFM fonts (namely the core PDF fonts).

**Comment by robvanderlee** [comment]
@bsweeney Thanks for your feedback. I've initially added your code suggestions though it gave me some errors here and there and therefor I've not applied all of it. I've also applied some minor code improvements and fixed the unit test issues.

I've also researched the possibility to use the `selectFont()` method in cPDF to use the cached font metrics. However, I would still need the data from the subtables. Currently I fetch these with the Font classes through `->getData()`. selectFont neither caches the information I need reliably nor returns the Font class. Currently it will only parse the font when [Subsetting is enabled](https://github.com/dompdf/dompdf/blob/master/lib/Cpdf.php#L1168). It will store the parsed data OR (binary) contents of the file in [the same variable](https://github.com/dompdf/dompdf/blob/master/lib/Cpdf.php#L1282). I didn't find it worth it for now to code around that. That might be an idea for future optimization. Refactoring this part in Cpdf.php will be more impactful than just this usecase.

**Comment by bsweeney** [comment]
I didn't receive any errors with my (limited) testing. If you can share details I can look to see what's going on.

As for the Cpdf logic, I was thinking that instead of parsing the actual font we can utilize the generated font metrics, [same as Cpdf](https://github.com/dompdf/dompdf/blob/master/lib/Cpdf.php#L3299). That could speed things up since a cached version of the parsed file is generated in the process. Since the metrics provide information regarding the supported Unicode characters it should have sufficient information to do the font matching. Once a font is loaded by Cpdf you can access the glyph index through the fonts property.

My only concern with using Cpdf is that it would have to be the back end in use. But it does looks like PDFLib supports retrieving font information as well so it looks like it we could modify the Canvas adapters to retrieve this information. Then again, this is a font metrics class so adding native font parsing logic makes sense, I just wonder if it would be faster to do it using the metrics file (borrowing the Cpdf logic) instead of php-font-lib to fully parse the font again.

**Comment by robvanderlee** [comment]
I get what you are trying to say and it does sound like a sound idea but I don't see how we could implement that without having too much impact on the rest.

As for the issues i've got when working the the suggested code for `getTextFamilies()`:

1. `$fonts[$family] = $font = $this->getFont($family);` needs a trim in order to correctly parse the font name. 
2. `fontSupportsGlyph()` does not exist? I changed this to the `canStyleRender()` method - arguably that name should be changed as I do think `fontSupportsGlyph()` would be better with all the changes since it's initial addition.
3. Then it will render without issues but obviously something else in the logic is flawed as it will not render correctly anymore. ![image](https://user-images.githubusercontent.com/124156158/227566815-c5896e03-f167-4332-9af2-8496871e4bbb.png)

**Comment by bsweeney** [comment]
1. For sure. In my local I modified the call from the Text reflower to be `$families = array_map(function ($value) { return trim($value, " '\""); }, explode(",", $style->get_specified("font_family")));`. Apparently I forgot to update the suggestion.
2. Whoops. An added function I forgot to include.
3. I'll resolve current suggestions and do another round with, hopefully, all the changes.

**Comment by rvdlee** [comment]
Thats okay! I figured as much! Have a great weekend and ill look at it when you are able to get back at it.

**Comment by bsweeney** [comment]
I wasn't sure using the metrics files would impart much of a performance boost ... but I was wrong. Again my testing has been limited, but using the metrics shaves off a decent amount of time in my testing.

I'm still trying to decide how best to handle this. FontMetrics already leans on the PDF back end for some of its functionality, so utilizing it for retrieving the glyph index seems reasonable. I'll see what I can do with the metrics and update my code suggestions.

**Comment by robvanderlee** [comment]
Just tested the current work. It's coming out good on my machine and has improved performance. I'm rendering the same file (that took ~1.9s) to render in ~1.2s now. I'd say that's a huge gain. You @Mellthas is providing good feedback so I'd better not meddle now. This LGTM guys!

**Comment by robvanderlee** [comment]
Is there anything I can do at this point to contribute?

**Comment by bsweeney** [comment]
I think we're good? I've been distracted by some other work of late and also trying to finish up another change that I can't quite get right. Thanks for checking in.

**Comment by robvanderlee** [comment]
Checking in. If there is anything I can do to speed up the last mile then let me know. It's not my intention to push you into prioritizing this, just wanna know the current state. Seeing as this is such a rich feature that a lot of people can benefit from.

**Comment by bsweeney** [comment]
Nothing more to do. I was waiting to see if anyone had any more feedback while I reviewed other tickets slated for the next release. It's been a month so I think we're good on this feature. Thanks for checking back in.

**Comment by robvanderlee** [comment]
@bsweeney I've tried implementing this feature in our codebase and somehow it broke on me. I'm in the process of figuring out what is broken now since my last testing.

**Comment by robvanderlee** [comment]
I still had my feature branch locally. It was behind some but specifically the japanese characters in Noto seem to be broken. That might be because the truetype hack ain't working anymore. That's my best guess for now.

[fallback-css.on-master.pdf](https://github.com/dompdf/dompdf/files/12194513/fallback-css.on-master.pdf)
[fallback-css.on-feature-branch.pdf](https://github.com/dompdf/dompdf/files/12194516/fallback-css.on-feature-branch.pdf)

Will see if I can provide you some solid information on this hunch.

**Comment by robvanderlee** [comment]
I found that in `src/FontMetrics.php:L354` it fails to load the Noto Sans JS font when performing the `$this->getFont()` call. A little further searching brought me to `src/Css/Stylesheet.php:L1466` where a helper class does some magic to the provided url. It manipulates the raw to a lowercased url resulting in a 404.

**Original value is a valid 200:**
https://fonts.gstatic.com/ea/notosansjp/v5/NotoSansJP-Regular.otf

**Manipulated value resulting in 404:**
https://fonts.gstatic.com/ea/notosansjp/v5/notosansjp-regular.otf

**Comment by bsweeney** [comment]
Are you running with this branch specifically or with the master branch. The casing issue should have been addressed with #3176. Since both branches are merged in preparation for a release you should be able to just use the master branch.

When I run with the linked Noto font it does install correctly but php-font-lib is having trouble parsing the font for subsetting so I have to run with that feature disabled.

**Comment by bsweeney** [comment]
Thank you, I'll take a look.

**Comment by bsweeney** [comment]
After a bit more research I did find a relevant bug in how we're handling the `src` attribute. Current logic lowercases CSS values by default. I have a fix already but have not yet had a chance to finish some related work.

**Comment by robvanderlee** [comment]
@bsweeney okay, good to know that this is in the works then! :tada:

**Comment by 8ctopus** [comment]
This feature is awesome, thank you! Could we please have a release so we can use it?
