### ISSUE TITLE
Path cannot be empty FontMetrics.php:233 issue

### ISSUE THREAD

**Issue by aschurf** [dompdf/dompdf#3143]
Hello! 

I am taking my first steps in dompdf. I really like it and everything works great on my localhost. But as soon as I try to create a pdf from html on the production server, I run into a 

Path cannot be empty at dompdf/vendor/dompdf/dompdf/src/FontMetrics.php:233

I tried installing via Composer and using a zip archive, as well as checking folder permissions, but nothing helped. What could be the reason?

my code:

```
    require_once '/dompdf/autoload.inc.php';
    use Dompdf\Dompdf;
    use Dompdf\Options;

    $options = new Options();
    $options->set('isRemoteEnabled', true);

    $dompdf = new Dompdf($options);
    $dompdf->loadHtmlFile("/pdfreport");

    $dompdf->setPaper('A4', 'portrait');

    $dompdf->render();

    $dompdf->stream();
```

**Comment by bsweeney** [comment]
The error indicates that the temporary directory isn't writable by Dompdf. You'll need to specify a custom directory via Options configuration:

```
$options->set("tempDir", "/a/writable/path");
```
