### ISSUE TITLE
Issue with "white-space: nowrap"

### ISSUE THREAD

**Issue by MarcPinnell** [dompdf/dompdf#3144]
Having an issue with white-space: nowrap not working as I expect it to and could use some guidance.

I would expect this code (simplified for readability) to cut off the long name (hide it). 

```
<div style="display:block;border-bottom: 1px solid black;overflow:hidden; white-space: nowrap;">
	 <span style="width: 25%; float: left;">5632</span>
	<span style="width: 75%"; float: left;>BROCK & PHILLIP OBENDORF FARMS, LLC.</span>
 </div>
```

Instead when I generate the PDF it is putting it on a new line in its entirety. This works fine when I look at the HTML.
 
![Screenshot 2023-02-28 at 4 12 01 PM](https://user-images.githubusercontent.com/4871176/222012561-2c1f2a18-207d-4aed-84e3-3f801b7dd2d3.png)

**Comment by MarcPinnell** [comment]
For some reason the code block won't post. Ugh.
![Screenshot 2023-02-28 at 4 20 14 PM](https://user-images.githubusercontent.com/4871176/222013071-d6c16c8f-12ee-4d0f-beea-d24f6df8c8c6.png)

**Comment by bsweeney** [comment]
Instead of a single backtick you have to use three and a line break to indicate a code block. The line break in the middle of the code is confusing the markdown parser.

**Comment by bsweeney** [comment]
This looks like a variation on #800. I do not have a workaround at the present time. Follow that issue for updates.

**Comment by MarcPinnell** [comment]
> Instead of a single backtick you have to use three and a line break to indicate a code block. The line break in the middle of the code is confusing the markdown parser.

Thanks. I had just clicked the "code" icon in the tool bar. I don't use markdown hardly at all so have to rely on "helpers" :)
