### ISSUE TITLE
iconv_substr(): Detected an incomplete multibyte character in input string 

### ISSUE THREAD

**Issue by matiass** [dompdf/dompdf#3150]
Al actualizar dompdf a la versión 2.0 y actualizar PHP a la versión 8.2, en ciertas ocasiones estoy obteniendo el siguiente error:

> iconv_substr(): Detected an incomplete multibyte character in input string {"userId":{"Ramsey\\Uuid\\Lazy\\LazyUuidFromString":"47c673b2-34f4-4534-b3a3-e374d7b5312f"},"exception":"[object] (ErrorException(code: 0): iconv_substr(): Detected an incomplete multibyte character in input string at /vendor/symfony/polyfill-mbstring/Mbstring.php:636
> 
> \# 0 /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
> \# 1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
> \# 2 /vendor/symfony/polyfill-mbstring/Mbstring.php(636): iconv_substr()
> \# 3 /vendor/symfony/polyfill-mbstring/bootstrap80.php(72): Symfony\\Polyfill\\Mbstring\\Mbstring::mb_substr()
> \# 4 /vendor/dompdf/dompdf/src/FrameReflower/Text.php(437): mb_substr()
> \# 5 /vendor/dompdf/dompdf/src/LineBox.php(370): Dompdf\\FrameReflower\\Text->trim_trailing_ws()
> \# 6 /vendor/dompdf/dompdf/src/FrameReflower/Block.php(445): Dompdf\\LineBox->trim_trailing_ws()
> \# 7 /vendor/dompdf/dompdf/src/FrameReflower/Block.php(904): Dompdf\\FrameReflower\\Block->_text_align()
> \# 8 /vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(916): Dompdf\\FrameReflower\\Block->reflow()
> \# 9 /vendor/dompdf/dompdf/src/FrameReflower/Block.php(865): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow()
> \# 10 /vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(916): Dompdf\\FrameReflower\\Block->reflow()
> \# 11 /vendor/dompdf/dompdf/src/FrameReflower/Block.php(865): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow()
> \# 12 /vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(916): Dompdf\\FrameReflower\\Block->reflow()
> \# 13 /vendor/dompdf/dompdf/src/FrameReflower/Block.php(865): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow()
> \# 14 /vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(916): Dompdf\\FrameReflower\\Block->reflow()
> \# 15 /vendor/dompdf/dompdf/src/FrameReflower/Page.php(142): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow()
> \# 16 /vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(916): Dompdf\\FrameReflower\\Page->reflow()
> \# 17 /vendor/dompdf/dompdf/src/Dompdf.php(770): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow()
> \# 18 /vendor/barryvdh/laravel-dompdf/src/PDF.php(213): Dompdf\\Dompdf->render()
> \# 19 /vendor/barryvdh/laravel-dompdf/src/PDF.php(169): Barryvdh\\DomPDF\\PDF->render()
> \# 20 /app/Mails/UserActivation.php(71): Barryvdh\\DomPDF\\PDF->output()
> \# 21 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Mails\\UserActivation->build()
> \# 22 /vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
> \# 23 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
> \# 24 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
> \# 25 /vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
> \# 26 /vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(1568): Illuminate\\Container\\Container->call()
> \# 27 /vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(198): Illuminate\\Mail\\Mailable->prepareMailableForDelivery()
> \# 28 /vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Mail\\Mailable->Illuminate\\Mail\\{closure}()
> \# 29 /vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(197): Illuminate\\Mail\\Mailable->withLocale()
> \# 30 /vendor/laravel/framework/src/Illuminate/Mail/SendQueuedMailable.php(74): Illuminate\\Mail\\Mailable->send()
> \# 31 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Mail\\SendQueuedMailable->handle()
> \# 32 /vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
> \# 33 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
> \# 34 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
> \# 35 /vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
> \# 36 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
> \# 37 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
> \# 38 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> \# 39 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
> \# 40 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Bus\\Dispatcher->dispatchNow()
> \# 41 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
> \# 42 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
> \# 43 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
> \# 44 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
> \# 45 /vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
> \# 46 /vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\\Queue\\Jobs\\Job->fire()
> \# 47 /vendor/laravel/framework/src/Illuminate/Queue/Queue.php(57): Illuminate\\Queue\\SyncQueue->push()
> \# 48 /vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(232): Illuminate\\Queue\\Queue->pushOn()
> \# 49 /vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(421): Illuminate\\Mail\\Mailable->queue()
> \# 50 /src/Services/Users.php(233): Illuminate\\Mail\\Mailer->queue()

**Comment by bsweeney** [comment]
The actual error appears to be in the Symfony MBString polyfill and not in Dompdf. If you can, using the actual MBString extension might resolve the error.

To determine if there's something we need to address in Dompdf we'd need to see a sample document that reproduces the error.

**Comment by matiass** [comment]
> 

The error ocurred on the next text "Las Partes entienden que el principio contra proferentem de interpretación no resulta aplicable a estos"

The complete line is "<p>Las Partes entienden que el principio contra proferentem de interpretación no resulta aplicable a estos Términos y Condiciones; es decir, cualquier ambigüedad o discrepancia en los presentes debe resolverse de acuerdo con la interpretación más razonable y no estrictamente en favor o en contra de cualquiera de una u otras Partes en virtud de la autoría de dicha una u otra Parte en una disposición pertinente de los presentes. </p>".

It's rare because does not always fail and there is no strange character.

any suggestions?

**Comment by bsweeney** [comment]
I'm unable to reproduce just using a straight call to the Symfony method. But I was able to do so with the following contrived logic:

```
$text = "&eacute;";
$text =  html_entity_decode($text, ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML401, "iso-8859-1");
echo $text . "\n";
echo \Symfony\Polyfill\Mbstring\Mbstring::mb_substr($text, 0, -1);
```

So, two things to check:
1. the content of the document is encoded correctly
2. the correct encoding is specified in the HTML document

In order to see if Dompdf is doing something wrong I'll need to set up a separate instance that relies on that library. Even then I may be unable to reproduce if the issue is caused when that the string is being incorrectly truncated somewhere else in the logic. And that would depend on the styling.

Does the error occur if you try to render just a simple document?

```
<html>
<body>
<p>Las Partes entienden que el principio contra proferentem de interpretación no resulta aplicable a estos Términos y Condiciones; es decir, cualquier ambigüedad o discrepancia en los presentes debe resolverse de acuerdo con la interpretación más razonable y no estrictamente en favor o en contra de cualquiera de una u otras Partes en virtud de la autoría de dicha una u otra Parte en una disposición pertinente de los presentes. </p>
</body>
</html>
```

**Comment by matiass** [comment]
Apparently it was solved by adding the mbstring extension
