### ISSUE TITLE
page border not working for multiple pages

### ISSUE THREAD

**Issue by Sivan4562** [dompdf/dompdf#3153]
hi guys

I am currently working on dompdf using laravel. the version is 0.9.0.
I have written the page border in the body tag but it works on the first page on the second page the border is not applied

Like This

![image](https://user-images.githubusercontent.com/110915382/224964368-d41b6af6-5eb2-4dcd-838d-2550fbedee20.png)

how I can fix them

**Comment by bsweeney** [comment]
Would need to see the HTML+CSS.

**Comment by Sivan4562** [comment]
Here Is my code
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            border-radius: 2px solid black;
            padding: 10px;;
        }
    </style>
</head>
<body>
    <h1>Hai</h1>
</body>
</html>

**Comment by bsweeney** [comment]
Your CSS isn't quite right. You specified the border as a border radius.

Try the following:
```
body{
    border: 2px solid black;
    padding: 10px;
}
```

and if you did want a border radius:
Try the following:
```
body{
    border: 2px solid black;
    border-radius: 10px;
    padding: 10px;
}
```

**Comment by Sivan456** [comment]
Hi @bsweeney,
            I tried your above css in the body tag but it cannot apply to the separate page it used the whole page like the below image
![image](https://github.com/dompdf/dompdf/assets/86248110/4ce11d23-e12c-4042-b52e-a47d3609fd59)

**Comment by bsweeney** [comment]
Would need to see a sample of the HTML + CSS to determine what's going on. It looks like you're applying a border to something other than the BODY element based on the rendering.

**Comment by Sivan456** [comment]
Hi @bsweeney,

I am sharing my code below here,

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            border: 2px solid black;
            border-radius: 10px;
            padding: 10px;
        }
    </style>
</head>
<body>
    <div>
        <h1>Logo</h1>
    </div>
    <table>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa@gmail.com</td>
            <td>9658452535</td>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa@gmail.com</td>
            <td>9658452535</td>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa@gmail.com</td>
            <td>9658452535</td>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa@gmail.com</td>
            <td>9658452535</td>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa@gmail.com</td>
            <td>9658452535</td>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa@gmail.com</td>
            <td>9658452535</td>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa@gmail.com</td>
            <td>9658452535</td>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa@gmail.com</td>
            <td>9658452535</td>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa@gmail.com</td>
            <td>9658452535</td>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa@gmail.com</td>
            <td>9658452535</td>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa@gmail.com</td>
            <td>9658452535</td>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa@gmail.com</td>
            <td>9658452535</td>
        </tr>
        <tr>
            <td>aa</td>
            <td>aa@gmail.com</td>
            <td>9658452535</td>
        </tr>
    </table>
    <div>
        <p>------------------</p>
        <h1>singnature</h1>
    </div>
</body>
</html>
```

**Comment by bsweeney** [comment]
I'm unable to reproduce the issue with that sample. Is there other styling applied to the document that may be causing your issue?

**Comment by Sivan456** [comment]
Hi @bsweeney,
I cannot add any other style for this pdf and the above code is not a sample code it is my original code that was deployed on the server. but in dom pdf version 0.8.3 the border is working fine (i.e.) the border is separate for the multiple pages but in this 0.9.0 version didn't work properly? what can I do for this @bsweeney

**Comment by bsweeney** [comment]
This may be _similar_ to the code on your server, but just looking at the content of the HTML and the image I can see that they are not the same. Also, the sample you posted is fully contained on a single page (unless you're using a very small page size) so it wouldn't reproduce the issue.

Also note that there has been no 0.9.0 release of Dompdf.

If you can reproduce the issue using the [debug helper](https://eclecticgeek.com/dompdf/debug.php) and post a link here I'll take another look.
