### ISSUE TITLE
Wrong folder with registered fonts

### ISSUE THREAD

**Issue by Atsyn** [dompdf/dompdf#3157]
Hello. I have a problem with fonts.
Your script register custom fonts and make several files in **fontDir**:
```
font_name_**md5**.ttf
font_name_**md5**.ufm
installed-fonts.json
```
But we use autodeploy system from git and those files lock deploy.

I think those files should be located in a **fontCache** directory.

**Comment by bsweeney** [comment]
fontDir is the correct location, that is where the font file, font metrics, and index are intended to be located. fontCache is for caching files (parsed versions of the font metrics file) and is by default the same as fontDir. You can modify the fontDir and fontCache directories by specifying the relevant options.

For example:
```
$dompdf = new Dompdf(["fontDir" => "/writeable/path"]);
```

The distributed font directory is always read regardless of the fontDir configuration.

**Comment by Atsyn** [comment]
My font directory and font placed in to the git repository.
And no ny temporary files shouldn't be located in the repository.
But this library do that.

Alternative variant:
Could you extend options and add additional folder for the font metrics, and index?

**Comment by bsweeney** [comment]
This library only writes to the lib/fonts directory in the default configuration. If you change the options as demonstrated above the files you cited will be written to that location instead.
