### ISSUE TITLE
Rendering ServiceMark ℠ as question mark ?

### ISSUE THREAD

**Issue by markkimsal** [dompdf/dompdf#3161]
I'm not sure where to go with this one.  I do not think it's a font issue.  I decompressed the output pdf with `qpdf` and the output PDF contains the actual question mark, not a character that has no glyph.

This happens with PHP 8.0.23 and dompdf 1.2.2 or dompdf 2.0.3

```php
<?php
include('../vendor/autoload.php');
$tableHtml = getHtml();
$dompdf = new \Dompdf\Dompdf();
$dompdf->loadHtml($tableHtml);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
header('Content-type: application/pdf');
$dompdf->stream();

function getHtml() {
    return 
'
<p>html entity 8480: &#8480;</p>
<p>pasted unicode: ℠</p>
<p>pasted trademark: ®</p>
';
}
```
![image](https://user-images.githubusercontent.com/54099/226107690-325227c1-24e7-4c0f-9036-54c724c1a546.png)

```
8 0 obj
<< /Length 211 >>
stream

0.000 0.000 0.000 rg
BT 34.016 537.859 Td /F1 12.0 Tf  [(html entity 8480: ?)] TJ ET
BT 34.016 511.603 Td /F1 12.0 Tf  [(pasted unicode: ?)] TJ ET                                                                                
BT 34.016 485.347 Td /F1 12.0 Tf  [(pasted trademark: ®)] TJ ETendstream
endobj
```

**Comment by bsweeney** [comment]
You'll need to style your text with a supporting font. The core PDF fonts (Helvetica, Times Roman, Courier) and generic font families (sans-serif, serif, monospace) only support windows-ansi encoded characters.

The bundled DejaVu fonts will work for those characters:

```
<style>
* { font-family: DejaVu Sans; }
</style>
<p>html entity 8480: &#8480;</p>
<p>pasted unicode: ℠</p>
<p>pasted trademark: ®</p>
```

**Comment by markkimsal** [comment]
Thanks for the quick response.  This was very strange looking to me because (r) and TM rendered so well and one would think SM would be right along next to all those characters.  I was certain it wasn't a font issue, but then it was.  Finding that the renderer changes the encoding to match the font was quite a surprise.

For future visotors:

The lib/Cpdf.php is converting everything to $targetEncoding "Windows-1252" because Times-Roman doesn't support Unicode 

```php
        if ($convert_encoding) {
            $cf = $this->currentFont;
            if (isset($this->fonts[$cf]) && $this->fonts[$cf]['isUnicode']) {
                $text = $this->utf8toUtf16BE($text, $bom);
            } else {
                $text = mb_convert_encoding($text, self::$targetEncoding, 'UTF-8');
            }
        } elseif ($bom) {
            $text = $this->utf8toUtf16BE($text, $bom);
        }
```

**Comment by bsweeney** [comment]
In a future release we'll likely modify Dompdf to use an installed font if the rendered characters are not supported. The work in #3155 should help in that regard.
