### ISSUE TITLE
Incorrect output of font

### ISSUE THREAD

**Issue by dnznk** [dompdf/dompdf#3162]
**Describe the bug**
Sometimes the content of the generated PDF is Japanese. Just like for many others before me the PDF shows either only question marks or boxes, hence can't display the special characters.

**To Reproduce**
- `"laravel/framework": "^7.0"`, `"barryvdh/laravel-dompdf": "^2.0",`
- `return Pdf::loadView('pdfs.explo', $data)->stream($pdfName . '.pdf');`
- Characters that won't display: スペア パーツ [example]
- Already tried to use DejaVu Sans (shows boxes) and also NotoSans (donwloaded and added to storage, aswell as implemented with `@font-face`)
- `'convert_entities' => true,` set to false
- If I change the output not to show a rendered PDF but a html page, everything is displayed correctly.

**Expected behavior**
The Japanese characters (same problem for Greek) should be displayed in the rendered PDF.

**Screenshots**
![Bildschirm_foto 2023-03-17 um 10 05 18](https://user-images.githubusercontent.com/107815714/225867411-49b17bde-2b5b-4eaf-a60b-37e5c29e465e.png)

**Additional context**

**Comment by bsweeney** [comment]
Would need to see your HTML+CSS to help determine why the characters aren't displayed.

**Comment by bsweeney** [comment]
The DejaVu fonts do not support Japanese characters. Do you have a sample with the Noto font?

**Comment by bsweeney** [comment]
Did you download [Noto Sans](https://fonts.google.com/noto/specimen/Noto+Sans) or [Noto Sans Japanese](https://fonts.google.com/noto/specimen/Noto+Sans+JP)? I don't believe there's a version of the font with all the supported glyphs in a single file.

**Comment by dnznk** [comment]
Yes, I did try NotoSansJP aswell as NotoSans.
I also converted NotoSansJP to .ttf format.

**Comment by bsweeney** [comment]
Dompdf's font parsing library has some trouble with the Noto fonts. In my limited testing I wasn't able to parse the font so it could be used.

It's hard to debug this type of issue without full details on the HTML document and access to the font files you are using.

Have you tried other fonts? For example, using Kosugi Maru renders OK for me:

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">
  <style>
    * { font-family: Kosugi Maru, DejaVu Sans, sans-serif };
  </style>
</head>
<body>
  <p>スペア パーツ</p>
</body>
</html>
```

**Comment by bsweeney** [comment]
FYI if an OTF font isn't parsing correctly you can try disabling font subsetting. Of course, if that does work the PDF file size will increase significantly.

**Comment by dnznk** [comment]
So I tried the above example with google fonts but get the following error (in a laravel blade context)
`ErrorException - unpack(): Type n: not enough input, need 2, have 1
unpack(): Type n: not enough input, need 2, have 1`

The text I'm trying to display is coming from here:
```
<td style="vertical-align: middle; font-size: 10px; text-align: right; padding: 0;">
				{{ implode(' > ', $breadcrumb) }}
			</td>
```

Where exactly would I disable the subsetting? Found it in the Options.php but didn't change anything.

**Comment by bsweeney** [comment]
The unpack error is something we definitely need to fix in php-font-lib, related issue is dompdf/php-font-lib#47. It's a non-consistent error related to specific fonts so you might try a different one.

As for disabling font subsetting, there are a few ways to do that such as during Dompdf instantiation:
```
$dompdf = new Dompdf(["isFontSubsettingEnabled" => false]);
```
