### ISSUE TITLE
have trouble with border-radius when page break at table tag

### ISSUE THREAD

**Issue by vuhoang123** [dompdf/dompdf#3164]
i set border-radius for table and when the page break, the end of first table in first page and head of table in second page is not border, how i can fix it?
here is my code

```
table {
            border-radius: 5px;
            border: 1px solid #fff;
            overflow: hidden;
        }

th    {
            border: 0 .5px 0 .5px solid #fff;
        }
```
![image](https://user-images.githubusercontent.com/59307469/226664792-bb2c4afa-4d6b-4f47-830e-e2fac5e2ed64.png)

**Comment by bsweeney** [comment]
I'm unclear on whether this is a single table split across multiple pages or something else. Can you supply a full example of your HTML + CSS?

That being said, it sounds like you want to modify the rendering behavior when an element is split across pages. The default behavior is to "continue" the border. There is a CSS option that modifies how split elements render, though we have not yet implemented it. Watch #640 for updates.

If this is what you want, there may be a way to accommodate this using callbacks, though I would have to investigate more.
