### ISSUE TITLE
The row #31 could not be found, please file an issue in the tracker with the HTML code

### ISSUE THREAD

**Issue by arhamroshan** [dompdf/dompdf#3167]
Issue
When I am printing multiple html pages and one of page content is getting larger so it should go on other page but its is throwing this error.

To Reproduce
Find the html code below
[test.txt](https://github.com/barryvdh/laravel-dompdf/files/10880874/test.txt)

Expected behavior
It should not throw this error and print the pdf smoothly

Versions
Php 8.1
Laravel 9
Dompdf 2.0

Screenshots
Find the attached screenshot
![image](https://user-images.githubusercontent.com/111501793/227340521-6538abda-dfc9-4d81-8540-8ffabe2f7404.png)

**Comment by bsweeney** [comment]
The document you posted has two full HTML document inside it. If I render each document separately Dompdf does not run into errors, but Dompdf does not seem to be able to handle two full HTML structures in the same document. I imagine that is not what you intended to product.

**Comment by arhamroshan** [comment]
Thanks for your quick response 
I want to render multiple html to generate multiple pdf at once yes it is working fine when i am generating only one html, but its giving this error when i am generating multiple html so what is the solution for it. How i gonna achieve this?

**Comment by arhamroshan** [comment]
Thanks Buddy I have resolved this issue by merging all the pdf string output in the end using this package
https://github.com/Webklex/laravel-pdfmerger
