### ISSUE TITLE
Dom PDF is generating blank page at the start of document

### ISSUE THREAD

**Issue by arhamroshan** [dompdf/dompdf#3171]
Find the html code below
[purchase-order.txt](https://github.com/dompdf/dompdf/files/11089000/purchase-order.txt)

Paper size
$dompdf = app()->make('dompdf.wrapper');
$dompdf->setPaper('a4', 'landscape');

Screenshots
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/111501793/228229932-1f1a64d7-2252-400b-bd0c-921d6edf2dc5.png">
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/111501793/228230006-b38140cc-f594-4a2d-b5db-6374ec464e50.png">

**Comment by bsweeney** [comment]
In your stylesheet, you've indicate to avoid page breaks inside the table. So Dompdf is attempting to honor that by moving the table to the next page to try and keep it all together. Just remove that styling and the leading blank page will go away.
