### ISSUE TITLE
dompdf 2.0.3 compatible with php 8.2?

### ISSUE THREAD

**Issue by whitejedi86** [dompdf/dompdf#3174]
dompdf 2.0.3 and codeigniter 4 generates blank or emty pdf, no errors in console, in php log or codeigniter log

**Comment by bsweeney** [comment]
As far as I know it should be compatible. [Unit tests](https://github.com/dompdf/dompdf/actions) do not indicate any issues. And the tests I've run do not appear to show any problems.

You can try [enabling additional messaging](https://github.com/dompdf/dompdf/wiki/Debugging-Dompdf) to see if it's an issue with Dompdf. Or maybe a necessary PHP extension is missing?

**Comment by whitejedi86** [comment]
hello, i have managed to track down the issue, its not a php 8.2 problem but rather a codeigniter 4/dompdf conflict, setting codeigniter from development mode to production mode gives out clean pdfs, thank you for your quick response

**Comment by bsweeney** [comment]
Good to know. Thanks for the follow up.
