### ISSUE TITLE
margins

### ISSUE THREAD

**Issue by wsimm** [dompdf/dompdf#3177]
Hi, how can i avoid the margin and define the exact  pdf width and height

**Comment by bsweeney** [comment]
Page size is set using the setPaper method. You can specify standard paper sizes:

```
$dompdf->setPaper('a4', 'landscape');
```

or a custom size (units are PT, 72 PT per inch) using an array of four decimal values, with the first two values always 0:

```
$dompdf->setPaper([0, 0, 500, 500]);
```

Page margins are set via CSS. For example, no margins:

```
@page { margin: 0px; }
```

You can find a lot of this information in the [wiki](https://github.com/dompdf/dompdf/wiki).
