### ISSUE TITLE
Custom Font not support 

### ISSUE THREAD

**Issue by ratandeora1** [dompdf/dompdf#3184]
I m trying to add custom font but its not support and i m aslo add font on my server
```
@font-face {
        font-family: "poppins";           
        src: url("fonts/Poppins-Black.ttf");
        font-weight: normal;
        font-style: normal;
    }
```

but not working

**Comment by bsweeney** [comment]
Where is the font in relation to the HTML file and or PHP script? What is the relevant PHP script used to load the HTML into Dompdf? Local file paths have to be relative either to the HTML file (if using `$dompdf->loadHtmlFile()`) or the executing PHP script (if using `$dompdf->loadHtml()`).

**Comment by ratandeora1** [comment]
> Where is the font in relation to the HTML file and or PHP script? What is the relevant PHP script used to load the HTML into Dompdf? Local file paths have to be relative either to the HTML file (if using `$dompdf->loadHtmlFile()`) or the executing PHP script (if using `$dompdf->loadHtml()`).

I m using this code

$dompdf->loadHtml($html);

**Comment by bsweeney** [comment]
So if the script is in, as an example, /inet/lib/, then the font would have to be under /inet/lib/fonts.
