### ISSUE TITLE
dompdf is rendering emoji SVG images differently then the browser

### ISSUE THREAD

**Issue by ibizavenue** [dompdf/dompdf#3187]
Hello,

We are using dompdf for an HTML editor we are developing. The HTML editor supports SVG images and hence the PDF generated file also needs to support SVG. The SVG images we'd like to support are emojis. We have tried using emojis (SVGs) from Google and OpenMoji. Both are rendered "incorrectly" (differently than the browser/editor). See image below showing differences. 

PNGs work correctly.

Is there a fix/workaround?

![emoji-dompdf](https://user-images.githubusercontent.com/25492496/233704580-931d6943-c2da-48e7-88d7-a848949e9cf7.png)

**Comment by bsweeney** [comment]
Which version of Dompdf and php-svg-lib are you using? Do you have a sample of the SVG for those emoji?

In the latest release of both Dompdf and php-svg-lib I used the following:
```
<img src="https://openmoji.org/data/color/svg/1F600.svg">
```
and the emoji rendered as expected

**Comment by ibizavenue** [comment]
Thanks for the quick reply! 😊

I believe it is version 2.0.0 but I need to confirm with the developer regarding the version of Dompdf he is using. (Need to get back to you on this.)

The OpenMoji file you pointed to, https://openmoji.org/data/color/svg/1F600.svg matches the one we are using (and is problematic for us). See attached SVG.

I've also attached the rendered PDF showing the problem. (Note the missing eyes.) Maybe this can help identify the issue?

![1F600](https://user-images.githubusercontent.com/25492496/233724623-d8a9f5ae-2833-4377-9535-472bcd731a65.svg)

[emoji-1F600.pdf](https://github.com/dompdf/dompdf/files/11298911/emoji-1F600.pdf)

**Comment by bsweeney** [comment]
OK yes that's the one that rendered OK. Here's the PDF I generated: [render.pdf](https://github.com/dompdf/dompdf/files/11298979/render.pdf)

You can test this out yourself on the [debug helper](https://eclecticgeek.com/dompdf/debug.php), though I don't currently have a way to select the version of php-svg-lib in use. But you can see the difference if you switch between 2.0.3 and 1.2.2

**Comment by ibizavenue** [comment]
Tried the debug helper. It renders correctly with the latest version 2.0.3 and incorrectly with the older version we are running (2.0.0).

I'll ask my developer to update the version.

Thanks very much for your super quick reply - much appreciated!!!!!

**Comment by bsweeney** [comment]
Thanks for the follow up and glad to hear it should be an easy fix.

**Comment by ibizavenue** [comment]
Thank you for your effort on this lib!

**Comment by ibizavenue** [comment]
Again, thanks for the quick reply. ⭐⭐⭐⭐⭐

Not sure whether your suggested workaround is a viable solution. There are about 2000 images in the Google set. I haven't gone through them to see how many are problematic. (The problem may be with a small subset or it may be with the entire set??? It would need further investigation.)

I took a look at the related issue you mention. I notice that it has been open for a while. Any time for resolving this? (A timeline will help us determine whether we provide support for Google emojis in our editor.)

**Comment by ibizavenue** [comment]
Completely understand and very much appreciate your effort with Dompdf (and associated libs). 

I'll investigate to see whether a search and replace is feasible or not.

Best regards,
