### ISSUE TITLE
Not downloading all font weights at once from Google Fonts link

### ISSUE THREAD

**Issue by UVLabs** [dompdf/dompdf#3188]
If you add the following link tag to the HTML file, DomPDF won't download the normal and 600 font-weight for those fonts at once:

`<link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@600&family=Titillium+Web:wght@600&display=swap" rel="stylesheet" type="text/css">`

It will only download the 600 font-weight:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/10324144/233787442-ac071d37-4d88-40fd-87e5-35718b70ae69.png">

To get the `normal` font-weight downloaded, you'd have to remove the weight attributes from the link and generate the PDF again so that DomPDF can download the `normal` font-weight:

`<link href="https://fonts.googleapis.com/css2?family=Noto+Sans&family=Titillium+Web&display=swap" rel="stylesheet" type="text/css">`

At that point, DomPDF would have the `installed-fonts.json` file like this:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/10324144/233787389-550466cd-22c6-4ae5-98d2-514ca7356f04.png">

It seems like DomPDF is forgetting that a normal font-weight exists once it sees the `wght@` attribute in the Google fonts link

**Comment by bsweeney** [comment]
There's no issue here. The URL with the font weight only specifies the font files with a weight of 600. There is no reference to the normal font weight. You can see that by [opening up the stylesheet](https://fonts.googleapis.com/css2?family=Noto+Sans:wght@600&family=Titillium+Web:wght@600&display=swap) in your browser.

If you want to load both the normal-weight font and the 600-weight font you have to select that variant as well. That looks like this for Titillium (I also threw in the italic version):

```
<link href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital,wght@0,400;0,600;1,400;1,600&display=swap" rel="stylesheet">
```

**Comment by UVLabs** [comment]
Ah, thank you
