### ISSUE TITLE
Checkbox makes the pdf file over 10x bigger 

### ISSUE THREAD

**Issue by Aeropixel** [dompdf/dompdf#3189]
Hi!
I'm using barryvdh/laravel-dompdf v2.0.1 which is a wrapper of dompdf and I'm having the following issue:

When adding **_any checkbox_** to a pdf the generated file multiplies its size, memory consumption and time to process the file.
Previously everything was working fine, with my file having around 20KB of space, processed in about 100ms and now it takes almost 1MB and is processed in about 1 entire second.
There are no errors, the document apparently looks the same but the filesize is enormous now.

I've tried tried to generate a new file just with a single checkbox and these are the results:
![image](https://user-images.githubusercontent.com/5835615/234020038-e5e9939a-9461-4c7d-b392-79874db1a654.png)
![image](https://user-images.githubusercontent.com/5835615/234020932-7db0e7a6-539c-41ac-a86e-851e453869af.png)

Any ideas? Did anyone else has this issue?

**Comment by bsweeney** [comment]
Check boxes (and other form fields) require the use of the bundled DejaVu fonts to render the appropriate character(s). This doesn't cause a significant increase in file size unless you have font subsetting disabled.
