### ISSUE TITLE
Call to a member function get_content_box() on null  

### ISSUE THREAD

**Issue by stefandoorn** [dompdf/dompdf#3194]
DOMPDF version: `v2.0.3`
PHP version: `7.4`

I have an HTML that renders perfectly fine when ran in a single command or stand-alone thing. Now we moved some of our PDF generation into Symfony Messenger and that's a long running thread, and it seems that sometimes the PDF generation errors. I do suspect that there is something kept in memory and/or not cleaned properly. Unfortunately, I haven't figured it out myself yet what could be the cause here.

It only happens sometimes, and I feel it's only when there is 2 PDF's generated in a single run of messages being handled. We quit our queue after 45 seconds and re-start it, and based on our traffic it doesn't happen that often that 2 generations get in the same run.

Error: `Call to a member function get_content_box() on null`  

In this block of code:

```
$block_parent = $frame->find_block_parent();
$parent_content = $block_parent->get_content_box();
```

Path: `src/FrameReflower/Block.php`

PDF generation itself is rather simple:

```
$options = new Options();
$options->setChroot(sprintf('%s/public/bundles', $projectDir));

$pdf = new Dompdf($options);

$pdf->loadHtml($this->html);
$pdf->setPaper('Letter', 'portrait');
$pdf->render();
```

The HTML is rather simple and have been working for several years rather flawless.

I can confirm locally it happens on consecutive runs only. The first PDF gets generated, the second errors:

```
#0 /var/www/html/symfony/vendor/dompdf/dompdf/src/FrameReflower/Block.php(236): Dompdf\FrameReflower\Block->_calculate_width()
#1 /var/www/html/symfony/vendor/dompdf/dompdf/src/FrameReflower/Block.php(811): Dompdf\FrameReflower\Block->_calculate_restricted_width()
#2 /var/www/html/symfony/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Block->reflow()
#3 /var/www/html/symfony/vendor/dompdf/dompdf/src/FrameReflower/Inline.php(162): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#4 /var/www/html/symfony/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Inline->reflow()
#5 /var/www/html/symfony/vendor/dompdf/dompdf/src/FrameReflower/Page.php(142): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#6 /var/www/html/symfony/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Page->reflow()
#7 /var/www/html/symfony/vendor/dompdf/dompdf/src/Dompdf.php(765): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#8 /var/www/html/symfony/bundles/OrderInvoicePdfBundle/Pdf/Pdf.php(40): Dompdf\Dompdf->render()
```

**Comment by stefandoorn** [comment]
Original code that gave issues (this service is marked as `shared: false` so Symfony should create a new object each time it's requested:

```php
class Pdf
{
    /**
     * @var Dompdf
     */
    private $pdf;

    /**
     * @var string
     */
    private $html;

    public function __construct(string $projectDir)
    {
        $options = new Options();
        $options->setChroot(sprintf('%s/public/bundles', $projectDir));

        $this->pdf = new Dompdf($options);
    }

    public function setHtml(string $html)
    {
        $this->html = $html;
    }

    public function generate(): string
    {
        $this->pdf->loadHtml($this->html);
        $this->pdf->setPaper('Letter', 'portrait');
        $this->pdf->render();

        $font = $this->pdf->getFontMetrics()->get_font('Helvetica', 'normal');
        /** @var CPDF $canvas */
        $canvas = $this->pdf->getCanvas();
        $canvas->page_text(300, 768, '{PAGE_NUM} / {PAGE_COUNT}', $font, 6, [0, 0, 0]);

        return $this->pdf->output();
    }
}
```

Refactored into:

```php
class Pdf
{
    private Options $options;

    private string $html;

    public function __construct(string $projectDir)
    {
        $this->options = new Options();
        $this->options->setChroot(sprintf('%s/public/bundles', $projectDir));
    }

    public function setHtml(string $html)
    {
        $this->html = $html;
    }

    public function generate(): string
    {
        $pdf = new Dompdf($this->options);

        $pdf->loadHtml($this->html);
        $pdf->setPaper('Letter', 'portrait');
        $pdf->render();

        $font = $pdf->getFontMetrics()->get_font('Helvetica', 'normal');
        /** @var CPDF $canvas */
        $canvas = $pdf->getCanvas();
        $canvas->page_text(300, 768, '{PAGE_NUM} / {PAGE_COUNT}', $font, 6, [0, 0, 0]);

        return $pdf->output();
    }
}
```

Error is now gone locally. So it seems to have to do something with re-using the object `Dompdf` of on consecutive runs sharing memory. And maybe something combined with how the Symfony service container works.

Anyway - closing it as it solves my problem but keeping the issue for others.

**Comment by bsweeney** [comment]
Thanks for the posting your finding. I've seen issues in the past with rendering multiple documents without destroying/reinstantiating Dompdf, though not this particular error. Not much work has been done to alleviate this type of issue so any long-running service that utilizes Dompdf should instantiate a new instance on each use, as you did in your refactor.
