### ISSUE TITLE
Is any way to do anchor links?

### ISSUE THREAD

**Issue by sdsoldi** [dompdf/dompdf#3197]
I need to do an anchor link but a tag is showing like text

```
<div id="todiv">Title</div>
<a href="#todiv">Go top</a>
```

**Comment by sdsoldi** [comment]
My bad... dummy works. In my pdfs no :( I'm going to check all the tags

Thanks and sorry for issue

**Comment by bsweeney** [comment]
No worries. There have been some scenarios in the past where the document structure impacted how the links rendered. If you continue to run into the issue and can isolate the problematic layout let us know.
