### ISSUE TITLE
NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/741

### ISSUE THREAD

**Issue by adityadees** [dompdf/dompdf#3204]
I'm not really sure where's the issue come from but the error is like this

<img width="1393" alt="image" src="https://github.com/dompdf/dompdf/assets/37553901/a555a7d4-12ca-4651-90a2-7146057a0c9a">

I'm using 
- laravel  9.52.7  
- PHP 8.1.11
- dockekr  with alpine
- imagic   3.7.0

some of configuration is like this
<img width="692" alt="image" src="https://github.com/dompdf/dompdf/assets/37553901/4cf2acb8-58b3-4d26-8f31-29d5825d2ba1">

<img width="1417" alt="image" src="https://github.com/dompdf/dompdf/assets/37553901/5388f42a-97cd-46f3-88c1-72130d9c89be">
<img width="1417" alt="image" src="https://github.com/dompdf/dompdf/assets/37553901/4a0ebcdd-7c08-4260-a1e3-62808489a96a">

- and use this package https://github.com/barryvdh/laravel-dompdf

the error is when I'm trying to use base 64 like this
`<img src="data:image/png;base64,' . base64_encode($myImage)" />`

The problem is that different images have different results, sometimes it can generate a pdf, sometimes it can't because of an image error. the error that appears is like this

```NoDecodeDelegateForThisImageFormat `PNG' ` or `NoDecodeDelegateForThisImageFormat `JPG' ```

anyone know why I got this error?

**Comment by bsweeney** [comment]
That sounds like a general issue processing the image format. I.e., something about the image isn't supported by your copy of IMagic. If you can post a sample image that causes the issue we can take a look.

Might need to add a GD fallback when imagick fails.

**Comment by adityadees** [comment]
so are that means we can't use any image for processing?

**Comment by adityadees** [comment]
fixed !

**Comment by bsweeney** [comment]
Glad you were able to figure it out. How'd you fix it (in case anyone else encounters the same issue)?

**Comment by adityadees** [comment]
I'll reopen this issue till you think this clear for you

1. I'm using alpine container with php 8.1

2. add this `php81-pecl-imagick --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community`
 <img width="650" alt="image" src="https://github.com/dompdf/dompdf/assets/37553901/cfe68cc9-7197-4b02-90b7-7264f661c353">
 

3. and this my latest ext configuration I just add ` imagemagick ` but I don't think this ext really matters, what matters is the `php81-pecl-imagick` part above, and you need download it from community repository
<img width="650" alt="image" src="https://github.com/dompdf/dompdf/assets/37553901/cb9ff1b4-a004-453b-bbb8-1a8a6b98598d">


4. and now I got all the supported format 
<img width="1072" alt="image" src="https://github.com/dompdf/dompdf/assets/37553901/d8efc1f0-3c89-4e0e-85ee-8b6f3dac3066">
