### ISSUE TITLE
Stream method generates broken PDF file, while saving output to file works just fine

### ISSUE THREAD

**Issue by kordianurban** [dompdf/dompdf#3206]
When i generate a PDF file and save it to file on the server it works just fine, but when i use $dompdf->stream('my-file.pdf'); the PDF wont load

**Comment by kordianurban** [comment]
To be honest even this simple code wont load pdf properly:
```
$dompdf = new Dompdf();
$dompdf->loadHtml('hello world');

// (Optional) Setup the paper size and orientation
$dompdf->setPaper('A4', 'landscape');

// Render the HTML as PDF
$dompdf->render();

// Output the generated PDF to Browser
$dompdf->stream();
```

**Comment by bsweeney** [comment]
So what does happen?

**Comment by kordianurban** [comment]
literally nothing, chrome tries to download pdf but it fails and it keeps trying, even after success the pdf wont load and its says "unable to load pdf"

**Comment by bsweeney** [comment]
Could be that the connection to the server isn't being closed appropriately by some process. You might try calling `exit;` after the stream method.

**Comment by kordianurban** [comment]
i do right after stream method

**Comment by bsweeney** [comment]
But the streamed file does look like a PDF? Can you share a URL or copy of the file?

**Comment by kordianurban** [comment]
looks like my issue is font based, when i removed `font-family: "dejavu sans"; `it worked, however i am now not able to makeit work with the font

**Comment by kordianurban** [comment]
Yeah exactly, i would be completely fine with it as long as it would be broken in both ways, but i was able to save pdf to file on the server and mail it to myself, but it wouldnt load when streamed, ill give it a try and play a bit with the font, thanks for help

**Comment by kordianurban** [comment]
So the result of my testing is:
no font-family - works
font-family: Courier; - works
font-family: DejaVu Sans; - not working

**Comment by bsweeney** [comment]
Would need additional information to understand what's happening here. The wiki has some [troubleshooting tips](https://github.com/dompdf/dompdf/wiki/Troubleshooting-Dompdf).
