### ISSUE TITLE
ImagickException: NoDecodeDelegateForThisImageFormat `PNG'

### ISSUE THREAD

**Issue by JeyjooMilano** [dompdf/dompdf#3209]
Hello,

DomPDF workds perfectly on ny test server. On the production server I get the following error:

ImagickException: NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/741 in /dompdf/vendor/dompdf/dompdf/lib/Cpdf.php:5709

Any ideas what is goign wrong?

Thank you

**Comment by bsweeney** [comment]
No idea, but maybe the OP from #3204 can provide guidance.
