### ISSUE TITLE
Call to undefined function Dompdf\Renderer\imagecreatefromjpeg() in laravel

### ISSUE THREAD

**Issue by TungLeFlex** [dompdf/dompdf#3214]
I'm using dompdf v2.0.0 and barryvdh/laravel-dompdf v2.0.0 in my laravel project. And i use `extension=gd2;` in php.ini
I want to create a PDF file and view on browser from template.blade.php. However, I get this error and don't get PDF view. After that, move to vendor/dompdf/dompdf/src/Renderer/AbstractRenderer.php delete following lines:
```
case "jpeg":
      $src = @imagecreatefromjpeg($img);
      break;
```
What should I do to use imagecreatefromjpeg()?

**Comment by bsweeney** [comment]
First, don't remove any lines from the source. I mean, you _can_ but then you're probably breaking Dompdf functionality.

`imagecreatefromjpeg` is a core function within GD. You're probably missing the libjpeg supporting library or your php build wasn't configured correctly.

When you execute `php -i` from the command line the GD section will indicate if JPEG is supported:

```
gd

GD Support => enabled
GD Version => bundled (2.1.0 compatible)
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.9.1
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 9 compatible
PNG Support => enabled
libPNG Version => 1.6.34
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30512
XBM Support => enabled
WebP Support => enabled
BMP Support => enabled
TGA Read Support => enabled
```

**Comment by TungLeFlex** [comment]
I have add following code in Dockerfile to build on Docker. And I don't get any error while building:
```
RUN apt-get update && apt-get install -y \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libzip-dev \
    vim \
    libjpeg-dev
RUN docker-php-ext-configure zip \
  && docker-php-ext-install zip gd
```

**Comment by tony84727** [comment]
Try adding `docker-php-ext-configure gd --with-jpeg`
```
RUN docker-php-ext-configure zip \
  && docker-php-ext-configure gd --with-jpeg \
  && docker-php-ext-install zip gd
```

Might be related to https://github.com/docker-library/php/issues/926
