### ISSUE TITLE
Urgent: Problem with loadfile on Laravel 10

### ISSUE THREAD

**Issue by lucapellegrino70** [dompdf/dompdf#3218]
Hello,
I am trying to convert html to pdf as follows:

use Barryvdh\DomPDF\Facade\Pdf;

  $pdf = app()->make('dompdf.wrapper');
  $pdf = \PDF::loadFile(public_path('templates/myfile.html));
  $pdf->setPaper('A4', 'portrait');
  $pdf->save(public_path('templates/blabla.pdf));

This code was working but since I updated Laravel and Barryvdh is not working anymore, it gives error in loadfile

How can I solve this?

Thank you

**Comment by bsweeney** [comment]
Solved? I don't use laravel but others might so you can help others by sharing your solution if you found one.
