### ISSUE TITLE
Uncaught Error: Call to undefined function mb_strtolower()

### ISSUE THREAD

**Issue by chris883773** [dompdf/dompdf#3219]
Hello,

i got the following error in: 
tail -f /var/log/apache2/error.log

_[Fri Jun 02 12:57:09.453689 2023] [php7:error] [pid 638] [client XXX.xxx.XXX.xxxx:60946] PHP Fatal error:  Uncaught Error: Call to undefined function mb_strtolower() in /usr/share/php/dompdf/include/autoload.inc.php:19\nStack trace:\n#0 [internal function]: DOMPDF_autoload()\n#1 /var/www/html/create_pdf.php(88): spl_autoload_call()\n#2 {main}\n  thrown in /usr/share/php/dompdf/include/autoload.inc.php_

I hope that anybody can help me.

**Comment by bsweeney** [comment]
Dompdf relies on the MBString extension for PHP. Install that and the error should go away.

Also worth noting, you seem to be using an older version of Dompdf. Recommend upgrading to the latest if you can.
