### ISSUE TITLE
Broken images after CakePHP and PHP upgrade

### ISSUE THREAD

**Issue by vonba** [dompdf/dompdf#3221]
After upgrading CakePHP from 3.x to 4.x, images now no longer load ("image not found or type unknown").
I am loading images from the local filesystem using full, absolute paths. I have also tried using a web accessible URL with the same result.

**Upgrades:**
cakephp/cakephp 3.8 => 4.4
friendsofcake/cakepdf 3.5 => 4.1.2
dompdf/dompdf 0.8.3 => 2.0
PHP was also upgraded from 7.4 to 8.2.

Everything other than the images works perfectly. Even when testing with a hardcoded (and triple checked) path, the images do not load. To be clear: nothing other than upgrading has changed, including permissions.

**Example:**
`<img src="/Users/myuser/htdocs/myproject/webroot/img/logo.png" alt="Logo" />
`
CakePdf config:
```
Configure::write('CakePdf', [
    'engine' => 'CakePdf.DomPdf',
    'options' => [
        'isRemoteEnabled' => true
    ]
    'margin' => [
        'bottom' => 50,
        'left' => 50,
        'right' => 50,
        'top' => 50
    ],
    'encoding' => 'UTF-8',
    'orientation' => 'portrait',
    'download' => true,
]);
```

**Comment by bsweeney** [comment]
With newer releases of Dompdf local resources must be allowed by setting the chroot option. Using the information you provided it would probably look something like this:

```
Configure::write('CakePdf', [
    'engine' => 'CakePdf.DomPdf',
    'options' => [
        'isRemoteEnabled' => true,
        'chroot' => ['/Users/myuser/htdocs/myproject/webroot/img']
    ]
    'margin' => [
        'bottom' => 50,
        'left' => 50,
        'right' => 50,
        'top' => 50
    ],
    'encoding' => 'UTF-8',
    'orientation' => 'portrait',
    'download' => true,
]);
```

chroot is an array of paths so you can specify all the relevant resource paths (or a single one that encompasses all resources paths).
