### ISSUE TITLE
Entire text shows as one paragraph

### ISSUE THREAD

**Issue by Bhushannn** [dompdf/dompdf#3233]
I am using the Dompdf to download the text from Textarea. In my textarea, I have multiple paragraphs, but when I download them as pdf they show all as one paragraph. Please help me to fix this issues. Urgently Important

**Comment by bsweeney** [comment]
Dompdf is an HTML parser and so, just like with a web browser, plain text will render without line breaks.

If you want to render text with the included line breaks you'll need to adjust the [white-space styling](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space).
