### ISSUE TITLE
h1-hx dont have custom fonts applied

### ISSUE THREAD

**Issue by manuelKruesi** [dompdf/dompdf#3234]
Hello together, i'm currently having an issue where i want to use css-loaded fonts in the pdf. 
But i noticed that all the title tags are not styled with the font as you can see in the attached screenshot:
![Bildschirmfoto 2023-06-23 um 16 45 58](https://github.com/dompdf/dompdf/assets/48511934/f271f83a-fee7-4171-897f-881e05c3926d)
The html looks like the following:

```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Caprasimo&display=swap" rel="stylesheet">
		<style>
			
			body {
				font-family: 'Caprasimo', sans-serif !important;
			}
			h1{
				font-family: 'Caprasimo', sans-serif !important;
				font-size: 90px;
			}
		</style>
	</head>
	<body>
		<h1>This is h1 text</h1>
		<div><p>this is p text</p></div>
	</body>
</html>
```
And these are the options for DomPdf on generation of the PDF:
```		
$this->dompdf->set_option('fontDir', realpath(TEMP_PATH));
$this->dompdf->set_option('fontCache', realpath(TEMP_PATH));
$this->dompdf->set_option('tempDir', realpath(TEMP_PATH));
$this->dompdf->set_option('chroot', realpath(TEMP_PATH));
$this->dompdf->set_option('isRemoteEnabled', true);
```
Is this a known issue? Only reference i've found is the following: [issue#2064](https://github.com/dompdf/dompdf/issues/2064)
Or am I overlooking something? Feedback would be greatly appreciated!
Cheers

**Comment by bsweeney** [comment]
While browsers will often attempt to simulate font variants if a supporting file isn't present, Dompdf requires the actual font variant. The font you're attempting to use only includes the normal variant, but H1 text is bold so you would need a font that supports bold as well.

You can still use the font for H* elements, but you would need to modify the styling so that these elements are not bold.

```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Caprasimo&display=swap" rel="stylesheet">
		<style>
			
			body {
				font-family: 'Caprasimo', sans-serif !important;
			}
			h1{
				font-family: 'Caprasimo', sans-serif !important;
				font-size: 90px;
				font-weight: normal;
			}
		</style>
	</head>
	<body>
		<h1>This is h1 text</h1>
		<div><p>this is p text</p></div>
	</body>
</html>
```
