### ISSUE TITLE
Inconsistent PDF Output and Missing Fonts in Dev and Prod Environments

### ISSUE THREAD

**Issue by lavaqq** [dompdf/dompdf#3235]
My controller :

```php
    public function show(Invoice $record)
    {
        $html = view('test', ['data' => $record])->render;

        $tmp = sys_get_temp_dir();

        $dompdf = new Dompdf([
            'logOutputFile' => '',
            'isRemoteEnabled' => true,
            'fontDir' => $tmp,
            'fontCache' => $tmp,
            'tempDir' => $tmp,
            'chroot' => $tmp,
        ]);

        $dompdf->loadHtml($html);

        $dompdf->render();

        $dompdf->stream('test.pdf', [
            'compress' => true,
            'Attachment' => false,
        ]);
    }
    public function testShow(Invoice $record)
    {
        $html = view('pdf.invoice', ['data' => $record]);
        $dompdf = new Dompdf();
        $dompdf->loadHtml($html);
        $dompdf->render();
        $dompdf->stream();
    }
```

My blade file :
```html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Poppins';
            margin: 64px;
        }
    </style>
</head>

<body>
    <p>REFERENCE : {{ $data->reference }}</p>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique soluta nihil quos beatae quam recusandae
        repellendus sequi tenetur consequuntur explicabo quia, ad ipsa repudiandae! Non laboriosam sed praesentium fugit
        veniam.
    </p>
</body>

</html>
```

The show function in my application is currently causing issues with PDF rendering. In the development environment, it returns a blank PDF, while in the production environment on a web server, it returns a string representation of the PDF (screenshot: [link](https://imgur.com/8XE58x2)).

The testShow function generates a PDF without fonts in the dev environment and exhibits the same behavior as the show function in the prod environment.

Appreciate your assistance in resolving this issue.

**Comment by lavaqq** [comment]
The blank PDF was my my fault `$html = view('test', ['data' => $record])->render;` needed to be `$html = view('test', ['data' => $record])->render();`

The Poppins font is loading in dev environment but in the prod environment still (screenshot: [link](https://imgur.com/8XE58x2)).

**Comment by lavaqq** [comment]
If we add an `exit()` at the end of the show function, the pdf appears in production. But still no font.

src : [link](https://stackoverflow.com/questions/66701059/dompdf-not-generating-pdf-on-production-server-only-showing-code)

**Comment by lavaqq** [comment]
I checked the permissions on the server and ran a test with :

```php
    $name = 'testfile.txt';
    $content = "test";
    $directory = sys_get_temp_dir();
    $path = $directory . DIRECTORY_SEPARATOR . $name;
    $handle = fopen($path, 'w');
    if ($handle !== false) {
        fwrite($handle, $content);
        fclose($handle);
    }
```

Everything works on this side. I'm a bit lost with the problem.

Is it possible to use a local font instead of the remote method?

**Comment by bsweeney** [comment]
Of course, just specify a path to the file on the filesystem, relative to the executing PHP script or absolute from the root of the filesystem. And make sure whatever path you use is specified for the chroot option.

**Comment by lavaqq** [comment]
I've tried everything I know, but I can't get any production results. I've given up on the idea of putting a font outside the library core. 

Thank you for trying to help me and for your time.

**Comment by lavaqq** [comment]
In the end, I did look for a solution and I succeeded.

I finally used [laravel-dompdf](https://github.com/barryvdh/laravel-dompdf) which is a dompdf wrapper for Laravel.

I created a fonts folder in the storage with in it the font ttf files.

```
.
├── bootstrap 
├── config 
├── database 
├── public 
├── resources 
├── routes 
├── storage/
│   └── fonts/
│       ├── Poppins-Medium.ttf
│       └── Poppins-SemiBold.ttf
└── tests 
```

I created  the gitignore :

```
/*
!Poppins-Medium.ttf
!Poppins-SemiBold.ttf
!.gitignore
```

I modified the css of the blade file:

```
@font-face {
    font-family: 'Poppins';
    font-style: normal;
    font-weight: 500;
    src: url({{ storage_path('fonts/Poppins-Medium.ttf') }}) format('truetype');
}

@font-face {
    font-family: 'Poppins';
    font-style: normal;
    font-weight: 600;
    src: url({{ storage_path('fonts/Poppins-SemiBold.ttf') }}) format('truetype');
}
```

I modified my controller using the wrapper's facade:

```php
<?php

namespace App\Http\Controllers;

use Barryvdh\DomPDF\Facade\Pdf;

class testController extends Controller
{
    public function show(Test $record)
    {
        $pdf = Pdf::loadView('pdf.invoice', ['data' => $record]);
        return $pdf->stream($record->name . ' (' . $record->created_at->format('m/d/Y') . ')' . '.pdf');
    }
}
```

Pushed to production and finally everything works.

Thank you for trying to help me and for your time @bsweeney. I hope my issue will maybe help others.

**Comment by bsweeney** [comment]
Glad you were able to work it out. Thanks for posting your solution.
