### ISSUE TITLE
CSS page width different to dompdf page width

### ISSUE THREAD

**Issue by GrandeDominus** [dompdf/dompdf#3236]
Dompdf a4 portrait page width is 595.28 PX. When I create a div with that width using css it doesn't cover the whole page. What is going on here?

**Comment by bsweeney** [comment]
The width is 595.28 *_PT_*. Dompdf performs a translation from PX to PT during the rendering process based on the DPI [Option](https://github.com/dompdf/dompdf/wiki/Usage#options). The default DPI is 96 (to line up with somewhat typical browser DPI). If you want your pixel-dimensions to line up to the document dimensions set that option to 72 (PDFs use a hard-coded PT-per-inch of 72).
