### ISSUE TITLE
I can't get custom fonts to work

### ISSUE THREAD

**Issue by phillipstemann** [dompdf/dompdf#3237]
Hi,

I've made a custom solution as a custom PHP script that takes a URL and then generates a PDF, and everything is working except my custom font.
I'm using Euclid Square as my custom font, and I can't get it to work. Can you see what I'm doing wrong?
Roboto is working perfectly, it's just my local custom font.

    // Generate PDF
    use Dompdf\Dompdf;
    use Dompdf\Options;
    $dompdf = new Dompdf();
    $options = $dompdf->getOptions();
    $options->set('isRemoteEnabled', true);
    $options->set('isFontSubsettingEnabled', true);
    $dompdf->setOptions($options);
    $dompdf->loadHtml('
	<!DOCTYPE html>
	<html>
		<head>
			<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
			<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
			<style>
				@font-face {
					font-family: \'euclid_square_semi_bold\';
					font-style: normal;
					font-weight: normal;
					font-display: auto;
					src: url(/wp-content/uploads/_Fonts/EuclidSquare-Semibold.ttf) format(\'truetype\')
				}
				h3, h4, h5 {
					font-family: Roboto, sans-serif;
					color: #001f4a;
					letter-spacing: -1px;
				}
				h1 {
					font-family: euclid_square_semi_bold, sans-serif !important;
					color: #001f4a;
					font-size: 40pt;
					line-height: 46pt;
					letter-spacing: -1px;
					margin: 0px 0 0 8%;
				}
			</style>
		</head>
		<body>
			<img class="logo" src="/wp-content/uploads/teamslogo.png" />
			' .$divContent. '
			<div class="page_break"></div>
		</body>
	</html>');
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
	$fileName = $blogTitle->item(0)->textContent;
	$fileName = str_replace("å", "aa", $fileName);
	$fileName = str_replace("ø", "o", $fileName);
	$fileName = str_replace("æ", "ae", $fileName);
	$fileName = preg_replace('/\W+/', '-', strtolower(trim($fileName)));
        $dompdf->stream($fileName. ".pdf",array("Attachment" => false));

**Comment by bsweeney** [comment]
First, since you're using `loadHtml` any local filesystem paths are based on:
- the current working directory for paths that _do not_ start with "/"
- the root of the filesystem for paths starting with a "/"

You'll need to make sure the path is valid with that in mind. Presumably wp-content is not in the root of your filesystem.

Local filesystem resource references must be allowed by adding relevant paths to the chroot option.
```
$options->set('chroot', ['/path/to/wp-content']);
```

Note, if this is the problem it would also impact the ability of Dompdf to render your logo image as well.

**Comment by phillipstemann** [comment]
Thank you for the answer bsweeney.
But even if I add the full URL to the font including my domain name like:
https://domain.com/wp-content/uploads/_Fonts/EuclidSquare-Semibold.ttf

Then it still doesn't work.

**Comment by bsweeney** [comment]
In your sample you're styling the H1 element with the Euclid font. Your `@font-face` declaration specifies that Euclid is a normal-weight font. If you want to use Euclid with header elements, you will need to either specify that the font is a bold font, or style your header elements as normal-weight.
