### ISSUE TITLE
Circled digit cannot work, ex: ①②③

### ISSUE THREAD

**Issue by AQ30732653** [dompdf/dompdf#3242]
Chinese work, but circled digit cannot work.
ex: ①②③

blade
```
@font-face {
      font-family: 'microsoft jhenghei';
      font-weight: normal;
      font-style: normal;
      font-variant: normal;
      src: url({{ storage_path('fonts/microsoft-jhenghei.ttf') }}) format('truetype');
    }

    body {
      font-family: 'microsoft jhenghei', serif;
    }
```

controller

```
return Pdf::loadHTML($html)
            ->setPaper('a4')
            ->setOption('isPhpEnabled', true)
            ->setOption('isFontSubsettingEnabled', true)
            ->setOption('encoding', 'UTF-8')
            ->download('example.pdf');
```

**Comment by bsweeney** [comment]
Does the font support those characters?

**Comment by AQ30732653** [comment]
> Does the font support those characters?

It works in html as long as the content-type is text/html

```
return response($html)
        ->header('Content-Type', 'text/html');
```

**Comment by bsweeney** [comment]
I'm sure, but web browsers have a more robust font selection mechanism than Dompdf. In most web browsers if a font does not support a character the browser will try another available font, with the default font usually supporting most characters. In current releases of Dompdf if the font does not support a character the character will not display.

I pulled the font from one of my own systems and it renders that character. It's possible the variant you're using does not support the character.

**Comment by AQ30732653** [comment]
I am give up. Because dompdf cannot support circle digit.

**Comment by bsweeney** [comment]
> dompdf cannot support circle digit

Well, that's not true. I rendered the attached with Dompdf. But if you don't have the time to try and determine the issue that's understandable.

[3242.html.pdf](https://github.com/dompdf/dompdf/files/12134817/3242.html.pdf)
