### ISSUE TITLE
Margin added on Print view of PDF

### ISSUE THREAD

**Issue by jenb-jbcole** [dompdf/dompdf#3265]
Hello,

We are having this issue where generating the PDF looks ok on Chrome, but as soon as the user tries to print it, it adds margin left, right and bottom of paper. We are setting the default paper size to be A4, and this is also what the print view is using, so it's confusing why this is happening.
Additionally, I saw people suggesting @page {margin:0px} but this did not work. I'm not actually sure if there's another setup needed to get this @page syntax to work? All I know is that adding it to my css file made no difference (any other styles such as @page {background-color:red} for example does not work either).

Please any suggestions? 🙏

**Comment by bsweeney** [comment]
No need to post your question in multiple locations. Will answer in the [discussion](https://github.com/dompdf/dompdf/discussions/3264).
