### ISSUE TITLE
 mb_convert_encoding(): Unable to detect character encoding in

### ISSUE THREAD

**Issue by AntonSibgatulin** [dompdf/dompdf#3277]
Warning: mb_convert_encoding(): Unable to detect character encoding in /var/www/html/dompdf/vendor/dompdf/dompdf/src/Dompdf.php on line 435

Warning: mb_convert_encoding(): Unable to create character encoding converter in /var/www/html/dompdf/vendor/dompdf/dompdf/src/Dompdf.php on line 435

Fatal error: Uncaught Error: Class 'DOMImplementation' not found in /var/www/html/dompdf/vendor/masterminds/html5/src/HTML5/Parser/DOMTreeBuilder.php:172 Stack trace:
0 /var/www/html/dompdf/vendor/masterminds/html5/src/HTML5.php(157): Masterminds\HTML5\Parser\DOMTreeBuilder->__construct()
1 /var/www/html/dompdf/vendor/masterminds/html5/src/HTML5.php(89): Masterminds\HTML5->parse()
2 /var/www/html/dompdf/vendor/dompdf/dompdf/src/Dompdf.php(478): Masterminds\HTML5->loadHTML()
3 /var/www/html/uploud.php(115): Dompdf\Dompdf->loadHtml()
4 /var/www/html/uploud.php(215): splitImage()
5 {main} thrown in /var/www/html/dompdf/vendor/masterminds/html5/src/HTML5/Parser/DOMTreeBuilder.php on line 172

**Comment by bsweeney** [comment]
The encoding issue could be related to the fix proposed in #3270. Would need to see your HTML to validate the issue.

As for the DOMImplementation error ... no idea. The Internet seems to indicate you're maybe missing the DOM module from your PHP installation ([ref](https://stackoverflow.com/a/4258282/264628)).
