### ISSUE TITLE
svg: mismatch in size of pdf 

### ISSUE THREAD

**Issue by EvEggelen** [dompdf/dompdf#3283]
I am trying to workaround the problem of not supporting inline svg in Dompdf 2.0.3. I tested the html with the W3 validator and in a webbrowser. The output in a webbrowser is as expected ( www.fiddly.org/fe89a ). However the sizes of the svg do not match in the pdf ( see attachment ). Is there something that I am missing or how I can workaround it. Is this issue still present in the master ?

in PHP I make the image with the following code:
```
$inlinesvg=<<<EOT
                       <svg  version="1.1" viewBox="0 0 100 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg">
                         <rect x="0" y="0" width="100" height="100" />
                         <circle cx="50" cy="50" r="25" fill="white" />
                       </svg>
EOT; 
$testSVG .='<img class="graph" src="data:image/svg+xml;base64,' . base64_encode($inlinesvg) . '">';
```

```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>SVG tests</title>
    <style>
    body {
         width: 210mm;
         height: 281mm;
         padding: 0mm;
         overflow: hidden;
       }
       
    .graph {
         width: 210mm;
         height: 105mm;
       }
    </style>
  </head>
    <body>
       <div>
            <img class="graph" alt="svg" src="data:image/svg+xml;base64,ICAgICAgICAgICAgICAgICAgICAgICA8c3ZnIHZlcnNpb249IjEuMSIgdmlld0JveD0iMCAwIDEwMCAxMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgICAgICAgICAgICAgICAgICAgICAgICA8IS0tCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGNpcmNsZSBjeD0iNTAlIiBjeT0iNTAlIiByPSI1MCUiIHN0cm9rZT0iYmxhY2siIHN0cm9rZS13aWR0aD0iMSIgZmlsbD0iIzAwQTE5OCI+PC9jaXJjbGU+CiAgICAgICAgICAgICAgICAgICAgICAgICAtLT4KICAgICAgICAgICAgICAgICAgICAgICAgIDxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiAvPgogICAgICAgICAgICAgICAgICAgICAgICAgPGNpcmNsZSBjeD0iNTAiIGN5PSI1MCIgcj0iNTAiIGZpbGw9IndoaXRlIiAvPgogICAgICAgICAgICAgICAgICAgICAgIDwvc3ZnPg==">
       </div>
    </body>
</html>
```
[test_svg.pdf](https://github.com/dompdf/dompdf/files/12709128/test_svg.pdf)

**Comment by bsweeney** [comment]
Seems ... fine? I get pretty much the same output when I print to PDF. Maybe I don't understand your expectation. Can you describe what you're expecting to see in the PDF?

Note that as far as document dimensions, you might want to be using `@page` instead of `body`:

```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>SVG tests</title>
    <style>
    @page {
      width: 210mm;
      height: 281mm;
      margin: 0;
    }
    .graph {
         width: 210mm;
         height: 105mm;
       }
    </style>
  </head>
    <body>
       <div>
            <img class="graph" alt="svg" src="data:image/svg+xml;base64,ICAgICAgICAgICAgICAgICAgICAgICA8c3ZnIHZlcnNpb249IjEuMSIgdmlld0JveD0iMCAwIDEwMCAxMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgICAgICAgICAgICAgICAgICAgICAgICA8IS0tCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGNpcmNsZSBjeD0iNTAlIiBjeT0iNTAlIiByPSI1MCUiIHN0cm9rZT0iYmxhY2siIHN0cm9rZS13aWR0aD0iMSIgZmlsbD0iIzAwQTE5OCI+PC9jaXJjbGU+CiAgICAgICAgICAgICAgICAgICAgICAgICAtLT4KICAgICAgICAgICAgICAgICAgICAgICAgIDxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiAvPgogICAgICAgICAgICAgICAgICAgICAgICAgPGNpcmNsZSBjeD0iNTAiIGN5PSI1MCIgcj0iNTAiIGZpbGw9IndoaXRlIiAvPgogICAgICAgICAgICAgICAgICAgICAgIDwvc3ZnPg==">
       </div>
    </body>
</html>
```

**Comment by EvEggelen** [comment]
In the pdf created by dompdf ( using body ) it looked like there was an offset on the left. Therefore something was missing on the right( as the width was correct). This was not the case in the browser and pdf print from the browser ( see below)
[SVG tests-chrome.pdf](https://github.com/dompdf/dompdf/files/12709306/SVG.tests-chrome.pdf)

But using the @page instead of body resulted in the correct pdf from dompdf ( at least this is what I expected ) . Also browsers give the same output. 
[testusingpage.pdf](https://github.com/dompdf/dompdf/files/12709314/testusingpage.pdf)

Thanks for the tip of using @page. But is it not valid css/html using body ? What could explain the difference in output when using body ?

**Comment by bsweeney** [comment]
Styling the `body` element is valid (try adding `background-color: gold;` to the body styling). `@page` represents the container for the document (the page itself), where the body is considered an element within the page. Where the difference in rendering comes from is that Dompdf applies a default margin to the page while (I think) the browsers do not. With a simple tweak of your original HTML you can get similar rendering from a web browser.

```
  <!DOCTYPE html>
  <html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>SVG tests</title>
    <style>
    @page {
      margin: 1in;
    }
    body {
       width: 210mm;
       height: 281mm;
       padding: 0mm;
       overflow: hidden;
     }
       
    .graph {
         width: 210mm;
         height: 105mm;
       }
    </style>
  </head>
    <body>
       <div>
            <img class="graph" alt="svg" src="data:image/svg+xml;base64,ICAgICAgICAgICAgICAgICAgICAgICA8c3ZnIHZlcnNpb249IjEuMSIgdmlld0JveD0iMCAwIDEwMCAxMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgICAgICAgICAgICAgICAgICAgICAgICA8IS0tCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGNpcmNsZSBjeD0iNTAlIiBjeT0iNTAlIiByPSI1MCUiIHN0cm9rZT0iYmxhY2siIHN0cm9rZS13aWR0aD0iMSIgZmlsbD0iIzAwQTE5OCI+PC9jaXJjbGU+CiAgICAgICAgICAgICAgICAgICAgICAgICAtLT4KICAgICAgICAgICAgICAgICAgICAgICAgIDxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiAvPgogICAgICAgICAgICAgICAgICAgICAgICAgPGNpcmNsZSBjeD0iNTAiIGN5PSI1MCIgcj0iNTAiIGZpbGw9IndoaXRlIiAvPgogICAgICAgICAgICAgICAgICAgICAgIDwvc3ZnPg==">
       </div>
    </body>
  </html>
```

There are additional nuances here between page, html, and body. And probably even slightly different interpretations of those concepts between web browsers and Dompdf. I'd really have to sit down and think through this all before I could provide a more thorough and accurate explanation.
