### ISSUE TITLE
The fallback fonts dont work in dompdf when rendering a pdf in laravel

### ISSUE THREAD

**Issue by MaharshM** [dompdf/dompdf#3297]
### Discussed in https://github.com/dompdf/dompdf/discussions/3296

<div type='discussions-op-text'>

<sup>Originally posted by **MaharshM** October 12, 2023</sup>
I have a blade file which im rendering on a pdf, everything works out great and all, the headers, footers and all the other stuff but the only problem is the content we're rendering is dynamic and our client has customers in multiple countries so we're never really sure what the language of the content exactly is going to be. I have added the css for this like this

STYLE
```
 <style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic&family=Noto+Sans&family=Noto+Sans+SC&display=swap');
    @import url('https://api.fontshare.com/v2/css?f[]=satoshi@500,300,400&display=swap');

        body{
            font-family:  'Satoshi' ,'Noto Sans SC',  'Nato Naskh Arabic',  serif;
        }
</style>
```

Backend code to generate pdf
```
use Barryvdh\DomPDF\Facade\Pdf;

$pdf = Pdf::loadView('GenerateCompanyPdf', $data)->save(public_path('something.pdf'));
return $pdf->download('something.pdf');
```

This renders the pdf in the expected 'Satoshi' font, as expected but the characters that are not in Satoshi are rendered as empty boxes. Ive tried with omitting the Satoshi font and replacing it with Noto Sans SC (Simplified Chinese) and then the chinese characters are displayed as intended. But our entire website is in Satoshi font and we cant change that for just a pdf. Is there something I'm doing wrong or missing? Id appreciate any help or clue i can get, Thanks.</div>

**Comment by bsweeney** [comment]
This was previously reported in #3142 and built out in #3155.

Current releases of Dompdf (up to 2.0.3) do not support this functionality. The functionality will be included in the forthcoming 2.1.0 release and is available in the master branch or the nightly download.
