### ISSUE TITLE
getimagesize(): corrupt JPEG data: 130816 extraneous bytes

### ISSUE THREAD

**Issue by abdulmananse** [dompdf/dompdf#3301]
getimagesize(): corrupt JPEG data: 130816 extraneous bytes before marker at /vendor/dompdf/dompdf/src/Helpers.php:670

**Comment by bsweeney** [comment]
Can you share the JPEG file causing the issue?

**Comment by abdulmananse** [comment]
https://peima-sis.punjab.gov.pk/storage/93718/0811795.jpeg

**Comment by bsweeney** [comment]
I'm not seeing that error with the latest release. Which version are you using?

**Comment by bsweeney** [comment]
I can no longer access the sample image. Please attach to this issue if you wish to pursue. I would like to test in the context of #3507.
