### ISSUE TITLE
Unable to print content of Two equal columns from the First Page

### ISSUE THREAD

**Issue by developernurullah** [dompdf/dompdf#3305]
I'm using DOMPDF for html to pdf conversion in PHP. I've simple CSS for creating two columns in DOMPDF. But whenever content in left column increases, the content of right column jumps to next page.

**Comment by developernurullah** [comment]
I have two column with width 50% , first-column has long content that exceeds the first page and second-column has short content. When we generate pdf, only first-column content printed from the first page, second-column content printed from the second page but I want to get printed both content from the first page. if exceed any one of them then move to the next page

**Comment by bsweeney** [comment]
This is to be expected with the current Dompdf layout engine. I am in the process of working on a fix, which you try out if you want using the [paging-updates](https://github.com/dompdf/dompdf/tree/paging-updates) branch. There are a few related issues you might follow, I suggest #1192.

**Comment by developernurullah** [comment]
Oka

> This is to be expected with the current Dompdf layout engine. I am in the process of working on a fix, which you try out if you want using the [paging-updates](https://github.com/dompdf/dompdf/tree/paging-updates) branch. There are a few related issues you might follow, I suggest #1192.

Okay Thanks

**Comment by developernurullah** [comment]
hello there , there a lot's of issue in this branch [paging-updates](https://github.com/dompdf/dompdf/tree/paging-updates) branch
Please provide me the code by which this the following this issue only fixed 
Unable to print content of Two equal columns from the First Page

**Comment by bsweeney** [comment]
"lot's of issues" meaning what? If the code on that branch isn't working then there are no other options at this point.

**Comment by developernurullah** [comment]
meaning that, When I have set  long content in two column of first row and also add some content in two column or single column of the second row . after that i generate pdf, some part of first row content move to the second page but second rows leaves the pdf page or no printed in pdf page

**Comment by bsweeney** [comment]
I would need to see sample document to provide any guidance.

Note that the paging-updates branch is still a work in progress so it may not sufficiently handle your use case.

**Comment by emmguyot-adscom** [comment]
@bsweeney Thanks for your work in the paging-updates branch.
According to you, what is its current status ?
Do you think we could rebase it on master and try to use it or do you think it isn't stable enough?

**Comment by bsweeney** [comment]
I rebased the branch a few weeks ago so you can try it out if you want. However, I don't think it's functionally ready. There are scenarios where it will produce incorrect output.

**Comment by emmguyot-adscom** [comment]
Ok we'll try this and check if it's ok in our case.

**Comment by bsweeney** [comment]
Looks like I had rebased locally already, I just hadn't pushed the changes. paging-updates should be up-to-date with master, plus the work-in-progress changes to improve content paging.

**Comment by emmguyot-adscom** [comment]
We've tested with our html and the second page isn't properly rendered : Le left column is shifted to the center of the page, whereas the right column is ok.
![image](https://github.com/dompdf/dompdf/assets/16957867/c7bd7134-c206-46db-a935-95fddccda6b0)
Here are the main structure of the column we used : 
```
<div style="width: 100%;clear:both;padding: 0;position:relative;">
        <div class="content-left" style="width: 58%; float: left;">
        <div class="sidebar" style="float:right; width: 36%;border: solid 1px #707070; padding: 10px;margin-top:25px;">
```

**Comment by emmguyot-adscom** [comment]
We've switched to a table layout and now the result is fine
```
<table><tr>
            <td class="content-left" style="width: 58%;" valign="top">...</td>
           <td class="sidebar" style="width: 36%;"  valign="top">...</td>
</tr></table>
```

We'll keep on using this branch.

**Comment by bsweeney** [comment]
I'm not seeing the same issue when doing a test render with floats. If you're willing to provide more context for the problem HTML I'll see if I can improve the render.

**Comment by emmguyot-adscom** [comment]
@bsweeney I send it to you by email
