### ISSUE TITLE
Displaying Page Number and Count with DOMPDF Footer 

### ISSUE THREAD

**Issue by SAINI673** [dompdf/dompdf#3308]
This code is not proper working 

```
$pdf->get_canvas()->page_text(280, 800, "Page: {PAGE_NUM} of {PAGE_COUNT}", $font,12, array(0,0,0));
```

So that any solution Displaying Page Number and Count with DOMPDF Footer.

**Comment by bsweeney** [comment]
In what context are you using that code? Do you have a sample of your document?
