### ISSUE TITLE
issue when trying to style a heading

### ISSUE THREAD

**Issue by 2dareis2do** [dompdf/dompdf#3313]
I also have an issue when using bootstrap 5.x as base theme. My main issue I faced was trying to change the font-family heading tags, e.g. h1, h2, etc in my print stylesheet.

I have posted a bit more info on the issue originally here https://www.drupal.org/project/entity_print/issues/3103885#comment-15300550

I also have an issue when using bootstrap 5.x as base theme. My main issue I faced was trying to change the font-family heading tags, e.g. h1, h2, etc in my print stylesheet.

I could see the changes on other elements e.g.

I am loading my font like so

```
@font-face {
  font-family: 'DanielBlack';
  src:  url('../fonts/daniel-black-webfont.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
```
This is then imported from my entiityprint-all.scss file which compiles to css/entiityprint-all.css

So I can change the body font e.g.

```
body {
  font-family: "DanielBlack";
}
```
but this does not seem to work.

```
h1 {
  font-family: "DanielBlack";
}
```
however this does seem to work ok:

```
h1 {
  font-size:20pt;
}
```
I get that dompdf does not support css variables etc and that there is no support for bootstrap 5. However I do not really understand why I can set the custom font on some elements, and not others.

I have also checked /tmp folder and can see that dompdf seems to recognise the fonts there in installed-fonts.json. This needs to be manually cleared as if you want to reset things there. I have also made sure that $headings-font-family is not set to null, and also moved

$font-family-code: 
$font-family-sans-serif: 
$font-family-monospace: 
$font-family-serif: 
$font-family-base: $font-family-sans-serif;
from typography to variables as this tends to be loaded first.

Further more I have removed references like this

```
$font-family-base: var(--#{$prefix}font-sans-serif);
$font-family-code: var(--#{$prefix}font-monospace);
$font-family-serif: var(--#{$prefix}font-serif);
```
Other things I have tried using the dompdf media query e.g.

```
@media dompdf {
  h2 {
    font-family: "DanielBlack";
  }
}
```
But unfortunately no success there either. As mentioned preview seems to work fine but there are other differences from the final generated pdf as far as i can tell.

Not sure if i am missing anything obvious, or if the issues I am having actually stem from using Bootstrap 5.x base theme or not. I think the main issues there appear to be no support for flex box or grid as well as limited support for css variables. Not sure how that relates to this issue?

I have also tried the above patch e.g.disabling css optimisation

**Comment by bsweeney** [comment]
In your HTML sample you still haven't defined a bold weight for the "Daniel Black" font. The core fonts work because a style is defined for the various combinations of family/style/weight.

Try the following HTML:

```
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<style>

@font-face {
  font-family: 'DanielBlack';
  src:  url('https://danlobo.co.uk/themes/custom/danlobo_bootstrap_sass/fonts/daniel-black-webfont.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'DanielBlack';
  src:  url('https://danlobo.co.uk/themes/custom/danlobo_bootstrap_sass/fonts/daniel-black-webfont.ttf') format('truetype');
  font-weight: bold;
  font-style: normal;
}

@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: normal;
  src: url(http://themes.googleusercontent.com/static/fonts/opensans/v8/cJZKeOuBrn4kERxqtaUH3aCWcynf_cDxXwCLxiixG1c.ttf) format('truetype');
}

* {
  font-family: "Open Sans";
}

.daniel {
  font-family: "DanielBlack";
}

.size3 {
  font-size: 3rem;
}
        
h3 {
  color: red;
  font-family: DanielBlack;
}
</style>

</head>
<body>
  

<h1 class="daniel">h1 with daniel class</h2>
<h1>h1 with no class</h2>

<h2 class="daniel">h2 with daniel class</h2>
<h2>h2 with no class</h2>

<h3 class="daniel">h2 with daniel class</h3>
<h3 class="daniel size3">h2 with daniel and size3 class</h3>
<h3 class="size3">h2 with size3 class</h3>
<h3>h3 with no class</h3>

<span class="daniel">span with daniel class</span>
<span>span with no class</span>

<p class="daniel">p with daniel class</p>
<p>p with no class</p>

Some text no tag

</body>
</html>
```

[3313.pdf](https://github.com/dompdf/dompdf/files/13242479/3313.pdf)

**Comment by 2dareis2do** [comment]
Firstly thank you for your quick response and an awesome library.

Ok yes you are correct. 💯

I can also set font weight to 500 with the same result.

I was actually looking at this last night  but decided to not set the font-weight to anything other than normal because this seems to add a faux bold on top of the normal weight. You can see for your self  the difference in the browser. That said this stylesheet has been created purely for pdf generation so perhaps it does not matter so much? 

Typically, I would  try and load a bold font variation for say strong tags and then also set the font weight to normal as this is already in the font. Hope that makes sense?

Once again thanks for your quick response. I will adjust my print style sheet accordingly.

**Comment by bsweeney** [comment]
> I can also set font weight to 500 with the same result.

Correct, Dompdf also supports numeric weights with normal = 400 and bold = 700.

> I was actually looking at this last night but decided to not set the font-weight to anything other than normal because this seems to add a faux bold on top of the normal weight. You can see for your self the difference in the browser. That said this stylesheet has been created purely for pdf generation so perhaps it does not matter so much?

Correct, if your stylesheet is purely focused on PDF generation with Dompdf then this is less of an issue.

First, a web browser will select the closest font variant if an exact match doesn't exist. This behavior is codified in the CSS spec outlining [the font matching algorithm](https://drafts.csswg.org/css-fonts/#font-matching-algorithm). Dompdf requires exact matching at present, though at some point we will implement something closer to spec.

Second, as you noted, some browsers will simulate a weight if the specified font does not have a defined variant. This behavior is noted in the spec and, if supported by the browser, can be controlled via the [font-synthesis](https://drafts.csswg.org/css-fonts/#font-synthesis-intro) property.

**Comment by 2dareis2do** [comment]
The font matching algorithm is really interesting. I was not aware you can do stuff like this:

```
@font-face {
  font-family: BaskervilleFull;
  src: url(baskerville-regular.woff2);
}

@font-face {
  font-family: BaskervilleFull;
  src: url(baskerville-italic.woff2);
  font-style: italic;
}

```
so italic would be loaded when it matches. Same font family different font.

hmm so I also guess you could add like this?

```
@font-face {
  font-family: BaskervilleFull;
  src: url(baskerville-bold.woff2);
  font-weight: bold;
}

```

so that bold  variation is loaded when required.

Will have to try this.

also confirms font-family names are case insensitive, which I was wondering about.

> This property controls whether user agents are allowed to synthesize bold font faces when a font family lacks bold faces

Also sounds interesting.
