### ISSUE TITLE
Greek Characters are converted to "???????"

### ISSUE THREAD

**Issue by gsofficework** [dompdf/dompdf#3324]
We are unable to display Greek characters in the generated PDF. Generated PDF converts those characters into "?????".

We are using Laravel 9 and dompdf package. I have added detailed steps to help you understand that we render a simple PDF text. But it's not working. 

I appreciate any help you can provide. Thanks in advance!

### **Detailed steps to re-produce the issue:**

 - Install fresh Laravel project with Laravel Version 9
 - Install dompdf package
 - Open the web.php file and create a route as follows:
 ```
 Route::get('/', function () {
    $pdfContent ='<!DOCTYPE html>
          <html>
	          <head>
		          <title></title>
		          <style>
			          body {
				          font-family: Arial;
			          }
		          </style>
	          </head>
	          <body>
		          Greek Content :
		          <br/>
		          Με το παρόν σας ευχαριστούμε για τη νέα σας ανάθεση
	          </body>
          </html> ';

    $domPdf = new Dompdf();
    $domPdf->loadHtml($pdfContent);
    $domPdf->render();
    $domPdf->stream('test.pdf', ["Attachment" => false]);
    exit(0);
});
```

- Trigger the URL
- You'll see "?????????????????????" instead of proper Greek content

**Comment by bsweeney** [comment]
You have to specify a font installed into Dompdf that supports your desired characters. The core PDF fonts (Helvetica, Times Roman) only support characters included in Windows ANSI encoding. Try DejaVu Sans:

```
<style>
  body {
    font-family: DejaVu Sans;
  }
</style>
```

**Comment by jigars-fabninjas** [comment]
Thank you for the quick response, but we want to add fonts like Arial, Calibri, Open Sans and some Google fonts. 
Our requirement is to let users generate letters in different fonts using the Froala editor and generate the PDF from the HTML.
Can you provide details on adding different fonts supporting Greek Characters in Laravel 9 & dompdf?

**Comment by bsweeney** [comment]
To support additional fonts you would need to install them. Dompdf supports using the standard CSS `@font-face` declaration so you don't really have to do anything special. Google fonts should work fine.

I recommend that you read through the following wiki articles:

- [About Fonts and Character Encoding](https://github.com/dompdf/dompdf/wiki/About-Fonts-and-Character-Encoding)
- [Unicode How-To](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo)
