### ISSUE TITLE
Applying Custom font generated after running load_font.php

### ISSUE THREAD

**Issue by fhafha28** [dompdf/dompdf#3335]
Hi,

I generated font named Poppins-Regular using load_font.php. 
Then **Poppins-Regular.ufm** file is generated in **vendor/dompdf/dompdf/lib/fonts**

Until here, there was no problem, but if I see the generated pdf file, the font is not applied. 
Below is my code in html file. 

```
<style>
    @font-face{
        font-family: 'Poppins';
        scr: url('storage/fonts/Poppins-Regular.ttf') format('ttf');
        font-weight: normal;
        font-style: normal;
    }
    body {
        font-family: Poppins;
    }
</style>
```

Here is my code in my controller

```
$pdf = PDF::loadView('my_pdf',
    compact('variable')
);
$pdf->render();
return $pdf->stream();
```

Here is my dompdf configuration in config/dompdf.php which is the same as default.

```
"font_dir" => storage_path('fonts'),   
"font_cache" => storage_path('fonts'),
"temp_dir" => sys_get_temp_dir(),
"chroot" => realpath(base_path()),
```

In my storage/fonts, there is Poppins-Regular.ttf file exists. 

Do you have any idea why it is not applied properly?

**Comment by bsweeney** [comment]
`format('ttf')` should be `format(truetype)`

**Comment by fhafha28** [comment]
Thanks for catching. I changed to :

>   scr: url("storage/fonts/Poppins-Regular.ttf") format("truetype");

but the problem still persist....

**Comment by fhafha28** [comment]
The browser tap for the generated PDF shows this icon, can it be a hint for something..?
<img width="179" alt="icon in tab" src="https://github.com/dompdf/dompdf/assets/96311086/f32200ac-53f2-43bd-83b0-418872a38def">
