### ISSUE TITLE
Problem persists: applying font Poppins.ufm

### ISSUE THREAD

**Issue by fhafha28** [dompdf/dompdf#3336]
Thanks for catching. I changed to :

scr: url("storage/fonts/Poppins-Regular.ttf") format("truetype");

but the problem still persist....

The browser tab for the generated pdf shows this icon. Can it be a hint for something...?

<img width="179" alt="icon in tab" src="https://github.com/dompdf/dompdf/assets/96311086/e454e578-d9f7-4e14-833e-eee56a200507">

**Comment by fhafha28** [comment]
Here is my html code again

>     <style>
>         @font-face {
>             font-family: "Poppins";
>             scr: url("storage/fonts/Poppins-Regular.ttf") format("truetype");
>             font-weight: normal;
>             font-style: normal;
>         }
> 
>         body {
>             font-family: Poppins;
>         }
>     </style>

and it is my config/dmpdf.php

>    "font_dir" => storage_path('fonts'), 
>   "font_cache" => storage_path('fonts'),
>         "temp_dir" => sys_get_temp_dir(),
>         "chroot" => realpath(base_path()),


and I have **Poppins-Regular.ufm** file in **vendor/dompdf/dompdf/lib/fonts**

**Comment by bsweeney** [comment]
If you use load_font.php you do not also need to use `@font-face`. Are both the font file and the UFM in the fonts directory?

**Comment by fhafha28** [comment]
I apologize for opening new issues. It was marked as completed so I thought you would not wee it again. 

I changed html without @font-face

> <style>
>     body{
>         font-font: Poppins;
>     }
> </style>

However, the problem persists...

Both ttf  and utf files are in **vendor/dompdf/dompdf/lib/fonts** 

Also I have Poppins.ttf file in storage/fonts. I have it in both places to be sure but it does not work..
I tried to delete either one in each folder, but none of them work.

**Comment by fhafha28** [comment]
In **app/strage/fonts**  , there is  **Times-Bold.afm.json** . Whenever deleted it and regenerated PDF, **Times-Bold.afm.json** is created again in **app/strage/fonts**  
 
<img width="153" alt="storage_fonts" src="https://github.com/dompdf/dompdf/assets/96311086/5a3117ab-5977-4110-a0f6-32511743e00d">

Does it related to this issue somehow?

**Comment by bsweeney** [comment]
The JSON file is a cached version of the AFM generated when using the font. You should see a JSON file generated for any font used. Also note, information for the font should appear in installed-font.json.

**Comment by fhafha28** [comment]
I can see that it is generated correctly in **installed-fonts.json**. I think it does not generate  a cached version of the AFM for Poppins font. 

Could you tell me where should I check further to correct this issue? 

> {
>     "poppins": {
>         "normal": "C:\\xampp\\htdocs\\my_project\\vendor\\dompdf\\dompdf\/lib\/fonts\/Poppins",
>         "bold": "C:\\xampp\\htdocs\\my_project\\vendor\\dompdf\\dompdf\/lib\/fonts\/Poppins-Bold",
>         "italic": "C:\\xampp\\htdocs\\my_project\\vendor\\dompdf\\dompdf\/lib\/fonts\/Poppins-Italic",
>         "bold_italic": "C:\\xampp\\htdocs\\my_project\\vendor\\dompdf\\dompdf\/lib\/fonts\/Poppins-BoldItalic"
>     }
> }

**Comment by fhafha28** [comment]
I checked again and revised my code and file name and checked installed-font.json. and now it works as expected. I really appreciate your answer. Thank you so much.

**Comment by fhafha28** [comment]
I checked installed-font.json.  and I revised my code and file name and now it works as expected. Thank you. I appreciate your help. :^)

**Comment by bsweeney** [comment]
Based on what you've provided things seem to be configured correctly. You'll need to see if you can generate some additional logging to determine what's going on. See the wiki for instructions: https://github.com/dompdf/dompdf/wiki/Debugging-Dompdf

**Comment by fhafha28** [comment]
I am not sure I did it correct. I did it like that  but there was no error showing up and it does not generate a cached version of the AFM for poppins font.

>     public function myPdfGeneratingMethod()
>     {
>         ini_set("display_errors", true);
>         ini_set("error_log", "phperr.log");
>         ini_set("log_errors", true);
>         error_reporting(E_ALL);
> 
>         ini_set("display_errors", true);
>         ini_set("error_log", "phperr.log");
>         ini_set("log_errors", true);
>         error_reporting(E_ALL);
> 
>         $_dompdf_show_warnings = true; // record warnings generated by Dompdf
>         $_dompdf_debug = false; // output frame details for every frame in the document
>         $_DOMPDF_DEBUG_TYPES = [
>             'page-break' => false // record information about page break determination
>         ];
> 
>         $dompdf = new Dompdf([
>             "logOutputFile" => "log.html",
>             "debugPng" => false, // extra messaging
>             "debugKeepTemp" => false, // don't delete temp files
>             'debugCss' => false, // output Style parsing information and frame details for every frame in the document
>             'debugLayout' => false, // draw boxes around frames
>             'debugLayoutLines' => false, // line boxes
>             'debugLayoutBlocks' => false, // block frames
>             'debugLayoutInline' => false, // inline frames
>             'debugLayoutPaddingBox' => false // padding box
>         ]);
> 
>         $html = file_get_contents('C:\xampp\htdocs\my_project\resources\testHtml.html');
>         $dompdf->loadHtml($html);
>         $dompdf->render();
> }
> 

though they render testHtml.html without error message but font is not applied.

I also tried to change config/dompdf.php  like 

>         "enable_html5_parser" => true,
>         "debugPng" => false, // extra messaging
>         "debugKeepTemp" => false, // don't delete temp files
>         'debugCss' => false, // output Style parsing information and frame details for every frame in the document
>         'debugLayout' => false, // draw boxes around frames
>         'debugLayoutLines' => false, // line boxes
>         'debugLayoutBlocks' => false, // block frames
>         'debugLayoutInline' => false, // inline frames
>         'debugLayoutPaddingBox' => false, // padding box
>         'show_warnings' => true,
>         'debug'=>false,
>         'page-break'=>false,


But there was no error coming up



Originally I was using blade template, so I made test html file and try it. below is my html file. It is my test HTML file. 

> 
> <!DOCTYPE html>
> <html lang="da">
> <head>
>     
>     <meta charset="utf-8">
>     {{--    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">--}}
>     <meta name="viewport" content="width=device-width, initial-scale=1">
>     <title>test HTML</title>
> </head>
> <body>
> <p style="font-family: Poppins">Ut et enim omnis nim omnis dolor sunt repellat</p>
> 
> <p style="font-family: poppins">Ut et enim omnis nim omnis dolor sunt repellat</p>
> 
> </body>
> </html>

Could you please see whether I set up something incorrect so it does not show any error message? 
I checked phperr.log and laravel.log but there was no errors related to dompdf showing up.

**Comment by bsweeney** [comment]
Honestly I don't really see anything here to explain why it's not working. For the actual file you're attempting to render it could be something more generally related to laravel, but I don't use that framework so I'll be of limited help figuring out something there.

Is the path to the font file correct in installed-fonts.json?

Have you tried loading the font via Google Fonts?

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <link href="https://fonts.googleapis.com/css2?family=Edu+TAS+Beginner&family=Poppins&display=swap" rel="stylesheet">
  <style>
    body {
      font-family: Poppins;
    }
  </style>
</head>
<body>
  <p>dompdf</p>
</body>
</html>
```

**Comment by fhafha28** [comment]
The problem persists but thank you so much for your time and effort in helping me tackle this issue. Although we haven't found a solution, it has been helpful and I appreciate the discussion.

**Comment by fhafha28** [comment]
It works if I use link rather than ttf files. Thank you so much for your help. I really appreciate your time and discussions together. 
:^)

**Comment by Bizarrus** [comment]
Its your problem, take a look:

![image](https://github.com/dompdf/dompdf/assets/1371300/d309d08b-9682-4621-a796-586cefa1feb9)

The CSS Property calls **src** (for source) and **_NOT_** **scr**.

**Comment by bsweeney** [comment]
Good eye! I can't believe I missed that smh
