### ISSUE TITLE
the pdf is not showing the image (png)

### ISSUE THREAD

**Issue by jwprogramer** [dompdf/dompdf#3337]
I'm having a problem displaying the image of my view. I made all the settings, but it didn't work. 

my code:

PDFController

```
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Venda;
use Dompdf\Dompdf;
use Dompdf\Options;

class PDFController extends Controller
{
    public function generatePdf($id)
    {
        $invoice = Venda::find($id);
        $user = $invoice->user;

      
        $options = new Options();
        $options->set('isHtml5ParserEnabled', true);
        $options->set('isPhpEnabled', true);
        $options->set('isRemoteEnable', true);

        $pdf = new Dompdf($options);

    
        $html = view('invoice.pdf', compact('invoice', 'user'));
        
        
    
        $pdf->loadHtml($html);
      
        $pdf->setPaper('A4', 'portrait');
       
        $pdf->render();
        
        $pdf->stream('invoice.pdf');
    }

    public function index($id)
    {
        $invoice = Venda::find($id);
        $user = $invoice->user;
        return view('invoice.pdf', compact('invoice', 'user'));
    }
}
```

View - invoice.pdf

**Comment by jwprogramer** [comment]
``view - invoice.pdf

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fatura - Nº {{ $invoice->id }}</title>
    <style>
            .invoice-box {
				max-width: 800px;
				margin: auto;
				padding: 30px;
				border: 1px solid #eee;
				box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
				font-size: 16px;
				line-height: 24px;
				font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
				color: #555;
			}

			.invoice-box table {
				width: 100%;
				line-height: inherit;
				text-align: left;
			}

			.invoice-box table td {
				padding: 5px;
				vertical-align: top;
			}

			.invoice-box table tr td:nth-child(2) {
				text-align: right;
			}

			.invoice-box table tr.top table td {
				padding-bottom: 20px;
			}

			.invoice-box table tr.top table td.title {
				font-size: 45px;
				line-height: 45px;
				color: #333;
			}

			.invoice-box table tr.information table td {
				padding-bottom: 40px;
			}

			.invoice-box table tr.heading td {
				background: #eee;
				border-bottom: 1px solid #ddd;
				font-weight: bold;
			}

			.invoice-box table tr.details td {
				padding-bottom: 20px;
			}

			.invoice-box table tr.item td {
				border-bottom: 1px solid #eee;
			}

			.invoice-box table tr.item.last td {
				border-bottom: none;
			}

			.invoice-box table tr.total td:nth-child(2) {
				border-top: 2px solid #eee;
				font-weight: bold;
			}

			@media only screen and (max-width: 600px) {
				.invoice-box table tr.top table td {
					width: 100%;
					display: block;
					text-align: center;
				}

				.invoice-box table tr.information table td {
					width: 100%;
					display: block;
					text-align: center;
				}
			}

			/** RTL **/
			.invoice-box.rtl {
				direction: rtl;
				font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
			}

			.invoice-box.rtl table {
				text-align: right;
			}

			.invoice-box.rtl table tr td:nth-child(2) {
				text-align: left;
			}
    </style>
</head>


<body>

        <div class="invoice-box">
			<table cellpadding="0" cellspacing="0">
				<tr class="top">
					<td colspan="4">
						<table>
							<tr>
								<td class="title">
									<img
										src="{{ asset('images/logoProjetoSolarTech.png') }}"
										style="width: 100%; max-width: 300px"
									/>
								</td>

								<td>
									<b>Fatura #: {{ $invoice['id'] }}</b><br />
									Data:{{ date('d/m/Y', strtotime($invoice->created_at)) }}<br />
								</td>
							</tr>
						</table>
					</td>
				</tr>

				<tr class="information">
					<td colspan="4">
						<table>
							<tr>
								<td>
									<h2>{{ $invoice->user->name }}</h2><br />
									{{ $invoice->user->cpf }}<br />
                                    {{ $invoice->user->email }}<br />
								</td>
								<td>
									Rua {{ $invoice->user->logradouro }}<br />
									{{ $invoice->user->numero_casa }}<br />
                                    {{ $invoice->user->bairro }}<br />
                                    {{ $invoice->user->cidade }}/{{ $invoice->user->estado }}<br />
                                    {{ $invoice->user->cep }}
								</td>
							</tr>
						</table>
					</td>
				</tr>

				<tr class="heading">
					<td>Data</td>
                    <td></td>
                    <td></td>
					<td>Status Pagamento</td>
				</tr>

				<tr class="details">
					<td>Data</td>
                    <td></td>
                    <td></td>
					<td>1000</td>
				</tr>

				<tr class="heading">
					<td>Produto</td>
                    <td>Quantidade de Placas</td>
                    <td></td>
					<td>Valor</td>
				</tr>

				<tr class="item">
					<td>{{ $invoice->nomePacote }}</td>
                    <td>{{ $invoice->quantidadePlacas }}</td>
                    <td></td>
					<td>R$ {{ number_format($invoice->valorFinal, 2, ',', '.') }}</td>
				</tr>

				<tr class="total">
					<td></td>
                    <td></td>
                    <td></td>
					<td><h3> Total: R$ {{ number_format($invoice->valorFinal, 2, ',', '.') }}</h3></td>
				</tr>
			</table>
		</div>

      

</body>

`</html>`

**Comment by bsweeney** [comment]
You're talking about `{{ asset('images/logoProjetoSolarTech.png') }}`, which produces ... a URL with protocol (e.g., `https://example.com/images/logoProjectoSolarTech.png`)?

I don't see anything wrong with the HTML or PHP. Some potential issues I can think of:
- missing libpng, check your PHP GD configuration (e.g., via `phpinfo()`) for indication of the library version
- inability to write to the temp directory, which you can change via the `tempDir` option

You can try to get more info from Dompdf about the failure by [enabling additional debug messaging](https://github.com/dompdf/dompdf/wiki/Debugging-Dompdf).

**Comment by Jaczk** [comment]
`src="{{ asset('images/logoProjetoSolarTech.png') }}"` have you tried change this code into `src="{{ public_path('images/logoProjetoSolarTech.png') }}"`?, i think the problem lies in dompdf cant use asset function like in php

**Comment by jwprogramer** [comment]
I'm accessing it locally. Using artisan serves from laravel.

I've already tried using public_path(), but the error persists.

**Comment by Jaczk** [comment]
I'm sorry, but what is the error?, the image didn't show (i just show an x logo, or not appear), or it cant even load the pdf file?. Also check if your path to the image is correct.

**Comment by jwprogramer** [comment]
I am sorry. Yes, the pdf is generated, but the image appears with an X (does not load).

**Comment by Jaczk** [comment]
Did you also check the php extension from the comment before, when you check phpinfo()?, the extension can also affect why your images can't show up.

**Comment by obla4ko339** [comment]
My image appears with an X (Image not found or type unknown)
how to fix ?

**Comment by Jaczk** [comment]
Can you access directly into the image file?, or make sure the path is correct, in my case image appear x is because my path to the image was wrong and using asset() like in php

**Comment by jwprogramer** [comment]
I did it, I made a function to correct the path data:image/svg+xml;base64,".base64_encode() and decrease the image size

**Comment by jwprogramer** [comment]
thank you to everyone who cooperated
