### ISSUE TITLE
Load a chinese font

### ISSUE THREAD

**Issue by axelf** [dompdf/dompdf#3352]
Hi,

this does not work for me:
https://github.com/dompdf/dompdf/issues/2773
https://github.com/dompdf/dompdf/wiki/UnicodeHowTo#load-a-font-supporting-your-characters-into-dompdf

I cannot load a chinese font.

This is what i have:
`@font-face {
      font-family: "NanumGothic";
      font-style: normal;
      font-weight: normal;
      src: url("../../fonts/NanumGothic-Regular.ttf") format("truetype");
}`

How can i load the font into the fonts folder of dompdf? I use version 2.0.3. What else i have to do?
From the documentation: "So long as the font you want to load is accessible to dompdf you can load it easily via CSS." I think this is the problem, the font is not accessible in dompdf. I need a .ufm and .ufm.json file

`$options->setDefaultFont("NanumGothic");`

**Comment by bsweeney** [comment]
When accessing fonts via the local filesystem, using a relative path the path will be based of the HTML file (for `$dompdf->loadHtmlFile()`) or the executing PHP script (for `$dompdf->loadHtml()`).

Also, worth noting that you don't load fonts from the fonts folder. That's where fonts are stored once they have been installed by Dompdf. That's also where the generated font metrics (UFM files) will be stored.

At any rate, glad you were able to figure it out.

**Comment by axelf** [comment]
@bsweeney thank you for your help. 
If i set the fontDir will the default fonts, come with the library, still available or do i have to copy this fonts also in the new font dir?

**Comment by bsweeney** [comment]
The bundled fonts are still available. That directory is always read, regardless of the fontDir setting. Any newly installed fonts would go into the directory specified by fontDir.

**Comment by axelf** [comment]
Ok, thank you for the help :-)

**Comment by axelf** [comment]
@bsweeney this issuse is not solved :( on my production server the font will not be created in the fonts directory. (in the dev env it is working) Then i changed the font dir set chmod 777 and it is also not working. Then i copied my locally created files in the font dir and this is not working. The font is firefly. what do i have to change in production? permissions? I see no .ttf and .ufm file. The directory in my css (@font-face) is correct.

**Comment by bsweeney** [comment]
Are any errors logged by PHP? You might need to [enable additional debug messaging](https://github.com/dompdf/dompdf/wiki/Debugging-Dompdf) to see what errors are occurring.

**Comment by axelf** [comment]
I cannot see any errors. All data are in the document but instead of the font i only see ?????

**Comment by axelf** [comment]
@bsweeney i used your link for bedugging and this is the error i got:
file_get_contents(http://mydoman/fonts/fireflysung.ttf): Failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized Dompdf 

But if i call http://mydoman/fonts/fireflysung.ttf in the browser, the font fil will be downloaded

**Comment by bsweeney** [comment]
The htaccess protection is likely the cause. You might try allowing access without authentication for localhost. Or exclude the fonts directory from authentication. Or [customize the context](https://github.com/dompdf/dompdf/wiki/Common-Use-Cases#custom-http-stream-context) to provide HTTP BASIC authentication from Dompdf (though that impacts all requests not just the one to your font).

**Comment by axelf** [comment]
Thank you for your help. I appreciate that. This was the reason. 
To keep the effort to a minimum for now, I deactivated the htaccess in order to test if it is working. It is my staging env.
