### ISSUE TITLE
How to display Vietnamese with times new roman font in pdf utf-8 ?

### ISSUE THREAD

**Issue by Goang14** [dompdf/dompdf#3360]
![image](https://github.com/dompdf/dompdf/assets/107413554/19e4b02e-666d-460f-9b05-467982e8ae7e)

I want to display the Vietnamese language but it is currently faulty, I want to use font time new roman.
Thanks very much!

**Comment by bsweeney** [comment]
The core PDF fonts do not support characters other than Windows ANSI. This is per the spec. Most PDF generators get around this by always using a custom font. You'll want to review the documentation related to [fonts](https://github.com/dompdf/dompdf/wiki/About-Fonts-and-Character-Encoding) and [Unicode](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo).

tl;dr style your text with the bundled DejaVu Serif font:

```
<style>
  * {
    font-family: DejaVu Serif, serif;
  }
</style>
```
