### ISSUE TITLE
HTML <bdi> tag isn't working as well

### ISSUE THREAD

**Issue by Ok9xNirab** [dompdf/dompdf#3361]
For example,
```html
<span class="woocommerce-Price-amount amount">
       <bdi>18.00<span class="woocommerce-Price-currencySymbol">ر.س</span>
      </bdi>
</span>
```

On html rendering, 
The currency will be display before amount automatically because it's arabian Text and also inside `<bdi>` tag.

**Thanks**

**Comment by bsweeney** [comment]
Generally speaking, Dompdf does not yet support bidi at all. You can follow #2619 for updates.

Once basic bidi functionality is working we should be able to add support for the `bdi` tag.
