### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by Yusufjonov707** [dompdf/dompdf#3375]
public function downloadPdf()
    {
        $pdf = Pdf::loadHTML("<h1>Hello</h1>");
        return $pdf->download('aaa.pdf');
    }
I am just useing this function just to check download . "Malformed UTF-8 characters, possibly incorrectly encoded" this is the problem . With save() fynction is working  even with my page but download.

**Comment by Yusufjonov707** [comment]
already use<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

**Comment by Yusufjonov707** [comment]
already useing "<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>"

**Comment by Yusufjonov707** [comment]
already useing  "meta http-equiv="Content-Type" content="text/html; charset=utf-8"/"

**Comment by bsweeney** [comment]
Do you get this message for the "Hello" text you posted? There is a known issue where [some characters will cause a regex error](https://github.com/dompdf/dompdf/issues/2550), but not with that specific text.

**Comment by Yusufjonov707** [comment]
Even I write single character still getting this error.

**Comment by bsweeney** [comment]
On what line is the error occurring?

**Comment by Yusufjonov707** [comment]
Yes ofc !! 
![image](https://github.com/dompdf/dompdf/assets/114744690/7df176af-d157-4d5a-a33a-d76e1ca8a29d)
![image (1)](https://github.com/dompdf/dompdf/assets/114744690/db22f96f-a280-4b68-98c9-46a7fce38c5c)

**Comment by Yusufjonov707** [comment]
anything else ?

**Comment by Yusufjonov707** [comment]
anything else ?

**Comment by bsweeney** [comment]
Based on those screen shots it doesn't look like the error is coming from Dompdf. To be sure I'd need to know more information. What is the logic on the line that's triggering the error? The detailed exception should show the call stack.

**Comment by Yusufjonov707** [comment]
that function sets language to web . 
![image (3)](https://github.com/dompdf/dompdf/assets/114744690/1eb961d0-26d3-4a89-af2d-bee08074dc72)
![image (2)](https://github.com/dompdf/dompdf/assets/114744690/8dd6d17a-2c8d-4295-b390-5e76e7c2ba2e)
can that some how interact pdf ?

**Comment by bsweeney** [comment]
Now you're moving out of my realm of knowledge. You might have better luck on StackOverlow.

This is symfony, correct? I don't think changing locale would interact with the PDF, unless there was some type of attempt to translate the content based on the locale.

**Comment by parallels999** [comment]
did you try this
```php
public function downloadPdf()
{
    $pdf = Pdf::loadHTML("<h1>Hello</h1>");
    //return $pdf->download('aaa.pdf');
    return response()->streamDownload(function () use ($pdf) {
        echo $pdf->stream();
    }, 'aaa.pdf');
}

```

**Comment by bsweeney** [comment]
None of that relates to Dompdf directly. The `Pdf` class you're using is a wrapper around Dompdf implemented that integrates Dompdf with your framework and which I had no involvement in developing. And the screen shots you provided show wrapping function calls but not the actual line triggering the error. I can help with issues directly related to Dompdf, but if the issue is coming from your framework you're better off looking elsewhere for help. Though I am happy to try to guide you to a solution I don't have experience with the framework you're using and so I can, at best, make suggestions based on past debugging experience with other systems.

**Comment by Yusufjonov707** [comment]
Thanks you guys !!! It worked

**Comment by bsweeney** [comment]
Can you post your solution in case somebody else runs across the issue?

**Comment by parallels999** [comment]
>Can you post your solution in case somebody else runs across the issue?

@bsweeney hi, It feels like you deliberately ignored the solution I posted. Maybe i'm invisible😄

**Comment by bsweeney** [comment]
Didn't realize that the code you posted _was_ the solution ha ha 😅

**Comment by markosole** [comment]
Hi all, 

I am sort of stuck on simiral trail with UTF-8 encoding issue. My example is below and result what I'm getting with it. I've tried by  setting UTF-8 in my blade, as suggested in readme. With example below there's no font defined. and I have already tried with multiple fonts just in case. 

```php
// Also tried:  Pdf::loadHTML('<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><h1>Hello č š ž đ Ć Č </h1>');
$pdf = Pdf::loadHTML("<h1>Hello č š ž đ Ć Č </h1>");
    //return $pdf->download('aaa.pdf');
    return response()->streamDownload(function () use ($pdf) {
        echo $pdf->stream();
    }, 'aaa.pdf'); 
   
```

**Result:** 

```
Hello ? š ž ? ? ?
```
Ais there anything else that we could try maybe?

**Comment by bsweeney** [comment]
@markosole seems like a different problem entirely. Your issue appears to be related to character representation in the PDF instead of an error in the response pipeline. Recommend you read through [related pages on the wiki](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo), but at a base level make sure you are styling your text a font that supports your characters (e.g., `<h1 style="font-family: DejaVu Sans">Hello č š ž đ Ć Č </h1>`).

**Comment by markosole** [comment]
@bsweeney Thanks for pointing that out, After serveral different combinations I made it work. Having proper font `DejaVu` made difference. I am using translations and `__('Enter username')`  which translates to Croatian wasn't picking up and showing properly.

**Comment by alirfanyasin** [comment]
> ```
>  return response()->streamDownload(function () use ($pdf) {
>         echo $pdf->stream();
>     }, 'aaa.pdf');
> ```

this is very helpful

**Comment by ramona2324** [comment]
> did you try this
> 
> ```
> public function downloadPdf()
> {
>     $pdf = Pdf::loadHTML("<h1>Hello</h1>");
>     //return $pdf->download('aaa.pdf');
>     return response()->streamDownload(function () use ($pdf) {
>         echo $pdf->stream();
>     }, 'aaa.pdf');
> }
> ```

thank you for thisss

**Comment by Kwenziwa** [comment]
> did you try this
> 
> ```
> public function downloadPdf()
> {
>     $pdf = Pdf::loadHTML("<h1>Hello</h1>");
>     //return $pdf->download('aaa.pdf');
>     return response()->streamDownload(function () use ($pdf) {
>         echo $pdf->stream();
>     }, 'aaa.pdf');
> }
> ```

this worked for me. Thank you

**Comment by vikashdukeinfo** [comment]
it works on only download not in preview or load pdf instead download
