### ISSUE TITLE
Local paths with `background-image`

### ISSUE THREAD

**Issue by BelleNottelling** [dompdf/dompdf#3381]
Hello,

I'm one of the maintainers of the FOSSBilling project and I'm trying to identify what's going wrong in this issue that was reported to us: https://github.com/FOSSBilling/FOSSBilling/issues/2070.

I was able to get the background image to render correctly when using a remote URL and specifically enabling remote content in the DomPDF content and I was also able to get it to work correctly by first base64 encoding the image, however despite my best efforts I can't seem to get providing a local path to work correctly.

The content is dynamically rendered using twig, I've attached the HTML that twig outputs and feeds into DomPDF onto the issue (as a zip, because GitHub file restrictions): [pdf.zip](https://github.com/dompdf/dompdf/files/14009385/pdf.zip).

The full path on my server (with any personal info stripped) to the image would be as follows: `/home/example/domains/example.com/public_html/themes/huraga/custom_html/briefpapier.jpg`. The chroot is set to the `$_SERVER['DOCUMENT_ROOT']` variable which on my server is `/home/example/domains/example.com/public_html`.

I've tried:

- `background-image: url('../themes/huraga/custom_html/briefpapier.jpg');`
- `background-image: url('./themes/huraga/custom_html/briefpapier.jpg');`
- `background-image: url('/themes/huraga/custom_html/briefpapier.jpg');`
- `background-image: url('themes/huraga/custom_html/briefpapier.jpg');` 
- `background-image: url('../home/example/domains/example.com/public_html/themes/huraga/custom_html/briefpapier.jpg/themes/huraga/custom_html/briefpapier.jpg');`
- `background-image: url('./home/example/domains/example.com/public_html/themes/huraga/custom_html/briefpapier.jpg/themes/huraga/custom_html/briefpapier.jpg');`
- `background-image: url('/home/example/domains/example.com/public_html/themes/huraga/custom_html/briefpapier.jpg/themes/huraga/custom_html/briefpapier.jpg');`

Am I just having a moment here and doing something dumb or is there an actual bug here?
Thank you and I apologize in advance if I've just done something wrong.

**Comment by BelleNottelling** [comment]
> For filesystem paths the image URL should be relative to the executing script (for relative paths)

Oof that's pretty inconvenient. I thought it would be relative to the chroot that's set.
In our case DomPDF is called from `modules/Invoice/Service.php` which I'd expect basically nobody to be putting their custom assets under. Can we override that behavior?

> An absolute path should be OK, so I would expect `/home/example/domains/example.com/public_html/themes/huraga/custom_html/briefpapier.jpg` to work.

Unfortunately I am having no luck with that, the image doesn't render.
I could verywell be doing something wrong here, but when I enable debugging for the CSS I find this which makes it seem that DomPDF isn't getting the path for the image from the CSS properties:

```
[_parse_sections[section[_parse_properties(background-image:=url('/home/example/domains/example.com/public_html/themes/huraga/custom_html/briefpapier.jpg'))<pre>[_image
Array
(
    [0] => file://
    [1] => 
    [2] => ./
    [3] => none
    [protocol] => file://
    [host] => 
    [path] => ./
    [file] => none
    [resource] => 
)


none
_image]
```

This is with version 2.0.4 and PHP 8.1.26 with AlmaLinux 9 for the host OS.

**Comment by bsweeney** [comment]
> Oof that's pretty inconvenient. I thought it would be relative to the chroot that's set. In our case DomPDF is called from modules/Invoice/Service.php which I'd expect basically nobody to be putting their custom assets under. Can we override that behavior?

chroot was an unfortunate name choice for that option. It's a legacy setting and I haven't gotten around to renaming it yet. A more appropriate name would be something like AllowedLocalFilesystemPaths.

As for retargeting the path to the document root, it only works if the URL is relative. If you specify a base path it should pre-pend to any relative paths. So, something like `$dompdf->setBasePath("/home/example/domains/example.com/public_html");` should cause a relative path ("themes/huraga/custom_html/briefpapier.jpg") to resolve to the full filesystem path.

> when I enable debugging for the CSS I find this which makes it seem that DomPDF isn't getting the path for the image from the CSS properties.

It looks like Dompdf is parsing your CSS just fine, but when it tries to resolve the path on the local filesystem it's failing. Dompdf runs filesystem paths through `realpath` so first thing would be to confirm that the path is correct.

**Comment by BelleNottelling** [comment]
Well. I embarrassingly must admit this was indeed 100% a me problem.
I accidentally flipped `html_custom` in my head to turn it into `custom_html`, so I spent all that time testing the wrong path.

I apologies for taking up your time on this. Thanks for the input on the relative paths & how to set the base path.
Take care!

**Comment by bsweeney** [comment]
Who among us has not made a similar error. Glad you worked it out.
