### ISSUE TITLE
Arabic Text issue ?????

### ISSUE THREAD

**Issue by bilalaliofficial** [dompdf/dompdf#3387]
I am facing challenges with Arabic text in PDF generation despite trying various solutions. The issue persists, with the characters displaying as question marks (?????) instead of Arabic. Event I have attempted to address this by downloading and utilizing the Firefly font, but the problem remains unresolved.

Dompdf latest version
![image](https://github.com/dompdf/dompdf/assets/78023369/881cc696-9228-4d06-8742-8347b780ed84)

**Comment by bsweeney** [comment]
Firefly does not support Arabic text, only Chinese. Can you specify what solutions have you tried?

Also, please refer to #712. While Dompdf can display Arabic characters, text in that language is not fully supported.

**Comment by Absk-tiwari** [comment]
Hindi text not working as well , the issue is same as above "?????" 
Would it work for Hindi? @bsweeney

**Comment by bsweeney** [comment]
Similar issues for Hindi as for Arabic. Follow #2619 for updates.
