### ISSUE TITLE
In PHP 8.1.27 OK - In 8.2.15 Fails with Uncaught Error: Call to undefined function Dompdf\mb_internal_encoding()

### ISSUE THREAD

**Issue by dbareis** [dompdf/dompdf#3391]
The code works in PHP 8.1.27, when I change it in CPANEL to 8.3 it fails, also in PHP 8.2.15

`[09-Feb-2024 22:20:18 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Dompdf\mb_internal_encoding() in /home/wcipporg/public_html/wp-content/themes/oceanwp-child-theme-master/PHP Libraries/DomPDF/v2.0.4/vendor/dompdf/dompdf/src/Dompdf.php:295
Stack trace:
#0 /home/wcipporg/public_html/wp-content/themes/oceanwp-child-theme-master/PHP Libraries/DomPDF/v2.0.4/vendor/dompdf/dompdf/src/Dompdf.php(269): Dompdf\Dompdf->setPhpConfig()
#1 /home/wcipporg/public_html/wp-content/themes/oceanwp-child-theme-master/functions-PDF-CREATION.php(24): Dompdf\Dompdf->__construct()
#2 /home/wcipporg/public_html/wp-content/themes/oceanwp-child-theme-master/ShoppingCart-Review-Edit-SUBMIT-ORDER.php(2101): CreatePdfFromHtml()
#3 /home/wcipporg/public_html/wp-content/themes/oceanwp-child-theme-master/ShoppingCart-Review-Edit-SUBMIT-ORDER.php(566): SendOrderUpdateEmail()
#4 /home/wcipporg/public_html/wp-content/themes/oceanwp-child-theme-master/ShoppingCart-Review-Edit-SUBMIT-ORDER.php(51): Save4SubmittedOrder()
#5 /home/wcipporg/public_html/wp-content/themes/oceanwp-child-theme-master/php-theme-template-dynamic-pages-header-footer.php(37): CustomTemplateContents()
#6 /home/wcipporg/public_html/wp-content/themes/oceanwp-child-theme-master/ShoppingCart-Review-Edit-SUBMIT-ORDER.php(1087): require('/home/wcipporg/...')
#7 /home/wcipporg/public_html/wp-includes/template.php(790): require_once('/home/wcipporg/...')
#8 /home/wcipporg/public_html/wp-includes/template.php(725): load_template()
#9 /home/wcipporg/public_html/wp-content/plugins/pods/components/Pages.php(1455): locate_template()
#10 /home/wcipporg/public_html/wp-includes/class-wp-hook.php(324): Pods_Pages->template_redirect()
#11 /home/wcipporg/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#12 /home/wcipporg/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#13 /home/wcipporg/public_html/wp-includes/template-loader.php(13): do_action()
#14 /home/wcipporg/public_html/wp-blog-header.php(19): require_once('/home/wcipporg/...')
#15 /home/wcipporg/public_html/index.php(17): require('/home/wcipporg/...')
#16 {main}
  thrown in /home/wcipporg/public_html/wp-content/themes/oceanwp-child-theme-master/PHP Libraries/DomPDF/v2.0.4/vendor/dompdf/dompdf/src/Dompdf.php on line 295`

**Comment by bsweeney** [comment]
Is the MBString PHP extension enabled in your 8.2 and 8.3 installations?

**Comment by bsweeney** [comment]
And if you call `phpinfo();` or run `php -i` you see the mbstring section?

**Comment by dbareis** [comment]
@bsweeney

No it seems to be disabled.

`Configure Command | './configure' ' ...'--disable-mbstring'`

Is this an issue with the hosting company?

**Comment by bsweeney** [comment]
Yes, you'll need to figure out with your host how to enable the extension.

**Comment by dbareis** [comment]
@bsweeney 
The hosting company fixed it now I have a similar issue: **Class "DOMImplementation" not found**

I am chasing the company again about this, but it seems that it would be relatively simple for dompdf, to check for and report all **missing** requirements at once on loading.

**Comment by bsweeney** [comment]
That's the purpose of using composer, so that we don't have to write that logic ourselves. Still, I see you point. It may be useful to have a script to help identify these types of issues. Something to consider along with some other post-installation logic that has been suggested.
