### ISSUE TITLE
Invalid PDF without adding large-ish png

### ISSUE THREAD

**Issue by lee-van-oetz** [dompdf/dompdf#3392]
I'm hitting a rather strange issue -- on the production server, I only get valid PDF if I add large enough? image into the HTML -- doesn't even have to be in <img> tag, just having that long string there is enough. I'm thinking this somehow forces something to allocate enough memory as opposed to when it's not there. Problem is, I'm not hitting any errors, I just get borked PDF. On top of that, this is only happening on the prod server -- things work fine on my machine. Any hints on what I can check would be appreciated.

**Comment by bsweeney** [comment]
Invalid PDF in what way? Is the PDF produced but incomplete? Could there be some kind of caching going on that's preventing the full PDF from streaming to the browser?

**Comment by lee-van-oetz** [comment]
[This](https://github.com/dompdf/dompdf/files/14256853/T5355.pdf) is the pdf; it seems complete to me starting with `%PDF` and ending with `EOF`. I don't think there's any caching going on -- I was editing the HTML trying to pin down when it works and when it doesn't work and output was changing accordingly. I'll upload the HTML in about 8 hours -- unable to do it now.

**Comment by bsweeney** [comment]
Definitely not valid. Something is HTML-encoding the document. Right away I noticed that `<` and `>` are encoded as `&lt;` and `&gt;` respectively.

**Comment by lee-van-oetz** [comment]
Apologies for late reaction. This was in Laravel API context -- sometimes Laravel was messing up headers and result didn't come through as PDF.

**Comment by bsweeney** [comment]
No worries glad you were able to work out the source of the issue.
