### ISSUE TITLE
Bad character display on No-Break Space character

### ISSUE THREAD

**Issue by sylvain-** [dompdf/dompdf#3396]
the pdf display an ? instead of Narrow No-Break Space \u{202F}

**Comment by bsweeney** [comment]
If the encoding associated with the font doesn't support a character it will be replaced with a `?`. If the encoding supports the font but the font does not have a supporting glyph then the default replacement character (�) will be used.

Compare text styled with a core PDF font:

```
<div style="font-family: sans-serif;">&#x202F;</div>
```

versus text styled with the bundled DejaVu Sans:

```
<div style="font-family: dejavu sans;">&#x202F;</div>
```
