### ISSUE TITLE
Can I have 2 text blocks without page break in between stick together?

### ISSUE THREAD

**Issue by 8bamo** [dompdf/dompdf#3397]
@bsweeney 
I got a case  that 2 text blocks should always be at the same page.
Is this possible with dompdf?

**Comment by bsweeney** [comment]
Easiest way to do this would be to wrap the blocks in a container that is styled with `page-break-inside: avoid;`:

```
<div style="page-break-inside: avoid;">
    <div id="block1">...</div>
    <div id="block2">...</div>
</div>
```
