### ISSUE TITLE
Encryption not working with Unicode

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#340]
_Original author: freecorv...@gmail.com (August 08, 2011 23:38:10)_

<b>What steps will reproduce the problem?</b>

Run the following PHP code:

``` php
<?php

$html = '
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
<div style="font-family: DejaVu Sans Condensed, monospace; font-size: 11px;">
Персонализиране хедър
</div>
</body>
</html>
';

include_once('dompdf/dompdf_config.inc.php');
$dompdf = new DOMPDF();
$dompdf->load_html($html);
$dompdf->render();
$dompdf->get_canvas()->get_cpdf()->setEncryption('userpass', 'ownerpass', array('print'));
$dompdf->stream('unicode.pdf', array('Attachment' => 1));

?>
```

<b>What is the expected output? What do you see instead?</b>

Text should read Персонализиране хедър. However, it appears as ~20 unreadable characters (can't copy and paste here because of the locked permissions).

<b>What version of the product are you using? On what operating system?</b>

I'm running the trunk version on Linux/Ubuntu, PHP 5.3.5.

<b>Please provide any additional information below.</b>

I added the line with setEncryption between the render() and the stream() calls, according to this post: http://www.dashinteractive.net/dompdf/index.php?v=1702369

If you remove the call to setEncryption, the problem no longer appears (but obviously no password protection is enforced either).

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=334_

**Comment by gozonjoedaimar** [comment]
Any updates about this bug?

**Comment by bsweeney** [comment]
Nothing yet.

**Comment by olya-shamian** [comment]
For me it happens, when I use Unicode - without the encryption the Cyrillic characters show up perfectly, when I use the style tag with font DejaVu Sans.

I thought it looked like Cpdf needs me to set font, too, before calling setEncryption (which I called, btw, with username and pass being empty). If only I knew, how to set those fonts to Cpdf in a correct way. Does anyone know how to do that?

And of course, if that doesn't help, I'll be waiting for this bug fix, too.

Thank you!

**Comment by simonberger** [comment]
This problem should be fixed in develop.

**Comment by pYr0x** [comment]
for me, unicode characters like `Ä` `Ö` `Ü`  doesn't work with encryption and font `DejaVu Sans`
=> all work with the font `Helvetica`

**Comment by igorespin** [comment]
I'm using v0.8.5 with DejaVu Sans and encryption and the resulting PDF is blank. Is this still a bug?

**Comment by simonberger** [comment]
The latest version is 0.8.6 with a fix for encryption.

**Comment by igorespin** [comment]
Excelent! It's working, thanks.
