### ISSUE TITLE
How to handle with image in php 8.0 

### ISSUE THREAD

**Issue by arseniomuanda** [dompdf/dompdf#3404]

**Comment by bsweeney** [comment]
please provide more details

**Comment by arseniomuanda** [comment]
When I try to load an image through domdpf, no matter what I do, nothing works.

**Comment by bsweeney** [comment]
What have you tried? How is the image referenced? Have you checked the [base requirements](https://github.com/dompdf/dompdf/wiki/Requirements), Dompdf [configuration](https://github.com/dompdf/dompdf/wiki/Usage#options), and [resource reference notes](https://github.com/dompdf/dompdf/wiki/Usage#resource-references-and-uri-validation)? Did it work in other versions of PHP (since you mention 8.0)?

**Comment by arseniomuanda** [comment]
`options = new Options();
        $options->setChroot('');


        $dompdf = new Dompdf();
        $dompdf->setOptions($options);

        $html = view('relatorios/morador', $data);
        #return $html;

        $dompdf->getCanvas();
        $dompdf->loadHtml(html_entity_decode($html), 'UTF-8');

        // (Optional) Setup the paper size and orientation
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();
        ob_end_clean();

        // Output the generated PDF to Browser
        $dompdf->stream($morador->nome, array("Attachment" => false));
        exit;`

**Comment by arseniomuanda** [comment]
![image](https://github.com/dompdf/dompdf/assets/66343929/a453d397-3ed5-4fdf-a9d4-1dd52331a541)

**Comment by bsweeney** [comment]
And the rendered HTML looks like what? You're, presumably, attempting to reference a local path. The issue may be the path reference, which may not be under the current working directory or valid when resolved based on the executing PHP script.

**Comment by bsweeney** [comment]
sample/city.png would be relative to the document if rendering a file (`$dompdf->loadHtmlFile(...);`) or the executing PHP script if rendering from a string (`$dompdf->loadHtml(...);`). Also, you have to ensure that the resource path is allowed. The default rules require `isRemoteEnabled` for images loaded over HTTP and for local files the path must be added to the `chroot` option.
