### ISSUE TITLE
No block-level parent found. Not good. (Line 66)

### ISSUE THREAD

**Issue by Axel-XA** [dompdf/dompdf#3407]
So,I have dompdf installed for a project of mine,however when I try converting into PDF I get the following error:

((An uncaught Exception was encountered
Type: DOMPDF_Exception

Message: No block-level parent found. Not good.

Filename: C:\xampp\htdocs\Project\application\libraries\dompdf\include\inline_positioner.cls.php

Line Number: 66

Backtrace:

File: C:\xampp\htdocs\Project\libraries\dompdf\include\frame_decorator.cls.php
Line: 471
Function: position

File: C:\xampp\htdocs\Project\application\libraries\dompdf\include\text_frame_reflower.cls.php
Line: 340
Function: position

File: C:\xampp\htdocs\Project\application\libraries\dompdf\include\frame_decorator.cls.php
Line: 477
Function: reflow

File: C:\xampp\htdocs\Project\application\libraries\dompdf\include\page_frame_reflower.cls.php
Line: 169
Function: reflow

File: C:\xampp\htdocs\Project\application\libraries\dompdf\include\frame_decorator.cls.php
Line: 477
Function: reflow

File: C:\xampp\htdocs\Project\application\libraries\dompdf\include\dompdf.cls.php
Line: 680
Function: reflow

File: C:\xampp\htdocs\Project\application\controllers\bo_engine\Commande_engine.php
Line: 611
Function: render

File: C:\xampp\htdocs\Project\index.php
Line: 315
Function: require_once))

Not sure why is this happening,I looked around on google and there's little to no matches on my problem,on my code,at least....I tried all solutions concerning this problem,from changing CSS,to reinstalling dompdf,to trying older versions to changing:
<  html>

...

<\html>
to : 
<   html><\html>
yet the problem persists,I don't understand if the problem with me or my Project
Apologies in advance if the error was my fault in any way;I'm still new to this and I'm still learning.

**Comment by bsweeney** [comment]
Would need to see a sample of the HTML causing a problem before I could analyze the issue.

**Comment by Axel-XA** [comment]
Thank you,the issue was fixed by updating my XAMPP application and switching to a different version
