### ISSUE TITLE
々 japanese character not showing when csv generated but other character are showing perfectly.

### ISSUE THREAD

**Issue by mabruratiqi** [dompdf/dompdf#3413]
I am using larave-dompdf  package to generate invoice pdf. I am using noto sans jp font family in the blade file. when pdf is generated all characters are showing except '々' this one.
Can any one please suggest me what should I do to show it ?

**Comment by bsweeney** [comment]
It worked OK with a quick test. What version of Dompdf are you using? Can you provide a sample of your HTML + CSS?

**Comment by mabruratiqi** [comment]
> It worked OK with a quick test. What version of Dompdf are you using? Can you provide a sample of your HTML + CSS?

@bsweeney Thank you for your reply.
I am using barryvdh/laravel-dompdf , the version is v0.9.0. 
the HTML code is : 

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Invoice File - {!! config('app.name') !!}</title>
        <style type="text/css">
            @font-face {
                font-family: 'notosansjp-bold';
                font-weight: bold;
                src:
                    url("{{ \App\Support\Helper::urlStatic('fonts/notosansjp-bold.otf') }}") format('otf'),
                    url("{{ \App\Support\Helper::urlStatic('fonts/notosansjp-bold.ttf') }}") format('truetype');
            }

            @font-face {
                font-family: 'notosansjp-medium';
                font-weight: medium;
                src:
                    url("{{ \App\Support\Helper::urlStatic('fonts/notosansjp-medium.otf') }}") format('otf'),
                    url("{{ \App\Support\Helper::urlStatic('fonts/notosansjp-medium.ttf') }}") format('truetype');
            }

            @font-face {
                font-family: 'notosansjp-regular';
                font-weight: normal;
                src:
                    url("{{ \App\Support\Helper::urlStatic('fonts/notosansjp-regular.otf') }}") format('otf'),
                    url("{{ \App\Support\Helper::urlStatic('fonts/notosansjp-regular.ttf') }}") format('truetype');
            }

            body {
                padding: 60px;
                margin: 0;
                background: #ffffff;
                font-family: notosansjp-regular, notosansjp-bold, notosansjp-medium, sans-serif;
            }
        </style>
    </head>
    <body>
            <div class="info-left">
                <p>{{ $invoiceInfo->user->contractor_name }}<span> 様</span></p>
          </div>
    </div>
 the $invoiceInfo->user->contractor_name contains this **々** character and its showing only a dot.
Thanks in advance.

**Comment by bsweeney** [comment]
I'm not involved in the Laravel project, but 0.9.0 is fairly old. Are you able to upgrade to the latest release?

You might try clearing out your installed fonts (for laravel, typically in the storage directory).

There have been some issues in the past with font parsing that should be addressed by the latest release of php-font-lib. You should at least update that library.

**Comment by bsweeney** [comment]
FYI, I tested with the following:

```
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&amp;display=swap" rel="stylesheet">
<style>
body {
  font-family: "Noto Sans JP", sans-serif;
  font-optical-sizing: auto;
  font-weight: 400;
  font-style: normal;
}
</style>
</head>
<body>
  々
</body>
</html>
```

**Comment by mabruratiqi** [comment]
> FYI, I tested with the following:
> 
> ```
> <!DOCTYPE html>
> <html>
> <head>
>   <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
> <link rel="preconnect" href="https://fonts.googleapis.com">
> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
> <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&amp;display=swap" rel="stylesheet">
> <style>
> body {
>   font-family: "Noto Sans JP", sans-serif;
>   font-optical-sizing: auto;
>   font-weight: 400;
>   font-style: normal;
> }
> </style>
> </head>
> <body>
>   々
> </body>
> </html>
> ```

Using it , did you get expected result ?
and what is the version of dompdf.

**Comment by bsweeney** [comment]
I did get the expected result. I tested with a few versions of Dompdf, 0.8.6, 1.0.2, and 2.0.4.

**Comment by mabruratiqi** [comment]
> FYI, I tested with the following:
> 
> ```
> <!DOCTYPE html>
> <html>
> <head>
>   <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
> <link rel="preconnect" href="https://fonts.googleapis.com">
> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
> <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&amp;display=swap" rel="stylesheet">
> <style>
> body {
>   font-family: "Noto Sans JP", sans-serif;
>   font-optical-sizing: auto;
>   font-weight: 400;
>   font-style: normal;
> }
> </style>
> </head>
> <body>
>   々
> </body>
> </html>
> ```

Thank you very much, it works.
You save my a lot of time.
Thanks.

**Comment by bsweeney** [comment]
Maybe the version of the font you were using was older and didn't have that character represented? At any rate glad to hear you were able to get the desired result.
