### ISSUE TITLE
Dompdf is not supporting Arabic fonts.

### ISSUE THREAD

**Issue by itssaqlain06** [dompdf/dompdf#3414]
Used every single method.
autoScriptToLang
autoScriptToFont.

everything is perfectly displaying in browser but not in pdf

**Comment by bsweeney** [comment]
Neither of those methods relate to Dompdf. There are two levels of support. Basic character rendering support requires a supporting font. Have you read through the following articles on the wiki:

- [About Fonts and Character Encoding](https://github.com/dompdf/dompdf/wiki/About-Fonts-and-Character-Encoding)
- [Unicode How-to](https://github.com/dompdf/dompdf/wiki/UnicodeHowTo)

Beyond that, Dompdf does not yet support complex text layout, meaning that shaping is not performed to join characters. Following #2619 for updates on support for complex text layout. You can read through the discussion in #712 for suggestions on how to improve rendering.
