### ISSUE TITLE
get no Output in Mobile, Windows OK

### ISSUE THREAD

**Issue by glenoka** [dompdf/dompdf#3422]
```
public function generatePDF(){
        $html = 'Just test ';
$dompdf = new DOMPDF();
$dompdf->load_html($html);
$dompdf->set_paper("letter", "portrait");
$dompdf->render();
$dompdf->stream('Stuff');
    }
```

even a simple code like this one, it's doesn't show pop up for download any file in mobile(use Safari and Chrome). Idk in windows show error like this `GET http://192.168.1.8:8000/user/generatePDF?user=4&month=02&years=2024 net::ERR_BLOCKED_BY_CLIENT` But still show download file in Windows.  i use latest version. 
```
 "name": "dompdf/dompdf",
            "version": "v2.0.4",
```

**Comment by bsweeney** [comment]
Did you figure out the issue?
