### ISSUE TITLE
dompdf 2.04 PHP 8.2 Deprecated message

### ISSUE THREAD

**Issue by Micccza** [dompdf/dompdf#3424]
> Deprecated: preg_match_all(): Passing null to parameter 2 ($subject) of type string is deprecated in /homepages/htdocs/test/shop/dompdf204/vendor/dompdf/dompdf/src/Css/Stylesheet.php on [line 1448](https://github.com/dompdf/dompdf/blob/v2.0.4/src/Css/Stylesheet.php#L1448)

`preg_match_all("/(url|local)\s*\(\s*[\"\']?([^\"\'\)]+)[\"\']?\s*\)\s*(format\s*\(\s*[\"\']?([^\"\'\)]+)[\"\']?\s*\))?/i", $descriptors->src, $src);`

**Comment by bsweeney** [comment]
Would need to see a sample of the stylesheet to know what's causing the error.

**Comment by Micccza** [comment]
i found the problem! Using `font-family: "DejaVu Sans","Arial"` in the CSS file but the arial font is not in the fonts folder causes the error message.

**Comment by bsweeney** [comment]
That would not be the cause of the issue. Line 1448 is contained in a method that parses `@font-face` declarations. The relevant CSS probably looks something like:

```
@font-face {
    font-family: Arial;
}
```

Which is not a valid [font-face declaration](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face). If you want to specify the font used to display the content you would use something like the following declaration:

```
* {
    font-family: Arial;
}
```

The upcoming 3.0.0 release appears to be able to process the invalid font-face declaration without error.

**Comment by Micccza** [comment]
yes, i remember i had some old code like this in the beginning of the CSS file:

`@font-face {
    xfont-family: Arial;
}`

I added a x in front of the property to deactivate the font. i guess this caused the error!
