### ISSUE TITLE
Gujarati Language Some Fonts are not displaying as Expected

### ISSUE THREAD

**Issue by fwt-parth-jariwala** [dompdf/dompdf#3425]
->Raw HTML:
![image](https://github.com/dompdf/dompdf/assets/110459026/1a98dda4-3115-4e17-a393-b1ffed42c4c4)
->Output:
![image](https://github.com/dompdf/dompdf/assets/110459026/a7143fb4-4f08-4f18-becc-9cf64b106b09)
->Some words are not displaying as expected

**Comment by bsweeney** [comment]
Until Dompdf supports complex text layout operations the letter shaping required by Gujarati script should be performed prior to document rendering. Watch #2619 for updates.
