### ISSUE TITLE
Incompatible function signature for imagepolygon() and imagefilledpolygon() in GD.php

### ISSUE THREAD

**Issue by MarkMaldaba** [dompdf/dompdf#3428]
In PHP 8.0, a new function signature was introduced for the `imagepolygon()` and related functions, which removed the `$num_points` argument.  Instead the number of points is deduced from the size of the supplied array.

In PHP 8.1, the old function signature was deprecated and a deprecation notice will be issued if it is used.

In 4de9ec9, DomPDF was updated to use the new function signature.  In addition, an new call to `imagepolygon()` was added in 1d6f991c, also using the new function signature.

This means that the GD backend is currently broken on PHP 7.

The code should be updated to do a PHP version check and to use the old signature on PHP < 8 and the new signature on more recent PHP versions.

This affects any calls to `imagepolygon()`, `imageopenpolygon()` and `imagefilledpolygon()`.  All such instances are in `GD.php`.

**Comment by bsweeney** [comment]
I'm planning a 2.0.6 release with some minor changes, I'll include an update to address the compatibility issue.

**Comment by bsweeney** [comment]
This was fixed in 2.0.5/3.0.0.

**Comment by MarkMaldaba** [comment]
> This was fixed in 2.0.5/3.0.0.

Great stuff.  Thank you for the speedy fix!
