### ISSUE TITLE
Allowed memory size of 16777216 bytes exhausted

### ISSUE THREAD

**Issue by stephanITC** [dompdf/dompdf#3432]
Recently I discovered an issue when using a custom font.
I followed the guidelines to implement.
Adding `@font-face` and appropriate styles to the head of my html does not give me any output when using segoe-ui font.
Even increasing the memory value for php to infinite (-1) does not make it work.
Using default fonts (courier, symbol, ...) is no issue.

Any advice on this?

**Comment by stephanITC** [comment]
I am using Dompdf 2.0.4.

My Code looks like this:

```
$dompdf = new Dompdf([
	'isRemoteEnabled' => true,
	'isHtml5ParserEnabled' => true,
	'chroot' => ABSPATH, // this is my constant for the projects absolute path (works for all images, etc)
	'defaultFont' => 'Courier',
]);

$html = '	<!DOCTYPE html>
		<html lang="de">
			<head>
			        <style>
				        @font-face {
					        font-family: "segoe-ui";
					        font-weight: 300;
					        font-style: normal;
					        font-variant: normal;
					        src: url("../public/assets/fonts/segoe-ui/SegoeUI.ttf") format("truetype");
				        }
				        body {
					        font-family: "segoe-ui", sans-serif;
					        font-weight:300;
				        }
			        </style>
			        <title>PDF</title>
        		</head>
				<body>
					This is a string as the only content in the pdf
				</body>
			</html>';

$dompdf->loadHtml( $html );
$dompdf->setPaper('A4');
$dompdf->render();

$canvas = $dompdf->getCanvas();
$canvas->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) use ($dompdf) {
	$text = 'Seite ' . $pageNumber . ' / ' . $pageCount;
	$font = $fontMetrics->getFont('DejaVuSans');
	$size = 9;
	$canvas->text(62, 78, $text, $font, $size);
});

$filename = 'test.pdf';
$dompdf->stream( $filename, [
	'compress' => true,
	'Attachment' => false,
]);
```

I increased the Memory Limit to 128M. Using the code above i still get:
`Allowed memory size of 134217728 bytes exhausted (tried to allocate 65015808 bytes)`
Setting up code above with default font "Courier" everything renders as it should.

Additional information:
I am running my Dev-Environment in WSL ( Apache, PHP, MySQL). I gave 32GB of available Memory to WSL via .wslconfig. When opening up my Task Manager and unlimiting the PHP memory_limit i can see my PCs usage increasing from (default) 20GB to up to 30GB before the script breaks.

**Comment by bsweeney** [comment]
I certainly would not expect that particular sample to cause a memory limit exception. Maybe something about your copy of the font is problematic? Have you tried installing another font?

**Comment by stephanITC** [comment]
Finally found the issue: the .../vendor/dompdf/dompdf/lib/fonts/ directory has not had sufficient rights to create the .ufm font and .ufm.json file. chmod -R 777 fonts/ made it work.
unfortunately no error reported that...

**Comment by bsweeney** [comment]
Dompdf might be swallowing that error to prevent it from halting rendering. [Enabling additional debug messaging](https://github.com/dompdf/dompdf/wiki/Troubleshooting-Dompdf#debugging) would have exposed the problem.

I am surprised lack of permissions was causing a memory limit exception. I'd have to look into it to see what Dompdf is doing in that scenario.

FYI there is a request to add a post-installation task to check permissions. I'm also thinking of a way of generating info on demand to validate the installation.
