### ISSUE TITLE
Naira Symbol - Currency Not Working

### ISSUE THREAD

**Issue by osawereao** [dompdf/dompdf#3436]
The naira symbol ₦ doesn't display on the PDF

**Comment by bsweeney** [comment]
What does your HTML look like? Are you using a font that supports that character?

**Comment by osawereao** [comment]
I am not using any special font with the PDF;
Currency like $, £ and € display correctly.
I am  running in via Laravel using the wrapper

**Comment by bsweeney** [comment]
Core fonts only support characters represented in Windows ANSI. Expanded character support is provided with the bundled DejaVu fonts (which do support the ₦ character).

Try the following:

```
<style>
* { font-family: DejaVu Sans, sans-serif; }
</style>
₦
```
