### ISSUE TITLE
setEncryption not working with variable

### ISSUE THREAD

**Issue by tavitomedcol** [dompdf/dompdf#3437]
Hello, when I try to encrypt a pdf with a password, it only works with a direct string, example: setEncryption(1234, 5678) but I need the password to be a variable setEncryption($var,123456789). any solution? thanks

this is my line of code:

$dompdf->getCanvas() ->get_cpdf() ->setEncryption(**$var**, '123456789', ['print', 'modify', 'copy', 'add']);

**Comment by bsweeney** [comment]
Should be no difference in functionality whether you use a string or variable. What values have you tried for $var? Do you receive any errors when calling the method?

**Comment by tavitomedcol** [comment]
No error is displayed. It just says that the pdf cannot be opened. It only opens what is inside the quotes '$var' opens with $var but does not take the value of the variable, even if the variable is found alone $var without quotes

**Comment by bsweeney** [comment]
At what point are you setting `$var` and at what point do you call `setEncryption`?

**Comment by tavitomedcol** [comment]
This is my code

session_start();
$id=$_REQUEST['id'];
ob_start();

require_once 'printpdf.php';

$html = ob_get_clean();


$_SESSION['pdf']['content'] = $html;
$_SESSION['pdf']['filename'] = 'INF'.$id.'.pdf';

$html = $_SESSION['pdf']['content'];
$filename = $_SESSION['pdf']['filename'];

$options = new Options();
$options->set('isRemoteEnabled', true);
$dompdf = new DOMPDF($options);
 
$dompdf->loadHtml($html);
$dompdf->set_paper('letter', 'portrait');

$dompdf->render();

$password=$rs->idper;
$dompdf->getCanvas() ->get_cpdf() ->setEncryption(**$password**, '12108', array('print', 'modify', 'copy', 'add'));
$output=$dompdf->output();
//$dompdf->stream();
file_put_contents($filename, $output);

unset($_SESSION['pdf']);

**Comment by tavitomedcol** [comment]
**$password**='1234';
$dompdf->getCanvas() ->get_cpdf() ->setEncryption(**$password**, '**12108**', array('print', 'modify', 'copy', 'add'));
$output=$dompdf->output();
//$dompdf->stream();
file_put_contents($filename, $output);

unset($_SESSION['pdf']);

![image](https://github.com/dompdf/dompdf/assets/167258066/64ef1d9d-6b5c-4c86-ab7f-1c4769618363)

not open
![image](https://github.com/dompdf/dompdf/assets/167258066/8111b18b-5210-4b71-875d-e9903796ee16)

Only open with 12108 not with de var $password

**Comment by bsweeney** [comment]
Your logic looks OK. Are you running under a locale other than en_US? I would not expect that to cause issues with the password functionality, but I haven't tested that scenario in a while.

**Comment by tavitomedcol** [comment]
Solved, the variable changes its value per session variable, so the value did not clear and always kept the same value, why? magic, for no reason. Thanks
