### ISSUE TITLE
<pre> tags make extra space on first line

### ISSUE THREAD

**Issue by harsh-thedriftpoint** [dompdf/dompdf#3438]
when creating pdf with pre tag its creating extra space and that causes indentation error

```
<pre style="background-color: black; color: white;">
def Main(arg):
    # code goes here
     return arg


input = input()
print(Main(input))
</pre>
```

i want this code in pre tag to get indentation but it does add additional spaces
							 
							 
after dom pdf it renders as [https://prnt.sc/aAvgvV0axt74](https://prnt.sc/aAvgvV0axt74) like this i want to get rid of extra spaces

**Comment by bsweeney** [comment]
Can't provide guidance without seeing a sample of the HTML + CSS.

**Comment by bsweeney** [comment]
I'm not seeing the same issue when testing with the sample provided. If this is in the context of a larger document it would help to see the sample in context.
