### ISSUE TITLE
Page break not working in long text

### ISSUE THREAD

**Issue by nousath** [dompdf/dompdf#3445]
[render.pdf](https://github.com/dompdf/dompdf/files/15082211/render.pdf)

I have a problem with my code that page break is not working with long text. kindly update me

**Comment by bsweeney** [comment]
Can't help much without seeing the HTML and CSS related to the document. However, it looks like your long text is inside a table cell. Current releases of Dompdf do not yet support splitting a table cell across pages. And update is in progress related to that.

Support for this feature is in development, and you can follow #98 for updates. If you want to test out current level of support, you can find updates in the paging-updates branch.

**Comment by nousath** [comment]
@bsweeney check this

`<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Proposal - {proposal_number}</title>
    <style>
        @page {
            margin-top: 10px;
            margin-bottom: 30px;
            margin-left: 30px;
            margin-right: 30px;
            border: 1px solid #7E7E89;
            page-break-after: always;
        }

        body {
            border: 1px solid #7E7E89;
            page-break-inside: avoid;

        }

        .item_th {
            border: 1px solid #7E7E89;
            padding: 3px;
            padding-left: 8px;
            font-size: 13px;
        }

        .item_td {
            border: 1px solid #7E7E89;
            border-top: 0px;
            padding: 5px;
            padding-left: 8px;
            font-size: 15px;
            text-align: left;
        }



        .taxSummary {
            border: 1px solid black;
            border-collapse: collapse;

        }


        .table_main {
            border: 1px solid #7E7E89;
            padding: 3px;
            padding-left: 8px;
            font-size: 13px;
            border-collapse: collapse;
        }



        .verticalLine {
            margin-top: 88px;
            padding-top: 35px;
            border-left: -3px solid Black;
            height: 272px;
            position: absolute;
            left: 50%;
            right: 50%;
            margin-left: -3px;
            margin-right: 3px;
            top: 10;
        }

        .tax-area {
            border: 0px;
            width: 100%;
            font-weight: bold;
        }

        .tax-area .name {
            font-size: 12px;
            text-align: right;
            width: 50%;
            border: 0px;
        }

        .tax-area .rate {
            font-size: 15px;
            padding: 5px;
            text-align: right;
            border: 0px;
            width: 50%;
        }

        .footer {
            position: fixed;
            bottom: -1px;
            left: 25px;
            right: 35px;
            height: 80px;
            /** Extra personal styles **/
            color: Black;
            margin-top: 10px;
            text-align: center;
            line-height: 15px;
            font-size: 15px;

        }

        hr {
            width: 700px;
            margin-left: auto;
            margin-right: auto;
            font-size: 16px;
        }

        .avoid-break {
            page-break-inside: avoid;
            margin: 0;
            padding: 0;
        }

        table.items {
            page-break-inside: avoid !important;
            -webkit-column-break-inside: avoid;
            break-inside: avoid;
            -webkit-region-break-inside: avoid;
            table-layout: fixed
        }

        .items tr {
            page-break-inside: avoid;
            page-break-after: auto;
            vertical-align: top;
            overflow-wrap: anywhere;
            word-wrap: break-word;
        }

        table {
            page-break-before: avoid;
            page-break-after: avoid;
            page-break-inside: avoid;
        }

        table td {}

        /*table.items {*/
        /*    page-break-after:auto;*/
        /*white-space: break-word;*/
        /*    overflow-wrap: break-word;*/
        /*}*/
        /*table.items td{*/
        /*    min-height:  1000px !important;*/
        /*overflow-wrap: break-word;*/
        /*}*/
    </style>

</head>

<body>
    <table width="100%" cellspacing="0" height="20%">
        <tr>
            <td colspan="4">
                <img width="150px" align="left" height="100px" style="vertical-align: middle;margin:20px" src="{logo_url}">
                TEST
                <span style="font-weight: bold;font-size: 30px;margin-left:150px;"> Proforma Invoice </span>
            </td>
        </tr>
        <tr>
            <td class="table_main" style="border-right: none;border-left: none;" width="20%">
                #<br>
                Estimate Date<br>
                Expiry Date<br>
                Reference#
            </td>
            <td class="table_main" style="border-left: none;" width="30%">
                <span style="font-weight: bold;">: {proposal_number}</span><br>
                <span style="font-weight: bold;">: {proposal_date}</span><br>
                <span style="font-weight: bold;">: {proposal_open_till}</span><br>
                <span style="font-weight: bold;">: {proposal_reference}</span>
            </td>
            <td class="table_main" style="border-right: none;" width="20%">
                <p style="margin-bottom: 50px;">Place Of Supply</p>
            </td>
            <td style="border-left: none;border-right: none;" class="table_main" width="30%">
                <p style="margin-bottom: 50px;font-weight: bold;">: {proposal_country}</p>
            </td>
        </tr>
        <tr>
            <td colspan="2" class="table_main" style="background-color: #F2F2F2;width: 50%;"><b>Bill To</b>
            </td>
            <td colspan="2" class="table_main" style="background-color: #F2F2F2;width: 50%;"><b>Ship To</b>
            </td>
        </tr>
        <tr>
            <td colspan="2" class="table_main" style="width: 50%;border-left: none;">
               fdg
            </td>
            <td colspan="2" class="table_main" style="width: 50%;border-right: none;">
               fdgdfg
            </td>
        </tr>
        <tr>
            <td colspan="4" class="table_main" style="border-bottom: none;border-left: none;border-right: none;">
                <span>Subject :</span><br>
            </td>
        </tr>
        <tr>
            <td colspan="4" class="table_main" style="border-top: none;border-left: none;border-right: none;">
                <span style="font-weight: bold;">{proposal_subject}</span>
            </td>
        </tr>
    </table>

    <table width="100%" class="items" cellspacing="0" cellpadding="0" style="margin-top: 0px;">
        <thead>
            <tr>
                <th class="item_th" align="left" style="background-color: #F2F2F2;border-top: none;border-left: none;" width="3%">#</th>
                <th class="item_th" align="left" style="background-color: #F2F2F2;border-top: none;" width="60%">Item &
                    Description</th>
                <th class="item_th" align="right" style="background-color: #F2F2F2;border-top: none;" width="7%">Qty
                </th>
                <th class="item_th" align="right" style="background-color: #F2F2F2;border-top: none;" width="15%">Rate
                </th>
                <th class="item_th" align="right" style="background-color: #F2F2F2;border-top: none;border-right: none;" width="15%">
                    Amount
                </th>
            </tr>
        </thead>
        <tbody>
            {items_loop}
            <tr>
                <td class="item_td" style="border-left: none;">{item_serial[]}</td>
                <td class="item_td" style="font-size:15px">{item_description[]} <small>-
                        {item_long_description[]}</small></td>
                <td class="item_td" style="text-align:right;font-weight:bold">{item_qty[]}</td>
                <td class="item_td" style="text-align:right;">{item_rate[]}</td>
                <td class="item_td" style="text-align:right;font-weight:bold;border-right: none;">
                    {item_amount[]}</td>
            </tr>
            {items_loop_end}
        </tbody>
    </table>

    <table cellspacing="0" cellpadding="0" style="width:100%;margin-top:0px;">
        <tr>
            <td class="table_main" style="width: 60%;border-right: none;border-bottom: none;border-top: none;border-left: none;">
            </td>
            <td class="table_main" style="width: 40%;border-top: none;border-right: none;">
                <table cellspacing="0" cellpadding="0" width="100%">
                    <tr>
                        <td align="right">Sub Total</td>
                        <td align="right" style="padding: 5px;">{proposal_subtotal}</td>
                    </tr>
                    <tr>
                        <td colspan="2">{proposal_taxes}</td>
                    </tr>
                    <tr>
                        <td align="right">Discount</td>
                        <td align="right" style="padding: 5px;">{proposal_discount}</td>
                    </tr>
                    <tr>
                        <td align="right"><b>Total</b></td>
                        <td align="right" style="padding: 5px;"><b>{proposal_total}</b></td>
                    </tr>
                </table>
            </td>
        </tr>
       
    </table>

    </body>

</html>
[0aaa7c18-9ad8-4466-9e84-9ce5bdb79227.pdf](https://github.com/dompdf/dompdf/files/15090082/0aaa7c18-9ad8-4466-9e84-9ce5bdb79227.pdf)
`

**Comment by nousath** [comment]
@bsweeney check this

My Source Code
[html and css.txt](https://github.com/dompdf/dompdf/files/15090110/html.and.css.txt)

Output
[0aaa7c18-9ad8-4466-9e84-9ce5bdb79227.pdf](https://github.com/dompdf/dompdf/files/15090109/0aaa7c18-9ad8-4466-9e84-9ce5bdb79227.pdf)
