### ISSUE TITLE
text() font in page_script() is ignored in specific situation with SVG img file

### ISSUE THREAD

**Issue by marcovo-peercode** [dompdf/dompdf#3447]
- PHP version: 8.1
 - `dompdf/dompdf` version: 2.0.7
 - `barryvdh/laravel-dompdf` version: 2.1.1
 - `phenx/php-svg-lib` version: 0.5.4

Consider the following file `dompdf.blade.php`:

```
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        html, body {
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>
</head>
<body>

<table>
    <tbody>
    <tr>
        <td>
            <img src="{{ resource_path('image.svg') }}" alt="image"/>
        </td>
    </tr>
    </tbody>
</table>

{{--<span>&nbsp;</span>--}}

<script type="text/php">
    if ( isset($pdf) ) {
        $pdf->page_script('
          $font = $fontMetrics->get_font("Arial, Helvetica, sans-serif", "normal");
          $size = 8;
          $pageText = "File " . $PAGE_NUM . " / " . $PAGE_COUNT;
      $y = 15;
      $x = 35;
      $pdf->text($x, $y, $pageText, $font, $size);
    ');
}
</script>
</body>
</html>
```

With `image.svg`:
```
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
    <circle cx="50" cy="50" r="50" />
</svg>
```

And initiating PHP:
```
        $dompdf = \PDF::loadView('dompdf');
        $dompdf->setPaper('A4');
        return $dompdf->download('file.pdf');
```

Note that the `text()` call in `page_script()` defines a sans-serif font. However, in the resulting PDF a serif font is seen:
![afbeelding](https://github.com/dompdf/dompdf/assets/48310153/384cf0a0-8e8a-454d-8493-7d96d32c2a1e)

Compare this to either one of the following distinct situations:
 - We remove the table, making `<img>` a direct child of `<body>`
 - We uncomment the commented `<span>`
 - We remove the `<img>` tag

When doing either of those, the mentioned text is correctly displayed in the sans-serif font. This screenshot is of the second case, uncommenting `<span>`:
![afbeelding](https://github.com/dompdf/dompdf/assets/48310153/1745670a-b030-4f6e-b1f8-b70db1d9b57d)

This same behaviour is present when changing the page_script to the new callback signature:
```
    if ( isset($pdf) ) {
        $pdf->page_script(function ($pageNumber, $pageCount, $canvas, $fontMetrics) {
            $font = $fontMetrics->get_font("Arial, Helvetica, sans-serif", "normal");
            $size = 8;
            $pageText = "File " . $pageNumber . " / " . $pageCount;
            $y = 15;
            $x = 35;
            $canvas->text($x, $y, $pageText, $font, $size);
        });
    }
```

**Expected behaviour:** In all cases the sans-serif font should be used, as declared

**Observed behaviour:** With the `<img>` inside the `<table>` with no content under the table, the serif font is seen.

**Workaround:** make sure there is content after the table with the image. This could be actual content, or invisible content like the `<span>&nbsp;</span>` used here.

I suspect this could be caused due to perhaps the `<img>` being the last thing painted (in the setting of a table?) on the page, and a drawing context thereafter not being reset, or overwritten, or the like?

**Comment by bsweeney** [comment]
The primary issue here is that your `get_font` usage is incorrect. That method expects a single font family name, not a CSS-style list of alternate families. So, what's actually happening is that your call to that method is returning null, which is interpreted by Cpdf as using the last-applied font.

Try modifying the line as follows:
```
$font = $fontMetrics->getFont("sans-serif", "normal");
```

**Comment by marcovo-peercode** [comment]
Thanks, this solved the issue!

I do feel that perhaps `getFont()` should not be returning `null`s (but rather throw an exception) to make these kinds of issues more transparent. Not sure what the implications of that would ultimately be though.

**Comment by bsweeney** [comment]
Returning `null` is intended to indicate that a matching font wasn't found and is used internally to perform a fallback search for a match against the default font using just the weight/style. I'm not sure how I feel about throwing an exception since usage is still "correct" it's just that the font name doesn't match anything loaded into Dompdf.
