### ISSUE TITLE
utf-8 character not rendering

### ISSUE THREAD

**Issue by gdandersson** [dompdf/dompdf#3453]
When adding the utf8-character 🟢 to the output, it just creates an .. window-like icon, attached here:
<img width="89" alt="Screenshot 2024-05-02 at 09 14 51" src="https://github.com/dompdf/dompdf/assets/52959348/64f14321-fb2e-464c-8c2a-9a3332afc045">

Using 2.0.8 (via barryvdh/laravel-dompdf 2.1.1, if that makes a difference)

**Comment by bsweeney** [comment]
That's an emoji, which resides in the Supplementary Multilingual Plane. Dompdf currently only supports the Basic Multilingual Plane. Follow #1698 for updates.
