### ISSUE TITLE
Bad quality when i use background image on div element

### ISSUE THREAD

**Issue by BrandonSev** [dompdf/dompdf#3460]
Hi,

I have a problem when i try to show image with background-image on div element. The image appear but the quality instead of <img> tag is very bad. I use background image beacause i need apply a contain property otherwsise with width and height on img tag attribute the image is deformed.

Anyone have a solution for this?

Thanks.

**Comment by bsweeney** [comment]
I think there are probably a few related issues:
- #2278 for object-fit support
- #3284 and #3359 for issues with image processing

You might try bumping up the Dompdf DPI, though take note that it might impact layout in other ways. If that doesn't work, do you need both width and height?

If that modifying the DPI doesn't work you could try a tweaked HTML structure. It's harder to center the image in the space vertically but you can at least prevent the deformation.

```
<div style="width: 200; height: 200; text-align: center; background-color: orange; border: 1px solid green;">
  <img src="https://placehold.co/600x400/000000/FFF" style="max-width: 100%; max-height: 100%; margin: auto;">
</div>

<div style="width: 200; height: 200; text-align: center; background-color: orange; border: 1px solid green;">
  <img src="https://placehold.co/400x600/000000/FFF" style="max-width: 100%; max-height: 100%;">
</div>
```

**Comment by BrandonSev** [comment]
> I think there are probably a few related issues:
> 
> * [object-fit support ? #2278](https://github.com/dompdf/dompdf/issues/2278) for object-fit support
> * [Quality difference between background-image and <img> #3284](https://github.com/dompdf/dompdf/issues/3284) and [PDF file size too large - option to bypass png image recompression?  #3359](https://github.com/dompdf/dompdf/issues/3359) for issues with image processing
> 
> You might try bumping up the Dompdf DPI, though take note that it might impact layout in other ways. If that doesn't work, do you need both width and height?
> 
> If that modifying the DPI doesn't work you could try a tweaked HTML structure. It's harder to center the image in the space vertically but you can at least prevent the deformation.
> 
> ```
> <div style="width: 200; height: 200; text-align: center; background-color: orange; border: 1px solid green;">
>   <img src="https://placehold.co/600x400/000000/FFF" style="max-width: 100%; max-height: 100%; margin: auto;">
> </div>
> 
> <div style="width: 200; height: 200; text-align: center; background-color: orange; border: 1px solid green;">
>   <img src="https://placehold.co/400x600/000000/FFF" style="max-width: 100%; max-height: 100%;">
> </div>
> ```

Thank you for your reply! :heart: 

It works with your structure. I simply added a relative position to the parent element (div) and then applied an absolute position to the img tag and added a transformation in css to align it in the middle

**Comment by bsweeney** [comment]
Glad to hear it! You can follow one of the cited issues for updates on addressing these feature needs/updates.

**Comment by eugabrielsilva** [comment]
@BrandonSev can you share your complete solution code? I'm having the same issue as well
