### ISSUE TITLE
save generated file in to public folder

### ISSUE THREAD

**Issue by irakli-ika** [dompdf/dompdf#3463]
How can I save the generated file in the public folder?
I tried this but it not working

```
$dompdf = new Dompdf();
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$pdfContent = $dompdf->output();
$filePath = 'invoices/invoice-' . $data['name'] . '.pdf';
Storage::disk('public')->put($filePath, $pdfContent);
return response()->json(['message' => 'PDF generated and saved successfully!', 'path' => $filePath]);`
```

**Comment by bsweeney** [comment]
I don't see a call to load the HTML document (e.g. `$dompdf->loadHtml($html);`). I can't say anything about the file saving part since I don't use any frameworks .. but looks OK.

What about it isn't working?
