### ISSUE TITLE
Page header

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#347]
_Original author: patil.sh...@gmail.com (August 18, 2011 11:46:30)_

<b>What steps will reproduce the problem?</b>
1. Adding headers and footer in standard way
2. Check, if page 1 then dont print header and footer.
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
Should print on all pages, except for first page

<b>What version of the product are you using? On what operating system?</b>
0.5

<b>Please provide any additional information below.</b>

``` php
  $pgno = "{PAGE_NUM}"
  //$pgno = $pgno++;

    if ($pgno=="1")
    {
      $pdf->page_text(12, 100, $pgno." Annex for GGN <?=$lic_rs['ProjectGGN_VC']?>", $font, 8, array(0,0,0));
    }
    else
    {
        $pdf->page_text(12, 100, "else pg: "."{PAGE_NUM}"." ".(int)($pgno)."<?=$rs['ProjectGGN_VC']?>", $font, 12, array(0,0,0));
    }
```

It always hits else section.

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=341_

**Comment by Devod-co-uk** [comment]
Old answer but still relevant, thank you!!!!!!!!
I'm using laravel but here is my solution:
Controller:
`        public function printPDF(Request $request, PDF $pdf)
    {
        $data = [
            'key' => $value,
            'key2' => 'value2',
            
        ];
        $pdf = \App::make('dompdf.wrapper');
        $pdf->getDomPDF()->set_option("enable_php", true);
        $pdf->loadView('PDFs/pdf_view', $data);
        return $pdf->download('FILE_NAME.pdf');
    }`
View:
`        <script type="text/php">
        if (isset($pdf)) {

            $pdf->page_script('

                if ($PAGE_NUM != 1) {

                    $font = $fontMetrics->getFont("Verdana");
                    $footer_size = 10;

{{--                    FOOTER TXT     --}}

                    $text = "Page " . $PAGE_NUM . " of " . $PAGE_COUNT;
                    $width = $fontMetrics->get_text_width($text, $font, $footer_size) / 2;
                    $x = ($pdf->get_width() - $width) / 2;
                    $y = $pdf->get_height() - 35;
                    $pdf->text($x, $y, $text , $font, 8, array(0,0,0));

{{--                    HEADER TXT     --}}

                    $header_text = "Project Title: {{ $project->name }}";
                    $header_width = $fontMetrics->get_text_width($header_text, $font, $footer_size) / 2;
                    $header_x = ($pdf->get_width() - $header_width) / 2;
                    $header_y = 35;
                    $pdf->text($header_x, $header_y, $header_text , $font, 12, array(0,0,0));

{{--                    HEADER IMG     --}}

                    $img_width = 300;
                    $img_loc_width = $x = ($pdf->get_width() - $img_width) / 2;
                    $img_url2 = public_path() . "/img/qp_values.jpg";
                    $pdf->image($img_url2, $img_loc_width, 55, $img_width, 80, "normal");

                }
            ');
        }
    </script>`
