### ISSUE TITLE
Facing issue related page break while content is lengthy.

### ISSUE THREAD

**Issue by NirmalPatelDifferenz** [dompdf/dompdf#3486]
![MicrosoftTeams-image](https://github.com/dompdf/dompdf/assets/166581586/ec1a2778-eff6-45d1-b904-2c9ec9ca6960)
![MicrosoftTeams-image (2)](https://github.com/dompdf/dompdf/assets/166581586/fc49fb82-6f2c-4cb7-8bc9-22504e1376d6)

Guys, I am facing an issue related to PDF design collapse while generating PDF with dompdf library with version 0.9.0. I also attached a couple of Images where you can see my issue on page breaking have you ever seen this issue while generating pdf in your web applications? Then, please reach out to us and help us out, we tried a lot but failed to achieve our desired result.

On top of that, when <tr> tag starts and displays some content inside the pdf section and when content is lengthy then dompdf auto page breaks happen and after that time that <tr> content will hidden inside the page and not able to move down the next page. 

Our expected output is when the content is lengthy and page auto breaks at that time the merged cells should examines properly after the page breaks as well. So, please give us some precious suggestions from your side to solve this issue.

**Comment by NirmalPatelDifferenz** [comment]
[HTML-CSS.txt](https://github.com/user-attachments/files/16053230/HTML-CSS.txt)

This is the sample HTML and CSS code of the above-given images.

**Comment by bsweeney** [comment]
You are running into the issue outlined in #98. I am in the middle of an update that will handle the ability to split a table cell, though I do not yet have a time frame for completion.
