### ISSUE TITLE
Diacritics doesn't work with times new roman font.

### ISSUE THREAD

**Issue by CosminCotulbea** [dompdf/dompdf#3493]
![image](https://github.com/dompdf/dompdf/assets/26275243/949ced6d-de4d-4f06-8fe0-f713a0828cb0)

I have to use times new roman but the diacritics doesn't work. I used deja vu font before this and everything was all right but now we have to use times new roman and i don't know how to fix this,

Any idea ?
Thanks!

**Comment by bsweeney** [comment]
The [core PDF fonts have limited character support](https://github.com/dompdf/dompdf/wiki/About-Fonts-and-Character-Encoding). You can use DejaVu Serif as a replacement serif font.
