### ISSUE TITLE
custom font not working when text is wrapped in <i>

### ISSUE THREAD

**Issue by ballotade** [dompdf/dompdf#3505]
Hello,
I included a custom font and it worked well. Now I wanted the font to be italic, and so I wrapped it into an i-Tag, but then the font isn't used anymore.

It's the same with b-Tag (bold) and u-Tag (underline).

Is there something I can do about it?
Thanx

**Comment by bsweeney** [comment]
Have you specified bold and italic variants? Dompdf does not simulate font style or weight as may be done by some browsers, so you have to supply a version for each style/weight combination you intend to use.

**Comment by ballotade** [comment]
Ah, okay. Thanks for the answer.
No, I don't have any variants of this font. Then I guess it just doesn't work.
