### ISSUE TITLE
Margin-Top Not Applied When Table Starts on a New Page

### ISSUE THREAD

**Issue by Abhishek-Jetani** [dompdf/dompdf#3515]
Description: When I add a `margin-top: 20px` to an element, it applies correctly and works as expected. However, when a table starts on a new page, the `margin-top: 20px` does not seem to apply.

**Steps to Reproduce:**

1. Add `margin-top: 20px` to a table tag.
2. Generate the PDF.
3. Observe that the margin is correctly applied when the element is on the same page but not when the table starts on a new page.

**Expected Behavior:** The margin-top: 20px should be consistently applied to the table or element, including when it starts on a new page.

**Actual Behavior:** The margin-top: 20px is not applied when the table starts on a new page.

**Additional Information:**
- Version of DOMPDF: 2.2

**Comment by bsweeney** [comment]
This is the expected behavior per the spec until we add support for `box-decoration-break`. Watch #640 for updates.
