### ISSUE TITLE
Php 8.4 Deprecation of Non-nullable Parameters Defaulting to null

### ISSUE THREAD

**Issue by oleibman** [dompdf/dompdf#3521]
My apologies if this is premature, but Php8.4 is already in Beta, and will be a production version soon enough. You have already merged PR #3508 which addresses this in one module, but it is not yet part of a release, and there are many other places in your code which have the same problem and do not yet appear to be addressed.

I used the following regular expression to find other statements with the problem. I hope it is sufficient, but I am at least confident there are no false positives:
```
/(?<![?\w])\w+ [$]\w+ = null[,)]/
```

Here is the list:
- Helpers.php
    - public static function uniord(string $c, string $encoding = null)
    - public static function unichr(int $c, string $encoding = null)
- Options.php (addressed by PR #3508)
    - public function __construct(array $attributes = null)
- FrameDecorator/AbstractFrameRedecorator.php
    - final function reflow(Block $block = null)
- FrameReflower/AbstractFrameReflower.php
    - abstract function reflow(Block $block = null);
- FrameReflower/Block.php
    - function reflow(BlockFrameDecorator $block = null)
- FrameReflower/Image.php
    - function reflow(BlockFrameDecorator $block = null)
- FrameReflower/Inline.php
    - function reflow(BlockFrameDecorator $block = null)
- FrameReflower/ListBullet.php
    - function reflow(BlockFrameDecorator $block = null)
- FrameReflower/NullFrameReflower.php
    - function reflow(BlockFrameDecorator $block = null)
- FrameReflower/Page.php
    - function reflow(BlockFrameDecorator $block = null)
- FrameReflower/Table.php
    - function reflow(BlockFrameDecorator $block = null)
- FrameReflower/TableCell.php
    - function reflow(BlockFrameDecorator $block = null)
- FrameReflower/TableRow.php
    - function reflow(BlockFrameDecorator $block = null)
- FrameReflower/TableRowGroup.php
    - function reflow(BlockFrameDecorator $block = null)
- FrameReflower/Text.php
    - function reflow(BlockFrameDecorator $block = null)
- php-font-lib\src\FontLib\TrueType
    - private function uniord (string $c, string $encoding = null)

**Comment by bsweeney** [comment]
I'm attempting to get a build of PHP running on my own system so I can do some testing.

**Comment by Xon** [comment]
I've used this regex (`function.*\([^\?\)]+\s*[\w]+\s*\$[\w]+\s*=\s*null.*?\)`) to find functions which require updating, but your version works too.

If this project uses php-cs-fixer, a rule could be added to flag this an an error.

The `?string` syntax requires php 7.1, so there isn't any down-version compatibility issues at least

**Comment by swiffer** [comment]
remember to consider variables passed by reference -> `/(?<![?\w])\w+ [&$]+\w+ = null[,)]/`
