### ISSUE TITLE
CSS properties on the element itself are partially working

### ISSUE THREAD

**Issue by Elikill58** [dompdf/dompdf#3527]
I was using dompdf 2.0.4 with local installation, and I'm upgrading to v3.0.0.

I'm using code like this:
```html
<html>
<head>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">          
    <style>
     .table {
         color: gray;
     }
    </style>
</head> 
<body>
    <table>
        <tbody>
            <tr style="color: red;"><th style="width: 50%;">some th</th></tr>
        </tbody>
    </table>
</body>
</html>
```
I'm using this code to generate it:
```php
$dompdf = new Dompdf(new Options(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true, 'chroot' => '']));
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();   
$canvas = $dompdf->getCanvas(); 
// Ajout du compteur de page 
$canvas->page_script('
    $text = "$PAGE_NUM / $PAGE_COUNT";
    $pdf->text(535, 791.89, $text, \'Corbel\', 10, array(0,0,0));
');

$dompdf->addInfo('object', $params["title"]);

ob_end_clean();
$dompdf->stream(isset($params["pdf_name"]) ? $params["pdf_name"] : "document.pdf", ["Attachment" => 0]);
```
Before, all colors were well rendered. After migration, all colors are in light gray. If I comment the bootstrap line, I see the difference. Which means this CSS file is well loaded. But, the inline CSS content (here `color:`, but seems to be the same with others style as width) seems to be ignored.

I read the v3.0.0 made changes about this, so I switch to v2.0.8, and it's working fine.

How can I do? Should I use `<style>` to setup all css content?

**Comment by bsweeney** [comment]
Your sample renders as expected for me. The color is fine. And the width, well your sample doesn't have more than one cell so I would expect to see that cell fill the table even with a width provided.

What change with the 3.0.0 release are you referring to?

**Comment by Elikill58** [comment]
> Your sample renders as expected for me. The color is fine. And the width, well your sample doesn't have more than one cell so I would expect to see that cell fill the table even with a width provided.
> 
> What change with the 3.0.0 release are you referring to?

Oh really ? Sad for me. I'm refering to all CSS related content.

Maybe it's because of property order. Can you try by adding color to the table, with a general rule (so no inline as the color in my example). I changed my main post. (In my case, it seems to be from an external css file)

**Comment by bsweeney** [comment]
Your updated sample also works for me. Are you saying that using the sample you provided on your own system that the rendered PDF isn't rendered correctly?

I'm using the [debug helper](https://eclecticgeek.com/dompdf/debug.php) to test, which you are welcome to use to try and reproduce the issue.

**Comment by Elikill58** [comment]
OMG.

I just realize something. With this code:
```html
<html>
<head>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <style>
    table th {
        font-size: 0.8rem;
        color: gray;
    }
    </style>
</head> 
<body>
    <table>
        <tbody>
            <tr style="color: red;"><th style="width: 50%;">some th</th></tr>
        </tbody>
    </table>
</body>
</html>
```
I got the "issue". But, it's working as expected. It's just my CSS declaration (that I put here on `<style>`, but were simply lost in an external CSS file) that was overriding the color, thanks to the change made for this version, my "bug" were revealed :o

I'm closing this... Sorry

**Comment by bsweeney** [comment]
Glad you were able to work out this issue and particularly glad we didn't introduce a new issue 😅
