### ISSUE TITLE
calling file_exists("/.ufm") throws exception

### ISSUE THREAD

**Issue by mspiderv** [dompdf/dompdf#3539]
dompdf version: 2.0.8

Im getting the following PHP error:

**file_exists(): open_basedir restriction in effect. File(/.ufm) is not within the allowed path(s):**

This error is trigerred by the following code: https://github.com/dompdf/dompdf/blob/master/lib/Cpdf.php#L3337

Explanation: For some reason (I don't know why) the "$font" variable (here: https://github.com/dompdf/dompdf/blob/master/lib/Cpdf.php#L3299) is empty string. This is not a problem on local environment, because calling this code `file_exists("/.ufm")` simply returns `false` but **IT IS** a problem on PHP webhostings, where you are not allowed (because of the security reasons) check, weather some file exists or not in certain directories (`/` in this case).

**Comment by bsweeney** [comment]
This should be addressed by #3415 and that change will be included in the next release.

If you are able to provide sample code that reproduces the issue that would help. So far I have not been able to reproduce to determine if there's an issue elsewhere int he code that needs to be fixed.
