### ISSUE TITLE
Install DomPDF version 3.0 without composer

### ISSUE THREAD

**Issue by EmanueleBaron** [dompdf/dompdf#3548]
I'm trying install DomPDF version 3.0 without composer, I utilizing this project:https://github.com/dompdf/dompdf/releases, in dompdf_3-0-0.zip.
But I received this error: Class 'Dompdf\Cpdf' not found in "dompdf\dompdf\src\Adapter\CPDF.php:177"
I include this autoloder in paste dompdf/src.
And my php,
```
require_once 'dompdf/dompdf/src/Autoloader.php';
require_once 'dompdf/php-font-lib/src/FontLib/Autoloader.php';
require_once 'dompdf/php-svg-lib/src/svg/autoload.php';

Dompdf\Autoloader::register();
use Dompdf\Dompdf;
use Dompdf\Options;"
```

Someone help me? why received error in Cpdf?

**Comment by bsweeney** [comment]
You should need to do all that work loading autoloaders when using the packaged release. The archive includes a file at dompdf/autoload.inc.php that is built as part of the packaging process and handles the autoload work. So, you should just need to use the following in your script:

```
require_once 'dompdf/autoload.inc.php';

use Dompdf\Dompdf;
use Dompdf\Options;

$options = new Options();
$dompdf = new Dompdf($options);
// load and render your document
```

This is covered in the [README](https://github.com/dompdf/dompdf/blob/master/README.md).

**Comment by bsweeney** [comment]
The file is not part of the project source because it is generated when we build the packaged version. When you browse the files extracted from the ZIP it should be in the top-level directory.

![image](https://github.com/user-attachments/assets/8f752dbd-e6d9-4c96-ac64-e06d43532b2b)
