### ISSUE TITLE
php 8.4 deprecations

### ISSUE THREAD

**Issue by 8ctopus** [dompdf/dompdf#3557]
In php 8.4, dompdf 3.0.0 triggers several deprecations about implicit nullable parameters.
I saw you already started working on it. #3556

There are two other places with issues @swiffer 

1 test triggered 2 PHP deprecations:

```
1) K:\dev\github\php-pigeon-invoice\vendor\dompdf\dompdf\src\Helpers.php:582
Constant E_STRICT is deprecated

Triggered by:

* Tests\InvoiceTest::testBase
  K:\dev\github\php-pigeon-invoice\tests\InvoiceTest.php:24

2) K:\dev\github\php-pigeon-invoice\vendor\dompdf\php-font-lib\src\FontLib\TrueType\File.php:103
FontLib\TrueType\File::uniord(): Implicitly marking parameter $encoding as nullable is deprecated, the explicit nullable type must be used instead
```

**Comment by swiffer** [comment]
good catch - would you like to open a PR yourself?

**Comment by swiffer** [comment]
just stepped in for the first time as well. cannot do it right now so feel free to open the PRs.

**Comment by 8ctopus** [comment]
https://github.com/dompdf/dompdf/pull/3558
https://github.com/dompdf/php-font-lib/pull/142

It's done.

**Comment by bsweeney** [comment]
good catch thank you for the help

**Comment by dennis-koster** [comment]
@swiffer Would it be possible to get this fix also in a `2.x` release? I'd be happy to provide a PR but I am not sure which branch to point it to.

**Comment by bsweeney** [comment]
We don't maintain older versions of Dompdf. While there are some changes (improvements) in functionality the migration from v2 to v3 should not cause significant problems.
