### ISSUE TITLE
CSS: Named @page rules

### ISSUE THREAD

**Issue by bohwaz** [dompdf/dompdf#3562]
Here is my CSS:

```
@page {
    margin: 1cm;
}

@page landscape {
    size: A4 landscape;
}

.pdf[data-prefer-landscape] {
    page: landscape;
}
```

And my HTML:

```
<html class="pdf" data-prefer-landscape="1">
…
```

Currently (AFAIK), DomPDF doesn't seem to support named `page:` rules (last of my CSS rules), which makes DomPDF outputting the page as portrait instead.

In this case, it can be fixed in PHP code:

```
		if (strpos($html, 'data-prefer-landscape') !== false) {
			$dompdf->setPaper('A4', 'landscape');
		}
```

But if DomPDF did support `page:` rules, it would make a lot of nice things possible, eg. setting different margins for some pages, and so on.

Thank you, we just donated $200, to thank you for the great work you are doing :)

**Comment by bsweeney** [comment]
Thank you for the suggestions. I agree this would make a nice addition, and it's been on my mind for a while now (see #498). There was some initial work to support just such a feature with #613 but we never finalized it. Follow 498 for updates I'll put it in the next minor release milestone, though can't say if the change will make that release or be pushed to a later release.
