### ISSUE TITLE
SVG image triggers a PHP 8.4 deprecation warning

### ISSUE THREAD

**Issue by boutetnico** [dompdf/dompdf#3566]
Dompdf 3.0.1
PHP 8.4.2

A base64 encoded SVG image triggers a deprecating warning:
```
<img src="data:image/svg+xml;base64,REDACTED" style="width:100%; max-width:128px;">
```

`Deprecated: xml_set_element_handler(): Passing non-callable strings is deprecated since 8.4 in /var/www/website/vendor/dompdf/dompdf/src/Image/Cache.php on line 141`

**Comment by bsweeney** [comment]
The fix for that is ready for release, which I plan to do this week.
