### ISSUE TITLE
PDF output renders incorrectly - no spaces between words except when using monospace fonts

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#357]
_Original author: sa...@midsummerenergy.co.uk (September 09, 2011 15:13:01)_

<b>What steps will reproduce the problem?</b>
1.Using dompdf on my server to generate any pdf - except when a monospace font is specified by CSS

<b>What is the expected output? What do you see instead?</b>
- all the dompdf examples generate pdfs, which are rendered correctly except that there are no spaces between words. See the attached example, which is the 'text-align' example supplied with dompdf.

The exceptions are when using monospace fonts (which do render correctly), and when using justified text (although even here the spaces are usually too small).

<b>What version of the product are you using? On what operating system?</b>
- DOMPDF 0.6.0, on a Centos 5 server with PHP 5.3.3.

<b>Please provide any additional information below.</b>
- Seems like a great product - but do hope I can sort out the lost spaces problem as at present it is not usable on our server!

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=351_

**Comment by bsweeney** [comment]
This is a relatively old issue and the files have been lost to the bit bucket. If anyone has any useful info to report please do so and we'll re-open.
