### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted (tried to allocate 7680 bytes) 

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#364]
_Original author: josueru...@gmail.com (October 03, 2011 23:24:18)_

<b>What steps will reproduce the problem?</b>
1.Pass the html to library

<b>What is the expected output? What do you see instead?</b>
I got that message 
Allowed memory size of 134217728 bytes exhausted (tried to allocate 7680 bytes)  in /home7/prosysco/public_html/102011/dompdf/include/text_frame_reflower.cls.php(381) : runtime-created function on line 1

<b>What version of the product are you using? On what operating system?</b>
DOMPDF 0.6.0 beta2 

<b>Please provide any additional information below.</b>

I've expando de memory on my server but I doesnt work
I some times i get this error when I set the memory with 256 mb

i need some help with this issue Thanks!!

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=358_

**Comment by yogeshkoli** [comment]
any update on the above issue? 
I am getting same error with my script while generating the pdf with html code contenting tables and lot of text.

here is error:

`PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 65552 bytes) `

**Comment by bsweeney** [comment]
@yogeshkoli the error is fairly generic so it's difficult to determine the cause. A starting place for help with debugging is to post the document you're having trouble rendering.

**Comment by sukhdeepsingh5** [comment]
Try this https://github.com/barryvdh/laravel-snappy for larger documents.
