### ISSUE TITLE
rowspan and page break

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#367]
_Original author: ydb1...@gmail.com (October 11, 2011 03:30:00)_

<b>What steps will reproduce the problem?</b>
1. a table cell that has rowsapn &gt; 1
2. page break that is calculated to a row that &quot;splitts&quot; that cell
3. That should do it...

<b>What is the expected output? What do you see instead?</b>
Rendering fails

<b>What version of the product are you using? On what operating system?</b>
DOMPDF 0.6.0 beta2

<b>Please provide any additional information below.</b>

I solved it by inserting:
1. in Table_Row_Group_Frame_Decorator::split()
after:     $cellmap = $this-&gt;get_parent()-&gt;get_cellmap();

```
while($child-&gt;get_node()-&gt;getAttribute(&quot;dontbreak&quot;)){
    $child = $child-&gt;get_prev_sibling();
}
```
1. in the html &lt;tr &quot;dontbreak&quot;=&quot;1&quot;&gt; for each row that has cells that starts before it.

Thank you for that wonderful software.
Yariv
ydb1976@gmail.com

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=361_

**Comment by Bargoor** [comment]
For me works if i add <tr dontbreak="1"> with "" nothing happends
