### ISSUE TITLE
support display:inline-block

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#371]
_Original author: eclecticgeek (October 15, 2011 04:07:41)_

<b>What would you like dompdf to do:</b>
Render inline-block correctly

<b>Do you have an example:</b>
http://www.brunildo.org/test/inline-block.html

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=365_

**Comment by bsweeney** [comment]
This is partially implemented, but width calculation is off for `width: auto`. See #627.
