### ISSUE TITLE
safari spits out pdf.html as pdf file type

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#384]
_Original author: i...@interfacecreation.com (November 09, 2011 08:20:21)_

I am not able to get a pdf downloaded using safari it spits out example.pdf.html instead of example.pdf

i added header for the document but no difference.

<b>What version of the product are you using? On what operating system?</b>
0.6

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=378_

**Comment by Shetza** [comment]
Add a die() at the end of the method solved the issue for me
