### ISSUE TITLE
Non-ISO characters in content not displayed correctly

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#392]
_Original author: muellera...@tele2.de (December 02, 2011 06:27:47)_

<b>What steps will reproduce the problem?</b>
1. Put non-ISO characters (e.g. Greek symbols) in content of html body
2. Convert html-code to PDF
3. display PDF and question-marks are shown (in PDF, not in HTML)

<b>What is the expected output? What do you see instead?</b>
correct Greek symbols in the same way as in the HTML document

<b>What version of the product are you using? On what operating system?</b>
0.6 Beta

<b>Please provide the HTML source code you want to convert, or any additional</b>
<b>information.</b>

The HTML-document is W3-appropriate, coded in UTF-8 and encoding is done in 3 various ways - hexadecimal, decimal and ISO-/ANSI-coded.
All codings produce the same result:
They are all shown correctly in the HTML-document and displayed as question-marks in the PDF.

Is there any work-around to display these Non-ISO characters? I already checked other issues and found &quot;320&quot; but this won't help me with my problem.

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=386_

**Comment by bsweeney** [comment]
With the latest release you should be able to use the DejaVu fonts to display a wide range of characters. If further assistance is needed please open a new issue.
