### ISSUE TITLE
<label> inside <p> tag causes the removal of a whitespace before bold tag

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#393]
_Original author: valentin...@gmail.com (December 06, 2011 11:50:04)_

<b>What steps will reproduce the problem?</b>
1. When sending the text below to dompdf (no CSS needed):

&lt;p&gt;&lt;label&gt;Here is some &lt;b&gt;bold&lt;/b&gt; text and again &lt;strong&gt;some bold&lt;/strong&gt; text&lt;/label&gt;&lt;/p&gt;
1. The space before the tag &lt;b&gt; or &lt;strong&gt; is removed.
2. It's not a big issue but sometimes you can some preformatted text that you directly output to dompdf (from google maps api for example).
3. When removing the &lt;p&gt; tag it works as expected.

<b>What is the expected output? What do you see instead?</b>

Expected output: Here is some bold text and again some bold text

What I get is: Here is somebold text and againsome bold text

<b>What version of the product are you using? On what operating system?</b>

I am using the revision r436. / Windows 7.

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=387_

**Comment by Gummibeer** [comment]
The problem isn't solved yet and it's very annoying if you create PDFs out of wysiwyg editor html where most times the trailing spaces are in the formatting tag.
I thing it would be a good start to make this optional with a configuration value. This way there is a hint that dompdf does this and gives the ability for the user to disable this behaviour if it is unwanted.

**Comment by bsweeney** [comment]
@Gummibeer we are aware of the continuing difficulties of nested inline elements and removed spacing. If we add an option such as you request or the problem will likely run in the other direction (too much space between letters). Maybe that would be preferable, but I think it would require not much more work to resolve the issue. I think at this point it would make sense to open a new issue considering the age of this one.

**Comment by Gummibeer** [comment]
@bsweeney we have forked dompdf now and disabled the two lines that remove spaces and everything looks good. Specialy in case of wysiwyg content it's ok to tell the user "you've added two spaces there are two spaces" but it's not ok to tell him "you've added a space but we removed it cause it is at the wrong place"!
And also in case you load a predefined template or whatever in - it's better to display what was given than trying to fix things that shouldn't be fixed cause they are right how they are. Also if I want multiple spaces there - they have to stay there.

So adding a configuration would be good in every case - cause as dev I know what I put in and want to get the same out. Dompdf is a html to pdf converter and not a html cleanup tool.

**Comment by bsweeney** [comment]
The HTML spec specifies that extra white space is ignored and that's why we go through the trouble of removing it when rendering text. If adding multiple spaces the requirement should be that the space is either "pre" styled text or uses non-breaking spaces. Those shouldn't be removed by dompdf. But if you're talking about using something like `two. <span> Spaces</span>` to define extra space, most browsers will remove that extra space as well.

If you have specific examples of where this is a problem or incorrect in your view it would be helpful to see. Preferably in a new ticket.

**Comment by Gummibeer** [comment]
Ok, our problem atm is this:
`<p>lorem ipsum <strong>word </strong>word lorem</p>`
is transformed to
`<p>lorem ipsum <strong>word</strong>word lorem</p>`

so the space isn't moved but removed. the contents are generated with wysiwyg editor and the user decides where he closes the formatting tag.

**Comment by bsweeney** [comment]
OK, yes. That is a known issue that we still need to address and is not the correct/desired behavior. We do still want to trim space in general, but we'll take a closer look at improving detection of space on the borders inside and outside of inline elements.
