### ISSUE TITLE
List item bullet handling not optimal during page split

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#403]
_Original author: eclecticgeek (December 21, 2011 21:12:47)_

When a list item (LI) falls at the bottom of a page such that all the content in that LI is pushed to the next page the number remains on the preceding page. Ideally when no content remains for that LI on the current page it will be pushed to the next page.

Confirmed in trunk r449.

Sample code attached.

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=397_

**Comment by bsweeney** [comment]
Still a problem. Here's the HTML from the original issue:

```
<html>
<style>
    .block {
        height: 200px;
        width: 200px;
        background-color: orange;
    }
</style>

<body>
    <ol>
        <li>
            <div class="block">X</div>
        </li>
        <li>
            <div class="block">X</div>
        </li>
        <li>
            <div class="block">X</div>
        </li>
        <li>
            <div class="block">X</div>
        </li>
        <li>
            <div class="block">X</div>
        </li>
    </ol>
</body>

</html>
```

**Comment by bsweeney** [comment]
Actually. I think this particular issue has been resolved. However, there appears to be another issue around list bullets after the page break. The sample in 1799 is missing a bullet on the following page in the current release (0.8.5).

**Comment by bsweeney** [comment]
smh ... or not. The sample from 1799 has a list item with a line break but the same text.

Never make assumptions about what you're looking at, folks.

**Comment by bsweeney** [comment]
I believe this issue is sufficiently addressed by the current release. Please post back if anyone is able to determine otherwise.
