### ISSUE TITLE
Certain locale settings break rendering (PHP bug)

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#450]
_Original author: eclecticgeek (March 19, 2012 02:35:06)_

If a user sets the PHP locale to certain values (e.g. tr_TR for Turkish) DOMPDF will die with the following error:
Fatal error: Interface 'IteratorAggregate' not found in dompdf/include/frame.cls.php

The issue is due to a bug in PHP (see references below). As I understand it, when a PHP class is instantiated a quick match is made using a lowercase version of the class name. In some languages upper- and lowercase versions of a letter are different than in other languages (e.g. Turkish vs. English). When the locale is set one of those languages the lowercase version of the class name no longer matches.

DOMPDF dies at the above class, but others may also be affected.

Since the problem has been present in PHP for a number of years we may want to go ahead and build a work around into the DOMPDF source (if feasible).

Support group discussion:
https://groups.google.com/d/topic/dompdf/NrCz8Qeen1I/discussion

PHP bug references:
https://bugs.php.net/bug.php?id=18556
https://bugs.php.net/bug.php?id=35050

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=444_

**Comment by bsweeney** [comment]
Closing. I believe PHP has addressed the underlying issue.
