### ISSUE TITLE
Ordered list value property ignored

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#477]
_Original author: a_re...@live.co.uk (April 25, 2012 10:37:40)_

<b>What steps will reproduce the problem?</b>

Here is a source example:

$html = &lt;&lt;&lt;HTML
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;body&gt;
&lt;ol&gt;
    &lt;li value=&quot;1&quot;&gt;First Item&lt;/li&gt;
    &lt;li value=&quot;2&quot;&gt;Second Item&lt;/li&gt;
    &lt;li value=&quot;5&quot;&gt;Third Item&lt;/li&gt;
    &lt;li value=&quot;6&quot;&gt;Fourth Item&lt;/li&gt;
&lt;/ol&gt;
&lt;/body&gt;
&lt;/html&gt;
HTML;

require_once APPPATH . 'third_party/dompdf/dompdf_config.inc.php';
$dompdf = new DOMPDF();
$dompdf-&gt;load_html($html);
$dompdf-&gt;set_paper('letter', 'portrait');
$dompdf-&gt;render();
$dompdf-&gt;stream('dompdf_out.pdf', array('Attachment' =&gt; false));

<b>What is the expected output? What do you see instead?</b>

I expect to see:
1. First Item
2. Second Item
3. Third Item
4. Fourth Item

But what I see instead:
1. First Item
2. Second Item
3. Third Item
4. Fourth Item

It ignores the value property of the ordered list when it should recognize it.

<b>What version of dompdf are you using? What version of PHP? On what</b>
<b>operating system?</b>

Windows 7, PHP 5.3.5, using the latest DOM copy pulled from SVN trunk today 25/04/2012.

Thank you.

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=471_

**Comment by ancabr** [comment]
Did someone managed to use the "value" attribute of the li tag somehow in the PDF?

**Comment by bsweeney** [comment]
@ancabr seems to work fine. Which version of Dompdf are you using? Do you have some sample HTML?
