### ISSUE TITLE
Assign current page number to  new variable

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#483]
_Original author: amtpraja...@gmail.com (April 30, 2012 06:54:16)_

I want to store current page number to new variable and use it for further processing.but i am not able to do so.

i am using like 

``` php
<script type="text/php"> 
if ($pdf) { 
$GLOBALS['chapters'][1] = $pdf->get_page_number() + 1;

}
```

but  $GLOBALS['chapters'] producing NULL value .my inline PHP script is on .

i want like this $page_num = CURRENT PAGE NUMBER;

version of dompdf : dompdf_0-6-0_beta3
version of PHP: 5.3
operating system : Windows XP

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=477_

**Comment by PowerKiKi** [comment]
I think this very old question should be closed as it very likely is a misuse/misunderstanding of dompdf.

**Comment by bsweeney** [comment]
@PowerKiKi thanks for the pointer. There are some very old questions, don't have much time to go through them unless called out.
