### ISSUE TITLE
Include version number in a DOMPDF_VERSION define

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#493]
_Original author: j...@venturas.org (May 21, 2012 08:46:22)_

I'd like to be able to discover the version of dompdf without having to resort to the following:

  // Poor man's way to find dompdf version
  if (!defined('DOMPDF_DIR')) {
    return 'unknown';
  }
  else if (!defined('DOMPDF_CHROOT')) {
    return '0.5.1';
  }
  elseif (!defined('DOMPDF_FONT_CACHE')) {
    return '0.5.2';
  }
  elseif (!defined('DOMPDF_LOG_OUTPUT_FILE')) {
    return '0.6.0 beta1';
  }
  elseif (!defined('DOMPDF_ADMIN_USERNAME')) {
    return '0.6.0 beta2';
  }
  else {
    return '0.6.0 beta3';
  }

Ideally, create a define (e.g. DOMPDF_VERSION) with the version number of each release.

Thanks

Joao Ventura
(maintainer of the Drupal print module, which integrates with dompdf)

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=487_

**Comment by bsweeney** [comment]
This was done a while ago, though the version info in Composer current shows the hash of the tagged commit.
