### ISSUE TITLE
command line mode CSS bug: background-image

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#50]
_Original author: timothy....@gmail.com (July 21, 2009 20:41:09)_

Hi!  I hope this is the correct place to report this problem.  I've searched the issues here and the 
discussion group, but I haven't found this problem mentioned.
Thanks for an excellent PDF creator!
-Tim

<b>What steps will reproduce the problem?</b>
1.  In your css, explicitly set {background-image: none;} for any element
2.  Inside your php script, use the dompdf class directly.  Specifically, the script will hang on 
$dompdf-&gt;render();
3.  call your php script from the command line:
~# php -f /path/to/script/myscript.php

<b>What is the expected output? What do you see instead?</b>
I expect no errors to output, and the dompdf object to successfully call the render() function.
Instead, the following Fatal Error occurs:

```
PHP Fatal error:  Uncaught exception 'DOMPDF_Exception' with message 'Unknown image type: 
/path/to/script/none.' in /path/to/script/dompdf/include/image_cache.cls.php:81
Stack trace:
#0 /path/to/script/dompdf/include/abstract_renderer.cls.php(105): 
Image_Cache::resolve_url('/path/to/script/', NULL, '', '')
#1 /path/to/script/dompdf/include/block_renderer.cls.php(62): Abstract_Renderer-
&gt;_background_image('/path/to/script/', 8, 8.04, 596, 100.464, Object(Style))
#2 /path/to/script/dompdf/include/renderer.cls.php(180): Block_Renderer-
&gt;render(Object(Block_Frame_Decorator))
#3 /path/to/script/dompdf/include/renderer.cls.php(91): Renderer-&gt;_render_frame('block', 
Object(Block_Frame_Decorator))
#4 /path/to/script/ in /path/to/script/dompdf/include/image_cache.cls.php on line 81
```

It looks to me as if dompdf is taking the 'none' after 'background-image:' literally, and trying to 
find a local image called 'none'.  Of course, there is no such image, and dompdf crashes.

<b>What version of the product are you using? On what operating system?</b>
Version: 0.5.1
OS: Mac OS X Server 10.4.11

<b>Please provide any additional information below.</b>
This error does no occur if the php script is available to the web and called via a browser, only 
when called directly in command line mode.

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=43_

**Comment by bsweeney** [comment]
Closing. This issue is rather obscure, haven't seen report of a similar problem of late.
