### ISSUE TITLE
InDesign PDF Place does not work

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#517]
_Original author: kremer....@gmail.com (July 02, 2012 15:08:26)_

<b>What steps will reproduce the problem?</b>
Generate any PDF with DOMPDF.

<b>What is the expected output? What do you see instead?</b>
Should be able to place the generated PDF in InDesign but InDesign errors.

<b>What version of dompdf are you using? What version of PHP? On what</b>
<b>operating system?</b>
DOMPDF=latest; PHP=5.3.1

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=511_

**Comment by bsweeney** [comment]
Improvements to font subsetting and PDF generation may have resolved this issue. If not let us know.
