### ISSUE TITLE
border-collapse doesn't retain borders on page break

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#518]
_Original author: makethat... (July 03, 2012 18:51:09)_

If you are using a table with border-collapse and the table breaks between pages, the first row on the new page is missing it's top border.

An example:
![35f1a842452090c8f3c6035e74438211](https://user-images.githubusercontent.com/485897/138708355-5afa6dc7-ae48-400a-967e-62ee1a903983.png)

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=512_

**Comment by dhelly** [comment]
I had the same problem in my application, but I removed the tag "<tbody>" by "<body>" and it worked for me. ;)

**Comment by dhelly** [comment]
I had the same problem in my application, but I removed the tag "tbody" by "body" in the table and it worked for me.
