### ISSUE TITLE
Remove Warnings/Errors in DOMPDF Code Validation

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#520]
_Original author: virg (July 10, 2012 02:58:23)_

There are 89 code validation warnings/errors in the DOMPDF that stem from four main categories:

1) Assignment in condition

   Easy fixes, for example:
     CHANGE:   while ( $child = $this-&gt;_first_child )
     TO:       while ( ($child = $this-&gt;_first_child) !== false )

2) Bad escape sequence: \?

   Easy fixes, for example:
     CHANGE:   $ret = preg_replace(&quot;/\?(._)$/&quot;, &quot;&quot;, $ret);
     TO:       $ret = preg_replace('/\?(._)$/', &quot;&quot;, $ret);

3) Class not found
  *\* See Attached Errors **

4) Class 'TCPDF_Adapter' must implement inherited abstract method 'scale(...)'
  *\* See Attached Errors **

These can be fixed very quickly by simply performing basic validation across the project using an IDE such as Eclipse or Zend Studio. I would be extremely grateful if these were fixed in the main repository instead of having to fork and maintain a separate clone.

[DOMPDF Errors.xlsx](https://github.com/dompdf/dompdf/files/7664330/DOMPDF.Errors.xlsx)

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=514_

**Comment by bsweeney** [comment]
If these haven't been addressed by now, well ...
