### ISSUE TITLE
page-break-inside:avoid bad break next element

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#521]
_Original author: jonasfon (July 12, 2012 20:55:57)_

<b>What steps will reproduce the problem?</b>
With this HTML:
&lt;div style=&quot;page-break-inside:avoid&quot;&gt;
    &lt;div class=&quot;top&quot;&gt;top top top top top top top top top top top top top top top top top top top top top top top top top top top toptop top top top top top top top top top top top top toptop top top top top top top top top top top top top top &lt;/div&gt;
    &lt;div class=&quot;bottom&quot;&gt;bottom bottom bottom bottom bottom bottom bottom bottom bottom bottom bottom bottom bottom bottom bottom bottom bottom bottom bottom bottom bottom bottom bottom bottom &lt;/div&gt;
&lt;/div&gt;

This piece of code when dompdf need to break a page, put this element in next page, all fine. But, inside of element div.bottom look bad.

<b>What is the expected output? What do you see instead?</b>
nicely formatted, without bad tab inside div.bottom.

<b>What version of dompdf are you using? What version of PHP? On what</b>
<b>operating system?</b>

dompdf 0.6.0
PHP 5.3.1 linux

<b>Please provide the HTML source code you want to convert, or any additional</b>
<b>information.</b>

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=515_

**Comment by bsweeney** [comment]
Any issues rendering the sample code provided should all be addressed.
