### ISSUE TITLE
[PATCH] Fix CSS :nth-child() pseudo-selector

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#542]
_Original author: mcuelena...@gmail.com (September 22, 2012 14:37:28)_

When parsing CSS, the parser didn't properly skip the complete token; which resulted in it trying to parse the contents of the selector (again).
This made it parse e.g. &quot;td:nth-child(n+2)&quot; as &quot;td:nth-child(n+2) + 2&quot;.

This patch fixes that behaviour.

``` diff
diff --git a/dompdf/include/stylesheet.cls.php b/dompdf/include/stylesheet.cls.php
index fb3a748..907f884 100644
--- dompdf/include/stylesheet.cls.php
+++ dompdf/include/stylesheet.cls.php
@@ -556,6 +556,7 @@ class Stylesheet {
             $condition = $this->_selector_an_plus_b($nth, $last);
           }

+          $i += strlen($nth) + 2;
           $query .= "[$condition]";
           $tok = "";
           break;
```

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=536_

**Comment by bsweeney** [comment]
It _looks_ like any nth-child issues are now fully addressed ... though this particular patch does not appear to have been applied. It's entirely likely other changes were made that address this issue. I'll have to compare the relevant code as it stood when this patch was originally addressed against what it looks like now.
