### ISSUE TITLE
element:nth-child(n) acts more like element:nth-of-type(n)

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#543]
_Original author: eclecticgeek (September 24, 2012 15:07:08)_

The :nth-child() selector should count all elements when determining if an element is affected by the selector formula. Even if an element is specified, all elements should be counted and the rule is applied only if the specified element _and_ the selector formula are both satisfied.

For example, if we have the following style:

``` css
#container p:nth-child(2n) { background-color: blue; }
```

And the following HTML:

``` html
<div id="container">
  <h1>Title</h1>
  <p>This is blue</p>
  <p>This is not blue</p>
</div>
```

The first P encountered will be blue because it matches the criterion.

References:
http://dev.w3.org/csswg/selectors3/#nth-child-pseudo
https://developer.mozilla.org/en-US/docs/CSS/:nth-child
http://www.quirksmode.org/css/nthchild.html
http://css-tricks.com/how-nth-child-works/

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=537_

**Comment by simison** [comment]
In case anyone needs to replace their nth-child CSS with something that works with dompdf:

>th + th = nth-child(2)

**Comment by bsweeney** [comment]
FYI nth-child and nth-of-type have the same behavior because the same code is used for each ([ref in 0.7.0](https://github.com/dompdf/dompdf/blob/v0.7.0/src/Css/Stylesheet.php#L583)).
