### ISSUE TITLE
layout breaks after large number of pages

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#550]
_Original author: hungvt (October 08, 2012 05:56:43)_

I'm trying to generate from a html file to PDF. i have attached here. could you check it for me and let me know what happen?

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=544_

**Comment by martijngastkemper** [comment]
#620 Mentions the same issue and provides [the source of the problem](https://github.com/dompdf/dompdf/issues/620#issuecomment-119218509).

**Comment by bsweeney** [comment]
Unfortunately samples are missing from both issues 😞. Going to close this in favor of 620 since multiple issues were discussed here and 620 at least seems a bit more focused.
