### ISSUE TITLE
Support for position:fixed

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#56]
_Original author: tomd (July 31, 2009 09:16:00)_

<b>What would you like dompdf to do:</b>

Print position-fixed elements on every page as the browser actually do
(Firefox at least). That would add effortless headers and footers - as well
as left/right margin decorations - capabilities.

<b>Do you have an example:</b>

Here is a topic where I explained my problem with browser only printing
solution, that's why we're envisaging server-side PDF generation instead :
http://forums.mozillazine.org/viewtopic.php?f=7&amp;t=885955.

The actual HTML file is there :
http://mediboard.svn.sourceforge.net/viewvc/mediboard/trunk/modules/dPcompteRendu/templates/printable.html?revision=4919

You will find attached the printing results with server side dompdf 0.5.1
browser side Firefox 3.5.

[Printed Document (v4919) with dompdf.pdf](https://github.com/user-attachments/files/16325742/Printed.Document.v4919.with.dompdf.pdf)
[Printed Document (v4919) with browser.pdf](https://github.com/user-attachments/files/16325743/Printed.Document.v4919.with.browser.pdf)

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=49_

**Comment by strarsis** [comment]
Please note that the element that should be positioned fixed must be a direct child element of the body/page.
I encountered an issue where the fixed-positioned element was not rendered, the reason was the element being nested.

**Comment by bsweeney** [comment]
@strarsis follow #1574 for updates to that issue.
