### ISSUE TITLE
Table width stretches after PDF conversion

### ISSUE THREAD

**Issue by stoopkid1** [dompdf/dompdf#569]
I'm sure this is a very simple answer, but after looking through the Wiki and the examples, I cannot figure out how to fix my problem.

I have a table that replicates a Medical Form. When I assign a table width via CSS the table width changes on my HTML page, but never on my PDF. I cannot figure out how to assign a width that will follow from the HTML to the PDF conversion. 

What are the steps to assigning a table width that will also work on the PDF?

Here is my test page: http://www.stoopkids.com/rcs/med/test.php

No matter what width I assign, whether inline css or through a css file, the PDF always cuts off a huge portion of the table. How can I fix this? I am not trying to do anything fancy, just a simple table but it stretches out on the PDF conversion.

I am using the most recent release of DOM PDF, Windows 7, PHP5.

**Comment by MrGusan** [comment]
Remove any new lines inside td elements, it will fix it. td or th elements opening and closing tags should be in one line

**Comment by bsweeney** [comment]
This issue is long past its freshness date and the example HTML originally linked it no longer available. Closing.
