### ISSUE TITLE
Split www & cli into their own projects

### ISSUE THREAD

**Issue by raykolbe** [dompdf/dompdf#570]
As the title states, I'm recommending that DOMPDF be broken out into a few projects. Specifically I see DOMPDF as:

* DOMPDF lib -- the core components of DOMPDF
* CLI -- a command line interface for managing fonts and generating PDFs using DOMPDF lib
* WWW - a web-based management page(s) that would use CLI

By splitting these out, we break our problem domains down, allowing for more maintainable code bases, clear responsibilities, and allowing the opportunity for other projects to implement their own replacement package (e.g. 3rd party web-based management site).

If you take a look at my (now defunct) dompdf project (https://github.com/raykolbe/dompdf) you'll see that I started breaking everything down to just the DOMPDF lib basics. I would like to see this continue (now I'm going to fork you!).

Ref: #558

**Comment by bsweeney** [comment]
Utility code was removed in commit db8ca427128dcce38698dade85cdd195a1c504ee.

**Comment by bsweeney** [comment]
This code will eventually be made part of the [dompdf-utils](https://github.com/dompdf/utils) project
