### ISSUE TITLE
How to add header & footer (using html) for every page.

### ISSUE THREAD

**Issue by hungvt** [dompdf/dompdf#571]
Hello,
i'm wondering can your DOMPDF can add header & footer for every page by using html?
I got some tips but all of them tell me by using &lt;script type="text/php"&gt;...&lt;/script&gt;
My html file will like this:

``` html
<div class="page">
<!-- content of page -->

<div style="position: absolute;bottom: 10px; left: 10px; ">THIS IS MY FOOTER</div>
</div>

My css:
.page {
page-break-after:always;
position: relative;
}
```

I have a lot of content within the page So with my html document your DOMPDF will render to many pages.
The problem is the footer will be only displayed in the last page. Is there any way to add the my footer to any page?

I have an idea like this.

``` html
<div style="A_CSS_ATTRIBUTE:all;position: absolute;bottom: 10px; left: 10px; ">THIS IS MY FOOTER</div>

<div class="page">
<!-- content of page -->
</div>
```

So anytime we got the style is A_CSS_ATTRIBUTE:all; we will render that object for all page.

**Comment by hergy88** [comment]
Hi bsweeney,

Thank you so much for the advice!
I had the problem not was printing the footer on the first page, but only in the other. It works perfectly if i put footer at the top HTML.

**Comment by dpbcharith** [comment]
thanks

**Comment by Asimov500** [comment]
I have made a header using the above code, but how do you stop the following pages going over the header? Say my header was a variable height. It could be 300px high or 200px.  So it shows at the top of the page, but my table which is cascading over one page to the next is going over the header. Is there any way to stop this?

**Comment by Asimov500** [comment]
Thanks. What I did was to give my <body> a margin-top which solved the problem. In the end I forced the image at the top to a specific height and and the margin-top and that solved my problem, and I used .header{position:fixed;top:0px;}

**Comment by master455** [comment]
A little observation:

If you are using **Phalcon PHP Framework** (i'm using 3.2 version) and you want this behavior, in Action to generate pdf must put:

```
$this->view->disable(); // disable output view 

// disable all parents rendering levels
$this->view->disableLevel(
            array( 
                View::LEVEL_BEFORE_TEMPLATE => true,
                View::LEVEL_LAYOUT          => true,
                View::LEVEL_AFTER_TEMPLATE  => true,
                View::LEVEL_MAIN_LAYOUT     => true
            )
        );
```

**_On the contrary, DomPDF only generate Header and Footer in first page and it don't in all pages._**

**Comment by hermanomark** [comment]
> ```
>  <div class="footer">Page: <span class="pagenum"></span></div>
> ```

is this obsolete now? I tried it only shows 0 on every page

**Comment by bsweeney** [comment]
@hermanomark should be fine. What version of Dompdf, and what is your CSS?
