### ISSUE TITLE
nested divs with page-break-inside:avoid start rendering on wrong page, gain strange bottom padding

### ISSUE THREAD

**Issue by s3lf** [dompdf/dompdf#577]
sorry, i posted this on the code.google.com page first (http://code.google.com/p/dompdf/issues/detail?id=515#c18) and now realised your issues section has been moved. so this is a copy of my report there. i didnt find anything related to that exact problem here, but i could have missed that... however, here's the report:

Creating a script for automatically generating catalogue PDFs, I noticed a strange behaviour in some cases when using dompdf to display divs containing tables. Since I could not find any info on that particular thing, I created a test file and could narrow down a part of the problem to one particular css setting.

REPRODUCTION:
to reproduce with the attached template.php file: set dompdf to use inline php, dpi to 96, paper to A4 portrait

The attached file uses its embedded style definition to define 
- divs with class "nobreak" as -> page-break-inside:avoid; and grey border/bg
- divs with class "inside" as -> width:400px; and red border/bg

The body code is quite simple, just having "nobreak" divs containing 2 "inside" divs each, and inside those several lines of text.

EXPECTED: 
If possible (due to height of "nobreak" div), all "nobreak" divs should not have a page break inside. 

RESULT: 
"nobreak" divs are (just check the css bounding boxes) often rendered partly on the page they wouldn't fit in, partly on the other page. However their content is entirely being rendered on the next page. This would be ok for me, but in unluckily the "nobreak" div gains height it doesn't need, like an additional padding-bottom. 

FINDING: 
If I comment out the line specifying the "inside" div width (line 32), the height-gaining problem disappears. But still the "nobreak" divs will start rendering on the previous page.

VERSION:
I am currently using dompdf 0.6.0 b3. I also tried using a nightly version (as recommended by lewiji) I downloaded about three weeks ago, but that seemed to completely ignore the page-break-inside:avoid; ...
I am testing on local Server on my Computer here Windows 7 Enterprise 32bit (PHP 5.3.5) and on an Online Server using some Linux version (PHP 5.3.15). 

4 attached files:
dompdf.config.inc.php (for dompdf 0.6.0 b3)
createpdf.php (containing the rendering code, just 10 lines)
template.php (containing inline php and html code to render as pdf)
and the pdf file of the result I am getting.

--> the files are attached to my report in your google issues section: http://code.google.com/p/dompdf/issues/detail?id=515#c18 <--

thanks a lot for looking into this!

**Comment by bsweeney** [comment]
closing in favor of original issue #521
