### ISSUE TITLE
frame_decorator.cls.php hangs on large tables

### ISSUE THREAD

**Issue by jakejackson1** [dompdf/dompdf#595]
Hi,

My PHP server shows that the maximum execution time is being exceeded on line 393 of frame_decorator.cls.php when trying to render largish tables (a handful of pages at most). You can view the HTML that is trying to be rendered here: http://clients.blueliquiddesigns.com.au/code.txt

I've used the exact same code on smaller table data without a problem before but this issue seems to persist across different server configurations. 

I'm running 0.6.0 beta 3. Any help would be greatly appreciated.

**Comment by bsweeney** [comment]
No sample code to test against.
