### ISSUE TITLE
Underline not rendered correctly.

### ISSUE THREAD

**Issue by tic2000** [dompdf/dompdf#609]
What steps will reproduce the problem?

Save <a href="http://dev.multibrandingshop.com/aachen.ttf">this font</a>.
Install it in your dompdf.
Try to put some underlined text in a PDF using the new font family.

What is the expected output? What do you see instead?

Expected <a href="http://dev.multibrandingshop.com/correct.pdf">output</a>
Actual <a href="http://dev.multibrandingshop.com/after-17446bc.pdf">output</a>

What version of dompdf are you using? What version of PHP? On what
operating system?
Latest. 5.3. Tried both on linux and Mac.

Please provide the HTML source code you want to convert, or any additional
information.

Any underlined text will do.

I was using an older version of dompdf and I tried to underline that font. The result was a to thin underline and way below the text. But the text was at top as it should have been.

I updated to the latest version and now the underline is OK, but the text is where the old underline was.

The commit that fixed the underline and broke the text is 17446bc.
Looking at the 2 ufm files I noticed that the one with the text in the correct position had
Ascender 857
Descender -143
FontBBox -25 -332 1078 1144

while the wrong one had
Ascender 1144
Descender -332
FontBBox -25 -332 1078 1144

The same day this was commited, March 25th of last year, a change for php-font-lib was done too. Reverting the change for php-font-lib was how I actually generated the correct pdf. Now both the underline is in the right position and has the right thickness and the text is in the right position too.

But I don't know what that could brake either.

**Comment by inbaz** [comment]
Hey, I found this issue and I got nearly the same problem. I've inserted Open Sans from the google fonts into my document with this link tag:

**Comment by ethaizone** [comment]
@inbaz I tried edit .ufm.php file in vendor directory and this work for me too.

My font is Garuda and Initial UnderlinePosition value is -32. I need change it to -1100 for make it look good in my pdf. 

Thank you for point out this info.  It help me a lot. :)

**Comment by ethaizone** [comment]
Maybe this is related issue on https://github.com/PhenX/php-font-lib/issues/7

In this line.
https://github.com/dompdf/dompdf/blob/5113accd9ae5d466077cce5208dcf3fb871bf8f6/src/Renderer/Text.php#L107

Value will divide by 1000 for use in lib. Maybe this is fail from php-font-lib?

**Comment by ethaizone** [comment]
https://github.com/dompdf/dompdf/blob/5113accd9ae5d466077cce5208dcf3fb871bf8f6/src/Renderer/Text.php#L135

Currently this line don't have proper value. I think we expect `$deco_y` should have **baseline position** but I don't know how we can get that. In php-font-lib they don't provide more infomation such as XHeight value but I don't think it will help us too. 

https://github.com/dompdf/dompdf/commit/763ed27ba0a036b3958bd12674ba9a352dac267d#diff-47ad25618e24e7cdae67048db5fb13cfL92

For this older commit. Just as you see. These code use  Ascender and Decender value to shift `$base` position for use adjust `$deco_y` later. For me I like that lastest implement that make `$base`  stay as it be but I think we need to find they way how we can get **baseline** and use it as `$deco_y`.

Ref: http://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/5004.AFM_Spec.pdf
http://www.washington.edu/perl5man/sitemodules/Font/AFM.html

**Comment by ethaizone** [comment]
IDK why but this fix for me. Need someone to test it,

https://github.com/dompdf/dompdf/pull/1631

**Comment by ismael-cm** [comment]
Intente varias cosas, incluso de este foro. Yo lo arreglé colocándole un Font.

@font-face {
    font-family: "Roboto-Regular";
    src: url("../dompdf/lib/fonts/Roboto-Regular.ttf") format("truetype");
}
            

body {
    font-family: "Roboto-Regular";
}
