### ISSUE TITLE
Floats not working in current version, but were before

### ISSUE THREAD

**Issue by Harrisonbro** [dompdf/dompdf#611]
Using the most current version of dompdf (commit [424c235949](https://github.com/dompdf/dompdf/commit/424c235949407b590002e7f0f4be2e0e911bc784)) the floats in my PDF seem to have stopped working. 

On a previous version they did work, but now don't. I updated because the newer versions support page-break-inside: avoid; which is really useful for tables.

I am giving dompdf [this HTML](http://cl.ly/Nrpu) and [this CSS](http://cl.ly/Ns34). On the older versions the PDF looked [like this](http://f.cl.ly/items/1P1829190j0b2I0d1o2G/old%20version.pdf), now with the latest version of the master branch it looks [like this](http://f.cl.ly/items/2k2J1Y3z1D1c1G2D2U3C/current%20version.pdf). Looks to me like the top right section is not floating correctly so it's pushing the logo down below it.

Environment:
- MAMP Pro version 2.1.2
- PHP version 5.3.20
- Mac OS X Lion 10.7.5

Hope you can help! Thanks for the great work you guys are doing — really useful project.

**Comment by mohit-eis** [comment]
I already define 
define("DOMPDF_ENABLE_CSS_FLOAT", true);

but still not working.

**Comment by bsweeney** [comment]
@mohit-eis can you share a sample of your HTML?

**Comment by mohit-eis** [comment]
can we add external HTML file???

**Comment by bsweeney** [comment]
github doesn't accept file uploads, but you can link to the file hosted elsewhere.

**Comment by mohit-eis** [comment]
I want to add external html file in $html variable in dompdf content.  is it possible???

**Comment by bsweeney** [comment]
dompdf can natively access external files, just use `$dompdf->load_html_file()`. Or if you want to load the HTML document into a variable first use the `file_get_contents()` PHP function then `$dompdf->load_html()`.

**Comment by bsweeney** [comment]
@mohit-eis FYI general questions are best asked on the support forum: http://groups.google.com/group/dompdf
