### ISSUE TITLE
Support referencing resources in PHAR archives

### ISSUE THREAD

**Issue by bacinsky** [dompdf/dompdf#621]
Add "phar://" to
https://github.com/dompdf/dompdf/blob/master/include/functions.inc.php#L143

**Comment by bsweeney** [comment]
Noted elsewhere: https://bugs.php.net/bug.php?id=52769

**Comment by UweKeim** [comment]
What currently works on my Windows dev machine is to remove all `realpath` calls inside the dompdf sources.

I.e. this:

```php
$dir = realpath(__DIR__ . "/../..");
```

will become this:

```php
$dir = (__DIR__ . "/../..");
```

Inside PHAR archives, `realpath` for paths _inside_ a PHAR file returns `false` (See [#52769](https://bugs.php.net/bug.php?id=52769)).

**Comment by bsweeney** [comment]
Also see https://groups.google.com/d/topic/dompdf/PxGsXAjXIkI/discussion
