### ISSUE TITLE
Unable to access any examples or demo locally

### ISSUE THREAD

**Issue by Annaleria** [dompdf/dompdf#625]
I have tried several setting and now I get the error Fatal error: Call to undefined method domdocument::appendChild() in C:\wamp\www\dompdf-master\lib\html5lib\TreeBuilder.php on line 229

Several times now I appear to having issues with the domdocument class.  Has there been a new copy of this recently or am I missing something?

**Comment by bsweeney** [comment]
Samples are no longer included with the library (though may be resurrected in the [utils project](https://github.com/dompdf/utils)).
