### ISSUE TITLE
Problem with UTF-8

### ISSUE THREAD

**Issue by cesarbsilva** [dompdf/dompdf#626]
I have a problem with the character encoding UTF-8.

In html added:
  meta http-equiv="content-type" content="text/html;charset=utf-8" 

But when generating the pdf appears to me the following:

"55.6% - Inferior a 2 salários mínimos 
22.2% - De 2 a 5 sala?rios mi?nimos"

The demo is the same problem.

The strange thing is that the same word appears both correctly, as wrong

Because sometimes it works and sometimes not?

**Comment by kyobul** [comment]
Concerning Thujohn/PDF and Laravel specifically I had this encoding issue only on production server side. I solved it by passing all the string output in the generated pdf through the Laravel e() helper function which runs htmlentities over the given string, with UTF-8 support.

**Comment by probircse** [comment]
Today I am downloading new version of Dompdf. I Used this code below
`require_once 'dompdf/autoload.inc.php';
use Dompdf\Dompdf;
$dompdf = new Dompdf();
$dompdf->loadHtml('hello world');
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
$dompdf->stream();`

But I have getting error to open generate pdf by Dompdf
![error](https://cloud.githubusercontent.com/assets/17059457/14672987/142364f8-071d-11e6-8867-fde81572bf87.jpg)

Anyone please help me

**Comment by bsweeney** [comment]
@probircse FYI best practice if you're having an issue unrelated to the ongoing discussion is to open a [new issue](https://github.com/dompdf/dompdf/issues/new) or post to the [support forum](http://groups.google.com/group/dompdf).

That being said, there's a good chance PHP threw a notice that got caught in the PDF content stream. Try opening your PDF in a text editor, the notices usually wind up above the PDF source.

**Comment by molcik** [comment]
I had problems with UTF-8 chars and finally resolved it. **Here is [tutorial](https://filipmolcik.com/dompdf-with-special-characters-utf-8/).**

**Comment by krisnafitrar** [comment]
hmm i have same problem with UTF-8

**Comment by mr-ben-jeckson** [comment]
terrifying issues of my entire development life Zzzzzzzz

**Comment by mr-ben-jeckson** [comment]
haha reading issues. Wasting time. I should develop core myself. DejaVu Sans is funny :'(
![1](https://github.com/dompdf/dompdf/assets/30015653/e6964644-c7f2-4669-bffb-000d7b5dbd9b)
![2](https://github.com/dompdf/dompdf/assets/30015653/f8606b96-bc35-478d-ba03-2f03549a462f)
