### ISSUE TITLE
DOMPDF and PAGE-BREAK-INSIDE

### ISSUE THREAD

**Issue by ynthn** [dompdf/dompdf#653]
Hi I need help, I have an HTML DIV that has several text as follows:

``` html
<div style="page-break-inside:avoid;">

<div class="title">title...</div>

<div class="text">text...text...text...text...text...text...</div>

</div>
```

the problem is when the text very large, exceeding a page, blank pages are generated and the text is not complete.
How I can fix this?

from already thank you very much.

**Comment by sinothoma** [comment]
Hello All, 
I am used the following html code,I got several blank pages and content is not displaying properly in the table.

<html>
  <head>
    <title>Sample "Hello, World" Application</title>
  </head>
  <style type="text/css">
						#footer {
						  position: fixed;
						  left: 0;
						  right: 0;
						  color: #0000;
						}
						#footer {
						  bottom: 0;
						}
						#footer table {
							width: 100%;
							border-collapse: collapse;
							border: none;
						}
						#footer td {
						  padding: 0;
							width: 50%;
						}
						.page-number {
						  text-align: center;
						}
						
						
						</style>
<body>
<table width="550" border="1" cellpadding="0" cellspacing="0" style="font-family:Arial, Helvetica, sans-serif; font-size:11px; margin-top:0;border-bottom:0.5px;border-top:0.5px; page-break-inside: auto;">
								<tr style="border-bottom:solid 1px #000;">
								   <td height="15" width="10%" valign="top" style="padding-top:2px;">&nbsp;&nbsp;</td>
								   <td width="10%" valign="top" style="padding-top:2px;">&nbsp;&nbsp;</td>
								   <td width="20%" valign="top" style="padding-left:5px; padding-top:2px;"></td>
								   <td width="60%"  valign="top" style="padding-left:5px; padding-top:2px;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum. Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem IpsumAldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
								   when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
								   but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
								   Lorem Ipsum passages, and more recently with desktop publishing software like 
								   Aldus PageMaker including versions of Lorem Ipsum</td>
								 </tr> 
								 </table>
 </body>
</html>

**Comment by bsweeney** [comment]
@sinothoma you're probably running into issue #98.

**Comment by ArvidEnbom** [comment]
I have this issue as well. Whenever I use `page-break-inside:avoid` on an element that is larger than one page, the entire element is squished into the top left corner, and I get all sorts of other issues.

Right now I'm forced to comment out the `page-break-inside:avoid` and just have the element continue on the next page, since there's no way to solve it.

**Comment by rick31** [comment]
have you found  a solution to this problem ?

**Comment by bsweeney** [comment]
Looks like the particular issue outlined here has been addressed (tested in 0.8.3).

@rick31 if you have a sample that doesn't work in the latest release of Dompdf feel free to follow up.

**Comment by parmarvishal21** [comment]
@sinothoma Have you found a solution to this problem ?

**Comment by parmarvishal21** [comment]
> Hello All,
> I am used the following html code,I got several blank pages and content is not displaying properly in the table.
> 
> ```
> <html>
>   <head>
>     <title>Sample "Hello, World" Application</title>
>   </head>
>   <style type="text/css">
>                         #footer {
>                           position: fixed;
>                           left: 0;
>                           right: 0;
>                           color: #0000;
>                         }
>                         #footer {
>                           bottom: 0;
>                         }
>                         #footer table {
>                             width: 100%;
>                             border-collapse: collapse;
>                             border: none;
>                         }
>                         #footer td {
>                           padding: 0;
>                             width: 50%;
>                         }
>                         .page-number {
>                           text-align: center;
>                         }
> 
> 
>                         </style>
> <body>
> 
> <table width="550" border="1" cellpadding="0" cellspacing="0" style="font-family:Arial, Helvetica, sans-serif; font-size:11px; margin-top:0;border-bottom:0.5px;border-top:0.5px; page-break-inside: auto;">
>                                 <tr style="border-bottom:solid 1px #000;">
>                                    <td height="15" width="10%" valign="top" style="padding-top:2px;">&nbsp;&nbsp;</td>
>                                    <td width="10%" valign="top" style="padding-top:2px;">&nbsp;&nbsp;</td>
>                                    <td width="20%" valign="top" style="padding-left:5px; padding-top:2px;"></td>
>                                    <td width="60%"  valign="top" style="padding-left:5px; padding-top:2px;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum. Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem IpsumAldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
>                                    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, 
>                                    but also the leap into electronic typesetting,remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
>                                    Lorem Ipsum passages, and more recently with desktop publishing software like 
>                                    Aldus PageMaker including versions of Lorem Ipsum</td>
>                                  </tr> 
>                                  </table>
>  </body>
> </html>                              
> ```

@sinothoma Have you found a solution to this problem ?

**Comment by bsweeney** [comment]
@parmarvishal21 Dompdf won't be able to handle that particular layout very well. The current code base does not support breaking an individual table cell/row across pages. The results you're getting are because Dompdf is trying to ensure that large table cell starts on a single page.

Follow #98 for updates on this issue.
