### ISSUE TITLE
When DOMPDF_ENABLE_FONTSUBSETTING = true, spaces width is too large

### ISSUE THREAD

**Issue by MrZver** [dompdf/dompdf#663]
I have some issue with DomPdf.
I'm use UTF-8 and font Times-Roman and when:
DOMPDF_ENABLE_FONTSUBSETTING = false
I have correct pdf view:
![correct_pdf](https://f.cloud.github.com/assets/4669362/636451/4fccec76-d283-11e2-8634-0670560e38c4.jpg)
but this pdf its too large and I'm use this for resolve problem:
DOMPDF_ENABLE_FONTSUBSETTING = true
Problem with size resolved, but I have new problem with view (i think spaces width is too large)
This is incorrect view:
![incorrect_pdf](https://f.cloud.github.com/assets/4669362/636462/cc38bad8-d283-11e2-9c7f-013239eccc39.jpg)
Please help resolve this problem.

**Comment by kamalsamra** [comment]
I am still facing this issue and my font file contain entry of space

**Comment by bsweeney** [comment]
@kamalsamra the UFM file contains the entry?

**Comment by kamalsamra** [comment]
Yes
