### ISSUE TITLE
Errors and warnings with dompdf while pdf creating with URL " ( ! ) Warning: DOMXPath::query() "

### ISSUE THREAD

**Issue by nk-nareshkumar** [dompdf/dompdf#668]
I am trying to create PDF of Google home page http://www.google.com and url http://code.google.com/p/dompdf/wiki/Installation.

But instead of PDF both url giving something getting wrong. Please guide me.
code 
code

    <?php
    
    	require_once("dompdf/dompdf_config.inc.php");
    	$content = file_get_contents('http://code.google.com/p/dompdf/wiki/Installation');
    	$dompdf = new DOMPDF();
    	$dompdf->load_html($content);
    	$dompdf->render();
    	$dompdf->stream("sample.pdf");
    
    ?>

and result facing with url **http://code.google.com/p/dompdf/wiki/Installation**

![2013-06-13 18-00-11](https://f.cloud.github.com/assets/2937132/648319/80afe38e-d427-11e2-9201-ff0b2d2e84b4.png)

and result facing with url **http://www.google.com**

![2013-06-13 18-01-59](https://f.cloud.github.com/assets/2937132/648324/9271f99a-d427-11e2-856a-f168692cb033.png)

**Comment by IreneArgolloDelgadillo** [comment]
i try to do this  :
 public function convertToPdfAction(Request $request, $id)
    {
        $options = new Options();
        $options->set('defaultFont', 'Courier');
        $dompdf = new Dompdf($options);
        $html = file_get_contents( $this->render('http://localhost:8000/test/') );
        $dompdf->loadHtml($html);

        $dompdf->setPaper('A4', 'landscape');
        $dompdf->render();
        $dompdf->stream();

    }

it doesnt work, this is the error:
Unable to find template "http:/www.google.com" (looked into: D:\web\ist\ExamenesEnLinea\tis\app/Resources/views, D:\web\ist\ExamenesEnLinea\tis\vendor\symfony\symfony\src\Symfony\Bridge\Twig/Resources/views/Form).
500 Internal Server Error - InvalidArgumentException
1 linked Exception: Twig_Error_Loader »

anyone know why?, please help me

**Comment by bsweeney** [comment]
@IreneArgolloDelgadillo this doesn't seem to be an issue with dompdf. That error is not one that would be thrown by dompdf. You might try checking that the page renders ok without converting to PDF first.

**Comment by Mathias-Wa-Mucani** [comment]
Hello geeks,

Has any of you guys encountered an error with dompdf when previewing the pdf file contents in the browser and lots of unformatted and unnecessary text are first printed then the actual content comes down? It works very fine on localhost but have now hosted the system on a live server and getting these kind of weird behavior shown in the pics. Thanks in advance please for any help......
![Screen Shot 2021-11-13 at 02 23 14](https://user-images.githubusercontent.com/60660749/141595220-20728526-b25d-4b5a-b2a8-79458d3c4dbf.png)
![Screen Shot 2021-11-13 at 02 22 47](https://user-images.githubusercontent.com/60660749/141595282-7ccfcaf8-a987-4023-9bd3-0d5f4538b8b8.png)

**Comment by bsweeney** [comment]
@Mathias-Wa-Mucani best to [start a new discussion](https://github.com/dompdf/dompdf/discussions/new) for questions of this nature. Definitely don't add unrelated comments to an existing issue.

I started a new discussion for you here: https://github.com/dompdf/dompdf/discussions/2639

**Comment by Mathias-Wa-Mucani** [comment]
I'm sorry for blundering that way! That issue has been boggling my mind....
thanks anyways

____________________
mathiaswamucani
