### ISSUE TITLE
Support numeric font weights

### ISSUE THREAD

**Issue by wowpages** [dompdf/dompdf#675]
Using Google Web Fonts works great, but I can't get the font-weight to work. If I add font-weight: bold or font-weight: 700 it works fine in HTML but reverts to the default font in dompdf.

`<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700,400italic' rel='stylesheet' type='text/css'>`

works fine in HTML and dompdf:  `font-family: 'QuattrocentoSans';`

works fine in HTML but NOT dompdf:   `font-family: 'QuattrocentoSans'; font-weight: bold;` or `font-family: 'QuattrocentoSans'; font-weight: 700;`

Is there a way to get the bold versions to work in dompdf?

**Comment by adammwood** [comment]
For anyone running into the limitation of only being able to define a 'normal' and 'bold' font weight, there is a simple workaround that essentially allows you to use any number of font weights and styles: **create additional font families for the additional weights**.

For example, we needed to use Open Sans at 300 (light), 400 (regular) and 600 (semi bold). To achieve this we just used 'Open Sans Light' at 'normal' for 300, 'Open Sans' at 'normal' for 400 and 'Open Sans' at 'bold' for 600.

The CSS (with local fonts) would look like this:

```
@font-face {
    font-family: 'Open Sans Light';
    src: url('/assets/fonts/opensans-light-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'Open Sans Light';
    src: url('/assets/fonts/opensans-lightitalic-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: italic;
}

@font-face {
    font-family: 'Open Sans';
    src: url('/assets/fonts/opensans-regular-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'Open Sans';
    src: url('/assets/fontsopensans-italic-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: italic;
}

@font-face {
    font-family: 'Open Sans';
    src: url('/assets/fonts/opensans-semibold-webfont.ttf') format('truetype');
    font-weight: bold;
    font-style: normal;
}

@font-face {
    font-family: 'Open Sans';
    src: url('/assets/fonts/opensans-semibolditalic-webfont.ttf') format('truetype');
    font-weight: bold;
    font-style: italic;
}
```

**Comment by bsweeney** [comment]
@adammwood nice, thanks for the reminder! You could also define more specific font families if you wanted to be able to display even more variations (e.g. Open Sans Light in normal, italic, and bold variants as well as Open Sans in normal, italic, and bold variants). The only issue is that you wouldn't get the same flexibility you get by being able to use numeric weight values.

**Comment by adammwood** [comment]
@bsweeney I might have phrased that confusingly, but we are essentially using numeric weight values, just in a way that dompdf can work with...

There's no such font family as 'Open Sans Light', it's just the 300 version of 'Open Sans'. So in the example above we're using Open Sans at:

300 normal & italic
400 normal & italic
600 normal & italic

... the only reason we're creating the 'Open Sans Light' family is to allow us to use a third weight in addition to normal (400) and bold (600). Yes, you're not able to write CSS font-weight declarations with numeric values, but you can easily work around that by defining the correct font-family and weight (normal or bold).

We could easily create another family of 'Open Sans Black' using the same method if we wanted to use 700 and 800 as well.

**Comment by adammwood** [comment]
An easier way of phrasing it, or as advice for anyone needing more than one font weight, is to just declare a new font family for every weight. 

So when you want to use this, which won't work with dompdf:

```
@font-face {
    font-family: 'Open Sans';
    src: url('/assets/fonts/opensans-light-webfont.ttf') format('truetype');
    font-weight: 300;
    font-style: normal;
}

@font-face {
    font-family: 'Open Sans';
    src: url('/assets/fonts/opensans-lightitalic-webfont.ttf') format('truetype');
    font-weight: 300;
    font-style: italic;
}

@font-face {
    font-family: 'Open Sans';
    src: url('/assets/fonts/opensans-regular-webfont.ttf') format('truetype');
    font-weight: 400;
    font-style: normal;
}

@font-face {
    font-family: 'Open Sans';
    src: url('/assets/fontsopensans-italic-webfont.ttf') format('truetype');
    font-weight: 400;
    font-style: italic;
}

@font-face {
    font-family: 'Open Sans';
    src: url('/assets/fonts/opensans-semibold-webfont.ttf') format('truetype');
    font-weight: 600;
    font-style: normal;
}

@font-face {
    font-family: 'Open Sans';
    src: url('/assets/fonts/opensans-semibolditalic-webfont.ttf') format('truetype');
    font-weight: 600;
    font-style: italic;
}
```

use this instead, which works fine as it can cache the styles for each font:

```
@font-face {
    font-family: 'Open Sans Light';
    src: url('/assets/fonts/opensans-light-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'Open Sans';
    src: url('/assets/fonts/opensans-lightitalic-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: italic;
}

@font-face {
    font-family: 'Open Sans Regular';
    src: url('/assets/fonts/opensans-regular-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'Open Sans Regular';
    src: url('/assets/fontsopensans-italic-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: italic;
}

@font-face {
    font-family: 'Open Sans Semi-Bold';
    src: url('/assets/fonts/opensans-semibold-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'Open Sans Semi-Bold';
    src: url('/assets/fonts/opensans-semibolditalic-webfont.ttf') format('truetype');
    font-weight: normal;
    font-style: italic;
}
```

You just need to make some changes to your CSS then to adapt to this. So, if you wanted your bold styling to use 'Open Sans Semi-Bold', just declare:

```
strong,
b {
    font-family: 'Open Sans Semi-Bold', sans-serif;
    font-weight: normal;
}

```

**Comment by bsweeney** [comment]
@adammwood I think the confusing phrasing is on my part. We're pretty much talking about the same thing. As you noted font family name in the `@font-face` declaration doesn't really matter. You could just as easily name the font families "Open Sans 300", "Open Sans 400", etc.

Thanks again for detailing the work-around until we add support.

**Comment by honsa** [comment]
still open? 
would make it much more comfortable to use with numeric font-weight values.

**Comment by lquast** [comment]
https://github.com/dompdf/dompdf/pull/1896
