### ISSUE TITLE
Cellmap->get_spanned_cells: "Frame not found in cellmap" when rowspanned table spans to the next page

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#68]
_Original author: anatoli...@gmail.com (September 03, 2009 20:30:09)_

<b>What steps will reproduce the problem?</b>
1. rowpanned table that doesn't feet to one page

<b>What is the expected output? What do you see instead?</b>

If I change the font size of the cells content for the table to feed in 
one page, no error occurs. If it's expected to span to the next page, the 
error occurs.

<b>What version of the product are you using? On what operating system?</b>

The trunk version svned on Sept 03, 2009. x86_64 GNU/Linux.

<b>Please provide any additional information below.</b>

This error existed in the 0.5.1 version as well.

Stack trace:

```
#0 /home/.../dompdf/include/table_cell_renderer.cls.php(74): Cellmap-
&gt;get_spanned_cells(Object(Table_Cell_Frame_Decorator))
#1 /home/.../dompdf/include/renderer.cls.php(222): Table_Cell_Renderer-
&gt;render(Object(Table_Cell_Frame_Decorator))
#2 /home/.../dompdf/include/renderer.cls.php(110): Renderer-&gt;_render_frame
('table-cell', Object(Table_Cell_Frame_Decorator))
#3 /home/.../dompdf/include/renderer.cls.php(143): Renderer-&gt;render(Object
(Table_Cell_Frame_Decorator))
#4 /home/.../dompdf/include/renderer.cls.php(143): Renderer-&gt;render(Object
(Table_Row_Frame_Decorator))
#5 /home/.../dompdf/include/renderer.cls.php(143): Renderer-&gt;render(Object
(Table_Frame_Decorator))
#6 /home/.../dompdf/include/renderer.cls.php(143): Renderer-&gt;render(Object
(Block_Frame_Decorator))
#7 /home/.../dompdf/include/page_frame_reflower.cls.php(103): Renderer-
&gt;render(Object(Block_Frame_Decorator))
#8 /home/.../dompdf/include/frame_decorator.cls.php(388): 
Page_Frame_Reflower-&gt;reflow()
#9 /home/.../dompdf/include/dompdf.cls.php(509): Frame_Decorator-&gt;reflow()
#10 /home/.../file.php(26): DOMPDF-&gt;render()
#11 {main}
  thrown in /home/.../dompdf/include/cellmap.cls.php on line 224
```

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=61_

**Comment by blerin27** [comment]
I have been facing the same problem for days, in a huge table with rowspan and colspan, but no _border-collapse:collapse_

I have resolved it by adding this to the style of my table element:

    table
    {
       border-collapse:unset;   
    }

Hope it helps!

**Comment by MarcosBL** [comment]
@blerin27 thanks ! That fixed it for me as well

**Comment by faisalbahadur** [comment]
add    <span style="page-break-after:always;"></span> after your code

**Comment by bsweeney** [comment]
I don't believe there is an issue with Dompdf crashing in this situation anymore (though there is still work to do to better support rowspan across pages).
