### ISSUE TITLE
PDF won't save when encryption is used

### ISSUE THREAD

**Issue by mga242** [dompdf/dompdf#707]
When using encryption:

$dompdf->get_canvas()->get_cpdf()->setEncryption('', 'password', array('print'));

If you open the pdf and use file->save as->pdf it gives the error "The document could not be saved. There was a problem reading this document (135)."

If you right click on the pdf, save as works fine. Also, not using setEncryption you can use file->save as->pdf with no problem.

I tried adding save to the array('print','save') but no luck. Anybody know of a fix?

**Comment by bsweeney** [comment]
Still a problem in the final release?

**Comment by georgerujoiu2017** [comment]
This is still an issue in version 1.0.2
