### ISSUE TITLE
Large UL list breaks layout

### ISSUE THREAD

**Issue by ruudboy** [dompdf/dompdf#709]
I have a large ul list and it breaks at the end of the page.
It is also not continuing on the next page.
Because of this problem i also have 50 white pages before the ul list page.

![ullist](https://f.cloud.github.com/assets/5371622/1071691/7741a568-147c-11e3-9c47-2a649f4d566f.png)

The css code i use is:

```
@page { margin-top: 0px; margin-left: 0px; margin-bottom: 0px; }
```

**Comment by bsweeney** [comment]
Been a while, is this still an issue with the current release?

I tried a long unordered list (3 pages worth) and it didn't seem to have any ill affect. If this is still a problem can you provide more details?
