### ISSUE TITLE
page break double increments a counter

### ISSUE THREAD

**Issue by nrwiersma** [dompdf/dompdf#710]
Hi,

It seems that if you have a page-break inside a class that increments a counter, it will increment the counter again while not updating the displayed values. You can see this issue if you use the same counter on a div and ol li and span the div across a page-break and use div { page-break-inside: avoid }. The result looks like:

```
1. Duties
  1.1 Blah Blah
  --- Page would break here but the whole thing is moved to new page ---
  2.2 Blah Blah
  2.3 Blah Blah
```

In this case you should be incrementing on the header and the li using the same counter. It seems that by moving the header, it re-increments the counter.

Thanks

**Comment by tamaghna91** [comment]
I have a problem again @bsweeney. On page changes, second page gap from top and content become doubled and it increases further.Any help??

**Comment by bsweeney** [comment]
@tamaghna91 this is probably an unrelated issue, though it sounds familiar. Can you start a new discussion with a sample of the HTML on the [support forum](http://groups.google.com/group/dompdf)?

**Comment by tamaghna91** [comment]
@bsweeney,I myself managed to fix the problem,but not satisfied as it doesn't meet the coding standard btw thanks for your help.

**Comment by bsweeney** [comment]
@tamaghna91 if you've found a bug feel free to start a new issue. If you need any guidance or have any questions feel free to post to the support forum.
