### ISSUE TITLE
Print a generated pdf via embedded javascript

### ISSUE THREAD

**Issue by jameswilson** [dompdf/dompdf#713]
It appears that it may be technically possible to embed some javascript inside the generated pdf that could automatically load the pdf viewer's print dialog upon load.

Is there any way to embed javascript into the pdf with DOMPDF, or can this only be done if you have implemented your own web-based PDF Viewer?

References:
- http://stackoverflow.com/questions/6167995/generate-a-pdf-that-automatically-prints
- http://stackoverflow.com/questions/8733276/how-to-open-print-dialog-after-pdf-generated

**Comment by aminemrabet** [comment]
To make it work, you need to use this JS bloc inside your PDF Blade : 

`<script type="text/javascript">
            try {
                this.print();
            } catch (e) {
                window.onload = window.print;
            }
</script>`

I hope it helps !

**Comment by chaitaliTej** [comment]
Thank you 
<script type="text/javascript"> try { this.print(); } catch (e) { window.onload = window.print; } </script> this script working fine

**Comment by chaitaliTej** [comment]
Thank you that script was working fine

**Comment by JesustheLord** [comment]
Thank you so much. Worked for me too.

**Comment by ShekhSaifuddin007** [comment]
`<script type="text/javascript"> try { this.print(); } catch (e) { window.onload = window.print; } </script>`
this line go directly in print window but I have other script for showing total amount in words but this pdf generator totally skip those lines. What should I do..??

**Comment by ShekhSaifuddin007** [comment]
`<script type="text/javascript"> try { this.print(); } catch (e) { window.onload = window.print; } </script>`
this line go directly in print window but I have other script for showing total amount in words but this pdf generator totally skip those lines. What should I do..??
