### ISSUE TITLE
Footer not shown on first page when not rendered in front of the other page content

### ISSUE THREAD

**Issue by ntarandek** [dompdf/dompdf#715]
If I have elements ordered like this HEADER - FOOTER - CONTENT then both header and footer are shown correctly on each page.

But since I need some data in footer which is collected during CONTENT generation, I changed the order to HEADER - CONTENT - FOOTER which in fact seems logical. But then there is a problem - footer isn't shown on the first page! If I move it up it's shown again, but it has no data it needs. I know, I could prepare the data before processing the HEADER/FOOTER but there are other considerations that prevent me to do that :(

One important note, I'm using 0.6.0 beta 3 and HTML/CSS based footers (no direct PHP processing).

Is there any solution for this so I can keep my "logical" order of elements?

Thank you.

**Comment by bsweeney** [comment]
related to #491
