### ISSUE TITLE
Font leading issues

### ISSUE THREAD

**Issue by thenissengroup** [dompdf/dompdf#729]
Hi, when I use DOMPDF to generate a PDF using an HTML file, the fonts always are slightly off vertically.  When I run the same exact HTML through a 3rd party service like PDFcrowd, their PDF matches the HTML perfectly.  Do I have something configured incorrectly like the font aspect ratio and/or DPI?  Thanks,

-Jay

![image](https://f.cloud.github.com/assets/5713069/1355759/6c417496-376c-11e3-8c67-847259475116.png)

![image](https://f.cloud.github.com/assets/5713069/1355760/77a2559e-376c-11e3-8a49-21582c32ef61.png)

**Comment by bsweeney** [comment]
Since we do not have sample HTML against which to test I'm closing this issue.

Note that vertical alignment will be much improved with the upcoming release.
