### ISSUE TITLE
unreadable meta tags when using protection

### ISSUE THREAD

**Issue by osworx** [dompdf/dompdf#732]
Hello,

I am using the latest 0.6.0-b3 version.
The case:

A. generating a pdf with the standard value works perfectly, also meta tags like

````<meta name="author" content="author here" />````
````<meta name="description" content="description here" />````

B. as A but now with protection using

````$dompdf->get_canvas()->get_cpdf()->setEncryption( '', '', array( 'print' ) );````

results in unreadable meta tags like:
>¥ÔıhoÎ here

and

>¥ÔıcrÎptionùłer¿

The pdf itself is working in both cases.
The meta tags have to be valid and readable, because they are invoices where tags like that are important.
And the protection also working on both cases.

![dompdf_meta_tags](https://f.cloud.github.com/assets/1905204/1460781/db9378c0-446f-11e3-97db-49e6c008fd11.png)

**Comment by bsweeney** [comment]
I believe this has been addressed in the final release.
