### ISSUE TITLE
Absolute paths do not work in conjunction with base_path

### ISSUE THREAD

**Issue by bertptrs** [dompdf/dompdf#739]
For some project, I render a preview invoice to html, and use dompdf to render it to PDF. The idea is that the preview URL supplies a valid html page and that the output of that URL can be rendered.

Unfortunately, it doesn't. Base URL works for referencing external files as long as they're relative paths. In this case, this results in the following workaround:

``` html
<!-- Expected URL, valid for direct viewing -->
<link rel="stylesheet" href="/assets/css/factuur.css" type="text/css">
<!-- URL neccesary for DOMPDF to find the file -->
<link rel="stylesheet" href="assets/css/factuur.css" type="text/css">
```

This is unexpected behavior and an ugly workaround. Can this be fixed?
- PHP version: PHP 5.5.3-1ubuntu2 (cli)
- DOMPDF: installed using composer, master branch.

**Comment by dedius** [comment]
The only working solution for me was to add `<base href="http://example.com/HTML/file/path">` in html head, and to set `$options->set('isRemoteEnabled', TRUE);`
