### ISSUE TITLE
Suggestion for namespace implementation

### ISSUE THREAD

**Issue by SplicePHP** [dompdf/dompdf#740]
I just figured out a way you can implement namespaces while keeping legacy support.

I love the library and would like to see namespaces implemented.

I stumbled across this while trying to create global aliases.

You create the project to psr-0 standards.
Then create a include dir next to your root namespace.
In the include dir you extend the namespaced classes with regular classes.

You load it like this in composer:

```
//With legacy support:
"autoload": {
    "psr-0": {
        "RootNamespace\\": "."
    },
    "classmap": ["include/"]
}
```

```
//New project:
"autoload": {
    "psr-0": {
        "RootNamespace\\": "."
    }
}
```

This still assumes php 5.3 but I think support for 5.2 can be dropped by now.

For a mor comprehensive explanation go to this url.

http://stackoverflow.com/questions/19890310/php-global-namespace-aliases

**Comment by bsweeney** [comment]
Looks like we've got this covered with the current state of the develop branch. Way too many commits to cite (since I wasn't keep track :disappointed: ). The changes were authored by @gabrielbull, @PhenX, @barryvdh (with a little clean up by me).
