### ISSUE TITLE
@page :odd / :even backgrounds hack

### ISSUE THREAD

**Issue by ruudk** [dompdf/dompdf#741]
I used this ugly hack to get it an odd/even background working. Now you can set `@page :odd { background: url() }` and it will overwrite the body every time it's an odd page.

Maybe somebody can use this or use it as a base for a PR.

``` patch
diff --git a/dompdf/include/page_frame_reflower.cls.php b/dompdf/include/page_frame_reflower.cls.php
index b6793f3d021650454908716d0a453c1b9fa8eb05..19351f947a483e8019ee70738897824660006ef9 100644
--- a/dompdf/include/page_frame_reflower.cls.php
+++ b/dompdf/include/page_frame_reflower.cls.php
@@ -46,37 +46,47 @@ class Page_Frame_Reflower extends Frame_Reflower {
     $this->_stacking_context[$z_index][] = $frame;
   }

-  function apply_page_style(Frame $frame, $page_number){
+  function apply_page_style(Frame $frame, $page_number, Frame $child){
     $style = $frame->get_style();
     $page_styles = $style->get_stylesheet()->get_page_styles();

     // http://www.w3.org/TR/CSS21/page.html#page-selectors
     if ( count($page_styles) > 1 ) {
       $odd   = $page_number % 2 == 1;
       $first = $page_number == 1;

       $style = clone $page_styles["base"];

       // FIXME RTL
       if ( $odd && isset($page_styles[":right"]) ) {
         $style->merge($page_styles[":right"]);
+
+        $child->get_style()->merge($page_styles[":right"]);
       }

       if ( $odd && isset($page_styles[":odd"]) ) {
         $style->merge($page_styles[":odd"]);
+
+        $child->get_style()->merge($page_styles[":odd"]);
       }

       // FIXME RTL
       if ( !$odd && isset($page_styles[":left"]) ) {
         $style->merge($page_styles[":left"]);
+
+        $child->get_style()->merge($page_styles[":left"]);
       }

       if ( !$odd && isset($page_styles[":even"]) ) {
         $style->merge($page_styles[":even"]);
+
+        $child->get_style()->merge($page_styles[":even"]);
       }

       if ( $first && isset($page_styles[":first"]) ) {
         $style->merge($page_styles[":first"]);
+
+        $child->get_style()->merge($page_styles[":first"]);
       }

       $frame->set_style($style);
@@ -96,7 +106,7 @@ class Page_Frame_Reflower extends Frame_Reflower {
     $current_page = 0;

     while ($child) {
-      $this->apply_page_style($this->_frame, $current_page + 1);
+      $this->apply_page_style($this->_frame, $current_page + 1, $child);

       $style = $this->_frame->get_style();

```

**Comment by ReneFroger** [comment]
Thanks for your contribution. But how does this work? 

I added the differences to page_frame_reflower.cls.php, then in the `<head>` between the `<style>` tags: 

            `@page :odd { background-color: #808000 ; }`

But I see no change on odd page's.

**Comment by bsweeney** [comment]
It may be out of date with regard to the current code but this does give us something to think about. This is definitely an interesting idea.

**Comment by ruudk** [comment]
Why keep stuff open for so long? There is no value in having things on a list when it's not being worked out. That why I closed it. I don't want this in my list of issues.

**Comment by bsweeney** [comment]
Were this a business I would agree with you. Not much point in leaving issues open for extended periods. Typically that means there's no business interest in addressing it. But this project is not maintained as part of a business strategy. Nobody works on the project full time and so things tend to be addressed as the volunteers working on it have time. And issues that point out valid problems or enhancements are worth keeping open until we're sure the issue is addressed.

Still, your point is taken. I opened a new issue for this enhancement (#1572).
