### ISSUE TITLE
Negative CSS padding is allowed

### ISSUE THREAD

**Issue by KaeruCT** [dompdf/dompdf#742]
I don't really see this as a bug, but I think it does not conform to the CSS spec.

HTML used

```
<html>
<head>
<style type="text/css">
#positive {
    padding: 20px;
    border: #00f 1px solid;
}
#negative {
    padding: -20px;
    border: #f00 1px solid;
}
</style>
</head>
<body>
    <div id="positive">
        positive padding
    </div>
    <div id="negative">
        negative padding
    </div>
</body>
</html>
```

Here's how it renders on my web browser (Chromium):
![html](https://f.cloud.github.com/assets/1018253/1544641/fd87f62e-4d69-11e3-9e80-6b5a7b511e97.png)

Here's how dompdf renders it:
![pdf](https://f.cloud.github.com/assets/1018253/1544642/fd8cc7b2-4d69-11e3-872c-d70738d61e2b.png)

This is happening on the master branch.
PHP version used:

```
PHP 5.5.3-1ubuntu2 (cli) (built: Oct  9 2013 14:49:12) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2013 Zend Technologies
    with Zend OPcache v7.0.3-dev, Copyright (c) 1999-2013, by Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans
```

**Comment by Mellthas** [comment]
This has been addressed at some point, negative padding is not applied anymore.
