### ISSUE TITLE
feature request: page break hooks before/after

### ISSUE THREAD

**Issue by quantumJLBass** [dompdf/dompdf#757]
Hello, I have been working with this for the last few days trying to match up a document but I keep having to do all these work arounds that would be much easy if there was a callback to a function right before the page break or right after.  I need a better solution to getting an html footer but not use css count for the number. Maybe the callback passes in the html for that page?  There could be more hooks that would be helpful here too.

With the before/after callbacks I could solve Bookmarking, table of contents, numbering and all kinds of other things that I have been having to write workarounds for.  Thank you for the time.

**Comment by bsweeney** [comment]
As long as I've maintained this project I've almost never dealt with them. But I was recently reminded that dompdf does indeed have callback support. See #1424. Now I just need to add some documentation.

**Comment by bsweeney** [comment]
[Documentation on callbacks is available in the wiki.](https://github.com/dompdf/dompdf/wiki/Usage#callbacks) I should also note that page count can be adjusted via CSS. Total page is still something that needs to be handled outside of the HTML/CSS.
