### ISSUE TITLE
Less Than symbol problem

### ISSUE THREAD

**Issue by domenicogioia** [dompdf/dompdf#763]
If I try to generate this document:

``` html
<html><head></head>
<body> ciao < 4 </body>
</html>
```

I aspect to see in pdf "ciao < 4" but in the final pdf I see only ciao
![schermata 2014-01-12 alle 12 38 30](https://f.cloud.github.com/assets/2702471/1896094/1d016688-7b7e-11e3-9db7-b11d34d90643.png)
![schermata 2014-01-12 alle 12 38 22](https://f.cloud.github.com/assets/2702471/1896095/1d17b668-7b7e-11e3-8b29-0afd1cd9168e.png)

**Comment by zonky2** [comment]
in newer version use `$options->set('isHtml5ParserEnabled', true);`
