### ISSUE TITLE
ErrorException DOMXPath::query(): Invalid expression

### ISSUE THREAD

**Issue by adamgoose** [dompdf/dompdf#764]
When attempting to generate a PDF based on Twitter Bootstrap, I receive the following error:

```
ErrorException
DOMXPath::query(): Invalid expression
```

on `/vagrant/vendor/dompdf/dompdf/include/stylesheet.cls.php` line [853](https://github.com/dompdf/dompdf/blob/master/include/stylesheet.cls.php#L853).

I have modified the code as follows for debug purposes:

```
  try {
    $nodes = @$xp->query($query["query"]);
  } catch (\Exception $e) {
    dd($query["query"]); // die and dump value
  }
```

And received the following output:

```
string '//descendant::button*' (length=21)
```

The output of the HTML send into the dompdf can be found here: [gist](https://gist.github.com/adamgoose/8405536). As far as I'm aware, the bootstrap file has not been manipulated from its designated version (2.3.1). Pulling in v2.3.1 from bootstrap CDN produces the same error. There are not other stylesheets being applied to the document.

**Comment by DerDu** [comment]
This issue still exists if i do this in css

    svg:not(:root) {
        overflow: hidden;
    }
