### ISSUE TITLE
Enhance remote font / webfont caching

### ISSUE THREAD

**Issue by Spreeuw** [dompdf/dompdf#774]
I have an issue with displaying special characters (Č or č in this specific case) when using a google font.

I include the remote font in the html header like this:

``` html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link href='http://fonts.googleapis.com/css?family=Open+Sans&subset=latin,latin-ext,cyrillic,cyrillic-ext' rel='stylesheet' type='text/css'>
```

Then I define this font in the CSS:

``` css
body {
    font-family: 'Open Sans', sans-serif;
    font-size: 9pt;
}
```

This version of Open Sans (note the subset definition in the url) supports a very wide range of special characters, including the two characters I mentioned above. It renders fine in the browser, but doesn't display in the PDF. Is this known behavior, or is there a setting I am missing?

Note that these characters are rendering fine when I set the font to DejaVu Sans.

**Comment by jimi007** [comment]
Thanks for the details on this issue. I was struggling few hours to get text in custom font but failed and finally this method helps. "font-weight: normal" and "&subset=latin,latin-ext" caused to displayed custom font in PDF.
