### ISSUE TITLE
Input field values not rendering

### ISSUE THREAD

**Issue by fusionPT** [dompdf/dompdf#778]
The input field values are not rendering.

**Comment by ripunjoy-sarma** [comment]
iam using html table and having inline php ..but when i am going to generate dompdf it is unable to show the php database value...i hv gone through all setting of dompdf..and file get contents and curl method also....plz help me i stucked at this position....i am using laravel framework..here is my coding

//$htmlContent = \View::make('Certificate-Diploma.print')->with('data',$data);
        $htmlContent= view('Certificate-Diploma.print', compact('data','$data','message','subject','mailAttachment'));
	
	
        // pdf file params
        $fileName = $fileName;
        $filePath = './storage/';
        // generate the pdf file
        \PDF::loadHTML($htmlContent)
        ->setPaper('a4')
        ->setOrientation('portrait')
        ->save($filePath.$fileName);

**Comment by bsweeney** [comment]
@ripunjoy-sarma to get help with your issue post your question to the [support forum](http://groups.google.com/group/dompdf) or to [StackOverflow](http://stackoverflow.com/questions/tagged/dompdf)
