### ISSUE TITLE
Issues with Google fonts loading

### ISSUE THREAD

**Issue by jonlambert** [dompdf/dompdf#784]
I'm having issues loading fonts into the page. When rendering this markup in a browser, it works fine. Rendering it using dompdf... The fonts don't work at all.

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-15">
<link href='http://fonts.googleapis.com/css?family=Give+You+Glory&v2' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Wallpoet&v2' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister&v2' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro&v2' rel='stylesheet' type='text/css'>
<style type="text/css">
    body {
        font-family: sans-serif;
        font-family: 'Source Sans Pro';
    }
    p {
        font-size: 2em;
        background: #eee;
        padding: 1em;
    }

    h2 {
        color: #999;
    }
</style>
</head>
<body>

<h2>Give You Glory</h2>
<p style="font-family: 'Source Sans Pro', sans-serif;">
  Grumpy wizards make toxic brew for the evil Queen and Jack
</p>

<h2>Wallpoet</h2>
<p style="font-family: 'Wallpoet', sans-serif;">
  Grumpy wizards make toxic brew for the evil Queen and Jack
</p>

<h2>Love Ya Like A Sister</h2>
<p style="font-family: 'Love Ya Like A Sister', sans-serif;">
  Grumpy wizards make toxic brew for the evil Queen and Jack
</p>

</body>
</html>
```

**Comment by jpswade** [comment]
The issue with the h1 tag also appears to affect the font-size, as in, it is not registered.

**Comment by perfectsenseab** [comment]
We also confirm that it works on <P> tags but not on <H1> tags.

**Comment by perfectsenseab** [comment]
We also confirm that it works on P tags but not on H1 tags.

**Comment by MatKershaw** [comment]
Confirm the issue is due to the font weight - if you change font-weight of h1 to normal it renders as custom font.

**Comment by Hammad51** [comment]
Too late to comment on the issue, but experienced the same issue while working with dompdf. I was loading fonts from google like 
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
but domPDF was not generating the pdf instead was throwing error, so what i did to fix it, i comment out these 2 lines in dompdf.php, not sure it's the right way to fix the issue but for my case it worked just fine (using dompdf with Laravel 5)
"DOMPDF_FONT_DIR" => storage_path('fonts/')
"DOMPDF_FONT_CACHE" => storage_path('fonts/')

might be help full for someone experiencing same issue

**Comment by ksvendsen** [comment]
@Hammad51 
You have to create the directory in laravel at `storage/fonts` then it works.

**Comment by Hammad51** [comment]
@ksvendsen yes you are right, I had to create storage/fonts dir to fix the issue the solution i wrote earlier was not wise and shouldn't adopted, forget to update the thread.. Thanks for your comment :)

**Comment by tristanbailey** [comment]
Fonts from Google as TTF if you are not using a major browser was a good tip:  
On the cli was one simple way to skip the browser  
wget https://fonts.googleapis.com/css?family=Open+Sans:400,700,300

**Comment by ashrafsaqib** [comment]
I found using 

`<link href="https://fonts.googleapis.com/css?family=Tinos" rel="stylesheet">`

will make css 
`background image: url();`
Stop working 

So I opened the Google Font CSS file and extracted the actual @font-face property by help of chrome dev tool.

Now using this made backgrounds work again


   ```
@font-face {
          font-family: 'Tinos';
          font-style: normal;
          font-weight: 400;
          src: local('Tinos Regular'), local('Tinos-Regular'), url(https://fonts.gstatic.com/s/tinos/v11/buE4poGnedXvwjX7fmQ.woff2) format('woff2');
        }
        body {
            font-family: 'Tinos', serif;
        }
```

instead of 

`<link href="https://fonts.googleapis.com/css?family=Tinos" rel="stylesheet">`

**Comment by Sharifur** [comment]
> @Hammad51
> You have to create the directory in laravel at `storage/fonts` then it works.

thanks you so much.
