### ISSUE TITLE
Arabic support

### ISSUE THREAD

**Issue by tareq-halaby** [dompdf/dompdf#785]
Hello, there's a problem withe the arabic support in DomPDF

Any help?

![29qlp 1](https://f.cloud.github.com/assets/1264607/2177895/a371f550-9647-11e3-9d54-524c90e2599d.png)

**Comment by Kalmuraee** [comment]
Issue

**Comment by truthglow** [comment]
any news please about this issue, I am suffering the same thing here?

**Comment by bsweeney** [comment]
@truthglow sorry, nothing yet. Have you tried the suggestions in #712?

**Comment by truthglow** [comment]
wow, more than one year and no utf8 (unicode) :( 
but it's something to be added for inter-nationality

**Comment by bsweeney** [comment]
@truthglow that's not exactly true. We have UTF8/Unicode support. That's mainly a character encoding issue.

What we still need to work out is how to accurately render the character to PDF. Individual characters seem to be fine, it's just that combined characters are not.

Then on top of that we'll need to add RTL support.

**Comment by bsweeney** [comment]
Closing this issue. Watch #712 for updates related to supporting Arabic glyphs better and #1009 for RTL support.
