### ISSUE TITLE
Make whole project PSR-* compliant

### ISSUE THREAD

**Issue by gabrielbull** [dompdf/dompdf#790]
Using industry standard instead of project specific standards is best practice.

Started work on this with PR #788 

TODO:

- [x] Implement namespace
- [x] Rename ``include`` directory to ``src`` directory

**Comment by beporter** [comment]
I should really have posted this here: https://github.com/dompdf/dompdf/pull/788#issuecomment-125985214

**Comment by bsweeney** [comment]
Check out the develop branch, it should have everything you need. With luck we'll wrap up development on that release in the near future, merge back into master, and quickly follow up with a final release.

I've been thinking of how to better delineate the project's needs and how the community can help. Feel free to offer any suggestions.
