### ISSUE TITLE
Default line-heights (?)

### ISSUE THREAD

**Issue by Spreeuw** [dompdf/dompdf#792]
The following HTML behaves somewhat unexpected:

``` html
<tbody>
        <tr>
            <td>Cell content with <i>italic</i> text</td>
            <td><span>Cell content with <i>italic</i> text</span></td>
        </tr>
</tbody>
```

In the first cell, the italic text is printed slightly lower than the other text in that cell.
In the second cell, everything is printed on one line.

I have no special declarations for `<i>` or `<span>` in the css of this document, so I was wondering if theres an inconsistency in line-heights? I tried resetting padding and margins of the `<i>` element but that didn't do anything. Then I set the document line-height (also not set anywhere in the css) and everything was aligned.

**Comment by bsweeney** [comment]
The alignment issue here appears to have been addressed.
