### ISSUE TITLE
Rowspan is not working while page breaks in 0.6.0 beta3 Dompdf

### ISSUE THREAD

**Issue by jangya** [dompdf/dompdf#812]
hii,here is dompdf 0.6.0 beta3 and it seems like while pages break it just lost the information about the rowspan attribute and sometimes it is not able to generate even.
And here is the HTML source that should be fixed.

**Comment by bsweeney** [comment]
This is pretty stale. While I think maybe the issue is still relevant there's not enough detail here to know for sure. If you have more details and have confirmed this is still an issue on 0.7.x please let us know.
