### ISSUE TITLE
Line-height not the same in HTML and PDF

### ISSUE THREAD

**Issue by jhice** [dompdf/dompdf#814]
Hi,
First, thanks for you great lib.

It seems that the line-height of the typo is not the same by default, look at these two samples :

HTML
![image](https://cloud.githubusercontent.com/assets/3470143/2658560/f8c6dc1e-c009-11e3-9fa6-b8cad7b70776.png)

PDF
![image](https://cloud.githubusercontent.com/assets/3470143/2658589/43daad34-c00a-11e3-87be-1225a2d2fdeb.png)

Even if we force a line-height in the CSS, it will not be the same once rendered ind PDF. And it differs from font to font.

I've tried to patch the space between blocks or frames to reduce them, but after browsing and following much part of the code I dont find where this value is set (much hours spent on that...).

I tried the DOMPDF_FONT_HEIGHT_RATIO but it does not act the same depending on the font, and it does get up the blocks a little.

Ideally I want to reduce the height of the blocks or the space between the blocks, wich corresponds to "line-height", even by patching the code if no other solution.

Thanks.

**Comment by charanjit-singh** [comment]
same issue

**Comment by bsweeney** [comment]
@charanjit-singh this is an older issue and it doesn't have any details we can use to determine what is happening so I'm going to close it. Feel free to open a new issue with more details.
