### ISSUE TITLE
Last line of paragraph next to a floated image

### ISSUE THREAD

**Issue by sffetlio** [dompdf/dompdf#821]
Hello, I noticed one bug. I have several paragraphs and a image that has float: left

Everything works great, the only problem is that the last line of each paragraph that is next the the image is not displayed correctly. It begins from the beginning of the row, instead of next to the image. I can select the text through the image.
![capture](https://cloud.githubusercontent.com/assets/3785861/2892153/cb6eac98-d539-11e3-8a82-a7bf275cff7f.JPG)

The html is simple:

```
<p> We insist the installation is done in such ... <img src="images/image002.jpg" style="width: 380px; height: 460px" class="floatLeft"/> We believe our reputation ... </p>
<p>Once the season is over... </p>
<p>... </p>
```

I use dompdf-0.6.1

```
define('DOMPDF_ENABLE_CSS_FLOAT', true);
define('DOMPDF_ENABLE_REMOTE', true);
define('DOMPDF_ENABLE_HTML5PARSER', true);
define('DOMPDF_FONT_HEIGHT_RATIO', 1);
```

**Comment by bsweeney** [comment]
I know your post is a bit old, but I can't quite reproduce the issue. If you're still around do you have a complete example of the HTML+CSS that was causing the problem?

**Comment by sffetlio** [comment]
Sorry, I can't give you a complete example, the document is really big. I looked through the html and last time I forgot to mention that the <p> tags have "text-align: justify;". Maybe this could help you. And it only happens if the image is long enough so there are more than 1 paragraphs next to it.

**Comment by bsweeney** [comment]
That was it, thanks.
