### ISSUE TITLE
Generated PDF -> Download breaks on last bits -> "The network connection was lost"

### ISSUE THREAD

**Issue by stzoho** [dompdf/dompdf#826]
Hi everyone…

strange thing happens…

I built a lightroom for a photographer. You are able to select images and then hit "download" to get the pdf file. Used to work perfect.
But now, when I hit the download button, the download starts and then breaks on the last bits and i get the note "The network connection was lost"… (on Safari)
Tried a few other browsers… same thing.

I have absolutely no clue.

Thanks for any help or hints.

**Comment by jespermartinez** [comment]
I have the same #issue can anyone help me out how to fix it?

**Comment by bsweeney** [comment]
@jespermartinez not without more details.

**Comment by Rosso2050** [comment]
it works for me ...
sudo chmod -R 777 /tmp
