### ISSUE TITLE
[NFR] Import / Merge pdf

### ISSUE THREAD

**Issue by ruudboon** [dompdf/dompdf#828]
I would be great if I can use an existing pdf as a base for a new page. I would like to import a pdf with vectors (logo etc) and then overlay it with data from my application.

**Comment by bsweeney** [comment]
Unlikely to do this because of the complexities of implementation for the CPDF library. There are other projects (FPDF+FPDI) that can help.

If you're using PDFLib someone's talking about using a custom adapter to do this, see #2069.
