### ISSUE TITLE
DOMPDF not rendering unicode fonts character as it is

### ISSUE THREAD

**Issue by logindian** [dompdf/dompdf#838]
I used http://eclecticgeek.com/dompdf/load_font.php to generate Unicode TAMIL language font(latha by microsoft font) .I have copied the fonts into respective folders.

But I see the fonts are not printing as it is.

My code:

``` html
<p style="font-family: tamil-latha, verdana, sans-serif;" >தமிழ்</p>
```

But what is printed in PDF is :
![untitled](https://cloud.githubusercontent.com/assets/6823934/3415977/79ffc484-fe27-11e3-90b0-672f9ade6353.png)

Both the values are not Same. There is some box is coming near the font and a dot on last character is missing..
Font Link : http://font.downloadatoz.com/font,6907,latha.html

Note: I have also added newly created font into dompdf_font_family_cache.dist.php

``` php
'tamil-latha' => 
  array (
    'normal' => DOMPDF_FONT_DIR . 'latha',
    'bold' => DOMPDF_FONT_DIR . 'latha',
    'italic' => DOMPDF_FONT_DIR . 'latha',
    'bold_italic' => DOMPDF_FONT_DIR . 'latha',
  ),
```

Kindly suggest me how should i get the Unicode fonts as similar to original fonts.

**Comment by moeseth** [comment]
@bsweeney Hi, can you help me debug this? http://eclecticgeek.com/dompdf/debug.php?identifier=45261abdcca702deb6c11cd11dd6c2df

**Comment by bsweeney** [comment]
@moeseth you should start a new discussion on the support forum to work through any problems you're having. Unless you can definitively identify a problem with the solution for a closed issue that is.

That being said, the format specifier in your `@font-face` declaration should be "truetype" and not "ttf" (a mistake I often make myself).

**Comment by ikhan009** [comment]
> @moeseth you should start a new discussion on the [support forum](http://groups.google.com/group/dompdf) to work through any problems you're having. Unless you can definitively identify a problem with the solution for a closed issue that is.
> 
> That being said, the format specifier in your `@font-face` declaration should be "truetype" and not "ttf" (a mistake I often make myself).

how to show the Urdu alphabet in my PDF file and how to add the Urdu alphabet Unicode .
in my page urdu font not show

**Comment by palistha01** [comment]
I have a problem with the character encoding UTF-8.I want to generate pdf which supports Nepali language. I want to fetch data from database which is in Nepali language and display in pdf .

test.php

<?php
$html = '
  <html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <style>
    @font-face {
      font-family: latha;
      font-style: normal;
      font-weight: 400;
      src: url("D:\OrangeHRM\3.3.1\htdocs\test\fonts\CODE2000.TTF") format("true-type");
    }
    </style>
  </head>
  <body>
    Word Details<br/>
    <div style="float:left;width:96%">
    <table border="0" width="100%">
      <tr>
        <th>English Word : </th>
        <td><input type="text" name="enhlish" value="'."भिम कुमारी भट्ट".'"/></td>
      </tr>
      <tr>
        <td colspan="2"><hr/></td>
      </tr>
   >   <tr>
   >     <th>Tamli Word : </th>
  >      <td><input type="text" name="tamli" value="'."sdf".'" style="font->family: latha, sans-serif;" /></td>
   >   </tr>
  >  </table>
 > </body>
> </html>
>';
>$filename = "test.php";
>require_once 'dompdf/autoload.inc.php';
>use Dompdf\Dompdf;
>$dompdf = new Dompdf();
>$dompdf->loadHtml($html,'UTF-8');
>$dompdf->setPaper('A4', 'landscape');
>$dompdf->render();
>$dompdf->stream($filename);

**Comment by bsweeney** [comment]
@palistha01 you should start a new issue rather than comment on a closed one. Also, please indicate which version of Dompdf you are using.

**Comment by manojdmali** [comment]
i am searching same solution.
