### ISSUE TITLE
"doubling" of page breaks when page-break-before applied to long element

### ISSUE THREAD

**Issue by ronan-ft** [dompdf/dompdf#854]
The XHTML at http://pastie.org/9475948, when rendered with a recent
version of dompdf (from commit c3527d98d03e61847bd25f9e5cedf86dcc46bebf),
produces a PDF document with unwanted blank pages.  (A "raw" version of
that XHTML is at http://pastie.org/pastes/9475948/text.  The markup was
generated with the PHP code at http://pastie.org/9475942 .)

What seems to happen is that dompdf inserts 2 page breaks where it should
insert only 1.

This problem seems similar to #793.  However, I find that bug report, and
the discussion that follows, somewhat hard to understand, so I have chosen
to make a new bug report rather than report my observations under #793.

In case it matters: PHP_VERSION for me is 5.4.4-14+deb7u12. The OS is
Debian Linux 7.6.

**Comment by jdsiddon** [comment]
The auto page break fixed my issue as well!

**Comment by MarkMaldaba** [comment]
It looks like this was fixed quite a long time ago, in commit 274c1c9bf376bb0fdac935cae19448fe6413ba17.

Close?
