### ISSUE TITLE
Extra margin space introduced after page break

### ISSUE THREAD

**Issue by quantumdot** [dompdf/dompdf#855]
First, Thanks for all the hard work, I'm generally quite pleased with DOMPDF!

I'm experiencing an issue where a set of elements is shifted to the right after making a page break:
![break1](https://cloud.githubusercontent.com/assets/8483606/3957346/fb663d6c-2714-11e4-8aed-52b2f46b32b4.jpg)

sample HTML code: http://pastie.org/private/ynewvbsprgnboifnp1la3g

I am using the latest zip version of DOMPDF available on github, and I have tested on both PHP 5.5.9 and 5.3.1, both on windows systems running apache.

The offending element is a li element and contains two divs that are each displayed as inline-block with fixed widths. The inside divs have no margin or padding, however the containing li has only a padding of 5px all around. The li elements themselves have 'page-break-inside: avoid;'

**Comment by bsweeney** [comment]
Apparently I never got back to you :(

I supposed at this point no further help is needed, but if so feel free to post back and I'll open this back up.
