### ISSUE TITLE
Exception parsing Zurb foundation css

### ISSUE THREAD

**Issue by th3hamburgler** [dompdf/dompdf#859]
Having an issue creating a pdf using a stylesheet that includes the foundation css framework. I've narrowed it down to parsing the actual foundation css file.

This exception can be triggered by parsing a simple html file including the following css file:

http://cdn.foundation5.zurb.com/foundation.css

php version: _PHP 5.5.12-2+deb.sury.org~trusty+1 (cli) (built: May 12 2014 13:48:43)_

summary of exception:

```
exception 'ErrorException' with message 'Trying to get property of non-object' in /home/vagrant/Sites/sam.site/vendor/dompdf/dompdf/include/style.cls.php:506
Stack trace:
#0 /home/vagrant/Sites/sam.site/vendor/dompdf/dompdf/include/style.cls.php(506): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/home/vagrant/S...', 506, Array)
#1 /home/vagrant/Sites/sam.site/vendor/dompdf/dompdf/include/style.cls.php(1989): Style->length_in_pt('1rem')
#2 /home/vagrant/Sites/sam.site/vendor/dompdf/dompdf/include/style.cls.php(1949): Style->_set_border_radius_corner('1rem', 'top_left')
#3 /home/vagrant/Sites/sam.site/vendor/dompdf/dompdf/include/style.cls.php(704): Style->set_border_top_left_radius('1rem')
#4 /home/vagrant/Sites/sam.site/vendor/dompdf/dompdf/include/stylesheet.cls.php(1352): Style->__set('border-top-left...', '1rem')
#5 /home/vagrant/Sites/sam.site/vendor/dompdf/dompdf/include/stylesheet.cls.php(1380): Stylesheet->_parse_properties('-webkit-top-lef...')
#6 /home/vagrant/Sites/sam.site/vendor/dompdf/dompdf/include/stylesheet.cls.php(1127): Stylesheet->_parse_sections('.button-group.r...')
#7 /home/vagrant/Sites/sam.site/vendor/dompdf/dompdf/include/stylesheet.cls.php(331): Stylesheet->_parse_css('meta.foundation...')
```

Thank you, let me know if I can provide any further information.

**Comment by DmitryPogodaev** [comment]
Hi, all!
Have the same warning. Waiting for fix

**Comment by str** [comment]
+1 on the error

**Comment by bsweeney** [comment]
Unable to reproduce the error using sample templates from the Foundation site. Rendering is not particularly great, especially with support for some CSS features (e.g., Flexbox #971). But, like with Bootstrap, supporting the framework as a whole would require a project to complete and we'll continue to focus on the individual CSS features that will improve compatibility over time as they're implemented.
