### ISSUE TITLE
Form elements do not display

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#86]
_Original author: dezu...@gmail.com (October 12, 2009 01:37:24)_

<b>What steps will reproduce the problem?</b>
1. Include form inputs on an html page.
2. Render a pdf from that page
3. form elements do not display

<b>What is the expected output? What do you see instead?</b>
I would expect to see the form elements on the PDF

<b>What version of the product are you using? On what operating system?</b>
0.5.1

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=79_

**Comment by nickwuk** [comment]
I have an issue with displaying a radio field, it displays correctly on my local server (XAMPP on Win7) but when uploaded to an online Apache server it displays as a question mark in the Pdf. I've re-uploaded DomPdf files but that made no difference. Any ideas please?

**Comment by bsweeney** [comment]
I believe we have sufficiently incorporated form field display as of 0.8.0. Closing unless someone is able to point out an oversight on our part.
