### ISSUE TITLE
Images not showing when center-align

### ISSUE THREAD

**Issue by vpakg** [dompdf/dompdf#861]
Not sure if this qualifies as a bug, but maybe someone know the answer for a problem I'm having. I have multiple forms (laravel 4.2) with tinyMCE inputs that saves to the database in order to generate a PDF with the content from the database. 

Whenever the user center-align the image with TinyMCE, it doesn't show in the PDF. It doesn't give me any errors, it simply doesn't show. If I go back to the form and right-align the image, it shows again, but the users of the system required full control of the interface.

does anyone knows what could be causing this?

This is a sample of the view that is being used by DOMPDF, the image is contained within product description.

```
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>{{Lang::choice('page_elements/general.proposal', 2)}}</title>
        <style type="text/css">
        </style>
    </head>
    <body>
        <div class="product_section">
           <div class="text-block">{{($proposalProduct->description)}}</div>
        </div>
    </body>
    </html>
```

This is a sample of what the product description (formatted by TinyMCE) is returning.

```
<p>This is a sample product, using images and tinyMCE.</p>
<p><img style="-webkit-user-select: none; margin-left: auto; margin-right: auto;"   src="http://mywebsite.com/products/images/product1.png" alt="" /></p>
```

Thanks for the help.

**Comment by Mellthas** [comment]
The sample works now. The auto margins should only center the image if it had `display: block`.
