### ISSUE TITLE
header overwrites the text of the page

### ISSUE THREAD

**Issue by franzholz** [dompdf/dompdf#867]
I did follow the steps from #571 and #864 for the creation of a header.

Unfortunately the header on the second page overwrites the other text on the page. How can I avoid this?
I have added a container class in order to have a padding on the first page. I do not know how to get a space on the second and the following pages. I would prefer to get rid of the container class, because the HTML is generated by PHP. And I do not know how many pixels I must set in the end.

```
.header {top: 0; position: fixed;}
.footer {bottom: 0px; position: fixed;}
.container {margin: 0 auto; overflow: auto; padding: 80px;}
```

The example is here:

http://jambage.com/fehlersuche/Zulu-Bill-2.html
http://jambage.com/fehlersuche/Zulu-Bill-2.pdf

**Comment by shimax** [comment]
**this is bug in chrome. still overlapping content with footer**
![capture](https://cloud.githubusercontent.com/assets/12815658/22058909/81f298dc-dd8c-11e6-9829-e3fbbd13ceb0.PNG)

**Comment by bsweeney** [comment]
@shimax you need to set the header/footer inside the page margins to avoid header/footer overlap. You didn't provide sample HTML, but let's say your footer is styled `.footer { position: fixed; bottom: 0px; left: 0px; right: 0px; }`. Content that flows to the bottom of the page will run under the footer element. To avoid this, push the footer into the page margins, for example `.footer { position: fixed; bottom: -1in; left: 0px; right: 0px; }`

**Comment by shimax** [comment]
this is not working for me
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">

<title>Header and Footer example</title>
<style type="text/css">

@page {
	margin: 2cm;
}

body {
  font-family: sans-serif;
	margin-bottom: 1in;
	text-align: justify;
}

#header,
#footer {
  position: fixed;
  left: 0;
	right: 0;
	color: #aaa;
	font-size: 0.9em;
}

#header {
  top: 0;
	border-bottom: 0.1pt solid #aaa;
}

#footer {
  bottom: 0;
  left: 0px;
  right: 0px;
  border-top: 0.1pt solid #aaa;
}

#header table,
#footer table {
	width: 100%;
	border-collapse: collapse;
	border: none;
}

#header td,
#footer td {
  padding: 0;
	width: 50%;
}

.page-number {
  text-align: right;
}

.page-number:before {
  content: "Page " counter(page); 
}

hr {
  page-break-after: always;
  border: 0;
}

</style>
  
</head><body onload="window.print()">

<div id="header">
  <table><tbody><tr><td>Example document</td><td style="text-align: right;">Author</td></tr></tbody></table>
</div>

<div id="footer">
  <div class="page-number">
    <pre>hfghfg</pre>
    <pre>hfghfg</pre>
    <pre>hfghfg</pre>
  </div>
</div>

<h2>Section 1</h2>

<p>
	<img src="images/dompdf_simple.png" style="float: right; margin: 0.5em;">
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed non
risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec,
ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula
massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci
nec nonummy molestie, enim est eleifend mi, non fermentum diam nisl sit
amet erat. Duis semper. Duis arcu massa, scelerisque vitae, consequat
in, pretium a, enim. Pellentesque congue. Ut in risus volutpat libero
pharetra tempor. Cras vestibulum bibendum augue. Praesent egestas leo
in pede. Praesent blandit odio eu enim. Pellentesque sed dui ut augue
blandit sodales. Vestibulum ante ipsum primis in faucibus orci luctus
et ultrices posuere cubilia Curae; Aliquam nibh. Mauris ac mauris sed
pede pellentesque fermentum. Maecenas adipiscing ante non diam sodales
hendrerit.</p>

<hr>

<h2>Section 2</h2>

<p>
  <img src="images/goldengate.jpg" style="float: left; padding: 0.5em;" width="180">
	Ut velit mauris, egestas sed, gravida nec, ornare ut, mi. Aenean ut
orci vel massa suscipit pulvinar. Nulla sollicitudin. Fusce varius,
ligula non tempus aliquam, nunc turpis ullamcorper nibh, in tempus
sapien eros vitae ligula. Pellentesque rhoncus nunc et augue. Integer
id felis. Curabitur aliquet pellentesque diam. Integer quis metus vitae
elit lobortis egestas. Lorem ipsum dolor sit amet, consectetuer
adipiscing elit. Morbi vel erat non mauris convallis vehicula. Nulla et
sapien. Integer tortor tellus, aliquam faucibus, convallis id, congue
eu, quam. Mauris ullamcorper felis vitae erat. Proin feugiat, augue non
elementum posuere, metus purus iaculis lectus, et tristique ligula
justo vitae magna. Morbi vel erat non mauris convallis vehicula. Nulla et
sapien. Integer tortor tellus, aliquam faucibus, convallis id, congue
eu, quam. Mauris ullamcorper felis vitae erat. Proin feugiat, augue non
elementum posuere, metus purus iaculis lectus, et tristique ligula
justo vitae magna.</p>

<hr>

<h2>Section 3</h2>


<p><span style="float: left; font-size: 4em; width: 0.7em; height: 0.9em; line-height: 1;">A</span>liquam convallis sollicitudin purus. Praesent aliquam, enim at
fermentum mollis, ligula massa adipiscing nisl, ac euismod nibh nisl eu
lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam euismod
libero eu enim. Nulla nec felis sed leo placerat imperdiet. Aenean
suscipit nulla in justo. Suspendisse cursus rutrum augue. Nulla
tincidunt tincidunt mi. Curabitur iaculis, lorem vel rhoncus faucibus,
felis magna fermentum augue, et ultricies lacus lorem varius purus.
Curabitur eu amet.</p>

<p>Aliquam convallis sollicitudin purus. Praesent aliquam, enim at
fermentum mollis, ligula massa adipiscing nisl, ac euismod nibh nisl eu
lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam euismod
libero eu enim. Nulla nec felis sed leo placerat imperdiet. Aenean
suscipit nulla in justo. Suspendisse cursus rutrum augue. Nulla
tincidunt tincidunt mi. Curabitur iaculis, lorem vel rhoncus faucibus,
felis magna fermentum augue, et ultricies lacus lorem varius purus.
Curabitur eu amet.</p>

<p>Aliquam convallis sollicitudin purus. Praesent aliquam, enim at
fermentum mollis, ligula massa adipiscing nisl, ac euismod nibh nisl eu
lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam euismod
libero eu enim. Nulla nec felis sed leo placerat imperdiet. Aenean
suscipit nulla in justo. Suspendisse cursus rutrum augue. Nulla
tincidunt tincidunt mi. Curabitur iaculis, lorem vel rhoncus faucibus,
felis magna fermentum augue, et ultricies lacus lorem varius purus.
Curabitur eu amet.</p>

<p>Aliquam convallis sollicitudin purus. Praesent aliquam, enim at
fermentum mollis, ligula massa adipiscing nisl, ac euismod nibh nisl eu
lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam euismod
libero eu enim. Nulla nec felis sed leo placerat imperdiet. Aenean
suscipit nulla in justo. Suspendisse cursus rutrum augue. Nulla
tincidunt tincidunt mi. Curabitur iaculis, lorem vel rhoncus faucibus,
felis magna fermentum augue, et ultricies lacus lorem varius purus.
Curabitur eu amet.</p>

<p>Aliquam convallis sollicitudin purus. Praesent aliquam, enim at
fermentum mollis, ligula massa adipiscing nisl, ac euismod nibh nisl eu
lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam euismod
libero eu enim. Nulla nec felis sed leo placerat imperdiet. Aenean
suscipit nulla in justo. Suspendisse cursus rutrum augue. Nulla
tincidunt tincidunt mi. Curabitur iaculis, lorem vel rhoncus faucibus,
felis magna fermentum augue, et ultricies lacus lorem varius purus.
Curabitur eu amet.</p>

<p>Aliquam convallis sollicitudin purus. Praesent aliquam, enim at
fermentum mollis, ligula massa adipiscing nisl, ac euismod nibh nisl eu
lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam euismod
libero eu enim. Nulla nec felis sed leo placerat imperdiet. Aenean
suscipit nulla in justo. Suspendisse cursus rutrum augue. Nulla
tincidunt tincidunt mi. Curabitur iaculis, lorem vel rhoncus faucibus,
felis magna fermentum augue, et ultricies lacus lorem varius purus.
Curabitur eu amet.</p>

<p>Aliquam convallis sollicitudin purus. Praesent aliquam, enim at
fermentum mollis, ligula massa adipiscing nisl, ac euismod nibh nisl eu
lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam euismod
libero eu enim. Nulla nec felis sed leo placerat imperdiet. Aenean
suscipit nulla in justo. Suspendisse cursus rutrum augue. Nulla
tincidunt tincidunt mi. Curabitur iaculis, lorem vel rhoncus faucibus,
felis magna fermentum augue, et ultricies lacus lorem varius purus.
Curabitur eu amet.</p>

<p>Aliquam convallis sollicitudin purus. Praesent aliquam, enim at
fermentum mollis, ligula massa adipiscing nisl, ac euismod nibh nisl eu
lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam euismod
libero eu enim. Nulla nec felis sed leo placerat imperdiet. Aenean
suscipit nulla in justo. Suspendisse cursus rutrum augue. Nulla
tincidunt tincidunt mi. Curabitur iaculis, lorem vel rhoncus faucibus,
felis magna fermentum augue, et ultricies lacus lorem varius purus.
Curabitur eu amet.</p>

<p>Aliquam convallis sollicitudin purus. Praesent aliquam, enim at
fermentum mollis, ligula massa adipiscing nisl, ac euismod nibh nisl eu
lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam euismod
libero eu enim. Nulla nec felis sed leo placerat imperdiet. Aenean
suscipit nulla in justo. Suspendisse cursus rutrum augue. Nulla
tincidunt tincidunt mi. Curabitur iaculis, lorem vel rhoncus faucibus,
felis magna fermentum augue, et ultricies lacus lorem varius purus.
Curabitur eu amet.</p>

<p>Aliquam convallis sollicitudin purus. Praesent aliquam, enim at
fermentum mollis, ligula massa adipiscing nisl, ac euismod nibh nisl eu
lectus. Fusce vulputate sem at sapien. Vivamus leo. Aliquam euismod
libero eu enim. Nulla nec felis sed leo placerat imperdiet. Aenean
suscipit nulla in justo. Suspendisse cursus rutrum augue. Nulla
tincidunt tincidunt mi. Curabitur iaculis, lorem vel rhoncus faucibus,
felis magna fermentum augue, et ultricies lacus lorem varius purus.
Curabitur eu amet.</p>


</body></html>

**Comment by shimax** [comment]
<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>print css test by mtness</title>

    <style>
        @media print
        {
            #footer {
                display: block;
                position: fixed;
                bottom: 0;
            }
        }
    </style>
</head>
<body>
<div class="container">
    <button onclick="doPrint()" class="btn btn-info">Print</button>
    <div id="Printable">

        <table border="0" width="100%">
            <thead>
                <tr>
                    <th style="width:100%">page header</th>
                </tr>

                <tr>
                    <th><hr style="color:#000080"/></th>
                </tr>
            </thead>

            <tfoot>
                <tr>
                    <td width="100%">
                        <table width="100%" border="0">
                            <tr>
                                <td colspan="4"><br>&nbsp;table footer</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>

            <tbody>
            @for($i = 0; $i < 50; $i++)
                <tr>
                    <td width="100%">
                        put your text (for example article main body, title etc...)
                    </td>
                </tr>
            @endfor
            </tbody>
        </table>

        <table id="footer" width="100%">
            <tr>
                <td width="100%">
                    footer text
                </td>
            </tr>
        </table>

    </div>
</div>

<script>

    function doPrint() {
        window.print();
    }
</script>
</body>
</html>

**Comment by shimax** [comment]
if i put -1in , footer prints in second page on top of the header, if i give 1in, footer again overlapping with the content, if i give zero it works fine, but the space is not enough print multiple lines in that small area.

**Comment by bsweeney** [comment]
😑

Can't really help you there. I know a lot about how to deal with this type of formatting in dompdf but haven't spent much time in the browser environment doing the same.

**Comment by udaypedakota** [comment]
[Balance_Sheet_Report (32).pdf](https://github.com/dompdf/dompdf/files/14138263/Balance_Sheet_Report.32.pdf)
i have issue on header was overlaping on second page table data in html pdf

**Comment by bsweeney** [comment]
@udaypedakota [start a new discussion](https://github.com/dompdf/dompdf/discussions/new/choose) and we can figure out what's going on.

**Comment by yogesh-bavishi-1** [comment]
BTW I was upgrading from 0.8.x to 2.0.x and the output was changed. And the discussion helped me.  The `margin` thing needs to be changed.

**Comment by Anishaaaaaaaaaaa** [comment]
i too face the same issue
![Capture](https://github.com/dompdf/dompdf/assets/169022869/e4615fc7-8751-42e8-b240-e4872607499f)
this is my code in my controller
$headerHtml = '<div style="position: fixed; top: -20px; left: 0px; right: 0px; height: 50px;>
    <div style="height: 50px; display: inline-block;">
        <img src="'. asset("images/logoo.jpg") .'" alt="Logo" style="height: 40px; width: auto; vertical-align: middle;">
        <div style="float:right;">
        <p style="font-size: 12px;">Worldwide Campus LLP <br>Authorized Agent for Feel At Home </p>
        </div>
    </div>
</div>';

    // Render the footer HTML
    $footerHtml = '
    <div style="position: fixed; bottom: 0; left: 0; right: 0; height: 30px;  text-align: center; line-height: 30px;">
    <script type="text/php">
        if (isset($pdf)) {
            $font = $fontMetrics->get_font("Arial, Helvetica, sans-serif", "normal");
            $size = 10;
            // Calculate X coordinate for horizontal centering
            $x = 270; // Assuming A4 paper width is 595 units, and div width is 175 units
            // Calculate Y coordinate for vertical centering
            $y = 800; // Half of the div height
            $pdf->page_text($x, $y, "Page {PAGE_NUM} of {PAGE_COUNT}", $font, $size);
        }
    </script>
</div>
';

    $tableContent = $this->extractTableContent($view);

   
    $contentHtml = '<div style="margin-top: 50px;">' . $tableContent . '</div>';
    // Combine header, footer, and main content
    $pdfHtml = $headerHtml . $contentHtml . $footerHtml;
    
    this issue exist only when the $contentHtml prints on the second page of the pdf
