### ISSUE TITLE
Double colon :: CSS notation DOMXPath “Invalid expression” warnings

### ISSUE THREAD

**Issue by twistedpixel** [dompdf/dompdf#869]
Just curious, I have started using dompdf and my Codeigniter error logs are full of these errors pointing at line 853 of stylesheet.cls.php and I'm wondering if this is an issue with dompdf or the DOMXPath parser itself?

It's obviously not causing issues with my PDFs but rather irritating to have these warnings clogging up my log files which I aim to keep squeaky clean!

Also, I don't think it's just the double colon although it took me hours to track down that and I'm really not looking forward to tracking down other apparently invalid expressions which are not actually invalid.. so if anyone knows of others that produce this error please let me know.

**Comment by DerDu** [comment]
Same for me using bootstrap style

    svg:not(:root) {
        overflow: hidden;
    }

DomPDF 0.6.1
Bootstrap 3.3.5

**Comment by twistedpixel** [comment]
The problem with this is that you really have to override CodeIgniter's exception handling to be able to suppress the errors that it picks up. I've not had time to do this so I just wrote a parser to remove them from my log files for now. It's not really ideal so maybe it's time for me to revisit this.

**Comment by twistedpixel** [comment]
If I remember correctly, CodeIgniter's error handler/logger used debug_backtrace() or something to look for errors and so the try/catch solution didn't work.
