### ISSUE TITLE
Line break after opening bracket "(" or before closing bracket ")"

### ISSUE THREAD

**Issue by zincdesign** [dompdf/dompdf#879]
There are awkward line breaks leaving a lone opening bracket on the previous line or a closing bracket on the following line. 

This usually happens when a URL link or a span style is within the brackets.

**Comment by zincdesign** [comment]
We have discovered this issue happens after superscript characters too. See attached image
![image001](https://cloud.githubusercontent.com/assets/9975543/5804523/96fef130-9ffe-11e4-8f84-7951433a80d2.png)
Do you know if any adjustments have been made to rectify this problem at all?

**Comment by bsweeney** [comment]
Nothing as of yet, sorry. The issue will affect any inline element since, I believe, an inline element is treated similar to a word break.

**Comment by zincdesign** [comment]
Hi. Sorry, I am just checking in to see if any progress have been made with this issue?

**Comment by bsweeney** [comment]
No, sorry. It's definitely something we want to fix I'm just not sure when we'll be able to look at it. I wasn't even able to find a decent work around since the issue has to do with how inline elements are treated.

**Comment by bsweeney** [comment]
closing in favor of #1036 which provides a clearer picture of the issue
