### ISSUE TITLE
word break whit <shy>

### ISSUE THREAD

**Issue by kruske** [dompdf/dompdf#888]
In "text_frame_reflower.cls.php" i see "@todo support &lt;shy&gt;, &lt;wbr&gt;" but no push "-" to end of line.

Now de en of line is ok, EX: the word "example" cut in ex-ample, but no push "-"

**Comment by bsweeney** [comment]
Yes, we haven't yet addressed this issue. That particular section of code is just one part that will need to be modified in order to support `&shy;`. Please watch issue #104 for updates.

**Comment by naitsirch** [comment]
This is fixed in #2009
