### ISSUE TITLE
I can't display special characters!

### ISSUE THREAD

**Issue by gozonjoedaimar** [dompdf/dompdf#893]
Hi, i can't display these following special characters, ūāēīņ. Can you help me with these? Thank you in advance.

**Comment by bsweeney** [comment]
The built-in fonts specified by the PDF spec only support characters from the Windows ANSI encoding. If you want to display characters not supported by this encoding you have to use an alternate font. dompdf as of 0.6.0 supplies the DejaVu fonts which support a fairly large number of characters from Unicode encoding.

Quick testing indicates that the characters you specified are supported. Try something like the following:

```html
<div style="font-family:DejaVu Sans; sans-serif">ūāēīņ</div>
```

**Comment by gozonjoedaimar** [comment]
How can i test this? I already tried this code. and still displays ????. Can you help me?

**Comment by bsweeney** [comment]
That one should work without any modification of the HTML or dompdf configuration if you're using 0.6.1. Are you doing anything to the HTML before passing it to dompdf?

**Comment by gozonjoedaimar** [comment]
Oh my, I think it's my fault. I forgot to remove utf8_decode while i was debugging. Thanks anyway.

$dompdf->load_html(utf8_decode($text));

**Comment by gozonjoedaimar** [comment]
When I add this line of code. The characters are displayed as box. How can I fix this?

	$text = '<div style="font-family:DejaVu Sans; sans-serif">ūāēīņ</div>';

	$dompdf = new DOMPDF();
	$dompdf->load_html($text);
	$dompdf->render();
	$canvas = $dompdf->get_canvas();

	$canvas->get_cpdf()->setEncryption($pass,'admin123',array());  // This code
	$dompdf->stream('book.pdf');

**Comment by bsweeney** [comment]
Encrypted documents with embedded fonts and missing glyphs is a known issue. Visit and watch issue #340 for updates.
