### ISSUE TITLE
Dompdf generating red lines in document

### ISSUE THREAD

**Issue by Carlitta87** [dompdf/dompdf#894]
I maybe doing the wrong way, im not sure but the pdf i generate is producing red lines around every single elements. As seen below.
When I add the exit function after the stream call, i got this data:
![screen shot 2015-01-15 at 5 34 34 pm](https://cloud.githubusercontent.com/assets/2539915/5768241/cfd50e38-9cdc-11e4-8e2e-a98e676f373e.png)

I was hoping someone could give some insight as to why this happened and how can i remedy this. I have no idea how to resolve this. Help please

![screen shot 2015-01-15 at 5 29 36 pm](https://cloud.githubusercontent.com/assets/2539915/5768154/3184388a-9cdc-11e4-8717-b745e1044c35.png)

I also used the code below to generating the pdf
<pre>
 $html_content = trim(stripslashes($html_content));
 $html_content = "<p>Testing123</p>";
 $dompdf = new DOMPDF();
 $dompdf->load_html($html_content);
 $dompdf->set_paper('letter', 'portrait');
 $dompdf->render();
 $dompdf->stream("newfile.pdf");
 exit;
</pre>

**Comment by bsweeney** [comment]
Looks like you have layout debugging enabled. Ensure that the DEBUG_LAYOUT configuration constant is set to false. You can set it from dompdf_config.inc.php or dompdf_custom_config.inc.php.

**Comment by bsweeney** [comment]
also asked here: http://stackoverflow.com/q/27987206/264628
