### ISSUE TITLE
Image not showed, rendered

### ISSUE THREAD

**Issue by Rodjaaa** [dompdf/dompdf#897]
Hi, i have problem with using dompdf. I searched over internet for all kinds of "fixes" for this problem. Image is "downloaded" to tmp directory but it wont render. I am using CPDF for backend and i cannot use GD2 or PDFLib. So, as i say. Image is downloaded to tmp but it is not rendered to document. I am using path http://.... if i use path /var/... then i get error "image is not found" and alt is displayed but with http:// path alt is not displayed neither image,  so it must be something with rendering.... is this bug or my config is wrong? Image is jpg. i tried png also, same result.

**Comment by bsweeney** [comment]
You can not use GD2? With v0.6.x GD is now a requirement. You could try 0.5.x, it has some image support even for systems that do not have GD.

**Comment by Rodjaaa** [comment]
When i change backend to GD then i get error "the image blob:http..... cannot be displayed because it contains errors" and title is PNG image, my images in html are jpg. When it is CPDF then i get pdf document but without images.

**Comment by bsweeney** [comment]
Sorry, I didn't mean to change the dompdf back end to GD. I was asking if you had the GD PHP extension installed on your system.

Image issues are difficult to diagnose remotely. You said you're getting the temp files when using http://. Do you get any error from PHP (like in the error log)? Does the dompdf "user" have read/write access to the temp directory.

Also, if the http:// image is not rendered what do you see in it's place?

**Comment by Rodjaaa** [comment]
Yes, PHP GD extension is installed, i dont have GMagick or IMagick but i dont use png images. In error log there in nothing, no error from dompdf. Yes tmp directory is 777 mod so yes. In place of picture there is nothing, white space. for example i have picture on http://domain.com/image1.jpg , if i put src to match it then i get white blank space instead of picture and it will be in tmp folder, i set to keep temp. If i change src to non exist image like http://domain.com/image_1.jpg than i will get gray image, image not found error but dompdf will render gray image.... I dont know what else can it be?
Date: Mon, 9 Feb 2015 18:11:02 -0800

**Comment by bsweeney** [comment]
If there were a problem processing the image you should get an error or a notice at some point. You might have to modify PHP's error reporting settings.

Can you post a sample PDF so that we can look at its source?
