### ISSUE TITLE
Installable PEAR package

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#9]
_Original author: ryan.mas...@gmail.com (April 29, 2009 18:06:32)_

<b>What would you like dompdf to do:</b>

It'd be handy to create a pear installabe package for dompdf. This would
involve creating a package.xml and using pear to read this package and tar
up the files into one nice neat tgz.

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=2_

**Comment by bsweeney** [comment]
Closing because Composer.
