### ISSUE TITLE
Simple usage example?

### ISSUE THREAD

**Issue by canfiax** [dompdf/dompdf#900]
Would anyone bother to show me a small piece of example code, when installed from "Composer"?

I kinda miss some piece of example code, to transform, say a HTML string, or web-URL to a PDF, and then save it in the file system.

How can I do this, using this library?

**Comment by bsweeney** [comment]
Have you read the [dompdf README instructions related to composer](https://github.com/dompdf/dompdf#install-with-composer) or the [dompdf & Composer quick start](https://github.com/dompdf/dompdf/wiki/DOMPDF-and-Composer-Quick-start-guide) in the wiki?

**Comment by alex-ception** [comment]
IMHO, disabling dompdf autoloader and include the configuration file is not a viable solution, it's a workaround.
I use open sources PHP tools which are including composer autoloader by themselves (and therefore don't add the define and the include). I won't patch these tools just to make dompdf work on them.
Have you considered finding a real solution ?

**Comment by canfiax** [comment]
Thanks, the wiki got met started.

**Comment by bsweeney** [comment]
@alex-ception your issues will likely be addressed by the forthcoming release. Feel free to check out the develop branch if you want to see how it works. If you run into any other problems it's best to [open a new issue](https://github.com/dompdf/dompdf/issues/new) or [start a discussion on the support forum](http://groups.google.com/group/dompdf).
