### ISSUE TITLE
No block-level parent found. Not good.

### ISSUE THREAD

**Issue by Steinweber** [dompdf/dompdf#902]
Fatal error: Uncaught exception 'DOMPDF_Exception' with message 'No block-level parent found. Not good.' in /var/www/web50/htdocs/system/library/dompdf/include/inline_positioner.cls.php:37

All installaled
PHP 5.0+
MBString extension
DOM extension
GD extension

No Images, just external css/js

**Comment by bsweeney** [comment]
Check your PHP error log. Typically this error is the result of a null value being parsed, which probably means your document content was lost during initial processing.

**Comment by Steinweber** [comment]
new install of dompdf resolved the problem

**Comment by VerzatileTom** [comment]
Hi, dompdf is working on my localhost but im getting this error on live server. what could be the solution for this?

**Comment by bsweeney** [comment]
You should check your inputs to make sure the content variable (if using `$dompdf->load_html()`) isn't being nulled out. Also look in your PHP logs for any errors. Also, perhaps you're missing a PHP extension or an external PHP library (e.g. the HTML 5 parser) on the server?

**Comment by tomvo** [comment]
I had this happen when I tried to call `loadHTML()` twice on the same object.

**Comment by VerzatileTom** [comment]
i'm using $dompdf->loadView()

**Comment by bsweeney** [comment]
`$dompdf->loadView()`? Are you using dompdf with another library? That method isn't part of dompdf.

**Comment by VerzatileTom** [comment]
oh silly me! im so sorry, I thought its the same. Sorry for bothering you. *flies away*

**Comment by bsweeney** [comment]
Ha ha ... we all do it (you *will not* look at my recent github activity). The error is from dompdf, but you might have better luck with the other library. If that doesn't help come on back over and we can hash it out in the support form.

**Comment by themao** [comment]
I'm doubling @tomvo, I also receive this error when using loadHtml() twice on the same object. I need to generate several pdf files from a list of html templates, so there's no way to avoid using this method twice. 

Is there anything that has to be called before loading new html? It looks like it creates new DOMDocument every time, but still it might have some leftovers from the previous 'generations', am I right?

**Comment by themao** [comment]
For googlers like me, it refers to this bug https://github.com/dompdf/dompdf/issues/1056

**Comment by bsweeney** [comment]
I haven't yet spent much time trying to figure out exactly what would need to be changed to support this. I thought maybe the canvas and frame tree would need to be reset. But the canvas is currently set at render time and the frame tree when a document is loaded. So...

You should be able to `unset($dompdf)` to clear out any objects that may be causing conflicts.

**Comment by themao** [comment]
Yes, that's how I'm handling it now. I tried debugging a little bit, but couldn't yet find more that you've just said - everything seems to be set at render time.

**Comment by aquaticpond** [comment]
I am seeing this error as well in my vagrant and my production server. I have the extensions and it throws weather or not html5 parser option is enabled. Only thing I can think is I'm using PHP7?

// error
Fatal error: Uncaught Dompdf\Exception: No block-level parent found. Not good.

// code
$dompdf = new Dompdf(['isHtml5ParserEnabled' => true]);
$dompdf->setPaper('A4', 'landscape');
$dompdf->loadHtml($html);
$dompdf->render("<strong>yer a pdf harry!</strong>");

**Comment by bsweeney** [comment]
@aquaticpond using the 0.7.0 final release? Do you get anything back if you call `$dompdf->output_html();` instead of render? What if you disable the HTML5 parser?

**Comment by aquaticpond** [comment]
output_html() returns the same string input to load_html(). Toggling isHtml5ParserEnabled yields no difference.

**Comment by bsweeney** [comment]
Typically this error is thrown when the variable containing the HTML contents is null. There have been issues in the past where a bug in the HTML processing would result in the HTML content being nulled before by dompdf, but I believe those have been cleared up with the latest release.

Do you see any notices or warnings thrown by PHP besides the initial one.

**Comment by aquaticpond** [comment]
No sir, what you see is all I have. I also tried wrapping in a DIV and providing a full HTML5 document.

**Comment by aquaticpond** [comment]
`$dompdf->loadHtml("<div>herp</div><div>derp</div>");`

Uncommented line 800 of AbstractFrameDecorator and got:

`html:
Id: 0
Class: Dompdf\Frame
Decorator: Dompdf\FrameDecorator\Page
Position:
Array
(
    [x] => 
    [y] => 
    [0] => 
    [1] => 
)
Containing block:
Array
(
    [x] => 0
    [y] => 0
    [w] => 841.89
    [h] => 595.28
    [0] => 0
    [1] => 0
    [2] => 841.89
    [3] => 595.28
)
Margin width:
auto
Margin height:
auto
Style:
Array
(
    [parent_font_size] => 12
    [font_size] => 12
    [width] => auto
    [margin_left] => 0
    [margin_right] => 0
    [border_left_width] => medium
    [border_left_style] => none
    [border_right_width] => medium
    [border_right_style] => none
    [padding_left] => 0
    [padding_right] => 0
    [height] => auto
    [margin_top] => 0
    [margin_bottom] => 0
    [border_top_width] => medium
    [border_top_style] => none
    [border_bottom_width] => medium
    [border_bottom_style] => none
    [padding_top] => 0
    [padding_bottom] => 0
)
body:
Id: 1
Class: Dompdf\Frame
Parent:html (0000000032258bd2000000002aa63c94) 
Decorator: Dompdf\FrameDecorator\Inline
Position:
Array
(
    [x] => 
    [y] => 
    [0] => 
    [1] => 
)
Containing block:
Array
(
    [x] => 0
    [y] => 0
    [w] => 841.89
    [h] => 595.28
    [0] => 0
    [1] => 0
    [2] => 841.89
    [3] => 595.28
)
Margin width:
auto
Margin height:
auto
Style:
Array
(
    [parent_font_size] => 12
    [font_size] => 12
    [float] => none
    [position] => static
    [display] => inline
    [width] => auto
    [margin_left] => 0
    [margin_right] => 0
    [border_left_width] => medium
    [border_left_style] => none
    [border_right_width] => medium
    [border_right_style] => none
    [padding_left] => 0
    [padding_right] => 0
    [height] => auto
    [margin_top] => 0
    [margin_bottom] => 0
    [border_top_width] => medium
    [border_top_style] => none
    [border_bottom_width] => medium
    [border_bottom_style] => none
    [padding_top] => 0
    [padding_bottom] => 0
)
`

**Comment by bsweeney** [comment]
Certainly looks to be that there was not content. What OS are you running on? Version of PHP?

**Comment by aquaticpond** [comment]
PHP7, Ubuntu and CentOS 6.7

**Comment by marcleimvs** [comment]
I use Dompdf within Joomla projects and I've changed Dompdf directories to suite my projects needs, then I started to have such an error 'No block-level parent found. Not good'. Checking the Stylesheet class, it loads the default CSS 'html.css' in 'res' directory and I noticed that the method getDefaultStylesheet() specify a relative path which makes the css file inaccessible, thus Dompdf does not create the 'base' style to process when render() method is called. Without it, block-level parent rise such an error. After I changed the relative path in getDefaultStylesheet() method of Stylesheet class, pointing right to the resource file, everything worked fine. Hope this help!

**Comment by akovalyov** [comment]
I have a very same trouble when reusing a Dompdf instance for multiple PDF documents creation. Quite confusing if using DI and Dompdf as a service. Looks like, something is not cleaned up correctly after rendering.

**Comment by bsweeney** [comment]
@akovalyov hoping to fix this in the next release. Follow #1056 for updates.

**Comment by UweKeim** [comment]
Same here as @marcleimvs said:

After I configured alternative directories, I get the same error:

> No block-level parent found.  Not good.

**Comment by bsweeney** [comment]
@marcleimvs, @UweKeim: when you state that you change the Dompdf directories to suite your project's needs ... what exactly does that mean? There is a level of configuration possible, but moving the lib/res directory isn't one of those options. We can look at making that a possibility if it's something that's needed.

**Comment by UweKeim** [comment]
@bsweeney In [my case](https://groups.google.com/forum/#!topic/dompdf/PxGsXAjXIkI) I tried to move the writable font folders outside my PHAR.

This was not sufficient.

What currently works on my Windows dev machine is to remove all `realpath` calls inside the dompdf sources.

I.e. this:

```php
$dir = realpath(__DIR__ . "/../..");
```

will become this:

```php
$dir = (__DIR__ . "/../..");
```

Inside PHAR archives, `realpath` for paths _inside_ a PHAR file returns `false` (See [#52769](https://bugs.php.net/bug.php?id=52769)).

**Comment by bsweeney** [comment]
@UweKeim let's move this discussion to #621.

**Comment by iiamfawad** [comment]
Hi there, I'm facing the same issue on my server. What are the possible solutions? Can anyone help please, I'm stuck!

**Comment by bsweeney** [comment]
@iiamfawad which version of dompdf? What steps have you taken so far?

**Comment by sitilge** [comment]
I've read all the posts on "No block-level parent found. Not good." exception and nothing worked so I decided to start from scratch. I started with a simple snippet
````
$html = '
        <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        </head>
        <body>
            <p>Some text here</p>
        </body>
        </html>
    ';

$dompdf = new Dompdf();

$dompdf->loadHtml($html);

$dompdf->setPaper('A4', 'landscape');

$dompdf->render();

$dompdf->stream("ticket");
````

Obviously, the html is a mere skeleton, no css magic there but still it yields the exception. If the head tag is removed, the snippet works as it should.

What am I missing here?

Disclaimer

Running arch 4.11, php 7.1.7, dompdf 0.8.0. I've read the relase notes of the latest dompdf saying that php 7.1 is supported.

**Comment by marcleimvs** [comment]
When i changed the getDefaultStylesheet() in Stylesheet.php, as below, the error is gone!

`    public static function getDefaultStylesheet()`
 `   {`
 `       //$dir = realpath(__DIR__ . "/../..");`
 `       $dir = realpath(__DIR__ . "/..");`
 `       return $dir . self::DEFAULT_STYLESHEET;`
 `   }`
` 
Try to debug the directory "$dir" to see if it points to a valid path...

**Comment by sitilge** [comment]
After enabling the HTML5 parser, the error was solved.

````
$options = new Options([
     'isHtml5ParserEnabled' => true
]);

$dompdf->setOptions($options);
````

**Comment by bsweeney** [comment]
Thank you for the follow-ups.

@marcleimvs which version of Dompdf are you using? That _should_ be the correct path for 0.7.0 or higher since `__DIR__` returns the path to Stylesheet.php. In these versions the default stylesheet path starts two directory levels higher up. What values do you get for `__DIR__` and `$dir` with the original code?

@sitilge I'm not sure why turning on the HTML5 parser would fix the issue considering the simplicity of the HTML document. It might be an issue with one of the libraries, or possibly system configuration. Are you on *nix or Windows?

**Comment by sitilge** [comment]
Running arch 4.11.

**Comment by bsweeney** [comment]
@sitilge sounds similar to #1494 ... want to continue in that issue?

**Comment by sitilge** [comment]
@bsweeney yes, please do so.

**Comment by ciromattia** [comment]
@sitilge I had the same issue, #1494 indeed was the cause even if I used the HTML5 parse, try to remove whitespaces between <html>, <head> and <body> blocks, like this:

```
$html = '
        <html><head>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        </head><body>
            <p>Some text here</p>
        </body></html>
    ';
```

**Comment by sitilge** [comment]
@ciromattia probably, but it does not feel right... I'm using the parser, error is solved.

**Comment by bsweeney** [comment]
I merged #1570 which addresses one possible cause of this issue. Other potential/actual causes mentioned we'll address as part of the referenced issues.

**Comment by ohader** [comment]
I can confirm it's fixed with commit ad41b6dd17ba774b017407ffba09c14a66665723. Thx!

**Comment by alanducnguyen** [comment]
I got the same issue "No block-level parent found. Not good". 
After the investigation, I tried to call loadView() with simple HTML only.
I discovered that my HTML view is not well-form. (The <link> tag located outside of <head> tag).
In hopeful, anyone had the same case with me can fix the issue.
Sometimes, The error "No block-level parent found. Not good" cause of some HTML is not valid. 
Try to make sure the HTML tag valid, then the issue will be gone.
Thanks.

**Comment by murph133** [comment]
I had the same problem. It was solved simply by update the software version.

Run `composer update`

**Comment by nadiyaparaamit** [comment]
Remove <thead> and <tbody> tags
and remove space between <html><head> , </head><body> and </body></html>

It will work fine.!

**Comment by rmoni3000** [comment]
@nadiyaparaamit solution's worked perfectly for me! (Y)

**Comment by nadiyaparaamit** [comment]
👍

**Comment by wreardan** [comment]
Remove <thead> and <tbody> tags - I did not do this because these were needed for multi-page table headers.

Remove space between <html><head> , </head><body> and </body></html> I did this and it worked!  Thank you so much!  I did not think this would work but for some reason it did.

**Comment by jeffersonor900** [comment]
@sitilge  where? 
"After enabling the HTML5 parser, the error was solved."
$options = new Options([
     'isHtml5ParserEnabled' => true
]);

$dompdf->setOptions($options);

**Comment by jeffersonor900** [comment]
@nadiyaparaamit  it did not work

"Remove <thead> and <tbody> tags
and remove space between <html><head> , </head><body> and </body></html>

It will work fine.!"

**Comment by jeffersonor900** [comment]
Hi there, I'm facing the same issue. What are the possible solutions? Can anyone help please, I'm stuck!

**Comment by DuncanFairley** [comment]
This just happened to me as well after doing a FreeBSD 11.0 > 11.1 upgrade. Haven't experienced this before when upgrading.

**Comment by hanoii** [comment]
@nadiyaparaamit what is this dark magic 😄 ? It did work for me 🥇 .

This happened on an old project (where I am using an old version of dompdf) and just moved it to a new server. It wasn't happening on the old one with the same codebase. Any ideas of this?

**Comment by themao** [comment]
@jeffersonor900 there is a workaround for this issue https://github.com/dompdf/dompdf/issues/902#issuecomment-197655763

**Comment by jdicdican** [comment]
https://github.com/dompdf/dompdf/issues/902#issuecomment-359449394 - thanks @nadiyaparaamit, this saved my day

**Comment by LiamMcArthur** [comment]
@hanoii did you ever manage to fix this? I'm currently migrating from one server to another and having the same problem!

**Comment by josephdicdican** [comment]
I am working on local, php version - PHP 5.6.36 (cli) removing spaces did not working for me. Please help
> exception 'DOMPDF_Exception' with message 'No block-level parent found.  Not good.' in

**Comment by hanoii** [comment]
@liam @josephdicdican I fixed it by following https://github.com/dompdf/dompdf/issues/902#issuecomment-359449394

Make sure ALL spaces are removed.

**Comment by josephdicdican** [comment]
thanks @hanoii , I doubted it would solve the issue but it really did. My bad, I am editing the wrong pdf layout blade.

**Comment by LiamMcArthur** [comment]
It turned out composer update was failing because my directory path exceeded 260 chars. Instead, I've manually copied across all of the files from the updated version and it's all working perfectly now!

**Comment by nospoon** [comment]
This is not fixed as of 0.8.2. Removing tags and spaces is NOT a solution, it's a hack.

**Comment by egan95** [comment]
Remove tag <head> and </head> . it's worked for me...

**Comment by victor-priceputu** [comment]
Had the same issue, for me it was caused by the `html` tag not being detected as a block-level parent.
Had to add the following CSS to fix it:
`html, body {
            display: block;
        }`

**Comment by victor-priceputu** [comment]
Had the same issue, for me it was caused by the `html` tag not being detected as a block-level parent.
Had to add the following CSS to fix it:
`html, body { display: block; }`

**Comment by bsweeney** [comment]
Interestingly, in our default CSS we style the HTML element with `display: -dompdf-page;` ... but that display type isn't referenced anywhere. I'll have to research this a bit more.

The BODY element is appropriately styled with `display: block;` but that can be overridden. I'll update the base stylesheet to at least add !important to the body display styling.

---

> Removing tags and spaces is NOT a solution, it's a hack.

Agreed, and if the problem were with Dompdf we would (eventually) address the issue so the hack wouldn't be needed. For the cases discussed where this is the workaround the bug is not with Dompdf but with a system library. That's beyond the scope of our control and should be reported to the team that maintains that library.

That being said, there is one issue we have not yet addressed brought up by the previous comment: display styling on the body element can throw an exception. And if you're interested in seeing that fixed follow #1869.

**Comment by tuckbloor** [comment]
> For googlers like me, it refers to this bug #1056

thank you

**Comment by tuckbloor** [comment]
For me the foloowing worked,  remove white space between <html><head> 
and </head><body>
and</body></html> and remove <thead> and <tbody> tags

**Comment by ovisopa** [comment]
I used domPDF (0.5.1) on many websites I made in the past, everything **was fine for years**, until yesterday when I updated my cPanel server to newer PHP (7.1 and for older websites also 5.6, before I had 5.4)

Now with PHP 5.6 all websites I made in the past CAN'T generate anymore the PDF invoices, all have this error, which I'm not yet sure yet how to solve after reading the comments, so far I tried to delete (<head> tags), tried the #902 comment suggestion to unset($dompdf) nothing worked. 

So , is there any fix ?

Thank you.

**Comment by Sheep42** [comment]
Can confirm that updating from dompdf 0.8.0 to 0.8.3 fixed the issue for me. In our case, the server was switched to PHP-fpm and that's when it broke.

**Comment by hguru** [comment]
an update will be required

**Comment by javacado** [comment]
@nadiyaparaamit solution's worked perfectly for me too! My issue happened after an update of apache/cpanel etc. Just removing the spaces did the trick.

**Comment by AygnYldz** [comment]
> Remove `<thead>` and `<tbody>` tags
> and remove space between `<html><head>` , `</head><body>` and `</body></html>`
> 
> It will work fine.!

@nadiyaparaamit Thanks

**Comment by sync3ds** [comment]
For who is still facing this problem, the suggestion to add 'isHtml5ParserEnabled' to the options worked for me.
`$dompdf = new Dompdf(array(
	...
	...
	'isHtml5ParserEnabled' => true
));`

**Comment by SSDAbuBakarPHP** [comment]
> Remove tag `<head>` and `</head>` . it's worked for me...

it worked for me also

**Comment by luigilima** [comment]
Edit the anycodings_php dompdf/dompdf_config.inc.php 
from
def("DOMPDF_ENABLE_HTML5PARSER", false);
to
def("DOMPDF_ENABLE_HTML5PARSER", true);

**Comment by RahulSinghalChicago** [comment]
> 'isHtml5ParserEnabled' => true

This is the way.

**Comment by javacado** [comment]
There are a couple of ways, you can see many of them documented and discussed here:
https://stackoverflow.com/questions/37521775/dompdf-error-no-block-level-parent-found-not-good/56958899#56958899
