### ISSUE TITLE
Custom Fonts, encoding and line-height Problem 

### ISSUE THREAD

**Issue by castler** [dompdf/dompdf#911]
Hello,

I was trying to add Courier New to DomPDF. But the "&nbsp" is not shown as a space, it is shown as wierd symbol.

Also I tried to add Comic Sans, this worked very well but the line-height is showing different to other fonts.

Do you have any work arounds?

**Comment by bsweeney** [comment]
Which version of dompdf are you using? Where did you get your font and how are you adding it (e.g. using load_font.php)? Do you have a sample document?

The line-height issues could be a processing problem with the font. I'm not sure about the issue with a non-breaking space. It could be an encoding error, or it could be that the font has an odd character encoded in that space.
