### ISSUE TITLE
PNG images displaying with white forecolor and black background on pdf for DOMPDF 0.6.0 beta 3 

### ISSUE THREAD

**Issue by phixtalk** [dompdf/dompdf#915]
Hello everyone
please i am having challenges when generating pdf with transparent png files
i have research and found that the problem is from the alpha channels or something...
but even after updating  dompdf_config.custom.inc.php, dompdf_config.inc.php and class.pdf.php files 
with the bug fixes, it still did not change. 
i dont know what i am missing. would really appreciate any help.
Also is this bug fixed in the latest version i.e DOMPDF 0.6.1?
![capture](https://cloud.githubusercontent.com/assets/9976895/6607930/1e1fc2b8-c843-11e4-9d54-30efa66fb6e6.PNG)

**Comment by bsweeney** [comment]
We did make some changes to image handling between the beta and final release. You should be able to perform an in-place update of dompdf. If you want to test the release you can always pop over to the debug helper on my site: http://eclecticgeek.com/dompdf/debug.php

**Comment by bsweeney** [comment]
If this is still an issue post back and let us know, closing for now.
