### ISSUE TITLE
 Cannot redeclare class FontLib\Font

### ISSUE THREAD

**Issue by maitriya** [dompdf/dompdf#916]
I am using DOMPDF 0.6.1, php-font-lib 0.3.1, PHP 5.4.26. I need to generate a PDF containing Chinese characters.

My HTML looks like:

      <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
            <style>
              @font-face {
                font-family: "Noto Sans";
                font-style: normal;
                font-weight: 400;
                src: url(http://eclecticgeek.com/dompdf/fonts/cjk/fireflysung.ttf) format("truetype");
              }
              body { font-family: Noto Sans, DejaVu Sans, sans-serif; }
            </style>
        </head>
        <body>test</body>
      </html>

I am getting the following error:

    PHP Fatal error:  Cannot redeclare class FontLib\Font in /dompdf/lib/php-font-lib/classes/Font.php on line 16

**Comment by bsweeney** [comment]
Your issue appears to be in your PHP code. How are you using dompdf?

**Comment by maitriya** [comment]
require_once(sfConfig::get('sf_lib_dir') . '/dompdf/dompdf_config.inc.php');
   
    $dompdf = new DOMPDF();

    $font_family = 'Noto Sans, DejaVu Sans, sans-serif';

    $html = '
      <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
            <style>
              @font-face {
                font-family: "Noto Sans";
                font-style: normal;
                font-weight: 400;
                src: url(http://eclecticgeek.com/dompdf/fonts/cjk/fireflysung.ttf) format("truetype");
              }
              body { font-family: '.$font_family.'; }
            </style>
        </head>
        <body>' . $html . '</body>
      </html>
    ';

    $dompdf->load_html($html);
    $dompdf->render();

    $output = $dompdf->output();
    file_put_contents($file_path, $output);

**Comment by bsweeney** [comment]
Well, that's simple and straightforward. Are you using APC or some other opcode cache?

**Comment by maitriya** [comment]
eaccelerator

**Comment by bsweeney** [comment]
I've seen some posts indicating that opcache may be the cause. I think there are two potential work-arounds:

1. modify the php-font-lib includes to use an absolute path
2. exclude php-font-lib from caching

I don't know if there's any advice specific to eaccelerator.

**Comment by maitriya** [comment]
OK
