### ISSUE TITLE
Border radius

### ISSUE THREAD

**Issue by canfiax** [dompdf/dompdf#918]
Does there exist an version of dompdf somewhere, that supports border-radius? I've found this: https://code.google.com/p/dompdf/source/browse/trunk/dompdf/www/test/css_border_radius.html?spec=svn496&r=496, but seems old.

**Comment by bsweeney** [comment]
Sure does. Here's a live sample: http://pxd.me/dompdf/www/examples.php#css_border_radius.html,pdf

You can follow progress in issue #374.
