### ISSUE TITLE
Fatal Error when generating PDF: Call to undefined method Style::merge()

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#92]
_Original author: sethcrie...@gmail.com (November 04, 2009 23:40:08)_

<b>What steps will reproduce the problem?</b>
1. Install dompdf
2. Try to generate a pdf

<b>What is the expected output? What do you see instead?</b>
Expect to see a generated PDF, instead, a fatal php error is thrown: Fatal
error: Call to undefined method Style::merge() in
/var/www/vhosts/playmakerprocrm.com/subdomains/sm/httpdocs/lib/dompdf/include/stylesheet.cls.php
on line 196

<b>What version of the product are you using? On what operating system?</b>
0.5.1 on Apache/Linux/RedHat

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=85_

**Comment by SAIF001** [comment]
I am getting the following error with dompdf_0-8-0 when I want to generate PDF
Fatal error: Call to undefined method Dompdf\FrameDecorator\Page::add_line() in C:\wamp\www\dompdf\src\Positioner\Block.php on line 40
 
I have found that the error is in the following code block in Block.php:
    if ($p) {
            $float = $style->float;
            if (!$float || $float === "none") {
                $p->add_line(true);  }
            $y = $p->get_current_line_box()->y;
        }

But when I delete two lines ($p->add_line(true);  and  $y = $p->get_current_line_box()->y; ) from Block.php, I got PDF but lines are interrupted.

Please help me

**Comment by bsweeney** [comment]
@SAIF001 you'll either want to [start a new issue](https://github.com/dompdf/dompdf/issues/new) or a new discussion on the [support forum](http://groups.google.com/group/dompdf). When you do please be sure to provide a sample of the HTML that's causing causing problems.
