### ISSUE TITLE
Font manager assumes font cache is same as font directory

### ISSUE THREAD

**Issue by dleffler** [dompdf/dompdf#921]
The code in /www/fonts.php assumes the font cache file is located in the same folder as the fonts (basically the Installed Fonts list is a list of all files within the /lib/fonts/ folder).  It doesn't account for the cache folder being elsewhere (as set in the custom config.

**Comment by bsweeney** [comment]
I've been working on fixing some of the font issues for the next release. Are you using v0.6.1?

**Comment by dleffler** [comment]
Yes, 0.6.1.  This is mostly an irk :)

**Comment by bsweeney** [comment]
This code was removed but I plan to revive in the utils project.
