### ISSUE TITLE
Support CSS3 "initial" keyword

### ISSUE THREAD

**Issue by md84419** [dompdf/dompdf#924]
I am having problems using line-height: initial.  It doesn't seem to work in dompdf but does in Chrome.

I have a testcase at http://pastebin.com/VPaXZ7ni

Compare the testcase rendered in dompdf as provided, with the same testcase with line 38 changed to uncomment the declaration.

**Comment by md84419** [comment]
I am using the version cloned from git on 24th March 2015 14:05 GMT/WET.

**Comment by bsweeney** [comment]
I don't see "initial" listed anywhere as a possible value for line-height. ([mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height))

**Comment by md84419** [comment]
Its defined in CSS3 and HTML5:

https://developer.mozilla.org/en-US/docs/Web/CSS/initial

**Comment by bsweeney** [comment]
Ah ha ha, yes. Sorry, I was aware of that property. Just ... slipped my mind.

So, obviously, it's not currently supported. But certainly this should be something we ca do.

**Comment by bsweeney** [comment]
Related to issue #612.
