### ISSUE TITLE
Unable to access authenticated content

### ISSUE THREAD

**Issue by notch-1** [dompdf/dompdf#927]
Hi, i can't get remote images to work, the src is "https://localhost/index.php?stimimg=4".
It does not seems to be the "advanced params" case that i see in the remote image example, so what am i doing wrong?
I'm using version 0.6.1.
Thanks

**Comment by bsweeney** [comment]
Presumably if you browse directly you get the expected response. What about if you browse from the server to the url? If the response produced is a valid image it would help to see a sample of the image output from the image script.

**Comment by notch-1** [comment]
Yes the image works fine, even from the server itself (which is not on the localhost anymore).
Here is the code from the image script:

$image = imagecreatefromstring($hex_string);
header("Content-Type: image/png");
imagepng($image, NULL, 9, PNG_NO_FILTER);
exit();

Thank you

**Comment by bsweeney** [comment]
I have been unable to duplicate the issue except by purposely corrupting the output (e.g., sending some minimal content (e.g. a line break) before generating and serving the issue. If you image is online is it publicly accessible? If so I can take a look. Perhaps it's something specific to your image/setup.

**Comment by notch-1** [comment]
now it is: https://188.10.135.140:9000/?stimimg=4
Thank you

**Comment by notch-1** [comment]
Editing the image script to post the link here i found out that if the script skips the login check the pdf is generated correctly. Maybe something got printed in the process...

**Comment by notch-1** [comment]
Ok it's the very line that checks if the user is logged in, for the image the login just fails. Suggestions?
Thanks

**Comment by bsweeney** [comment]
So you have to be logged in to view the image? If that's the case you'll need to pass the user's credentials to dompdf so that it can forward those to the script. I have not done this myself, though there are examples of how to do it on the web.

Relevant discussion on the support group:
https://groups.google.com/forum/#!msg/dompdf/A54NP-AtU3A/7W67l1xU9bcJ

**Comment by bsweeney** [comment]
This discussion on StackOverflow might also be useful: http://stackoverflow.com/a/30363868/264628

**Comment by notch-1** [comment]
I tried but i had no luck... Somehow the cookie or session data were empty inside the context, i don't remember wich one. 
Anyway, I switched to embedded img and avoided the issue.
Thanks anyway

**Comment by bsweeney** [comment]
I'm glad you were able to find a solution. I do hope to provide more guidance on accessing authenticated content in the future. Perhaps we'll use this issue as a reminder.

**Comment by bsweeney** [comment]
Supplying a [context with authorization header](https://github.com/dompdf/dompdf/wiki/Common-Use-Cases#custom-http-stream-context) is now documented in the wiki.
