### ISSUE TITLE
error after migrating to a new server

### ISSUE THREAD

**Issue by steve66nz** [dompdf/dompdf#930]
I've checked all the obvious things like paths, file ownership and permissions I think.

Here's the error: (I'm not sure which source file this comes from)
DOMDocument::loadHTML(): htmlParseEntityRef: no name in Entity, line: 146 DOMDocument::loadHTML(): htmlParseEntityRef: no name in Entity, line: 288 DOMDocument::loadHTML(): htmlParseEntityRef: no name in Entity, line: 288 DOMDocument::loadHTML(): Unexpected end tag : p in Entity, line: 634 Unable to stream pdf: headers already sent

I can send a link privately of the generated html just prior to being passed into dompdf.

This all worked fine on the previous server. It generates a large report of 30 to 40 pages and full of photos. The finished PDF size is usually around 2MB.

The PHP code looks like this:
```
  require_once("dompdf_060/dompdf_config.inc.php");
  $old_limit = ini_set("memory_limit", "1000M");
  $dompdf = new DOMPDF();
  $dompdf->load_html($html);  // loaded from a template, database, external images etc
  $dompdf->set_paper("A4", "portrait");
  $dompdf->render();
  $dompdf->stream(htmlspecialchars_decode($customer_name).'.pdf');
```

thanks,
Steve

**Comment by bsweeney** [comment]
The issue may have been present on the other server, but you might not have noticed. These are notices and as such don't affect the ability of dompdf to continue processing. The PDF is created, just not streamable because of the notice text already sent to the browser (as evidenced by the "Unable to stream pdf: headers already sent" text. Your previous server may have suppressed notices or disabled sending that content to the browser (which is recommended).

So you can either:
 1. Run your html through a validator and correct any issues. dompdf is fairly finicky about the HTML syntax.
 2. If you're using dompdf 0.6.1 you can try enabling the HTML5 parser. This can help correct a number of syntactical issues, though it's not perfect.

**Comment by steve66nz** [comment]
Thanks for your reply.
 
I had already noticed that the html template had no doctype at all so I
tried validating it as is, then as a doctype of html 5, and currently as
4.01 transitional. I got least errors with the latter and mostly minor ones.
I also fixed a couple of css issues. Maybe I'll try installing 0.6.1 and
turn on html 5 as you suggest, and do some more cleanup.
 
With regards the notices - how do I go about suppressing or disabling them?
Is that something the hosting provider can do for me, or is it a setting in
dompdf?
 
regards,
Steve
 


  _____

**Comment by bsweeney** [comment]
Lack of a doctype shouldn't have much of an effect when loading into dompdf. But you should definitely see fewer errors and better rendering updating to 0.6.1 even if you don't use the HTML5 parser.

The display of errors/warnings/notices from PHP is typically controlled by the PHP configuration (php.ini). You can also change this configuration at run-time by calling `ini_set('display_errors', false);`.

**Comment by sinayoq** [comment]
You can disable all messages , execute the instructions prone to failure and reactivate the messages to restore stability to the system.

        // Desactivamos los posibles warning para que no se envien los headers
        error_reporting(0);
        
	$dompdf = new DOMPDF();
	$dompdf->load_html($html);	
	$dompdf->render();
    
        // Save file    
        $output = $dompdf->output();
        $dest = "/your-directory/final_file.pdf";        
        $result = file_put_contents($dest, $output);        
            
        // Reactivamos los warning            
        error_reporting(E_ALL ^ E_NOTICE);                        
                
        if( $result ) {
            // Send file       
            $dompdf->stream($dest);            
        }
        else{            
             echo "<p> An unexpected error has occurred. Please try again later or contact support. </p>"; 			
        }
