### ISSUE TITLE
margin of about 12 mm

### ISSUE THREAD

**Issue by mfeske** [dompdf/dompdf#934]
Hi, I have a problem when using DOMPDF. The HTML page is displayed correctly, but when I get the PDF generating a margin of about 12 mm to. Where is this defined? I'd like to create a letter to DIN 5008 B.
greeting
Micha

**Comment by bsweeney** [comment]
Here is what I responded with in the [support group](https://groups.google.com/d/msg/dompdf/Kd1Iap89Vo0/tNIhup09Ou4J): 

> It would help to see a sample of the HTML. You can set page margins with the `@page { margin: ...; }` styling, but I suspect that's maybe not the issue here?

**Comment by mfeske** [comment]
Hello bsweeney, thanks for your fast response.
theire is the margin 0cm.

@page {
   size: 21cm 29.7cm;
   margin-top: 0cm;
   margin-bottom: 0cm;
   border: 1px solid blue;
}
logo1 {
  position:absolute; top:10mm; right:20mm;
}
logo2 {
  color: red;
}
subject {
  position:absolute; top:98.46mm; left:25mm;
}
content {
  color: blue;
  position:absolute; top:108.46mm; left:25mm;
}
footer {
 color: red;
 position:absolute; top:270mm; left:25mm;
}
marker1 {
 position:absolute; top:105mm;
}
marker2 {
 position:absolute; top:148.5mm; left:-10mm;
}
marker3 {
 position:absolute; top:192mm;
}
#box0 {
 background-color: silver;
 font-size: 6px;
 position: absolute;
 top: 45mm;
 left: 20mm;
 width: 85mm;
 height: 2.0mm;
 border: 1px solid black;
}
#box1 {
 background-color: silver;
 font-size: 12px;
 position: absolute;
 top: 47mm;
 left: 20mm;
 width: 85mm;
 height: 15.7mm;
 border: 1px solid black;
}
#box2 {
 background-color: silver;
 position: absolute;
 top: 62.7mm;
 left: 20mm;
 width: 85mm;
 height: 27.3mm;
 border: 1px solid black;
}
#box3 {
 background-color: silver;
 position: absolute;
 top: 50mm;
 right: 10mm;
 width: 65mm;
 height: 30mm;
 border: 1px solid black;
 -moz-border-radius: 20px;
 -webkit-border-radius: 20px;
 border-radius: 20px;
-webkit-border-radius: 20px;
 border-radius: 20px;
 padding: 5mm;
}
#box3a {
 position: absolute;
 top: 50mm;
 right: 10mm;
 width: 27.5mm;
 height: 30mm;
 padding: 5mm;
}

and in my php file theire is no margin to
<?php
require_once(".../dompdf/dompdf_config.inc.php");
$kdnr =  $_POST['kdnr'];
$absender =  $_POST['absender'];
$empfaenger =  $_POST['empfaenger'];
$telefaxno =  $_POST['telefaxno'];
$betreff =  $_POST['betreff'];
$text =  $_POST['text'];

$html =
"<html>".
"<head>".
"<link rel='stylesheet' type='text/css' href='css/telefax.css'/>".
"</head>".
"<body>".
"<logo1><img src='img/logo_small.png'></logo1>".
"<div id='box0'>$absender</div>".
"<div id='box1'>Zusatz- und Vermerkzone</div>".
"<div id='box2'>$empfaenger</div>".
"<div id='box3'>Datum:<br>Seite:<br>Kundennummer:</div>".
"<div id='box3a'>$date<br>1 von 1<br>$kdnr</div>".
"<subject>Betreff $betreff</subject>".
"<content>Hier der Text $text</content>".
"<footer>Hier die Unternehmens Pflichtangaben</footer>".
"<marker1><hr style='width:20px; color:black; height:1px; margin-left:0; text-align:left;'></marker1>".
"<marker2><hr style='width:30px; color:black; height:1px; margin-left:0; text-align:left;'></marker2>".
"<marker3><hr style='width:20px; color:black; height:1px; margin-left:0; text-align:left;'></marker3>".
"</body></html>";

$dompdf = new DOMPDF();
$dompdf->load_html($html);
$dompdf->render();
#$dompdf->stream("sample.pdf");
$pdf = $dompdf->output();
file_put_contents("file.pdf", $pdf);

?>

**Comment by bsweeney** [comment]
There is a default margin of 1.2cm in the [base stylesheet](https://github.com/dompdf/dompdf/blob/v0.6.1/lib/res/html.css#L19). If you desire more or less margin on the left or right of the document you should add that to your `@page` declaration (which currently only specifies the top/bottom margin).
