### ISSUE TITLE
Using function

### ISSUE THREAD

**Issue by Sebazz** [dompdf/dompdf#936]
Hello i am using dompdf to generate writings. People fill inputs and generate fills, but i got one problem with checkbox. I wanna to use function witch it get and displayw witch checkbox was chose by user. When i put functions it doesn't work...

My function: 

```php
function skladki() {
$skladka = $_POST["input_name"]
    if ($skladka == 1) {
        echo "No";
    } else {
        echo "Yes";
    }
}
```

and displaying with concatenation `skladki();` 

Is there some limits with using functions?

Sorry for my bad English, regards

**Comment by bsweeney** [comment]
You should build your HTML document completely before you pass it to dompdf. A quick way to get started is to write a script to generate an HTML document then add output buffering to capture the content. Place your dompdf code at the bottom to render the captured content to PDF.

**Comment by Sebazz** [comment]
hmm thanks, i will it try tommorow :+1:

**Comment by bsweeney** [comment]
Hope it worked out. Follow up on the support forum if you have any other questions: http://groups.google.com/group/dompdf
