### ISSUE TITLE
Upgrading to dompdf 0.7.0 beta

### ISSUE THREAD

**Issue by vkeranov** [dompdf/dompdf#937]
Acually it is not exactly an issue, but I couldn't find some sort of support forums. So, excuse me if this is the wrong place. The info about the upgrade is not so complete. For example the requirements say we need php-font-lib v0.3.x, but the latest stable is 0.4.0. Does it mean I have to use an older version of php-font-lib? And something else... The requirements page on the wiki is linked in the changelog, but it was not updated since 2013.

I am using dompdf by simply downloading the code, without Composer. And it is also written:
>If you're not yet using Composer you can download an archived release of dompdf which includes all the files you need to use the library.

But the php-font-lib is not included by default. I think it was included in dompdf 0.6.x.

So... Should I manually download php-font-lib and place it inside the /lib folder?
Which version should I download? 0.4.0 or 0.3.x (as said in the requirements)?
Do I need php-font-lib for dompdf at all? Or maybe the new version 0.7.x will not use it?
Since dompdf_config.inc.php is removed should I set **all** dompdf options at run time? Maybe a short example will help about this...

Thanks in advance!

**Comment by bsweeney** [comment]
The support forums are here: http://groups.google.com/group/dompdf

If you download the archived release and not the source code you should have all the files you need. The archived release is named [dompdf-0.7.0.beta.zip](https://github.com/dompdf/dompdf/releases/download/v0.7.0-beta/dompdf-0.7.0.beta.zip) on the release page.

dompdf v0.7.0 uses php-font-lib v0.3.x. I believe v0.4.x may be drop-in compatible. You *may* not need the library at all, but without it you would not be able to use anything but the core PDF fonts. However, using a different version or excluding the library has not been tested. So let's just say php-font-lib v0.3.x is required.

The requirements page is mostly accurate for this release. We will be updating the wiki when we release the final version of dompdf.

You do not need to set **all** options, just the ones you want to change from the default. dompdf should run out of the box without modifying any options. Your question does suggest we should outline the options on the wiki.

If you look at the README.md file you should see the basics of using this version of dompdf. The wiki will hopefully have more information with the final release. Also, we're hoping to put together a "utilities" project which will include some of the removed content (e.g. the www directory) and, hopefully, some scripts and information on migrating from 0.6.x to 0.7.x.

**Comment by vkeranov** [comment]
@bsweeney, big thank you for this answer. Just one last question though...
You said I don't need php-font-lib if I want to use the core fonts, located at /lib/fonts. Does it mean I can not use another font (Arial for example) if iI just drop the font files in this folder?

Thanks again!

**Comment by bsweeney** [comment]
The core PDF fonts are only Helvetica, Times, and Courier. You will need php-font-lib if you want to use the DejaVu fonts included with dompdf (or, at least, if you want to use them with font subsetting). The DejaVu fonts are included to allow characters beyond those supported by Windows ANSI encoding.

Also, you can't just drop your fonts in that folder. The fonts have to be processed so that the font metrics can be extracted and the font location recorded. With the 0.7.0 beta the only way to do that is using a CSS `@font-face` declaration.

**Comment by vkeranov** [comment]
Got it!
Actually with dompdf 0.6.x I am able to use Arial by simply adding the font files in /lib/fonts. I am also adding the font in /lib/fonts/dompdf_font_family_cache.dist.php
And then I am using an external css file where I am declaring Arial as my main font. Will this be the same with 0.7.0?

**Comment by VienNguyen113** [comment]
Hi!
I want to use my font such as: Commons in my pdf, what should i do?
