### ISSUE TITLE
[0.7] functions.inc.php / mbstring

### ISSUE THREAD

**Issue by barryvdh** [dompdf/dompdf#944]
The functions.inc.php is probably a left-over from PHP pre-5.3, but it should probably be removed.
You are defining the mb_string functions with fixed results. 

If dompdf requires them, you can require the extension in php, or use/suggest a proper fallback, like https://github.com/tchwork/utf8

Also there are a lot of functions defined there that don't seem to have much to do with Dompdf. If they are needed, I suggest putting them in a namespaced helper class or something (`Dompdf\Helper::define()` or `Dompdf\Debug::enableMemoryProfile()`)

I would also suggest removing autoload.php and just tell them to run those two lines themselves for manual installation. Composer shouldn't need the Autoloader (see #943)

```
require_once __DIR__ . "/Dompdf/Autoloader.php";
Dompdf\Autoloader::register();
```

And you could also move to PSR-4, which is recommended over PSR-0, by just changing the composer.json: 

```
"autoload": {
    "psr-4" : {
        "Dompdf//" : "src/"
    }
},
```

And put the files one level higher (so `src/Dompdf.php`, `src/Canvas.php` etc)

**Comment by bsweeney** [comment]
Can you clarify what you mean by "defining the mb_string functions with fixed results" (sorry, a bit dense today)? Still I think this is a good suggestion. We have talked about using a third-party library to better support UTF8 but hadn't really worked out any details yet.

Some of the functions originally defined in functions.inc.php were pushed in to a helper class. I'm not sure why that was only a partially job. But it does make sense to move the rest into the helper class.

I was hoping to keep the pre-release stage relatively short by avoiding any additional major changes between now and the final 0.7.x release. Any thoughts on targeting this recommendation to a following release?

**Comment by barryvdh** [comment]
I meant that the result is 'fixed'/static/always the same:

	if (!function_exists('mb_detect_encoding')) {
		function mb_detect_encoding($data, $encoding_list = array('iso-8859-1'), $strict = false)
		{
			return 'iso-8859-1';
		}
	}

So when this is loaded, other libraries/code could think mb_detect_encoding is available, but in this case, it isn't reliable.

But the functions.php file isn't really used, is it? You suggest to load it in the readme for manual installation, but not for the composer on. Or am I overlooking something? So can't it just be removed?

**Comment by bsweeney** [comment]
Ah, yes. I see what you mean. dompdf relies on mbstring and so without it things break horribly, which is why we defined replacements. You are probably right that we should just require mbstring and move on, at least until we can work in something like the lib you pointed out.

Some of the other functions defined in functions.inc.php are still being used as well. I think we can do away with or integrate the remainder of the code in that file. But not for the current release. Which means the composer instructions will need to be updated.

**Comment by barryvdh** [comment]
You shouldn't need to require any other files manually when using Composer. You can autoload some files in composer.json directly.

**Comment by barryvdh** [comment]
And why can't this be done for the upcoming 0.7 release? 

For composer, require ext-mbstring. For manual, create a file 'mbstring-compat.php' or something, and let them require that. (Or suggest the extension on composer, and if needed, let them require that for or let them choose their own workaround).

For the rest of the functions in functions.php, I ran a check with PhpStorm

- `def()`: not used
- `imagecreatefrombmp()`, 1 usage in AbstractRenderer. Could be either moved to a method of AbstractRenderer or a static method.
- `date_default_timezone_get` and `date_default_timezone_set

**Comment by barryvdh** [comment]
Oops, message got cut off to soon, updated my reply.

**Comment by barryvdh** [comment]
Submitted PR in #948

**Comment by bsweeney** [comment]
I'm not saying it can't be fixed it's just that ... well ... I'm anxious to put out a new release. This code has been sitting for a while. But I guess I shouldn't let my desire to release override good coding practice. It's waited this long a few more months shouldn't have any serious consequences. I'll go ahead and implement the changes you've suggested and release a second beta in the near future.

**Comment by barryvdh** [comment]
Yeah but these changes aren't really breaking are they?

**Comment by bsweeney** [comment]
Not breaking, no. It was more about me wanting to stick with a single beta barring any major issues. But we should go ahead and address these concerns, especially since you've already done the work.

**Comment by bsweeney** [comment]
Partially addressed by commit f661eb59a261cc3d7f9abd3fcd8e85882c99f463. The MBString compatibility functions will probably be resurrected in the forthcoming utils project until we have a chance to look at more robust alternatives.

**Comment by barryvdh** [comment]
Okay cool. Probably best to require the extension in composer also.

**Comment by bsweeney** [comment]
I think this is sufficiently addressed for now. I don't know that we really need to build out an MBString shim, especially since options already exist.
