### ISSUE TITLE
Undefined variable: key in dompdf\

### ISSUE THREAD

**Issue by himaushu** [dompdf/dompdf#946]
facing following issues wfth dompdf :

 Undefined variable: key in dompdf\include\stylesheet.cls.php on line 1058
PHP Notice:  Undefined variable: key in dompdf\include\stylesheet.cls.php on line 1059

         // Store the style for later...
          if ( empty($this->_page_styles[$key]) )

I have apache-php setup on windows...

Am i missing any configuration?

Thanx
HD

**Comment by bsweeney** [comment]
see https://groups.google.com/d/topic/dompdf/d0guRp-hXp8/discussion
