### ISSUE TITLE
Version Numbers?

### ISSUE THREAD

**Issue by nomaddesign** [dompdf/dompdf#972]
Sorry if this is a dumb question, but... Where are version numbers documented in installed code?

**Comment by bsweeney** [comment]
Not a dumb question at all. That information does not appear to be documented in the code. We'll add it for the next release.

**Comment by bsweeney** [comment]
Forgot to tag the relevant commit. Closed by 5d80bca8fe8586dc8c29fe3aa1f0b8e96cc94918.
