### ISSUE TITLE
Escaping spaces for paths with spaces

### ISSUE THREAD

**Issue by mvkaran** [dompdf/dompdf#974]
I've noticed that the paths being used throughout the code base are not being escaped for spaces. It might cause some problems while being used with a WAMP or similar Windows stack.
Though only noobs will keep spaces in paths, it's better to quote the paths before being used.

**Comment by bsweeney** [comment]
Can you point to an example of this in the code where we might run into problems?

**Comment by mvkaran** [comment]
I came across this issue in include/font_metrics.cls.php line 343
file_put_contents($local_file, file_get_contents($remote_file));

If the path $local_file contains a space, the path will differ from the intended path which might throw an error.

**Comment by bsweeney** [comment]
I'm not sure there's a problem here. I believe `file_get_contents` and `file_put_contents` both handle spaces just fine. If someone can point out exactly what problem is ocurring we'll look into it more.
