### ISSUE TITLE
Google Font Montserrat can't make it bold

### ISSUE THREAD

**Issue by norxu** [dompdf/dompdf#979]
I'm using google fonts Montserrat (https://www.google.com/fonts/specimen/Montserrat) and it's impossible tot make it appear BOLD. Any idea? 

I've tried solution in issue <a href="https://github.com/dompdf/dompdf/issues/675">#675</a> but is not working

**Comment by bsweeney** [comment]
Seems to work ok with the following:

```html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<style>
@font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 400;
  src: local('Montserrat-Regular'), url(http://fonts.gstatic.com/s/montserrat/v6/zhcz-_WihjSQC0oHJ9TCYC3USBnSvpkopQaUR-2r7iU.ttf) format('truetype');
}
@font-face {
  font-family: 'Montserrat';
  font-style: bold;
  font-weight: 700;
  src: local('Montserrat-Bold'), url(http://fonts.gstatic.com/s/montserrat/v6/IQHow_FEYlDC4Gzy_m8fcvEr6Hm6RMS0v1dtXsGir4g.ttf) format('truetype');
}
</style>
</head>
<body>
  <p style="font-family: Montserrat, serif;">Grumpy wizards make toxic brew for the evil Queen and Jack.</p>
  <p style="font-family: Montserrat, serif; font-weight: bold;">Grumpy wizards make toxic brew for the evil Queen and Jack.</p>
</body>
</html>
```

Double-check your font reference. Did you update the font-style for the bold version? You could also name it differently, but then you would have to style bold text with that font instead of just using a bold indicator (e.g. font-weight, `b`, or `strong`).

**Comment by norxu** [comment]
Thanks quick-reply. I was checking with woff2 font. I'll give it a try with truetype.

**Comment by bsweeney** [comment]
Yeah, sorry. We pretty much only support TrueType right now.

**Comment by messinismarios** [comment]
Does this still work with v.0.8.4? I'm trying to load the same exact font and even though the .html file is great on browser, the rendered .pdf doesn't seem to load the font.

```
@font-face {
      font-family: 'Montserrat';
      font-style: normal;
      font-weight: 400;
      src: local('Montserrat-Regular'), url(http://fonts.gstatic.com/s/montserrat/v6/zhcz-_WihjSQC0oHJ9TCYC3USBnSvpkopQaUR-2r7iU.ttf) format('truetype');
}

@font-face {
      font-family: 'Montserrat';
      font-style: bold;
      font-weight: 700;
      src: local('Montserrat-Bold'), url(http://fonts.gstatic.com/s/montserrat/v6/IQHow_FEYlDC4Gzy_m8fcvEr6Hm6RMS0v1dtXsGir4g.ttf) format('truetype');
}
    
p {
      max-width: 1053px;
      margin: auto;
      padding: 10px 30px 0 30px;
      font-size: 16px;
      line-height: 24px;
      font-family: 'Montserrat', serif;
      color: #555;
  }
```

**Comment by bsweeney** [comment]
@messinismarios works for me but note that in your bold `@font-face` declaration the font style should be "normal" not "bold". That could be throwing off the parsing. You might also try taking out the "local" resource URL and see if that helps.

Also, if you upgraded Dompdf after having used the file it could be that the registration is off. Try removing the dompdf_font_family_cache.php file from the font directory.

**Comment by Pandi-Selvi** [comment]
I have a problem on Montserrat bold text. When I was load my web page,Normal text are running correctly but the bold text in Montserrat running slowly and take few seconds to display why?

**Comment by bsweeney** [comment]
@Pandi-Selvi do you have font subsetting enabled?
