### ISSUE TITLE
PDF won't render - timeout when adding a huge amount of table rows

### ISSUE THREAD

**Issue by eavuursteen** [dompdf/dompdf#980]
Hi DomPDF,

We've frequently used DomPDF successfully, but now we are having trouble with generating a quotation request as PDF when checking a lot of checkboxes with extra options for the car lease website.
The HTML can be found here: http://pastebin.com/SzyxTXZS.
In the code I've used a "<!-- @DOMPDF: "-comment for the rows which causes the problem.
Without the indicated rows, everything works properly.
I've run the code through the W3 Validator and the HTML is valid as HTML4/Transitional, except for a warning for the shorthand "meta charset"-tag.

**Comment by bsweeney** [comment]
Looks like you're using a nested tables. Normally this is fine, but if any one table cell is larger than the size of the page you'll run into this issue (see #98). Your layout is a bit difficult to work with, but you might be able to adjust things such that this issue doesn't occur. Try using `div` elements where possible and maybe surround the options table in a div to position it correctly.

**Comment by chrislandeza** [comment]
Any updates on this issue?

**Comment by joecutter** [comment]
any progress

**Comment by bsweeney** [comment]
For handling table cells larger than the page size? Nothing yet.

The pastebin for this issue is no longer available so I'm going to close it unless relevant info it re-posted.
