### ISSUE TITLE
Generated PDF is showing garbage characters in Firefox

### ISSUE THREAD

**Issue by sams46** [dompdf/dompdf#982]
PDF was displaying right in Firefox but after some Firefox latest update it is showing garbage characters in place of text in the lot of places of the generated PDF. How can i fix?

**Comment by bsweeney** [comment]
Which version of dompdf? Which version of Firefox? Do you have a sample of the HTML & rendered PDF?

**Comment by sams46** [comment]
dompdf_0-6-0_beta3 is dompdf and 39.0 is the Firefox version. I have attached shots of HTML sample and PDF section:

![sample_code](https://cloud.githubusercontent.com/assets/1197209/8589395/cbf805d0-2626-11e5-85f7-89f340350859.png)
![garbage_characters_shot](https://cloud.githubusercontent.com/assets/1197209/8589876/139adb2e-262c-11e5-92a2-9b89d9553e5f.png)

**Comment by bsweeney** [comment]
What are the font stylings on that text? Could be an issue with font subsetting, if turned on try turning it off. You also might try upgrading to the stable 0.6.x release ([0.6.1](https://github.com/dompdf/dompdf/releases/tag/v0.6.1)).

**Comment by sams46** [comment]
It was working fine before firefox update. My font-family is Myriad Pro and I have generated through load_font.php but it still showing same garbage characters.

**Comment by bsweeney** [comment]
Are you calling both stream() and output() on the rendered document? This has proven to be a problem when using the CPDF backend.
