### ISSUE TITLE
"File not found" error in Wordpress/CodeIgniter integration

### ISSUE THREAD

**Issue by quebec87** [dompdf/dompdf#984]
My website is using Wordpress to create most pages and layouts. Besides that there is a small booking system which wrote by CodeIgniter. I'm trying to integrate the CI into Wordpress, so that I can use the wordpress menu and header, footer. However, the dompdf won't work anymore after the integration. I'm not sure where is wrong and hope someone can help me with that.

TO reproduce the problem:
1.Implement dompdf into CodeIgniter. (https://github.com/bcit-ci/CodeIgniter/wiki/PDF-generation-using-dompdf)

2 Place CodeIgniter within Wordpress. (followed https://github.com/AdeptMarketing/Wordpress_CI)
So far everything is good and dompdf can create pdf file.

3.In the CodeIgniter_folder/index.php   -- add "require('../wp-blog-header.php');" at bottom.
Dompdf won't work anymore and shows "File not found" error. 
p.s. the define("DOMPDF_ENABLE_PHP", true); is uncomment in the  dompdf_config.custom.inc.php

**Comment by bsweeney** [comment]
Which file is not found? Is that the status/page returned by the web server or an error returned by PHP?

**Comment by quebec87** [comment]
thanks for reply.
here is the screen shot 
![filenotfound](https://cloud.githubusercontent.com/assets/10112394/8625531/f3402522-2771-11e5-9ef1-1b89fd9e695f.jpg)

and this is the site_home controller
class Site_home extends CI_Controller {
	public function index()
	{
		$this->load->view('welcome_message');
	}
	public function testD(){
		$this->load->helper(array('dompdf','file'));
		$html = $this->load->view('welcome_message');
		pdf_create($html, 'mypdf');
	}
}

**Comment by bsweeney** [comment]
I know this is a bit old, but are you still having problems? Any useful information in the log files?

**Comment by pprotschka** [comment]
...same issue. any solution?

**Comment by bsweeney** [comment]
I've got nothing. Seems more like an integration issue, in which case we may not be able to provide much guidance.
