### ISSUE TITLE
$options should not be private

### ISSUE THREAD

**Issue by vkeranov** [dompdf/dompdf#987]
In src/Dompdf.php `$options` is private. In the same time function `get_option` is deprecated. So if I make a little test and delete the deprecated `get_option` the result is not good.

The error is in CanvasFactory.php where get_option is used here:

```
$DOMPDF_PDF_BACKEND = $dompdf->get_option('pdf_backend');
```

And if I change this to:

```
$DOMPDF_PDF_BACKEND = $dompdf->options->get('pdf_backend');
```

The result is:
Cannot access private property Dompdf\Dompdf::$options in...

Of course if I change the $options to public, the problem is gone. Is there a reason why this is private?

**Comment by bsweeney** [comment]
I think keeping options property private is OK, but the rest of the code does need to be updated as `get_option()` is still heavily used. Based on the current state of the code the appropriate method would be to call `getOptions()` then work off of the returned object.

**Comment by vkeranov** [comment]
Well I see your point and I understand your opinion for keeping it private. But the big picture is different. We do have a lots of deprecated stuff which just makes the code size bigger and bigger. If something is deprecated then it means that all other places where it is used should be updated also. Just see functions like load_html_file, remove_text_nodes, enable_caching, parse_default_view, output_html... All those are marked as deprecated, but they are used everywhere.

If a developer marks some piece of the code as deprecated, he should also update the code and replace the calls where those functions are used. You're working on a new version which is full of these. It doesn't make sense...

**Comment by bsweeney** [comment]
I don't disagree.

**Comment by bsweeney** [comment]
Internally Dompdf is no longer using the deprecated function.
