### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by tushar4monto** [dompdf/dompdf#989]
Hello 
i have just down load and use this dompdf-master in my local wamp server (PHP 5.5.12) and run dompdf-master folder and i have get this ERRORs

Warning: require_once(G:/wamp/www/dompdf_master/lib/php-font-lib/classes/Font.php): failed to open stream: No such file or directory in G:\wamp\www\dompdf_master\dompdf_config.inc.php on line 332

Fatal error: require_once(): Failed opening required 'G:/wamp/www/dompdf_master/lib/php-font-lib/classes/Font.php' (include_path='.;C:\php\pear') in G:\wamp\www\dompdf_master\dompdf_config.inc.php on line 332

please help me how to use your dompdf-master folder

**Comment by bsweeney** [comment]
You are missing [php-font-lib](https://github.com/PhenX/php-font-lib) from your installation. When downloading the source from github external libraries are not included. You might have better luck downloading the [version bundle](https://github.com/dompdf/dompdf/releases/download/v0.6.1/dompdf-0.6.1.zip) or using [Composer](https://getcomposer.org/).
