### ISSUE TITLE
More lines stop working 

### ISSUE THREAD

**Issue by dlxko** [dompdf/dompdf#990]
When I enter 1153 to loop it works but when I enter more it stops working at all ...
Need to create very big PDF no possibility to do it :( 

```php
$CreatedPDF = "<html><head></head><body>";
for ($i = 1; $i <= 1153; $i++)
  $CreatedPDF .= '<br>';
  $CreatedPDF .= "</body></html>";
        
  // Render PDF file
  $dompdf = new DOMPDF();
  $dompdf->set_paper(array(0,0,595.28,841.89));
  $dompdf->load_html( utf8_decode( $CreatedPDF ) );
  $dompdf->render();
```

**Comment by bsweeney** [comment]
If I were to guess I'd say you ran out of memory or exceeded the max execution time. But it would be easier to know if you could retrieve any errors produced.

You also might try adding a container around the document content. There have been issues related to overly large inline content contained by the body element. For example, try:

```php
$CreatedPDF = "<html><head></head><body><div>";
for ($i = 1; $i <= 1153; $i++)
  $CreatedPDF .= '<br>';
  $CreatedPDF .= "</div></body></html>";
```

**Comment by dlxko** [comment]
This doesn't help :( I trace the problem and it looks like 

frame_factory.cls.php:201
$deco = new $decorator($frame, $dompdf);

Decorator can't be created

**Comment by baconface** [comment]
I don't have issues with this. If I had to guess your PHP allowed memory exceeded. You need to increase this in your php.ini.

**Comment by bsweeney** [comment]
FYI, just to confirm possible memory overload, I was able to render the same simple HTML with > 4500 lines. Took a while, though. The stats on the render were 9674 frames, 116224.00 KB, 62085.88 ms.

**Comment by dlxko** [comment]
The problem was with memory overload can be closed for me, thanks

**Comment by bsweeney** [comment]
Thanks for the follow up. Glad the issue was determined, hope you were able to resolve without too much trouble.
