### ISSUE TITLE
Avoid using debug_string_backtrace() unless debugging mode is enabled?

### ISSUE THREAD

**Issue by mlutfy** [dompdf/dompdf#995]
In the latest 0.6.x versions, dompdf uses debug_string_backtrace() in dompdf/lib/html5lib/TreeBuilder.php, function getElementCategory() [ref](https://github.com/dompdf/dompdf/blob/develop/lib/html5lib/TreeBuilder.php#L3368)

```
    private function getElementCategory($node) {
        if (!is_object($node)) debug_print_backtrace();
```

Presumably this was put there because it was very unlikely to happen, but it's still a risk of exposing system information.

I'm not very familiar with the dompdf code base. What would be the best way to throw a parse error?

For context: this issue was raised by a security scan of our (free software project) code base. Scanners can be very annoying at times, but to us it seems like a valid concern. Will be happy to send a PR.

Thanks

**Comment by bsweeney** [comment]
The html5lib is a third-party library not maintained by us. It has a number of issues and we're looking to migrate to something else, probably Masterminds/html5-php (which is a fork of the original project). With that in mind it's probably not worthwhile to address this issue.

Also, the library is not strictly needed. If you're not using it (e.g. if your HTML document structure is solid) you can disable usage in the options.

**Comment by mlutfy** [comment]
Thanks for the quick response. If I understand the correctly, dompdf does not enable html5lib by default ("isHtml5ParserEnabled" option), so seems OK to ignore this issue for now.
